### ISSUE TITLE
Add some info about sphinx and rest (including links) to developer guide

### ISSUE THREAD

**Issue by jpflori** [sagemath/sage#10077]
<div id="comment:0"></div>

There is a problem within http://www.sagemath.org/doc/developer/conventions.html. It says to use ".. NOTE::" and there is "NOTES:" in the example.

There is also nothing about "TESTS:" section which is often used whithin the source code. 

The recurrent use of ".. blah ::", "::" and "sage: " could also be documented or at least directly point to the corresponding pages of Sphynx doc (even if looking at the examples is of course the best way to go and looking through Sphynx doc also explains many things).

CC:  @sagetrac-mvngu @jhpalmieri @kcrisman @nathanncohen

Component: **documentation**

Keywords: **coding convention**

Author: **Minh Van Nguyen**

_Issue created by migration from https://trac.sagemath.org/ticket/10077_

**Comment by mkoeppe** [comment]
Closing as outdated.
