### ISSUE TITLE
Printing html documentation cuts off a couple of inches on the right when the sidebar is not collapsed before printing

### ISSUE THREAD

**Issue by jasongrout** [sagemath/sage#10178]
<div id="comment:0"></div>

If I try to print the html documentation,for example, here:

http://sagemath.org/doc/tutorial/tour_rings.html

The (blank) sidebar takes up a couple of inches on the left, and the rightmost couple of inches is cut off.

This was reported by Dan Willis.

CC:  @jhpalmieri @qed777

Component: **documentation**

_Issue created by migration from https://trac.sagemath.org/ticket/10178_

**Comment by mkoeppe** [comment]
Closing as outdated
