### ISSUE TITLE
Add BMSS algorithm for isogenies of elliptic curves

### ISSUE THREAD

**Issue by defeo** [sagemath/sage#11095]
<div id="comment:0"></div>

Add the algorithm by Bostan, Morain, Salvy and Schost for normalized isogenies in characteristic 0 or large enough.

References:

[BMSS08] Alin Bostan, François Morain, Bruno Salvy, and Éric Schost, Fast algorithms for computing isogenies between elliptic curves, Mathematics of Computation 77 (2008), 1755–1778.

Apply: [attachment: trac_11095_isogenies_char_0_v3.patch​](https://github.com/sagemath/sage/files/ticket11095/0e2630fbe9449c551f50bca100e732dd.gz)

CC:  @categorie @jpflori @pjbruin

Component: **elliptic curves**

Keywords: **isogenies ecc2011**

Work Issues: **merge conflicts**

Author: **Luca De Feo**

Branch/Commit: **[public/ticket/11095](https://github.com/sagemath/sagetrac-mirror/tree/public/ticket/11095) @ [`59417df`](https://github.com/sagemath/sagetrac-mirror/commit/59417df5c944443f91d51d996d1d825f144ab734)**

Reviewer: **John Cremona, Marco Streng**

_Issue created by migration from https://trac.sagemath.org/ticket/11095_

**Comment by defeo** [comment]
Description changed:
``````diff
--- 
+++ 
@@ -1,4 +1,4 @@
-Add the algorithm by Bostain, Morain, Salvy and Schost for normalized cyclic isogenies in characteristic 0 or large enough.
+Add the algorithm by Bostain, Morain, Salvy and Schost for normalized isogenies in characteristic 0 or large enough.
 
 References:
 
``````

**Comment by zimmermann6** [comment]
Description changed:
``````diff
--- 
+++ 
@@ -1,4 +1,4 @@
-Add the algorithm by Bostain, Morain, Salvy and Schost for normalized isogenies in characteristic 0 or large enough.
+Add the algorithm by Bostan, Morain, Salvy and Schost for normalized isogenies in characteristic 0 or large enough.
 
 References:
 
``````

**Comment by fchapoton** [comment]
Description changed:
``````diff
--- 
+++ 
@@ -4,3 +4,4 @@
 
 [BMSS08] Alin Bostan, François Morain, Bruno Salvy, and Éric Schost, Fast algorithms for computing isogenies between elliptic curves, Mathematics of Computation 77 (2008), 1755–1778.
 
+Apply: [attachment: trac_11095_isogenies_char_0_v3.patch​](https://github.com/sagemath/sage/files/ticket11095/0e2630fbe9449c551f50bca100e732dd.gz)
``````

**Comment by yyyyx4** [comment]
An implementation of the BMSS algorithm was added in #36285.
