### ISSUE TITLE
document the patchbot

### ISSUE THREAD

**Issue by dandrake** [sagemath/sage#12505]
<div id="comment:0"></div>

At #12486, we add Robert Bradshaw's patchbot to Sage so that anyone can run a patchbot. We should document it, though!

***EDIT:**

The code is now commented, at least a little.

And some doc on how to use it is available here:

https://wiki.sagemath.org/buildbot

CC:  @robertwb @kini

Component: **documentation**

Keywords: **patchbot**

Reviewer: **Kwankyu Lee**

_Issue created by migration from https://trac.sagemath.org/ticket/12505_

**Comment by mkoeppe** [comment]
<div id="comment:9" align="right">comment:9</div>

outdated; the patchbot will be retired

**Comment by kwankyu** [comment]
Reviewer: **Kwankyu Lee**

**Comment by kwankyu** [comment]
<div id="comment:10" align="right">comment:10</div>

Yes.
