### ISSUE TITLE
find and fix memory leak in docbuilding

### ISSUE THREAD

**Issue by jhpalmieri** [sagemath/sage#13127]
<div id="comment:0"></div>

It seems that there is a memory leak when building the documentation. This might be caused by the intersphinx extension (enabled at #9128). We should track this down and fix it.

See #13057 for some relevant discussion. The patch there turned off the intersphinx extension during introspection, in part because of this memory leak. If we can fix the problem, we can reenable this extension, thus enabling commands like `sage.algebras.group_algebra_new.GroupAlgebra.one_basis?` to display links in the notebook.

CC:  @hivert

Component: **documentation**

Keywords: **sphinx**

_Issue created by migration from https://trac.sagemath.org/ticket/13127_

**Comment by mkoeppe** [comment]
Closing as outdated.
