### ISSUE TITLE
intersphinx and introspection: fix the links

### ISSUE THREAD

**Issue by jhpalmieri** [sagemath/sage#13128]
<div id="comment:0"></div>

Ticket #9128 turned on the intersphinx extension for Sphinx, thus proving nice cross-referencing in the reference manual. In the notebook, though, this doesn't construct the correct links: executing

```
sage.algebras.group_algebra_new.GroupAlgebra.one_basis?
```
produces a docstring with a url

```
localhost:8000/FULL_PATH_TO_REFERENCE_MANUAL/sage/categories/algebras_with_basis.html#sage.categories.algebras_with_basis.AlgebrasWithBasis.ParentMethods.one_basis
```

Note that #13057 disabled intersphinx when using introspection because of a slow-down and apparent memory leak. Those issues need to be addressed — see #13127 — before this ticket can be merged.
which should probably instead be

```
localhost:8000/doc/static/reference/sage/categories/algebras_with_basis.html#sage.categories.algebras_with_basis.AlgebrasWithBasis.ParentMethods.one_basis
```

Depends on #13127

CC:  @hivert

Component: **documentation**

Keywords: **introspection intersphinx**

_Issue created by migration from https://trac.sagemath.org/ticket/13128_

**Comment by mkoeppe** [comment]
outdated (sagenb)
