### ISSUE TITLE
Should use a better sphinx patch to make documentation examples interactive

### ISSUE THREAD

**Issue by 37a92f17-2ef8-4e0e-9a36-10478a357b6c** [sagemath/sage#13230]
<div id="comment:0"></div>

I believe the sphinx patch:

`-            if source.startswith('>>>'):`

`+            if source.startswith('>>>') or source.startswith('sage: '):`

is too much intrusive to be applied on a system wide sphinx (actually, I applied it to Mandriva python-sphinx package long ago...).

But it was required to make examples interactive in my WIP fedora sagemath package using system wide packages.

Component: **documentation**

_Issue created by migration from https://trac.sagemath.org/ticket/13230_

**Comment by mkoeppe** [comment]
outdated
