### ISSUE TITLE
documentation for matrix( ) mentions ncols and nrows

### ISSUE THREAD

**Issue by cf9aafe6-de78-49e1-8b85-98b19cd76ddc** [sagemath/sage#14132]
<div id="comment:0"></div>

matrix( ncols=...,nrows=... ) does not create a matrix (even a sparse one) with the according number of columns and rows, contrary to what's described here

http://sagemath.org/doc/reference/sage/matrix/constructor.html

---

EDIT. 

This ticket brings to the fore, the some anomalies in the matrix constructor class. This is basically about how we handle edge cases.

Work Issues. 

(1) Implementation Issues. 

    (*) the keywords `nrows` and `ncols` are not working as desired. 

(2) Documentation Issues. 

   (*) **'Annotated List of Examples**'. Right now, there are a bunch of examples out there. They are not all<sup>TM</sup> - not even most of - the possible ways to use the `matrix` command. 

   (*) "The ring defaults to ZZ if it is not specified or cannot be determined from the entries." Clearly not happening: 

```
sage: matrix(nrows=2, ncols=3)
[]
sage: matrix(2,3)
[0 0 0]
[0 0 0]
sage: matrix(ZZ, nrows=2, ncols=3)
[0 0 0]
[0 0 0]
```

  (*) "If the numbers of rows and columns are not specified and cannot be determined, then an empty 0x0 matrix is returned." There are two issues: 

```
sage: matrix(ZZ, ncols=3)         
[]
```

As the example illustrates, the "and" should be really an "or". "an empty matrix" should be the empty matrix. 

  (*) "The ring, number of rows, and number of columns of the matrix can be specified by setting the ring, nrows, or ncols parameters or by passing them as the first arguments to the function in the order ring, nrows, ncols." All examples are of the kind described after "or". We should add examples of the first kind. (Doing that would have uncovered the implementation issues.)

CC:  @rbeezer @jasongrout

Component: **documentation**

Keywords: **matrix ncols nrows**

_Issue created by migration from https://trac.sagemath.org/ticket/14132_

**Comment by mkoeppe** [comment]
outdated, worksforme
