### ISSUE TITLE
function( ) normative doc wrong

### ISSUE THREAD

**Issue by cf9aafe6-de78-49e1-8b85-98b19cd76ddc** [sagemath/sage#14468]
<div id="comment:0"></div>

It does not mention a second positional argument whatsoever, although the examples make it clear that, say, the 2nd argument is the variable the function has as a parameter.

Component: **documentation**

Keywords: **function**

_Issue created by migration from https://trac.sagemath.org/ticket/14468_

**Comment by DaveWitteMorris** [comment]
This issue is invalid.

The description refers to the variable `x` in the expression `function(f)(x)` as the "second positional argument" of `function`, but that's not what it is. Rather, `x` is the argument of the function that was created by the call `function(f)`.
