### ISSUE TITLE
Cython sometimes embeds wrong file names in docstrings

### ISSUE THREAD

**Issue by vbraun** [sagemath/sage#14634]
<div id="comment:0"></div>

Cython's `Nodes.relative_position` makes file names relative by stripping off the first `len(os.path.abspath(os.getcwd()))` characters. This is totally wrong if the file is from the include search path and not relative to `cwd`

Upstream bug report: http://trac.cython.org/cython_trac/ticket/817

The first patch makes the last two includes in Sage absolute, which triggers the bug.

Apply:
* [attachment: trac_14634_fix_includes.patch](https://github.com/sagemath/sage-prod/files/10657839/trac_14634_fix_includes.patch.gz)

Depends on #12728

Upstream: **Reported upstream. No feedback yet.**

Component: **cython**

_Issue created by migration from https://trac.sagemath.org/ticket/14634_

**Comment by mkoeppe** [comment]
Closing as outdated
