### ISSUE TITLE
patchbot test (with accent é to check) and unicode 羊 in the title

### ISSUE THREAD

**Issue by robertwb** [sagemath/sage#14974]
<div id="comment:0"></div>

**THIS IS A TEST TICKET FOR THE PATCHBOT ; DO NOT MERGE!**

Just a test with
newlines, commas, and "quotes."

CC:  a b c

Component: **PLEASE CHANGE**

Keywords: **patchbot**

Author: **George Smiley**

Branch/Commit: **[public/ticket/14974](https://github.com/sagemath/sagetrac-mirror/tree/public/ticket/14974) @ [`e786fc5`](https://github.com/sagemath/sagetrac-mirror/commit/e786fc5123a5013e062bc505d9c9a65cf7de850d)**

_Issue created by migration from https://trac.sagemath.org/ticket/14974_

**Comment by mkoeppe** [comment]
No longer needed.
