### ISSUE TITLE
Make elliptic_j function symbolic

### ISSUE THREAD

**Issue by cb647bba-30a0-444e-843a-180ae032f251** [sagemath/sage#15354]
<div id="comment:0"></div>

Sage's elliptic_j function does not behave similarly to the other standard or special functions: it tries to numerically evaluate instead of building a symbolic expression:

```
sage: elliptic_j(I)
1728.00000000000
sage: elliptic_j(x)
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
...
TypeError: Cannot evaluate symbolic expression to a numeric value.
```

This is very weird: it means, for example, that plot(real(elliptic_j(x+I)), (x,0,1)) will fail (instead, one must use plot(lambda t: real(elliptic_j(t+I)), (0,1)))

* http://mpmath.googlecode.com/svn/tags/0.15/doc/build/functions/elliptic.html#kleinj
* https://en.wikipedia.org/wiki/J-invariant

Component: **symbolics**

Keywords: **special function, elliptic**

_Issue created by migration from https://trac.sagemath.org/ticket/15354_

**Comment by grhkm21** [comment]
I looked at this just now, it doesn't seem too trivial, as the current implementation actually calls `pari`:

```sage
    CC = z.parent()
    if not isinstance(CC, sage.rings.abc.ComplexField):
        from sage.rings.complex_mpfr import ComplexField
        CC = ComplexField(prec)
        try:
            z = CC(z)
        except ValueError:
            raise ValueError("elliptic_j only defined for complex arguments.")
    from sage.libs.pari.all import pari
    return CC(pari(z).ellj())
```
I'm not sure how you can represent the function symbolically either, since it is transcendental in general (?) I will close the issue for now, if anyone has a better idea feel free to reopen.

**Comment by user202729** [comment]
@grhkm21 Old issue but it can certainly be represented symbolically. I guess the issue can be kept as a tracking issue.

For example with `gamma`:

```python
sage: gamma(5)
24
sage: gamma(5, hold=True)
gamma(5)
```

(Though I don't understand enough about how Sage represents symbolic expression in general, I think the symbolic expression tree must be recognize-able by Maxima for things like e.g. `simplify()` to work? Through a cursory search Maxima doesn't seem to have modular form.)

**Comment by user202729** [comment]
@grhkm21 Old issue but it can certainly be represented symbolically. I guess the issue can be kept as a tracking issue.

For example with `gamma`:

```python
sage: gamma(5)
24
sage: gamma(5, hold=True)
gamma(5)
```

(Though I don't understand enough about how Sage represents symbolic expression in general, I think the symbolic expression tree must be recognize-able by Maxima for things like e.g. `simplify()` to work? Through a cursory search Maxima doesn't seem to have modular form.)
