### ISSUE TITLE
Fix buildbot random failures

### ISSUE THREAD

**Issue by vbraun** [sagemath/sage#15459]
<div id="comment:0"></div>

Here is the list of issues that I ran into on the buildbot:

Failures existing already a long time:
* Trac #9827: Intermittent doctest failure in sage/interfaces/psage.py
* Trac #10476: Problems interrupting Singular
* Trac #15477: random doctest failures in Curve_generic.geometric_genus
* Trac #15443: Random time outs in ecm.py
* Trac #15535: LinBox: you are running out of primes. 1000 coprime primes found
* Trac #16638: Random failure in integer_vector

Failures new since Sage 6.0:
* Trac #15441: Clean up ecl SIGCHLD configuration
* Trac #15457: sage-cleaner does not quit
* Trac #15534: Corrupt pickle in cluster_seed.py
* Trac #15585: Random failure in SimplicialComplex.is_cohen_macaulay
* Trac #15631: Random failures in sandpiles.py
* Trac #15811: Random doctest failure in maxima_abstract.py
* Trac #15899: Random failures in decorate `@`fork
* Trac #16658: Random failure in hyperelliptic_finite_field.py
* Trac #16667: Random failure in polynomial_element.pyx
* Trac #16681: Random doctest failures in sage/rings/algebraic_closure_finite_field.py
* Trac #16713 Random failure in lseries_ell.py
* Trac #16744: Random failure in elliptic_curves/constructor.py
* Trac #16745 Random OperationalError: disk I/O error

Done:
* Trac #15440: Random spaces injected into Maxima pexpect output

Depends on #13015

Component: **misc**

Keywords: **random_fail**

_Issue created by migration from https://trac.sagemath.org/ticket/15459_

**Comment by tobiasdiez** [comment]
With the migration to github, the buildbot is no longer used and thus this ticket seems obsolete (and it's quite old anyway).
