### ISSUE TITLE
Add somewhatfptufvs package

### ISSUE THREAD

**Issue by b7f74c3c-841c-439d-9357-b4403a2c3f3d** [sagemath/sage#15735]
<div id="comment:0"></div>

This is pushing of a new (c/c++) spkg somewhatfptufvs.

I merge it with generic_graphs, as there is a similar algorithm for directed graphs, even if it is not implemented in this package yet.

The somewhatfptufvs package is in attachment and in the mail. Expect to see a new version soon that has an implementation for weighted undirected graphs. Some documentation would be nice too.

I claim that this solver the graph problem Feedback Vertex Set, and does so faster then the LP algorithm available. See appendix in Readme for a benchmark written for sage notebook. (performance on weighted undirected graphs remains to be seen)
I do not imagine this package replacing anything. All LP "genre" implementations like the MIP, should be quite generic. They solve many problems, and does so with small formulas.
The solver I present require constant amount of memory, no dependencies, have reasonable build time, and there is room for reducing it's spkg size.
Usability of this package extend the usability beyond what MIP can provide with regards to representation of weights, if not the same usability. I have not implemented it with support for directed graphs. There are also some limitations I find to be fitting, as in that these assumptions are common, require not much effort, would be nothing but a new code-file if added to package, and these assumptions are documented/todos.
I have no reason to believe that this software is not stable.

Dependencies: **None**

Upstream: **None of the above - read trac for reasoning.**

CC:  @nathanncohen

Component: **PLEASE CHANGE**

Keywords: **hard, feedback vertex set**

Author: **spurtuna**

Branch/Commit: **[u/spurtuna/15735please](https://github.com/sagemath/sagetrac-mirror/tree/u/spurtuna/15735please) @ [`31b7a20`](https://github.com/sagemath/sagetrac-mirror/commit/31b7a2036a17ce63d9b85e9b6ef4e3b2a5de4b3c)**

_Issue created by migration from https://trac.sagemath.org/ticket/15735_

**Comment by dcoudert** [comment]
This issue is abandoned. I propose to close it.
