### ISSUE TITLE
Merge and improve sage's benchmarking frameworks

### ISSUE THREAD

**Issue by mezzarobba** [sagemath/sage#16510]
<div id="comment:0"></div>

Some experimental work I started a while ago and have no time to continue right now.

Overall goal: make it easy both to benchmark sage against other tools and to track the performance of various subsystems across versions.

More or less done:
* Merge the various existing bits of benchmarking infrastructure.
* Port existing benchmarks to the unified framework.
Todo:
* Support creating benchmark suites.
* Support saving the results of a run (to compare several versions of sage or test the performance impact of a patch).
* Clean up and improve the existing benchmarks.
* ...

Component: **performance**

Branch/Commit: **[public/benchmarking-framework](https://github.com/sagemath/sagetrac-mirror/tree/public/benchmarking-framework) @ [`0a7b47f`](https://github.com/sagemath/sagetrac-mirror/commit/0a7b47fdc1657a8cee98d6407696e66548225ed3)**

_Issue created by migration from https://trac.sagemath.org/ticket/16510_

**Comment by saraedum** [comment]
see also https://github.com/sagemath/sage/issues/25262 for using an external tool (asv) instead.

**Comment by mezzarobba** [comment]
Yes, that's certainly a better option, and the attached branch has bitrotten. I think we can close this ticket. (Opinions?)

**Comment by vincentmacri** [comment]
> Yes, that's certainly a better option, and the attached branch has bitrotten. I think we can close this ticket. (Opinions?)

Since you created the ticket I think if you're good with closing it then it can be closed. Closing as stale.
