### ISSUE TITLE
Lazy import more algebras

### ISSUE THREAD

**Issue by tscrim** [sagemath/sage#17271]
<div id="comment:0"></div>

There are algebras which are not standard or high usage that could be lazily imported in order to help startup time. This will likely need some discussion. Followup to #16219.

Depends on #16219

CC:  @nthiery

Component: **misc**

Keywords: **lazy import, startup time**

_Issue created by migration from https://trac.sagemath.org/ticket/17271_

**Comment by mkoeppe** [comment]
As of 10.0.beta9, many algebras are already `lazy_import`ed. Can we close? @tscrim

**Comment by tscrim** [comment]
Yes, I think so.
