### ISSUE TITLE
sage developer's guide should mention pyflakes

### ISSUE THREAD

**Issue by saliola** [sagemath/sage#17992]
<div id="comment:0"></div>

It would be nice if the Sage Developer's Guide include a section on pyflakes, since it is a very useful developer tool.

(Perhaps it might be a good idea to include a section on useful developer tools.)

Depends on #30361

CC:  @nthiery @tobiasdiez @mkoeppe

Component: **documentation**

Keywords: **days64, developer's guide**

_Issue created by migration from https://trac.sagemath.org/ticket/17992_

**Comment by mkoeppe** [comment]
`src/doc/en/developer/tools.rst
