### ISSUE TITLE
Recursive load makes symbol?? display the wrong File: information

### ISSUE THREAD

**Issue by 93749b3a-c0a4-47a7-b178-004ba08b0b97** [sagemath/sage#181]
<div id="comment:0"></div>

We use the example in examples/programming/recursive_load.  

(*Note: this file no longer exists, but one could recreate this situation*)

file1.sage defines a symbol foo.
file2.sage defines a symbol bar.

Each file loads the other recursively.

If we load file2.sage first, then the source code for foo is displayed correctly by foo?? but the File: information is wrong.  The File: should read file1.sage.

```
sage: load file2.sage
loaded file1.sage
I'm now defining s
loaded file1.sage

sage: foo??
Type:           function
Base Class:     <type 'function'>
String Form:    <function foo at 0x8fd6db0>
Namespace:      Interactive
File:           /Users/nalexand/Devel/sage-alpha8/examples/programming/recursive_load/file2.py
Definition:     foo(n)
Source:
def foo(n):
    print "foo"
    return n**Integer(2)
```

Component: **user interface**

Keywords: **recursive load source file**

_Issue created by migration from https://trac.sagemath.org/ticket/181_

**Comment by kcrisman** [comment]
Description changed:
``````diff
--- 
+++ 
@@ -1,4 +1,6 @@
-We use the example in examples/programming/recursive_load.
+We use the example in examples/programming/recursive_load.  
+
+(*Note: this file no longer exists, but one could recreate this situation*)
 
 file1.sage defines a symbol foo.
 file2.sage defines a symbol bar.
``````

**Comment by jhpalmieri** [comment]
> So I'm going to change this to an enhancement request rather than a defect,
> as it's not even clear what the right design should be, and currently no invalid
> output is actually being produced.

From this point of view, I don't see an actual issue here. I propose closing this.
