### ISSUE TITLE
Automatic error message when packages are not installed

### ISSUE THREAD

**Issue by jdemeyer** [sagemath/sage#19622]
<div id="comment:0"></div>

We add some magic to the Sage setup scripts such that `OptionalExtension`s whose package is not installed automatically raise an user-friendly exception:

```
sage: G = graphs.PetersenGraph()
sage: G.automorphism_group(algorithm='bliss') 
---------------------------------------------------------------------------
PackageNotFoundError                      Traceback (most recent call last)
<ipython-input-2-8e034558a836> in <module>()
----> 1 G.automorphism_group(algorithm='bliss')

/usr/local/src/sage-config/local/lib/python2.7/site-packages/sage/graphs/generic_graph.pyc in automorphism_group(self, partition, verbosity, edge_labels, order, return_group, orbits, algorithm)
  20062             if edge_labels:
  20063                 raise ValueError("bliss cannot be used when edge_labels is True")
> 20064             from sage.graphs.bliss import automorphism_group
  20065 
  20066             A = automorphism_group(self, partition)

PackageNotFoundError: the package 'bliss' was not found. You can install it by running 'sage -i bliss' in a shell
```

CC:  @jm58660

Component: **user interface**

Work Issues: **rebase**

Author: **Jeroen Demeyer**

Branch/Commit: **[u/jdemeyer/better_error_message_when__bliss__is_not_installed](https://github.com/sagemath/sagetrac-mirror/tree/u/jdemeyer/better_error_message_when__bliss__is_not_installed) @ [`bd63cfa`](https://github.com/sagemath/sagetrac-mirror/commit/bd63cfa33ab37e8a67cac13298777008ef2d5acd)**

_Issue created by migration from https://trac.sagemath.org/ticket/19622_

**Comment by mkoeppe** [comment]
Outdated
