### ISSUE TITLE
Potential refactoring of the species code

### ISSUE THREAD

**Issue by nthiery** [sagemath/sage#20622]
<div id="comment:0"></div>

The branch attached to this ticket propose a refactoring of the species code by Jean-Baptiste Priez

See src/sage/combinat/species2.

CC:  @tscrim @fchapoton

Component: **combinatorics**

Keywords: **species, LazyPowerSeries**

Branch/Commit: **[public/combinat/species-refactoring](https://github.com/sagemath/sagetrac-mirror/tree/public/combinat/species-refactoring) @ [`4bdf1cb`](https://github.com/sagemath/sagetrac-mirror/commit/4bdf1cbbb93de9376cbd75c9e6488d6b3aa8ebfa)**

_Issue created by migration from https://trac.sagemath.org/ticket/20622_

**Comment by mantepse** [comment]
Changed keywords from none to **species, LazyPowerSeries**

**Comment by mantepse** [comment]
<div id="comment:7" align="right">comment:7</div>

I think we can close this, since the new `LazyPowerSeries` code has been merged.

**Comment by tscrim** [comment]
<div id="comment:8" align="right">comment:8</div>

Possibly, but there might be some other refactoring independent of the power series stuff that could be desired. It would be good if there was a little bit more information in this regard.
