### ISSUE TITLE
guessing k-regular sequences

### ISSUE THREAD

**Issue by dkrenn** [sagemath/sage#21204]
<div id="comment:0"></div>

Code for guessing the parameters of k-regular sequences from the first few entries of a list/sequence/etc.

See also Meta ticket #21202.

Depends on #21319

CC:  @rwst

Component: **combinatorics**

Author: **Daniel Krenn**

Branch/Commit: **[u/cheuberg/sequences/k-regular-guess](https://github.com/sagemath/sagetrac-mirror/tree/u/cheuberg/sequences/k-regular-guess) @ [`ae06d17`](https://github.com/sagemath/sagetrac-mirror/commit/ae06d17a726de124938b43736d68571eca60000a)**

Reviewer: **Clemens Heuberger**

_Issue created by migration from https://trac.sagemath.org/ticket/21204_

**Comment by cheuberg** [comment]
Changed branch from **[u/dkrenn/sequences/k-regular-guess](https://github.com/sagemath/sagetrac-mirror/tree/u/dkrenn/sequences/k-regular-guess)** to **[u/cheuberg/sequences/k-regular-guess](https://github.com/sagemath/sagetrac-mirror/tree/u/cheuberg/sequences/k-regular-guess)**

**Comment by cheuberg** [comment]
<div id="comment:37" align="right">comment:37</div>

Clean merge of the latest beta (9.8.beta1)

---
New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/9b2e3596140223377baeb0d603e4e2dbdbc4750a"><code>9b2e359</code></a></td><td><code>Merge tag '9.7.beta7' into HEAD</code></td></tr><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/5cab567743ec6e4175807b27fb34936658664821"><code>5cab567</code></a></td><td><code>Merge tag '9.8.beta1' into u/cheuberg/sequences/k-regular-guess</code></td></tr></table>

**Comment by cheuberg** [comment]
Changed commit from **[`3c634df`](https://github.com/sagemath/sagetrac-mirror/commit/3c634dfa4a3e0fea249bc59e8e6fb0aab0dc06e5)** to **[`5cab567`](https://github.com/sagemath/sagetrac-mirror/commit/5cab567743ec6e4175807b27fb34936658664821)**

**Comment by cheuberg** [comment]
<div id="comment:38" align="right">comment:38</div>

Sorry, that was a wrong push. I'll fix it soon.

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
Changed commit from **[`5cab567`](https://github.com/sagemath/sagetrac-mirror/commit/5cab567743ec6e4175807b27fb34936658664821)** to **[`8ee2328`](https://github.com/sagemath/sagetrac-mirror/commit/8ee2328f141bc53305be09f08561dceaff8d7a78)**

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
<div id="comment:39"></div>

Branch pushed to git repo; I updated commit sha1. This was a forced push. Last 10 new commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/bde8e679f9c51dcb69106d5aa561a2bab0b32226"><code>bde8e67</code></a></td><td><code>Merge branch 't/21319/sequences/rec-hash' into t/21204/sequences/k-regular-guess</code></td></tr><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/622c3f67a238f25c824b28cbe7bc5235a4177747"><code>622c3f6</code></a></td><td><code>Merge branch 'u/dkrenn/sequences/rec-hash' into u/dkrenn/sequences/k-regular-guess</code></td></tr><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/4e7f61556b267b7444e19d1667ab971f0d90bfac"><code>4e7f615</code></a></td><td><code>Merge branch 'u/dkrenn/sequences/rec-hash' into u/dkrenn/sequences/k-regular-guess</code></td></tr><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/e726278bb2cf8c62977ccba1458954c885785dbd"><code>e726278</code></a></td><td><code>Merge branch 't/21319/sequences/rec-hash' into t/21204/sequences/k-regular-guess</code></td></tr><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/dcc7cd10d93039d84503d0128c3925b0c17adff0"><code>dcc7cd1</code></a></td><td><code>Trac #21204: cherry-pick to avoid merge conflict</code></td></tr><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/c0519f07490f7f6114765a12a72ced1956f811b7"><code>c0519f0</code></a></td><td><code>Trac #21204: fixup code and tests</code></td></tr><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/5ce5276bf6e99b0efe389bd4db985562b8b6c445"><code>5ce5276</code></a></td><td><code>Merge branch 't/21319/sequences/rec-hash' into t/21204/sequences/k-regular-guess</code></td></tr><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/00047cea6b8830b154d8b8954ceaecd24d32ab20"><code>00047ce</code></a></td><td><code>Trac #21204: fix punctuation</code></td></tr><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/3c634dfa4a3e0fea249bc59e8e6fb0aab0dc06e5"><code>3c634df</code></a></td><td><code>Merge branch 't/21319/sequences/rec-hash' into t/21204/sequences/k-regular-guess</code></td></tr><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/8ee2328f141bc53305be09f08561dceaff8d7a78"><code>8ee2328</code></a></td><td><code>Merge tag '9.8.beta1' into u/cheuberg/sequences/k-regular-guess</code></td></tr></table>

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
Changed commit from **[`8ee2328`](https://github.com/sagemath/sagetrac-mirror/commit/8ee2328f141bc53305be09f08561dceaff8d7a78)** to **[`4337bd3`](https://github.com/sagemath/sagetrac-mirror/commit/4337bd3bfd6ec1297260c009acd48666c105de24)**

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
<div id="comment:40"></div>

Branch pushed to git repo; I updated commit sha1. New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/4337bd3bfd6ec1297260c009acd48666c105de24"><code>4337bd3</code></a></td><td><code>Fix pycodestyle issue E306</code></td></tr></table>

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
<div id="comment:41"></div>

Branch pushed to git repo; I updated commit sha1. New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/ae06d17a726de124938b43736d68571eca60000a"><code>ae06d17</code></a></td><td><code>Trac #21204: Fix typo</code></td></tr></table>

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
Changed commit from **[`4337bd3`](https://github.com/sagemath/sagetrac-mirror/commit/4337bd3bfd6ec1297260c009acd48666c105de24)** to **[`ae06d17`](https://github.com/sagemath/sagetrac-mirror/commit/ae06d17a726de124938b43736d68571eca60000a)**

**Comment by cheuberg** [comment]
Reviewer: **Clemens Heuberger**
