### ISSUE TITLE
Introduce extension of scalars coercion of CombinatorialFreeModules

### ISSUE THREAD

**Issue by tscrim** [sagemath/sage#21405]
<div id="comment:0"></div>

Currently, `CombinatorialFreeModule` does not allow coercion from another `CombinatorialFreeModule` with the same indices but with a base ring coercion:

```sage
sage: C = CombinatorialFreeModule(ZZ, Set([1,2]))
sage: CQ = CombinatorialFreeModule(QQ, Set([1,2]))
sage: CQ.has_coerce_map_from(C)
False
```
In this ticket, we introduce such a coercion and also implement `C.change_ring(QQ)` (which also makes `C.base_extend(QQ)` work).

CC:  @sagetrac-sage-combinat @nthiery @darijgr @fchapoton

Component: **combinatorics**

Keywords: **combinatorial free module**

Author: **Travis Scrimshaw, Matthias Koeppe**

Reviewer: **Darij Grinberg**

_Issue created by migration from https://trac.sagemath.org/ticket/21405_

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
Changed commit from **[`286883e`](https://github.com/sagemath/sagetrac-mirror/commit/286883e5880c388fb74bc6c0c63352ad716d5fad)** to **[`7f69146`](https://github.com/sagemath/sagetrac-mirror/commit/7f69146f4390e52a7d62f900a2de1db9385e19bc)**

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
<div id="comment:20"></div>

Branch pushed to git repo; I updated commit sha1. This was a forced push. New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/1da89f6ee2a6584ffe2d47ada4c953aa41d6510a"><code>1da89f6</code></a></td><td><code>Initial version of introducing coercion of base rings.</code></td></tr><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/7f69146f4390e52a7d62f900a2de1db9385e19bc"><code>7f69146</code></a></td><td><code>review</code></td></tr></table>

**Comment by mkoeppe** [comment]
<div id="comment:21" align="right">comment:21</div>

rebased on 9.8.beta6

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
<div id="comment:22"></div>

Branch pushed to git repo; I updated commit sha1. New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/69d5605c475c22cbeabd9ef15c8d979ba84c0e7e"><code>69d5605</code></a></td><td><code>CombinatorialFreeModule.change_ring: New</code></td></tr></table>

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
Changed commit from **[`7f69146`](https://github.com/sagemath/sagetrac-mirror/commit/7f69146f4390e52a7d62f900a2de1db9385e19bc)** to **[`69d5605`](https://github.com/sagemath/sagetrac-mirror/commit/69d5605c475c22cbeabd9ef15c8d979ba84c0e7e)**

**Comment by mkoeppe** [comment]
<div id="comment:23" align="right">comment:23</div>

The test in `CombinatorialFreeModule._coerce_map_from_` was not strict enough, leading to lots of doctest failures in combinat.

I'm replacing it with a stricter test based on `base_extend`.

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
Changed commit from **[`69d5605`](https://github.com/sagemath/sagetrac-mirror/commit/69d5605c475c22cbeabd9ef15c8d979ba84c0e7e)** to **[`bc88a0b`](https://github.com/sagemath/sagetrac-mirror/commit/bc88a0bd451f27661a7f6a675eb8983ec140b8d8)**

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
<div id="comment:24"></div>

Branch pushed to git repo; I updated commit sha1. New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/bc88a0bd451f27661a7f6a675eb8983ec140b8d8"><code>bc88a0b</code></a></td><td><code>CombinatorialFreeModule._coerce_map_from_: Tighten test using base_extend</code></td></tr></table>

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
Changed commit from **[`bc88a0b`](https://github.com/sagemath/sagetrac-mirror/commit/bc88a0bd451f27661a7f6a675eb8983ec140b8d8)** to **[`e82d44f`](https://github.com/sagemath/sagetrac-mirror/commit/e82d44f2b4becc9a30fa8d991bd3c469dc1b397b)**

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
<div id="comment:25"></div>

Branch pushed to git repo; I updated commit sha1. New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/e82d44f2b4becc9a30fa8d991bd3c469dc1b397b"><code>e82d44f</code></a></td><td><code>src/sage/combinat/free_module.py: Add doctest</code></td></tr></table>

**Comment by mkoeppe** [comment]
<div id="comment:26" align="right">comment:26</div>

The changed doctests in `src/sage/modules/with_basis/indexed_element.pyx` fail

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
Changed commit from **[`e82d44f`](https://github.com/sagemath/sagetrac-mirror/commit/e82d44f2b4becc9a30fa8d991bd3c469dc1b397b)** to **[`083c680`](https://github.com/sagemath/sagetrac-mirror/commit/083c680990ade93ece1f1bcda3e9c4224685dbca)**

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
<div id="comment:27"></div>

Branch pushed to git repo; I updated commit sha1. New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/083c680990ade93ece1f1bcda3e9c4224685dbca"><code>083c680</code></a></td><td><code>src/sage/modules/with_basis/indexed_element.pyx: Revert changes to doctests</code></td></tr></table>

**Comment by mkoeppe** [comment]
Changed author from **Travis Scrimshaw** to **Travis Scrimshaw, Matthias Koeppe**

**Comment by mkoeppe** [comment]
<div id="comment:30" align="right">comment:30</div>

Bots are green, ready for review

**Comment by mkoeppe** [comment]
Removed branch from the issue description; replaced by PR #35102
