### ISSUE TITLE
EllipticCurveIsogeny raising a value error that an isogeny doesn't exist while it most certainly does!

### ISSUE THREAD

**Issue by koffie** [sagemath/sage#21883]
<div id="comment:0"></div>

```
sage: E = EllipticCurve_from_j(0)
sage: E
Elliptic Curve defined by y^2 + y = x^3 over Rational Field
sage: phi = E.isogenies_prime_degree(3)[1]
sage: phi
Isogeny of degree 3 from Elliptic Curve defined by y^2 + y = x^3 over Rational Field to Elliptic Curve defined by y^2 + y = x^3 - 7 over Rational Field
sage: EllipticCurveIsogeny(E,None,codomain=phi.codomain(),degree=3)
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-58-7c6e8f3f3fa6> in <module>()
----> 1 EllipticCurveIsogeny(E,None,codomain=phi.codomain(),degree=Integer(3))

/Applications/sage/local/lib/python2.7/site-packages/sage/schemes/elliptic_curves/ell_curve_isogeny.pyc in __init__(self, E, kernel, codomain, degree, model, check)
   1008             old_codomain = codomain
   1009 
-> 1010             (pre_isom, post_isom, E, codomain, kernel) = compute_sequence_of_maps(E, codomain, degree)
   1011 
   1012         self.__init_algebraic_structs(E)

/Applications/sage/local/lib/python2.7/site-packages/sage/schemes/elliptic_curves/ell_curve_isogeny.pyc in compute_sequence_of_maps(E1, E2, ell)
   4003     (E1pr, E2pr, pre_isom, post_isom) = compute_intermediate_curves(E1, E2)
   4004 
-> 4005     ker_poly = compute_isogeny_kernel_polynomial(E1pr, E2pr, ell)
   4006 
   4007     return (pre_isom, post_isom, E1pr, E2pr, ker_poly)

/Applications/sage/local/lib/python2.7/site-packages/sage/schemes/elliptic_curves/ell_curve_isogeny.pyc in compute_isogeny_kernel_polynomial(E1, E2, ell, algorithm)
   3831         x^3 + x
   3832     """
-> 3833     return split_kernel_polynomial(compute_isogeny_starks(E1, E2, ell))
   3834 
   3835 def compute_intermediate_curves(E1, E2):

/Applications/sage/local/lib/python2.7/site-packages/sage/schemes/elliptic_curves/ell_curve_isogeny.pyc in compute_isogeny_starks(E1, E2, ell)
   3735         if (n == ell+1 or T == 0):
   3736             if (T == 0 or T.valuation()<2):
-> 3737                 raise ValueError("The two curves are not linked by a cyclic normalized isogeny of degree %s" % ell)
   3738             break
   3739 

ValueError: The two curves are not linked by a cyclic normalized isogeny of degree 3
```

The above might seem like a silly example, since I am asking for an object I already know. But it is the underlying problem of why:

```
sage: phi.dual()
...
ValueError: The two curves are not linked by a cyclic normalized isogeny of degree 3
```
is also broken.

Component: **elliptic curves**

_Issue created by migration from https://trac.sagemath.org/ticket/21883_

**Comment by JohnCremona** [comment]
I had forgotten all about this but it really needs to be fixed.  Trying all curves of conductor <1000 and all prime degrees of isogeny, the ones where computing the dual fails are these (only degree 3 for some reason):

27a1, phi of degree 3, dual fails
27a3, phi of degree 3, dual fails
36a1, phi of degree 3, dual fails
36a3, phi of degree 3, dual fails
108a1, phi of degree 3, dual fails
108a2, phi of degree 3, dual fails
144a1, phi of degree 3, dual fails
144a3, phi of degree 3, dual fails
225a1, phi of degree 3, dual fails
225a2, phi of degree 3, dual fails
225b1, phi of degree 3, dual fails
225b2, phi of degree 3, dual fails
243a1, phi of degree 3, dual fails
243a2, phi of degree 3, dual fails
243b1, phi of degree 3, dual fails
243b2, phi of degree 3, dual fails
432a1, phi of degree 3, dual fails
432a3, phi of degree 3, dual fails
432b1, phi of degree 3, dual fails
432b2, phi of degree 3, dual fails
441a1, phi of degree 3, dual fails
441a2, phi of degree 3, dual fails
441b1, phi of degree 3, dual fails
441b2, phi of degree 3, dual fails
576a1, phi of degree 3, dual fails
576a3, phi of degree 3, dual fails
576e1, phi of degree 3, dual fails
576e3, phi of degree 3, dual fails
675a1, phi of degree 3, dual fails
675a2, phi of degree 3, dual fails
675c1, phi of degree 3, dual fails
675c2, phi of degree 3, dual fails
675e1, phi of degree 3, dual fails
675e2, phi of degree 3, dual fails
900a1, phi of degree 3, dual fails
900a2, phi of degree 3, dual fails
900b1, phi of degree 3, dual fails
900b3, phi of degree 3, dual fails
900c1, phi of degree 3, dual fails
900c2, phi of degree 3, dual fails
972a1, phi of degree 3, dual fails
972a2, phi of degree 3, dual fails
972b1, phi of degree 3, dual fails
972b2, phi of degree 3, dual fails
972c1, phi of degree 3, dual fails
972c2, phi of degree 3, dual fails
972d1, phi of degree 3, dual fails
972d2, phi of degree 3, dual fails

**Comment by yyyyx4** [comment]
This appears to be a precision issue in `compute_isogeny_stark()` which apparently only affects curves with 𝑗‑invariant 0 and isogenies of degree ℓ=3. I'll create a pull request with a simple fix shortly.
