### ISSUE TITLE
Substitutions inside piecewise functions don't work

### ISSUE THREAD

**Issue by rwst** [sagemath/sage#22102]
<div id="comment:0"></div>

Not implemented at the moment

```
sage: f = piecewise([((0,1), x^2), ([-1,0], -x)], var=x);
sage: f.subs(x=-1)
1
sage: f.subs(x=y)
...
ValueError: substituting the piecewise variable must result in real number
```

Component: **symbolics**

Author: **Ralf Stephan**

Branch/Commit: **[u/rws/substitutions_inside_piecewise_functions_don_t_work](https://github.com/sagemath/sagetrac-mirror/tree/u/rws/substitutions_inside_piecewise_functions_don_t_work) @ [`98cab8b`](https://github.com/sagemath/sagetrac-mirror/commit/98cab8bb643a9545058bd0eca1a0d5054bdf0a38)**

_Issue created by migration from https://trac.sagemath.org/ticket/22102_

**Comment by fchapoton** [comment]
see #38706 for some progress
