### ISSUE TITLE
Support installing Python packages from wheels

### ISSUE THREAD

**Issue by jdemeyer** [sagemath/sage#22595]
<div id="comment:0"></div>

There is a tendency towards distributing Python packages as wheels only. We should support that in Sage, at least for wheels which are system-independent.

CC:  @embray

Component: **build**

Keywords: **days85**

_Issue created by migration from https://trac.sagemath.org/ticket/22595_

**Comment by mkoeppe** [comment]
Since #34450 (Sage 9.7) we have (platform-independent) wheel packages; closing as completed.
