### ISSUE TITLE
Sage generates crash report when you press Ctrl+C on startup

### ISSUE THREAD

**Issue by 99514226-a908-499f-9d44-b1ea6f8968c4** [sagemath/sage#22612]
<div id="comment:0"></div>

When I start Sage from the command line and press Ctrl+C before it starts up fully, it generates a crash report. It seems like it should quit more gracefully. I'm attaching the crash report.

Component: **PLEASE CHANGE**

_Issue created by migration from https://trac.sagemath.org/ticket/22612_

**Comment by mkoeppe** [comment]
Closing as outdated.
