### ISSUE TITLE
Don't embed rpaths during the build

### ISSUE THREAD

**Issue by c4796b8b-df47-4c78-a415-d934347608f6** [sagemath/sage#23359]
<div id="comment:0"></div>

As per #22509, `DESTDIR` is useful in the cases where the build process needs to hard-code `--prefix` paths in the build output. For example, embedded rpaths. This is not only useful but vital for binary distros who can't write to /usr during a build.

It's less important - and one can get away with only supporting `--prefix` - if the build does not embed these paths. However nowadays `DESTDIR` is a common standard, so it's good to support it regardless.

Since Sage 8.0 currently does not support DESTDIR (and neither did previous versions) I have to carry the following patch in Debian. It would be technically unnecessary after DESTDIR support is introduced, however in Debian we also have a policy to avoid rpath if possible.

Even disregarding Debian, there is no particular reason for Sage to go embedding rpaths in its binaries, it prevents SAGE_LOCAL from being moved to different places around the filesystem. AFAICS, no other part of Sage involves embedding build paths, and one can freely move a SAGE_LOCAL around after applying this patch.

Component: **build**

Author: **Ximin Luo**

Branch/Commit: **[u/infinity0/don_t_embed_rpaths_during_the_build](https://github.com/sagemath/sagetrac-mirror/tree/u/infinity0/don_t_embed_rpaths_during_the_build) @ [`d3d0f46`](https://github.com/sagemath/sagetrac-mirror/commit/d3d0f46c33eb5cd230247a30ecef4e7ea33b70b5)**

_Issue created by migration from https://trac.sagemath.org/ticket/23359_

**Comment by c4796b8b-df47-4c78-a415-d934347608f6** [comment]
Description changed:
``````diff
--- 
+++ 
@@ -1 +1,8 @@
+As per #22509, `DESTDIR` is useful in the cases where the build process needs to hard-code `--prefix` paths in the build output. For example, embedded rpaths. This is not only useful but vital for binary distros who can't write to /usr during a build.
 
+It's less important - and one can get away with only supporting `--prefix` - if the build does not embed these paths. However nowadays `DESTDIR` is a common standard, so it's good to support it regardless.
+
+Since Sage 8.0 currently does not support DESTDIR (and neither did previous versions) I have to carry the following patch in Debian. It would be technically unnecessary after DESTDIR support is introduced, however in Debian we also have a policy to avoid rpath if possible.
+
+Even disregarding Debian, there is no particular reason for Sage to go embedding rpaths in its binaries, it prevents SAGE_LOCAL from being moved to different places around the filesystem. AFAICS, no other part of Sage involves embedding build paths, and one can freely move a SAGE_LOCAL around after applying this patch.
+
``````

**Comment by mkoeppe** [comment]
Closing as not planned.
