### ISSUE TITLE
Unlinkable documentation files

### ISSUE THREAD

**Issue by rwst** [sagemath/sage#23666]
<div id="comment:0"></div>

There are two files that refer to documents up the tree without any problem:
* `src/doc/en/prep/Quickstarts/Multivariable-Calculus.rst` links `<../Calculus>`
* `src/doc/en/prep/Quickstarts/Interact.rst` links to `<../Programming>`

but it was not possible for me to compile a link to `<../polynomial_rings/index>` included in the file `src/doc/en/reference/calculus/index.rst` nor a similar link upwards.

Condition: it must be compiled with `make` after `make doc-clean`

Component: **documentation**

_Issue created by migration from https://trac.sagemath.org/ticket/23666_

**Comment by mkoeppe** [comment]
Closing as superseded by #37597
