### ISSUE TITLE
make sage work on arm64/aarch64

### ISSUE THREAD

**Issue by dimpase** [sagemath/sage#23687]
<div id="comment:0"></div>

This is [known to work in debian](https://groups.google.com/d/msg/sage-packaging/8LLsdHPAPXc/J9iZDZNGBQAJ), but
needs at least newer gc version, maybe more.

Depends on #23700
Depends on #23701
Depends on #23712

CC:  @kiwifb

Component: **porting**

_Issue created by migration from https://trac.sagemath.org/ticket/23687_

**Comment by mkoeppe** [comment]
Closing this, as Sage is routinely built on M1/M2 Macs these days
