### ISSUE TITLE
Upgrade to Tachyon 0.99.5

### ISSUE THREAD

**Issue by dimpase** [sagemath/sage#23712]
<div id="comment:0"></div>

We currently are shipping a 12 years old tachyon (0.98.9).

0.99.2 was released Dec 2021. http://jedi.ks.uiuc.edu/~johns/raytracer/files/

This is also needed to make Sage work on arm64/aarch64, see #23687.

Many distributions are still on 0.99.beta6 - https://repology.org/project/tachyon/versions

In Debian:
- https://salsa.debian.org/science-team/tachyon
- https://packages.debian.org/source/buster/tachyon
- https://packages.debian.org/source/sid/tachyon
- https://packages.debian.org/source/stretch/tachyon

CC:  @slel @orlitzky @kiwifb @antonio-rojas @tscrim

Component: **packages: standard**

Keywords: **upgrade, tachyon**

Author: **Dima Pasechnik, Gonzalo Tornaría**

Branch/Commit: **[u/dimpase/packages/tachyon0992](https://github.com/sagemath/sagetrac-mirror/tree/u/dimpase/packages/tachyon0992) @ [`d3034fc`](https://github.com/sagemath/sagetrac-mirror/commit/d3034fce69bfe19a5f5f73d5f6aecff19c223a2a)**

Reviewer: **Matthias Koeppe**

_Issue created by migration from https://trac.sagemath.org/ticket/23712_

**Comment by slel** [comment]
Description changed:
``````diff
--- 
+++ 
@@ -3,5 +3,11 @@
 
 This is also needed to make Sage work on arm64/aarch64, see #23687.
 
-the tarball is here: http://jedi.ks.uiuc.edu/~johns/tachyon/files/0.99b6/tachyon-0.99b6.tar.gz
+- **Tarball**: http://jedi.ks.uiuc.edu/~johns/tachyon/files/0.99b6/tachyon-0.99b6.tar.gz
 
+In Debian:
+- https://salsa.debian.org/science-team/tachyon
+- https://packages.debian.org/source/buster/tachyon
+- https://packages.debian.org/source/sid/tachyon
+- https://packages.debian.org/source/stretch/tachyon
+
``````

**Comment by mkoeppe** [comment]
Description changed:
``````diff
--- 
+++ 
@@ -1,9 +1,13 @@
 We currently are shipping a 7 years old tachyon (0.98).
-0.99b6 is from 2013, and is de facto stable version, e.g. in debian or gentoo.
+
+0.99.2 was released Dec 2021. http://jedi.ks.uiuc.edu/~johns/raytracer/files/
 
 This is also needed to make Sage work on arm64/aarch64, see #23687.
 
-- **Tarball**: http://jedi.ks.uiuc.edu/~johns/tachyon/files/0.99b6/tachyon-0.99b6.tar.gz
+- **Tarball**: http://jedi.ks.uiuc.edu/~johns/raytracer/files/0.99.2/tachyon-0.99.2.tar.gz
+
+Many distributions are still on 0.99.beta6 - https://repology.org/project/tachyon/versions
+
 
 In Debian:
 - https://salsa.debian.org/science-team/tachyon
``````

**Comment by mkoeppe** [comment]
Description changed:
``````diff
--- 
+++ 
@@ -1,4 +1,4 @@
-We currently are shipping a 7 years old tachyon (0.98).
+We currently are shipping a 12 years old tachyon (0.98.9).
 
 0.99.2 was released Dec 2021. http://jedi.ks.uiuc.edu/~johns/raytracer/files/
 
``````

**Comment by tornaria** [comment]
<div id="comment:28" align="right">comment:28</div>

The following makes all tests pass with new versions of tachyon, without breaking old versions. I tested it with 0.99 (old) and 0.99.5 (new).

This does not change the sage interface in `sage.plot.plot3d.tachyon`, it will still use `focallength` so the change is very safe to apply. In the future (possibly when tachyon in sage gets upgraded), all the `focallength` occurences in `sage.plot.plot3d.tachyon` can be replaced by `focaldist` for consistency with new tachyon, and the logic here can be reversed (i.e. patch the model when `self.version() < '0.99.2'`).




```diff
--- a/src/sage/interfaces/tachyon.py
+++ b/src/sage/interfaces/tachyon.py
@@ -683,12 +683,14 @@
 #*****************************************************************************
 
 import os
+import re
 
 from sage.cpython.string import bytes_to_str
 from sage.misc.pager import pager
 from sage.misc.superseded import deprecation
 from sage.misc.temporary_file import tmp_filename
 from sage.structure.sage_object import SageObject
+from sage.misc.cachefunc import cached_method
 
 
 class TachyonRT(SageObject):
@@ -799,6 +801,11 @@ class TachyonRT(SageObject):
             Parser failed due to an input file syntax error.
             Aborting render.
         """
+        if self.version() >= '0.99.2':
+            # this keyword was changed in 0.99.2
+            model = model.replace(
+                    "              focallength ",
+                    "              focaldist ")
         modelfile = tmp_filename(ext='.dat')
         with open(modelfile, 'w') as file:
             file.write(model)
@@ -851,6 +858,22 @@ class TachyonRT(SageObject):
         else:
             print(r)
 
+    @cached_method
+    def version(self):
+        """
+        Returns the version of the Tachyon raytracer being used.
+
+        TESTS::
+
+            sage: tachyon_rt.version()  # not tested
+            0.98.9
+            sage: tachyon_rt.version() >= '0.98.9'
+            True
+        """
+        with os.popen('tachyon') as f:
+            r = f.read()
+        return re.search(r"Version ([\d.]*)", r)[1]
+
     def help(self, use_pager=True):
         """
         Deprecated: type 'sage.interfaces.tachyon?' for help
```


BTW, in order for tachyon spkg to work in aarch64, all I had to do is the following trivial change:

```diff
--- a/build/pkgs/tachyon/spkg-install.in
+++ b/build/pkgs/tachyon/spkg-install.in
@@ -30,7 +30,7 @@
     ppc*|powerpc*)
         TARGET=linux-ppc
         ;;
-    armv6l*|armv7l*)
+    armv6l*|armv7l*|aarch64*)
         TARGET=linux-arm-thr
         ;;
     esac
```

**Comment by dimpase** [comment]
<div id="comment:29" align="right">comment:29</div>

afk, please post your branch here

**Comment by tornaria** [comment]
<div id="comment:30" align="right">comment:30</div>

See `u/tornaria/tachyon`. I'm not sure if I should overwrite the current branch, or move this to a separate ticket.

My branch is "safe" in the sense that it doesn't touch the spkg (other than allowing building on linux aarch64 but that is broken now and the trivial change doesn't affect other architectures) but it will allow sagemath to work ok with newer versions of tachyon in the system.

I'd rather see those two commits on 9.8 if upgrading tachyon spkg needs more testing, since I will be upgrading tachyon on void linux soon.

**Comment by dimpase** [comment]
<div id="comment:31" align="right">comment:31</div>

changing Branch field here does not overwrite anything - the old branch stays good and well. (you need to use git to overwrite a branch)

**Comment by dimpase** [comment]
Changed author from **Dima Pasechnik** to **Dima Pasechnik, Gonzalo Tornaría**

**Comment by dimpase** [comment]
Changed branch from **[public/23712](https://github.com/sagemath/sagetrac-mirror/tree/public/23712)** to **[u/tornaria/tachyon](https://github.com/sagemath/sagetrac-mirror/tree/u/tornaria/tachyon)**

**Comment by dimpase** [comment]
<div id="comment:32"></div>

New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/55c04623a4b7404f5e4f9d152366d53e9c21cfa6"><code>55c0462</code></a></td><td><code>Trac #23712: support tachyon >= 0.99.2</code></td></tr><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/3390c835ec5301d074931d6bc1ce3106ffdf4446"><code>3390c83</code></a></td><td><code>Trac #23712: aarch64 support for tachyon spkg</code></td></tr></table>

**Comment by dimpase** [comment]
Changed commit from **[`6209e8e`](https://github.com/sagemath/sagetrac-mirror/commit/6209e8e5903286a51f8bdbfd7fffc829a4e1d617)** to **[`3390c83`](https://github.com/sagemath/sagetrac-mirror/commit/3390c835ec5301d074931d6bc1ce3106ffdf4446)**

**Comment by dimpase** [comment]
<div id="comment:33" align="right">comment:33</div>

added checksums etc (for 0.99.5)

**Comment by dimpase** [comment]
Changed commit from **[`3390c83`](https://github.com/sagemath/sagetrac-mirror/commit/3390c835ec5301d074931d6bc1ce3106ffdf4446)** to **[`d86d550`](https://github.com/sagemath/sagetrac-mirror/commit/d86d550de2a3b64c454d8e1534b81d93f590f093)**

**Comment by dimpase** [comment]
Changed branch from **[u/tornaria/tachyon](https://github.com/sagemath/sagetrac-mirror/tree/u/tornaria/tachyon)** to **[u/dimpase/packages/tachyon0992](https://github.com/sagemath/sagetrac-mirror/tree/u/dimpase/packages/tachyon0992)**

**Comment by dimpase** [comment]
Description changed:
``````diff
--- 
+++ 
@@ -4,7 +4,7 @@
 
 This is also needed to make Sage work on arm64/aarch64, see #23687.
 
-- **Tarball**: http://jedi.ks.uiuc.edu/~johns/raytracer/files/0.99.2/tachyon-0.99.2.tar.gz
+
 
 Many distributions are still on 0.99.beta6 - https://repology.org/project/tachyon/versions
 
``````

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
Changed commit from **[`d86d550`](https://github.com/sagemath/sagetrac-mirror/commit/d86d550de2a3b64c454d8e1534b81d93f590f093)** to **[`3756c85`](https://github.com/sagemath/sagetrac-mirror/commit/3756c85a1ca118f9a0244c8029268740cb01bdb1)**

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
<div id="comment:35"></div>

Branch pushed to git repo; I updated commit sha1. New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/3756c85a1ca118f9a0244c8029268740cb01bdb1"><code>3756c85</code></a></td><td><code>remove patches</code></td></tr></table>

**Comment by dimpase** [comment]
<div id="comment:36" align="right">comment:36</div>

doesn't work with 0.99.5: typical error is

```
sage -t --warn-long 60.9 --random-seed=298292522010650641629269891184485194160 src/sage/plot/plot3d/implicit_plot3d.py
**********************************************************************
File "src/sage/plot/plot3d/implicit_plot3d.py", line 53, in sage.plot.plot3d.implicit_plot3d.implicit_plot3d
Failed example:
    implicit_plot3d((x^2 + y^2 + z^2), (x,-2,2), (y,-2,2), (z,-2,2), plot_points=60, contour=[1,3,5],
                    region=lambda x,y,z: x<=0.2 or y>=0.2 or z<=0.2, color='aquamarine').show(viewer='tachyon')
Exception raised:
    Traceback (most recent call last):
      File "/mnt/opt/Sage/sage-dev/src/sage/doctest/forker.py", line 695, in _run
        self.compile_and_execute(example, compiler, test.globs)
      File "/mnt/opt/Sage/sage-dev/src/sage/doctest/forker.py", line 1093, in compile_and_execute
        exec(compiled, globs)
      File "<doctest sage.plot.plot3d.implicit_plot3d.implicit_plot3d[2]>", line 1, in <module>
        implicit_plot3d((x**Integer(2) + y**Integer(2) + z**Integer(2)), (x,-Integer(2),Integer(2)), (y,-Integer(2),Integer(2)), (z,-Integer(2),Integer(2)), plot_points=Integer(60), contour=[Integer(1),Integer(3),Integer(5)],
      File "sage/plot/plot3d/base.pyx", line 1800, in sage.plot.plot3d.base.Graphics3d.show
        dm.display_immediately(self, **kwds)
      File "/mnt/opt/Sage/sage-dev/src/sage/repl/rich_output/display_manager.py", line 854, in display_immediately
        self._backend.display_immediately(plain_text, rich_output)
      File "/mnt/opt/Sage/sage-dev/src/sage/repl/rich_output/backend_doctest.py", line 210, in display_immediately
        self.validate(rich_output)
      File "/mnt/opt/Sage/sage-dev/src/sage/repl/rich_output/backend_doctest.py", line 271, in validate
        assert rich_output.png.get().startswith(b'\x89PNG')
    AssertionError
```

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
Changed commit from **[`3756c85`](https://github.com/sagemath/sagetrac-mirror/commit/3756c85a1ca118f9a0244c8029268740cb01bdb1)** to **[`d6656e8`](https://github.com/sagemath/sagetrac-mirror/commit/d6656e85c51280e236494d8a3ef9a12811e5379d)**

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
<div id="comment:37"></div>

Branch pushed to git repo; I updated commit sha1. New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/d6656e85c51280e236494d8a3ef9a12811e5379d"><code>d6656e8</code></a></td><td><code>add patch to tell tachyon to use png (from public/23712)</code></td></tr></table>

**Comment by dimpase** [comment]
<div id="comment:38" align="right">comment:38</div>

png patch was missing from Gonzalo's branch; we now add it, and it fixed [comment:36](#comment%3A36)

**Comment by dimpase** [comment]
<div id="comment:39" align="right">comment:39</div>

OK, now tests pass, both with this 0.99.5, and with 0.99 (from Fedora)

Good to go?

**Comment by dimpase** [comment]
<div id="comment:40" align="right">comment:40</div>

ping?

**Comment by mkoeppe** [comment]
<div id="comment:41" align="right">comment:41</div>

upstream server is down

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
<div id="comment:42"></div>

Branch pushed to git repo; I updated commit sha1. New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/d3034fce69bfe19a5f5f73d5f6aecff19c223a2a"><code>d3034fc</code></a></td><td><code>re-host tachyon tarball</code></td></tr></table>

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
Changed commit from **[`d6656e8`](https://github.com/sagemath/sagetrac-mirror/commit/d6656e85c51280e236494d8a3ef9a12811e5379d)** to **[`d3034fc`](https://github.com/sagemath/sagetrac-mirror/commit/d3034fce69bfe19a5f5f73d5f6aecff19c223a2a)**

**Comment by dimpase** [comment]
<div id="comment:43" align="right">comment:43</div>

I've had a copy, so I put it up for downloading

**Comment by mkoeppe** [comment]
<div id="comment:44" align="right">comment:44</div>

Thanks. Builds and tests OK on macOS (Intel) and `debian-buster-i386-standard`

**Comment by mkoeppe** [comment]
Reviewer: **Matthias Koeppe**

**Comment by vbraun** [comment]
<div id="comment:46" align="right">comment:46</div>

Doesn't run if the OS doesn't come with libpng:

```
tachyon: error while loading shared libraries: libpng16.so.16: cannot open shared object file: No such file or directory
```

**Comment by tornaria** [comment]
> I've had a copy, so I put it up for downloading

I found this at https://mirrors.mit.edu/sage/spkg/upstream/tachyon/index.html.

I can confirm by md5 that it is the same file I have from upstream. However, the original filename is `tachyon-0.99.5.tar.gz` and it is indeed compressed with gzip.

**Comment by tornaria** [comment]
> > I've had a copy, so I put it up for downloading
> 
> I found this at https://mirrors.mit.edu/sage/spkg/upstream/tachyon/index.html.
> 
> I can confirm by md5 that it is the same file I have from upstream. However, the original filename is `tachyon-0.99.5.tar.gz` and it is indeed compressed with gzip.

@dimpase can you please rename the file at https://mirrors.mit.edu/sage/spkg/upstream/tachyon/index.html from `...bz2` to `...gz`? This is indeed the original upstream file:
```
$ md5sum hostdir/sources/tachyon-0.99.5/tachyon-0.99.5.tar.gz
378156b54842fc91791daea6dd6f1a72  hostdir/sources/tachyon-0.99.5/tachyon-0.99.5.tar.gz
$ file hostdir/sources/tachyon-0.99.5/tachyon-0.99.5.tar.gz
hostdir/sources/tachyon-0.99.5/tachyon-0.99.5.tar.gz: gzip compressed data, was "tachyon20220423.tar", last modified: Sat Apr 23 15:25:31 2022, from Unix, original size modulo 2^32 8908800
```

BTW, the support for newer tachyon is already merged so it should be possible now to upgrade without trouble. I'm using 0.99.5 myself locally built, but I haven't been able to update the package on void just because of the missing release tarball.

**Comment by tornaria** [comment]
PS: in case you care about the date:
```
$ TZ=UTC ls --full-time hostdir/sources/tachyon-0.99.5/tachyon-0.99.5.tar.gz                                                             │
│-rw-r--r-- 1 tornaria tornaria 1163063 2022-04-23 15:06:53.000000000 +0000 hostdir/sources/tachyon-0.99.5/tachyon-0.99.5.tar.gz
```
AFAIK this should be the original timestamp.

**Comment by dimpase** [comment]
I can't rename anything there, it's @vbraun who can

**Comment by tornaria** [comment]
@vbraun or @haraldschilly : could you please fix the upstream source file `tachyon-0.99.5.tar.gz`?

This file is available in sagemath mirror, e.g. https://mirrors.mit.edu/sage/spkg/upstream/tachyon/index.html, but it is incorrectly named `tachyon-0.99.5.tar.bz2`.

This is the original file with the original timestamp that I downloaded from https://web.archive.org/web/20220523051055/http://jedi.ks.uiuc.edu/~johns/tachyon/files/0.99.5/:

```
$ TZ=UTC ls --full-time tachyon-0.99.5.tar.gz 
-rw-r--r-- 1 tornaria tornaria 1163063 2022-04-23 15:06:53.000000000 +0000 tachyon-0.99.5.tar.gz
$ sha256sum tachyon-0.99.5.tar.gz 
09203c102311149f5df5cc367409f96c725742666d19c24db5ba994d5a81a6f5  tachyon-0.99.5.tar.gz
$ nix --extra-experimental-features nix-command hash file tachyon-0.99.5.tar.gz 
sha256-CSA8ECMRFJ9d9cw2dAn5bHJXQmZtGcJNtbqZTVqBpvU=
$ md5sum tachyon-0.99.5.tar.gz 
378156b54842fc91791daea6dd6f1a72  tachyon-0.99.5.tar.gz
```

As a reference, the sha256sum matches the one in [archlinux](https://github.com/archlinux/svntogit-community/blob/packages/tachyon/trunk/PKGBUILD#L16) and in [nixpkgs](https://github.com/NixOS/nixpkgs/blob/nixos-22.11/pkgs/development/libraries/tachyon/default.nix#L15).

The file that it is now available in the sagemath upstream mirror is the correct one, but the filename is not the original one (neither is the timestamp).

**Comment by mkoeppe** [comment]
> the support for newer tachyon is already merged so it should be possible now to upgrade without trouble

Let's restart this effort for Sage 10.3.

Current version in Sage gives an error with conda-forge-python3.11-minimal https://github.com/sagemath/sage/actions/runs/6842945144/job/18604992673#step:11:2493
```
  [tachyon-0.98.9.p7]   /opt/conda/bin/x86_64-conda-linux-gnu-cc -m64 -Wall -O3 -fomit-frame-pointer -ffast-math -DLinux -DLP64 -DTHR -D_REENTRANT  -DUSEPNG    -I/sage/local/include  -c ../src/pngfile.c -o ../compile/linux-64-thr/libtachyon/pngfile.o
  [tachyon-0.98.9.p7]   ../src/pngfile.c:33:10: fatal error: png.h: No such file or directory
  [tachyon-0.98.9.p7]      33 | #include "png.h" /* the libpng library headers */
  [tachyon-0.98.9.p7]         |          ^~~~~~~
  [tachyon-0.98.9.p7]   compilation terminated.
  [tachyon-0.98.9.p7]   make[5]: *** [Makefile:317: ../compile/linux-64-thr/libtachyon/pngfile.o] Error 1
```
... and I'd rather debug it for the new version than for the ancient version...

**Comment by mkoeppe** [comment]
> I can confirm by md5 that it is the same file I have from upstream. However, the original filename is `tachyon-0.99.5.tar.gz` and it is indeed compressed with gzip.

@tornaria In #36959, I have changed the `tarball` attribute to the correct file extension, so a new file tachyon-0.99.5.tar.gz will be uploaded to the mirrors when this PR is merged.

**Comment by aikrahguzar** [comment]
I am running into problems with building sage on aarch64 linux due to tachyon. The buid failed with,
```
[spkg-install] Error: Sorry, your platform isn't supported by Tachyon and/or Sage. Exiting...
```
when trying to install tachyon-0.98.9.p7

**Comment by mkoeppe** [comment]
Or rather https://github.com/sagemath/sage/pull/36969

**Comment by aikrahguzar** [comment]
> Or rather #36969

I tried, this time build progresses further but still fails with,
```
[spkg-install] make[5]: *** No rule to make target 'linux-arm-thr'.  Stop.
```
I am attaching the full log too: 
[tachyon-0.99.5.log.txt](https://github.com/user-attachments/files/16378101/tachyon-0.99.5.log.txt)

**Comment by aikrahguzar** [comment]
> @aikrahguzar - does your OS have a tachyon package ? If so, can you install it, and tell Sage to use it (running ./configure again).

Fedora doesn't seem to have a tachyon package. At least `dnf search tachyon` doesn't return anything.

> Or else you can install tachyon into /usr/local, and tell Sage to use it (running ./configure again).

I will try the manual source installation of tachyon later.

**Comment by dimpase** [comment]
this looks like tachyon needs a patch to  build on such a system.

Hopefully just a Makefile target, which would be the same as for an aarch64 linux, only named differently.

**Comment by aikrahguzar** [comment]
> this looks like tachyon needs a patch to build on such a system.
> 
> Hopefully just a Makefile target, which would be the same as for an aarch64 linux, only named differently.

Almost only result I could find for `linux-arm-thr` was [a sage patch for tachyon](https://raw.githubusercontent.com/sagemath/sage/develop/build/pkgs/tachyon/patches/Make-arch.patch). The patch doesn't apply but after clumsily messing about with the following allows tachyon to build:
[Make-arch.patch](https://github.com/user-attachments/files/16380189/Make-arch.patch)

The build is now continuing.

**Comment by dimpase** [comment]
@aikrahguzar - were you still using tachyon 0.98, but added this patch?

or you needed it with the branch updating to 0.99.5 ?

**Comment by aikrahguzar** [comment]
> @aikrahguzar - were you still using tachyon 0.98, but added this patch?
> 
> or you needed it with the branch updating to 0.99.5 ?

The later i.e. I added the patch on top of #36969

**Comment by dimpase** [comment]
> > @aikrahguzar - were you still using tachyon 0.98, but added this patch?
> > 
> > or you needed it with the branch updating to 0.99.5 ?
> 
> The later i.e. I added the patch on top of #36969

please add a review to #36969 mentioning this
