### ISSUE TITLE
Reduction of point Clusters

### ISSUE THREAD

**Issue by d99bb657-85da-4e6a-9cf4-9041874f39c0** [sagemath/sage#23737]
<div id="comment:0"></div>

This has been implemented as part of GSOC 2017 using  Michael Stoll's paper Reduction theory of Point Clusters in Projective Space.

CC:  @bhutz @pfili

Component: **dynamics**

_Issue created by migration from https://trac.sagemath.org/ticket/23737_

**Comment by d99bb657-85da-4e6a-9cf4-9041874f39c0** [comment]
Description changed:
``````diff
--- 
+++ 
@@ -1 +1 @@
-This has been implemented as part of GSOC 2017 using  Michale Stoll's paper Reduction theory of Point Clusters in Projective Space.
+This has been implemented as part of GSOC 2017 using  Michael Stoll's paper Reduction theory of Point Clusters in Projective Space.
``````

**Comment by guojing0** [comment]
See #32292
