### ISSUE TITLE
Python builds can fail if an old libpython is present in SAGE_LOCAL

### ISSUE THREAD

**Issue by embray** [sagemath/sage#24403]
<div id="comment:0"></div>

I think this is the cause of various reports like [ths one](https://groups.google.com/d/msg/sage-devel/l-d_AYiPzTw/6DjEQYvQBAAJ).

This can happen if, for some reason (there are various ways this could happen) the python spkg isn't installed, but an old version wasn't properly uninstalled either and an old libpython is still around that is binary incompatible with the new version.

What happens is that Python's main `setup.py` tests importing an extension module after building it.  However, because we link with `-Wl,-rpath=$SAGE_LOCAL/lib` the just-built Python interpreter links with the old libpython and ignores the `LD_LIBRARY_PATH` setting that Python adds in its `Makefile`.

One possible workaround would be to build with `--enable-new-dtags` but as #23161 seems to suggest this might be a problem?

Component: **build**

_Issue created by migration from https://trac.sagemath.org/ticket/24403_

**Comment by mkoeppe** [comment]
outdated
