### ISSUE TITLE
deprecate is_RealNumber, is_AlgebraicNumber, is_RealIntervalFieldElement, ...

### ISSUE THREAD

**Issue by videlec** [sagemath/sage#24525]
<div id="comment:0"></div>

We deprecate `is_RealNumber`, `is_ComplexNumber`, `is_AlgebraicNumber`, `is_RealIntervalFieldElement`, ...

`git grep 'is_.*Number('` and `git grep -E 'is_(Real|Complex).*Element[(]'` only shows a small number of uses.

We replace all uses either by 
- `isinstance` tests with the element class (if the module providing it is imported already) or
- `isinstance` tests of the parent with an abc defined in `sage.rings.abc`

See also:
- #24457
- discussion in [this sage-devel thread](https://groups.google.com/forum/#!topic/sage-devel/wEzb0awmyN0)

Depends on #32566

CC:  @tscrim

Component: **basic arithmetic**

_Issue created by migration from https://trac.sagemath.org/ticket/24525_

**Comment by videlec** [comment]
Description changed:
``````diff
--- 
+++ 
@@ -1 +1,3 @@
+As part of #24457 we deprecate `is_RealField` and `is_RealNumber` in favor of `isinstance`.
 
+See also the discussion in [this sage-devel thread](https://groups.google.com/forum/#!topic/sage-devel/wEzb0awmyN0)
``````

**Comment by mkoeppe** [comment]
Description changed:
``````diff
--- 
+++ 
@@ -1,3 +1,12 @@
-As part of #24457 we deprecate `is_RealField` and `is_RealNumber` in favor of `isinstance`.
+We deprecate `is_RealNumber`, `is_ComplexNumber`, `is_AlgebraicNumber`, `is_RealIntervalFieldElement`, ...
 
-See also the discussion in [this sage-devel thread](https://groups.google.com/forum/#!topic/sage-devel/wEzb0awmyN0)
+`git grep 'is_.*Number('` and `git grep -E 'is_(Real|Complex).*Element[(]'` only shows a small number of uses.
+
+We replace all uses either by 
+- `isinstance` tests with the element class (if the module providing it is imported already) or
+- `isinstance` tests of the parent with an abc defined in `sage.rings.abc`
+
+See also:
+- #24457
+- discussion in [this sage-devel thread](https://groups.google.com/forum/#!topic/sage-devel/wEzb0awmyN0)
+
``````
