### ISSUE TITLE
Some paths in R binaries still point to the build directory

### ISSUE THREAD

**Issue by edd8e884-f507-429a-b577-5d554626c0fe** [sagemath/sage#24675]
<div id="comment:0"></div>

Some paths in R binaries still point to the build directory, for example, in the file `$SAGE_ROOT/local/lib/R/bin/R` we can see `R_HOME_DIR="/opt/sagemath/sage-source/local/var/tmp/sage/build/r-3.4.3/src` which corresponds to the build dir (hence does not exist anymore once R is installed).

This causes issues, for example if we ask rstudio to use Sage's R. See [this sage-devel thread](https://groups.google.com/d/msg/sage-devel/rpTr7boUQbA/SRkFb7IbCAAJ).

CC:  @kiwifb @EmmanuelCharpentier

Component: **packages: standard**

Keywords: **sdl**

Reviewer: **François Bissey**

_Issue created by migration from https://trac.sagemath.org/ticket/24675_

**Comment by mkoeppe** [comment]
<div id="comment:5" align="right">comment:5</div>

outdated; we no longer have an R package

**Comment by kiwifb** [comment]
Reviewer: **François Bissey**
