### ISSUE TITLE
strongly regular tournaments

### ISSUE THREAD

**Issue by dimpase** [sagemath/sage#24682]
<div id="comment:0"></div>

This is a followup to #24045:

This is generalisation of Paley digraphs from #24045, due to A.Duval, [​J.Comb.Th. 47(1988) pp. 71-100](http://www.sciencedirect.com/science/article/pii/009731658890043X), nowadays called strongly regular digraph/tournament. We can use code in comment 14 of #24045, and Paley would be a subcase (in fact, this code will give you Paley if 4n-1 happens to be a prime power).

Component: **graph theory**

Author: **Matteo Cati**

_Issue created by migration from https://trac.sagemath.org/ticket/24682_

**Comment by MatteoCati** [comment]
Author: **Matteo Cati**

**Comment by MatteoCati** [comment]
Commit: **[`4cd5664`](https://github.com/sagemath/sagetrac-mirror/commit/4cd5664783cec72b06c23cf4be75821943ec7ece)**

**Comment by MatteoCati** [comment]
<div id="comment:2"></div>

New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/4cd5664783cec72b06c23cf4be75821943ec7ece"><code>4cd5664</code></a></td><td><code>Add construction of strongly regular digraph</code></td></tr></table>

**Comment by MatteoCati** [comment]
Branch: **[u/gh-MatteoCati/add_strongly_regular_digraph](https://github.com/sagemath/sagetrac-mirror/tree/u/gh-MatteoCati/add_strongly_regular_digraph)**

**Comment by dcoudert** [comment]
<div id="comment:3" align="right">comment:3</div>

You assume the existence of a unique strongly regular digraph of order n. Is it the case ?

- `n+1` -> `n + 1`
- `f'Strongly regular digraph'` -> `'Strongly regular digraph'`

**Comment by dimpase** [comment]
<div id="comment:4" align="right">comment:4</div>

no, they are usually not unique (IIRC, already for 19 nodes it's not the case)

**Comment by dimpase** [comment]
<div id="comment:5" align="right">comment:5</div>

But where do you see a uniqueness promise? The docs say 

```
Return a Strongly Regular digraph with `n` vertices.`
```

**Comment by dcoudert** [comment]
<div id="comment:6" align="right">comment:6</div>

I haven't seen any promise on the uniqueness. I just observed that the construction always returns the same digraph of order n. 
You could add in the documentation for future work to add other constructions.

**Comment by dimpase** [comment]
<div id="comment:7" align="right">comment:7</div>

yes, it's the same for many other combinatorics and graphs constructions.
E.g. if you ask for a Hadamard matrix of order n you get the 1st found, or if you ask got a strongly regular graph with the given parameters you get the 1st founds, same for block designs, orthogonal arrays, etc.

(the trac is read-only for all, except me, now, we'll get back to this on [GitHub](../wiki/GitHub) :-))

**Comment by dimpase** [comment]
<div id="comment:8" align="right">comment:8</div>

test+1

**Comment by mkoeppe** [comment]
Removed branch from the issue description because it has been replaced by PR #34986
