### ISSUE TITLE
Add is_supergreedy() to linear extension

### ISSUE THREAD

**Issue by f29946bc-ee7b-48cd-9abc-3445948c551d** [sagemath/sage#24700]
<div id="comment:0"></div>

Add a function to check if a linear extension of a poset is supergreedy. (Compare to #24632.)

Component: **combinatorics**

Author: **Rohan Garg**

Reviewer: **Jori Mäntysalo**

_Issue created by migration from https://trac.sagemath.org/ticket/24700_

**Comment by Sandstorm831** [comment]
<div id="comment:2"></div>

New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/86fc48deddc00b508b5c75582b876315771eae49"><code>86fc48d</code></a></td><td><code>added is_supergreedy() function</code></td></tr></table>

**Comment by Sandstorm831** [comment]
Branch: **[u/gh-Sandstorm831/24700](https://github.com/sagemath/sagetrac-mirror/tree/u/gh-Sandstorm831/24700)**

**Comment by Sandstorm831** [comment]
Commit: **[`86fc48d`](https://github.com/sagemath/sagetrac-mirror/commit/86fc48deddc00b508b5c75582b876315771eae49)**

**Comment by Sandstorm831** [comment]
<div id="comment:3" align="right">comment:3</div>

I have added the is_supergreedy() function in the linear_extensions.py file, and would be glad for any reviews

**Comment by f29946bc-ee7b-48cd-9abc-3445948c551d** [comment]
<div id="comment:4" align="right">comment:4</div>

This could should have crosslinks is_greedy() <-> is_supergreedy().

Currently documentation for is_greedy has a paragraph "Informally said...". I suggest adding similar to this, like

Informally said a linear extension is supergreedy if it “always goes up when possible and returns down as less as possible”.

**Comment by f29946bc-ee7b-48cd-9abc-3445948c551d** [comment]
<div id="comment:5" align="right">comment:5</div>

Maybe I don't understand this. Example in the code lists all linear extensions of the Pentagon poset. But at least some linear extension must be supergreedy. I think the smallest example of greedy but no supergreedy extension can be found in the 4-element poset "a V letter and a lone element".

But it has been a while from the time I look about posets.

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
<div id="comment:6"></div>

Branch pushed to git repo; I updated commit sha1. New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/cef5e45ab22d95b6e313cf3e40dcd7cf3dab44b9"><code>cef5e45</code></a></td><td><code>implemented diff algo, for borderline cases</code></td></tr></table>

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
Changed commit from **[`86fc48d`](https://github.com/sagemath/sagetrac-mirror/commit/86fc48deddc00b508b5c75582b876315771eae49)** to **[`cef5e45`](https://github.com/sagemath/sagetrac-mirror/commit/cef5e45ab22d95b6e313cf3e40dcd7cf3dab44b9)**

**Comment by Sandstorm831** [comment]
<div id="comment:7" align="right">comment:7</div>

I have changed the algorithm, last algorithm was missing some borderline cases, which is now fixed. I had tried to find, but only informal definition I could get is set of supergreedy linear extension is exactly same as that of depth first search set. In pentagon poset, although there are 2 sequences are possible which are supergreedy but those sequences are not linear extensions, so that doesn't appear when is_supergreedy() is called. I don't know about the minimum element poset where is_greedy but not supergreedy case appear, but during testing, there are indeed cases when linear extension is supergreedy and not greedy. Also resources of supergreedy is very much limited, I can find only one paper where I can got the definition, after that 2-3 papers just copied the same definition from the original one, so lack of materials also made things tricky, you can find the original paper [https://trotter.math.gatech.edu/papers/66.pdf](https://trotter.math.gatech.edu/papers/66.pdf) .please let me know, if there changes to do.

**Comment by f29946bc-ee7b-48cd-9abc-3445948c551d** [comment]
<div id="comment:9" align="right">comment:9</div>

I think one can write an informal description without reference to an article.

The codes seems to get stuck with

`for le in Poset({1: [2, 3], 4: []}).linear_extensions(): print (le, le.is_supergreedy())`

Please check with something like for P in Posets(): print(len([le for le in P.linear_extension() if le.is_supergreedy()]) or similar.

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
Changed commit from **[`cef5e45`](https://github.com/sagemath/sagetrac-mirror/commit/cef5e45ab22d95b6e313cf3e40dcd7cf3dab44b9)** to **[`200441d`](https://github.com/sagemath/sagetrac-mirror/commit/200441dae09c8693f851178d6c28df6d80b3cc68)**

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
<div id="comment:10"></div>

Branch pushed to git repo; I updated commit sha1. New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/200441dae09c8693f851178d6c28df6d80b3cc68"><code>200441d</code></a></td><td><code>correcting function for disjoint set of points</code></td></tr></table>

**Comment by Sandstorm831** [comment]
<div id="comment:11" align="right">comment:11</div>

Thanks for the pointing out the error, My algorithm didn't account for disjointed points altogether, so have to change somethings, and also had to define a helper function named complete_supergreedy() for the original function. Please review and let me know if there is any other changes. As far as I know for some informal definition, then I can't say anything concretely as greedy is different from supergreedy so I am also not sure, And apologies for the delay as the this function is somewhat tricky to implement, so it took some time of me.

**Comment by f29946bc-ee7b-48cd-9abc-3445948c551d** [comment]
<div id="comment:12" align="right">comment:12</div>

Now it does not stuck, but says that every linear extension of `Poset({1: [2, 3], 4: []})` is supergreedy, even those that are not greedy. Try

```
sage: P = Poset({1: [2, 3], 4: []})
sage: for le in P.linear_extensions(): print (le, le.is_greedy(), le.is_supergreedy())
```

**Comment by mantepse** [comment]
<div id="comment:13" align="right">comment:13</div>

once you are done it would be great if you could compare with the data (not the code!) recorded at http://www.findstat.org/StatisticsDatabase/St001106/

**Comment by f29946bc-ee7b-48cd-9abc-3445948c551d** [comment]
<div id="comment:14" align="right">comment:14</div>

For testing might be easier to first make #34933.

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
Changed commit from **[`200441d`](https://github.com/sagemath/sagetrac-mirror/commit/200441dae09c8693f851178d6c28df6d80b3cc68)** to **[`5cd17f1`](https://github.com/sagemath/sagetrac-mirror/commit/5cd17f1a3c787cf4739667343b025dce369332d3)**

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
<div id="comment:15"></div>

Branch pushed to git repo; I updated commit sha1. New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/5cd17f1a3c787cf4739667343b025dce369332d3"><code>5cd17f1</code></a></td><td><code>correcting function</code></td></tr></table>

**Comment by Sandstorm831** [comment]
<div id="comment:16" align="right">comment:16</div>

Thanks Jori for the help. [http://www.findstat.org/StatisticsDatabase/St001106/](http://www.findstat.org/StatisticsDatabase/St001106/) helped me a lot to figure out original meaning of supergreedy as mentioned in article. This time I checked my function extensively on this dataset, and glad to tell all of them passed. please look at my code, and would be glad for reviews.

**Comment by f29946bc-ee7b-48cd-9abc-3445948c551d** [comment]
<div id="comment:18" align="right">comment:18</div>

I will read the code later. I guess this works now; FYI here are my test codes:

```
for i in range(9):
    for P in Posets(i):
        a = sum(1 for le in P.linear_extensions() if le.is_supergreedy())
        b = sum(1 for _ in P._hasse_diagram.supergreedy_linear_extensions_iterator())
        if a != b:
            P.show()
            break
    else:
        print("OK %s" % i)
```

```
for i in range(100):
    P = posets.RandomPoset(10, 0.15)
    for le_ in P._hasse_diagram.supergreedy_linear_extensions_iterator():
        le = P.linear_extension([P[e] for e in le_])
        if not le.is_supergreedy():
            P.show()
            print(le)
            break
    else:
        print("OK")
```

```
for i in range(100):
    P = posets.RandomPoset(10, 0.15)
    a = sum(1 for le in P.linear_extensions() if le.is_supergreedy())
    b = sum(1 for _ in P._hasse_diagram.supergreedy_linear_extensions_iterator())
    if a != b:
        P.show()
        break
    print(i)
```

**Comment by f29946bc-ee7b-48cd-9abc-3445948c551d** [comment]
<div id="comment:19" align="right">comment:19</div>

Html documentation does not build nicely. Needs an empty line after `EXAMPLES::`. And yes, this is irritating.

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
Changed commit from **[`5cd17f1`](https://github.com/sagemath/sagetrac-mirror/commit/5cd17f1a3c787cf4739667343b025dce369332d3)** to **[`1406cdc`](https://github.com/sagemath/sagetrac-mirror/commit/1406cdc3a3691819a3081bf737275845c7c6cc4b)**

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
<div id="comment:20"></div>

Branch pushed to git repo; I updated commit sha1. New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/1406cdc3a3691819a3081bf737275845c7c6cc4b"><code>1406cdc</code></a></td><td><code>documentation changes</code></td></tr></table>

**Comment by Sandstorm831** [comment]
<div id="comment:21" align="right">comment:21</div>

Sorry for the inconvenience caused sir

**Comment by f29946bc-ee7b-48cd-9abc-3445948c551d** [comment]
<div id="comment:22" align="right">comment:22</div>

No more complains.

**Comment by f29946bc-ee7b-48cd-9abc-3445948c551d** [comment]
Author: **Rohan Garg**

**Comment by f29946bc-ee7b-48cd-9abc-3445948c551d** [comment]
Reviewer: **Jori Mäntysalo**

**Comment by f29946bc-ee7b-48cd-9abc-3445948c551d** [comment]
<div id="comment:23" align="right">comment:23</div>

(To clarify "And yes, this is irritating.": I meant that the docbuild system is irritating, it is very easy to have documentation compiled but with wrong indentation or similar.)

**Comment by Sandstorm831** [comment]
<div id="comment:24" align="right">comment:24</div>

ok, got it. Sir, Can you suggest more few more tickets to work upon. I also have 2 more tickets I am working upon and needs review so it would be great If you can give review on those also. 33548 and 32439.

**Comment by f29946bc-ee7b-48cd-9abc-3445948c551d** [comment]
<div id="comment:25" align="right">comment:25</div>

For 33548 no, I do not know matrices good enough. For 32439 maybe, but I suggest asking for someone else.

**Comment by Sandstorm831** [comment]
<div id="comment:26" align="right">comment:26</div>

Ok, thanks sir

**Comment by vbraun** [comment]
I'm getting 
```
sage -t --long --warn-long 37.4 --random-seed=123 src/sage/combinat/posets/linear_extensions.py
**********************************************************************
File "src/sage/combinat/posets/linear_extensions.py", line 283, in sage.combinat.posets.linear_extensions.?.is_supergreedy
Failed example:
    for l in Q.linear_extensions():
        if not l.is_supergreedy():
            print(l)
Expected:
    [0, 1, 2, 3, 4]
    [0, 2, 3, 1, 4]
    [0, 2, 1, 3, 4]
Got:
    [0, 2, 1, 3, 4]
**********************************************************************
1 item had failures:
   1 of   9 in sage.combinat.posets.linear_extensions.?.is_supergreedy
    [174 tests, 1 failure, 0.16 s]
----------------------------------------------------------------------
sage -t --long --warn-long 37.4 --random-seed=123 src/sage/combinat/posets/linear_extensions.py  # 1 doctest failed
----------------------------------------------------------------------
```
Since we just moved to github please create a pull request here to continue working on this ticket

**Comment by Sandstorm831** [comment]
Yea sir, I have already opened a PR and also corrected the issue. Thankyou for your response.

**Comment by Sandstorm831** [comment]
Yes sir, I have already opened a PR and also corrected the issue. Thankyou for your response.

**Comment by mkoeppe** [comment]
Removed branch from the issue description; replaced by PR #34970.
