### ISSUE TITLE
ratpoints fails to build with clang on ubuntu

### ISSUE THREAD

**Issue by simon-king-jena** [sagemath/sage#24708]
<div id="comment:0"></div>

I attempted to build Sage with clang, with `CC=clang CXX="clang++ -I/usr/include/libcxxabi/ --stdlib=libc++" make`. Note that fpylll does not complain (see #24707).

I get two failing packages: sagelib (see #24705) and ratpoints. Here is the 
[ratpoints log](http://users.minet.uni-jena.de/cohomology/logs/ratpoints-2.1.3.p4.log) I guess the ratpoints developers should be contacted, but I don't know how.

Upstream: **None of the above - read trac for reasoning.**

Component: **packages: standard**

Keywords: **ratpoints clang**

Reviewer: **Dima Pasechnik**

_Issue created by migration from https://trac.sagemath.org/ticket/24708_

**Comment by mkoeppe** [comment]
<div id="comment:12" align="right">comment:12</div>

outdated - the `ratpoints` package has been removed

**Comment by dimpase** [comment]
<div id="comment:13" align="right">comment:13</div>

removed in #24531, indeed

**Comment by dimpase** [comment]
Reviewer: **Dima Pasechnik**
