### ISSUE TITLE
Cygwin: static resources for HTML docs missing

### ISSUE THREAD

**Issue by embray** [sagemath/sage#25089]
<div id="comment:0"></div>

There's a long-standing problem on Cygwin that the built HTML docs don't work correctly locally, because various common static resources (CSS, JS, etc.) can't be found.  This is because the Sage multi-doc builder hacks things a bit so that individual sub-docs don't have their own copies of the `_static` dir, but rather symlink to a common `_static` dir, presumably to save space on duplicate files.

Unfortunately, this is broken on Windows, since native Windows apps (i.e. the browser) don't understand Cygwin symlinks.

This could be worked around, perhaps, by making hard links instead.

Component: **porting: Cygwin**

Keywords: **docbuild**

_Issue created by migration from https://trac.sagemath.org/ticket/25089_

**Comment by mkoeppe** [comment]
dup of #35538
