### ISSUE TITLE
Add spkg-legacy-uninstall scripts for most standard packages

### ISSUE THREAD

**Issue by embray** [sagemath/sage#25140]
<div id="comment:0"></div>

This is a followup to #25139 and represents work that was originally done in #22510 to convert most packages to use `spkg-legacy-uninstall` and remove uninstall-related commands from their `spkg-install` scripts.

This work was brought over from an older branch and still needs some adjustment: It should incorporate the changes from the #24024 metaticket which conflict with some of these changes.  There are also some additional optional and experimental packages (and maybe a couple standard packages) that still need to be updated as well.

Probably won't bother with that until and unless #25139 is approved of in some form that still includes the `spkg-legacy-uninstall` feature.

---

To summarize what this is about: Part of the goal in implementing the new installation/uninstallation system for packages is that `spkg-install` should, ideally, not modify `$SAGE_LOCAL` in any way, at least for packages that support `DESTDIR`-based installation.  This allows more separation from the building of packages from their runtime installation target.

However, many packages' `spkg-install` or `spkg-build` include commands (mostly in the form of `rm -rf`'s) to clean up files from previous installs of those packages.  This is no longer necessary for new-style package installations that track exactly what files are installed by a package.  But it is still necessary when upgrading from old installs of packages that don't have a file manifest.  This is what the `spkg-legacy-uninstall` script is for.  It's just taking the `rm -rf`'s from `spkg-install` and moving it into a separate script that is called by the uninstaller if it doesn't have a file manifest for that package.

So this ticket is just creating the `spkg-legacy-uninstall` for many packages that already have `DESTDIR` support.

Component: **build**

Keywords: **uninstall**

Author: **Erik Bray**

Branch/Commit: **[u/embray/build/spkg-uninstall/legacy-uninstallers](https://github.com/sagemath/sagetrac-mirror/tree/u/embray/build/spkg-uninstall/legacy-uninstallers) @ [`e2d2b01`](https://github.com/sagemath/sagetrac-mirror/commit/e2d2b01f15e25c24334d8e6f110c3302d41cdd6f)**

Reviewer: **Julian Rüth**

_Issue created by migration from https://trac.sagemath.org/ticket/25140_

**Comment by embray** [comment]
Description changed:
``````diff
--- 
+++ 
@@ -3,3 +3,11 @@
 This work was brought over from an older branch and still needs some adjustment: It should incorporate the changes from the #24024 metaticket which conflict with some of these changes.  There are also some additional optional and experimental packages (and maybe a couple standard packages) that still need to be updated as well.
 
 Probably won't bother with that until and unless #25139 is approved of in some form that still includes the `spkg-legacy-uninstall` feature.
+
+---
+
+To summarize what this is about: Part of the goal in implementing the new installation/uninstallation system for packages is that `spkg-install` should, ideally, not modify `$SAGE_LOCAL` in any way, at least for packages that support `DESTDIR`-based installation.  This allows more separation from the building of packages from their runtime installation target.
+
+However, many packages' `spkg-install` or `spkg-build` include commands (mostly in the form of `rm -rf`'s) to clean up files from previous installs of those packages.  This is no longer necessary for new-style package installations that track exactly what files are installed by a package.  But it is still necessary when upgrading from old installs of packages that don't have a file manifest.  This is what the `spkg-legacy-uninstall` script is for.  It's just taking the `rm -rf`'s from `spkg-install` and moving it into a separate script that is called by the uninstaller if it doesn't have a file manifest for that package.
+
+So this ticket is just creating the `spkg-legacy-uninstall` for many packages that already have `DESTDIR` support.
``````

**Comment by mkoeppe** [comment]
Different versions of the `spkg-legacy-uninstall` scripts were added to Sage in 
- cb965d214cfe4c12098f1644195c0886bdeb6f21 for `boost_cropped`
- 6a2596e9773d89010184d0235cf54d28eb500226 for `ecl`
- 8635c525f1e03a465b80f8dc074000677053472e for `gfan`
- 87c694f059e839a4bb12db80037f3c4398b56c2b for `jmol`
- 6c886823bb09b90e8b5283ef42c11da461735b03 for `libgd`
- 0f3dab964e4da4926cc1cb371b3b2272663301aa for `numpy`
- 0157c38bcd365310e822cfb63557d8e88bb04507 for `python3`
