### ISSUE TITLE
Add ability to generate graphs based on correlations of sequences

### ISSUE THREAD

**Issue by rkingan** [sagemath/sage#25933]
<div id="comment:0"></div>

Given a list of labeled real-valued vectors and a significance level `alpha`, generate a graph with vertices corresponding to the list's labels where two vertices are connected by an edge if the corresponding vectors have a correlation coefficient that is positive or negative at the specified significance level. An object creating the graph should support the `plot` method, which will plot the generated graph using a circular layout.

CC:  @dcoudert

Component: **graph theory**

Keywords: **sagedays@icerm**

Author: **Robert Kingan**

_Issue created by migration from https://trac.sagemath.org/ticket/25933_

**Comment by 701607be-2c9c-4f1e-9069-e5945d2c495d** [comment]
Commit: **[`abc6100`](https://github.com/sagemath/sagetrac-mirror/commit/abc6100c7802997b69421a8b1dee1c4cddafbea1)**

**Comment by 701607be-2c9c-4f1e-9069-e5945d2c495d** [comment]
<div id="comment:4" align="right">comment:4</div>

I've made a very bare-bones start on this but please tear it apart.

One note about my plot() implementation - the graph.plot function invokes the constructor at `.__class__()` about 10 methods deep (specifically, at the start of `GenericGraph._subgraph_by_adding`).

In the plot method I've put in a hack that works around it, 

```
def plot(self):

    self.__class__=Graph
    p=self.plot()
    self.__class__=CorrelationGraph

    return p
```


but I think this is a symptom of a larger issue. Making assumptions about the arguments of the class constructor of a passed object feels like poor design, and we should be able to inherit the plot method with any class, without restrictions on the shape of said class' constructor.

If anyone can find a better workaround please let me know, this is the tidiest one I've found.

---
New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/abc6100c7802997b69421a8b1dee1c4cddafbea1"><code>abc6100</code></a></td><td><code>initial implementation start</code></td></tr></table>

**Comment by 701607be-2c9c-4f1e-9069-e5945d2c495d** [comment]
Changed branch from **[correlation-graph](https://github.com/sagemath/sagetrac-mirror/tree/correlation-graph)** to **[u/gh-Bruno-TT/correlation-graph](https://github.com/sagemath/sagetrac-mirror/tree/u/gh-Bruno-TT/correlation-graph)**

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
<div id="comment:5"></div>

Branch pushed to git repo; I updated commit sha1. New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/2798d32e656bcda32402fe946a3352af5a2654ed"><code>2798d32</code></a></td><td><code>base test fix</code></td></tr></table>

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
Changed commit from **[`abc6100`](https://github.com/sagemath/sagetrac-mirror/commit/abc6100c7802997b69421a8b1dee1c4cddafbea1)** to **[`2798d32`](https://github.com/sagemath/sagetrac-mirror/commit/2798d32e656bcda32402fe946a3352af5a2654ed)**

**Comment by dcoudert** [comment]
<div id="comment:7" align="right">comment:7</div>

Several comments:
- graph generators are usually placed in `src/sage/graphs/generators/` and made accessible as `graphs.<TAB>`
- Your method must be commented. I'm not sure to understand the steps.
- If you think the current design of the plot method must be improved, please open a dedicated ticket

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
Changed commit from **[`2798d32`](https://github.com/sagemath/sagetrac-mirror/commit/2798d32e656bcda32402fe946a3352af5a2654ed)** to **[`ee12eac`](https://github.com/sagemath/sagetrac-mirror/commit/ee12eacbb882a55720781279c8fc846023aab6df)**

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
<div id="comment:8"></div>

Branch pushed to git repo; I updated commit sha1. New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/ee12eacbb882a55720781279c8fc846023aab6df"><code>ee12eac</code></a></td><td><code>changed class to generator method + tab completion</code></td></tr></table>

**Comment by dcoudert** [comment]
<div id="comment:9" align="right">comment:9</div>

Better this way.

Note that the current doctest is not working since parameter `include_anticorrelation` is required. You should certainly set its default value and add doctests using it.

Coding style:
- `boolean_adjacency_matrix = (corrs>=alpha)` -> `boolean_adjacency_matrix = corrs >= alpha`. I don't think you need the parathenses.
- `adjacency_matrix=Matrix(boolean_adjacency_matrix.astype(int))` -> `adjacency_matrix = Matrix(boolean_adjacency_matrix.astype(int))`

and of course add the documentation.

**Comment by Bruno-TT** [comment]
PR here: #35009 

I've changed the above as per your suggestions David, and added some documentation

**Comment by mkoeppe** [comment]
Removed branch from issue description; replaced by PR #35009
