### ISSUE TITLE
Better error reporting for failed CI builds

### ISSUE THREAD

**Issue by saraedum** [sagemath/sage#26085]
<div id="comment:0"></div>

Currently, there are a bunch of confusing error codes that can show up at the end of CI builds. It would be nice to translate them to something more readable, e.g.,

* 137: the machine was preempted, please try again.
* timeout: there were too many SPKG changes and you are running on shared infrastructure that cannot handle that...
* no space left on device: essentially the same
* ...

Depends on #24655

CC:  @embray @slel

Component: **build**

Keywords: **ContinuousIntegration**

Author: **Julian Rüth**

_Issue created by migration from https://trac.sagemath.org/ticket/26085_

**Comment by mkoeppe** [comment]
outdated
