### ISSUE TITLE
add SIXEL support for terminal display

### ISSUE THREAD

**Issue by fchapoton** [sagemath/sage#26544]
<div id="comment:0"></div>

see https://groups.google.com/d/msg/sage-devel/rJ_W0EgRLMg/5B5UU2VyAAAJ

for a discussion of this.

Python interface there: https://github.com/saitoha/PySixel

and

https://github.com/saitoha/libsixel

See also: https://github.com/koppa/matplotlib-sixel

CC:  @embray @slel

Component: **interfaces**

_Issue created by migration from https://trac.sagemath.org/ticket/26544_

**Comment by fchapoton** [comment]
Description changed:
``````diff
--- 
+++ 
@@ -3,3 +3,7 @@
 for a discussion of this.
 
 Python interface there: https://github.com/saitoha/PySixel
+
+and
+
+https://github.com/saitoha/libsixel
``````

**Comment by seblabbe** [comment]
Description changed:
``````diff
--- 
+++ 
@@ -7,3 +7,5 @@
 and
 
 https://github.com/saitoha/libsixel
+
+See also: https://github.com/koppa/matplotlib-sixel
``````

**Comment by fchapoton** [comment]
So I think we can close this, and let people try to use Euporie with a sagemath kernel if they want.

**Comment by mkoeppe** [comment]
Nice find.
