### ISSUE TITLE
Remove bad mathjax symlink and bad mathjax directories

### ISSUE THREAD

**Issue by jhpalmieri** [sagemath/sage#26612]
<div id="comment:0"></div>

The problem reported in #26152 has returned, it seems. As a result, users may end up with a symlink `SAGE_SHARE/mathjax/mathjax` pointing to its parent directory, and this ends up producing a directory `SAGE_DOC/html/en/reference/_static/mathjax` which contains a subdirectory `mathjax` which also contains a subdirectory `mathjax`, etc., hence needlessly using gigabytes of disk space. Let's get rid of these problematic files.

Depends on #26641

Component: **documentation**

Author: **John Palmieri**

Branch/Commit: **[u/jhpalmieri/no-mathjax](https://github.com/sagemath/sagetrac-mirror/tree/u/jhpalmieri/no-mathjax) @ [`ae3812d`](https://github.com/sagemath/sagetrac-mirror/commit/ae3812d060e0df45073d17ff928dcc34b8fcc0eb)**

_Issue created by migration from https://trac.sagemath.org/ticket/26612_

**Comment by kwankyu** [comment]
This issue does not exist, and will never happen again after #36098.
