### ISSUE TITLE
link sphinx docs of Sage components in reference manual

### ISSUE THREAD

**Issue by dimpase** [sagemath/sage#27164]
<div id="comment:0"></div>

As Sage gets increasingly modular, it becomes important (also for the doc website, currently it has broken links to e.g. sagenb interacts in the reference manual) that these spun off docs are still easy to find.

In fact, sphinx has an extension to link different projects, 
see http://www.sphinx-doc.org/en/master/usage/extensions/intersphinx.html

so this appears quite doable. 
Here is an incomplete docs to link

* sagetex
* sagenb  (see #25382)
* cypari
* cysignals
* pplpy (not yet in Sage, see #23024)

CC:  @embray @kiwifb @antonio-rojas @timokau @infinity0

Component: **documentation**

_Issue created by migration from https://trac.sagemath.org/ticket/27164_

**Comment by videlec** [comment]
Description changed:
``````diff
--- 
+++ 
@@ -10,6 +10,6 @@
 * sagenb  (see #25382)
 * cypari
 * cysignals
-* pyppl (not yet in Sage, see #23024)
+* pplpy (not yet in Sage, see #23024)
 
 
``````
