### ISSUE TITLE
Docker images for Sage missing make

### ISSUE THREAD

**Issue by embray** [sagemath/sage#27288]
<div id="comment:0"></div>

For some reason the official `sagemath/sagemath` images don't include `make`, which at a minimum is necessary for installing optional packages within the image (which should be considered essential functionality).

CC:  @saraedum @JohnCremona @slel

Component: **docker**

Author: **Erik Bray**

Branch/Commit: **[u/embray/docker/ticket-27288](https://github.com/sagemath/sagetrac-mirror/tree/u/embray/docker/ticket-27288) @ [`d4ac0b4`](https://github.com/sagemath/sagetrac-mirror/commit/d4ac0b49daec7e92a6a9ae44a34cbeb752f40494)**

_Issue created by migration from https://trac.sagemath.org/ticket/27288_

**Comment by mkoeppe** [comment]
outdated
