### ISSUE TITLE
Implement Decorated Permutations

### ISSUE THREAD

**Issue by 1adc0eef-8957-46d9-975b-2dd71dfbd9ba** [sagemath/sage#27286]
<div id="comment:0"></div>

Implementing a class corresponding to decorated permutations (permutations in which non-fixed points are assigned one of two possible colors). 

Originally defined by Postnikov in 'Total Positivity, Grassmannians, and Networks' as one of many objects in bijection with totally nonegative cells of the Grassmannian (positively oriented matroids, le-diagrams, Grassman necklaces, equivalence classes of plabic graphs).

CC:  @DanielTamayo22 @tscrim

Component: **combinatorics**

Reviewer: **Travis Scrimshaw**

_Issue created by migration from https://trac.sagemath.org/ticket/27286_

**Comment by mantepse** [comment]
<div id="comment:9" align="right">comment:9</div>

I think that most of this is obsolete, there is a class `DecoratedPermutation` and a class `ColeredPermutations` already.  It remains to check whether any features in this branch should be cherry-picked.

**Comment by tscrim** [comment]
Changed branch from **[u/gh-DanielTamayo22/positroid](https://github.com/sagemath/sagetrac-mirror/tree/u/gh-DanielTamayo22/positroid)** to none

**Comment by tscrim** [comment]
Changed commit from **[`9afa309`](https://github.com/sagemath/sagetrac-mirror/commit/9afa309a1a4e45e0a35870eec5fb5b92dbb41c0a)** to none

**Comment by tscrim** [comment]
Reviewer: **Travis Scrimshaw**

**Comment by tscrim** [comment]
<div id="comment:10" align="right">comment:10</div>

I think your code for decorated permutations already does everything that is provided by this code, most of which is just copied from `ColoredPermutation[s]`. I think we can close this as a duplicate.
