### ISSUE TITLE
Flint fails to install with gmp from system

### ISSUE THREAD

**Issue by timokau** [sagemath/sage#27708]
<div id="comment:0"></div>

Trying to build sage using its own build system with gmp present results in:

```
Package 'flint' is currently not installed
No legacy uninstaller found for 'flint'; nothing to do
Configuring FLINT.
Invalid GMP directory
```

Flint fails to build. Looking into its configure script, it looks for GMP in `/usr/local` or whatever was passed as `--with-gmp` at configure time. However gmp is located in `/usr`, not `/usr/local`. Sage passes the contents of the `SAGE_GMP_PREFIX` variable to `--with-gmp`, but according to the install logs that environment variable is empty (while `SAGE_GMP_INCLUDE` is set correctly):

```
SAGE_EXTCODE=/home/timo/repos/sage/local/share/sage/ext
SAGE_GMP_INCLUDE=///usr/include
SAGE_GMP_PREFIX=
SAGE_LOCAL=/home/timo/repos/sage/local
SAGE_LOGS=/home/timo/repos/sage/logs/pkgs
```

CC:  @embray @dimpase @slel @wbhart @zerline

Component: **build: configure**

_Issue created by migration from https://trac.sagemath.org/ticket/27708_

**Comment by mkoeppe** [comment]
outdated
