### ISSUE TITLE
latex representation of lazy power series

### ISSUE THREAD

**Issue by dkrenn** [sagemath/sage#27806]
<div id="comment:0"></div>

```
sage: P.<z> = LazyPowerSeriesRing(QQ)
sage: C = P()
sage: C.define(1 + z*C^2)
sage: latex(C)
```
returns

```
\text{\texttt{1{ }+{ }z{ }+{ }2*z{\char`\^}2{ }+{ }5*z{\char`\^}3{ }+{ }14*z{\char`\^}4{ }+{ }42*z{\char`\^}5{ }+{ }132*z{\char`\^}6{ }+{ }429*z{\char`\^}7{ }+{ }1430*z{\char`\^}8{ }+{ }4862*z{\char`\^}9{ }+{ }16796*z{\char`\^}10{ }+{ }O(x{\char`\^}11)}}
```
which is not the expected LaTeX-representation. One would expect

```
1 + z + 2z^2 + ...
```

(Reported by T.W., 2019-05-09)

CC:  @sagetrac-twiklund

Component: **misc**

_Issue created by migration from https://trac.sagemath.org/ticket/27806_

**Comment by mantepse** [comment]
This works now, since the lazy power series ring was reimplemented from scratch.
