### ISSUE TITLE
Use SageMathCell to embed interacts examples in the docs

### ISSUE THREAD

**Issue by embray** [sagemath/sage#28246]
<div id="comment:0"></div>

The official [Interact Quickstart](https://doc.sagemath.org/html/en/prep/Quickstarts/Interact.html) in the documentation lacks example output, making it a bit unimpressive to readers, who might not otherwise be sufficiently motivated to try it themselves.

The page *does* link to http://wiki.sagemath.org/interact, which shows an interactive example in [SageMathCell](../wiki/SageMathCell), but it would be better if the actual examples in the docs worked interactively as well.

I think it would be straightforward to add a special Sphinx directive for embedding an interactive cell.  Obviously, it would only work when viewing the docs with an internet connection.  For when it doesn't work, it would also be nice if the directive could be supplied a fallback screenshot (ideally, and interactive GIF).  These fallback screenshots would have to be supplied manually, unfortunately.

Adding a special directive would be ideal since it would make it easier to provide interact examples in other parts of the docs as well.

An even more sophisticated possibility would be a button to turn any examples in the docs into interactive cells.  I feel like this has been tried before, but I don't remember where I've seen it...

CC:  @kwankyu

Component: **documentation**

_Issue created by migration from https://trac.sagemath.org/ticket/28246_

**Comment by mkoeppe** [comment]
> #33320 now fulfills the wishes of this ticket albeit with jupyter-sphinx rather than sagemath-cell.

Hence closing
