### ISSUE TITLE
Implement Symmetry Classes of Plane Partitions

### ISSUE THREAD

**Issue by 1adc0eef-8957-46d9-975b-2dd71dfbd9ba** [sagemath/sage#28244]
<div id="comment:0"></div>

Create classes for the different symmetry classes of plane partitions (Cyclically symmetric, Totally Symmetric, etc.), along with methods taking elements in these symmetry classes to an object in a fundamental domain (usually an order ideal in some associated poset). 

CC:  @jessicapalencia @tscrim @mantepse

Component: **combinatorics**

Keywords: **days99, IMA Coding Sprint**

Author: **Kevin Dilks, Spencer Cook, Jessica Striker**

Branch/Commit: **[public/combinat/symmetry_classes_plane_partitions-28244](https://github.com/sagemath/sagetrac-mirror/tree/public/combinat/symmetry_classes_plane_partitions-28244) @ [`a3c1c58`](https://github.com/sagemath/sagetrac-mirror/commit/a3c1c586e5bdc71a727f3ea03c4ee0da062bc711)**

Reviewer: **Travis Scrimshaw**

_Issue created by migration from https://trac.sagemath.org/ticket/28244_

**Comment by 6f4e04c0-2bd7-49f3-b83f-e15e1c4a8514** [comment]
<div id="comment:60" align="right">comment:60</div>

Any update? Wondering what is left to do to finish this.

**Comment by tscrim** [comment]
<div id="comment:61" align="right">comment:61</div>

I think all of my comments were addressed, but I am not 100% certain from the commits. This will need a rebasing to the latest `develop` and any commented out code should be removed. Otherwise it should be good to go.

**Comment by 6f4e04c0-2bd7-49f3-b83f-e15e1c4a8514** [comment]
<div id="comment:62" align="right">comment:62</div>

Hi Travis, Can you finish this or recommend someone who could? I don't have time at the moment, or a working development version of Sage. But I have gotten some requests from Sage users for this functionality!

**Comment by tscrim** [comment]
Changed commit from **[`40842e8`](https://github.com/sagemath/sagetrac-mirror/commit/40842e8e14080fff7422d902071de93051dc4820)** to **[`77a5b52`](https://github.com/sagemath/sagetrac-mirror/commit/77a5b52bf50f0953dea2f1c57f7de6c61d7f50da)**

**Comment by tscrim** [comment]
Changed branch from **[u/kdilks/SymPP](https://github.com/sagemath/sagetrac-mirror/tree/u/kdilks/SymPP)** to **[public/combinat/symmetry_classes_plane_partitions-28244](https://github.com/sagemath/sagetrac-mirror/tree/public/combinat/symmetry_classes_plane_partitions-28244)**

**Comment by tscrim** [comment]
<div id="comment:63" align="right">comment:63</div>

I did what I could, but it should be good to go. There are probably still some other cleanup stuff to do wrt to the code style, but it now works for me.

---
New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/29a0c4ff03b028681a805ce8e087fc6421ef8bc1"><code>29a0c4f</code></a></td><td><code>Merge branch 'u/kdilks/SymPP' of https://github.com/sagemath/sagetrac-mirror into public/combinat/symmetry_classes_plane_partitions-28244</code></td></tr><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/77a5b52bf50f0953dea2f1c57f7de6c61d7f50da"><code>77a5b52</code></a></td><td><code>A number of reviewer changes and cleanup.</code></td></tr></table>

**Comment by mkoeppe** [comment]
<div id="comment:64" align="right">comment:64</div>

pyright complains:

```
  /__w/sagetrac-mirror/sagetrac-mirror/src/sage/combinat/plane_partition.py:49:20 - error: Expected class as second argument to NewType
```

**Comment by fchapoton** [comment]
<div id="comment:65" align="right">comment:65</div>

Who asked for pyright compliance ? where is the report to be seen ?

On the other hand, the linter complains about many trailing whitespaces.
and about the documentation:

```
./sage/combinat/plane_partition.py:1173:1: RST214 Inline literal start-string without end-string.
```

**Comment by mkoeppe** [comment]
<div id="comment:66" align="right">comment:66</div>

It's part of the "Build & Test" workflow.

**Comment by mkoeppe** [comment]
<div id="comment:67" align="right">comment:67</div>

pyright is right; the file uses `NewType` incorrectly. https://docs.python.org/3/library/typing.html#typing.NewType

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
<div id="comment:68"></div>

Branch pushed to git repo; I updated commit sha1. New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/4390f3161a029a7e1853a311f3c8027ec8af85f4"><code>4390f31</code></a></td><td><code>Removed NewType and other small fixes.</code></td></tr></table>

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
Changed commit from **[`77a5b52`](https://github.com/sagemath/sagetrac-mirror/commit/77a5b52bf50f0953dea2f1c57f7de6c61d7f50da)** to **[`4390f31`](https://github.com/sagemath/sagetrac-mirror/commit/4390f3161a029a7e1853a311f3c8027ec8af85f4)**

**Comment by tscrim** [comment]
<div id="comment:69" align="right">comment:69</div>

Thanks. I removed the `NewType` and fixed the doc error.

**Comment by fchapoton** [comment]
<div id="comment:71" align="right">comment:71</div>

still

```
./sage/combinat/plane_partition.py:3044:28: E111 indentation is not a multiple of 4
19
./sage/combinat/plane_partition.py:3136:1: W391 blank line at end of file
```

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
Changed commit from **[`4390f31`](https://github.com/sagemath/sagetrac-mirror/commit/4390f3161a029a7e1853a311f3c8027ec8af85f4)** to **[`a3c1c58`](https://github.com/sagemath/sagetrac-mirror/commit/a3c1c586e5bdc71a727f3ea03c4ee0da062bc711)**

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
<div id="comment:72"></div>

Branch pushed to git repo; I updated commit sha1. New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/a3c1c586e5bdc71a727f3ea03c4ee0da062bc711"><code>a3c1c58</code></a></td><td><code>Fixing pycodestyle.</code></td></tr></table>

**Comment by tscrim** [comment]
<div id="comment:73" align="right">comment:73</div>

This should take care of those.
