### ISSUE TITLE
MathJax causing unusual hanging in large notebooks

### ISSUE THREAD

**Issue by embray** [sagemath/sage#28257]
<div id="comment:0"></div>

A problem we kept having at Sage Days 102 is that one of the instructors created a (very good) tutorial notebook for Sage that is quite long, and simply opening it would cause users' web browsers to hang, possibly for several minutes on slower machines.

It has since (because of this problem, in part) been broken up into several smaller notebooks, but you can see the original large notebook here:

https://github.com/gabayae/sage-days-102/blob/a8bfb27528540116b8d17726d283a28a66200005/sage_days_102_introduction_to_sagemath.ipynb

This would hang on Firefox and Chrome (in both cases going so slowly that the browser will interrupt execution several times and prompt the user to either wait, or permanently halt execution of the script, at which point Latex rendering stops working, and sometimes the page doesn't finish loading).

I've also observed this problem on some other large-ish notebooks such as https://raw.githubusercontent.com/sagemanifolds/SageManifolds/master/Notebooks/SM_sphere_S2.ipynb

Yes, MathJax can be slow at times, but it's supposed to lazily do typesetting in the background once the page has loaded.  However, in this case, it seems to be hanging the whole page before the DOM is even fully loaded.

While this is happening, MathJax displays a message in the corner of the page of `Loading [MathJax]/extensions/Safe.js`.  So whatever this `Safe.js` extension is, it seems to cause serious problems on large notebooks.

Furthemore, the notebook we were having problems with doesn't actually have *that many* equations in it, so it's not a problem of slow rendering.  I actually extracted all the equations from the notebook and pasted them into a single cell, and it renders almost immediately.  The problem seems to have more to do with just the size of the HTML page.

CC:  @evansdoe @egourgoulhon

Component: **notebook**

Keywords: **days102**

_Issue created by migration from https://trac.sagemath.org/ticket/28257_

**Comment by kwankyu** [comment]
The first notebook does not open, with message
```
Unreadable Notebook: /Users/kwankyu/Workplace/sage/sage_days_102_introduction_to_sagemath.ipynb NotJSONError("Notebook does not appear to be JSON: '\\n\\n\\n\\n\\n\\n<!DOCTYPE html>\\n<html lang...")
```
and the second notebook opens well though it takes some time to render all equations.

This is jupyterlab 3.5.3 and its classic version.

Hence the problems in the description do not appear anymore. At least I think there is nothing to do on our side. I am closing this issue.
