### ISSUE TITLE
Implement check for Lorentzian polynomials

### ISSUE THREAD

**Issue by bgillesp** [sagemath/sage#28252]
<div id="comment:0"></div>

Implement a check for Lorentzian polynomials, as defined in "Lorentzian Polynomials", https://arxiv.org/abs/1902.03719.

Part of the "Geometry and Combinatorics of Matroids" project at Sage Days 99 at the Institute for Mathematics and its Applications, at University of Minnesota Twin Cities.

CC:  @tscrim @kwankyu @slel @dcoudert

Component: **commutative algebra**

Keywords: **IMA Coding Sprints, days99, polynomials, discrete convex analysis**

Author: **Galen Dorpalen-Barry, Bryan Gillespie, Jacob P. Matherne, Thomas McConville**

Branch/Commit: **[public/28252](https://github.com/sagemath/sagetrac-mirror/tree/public/28252) @ [`5fa1a05`](https://github.com/sagemath/sagetrac-mirror/commit/5fa1a0534c9b4a51cdb6a9ad65c29c06a9e52798)**

Reviewer: **Aritra Bhattacharya, Samuel Lelièvre, Julian Rüth**

_Issue created by migration from https://trac.sagemath.org/ticket/28252_

**Comment by bgillesp** [comment]
Description changed:
``````diff
--- 
+++ 
@@ -1 +1 @@
-
+Implement a check for Lorentzian polynomials, as defined in "Lorentzian Polynomials", https://arxiv.org/abs/1902.03719.
``````

**Comment by bgillesp** [comment]
Description changed:
``````diff
--- 
+++ 
@@ -1 +1,3 @@
 Implement a check for Lorentzian polynomials, as defined in "Lorentzian Polynomials", https://arxiv.org/abs/1902.03719.
+
+Part of the "Geometry and Combinatorics of Matroids" project at Sage Days 99 at the Institute for Mathematics and its Applications, at University of Minnesota Twin Cities.
``````

**Comment by fchapoton** [comment]
<div id="comment:37" align="right">comment:37</div>

still some failing doctests

**Comment by fchapoton** [comment]
<div id="comment:38" align="right">comment:38</div>

somebody among the many authors should stand up and fix the 3 (easy?) failing doctests

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
<div id="comment:39"></div>

Branch pushed to git repo; I updated commit sha1. New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/2228c5564093ca7e0bc4a7b9968d13068d50f25d"><code>2228c55</code></a></td><td><code>Merge branch 'public/28252' in 9.8.beta2</code></td></tr><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/65ade873d47ba1f1648ceaa5c2004f58a3700d6b"><code>65ade87</code></a></td><td><code>fix doctests</code></td></tr></table>

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
Changed commit from **[`53758bb`](https://github.com/sagemath/sagetrac-mirror/commit/53758bb763bb53af222f11f330b65cc4f3d2c37c)** to **[`65ade87`](https://github.com/sagemath/sagetrac-mirror/commit/65ade873d47ba1f1648ceaa5c2004f58a3700d6b)**

**Comment by fchapoton** [comment]
<div id="comment:40" align="right">comment:40</div>

I have fixed the doctests myself, sigh.

**Comment by fchapoton** [comment]
<div id="comment:41" align="right">comment:41</div>

any reviewer available for this interesting stuff ?

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
Changed commit from **[`65ade87`](https://github.com/sagemath/sagetrac-mirror/commit/65ade873d47ba1f1648ceaa5c2004f58a3700d6b)** to **[`bb560f0`](https://github.com/sagemath/sagetrac-mirror/commit/bb560f03dbc58cd2e8b075d72d069061bb216caa)**

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
<div id="comment:42"></div>

Branch pushed to git repo; I updated commit sha1. New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/bb560f03dbc58cd2e8b075d72d069061bb216caa"><code>bb560f0</code></a></td><td><code>really fix doctests</code></td></tr></table>

**Comment by fchapoton** [comment]
<div id="comment:43" align="right">comment:43</div>

anyone interested ? This is ready for review, but it seems that the authors are not listening.

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
<div id="comment:44"></div>

Branch pushed to git repo; I updated commit sha1. New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/5fa1a0534c9b4a51cdb6a9ad65c29c06a9e52798"><code>5fa1a05</code></a></td><td><code>Merge branch 'public/28252' in 9.8.b7</code></td></tr></table>

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
Changed commit from **[`bb560f0`](https://github.com/sagemath/sagetrac-mirror/commit/bb560f03dbc58cd2e8b075d72d069061bb216caa)** to **[`5fa1a05`](https://github.com/sagemath/sagetrac-mirror/commit/5fa1a0534c9b4a51cdb6a9ad65c29c06a9e52798)**

**Comment by mkoeppe** [comment]
Removed branch from the issue description because it has been replaced by PR #35021
