### ISSUE TITLE
Implemented is_chebyshev and is_lattes for one dimensional projective dynamical systems

### ISSUE THREAD

**Issue by 8850bfe1-3856-490c-8413-70c107ea0038** [sagemath/sage#28292]
<div id="comment:0"></div>

Added functions to projective dynamical systems which test whether the dynamical system is conjugate (over an algebraic closure of the base field) to a Chebyshev polynomial or to a Lattes map.

Component: **dynamics**

Keywords: **SI2019, sd104**

Author: **Trevor Hyde, Fiona Lu, Alex Shearer**

Branch/Commit: **[u/gh-EnderWannabe/implemented_is_chebyshev_and_is_lattes_for_one_dimensional_projective_dynamical_systems](https://github.com/sagemath/sagetrac-mirror/tree/u/gh-EnderWannabe/implemented_is_chebyshev_and_is_lattes_for_one_dimensional_projective_dynamical_systems) @ [`0d6c684`](https://github.com/sagemath/sagetrac-mirror/commit/0d6c684580c93527c3598f681fafa5737000cf23)**

Reviewer: **Andrew Odesky, Benjamin Krakoff, Krystal Maughan, Mingming Zhang**

_Issue created by migration from https://trac.sagemath.org/ticket/28292_

**Comment by mkoeppe** [comment]
Branch has merge conflicts
