### ISSUE TITLE
field_of_definition_critical() fails on homogenized affine dynamical systems.

### ISSUE THREAD

**Issue by 8850bfe1-3856-490c-8413-70c107ea0038** [sagemath/sage#28293]
<div id="comment:0"></div>

If a projective dynamical system `F` is created by homogenizing an affine dynamical system, then calling `F.field_of_definition_critical()` returns a type error.

The below example returns an error.

```
K.<x> = FractionField(PolynomialRing(QQ,'x'))
F = DynamicalSystem_affine((x^2 + 1)/(x^2 - 1))
FF = F.homogenize(1)
FF.field_of_definition_critical()
```

But constructing the same map as a projective dynamical system directly gives no error.

```
P.<x,y> = ProjectiveSpace(QQ,1)
FF = DynamicalSystem_projective([x^2 + y^2, x^2 - y^2])
FF.field_of_definition_critical()
```

Component: **dynamics**

Author: **Trevor Hyde**

_Issue created by migration from https://trac.sagemath.org/ticket/28293_

**Comment by guojing0** [comment]
> Fixed in #31896, should be marked as closed.
