### ISSUE TITLE
Worksheet to test the class `DegenerateMetric`

### ISSUE THREAD

**Issue by 8f7278ee-e22d-4c4e-aed1-8e3fe00e8e9a** [sagemath/sage#28577]
<div id="comment:0"></div>

This ticket only contains a worksheet,
`ClassDegenerateMetric`, that helps to test
<code>:class:\`~sage.manifolds.differentiable.metric.DegenerateMetric\`</code>.

Depends on #1

CC:  @egourgoulhon @slel

Component: **geometry**

Author: **Hans Fotsing Tetsing**

Branch/Commit: **[public/manifolds/Sheets](https://github.com/sagemath/sagetrac-mirror/tree/public/manifolds/Sheets) @ [`8720884`](https://github.com/sagemath/sagetrac-mirror/commit/8720884eba204fb3375844234d2b238036a8c933)**

_Issue created by migration from https://trac.sagemath.org/ticket/28577_

**Comment by 8f7278ee-e22d-4c4e-aed1-8e3fe00e8e9a** [comment]
Description changed:
``````diff
--- 
+++ 
@@ -1 +1 @@
-
+This Ticket only contains a worksheet (ClassDegenerateMetric) that help to test :class:`~sage.manifolds.differentiable.metric.DegenerateMetric`
``````

**Comment by 8f7278ee-e22d-4c4e-aed1-8e3fe00e8e9a** [comment]
Description changed:
``````diff
--- 
+++ 
@@ -1 +1 @@
-This Ticket only contains a worksheet (ClassDegenerateMetric) that help to test :class:`~sage.manifolds.differentiable.metric.DegenerateMetric`
+This Ticket only contains a worksheet, ClassDegenerateMetric, that helps to test :class:`~sage.manifolds.differentiable.metric.DegenerateMetric`
``````

**Comment by slel** [comment]
Description changed:
``````diff
--- 
+++ 
@@ -1 +1,3 @@
-This Ticket only contains a worksheet, ClassDegenerateMetric, that helps to test :class:`~sage.manifolds.differentiable.metric.DegenerateMetric`
+This ticket only contains a worksheet,
+`ClassDegenerateMetric`, that helps to test
+<code>:class:\`~sage.manifolds.differentiable.metric.DegenerateMetric\`</code>.
``````
