### ISSUE TITLE
openblas sometimes fails its testsuite on OS X

### ISSUE THREAD

**Issue by jhpalmieri** [sagemath/sage#28731]
<div id="comment:0"></div>

On OS X, `./sage -f -c openblas` can fail (but it's intermittent) with the message

```
ld: file too small (length=0) file '../libopenblas_skylakexp-r0.3.6.a' for architecture x86_64
collect2: error: ld returned 1 exit status
make[3]: *** [dblat1] Error 1
```
If I look at `local/var/tmp/sage/build/openblas-0.3.6.p0/src`, I see

```
  lrwxr-xr-x  1 jpalmier staff       29 Nov 13 13:04 libopenblas.a -> libopenblas_haswellp-r0.3.6.a
  lrwxr-xr-x  1 jpalmier staff       33 Nov 13 13:08 libopenblas.dylib -> libopenblas_haswellp-r0.3.6.dylib
  -rw-r--r--  1 jpalmier staff 22764680 Nov 13 13:08 libopenblas_haswellp-r0.3.6.a
  -rwxr-xr-x  1 jpalmier staff 14355896 Nov 13 13:08 libopenblas_haswellp-r0.3.6.dylib
  -rw-r--r--  1 jpalmier staff        0 Nov 13 13:08 libopenblas_skylakexp-r0.3.6.a
```
I don't know why it's looking for `libopenblas_skylakexp-r0.3.6.a`.

Component: **packages: standard**

_Issue created by migration from https://trac.sagemath.org/ticket/28731_

**Comment by mkoeppe** [comment]
close as outdated?

**Comment by jhpalmieri** [comment]
Yes, that's fine with me. (Am I allowed to close the issue, or should I leave that for the release manager?)

**Comment by mkoeppe** [comment]
I'd think it's fine to just close it.
