### ISSUE TITLE
Polymake interface hangs

### ISSUE THREAD

**Issue by 6b8a00d1-0beb-4653-a6ee-6a3405149463** [sagemath/sage#29946]
<div id="comment:0"></div>

On Ubuntu 20.04

Running the code

```
import sage.all
from sage.interfaces.polymake import polymake_expect as polymake
polymake.application("polytope")
```

results in a hang (code never exits).

Output of sage -polymake --version:

```
polymake version 3.4
Copyright (c) 1997-2019
Ewgenij Gawrilow, Michael Joswig (TU Berlin)
https://polymake.org

This is free software licensed under GPL; see the source for copying conditions.
There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

Output of sage --version

```
SageMath version 9.1, Release Date: 2020-05-20
```

Component: **interfaces**

Keywords: **polymake**

_Issue created by migration from https://trac.sagemath.org/ticket/29946_

**Comment by mkoeppe** [comment]
<div id="comment:7" align="right">comment:7</div>

outdated - the `Polymake_pexpect` has been removed
