### ISSUE TITLE
System package information and spkg-configure for mathjax

### ISSUE THREAD

**Issue by mkoeppe** [sagemath/sage#30296]
<div id="comment:0"></div>

After #31035, our `mathjax` spkg is only used in our sphinx documentation.  We currently ship a "stripped" version of mathjax 2.7.4 (see `build/pkgs/mathjax/spkg-src`; #25032, #18596); #25833 proposes an upgrade to 3.x.

We add an `spkg-configure.m4` script for the standard package `mathjax`, as well as corresponding system package information in `build/pkgs/mathjax/distros/` using https://repology.org/projects/?search=mathjax

---

Random references:

py-mathjax/pypi/py-mathjax at master · kiwi0fruit/py-mathjax
https://github.com/kiwi0fruit/py-mathjax/tree/master/pypi/py-mathjax

Debian JavaScript Maintainers / mathjax · GitLab
https://salsa.debian.org/js-team/mathjax

sphinx/setup.py at 3.x · sphinx-doc/sphinx
https://github.com/sphinx-doc/sphinx/blob/3.x/setup.py

Math support for HTML outputs in Sphinx — Sphinx 4.0.0+ documentation
https://www.sphinx-doc.org/en/master/usage/extensions/math.html#module-sphinx.ext.mathjax

sphinx-ext-mathjax - Google Search
https://www.google.com/search?safe=off&sxsrf=ALeKk03spVlQ9ALPLJJCbNfF9EIdC_LYuQ%3A1596929073175&ei=MTQvX8mUCuKU0PEPu-yOiAE&q=sphinx-ext-mathjax&oq=sphinx-ext-mathjax&gs_lcp=CgZwc3ktYWIQAzIFCAAQzQIyBQgAEM0CMggIABDNAhCLAzIICAAQzQIQiwMyCAgAEM0CEIsDOgQIABBHOgcIIxCwAhAnOgcIIRAKEKABOgUIIRCgAToFCCEQqwJQmyhY4UVgtFBoAHABeACAAWqIAeUHkgEDOS4ymAEAoAEBqgEHZ3dzLXdpergBA8ABAQ&sclient=psy-ab&ved=0ahUKEwiJ8Yyx4IzrAhViCjQIHTu2AxEQ4dUDCAw&uact=5

Math support for HTML outputs in Sphinx — Sphinx 4.0.0+ documentation
https://www.sphinx-doc.org/en/master/usage/extensions/math.html#module-sphinx.ext.mathjax

sphinx/mathjax.py at 3.x · sphinx-doc/sphinx
https://github.com/sphinx-doc/sphinx/blob/3.x/sphinx/ext/mathjax.py

CC:  @jcamp0x2a @paulmasson @slel @egourgoulhon @orlitzky @kwankyu @jhpalmieri @nthiery @enriqueartal @kiwifb @antonio-rojas @tobihan @Etn40ff @tobiasdiez

Component: **packages: standard**

Keywords: **mathjax, sd111**

Author: **Samuel Lelièvre, ...**

Branch/Commit: **[public/30296](https://github.com/sagemath/sagetrac-mirror/tree/public/30296) @ [`5c624ab`](https://github.com/sagemath/sagetrac-mirror/commit/5c624abfd948829125163f91f4bd4b24d0ecb797)**

_Issue created by migration from https://trac.sagemath.org/ticket/30296_

**Comment by mkoeppe** [comment]
Description changed:
``````diff
--- 
+++ 
@@ -1,3 +1,29 @@
 We add an `spkg-configure.m4` script for the standard package `mathjax`, as well as corresponding system package information in `build/pkgs/mathjax/distros/`
 
 
+
+
+---
+
+Random references:
+
+py-mathjax/pypi/py-mathjax at master · kiwi0fruit/py-mathjax
+https://github.com/kiwi0fruit/py-mathjax/tree/master/pypi/py-mathjax
+
+Debian JavaScript Maintainers / mathjax · [GitLab](../wiki/GitLab)
+https://salsa.debian.org/js-team/mathjax
+
+sphinx/setup.py at 3.x · sphinx-doc/sphinx
+https://github.com/sphinx-doc/sphinx/blob/3.x/setup.py
+
+Math support for HTML outputs in Sphinx — Sphinx 4.0.0+ documentation
+https://www.sphinx-doc.org/en/master/usage/extensions/math.html#module-sphinx.ext.mathjax
+
+sphinx-ext-mathjax - Google Search
+https://www.google.com/search?safe=off&sxsrf=ALeKk03spVlQ9ALPLJJCbNfF9EIdC_LYuQ%3A1596929073175&ei=MTQvX8mUCuKU0PEPu-yOiAE&q=sphinx-ext-mathjax&oq=sphinx-ext-mathjax&gs_lcp=CgZwc3ktYWIQAzIFCAAQzQIyBQgAEM0CMggIABDNAhCLAzIICAAQzQIQiwMyCAgAEM0CEIsDOgQIABBHOgcIIxCwAhAnOgcIIRAKEKABOgUIIRCgAToFCCEQqwJQmyhY4UVgtFBoAHABeACAAWqIAeUHkgEDOS4ymAEAoAEBqgEHZ3dzLXdpergBA8ABAQ&sclient=psy-ab&ved=0ahUKEwiJ8Yyx4IzrAhViCjQIHTu2AxEQ4dUDCAw&uact=5
+
+Math support for HTML outputs in Sphinx — Sphinx 4.0.0+ documentation
+https://www.sphinx-doc.org/en/master/usage/extensions/math.html#module-sphinx.ext.mathjax
+
+sphinx/mathjax.py at 3.x · sphinx-doc/sphinx
+https://github.com/sphinx-doc/sphinx/blob/3.x/sphinx/ext/mathjax.py
``````

**Comment by slel** [comment]
Description changed:
``````diff
--- 
+++ 
@@ -1,7 +1,4 @@
 We add an `spkg-configure.m4` script for the standard package `mathjax`, as well as corresponding system package information in `build/pkgs/mathjax/distros/`
-
-
-
 
 ---
 
@@ -10,7 +7,7 @@
 py-mathjax/pypi/py-mathjax at master · kiwi0fruit/py-mathjax
 https://github.com/kiwi0fruit/py-mathjax/tree/master/pypi/py-mathjax
 
-Debian JavaScript Maintainers / mathjax · [GitLab](../wiki/GitLab)
+Debian JavaScript Maintainers / mathjax · GitLab
 https://salsa.debian.org/js-team/mathjax
 
 sphinx/setup.py at 3.x · sphinx-doc/sphinx
@@ -27,3 +24,4 @@
 
 sphinx/mathjax.py at 3.x · sphinx-doc/sphinx
 https://github.com/sphinx-doc/sphinx/blob/3.x/sphinx/ext/mathjax.py
+
``````

**Comment by mkoeppe** [comment]
Description changed:
``````diff
--- 
+++ 
@@ -1,4 +1,15 @@
+mathjax is used in our sphinx documentation and in the Jupyter notebook.  We currently ship a "stripped" version of mathjax 2.7.4 (see `build/pkgs/mathjax/spkg-src`; #25032, #18596); #25833 proposes an upgrade to 3.x.
+
 We add an `spkg-configure.m4` script for the standard package `mathjax`, as well as corresponding system package information in `build/pkgs/mathjax/distros/`
+
+Open questions:
+
+- Is there any difference in font rendering between the mathjax that comes with Jupyter notebook and our copy of mathjax? Does Jupyter notebook rely on online resources for any font rendering? 
+
+  (This should be apparent in comparing Sage running in system Jupyter notebook vs. the Sage distributions's Jupyter notebook - which uses the configuration in `build/pkgs/notebook/jupyter_notebook_config.py`)
+
+- If no, we can remove this configuration item from our notebook configuration; and this ticket will reduce to sphinx docbuild questions only.
+
 
 ---
 
``````

**Comment by mkoeppe** [comment]
Description changed:
``````diff
--- 
+++ 
@@ -8,7 +8,7 @@
 
   (This should be apparent in comparing Sage running in system Jupyter notebook vs. the Sage distributions's Jupyter notebook - which uses the configuration in `build/pkgs/notebook/jupyter_notebook_config.py`)
 
-- If no, we can remove this configuration item from our notebook configuration; and this ticket will reduce to sphinx docbuild questions only.
+- If no, we can remove this configuration item from our notebook configuration; and this ticket will reduce to sphinx docbuild questions only. (Done in #31035)
 
 
 ---
``````

**Comment by mkoeppe** [comment]
Description changed:
``````diff
--- 
+++ 
@@ -1,15 +1,6 @@
-mathjax is used in our sphinx documentation and in the Jupyter notebook.  We currently ship a "stripped" version of mathjax 2.7.4 (see `build/pkgs/mathjax/spkg-src`; #25032, #18596); #25833 proposes an upgrade to 3.x.
+After #31035, our `mathjax` spkg is only used in our sphinx documentation.  We currently ship a "stripped" version of mathjax 2.7.4 (see `build/pkgs/mathjax/spkg-src`; #25032, #18596); #25833 proposes an upgrade to 3.x.
 
 We add an `spkg-configure.m4` script for the standard package `mathjax`, as well as corresponding system package information in `build/pkgs/mathjax/distros/`
-
-Open questions:
-
-- Is there any difference in font rendering between the mathjax that comes with Jupyter notebook and our copy of mathjax? Does Jupyter notebook rely on online resources for any font rendering? 
-
-  (This should be apparent in comparing Sage running in system Jupyter notebook vs. the Sage distributions's Jupyter notebook - which uses the configuration in `build/pkgs/notebook/jupyter_notebook_config.py`)
-
-- If no, we can remove this configuration item from our notebook configuration; and this ticket will reduce to sphinx docbuild questions only. (Done in #31035)
-
 
 ---
 
``````

**Comment by mkoeppe** [comment]
Description changed:
``````diff
--- 
+++ 
@@ -1,6 +1,6 @@
 After #31035, our `mathjax` spkg is only used in our sphinx documentation.  We currently ship a "stripped" version of mathjax 2.7.4 (see `build/pkgs/mathjax/spkg-src`; #25032, #18596); #25833 proposes an upgrade to 3.x.
 
-We add an `spkg-configure.m4` script for the standard package `mathjax`, as well as corresponding system package information in `build/pkgs/mathjax/distros/`
+We add an `spkg-configure.m4` script for the standard package `mathjax`, as well as corresponding system package information in `build/pkgs/mathjax/distros/` using https://repology.org/projects/?search=mathjax
 
 ---
 
``````

**Comment by kwankyu** [comment]
<div id="comment:53" align="right">comment:53</div>

Replying to [Michael Orlitzky](#comment%3A49):
> Ultimately I can write the spkg-configure if no one else does it. I'll probably wait until the mathjax-3.x upgrade is done though.

Now that mathjax3 is well in place, would you do the work? 

From Matthias: `src/sage/docs/conf.py` expects sage.env.MATHJAX_DIR to be set to the location. This is what we'd have to configure if we take mathjax either from a system installation, or some other source.

**Comment by orlitzky** [comment]
<div id="comment:54" align="right">comment:54</div>

Replying to [Kwankyu Lee](#comment%3A53):
> Replying to [Michael Orlitzky](#comment%3A49):
> > Ultimately I can write the spkg-configure if no one else does it. I'll probably wait until the mathjax-3.x upgrade is done though.
> 
> 
> Now that mathjax3 is well in place, would you do the work?

Now I'm waiting for my distro package to be upgraded (https://bugs.gentoo.org/837722), but yes, I'll get to it eventually.

**Comment by mkoeppe** [comment]
On the question of the many copies of mathjax in `_static`, see https://github.com/sagemath/sage/issues/35538#issuecomment-1514352367

**Comment by mkoeppe** [comment]
On conda, the `mathjax` package installs into `lib/mathjax/es5/` (https://github.com/conda-forge/mathjax-feedstock/blob/main/recipe/mathjax-path)

**Comment by kwankyu** [comment]
@orlitzky is working on this issue. Unfortunately there is [a problem with no easy fix](https://github.com/sagemath/sage/pull/36098#discussion_r1299280160) in using system mathjax without incurring a regression in using spkg mathjax. (In my view,  many systems mathjax are installed in a way not working nicely with Sphinx but conda and our spkg are doing it right).

I still have doubts on the benefits of using system mathjax. We need mathjax only for our documentation. I think the documentation should use mathjax CDN in the first place, but for users without internet, we provide spkg mathjax. The spkg is small and takes no time in installing as it is just a bunch of javascript and data files. Then why do we make efforts to use system mathjax? Of course, I would not ask this if there was no regression in using system mathjax.

If there's a convincing argument, then I would accept the regression (which is only about organization not about functioning),

**Comment by kwankyu** [comment]
#36098 just got positive review. I am not sure if that may close this issue.

**Comment by orlitzky** [comment]
I used a `Closes:` tag in one my commits that should close the issue automatically when it is merged: https://github.blog/2013-01-22-closing-issues-via-commit-messages/
