### ISSUE TITLE
Allow pull requests from Github

### ISSUE THREAD

**Issue by tobiasdiez** [sagemath/sage#30406]
<div id="comment:0"></div>

I've heard that once upon a time there was a bot that created trac issues based on GitHub PRs. Apparently the bot was lost.

I found https://github.com/trac-hacks/trac-github which has the feature to "update the local git mirror used by Trac after each push to GitHub, and notify the new changesets to Trac;". Sounds like this is exactly what would be needed to allow PRs from github.
I couldn't find anything on how to install trac plugins here on sage.

Related:

- #30363: Migrate to GitHub

Depends on #30363

CC:  @embray @mkoeppe @robertwb @slel @williamstein

Component: **misc**

_Issue created by migration from https://trac.sagemath.org/ticket/30406_

**Comment by slel** [comment]
Description changed:
``````diff
--- 
+++ 
@@ -1,6 +1,8 @@
-I've heard that once upon a time there was a bot that created trac issues based on github PRs. Apparently the bot was lost.
+I've heard that once upon a time there was a bot that created trac issues based on GitHub PRs. Apparently the bot was lost.
 
-I found https://github.com/trac-hacks/trac-github which has the feature to "update the local git mirror used by Trac after each push to [GitHub](../wiki/GitHub), and notify the new changesets to Trac;". Sounds like this is exactly what would be needed to allow PRs from github.
+I found https://github.com/trac-hacks/trac-github which has the feature to "update the local git mirror used by Trac after each push to GitHub, and notify the new changesets to Trac;". Sounds like this is exactly what would be needed to allow PRs from github.
 I couldn't find anything on how to install trac plugins here on sage.
 
+Related:
 
+- #30363: Migrate to GitHub
``````
