### ISSUE TITLE
Remove pyflakes?

### ISSUE THREAD

**Issue by tobiasdiez** [sagemath/sage#30415]
<div id="comment:0"></div>

With #30361 and #30404 pyright is added as a static type checker. Besides type checking, it also includes almost all checks that are performed by pyflakes. 

As far as I can see, the differences are as follows:
- Pyright excels at type checking
- Pyflakes has no support for type checking, and indeed is not even able to handle basic typing syntax (this would need among others https://github.com/PyCQA/pyflakes/pull/530, which seems to be stale) 
- Pyflakes checks for basic validity of the arguments to "format" and "print", this is not supported by pyright 

So it depends on how important the print and format validation are. Maybe they are also covered by lgtm?

Resources:
- List of checks of pyright: https://github.com/microsoft/pyright/blob/master/docs/configuration.md#type-check-diagnostics-settings
- List of checks of pyflakes: https://flake8.pycqa.org/en/latest/user/error-codes.html

Depending on the outcome, the stub documentation of pyflakes added in #30361 needs be extended or removed.

CC:  @mkoeppe @fchapoton @mjungmath @kliem

Component: **build**

_Issue created by migration from https://trac.sagemath.org/ticket/30415_

**Comment by fchapoton** [comment]
Can we close this one as invalid, given that the patchbot is gone away ? We should also remove the pyflakes pkg.
