### ISSUE TITLE
Fold src/bin/sage-num-threads.py into sagelib Python code

### ISSUE THREAD

**Issue by mkoeppe** [sagemath/sage#30639]
<div id="comment:0"></div>

As a follow-up to #29355 (which separated build-time from run-time
determination of the number of threads to use), we get rid of
`src/bin/sage-num-threads.py` completely by implementing the
desired defaulting behavior for the number of threads used in
`src/sage/parallel/ncpus.py` and `src/sage/doctest/control.py`.

Depends on #33317

CC:  @jhpalmieri @slel

Component: **refactoring**

Reviewer: **Matthias Koeppe**

_Issue created by migration from https://trac.sagemath.org/ticket/30639_

**Comment by slel** [comment]
Description changed:
``````diff
--- 
+++ 
@@ -1,2 +1,6 @@
-As a follow-up to #29355 (which separated build-time from run-time determination of number of threads to use), we get rid of `src/bin/sage-num-threads.py` completely by implementing the desired defaulting behavior for the number of threads used in `src/sage/parallel/ncpus.py` and `src/sage/doctest/control.py.
+As a follow-up to #29355 (which separated build-time from run-time
+determination of the number of threads to use), we get rid of
+`src/bin/sage-num-threads.py` completely by implementing the
+desired defaulting behavior for the number of threads used in
+`src/sage/parallel/ncpus.py` and `src/sage/doctest/control.py`.
 
``````
