### ISSUE TITLE
try to upgrade tdlib

### ISSUE THREAD

**Issue by dimpase** [sagemath/sage#30813]
<div id="comment:0"></div>

tdlib appears in development, at https://github.com/freetdi/tdlib - now at version 0.9.

Not sure whether it it easy to upgrade, but one should try.

CC:  @dcoudert @sagetrac-llarisch

Component: **packages: optional**

_Issue created by migration from https://trac.sagemath.org/ticket/30813_

**Comment by mkoeppe** [comment]
- Latest release = 0.9.1 on gitlab
- Latest commit = Sep 11, 2023
- Arch package https://archlinux.org/packages/extra/any/tdlib/ advertises itself as 0.9.2 @antonio-rojas 
- repo https://github.com/freetdi/tdlib/commits/develop/ is synced but has no releases, no tags

**Comment by mkoeppe** [comment]
- Sage patch by @antonio-rojas https://gitlab.archlinux.org/archlinux/packaging/packages/sagemath/-/blob/main/sagemath-tdlib-0.9.patch?ref_type=heads

**Comment by felix-salfelder** [comment]
There's some unfinished work on new python bindings for treedec. The goal is to replace the "tdlib" cython code by ordinary c++, with a more pythonic interface. And there is an experimental but stand-alone setup.py.

See the python_build branch in the git source repo and https://www.algok.uni-bamberg.de/freetdi.html for possible future work.

**Comment by mkoeppe** [comment]
@felix-salfelder Thanks for the pointer. Note we are packaging https://pypi.org/project/sagemath-tdlib/ (you may have already seen that)

**Comment by antonio-rojas** [comment]
> * Sage patch by @antonio-rojas https://gitlab.archlinux.org/archlinux/packaging/packages/sagemath/-/blob/main/sagemath-tdlib-0.9.patch?ref_type=heads

Patch credit goes to Fedora, TBF.

**Comment by antonio-rojas** [comment]
@felix-salfelder hi, is there a reason why there is no 0.9.2 tag? Last commit being "Release 0.9.2" suggests that it's done.

**Comment by felix-salfelder** [comment]
On Fri, Jun 07, 2024 at 12:13:01AM -0700, Antonio Rojas wrote:
> @felix-salfelder hi, is there a reason why there is no 0.9.2 tag? Last
> commit being "Release 0.9.2" suggests that it's done.

Not sure where it went. Perhaps I forgot to push it...  I have just
updated git tags and tarballs [1]. The migration from git**b remains in
limbo for now.

[1] https://www.algok.uni-bamberg.de/freetdi.html
