### ISSUE TITLE
Make arb config more flexible and find also flint-arb

### ISSUE THREAD

**Issue by tobiasdiez** [sagemath/sage#30936]
<div id="comment:0"></div>

If one has flint-arb installed but not arb as a system package, then compilation currently fails unless one explicitly sets `ARB_LIBRARY = flint-arb`. In this ticket, we also check for the existence of flint-arb making this manual step obsolete. This is similar in spirit to #30706, which does the same for CBLAS.

The config file `build/pgks/arb/spkg-configure.m4` does a similar check (I think) and maybe can/needs to be adapted as well. If that's the case I would like to ask if somebody else can implement the necessary changes, as I've no experience with these config files. Thanks!

Depends on #30901

CC:  @mkoeppe

Component: **build**

Branch/Commit: **[public/build/arbconfig](https://github.com/sagemath/sagetrac-mirror/tree/public/build/arbconfig) @ [`5d606e5`](https://github.com/sagemath/sagetrac-mirror/commit/5d606e5a58b278d6d5d242c08b9b647983ca2a10)**

_Issue created by migration from https://trac.sagemath.org/ticket/30936_

**Comment by mkoeppe** [comment]
Outdated; we have `SAGE_ARB_LIBRARY`.
