### ISSUE TITLE
deprecate or remove InfiniteAbstractCombinatorialClass

### ISSUE THREAD

**Issue by fchapoton** [sagemath/sage#31545]
<div id="comment:0"></div>

which is no longer used anywhere.

Component: **combinatorics**

Author: **Frédéric Chapoton**

Branch/Commit: **[`abb7c3e`](https://github.com/sagemath/sagetrac-mirror/commit/abb7c3e4790b42d40cb9cd960315befb4f5ac3c2)**

Reviewer: **Matthias Koeppe**

_Issue created by migration from https://trac.sagemath.org/ticket/31545_

**Comment by dimpase** [comment]
@fchapoton This deprecation is inconsistent. While `InfiniteAbstractCombinatorialClass` can indeed go, `UnionCombinatorialClass` and `FilteredCombinatorialClass` are used in `CombinatorialClass` - which is not formally deprecated (there is a comment there saying it is, but no deprecation notice).

**Comment by mkoeppe** [comment]
I think it was deprecated before deprecation notices were invented.

**Comment by mkoeppe** [comment]
For consistency I think it's best not to re-open issues with attached merged Trac branches.

**Comment by dimpase** [comment]
OK, I'll open a new one.

The problem is that some of the classes deprecated here are in use by not deprecated classes. So it's an incomplete job.
