### ISSUE TITLE
Page does not exist: http://www.friedspace.com/QS/

### ISSUE THREAD

**Issue by 863a3e0b-4984-4e25-a014-9b0dbfeda434** [sagemath/sage#31733]
<div id="comment:0"></div>

Stale link?

https://github.com/sagemath/sagetrac-mirror/blob/develop/build/pkgs/flintqs/SPKG.rst

https://github.com/sagemath/documentation/blob/445b7aef505eabde274d2489c4d3beeea7c5f314/html/en/reference/spkg/flintqs.html#L63

Cross-ref: https://github.com/sagemath/documentation/issues/25

CC:  @slel @wbhart

Component: **packages: standard**

Keywords: **flintQS**

_Issue created by migration from https://trac.sagemath.org/ticket/31733_

**Comment by 863a3e0b-4984-4e25-a014-9b0dbfeda434** [comment]
Description changed:
``````diff
--- 
+++ 
@@ -1,4 +1,6 @@
 Stale link?
+
+https://github.com/sagemath/sagetrac-mirror/blob/develop/build/pkgs/flintqs/SPKG.rst
 
 https://github.com/sagemath/documentation/blob/445b7aef505eabde274d2489c4d3beeea7c5f314/html/en/reference/spkg/flintqs.html#L63
 
``````

**Comment by DaveWitteMorris** [comment]
<div id="comment:7" align="right">comment:7</div>

Perhaps we should link to the archived page at https://web.archive.org/web/20200506164219/http://www.friedspace.com/QS/

**Comment by mkoeppe** [comment]
Outdated: package was removed in #35419
