### ISSUE TITLE
MIPVariable: Change to a subclass of FiniteFamily

### ISSUE THREAD

**Issue by mkoeppe** [sagemath/sage#31750]
<div id="comment:0"></div>

... to give it a richer set of operations, such as `len()` to get the number of components and an implementation of `.inverse_family()` to allow looking up the key of a given component (`LinearFunction` instance).

This requires making `AbstractFamily` and `FiniteFamily` Cython classes.

Depends on #34839

CC:  @yuan-zhou @tscrim @mantepse

Component: **linear programming**

Author: **Matthias Koeppe**

_Issue created by migration from https://trac.sagemath.org/ticket/31750_

**Comment by mkoeppe** [comment]
Description changed:
``````diff
--- 
+++ 
@@ -1,3 +1,4 @@
 ... to give it a richer set of operations, such as `len()` to get the number of components and an implementation of `.inverse_family()` to allow looking up the key of a given component (`LinearFunction` instance).
 
+This requires making `AbstractFamily` and `FiniteFamily` Cython classes.
 
``````

**Comment by mkoeppe** [comment]
Author: **Matthias Koeppe**

**Comment by mkoeppe** [comment]
Branch: **[u/mkoeppe/mipvariable__change_to_a_subclass_of_finitefamily](https://github.com/sagemath/sagetrac-mirror/tree/u/mkoeppe/mipvariable__change_to_a_subclass_of_finitefamily)**

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
Commit: **[`3beb977`](https://github.com/sagemath/sagetrac-mirror/commit/3beb9779f2278fa75961784ca22c219d1aaeef9e)**

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
<div id="comment:9"></div>

Branch pushed to git repo; I updated commit sha1. This was a forced push. New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/96366a667a5d91663dd9b3be660a4a015653ae91"><code>96366a6</code></a></td><td><code>sage.sets.family: Cythonize</code></td></tr><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/3beb9779f2278fa75961784ca22c219d1aaeef9e"><code>3beb977</code></a></td><td><code>MIPVariable: Make it a subclass of FiniteFamily</code></td></tr></table>

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
<div id="comment:10"></div>

Branch pushed to git repo; I updated commit sha1. New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/a278c804bd605dcaf656adfc8448a5a7d5e68a84"><code>a278c80</code></a></td><td><code>src/sage/sets/family.py: Update copyright according to git blame -w --date=format:%Y FILE | sort -k2</code></td></tr><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/11aeb808166506e4f733f221b2fa28f8bb477b09"><code>11aeb80</code></a></td><td><code>sage.sets.family: Fix pickling</code></td></tr></table>

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
Changed commit from **[`3beb977`](https://github.com/sagemath/sagetrac-mirror/commit/3beb9779f2278fa75961784ca22c219d1aaeef9e)** to **[`11aeb80`](https://github.com/sagemath/sagetrac-mirror/commit/11aeb808166506e4f733f221b2fa28f8bb477b09)**

**Comment by mkoeppe** [comment]
<div id="comment:11" align="right">comment:11</div>


```
sage -t --random-seed=163374757519390176193284183888236547352 doc/en/thematic_tutorials/lie/weyl_groups.rst  # 2 doctests failed
sage -t --random-seed=163374757519390176193284183888236547352 sage/algebras/fusion_rings/fusion_ring.py  # 17 doctests failed
sage -t --random-seed=163374757519390176193284183888236547352 sage/algebras/iwahori_hecke_algebra.py  # 3 doctests failed
sage -t --random-seed=163374757519390176193284183888236547352 sage/algebras/lie_algebras/nilpotent_lie_algebra.py  # 10 doctests failed
sage -t --random-seed=163374757519390176193284183888236547352 sage/algebras/lie_algebras/quotient.py  # 7 doctests failed
sage -t --random-seed=163374757519390176193284183888236547352 sage/algebras/lie_algebras/subalgebra.py  # 4 doctests failed
sage -t --random-seed=163374757519390176193284183888236547352 sage/categories/finite_dimensional_algebras_with_basis.py  # 26 doctests failed
sage -t --random-seed=163374757519390176193284183888236547352 sage/categories/finite_dimensional_lie_algebras_with_basis.py  # 3 doctests failed
sage -t --random-seed=163374757519390176193284183888236547352 sage/categories/finite_dimensional_semisimple_algebras_with_basis.py  # 9 doctests failed
sage -t --random-seed=163374757519390176193284183888236547352 sage/categories/lie_algebras.py  # 2 doctests failed
sage -t --random-seed=163374757519390176193284183888236547352 sage/groups/lie_gps/nilpotent_lie_group.py  # 2 doctests failed
sage -t --random-seed=163374757519390176193284183888236547352 sage/modules/with_basis/morphism.py  # 1 doctest failed
sage -t --random-seed=163374757519390176193284183888236547352 sage/modules/with_basis/subquotient.py  # 2 doctests failed
sage -t --random-seed=163374757519390176193284183888236547352 sage/sets/family.pyx  # 1 doctest failed
```

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
Changed commit from **[`11aeb80`](https://github.com/sagemath/sagetrac-mirror/commit/11aeb808166506e4f733f221b2fa28f8bb477b09)** to **[`d312578`](https://github.com/sagemath/sagetrac-mirror/commit/d312578e1c9215ac602a7d26feccfb4fd4ce1032)**

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
<div id="comment:12"></div>

Branch pushed to git repo; I updated commit sha1. New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/d312578e1c9215ac602a7d26feccfb4fd4ce1032"><code>d312578</code></a></td><td><code>src/sage/sets/family.pxd: Make attributes public</code></td></tr></table>

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
Changed commit from **[`d312578`](https://github.com/sagemath/sagetrac-mirror/commit/d312578e1c9215ac602a7d26feccfb4fd4ce1032)** to **[`450f9c6`](https://github.com/sagemath/sagetrac-mirror/commit/450f9c63e05cae3661f147c6bb54b9137cf15bf6)**

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
<div id="comment:13"></div>

Branch pushed to git repo; I updated commit sha1. New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/450f9c63e05cae3661f147c6bb54b9137cf15bf6"><code>450f9c6</code></a></td><td><code>Make FiniteFamily a Python subclass of FiniteFamily_base - so that EnumeratedSets mixins work correctly</code></td></tr></table>

**Comment by mkoeppe** [comment]
Dependencies: **#34839**

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
<div id="comment:15"></div>

Branch pushed to git repo; I updated commit sha1. New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/d302a628936a965d4e5c3501b7989028274fac95"><code>d302a62</code></a></td><td><code>tox.ini, src/tox.ini: Adjust to tox 4, autoprovision tox >= 3.18</code></td></tr><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/f8703aeba13b8663e55b46494dec4fd305e65374"><code>f8703ae</code></a></td><td><code>.github/workflows/lint.yml: Invoke tox with --</code></td></tr><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/9d76204fb5801054755b2e7bc54aeb6743742ced"><code>9d76204</code></a></td><td><code>fix some rst issues in sage_docbuild and sage_setup</code></td></tr><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/70da140f5f430c1cab53a858a8b33d43d23baf1e"><code>70da140</code></a></td><td><code>Merge branch 'u/chapoton/support_tox_4' in 9.8.b6</code></td></tr><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/8b2ada9af6a29fc808b23df0dbc6c7b1a2f64237"><code>8b2ada9</code></a></td><td><code>Merge #34839</code></td></tr></table>

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
Changed commit from **[`450f9c6`](https://github.com/sagemath/sagetrac-mirror/commit/450f9c63e05cae3661f147c6bb54b9137cf15bf6)** to **[`8b2ada9`](https://github.com/sagemath/sagetrac-mirror/commit/8b2ada9af6a29fc808b23df0dbc6c7b1a2f64237)**

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
Changed commit from **[`8b2ada9`](https://github.com/sagemath/sagetrac-mirror/commit/8b2ada9af6a29fc808b23df0dbc6c7b1a2f64237)** to **[`02ffd0a`](https://github.com/sagemath/sagetrac-mirror/commit/02ffd0a92969d389c3918f96bae73712cd1a7fe3)**

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
<div id="comment:16"></div>

Branch pushed to git repo; I updated commit sha1. New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/e521c9c85214e9f9e0b4854d19905916e4cb8a12"><code>e521c9c</code></a></td><td><code>Revert "Make FiniteFamily a Python subclass of FiniteFamily_base - so that EnumeratedSets mixins work correctly"</code></td></tr><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/02ffd0a92969d389c3918f96bae73712cd1a7fe3"><code>02ffd0a</code></a></td><td><code>FiniteFamily: Simpler solution that makes EnumeratedSets mixins work correctly</code></td></tr></table>

**Comment by mkoeppe** [comment]
Removed branch from issue description; replaced by PR #35121
