### ISSUE TITLE
Stop loading all installed GAP packages

### ISSUE THREAD

**Issue by antonio-rojas** [sagemath/sage#31761]
<div id="comment:0"></div>

On a fresh run of the GAP interface, Sage caches a GAP workspace which loads every single GAP package on the system. While this might be OK with Sage's trimmed-down version of gap_packages, if using a system GAP install 
with all optional packages installed this can take a massive amount of memory (~1GB with all packages included in the 4.11.1 tarball), which in many casses surpasses the default gap_memory_pool_size value, causing crashes. This will become a common issue once #29644 is merged.

Possible solutions:

1) Don't preload packages in Sage and let GAP load its default list of packages

2) Load a hardcoded list of packages (such as those installed by the gap and gap_packages spkg's)

CC:  @dimpase

Component: **packages: standard**

_Issue created by migration from https://trac.sagemath.org/ticket/31761_

**Comment by antonio-rojas** [comment]
Description changed:
``````diff
--- 
+++ 
@@ -2,6 +2,8 @@
 with all optional packages installed this can take a massive amount of memory (~1GB with all packages included in the 4.11.1 tarball), which in many casses surpasses the default gap_memory_pool_size value, causing crashes. This will become a common issue once #29644 is merged.
 
 Possible solutions:
+
 1) Don't preload packages in Sage and let GAP load its default list of packages
+
 2) Load a hardcoded list of packages (such as those installed by the gap and gap_packages spkg's)
 
``````

**Comment by orlitzky** [comment]
This is partially done in https://github.com/sagemath/sage/pull/36792, where the GAP interface and libgap are both now initialized with `-A`, and each has its own explicit list of auto-loaded packages. For example, `src/sage/ext_data/gap/sage.g ` now ends with,

```
# Load the GAP packages that GAP itself tries to autoload in the
# default configuration (see "PackagesToLoad" in lib/package.gi). The
# combination of passing -A to gap and these LoadPackage statements
# allows us to load the usual set of packages, but only if they are
# installed. So most people will get exactly the default behavior,
# but minimal installations won't throw warnings and fail tests.
_autoloads := [ "autpgrp", "alnuth", "crisp", "ctbllib", "factint", "fga",
                "irredsol", "laguna", "polenta", "polycyclic", "resclasses",
                "sophus", "tomlib" ];
for p in _autoloads do
  LoadPackage(p);
od;
```

I say "partially" though because I missed `gap_reset_workspace()`. It's still trying to load all installed packages.

I don't really know why we need to load anything in `gap_reset_workspace()` in the first place. Does `Gap(use_workspace_cache=False, max_workspace_size=None)` not go through the usual interface/libgap initialization?

**Comment by antonio-rojas** [comment]
Actually, with https://github.com/sagemath/sage/pull/36792 applied, the memory situation seems to be much better. The size of the saved workspace seems to be roughly the same with or without all gap-packages installed.

The issues now are caused by extra packages which are *optionally* (if present) loaded by standard packages which are themselves loaded by Sage. For instance, I'm getting doctest hangs in many modules. The backtrace shows that the hang is happening in 
```
/usr/lib/gap/pkg/browse/bin/x86_64-pc-linux-gnu-default64-kv8/ncurses.so
```
from the optional `browse` package, which is itself (optionally) loaded from `ctbllib`. Needs more investigation.

**Comment by orlitzky** [comment]
> from the optional `browse` package, which is itself (optionally) loaded from `ctbllib`. Needs more investigation.

I was just working on this package last night. It somehow manages to trash my terminal when I run the (GAP) test suites for browse, ctbllib, or spinsym. I worked around it by piping the output to tee; when stdout is not a tty, it leaves my terminal intact and thankfully the tests all still pass. Not the same problem, but maybe it's related.

**Comment by orlitzky** [comment]
> For instance, I'm getting doctest hangs in many modules. The backtrace shows that the hang is happening in
> 
> ```
> /usr/lib/gap/pkg/browse/bin/x86_64-pc-linux-gnu-default64-kv8/ncurses.so
> ```
> 
> from the optional `browse` package, which is itself (optionally) loaded from `ctbllib`. Needs more investigation.

Now that I've finished packaging everything, I have the same problem in the test suite.

The only reason I packaged `browse` in the first place is because the ctbllib test suite is horrendously slow without it. But this has me wondering which is the lesser evil.

**Comment by orlitzky** [comment]
FWIW the hangs from the Browse package can be avoided with e.g.

```
$ sage -t --all --long --timeout=0 2>&1 | tee logs/stdboth.log
```

it may be redirected to the clobbered terminal issue I ran into earlier, since that was also fixed with a `tee`.
