### ISSUE TITLE
Upgrade pcre to pcre2

### ISSUE THREAD

**Issue by orlitzky** [sagemath/sage#32231]
<div id="comment:0"></div>

Our "pcre" package exists only as a dependency of R as far as I can tell, and has been replaced by pcre2 (https://www.pcre.org/) both upstream and within R. We should use the newer library instead.

Component: **packages: standard**

_Issue created by migration from https://trac.sagemath.org/ticket/32231_

**Comment by mkoeppe** [comment]
No longer needed as we have reduced our `r` package to "dummy".
