### ISSUE TITLE
Use GNU Info to parse singular's Info file

### ISSUE THREAD

**Issue by orlitzky** [sagemath/sage#32242]
<div id="comment:0"></div>

Our Singular interface currently contains a hand-written parser for Singular's "info" file. In this ticket, we add an optional GNU Info package to parse this file instead.

Relative to running "info", the hand-written parser has several drawbacks:

* The extra code is a maintenance burden. We should not be wasting
  our time (poorly) reimplementing standard tools.

* The custom parser is buggy. For example, it is supposed to raise a
  `KeyError` when documentation for a non-existent function is
  requested. However, the parser does not keep track of what section
  it's in, so, for example, `get_docstring("Preface")` will happily
  return the contents of the preface even though "Preface" is not a
  Singular function.

* The first time documentation is requested, the entire info file
  (see above) is loaded into a dictionary. With the Singular info
  file currently weighing in at around 11MiB, this is wasting a
  good chunk of memory.

* The `singular_console()` itself tries to launch GNU Info to display
  its interactive help, and cannot use our hand-written parser.

The one downside to requiring "info" is that it would add a new runtime dependency to sagelib. To avoid that, we make GNU Info optional, and suggest to the user that he install it when he tries to read Singular's documentation.

GNU Info (or its superset, Texinfo) are widespread, portable, and easy to install on all of the systems we support, so in most cases this should be a "free" improvement.

Depends on #32302

Component: **packages: standard**

Author: **Michael Orlitzky**

Branch/Commit: **[u/mjo/ticket/32242](https://github.com/sagemath/sagetrac-mirror/tree/u/mjo/ticket/32242) @ [`137a918`](https://github.com/sagemath/sagetrac-mirror/commit/137a9182a02d4aa329a78c2e936b48431c1e9017)**

_Issue created by migration from https://trac.sagemath.org/ticket/32242_

**Comment by orlitzky** [comment]
Description changed:
``````diff
--- 
+++ 
@@ -1,6 +1,25 @@
-In the description of #29024, a few problems are listed as prerequisites for accepting a system installation of Singular. Basically, they ask that we either use singular in a less crazy manner, or find a way to make our existing hacks work with a system copy of singular.
+Our Singular interface currently contains a hand-written parser for Singular's "info" file. In this ticket, we add an optional GNU Info package to parse this file instead.
 
-One of those issues is that the `sage/interfaces/singular.py` is using an environment variable `SINGULARPATH` to guess at the location where Singular's Info file is installed, so that it can be manually parsed.
+Relative to running "info", the hand-written parser has several drawbacks:
 
-In the interest of using Singular in a less crazy manner, I propose we add the standalone GNU "info" as a new package, and use it to read Singular's documentation from wherever it is configured to do so. This eliminates two of the problems in #29024.
+* The extra code is a maintenance burden. We should not be wasting
+  our time (poorly) reimplementing standard tools.
 
+* The custom parser is buggy. For example, it is supposed to raise a
+  `KeyError` when documentation for a non-existent function is
+  requested. However, the parser does not keep track of what section
+  it's in, so, for example, `get_docstring("Preface")` will happily
+  return the contents of the preface even though "Preface" is not a
+  Singular function.
+
+* The first time documentation is requested, the entire info file
+  (see above) is loaded into a dictionary. With the Singular info
+  file currently weighing in at around 11MiB, this is wasting a
+  good chunk of memory.
+
+* The `singular_console()` itself tries to launch GNU Info to display
+  its interactive help, and cannot use our hand-written parser.
+
+The one downside to requiring "info" is that it would add a new runtime dependency to sagelib. To avoid that, we make GNU Info optional, and suggest to the user that he install it when he tries to read Singular's documentation.
+
+GNU Info (or its superset, Texinfo) are widespread, portable, and easy to install on all of the systems we support, so in most cases this should be a "free" improvement.
``````

**Comment by mkoeppe** [comment]
I think this should be closed as not wanted

**Comment by orlitzky** [comment]
Are you still opposed to this now that `info` is a standard package?

For the sage distribution, there's no additional runtime dependency because sage doesn't distinguish between build- and run-time dependencies; texinfo will be installed anyway.

On a linux distribution, texinfo will already be a runtime dependency of singular, because singular uses `info` for its interactive help. (It should really be a dependency of the singular SPKG if we expect `singular_console()` or `sage --singular` to work).

 I'm asking because I discovered another minor issue:

* The `info` program supports compression, but our hand-rolled parser doesn't.

**Comment by mkoeppe** [comment]
> Are you still opposed to this now that `info` is a standard package?

Yes, because https://github.com/sagemath/sage/issues/32242#issuecomment-1418140192 still applies -- it would be a new obstacle to pip-installability

**Comment by orlitzky** [comment]
I don't see pip/pypi as different from a linux distribution and its package manager in this scenario. How does singular get installed by pip? Does its interactive help work?

This really only affects interactive uses of sage and not the library itself. (Yes, you can access a docstring programmatically, but realistically...). If singular's interactive help doesn't work, I don't think it's reasonable to expect its help to work interactively through sage, either. Especially not if it brings extra costs along with it, those mentioned in the initial issue, and now the fact that we have to ensure that  `/usr/share/info/singular.info` is decompressed too.

**Comment by mkoeppe** [comment]
Singular will be shipped by the wheel of the distribution sagemath-symbolics (in prep at #35095)

I'm making all of Sage pip-installable, including interactive uses (that's provided by [sagemath-repl](https://pypi.org/project/sagemath-repl/))

**Comment by orlitzky** [comment]
Then aren't you going to find yourself in the same situation that linux distributions do? If we try (from our perspectives also as sage developers) to pretend that `info` isn't a dependency of singular, then attempting to use singular on its own will have a degraded experience, i.e. no help. That's a problem when you run `singular` independently from the CLI, but also when you run `sage --singular` or `sage: singular_console()`. The latter two should be deprecated IMO, but the bottom line is that if singular is a part of sage, then we have to install a usable singular.

**Comment by mkoeppe** [comment]
The purpose of shipping Singular in the pip-installable wheel will not be to provide a standalone Singular experience; only to use sage.libs.singular and sage.interfaces.singular

> when you run `sage --singular` or `sage: singular_console()`. The latter two should be deprecated IMO

I agree with this; in particular the consoles don't work within Jupyter.

**Comment by orlitzky** [comment]
> The purpose of shipping Singular in the pip-installable wheel will not be to provide a standalone Singular experience; only to use sage.libs.singular and sage.interfaces.singular

Ok, I at least know what we're talking about now, but I still think it's a long shot:

1. sage has to be made pip-installable
2. user has to _choose_ to install sage via pip
3. user wants to use the singular interface
4. user doesn't have `info` installed on his operating system
6. the **interactive** help for the singular interface is a hard requirement

All of those have to hold for the absence of the hand-rolled parser to become a problem. On the other hand, replacing it would immediately benefit the rest of us who actually use and develop sage right now.

**Comment by mkoeppe** [comment]
> replacing it would immediately benefit the rest of us who actually use and develop sage right now.

I'd say this is an exaggeration. None of the drawbacks listed in the issue description are user-visible at all.

If `info` was intended to be used programmatically, there would be a shared library offering that functionality.

But `info` really is just a standalone alternative to the info browser in Emacs (which, of course, reads in the info format using emacs lisp.)

**Comment by orlitzky** [comment]
> If info was intended to be used programmatically, there would be a shared library offering that functionality.

I'm using `info` in the exact same way that singular itself does. The singular manual is designed with command-line `info` in mind. This is the closest thing to an "official" way to parse it that there is.

**Comment by mkoeppe** [comment]
> I'm using `info` in the exact same way that singular itself does.

Not true. Singular runs `info` as an interactive program (when no other help facility configured in `help.cnf` is available).

**Comment by orlitzky** [comment]
Ok, I should have said _executing_ instead of _using_. You're choosing to focus on irrelevant details in the arguments I've made instead of the arguments themselves.

**Comment by mkoeppe** [comment]
Also, `info` is in no way "more official" than other parsers of the format. The format was invented for Emacs in the 1980s. The standalone info browser is much younger.

**Comment by orlitzky** [comment]
What I meant is that calling `info` with the name of the node is the closest thing there is to an official way to get to the correct documentation, because that's what singular itself does. The hand-rolled parser makes mistakes (see the original description), and while launching `info --node` might feel a little unprincipled compared to a _well-written_ parser, the fact that we're using what singular uses makes up for it.

**Comment by mkoeppe** [comment]
I don't think a "well-written parser" for info would look much different. The format *is* designed to be trivial to read by line-by-line text scanning. Sure, some of our regexes are ad hoc and not using the spec - https://www.gnu.org/software/texinfo/manual/texinfo/texinfo.html#Info-Format-Specification.

**Comment by orlitzky** [comment]
But like, there's already a well-written parser installed on everyone's machines, and it already transparently decompresses gzip, xz, bzip2, lzip, and lzma files. Why write another one and then ship it with sage to avoid making the first one a dependency of sage?
