### ISSUE TITLE
arb.h in arb/ on Fedora

### ISSUE THREAD

**Issue by dimpase** [sagemath/sage#32376]
<div id="comment:0"></div>

Fedora puts `arb.h` in arb/ subdirectory.
This means this has to be dealt in some way, if we want to use arb system library.

Issues for packages depending on arb:
- https://github.com/symengine/symengine/issues/1815
- https://github.com/flatsurf/e-antic/issues/200

Upstream: **Reported upstream. No feedback yet.**

CC:  @orlitzky @mkoeppe @jamesjer

Component: **build: configure**

_Issue created by migration from https://trac.sagemath.org/ticket/32376_

**Comment by mkoeppe** [comment]
Description changed:
``````diff
--- 
+++ 
@@ -1,2 +1,2 @@
-Fedora 35 puts `arb.h` in arb/ subdirectory.
+Fedora puts `arb.h` in arb/ subdirectory.
 This means this has to be dealt in some way, if we want to use arb system library.
``````

**Comment by mkoeppe** [comment]
Description changed:
``````diff
--- 
+++ 
@@ -1,2 +1,6 @@
 Fedora puts `arb.h` in arb/ subdirectory.
 This means this has to be dealt in some way, if we want to use arb system library.
+
+Issues for packages depending on arb:
+- https://github.com/symengine/symengine/issues/1815
+- https://github.com/flatsurf/e-antic/issues/200
``````

**Comment by mkoeppe** [comment]
Can this be closed after our move to FLINT 3?
