### ISSUE TITLE
Add half-angle transformations

### ISSUE THREAD

**Issue by 7822f248-ba56-45f1-ab3d-4de7482bdf9f** [sagemath/sage#32389]
<div id="comment:0"></div>

In some circumstances (e.g. integration),
it may be useful to rewrite

- expressions in sin(x), cos(x), etc.
  as expressions in tan(x/2),
- expressions in sinh(x), cosh(x), etc.
  as expressions in tanh(x/2)

This ticket implements a method
for this transformation.

CC:  @slel

Component: **symbolics**

Author: **Emmanuel Charpentier, Samuel Lelièvre**

Branch/Commit: **[u/slelievre/32389](https://github.com/sagemath/sagetrac-mirror/tree/u/slelievre/32389) @ [`a60e101`](https://github.com/sagemath/sagetrac-mirror/commit/a60e101f5ff5cd08baa787e29b3b3e02d3e1cc6f)**

Reviewer: **Samuel Lelièvre, Emmanuel Charpentier**

_Issue created by migration from https://trac.sagemath.org/ticket/32389_

**Comment by slel** [comment]
Description changed:
``````diff
--- 
+++ 
@@ -1,3 +1,10 @@
-In some circumstances (e. g. integration), it may be useful to replace expressions in sin(h)(x), cos(h)(x), etc... as expressions in tan(h)(x/2).
+In some circumstances (e.g. integration),
+it may be useful to rewrite
 
-This ticket implements a method for this transformation.
+- expressions in sin(x), cos(x), etc.
+  as expressions in tan(x/2),
+- expressions in sinh(x), cosh(x), etc.
+  as expressions in tanh(x/2)
+
+This ticket implements a method
+for this transformation.
``````
