### ISSUE TITLE
Add derivative operator

### ISSUE THREAD

**Issue by spaghettisalat** [sagemath/sage#32554]
<div id="comment:0"></div>

Currently, the output of a derivative of a symbolic function has the annoying property that sagemath cannot read it back as input, for example the following does not work because `D` is not defined.

```
sage: function('f'); var('x y')                                                                                                                                                                                                
sage: diff(f(x+y),x)                                                                                                                                                                                               
D[0](f)(x + y)
sage: D[0](f)(x + 2*y)
```

This ticket implements such a derivative operator that fixes this inconsistency.

Component: **symbolics**

Author: **Marius Gerbershagen**

_Issue created by migration from https://trac.sagemath.org/ticket/32554_

**Comment by mkoeppe** [comment]
Branch has merge conflicts

**Comment by spaghettisalat** [comment]
A branch where the merge conflicts are fixed is available at https://gitlab.com/spaghettisalat/sage/-/commits/public/derivative-operator. I would've updated the branch here on github but it seems that I lack permissions to do so.

**Comment by mkoeppe** [comment]
The procedure is to open a PR here and link it with this Issue.

**Comment by mkoeppe** [comment]
Removed branch from issue description; replaced by PR #35193
