### ISSUE TITLE
[mixed review] soname and correct -fPIC handling for zn_poly

### ISSUE THREAD

**Issue by timabbott** [sagemath/sage#3256]
<div id="comment:0"></div>

I've attached a patch (developed with Francois Bissey) that should make zn_poly have shared library versioning and build the shared library with -fPIC but the static library without -fPIC.

My patch includes the relevant changes to the Debian packaging to make it fully Debian policy-compliant.

It also includes the relevant changes to spkg-install and SAGE-style copy patches that should make SAGE use the new version, though I haven't tested that part.

CC:  @kiwifb @sagetrac-dmharvey

Component: **packages: standard**

Keywords: **editor_mabshoff**

_Issue created by migration from https://trac.sagemath.org/ticket/3256_

**Comment by mkoeppe** [comment]
Closing as outdated - we have removed the package in the meantime.
