### ISSUE TITLE
Deprecate is_FiniteField etc., make sage.rings.finite_rings a namespace package

### ISSUE THREAD

**Issue by mkoeppe** [sagemath/sage#32664]
<div id="comment:0"></div>

Part of meta-ticket #32414.

Deprecating `is_FiniteField`, `is_PrimeFiniteField`, and `is_FiniteFieldElement` is done for uniformity but is not needed to support modularization. #32432 shows that `sage.rings.finite_rings.finite_field_base` (which defines the ABC `FiniteField`) can be imported without pulling in implementation classes.

`sage.rings.finite_rings` must become a namespace package because element implementations depend on various libraries.

CC:  @dimpase @kwankyu @fchapoton @tscrim

Component: **refactoring**

Author: **Matthias Koeppe**

_Issue created by migration from https://trac.sagemath.org/ticket/32664_

**Comment by mkoeppe** [comment]
Description changed:
``````diff
--- 
+++ 
@@ -1 +1,4 @@
 Part of meta-ticket #32414.
+
+This is done for uniformity but is not needed to support modularization. #32432 shows that `finite_field_base` (which defines `is_FiniteField`) can be imported without pulling in implementation classes.
+
``````

**Comment by mkoeppe** [comment]
Changed dependencies from **#32612** to none

**Comment by mkoeppe** [comment]
Description changed:
``````diff
--- 
+++ 
@@ -1,4 +1,5 @@
 Part of meta-ticket #32414.
 
-This is done for uniformity but is not needed to support modularization. #32432 shows that `finite_field_base` (which defines `is_FiniteField`) can be imported without pulling in implementation classes.
+Deprecating `is_FiniteField` is done for uniformity but is not needed to support modularization. #32432 shows that `sage.finitefinite_field_base` (which defines the ABC `FiniteField`) can be imported without pulling in implementation classes.
 
+`sage.rings.finite_rings` must become a namespace package because element implementations depend on various libraries.
``````

**Comment by mkoeppe** [comment]
Description changed:
``````diff
--- 
+++ 
@@ -1,5 +1,5 @@
 Part of meta-ticket #32414.
 
-Deprecating `is_FiniteField` is done for uniformity but is not needed to support modularization. #32432 shows that `sage.finitefinite_field_base` (which defines the ABC `FiniteField`) can be imported without pulling in implementation classes.
+Deprecating `is_FiniteField` is done for uniformity but is not needed to support modularization. #32432 shows that `sage.rings.finite_rings.finite_field_base` (which defines the ABC `FiniteField`) can be imported without pulling in implementation classes.
 
 `sage.rings.finite_rings` must become a namespace package because element implementations depend on various libraries.
``````

**Comment by mkoeppe** [comment]
Branch: **[u/mkoeppe/add_sage_rings_abc_finitefield__deprecate_is_finitefield](https://github.com/sagemath/sagetrac-mirror/tree/u/mkoeppe/add_sage_rings_abc_finitefield__deprecate_is_finitefield)**

**Comment by mkoeppe** [comment]
Description changed:
``````diff
--- 
+++ 
@@ -1,5 +1,5 @@
 Part of meta-ticket #32414.
 
-Deprecating `is_FiniteField` is done for uniformity but is not needed to support modularization. #32432 shows that `sage.rings.finite_rings.finite_field_base` (which defines the ABC `FiniteField`) can be imported without pulling in implementation classes.
+Deprecating `is_FiniteField` and `is_PrimeFiniteField` is done for uniformity but is not needed to support modularization. #32432 shows that `sage.rings.finite_rings.finite_field_base` (which defines the ABC `FiniteField`) can be imported without pulling in implementation classes.
 
 `sage.rings.finite_rings` must become a namespace package because element implementations depend on various libraries.
``````

**Comment by mkoeppe** [comment]
Commit: **[`8af57c4`](https://github.com/sagemath/sagetrac-mirror/commit/8af57c4d497d0b5cb4aca92346d02d97a1236a0a)**

**Comment by mkoeppe** [comment]
<div id="comment:5"></div>

New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/8af57c4d497d0b5cb4aca92346d02d97a1236a0a"><code>8af57c4</code></a></td><td><code>sage.rings.finite_rings: Deprecate is_FiniteField, is_PrimeFiniteField</code></td></tr></table>

**Comment by mkoeppe** [comment]
Author: **Matthias Koeppe**

**Comment by mkoeppe** [comment]
Description changed:
``````diff
--- 
+++ 
@@ -1,5 +1,5 @@
 Part of meta-ticket #32414.
 
-Deprecating `is_FiniteField` and `is_PrimeFiniteField` is done for uniformity but is not needed to support modularization. #32432 shows that `sage.rings.finite_rings.finite_field_base` (which defines the ABC `FiniteField`) can be imported without pulling in implementation classes.
+Deprecating `is_FiniteField`, `is_PrimeFiniteField`, and `is_FiniteFieldElement` is done for uniformity but is not needed to support modularization. #32432 shows that `sage.rings.finite_rings.finite_field_base` (which defines the ABC `FiniteField`) can be imported without pulling in implementation classes.
 
 `sage.rings.finite_rings` must become a namespace package because element implementations depend on various libraries.
``````

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
<div id="comment:8"></div>

Branch pushed to git repo; I updated commit sha1. New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/98b433c74762d434e53529955855e2f40e27ce41"><code>98b433c</code></a></td><td><code>sage.rings.finite_rings: Make it a namespace package</code></td></tr><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/6323775b68af5bc8896ae376c5d3197208c2db32"><code>6323775</code></a></td><td><code>src/sage/rings/finite_rings/finite_field_constructor.py: Restore re-export of is_FiniteField</code></td></tr><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/473e9d46aa95a34f1cea2aac0d7b0b8d3aea88a7"><code>473e9d4</code></a></td><td><code>src/sage/rings/finite_rings/hom_finite_field.pyx: Import ABC as FiniteField_base</code></td></tr><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/b82fb1e4e304238b30b907ab284c21388601a3dc"><code>b82fb1e</code></a></td><td><code>sage.rings.finite_rings: Deprecate is_FiniteFieldElent</code></td></tr></table>

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
Changed commit from **[`8af57c4`](https://github.com/sagemath/sagetrac-mirror/commit/8af57c4d497d0b5cb4aca92346d02d97a1236a0a)** to **[`b82fb1e`](https://github.com/sagemath/sagetrac-mirror/commit/b82fb1e4e304238b30b907ab284c21388601a3dc)**

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
Changed commit from **[`b82fb1e`](https://github.com/sagemath/sagetrac-mirror/commit/b82fb1e4e304238b30b907ab284c21388601a3dc)** to **[`106b22e`](https://github.com/sagemath/sagetrac-mirror/commit/106b22e357b7c5effd84397b5f3ccc60933d5621)**

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
<div id="comment:9"></div>

Branch pushed to git repo; I updated commit sha1. New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/106b22e357b7c5effd84397b5f3ccc60933d5621"><code>106b22e</code></a></td><td><code>Fixups</code></td></tr></table>

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
Changed commit from **[`106b22e`](https://github.com/sagemath/sagetrac-mirror/commit/106b22e357b7c5effd84397b5f3ccc60933d5621)** to **[`de5cfad`](https://github.com/sagemath/sagetrac-mirror/commit/de5cfad4dbc3568ef0d3c065604b533dff03cdf3)**

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
<div id="comment:10"></div>

Branch pushed to git repo; I updated commit sha1. New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/de5cfad4dbc3568ef0d3c065604b533dff03cdf3"><code>de5cfad</code></a></td><td><code>Fixups</code></td></tr></table>

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
Changed commit from **[`de5cfad`](https://github.com/sagemath/sagetrac-mirror/commit/de5cfad4dbc3568ef0d3c065604b533dff03cdf3)** to **[`429b372`](https://github.com/sagemath/sagetrac-mirror/commit/429b3729335e04428f94a3213aacf3939cd1e6f0)**

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
<div id="comment:11"></div>

Branch pushed to git repo; I updated commit sha1. New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/429b3729335e04428f94a3213aacf3939cd1e6f0"><code>429b372</code></a></td><td><code>Fixup: Elements of finite fields are not instances of FieldElement</code></td></tr></table>

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
<div id="comment:13"></div>

Branch pushed to git repo; I updated commit sha1. New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/e633d8f1b69c3e5fd97eeafa43202a65bee45b32"><code>e633d8f</code></a></td><td><code>src/sage/crypto/mq/rijndael_gf.py: Fix imports</code></td></tr></table>

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
Changed commit from **[`429b372`](https://github.com/sagemath/sagetrac-mirror/commit/429b3729335e04428f94a3213aacf3939cd1e6f0)** to **[`e633d8f`](https://github.com/sagemath/sagetrac-mirror/commit/e633d8f1b69c3e5fd97eeafa43202a65bee45b32)**

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
Changed commit from **[`e633d8f`](https://github.com/sagemath/sagetrac-mirror/commit/e633d8f1b69c3e5fd97eeafa43202a65bee45b32)** to **[`886bc1a`](https://github.com/sagemath/sagetrac-mirror/commit/886bc1ac99c6a986e06192f2a86cd04a5869fe05)**

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
<div id="comment:14"></div>

Branch pushed to git repo; I updated commit sha1. This was a forced push. New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/886bc1ac99c6a986e06192f2a86cd04a5869fe05"><code>886bc1a</code></a></td><td><code>src/sage/crypto/mq/rijndael_gf.py: Fix imports</code></td></tr></table>

**Comment by dimpase** [comment]
<div id="comment:16" align="right">comment:16</div>

shouldn't this branch be based on #34804 ?

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
<div id="comment:17"></div>

Branch pushed to git repo; I updated commit sha1. This was a forced push. New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/53ede8c9bad73793c9431a51ac511eefa8c09eb2"><code>53ede8c</code></a></td><td><code>sage.rings.finite_rings: Deprecate is_FiniteField, is_PrimeFiniteField</code></td></tr><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/8d4d8e58683173fc9b452f9f3a8d764785ba1b36"><code>8d4d8e5</code></a></td><td><code>sage.rings.finite_rings: Make it a namespace package</code></td></tr><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/6ce26bc9f01f71faeb4a144a67b8487671cc45f5"><code>6ce26bc</code></a></td><td><code>src/sage/rings/finite_rings/finite_field_constructor.py: Restore re-export of is_FiniteField</code></td></tr><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/98a5484775ac1ec596baa9a3739499cf22cc61f0"><code>98a5484</code></a></td><td><code>src/sage/rings/finite_rings/hom_finite_field.pyx: Import ABC as FiniteField_base</code></td></tr><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/2e6b5efe57a925b6bd5c2d9b8ad49f7718e05af7"><code>2e6b5ef</code></a></td><td><code>sage.rings.finite_rings: Deprecate is_FiniteFieldElent</code></td></tr><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/3be7c975fb00896aef21d721eda69d6d22759385"><code>3be7c97</code></a></td><td><code>Fixups</code></td></tr><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/97a363e8cc60fc67718fad16d16ce583f24a7e0d"><code>97a363e</code></a></td><td><code>Fixups</code></td></tr><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/0c014033f33a907da6ba7c48224102e0ddd82af3"><code>0c01403</code></a></td><td><code>Fixup: Elements of finite fields are not instances of FieldElement</code></td></tr><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/9f4d1c4bd227c145d964bff1a4f40305f780be2d"><code>9f4d1c4</code></a></td><td><code>src/sage/crypto/mq/rijndael_gf.py: Fix imports</code></td></tr></table>

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
Changed commit from **[`886bc1a`](https://github.com/sagemath/sagetrac-mirror/commit/886bc1ac99c6a986e06192f2a86cd04a5869fe05)** to **[`9f4d1c4`](https://github.com/sagemath/sagetrac-mirror/commit/9f4d1c4bd227c145d964bff1a4f40305f780be2d)**

**Comment by mkoeppe** [comment]
<div id="comment:18" align="right">comment:18</div>

Replying to [Dima Pasechnik](#comment%3A16):
> shouldn't this branch be based on #34804 ?

There's no relation. #34804 merges cleanly with this branch

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
Changed commit from **[`9f4d1c4`](https://github.com/sagemath/sagetrac-mirror/commit/9f4d1c4bd227c145d964bff1a4f40305f780be2d)** to **[`9ebadcf`](https://github.com/sagemath/sagetrac-mirror/commit/9ebadcf81d3afe00b8114cc01cea3c413f0ab99f)**

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
<div id="comment:20"></div>

Branch pushed to git repo; I updated commit sha1. New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/9ebadcf81d3afe00b8114cc01cea3c413f0ab99f"><code>9ebadcf</code></a></td><td><code>Merge tag '9.8.beta6' into t/32664/add_sage_rings_abc_finitefield__deprecate_is_finitefield</code></td></tr></table>

**Comment by mkoeppe** [comment]
Tests ran successfully in https://github.com/sagemath/sagetrac-mirror/actions/runs/3860089783 (before the migration).

Needs review

**Comment by mkoeppe** [comment]
Removed branch from issue description; replaced by PR #35119
