### ISSUE TITLE
Filter singular system package out of tox.ini for homebrew

### ISSUE THREAD

**Issue by orlitzky** [sagemath/sage#32784]
<div id="comment:0"></div>

As a follow-up to #29024, we prevent the system singular from being used to run GH actions when the homebrew prefix is not `/usr/local` (which causes problems for its singular package).

CC:  @mkoeppe @dimpase

Component: **build**

Branch/Commit: **[u/mjo/ticket/32784](https://github.com/sagemath/sagetrac-mirror/tree/u/mjo/ticket/32784) @ [`e4aa49e`](https://github.com/sagemath/sagetrac-mirror/commit/e4aa49e31076b779c21193ba01e169f2779fba37)**

Reviewer: **Michael Orlitzky**

_Issue created by migration from https://trac.sagemath.org/ticket/32784_

**Comment by mkoeppe** [comment]
Changed author from **Michael Orlitzky** to none

**Comment by mkoeppe** [comment]
<div id="comment:9" align="right">comment:9</div>

No longer needed.

**Comment by orlitzky** [comment]
Reviewer: **Michael Orlitzky**
