### ISSUE TITLE
cython: Eliminate use of custom patches

### ISSUE THREAD

**Issue by mkoeppe** [sagemath/sage#32832]
<div id="comment:0"></div>

As noted in [#29665 comment:86](https://github.com/sagemath/sage/issues/29665#comment:86), our `cython` spkg uses custom patches:
- https://github.com/sagemath/sage-prod/tree/develop/build/pkgs/cython/patches

We should investigate whether they are still necessary.

Depends on #32985

Upstream: **Fixed upstream, but not in a stable release.**

CC:  @orlitzky @kiwifb @antonio-rojas @slel

Component: **packages: standard**

Author: **Michael Orlitzky**

_Issue created by migration from https://trac.sagemath.org/ticket/32832_

**Comment by orlitzky** [comment]
Changed commit from **[`78fe28c`](https://github.com/sagemath/sagetrac-mirror/commit/78fe28ce8b782928c44509e41c0bda7e9f3f3596)** to none

**Comment by orlitzky** [comment]
Changed branch from **[u/mjo/ticket/32832](https://github.com/sagemath/sagetrac-mirror/tree/u/mjo/ticket/32832)** to none

**Comment by orlitzky** [comment]
We beat this with cython-3.0.4.
