### ISSUE TITLE
Eliminate use of FLINT's NTL interface

### ISSUE THREAD

**Issue by mkoeppe** [sagemath/sage#32908]
<div id="comment:0"></div>

We currently insist that the FLINT library is built with its NTL interface.

This interface consists of just a few functions that could easily be provided instead by a small library separate from FLINT, or included in sagelib.  https://github.com/wbhart/flint2/blob/trunk/interfaces/NTL-interface.cpp

This could help with modularization. Also the use of NTL by Singular is minimal.

https://github.com/wbhart/flint2/issues/1039

CC:  @kiwifb @antonio-rojas

Component: **refactoring**

_Issue created by migration from https://trac.sagemath.org/ticket/32908_

**Comment by mkoeppe** [comment]
Description changed:
``````diff
--- 
+++ 
@@ -3,3 +3,6 @@
 This interface consists of just a few functions that could easily be provided instead by a small library separate from FLINT, or included in sagelib.  https://github.com/wbhart/flint2/blob/trunk/interfaces/NTL-interface.cpp
 
 This could help with modularization. Also the use of NTL by Singular is minimal.
+
+https://github.com/wbhart/flint2/issues/1039
+
``````

**Comment by mezzarobba** [comment]
Maybe no longer relevant now the NTL interface is header-only?
