### ISSUE TITLE
Upgrade: gc 8.0.6 and libatomic 7.6.12

### ISSUE THREAD

**Issue by slel** [sagemath/sage#32943]
<div id="comment:0"></div>

Releases:

- https://github.com/ivmai/bdwgc/releases
- https://github.com/ivmai/libatomic_ops/releases

Previous upgrade: #26287.

CC:  @antonio-rojas @dimpase @kiwifb @isuruf @mkoeppe @slel

Component: **packages: standard**

Keywords: **upgrade, gc, libatomic**

_Issue created by migration from https://trac.sagemath.org/ticket/32943_

**Comment by mkoeppe** [comment]
outdated
