### ISSUE TITLE
Upgrade to givaro-4.2.0 fflas-ffpack-2.5.0 linbox-1.7.0

### ISSUE THREAD

**Issue by ClementPernet** [sagemath/sage#32959]
<div id="comment:0"></div>

New packages are available here (with the corresponding checksums):

givaro: https://github.com/linbox-team/givaro/releases/tag/v4.2.0

fflas-ffpack: https://github.com/linbox-team/fflas-ffpack/releases/tag/v2.5.0

linbox: https://github.com/linbox-team/linbox/releases/tag/v1.7.0

The new versions require "a C++ compiler supporting C++11 standard. More precisely g++ v5 or greater, clang++ v3.4 or greater".
So this ticket depends on dropping support for some systems, see #32074.

Depends on #33316

CC:  @kiwifb @orlitzky

Component: **packages: standard**

Branch/Commit: **[u/cpernet/upgrade_to_givaro_4_2_0_fflas_ffpack_2_5_0_linbox_1_7_0](https://github.com/sagemath/sagetrac-mirror/tree/u/cpernet/upgrade_to_givaro_4_2_0_fflas_ffpack_2_5_0_linbox_1_7_0) @ [`4006e10`](https://github.com/sagemath/sagetrac-mirror/commit/4006e105dea890308f5b1d14366ecd779ca10b38)**

_Issue created by migration from https://trac.sagemath.org/ticket/32959_

**Comment by ClementPernet** [comment]
Description changed:
``````diff
--- 
+++ 
@@ -1 +1,5 @@
+New packages are available here (with the corresponding checksums):
 
+givaro: https://github.com/linbox-team/givaro/releases/tag/v4.2.0rc0
+fflas-ffpack: 
+linbox: 
``````

**Comment by ClementPernet** [comment]
Description changed:
``````diff
--- 
+++ 
@@ -1,5 +1,7 @@
 New packages are available here (with the corresponding checksums):
 
 givaro: https://github.com/linbox-team/givaro/releases/tag/v4.2.0rc0
+
 fflas-ffpack: 
+
 linbox: 
``````

**Comment by ClementPernet** [comment]
Description changed:
``````diff
--- 
+++ 
@@ -2,6 +2,6 @@
 
 givaro: https://github.com/linbox-team/givaro/releases/tag/v4.2.0rc0
 
-fflas-ffpack: 
+fflas-ffpack: https://github.com/linbox-team/fflas-ffpack/releases/tag/v2.5.0rc1
 
 linbox: 
``````

**Comment by ClementPernet** [comment]
Description changed:
``````diff
--- 
+++ 
@@ -1,7 +1,7 @@
 New packages are available here (with the corresponding checksums):
 
-givaro: https://github.com/linbox-team/givaro/releases/tag/v4.2.0rc0
+givaro: https://github.com/linbox-team/givaro/releases/tag/v4.2.0
 
-fflas-ffpack: https://github.com/linbox-team/fflas-ffpack/releases/tag/v2.5.0rc1
+fflas-ffpack: https://github.com/linbox-team/fflas-ffpack/releases/tag/v2.5.0
 
-linbox: 
+linbox: https://github.com/linbox-team/linbox/releases/tag/v1.7.0
``````

**Comment by mkoeppe** [comment]
Description changed:
``````diff
--- 
+++ 
@@ -5,3 +5,9 @@
 fflas-ffpack: https://github.com/linbox-team/fflas-ffpack/releases/tag/v2.5.0
 
 linbox: https://github.com/linbox-team/linbox/releases/tag/v1.7.0
+
+The new versions require "a C++ compiler supporting C++11 standard. More precisely g++ v5 or greater, clang++ v3.4 or greater".
+So this ticket depends on dropping support for some systems, see #32074.
+
+
+
``````

**Comment by isuruf** [comment]
@ClementPernet, any plans for a new minor version?
