### ISSUE TITLE
ctypes.utils.find_library broken on musl libc

### ISSUE THREAD

**Issue by tornaria** [sagemath/sage#33047]
<div id="comment:0"></div>

More precisely, `ctypes.util.find_library('c')` is broken which causes a failure `doctesting src/sage/misc/gperftools.py`.

The current commit adds a patch that I took from void linux, which in turn it's taken from alpine linux.

See: https://git.alpinelinux.org/aports/plain/main/python3/musl-find_library.patch.

CC:  @orlitzky

Component: **packages: standard**

Author: **Gonzalo Tornaría**

Branch/Commit: **[u/tornaria/python3-musl-find_library](https://github.com/sagemath/sagetrac-mirror/tree/u/tornaria/python3-musl-find_library) @ [`dc1a0e8`](https://github.com/sagemath/sagetrac-mirror/commit/dc1a0e8168a9ffb4fbf07dd03c0846b4933a6dbe)**

_Issue created by migration from https://trac.sagemath.org/ticket/33047_

**Comment by orlitzky** [comment]
What is this line of code in `gperftools.py` doing, anyway? To me it looks like a circuitous way of setting the OS handler for `SIGPROF` to `SIG_DFL`. Doesn't cysignals do that without having to guess the path to my libc.so?

**Comment by orlitzky** [comment]
Should be fixed in https://github.com/sagemath/sage/pull/38675
