### ISSUE TITLE
sage.env.sage_include_directories: Don't use distutils and SAGE_LIB

### ISSUE THREAD

**Issue by tornaria** [sagemath/sage#33137]
<div id="comment:0"></div>

- `src/sage/env.py` uses `distutils.sysconfig.get_python_inc()` which is deprecated, it has no replacement in sysconfig.

 Suggestion from fbissey: "we could use sysconfig.get_config_var('INCLUDEPY') which should give the same value." [#33135 comment:7](https://github.com/sagemath/sage/issues/33135#comment:7)

We also remove the use of `SAGE_LIB` in preparation of namespace packages.

This is the last use of `distutils` in the Sage library, except for uses in `src/sage/features/__init__.py` and `src/sage/misc/cython.py`, which are merely fallbacks when `setuptools` is not present.

 Comment from arojas: "I don't see any code in sagelib or cython that would emit this. Is this still needed at all?"

Follow-up: Once these uses of distutils are removed, their modules can be removed from the regex in the call to filterwarnings introduced by #33135.

Part of 
- Meta-ticket #31295: Replace imports from deprecated `distutils`
- Meta-ticket #33037: Remove use of `SAGE_LIB` and `SAGE_EXTCODE` variables

Depends on #32873

CC:  @antonio-rojas @dimpase

Component: **misc**

Author: **Frédéric Chapoton, Matthias Koeppe**

_Issue created by migration from https://trac.sagemath.org/ticket/33137_

**Comment by mkoeppe** [comment]
Description changed:
``````diff
--- 
+++ 
@@ -9,3 +9,6 @@
  Comment from arojas: "I don't see any code in sagelib or cython that would emit this. Is this still needed at all?"
 
 Once these uses of distutils are removed, their modules can be removed from the regex in the call to filterwarnings introduced by #33135.
+
+
+Part of Meta-ticket #31295: Replace imports from deprecated distutils
``````

**Comment by mkoeppe** [comment]
Description changed:
``````diff
--- 
+++ 
@@ -4,11 +4,13 @@
 
  Suggestion from fbissey: "we could use sysconfig.get_config_var('INCLUDEPY') which should give the same value." [#33135 comment:7](https://github.com/sagemath/sage/issues/33135#comment:7)
 
-- `src/sage/features/__init__.py` uses `distutils.errors.CCompilerError` which is not present in `setuptools.errors`.
+This is the last use of `distutils` in the Sage library, except for uses in `src/sage/features/__init__.py` and `src/sage/misc/cython.py`, which are merely fallbacks when `setuptools` is not present.
 
  Comment from arojas: "I don't see any code in sagelib or cython that would emit this. Is this still needed at all?"
 
-Once these uses of distutils are removed, their modules can be removed from the regex in the call to filterwarnings introduced by #33135.
+Follow-up: Once these uses of distutils are removed, their modules can be removed from the regex in the call to filterwarnings introduced by #33135.
 
+Part of 
+- Meta-ticket #31295: Replace imports from deprecated `distutils`
+- Meta-ticket #33037: Remove use of `SAGE_LIB` and `SAGE_EXTCODE` variables
 
-Part of Meta-ticket #31295: Replace imports from deprecated distutils
``````

**Comment by mkoeppe** [comment]
Description changed:
``````diff
--- 
+++ 
@@ -3,6 +3,8 @@
 - `src/sage/env.py` uses `distutils.sysconfig.get_python_inc()` which is deprecated, it has no replacement in sysconfig.
 
  Suggestion from fbissey: "we could use sysconfig.get_config_var('INCLUDEPY') which should give the same value." [#33135 comment:7](https://github.com/sagemath/sage/issues/33135#comment:7)
+
+We also remove the use of `SAGE_LIB` in preparation of namespace packages.
 
 This is the last use of `distutils` in the Sage library, except for uses in `src/sage/features/__init__.py` and `src/sage/misc/cython.py`, which are merely fallbacks when `setuptools` is not present.
 
``````

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
<div id="comment:22"></div>

Branch pushed to git repo; I updated commit sha1. This was a forced push. New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/9a77a819635a355dfee5805b5c87b7a6be219037"><code>9a77a81</code></a></td><td><code>sage.env.sage_include_directories: Do not append distutils.sysconfig.get_python_inc()</code></td></tr><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/e2688ef47fac633e5f5a299106e807e23f942d28"><code>e2688ef</code></a></td><td><code>sage.env.sage_include_directories: Append sysconfig variable INCLUDEPY</code></td></tr></table>

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
Changed commit from **[`fb965ec`](https://github.com/sagemath/sagetrac-mirror/commit/fb965ece366c9d67cfb99354c855f258267d600b)** to **[`e2688ef`](https://github.com/sagemath/sagetrac-mirror/commit/e2688ef47fac633e5f5a299106e807e23f942d28)**

**Comment by mkoeppe** [comment]
Removed branch from issue description; replaced by PR #35118.
