### ISSUE TITLE
tox -e relint: Do not complain about imports from sage.categories.all

### ISSUE THREAD

**Issue by mkoeppe** [sagemath/sage#33202]
<div id="comment:0"></div>

A refinement of #32899, #32879:

`sage.categories` is a namespace package: The most basic categories needed for coercion are distributed in **sagemath-objects**; everything else in **sagemath-categories**.

However, we now declare imports from `sage.categories.all` to be OK.

Rationale: Categories are supposed to be abstract - so there should not be compile-time or module-load-time dependencies. 

CC:  @kwankyu @fchapoton @tscrim @tobiasdiez

Component: **categories**

Reviewer: **Travis Scrimshaw**

_Issue created by migration from https://trac.sagemath.org/ticket/33202_

**Comment by mkoeppe** [comment]
Description changed:
``````diff
--- 
+++ 
@@ -1,6 +1,8 @@
+A refinement of #32899, #32879:
+
 `sage.categories` is a namespace package: The most basic categories needed for coercion are distributed in **sagemath-objects**; everything else in **sagemath-categories**.
 
-We declare imports from `sage.categories.all` to be OK.
+However, we now declare imports from `sage.categories.all` to be OK.
 
-Categories are supposed to be abstract - so there should not be compile-time or module-load-time dependencies.
+Rationale: Categories are supposed to be abstract - so there should not be compile-time or module-load-time dependencies. 
 
``````

**Comment by mkoeppe** [comment]
<div id="comment:11" align="right">comment:11</div>

No longer needed

**Comment by mkoeppe** [comment]
Changed author from **Matthias Koeppe** to none

**Comment by tscrim** [comment]
Reviewer: **Travis Scrimshaw**

**Comment by tscrim** [comment]
Changed commit from **[`f18fa73`](https://github.com/sagemath/sagetrac-mirror/commit/f18fa734aee58c9a265d11fb920679003a2982ea)** to none

**Comment by tscrim** [comment]
Changed branch from **[u/mkoeppe/tox__e_relint__do_not_complain_about_imports_from_sage_categories_all](https://github.com/sagemath/sagetrac-mirror/tree/u/mkoeppe/tox__e_relint__do_not_complain_about_imports_from_sage_categories_all)** to none
