### ISSUE TITLE
Equal hashes for non-isomorphic bipartite graphs with edge labels

### ISSUE THREAD

**Issue by maxale** [sagemath/sage#33255]
<div id="comment:0"></div>

The following code illustrates the problem that two bipartite graph `B1` and `B2` (both canonically labeled) are claimed to be equal and have equal hashes, while they are NOT isomorphic, let alone equal, as labeled graphs. 

When labels are ignored, these graphs are isomorphic, and so the problem may be caused by equality testing / `hash()` function somehow ignoring edge labels.

```
B1 = BipartiteGraph( [(0, 11, 2), (0, 12, 1), (0, 14, 1), (0, 16, 1), (1, 10, 1), (1, 13, 1), (1, 14, 2), (1, 16, 1), (2, 10, 2), (2, 11, 1), (2, 15, 1), (2, 16, 1), (3, 10, 1), (3, 12, 1), (3, 16, 2), (3, 17, 1), (4, 11, 1), (4, 13, 1), (4, 15, 2), (4, 17, 1), (5, 9, 2), (5, 14, 1), (5, 15, 1), (5, 17, 1), (6, 9, 1), (6, 13, 2), (6, 16, 1), (6, 17, 1), (7, 9, 1), (7, 10, 1), (7, 11, 1), (7, 12, 2), (7, 14, 1), (8, 9, 1), (8, 12, 1), (8, 13, 1), (8, 15, 1), (8, 17, 2)], immutable=True )

B2 = BipartiteGraph( [(0, 11, 1), (0, 12, 1), (0, 14, 2), (0, 16, 1), (1, 10, 2), (1, 13, 1), (1, 14, 1), (1, 16, 1), (2, 10, 1), (2, 11, 2), (2, 15, 1), (2, 16, 1), (3, 10, 1), (3, 12, 1), (3, 16, 2), (3, 17, 1), (4, 11, 1), (4, 13, 1), (4, 15, 2), (4, 17, 1), (5, 9, 2), (5, 14, 1), (5, 15, 1), (5, 17, 1), (6, 9, 1), (6, 13, 2), (6, 16, 1), (6, 17, 1), (7, 9, 1), (7, 10, 1), (7, 11, 1), (7, 12, 2), (7, 14, 1), (8, 9, 1), (8, 12, 1), (8, 13, 1), (8, 15, 1), (8, 17, 2)], immutable=True )

print('Same hashes:', hash(B1) == hash(B2) )
print('Isomorphic:', B1.is_isomorphic( B2, edge_labels=True ) )
print('Equal:', B1 == B2)
```

Component: **graph theory**

_Issue created by migration from https://trac.sagemath.org/ticket/33255_

**Comment by maxale** [comment]
Description changed:
``````diff
--- 
+++ 
@@ -1,6 +1,6 @@
-The following code illustrates the problem that two bipartite graph `B1` and `B2` (both canonically labeled) have equal hashes, while they are not isomorphic, let alone equal, as labeled graphs. 
+The following code illustrates the problem that two bipartite graph `B1` and `B2` (both canonically labeled) are claimed to be equal and have equal hashes, while they are NOT isomorphic, let alone equal, as labeled graphs. 
 
-When labels are ignored, these graphs are isomorphic, and so the problem may be caused by `hash()` function somehow ignoring edge labels.
+When labels are ignored, these graphs are isomorphic, and so the problem may be caused by equality testing / `hash()` function somehow ignoring edge labels.
 
 
 ```
@@ -10,6 +10,7 @@
 
 print('Same hashes:', hash(B1) == hash(B2) )
 print('Isomorphic:', B1.is_isomorphic( B2, edge_labels=True ) )
+print('Equal:', B1 == B2)
 ```
 
 
``````

**Comment by slel** [comment]
Description changed:
``````diff
--- 
+++ 
@@ -13,5 +13,3 @@
 print('Equal:', B1 == B2)
 ```
 
-
-
``````

**Comment by 701607be-2c9c-4f1e-9069-e5945d2c495d** [comment]
Branch: **[u/gh-Bruno-TT/bipartite-hashes](https://github.com/sagemath/sagetrac-mirror/tree/u/gh-Bruno-TT/bipartite-hashes)**

**Comment by 701607be-2c9c-4f1e-9069-e5945d2c495d** [comment]
Commit: **[`6d31aad`](https://github.com/sagemath/sagetrac-mirror/commit/6d31aad9f67f9ff414b4dbdce70444d9f0b69004)**

**Comment by 701607be-2c9c-4f1e-9069-e5945d2c495d** [comment]
<div id="comment:14" align="right">comment:14</div>

There was never a unanimous consensus on how to handle the weight/labelling logic, so I've implemented a suggestion.

My implementation adds an optional boolean parameter hash_labels to the class constructor, which if left empty will default to None and warn the user upon hash() invocation, and then include labels in the hash.

Let me know what you guys think.

(I'm new to the project so please feel free to give criticism, I'm assuming I've somehow misused trac).

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
<div id="comment:15"></div>

Branch pushed to git repo; I updated commit sha1. New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/e49602d2a4cf2bf2eda0dbeff47ba787aeed8156"><code>e49602d</code></a></td><td><code>forgot to actually put something in the commit lol</code></td></tr></table>

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
Changed commit from **[`6d31aad`](https://github.com/sagemath/sagetrac-mirror/commit/6d31aad9f67f9ff414b4dbdce70444d9f0b69004)** to **[`e49602d`](https://github.com/sagemath/sagetrac-mirror/commit/e49602d2a4cf2bf2eda0dbeff47ba787aeed8156)**

**Comment by dcoudert** [comment]
<div id="comment:16" align="right">comment:16</div>

Welcome to Sagemath.

To be consistent, you should add parameter `hash_labels` to all (bipartite) (di)graph classes and make sure the parameter is copied when making a copy of the graph.

I disagree with the default `None` value. We usually don't print warnings.
I think it should default to `False` (current behavior) and be set to `True` if either it's the input value or if the graph is weighted.

For the `__hash__` method, please check `Graph.__hash__??`. It's better to use frozenset to avoid sorting. So simply use `left = frozenset(self.left)`.

Finally, please try to use the same coding style as other methods.

**Comment by nbruin** [comment]
<div id="comment:17" align="right">comment:17</div>

and try to stick to informative commit messages. If this ticket is merged, the commit messages become a permanent part of the sagemath repository and people who need to investigate the code for later maintenance will bump into them. The way these messages are formulated reflects on you (the author) and on the project as a whole.

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
Changed commit from **[`e49602d`](https://github.com/sagemath/sagetrac-mirror/commit/e49602d2a4cf2bf2eda0dbeff47ba787aeed8156)** to **[`33206af`](https://github.com/sagemath/sagetrac-mirror/commit/33206afda26e6e74bbf434eeaceef31be65ed014)**

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
<div id="comment:18"></div>

Branch pushed to git repo; I updated commit sha1. New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/13f7f552f0e66cce119404781e23d0a872ae9c7f"><code>13f7f55</code></a></td><td><code>tweaks</code></td></tr><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/33206afda26e6e74bbf434eeaceef31be65ed014"><code>33206af</code></a></td><td><code>pep8 formatting</code></td></tr></table>

**Comment by 701607be-2c9c-4f1e-9069-e5945d2c495d** [comment]
<div id="comment:19" align="right">comment:19</div>

Replying to [David Coudert](#comment%3A16):
> To be consistent, you should add parameter `hash_labels` to all (bipartite) (di)graph classes and make sure the parameter is copied when making a copy of the graph.

Please could you clarify what you mean by this?

> I disagree with the default `None` value. We usually don't print warnings.
> I think it should default to `False` (current behavior) and be set to `True` if either it's the input value or if the graph is weighted.


```
def _use_hash_labels(self):
    return self.weighted() or self.hash_labels
```
Just changed the logic - is this what you mean?

> For the `__hash__` method, please check `Graph.__hash__??`. It's better to use frozenset to avoid sorting. So simply use `left = frozenset(self.left)`.

Cool, thanks for the tip - changed it.

> Finally, please try to use the same coding style as other methods.

I've run autopep8

---
New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/13f7f552f0e66cce119404781e23d0a872ae9c7f"><code>13f7f55</code></a></td><td><code>tweaks</code></td></tr><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/33206afda26e6e74bbf434eeaceef31be65ed014"><code>33206af</code></a></td><td><code>pep8 formatting</code></td></tr></table>

**Comment by dcoudert** [comment]
<div id="comment:20" align="right">comment:20</div>

Please avoid modifying parts of the code that have nothing to do with the objective of this ticket. It makes the reviewing process very difficult. To improve the coding style of a file, we prefer to open dedicated tickets and to not do it blindly.


Similarly to the `Graph__hash__` method, the `__hash__` method should be something like this (examples and tests are missing).

```
def __hash__(self):
    r"""
    Compute a hash for ``self``, if ``self`` is immutable.

    """
    if self.is_immutable():
        edge_items = self.edge_iterator(labels=self._weighted or self.hash_labels)
        if self.allows_multiple_edges():
            from collections import Counter
            edge_items = Counter(edge_items).items()
        return hash((frozenset(self.left),
                     frozenset(self.right),
                     frozenset(edge_items))
    raise TypeError("This graph is mutable, and thus not hashable. "
                    "Create an immutable copy by `g.copy(immutable=True)`")
```

Now, if we add this parameter to `BipartiteGraph`, it might be better to add it to `Graph`, `DiGraph`, etc. as well. Also, you must ensure that the parameter is copied if you do a copy.

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
<div id="comment:21"></div>

Branch pushed to git repo; I updated commit sha1. New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/aca2b6366fdc174aa0f17d327731748dea9f1952"><code>aca2b63</code></a></td><td><code>Revert "pep8 formatting"</code></td></tr></table>

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
Changed commit from **[`33206af`](https://github.com/sagemath/sagetrac-mirror/commit/33206afda26e6e74bbf434eeaceef31be65ed014)** to **[`aca2b63`](https://github.com/sagemath/sagetrac-mirror/commit/aca2b6366fdc174aa0f17d327731748dea9f1952)**

**Comment by 701607be-2c9c-4f1e-9069-e5945d2c495d** [comment]
<div id="comment:22" align="right">comment:22</div>

Replying to [David Coudert](#comment%3A20):
> Please avoid modifying parts of the code that have nothing to do with the objective of this ticket. It makes the reviewing process very difficult. To improve the coding style of a file, we prefer to open dedicated tickets and to not do it blindly.

Apologies for being too eager with the pep8 formatting - I've reverted the commit.


> Similarly to the `Graph__hash__` method, the `__hash__` method should be something like this (examples and tests are missing).
> 
> ```
> def __hash__(self):
>     r"""
>     Compute a hash for ``self``, if ``self`` is immutable.
> 
>     """
>     if self.is_immutable():
>         edge_items = self.edge_iterator(labels=self._weighted or self.hash_labels)
>         if self.allows_multiple_edges():
>             from collections import Counter
>             edge_items = Counter(edge_items).items()
>         return hash((frozenset(self.left),
>                      frozenset(self.right),
>                      frozenset(edge_items))
>     raise TypeError("This graph is mutable, and thus not hashable. "
>                     "Create an immutable copy by `g.copy(immutable=True)`")
> ```

I've had a play around with your suggestion, but there is some slightly weird behaviour.

I'm not exactly sure what's going on, but for some reason, hashing a tuple containing an edge_iterator() object gives unreliable results:


```
sage: B1 = BipartiteGraph([(1,2,3)], immutable=True)
sage: hash((B1.edge_iterator(labels=False),))
-4081111260156298028
sage: hash((B1.edge_iterator(labels=False),)) # same line as above
6054870339558346632
```

For now, I'm going to keep using my initial list/tuple_depth implementation since it seems to produce more reliable results

> Now, if we add this parameter to `BipartiteGraph`, it might be better to add it to `Graph`, `DiGraph`, etc. as well. 

Apologies for repeatedly asking for clarification, but are you saying I should add a hash_labels argument to the constructors of every graph class, [and/or _use_hash_labels() logic]?

> Also, you must ensure that the parameter is copied if you do a copy.

How should I go about making sure the parameter is copied?

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
<div id="comment:23"></div>

Branch pushed to git repo; I updated commit sha1. New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/eafaf288bf0b6fc26a81f290aa93080f185d356c"><code>eafaf28</code></a></td><td><code>prevent mutable graph hashing + label warnings</code></td></tr></table>

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
Changed commit from **[`aca2b63`](https://github.com/sagemath/sagetrac-mirror/commit/aca2b6366fdc174aa0f17d327731748dea9f1952)** to **[`eafaf28`](https://github.com/sagemath/sagetrac-mirror/commit/eafaf288bf0b6fc26a81f290aa93080f185d356c)**

**Comment by dcoudert** [comment]
<div id="comment:24" align="right">comment:24</div>

Have your tried the method I proposed to hash a `BipartiteGraph` ? it is very similar to the hash function for `Graph`. It makes a frozenset of the list of edges which prevents ordering issues.

Concerning copy, you must ensure in method copy of `src/sage/graphs/generic_graph.py` that attribute `hash_labels` is copied (if it exists).

If you want to generalize the idea to `Graph`, `DiGraph`, `GenericGraph`, the parameter should be set in the constructor of each of these classes and that the hash method of  `src/sage/graphs/generic_graph.py` should be updated accordingly.

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
<div id="comment:25"></div>

Branch pushed to git repo; I updated commit sha1. New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/f801dbd83f20e88b27f2c428488b40978733ccfd"><code>f801dbd</code></a></td><td><code>generic_graph supports hash_labels + tests</code></td></tr></table>

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
Changed commit from **[`eafaf28`](https://github.com/sagemath/sagetrac-mirror/commit/eafaf288bf0b6fc26a81f290aa93080f185d356c)** to **[`f801dbd`](https://github.com/sagemath/sagetrac-mirror/commit/f801dbd83f20e88b27f2c428488b40978733ccfd)**

**Comment by 701607be-2c9c-4f1e-9069-e5945d2c495d** [comment]
<div id="comment:26" align="right">comment:26</div>

Replying to [David Coudert](#comment%3A24):
> Have your tried the method I proposed to hash a `BipartiteGraph` ? it is very similar to the hash function for `Graph`. It makes a frozenset of the list of edges which prevents ordering issues.

Done!

> Concerning copy, you must ensure in method copy of `src/sage/graphs/generic_graph.py` that attribute `hash_labels` is copied (if it exists).

Done. Also added a hash_labels parameter to the copy method, although my solution is quite hacky - see my code comment for more info. The feature is fully functional, and I've written some quite comprehensive tests for it, but I also won't take it personally if someone wants to change it or remove it.


> If you want to generalize the idea to `Graph`, `DiGraph`, `GenericGraph`, the parameter should be set in the constructor of each of these classes and that the hash method of  `src/sage/graphs/generic_graph.py` should be updated accordingly.

Done, passing all tests.

**Comment by dcoudert** [comment]
<div id="comment:27" align="right">comment:27</div>

There is a merge conflict with the last beta version.

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
<div id="comment:28"></div>

Branch pushed to git repo; I updated commit sha1. New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/c379a13508c98291c090764422839b381ea03772"><code>c379a13</code></a></td><td><code>Merge tag '9.8.beta4' into u/gh-Bruno-TT/bipartite-hashes</code></td></tr></table>

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
Changed commit from **[`f801dbd`](https://github.com/sagemath/sagetrac-mirror/commit/f801dbd83f20e88b27f2c428488b40978733ccfd)** to **[`c379a13`](https://github.com/sagemath/sagetrac-mirror/commit/c379a13508c98291c090764422839b381ea03772)**

**Comment by 701607be-2c9c-4f1e-9069-e5945d2c495d** [comment]
<div id="comment:29" align="right">comment:29</div>

Replying to [David Coudert](#comment%3A27):
> There is a merge conflict with the last beta version.

think I've resolved it

**Comment by dcoudert** [comment]
<div id="comment:30" align="right">comment:30</div>

Some of the text in the commits should be in the ticket to ease the discussion. For instance I agree that returning `self` is not a good idea as one may for instance want to manipulate copies with different embedding.

Also, can you push the branch in public (e.g., `public/graphs/33255`) so that I can push review commits. It's faster for me that listing all the details that must be improved.

Thanks.

**Comment by 701607be-2c9c-4f1e-9069-e5945d2c495d** [comment]
<div id="comment:31" align="right">comment:31</div>

Replying to [David Coudert](#comment%3A30):
> Some of the text in the commits should be in the ticket to ease the discussion. For instance I agree that returning `self` is not a good idea as one may for instance want to manipulate copies with different embedding.

for anyone interested, here is the text he's referring to:

''This is an ugly hack but it works.
This function contains some fairly complex logic, and there is a comment further down that says "Immutable copy of an immutable graph ? return self !", the issue being that if we want to change the hash_labels behaviour, then
returning self is no longer a good option. I'd argue that a copy function
returning self is always bad behaviour, but that's out of the scope for this ticket.
Trying to weaken the if statement to include something like
        

```
and (hash_labels is None or (hash_labels==self._use_labels_for_hash()))
```


*doesn't work, since there is no fallback logic for making an immutable copy of an immutable graph, and my attempts at implementing one caused other tests to break in different bits of the code*

*the hack I've used creates a mutable copy of the graph and then makes an immutable copy of that one. I think this is a fairly unobtrusive implementation, since the function still runs as normally, assuming that they pass nothing into hash_labels, and seems to behave correctly otherwise.*

*However, this is obviously not optimal, and could definitely be improved upon by someone who understands the logic better.* 


> Also, can you push the branch in public (e.g., `public/graphs/33255`) so that I can push review commits. It's faster for me that listing all the details that must be improved.
> 
> Thanks.

pushed to `public/graphs/33255`

**Comment by dcoudert** [comment]
Changed branch from **[u/gh-Bruno-TT/bipartite-hashes](https://github.com/sagemath/sagetrac-mirror/tree/u/gh-Bruno-TT/bipartite-hashes)** to **[public/graphs/33255](https://github.com/sagemath/sagetrac-mirror/tree/public/graphs/33255)**

**Comment by dcoudert** [comment]
Changed commit from **[`c379a13`](https://github.com/sagemath/sagetrac-mirror/commit/c379a13508c98291c090764422839b381ea03772)** to **[`634ca63`](https://github.com/sagemath/sagetrac-mirror/commit/634ca632611af10278d5943fc6c6b275a4621d51)**

**Comment by dcoudert** [comment]
<div id="comment:32" align="right">comment:32</div>

I did several corrections / improvements. It currently passes tests, but I may have missed some cases.

I'll check the copy method asap. It's not obvious how to endup with a clean solution.

---
New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/569ec3caf59bf7c73532f2de6ab0f8a30ea156e2"><code>569ec3c</code></a></td><td><code>trac #33255: merged with 9.8.beta6</code></td></tr><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/837a8c7ef856c0c080c894de0789e5d66f956b3c"><code>837a8c7</code></a></td><td><code>trac #33255: review commit</code></td></tr><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/634ca632611af10278d5943fc6c6b275a4621d51"><code>634ca63</code></a></td><td><code>trac #33255: corrections</code></td></tr></table>

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
Changed commit from **[`634ca63`](https://github.com/sagemath/sagetrac-mirror/commit/634ca632611af10278d5943fc6c6b275a4621d51)** to **[`e993d2f`](https://github.com/sagemath/sagetrac-mirror/commit/e993d2f9aab597abc43fd5cf1da381dd0a8e8e9f)**

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
<div id="comment:33"></div>

Branch pushed to git repo; I updated commit sha1. New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/e993d2f9aab597abc43fd5cf1da381dd0a8e8e9f"><code>e993d2f</code></a></td><td><code>trac #33255: better copy</code></td></tr></table>

**Comment by dcoudert** [comment]
<div id="comment:34" align="right">comment:34</div>

This should do the job.

Roughly, if parameter `hash_labels` is `None`, we have the same behavior than for the `weighted` parameters. If the parameter is set, we create a (im)mutable copy of the graph depending on the value of parameter `immutable`.

In another ticket, we can change the default behavior of returning self when asking for a copy of an immutable graph without changing parameters.

**Comment by dcoudert** [comment]
Ready for review.

**Comment by mkoeppe** [comment]
Removed branch from issue description; replaced by PR #35146.

**Comment by mkoeppe** [comment]
Removed the status label – there's no need to have it on both PR and Issue.
