### ISSUE TITLE
CI target ticket for setuptools

### ISSUE THREAD

**Issue by mkoeppe** [sagemath/sage#33288]
<div id="comment:0"></div>

Target ticket for https://github.com/pypa/setuptools/blob/main/.github/workflows/ci-sage.yml

The branch here will be merged by the GH Actions workflow.

Depends on #33816

Component: **porting**

Branch/Commit: **[u/mkoeppe/setuptools_ci_target](https://github.com/sagemath/sagetrac-mirror/tree/u/mkoeppe/setuptools_ci_target) @ [`52361f5`](https://github.com/sagemath/sagetrac-mirror/commit/52361f594c8d27ed9787b05dcebbb06eded5da5b)**

_Issue created by migration from https://trac.sagemath.org/ticket/33288_

**Comment by mkoeppe** [comment]
Changed dependencies from **#34017** to **#33816**

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
<div id="comment:5"></div>

Branch pushed to git repo; I updated commit sha1. Last 10 new commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/ba6de8339036d621352d9baacc0efb4591f52fe3"><code>ba6de83</code></a></td><td><code>build/pkgs/gcc/build-gcc: Unset AS, LD</code></td></tr><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/5d9563be5c4853d61e4127b19c9c3bd1e1468f7a"><code>5d9563b</code></a></td><td><code>build/pkgs/gfortran/spkg-build.in: Work around build failure with Apple gcc (clang)</code></td></tr><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/6e6af03773b262fd791c8dd5aeaf2256bdc84adc"><code>6e6af03</code></a></td><td><code>build/pkgs/openblas: Update to 0.3.21</code></td></tr><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/33668cbf857be6033e2f176913a41cb6281478ff"><code>33668cb</code></a></td><td><code>Merge #34266</code></td></tr><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/3ad48d0f3428b5263bf831e23f6d6fd7ece09204"><code>3ad48d0</code></a></td><td><code>build/pkgs/gsl: Update to 2.7.1</code></td></tr><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/1e24d43c0371b3285ad508cd95f2f3e31e66dd58"><code>1e24d43</code></a></td><td><code>build/pkgs/gsl/patches: Import https://raw.githubusercontent.com/Homebrew/formula-patches/03cf8088210822aa2c1ab544ed58ea04c897d9c4/libtool/configure-big_sur.diff</code></td></tr><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/07d2dcbc22cb66741c8fcb69a1104c93b28e08d8"><code>07d2dcb</code></a></td><td><code>.github/workflows/docker.yml: Use ubuntu-bionic-i386 with gcc_8, remove manylinux-2_24-i686 (based on dropped debian-stretch)</code></td></tr><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/d24647a646ece6f80690c508de4028bb58e23923"><code>d24647a</code></a></td><td><code>Merge #34228</code></td></tr><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/e89ba553fa43eea1539f39cc423fd0174d371b64"><code>e89ba55</code></a></td><td><code>.github/workflows/ci-linux.yml: Fix typo which prevented 'minimal-*' from starting</code></td></tr><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/52361f594c8d27ed9787b05dcebbb06eded5da5b"><code>52361f5</code></a></td><td><code>Merge #33816</code></td></tr></table>

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
Changed commit from **[`58d62f4`](https://github.com/sagemath/sagetrac-mirror/commit/58d62f4e22ee7d7f8f38665ab5f40961f811e2ac)** to **[`52361f5`](https://github.com/sagemath/sagetrac-mirror/commit/52361f594c8d27ed9787b05dcebbb06eded5da5b)**

**Comment by mkoeppe** [comment]
Changed branch from **[u/mkoeppe/fix_tox_docker_builds_after__29941](https://github.com/sagemath/sagetrac-mirror/tree/u/mkoeppe/fix_tox_docker_builds_after__29941)** to **[u/mkoeppe/setuptools_ci_target](https://github.com/sagemath/sagetrac-mirror/tree/u/mkoeppe/setuptools_ci_target)**

**Comment by mkoeppe** [comment]
No longer in use after https://github.com/pypa/setuptools/pull/4058
