### ISSUE TITLE
is_prime for ideals uses factorization, can be VERY slow

### ISSUE THREAD

**Issue by tornaria** [sagemath/sage#33360]
<div id="comment:0"></div>

The implementation of `is_prime()` for ideals uses pari `idealfactor()`. This is a bad idea if the norm of the ideal is hard to factor.

Pari has `ismaximalideal()`, but it is broken in pari 2.13.3. As a workaround, since a prime ideal has prime power norm, we avoid factorization except on this (easy) case.

---

Was: VERY slow doctest in `sage/rings/number_field/number_field.py`

With sage 9.5:

```
$ time sage -t --long --warn-long 60.0 --random-seed=40834229707572602474454926153679777311 src/sage/rings/number_field/number_field.py 
Running doctests with ID 2022-02-16-15-58-06-58d0ee96.
Using --optional=build,pip,sage,sage_spkg,void
Features to be detected: 4ti2,benzene,bliss,buckygen,conway_polynomials,csdp,database_cremona_ellcurve,database_cremona_mini_ellcurve,database_jones_numfield,database_knotinfo,dvipng,graphviz,imagemagick,jupymake,kenzo,latte_int,lrslib,mcqd,meataxe,pandoc,pdf2svg,plantri,pynormaliz,rubiks,sage.combinat,sage.geometry.polyhedron,sage.graphs,sage.plot,sage.rings.number_field,sage.rings.real_double,sage.symbolic,sage_numerical_backends_coin,sagemath_doc_html,sphinx,tdlib
Doctesting 1 file.
sage -t --long --warn-long 60.0 --random-seed=40834229707572602474454926153679777311 src/sage/rings/number_field/number_field.py
**********************************************************************
File "src/sage/rings/number_field/number_field.py", line 2180, in sage.rings.number_field.number_field.NumberField_generic.?
Warning, slow doctest:
    while not K.random_element().is_prime():  # long time
        pass
Test ran for 1319.62 s
    [2265 tests, 1367.95 s]
----------------------------------------------------------------------
All tests passed!
----------------------------------------------------------------------
Total time for all tests: 1368.3 seconds
    cpu time: 1364.7 seconds
    cumulative wall time: 1367.9 seconds
Features detected for doctesting: 

real	22m51.641s
user	22m47.153s
sys	0m1.272s
```

CC:  @yyyyx4 @fchapoton

Component: **number fields**

Author: **Gonzalo Tornaría, Lorenz Panny**

Reviewer: **Lorenz Panny**

_Issue created by migration from https://trac.sagemath.org/ticket/33360_

**Comment by tornaria** [comment]
Description changed:
``````diff
--- 
+++ 
@@ -1,3 +1,11 @@
+The implementation of `is_prime()` for ideals uses pari `idealfactor()`. This is a bad idea if the norm of the ideal is hard to factor.
+
+Pari has `ismaximalideal()`, but it is broken in pari 2.13.3. As a workaround, since a prime ideal has prime power norm, we avoid factorization except on this (easy) case.
+
+---
+
+Was: VERY slow doctest in `sage/rings/number_field/number_field.py`
+
 With sage 9.5:
 
 ```
``````

**Comment by yyyyx4** [comment]
Changed author from **Gonzalo Tornaría** to **Gonzalo Tornaría, Lorenz Panny**

**Comment by yyyyx4** [comment]
<div id="comment:15" align="right">comment:15</div>

I implemented my suggestions from [comment:9](#comment%3A9) and [comment:12](#comment%3A12). Someone else will have to review the new changes.

---
New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/6330cee1a69229b2f5d8ac4a09a73d8152f5e14d"><code>6330cee</code></a></td><td><code>trac 33360: avoid factoring in is_prime()</code></td></tr><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/7f19cea54279fd9632f64707dead67f40c61f660"><code>7f19cea</code></a></td><td><code>Merge branch 'u/tornaria/33360-ideal.is_prime' into public/33360</code></td></tr><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/b938f7b81edb954aa3639043f0e09f15b2b98d1a"><code>b938f7b</code></a></td><td><code>opportunistically use idealismaximal() when PARI version is recent enough</code></td></tr></table>

**Comment by yyyyx4** [comment]
Changed branch from **[u/tornaria/33360-ideal.is_prime](https://github.com/sagemath/sagetrac-mirror/tree/u/tornaria/33360-ideal.is_prime)** to **[public/33360](https://github.com/sagemath/sagetrac-mirror/tree/public/33360)**

**Comment by yyyyx4** [comment]
Changed commit from **[`6330cee`](https://github.com/sagemath/sagetrac-mirror/commit/6330cee1a69229b2f5d8ac4a09a73d8152f5e14d)** to **[`b938f7b`](https://github.com/sagemath/sagetrac-mirror/commit/b938f7b81edb954aa3639043f0e09f15b2b98d1a)**

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
<div id="comment:16"></div>

Branch pushed to git repo; I updated commit sha1. New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/647bd454b78aba100286e74c60c876c70a83a596"><code>647bd45</code></a></td><td><code>Merge tag '9.8.beta1' into public/33360</code></td></tr><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/e3af4e3a1e11be18a340946dd97909bd911af1e5"><code>e3af4e3</code></a></td><td><code> #34537 requires PARI >= 2.15</code></td></tr></table>

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
Changed commit from **[`b938f7b`](https://github.com/sagemath/sagetrac-mirror/commit/b938f7b81edb954aa3639043f0e09f15b2b98d1a)** to **[`e3af4e3`](https://github.com/sagemath/sagetrac-mirror/commit/e3af4e3a1e11be18a340946dd97909bd911af1e5)**

**Comment by yyyyx4** [comment]
Dependencies: **#34537**

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
Changed commit from **[`e3af4e3`](https://github.com/sagemath/sagetrac-mirror/commit/e3af4e3a1e11be18a340946dd97909bd911af1e5)** to **[`58511ea`](https://github.com/sagemath/sagetrac-mirror/commit/58511ea3015159e1c1533cda12281aa9289e36c0)**

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
<div id="comment:18"></div>

Branch pushed to git repo; I updated commit sha1. New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/58511ea3015159e1c1533cda12281aa9289e36c0"><code>58511ea</code></a></td><td><code>remove unused import</code></td></tr></table>

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
Changed commit from **[`58511ea`](https://github.com/sagemath/sagetrac-mirror/commit/58511ea3015159e1c1533cda12281aa9289e36c0)** to **[`7eee1c4`](https://github.com/sagemath/sagetrac-mirror/commit/7eee1c4317586bc31dcded5e82837148c4bf8d54)**

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
<div id="comment:19"></div>

Branch pushed to git repo; I updated commit sha1. This was a forced push. New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/a9051b1a1569a0c7937529e89d7668a8d862ed97"><code>a9051b1</code></a></td><td><code>Merge branch 'u/tornaria/33360-ideal.is_prime' into public/33360</code></td></tr><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/7eee1c4317586bc31dcded5e82837148c4bf8d54"><code>7eee1c4</code></a></td><td><code>opportunistically use idealismaximal() when PARI version is recent enough</code></td></tr></table>

**Comment by yyyyx4** [comment]
<div id="comment:20" align="right">comment:20</div>

Reverted earlier changes from [comment:16](#comment%3A16) as #34537 appears to be stuck. Can we get this in?

**Comment by yyyyx4** [comment]
Changed dependencies from **#34537** to none

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
Changed commit from **[`7eee1c4`](https://github.com/sagemath/sagetrac-mirror/commit/7eee1c4317586bc31dcded5e82837148c4bf8d54)** to **[`689eb88`](https://github.com/sagemath/sagetrac-mirror/commit/689eb880afd39b6bb8916be32c1b92df5c425bf3)**

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
<div id="comment:21"></div>

Branch pushed to git repo; I updated commit sha1. New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/689eb880afd39b6bb8916be32c1b92df5c425bf3"><code>689eb88</code></a></td><td><code>fix docstring markup</code></td></tr></table>

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
Changed commit from **[`689eb88`](https://github.com/sagemath/sagetrac-mirror/commit/689eb880afd39b6bb8916be32c1b92df5c425bf3)** to **[`4ac2c9b`](https://github.com/sagemath/sagetrac-mirror/commit/4ac2c9ba19ccdb80b227d02920d128fe360101e5)**

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
<div id="comment:22"></div>

Branch pushed to git repo; I updated commit sha1. New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/4ac2c9ba19ccdb80b227d02920d128fe360101e5"><code>4ac2c9b</code></a></td><td><code>fix docstring markup some more</code></td></tr></table>

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
Changed commit from **[`4ac2c9b`](https://github.com/sagemath/sagetrac-mirror/commit/4ac2c9ba19ccdb80b227d02920d128fe360101e5)** to **[`b31f59b`](https://github.com/sagemath/sagetrac-mirror/commit/b31f59bbae2d851431154103adf2e995ddda76d0)**

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
<div id="comment:24"></div>

Branch pushed to git repo; I updated commit sha1. New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/100b39c4889ffbdebed1f062b0507a28d87b122e"><code>100b39c</code></a></td><td><code>Merge tag '9.8.beta6' into public/33360</code></td></tr><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/9a2bddbab74b6c7276b02534ffed938ae4c9aa39"><code>9a2bddb</code></a></td><td><code>#34537 requires PARI >= 2.15</code></td></tr><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/b31f59bbae2d851431154103adf2e995ddda76d0"><code>b31f59b</code></a></td><td><code>Merge tag '9.8.rc0' into public/33360</code></td></tr></table>

**Comment by mkoeppe** [comment]
Removed branch from issue description; replaced by PR https://github.com/sagemath/sage/pull/34980
