### ISSUE TITLE
Incorrect parent when evaluating constant multivariate polynomial

### ISSUE THREAD

**Issue by roed314** [sagemath/sage#33373]
<div id="comment:0"></div>

When evaluating a univariate polynomial, it correctly takes the parent of the input into account:

```
sage: k.<a> = GF(2^4)
sage: R.<x> = PolynomialRing(k)
sage: f = R(1)
sage: S.<y> = PolynomialRing(k)
sage: f(y).parent()
Univariate Polynomial Ring in y over Finite Field in a of size 2^4
```
Multivariate polynomials do not:

```
sage: k.<a> = GF(2^4)
sage: R.<x> = PolynomialRing(k, 1)
sage: f = R(1)
sage: S.<y> = PolynomialRing(k, 1)
sage: f(y).parent()
Finite Field in a of size 2^4
```

Component: **algebra**

Keywords: **pAdicBordeaux**

Author: **David Roe**

Reviewer: **Marc Mezzarobba**

_Issue created by migration from https://trac.sagemath.org/ticket/33373_

**Comment by mkoeppe** [comment]
Removed branch from issue description; replaced by PR #35045
