### ISSUE TITLE
Automatic image build is broken on GitLab

### ISSUE THREAD

**Issue by saraedum** [sagemath/sage#33406]
<div id="comment:0"></div>

Currently, images for https://hub.docker.com/repository/docker/sagemath/sagemath are not built automatically anymore. The main issue seems to be that there are no dedicated runners registered there anymore.

There are likely other problems since the [GitLab](../wiki/GitLab) Pipeline has not been running for ages now.

CC:  @videlec

Component: **docker**

Reviewer: **Kwankyu Lee**

_Issue created by migration from https://trac.sagemath.org/ticket/33406_

**Comment by kwankyu** [comment]
Reviewer: **Kwankyu Lee**

**Comment by kwankyu** [comment]
<div id="comment:5" align="right">comment:5</div>

Yes. This is not even referenced in the README on Docker Hub.
