### ISSUE TITLE
Improve documentation for cone.py

### ISSUE THREAD

**Issue by c8e94d3a-9db0-4530-9b60-81397324e6ee** [sagemath/sage#33695]
<div id="comment:0"></div>

The documentation and python script for one of the cone functions appears to have some typos.

Component: **documentation**

Keywords: **polyhedral_complex**

_Issue created by migration from https://trac.sagemath.org/ticket/33695_

**Comment by c8e94d3a-9db0-4530-9b60-81397324e6ee** [comment]
Description changed:
``````diff
--- 
+++ 
@@ -1 +1 @@
-The documentation and python script for one of the polyhedral_complex functions appears to have some typos.
+The documentation and python script for one of the cone functions appears to have some typos.
``````

**Comment by mkoeppe** [comment]
Closing because of lack of detail and activity
