### ISSUE TITLE
Ticket badges show "failing" when actually in progress

### ISSUE THREAD

**Issue by mkoeppe** [sagemath/sage#33818]
<div id="comment:0"></div>

Depends on #30363

CC:  @tobiasdiez

Component: **user interface**

Reviewer: **Kwankyu Lee**

_Issue created by migration from https://trac.sagemath.org/ticket/33818_

**Comment by kwankyu** [comment]
Reviewer: **Kwankyu Lee**

**Comment by kwankyu** [comment]
<div id="comment:5" align="right">comment:5</div>

Yes.
