### ISSUE TITLE
Tableau and plotting - conventions not working

### ISSUE THREAD

**Issue by thecaligarmo** [sagemath/sage#33998]
<div id="comment:0"></div>

For some reason, the `plot` method is not working with the convention. For example:

```
sage: Tableaux.options.convention="english"
sage: SemistandardTableau([[1,2],[2,3]]).pp()
  1  2
  2  3
sage: SemistandardTableau([[1,2],[2,3]]).plot()
Launched png viewer for Graphics object consisting of 10 graphics primitives
sage: Tableaux.options.convention="french"
sage: SemistandardTableau([[1,2],[2,3]]).pp()
  2  3
  1  2
sage: SemistandardTableau([[1,2],[2,3]]).plot()
Launched png viewer for Graphics object consisting of 10 graphics primitives
```

The pretty print works properly, but if you look at the graphics, both give English notation.

CC:  @jplab

Component: **combinatorics**

Author: **aram.dermenjian**

Branch/Commit: **[u/aram.dermenjian/tableau_and_plotting___conventions_not_working](https://github.com/sagemath/sagetrac-mirror/tree/u/aram.dermenjian/tableau_and_plotting___conventions_not_working) @ [`937ec5d`](https://github.com/sagemath/sagetrac-mirror/commit/937ec5da32a2c8a9a219591bfefdaf3237ae9c45)**

_Issue created by migration from https://trac.sagemath.org/ticket/33998_

**Comment by fchapoton** [comment]
closing as solved
