### ISSUE TITLE
Remove imports from sage.arith.all in the Sage library

### ISSUE THREAD

**Issue by mkoeppe** [sagemath/sage#34197]
<div id="comment:0"></div>

`sage.arith` is a namespace package after #33011, so we remove imports from `sage.arith.all` throughout the library 

https://doc.sagemath.org/html/en/developer/packaging_sage_library.html#module-level-runtime-dependencies

Component: **refactoring**

Branch/Commit: **[u/mkoeppe/remove_imports_from_sage_arith_all_in_the_sage_library](https://github.com/sagemath/sagetrac-mirror/tree/u/mkoeppe/remove_imports_from_sage_arith_all_in_the_sage_library) @ [`d6ce90c`](https://github.com/sagemath/sagetrac-mirror/commit/d6ce90c8e37b453d32cb726be5edbadd24f22862)**

_Issue created by migration from https://trac.sagemath.org/ticket/34197_

**Comment by mkoeppe** [comment]
Description changed:
``````diff
--- 
+++ 
@@ -1 +1,4 @@
+`sage.arith` is a namespace package after #33011, so we remove imports from `sage.arith.all` throughout the library 
 
+https://doc.sagemath.org/html/en/developer/packaging_sage_library.html#module-level-runtime-dependencies
+
``````

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
<div id="comment:6"></div>

Branch pushed to git repo; I updated commit sha1. This was a forced push. New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/e044d0d7ad1d29ceaacedd5aa33ba7e49d88f8e7"><code>e044d0d</code></a></td><td><code>git grep -l 'sage.arith.all import' | xargs sed -E -i.bak 's/sage.arith.all import (lcm|LCM) *$/sage.arith.functions import \1/'</code></td></tr><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/7ab066e60f2c4f176261ebd0eccc13fc91df8516"><code>7ab066e</code></a></td><td><code>Remove some imports from sage.arith.all</code></td></tr></table>

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
Changed commit from **[`1011578`](https://github.com/sagemath/sagetrac-mirror/commit/10115787bee8fe8b332de1a212a9206facf61b57)** to **[`7ab066e`](https://github.com/sagemath/sagetrac-mirror/commit/7ab066e60f2c4f176261ebd0eccc13fc91df8516)**

**Comment by mantepse** [comment]
<div id="comment:7" align="right">comment:7</div>

The changes in `sfa.py` and `generating_series.py` will probably create a (trivial) conflict (which requires manual interaction) with #34470.

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
<div id="comment:8"></div>

Branch pushed to git repo; I updated commit sha1. This was a forced push. New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/2c9bea2ff10dd344714a980cdaad722a3f1c1270"><code>2c9bea2</code></a></td><td><code>git grep -l 'sage.arith.all import' | xargs sed -E -i.bak 's/sage.arith.all import (lcm|LCM) *$/sage.arith.functions import \1/'</code></td></tr><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/27d033332a757422fff112d8c4fe05bdc64602a1"><code>27d0333</code></a></td><td><code>Remove some imports from sage.arith.all</code></td></tr></table>

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
Changed commit from **[`7ab066e`](https://github.com/sagemath/sagetrac-mirror/commit/7ab066e60f2c4f176261ebd0eccc13fc91df8516)** to **[`27d0333`](https://github.com/sagemath/sagetrac-mirror/commit/27d033332a757422fff112d8c4fe05bdc64602a1)**

**Comment by mkoeppe** [comment]
<div id="comment:9" align="right">comment:9</div>


```
        from . import padics
      File "/__w/sagetrac-mirror/sagetrac-mirror/src/sage/schemes/elliptic_curves/padics.py", line 26, in <module>
        from . import padic_lseries as plseries
      File "/__w/sagetrac-mirror/sagetrac-mirror/src/sage/schemes/elliptic_curves/padic_lseries.py", line 75, in <module>
        from sage.arith.functions import LCM
    ImportError: cannot import name 'LCM' from 'sage.arith.functions' (/__w/sagetrac-mirror/sagetrac-mirror/src/sage/arith/functions.cpython-38-x86_64-linux-gnu.so)
```
as seen in https://github.com/sagemath/sagetrac-mirror/actions/runs/3440141879/jobs/5738263597

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
<div id="comment:10"></div>

Branch pushed to git repo; I updated commit sha1. New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/d6ce90c8e37b453d32cb726be5edbadd24f22862"><code>d6ce90c</code></a></td><td><code>src/sage/schemes/elliptic_curves/padic_lseries.py: Fix up import</code></td></tr></table>

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
Changed commit from **[`27d0333`](https://github.com/sagemath/sagetrac-mirror/commit/27d033332a757422fff112d8c4fe05bdc64602a1)** to **[`d6ce90c`](https://github.com/sagemath/sagetrac-mirror/commit/d6ce90c8e37b453d32cb726be5edbadd24f22862)**

**Comment by mkoeppe** [comment]
<div id="comment:11" align="right">comment:11</div>

The remaining doctest failure

```
sage -t --random-seed=29164138248827613754957725053409603108 doc/de/a_tour_of_sage/index.rst  # 1 doctest failed
```
... is unrelated to the changes here

**Comment by mkoeppe** [comment]
<div id="comment:12" align="right">comment:12</div>

We can close this ticket as a duplicate; the new tool `sage -fiximports` added in #34945 can make these changes automatically.

**Comment by mkoeppe** [comment]
Changed author from **Matthias Koeppe, ...** to none
