### ISSUE TITLE
build from source fails with --with-system-flint=no

### ISSUE THREAD

**Issue by zimmermann6** [sagemath/sage#34220]
<div id="comment:0"></div>

I tried to build Sage 9.6 from source with `--with-system-flint=no`, and it fails, cf from `sagemath_doc_html-none.log`:

```
ImportError: libflint-2.8.4.so: cannot open shared object file: No such file or directory
Error: './sage --docbuild --all-documents' failed
make[5]: *** [Makefile:33: doc-inventory-reference] Error 1
```
The dynamic library built in `local/lib` is `libflint.so.16.1.4` (also named `libflint.so`).

CC:  @fredrik-johansson

Component: **packages: standard**

_Issue created by migration from https://trac.sagemath.org/ticket/34220_

**Comment by mkoeppe** [comment]
outdated
