### ISSUE TITLE
sparse strategies for composite elliptic-curve isogenies

### ISSUE THREAD

**Issue by yyyyx4** [sagemath/sage#34239]
<div id="comment:0"></div>

Some cryptographic applications (most prominently, https://sike.org/) rely on computing isogenies of huge prime-power degrees quickly. The current algorithm used for this in Sage (since #32744) is quadratic in the number of prime-degree steps. It is known from the SIKE literature how to do better, replacing quadratic by quasilinear scaling.

This patch implements a simple version of the quasilinear algorithm. I haven't found any example where the change incurs a noticeable slowdown, while (as shown below) there can be quite significant speedups.

Example:

```sage
sage: F = GF((2^216*3^137-1, 2))
sage: E.<P,Q> = EllipticCurve(F, [1,0])
sage: %timeit E.isogeny(P, algorithm="factored")
```

Sage 9.7.beta6:

```
2.19 s ± 341 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
```

This branch:

```
1.04 s ± 13.6 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
```

CC:  @defeo @JohnCremona @categorie

Component: **elliptic curves**

Author: **Lorenz Panny**

_Issue created by migration from https://trac.sagemath.org/ticket/34239_

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
<div id="comment:6"></div>

Branch pushed to git repo; I updated commit sha1. New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/ac5764852efcf6c4f5504723641f7cf8b02655f8"><code>ac57648</code></a></td><td><code>Merge tag '9.8.beta2' into public/sparse_strategies_for_composite_elliptic_curve_isogenies</code></td></tr></table>

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
Changed commit from **[`9012a31`](https://github.com/sagemath/sagetrac-mirror/commit/9012a3111c72d828dd84c1dac7edf28c707defb3)** to **[`ac57648`](https://github.com/sagemath/sagetrac-mirror/commit/ac5764852efcf6c4f5504723641f7cf8b02655f8)**

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
<div id="comment:7"></div>

Branch pushed to git repo; I updated commit sha1. New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/f6573631ec1826323424851503391b7a290e8028"><code>f657363</code></a></td><td><code>Merge tag '9.8.beta3' into public/sparse_strategies_for_composite_elliptic_curve_isogenies</code></td></tr></table>

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
Changed commit from **[`ac57648`](https://github.com/sagemath/sagetrac-mirror/commit/ac5764852efcf6c4f5504723641f7cf8b02655f8)** to **[`f657363`](https://github.com/sagemath/sagetrac-mirror/commit/f6573631ec1826323424851503391b7a290e8028)**

**Comment by mkoeppe** [comment]
Removed branch from the issue description because it has been replaced by PR #34965
