### ISSUE TITLE
Deprecate is_Polyhedron, is_Cone, is_LatticePolytope

### ISSUE THREAD

**Issue by mkoeppe** [sagemath/sage#34307]
<div id="comment:0"></div>

... and change all uses to `isinstance(sage.geometry.abc.Polyhedron)` etc.

(see #32414)

CC:  @yuan-zhou @jplab @NicoleYueqiLi

Component: **geometry**

_Issue created by migration from https://trac.sagemath.org/ticket/34307_

**Comment by Veeransh14** [comment]
I would Like to work on this Issue
