### ISSUE TITLE
New modularized distributions sagemath-{sirocco,bliss,meataxe,mcqd,coxeter3,tdlib}

### ISSUE THREAD

**Issue by isuruf** [sagemath/sage#34346]
<div id="comment:0"></div>

These are the python extension modules that depend on the optional packages sirocco, bliss, ...
- https://pypi.org/project/sagemath-meataxe
- https://pypi.org/project/sagemath-sirocco
- https://pypi.org/project/sagemath-bliss/
- https://pypi.org/project/sagemath-mcqd/
- https://pypi.org/project/sagemath-coxeter3/
- https://pypi.org/project/sagemath-tdlib/

We also add distros/conda.txt for some of these packages.

We should add this info to https://doc.sagemath.org/html/en/installation/conda.html#installing-all-of-sagemath-from-conda-not-for-development

Depends on #32874
Depends on #34761
Depends on #34858
Depends on #34855

CC:  @saraedum @mkoeppe @slel @kiwifb @antonio-rojas @tornaria @dimpase

Component: **refactoring**

Author: **Matthias Koeppe**

Branch/Commit: **[u/mkoeppe/document_new_conda_packages_sagemath_sirocco_and_sagemath_bliss](https://github.com/sagemath/sagetrac-mirror/tree/u/mkoeppe/document_new_conda_packages_sagemath_sirocco_and_sagemath_bliss) @ [`9686423`](https://github.com/sagemath/sagetrac-mirror/commit/96864238fe7712541ec373098bb2f58d607a041c)**

_Issue created by migration from https://trac.sagemath.org/ticket/34346_

**Comment by mkoeppe** [comment]
<div id="comment:4"></div>

New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/ebb11e18d0cda156743815f029cd74c92945a0a3"><code>ebb11e1</code></a></td><td><code>build/pkgs/sagemath_sirocco: New</code></td></tr></table>

**Comment by mkoeppe** [comment]
Commit: **[`ebb11e1`](https://github.com/sagemath/sagetrac-mirror/commit/ebb11e18d0cda156743815f029cd74c92945a0a3)**

**Comment by mkoeppe** [comment]
Dependencies: **#32874**

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
<div id="comment:5"></div>

Branch pushed to git repo; I updated commit sha1. This was a forced push. Last 10 new commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/05b44d76ecee64468ca1ee79d5b0559fc28c26d5"><code>05b44d7</code></a></td><td><code>build/pkgs/{sage_conf,sage_docbuild,sage_setup,sage_sws2rst}/spkg-install: Handle SAGE_WHEELS</code></td></tr><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/dde4bdb9c4553d9c25246a45d98a784e1c1cd8b3"><code>dde4bdb</code></a></td><td><code>src/sage/misc/package_dir.py: Fix docstring markup</code></td></tr><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/ffe67e8c6ad0efd6481aabec24dd0a4a1d603426"><code>ffe67e8</code></a></td><td><code>is_package_or_sage_namespace_package_dir: Add option distribution_filter</code></td></tr><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/11507a5f7e598035b4be6c00e89919190b271dc4"><code>11507a5</code></a></td><td><code>build/pkgs/sagelib/spkg-install: No need to uninstall before installing - cleaner is back in</code></td></tr><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/974c7fd8aa4dce5b2376ad430d1e0769d91b7912"><code>974c7fd</code></a></td><td><code>src/MANIFEST.in: Remove redundant entries for MANIFEST.in, pyproject.toml</code></td></tr><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/25898ba992588a8dc2df07e40c12a4dcee9909f3"><code>25898ba</code></a></td><td><code>src/MANIFEST.in: Exclude generated file farey_symbol.h; add comments</code></td></tr><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/cdfd3ee12d810a2c6bfeb41e17f91cf4e57d4307"><code>cdfd3ee</code></a></td><td><code>Merge #32874</code></td></tr><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/3a738f90e8d305f5e173ba15bbe9119d52f96b22"><code>3a738f9</code></a></td><td><code>src/bin/sage-update-version: Distribution name of sagelib is sagemath-standard</code></td></tr><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/13470326a0273235e4d5e5e29833bd947d63ab02"><code>1347032</code></a></td><td><code>build/pkgs/sagemath_bliss, pkgs/sagemath-bliss: New</code></td></tr><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/40794b145b0dd7c5f2f97a7a812cba2c06659228"><code>40794b1</code></a></td><td><code>build/pkgs/sagelib/spkg-install [--disable-editable --enable-wheels]: Do not handle sagemath-bliss</code></td></tr></table>

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
Changed commit from **[`ebb11e1`](https://github.com/sagemath/sagetrac-mirror/commit/ebb11e18d0cda156743815f029cd74c92945a0a3)** to **[`40794b1`](https://github.com/sagemath/sagetrac-mirror/commit/40794b145b0dd7c5f2f97a7a812cba2c06659228)**

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
Changed commit from **[`40794b1`](https://github.com/sagemath/sagetrac-mirror/commit/40794b145b0dd7c5f2f97a7a812cba2c06659228)** to **[`da9770d`](https://github.com/sagemath/sagetrac-mirror/commit/da9770deaffdf65b8500f1f1288671b22f9f01ae)**

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
<div id="comment:6"></div>

Branch pushed to git repo; I updated commit sha1. New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/9af0fb9a28af3fd5d817f9ed09b3ec4e45890e08"><code>9af0fb9</code></a></td><td><code>Makefile (wheels, pypi-sdists): Add sagemath_bliss</code></td></tr><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/da9770deaffdf65b8500f1f1288671b22f9f01ae"><code>da9770d</code></a></td><td><code>pkgs/sagemath-bliss/MANIFEST.in: Fixup</code></td></tr></table>

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
Changed commit from **[`da9770d`](https://github.com/sagemath/sagetrac-mirror/commit/da9770deaffdf65b8500f1f1288671b22f9f01ae)** to **[`fda314b`](https://github.com/sagemath/sagetrac-mirror/commit/fda314bfc20d8698ace08e84d111f05bf2f42abb)**

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
<div id="comment:8"></div>

Branch pushed to git repo; I updated commit sha1. New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/fda314bfc20d8698ace08e84d111f05bf2f42abb"><code>fda314b</code></a></td><td><code>Merge tag '9.8.beta3' into t/34346/document_new_conda_packages_sagemath_sirocco_and_sagemath_bliss</code></td></tr></table>

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
<div id="comment:9"></div>

Branch pushed to git repo; I updated commit sha1. New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/aeaf807daa357166aad420497020b6d9a84db459"><code>aeaf807</code></a></td><td><code>pkgs/sagemath-standard/MANIFEST.in: Exclude sage/graphs/bliss.pyx</code></td></tr></table>

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
Changed commit from **[`fda314b`](https://github.com/sagemath/sagetrac-mirror/commit/fda314bfc20d8698ace08e84d111f05bf2f42abb)** to **[`aeaf807`](https://github.com/sagemath/sagetrac-mirror/commit/aeaf807daa357166aad420497020b6d9a84db459)**

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
<div id="comment:10"></div>

Branch pushed to git repo; I updated commit sha1. New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/3f6011067b48276d077a09a2b14673fea968423f"><code>3f60110</code></a></td><td><code>Makefile (pypi-sdists): Fix up</code></td></tr></table>

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
Changed commit from **[`aeaf807`](https://github.com/sagemath/sagetrac-mirror/commit/aeaf807daa357166aad420497020b6d9a84db459)** to **[`3f60110`](https://github.com/sagemath/sagetrac-mirror/commit/3f6011067b48276d077a09a2b14673fea968423f)**

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
Changed commit from **[`3f60110`](https://github.com/sagemath/sagetrac-mirror/commit/3f6011067b48276d077a09a2b14673fea968423f)** to **[`d3fbc9e`](https://github.com/sagemath/sagetrac-mirror/commit/d3fbc9e16288370754123c2c1b6daa3f9820049e)**

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
<div id="comment:11"></div>

Branch pushed to git repo; I updated commit sha1. New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/6c09919b6104f74e60a740e57e839024598a5d16"><code>6c09919</code></a></td><td><code>pkgs/sagemath-bliss/setup.cfg.m4: Allow python 3.11</code></td></tr><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/d7ff87e958228c5a0de41892acf096b16fc8a880"><code>d7ff87e</code></a></td><td><code>build/pkgs/sagemath_sirocco, pkgs/sagemath-sirocco: New</code></td></tr><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/b8bbd0db7e60e851daf5ab173afcbd857b8407b7"><code>b8bbd0d</code></a></td><td><code>build/pkgs/sagemath_mcqd, pkgs/sagemath-mcqd: New</code></td></tr><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/2fe5ce9b9668fa25984542c80e702d900d8633f5"><code>2fe5ce9</code></a></td><td><code>build/pkgs/sagemath_tdlib, pkgs/sagemath-tdlib: New</code></td></tr><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/a63e8ab180e8163263cc0198c4df7d895625d322"><code>a63e8ab</code></a></td><td><code>build/pkgs/sagemath_coxeter3, pkgs/sagemath-coxeter3: New</code></td></tr><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/7eb6186634d07d7f5fae03530463ca5df39d5ef0"><code>7eb6186</code></a></td><td><code>build/pkgs/sagemath_fes, pkgs/sagemath-fes: New</code></td></tr><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/d3fbc9e16288370754123c2c1b6daa3f9820049e"><code>d3fbc9e</code></a></td><td><code>build/pkgs/sagemath_meataxe, pkgs/sagemath-meataxe: New</code></td></tr></table>

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
Changed commit from **[`d3fbc9e`](https://github.com/sagemath/sagetrac-mirror/commit/d3fbc9e16288370754123c2c1b6daa3f9820049e)** to **[`31552b5`](https://github.com/sagemath/sagetrac-mirror/commit/31552b564b75bdf7b071d0bd34621ac16109bdf2)**

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
<div id="comment:12"></div>

Branch pushed to git repo; I updated commit sha1. New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/31552b564b75bdf7b071d0bd34621ac16109bdf2"><code>31552b5</code></a></td><td><code>Makefile, build/pkgs/sagelib/spkg-install: Add remaining optional packages with extensions</code></td></tr></table>

**Comment by mkoeppe** [comment]
Description changed:
``````diff
--- 
+++ 
@@ -1,3 +1,5 @@
-These are the two python extension modules that depend on the optional packages sirocco and bliss.
+These are the python extension modules that depend on the optional packages sirocco, bliss, ...
+
+We also add distros/conda.txt for some of these packages.
 
 We should add this info to https://doc.sagemath.org/html/en/installation/conda.html#installing-all-of-sagemath-from-conda-not-for-development
``````

**Comment by mkoeppe** [comment]
Author: **Matthias Koeppe**

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
<div id="comment:14"></div>

Branch pushed to git repo; I updated commit sha1. New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/94331467da2c62bccf375bc2528d2c4db6f73742"><code>9433146</code></a></td><td><code>Update SPKG.rst</code></td></tr></table>

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
Changed commit from **[`31552b5`](https://github.com/sagemath/sagetrac-mirror/commit/31552b564b75bdf7b071d0bd34621ac16109bdf2)** to **[`9433146`](https://github.com/sagemath/sagetrac-mirror/commit/94331467da2c62bccf375bc2528d2c4db6f73742)**

**Comment by mkoeppe** [comment]
Changed dependencies from **#32874** to **#32874, #34761**

**Comment by mkoeppe** [comment]
Work Issues: **remove fes**

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
Changed commit from **[`9433146`](https://github.com/sagemath/sagetrac-mirror/commit/94331467da2c62bccf375bc2528d2c4db6f73742)** to **[`b8a15c8`](https://github.com/sagemath/sagetrac-mirror/commit/b8a15c8ceebb08d22249ad32e0b92ff52a68b315)**

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
<div id="comment:19"></div>

Branch pushed to git repo; I updated commit sha1. This was a forced push. New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/f22454277ed174c284542809a2b5b4d9ead3bde9"><code>f224542</code></a></td><td><code>build/pkgs/sagemath_meataxe, pkgs/sagemath-meataxe: New</code></td></tr><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/a0411505e01004e27a4616e048fc91e96f0dcfe0"><code>a041150</code></a></td><td><code>Makefile, build/pkgs/sagelib/spkg-install: Add remaining optional packages with extensions</code></td></tr><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/b8a15c8ceebb08d22249ad32e0b92ff52a68b315"><code>b8a15c8</code></a></td><td><code>Update SPKG.rst</code></td></tr></table>

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
Changed commit from **[`b8a15c8`](https://github.com/sagemath/sagetrac-mirror/commit/b8a15c8ceebb08d22249ad32e0b92ff52a68b315)** to **[`d249067`](https://github.com/sagemath/sagetrac-mirror/commit/d2490671f57b996dee5193bc1202e6b7c93a82a8)**

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
<div id="comment:20"></div>

Branch pushed to git repo; I updated commit sha1. New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/444d3f3f581a0f1cb2f3497664ffb46405182024"><code>444d3f3</code></a></td><td><code>src/sage/libs/fes.pyx: Remove</code></td></tr><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/e7c8026920c146b96a2c2999139eded1825b3110"><code>e7c8026</code></a></td><td><code>src/sage/rings/polynomial/multi_polynomial_sequence.py: Remove use of fes</code></td></tr><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/1ecd04267fc16a0e6b7b9c8763cd9ac6bb37f5d8"><code>1ecd042</code></a></td><td><code>src/doc/en/reference/libs/index.rst: Remove fes</code></td></tr><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/d2490671f57b996dee5193bc1202e6b7c93a82a8"><code>d249067</code></a></td><td><code>Merge #34761</code></td></tr></table>

**Comment by mkoeppe** [comment]
Changed work issues from **remove fes** to none

**Comment by mkoeppe** [comment]
Description changed:
``````diff
--- 
+++ 
@@ -1,4 +1,9 @@
 These are the python extension modules that depend on the optional packages sirocco, bliss, ...
+- https://pypi.org/project/sagemath-meataxe
+- https://pypi.org/project/sagemath-sirocco
+- https://pypi.org/project/sagemath-bliss/
+- https://pypi.org/project/sagemath-mcqd/
+- https://pypi.org/project/sagemath-coxeter3/
 
 We also add distros/conda.txt for some of these packages.
 
``````

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
Changed commit from **[`d249067`](https://github.com/sagemath/sagetrac-mirror/commit/d2490671f57b996dee5193bc1202e6b7c93a82a8)** to **[`b15ad5f`](https://github.com/sagemath/sagetrac-mirror/commit/b15ad5fe59e8e22dbd1fbf53c9f9ccd514142c02)**

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
<div id="comment:23"></div>

Branch pushed to git repo; I updated commit sha1. New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/b15ad5fe59e8e22dbd1fbf53c9f9ccd514142c02"><code>b15ad5f</code></a></td><td><code>pkgs/sagemath-meataxe/README.rst: Fix rst syntax</code></td></tr></table>

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
<div id="comment:25"></div>

Branch pushed to git repo; I updated commit sha1. New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/054e90758a345232d365605b9a9ef7aaea7ba55f"><code>054e907</code></a></td><td><code>Merge tag '9.8.beta4' into t/34346/document_new_conda_packages_sagemath_sirocco_and_sagemath_bliss</code></td></tr></table>

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
Changed commit from **[`b15ad5f`](https://github.com/sagemath/sagetrac-mirror/commit/b15ad5fe59e8e22dbd1fbf53c9f9ccd514142c02)** to **[`054e907`](https://github.com/sagemath/sagetrac-mirror/commit/054e90758a345232d365605b9a9ef7aaea7ba55f)**

**Comment by mkoeppe** [comment]
Description changed:
``````diff
--- 
+++ 
@@ -4,6 +4,7 @@
 - https://pypi.org/project/sagemath-bliss/
 - https://pypi.org/project/sagemath-mcqd/
 - https://pypi.org/project/sagemath-coxeter3/
+- https://pypi.org/project/sagemath-tdlib/
 
 We also add distros/conda.txt for some of these packages.
 
``````

**Comment by kwankyu** [comment]
<div id="comment:27" align="right">comment:27</div>

No tox.ini for these distribution packages?

**Comment by mkoeppe** [comment]
<div id="comment:28" align="right">comment:28</div>

Good idea, I'll add them

**Comment by kwankyu** [comment]
<div id="comment:29" align="right">comment:29</div>

and these lines (of `pkgs/sagemath-bliss/setup.py` for instance) are right?

```sage
if len(sys.argv) > 1 and (sys.argv[1] == "sdist" or sys.argv[1] == "egg_info"):
    sdist = True
else:
    sdist = False

if sdist:
    cmdclass = {}
else:
    ...
    lines that build source distribution ???
    ...
```

When running

```
    python3 -u setup.py --no-user-cfg sdist --dist-dir "$SAGE_DISTFILES"
```
the "if condition" actually fails so that the sdist is actually built, but this seems just a good luck. Am I reading something wrong?

**Comment by mkoeppe** [comment]
<div id="comment:31" align="right">comment:31</div>

Replying to [Kwankyu Lee](#comment%3A29):
> and these lines (of `pkgs/sagemath-bliss/setup.py` for instance) are right?
> 
> ```sage
> if len(sys.argv) > 1 and (sys.argv[1] == "sdist" or sys.argv[1] == "egg_info"):
>     sdist = True
> [...] 
> When running
> {{{
>     python3 -u setup.py --no-user-cfg sdist --dist-dir "$SAGE_DISTFILES"
> }}}
> the "if condition" actually fails 
> ```

Nice catch, indeed this test will go wrong when there are global options.
We have this in many of our `setup.py` scripts. It's only an optimization - avoiding to cythonize when it is unnecessary.

**Comment by mkoeppe** [comment]
Changed dependencies from **#32874, #34761** to **#32874, #34761, #34858**

**Comment by mkoeppe** [comment]
<div id="comment:32" align="right">comment:32</div>

I'm getting rid of this test where it was copied from in #34858.

**Comment by mkoeppe** [comment]
Changed dependencies from **#32874, #34761, #34858** to **#32874, #34761, #34858, #34855**

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
<div id="comment:34"></div>

Branch pushed to git repo; I updated commit sha1. Last 10 new commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/00deebede6ae54768e8648bee89038e26d3515f8"><code>00deebe</code></a></td><td><code>pkgs/sagemath-objects/setup.py: Run finder also for sdist, egg_info, dist_info</code></td></tr><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/39bd748020fb651e5aeb7640ffe182e493353c79"><code>39bd748</code></a></td><td><code>src/sage/dynamics/arithmetic_dynamics/projective_ds.py: Remove unused import of typing_extensions</code></td></tr><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/e22943612656b225396e4dea4fae654108b3cf3d"><code>e229436</code></a></td><td><code>Merge #34859</code></td></tr><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/2b39b3d2e2b0a8720dfcd764345c03c120e06396"><code>2b39b3d</code></a></td><td><code>Merge #34858</code></td></tr><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/c59622a42624037d4eba61e353ea07ae00bd55f6"><code>c59622a</code></a></td><td><code>build/pkgs/sagemath*/spkg-src: Use build</code></td></tr><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/7fc93d06de9f0e34d2ea2077f1a022750c722235"><code>7fc93d0</code></a></td><td><code>build/pkgs/sagemath*/spkg-src: Use --skip-dependency-check</code></td></tr><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/4940db4cf4d32617f23a87e04bddaa01061a7f5f"><code>4940db4</code></a></td><td><code>build/make/Makefile.in: Add targets SPKG-src for script packages</code></td></tr><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/573fcfdfba04041260f8e06e54e37eb8a9f85da4"><code>573fcfd</code></a></td><td><code>build/make/Makefile.in: Move targets pypi-sdists, wheel, pypi-wheels here; use SPKG-sdist targets</code></td></tr><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/0bd13ac7095789740ce098e23a7b0af4978c621c"><code>0bd13ac</code></a></td><td><code>build/make/Makefile.in: Remove duplicate setting of PYPI_WHEEL_PACKAGES</code></td></tr><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/c5da21eb499f95bc918b1f833d69856a24da4e2f"><code>c5da21e</code></a></td><td><code>Merge #34855</code></td></tr></table>

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
Changed commit from **[`054e907`](https://github.com/sagemath/sagetrac-mirror/commit/054e90758a345232d365605b9a9ef7aaea7ba55f)** to **[`c5da21e`](https://github.com/sagemath/sagetrac-mirror/commit/c5da21eb499f95bc918b1f833d69856a24da4e2f)**

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
<div id="comment:35"></div>

Branch pushed to git repo; I updated commit sha1. New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/96864238fe7712541ec373098bb2f58d607a041c"><code>9686423</code></a></td><td><code>build/pkgs/sagemath*/spkg-src: Use build</code></td></tr></table>

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
Changed commit from **[`c5da21e`](https://github.com/sagemath/sagetrac-mirror/commit/c5da21eb499f95bc918b1f833d69856a24da4e2f)** to **[`9686423`](https://github.com/sagemath/sagetrac-mirror/commit/96864238fe7712541ec373098bb2f58d607a041c)**
