### ISSUE TITLE
.devcontainer/portability-ubuntu-jammy-standard fails in GitHub Codespaces

### ISSUE THREAD

**Issue by mkoeppe** [sagemath/sage#34403]
<div id="comment:0"></div>

Follow-up from 

- #33671: Add devcontainer.json for development with VS Code in a Docker container.

**ISSUE**: `.devcontainer/portability-ubuntu-jammy-standard` fails in [GitHub](../wiki/GitHub) Codespaces as reported first in 

[#33671 comment:271](https://github.com/sagemath/sage/issues/33671#comment:271)

**TEST**: github codespaces uses the devcontainer CLI so you probably can reproduce this issue locally using ​https://code.visualstudio.com/docs/remote/devcontainer-cli.

- Install devcontainer CLI: `npm install -g `@`devcontainers/cli`
- Create and run devcontainer: `devcontainer up  --workspace-folder .` in sage source tree

Depends on #33671

CC:  @tobiasdiez

Component: **user interface**

_Issue created by migration from https://trac.sagemath.org/ticket/34403_

**Comment by kwankyu** [comment]
Description changed:
``````diff
--- 
+++ 
@@ -1,3 +1,10 @@
-Follow-up from #33671 needs_work enhancement
-Add devcontainer.json for development with VS Code in a Docker container.
+Follow-up from 
 
+- #33671: Add devcontainer.json for development with VS Code in a Docker container.
+
+`.devcontainer/portability-ubuntu-jammy-standard` fails in [GitHub](../wiki/GitHub) Codespaces as reported first in 
+
+[#33671 comment:271](https://github.com/sagemath/sage/issues/33671#comment:271)
+
+
+
``````

**Comment by kwankyu** [comment]
Description changed:
``````diff
--- 
+++ 
@@ -2,9 +2,13 @@
 
 - #33671: Add devcontainer.json for development with VS Code in a Docker container.
 
-`.devcontainer/portability-ubuntu-jammy-standard` fails in [GitHub](../wiki/GitHub) Codespaces as reported first in 
+**ISSUE**: `.devcontainer/portability-ubuntu-jammy-standard` fails in [GitHub](../wiki/GitHub) Codespaces as reported first in 
 
 [#33671 comment:271](https://github.com/sagemath/sage/issues/33671#comment:271)
 
+**TEST**: github codespaces uses the devcontainer CLI so you probably can reproduce this issue locally using ​https://code.visualstudio.com/docs/remote/devcontainer-cli.
+
+- Install devcontainer CLI: `npm install -g `@`devcontainers/cli`
+- Create and run devcontainer: `devcontainer up  --workspace-folder .` in sage source tree
 
 
``````

**Comment by mkoeppe** [comment]
<div id="comment:5" align="right">comment:5</div>

Looks like codespaces is now available to all

**Comment by mkoeppe** [comment]
Works for me. One needs an 8-core or 16-core configuration so that there is enough disk space. I'm adding this detail in #36954.
