### ISSUE TITLE
Implement infinite sums and products using lazy Laurent and Taylor series

### ISSUE THREAD

**Issue by tscrim** [sagemath/sage#34404]
<div id="comment:0"></div>

We should support these when each term/factor is strictly increasing in valuation. This can even be relaxed to weakly increasing, but then we allow the possibility it will run for forever.

CC:  @mantepse

Component: **algebra**

Keywords: **lazy power series, LazyPowerSeries**

_Issue created by migration from https://trac.sagemath.org/ticket/34404_

**Comment by tscrim** [comment]
Description changed:
``````diff
--- 
+++ 
@@ -1 +1 @@
-We should support these when each term/factor is strictly increasing in degree. This can even be relaxed to weakly increasing, but then we allow the possibility it will run for forever.
+We should support these when each term/factor is strictly increasing in valuation. This can even be relaxed to weakly increasing, but then we allow the possibility it will run for forever.
``````

**Comment by mantepse** [comment]
Closing manually, because the PR has been merged.
