### ISSUE TITLE
Wrong result for multivariate polynomial evaluation

### ISSUE THREAD

**Issue by yyyyx4** [sagemath/sage#34417]
<div id="comment:0"></div>

Example:

```sage
sage: R.<x,y> = Zmod(9)[]
sage: f = x^2 * y
sage: f(3, 1)
1
```

Upstream: **Fixed upstream, in a later stable release.**

CC:  @malb

Component: **algebra**

_Issue created by migration from https://trac.sagemath.org/ticket/34417_

**Comment by kwankyu** [comment]
<div id="comment:5" align="right">comment:5</div>

See #34591 for a path to a solution.

**Comment by kwankyu** [comment]
<div id="comment:6" align="right">comment:6</div>

Yes. There was a bug in `fast_map_common_subexp()`. I made a PR to Singular:

https://github.com/Singular/Singular/pull/1151

**Comment by kwankyu** [comment]
Upstream: **Reported upstream. No feedback yet.**

**Comment by kwankyu** [comment]
Changed upstream from **Reported upstream. No feedback yet.** to **Fixed upstream, in a later stable release.**

**Comment by kwankyu** [comment]
<div id="comment:9" align="right">comment:9</div>

Replying to [Kwankyu Lee](#comment%3A5):
> See #34591 for a path to a solution.

#34591 will also be fixed by the upstream patch.

**Comment by DaveWitteMorris** [comment]
<div id="comment:10" align="right">comment:10</div>

Thanks for fixing this! I looked at the singular code, but couldn't understand it, so didn't know what was wrong or how to fix it.

**Comment by yyyyx4** [comment]
This appears to be working correctly now.
