### ISSUE TITLE
Sirocco improvements: fix base number fields and braid monodromy of arrangements

### ISSUE THREAD

**Issue by enriqueartal** [sagemath/sage#34415]
<div id="comment:0"></div>

Now the input of the functions or methods `braid_monodromy` and `fundamental_group` is a polynomial `f(x, y)`  (or a curve defined by this polynomial) with coefficients in a number field `K` with a precise embedding in `QQbar`. 

The first main change proposed by this issue is to construct an extension `K1` containing the imaginary unit; this extension comes also with an embedding in `QQbar`. The main reason is that several intermediate computations deal with `f(x0,y)` where `x0` is a Gauss rational; considering these polynomials in `K1[y]` instead of `QQbar[y]` dramatically increase the speed of some of these intermediate computations.

The second main change is to allow the input to be a list of polynomials instead of just one. The method `braid_monodromy` starts with changes of variables of the type `x: x + y` till the global degree of `f` coincides with its `y`-degree. Next step is to compute the roots in `x` of its discriminant with respect to `y` using an internal funtion called `disc`. Both changes are useful for this function: Applying it to an example of a polynomial of degree 18 with coefficients in a number field of index 12 yields to more that 30 minutes of computation time. This polynomial has three factors. The computation of the discriminant of each factor and the resultant of the three pairs of factors is done in 15 seconds.

A new function `braid_monodromy_arrangement` adds a new feature, i.e., it computes the braid monodromy of the product of the polynomials in the list, with a new information, a dictionnary associating each strand to a precise polynomial.

The third main change is to provide a new way to get the presentation of the fundamental group of the complement of the curve. This new method has two advantages: the obtained presentation has information about the homotopy type of the complement of the affine curve and computations are faster. When computing the fundamental group, the relations come from the following computation; take a generator `g` of a free group and a braid `s`; the relation is obtained as `(g*s)/g` (the natural action of the braid group on the free group is already implemented. The problem is that these braids may be extremely long and these computations may take very long time. The new method performs less computations and cut the above method in several steps which takes into account some conjugations tricks. 

Finally, some computations have been parallelized. Also, sometimes the computations stopped for precision or parallelism issues and some solutions avoid these problems. 

The branch `puiseux` of this fork(https://github.com/enriqueartal/sage) contains the modifications.

CC:  @miguelmarco

Component: **algebraic geometry**

Author: **Enrique Artal**

Branch/Commit: **[u/enriqueartal/sirocco_improvements__discriminant_and_optional_information](https://github.com/sagemath/sagetrac-mirror/tree/u/enriqueartal/sirocco_improvements__discriminant_and_optional_information) @ [`963d744`](https://github.com/sagemath/sagetrac-mirror/commit/963d7442c9a6d22772103a2ef476613d7233a34b)**

_Issue created by migration from https://trac.sagemath.org/ticket/34415_

**Comment by enriqueartal** [comment]
Description changed:
``````diff
--- 
+++ 
@@ -1,7 +1,7 @@
-Given a polynomial `f(x, y)`, the method `braid_monodromy` starts with changes of variables of the type `x:x+y` till the global degree of `f` coincides with its `y`-degree. Next step is to compute its discriminant with respect to `y`.
+Given a polynomial `f(x, y)`, the method `braid_monodromy` starts with changes of variables of the type `x: x + y` till the global degree of `f` coincides with its `y`-degree. Next step is to compute its discriminant with respect to `y`.
 
 Applying it to an example of a polynomial of degree 18 with coefficients in a number field of index 12 yields to more that 30 minutes of computation time. This polynomial has three factors. The computation of the discriminant of each factor and the resultant of the three pairs of factors is done in 15 seconds.
 
 Now `Sirocco` takes into account the factors, so computing the discriminant via the factorization would reduce the time of computation. 
 
-In the same ideas it would be useful to know to which irreducible component each string of the braids correspond. As a first approach, at least the result could contain also the number of changes of variables and the base point, which contains the information to decide about the relationship of strings and factors.
+In the same ideas, it is useful for arrangements of curves to know to which irreducible component each strand of the braids correspond. A new function is define, `braid_monodromy_arrangement` which yields both the braid monodromy and the information of the strands
``````

**Comment by enriqueartal** [comment]
Description changed:
``````diff
--- 
+++ 
@@ -4,4 +4,6 @@
 
 Now `Sirocco` takes into account the factors, so computing the discriminant via the factorization would reduce the time of computation. 
 
-In the same ideas, it is useful for arrangements of curves to know to which irreducible component each strand of the braids correspond. A new function is define, `braid_monodromy_arrangement` which yields both the braid monodromy and the information of the strands
+In the same ideas, it is useful for arrangements of curves to know to which irreducible component each strand of the braids correspond. A new function is define, `braid_monodromy_arrangement` which yields both the braid monodromy and the information of the strands.
+
+Finally, a way to obtain a Puiseux presentation of the fundamental group is given.
``````

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
<div id="comment:18"></div>

Branch pushed to git repo; I updated commit sha1. New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/47a78659f64cba1aede8afddd3a0db9ffc2e59f8"><code>47a7865</code></a></td><td><code>Merge branch 'develop' into t/34415/sirocco_improvements__discriminant_and_optional_information</code></td></tr><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/7a2556b4e6f0aa01350ca5e287779d0e9537f49a"><code>7a2556b</code></a></td><td><code>Test passed. Check trac 26503</code></td></tr><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/bcb4797ec04e486f58096f2575e854bc152d1378"><code>bcb4797</code></a></td><td><code>tests</code></td></tr></table>

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
Changed commit from **[`c0ed857`](https://github.com/sagemath/sagetrac-mirror/commit/c0ed8577e7381346fea9af0d6a5ac60c016a9560)** to **[`bcb4797`](https://github.com/sagemath/sagetrac-mirror/commit/bcb4797ec04e486f58096f2575e854bc152d1378)**

**Comment by enriqueartal** [comment]
<div id="comment:19" align="right">comment:19</div>

This version passess the tests. At some point the description will be updated since more tasks have been done to shorten times of execution by replacing at some places `QQbar` by some number fields embedded in `QQbar`. Besides typos corrctions and more serious improvements there are a couple of things that could be done:
- Create classes of arrangement of affine or projective curves; besides braid monodromy of fundamental group, other methods could be created, e.g. for singular points assignment of branches to components.
- For the computation of `braid_monodromy`, there is an intermediate step consisting in the computation of a *geometric basis* of the fundamental group of a punctured plane. Sometimes it gives an error stopping the computations; we (@mmarco and me) analyzed the problem and he found out how to correct it.

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
<div id="comment:20"></div>

Branch pushed to git repo; I updated commit sha1. New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/a4f39161ee4c941e49a2d98e0ca6473e08f5f5c3"><code>a4f3916</code></a></td><td><code>Merge branch 'develop' into t/34415/sirocco_improvements__discriminant_and_optional_information</code></td></tr><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/704e58d15e536f4198991e023602c903a41d15ff"><code>704e58d</code></a></td><td><code>Merge branch 'develop' into t/34415/sirocco_improvements__discriminant_and_optional_information</code></td></tr><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/770384ee17ae018a865d17b30dc80e07cc3f9f1b"><code>770384e</code></a></td><td><code>Geometric basis and oriented circuits</code></td></tr></table>

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
Changed commit from **[`bcb4797`](https://github.com/sagemath/sagetrac-mirror/commit/bcb4797ec04e486f58096f2575e854bc152d1378)** to **[`770384e`](https://github.com/sagemath/sagetrac-mirror/commit/770384ee17ae018a865d17b30dc80e07cc3f9f1b)**

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
Changed commit from **[`770384e`](https://github.com/sagemath/sagetrac-mirror/commit/770384ee17ae018a865d17b30dc80e07cc3f9f1b)** to **[`bd9157c`](https://github.com/sagemath/sagetrac-mirror/commit/bd9157c6d3ac5cd95edb8f611926929c118e8da5)**

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
<div id="comment:21"></div>

Branch pushed to git repo; I updated commit sha1. New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/1ce7b6c6d49031ad8419414d642f7c7e65a5e5d8"><code>1ce7b6c</code></a></td><td><code>braid monodromy test to be checked</code></td></tr><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/bd9157c6d3ac5cd95edb8f611926929c118e8da5"><code>bd9157c</code></a></td><td><code>geometric_basis corrected</code></td></tr></table>

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
Changed commit from **[`bd9157c`](https://github.com/sagemath/sagetrac-mirror/commit/bd9157c6d3ac5cd95edb8f611926929c118e8da5)** to **[`443a53c`](https://github.com/sagemath/sagetrac-mirror/commit/443a53c2d6b8934af147d0e5702cf304b8cc9f74)**

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
<div id="comment:22"></div>

Branch pushed to git repo; I updated commit sha1. New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/443a53c2d6b8934af147d0e5702cf304b8cc9f74"><code>443a53c</code></a></td><td><code>add optional in a test</code></td></tr></table>

**Comment by fchapoton** [comment]
<div id="comment:23" align="right">comment:23</div>

no space around `=` signs inside the arguments of functions, please (pep8)

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
Changed commit from **[`443a53c`](https://github.com/sagemath/sagetrac-mirror/commit/443a53c2d6b8934af147d0e5702cf304b8cc9f74)** to **[`963d744`](https://github.com/sagemath/sagetrac-mirror/commit/963d7442c9a6d22772103a2ef476613d7233a34b)**

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
<div id="comment:24"></div>

Branch pushed to git repo; I updated commit sha1. New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/963d7442c9a6d22772103a2ef476613d7233a34b"><code>963d744</code></a></td><td><code>correct indent for lint</code></td></tr></table>
