### ISSUE TITLE
update argon2_cffi and sagenb_export

### ISSUE THREAD

**Issue by fchapoton** [sagemath/sage#34419]
<div id="comment:0"></div>

to avoid some dependencies to six

also cycler no longer depends on six

CC:  @mkoeppe @kiwifb

Component: **packages: standard**

Author: **Frédéric Chapoton**

Branch/Commit: **[u/chapoton/34419](https://github.com/sagemath/sagetrac-mirror/tree/u/chapoton/34419) @ [`f495e1a`](https://github.com/sagemath/sagetrac-mirror/commit/f495e1ab3379668ab4e3b568c5e54859c88ae4c9)**

_Issue created by migration from https://trac.sagemath.org/ticket/34419_

**Comment by fchapoton** [comment]
Description changed:
``````diff
--- 
+++ 
@@ -1 +1,3 @@
 to avoid some dependencies to six
+
+also cycler no longer depends on six
``````

**Comment by fchapoton** [comment]
<div id="comment:6" align="right">comment:6</div>

now a partial duplicate of #34676

**Comment by mkoeppe** [comment]
<div id="comment:8" align="right">comment:8</div>

`sagenb_export` needs upstream_url in checksums.ini

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
Changed commit from **[`2fadb89`](https://github.com/sagemath/sagetrac-mirror/commit/2fadb8987c968f605b18e8ddd5b290fbc57d6a5b)** to **[`f495e1a`](https://github.com/sagemath/sagetrac-mirror/commit/f495e1ab3379668ab4e3b568c5e54859c88ae4c9)**

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
<div id="comment:9"></div>

Branch pushed to git repo; I updated commit sha1. New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/49793edd0cc17d7d43d43af0314bed0ddcefb878"><code>49793ed</code></a></td><td><code>Merge branch 'u/chapoton/34419' in 9.8.b2</code></td></tr><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/f495e1ab3379668ab4e3b568c5e54859c88ae4c9"><code>f495e1a</code></a></td><td><code>adding upstream_url</code></td></tr></table>

**Comment by fchapoton** [comment]
dropping this one, partially done in #35416
