### ISSUE TITLE
show explicit formulas in documentation of WeierstrassIsomorphism

### ISSUE THREAD

**Issue by yyyyx4** [sagemath/sage#34439]
<div id="comment:0"></div>

Currently, the `WeierstrassIsomorphism` class doesn't actually specify how the isomorphism given by a tuple `(u,r,s,t)` is defined.
While this is fairly standard, it can't hurt to make it more explicit in the documentation, hence this very simple patch.

(The related `baseWI` class does show the coordinate transform, but it's written in the form corresponding more easily to the inverse isomorphism, and the change in curve models is not shown.)

Component: **elliptic curves**

Author: **Lorenz Panny**

_Issue created by migration from https://trac.sagemath.org/ticket/34439_

**Comment by kwankyu** [comment]
<div id="comment:4" align="right">comment:4</div>

Sage documentation does not show the docstring of the class `__init__` method. Hence your additional documentation reads incomplete. See

https://7e5829a3e3def0e2863ffb3edb2c324be073d1ac--sagemath-tobias.netlify.app/reference/arithmetic_curves/sage/schemes/elliptic_curves/weierstrass_morphism.html#module-sage.schemes.elliptic_curves.weierstrass_morphism

I suggest to move the docstring of `__init__` to the class docstring and combine with your docstring (except TESTS blocks). You can use the class `ProjectiveCurve`

https://github.com/sagemath/sage-prod/blob/develop/src/sage/schemes/curves/projective_curve.py

as a template.

As I skim through elliptic curves modules, I see that many of them need similar edits.

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
<div id="comment:5"></div>

Branch pushed to git repo; I updated commit sha1. This was a forced push. New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/11e8992edd551fdd8ff7f5037fc7d4ba48f95688"><code>11e8992</code></a></td><td><code>add explicit formulas to documentation of WeierstrassIsomorphism</code></td></tr><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/a8082ce73e9a934b685d6fc371706687cee41141"><code>a8082ce</code></a></td><td><code>lift documentation from .__init__() to class and tweak</code></td></tr></table>

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
Changed commit from **[`7e5829a`](https://github.com/sagemath/sagetrac-mirror/commit/7e5829a3e3def0e2863ffb3edb2c324be073d1ac)** to **[`a8082ce`](https://github.com/sagemath/sagetrac-mirror/commit/a8082ce73e9a934b685d6fc371706687cee41141)**

**Comment by yyyyx4** [comment]
<div id="comment:6" align="right">comment:6</div>

Thanks for pointing that out. Is it better now?

**Comment by mkoeppe** [comment]
Removed branch from the issue description because it has been replaced by PR #34967
