### ISSUE TITLE
Fix monomial_coefficients for submodules of free modules from sage.modules

### ISSUE THREAD

**Issue by mkoeppe** [sagemath/sage#34455]
<div id="comment:0"></div>

Bug: 

```
sage: V = ZZ^3
sage: U = V.submodule([[1, 2, 3], [1, 1, 1]])
sage: U
sage: u = U([2, 3, 4])
sage: u.monomial_coefficients()
{0: 2, 1: 3, 2: 4}
```
This is incorrect - by definition of `monomial_coefficients`, basis indices are mapped to coefficients; but

```
sage: u.parent().basis()
[
(1, 0, -1),
(0, 1, 2)
]
```

We also add a method `_test_monomial_coefficients` to run some tests on this and related methods of `ModulesWithBasis`.

Part of #30309

CC:  @tscrim @mmasdeu

Component: **linear algebra**

Author: **Matthias Koeppe, ...**

_Issue created by migration from https://trac.sagemath.org/ticket/34455_

**Comment by mkoeppe** [comment]
> It seems to be easy to fix: We change
> 
> ```python
> def monomial_coefficients(self, copy=True):
>     return self.__element.monomial_coefficients(copy=copy)
> ```
> 
> (or `self.element()`).

Done now in d41535bd1c36240c71e9344f71d18d2524548e9d (on https://github.com/sagemath/sage/pull/37526)

**Comment by mkoeppe** [comment]
Removed branch from the Issue description; replaced by PR #37526.

**Comment by mkoeppe** [comment]
@tscrim For now, as #25033 is unresolved, I am allowing `monomial_coefficients` to raise `NotImplementedError` without causing the test suite to fail.

**Comment by mkoeppe** [comment]
@tscrim I still see this failure and similar failures with #37526; I'm not sure if your explanation in https://github.com/sagemath/sage/issues/34455#issuecomment-1418185473 covers this or if you have suggestion for me how to debug this:
```
sage -t --random-seed=220469390813921570466256613500867018872 src/sage/algebras/lie_algebras/free_lie_algebra.py
**********************************************************************
File "src/sage/algebras/lie_algebras/free_lie_algebra.py", line 374, in sage.algebras.lie_algebras.free_lie_algebra.FreeLieAlgebra.__init__
Failed example:
    TestSuite(L).run()
Expected nothing
Got:
      Failure in _test_monomial_coefficients:
      Traceback (most recent call last):
        File "/Users/mkoeppe/s/sage/sage-rebasing/worktree-green/src/sage/misc/sage_unittest.py", line 297, in run
          test_method(tester=tester)
        File "/Users/mkoeppe/s/sage/sage-rebasing/worktree-green/src/sage/categories/modules_with_basis.py", line 1497, in _test_monomial_coefficients
          tester.assertEqual(self, self.parent().linear_combination(
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/Users/mkoeppe/s/sage/sage-rebasing/worktree-green/src/sage/categories/modules.py", line 630, in linear_combination
          return self.sum(coeff * element
                 ^^^^^^^^^^^^^^^^^^^^^^^^
        File "/Users/mkoeppe/s/sage/sage-rebasing/worktree-green/src/sage/categories/additive_monoids.py", line 71, in sum
          return sum(args, self.zero())
                 ^^^^^^^^^^^^^^^^^^^^^^
        File "/Users/mkoeppe/s/sage/sage-rebasing/worktree-green/src/sage/categories/modules.py", line 630, in <genexpr>
          return self.sum(coeff * element
                         ^^^^^^^^^^^^^^^^
        File "/Users/mkoeppe/s/sage/sage-rebasing/worktree-green/src/sage/categories/modules_with_basis.py", line 1498, in <genexpr>
          (basis[index], coefficient)
           ~~~~~^^^^^^^
        File "sage/structure/parent.pyx", line 1283, in sage.structure.parent.Parent.__getitem__
          return meth(n)
        File "/Users/mkoeppe/s/sage/sage-rebasing/worktree-green/src/sage/categories/enumerated_sets.py", line 466, in __getitem__
          return self.unrank(i)
                 ^^^^^^^^^^^^^^
        File "/Users/mkoeppe/s/sage/sage-rebasing/worktree-green/src/sage/categories/enumerated_sets.py", line 741, in _unrank_from_iterator
          raise ValueError(f"{r=} must be an integer")
      ValueError: r=x0 must be an integer
      ------------------------------------------------------------
      The following tests failed: _test_monomial_coefficients
    Failure in _test_elements
    The following tests failed: _test_elements
```

**Comment by tscrim** [comment]
> @tscrim I still see this failure and similar failures with #37526; I'm not sure if your explanation in [#34455 (comment)](https://github.com/sagemath/sage/issues/34455#issuecomment-1418185473) covers this or if you have suggestion for me how to debug this:

That comment doesn't apply to the free Lie algebra. In this case, the basis knows how to enumerate itself, but it doesn't match how the internal storage of elements is done:
```
sage: L = LieAlgebra(QQ, 3, 'x')
sage: v = L.an_element()
sage: LB = v.parent()
sage: LB.basis()
Disjoint union of Lazy family (graded basis(i))_{i in Positive integers}
```
In this case, we know exactly what the sets correspond to (Lyndon words), but the `_test_monomial_coefficients` is actually testing a stronger condition than what is required by the category. I'm not opposed to this strengthening as this consistency is good. Yet there is a technical issue here with not wanting to more directly expose the internal functionality (the `LieBracket`/`LieGenerator` classes), having a good enumeration/construction for the basis, and simplicity of the implementation. Note that this also has to apply to the Hall basis, where we don't have a good way to index them.

**Comment by mkoeppe** [comment]
> the `_test_monomial_coefficients` is actually testing a stronger condition than what is required by the category

I'm not sure that I understand what you mean. Are you saying that this (from `_test_monomial_coefficients`) is not guaranteed by the category?
```
tester.assertEqual(self, self.parent().linear_combination(
                (basis[index], coefficient)
                for index, coefficient in d.items()))
```

**Comment by tscrim** [comment]
> > the `_test_monomial_coefficients` is actually testing a stronger condition than what is required by the category
> 
> I'm not sure that I understand what you mean. Are you saying that this (from `_test_monomial_coefficients`) is not guaranteed by the category?
> 
> ```
> tester.assertEqual(self, self.parent().linear_combination(
>                 (basis[index], coefficient)
>                 for index, coefficient in d.items()))
> ```

Yes, that's correct. The `basis()` method just needs to return a model for the set of all basis elements. Specifically, I don't think is is required to be indexed by the same set that the elements internally use. It's possible that when code was lifted from CFM that this was not taken into account (since nearly all implementations do follow this additional specification given by the test), but there is currently no specification that I can see that requires this.

**Comment by mkoeppe** [comment]
I don't know, to me the documentation of the category leaves no doubt that the `monomial_coefficients` refer to the indices of the basis, not to something unspecified/internal of the elements.

**Comment by tscrim** [comment]
I am not quite convinced that it currently requires the consistency, but that is somewhat moot as I agree that it would be good for the result of `basis()` to have a `__getitem__` that takes the indices and returns basis elements. That's what the free Lie algebra bases need to do.
