### ISSUE TITLE
q-commuting Laurent polynomials

### ISSUE THREAD

**Issue by tscrim** [sagemath/sage#34472]
<div id="comment:0"></div>

Followup to #34412 following Frédéric’s comment. We implement q-commuting Laurent polynomials.

Depends on #34412

CC:  @fchapoton

Component: **algebra**

Keywords: **q-commuting, Laurent polynomial**

_Issue created by migration from https://trac.sagemath.org/ticket/34472_

**Comment by fchapoton** [comment]
closing as done in #35054
