### ISSUE TITLE
Update sympy to 1.12

### ISSUE THREAD

**Issue by mkoeppe** [sagemath/sage#34489]
<div id="comment:0"></div>

Depends on #34118

CC:  @kiwifb @oscarbenjamin @antonio-rojas @DaveWitteMorris

Component: **packages: standard**

Branch/Commit: **[u/gh-oscarbenjamin/update_sympy_to_1_12](https://github.com/sagemath/sagetrac-mirror/tree/u/gh-oscarbenjamin/update_sympy_to_1_12) @ [`4b87c2f`](https://github.com/sagemath/sagetrac-mirror/commit/4b87c2f258007d074d17e37869d8298f9b774bb8)**

_Issue created by migration from https://trac.sagemath.org/ticket/34489_

**Comment by tornaria** [comment]
I didn't need this for sympy 1.12, see: #35635, and please review.
