### ISSUE TITLE
Expand Schubert polynomials in the Key basis

### ISSUE THREAD

**Issue by trevorkarn** [sagemath/sage#34518]
<div id="comment:0"></div>

Expand Schubert polynomials in the Key Basis using the peelable tableaux algorithm of Reiner and Shimozono.

Depends on #34260
Depends on #34414

CC:  @tscrim @trevorkarn

Component: **combinatorics**

Keywords: **gsoc2022 key-polynomial schubert-polynomial**

Author: **Trevor K. Karn**

Branch/Commit: **[u/tscrim/schubert_key-34518](https://github.com/sagemath/sagetrac-mirror/tree/u/tscrim/schubert_key-34518) @ [`a4107d3`](https://github.com/sagemath/sagetrac-mirror/commit/a4107d3f23c5bb2ea6f828a0c33deb89ec636f3d)**

Reviewer: **Travis Scrimshaw**

_Issue created by migration from https://trac.sagemath.org/ticket/34518_

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
<div id="comment:4"></div>

Branch pushed to git repo; I updated commit sha1. This was a forced push. Last 10 new commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/40e135ec0f1ffc215afbd3e3d49d2aaed4ee5eb6"><code>40e135e</code></a></td><td><code>Simplify subs in finite case</code></td></tr><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/e7313bc060fbe0cda30f2e3a2126fcd1f3ab10ec"><code>e7313bc</code></a></td><td><code>Simplify action on infinite polynomial ring</code></td></tr><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/cd7d6b5fae2968363a21e65b40f79891973bacb4"><code>cd7d6b5</code></a></td><td><code>poly_gen -> poly_gens, uniformly use .subs, and while f.monomials -> while f</code></td></tr><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/d2776543f465a77be82901da1ecf9bbf34e64a02"><code>d277654</code></a></td><td><code>Remove duplicated code</code></td></tr><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/0ab036ad218986914f1a67af53a2819fb9fcf36d"><code>0ab036a</code></a></td><td><code>Add `_mul_` and remove .product()</code></td></tr><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/70e46873bdd5ec0c4d2a5cd4e1b9e2b41c8fa246"><code>70e4687</code></a></td><td><code>Add test for rational division and try with coefficients in GF(5)</code></td></tr><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/197b53e3db4adc8620a1fb9cbcacd64341a42153"><code>197b53e</code></a></td><td><code>PEP8 compliance</code></td></tr><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/4855ece48594a47c3d565477da7602b44592df2e"><code>4855ece</code></a></td><td><code>Fix pyflakes issues</code></td></tr><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/f657815232a083c08783ef4da822ca10d93f9dfb"><code>f657815</code></a></td><td><code>Add conversion from InfinitePolynomial to SchubertPolynomial</code></td></tr><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/3a2999b90411c4c57dc6bf761b469a6f74b3297d"><code>3a2999b</code></a></td><td><code>Add coercion from Schubert to Key</code></td></tr></table>

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
Changed commit from **[`ca0d86e`](https://github.com/sagemath/sagetrac-mirror/commit/ca0d86e4d33573ba67d4918f6218ab55657ae5c0)** to **[`3a2999b`](https://github.com/sagemath/sagetrac-mirror/commit/3a2999b90411c4c57dc6bf761b469a6f74b3297d)**

**Comment by tscrim** [comment]
Reviewer: **Travis Scrimshaw**

**Comment by tscrim** [comment]
<div id="comment:7" align="right">comment:7</div>

I added some systematic tests, which revealed a corner case issue with the diagrams/peelable tableaux that I fixed. If my changes are good, then positive review.

---
New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/710cfbbd6cefa381183746fbff6fd99ec46b6891"><code>710cfbb</code></a></td><td><code>Reviewer changes: refactored some of the divided difference code, doc changes, orther misc changes.</code></td></tr><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/5e8977fe18f6b38e9eb4aeca066438b8d7e0514d"><code>5e8977f</code></a></td><td><code>Add reviewer suggestions to docs and change behavior of conflicting subs</code></td></tr><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/a56e345cd9c3203b432f2f29c743f0f4606dc088"><code>a56e345</code></a></td><td><code>Doc change</code></td></tr><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/2e2c4f2990070e8f04bd5ace80aa4570eceeb54c"><code>2e2c4f2</code></a></td><td><code>Merge branch 'u/tkarn/inf-poly-subs-34581' of https://github.com/sagemath/sagetrac-mirror into u/tscrim/key_polynomials-34414</code></td></tr><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/34bbd610cf79e13bf291e2dd35de215f70b50789"><code>34bbd61</code></a></td><td><code>Merge branch 'u/tscrim/key_polynomials-34414' of https://github.com/sagemath/sagetrac-mirror into u/tscrim/key_polynomials-34414</code></td></tr><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/124900faa1c5ce221dd3076789a0d4b64d6376d1"><code>124900f</code></a></td><td><code>Removed unused copy for pyflakes.</code></td></tr><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/da45befae0051e85f106ebd1a1c00874b953f78c"><code>da45bef</code></a></td><td><code>Merge branch 'u/tkarn/schubert-key-34518' of https://github.com/sagemath/sagetrac-mirror into u/tscrim/schubert_key-34518</code></td></tr><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/a4107d3f23c5bb2ea6f828a0c33deb89ec636f3d"><code>a4107d3</code></a></td><td><code>Some fixes for corner case. Adding some systemmatic tests.</code></td></tr></table>

**Comment by tscrim** [comment]
Changed commit from **[`3a2999b`](https://github.com/sagemath/sagetrac-mirror/commit/3a2999b90411c4c57dc6bf761b469a6f74b3297d)** to **[`a4107d3`](https://github.com/sagemath/sagetrac-mirror/commit/a4107d3f23c5bb2ea6f828a0c33deb89ec636f3d)**

**Comment by tscrim** [comment]
Changed branch from **[u/tkarn/schubert-key-34518](https://github.com/sagemath/sagetrac-mirror/tree/u/tkarn/schubert-key-34518)** to **[u/tscrim/schubert_key-34518](https://github.com/sagemath/sagetrac-mirror/tree/u/tscrim/schubert_key-34518)**

**Comment by trevorkarn** [comment]
<div id="comment:8" align="right">comment:8</div>

LGTM, thanks for the catch!

**Comment by mkoeppe** [comment]
Merged in 10.0.beta0
