### ISSUE TITLE
Pip package git_trac_command

### ISSUE THREAD

**Issue by mkoeppe** [sagemath/sage#34524]
<div id="comment:0"></div>

(split out from #33613)

This is a pip-installable package

```
python3 -m pip install git+https://github.com/sagemath/git-trac-command
```
... but it is best to be installed by the user in their system environment, not in SAGE_VENV.

For example, we want to make it available on Gitpod, in devcontainers, and the user-facing Sage Docker images.

In `src/environment-dev.yml` (#33740), it should be added as a `pip: ` line. (This happens through #33613.)

Depends on #30363

Component: **packages: optional**

Branch/Commit: **[u/mkoeppe/pip_package_git_trac_command](https://github.com/sagemath/sagetrac-mirror/tree/u/mkoeppe/pip_package_git_trac_command) @ [`31db9da`](https://github.com/sagemath/sagetrac-mirror/commit/31db9da3fe0f7c32e7203e313c9226d9403b8886)**

_Issue created by migration from https://trac.sagemath.org/ticket/34524_

**Comment by mkoeppe** [comment]
Description changed:
``````diff
--- 
+++ 
@@ -1,2 +1,14 @@
 (split out from #33613)
 
+This is a pip-installable package
+
+```
+python3 -m pip install git+https://github.com/sagemath/git-trac-command
+```
+... but it is best to be installed by the user in their system environment, not in SAGE_VENV.
+
+For example, we want to make it available on Gitpod, in devcontainers, and the user-facing Sage Docker images.
+
+In `src/environment-dev.yml` (#33740), it should be added as a `pip: ` line. (This happens through #33613.)
+
+
``````

**Comment by tobiasdiez** [comment]
With the migration to github, this should no longer be necessary, right?

Should we also archive the repo https://github.com/sagemath/git-trac-command?

**Comment by mkoeppe** [comment]
I haven't archived the repo yet, because this also provides @vbraun's release manager scripts, and I'm not sure whether anything from there will still be needed.

**Comment by mkoeppe** [comment]
> With the migration to github, this should no longer be necessary, right?

That's right.
