### ISSUE TITLE
Typo in git-trac file of developer's guide

### ISSUE THREAD

**Issue by jhpalmieri** [sagemath/sage#34558]
<div id="comment:0"></div>

There is a missing double colon, so the first code block is not rendered correctly: look at https://doc.sagemath.org/html/en/developer/git_trac.html and the block at the top of the section "Installing the Git-Trac Command".

Component: **documentation**

Author: **John Palmieri**

Branch/Commit: **[`5d5f9ae`](https://github.com/sagemath/sagetrac-mirror/commit/5d5f9aefa7a2f38643c8bb264fe234683af47eff)**

Reviewer: **Matthias Koeppe**

_Issue created by migration from https://trac.sagemath.org/ticket/34558_

**Comment by jhpalmieri** [comment]
Branch: **[u/jhpalmieri/trac34558-missing-colons](https://github.com/sagemath/sagetrac-mirror/tree/u/jhpalmieri/trac34558-missing-colons)**

**Comment by jhpalmieri** [comment]
<div id="comment:2"></div>

New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/5d5f9aefa7a2f38643c8bb264fe234683af47eff"><code>5d5f9ae</code></a></td><td><code>trac 34558: add "::" so code block renders correctly</code></td></tr></table>

**Comment by jhpalmieri** [comment]
Commit: **[`5d5f9ae`](https://github.com/sagemath/sagetrac-mirror/commit/5d5f9aefa7a2f38643c8bb264fe234683af47eff)**

**Comment by jhpalmieri** [comment]
Description changed:
``````diff
--- 
+++ 
@@ -1 +1 @@
-There is a missing double colon, so the first code block is not rendered correctly.
+There is a missing double colon, so the first code block is not rendered correctly: look at https://doc.sagemath.org/html/en/developer/git_trac.html and the block at the top of the section "Installing the Git-Trac Command".
``````

**Comment by mkoeppe** [comment]
Reviewer: **Matthias Koeppe**

**Comment by jhpalmieri** [comment]
<div id="comment:5" align="right">comment:5</div>

Thank you!

**Comment by vbraun** [comment]
Changed branch from **[u/jhpalmieri/trac34558-missing-colons](https://github.com/sagemath/sagetrac-mirror/tree/u/jhpalmieri/trac34558-missing-colons)** to **[`5d5f9ae`](https://github.com/sagemath/sagetrac-mirror/commit/5d5f9aefa7a2f38643c8bb264fe234683af47eff)**
