### ISSUE TITLE
improve performance of Stream_cauchy_invert

### ISSUE THREAD

**Issue by mantepse** [sagemath/sage#34553]
<div id="comment:0"></div>

Depends on #34552

CC:  @tscrim

Component: **combinatorics**

Keywords: **LazyPowerSeries**

Author: **Martin Rubey**

Branch/Commit: **[u/mantepse/improve_performance_of_stream_cauchy_invert](https://github.com/sagemath/sagetrac-mirror/tree/u/mantepse/improve_performance_of_stream_cauchy_invert) @ [`09ed986`](https://github.com/sagemath/sagetrac-mirror/commit/09ed98633c5832d488bedb82d26aab2df53d0df6)**

_Issue created by migration from https://trac.sagemath.org/ticket/34553_

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
<div id="comment:6"></div>

Branch pushed to git repo; I updated commit sha1. New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/275b6505ddbcf96309e945bc6a7f0d6ddc107acd"><code>275b650</code></a></td><td><code>improve performance of Stream_plethysm</code></td></tr></table>

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
Changed commit from **[`436887a`](https://github.com/sagemath/sagetrac-mirror/commit/436887a3d10b21e6303470838bd2118388abc306)** to **[`275b650`](https://github.com/sagemath/sagetrac-mirror/commit/275b6505ddbcf96309e945bc6a7f0d6ddc107acd)**

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
<div id="comment:7"></div>

Branch pushed to git repo; I updated commit sha1. New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/2e63bf9db6370d7b0c0e280abf1b4d4348abe1a2"><code>2e63bf9</code></a></td><td><code>add explanations</code></td></tr></table>

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
Changed commit from **[`275b650`](https://github.com/sagemath/sagetrac-mirror/commit/275b6505ddbcf96309e945bc6a7f0d6ddc107acd)** to **[`2e63bf9`](https://github.com/sagemath/sagetrac-mirror/commit/2e63bf9db6370d7b0c0e280abf1b4d4348abe1a2)**

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
Changed commit from **[`2e63bf9`](https://github.com/sagemath/sagetrac-mirror/commit/2e63bf9db6370d7b0c0e280abf1b4d4348abe1a2)** to **[`85d6270`](https://github.com/sagemath/sagetrac-mirror/commit/85d627075626dc6ba0aa52740f7e5da37734ae77)**

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
<div id="comment:8"></div>

Branch pushed to git repo; I updated commit sha1. Last 10 new commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/cdea82086b729509648bd306a04346ecead00cb1"><code>cdea820</code></a></td><td><code>Merge branch 'public/rings/lazy_series_revert-34383' of https://github.com/sagemath/sagetrac-mirror into u/tscrim/derivatives_lazy_series-34413</code></td></tr><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/b7f04edc591b9cc009d2b663098f95650dde3398"><code>b7f04ed</code></a></td><td><code>Merge branch 'develop' of trac.sagemath.org:sage into t/34413/derivatives_lazy_series-34413</code></td></tr><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/2325826800eff4c209d64fa33c09d5dfa4ce78a3"><code>2325826</code></a></td><td><code>Merge branch 'u/mantepse/derivatives_lazy_series-34413' of trac.sagemath.org:sage into t/34422/implement_functorial_composition_of_lazy_symmetric_functiosn</code></td></tr><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/ebcf5c3b4cb3d238d8957d06ee96421cca939a4b"><code>ebcf5c3</code></a></td><td><code>Merge branch 'u/mantepse/implement_functorial_composition_of_lazy_symmetric_functiosn' of trac.sagemath.org:sage into t/34423/implement_arithmetic_product_of_lazy_symmetric_functions</code></td></tr><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/4172688e381f6b8e617bcd1a7583aec50f346307"><code>4172688</code></a></td><td><code>Merge branch 'u/mantepse/implement_arithmetic_product_of_lazy_symmetric_functions' of trac.sagemath.org:sage into t/32367/replace_lazy_power_series-32367</code></td></tr><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/41ca99b7bfee0c11c4ece0bffa0b9230a7b4f67b"><code>41ca99b</code></a></td><td><code>Merge branch 'u/mantepse/replace_lazy_power_series-32367' of trac.sagemath.org:sage into t/34470/categories_lazy_series-34470</code></td></tr><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/fb3a5cdb6745cb78983f6bf5fc88bef93f21040a"><code>fb3a5cd</code></a></td><td><code>Merge branch 'u/mantepse/categories_lazy_series-34470' of trac.sagemath.org:sage into t/34552/lazy_series_test_suite-34552</code></td></tr><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/855d2bf04aaebfc1696e34664b48521bffd6a79f"><code>855d2bf</code></a></td><td><code>remove unused variable</code></td></tr><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/75c275cf989059c02bf5bd11ad7ed0ba76b3ca5f"><code>75c275c</code></a></td><td><code>add documentation and doctests for _approximate_order</code></td></tr><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/85d627075626dc6ba0aa52740f7e5da37734ae77"><code>85d6270</code></a></td><td><code>Merge branch 'u/mantepse/lazy_series_test_suite-34552' of trac.sagemath.org:sage into t/34553/improve_performance_of_stream_cauchy_invert</code></td></tr></table>

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
Changed commit from **[`85d6270`](https://github.com/sagemath/sagetrac-mirror/commit/85d627075626dc6ba0aa52740f7e5da37734ae77)** to **[`09ed986`](https://github.com/sagemath/sagetrac-mirror/commit/09ed98633c5832d488bedb82d26aab2df53d0df6)**

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
<div id="comment:9"></div>

Branch pushed to git repo; I updated commit sha1. New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/539324204ae876de4292c469eed336d8b6ee0f4a"><code>5393242</code></a></td><td><code>fixes for pycodestyle and pyflakes</code></td></tr><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/67dff95676c5e40b6311785db4db3e53347b11c5"><code>67dff95</code></a></td><td><code>Merge branch 'develop' of trac.sagemath.org:sage into t/32367/replace_lazy_power_series-32367</code></td></tr><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/4fc981b458f8d628684decf221618911ace06333"><code>4fc981b</code></a></td><td><code>fix for pyflakes and blocks</code></td></tr><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/56cef070ebee69841f1ead61344557d10d0b56a0"><code>56cef07</code></a></td><td><code>Merge branch 'u/mantepse/replace_lazy_power_series-32367' of trac.sagemath.org:sage into t/34470/categories_lazy_series-34470</code></td></tr><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/3e84c90c8c9c3d74c8dd2b6b328029d74144b7bc"><code>3e84c90</code></a></td><td><code>Merge branch 'u/mantepse/categories_lazy_series-34470' of trac.sagemath.org:sage into t/34552/lazy_series_test_suite-34552</code></td></tr><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/09ed98633c5832d488bedb82d26aab2df53d0df6"><code>09ed986</code></a></td><td><code>Merge branch 'u/mantepse/lazy_series_test_suite-34552' of trac.sagemath.org:sage into t/34553/improve_performance_of_stream_cauchy_invert</code></td></tr></table>

**Comment by mantepse** [comment]
@tscrim: do you remember that, when we talked a few weeks ago, that I was puzzled that all the `:=` in `stream.py` were gone?  Here they are!  For some reason, this ticket never made it.

**Comment by mantepse** [comment]
I am resurrecting this right now.

**Comment by tscrim** [comment]
Indeed, I remember. It is good that you found them. `:)`
