### ISSUE TITLE
Height function for projective subvarieties

### ISSUE THREAD

**Issue by guojing0** [sagemath/sage#34559]
<div id="comment:0"></div>

We want to have a function that computes the height of the projective subvariety.

If X is a projective subvariety, then the height of X is the height of its associated Chow form.

CC:  @bhutz @EnderWannabe

Component: **algebraic geometry**

Author: **Jing Guo**

Branch/Commit: **[u/gh-guojing0/subvar](https://github.com/sagemath/sagetrac-mirror/tree/u/gh-guojing0/subvar) @ [`39f7ee2`](https://github.com/sagemath/sagetrac-mirror/commit/39f7ee231cffe13bee7ca84c25020877e5b16d00)**

Reviewer: **Ben Hutz**

_Issue created by migration from https://trac.sagemath.org/ticket/34559_

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
<div id="comment:1"></div>

Branch pushed to git repo; I updated commit sha1. New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/0b4c296d5c61dc0249701a04368ab5e9093be66e"><code>0b4c296</code></a></td><td><code>34559: Height functions for projective subschemes</code></td></tr></table>

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
Changed commit from **[`627b2bd`](https://github.com/sagemath/sagetrac-mirror/commit/627b2bdfe922e2f9eed9d190c19df778674bdcfb)** to **[`0b4c296`](https://github.com/sagemath/sagetrac-mirror/commit/0b4c296d5c61dc0249701a04368ab5e9093be66e)**

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
<div id="comment:2"></div>

Branch pushed to git repo; I updated commit sha1. New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/427e40a00ea58c0bbd70ea495f2db3c2e7c36671"><code>427e40a</code></a></td><td><code>34559: Add docs and examples</code></td></tr></table>

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
Changed commit from **[`0b4c296`](https://github.com/sagemath/sagetrac-mirror/commit/0b4c296d5c61dc0249701a04368ab5e9093be66e)** to **[`427e40a`](https://github.com/sagemath/sagetrac-mirror/commit/427e40a00ea58c0bbd70ea495f2db3c2e7c36671)**

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
Changed commit from **[`427e40a`](https://github.com/sagemath/sagetrac-mirror/commit/427e40a00ea58c0bbd70ea495f2db3c2e7c36671)** to **[`e77d5b5`](https://github.com/sagemath/sagetrac-mirror/commit/e77d5b5837f27f38c8cd1715cc0783035a939ec6)**

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
<div id="comment:3"></div>

Branch pushed to git repo; I updated commit sha1. New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/e77d5b5837f27f38c8cd1715cc0783035a939ec6"><code>e77d5b5</code></a></td><td><code>34559: Correct examples</code></td></tr></table>

**Comment by bhutz** [comment]
Reviewer: **Ben Hutz**

**Comment by bhutz** [comment]
<div id="comment:5" align="right">comment:5</div>

This is looking fine. Just one thing. Any example longer than about 0.5s should be marked as

```
#long time
```

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
Changed commit from **[`e77d5b5`](https://github.com/sagemath/sagetrac-mirror/commit/e77d5b5837f27f38c8cd1715cc0783035a939ec6)** to **[`39f7ee2`](https://github.com/sagemath/sagetrac-mirror/commit/39f7ee231cffe13bee7ca84c25020877e5b16d00)**

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
<div id="comment:6"></div>

Branch pushed to git repo; I updated commit sha1. New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/39f7ee231cffe13bee7ca84c25020877e5b16d00"><code>39f7ee2</code></a></td><td><code>34559: Long time comments</code></td></tr></table>

**Comment by guojing0** [comment]
<div id="comment:7" align="right">comment:7</div>

Thanks and done.
