### ISSUE TITLE
Moving some references to the master reference file

### ISSUE THREAD

**Issue by DennisJahn** [sagemath/sage#34566]
<div id="comment:0"></div>

Component: **documentation**

Author: **Dennis Jahn**

Branch/Commit: **[`017e300`](https://github.com/sagemath/sagetrac-mirror/commit/017e300cb7958405662cf7d21a85b5c4ddba2c7a)**

Reviewer: **Frédéric Chapoton**

_Issue created by migration from https://trac.sagemath.org/ticket/34566_

**Comment by DaveWitteMorris** [comment]
<div id="comment:1" align="right">comment:1</div>

This should presumably be part of metaticket #27497. What references is this ticket intended to deal with?

**Comment by DennisJahn** [comment]
<div id="comment:2" align="right">comment:2</div>

Replying to [Dave Morris](#comment%3A1):
> This should presumably be part of metaticket #27497. What references is this ticket intended to deal with?

In `sage/categories/weyl_groups.py` there are the two references [Dye] and [JahStu].
The have been added to the master reference file in #32669 as [Dy1994] and [JS2021].

I was waiting for the 'roll-out' of 9.7.1 and wanted to make the changes then.

**Comment by DennisJahn** [comment]
Branch: **[u/gh-DennisJahn/moving_some_references_to_the_master_reference_file](https://github.com/sagemath/sagetrac-mirror/tree/u/gh-DennisJahn/moving_some_references_to_the_master_reference_file)**

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
Commit: **[`017e300`](https://github.com/sagemath/sagetrac-mirror/commit/017e300cb7958405662cf7d21a85b5c4ddba2c7a)**

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
<div id="comment:4"></div>

Branch pushed to git repo; I updated commit sha1. New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/017e300cb7958405662cf7d21a85b5c4ddba2c7a"><code>017e300</code></a></td><td><code>changed the references</code></td></tr></table>

**Comment by fchapoton** [comment]
<div id="comment:6" align="right">comment:6</div>

ok

**Comment by fchapoton** [comment]
Reviewer: **Frédéric Chapoton**

**Comment by vbraun** [comment]
Changed branch from **[u/gh-DennisJahn/moving_some_references_to_the_master_reference_file](https://github.com/sagemath/sagetrac-mirror/tree/u/gh-DennisJahn/moving_some_references_to_the_master_reference_file)** to **[`017e300`](https://github.com/sagemath/sagetrac-mirror/commit/017e300cb7958405662cf7d21a85b5c4ddba2c7a)**
