### ISSUE TITLE
Fix wrong link in the documentation of topological submanifolds

### ISSUE THREAD

**Issue by egourgoulhon** [sagemath/sage#34565]
<div id="comment:0"></div>

The link in the `OUTPUT` field of the docstring of `TopologicalSubmanifold.open_subset` is corrected to <code>:class:\`TopologicalSubmanifold\`</code>

Component: **manifolds**

Author: **Eric Gourgoulhon**

Branch/Commit: **[`9584bf1`](https://github.com/sagemath/sagetrac-mirror/commit/9584bf16b9ddf4248f233d01c70184b5fa86e2e3)**

Reviewer: **Kwankyu Lee**

_Issue created by migration from https://trac.sagemath.org/ticket/34565_

**Comment by egourgoulhon** [comment]
Author: **Eric Gourgoulhon**

**Comment by egourgoulhon** [comment]
Branch: **[public/manifolds/fix_doc_topological_submanifolds-34565](https://github.com/sagemath/sagetrac-mirror/tree/public/manifolds/fix_doc_topological_submanifolds-34565)**

**Comment by egourgoulhon** [comment]
Commit: **[`9584bf1`](https://github.com/sagemath/sagetrac-mirror/commit/9584bf16b9ddf4248f233d01c70184b5fa86e2e3)**

**Comment by egourgoulhon** [comment]
<div id="comment:1"></div>

New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/9584bf16b9ddf4248f233d01c70184b5fa86e2e3"><code>9584bf1</code></a></td><td><code>Fix wrong link in the documentation of TopologicalSubmanifold.open_subset (Trac #34565)</code></td></tr></table>

**Comment by kwankyu** [comment]
<div id="comment:2" align="right">comment:2</div>

LGTM.

**Comment by kwankyu** [comment]
Reviewer: **Kwankyu Lee**

**Comment by egourgoulhon** [comment]
<div id="comment:3" align="right">comment:3</div>

Thanks for the review!

**Comment by vbraun** [comment]
Changed branch from **[public/manifolds/fix_doc_topological_submanifolds-34565](https://github.com/sagemath/sagetrac-mirror/tree/public/manifolds/fix_doc_topological_submanifolds-34565)** to **[`9584bf1`](https://github.com/sagemath/sagetrac-mirror/commit/9584bf16b9ddf4248f233d01c70184b5fa86e2e3)**
