### ISSUE TITLE
Documentation: There is no package in debian/ubuntu called openssh

### ISSUE THREAD

**Issue by pipedream** [sagemath/sage#34561]
<div id="comment:0"></div>

configure suggests to install openssh and openssh-client.

```
0 jan@muizenberg:/srv/sage-9.7$grep openssh src/doc/en/installation/debian-develop.txt.orig
  $ sudo apt-get install  autoconf automake git gpgconf libtool openssh openssh-client pkg-config
```

There is no package called openssh:
[https://packages.debian.org/search?keywords=openssh&searchon=names&exact=1&suite=all&section=all](https://packages.debian.org/search?keywords=openssh&searchon=names&exact=1&suite=all&section=all)
[https://packages.ubuntu.com/search?keywords=openssh&searchon=names&exact=1&suite=all&section=all](https://packages.ubuntu.com/search?keywords=openssh&searchon=names&exact=1&suite=all&section=all)

End-users often copy and paste this line, often not even reading the error or realising the command failed.

There is a meta-package called ssh depending on openssh-client and openssh-server, but we should not be advocating ssh server installations on laptops which often have terrible passwords, such as containing or equal to the username, or very poor passwords like 1234 or password. Yes, my students still do this.

```
0 jan@muizenberg:/srv/sage-9.7$apt depends ssh
ssh
  PreDepends: dpkg (>= 1.17.5)
    dpkg:i386
  Depends: openssh-client (>= 1:8.4p1-5+deb11u1)
    openssh-client:i386
  Depends: openssh-server (>= 1:8.4p1-5+deb11u1)
    openssh-server:i386
```

Attached patch to remove "openssh" from the instructions for debian, but keeping openssh-client.

Note I do not know whether a package called openssh exists for the other distros/platforms:

```
0 jan@muizenberg:/srv/sage-9.7$ls src/doc/en/installation/*-develop.txt
src/doc/en/installation/arch-develop.txt    src/doc/en/installation/debian-develop.txt  src/doc/en/installation/homebrew-develop.txt
src/doc/en/installation/cygwin-develop.txt  src/doc/en/installation/fedora-develop.txt  src/doc/en/installation/opensuse-develop.txt
```

Component: **documentation**

Author: **Jan Groenewald**

Branch/Commit: **[`2de6d46`](https://github.com/sagemath/sagetrac-mirror/commit/2de6d46f0363a6a3f8b45ad37fe150bc472abf86)**

Reviewer: **Matthias Koeppe**

_Issue created by migration from https://trac.sagemath.org/ticket/34561_

**Comment by mkoeppe** [comment]
<div id="comment:1" align="right">comment:1</div>

Attachment: **[debian-no-package-called-openssh.patch.gz](https://github.com/sagemath/sage-prod/files/10659654/debian-no-package-called-openssh.patch.gz)**

The correct file to patch is `build/pkgs/_develop/distros/debian.txt`

The instructions are generated from there.

**Comment by pipedream** [comment]
<div id="comment:2" align="right">comment:2</div>

Attached a patch to the correct file, build/pkgs/_develop/distros/debian.txt

**Comment by mkoeppe** [comment]
<div id="comment:3" align="right">comment:3</div>

Attachment: **[debian.txt.patch.gz](https://github.com/sagemath/sage-prod/files/10659655/debian.txt.patch.gz)**

**Comment by mkoeppe** [comment]
Branch: **[u/mkoeppe/documentation__there_is_no_package_in_debian_ubuntu_called_openssh](https://github.com/sagemath/sagetrac-mirror/tree/u/mkoeppe/documentation__there_is_no_package_in_debian_ubuntu_called_openssh)**

**Comment by mkoeppe** [comment]
<div id="comment:4"></div>

New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/2de6d46f0363a6a3f8b45ad37fe150bc472abf86"><code>2de6d46</code></a></td><td><code>build/pkgs/_develop/distros/debian.txt: Remove nonexistent package openssh</code></td></tr></table>

**Comment by mkoeppe** [comment]
Commit: **[`2de6d46`](https://github.com/sagemath/sagetrac-mirror/commit/2de6d46f0363a6a3f8b45ad37fe150bc472abf86)**

**Comment by mkoeppe** [comment]
Reviewer: **Matthias Koeppe**

**Comment by vbraun** [comment]
Changed branch from **[u/mkoeppe/documentation__there_is_no_package_in_debian_ubuntu_called_openssh](https://github.com/sagemath/sagetrac-mirror/tree/u/mkoeppe/documentation__there_is_no_package_in_debian_ubuntu_called_openssh)** to **[`2de6d46`](https://github.com/sagemath/sagetrac-mirror/commit/2de6d46f0363a6a3f8b45ad37fe150bc472abf86)**
