### ISSUE TITLE
Fix minor documentation formatting issues in dancing links

### ISSUE THREAD

**Issue by Kerl13** [sagemath/sage#34567]
<div id="comment:0"></div>

Component: **documentation**

Author: **Martin Pépin**

Branch: **[`1c9e627`](https://github.com/sagemath/sagetrac-mirror/commit/1c9e6279f6f8d7a9d94de35f1d6a8494818c42f8)**

Reviewer: **Frédéric Chapoton**

_Issue created by migration from https://trac.sagemath.org/ticket/34567_

**Comment by Kerl13** [comment]
Author: **Martin Pépin**

**Comment by fchapoton** [comment]
Reviewer: **Frédéric Chapoton**

**Comment by fchapoton** [comment]
<div id="comment:3" align="right">comment:3</div>

ok, feu vert

**Comment by vbraun** [comment]
Changed branch from **[u/MartinPepin/dancing_links_docs_formatting](https://github.com/sagemath/sagetrac-mirror/tree/u/MartinPepin/dancing_links_docs_formatting)** to **[`1c9e627`](https://github.com/sagemath/sagetrac-mirror/commit/1c9e6279f6f8d7a9d94de35f1d6a8494818c42f8)**

**Comment by seblabbe** [comment]
Changed commit from **[`1c9e627`](https://github.com/sagemath/sagetrac-mirror/commit/1c9e6279f6f8d7a9d94de35f1d6a8494818c42f8)** to none

**Comment by seblabbe** [comment]
<div id="comment:5" align="right">comment:5</div>

Is it normal that `build/pkgs/configure/checksums.ini` and `build/pkgs/configure/package-version.txt` were modified in this ticket?

**Comment by fchapoton** [comment]
<div id="comment:6" align="right">comment:6</div>

hmm, no. But this is the last commit that Volker has closed before the release.

**Comment by Kerl13** [comment]
<div id="comment:7" align="right">comment:7</div>

These files are not modified on `u/MartinPepin/dancing_links_docs_formatting` at least.

By the way, what's the usual practice regarding merged branches? Can I remove the branch on trac or is there a policy to keep them?
