### ISSUE TITLE
rename example to QuaternionicProjectivePlane

### ISSUE THREAD

**Issue by fchapoton** [sagemath/sage#34568]
<div id="comment:0"></div>

as this has been proved by Gorodkov in 2016 to be indeed the projective plane over H

https://arxiv.org/abs/1603.05541

CC:  @jhpalmieri

Component: **algebraic topology**

Author: **Frédéric Chapoton**

Branch/Commit: **[`ae5676b`](https://github.com/sagemath/sagetrac-mirror/commit/ae5676b4fdf9db1482c01e902a1e32a33eedacc8)**

Reviewer: **John Palmieri**

_Issue created by migration from https://trac.sagemath.org/ticket/34568_

**Comment by fchapoton** [comment]
Branch: **[u/chapoton/34568](https://github.com/sagemath/sagetrac-mirror/tree/u/chapoton/34568)**

**Comment by fchapoton** [comment]
Description changed:
``````diff
--- 
+++ 
@@ -1 +1,3 @@
 as this has been proved by Gorodkov in 2016 to be indeed the projective plane over H
+
+https://arxiv.org/abs/1603.05541
``````

**Comment by fchapoton** [comment]
<div id="comment:1"></div>

New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/9548409c9cd69ec52a3c5bca95331a5595d64727"><code>9548409</code></a></td><td><code>change name of example in simplicial complexes</code></td></tr></table>

**Comment by fchapoton** [comment]
Commit: **[`9548409`](https://github.com/sagemath/sagetrac-mirror/commit/9548409c9cd69ec52a3c5bca95331a5595d64727)**

**Comment by fchapoton** [comment]
<div id="comment:2" align="right">comment:2</div>

should be an easy review ; I am not sure it is worth deprecating the old name

**Comment by jhpalmieri** [comment]
<div id="comment:3" align="right">comment:3</div>

Thank you for discovering Gorodkov's result! The deprecation question is the only thing worth worrying about. It would be safest to deprecate the name, and then follow up pretty quickly and delete it. (I feel like some of our deprecation warnings linger for a while, but this one should definitely be short-lived.)

I could also be convinced that we don't need to deprecate it but just delete it. I do not expect that there are many people using this in their code, and it is easy to find the new command.

**Comment by fchapoton** [comment]
<div id="comment:4" align="right">comment:4</div>

Yes, it is indeed a nice result. I have learned that from a recent talk of Gaifullin, that has just found a minimal triangulation of OP2.

https://arxiv.org/abs/2207.08507

Well, maybe one could just put a deprecated alias in the catalog of examples. Putting an alias for a short time is not really an option, as the rule is to wait one year after the next release after the ticket.

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
Changed commit from **[`9548409`](https://github.com/sagemath/sagetrac-mirror/commit/9548409c9cd69ec52a3c5bca95331a5595d64727)** to **[`ae5676b`](https://github.com/sagemath/sagetrac-mirror/commit/ae5676b4fdf9db1482c01e902a1e32a33eedacc8)**

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
<div id="comment:5"></div>

Branch pushed to git repo; I updated commit sha1. New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/ae5676b4fdf9db1482c01e902a1e32a33eedacc8"><code>ae5676b</code></a></td><td><code>adding a deprecation</code></td></tr></table>

**Comment by jhpalmieri** [comment]
<div id="comment:6" align="right">comment:6</div>

Looks good to me. Docs build and tests pass.

**Comment by jhpalmieri** [comment]
Reviewer: **John Palmieri**

**Comment by vbraun** [comment]
Changed branch from **[u/chapoton/34568](https://github.com/sagemath/sagetrac-mirror/tree/u/chapoton/34568)** to **[`ae5676b`](https://github.com/sagemath/sagetrac-mirror/commit/ae5676b4fdf9db1482c01e902a1e32a33eedacc8)**
