### ISSUE TITLE
refactor multiple zeta values

### ISSUE THREAD

**Issue by fchapoton** [sagemath/sage#34562]
<div id="comment:0"></div>

This ticket mainly aims to separate the auxiliary F-algebra in another file.

This file implements a better custom-made F-algebra, with additional useful methods.

CC:  @videlec @tscrim

Component: **number theory**

Author: **Frédéric Chapoton**

Branch/Commit: **[`8a8cdf3`](https://github.com/sagemath/sagetrac-mirror/commit/8a8cdf3fd2ee95dae4c1523b34e561a6cce8639f)**

Reviewer: **Travis Scrimshaw**

_Issue created by migration from https://trac.sagemath.org/ticket/34562_

**Comment by fchapoton** [comment]
<div id="comment:1"></div>

New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/f8a5eea2cf1d80bc00e442a824498a7c77468869"><code>f8a5eea</code></a></td><td><code>refactor MZV using a new file for a better auxiliary F_algebra</code></td></tr></table>

**Comment by fchapoton** [comment]
Commit: **[`f8a5eea`](https://github.com/sagemath/sagetrac-mirror/commit/f8a5eea2cf1d80bc00e442a824498a7c77468869)**

**Comment by fchapoton** [comment]
Branch: **[u/chapoton/34562](https://github.com/sagemath/sagetrac-mirror/tree/u/chapoton/34562)**

**Comment by tscrim** [comment]
<div id="comment:2" align="right">comment:2</div>

Some quick comments about the `F_algebra`:

- The element's `coefficients` should return the nonzero coefficients, but the current implementation has different behavior.
- There should be a `from_vector` method on the parent. This is useful for the linear algebra methods.
- The `NN` can be a little funky when it comes to lazy imports not resolving correctly (#16522). It would be better to use `NonNegativeIntegers()` unless you specifically are looking for the algebraic aspects.
- Is there a reason why you are nailing `Indices` in the module level memory? It seems like the `str_to_index` is better as a method of the `F_algebra` and then you could access it by `self._indices` there (or `self.parent()._indices`).
- Instead of the recursive `basis_f_odd_iterator`, is it faster to use the iterators from `WeightedIntegerVectors` and `Permutations_mset` (which operate on lists)? It is a slightly more involved implementation, but I don't know how important speed is here.
- For the `product_on_basis`, it might be faster to do `self.sum()` since it works with the elements directly and has less transient elements.

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
<div id="comment:3"></div>

Branch pushed to git repo; I updated commit sha1. New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/3b06406df5cf16582b125245f5adc03d221f9d34"><code>3b06406</code></a></td><td><code>using NonNegativeIntegers instead of NN</code></td></tr></table>

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
Changed commit from **[`f8a5eea`](https://github.com/sagemath/sagetrac-mirror/commit/f8a5eea2cf1d80bc00e442a824498a7c77468869)** to **[`3b06406`](https://github.com/sagemath/sagetrac-mirror/commit/3b06406df5cf16582b125245f5adc03d221f9d34)**

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
<div id="comment:4"></div>

Branch pushed to git repo; I updated commit sha1. New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/c447fc23ea071c52e1dc0b8608934a05473826d4"><code>c447fc2</code></a></td><td><code>Merge branch 'u/chapoton/34562' in 9.7</code></td></tr><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/c7b3fee645b47b1236fd59eeb8f3f5ceffabc13b"><code>c7b3fee</code></a></td><td><code>remove wrong alias for coefficients</code></td></tr></table>

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
Changed commit from **[`3b06406`](https://github.com/sagemath/sagetrac-mirror/commit/3b06406df5cf16582b125245f5adc03d221f9d34)** to **[`c7b3fee`](https://github.com/sagemath/sagetrac-mirror/commit/c7b3fee645b47b1236fd59eeb8f3f5ceffabc13b)**

**Comment by fchapoton** [comment]
<div id="comment:5" align="right">comment:5</div>

Hello,

thanks a lot for the suggestions !

> - The element's `coefficients` should return the nonzero coefficients, but the current implementation has different behavior.

ok, done by removing the wrong alias that I had added.

> - There should be a `from_vector` method on the parent. This is useful for the linear algebra methods.

well, the difficulty is that it only makes sense for homogeneous elements, and the usual "from_vector" methods does not take the degree as input

> - The `NN` can be a little funky when it comes to lazy imports not resolving correctly (#16522). It would be better to use `NonNegativeIntegers()` unless you specifically are looking for the algebraic aspects.

I substituted that for NN and it works fine.

> - Is there a reason why you are nailing `Indices` in the module level memory? It seems like the `str_to_index` is better as a method of the `F_algebra` and then you could access it by `self._indices` there (or `self.parent()._indices`).

I would rather keep "str_to_index" as an independant auxiliary function. Why is it problematic to have Indices at the module level ? oh, I guess it will have to be initiated when the module is loaded..

> - Instead of the recursive `basis_f_odd_iterator`, is it faster to use the iterators from `WeightedIntegerVectors` and `Permutations_mset` (which operate on lists)? It is a slightly more involved implementation, but I don't know how important speed is here.

Not sure how to achieve "words of any length in odd integers at least 3 with sum n" using the existing tools. And speed generally matters in this file, indeed.

> - For the `product_on_basis`, it might be faster to do `self.sum()` since it works with the elements directly and has less transient elements.

I have not yet checked that last suggestion.

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
<div id="comment:6"></div>

Branch pushed to git repo; I updated commit sha1. New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/0a56256f45417f9047f05d14926c2dfc3e22b8b3"><code>0a56256</code></a></td><td><code>implement and use attribute _indices in F-algebra</code></td></tr></table>

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
Changed commit from **[`c7b3fee`](https://github.com/sagemath/sagetrac-mirror/commit/c7b3fee645b47b1236fd59eeb8f3f5ceffabc13b)** to **[`0a56256`](https://github.com/sagemath/sagetrac-mirror/commit/0a56256f45417f9047f05d14926c2dfc3e22b8b3)**

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
Changed commit from **[`0a56256`](https://github.com/sagemath/sagetrac-mirror/commit/0a56256f45417f9047f05d14926c2dfc3e22b8b3)** to **[`6f11059`](https://github.com/sagemath/sagetrac-mirror/commit/6f110595865af941c7b1afeba01ff0f536c1b556)**

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
<div id="comment:7"></div>

Branch pushed to git repo; I updated commit sha1. New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/6f110595865af941c7b1afeba01ff0f536c1b556"><code>6f11059</code></a></td><td><code>using sum_of_monomials</code></td></tr></table>

**Comment by tscrim** [comment]
<div id="comment:8" align="right">comment:8</div>

Replying to [Frédéric Chapoton](#comment%3A5):
> thanks a lot for the suggestions !

Thank you for all your work on Sage.

> > - There should be a `from_vector` method on the parent. This is useful for the linear algebra methods.
> 
> 
> well, the difficulty is that it only makes sense for homogeneous elements, and the usual "from_vector" methods does not take the degree as input

I see. This breaks the `CFM.from_vector(v.to_vector()) == v` loop though (although that is more for finite dimensional modules). Perhaps we could rename this here to `homogeneous_to_vector()` to make it more future-proof (if we implement a generic infinite dimensional version someday)?

> > - Is there a reason why you are nailing `Indices` in the module level memory? It seems like the `str_to_index` is better as a method of the `F_algebra` and then you could access it by `self._indices` there (or `self.parent()._indices`).
> 
> 
> I would rather keep "str_to_index" as an independant auxiliary function. Why is it problematic to have Indices at the module level ? oh, I guess it will have to be initiated when the module is loaded..

Subsequently it effectively gets nailed in memory. It's fairly lightweight (and only one of them), so its not a problem, but it still is something that gets carried around.

Also, you shouldn't need to set `self._indices = Indices`; that should be done by the `CFM.__init__()`.

> > - Instead of the recursive `basis_f_odd_iterator`, is it faster to use the iterators from `WeightedIntegerVectors` and `Permutations_mset` (which operate on lists)? It is a slightly more involved implementation, but I don't know how important speed is here.
> 
> 
> Not sure how to achieve "words of any length in odd integers at least 3 with sum n" using the existing tools. And speed generally matters in this file, indeed.

If speed matters, then perhaps we should just Cythonize the file. It would allow you to replace the `self.parent()` with `self._parent`, which is faster.

Perhaps iterating over the indices is not such an important operation for speed. Although it might be best to use lightweight classes (e.g., `tuple`) and implement shuffling without using the heavy `ShuffleProduct_w1w2` parent class. This becomes something like

```python
    def shuffle(t1, t2):
        n1 = len(t1)
        n2 = len(t2)
        for iv in IntegerVectors(n1, n1 + n2, max_part=1): # can probably even make this iterator smarter
            it1 = iter(t1)
            it2 = iter(t2)
            yield tuple([next(it1) if v else next(it2) for v in iv])
```

> > - For the `product_on_basis`, it might be faster to do `self.sum()` since it works with the elements directly and has less transient elements.
> 
> 
> I have not yet checked that last suggestion.

Your changes look like they should be faster. Even more so if we can make the indices involve less transient objects and/or checks.

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
<div id="comment:9"></div>

Branch pushed to git repo; I updated commit sha1. New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/d5ee67d85985f1be9c3807db3622bfa9ac4bc4a0"><code>d5ee67d</code></a></td><td><code>using homogeneous_to_vector and homogeneous_from_vector</code></td></tr></table>

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
Changed commit from **[`6f11059`](https://github.com/sagemath/sagetrac-mirror/commit/6f110595865af941c7b1afeba01ff0f536c1b556)** to **[`d5ee67d`](https://github.com/sagemath/sagetrac-mirror/commit/d5ee67d85985f1be9c3807db3622bfa9ac4bc4a0)**

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
Changed commit from **[`d5ee67d`](https://github.com/sagemath/sagetrac-mirror/commit/d5ee67d85985f1be9c3807db3622bfa9ac4bc4a0)** to **[`5df08cb`](https://github.com/sagemath/sagetrac-mirror/commit/5df08cb7dd7bffd732d6143a7d38244c30946e88)**

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
<div id="comment:10"></div>

Branch pushed to git repo; I updated commit sha1. New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/7d395b55bc21c2ca30cb0a0e9dd1fabd3656255f"><code>7d395b5</code></a></td><td><code>remove duplicate code</code></td></tr><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/5df08cb7dd7bffd732d6143a7d38244c30946e88"><code>5df08cb</code></a></td><td><code>simplify code a little bit in MZV</code></td></tr></table>

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
<div id="comment:11"></div>

Branch pushed to git repo; I updated commit sha1. New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/4bdced9c9f14129d69bd409db0660987d17221da"><code>4bdced9</code></a></td><td><code>small detail in MZV</code></td></tr></table>

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
Changed commit from **[`5df08cb`](https://github.com/sagemath/sagetrac-mirror/commit/5df08cb7dd7bffd732d6143a7d38244c30946e88)** to **[`4bdced9`](https://github.com/sagemath/sagetrac-mirror/commit/4bdced9c9f14129d69bd409db0660987d17221da)**

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
Changed commit from **[`4bdced9`](https://github.com/sagemath/sagetrac-mirror/commit/4bdced9c9f14129d69bd409db0660987d17221da)** to **[`7661288`](https://github.com/sagemath/sagetrac-mirror/commit/7661288224be017f92be37698032eb89fccb0622)**

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
<div id="comment:12"></div>

Branch pushed to git repo; I updated commit sha1. New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/7661288224be017f92be37698032eb89fccb0622"><code>7661288</code></a></td><td><code>a few more details in MZV</code></td></tr></table>

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
<div id="comment:13"></div>

Branch pushed to git repo; I updated commit sha1. New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/63695d79d12e7822f0539968fcac1ecb87f398a8"><code>63695d7</code></a></td><td><code>more fine-tuning details in MZV</code></td></tr></table>

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
Changed commit from **[`7661288`](https://github.com/sagemath/sagetrac-mirror/commit/7661288224be017f92be37698032eb89fccb0622)** to **[`63695d7`](https://github.com/sagemath/sagetrac-mirror/commit/63695d79d12e7822f0539968fcac1ecb87f398a8)**

**Comment by fchapoton** [comment]
<div id="comment:14" align="right">comment:14</div>

I guess it is now ready for review again.

**Comment by fchapoton** [comment]
<div id="comment:15" align="right">comment:15</div>

maybe one should simplify (in F_algebra) the double method "gen" versus "custom_gen" ?

**Comment by tscrim** [comment]
<div id="comment:16" align="right">comment:16</div>

It does look a bit weird to have both `gen` and `custom_gen`. Is there a reason to have both? Perhaps it could be a little better with a different name than `custom_gen`? I am not sure what a good name might be though.

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
Changed commit from **[`63695d7`](https://github.com/sagemath/sagetrac-mirror/commit/63695d79d12e7822f0539968fcac1ecb87f398a8)** to **[`6b80c50`](https://github.com/sagemath/sagetrac-mirror/commit/6b80c50d028c46ef48bc2cc9bac53446aa170958)**

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
<div id="comment:17"></div>

Branch pushed to git repo; I updated commit sha1. New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/6b80c50d028c46ef48bc2cc9bac53446aa170958"><code>6b80c50</code></a></td><td><code>get rid of custom_gen, now gen</code></td></tr></table>

**Comment by fchapoton** [comment]
<div id="comment:18" align="right">comment:18</div>

So I have removed the previous method "gen" (rather useless and not natural) and renamed "custom_gen" to "gen".

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
<div id="comment:19"></div>

Branch pushed to git repo; I updated commit sha1. New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/cac22914d83cc3d4e1b0a69de0c309af0fd552c6"><code>cac2291</code></a></td><td><code>using IntegerRange in MZV itself</code></td></tr></table>

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
Changed commit from **[`6b80c50`](https://github.com/sagemath/sagetrac-mirror/commit/6b80c50d028c46ef48bc2cc9bac53446aa170958)** to **[`cac2291`](https://github.com/sagemath/sagetrac-mirror/commit/cac22914d83cc3d4e1b0a69de0c309af0fd552c6)**

**Comment by tscrim** [comment]
<div id="comment:20" align="right">comment:20</div>

Thank you.

Do we want to use `IntegerRange` rather than the more specific `NonNegativeIntegers()`? This would also make it different than `F_algebra` (not that they need to be the same).

I think other than that, I would be happy to set a positive review (unless there are other changes you want to make).

**Comment by fchapoton** [comment]
<div id="comment:21" align="right">comment:21</div>

Well, I want to exclude 0. No idea what nonnegative means, as always.

**Comment by tscrim** [comment]
<div id="comment:22" align="right">comment:22</div>

Ah, right. Duh. Then how about `PositiveIntegers()`?

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
Changed commit from **[`cac2291`](https://github.com/sagemath/sagetrac-mirror/commit/cac22914d83cc3d4e1b0a69de0c309af0fd552c6)** to **[`8a8cdf3`](https://github.com/sagemath/sagetrac-mirror/commit/8a8cdf3fd2ee95dae4c1523b34e561a6cce8639f)**

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
<div id="comment:23"></div>

Branch pushed to git repo; I updated commit sha1. New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/8a8cdf3fd2ee95dae4c1523b34e561a6cce8639f"><code>8a8cdf3</code></a></td><td><code>using PositiveIntegers</code></td></tr></table>

**Comment by fchapoton** [comment]
<div id="comment:24" align="right">comment:24</div>

Indeed, now using `PositiveIntegers`.

I think I have no further changes to make.

**Comment by tscrim** [comment]
Reviewer: **Travis Scrimshaw**

**Comment by tscrim** [comment]
<div id="comment:25" align="right">comment:25</div>

Thanks. LGTM.

**Comment by vbraun** [comment]
Changed branch from **[u/chapoton/34562](https://github.com/sagemath/sagetrac-mirror/tree/u/chapoton/34562)** to **[`8a8cdf3`](https://github.com/sagemath/sagetrac-mirror/commit/8a8cdf3fd2ee95dae4c1523b34e561a6cce8639f)**
