### ISSUE TITLE
Uniformize headline: functions

### ISSUE THREAD

**Issue by kwankyu** [sagemath/sage#34574]
<div id="comment:0"></div>

Component: **documentation**

Author: **Kwankyu Lee**

Branch/Commit: **[`8184039`](https://github.com/sagemath/sagetrac-mirror/commit/818403963bc01bec9ee5a9f38383009c8fcf4942)**

Reviewer: **Matthias Koeppe**

_Issue created by migration from https://trac.sagemath.org/ticket/34574_

**Comment by kwankyu** [comment]
Author: **Kwankyu Lee**

**Comment by kwankyu** [comment]
Branch: **[u/klee/fix_invalid_escape_sequence_warning](https://github.com/sagemath/sagetrac-mirror/tree/u/klee/fix_invalid_escape_sequence_warning)**

**Comment by kwankyu** [comment]
Description changed:
``````diff
--- 
+++ 
@@ -1 +1,6 @@
+Noticed in
 
+```
+[sagemath_doc_html-none] .../src/sage/functions/special.py:852: 
+DeprecationWarning: invalid escape sequence \p
+```
``````

**Comment by kwankyu** [comment]
Commit: **[`6b0cb1f`](https://github.com/sagemath/sagetrac-mirror/commit/6b0cb1fd1b4223574a4283679d52fbdc1aacf506)**

**Comment by kwankyu** [comment]
<div id="comment:3"></div>

New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/dc25d4de7f23fe54485eccd6a362df9d871ab30b"><code>dc25d4d</code></a></td><td><code>Fix invalid escape sequence warning</code></td></tr><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/6b0cb1fd1b4223574a4283679d52fbdc1aacf506"><code>6b0cb1f</code></a></td><td><code>Uniformize headline: functions</code></td></tr></table>

**Comment by fchapoton** [comment]
<div id="comment:4" align="right">comment:4</div>

see #34465

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
Changed commit from **[`6b0cb1f`](https://github.com/sagemath/sagetrac-mirror/commit/6b0cb1fd1b4223574a4283679d52fbdc1aacf506)** to **[`8184039`](https://github.com/sagemath/sagetrac-mirror/commit/818403963bc01bec9ee5a9f38383009c8fcf4942)**

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
<div id="comment:5"></div>

Branch pushed to git repo; I updated commit sha1. New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/818403963bc01bec9ee5a9f38383009c8fcf4942"><code>8184039</code></a></td><td><code>Remove the fix from #34465</code></td></tr></table>

**Comment by kwankyu** [comment]
Description changed:
``````diff
--- 
+++ 
@@ -1,6 +1 @@
-Noticed in
 
-```
-[sagemath_doc_html-none] .../src/sage/functions/special.py:852: 
-DeprecationWarning: invalid escape sequence \p
-```
``````

**Comment by kwankyu** [comment]
<div id="comment:6" align="right">comment:6</div>

Replying to [Frédéric Chapoton](#comment%3A4):
> see #34465

Thanks :)

**Comment by mkoeppe** [comment]
Reviewer: **Matthias Koeppe**

**Comment by kwankyu** [comment]
<div id="comment:8" align="right">comment:8</div>

Thanks!

**Comment by vbraun** [comment]
Changed branch from **[u/klee/fix_invalid_escape_sequence_warning](https://github.com/sagemath/sagetrac-mirror/tree/u/klee/fix_invalid_escape_sequence_warning)** to **[`8184039`](https://github.com/sagemath/sagetrac-mirror/commit/818403963bc01bec9ee5a9f38383009c8fcf4942)**
