### ISSUE TITLE
Remove binary_function from ginac's code in sage

### ISSUE THREAD

**Issue by kiwifb** [sagemath/sage#34573]
<div id="comment:0"></div>

The use of `std::binary_function` and `std::unary_function` have been deprecated for almost 10 years and gcc-12 is now signalling it. They may be completely removed soon. We get the following warnings when building sage

```
INFO: compile options: '-I./sage/cpython -I/home/portage/sci-mathematics/sage-9999/work/sage-9999/src -I/usr/lib/python3.10/site-packages/numpy/core/include -I/usr/include/python3.10 -Ibuild/cythonized -I/usr/include/python3.10 -c'
extra options: '-fno-strict-aliasing -DCYTHON_CLINE_IN_TRACEBACK=1'
INFO: x86_64-pc-linux-gnu-gcc: build/cythonized/sage/symbolic/ring.c
INFO: x86_64-pc-linux-gnu-gcc: sage/symbolic/ginac/ex.cpp
In file included from sage/symbolic/ginac/basic.h:35,
                 from sage/symbolic/ginac/ex.h:26,
                 from sage/symbolic/ginac/assume.cpp:8:
sage/symbolic/ginac/ptr.h:162:11: warning: ‘template<class _Arg1, class _Arg2, class _Result> struct std::binary_function’ is deprecated [-Wdeprecated-declarations]
  162 |  : public binary_function<GiNaC::ptr<T>, GiNaC::ptr<T>, bool> {
      |           ^~~~~~~~~~~~~~~
In file included from /usr/lib/gcc/x86_64-pc-linux-gnu/12.2.0/include/g++-v12/bits/refwrap.h:39,
                 from /usr/lib/gcc/x86_64-pc-linux-gnu/12.2.0/include/g++-v12/vector:66,
                 from sage/symbolic/ginac/basic.h:26:
/usr/lib/gcc/x86_64-pc-linux-gnu/12.2.0/include/g++-v12/bits/stl_function.h:131:12: note: declared here
```
The following files contain offending code

```
src/sage/symbolic/ginac/order.h:class print_order : public std::binary_function<ex, ex, bool> {
src/sage/symbolic/ginac/order.h:        public std::binary_function<expair, expair, bool>
src/sage/symbolic/ginac/expair.h:struct expair_is_less : public std::binary_function<expair, expair, bool> {
src/sage/symbolic/ginac/expair.h:struct expair_rest_is_less : public std::binary_function<expair, expair, bool> {
src/sage/symbolic/ginac/expair.h:struct expair_swap : public std::binary_function<expair, expair, void> {
src/sage/symbolic/ginac/ptr.h: : public binary_function<GiNaC::ptr<T>, GiNaC::ptr<T>, bool> {
src/sage/symbolic/ginac/ex.h:struct ex_is_less : public std::binary_function<ex, ex, bool> {
src/sage/symbolic/ginac/ex.h:struct ex_is_equal : public std::binary_function<ex, ex, bool> {
src/sage/symbolic/ginac/ex.h:struct op0_is_equal : public std::binary_function<ex, ex, bool> {
src/sage/symbolic/ginac/ex.h:struct ex_swap : public std::binary_function<ex, ex, void> {
```

There are no instances of `unary_function` in sage.

I did a similar clean up in brial quite recently https://github.com/BRiAl/BRiAl/pull/52/files

CC:  @antonio-rojas

Component: **porting**

Author: **François Bissey**

Branch/Commit: **[`0dc211b`](https://github.com/sagemath/sagetrac-mirror/commit/0dc211bda2ce63861f3494a99f157ffea468baaa)**

Reviewer: **Matthias Koeppe**

_Issue created by migration from https://trac.sagemath.org/ticket/34573_

**Comment by mkoeppe** [comment]
<div id="comment:1" align="right">comment:1</div>

We should take a look at what upstream did with the affected code (see #33401). They had many C++ cleanups over the years.

**Comment by kiwifb** [comment]
<div id="comment:2" align="right">comment:2</div>

That is true, but right now I will just focus on that bit. Most of the time just removing the offending characters works. In real time, it appears to have compiled cleanly locally. Moving on doctesting.

**Comment by mkoeppe** [comment]
<div id="comment:3" align="right">comment:3</div>

Upstream did this change in 319c9533e12eba2449001c47545e3c3cf48c482f

**Comment by kiwifb** [comment]
<div id="comment:4" align="right">comment:4</div>

Right, I supposed I should discard what I have just done and use that instead. It should have gone through more testing.

**Comment by kiwifb** [comment]
<div id="comment:5" align="right">comment:5</div>

I never thought about that before, how do I track a hash down on github? Do You have to check out and search with git manually?

**Comment by mkoeppe** [comment]
<div id="comment:6" align="right">comment:6</div>

Only tried this out now, but a global search for that sha finds repo & commit!
https://github.com/search?q=319c9533e12eba2449001c47545e3c3cf48c482f&type=commits

**Comment by kiwifb** [comment]
<div id="comment:7" align="right">comment:7</div>

OK, that's interesting. So, my patch includes touching one file not in that commit because it is not in that repository. And the commit touches files we do not have in sage. Where they overlap, my job is identical to one white space difference.

So, I think I'll just send my branch and we'll think about synchronisation later because that won't be fun.

**Comment by mkoeppe** [comment]
<div id="comment:8" align="right">comment:8</div>

Yes, I agree.

**Comment by kiwifb** [comment]
Branch: **[u/fbissey/binary_function](https://github.com/sagemath/sagetrac-mirror/tree/u/fbissey/binary_function)**

**Comment by kiwifb** [comment]
Commit: **[`0dc211b`](https://github.com/sagemath/sagetrac-mirror/commit/0dc211bda2ce63861f3494a99f157ffea468baaa)**

**Comment by kiwifb** [comment]
<div id="comment:9"></div>

New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/0dc211bda2ce63861f3494a99f157ffea468baaa"><code>0dc211b</code></a></td><td><code>Removin binary_function from ginac code</code></td></tr></table>

**Comment by kiwifb** [comment]
Author: **François Bissey**

**Comment by mkoeppe** [comment]
Reviewer: **Matthias Koeppe**

**Comment by sheerluck** [comment]
<div id="comment:11" align="right">comment:11</div>

positive review from gentoo user

**Comment by vbraun** [comment]
Changed branch from **[u/fbissey/binary_function](https://github.com/sagemath/sagetrac-mirror/tree/u/fbissey/binary_function)** to **[`0dc211b`](https://github.com/sagemath/sagetrac-mirror/commit/0dc211bda2ce63861f3494a99f157ffea468baaa)**
