### ISSUE TITLE
do not create symmetric functions that are equal and different from 0

### ISSUE THREAD

**Issue by mantepse** [sagemath/sage#34576]
<div id="comment:0"></div>

```
┌────────────────────────────────────────────────────────────────────┐
│ SageMath version 9.7, Release Date: 2022-09-19                     │
│ Using Python 3.10.5. Type "help()" for help.                       │
└────────────────────────────────────────────────────────────────────┘
sage: s = SymmetricFunctions(ZZ).s()
sage: f = s(0/2); f
0
sage: f == 0
False
sage: f._monomial_coefficients
{[]: 0}
```

CC:  @zabrocki @tscrim

Component: **combinatorics**

Keywords: **symmetric functions**

Author: **Martin Rubey**

Branch: **[`e6ae236`](https://github.com/sagemath/sagetrac-mirror/commit/e6ae2366fc508188703fd2aa4b7a3595409a55fd)**

Reviewer: **Travis Scrimshaw**

_Issue created by migration from https://trac.sagemath.org/ticket/34576_

**Comment by mantepse** [comment]
Description changed:
``````diff
--- 
+++ 
@@ -1 +1,14 @@
 
+```
+┌────────────────────────────────────────────────────────────────────┐
+│ SageMath version 9.7, Release Date: 2022-09-19                     │
+│ Using Python 3.10.5. Type "help()" for help.                       │
+└────────────────────────────────────────────────────────────────────┘
+sage: s = SymmetricFunctions(ZZ).s()
+sage: f = s(0/2); f
+0
+sage: f == 0
+False
+sage: f._monomial_coefficients
+{[]: 0}
+```
``````

**Comment by mantepse** [comment]
Author: **Martin Rubey**

**Comment by mantepse** [comment]
Branch: **[u/mantepse/do_not_create_symmetric_functions_that_are_equal_and_different_from_0](https://github.com/sagemath/sagetrac-mirror/tree/u/mantepse/do_not_create_symmetric_functions_that_are_equal_and_different_from_0)**

**Comment by mantepse** [comment]
Commit: **[`e6ae236`](https://github.com/sagemath/sagetrac-mirror/commit/e6ae2366fc508188703fd2aa4b7a3595409a55fd)**

**Comment by mantepse** [comment]
<div id="comment:3"></div>

New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/e6ae2366fc508188703fd2aa4b7a3595409a55fd"><code>e6ae236</code></a></td><td><code>fix and slightly simplify _element_constructor_</code></td></tr></table>

**Comment by mantepse** [comment]
<div id="comment:4" align="right">comment:4</div>

Mike, could you have a look?

**Comment by mantepse** [comment]
Changed keywords from none to **symmetric functions**

**Comment by tscrim** [comment]
<div id="comment:5" align="right">comment:5</div>

Good catch; that is a fairly bad bug. Green bot => positive review.

**Comment by tscrim** [comment]
Reviewer: **Travis Scrimshaw**

**Comment by mantepse** [comment]
<div id="comment:7" align="right">comment:7</div>

Can I assume that the bug in `klyachko.py` is unrelated?

**Comment by tscrim** [comment]
<div id="comment:8" align="right">comment:8</div>

Yes, it is a known bug.

**Comment by vbraun** [comment]
Changed branch from **[u/mantepse/do_not_create_symmetric_functions_that_are_equal_and_different_from_0](https://github.com/sagemath/sagetrac-mirror/tree/u/mantepse/do_not_create_symmetric_functions_that_are_equal_and_different_from_0)** to **[`e6ae236`](https://github.com/sagemath/sagetrac-mirror/commit/e6ae2366fc508188703fd2aa4b7a3595409a55fd)**

**Comment by fchapoton** [comment]
Changed commit from **[`e6ae236`](https://github.com/sagemath/sagetrac-mirror/commit/e6ae2366fc508188703fd2aa4b7a3595409a55fd)** to none
