### ISSUE TITLE
GH Actions portability workflows: Use SAGE_FAT_BINARY=yes

### ISSUE THREAD

**Issue by mkoeppe** [sagemath/sage#34572]
<div id="comment:0"></div>

This will make the 2-stage builds from #33062 more robust (see [#33816 comment:60](https://github.com/sagemath/sage/issues/33816#comment:60)) and will make the 
devcontainer feature based on the portability images (https://trac.sagemath.org/wiki/ReleaseTours/sage-9.7#VisualStudioCodedevcontainers) more useful.

CC:  @dimpase @tobiasdiez @jhpalmieri

Component: **porting**

Author: **Matthias Koeppe**

Branch/Commit: **[`9696b34`](https://github.com/sagemath/sagetrac-mirror/commit/9696b346bd857f6ac8c2eaaacc6702de7e63120f)**

Reviewer: **Dima Pasechnik**

_Issue created by migration from https://trac.sagemath.org/ticket/34572_

**Comment by mkoeppe** [comment]
Branch: **[u/mkoeppe/gh_actions_portability_workflows__use_sage_fat_binary_yes](https://github.com/sagemath/sagetrac-mirror/tree/u/mkoeppe/gh_actions_portability_workflows__use_sage_fat_binary_yes)**

**Comment by mkoeppe** [comment]
<div id="comment:2"></div>

New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/9696b346bd857f6ac8c2eaaacc6702de7e63120f"><code>9696b34</code></a></td><td><code>.github/workflows/docker.yml: Use EXTRA_CONFIGURE_ARGS=--enable-fat-binary</code></td></tr></table>

**Comment by mkoeppe** [comment]
Author: **Matthias Koeppe**

**Comment by mkoeppe** [comment]
Commit: **[`9696b34`](https://github.com/sagemath/sagetrac-mirror/commit/9696b346bd857f6ac8c2eaaacc6702de7e63120f)**

**Comment by mkoeppe** [comment]
<div id="comment:3" align="right">comment:3</div>

The sporadic SIGILLs in stage `standard` are gone - https://github.com/mkoeppe/sage/actions/runs/3251926884

**Comment by dimpase** [comment]
<div id="comment:4" align="right">comment:4</div>

OK

**Comment by dimpase** [comment]
Reviewer: **Dima Pasechnik**

**Comment by mkoeppe** [comment]
<div id="comment:5" align="right">comment:5</div>

Thanks!

**Comment by vbraun** [comment]
Changed branch from **[u/mkoeppe/gh_actions_portability_workflows__use_sage_fat_binary_yes](https://github.com/sagemath/sagetrac-mirror/tree/u/mkoeppe/gh_actions_portability_workflows__use_sage_fat_binary_yes)** to **[`9696b34`](https://github.com/sagemath/sagetrac-mirror/commit/9696b346bd857f6ac8c2eaaacc6702de7e63120f)**
