### ISSUE TITLE
standard error messages in pbori

### ISSUE THREAD

**Issue by fchapoton** [sagemath/sage#34578]
<div id="comment:0"></div>

no capital, no final dot

Component: **commutative algebra**

Keywords: **pbori**

Author: **Frédéric Chapoton**

Branch/Commit: **[`82bfeaa`](https://github.com/sagemath/sagetrac-mirror/commit/82bfeaaaf6b772d0c893b12e7945707c745f0c0e)**

Reviewer: **David Coudert**

_Issue created by migration from https://trac.sagemath.org/ticket/34578_

**Comment by fchapoton** [comment]
Branch: **[u/chapoton/34578](https://github.com/sagemath/sagetrac-mirror/tree/u/chapoton/34578)**

**Comment by fchapoton** [comment]
<div id="comment:1"></div>

New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/82bfeaaaf6b772d0c893b12e7945707c745f0c0e"><code>82bfeaa</code></a></td><td><code>standard error messages in pbori/</code></td></tr></table>

**Comment by fchapoton** [comment]
Commit: **[`82bfeaa`](https://github.com/sagemath/sagetrac-mirror/commit/82bfeaaaf6b772d0c893b12e7945707c745f0c0e)**

**Comment by fchapoton** [comment]
Changed keywords from none to **pbori**

**Comment by dcoudert** [comment]
<div id="comment:3" align="right">comment:3</div>

LGTM.

**Comment by dcoudert** [comment]
Reviewer: **David Coudert**

**Comment by vbraun** [comment]
Changed branch from **[u/chapoton/34578](https://github.com/sagemath/sagetrac-mirror/tree/u/chapoton/34578)** to **[`82bfeaa`](https://github.com/sagemath/sagetrac-mirror/commit/82bfeaaaf6b772d0c893b12e7945707c745f0c0e)**
