### ISSUE TITLE
fix typo in docstring

### ISSUE THREAD

**Issue by mantepse** [sagemath/sage#34571]
<div id="comment:0"></div>

Component: **documentation**

Author: **Martin Rubey**

Branch/Commit: **[`6cb4043`](https://github.com/sagemath/sagetrac-mirror/commit/6cb40430327f5e7ac5addd78841119abdedcb916)**

Reviewer: **Frédéric Chapoton**

_Issue created by migration from https://trac.sagemath.org/ticket/34571_

**Comment by mantepse** [comment]
Branch: **[u/mantepse/fix_typo_in_docstring](https://github.com/sagemath/sagetrac-mirror/tree/u/mantepse/fix_typo_in_docstring)**

**Comment by mantepse** [comment]
<div id="comment:2" align="right">comment:2</div>

The docstring had `(1/a)^(-n)`, which comes out wrong when typeset.

---
New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/6cb40430327f5e7ac5addd78841119abdedcb916"><code>6cb4043</code></a></td><td><code>curly braces for typesetting</code></td></tr></table>

**Comment by mantepse** [comment]
Author: **Martin Rubey**

**Comment by mantepse** [comment]
Commit: **[`6cb4043`](https://github.com/sagemath/sagetrac-mirror/commit/6cb40430327f5e7ac5addd78841119abdedcb916)**

**Comment by fchapoton** [comment]
<div id="comment:3" align="right">comment:3</div>

gut

**Comment by fchapoton** [comment]
Reviewer: **Frédéric Chapoton**

**Comment by vbraun** [comment]
Changed branch from **[u/mantepse/fix_typo_in_docstring](https://github.com/sagemath/sagetrac-mirror/tree/u/mantepse/fix_typo_in_docstring)** to **[`6cb4043`](https://github.com/sagemath/sagetrac-mirror/commit/6cb40430327f5e7ac5addd78841119abdedcb916)**
