### ISSUE TITLE
Implement substitution in InfinitePolynomialRing

### ISSUE THREAD

**Issue by trevorkarn** [sagemath/sage#34581]
<div id="comment:0"></div>

Add the ability to substitute variables in `InfinitePolynomialRing`.

```
sage: R.<z> = InfinitePolynomialRing(QQ)
sage: f = z[1] + z[1]*z[2]*z[3]
sage: f.subs({z[1]:z[0]})
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Input In [3], in <cell line: 1>()
----> 1 f.subs({z[Integer(1)]:z[Integer(0)]})

File ~/Applications/sage/src/sage/structure/element.pyx:830, in sage.structure.element.Element.subs()
    828 if str(gen) in kwds:
    829     variables.append(kwds[str(gen)])
--> 830 elif in_dict and gen in in_dict:
    831     variables.append(in_dict[gen])
    832 else:

TypeError: unhashable type: 'InfinitePolynomialGen'
```

CC:  @tscrim @mwhansen @simon-king-jena

Component: **algebra**

Keywords: **polynomial infinite substitution subs**

Author: **Trevor K. Karn**

Branch/Commit: **[`a56e345`](https://github.com/sagemath/sagetrac-mirror/commit/a56e345cd9c3203b432f2f29c743f0f4606dc088)**

Reviewer: **Tomer Bauer, Travis Scrimshaw**

_Issue created by migration from https://trac.sagemath.org/ticket/34581_

**Comment by trevorkarn** [comment]
<div id="comment:1"></div>

New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/2ec0f39878c82bdb1802f98bff7ec0ffdd7c37a8"><code>2ec0f39</code></a></td><td><code>Add subs method</code></td></tr></table>

**Comment by trevorkarn** [comment]
Commit: **[`2ec0f39`](https://github.com/sagemath/sagetrac-mirror/commit/2ec0f39878c82bdb1802f98bff7ec0ffdd7c37a8)**

**Comment by trevorkarn** [comment]
Branch: **[u/tkarn/inf-poly-subs-34581](https://github.com/sagemath/sagetrac-mirror/tree/u/tkarn/inf-poly-subs-34581)**

**Comment by tscrim** [comment]
<div id="comment:2" align="right">comment:2</div>

There are some bad behaviors that this implements:

- It forces the inputs to be in the polynomial ring. I should be able to substitute anything I want where the computation makes such, such as square matrices. This should be a simple redirection.
- It forces the output to be in the infinite polynomial ring. Instead, the output should be the common parent of the input and the base ring.

The "standard" thing to do is redirect everything through `__call__` after parsing the inputs a bit, and probably should be done here too. Although I am a bit tempted to just instead do a simple redirect to `self._p.subs(*args, **kwds)`. Actually, there probably is a general problem of not expanding the input polynomial to be large enough to handle the input.

```
sage: f(x_10=f)
KeyError
sage: f(x_2=f)
x_3^2*x_2*x_1^2 + x_3*x_1^2 + x_1
sage: x[12]  # make it big enough
x_12
sage: f(x_10=f)
x_3*x_2*x_1 + x_1
```
Probably the input parsing of `subs` and `__call__` should be refactored out into a helper method, and then both of these methods redirect to their finite polynomial counterparts.

**Comment by fchapoton** [comment]
<div id="comment:3" align="right">comment:3</div>

beware of #34542

**Comment by mathzeta** [comment]
<div id="comment:4" align="right">comment:4</div>

This might answer [this question](https://ask.sagemath.org/question/42325/polynomial-rings-with-an-arbitrary-infinite-set-of-variables/) from 4 years ago. Thanks!

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
Changed commit from **[`2ec0f39`](https://github.com/sagemath/sagetrac-mirror/commit/2ec0f39878c82bdb1802f98bff7ec0ffdd7c37a8)** to **[`623021f`](https://github.com/sagemath/sagetrac-mirror/commit/623021f3c1fedd3040046b704ab9edccec3b0162)**

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
<div id="comment:5"></div>

Branch pushed to git repo; I updated commit sha1. This was a forced push. New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/74911139ceef9b690bd0c1369acc523a5802248f"><code>7491113</code></a></td><td><code>Add subs method</code></td></tr><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/623021f3c1fedd3040046b704ab9edccec3b0162"><code>623021f</code></a></td><td><code>Punt to call and add doctests</code></td></tr></table>

**Comment by trevorkarn** [comment]
<div id="comment:6" align="right">comment:6</div>

It looks like `__call__` took care of everything, so the `.subs()` method now does all of the preparsing and passes to `__call__`. I don't like the variable name `fixed`, but it is consistent with `MPolynomial_libsingular.subs()`.

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
Changed commit from **[`623021f`](https://github.com/sagemath/sagetrac-mirror/commit/623021f3c1fedd3040046b704ab9edccec3b0162)** to **[`0082d03`](https://github.com/sagemath/sagetrac-mirror/commit/0082d0327f68c2f0c6987d85d106b6f75a16982a)**

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
<div id="comment:7"></div>

Branch pushed to git repo; I updated commit sha1. New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/0082d0327f68c2f0c6987d85d106b6f75a16982a"><code>0082d03</code></a></td><td><code>PEP8 compliance</code></td></tr></table>

**Comment by trevorkarn** [comment]
<div id="comment:9" align="right">comment:9</div>

Green bot :)

**Comment by mathzeta** [comment]
<div id="comment:10" align="right">comment:10</div>

LGTM. positive review.

Almost unrelated to this ticket, already in the `__call__` method we can substitute all variables from a "finite" polynomial ring:

```sage
sage: R.<x> = InfinitePolynomialRing(QQ)
sage: S.<z, w> = QQ[]
sage: f = x[1] + x[1]*x[2]*x[3]
sage: f(x_1=w, x_2=z^2+1, x_3=z)
z^3*w + z*w + w
```

But it is a pity we do not have a canonical coercion when substituting only some of the variables:

```sage
sage: f(x_1=w)
[...]
TypeError: no canonical coercion from Multivariate Polynomial Ring in z, w over Rational Field to Multivariate Polynomial Ring in x_5, x_4, x_3, x_2, x_1, x_0 over Rational Field

During handling of the above exception, another exception occurred:
[...]
TypeError: unsupported operand parent(s) for *: 'Multivariate Polynomial Ring in x_5, x_4, x_3, x_2, x_1, x_0 over Rational Field' and 'Multivariate Polynomial Ring in z, w over Rational Field'
```

**Comment by mathzeta** [comment]
Reviewer: **Tomer Bauer**

**Comment by trevorkarn** [comment]
<div id="comment:11" align="right">comment:11</div>

Thanks! Where should the canonical coercion live? I recall seeing something that there is no coercion between polynomials from say `QQ[x]` and `QQ[y]` because it could live in any of `QQ[x,y]`, `QQ[x][y]`, `QQ[y][x]`. This seems like a similar problem to me. Should the substitution of some of the variables be in `QQ[x_0, x_1,...][w]` or `QQ[w][x_0, x_1,...]` (since I don't think `QQ[w,x_0,x_1,...]` exists in Sage yet).

**Comment by tscrim** [comment]
Changed reviewer from **Tomer Bauer** to **Tomer Bauer, Travis Scrimshaw**

**Comment by tscrim** [comment]
<div id="comment:12" align="right">comment:12</div>

Sorry for not being able to review this sooner.

A few things need to be addressed before a positive review from me.

Some doc changes:

```diff
-        Substitute variables in an infinite polynomial.
+        Substitute variables in ``self``.
 
         INPUT:
 
-        - ``fixed`` - (optional) dict with variable:value pairs
-        - ``**kwargs`` - names parameters
-        - ``fixed`` -- (optional) ``dict`` with ``{variable:value}`` pairs
-        - ``**kwargs`` -- named parameters
 
         OUTPUT:
-            a new polynomial
+
+        the resulting substitution
```

```diff
-If you want to substitute variables more generally, use the ``.subs``
-method::
+If you want to substitute variables, you can use the
+standard polynomial methods, such as
+:meth:`~sage.rings.polynomial.infinite_polynomial_element.InfinitePolynomial_sparse.subs`::
```

This documentation is not quite correct and make this change:

```diff
-       The substitution can also handle matrices. It will
-       return a matrix whose entries are polynomials in countably
-       many variables::
+       The substitution can also handle matrices::
```
It is more complicated than that as it does the substitution and then does the addition by coercion. You can check things by looking at the parent of the outputs (or doing additional substitutions).

This sentence seems incomplete:

```
        Passing ``fixed={x[1]: x[0]}``. Note that the keys::

            sage: f.subs({x[1]: x[0]})
            x_3*x_2*x_0 + x_0
```

I am not sure I would want to prohibit the mixing of the two types of inputs. I would just do `kwargs.update(fixed)`, which would be in line with what (some) other implementations do:

```
sage: R.<x,y> = PolynomialRing(QQ)
sage: x.subs({x:1})
1
sage: x.subs(x=5)
5
sage: x.subs({x:1}, x=5)
1
```

**Comment by tscrim** [comment]
<div id="comment:13" align="right">comment:13</div>

Coercion among polynomial rings is notoriously tricky to make consistent (there are some sage-devel threads about this). For example, how do you deal with `QQ[x][y,z]` versus `QQ[x,y][z]`, or a more complicated one, the ordering of the variables matters for Gröbner basis computations. So Sage just avoids doing it except in some trivial cases IIRC.

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
Changed commit from **[`0082d03`](https://github.com/sagemath/sagetrac-mirror/commit/0082d0327f68c2f0c6987d85d106b6f75a16982a)** to **[`5e8977f`](https://github.com/sagemath/sagetrac-mirror/commit/5e8977fe18f6b38e9eb4aeca066438b8d7e0514d)**

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
<div id="comment:14"></div>

Branch pushed to git repo; I updated commit sha1. New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/5e8977fe18f6b38e9eb4aeca066438b8d7e0514d"><code>5e8977f</code></a></td><td><code>Add reviewer suggestions to docs and change behavior of conflicting subs</code></td></tr></table>

**Comment by trevorkarn** [comment]
<div id="comment:15" align="right">comment:15</div>

Thanks for the input!

**Comment by tscrim** [comment]
<div id="comment:16" align="right">comment:16</div>

Thank you. One last little thing (an idiosyncrasy most likely), I generally try to avoid referencing Python double-underscore methods. So I would change

```diff
         Passing ``fixed={x[1]: x[0]}``. Note that the keys may be given
-        using the ``.__getitem__`` method of the infinite polynomial
-        generator ``x_*`` or as a string::
+        using the generators of the infinite polynomial ring
+        or as a string::
```
After you make this change (or a similar one), you can set a positive review on my behalf if you want.

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
Changed commit from **[`5e8977f`](https://github.com/sagemath/sagetrac-mirror/commit/5e8977fe18f6b38e9eb4aeca066438b8d7e0514d)** to **[`a56e345`](https://github.com/sagemath/sagetrac-mirror/commit/a56e345cd9c3203b432f2f29c743f0f4606dc088)**

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
<div id="comment:17"></div>

Branch pushed to git repo; I updated commit sha1. New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/a56e345cd9c3203b432f2f29c743f0f4606dc088"><code>a56e345</code></a></td><td><code>Doc change</code></td></tr></table>

**Comment by trevorkarn** [comment]
<div id="comment:18" align="right">comment:18</div>

Replying to [Travis Scrimshaw](#comment%3A16):
> Thank you. One last little thing (an idiosyncrasy most likely), I generally try to avoid referencing Python double-underscore methods. So I would change
> 
> ```diff
>          Passing ``fixed={x[1]: x[0]}``. Note that the keys may be given
> -        using the ``.__getitem__`` method of the infinite polynomial
> -        generator ``x_*`` or as a string::
> +        using the generators of the infinite polynomial ring
> +        or as a string::
> ```

Thanks!
> After you make this change (or a similar one), you can set a positive review on my behalf if you want.

**Comment by vbraun** [comment]
Changed branch from **[u/tkarn/inf-poly-subs-34581](https://github.com/sagemath/sagetrac-mirror/tree/u/tkarn/inf-poly-subs-34581)** to **[`a56e345`](https://github.com/sagemath/sagetrac-mirror/commit/a56e345cd9c3203b432f2f29c743f0f4606dc088)**
