### ISSUE TITLE
use .Display for gap character tables

### ISSUE THREAD

**Issue by fchapoton** [sagemath/sage#34584]
<div id="comment:0"></div>

CC:  @tscrim @kwankyu @kliem @slel

Component: **group theory**

Author: **Frédéric Chapoton**

Branch/Commit: **[`805bf11`](https://github.com/sagemath/sagetrac-mirror/commit/805bf1194f1944855faa95dd155b711f811e5393)**

Reviewer: **Travis Scrimshaw**

_Issue created by migration from https://trac.sagemath.org/ticket/34584_

**Comment by fchapoton** [comment]
<div id="comment:1" align="right">comment:1</div>

should be a very easy review

---
New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/805bf1194f1944855faa95dd155b711f811e5393"><code>805bf11</code></a></td><td><code>use .Display for character tables</code></td></tr></table>

**Comment by fchapoton** [comment]
Branch: **[u/chapoton/34584](https://github.com/sagemath/sagetrac-mirror/tree/u/chapoton/34584)**

**Comment by fchapoton** [comment]
Commit: **[`805bf11`](https://github.com/sagemath/sagetrac-mirror/commit/805bf1194f1944855faa95dd155b711f811e5393)**

**Comment by tscrim** [comment]
Reviewer: **Travis Scrimshaw**

**Comment by tscrim** [comment]
<div id="comment:2" align="right">comment:2</div>

LGTM.

**Comment by vbraun** [comment]
Changed branch from **[u/chapoton/34584](https://github.com/sagemath/sagetrac-mirror/tree/u/chapoton/34584)** to **[`805bf11`](https://github.com/sagemath/sagetrac-mirror/commit/805bf1194f1944855faa95dd155b711f811e5393)**
