### ISSUE TITLE
fix some E251 in modular

### ISSUE THREAD

**Issue by fchapoton** [sagemath/sage#34588]
<div id="comment:0"></div>

Component: **modular forms**

Author: **Frédéric Chapoton**

Branch/Commit: **[`18478ca`](https://github.com/sagemath/sagetrac-mirror/commit/18478cae2dc614a1e53890b6dbaee7431f107a4d)**

Reviewer: **Matthias Koeppe**

_Issue created by migration from https://trac.sagemath.org/ticket/34588_

**Comment by fchapoton** [comment]
Branch: **[u/chapoton/34588](https://github.com/sagemath/sagetrac-mirror/tree/u/chapoton/34588)**

**Comment by fchapoton** [comment]
Commit: **[`18478ca`](https://github.com/sagemath/sagetrac-mirror/commit/18478cae2dc614a1e53890b6dbaee7431f107a4d)**

**Comment by fchapoton** [comment]
<div id="comment:1"></div>

New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/905a0eeb762a802538fea630460624c37bf42605"><code>905a0ee</code></a></td><td><code>fix some E251 in modular/</code></td></tr><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/18478cae2dc614a1e53890b6dbaee7431f107a4d"><code>18478ca</code></a></td><td><code>fix E251 in Clifford too</code></td></tr></table>

**Comment by mkoeppe** [comment]
Reviewer: **Matthias Koeppe**

**Comment by vbraun** [comment]
Changed branch from **[u/chapoton/34588](https://github.com/sagemath/sagetrac-mirror/tree/u/chapoton/34588)** to **[`18478ca`](https://github.com/sagemath/sagetrac-mirror/commit/18478cae2dc614a1e53890b6dbaee7431f107a4d)**
