### ISSUE TITLE
Fix giac build to work with pari 2.15

### ISSUE THREAD

**Issue by mkoeppe** [sagemath/sage#34586]
<div id="comment:0"></div>

split out from #34537

A workaround is documented in https://trac.sagemath.org/wiki/ReleaseTours/sage-9.7#AvailabilityofSage9.7andinstallationhelp but we should get this in urgently.

Depends on #34496

Upstream: **Reported upstream. No feedback yet.**

CC:  @videlec @antonio-rojas @sagetrac-parisse

Component: **packages: standard**

Branch/Commit: **[u/mkoeppe/fix_giac_build_to_work_with_pari_2_15](https://github.com/sagemath/sagetrac-mirror/tree/u/mkoeppe/fix_giac_build_to_work_with_pari_2_15) @ [`041d16b`](https://github.com/sagemath/sagetrac-mirror/commit/041d16b521d8231e5b441015f08bb386f9d2a51c)**

Reviewer: **Dima Pasechnik**

_Issue created by migration from https://trac.sagemath.org/ticket/34586_

**Comment by mkoeppe** [comment]
Branch: **[u/mkoeppe/fix_giac_build_to_work_with_pari_2_15](https://github.com/sagemath/sagetrac-mirror/tree/u/mkoeppe/fix_giac_build_to_work_with_pari_2_15)**

**Comment by mkoeppe** [comment]
Reviewer: **Matthias Koeppe**

**Comment by mkoeppe** [comment]
<div id="comment:2"></div>

New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/041d16b521d8231e5b441015f08bb386f9d2a51c"><code>041d16b</code></a></td><td><code>ANYARG giac patch</code></td></tr></table>

**Comment by mkoeppe** [comment]
Commit: **[`041d16b`](https://github.com/sagemath/sagetrac-mirror/commit/041d16b521d8231e5b441015f08bb386f9d2a51c)**

**Comment by antonio-rojas** [comment]
<div id="comment:5" align="right">comment:5</div>

I'm not convinced that a broken build is worse than the build working and then having many things broken at runtime (all the test failures reported in #34537). If anything, system 2.15 should be rejected until #34537 is merged.

**Comment by mkoeppe** [comment]
<div id="comment:7" align="right">comment:7</div>

OK, that's probably better

**Comment by dimpase** [comment]
<div id="comment:8" align="right">comment:8</div>

We should disallow using of pari 2.15 from the system. I'll make patch - we already getting many reports on sage-devel etc due to this issus.

**Comment by dimpase** [comment]
<div id="comment:9" align="right">comment:9</div>

Replying to [Dima Pasechnik](#comment%3A8):
> We should disallow using of pari 2.15 from the system. I'll make patch - we already getting many reports on sage-devel etc due to this issus.
> 

Please see #34496 for the fix.

**Comment by mkoeppe** [comment]
Changed reviewer from **Matthias Koeppe** to none

**Comment by mkoeppe** [comment]
Changed author from **Vincent Delecroix** to none

**Comment by mkoeppe** [comment]
Dependencies: **#34496**

**Comment by dimpase** [comment]
Reviewer: **Dima Pasechnik**

**Comment by dimpase** [comment]
<div id="comment:12" align="right">comment:12</div>

upstream report: https://xcas.univ-grenoble-alpes.fr/forum/viewtopic.php?f=3&t=2800

**Comment by dimpase** [comment]
Upstream: **Reported upstream. No feedback yet.**

**Comment by antonio-rojas** [comment]
<div id="comment:13" align="right">comment:13</div>

Not sure if relevant for Sage, but the giac test suite segfaults here with pari 2.15 (after applying the build fix).

**Comment by dimpase** [comment]
<div id="comment:14" align="right">comment:14</div>

should be discussing on #34496, not here, sorry.

**Comment by dimpase** [comment]
<div id="comment:15" align="right">comment:15</div>

oops, I meant #34537
