### ISSUE TITLE
pep8 cleanup in algebras/letterplace pyx files

### ISSUE THREAD

**Issue by fchapoton** [sagemath/sage#34585]
<div id="comment:0"></div>

CC:  @tscrim @kwankyu @kliem @dcoudert

Component: **algebra**

Author: **Frédéric Chapoton**

Branch/Commit: **[`1d6ce21`](https://github.com/sagemath/sagetrac-mirror/commit/1d6ce21ab453aa0547927e3930d2600a0e1a826b)**

Reviewer: **Travis Scrimshaw**

_Issue created by migration from https://trac.sagemath.org/ticket/34585_

**Comment by fchapoton** [comment]
Branch: **[u/chapoton/34585](https://github.com/sagemath/sagetrac-mirror/tree/u/chapoton/34585)**

**Comment by fchapoton** [comment]
Commit: **[`8540c9a`](https://github.com/sagemath/sagetrac-mirror/commit/8540c9af9f1027bf229140e7a377be2e2ab97454)**

**Comment by fchapoton** [comment]
<div id="comment:1"></div>

New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/8540c9af9f1027bf229140e7a377be2e2ab97454"><code>8540c9a</code></a></td><td><code>pep8 cleanup in algebras/letterplace (pyx files)</code></td></tr></table>

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
Changed commit from **[`8540c9a`](https://github.com/sagemath/sagetrac-mirror/commit/8540c9af9f1027bf229140e7a377be2e2ab97454)** to **[`a4f089d`](https://github.com/sagemath/sagetrac-mirror/commit/a4f089d6cee897b4233b52ca9f644ac72a57e72e)**

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
<div id="comment:2"></div>

Branch pushed to git repo; I updated commit sha1. New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/a4f089d6cee897b4233b52ca9f644ac72a57e72e"><code>a4f089d</code></a></td><td><code>fix mistakes</code></td></tr></table>

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
Changed commit from **[`a4f089d`](https://github.com/sagemath/sagetrac-mirror/commit/a4f089d6cee897b4233b52ca9f644ac72a57e72e)** to **[`6dca1c4`](https://github.com/sagemath/sagetrac-mirror/commit/6dca1c4575c42384138e3f12c9b8d7496b86b0c1)**

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
<div id="comment:3"></div>

Branch pushed to git repo; I updated commit sha1. New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/6dca1c4575c42384138e3f12c9b8d7496b86b0c1"><code>6dca1c4</code></a></td><td><code>fix back the max</code></td></tr></table>

**Comment by mkoeppe** [comment]
<div id="comment:4" align="right">comment:4</div>

test failures

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
Changed commit from **[`6dca1c4`](https://github.com/sagemath/sagetrac-mirror/commit/6dca1c4575c42384138e3f12c9b8d7496b86b0c1)** to **[`1d6ce21`](https://github.com/sagemath/sagetrac-mirror/commit/1d6ce21ab453aa0547927e3930d2600a0e1a826b)**

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
<div id="comment:5"></div>

Branch pushed to git repo; I updated commit sha1. This was a forced push. New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/1d6ce21ab453aa0547927e3930d2600a0e1a826b"><code>1d6ce21</code></a></td><td><code>pep8 cleanup in algebras/letterplace (pyx files)</code></td></tr></table>

**Comment by fchapoton** [comment]
<div id="comment:6" align="right">comment:6</div>

hopefully fixed now

**Comment by fchapoton** [comment]
<div id="comment:7" align="right">comment:7</div>

green bot, so please review

**Comment by tscrim** [comment]
Reviewer: **Travis Scrimshaw**

**Comment by tscrim** [comment]
<div id="comment:8" align="right">comment:8</div>

LGTM.

**Comment by vbraun** [comment]
Changed branch from **[u/chapoton/34585](https://github.com/sagemath/sagetrac-mirror/tree/u/chapoton/34585)** to **[`1d6ce21`](https://github.com/sagemath/sagetrac-mirror/commit/1d6ce21ab453aa0547927e3930d2600a0e1a826b)**
