### ISSUE TITLE
add helper function to compute all monomials of a given degree

### ISSUE THREAD

**Issue by yyyyx4** [sagemath/sage#34599]
<div id="comment:0"></div>

This comes in handy occasionally:

```python
sage: R.<x,y,z> = ZZ[]
sage: R.monomials_of_degree(3)
[x^3, x^2*y, x^2*z, x*y^2, x*y*z, x*z^2, y^3, y^2*z, y*z^2, z^3]
```

Component: **algebra**

Author: **Lorenz Panny**

Branch/Commit: **[`c28b7e1`](https://github.com/sagemath/sagetrac-mirror/commit/c28b7e10fde5e8bfd368eded843c51f8aaf14a66)**

Reviewer: **Marc Mezzarobba**

_Issue created by migration from https://trac.sagemath.org/ticket/34599_

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
<div id="comment:2"></div>

Branch pushed to git repo; I updated commit sha1. This was a forced push. New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/c28b7e10fde5e8bfd368eded843c51f8aaf14a66"><code>c28b7e1</code></a></td><td><code>add MPolynomialRing_base.monomials_of_degree()</code></td></tr></table>

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
Changed commit from **[`a926716`](https://github.com/sagemath/sagetrac-mirror/commit/a926716d35fc93c9dcf80730595fe7c1e42952f1)** to **[`c28b7e1`](https://github.com/sagemath/sagetrac-mirror/commit/c28b7e10fde5e8bfd368eded843c51f8aaf14a66)**

**Comment by mezzarobba** [comment]
Reviewer: **Marc Mezzarobba**

**Comment by mezzarobba** [comment]
<div id="comment:3" align="right">comment:3</div>

Thank you!

**Comment by vbraun** [comment]
Changed branch from **[public/monomials_of_degree](https://github.com/sagemath/sagetrac-mirror/tree/public/monomials_of_degree)** to **[`c28b7e1`](https://github.com/sagemath/sagetrac-mirror/commit/c28b7e10fde5e8bfd368eded843c51f8aaf14a66)**
