### ISSUE TITLE
Fix findstat internet tests

### ISSUE THREAD

**Issue by jhpalmieri** [sagemath/sage#34595]
<div id="comment:0"></div>

Tickets #27408 and #22349 broke some "optional - internet" tests in findstat, so let's fix them.

Component: **graph theory**

Keywords: **findstat**

Author: **John Palmieri**

Branch/Commit: **[`9c44659`](https://github.com/sagemath/sagetrac-mirror/commit/9c4465943a0f0d4a8e6843e187cc15b82215302b)**

Reviewer: **David Coudert**

_Issue created by migration from https://trac.sagemath.org/ticket/34595_

**Comment by jhpalmieri** [comment]
Branch: **[u/jhpalmieri/findstat-internet-tests](https://github.com/sagemath/sagetrac-mirror/tree/u/jhpalmieri/findstat-internet-tests)**

**Comment by jhpalmieri** [comment]
<div id="comment:2"></div>

New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/9c4465943a0f0d4a8e6843e187cc15b82215302b"><code>9c44659</code></a></td><td><code>trac 34595: fix internet doctests in findstat.py</code></td></tr></table>

**Comment by jhpalmieri** [comment]
Commit: **[`9c44659`](https://github.com/sagemath/sagetrac-mirror/commit/9c4465943a0f0d4a8e6843e187cc15b82215302b)**

**Comment by dcoudert** [comment]
<div id="comment:3" align="right">comment:3</div>

When I run `./sage -t --optional=external src/sage/databases/findstat.py`, I got many doctests errors (152) like:

```
sage -t --warn-long 80.2 --random-seed=72649070764419291381942551007802275570 src/sage/databases/findstat.py
**********************************************************************
File "src/sage/databases/findstat.py", line 49, in sage.databases.findstat
Failed example:
    r = findstat([(m, m.number_of_nestings()) for n in range(6) for m in PM(2*n)], depth=1); r # optional -- internet
Exception raised:
    Traceback (most recent call last):
      File "/Users/dcoudert/sage/src/sage/doctest/forker.py", line 695, in _run
        self.compile_and_execute(example, compiler, test.globs)
      File "/Users/dcoudert/sage/src/sage/doctest/forker.py", line 1093, in compile_and_execute
        exec(compiled, globs)
      File "<doctest sage.databases.findstat[0]>", line 1, in <module>
        r = findstat([(m, m.number_of_nestings()) for n in range(Integer(6)) for m in PM(Integer(2)*n)], depth=Integer(1)); r # optional -- internet
      File "<doctest sage.databases.findstat[0]>", line 1, in <listcomp>
        r = findstat([(m, m.number_of_nestings()) for n in range(Integer(6)) for m in PM(Integer(2)*n)], depth=Integer(1)); r # optional -- internet
    NameError: name 'PM' is not defined
**********************************************************************
File "src/sage/databases/findstat.py", line 83, in sage.databases.findstat
Failed example:
    print(r[1].statistic().description())                                 # optional -- internet
Exception raised:
    Traceback (most recent call last):
      File "/Users/dcoudert/sage/src/sage/doctest/forker.py", line 695, in _run
        self.compile_and_execute(example, compiler, test.globs)
      File "/Users/dcoudert/sage/src/sage/doctest/forker.py", line 1093, in compile_and_execute
        exec(compiled, globs)
      File "<doctest sage.databases.findstat[1]>", line 1, in <module>
        print(r[Integer(1)].statistic().description())                                 # optional -- internet
    AttributeError: 'RFunction' object has no attribute 'statistic'
**********************************************************************
File "src/sage/databases/findstat.py", line 91, in sage.databases.findstat
Failed example:
    r[1].statistic().references()                                         # optional -- internet
Exception raised:
    Traceback (most recent call last):
      File "/Users/dcoudert/sage/src/sage/doctest/forker.py", line 695, in _run
        self.compile_and_execute(example, compiler, test.globs)
      File "/Users/dcoudert/sage/src/sage/doctest/forker.py", line 1093, in compile_and_execute
        exec(compiled, globs)
      File "<doctest sage.databases.findstat[2]>", line 1, in <module>
        r[Integer(1)].statistic().references()                                         # optional -- internet
    AttributeError: 'RFunction' object has no attribute 'statistic'
**********************************************************************
File "src/sage/databases/findstat.py", line 104, in sage.databases.findstat
Failed example:
    findstat(data, depth=0)                                               # optional -- internet
Exception raised:
    Traceback (most recent call last):
      File "/Users/dcoudert/sage/src/sage/doctest/forker.py", line 695, in _run
        self.compile_and_execute(example, compiler, test.globs)
      File "/Users/dcoudert/sage/src/sage/doctest/forker.py", line 1093, in compile_and_execute
        exec(compiled, globs)
      File "<doctest sage.databases.findstat[3]>", line 1, in <module>
        findstat(data, depth=Integer(0))                                               # optional -- internet
    NameError: name 'data' is not defined
**********************************************************************
File "src/sage/databases/findstat.py", line 434, in sage.databases.findstat._get_json
Failed example:
    _get_json(FINDSTAT_API_MAPS + "?xxx=yyy")                         # optional -- internet
Expected:
    Traceback (most recent call last):
    ...
    ValueError: E005: On filtering maps, the following parameters are not allowed: [u'xxx'].
Got:
    <BLANKLINE>
    Traceback (most recent call last):
      File "/Users/dcoudert/sage/src/sage/doctest/forker.py", line 695, in _run
        self.compile_and_execute(example, compiler, test.globs)
      File "/Users/dcoudert/sage/src/sage/doctest/forker.py", line 1093, in compile_and_execute
        exec(compiled, globs)
      File "<doctest sage.databases.findstat._get_json[0]>", line 1, in <module>
        _get_json(FINDSTAT_API_MAPS + "?xxx=yyy")                         # optional -- internet
    NameError: name '_get_json' is not defined
...
```
Am I doing something wrong in the way I launch the tests or is it something else ?

**Comment by mantepse** [comment]
Changed keywords from none to **findstat**

**Comment by mantepse** [comment]
<div id="comment:5" align="right">comment:5</div>

@dcoudert: possibly it should be

```
./sage -t --optional=sage,external src/sage/databases/findstat.py
```

@jhpalmieri: I am not sure right now, but I don't think that the sorting is actually necessary.  Is there a way to turn off the warning without specifying the sort parameter?

**Comment by dcoudert** [comment]
Reviewer: **David Coudert**

**Comment by dcoudert** [comment]
<div id="comment:6" align="right">comment:6</div>

All tests pass with `./sage -t --optional=sage,external src/sage/databases/findstat.py`. Thanks.

I set this ticket to positive review.

**Comment by mantepse** [comment]
<div id="comment:7" align="right">comment:7</div>

@dcoudert: Thank you, but did you see my [comment:3](#comment%3A3)?

**Comment by dcoudert** [comment]
<div id="comment:8" align="right">comment:8</div>

it passes tests if we set `sort=False`, but I don't know if I'm lucky or if sorting is not needed for these tests.

**Comment by jhpalmieri** [comment]
<div id="comment:9" align="right">comment:9</div>

Replying to [Martin Rubey](#comment%3A5):
> @jhpalmieri: I am not sure right now, but I don't think that the sorting is actually necessary.  Is there a way to turn off the warning without specifying the sort parameter?

Right now, the only way to avoid the deprecation warning is to specify the sort parameter. This was deemed necessary to make the switch from the default being sorted to the default being unsorted. The first change changes `sorted(X.edges(...))` to `X.edges(sort=True, ...)`, so that is just repeating the sorting that was already happening. The last change uses `X.edges(sort=False)`, The middle one is a doctest that prints the edges, and to get repeatability of the output, I thought it was safest to sort.

**Comment by dcoudert** [comment]
<div id="comment:10" align="right">comment:10</div>

Let's keep it as is. The extra cost of sorting is rather minimal here and we avoid unexpected behavior.

**Comment by mantepse** [comment]
<div id="comment:11" align="right">comment:11</div>

I agree!

**Comment by jhpalmieri** [comment]
<div id="comment:12" align="right">comment:12</div>

Great, thank you both!

**Comment by vbraun** [comment]
Changed branch from **[u/jhpalmieri/findstat-internet-tests](https://github.com/sagemath/sagetrac-mirror/tree/u/jhpalmieri/findstat-internet-tests)** to **[`9c44659`](https://github.com/sagemath/sagetrac-mirror/commit/9c4465943a0f0d4a8e6843e187cc15b82215302b)**
