### ISSUE TITLE
Use python-build instead of "pip wheel"

### ISSUE THREAD

**Issue by mkoeppe** [sagemath/sage#34590]
<div id="comment:0"></div>

(for packages that don't use `--no-use-pep517`)

... as another step to more modern tooling.

Depends on #34344
Depends on #34272
Depends on #32483

Component: **build**

_Issue created by migration from https://trac.sagemath.org/ticket/34590_

**Comment by mkoeppe** [comment]
Dependencies: **#34344, #34272**

**Comment by mkoeppe** [comment]
Changed dependencies from **#34344, #34272** to **#34344, #34272, #32483**

**Comment by mkoeppe** [comment]
Description changed:
``````diff
--- 
+++ 
@@ -1 +1,4 @@
+(for packages that don't use `--no-use-pep517`)
+
 ... as another step to more modern tooling.
+
``````

**Comment by mkoeppe** [comment]
Branch: **[u/mkoeppe/use_python_build_instead_of__pip_wheel_](https://github.com/sagemath/sagetrac-mirror/tree/u/mkoeppe/use_python_build_instead_of__pip_wheel_)**

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
<div id="comment:5"></div>

Branch pushed to git repo; I updated commit sha1. This was a forced push. New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/306accf151b0851cad013962ee3997d1c17acdb8"><code>306accf</code></a></td><td><code>build/pkgs/python_build: Change to a normal standard package</code></td></tr><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/63f1c01190f0a0db02b32f279741b4d6ddb9374c"><code>63f1c01</code></a></td><td><code>WIP</code></td></tr></table>

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
Commit: **[`63f1c01`](https://github.com/sagemath/sagetrac-mirror/commit/63f1c01190f0a0db02b32f279741b4d6ddb9374c)**

**Comment by mkoeppe** [comment]
Removed branch from issue description; replaced by PR #35618.
