### ISSUE TITLE
fix W605 in libs and rings/semirings

### ISSUE THREAD

**Issue by fchapoton** [sagemath/sage#34592]
<div id="comment:0"></div>

in pyx files, as py files are already ok

CC:  @tscrim @kwankyu @kliem @slel

Component: **refactoring**

Author: **Frédéric Chapoton**

Branch/Commit: **[`1205fc8`](https://github.com/sagemath/sagetrac-mirror/commit/1205fc8770a71791be27a13553c4ad04b1a220f5)**

Reviewer: **Travis Scrimshaw**

_Issue created by migration from https://trac.sagemath.org/ticket/34592_

**Comment by fchapoton** [comment]
Branch: **[u/chapoton/34592](https://github.com/sagemath/sagetrac-mirror/tree/u/chapoton/34592)**

**Comment by fchapoton** [comment]
Commit: **[`8266146`](https://github.com/sagemath/sagetrac-mirror/commit/8266146638d0a3596b89896132e7436d1b49581f)**

**Comment by fchapoton** [comment]
<div id="comment:1"></div>

New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/8266146638d0a3596b89896132e7436d1b49581f"><code>8266146</code></a></td><td><code>fix W605 in libs/ and rings/semirings/</code></td></tr></table>

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
<div id="comment:2"></div>

Branch pushed to git repo; I updated commit sha1. New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/307698f9426a6130b1af23c53e69baf8eb8a20c1"><code>307698f</code></a></td><td><code>more cleanup in libs/</code></td></tr></table>

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
Changed commit from **[`8266146`](https://github.com/sagemath/sagetrac-mirror/commit/8266146638d0a3596b89896132e7436d1b49581f)** to **[`307698f`](https://github.com/sagemath/sagetrac-mirror/commit/307698f9426a6130b1af23c53e69baf8eb8a20c1)**

**Comment by fchapoton** [comment]
<div id="comment:3" align="right">comment:3</div>

green lights, so please review

**Comment by tscrim** [comment]
<div id="comment:4" align="right">comment:4</div>

Two while-we-are-at-it things that could be pushed to later:

`.. note::` -> `.. NOTE::`

and

```diff
         r"""
-        Returns a \class{FiniteFieldElement} representation of this element.
+        Return a :class:`FiniteFieldElement` representation of this element.
 
-        If a \class{FiniteField} k is provided it is constructed in
-        this field if possible. A \class{FiniteField} will be
+        If a :class:`FiniteField` `k` is provided it is constructed in
+        this field if possible. A :class:`FiniteField` will be
         constructed if none is provided.
 
         INPUT:
 
-        k     -- optional GF(2**deg)
+        - ``k`` -- (optional) a field `\GF{2^d}`
 
         OUTPUT:
 
-        FiniteFieldElement over k
+        :class:`FiniteFieldElement` over ``k``
```

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
<div id="comment:5"></div>

Branch pushed to git repo; I updated commit sha1. New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/1205fc8770a71791be27a13553c4ad04b1a220f5"><code>1205fc8</code></a></td><td><code>details as suggested by the reviewer</code></td></tr></table>

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
Changed commit from **[`307698f`](https://github.com/sagemath/sagetrac-mirror/commit/307698f9426a6130b1af23c53e69baf8eb8a20c1)** to **[`1205fc8`](https://github.com/sagemath/sagetrac-mirror/commit/1205fc8770a71791be27a13553c4ad04b1a220f5)**

**Comment by tscrim** [comment]
Reviewer: **Travis Scrimshaw**

**Comment by tscrim** [comment]
<div id="comment:6" align="right">comment:6</div>

Thank you. Green bot => positive review.

**Comment by fchapoton** [comment]
<div id="comment:7" align="right">comment:7</div>

thanks.

let me consider that a green light from the github badge is enough

**Comment by vbraun** [comment]
Changed branch from **[u/chapoton/34592](https://github.com/sagemath/sagetrac-mirror/tree/u/chapoton/34592)** to **[`1205fc8`](https://github.com/sagemath/sagetrac-mirror/commit/1205fc8770a71791be27a13553c4ad04b1a220f5)**
