### ISSUE TITLE
Fix error in sage.misc.latex.view doctest

### ISSUE THREAD

**Issue by jhpalmieri** [sagemath/sage#34594]
<div id="comment:0"></div>

With 9.8.beta0, the command

```
sage -t --long --optional=sage,optional,external src/sage/misc/latex.py
```
gives error.

Excerpted from #33931.

Component: **misc**

Author: **John Palmieri, Sébastien Labbé**

Branch/Commit: **[`81ff989`](https://github.com/sagemath/sagetrac-mirror/commit/81ff989f53610b3c367a46e50ed046aa1cfe8f69)**

Reviewer: **Sébastien Labbé, John Palmieri**

_Issue created by migration from https://trac.sagemath.org/ticket/34594_

**Comment by jhpalmieri** [comment]
Branch: **[u/jhpalmieri/latex-error](https://github.com/sagemath/sagetrac-mirror/tree/u/jhpalmieri/latex-error)**

**Comment by jhpalmieri** [comment]
<div id="comment:2"></div>

New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/4b1d7cd04a8bb8a40c7e1dd7cdc9de6d8c0ec014"><code>4b1d7cd</code></a></td><td><code>trac 34594: a doctest in "view" in sage.misc.latex should call</code></td></tr></table>

**Comment by jhpalmieri** [comment]
Commit: **[`4b1d7cd`](https://github.com/sagemath/sagetrac-mirror/commit/4b1d7cd04a8bb8a40c7e1dd7cdc9de6d8c0ec014)**

**Comment by seblabbe** [comment]
<div id="comment:3" align="right">comment:3</div>

It seems we need to give the filename, not the file itself.

The command

```
sage -t --long --optional=sage,optional,external src/sage/misc/latex.py
```
gives

```
Using --optional=debian,external,glucose,pip,sage,sage_spkg
Features to be detected: 4ti2,benzene,bliss,buckygen,conway_polynomials,cplex,csdp,database_cremona_ellcurve,database_cremona_mini_ellcurve,database_cubic_hecke,database_jones_numfield,database_knotinfo,dvipng,ffmpeg,gfan,graphviz,gurobi,imagemagick,internet,jupymake,kenzo,latex,latex_package_tkz_graph,latte_int,lrslib,lualatex,macaulay2,magma,maple,mathematica,matlab,mcqd,meataxe,msolve,nauty,octave,palp,pandoc,pdf2svg,pdflatex,pdftocairo,phitigra,plantri,polytopes_db,polytopes_db_4d,pynormaliz,python_igraph,rubiks,sage.combinat,sage.geometry.polyhedron,sage.graphs,sage.groups,sage.misc.cython,sage.plot,sage.rings.number_field,sage.rings.padics,sage.rings.real_double,sage.symbolic,sage_numerical_backends_coin,sagemath_doc_html,scilab,sphinx,tdlib,xelatex
Doctesting 1 file.
sage -t --long --random-seed=49715222464713506332792189876546973295 src/sage/misc/latex.py
**********************************************************************
File "src/sage/misc/latex.py", line 1859, in sage.misc.latex.?
Failed example:
    with NamedTemporaryFile(mode="w+t", suffix=".tex") as f:  # optional - latex latex_package_tkz_graph
        _ = f.write(_latex_file_(g))
        f.flush()
        _run_latex_(f, engine="pdflatex")
Exception raised:
    Traceback (most recent call last):
      File "/home/slabbe/GitBox/sage/src/sage/doctest/forker.py", line 695, in _run
        self.compile_and_execute(example, compiler, test.globs)
      File "/home/slabbe/GitBox/sage/src/sage/doctest/forker.py", line 1093, in compile_and_execute
        exec(compiled, globs)
      File "<doctest sage.misc.latex.?[4]>", line 4, in <module>
        _run_latex_(f, engine="pdflatex")
      File "/home/slabbe/GitBox/sage/src/sage/misc/latex.py", line 771, in _run_latex_
        base, filename = os.path.split(filename)
      File "/home/slabbe/GitBox/sage/local/var/lib/sage/venv-python3.10.5/lib/python3.10/posixpath.py", line 103, in split
        p = os.fspath(p)
    TypeError: expected str, bytes or os.PathLike object, not _TemporaryFileWrapper
**********************************************************************
1 item had failures:
   1 of  19 in sage.misc.latex.?
    [257 tests, 1 failure, 1.64 s]
----------------------------------------------------------------------
sage -t --long --random-seed=49715222464713506332792189876546973295 src/sage/misc/latex.py  # 1 doctest failed
----------------------------------------------------------------------
Total time for all tests: 1.8 seconds
    cpu time: 0.3 seconds
    cumulative wall time: 1.6 seconds
Features detected for doctesting: imagemagick,latex,latex_package_tkz_graph
pytest is not installed in the venv, skip checking tests that rely on it
```

**Comment by seblabbe** [comment]
Reviewer: **Sébastien Labbé**

**Comment by seblabbe** [comment]
Changed commit from **[`4b1d7cd`](https://github.com/sagemath/sagetrac-mirror/commit/4b1d7cd04a8bb8a40c7e1dd7cdc9de6d8c0ec014)** to **[`81ff989`](https://github.com/sagemath/sagetrac-mirror/commit/81ff989f53610b3c367a46e50ed046aa1cfe8f69)**

**Comment by seblabbe** [comment]
Changed branch from **[u/jhpalmieri/latex-error](https://github.com/sagemath/sagetrac-mirror/tree/u/jhpalmieri/latex-error)** to **[u/slabbe/34594](https://github.com/sagemath/sagetrac-mirror/tree/u/slabbe/34594)**

**Comment by seblabbe** [comment]
<div id="comment:4" align="right">comment:4</div>

`f.name` does the job

---
New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/81ff989f53610b3c367a46e50ed046aa1cfe8f69"><code>81ff989</code></a></td><td><code>34594: f -> f.name</code></td></tr></table>

**Comment by seblabbe** [comment]
Description changed:
``````diff
--- 
+++ 
@@ -1,2 +1,9 @@
+With 9.8.beta0, the command
+
+```
+sage -t --long --optional=sage,optional,external src/sage/misc/latex.py
+```
+gives error.
+
 Excerpted from #33931.
 
``````

**Comment by jhpalmieri** [comment]
<div id="comment:6" align="right">comment:6</div>

Yes, that's the right fix. Sorry I got it wrong.

**Comment by jhpalmieri** [comment]
Changed author from **John Palmieri** to **John Palmieri, Sébastien Labbé**

**Comment by jhpalmieri** [comment]
Changed reviewer from **Sébastien Labbé** to **Sébastien Labbé, John Palmieri**

**Comment by seblabbe** [comment]
<div id="comment:7" align="right">comment:7</div>

One patchbot shows issues with doc. The other not. I think the docbuild issue is unrelated to the current ticket.

**Comment by jhpalmieri** [comment]
<div id="comment:8" align="right">comment:8</div>

I agree.

**Comment by vbraun** [comment]
Changed branch from **[u/slabbe/34594](https://github.com/sagemath/sagetrac-mirror/tree/u/slabbe/34594)** to **[`81ff989`](https://github.com/sagemath/sagetrac-mirror/commit/81ff989f53610b3c367a46e50ed046aa1cfe8f69)**
