### ISSUE TITLE
Document and manage temporary directories

### ISSUE THREAD

**Issue by jhpalmieri** [sagemath/sage#34593]
<div id="comment:0"></div>

This is a followup to #33213. Some users prefer (or need) to control where temporary files are created, and we should document this:

- as described at https://docs.python.org/3/library/tempfile.html#tempfile.gettempdir, users can set the environment variable `TMPDIR`

Possible follow-up: 
- Also, according to https://manpages.ubuntu.com/manpages/bionic/man8/tmpreaper.8.html, at least on some systems it would be helpful to create a non-writable file `.tmpreaper` in the directory to prevent the system from doing automatic cleanup on it.

Component: **misc**

Author: **John Palmieri**

Branch/Commit: **[`c729c7b`](https://github.com/sagemath/sagetrac-mirror/commit/c729c7be2d426cd2ca54d47ba2e823eb25469efa)**

Reviewer: **Matthias Koeppe**

_Issue created by migration from https://trac.sagemath.org/ticket/34593_

**Comment by jhpalmieri** [comment]
<div id="comment:1" align="right">comment:1</div>

Of course I don't know *where* we should document this, since it's a Python feature which may be used in various components of Sage. I don't know the natural home for it.

**Comment by egourgoulhon** [comment]
<div id="comment:2" align="right">comment:2</div>

Regarding the ticket title, IMHO the objective should be more "manage" than "document" since 3D plots are badly broken in Sage 9.7 for (at least) Ubuntu 22.04 users with the default settings, as revealed by https://ask.sagemath.org/question/64192/temporary-html-files-location-in-sage-97/

**Comment by jhpalmieri** [comment]
<div id="comment:4" align="right">comment:4</div>

Should Sage itself set the environment variable `TMPDIR`? (If the user hasn't set it, I mean.)

**Comment by egourgoulhon** [comment]
<div id="comment:5" align="right">comment:5</div>

Replying to [John Palmieri](#comment%3A4):
> Should Sage itself set the environment variable `TMPDIR`? (If the user hasn't set it, I mean.)

This could a solution, for instance defining `TMPDIR` to be a subdirectory of `DOT_SAGE`. But there may be some undesirable effects, e.g. for Sage running on servers or [SageMathCell](../wiki/SageMathCell). Also would it be desirable/doable to clean that directory when the Sage session ends?

**Comment by jhpalmieri** [comment]
Description changed:
``````diff
--- 
+++ 
@@ -1,4 +1,4 @@
-This is a followup to #33212. Some users prefer (or need) to control where temporary files are created, and we should document this:
+This is a followup to #33213. Some users prefer (or need) to control where temporary files are created, and we should document this:
 
 - as described at https://docs.python.org/3/library/tempfile.html#tempfile.gettempdir, users can set the environment variable `TMPDIR`
 
``````

**Comment by dimpase** [comment]
<div id="comment:7" align="right">comment:7</div>

Replying to [Eric Gourgoulhon](#comment%3A5):
> Replying to [John Palmieri](#comment%3A4):
> > Should Sage itself set the environment variable `TMPDIR`? (If the user hasn't set it, I mean.)
> 
> This could a solution, for instance defining `TMPDIR` to be a subdirectory of `DOT_SAGE`. But there may be some undesirable effects, e.g. for Sage running on servers or [SageMathCell](../wiki/SageMathCell). Also would it be desirable/doable to clean that directory when the Sage session ends? 

I beleive that the cleanup is automatic, using Python's `atexit` callback.
https://docs.python.org/3/library/atexit.html

(there is of course always a chance of a segfault-like abnormal exit, which might leave
rubbish after itself:

```
The functions registered via this module are not called when the program is killed
by a signal not handled by Python, when a Python fatal internal error is detected,
or when os._exit() is called.
```

This is what we have in `src/misc/temporary_file.py`:

```python
import tempfile

import atexit

# Until tmp_dir() and tmp_filename() are removed, we use this directory
# as the parent for all temporary files & directories created by them.
# This lets us clean up after those two functions when sage exits normally
# using an atexit hook
TMP_DIR_FILENAME_BASE=tempfile.TemporaryDirectory()
atexit.register(lambda: TMP_DIR_FILENAME_BASE.cleanup())
```

**Comment by dimpase** [comment]
<div id="comment:8" align="right">comment:8</div>

In an environment such as [SageMathCell](../wiki/SageMathCell), I think one user runs many Sage instances, so one cannot clean anything on startup without risking to affect other instances.

**Comment by mkoeppe** [comment]
<div id="comment:9" align="right">comment:9</div>

Let's move the documentation of runtime environment variables, starting at "Sage uses the following environment variables when it runs:" https://doc.sagemath.org/html/en/installation/source.html  to the "Launching section" and add TMPDIR there (perhaps pointer to Python runtime environment variables)

**Comment by jhpalmieri** [comment]
<div id="comment:10" align="right">comment:10</div>

It's not just Sage, it's a general Jupyter problem. See https://github.com/ContinuumIO/anaconda-issues/issues/12891 and https://askubuntu.com/questions/1389798/how-to-correctly-configure-snapd-firefox-to-open-local-html-file-generated-by.

**Comment by jhpalmieri** [comment]
<div id="comment:11" align="right">comment:11</div>

And also https://github.com/jupyter/notebook/issues/4500.

**Comment by jhpalmieri** [comment]
Branch: **[u/jhpalmieri/document-TMPDIR](https://github.com/sagemath/sagetrac-mirror/tree/u/jhpalmieri/document-TMPDIR)**

**Comment by jhpalmieri** [comment]
Author: **John Palmieri**

**Comment by jhpalmieri** [comment]
<div id="comment:13" align="right">comment:13</div>

Here is an addition to the documentation.

---
New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/c729c7be2d426cd2ca54d47ba2e823eb25469efa"><code>c729c7b</code></a></td><td><code>trac 34593: document the variable TMPDIR.</code></td></tr></table>

**Comment by jhpalmieri** [comment]
Commit: **[`c729c7b`](https://github.com/sagemath/sagetrac-mirror/commit/c729c7be2d426cd2ca54d47ba2e823eb25469efa)**

**Comment by mkoeppe** [comment]
Reviewer: **Matthias Koeppe**

**Comment by mkoeppe** [comment]
Description changed:
``````diff
--- 
+++ 
@@ -2,5 +2,6 @@
 
 - as described at https://docs.python.org/3/library/tempfile.html#tempfile.gettempdir, users can set the environment variable `TMPDIR`
 
-Also, according to https://manpages.ubuntu.com/manpages/bionic/man8/tmpreaper.8.html, at least on some systems it would be helpful to create a non-writable file `.tmpreaper` in the directory to prevent the system from doing automatic cleanup on it.
+Possible follow-up: 
+- Also, according to https://manpages.ubuntu.com/manpages/bionic/man8/tmpreaper.8.html, at least on some systems it would be helpful to create a non-writable file `.tmpreaper` in the directory to prevent the system from doing automatic cleanup on it.
 
``````

**Comment by jhpalmieri** [comment]
<div id="comment:15" align="right">comment:15</div>

Thank you!

**Comment by vbraun** [comment]
Changed branch from **[u/jhpalmieri/document-TMPDIR](https://github.com/sagemath/sagetrac-mirror/tree/u/jhpalmieri/document-TMPDIR)** to **[`c729c7b`](https://github.com/sagemath/sagetrac-mirror/commit/c729c7be2d426cd2ca54d47ba2e823eb25469efa)**

**Comment by Eloitor** [comment]
SAGE_TMP is mentioned here too: https://wiki.sagemath.org/Tips
