### ISSUE TITLE
fix more W391

### ISSUE THREAD

**Issue by fchapoton** [sagemath/sage#34596]
<div id="comment:0"></div>

and a few other things:

- not using (object)

- some more precise asserts

Component: **refactoring**

Author: **Frédéric Chapoton**

Branch/Commit: **[`188910c`](https://github.com/sagemath/sagetrac-mirror/commit/188910c1fe03a8147bd1a038ab5e0383571eb2e6)**

Reviewer: **Martin Rubey**

_Issue created by migration from https://trac.sagemath.org/ticket/34596_

**Comment by fchapoton** [comment]
Commit: **[`86648c2`](https://github.com/sagemath/sagetrac-mirror/commit/86648c20cf995e80c9e092926611c75fe1a6cd03)**

**Comment by fchapoton** [comment]
<div id="comment:1"></div>

New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/86648c20cf995e80c9e092926611c75fe1a6cd03"><code>86648c2</code></a></td><td><code>some care for W391 (final empty lines) and a few other things</code></td></tr></table>

**Comment by fchapoton** [comment]
Branch: **[u/chapoton/34596](https://github.com/sagemath/sagetrac-mirror/tree/u/chapoton/34596)**

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
Changed commit from **[`86648c2`](https://github.com/sagemath/sagetrac-mirror/commit/86648c20cf995e80c9e092926611c75fe1a6cd03)** to **[`bb97cf1`](https://github.com/sagemath/sagetrac-mirror/commit/bb97cf10b64b78ca49b86e631e605c2d1eaef328)**

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
<div id="comment:2"></div>

Branch pushed to git repo; I updated commit sha1. New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/bb97cf10b64b78ca49b86e631e605c2d1eaef328"><code>bb97cf1</code></a></td><td><code>fix detail</code></td></tr></table>

**Comment by mantepse** [comment]
<div id="comment:3" align="right">comment:3</div>

Please do not modify stream.py right now, this might hold up the long chain of tickets fixing really evil bugs, culminating in #34552.

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
<div id="comment:4"></div>

Branch pushed to git repo; I updated commit sha1. This was a forced push. New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/188910c1fe03a8147bd1a038ab5e0383571eb2e6"><code>188910c</code></a></td><td><code>some care for W391 (final empty lines) and a few other things</code></td></tr></table>

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
Changed commit from **[`bb97cf1`](https://github.com/sagemath/sagetrac-mirror/commit/bb97cf10b64b78ca49b86e631e605c2d1eaef328)** to **[`188910c`](https://github.com/sagemath/sagetrac-mirror/commit/188910c1fe03a8147bd1a038ab5e0383571eb2e6)**

**Comment by fchapoton** [comment]
<div id="comment:5" align="right">comment:5</div>

ok, now not touching this file at all

**Comment by mantepse** [comment]
<div id="comment:6" align="right">comment:6</div>

In `dev_tools.py`, it is unclear why you do not replace object in the following line

```
    for obj in itertools.chain.from_iterable(expand_comma_separated_names(object)
                                             for object in objects):
```
(although I admit it is unclear to me, why you replace object at all)

**Comment by fchapoton** [comment]
<div id="comment:7" align="right">comment:7</div>

once done, we will be able to check that nobody uses the obsolete syntax `class C(object):` anymore.

**Comment by mantepse** [comment]
Reviewer: **Martin Rubey**

**Comment by mantepse** [comment]
<div id="comment:8" align="right">comment:8</div>

Thank you!

**Comment by vbraun** [comment]
Changed branch from **[u/chapoton/34596](https://github.com/sagemath/sagetrac-mirror/tree/u/chapoton/34596)** to **[`188910c`](https://github.com/sagemath/sagetrac-mirror/commit/188910c1fe03a8147bd1a038ab5e0383571eb2e6)**
