### ISSUE TITLE
latte_int: Fix up patch

### ISSUE THREAD

**Issue by mkoeppe** [sagemath/sage#34604]
<div id="comment:0"></div>

#33981 broke the `latte_int` package.

Related: https://github.com/latte-int/latte/issues/31

CC:  @kiwifb @jhpalmieri @dimpase

Component: **packages: optional**

Author: **Matthias Koeppe**

Branch/Commit: **[`c5202ea`](https://github.com/sagemath/sagetrac-mirror/commit/c5202ea6a09218ab24e5f35f423529dc91b08ed5)**

Reviewer: **François Bissey, John Palmieri**

_Issue created by migration from https://trac.sagemath.org/ticket/34604_

**Comment by mkoeppe** [comment]
Branch: **[u/mkoeppe/latte_int__fix_up_patch](https://github.com/sagemath/sagetrac-mirror/tree/u/mkoeppe/latte_int__fix_up_patch)**

**Comment by mkoeppe** [comment]
Author: **Matthias Koeppe**

**Comment by mkoeppe** [comment]
Commit: **[`c5202ea`](https://github.com/sagemath/sagetrac-mirror/commit/c5202ea6a09218ab24e5f35f423529dc91b08ed5)**

**Comment by mkoeppe** [comment]
<div id="comment:2"></div>

New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/c5202ea6a09218ab24e5f35f423529dc91b08ed5"><code>c5202ea</code></a></td><td><code>build/pkgs/latte_int/patches/6dbf7f07d5c9e1f3afe793f782d191d4465088ae.patch: Remove hunks for files not in the distribution</code></td></tr></table>

**Comment by mkoeppe** [comment]
Description changed:
``````diff
--- 
+++ 
@@ -1 +1,3 @@
 #33981 broke the `latte_int` package.
+
+Related: https://github.com/latte-int/latte/issues/31
``````

**Comment by jhpalmieri** [comment]
<div id="comment:3" align="right">comment:3</div>

On Apple M2 it builds and passes its test suite, and `sage/interfaces/latte.py` passes its tests with `--optional=latte_int,sage`, as does `sage/geometry`.

**Comment by kiwifb** [comment]
Reviewer: **François Bissey, John Palmieri**

**Comment by kiwifb** [comment]
<div id="comment:4" align="right">comment:4</div>

LGTM as the person who raised the github issue.

**Comment by mkoeppe** [comment]
<div id="comment:5" align="right">comment:5</div>

Thanks both!

**Comment by vbraun** [comment]
Changed branch from **[u/mkoeppe/latte_int__fix_up_patch](https://github.com/sagemath/sagetrac-mirror/tree/u/mkoeppe/latte_int__fix_up_patch)** to **[`c5202ea`](https://github.com/sagemath/sagetrac-mirror/commit/c5202ea6a09218ab24e5f35f423529dc91b08ed5)**
