### ISSUE TITLE
fix doc with respect to a change in behavior for tikz method of polyhedron (since 9.7 -> since 9.8)

### ISSUE THREAD

**Issue by seblabbe** [sagemath/sage#34606]
<div id="comment:0"></div>

because #33002 was merged in 9.8 not in 9.7

Component: **graphics**

Author: **Sébastien Labbé**

Branch/Commit: **[`103bcc4`](https://github.com/sagemath/sagetrac-mirror/commit/103bcc4fa4eec920ac65979906f90403e269a79e)**

Reviewer: **Matthias Koeppe**

_Issue created by migration from https://trac.sagemath.org/ticket/34606_

**Comment by seblabbe** [comment]
<div id="comment:1"></div>

New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/103bcc4fa4eec920ac65979906f90403e269a79e"><code>103bcc4</code></a></td><td><code>34606: Since version 9.7 -> Since version 9.8</code></td></tr></table>

**Comment by seblabbe** [comment]
Branch: **[u/slabbe/34606](https://github.com/sagemath/sagetrac-mirror/tree/u/slabbe/34606)**

**Comment by seblabbe** [comment]
Author: **Sébastien Labbé**

**Comment by seblabbe** [comment]
Commit: **[`103bcc4`](https://github.com/sagemath/sagetrac-mirror/commit/103bcc4fa4eec920ac65979906f90403e269a79e)**

**Comment by mkoeppe** [comment]
Reviewer: **Matthias Koeppe**

**Comment by vbraun** [comment]
Changed branch from **[u/slabbe/34606](https://github.com/sagemath/sagetrac-mirror/tree/u/slabbe/34606)** to **[`103bcc4`](https://github.com/sagemath/sagetrac-mirror/commit/103bcc4fa4eec920ac65979906f90403e269a79e)**
