### ISSUE TITLE
fix W391 in modules, tests and rings

### ISSUE THREAD

**Issue by fchapoton** [sagemath/sage#34601]
<div id="comment:0"></div>

with #34596, we are almost there

one file in rings is left aside for the moment

Component: **refactoring**

Author: **Frédéric Chapoton**

Branch/Commit: **[`d4eddec`](https://github.com/sagemath/sagetrac-mirror/commit/d4eddeceb082a2525d3dcacf09020ef444bf66c1)**

Reviewer: **Matthias Koeppe**

_Issue created by migration from https://trac.sagemath.org/ticket/34601_

**Comment by fchapoton** [comment]
Branch: **[u/chapoton/34601](https://github.com/sagemath/sagetrac-mirror/tree/u/chapoton/34601)**

**Comment by fchapoton** [comment]
<div id="comment:1"></div>

New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/d4eddeceb082a2525d3dcacf09020ef444bf66c1"><code>d4eddec</code></a></td><td><code>fix W391 in tests, modules, rings</code></td></tr></table>

**Comment by fchapoton** [comment]
Commit: **[`d4eddec`](https://github.com/sagemath/sagetrac-mirror/commit/d4eddeceb082a2525d3dcacf09020ef444bf66c1)**

**Comment by mkoeppe** [comment]
Reviewer: **Matthias Koeppe**

**Comment by vbraun** [comment]
Changed branch from **[u/chapoton/34601](https://github.com/sagemath/sagetrac-mirror/tree/u/chapoton/34601)** to **[`d4eddec`](https://github.com/sagemath/sagetrac-mirror/commit/d4eddeceb082a2525d3dcacf09020ef444bf66c1)**
