### ISSUE TITLE
2 doctests failures with external software octave

### ISSUE THREAD

**Issue by seblabbe** [sagemath/sage#34607]
<div id="comment:0"></div>

With 9.8.beta0, the command

```
sage -t --optional=sage,external src/sage/interfaces/octave.py
```

gives

```
Using --optional=external,sage
Features to be detected: 4ti2,benzene,bliss,buckygen,conway_polynomials,cplex,csdp,database_cremona_ellcurve,database_cremona_mini_ellcurve,database_cubic_hecke,database_jones_numfield,database_knotinfo,dvipng,ffmpeg,gfan,graphviz,gurobi,imagemagick,internet,jupymake,kenzo,latex,latex_package_tkz_graph,latte_int,lrslib,lualatex,macaulay2,magma,maple,mathematica,matlab,mcqd,meataxe,msolve,nauty,octave,palp,pandoc,pdf2svg,pdflatex,pdftocairo,phitigra,plantri,polytopes_db,polytopes_db_4d,pynormaliz,python_igraph,rubiks,sage.combinat,sage.geometry.polyhedron,sage.graphs,sage.groups,sage.misc.cython,sage.plot,sage.rings.number_field,sage.rings.padics,sage.rings.real_double,sage.symbolic,sage_numerical_backends_coin,sagemath_doc_html,scilab,sphinx,tdlib,xelatex
Doctesting 1 file.
sage -t --random-seed=300683574861759875953529709931492404030 src/sage/interfaces/octave.py
**********************************************************************
File "src/sage/interfaces/octave.py", line 159, in sage.interfaces.octave.Octave
Failed example:
    octave.eval("a = [ 1, 1, 2; 3, 5, 8; 13, 21, 33 ]")    # optional - octave
Expected:
    'a =\n\n 1 1 2\n 3 5 8\n 13 21 33\n'
Got:
    'a =\n\n 1 1 2\n 3 5 8\n 13 21 33\n\n'
**********************************************************************
File "src/sage/interfaces/octave.py", line 161, in sage.interfaces.octave.Octave
Failed example:
    octave.eval("b = [ 1; 3; 13]")                         # optional - octave
Expected:
    'b =\n\n 1\n 3\n 13\n'
Got:
    'b =\n\n 1\n 3\n 13\n\n'
**********************************************************************
1 item had failures:
   2 of   8 in sage.interfaces.octave.Octave
    [132 tests, 2 failures, 0.77 s]
----------------------------------------------------------------------
sage -t --random-seed=300683574861759875953529709931492404030 src/sage/interfaces/octave.py  # 2 doctests failed
----------------------------------------------------------------------
Total time for all tests: 0.9 seconds
    cpu time: 0.3 seconds
    cumulative wall time: 0.8 seconds
Features detected for doctesting: octave
```

The octave on the machine is:

```
$ octave --version
octave: X11 DISPLAY environment variable not set
octave: disabling GUI features
GNU Octave, version 4.2.2
Copyright (C) 2018 John W. Eaton and others.
This is free software; see the source code for copying conditions.
There is ABSOLUTELY NO WARRANTY; not even for MERCHANTABILITY or
FITNESS FOR A PARTICULAR PURPOSE.

Octave was configured for "x86_64-pc-linux-gnu".

Additional information about Octave is available at http://www.octave.org.

Please contribute if you find this software useful.
For more information, visit http://www.octave.org/get-involved.html

Read http://www.octave.org/bugs.html to learn how to submit bug reports.
```

A recent ticket also fixing octave doctests failures is #33093

CC:  @jhpalmieri

Component: **doctest coverage**

Author: **Sébastien Labbé**

Branch/Commit: **[`d46a7fc`](https://github.com/sagemath/sagetrac-mirror/commit/d46a7fcd462b84e3163dfd79b9a57d759148d448)**

Reviewer: **John Palmieri**

_Issue created by migration from https://trac.sagemath.org/ticket/34607_

**Comment by seblabbe** [comment]
<div id="comment:1" align="right">comment:1</div>

In #33093, I was using GNU Octave, version 5.2.0. Here, I am using another machine which uses GNU Octave, version 4.2.2.

GNU Octave, version 5.2.0 returns strings ending with `"\n"`.

GNU Octave, version 4.2.2 returns strings ending with `"\n\n"`.

Proposed solution: let's strip the strings. I will post a branch soon.

**Comment by seblabbe** [comment]
Commit: **[`d46a7fc`](https://github.com/sagemath/sagetrac-mirror/commit/d46a7fcd462b84e3163dfd79b9a57d759148d448)**

**Comment by seblabbe** [comment]
Branch: **[u/slabbe/34607](https://github.com/sagemath/sagetrac-mirror/tree/u/slabbe/34607)**

**Comment by seblabbe** [comment]
Author: **Sébastien Labbé**

**Comment by seblabbe** [comment]
<div id="comment:2"></div>

New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/d46a7fcd462b84e3163dfd79b9a57d759148d448"><code>d46a7fc</code></a></td><td><code>34607: more robust octave doctests</code></td></tr></table>

**Comment by seblabbe** [comment]
<div id="comment:3" align="right">comment:3</div>

I am trying to add John Palmieri in cc. Hopefully, my guess for his username "jpalmieri" is okay? Strangely, I can't find the username in the wiki page?

**Comment by jhpalmieri** [comment]
<div id="comment:5" align="right">comment:5</div>

This works for me, and it should work regardless of how many `\n`'s octave inserts at the end.

**Comment by jhpalmieri** [comment]
Reviewer: **John Palmieri**

**Comment by vbraun** [comment]
Changed branch from **[u/slabbe/34607](https://github.com/sagemath/sagetrac-mirror/tree/u/slabbe/34607)** to **[`d46a7fc`](https://github.com/sagemath/sagetrac-mirror/commit/d46a7fcd462b84e3163dfd79b9a57d759148d448)**
