### ISSUE TITLE
add some missing EXAMPLES

### ISSUE THREAD

**Issue by fchapoton** [sagemath/sage#34602]
<div id="comment:0"></div>

that apparently do not provoke any rst error

Component: **documentation**

Author: **Frédéric Chapoton**

Branch/Commit: **[`a052558`](https://github.com/sagemath/sagetrac-mirror/commit/a052558ad0ccd5afe3293c7457edaa1f0cb8b414)**

Reviewer: **Marc Mezzarobba**

_Issue created by migration from https://trac.sagemath.org/ticket/34602_

**Comment by fchapoton** [comment]
Branch: **[u/chapoton/34602](https://github.com/sagemath/sagetrac-mirror/tree/u/chapoton/34602)**

**Comment by fchapoton** [comment]
Commit: **[`a052558`](https://github.com/sagemath/sagetrac-mirror/commit/a052558ad0ccd5afe3293c7457edaa1f0cb8b414)**

**Comment by fchapoton** [comment]
<div id="comment:1"></div>

New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/a052558ad0ccd5afe3293c7457edaa1f0cb8b414"><code>a052558</code></a></td><td><code>add some missing EXAMPLES</code></td></tr></table>

**Comment by mezzarobba** [comment]
Reviewer: **Marc Mezzarobba**

**Comment by vbraun** [comment]
Changed branch from **[u/chapoton/34602](https://github.com/sagemath/sagetrac-mirror/tree/u/chapoton/34602)** to **[`a052558`](https://github.com/sagemath/sagetrac-mirror/commit/a052558ad0ccd5afe3293c7457edaa1f0cb8b414)**
