### ISSUE TITLE
add missing EllipticCurveHom methods to √élu isogenies

### ISSUE THREAD

**Issue by yyyyx4** [sagemath/sage#34614]
<div id="comment:0"></div>

The `EllipticCurveHom_velusqrt` class introduced in #34303 inherits from `EllipticCurveHom` (#32388, #32502), but it doesn't yet implement all of the required methods. In this patch, we add them.

Diff without the dependency: https://github.com/sagemath/sagetrac-mirror/compare/7326051742a0d16d0810121739a05573ace6fb82...8cb0f29aa2cd5be18506e1d65eac954481d1ec8a

Depends on #34410

CC:  @defeo @JohnCremona @tscrim @kwankyu

Component: **elliptic curves**

Author: **Lorenz Panny**

Branch/Commit: **[`8cb0f29`](https://github.com/sagemath/sagetrac-mirror/commit/8cb0f29aa2cd5be18506e1d65eac954481d1ec8a)**

Reviewer: **Travis Scrimshaw, Kwankyu Lee**

_Issue created by migration from https://trac.sagemath.org/ticket/34614_

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
Changed commit from **[`0a38cc5`](https://github.com/sagemath/sagetrac-mirror/commit/0a38cc59d94e429ae38b6a7fdf56362b28c1ea6e)** to **[`726f2db`](https://github.com/sagemath/sagetrac-mirror/commit/726f2dbc5ecf3792eabf917ee0ae3cefb238d180)**

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
<div id="comment:2"></div>

Branch pushed to git repo; I updated commit sha1. This was a forced push. New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/7a64e8c5df466eded570e5564474e8f261eadd46"><code>7a64e8c</code></a></td><td><code>Merge branch 'public/change_default_composition_for_elliptic_curve_isogenies'</code></td></tr><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/726f2dbc5ecf3792eabf917ee0ae3cefb238d180"><code>726f2db</code></a></td><td><code>add more EllipticCurveHom methods to EllipticCurveHom_velusqrt</code></td></tr></table>

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
<div id="comment:3"></div>

Branch pushed to git repo; I updated commit sha1. This was a forced push. New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/7326051742a0d16d0810121739a05573ace6fb82"><code>7326051</code></a></td><td><code>Merge tag '9.8.beta1' into public/change_default_composition_for_elliptic_curve_isogenies</code></td></tr><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/c6bbbc38d92468035a2d3d0bab9842a4defca7d4"><code>c6bbbc3</code></a></td><td><code>add more EllipticCurveHom methods to EllipticCurveHom_velusqrt</code></td></tr></table>

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
Changed commit from **[`726f2db`](https://github.com/sagemath/sagetrac-mirror/commit/726f2dbc5ecf3792eabf917ee0ae3cefb238d180)** to **[`c6bbbc3`](https://github.com/sagemath/sagetrac-mirror/commit/c6bbbc38d92468035a2d3d0bab9842a4defca7d4)**

**Comment by yyyyx4** [comment]
Description changed:
``````diff
--- 
+++ 
@@ -1 +1,3 @@
 The `EllipticCurveHom_velusqrt` class introduced in #34303 inherits from `EllipticCurveHom` (#32388, #32502), but it doesn't yet implement all of the required methods.
+
+Diff without the dependency: https://github.com/sagemath/sagetrac-mirror/compare/7326051742a0d16d0810121739a05573ace6fb82...c6bbbc38d92468035a2d3d0bab9842a4defca7d4
``````

**Comment by yyyyx4** [comment]
Description changed:
``````diff
--- 
+++ 
@@ -1,3 +1,3 @@
-The `EllipticCurveHom_velusqrt` class introduced in #34303 inherits from `EllipticCurveHom` (#32388, #32502), but it doesn't yet implement all of the required methods.
+The `EllipticCurveHom_velusqrt` class introduced in #34303 inherits from `EllipticCurveHom` (#32388, #32502), but it doesn't yet implement all of the required methods. In this patch, we add them.
 
 Diff without the dependency: https://github.com/sagemath/sagetrac-mirror/compare/7326051742a0d16d0810121739a05573ace6fb82...c6bbbc38d92468035a2d3d0bab9842a4defca7d4
``````

**Comment by tscrim** [comment]
<div id="comment:6" align="right">comment:6</div>

Code wise, basically looks good (although I would like the long doctest output lines broken up a little bit). Could someone check the math?

**Comment by tscrim** [comment]
Reviewer: **Travis Scrimshaw**

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
<div id="comment:7"></div>

Branch pushed to git repo; I updated commit sha1. New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/8e95731eaec4211fd8e08d7ef3799a4640e5c107"><code>8e95731</code></a></td><td><code>Minor edits mostly on spaces</code></td></tr><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/df1024d2b46e5a4d4af577ab215eae8dab7158ab"><code>df1024d</code></a></td><td><code>Move as_morphism()</code></td></tr></table>

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
Changed commit from **[`c6bbbc3`](https://github.com/sagemath/sagetrac-mirror/commit/c6bbbc38d92468035a2d3d0bab9842a4defca7d4)** to **[`df1024d`](https://github.com/sagemath/sagetrac-mirror/commit/df1024d2b46e5a4d4af577ab215eae8dab7158ab)**

**Comment by kwankyu** [comment]
<div id="comment:8" align="right">comment:8</div>

I made minor edits. 

I took this opportunity to move the method `as_morphism()` to the class `EllipticCurveHom` so that it works with √élu isogenies. The method may be useful to check elliptic curve morphisms, though it is reasonably fast only for small examples.

One remark: There are notes like 

```
    def rational_maps(self):
        r"""
        Return the pair of explicit rational maps of this √élu isogeny
        as fractions of bivariate polynomials in `x` and `y`.

        .. NOTE::

            The data returned by this method has size linear in the degree.

        EXAMPLES::  
```   
The meaning of the note is obscure to me. How is the size of the data measured? If the data is a polynomial, then it may mean "the degree of the returned polynomial is linear in the degree of the isogeny". In this case, the data is two rational functions. You need to be explicit about what is the "size" of rational functions. I suggest that you rewrite the notes or remove them (as they are, the notes are not so useful).

**Comment by yyyyx4** [comment]
<div id="comment:9" align="right">comment:9</div>

Replying to [Kwankyu Lee](#comment%3A8):
> How is the size of the data measured?

It's literally the size of the object, as in "bytes of memory it takes to store".

The purpose of these remarks is to point out that merely writing down the result of calling these methods already requires time `Ω(ℓ)`, which means the √élu speedup (complexity `Õ(√ℓ)`) cannot apply to them. Perhaps that point should be made clearer.

**Comment by kwankyu** [comment]
<div id="comment:10" align="right">comment:10</div>

Replying to [Lorenz Panny](#comment%3A9):
> Replying to [Kwankyu Lee](#comment%3A8):
> > How is the size of the data measured?
> 
> 
> It's literally the size of the object, as in "bytes of memory it takes to store".

Okay.

> The purpose of these remarks is to point out that merely writing down the result of calling these methods already requires time `Ω(ℓ)`, which means the √élu speedup (complexity `Õ(√ℓ)`) cannot apply to them. Perhaps that point should be made clearer.

I now see what you mean by the note. Then if you want to keep those notes, I suggest that you write this explanation (implication) for these notes, once and for all, at the head of the file `hom_velusqrt.py`. Non-experts need the explanation.

Otherwise I am positive to the branch.

**Comment by kwankyu** [comment]
Changed reviewer from **Travis Scrimshaw** to **Travis Scrimshaw, Kwankyu Lee**

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
<div id="comment:12"></div>

Branch pushed to git repo; I updated commit sha1. New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/8cb0f29aa2cd5be18506e1d65eac954481d1ec8a"><code>8cb0f29</code></a></td><td><code>explain "output has linear size" remarks</code></td></tr></table>

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
Changed commit from **[`df1024d`](https://github.com/sagemath/sagetrac-mirror/commit/df1024d2b46e5a4d4af577ab215eae8dab7158ab)** to **[`8cb0f29`](https://github.com/sagemath/sagetrac-mirror/commit/8cb0f29aa2cd5be18506e1d65eac954481d1ec8a)**

**Comment by yyyyx4** [comment]
<div id="comment:13" align="right">comment:13</div>

Thanks! I added a note about it as you suggested.

**Comment by kwankyu** [comment]
<div id="comment:14" align="right">comment:14</div>

Thank you!

**Comment by yyyyx4** [comment]
Description changed:
``````diff
--- 
+++ 
@@ -1,3 +1,3 @@
 The `EllipticCurveHom_velusqrt` class introduced in #34303 inherits from `EllipticCurveHom` (#32388, #32502), but it doesn't yet implement all of the required methods. In this patch, we add them.
 
-Diff without the dependency: https://github.com/sagemath/sagetrac-mirror/compare/7326051742a0d16d0810121739a05573ace6fb82...c6bbbc38d92468035a2d3d0bab9842a4defca7d4
+Diff without the dependency: https://github.com/sagemath/sagetrac-mirror/compare/7326051742a0d16d0810121739a05573ace6fb82...8cb0f29aa2cd5be18506e1d65eac954481d1ec8a
``````

**Comment by vbraun** [comment]
Changed branch from **[public/more_EllipticCurveHom_methods_for_EllipticCurveHom_velusqrt](https://github.com/sagemath/sagetrac-mirror/tree/public/more_EllipticCurveHom_methods_for_EllipticCurveHom_velusqrt)** to **[`8cb0f29`](https://github.com/sagemath/sagetrac-mirror/commit/8cb0f29aa2cd5be18506e1d65eac954481d1ec8a)**
