### ISSUE TITLE
use libgap in dual abelian group elements

### ISSUE THREAD

**Issue by fchapoton** [sagemath/sage#34618]
<div id="comment:0"></div>

instead of the pexpect interface for gap

CC:  @tscrim @kwankyu @kliem @slel

Component: **group theory**

Author: **Frédéric Chapoton**

Branch/Commit: **[`9ee09df`](https://github.com/sagemath/sagetrac-mirror/commit/9ee09dff6dbbf41b2c237a4a419995a6c6830ace)**

Reviewer: **Travis Scrimshaw**

_Issue created by migration from https://trac.sagemath.org/ticket/34618_

**Comment by fchapoton** [comment]
Commit: **[`79ce7d9`](https://github.com/sagemath/sagetrac-mirror/commit/79ce7d94e90fe60d96d5d233a26611700319efca)**

**Comment by fchapoton** [comment]
<div id="comment:1"></div>

New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/79ce7d94e90fe60d96d5d233a26611700319efca"><code>79ce7d9</code></a></td><td><code>use libgap in elements of dual abelian groups</code></td></tr></table>

**Comment by fchapoton** [comment]
Branch: **[u/chapoton/34618](https://github.com/sagemath/sagetrac-mirror/tree/u/chapoton/34618)**

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
Changed commit from **[`79ce7d9`](https://github.com/sagemath/sagetrac-mirror/commit/79ce7d94e90fe60d96d5d233a26611700319efca)** to **[`9ee09df`](https://github.com/sagemath/sagetrac-mirror/commit/9ee09dff6dbbf41b2c237a4a419995a6c6830ace)**

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
<div id="comment:2"></div>

Branch pushed to git repo; I updated commit sha1. New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/9ee09dff6dbbf41b2c237a4a419995a6c6830ace"><code>9ee09df</code></a></td><td><code>remove import</code></td></tr></table>

**Comment by fchapoton** [comment]
<div id="comment:3" align="right">comment:3</div>

morally green lights, so please review

**Comment by tscrim** [comment]
<div id="comment:4" align="right">comment:4</div>

LGTM.

**Comment by tscrim** [comment]
Reviewer: **Travis Scrimshaw**

**Comment by vbraun** [comment]
Changed branch from **[u/chapoton/34618](https://github.com/sagemath/sagetrac-mirror/tree/u/chapoton/34618)** to **[`9ee09df`](https://github.com/sagemath/sagetrac-mirror/commit/9ee09dff6dbbf41b2c237a4a419995a6c6830ace)**
