### ISSUE TITLE
fix some details in doc of charpoly_frobenius

### ISSUE THREAD

**Issue by fchapoton** [sagemath/sage#34619]
<div id="comment:0"></div>

and also pep8 standard for the code in this file

Component: **algebraic geometry**

Author: **Frédéric Chapoton**

Branch/Commit: **[`0e88192`](https://github.com/sagemath/sagetrac-mirror/commit/0e88192afda9bfd7c551276380bc2dd76feadbb8)**

Reviewer: **David Coudert**

_Issue created by migration from https://trac.sagemath.org/ticket/34619_

**Comment by fchapoton** [comment]
<div id="comment:1"></div>

New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/5b787492299e3eca7636abd43d4b5cf5e99847b0"><code>5b78749</code></a></td><td><code>fix some details in doc of charpoly_frobenius</code></td></tr></table>

**Comment by fchapoton** [comment]
Branch: **[u/chapoton/34619](https://github.com/sagemath/sagetrac-mirror/tree/u/chapoton/34619)**

**Comment by fchapoton** [comment]
Commit: **[`5b78749`](https://github.com/sagemath/sagetrac-mirror/commit/5b787492299e3eca7636abd43d4b5cf5e99847b0)**

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
<div id="comment:2"></div>

Branch pushed to git repo; I updated commit sha1. New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/402bec3604c2276639e17cbee27cc0a6e9c4abf6"><code>402bec3</code></a></td><td><code>fix a bunch of similar errors in the doc</code></td></tr></table>

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
Changed commit from **[`5b78749`](https://github.com/sagemath/sagetrac-mirror/commit/5b787492299e3eca7636abd43d4b5cf5e99847b0)** to **[`402bec3`](https://github.com/sagemath/sagetrac-mirror/commit/402bec3604c2276639e17cbee27cc0a6e9c4abf6)**

**Comment by dcoudert** [comment]
<div id="comment:3" align="right">comment:3</div>

this one is not correct

```diff
-        If the `primitive_root` does not lie in an extension of `field`,
+        If the ``primitive_root`̀  does not lie in an extension of ``field``,
```

The `.` should be outside

```diff
+or just through ``finite_dynamical_systems.``
```

**Comment by fchapoton** [comment]
<div id="comment:4" align="right">comment:4</div>

Merci pour les suggestions.

Je ne comprends pas ce qui n'est pas correct dans le premier point, et je ne suis pas d'accord avec le second point. On est en train de parler de complétion-par-tab, donc le point va avec le reste.

**Comment by dcoudert** [comment]
<div id="comment:5" align="right">comment:5</div>

C'est peut-être un problème d'affichage chez moi, mais je vois 2 <code>\`</code> l'un au dessus de l'autre: <code>\`̀</code>

<code>\`\`primitive_root\`̀</code> -> <code>\`\`primitive_root\`\`</code>

pour le 2e point, tu as raison, je n'avais pas fait attention au context.

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
Changed commit from **[`402bec3`](https://github.com/sagemath/sagetrac-mirror/commit/402bec3604c2276639e17cbee27cc0a6e9c4abf6)** to **[`0e88192`](https://github.com/sagemath/sagetrac-mirror/commit/0e88192afda9bfd7c551276380bc2dd76feadbb8)**

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
<div id="comment:6"></div>

Branch pushed to git repo; I updated commit sha1. New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/0e88192afda9bfd7c551276380bc2dd76feadbb8"><code>0e88192</code></a></td><td><code>fix one detail</code></td></tr></table>

**Comment by fchapoton** [comment]
<div id="comment:7" align="right">comment:7</div>

peut-être mieux maintenant ?

**Comment by dcoudert** [comment]
<div id="comment:8" align="right">comment:8</div>

oui.

LGTM

**Comment by dcoudert** [comment]
Reviewer: **David Coudert**

**Comment by vbraun** [comment]
Changed branch from **[u/chapoton/34619](https://github.com/sagemath/sagetrac-mirror/tree/u/chapoton/34619)** to **[`0e88192`](https://github.com/sagemath/sagetrac-mirror/commit/0e88192afda9bfd7c551276380bc2dd76feadbb8)**
