### ISSUE TITLE
1 internet doctest failing in graphs/isgci.py

### ISSUE THREAD

**Issue by seblabbe** [sagemath/sage#34612]
<div id="comment:0"></div>

With 9.8.beta0, the command

```
sage -t --optional=sage,internet src/sage/graphs/isgci.py
```
gives

```
sage -t --random-seed=77042496144687512046172744154893811378 src/sage/graphs/isgci.py
**********************************************************************
File "src/sage/graphs/isgci.py", line 871, in sage.graphs.isgci.GraphClasses.update_db
Failed example:
    graph_classes.update_db()  # optional - internet
Expected nothing
Got:
    Database downloaded
**********************************************************************
1 item had failures:
   1 of   2 in sage.graphs.isgci.GraphClasses.update_db
    [86 tests, 1 failure, 2.26 s]
----------------------------------------------------------------------
sage -t --random-seed=77042496144687512046172744154893811378 src/sage/graphs/isgci.py  # 1 doctest failed
----------------------------------------------------------------------
```

Component: **doctest coverage**

Author: **Sébastien Labbé**

Branch/Commit: **[`1ef60e4`](https://github.com/sagemath/sagetrac-mirror/commit/1ef60e42efa64f9971a7b4d88034e53add4aa076)**

Reviewer: **David Coudert**

_Issue created by migration from https://trac.sagemath.org/ticket/34612_

**Comment by seblabbe** [comment]
<div id="comment:1" align="right">comment:1</div>

Seems to come from a recent commit of David, maybe #34211:

```
$ git blame src/sage/graphs/isgci.py | grep downloaded -C3
b9669295447b (Jori Mäntysalo    2017-02-18 11:56:48 +0200  869)         EXAMPLES::
e3be127f3853 (Nathann Cohen     2012-03-06 18:35:23 +0100  870) 
2302af6f35af (dcoudert          2022-08-08 16:57:43 +0200  871)             sage: graph_classes.update_db()  # optional - internet
e3be127f3853 (Nathann Cohen     2012-03-06 18:35:23 +0100  873)         """
e3be127f3853 (Nathann Cohen     2012-03-06 18:35:23 +0100  874)         self._download_db()
e3be127f3853 (Nathann Cohen     2012-03-06 18:35:23 +0100  875) 
1b1f7a220368 (Frédéric Chapoton 2016-05-11 17:35:09 +0200  876)         print("Database downloaded")
e3be127f3853 (Nathann Cohen     2012-03-06 18:35:23 +0100  877) 
e3be127f3853 (Nathann Cohen     2012-03-06 18:35:23 +0100  878)         self.classes.clear_cache()
e3be127f3853 (Nathann Cohen     2012-03-06 18:35:23 +0100  879)         self.inclusions.clear_cache()

```

**Comment by seblabbe** [comment]
Commit: **[`1ef60e4`](https://github.com/sagemath/sagetrac-mirror/commit/1ef60e42efa64f9971a7b4d88034e53add4aa076)**

**Comment by seblabbe** [comment]
<div id="comment:2"></div>

New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/1ef60e42efa64f9971a7b4d88034e53add4aa076"><code>1ef60e4</code></a></td><td><code>34612: fix failing internet doctest</code></td></tr></table>

**Comment by seblabbe** [comment]
Branch: **[u/slabbe/34612](https://github.com/sagemath/sagetrac-mirror/tree/u/slabbe/34612)**

**Comment by seblabbe** [comment]
Author: **Sébastien Labbé**

**Comment by dcoudert** [comment]
<div id="comment:3" align="right">comment:3</div>

LGTM.

**Comment by dcoudert** [comment]
Reviewer: **David Coudert**

**Comment by vbraun** [comment]
Changed branch from **[u/slabbe/34612](https://github.com/sagemath/sagetrac-mirror/tree/u/slabbe/34612)** to **[`1ef60e4`](https://github.com/sagemath/sagetrac-mirror/commit/1ef60e42efa64f9971a7b4d88034e53add4aa076)**
