### ISSUE TITLE
fix and activate pycodestyle W391

### ISSUE THREAD

**Issue by fchapoton** [sagemath/sage#34617]
<div id="comment:0"></div>

Component: **refactoring**

Author: **Frédéric Chapoton**

Branch/Commit: **[`fba8e59`](https://github.com/sagemath/sagetrac-mirror/commit/fba8e59f23883da82998cfef87aa45b06eae6f1f)**

Reviewer: **Matthias Koeppe**

_Issue created by migration from https://trac.sagemath.org/ticket/34617_

**Comment by fchapoton** [comment]
<div id="comment:1"></div>

New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/fba8e59f23883da82998cfef87aa45b06eae6f1f"><code>fba8e59</code></a></td><td><code>fix and activate check of W391</code></td></tr></table>

**Comment by fchapoton** [comment]
Commit: **[`fba8e59`](https://github.com/sagemath/sagetrac-mirror/commit/fba8e59f23883da82998cfef87aa45b06eae6f1f)**

**Comment by fchapoton** [comment]
Branch: **[u/chapoton/34617](https://github.com/sagemath/sagetrac-mirror/tree/u/chapoton/34617)**

**Comment by mkoeppe** [comment]
Reviewer: **Matthias Koeppe**

**Comment by vbraun** [comment]
Changed branch from **[u/chapoton/34617](https://github.com/sagemath/sagetrac-mirror/tree/u/chapoton/34617)** to **[`fba8e59`](https://github.com/sagemath/sagetrac-mirror/commit/fba8e59f23883da82998cfef87aa45b06eae6f1f)**
