### ISSUE TITLE
fix typos in docstrings of lazy series

### ISSUE THREAD

**Issue by mantepse** [sagemath/sage#34610]
<div id="comment:0"></div>

Component: **PLEASE CHANGE**

Branch: **[u/mantepse/fix_typos_in_docstrings_of_lazy_series](https://github.com/sagemath/sagetrac-mirror/tree/u/mantepse/fix_typos_in_docstrings_of_lazy_series)**

_Issue created by migration from https://trac.sagemath.org/ticket/34610_

**Comment by mantepse** [comment]
Branch: **[u/mantepse/fix_typos_in_docstrings_of_lazy_series](https://github.com/sagemath/sagetrac-mirror/tree/u/mantepse/fix_typos_in_docstrings_of_lazy_series)**

**Comment by mantepse** [comment]
@DavidAyotte, did you check whether this is subsumed by your recent pull request?

**Comment by DavidAyotte** [comment]
No sorry, I did not know about this ticket. I'll compare the two branches. Thank you for notifying me about this.

**Comment by mantepse** [comment]
This has been taken care of in #35254.
