### ISSUE TITLE
Use the kbd role in the doc

### ISSUE THREAD

**Issue by fchapoton** [sagemath/sage#34629]
<div id="comment:0"></div>

in particular to represent the Tab key as can be seen already near the end of

https://doc.sagemath.org/html/en/installation/launching.html

CC:  @tscrim @kwankyu @kliem @slel

Component: **documentation**

Author: **Frédéric Chapoton, ​John Palmieri**

Branch/Commit: **[`a0e1d3b`](https://github.com/sagemath/sagetrac-mirror/commit/a0e1d3b434dee8b6c8659426b24cac43587b917f)**

Reviewer: **Kwankyu Lee**

_Issue created by migration from https://trac.sagemath.org/ticket/34629_

**Comment by fchapoton** [comment]
Commit: **[`75fa0fd`](https://github.com/sagemath/sagetrac-mirror/commit/75fa0fd06de3066a035d927c1e6eca2557daaa26)**

**Comment by fchapoton** [comment]
<div id="comment:1"></div>

New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/75fa0fd06de3066a035d927c1e6eca2557daaa26"><code>75fa0fd</code></a></td><td><code>using the :kbd: role in the documentation (for Tab and other keys)</code></td></tr></table>

**Comment by fchapoton** [comment]
Branch: **[u/chapoton/34629](https://github.com/sagemath/sagetrac-mirror/tree/u/chapoton/34629)**

**Comment by fchapoton** [comment]
Description changed:
``````diff
--- 
+++ 
@@ -1 +1,5 @@
 in particular to represent the Tab key
+
+as can be seen already near the end of
+
+https://doc.sagemath.org/html/en/installation/launching.html
``````

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
Changed commit from **[`75fa0fd`](https://github.com/sagemath/sagetrac-mirror/commit/75fa0fd06de3066a035d927c1e6eca2557daaa26)** to **[`fbf3083`](https://github.com/sagemath/sagetrac-mirror/commit/fbf30830a63cfc099a86f99b9db7adfc26c6b9dc)**

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
<div id="comment:3"></div>

Branch pushed to git repo; I updated commit sha1. New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/fbf30830a63cfc099a86f99b9db7adfc26c6b9dc"><code>fbf3083</code></a></td><td><code>a few more</code></td></tr></table>

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
<div id="comment:4"></div>

Branch pushed to git repo; I updated commit sha1. New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/78f9a47421039ac0905fe6391986f8d44e456c7e"><code>78f9a47</code></a></td><td><code>again a few more :kbd:</code></td></tr></table>

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
Changed commit from **[`fbf3083`](https://github.com/sagemath/sagetrac-mirror/commit/fbf30830a63cfc099a86f99b9db7adfc26c6b9dc)** to **[`78f9a47`](https://github.com/sagemath/sagetrac-mirror/commit/78f9a47421039ac0905fe6391986f8d44e456c7e)**

**Comment by jhpalmieri** [comment]
<div id="comment:5" align="right">comment:5</div>

I've found some more. Can I push some changes?

**Comment by jhpalmieri** [comment]
Changed branch from **[u/chapoton/34629](https://github.com/sagemath/sagetrac-mirror/tree/u/chapoton/34629)** to **[u/jhpalmieri/34629](https://github.com/sagemath/sagetrac-mirror/tree/u/jhpalmieri/34629)**

**Comment by fchapoton** [comment]
Changed commit from **[`78f9a47`](https://github.com/sagemath/sagetrac-mirror/commit/78f9a47421039ac0905fe6391986f8d44e456c7e)** to **[`045adfb`](https://github.com/sagemath/sagetrac-mirror/commit/045adfb17e8eb0f88644c3787efc9f68228e8a4c)**

**Comment by fchapoton** [comment]
<div id="comment:7" align="right">comment:7</div>

sure, please do. Typo in your commit

```
:kbd:`Tab` key key
```

in src/doc/en/tutorial/interactive_shell.rst

---
New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/045adfb17e8eb0f88644c3787efc9f68228e8a4c"><code>045adfb</code></a></td><td><code>trac 34629: more :kbd:</code></td></tr></table>

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
<div id="comment:8"></div>

Branch pushed to git repo; I updated commit sha1. This was a forced push. New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/3900ab7480f32ea4cff97b03f0279c2b6241c917"><code>3900ab7</code></a></td><td><code>trac 34629: more :kbd:</code></td></tr></table>

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
Changed commit from **[`045adfb`](https://github.com/sagemath/sagetrac-mirror/commit/045adfb17e8eb0f88644c3787efc9f68228e8a4c)** to **[`3900ab7`](https://github.com/sagemath/sagetrac-mirror/commit/3900ab7480f32ea4cff97b03f0279c2b6241c917)**

**Comment by jhpalmieri** [comment]
<div id="comment:9" align="right">comment:9</div>

Typo fixed, thank you for catching that.

**Comment by fchapoton** [comment]
<div id="comment:10" align="right">comment:10</div>

oh, this breaks our rst linter, for instance

```
sage/databases/sql_db.py:1263:1: RST304 Unknown interpreted text role "kbd".
```
so we need to add this role to some list somewhere. But where ?

**Comment by fchapoton** [comment]
<div id="comment:11" align="right">comment:11</div>

probably in src/tox.ini where there is a list "rst-roles"

**Comment by fchapoton** [comment]
<div id="comment:12" align="right">comment:12</div>

let's see

---
New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/a0e1d3b434dee8b6c8659426b24cac43587b917f"><code>a0e1d3b</code></a></td><td><code>adding kbd to authorized roles</code></td></tr></table>

**Comment by fchapoton** [comment]
Changed branch from **[u/jhpalmieri/34629](https://github.com/sagemath/sagetrac-mirror/tree/u/jhpalmieri/34629)** to **[u/chapoton/34629](https://github.com/sagemath/sagetrac-mirror/tree/u/chapoton/34629)**

**Comment by fchapoton** [comment]
Changed commit from **[`3900ab7`](https://github.com/sagemath/sagetrac-mirror/commit/3900ab7480f32ea4cff97b03f0279c2b6241c917)** to **[`a0e1d3b`](https://github.com/sagemath/sagetrac-mirror/commit/a0e1d3b434dee8b6c8659426b24cac43587b917f)**

**Comment by fchapoton** [comment]
<div id="comment:13" align="right">comment:13</div>

The linter is now happy. Let's wait for the rest of the reports.

**Comment by fchapoton** [comment]
<div id="comment:14" align="right">comment:14</div>

good. John, please set to positive if you agree.

**Comment by kwankyu** [comment]
<div id="comment:15" align="right">comment:15</div>

LGTM in code and in doc.

**Comment by kwankyu** [comment]
Reviewer: **Kwankyu Lee**

**Comment by kwankyu** [comment]
Changed author from **Frédéric Chapoton** to **Frédéric Chapoton, ​John Palmieri**

**Comment by kwankyu** [comment]
Description changed:
``````diff
--- 
+++ 
@@ -1,5 +1,3 @@
-in particular to represent the Tab key
-
-as can be seen already near the end of
+in particular to represent the Tab key as can be seen already near the end of
 
 https://doc.sagemath.org/html/en/installation/launching.html
``````

**Comment by vbraun** [comment]
Changed branch from **[u/chapoton/34629](https://github.com/sagemath/sagetrac-mirror/tree/u/chapoton/34629)** to **[`a0e1d3b`](https://github.com/sagemath/sagetrac-mirror/commit/a0e1d3b434dee8b6c8659426b24cac43587b917f)**
