### ISSUE TITLE
partial cleanup in partition.py

### ISSUE THREAD

**Issue by fchapoton** [sagemath/sage#34622]
<div id="comment:0"></div>

some pep8, some code details, one shorter doctest, standard errors, etc

also using formatted strings a little bit

and modern syntax for super()

CC:  @tscrim @kwankyu @dcoudert

Component: **combinatorics**

Author: **Frédéric Chapoton**

Branch/Commit: **[`f1da83e`](https://github.com/sagemath/sagetrac-mirror/commit/f1da83e82a0f03aea53d1e54075535b12d1bcc18)**

Reviewer: **Matthias Koeppe**

_Issue created by migration from https://trac.sagemath.org/ticket/34622_

**Comment by fchapoton** [comment]
<div id="comment:1"></div>

New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/f1da83e82a0f03aea53d1e54075535b12d1bcc18"><code>f1da83e</code></a></td><td><code>partial cleanup in partition.py</code></td></tr></table>

**Comment by fchapoton** [comment]
Commit: **[`f1da83e`](https://github.com/sagemath/sagetrac-mirror/commit/f1da83e82a0f03aea53d1e54075535b12d1bcc18)**

**Comment by fchapoton** [comment]
Branch: **[u/chapoton/34622](https://github.com/sagemath/sagetrac-mirror/tree/u/chapoton/34622)**

**Comment by fchapoton** [comment]
Description changed:
``````diff
--- 
+++ 
@@ -1 +1,5 @@
 some pep8, some code details, one shorter doctest, standard errors, etc
+
+also using formatted strings a little bit
+
+and modern syntax for super()
``````

**Comment by fchapoton** [comment]
<div id="comment:3" align="right">comment:3</div>

green lights, so please review

**Comment by mkoeppe** [comment]
Reviewer: **Matthias Koeppe**

**Comment by vbraun** [comment]
Changed branch from **[u/chapoton/34622](https://github.com/sagemath/sagetrac-mirror/tree/u/chapoton/34622)** to **[`f1da83e`](https://github.com/sagemath/sagetrac-mirror/commit/f1da83e82a0f03aea53d1e54075535b12d1bcc18)**
