### ISSUE TITLE
Refresh the file free_quadratic_module

### ISSUE THREAD

**Issue by fchapoton** [sagemath/sage#34625]
<div id="comment:0"></div>

Cleanup, doc formatting, remove commented code, etc.

CC:  @tscrim @kwankyu @kliem @slel

Component: **quadratic forms**

Author: **Frédéric Chapoton**

Branch/Commit: **[`561f669`](https://github.com/sagemath/sagetrac-mirror/commit/561f6694a3ae136e97e3f62b1e155cc0474f661d)**

Reviewer: **Matthias Koeppe, Kwankyu Lee**

_Issue created by migration from https://trac.sagemath.org/ticket/34625_

**Comment by fchapoton** [comment]
<div id="comment:1"></div>

New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/0a42b28ba21f19a98796873b821f662975cd008f"><code>0a42b28</code></a></td><td><code>refresh the file free_quadratic_module</code></td></tr></table>

**Comment by fchapoton** [comment]
Commit: **[`0a42b28`](https://github.com/sagemath/sagetrac-mirror/commit/0a42b28ba21f19a98796873b821f662975cd008f)**

**Comment by fchapoton** [comment]
Branch: **[u/chapoton/34625](https://github.com/sagemath/sagetrac-mirror/tree/u/chapoton/34625)**

**Comment by mkoeppe** [comment]
Reviewer: **Matthias Koeppe**

**Comment by mkoeppe** [comment]
<div id="comment:2" align="right">comment:2</div>


```
     EXAMPLES:
 
     Since this is an embedded vector subspace with echelonized basis,
-    the echelon_coordinates() and user coordinates() agree::
+    the :meth:`echelon_coordinates` and :meth:`user coordinates` agree::
 
```
This does not look like a valid method name.

Otherwise LGTM

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
<div id="comment:3"></div>

Branch pushed to git repo; I updated commit sha1. New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/5d42e9e680a10977e73dc3258d90a538fd16e56b"><code>5d42e9e</code></a></td><td><code>detail in free_quadratic_module</code></td></tr></table>

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
Changed commit from **[`0a42b28`](https://github.com/sagemath/sagetrac-mirror/commit/0a42b28ba21f19a98796873b821f662975cd008f)** to **[`5d42e9e`](https://github.com/sagemath/sagetrac-mirror/commit/5d42e9e680a10977e73dc3258d90a538fd16e56b)**

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
<div id="comment:4"></div>

Branch pushed to git repo; I updated commit sha1. This was a forced push. New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/156914a3dad38540e669fefe651247f5e46a3d00"><code>156914a</code></a></td><td><code>refresh the file free_quadratic_module</code></td></tr></table>

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
Changed commit from **[`5d42e9e`](https://github.com/sagemath/sagetrac-mirror/commit/5d42e9e680a10977e73dc3258d90a538fd16e56b)** to **[`156914a`](https://github.com/sagemath/sagetrac-mirror/commit/156914a3dad38540e669fefe651247f5e46a3d00)**

**Comment by fchapoton** [comment]
<div id="comment:5" align="right">comment:5</div>

ok, thanks, fixed now (I squashed the commits)

**Comment by fchapoton** [comment]
<div id="comment:6" align="right">comment:6</div>

green lights, so please review

**Comment by kwankyu** [comment]
Changed branch from **[u/chapoton/34625](https://github.com/sagemath/sagetrac-mirror/tree/u/chapoton/34625)** to **[u/klee/34625](https://github.com/sagemath/sagetrac-mirror/tree/u/klee/34625)**

**Comment by kwankyu** [comment]
Changed commit from **[`156914a`](https://github.com/sagemath/sagetrac-mirror/commit/156914a3dad38540e669fefe651247f5e46a3d00)** to **[`561f669`](https://github.com/sagemath/sagetrac-mirror/commit/561f6694a3ae136e97e3f62b1e155cc0474f661d)**

**Comment by kwankyu** [comment]
<div id="comment:8" align="right">comment:8</div>

Positive review modulo my edits

---
New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/561f6694a3ae136e97e3f62b1e155cc0474f661d"><code>561f669</code></a></td><td><code>More edits</code></td></tr></table>

**Comment by kwankyu** [comment]
Changed reviewer from **Matthias Koeppe** to **Matthias Koeppe, Kwankyu Lee**

**Comment by kwankyu** [comment]
Description changed:
``````diff
--- 
+++ 
@@ -1 +1 @@
-pep cleanup, doc formatting, remove commented code, etc
+Cleanup, doc formatting, remove commented code, etc.
``````

**Comment by fchapoton** [comment]
<div id="comment:10" align="right">comment:10</div>

thanks, lights are green, so I am setting to positive now

**Comment by kwankyu** [comment]
<div id="comment:11" align="right">comment:11</div>

Thanks.

**Comment by vbraun** [comment]
Changed branch from **[u/klee/34625](https://github.com/sagemath/sagetrac-mirror/tree/u/klee/34625)** to **[`561f669`](https://github.com/sagemath/sagetrac-mirror/commit/561f6694a3ae136e97e3f62b1e155cc0474f661d)**
