### ISSUE TITLE
pep cleanup for the file weyl_group.py

### ISSUE THREAD

**Issue by fchapoton** [sagemath/sage#34620]
<div id="comment:0"></div>

Component: **combinatorics**

Author: **Frédéric Chapoton**

Branch/Commit: **[`f83a25d`](https://github.com/sagemath/sagetrac-mirror/commit/f83a25d0400626a5561c76ec837e58abc8ac5262)**

Reviewer: **David Coudert**

_Issue created by migration from https://trac.sagemath.org/ticket/34620_

**Comment by fchapoton** [comment]
Commit: **[`f83a25d`](https://github.com/sagemath/sagetrac-mirror/commit/f83a25d0400626a5561c76ec837e58abc8ac5262)**

**Comment by fchapoton** [comment]
<div id="comment:1"></div>

New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/f83a25d0400626a5561c76ec837e58abc8ac5262"><code>f83a25d</code></a></td><td><code>pep cleanup for Weyl groups</code></td></tr></table>

**Comment by fchapoton** [comment]
Branch: **[u/chapoton/34620](https://github.com/sagemath/sagetrac-mirror/tree/u/chapoton/34620)**

**Comment by dcoudert** [comment]
<div id="comment:2" align="right">comment:2</div>

on the way you could change `"""` -> `r"""` where needed

**Comment by fchapoton** [comment]
<div id="comment:3" align="right">comment:3</div>

En principe, les fichiers `.py` passent maintenant tous par `sage --tox -e rst` et divers vérificateurs, qui détectent si il manque `r"""` quelque part. Donc normalement, ça ne manque plus nul part, sauf dans les fichiers `.pyx`.

**Comment by dcoudert** [comment]
<div id="comment:4" align="right">comment:4</div>

OK.

LGTM.

**Comment by dcoudert** [comment]
Reviewer: **David Coudert**

**Comment by vbraun** [comment]
Changed branch from **[u/chapoton/34620](https://github.com/sagemath/sagetrac-mirror/tree/u/chapoton/34620)** to **[`f83a25d`](https://github.com/sagemath/sagetrac-mirror/commit/f83a25d0400626a5561c76ec837e58abc8ac5262)**
