### ISSUE TITLE
Fix broken gitpod

### ISSUE THREAD

**Issue by mkoeppe** [sagemath/sage#34623]
<div id="comment:0"></div>

as reported in https://groups.google.com/g/sage-devel/c/JIiytzMsLCU

Here we 
- improve error handling in the gitpod initialization scripts that eliminates the guesswork when something goes wrong 
- fix a mistake in the system package information for conda

CC:  @soehms @dimpase @tobiasdiez

Component: **build**

Author: **Matthias Koeppe**

Branch/Commit: **[`8b1063c`](https://github.com/sagemath/sagetrac-mirror/commit/8b1063c23912dc4f6cc5b53f4c929f8f87148183)**

Reviewer: **Tobias Diez**

_Issue created by migration from https://trac.sagemath.org/ticket/34623_

**Comment by mkoeppe** [comment]
<div id="comment:1" align="right">comment:1</div>

The conda environment creation fails (`mamba env create ...`, see .gitpod.yml "init" task)

```
(base) gitpod@sagemath-sagetracmirror-6rgcwwh5cer:/workspace/sagetrac-mirror$ mamba env create --file src/environment-dev.yml --prefix venv
conda-forge/noarch                                   9.4MB @   3.0MB/s  3.2s
conda-forge/linux-64                                25.7MB @   4.4MB/s  6.0s


Looking for: ['compilers', 'make', 'm4', 'perl', 'python', 'tar', 'bc', 'pkg-config', 'appdirs', 'arb', 'boost-cpp', 'brial', 'bzip2', 'cddlib', 'cliquer', 'cmake', 'curl', 'distlib', 'ecl', 'eclib', 'ecm', 'fflas-ffpack', 'filelock', 'libflint', 'flintqs', 'fplll', 'freetype', 'bdw-gc', 'gengetopt', 'gf2x', 'gfan', 'fortran-compiler', 'giac', 'givaro', 'glpk', 'gmp', 'gsl', 'iml', 'lcalc', 'libatomic_ops', 'libbraiding', 'libffi', 'libgd', 'libhomfly', 'xz', 'libpng', 'linbox', 'lrcalc', 'm4ri', 'm4rie', 'mpc', 'mpfi', 'mpfr', 'nauty', 'ncurses', 'ninja', 'ntl', 'openblas', 'blas=2[build=openblas]', 'openssl', 'palp', 'pari=[build=*_pthread]', 'pari-elldata', 'pari-galdata', 'pari-galpol', 'pari-seadata', 'pari-galdata', 'pari-seadata-small', 'patch', 'pcre', 'pkg-config', 'planarity', 'ppl', 'primecount', 'primesieve', 'qhull', 'r', 'r-essentials', 'readline', 'rw', 'singular', 'sqlite', 'suitesparse', 'symmetrica', 'sympow', 'tachyon', 'toml', 'tox', 'virtualenv', 'xz', 'zeromq', 'zlib', 'zn_poly', 'autoconf', 'automake', 'libtool', 'alabaster', 'appnope', 'argon2-cffi', 'asttokens', 'attrs', 'babel', 'backcall', 'backports.zoneinfo', 'beautifulsoup4', 'beniget', 'bleach', 'certifi', 'cffi', 'charset-normalizer', 'sagemath-db-combinatorial-designs', 'sagemath-db-conway-polynomials', 'cppy', 'cvxopt', 'cycler', 'cypari2', 'cysignals', 'cython', 'python-dateutil', 'decorator', 'defusedxml', 'deprecation', 'docutils', 'editables', 'sagemath-db-elliptic-curves', 'entrypoints', 'executing', 'python-fastjsonschema', 'flit-core', 'fonttools', 'fpylll', 'furo', 'gap-defaults', 'gast', 'gmpy2', 'sagemath-db-graphs', 'hatchling', 'html5lib', 'idna', 'imagesize', 'importlib_metadata', 'importlib-resources', 'ipykernel', 'ipython', 'ipython_genutils', 'ipywidgets', 'jedi', 'jinja2', 'jmol', 'jsonschema', 'jupyter_client', 'jupyter_core', 'jupyter-jsmol', 'jupyter-packaging', 'jupyter_sphinx', 'jupyterlab_pygments', 'kiwisolver', 'python-lrcalc', 'markupsafe', 'mathjax', "matplotlib[version='>=3.5.1']", 'matplotlib-inline', 'maxima', 'memory-allocator', 'mistune', 'mpmath', 'nbclient', 'nbconvert', 'nbformat', 'nest-asyncio', 'networkx', 'notebook', 'numpy', 'packaging', 'pandocfilters', 'parso', 'pathspec', 'pexpect', 'pickleshare', 'pillow', 'pip', 'pkgconfig', 'platformdirs', 'pluggy', 'ply', 'poetry-core', 'sagemath-db-polytopes', 'pplpy', 'primecountpy', 'prometheus_client', 'prompt_toolkit', 'ptyprocess', 'pure_eval', 'py', 'pybind11', 'pycparser', 'pygments', 'pyparsing', 'pyrsistent', 'pythran', 'pytz', 'pytz-deprecation-shim', 'pyzmq', 'requests', 'rpy2', 'sagetex', 'scipy', 'send2trash', "setuptools[version='<64']", 'setuptools_scm', 'setuptools-scm-git-archive', 'simplegeneric', 'six', 'snowballstemmer', 'soupsieve', 'sphinx', 'sphinxcontrib-applehelp', 'sphinxcontrib-devhelp', 'sphinxcontrib-htmlhelp', 'sphinxcontrib-jsmath', 'sphinxcontrib-qthelp', 'sphinxcontrib-serializinghtml', 'sphinxcontrib-websupport', 'stack_data', 'sympy', 'terminado', 'threejs-sage=122', 'tinycss2', 'tomli', 'tomlkit', 'tornado', 'traitlets', 'typing_extensions', 'tzdata', 'tzlocal', 'urllib3', 'vcversioner', 'wcwidth', 'webencodings', 'wheel', 'widgetsnbextension', 'zipp', 'openssh', 'pycodestyle', 'esbonio', 'git']


Encountered problems while solving:
  - nothing provides requested setuptools-scm-git-archive

```

**Comment by mkoeppe** [comment]
Branch: **[u/mkoeppe/fix_broken_gitpod](https://github.com/sagemath/sagetrac-mirror/tree/u/mkoeppe/fix_broken_gitpod)**

**Comment by mkoeppe** [comment]
<div id="comment:3"></div>

New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/cc24ab15c305a6d28237e329521b8c4bbd8ba03f"><code>cc24ab1</code></a></td><td><code>.gitpod.yml: Stop when errors occur in the init/command scripts</code></td></tr></table>

**Comment by mkoeppe** [comment]
Commit: **[`cc24ab1`](https://github.com/sagemath/sagetrac-mirror/commit/cc24ab15c305a6d28237e329521b8c4bbd8ba03f)**

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
<div id="comment:4"></div>

Branch pushed to git repo; I updated commit sha1. This was a forced push. New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/ad3a0a7effc1acd7c5204086282ac10af95abb32"><code>ad3a0a7</code></a></td><td><code>.gitpod.yml: Stop when errors occur in the init/command scripts</code></td></tr></table>

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
Changed commit from **[`cc24ab1`](https://github.com/sagemath/sagetrac-mirror/commit/cc24ab15c305a6d28237e329521b8c4bbd8ba03f)** to **[`ad3a0a7`](https://github.com/sagemath/sagetrac-mirror/commit/ad3a0a7effc1acd7c5204086282ac10af95abb32)**

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
Changed commit from **[`ad3a0a7`](https://github.com/sagemath/sagetrac-mirror/commit/ad3a0a7effc1acd7c5204086282ac10af95abb32)** to **[`5e73805`](https://github.com/sagemath/sagetrac-mirror/commit/5e738059d8d59774b613192c30be05aa907c1fc7)**

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
<div id="comment:5"></div>

Branch pushed to git repo; I updated commit sha1. This was a forced push. New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/5e738059d8d59774b613192c30be05aa907c1fc7"><code>5e73805</code></a></td><td><code>.gitpod.yml: Stop when errors occur in the init/command scripts</code></td></tr></table>

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
Changed commit from **[`5e73805`](https://github.com/sagemath/sagetrac-mirror/commit/5e738059d8d59774b613192c30be05aa907c1fc7)** to **[`40e6f51`](https://github.com/sagemath/sagetrac-mirror/commit/40e6f517d74e0463bbc9b6d09462f4178e9a9c47)**

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
<div id="comment:6"></div>

Branch pushed to git repo; I updated commit sha1. This was a forced push. New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/40e6f517d74e0463bbc9b6d09462f4178e9a9c47"><code>40e6f51</code></a></td><td><code>.gitpod.yml: Stop when errors occur in the init/command scripts</code></td></tr></table>

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
Changed commit from **[`40e6f51`](https://github.com/sagemath/sagetrac-mirror/commit/40e6f517d74e0463bbc9b6d09462f4178e9a9c47)** to **[`2d8fdae`](https://github.com/sagemath/sagetrac-mirror/commit/2d8fdae102dcec3fa90cae39156a6aea90931c0f)**

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
<div id="comment:7"></div>

Branch pushed to git repo; I updated commit sha1. This was a forced push. New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/2d8fdae102dcec3fa90cae39156a6aea90931c0f"><code>2d8fdae</code></a></td><td><code>.gitpod.yml: Stop when errors occur in the init/command scripts</code></td></tr></table>

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
Changed commit from **[`2d8fdae`](https://github.com/sagemath/sagetrac-mirror/commit/2d8fdae102dcec3fa90cae39156a6aea90931c0f)** to **[`d1fcd37`](https://github.com/sagemath/sagetrac-mirror/commit/d1fcd37e784141b5181b5af7ccf0778804386dbb)**

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
<div id="comment:8"></div>

Branch pushed to git repo; I updated commit sha1. New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/d1fcd37e784141b5181b5af7ccf0778804386dbb"><code>d1fcd37</code></a></td><td><code>build/pkgs/setuptools_scm_git_archive/distros/conda.txt: Remove - not available in the conda-forge channel</code></td></tr></table>

**Comment by mkoeppe** [comment]
Description changed:
``````diff
--- 
+++ 
@@ -1 +1,6 @@
 as reported in https://groups.google.com/g/sage-devel/c/JIiytzMsLCU
+
+Here we 
+- improve error handling in the gitpod initialization scripts that eliminates the guesswork when something goes wrong 
+- fix a mistake in the system package information for conda
+
``````

**Comment by mkoeppe** [comment]
Author: **Matthias Koeppe**

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
Changed commit from **[`d1fcd37`](https://github.com/sagemath/sagetrac-mirror/commit/d1fcd37e784141b5181b5af7ccf0778804386dbb)** to **[`9f055b5`](https://github.com/sagemath/sagetrac-mirror/commit/9f055b5bc739a0a66caeb6e64acbb1a9dd09fd1b)**

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
<div id="comment:11"></div>

Branch pushed to git repo; I updated commit sha1. New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/9f055b5bc739a0a66caeb6e64acbb1a9dd09fd1b"><code>9f055b5</code></a></td><td><code>.gitpod-command.sh: Fix up</code></td></tr></table>

**Comment by tobiasdiez** [comment]
<div id="comment:12" align="right">comment:12</div>

Thanks for working on this.

> that eliminates the guesswork when something goes wrong 

Not sure what guesswork you mean, but the full logs can be found at https://gitpod.io/t/sagemath/sagetrac-mirror-1/prebuilds or directly in the browser if you trigger a prebuild using the magical url.

The logs (https://gitpod.io/t/sagemath/sagetrac-mirror-1/41eac415-6e5a-41a3-9175-ac2fc463d659) for this branch indicate the following error

```
The tasks executed in the prebuild returned a non-zero exit code. headless task failed: exit status 1
```
but I couldn't find which command triggered it.

Another remark: Not sure if we really want to blow up the root folder by the additional gitpod scripts. Given that they should strongly simplify once we move to github (no extra trac nor ssh treatment will be necessary), I would propose to keep them inline.

**Comment by mkoeppe** [comment]
<div id="comment:14" align="right">comment:14</div>

Replying to [Tobias Diez](#comment%3A12):
> Thanks for working on this.
> 
> > that eliminates the guesswork when something goes wrong 
> 
> 
> Not sure what guesswork you mean

The one in ​https://groups.google.com/g/sage-devel/c/JIiytzMsLCU trying to diagnose based on error messages of commands that ran even though an earlier command failed.

**Comment by mkoeppe** [comment]
<div id="comment:15" align="right">comment:15</div>

Replying to [Tobias Diez](#comment%3A12):
> I would propose to keep them inline.

I moved it to separate scripts so that there is proper error handling. Whatever the gitpod folks do with the scripts, normal error handling is not working.

**Comment by mkoeppe** [comment]
<div id="comment:16" align="right">comment:16</div>

Replying to [Tobias Diez](#comment%3A12):
> Given that they should strongly simplify once we move to github (no extra trac nor ssh treatment will be necessary)

Good point. I'll move that part to a separate script and see if I can keep the other things inline.

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
<div id="comment:17"></div>

Branch pushed to git repo; I updated commit sha1. New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/9b955c0965fbe2969543625e59093e7695ed9f01"><code>9b955c0</code></a></td><td><code>.gitpod-setup-trac-remote.sh: New, move other scripts back into .gitpod.yml, chained with &&</code></td></tr></table>

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
Changed commit from **[`9f055b5`](https://github.com/sagemath/sagetrac-mirror/commit/9f055b5bc739a0a66caeb6e64acbb1a9dd09fd1b)** to **[`9b955c0`](https://github.com/sagemath/sagetrac-mirror/commit/9b955c0965fbe2969543625e59093e7695ed9f01)**

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
<div id="comment:18"></div>

Branch pushed to git repo; I updated commit sha1. This was a forced push. New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/400b680e3f9e85aee5e79931e518e9af71483f18"><code>400b680</code></a></td><td><code>.gitpod-setup-trac-remote.sh: New, move other scripts back into .gitpod.yml, chained with &&</code></td></tr></table>

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
Changed commit from **[`9b955c0`](https://github.com/sagemath/sagetrac-mirror/commit/9b955c0965fbe2969543625e59093e7695ed9f01)** to **[`400b680`](https://github.com/sagemath/sagetrac-mirror/commit/400b680e3f9e85aee5e79931e518e9af71483f18)**

**Comment by mkoeppe** [comment]
<div id="comment:19" align="right">comment:19</div>

prebuild is still running but looking good

**Comment by mkoeppe** [comment]
<div id="comment:20" align="right">comment:20</div>

Replying to [Tobias Diez](#comment%3A12):
> the full logs can be found at https://gitpod.io/t/sagemath/sagetrac-mirror-1/prebuilds or directly in the browser if you trigger a prebuild using the magical url.

Sure, but a problem is that when starting the gitpod, the terminal did not have enough scrollback, so one could not see the first error.

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
Changed commit from **[`400b680`](https://github.com/sagemath/sagetrac-mirror/commit/400b680e3f9e85aee5e79931e518e9af71483f18)** to **[`8b1063c`](https://github.com/sagemath/sagetrac-mirror/commit/8b1063c23912dc4f6cc5b53f4c929f8f87148183)**

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
<div id="comment:21"></div>

Branch pushed to git repo; I updated commit sha1. New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/8b1063c23912dc4f6cc5b53f4c929f8f87148183"><code>8b1063c</code></a></td><td><code>.gitpod.yml: Fix up comment placement</code></td></tr></table>

**Comment by tobiasdiez** [comment]
<div id="comment:22" align="right">comment:22</div>

Thanks for the quick follow-up. Code looks good to me, gitpod prebuild and actual start are working now again. So good to go.

Could you please open an issue at the gitpod repo with your error handling problem. That should be fixed upstream.

**Comment by tobiasdiez** [comment]
Reviewer: **Tobias Diez**

**Comment by mkoeppe** [comment]
<div id="comment:23" align="right">comment:23</div>

Thanks!

**Comment by mkoeppe** [comment]
<div id="comment:24" align="right">comment:24</div>

I've opened https://github.com/gitpod-io/gitpod/issues/13508

**Comment by soehms** [comment]
<div id="comment:25" align="right">comment:25</div>

Thank you for fixing this immediately!

Just to understand why it worked in former versions: The error has been triggered by the presence of `build/pkgs/setuptools_scm_git_archive/distros/conda.txt` which has been introduced recently in #33613, right?

**Comment by mkoeppe** [comment]
<div id="comment:26" align="right">comment:26</div>

Yes, that's right. It's a mistake I made in that ticket - that conda package does exist, but only in the default channel, not in the conda-forge channel.

**Comment by soehms** [comment]
<div id="comment:27" align="right">comment:27</div>

Replying to [Matthias Köppe](#comment%3A26):
> Yes, that's right. It's a mistake I made in that ticket - that conda package does exist, but only in the default channel, not in the conda-forge channel. 

I see. Thanks!

**Comment by vbraun** [comment]
Changed branch from **[u/mkoeppe/fix_broken_gitpod](https://github.com/sagemath/sagetrac-mirror/tree/u/mkoeppe/fix_broken_gitpod)** to **[`8b1063c`](https://github.com/sagemath/sagetrac-mirror/commit/8b1063c23912dc4f6cc5b53f4c929f8f87148183)**
