### ISSUE TITLE
Add tensor_factors() method to TensorProductOfHighestWeightModules in quantum_group_gap

### ISSUE THREAD

**Issue by tscrim** [sagemath/sage#34635]
<div id="comment:0"></div>

This fails with `gap_packages` installed since #34393.

However, there is another failure for the submodules. I do not think subobjects of tensor products should have a tensor product structure.

CC:  @mkoeppe @fchapoton

Component: **algebra**

Keywords: **quantum group, representation**

Author: **Travis Scrimshaw**

Branch/Commit: **[`918c372`](https://github.com/sagemath/sagetrac-mirror/commit/918c372df0fe4f80e0c20ec4f1579e0ab61ca3e7)**

Reviewer: **Matthias Koeppe**

_Issue created by migration from https://trac.sagemath.org/ticket/34635_

**Comment by mkoeppe** [comment]
Replying to [ticket:34635 Travis Scrimshaw]:
> I do not think subobjects of tensor products should have a tensor product structure.

I disagree

But it should be documented

**Comment by tscrim** [comment]
<div id="comment:2" align="right">comment:2</div>

If I take `V (x) W` and the submodule `V (x) w` for some fixed `w \in W`, what is the tensor product structure on that? I don't see how to make sense of that.

**Comment by mkoeppe** [comment]
<div id="comment:3" align="right">comment:3</div>

What are the morphisms in the category of tensor products of modules?

**Comment by tscrim** [comment]
<div id="comment:4" align="right">comment:4</div>

There is no difference with modules. Are you trying to say that we should have the tensor factors of `V (x) w` be `V` and the span of `w`? That might work, but how would this work with the problem at hand, where we have an `A`-repr inside of `V (x) W`?

**Comment by tscrim** [comment]
<div id="comment:5" align="right">comment:5</div>

Replying to [Travis Scrimshaw](#comment%3A4):
> There is no difference with modules.

Let me elaborate slightly on this. I believe we agree that the tensor product of finite dimensional modules is equivalent to the category of modules (over a (commutative?) ring `R`). It just has a little extra information about how the module was constructed (which is important for things like graded modules and representations).

**Comment by dimpase** [comment]
<div id="comment:6" align="right">comment:6</div>

Anyhow, an optional package gap_packages ought to pass the doctests, and it does not at the moment. Can you at least silence these warnings?

**Comment by tscrim** [comment]
Commit: **[`918c372`](https://github.com/sagemath/sagetrac-mirror/commit/918c372df0fe4f80e0c20ec4f1579e0ab61ca3e7)**

**Comment by tscrim** [comment]
Branch: **[public/algebra/tensor_quantum_group-34635](https://github.com/sagemath/sagetrac-mirror/tree/public/algebra/tensor_quantum_group-34635)**

**Comment by tscrim** [comment]
Author: **Travis Scrimshaw**

**Comment by tscrim** [comment]
<div id="comment:7" align="right">comment:7</div>

Here is a version where I work around the submodules of tensor products thinking it is a tensor product: I weakened the category of the submodules.

---
New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/67340e2562ae00d5d822cbf017c391358b7712ef"><code>67340e2</code></a></td><td><code>Adding tensor_factors() to tensor product of quantum group modules.</code></td></tr><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/918c372df0fe4f80e0c20ec4f1579e0ab61ca3e7"><code>918c372</code></a></td><td><code>Changing the category of the submodule to get around subobjects of tensor products being in tensor products.</code></td></tr></table>

**Comment by mkoeppe** [comment]
<div id="comment:8" align="right">comment:8</div>

LGTM. Tests OK with `gap_packages` installed.

**Comment by mkoeppe** [comment]
Reviewer: **Matthias Koeppe**

**Comment by vbraun** [comment]
Changed branch from **[public/algebra/tensor_quantum_group-34635](https://github.com/sagemath/sagetrac-mirror/tree/public/algebra/tensor_quantum_group-34635)** to **[`918c372`](https://github.com/sagemath/sagetrac-mirror/commit/918c372df0fe4f80e0c20ec4f1579e0ab61ca3e7)**
