### ISSUE TITLE
pep8 and code details for ribbon_tableau

### ISSUE THREAD

**Issue by fchapoton** [sagemath/sage#34637]
<div id="comment:0"></div>

including one change about super

CC:  @tscrim @kwankyu @kliem @slel

Component: **combinatorics**

Author: **Frédéric Chapoton**

Branch/Commit: **[`c58f3f0`](https://github.com/sagemath/sagetrac-mirror/commit/c58f3f0ac1a934e59682bdc464e655f1a2198bb5)**

Reviewer: **Travis Scrimshaw**

_Issue created by migration from https://trac.sagemath.org/ticket/34637_

**Comment by fchapoton** [comment]
Commit: **[`6fec49a`](https://github.com/sagemath/sagetrac-mirror/commit/6fec49af9b5fc2e916a87984f9f77984892a1e14)**

**Comment by fchapoton** [comment]
Branch: **[u/chapoton/34637](https://github.com/sagemath/sagetrac-mirror/tree/u/chapoton/34637)**

**Comment by fchapoton** [comment]
<div id="comment:1"></div>

New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/6fec49af9b5fc2e916a87984f9f77984892a1e14"><code>6fec49a</code></a></td><td><code>pep8 for ribbon_tableau</code></td></tr></table>

**Comment by fchapoton** [comment]
<div id="comment:2" align="right">comment:2</div>

lights and bot are morally green, so please review

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
<div id="comment:3"></div>

Branch pushed to git repo; I updated commit sha1. New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/e76b77aa21ac863922db119572e0eb4868f5e086"><code>e76b77a</code></a></td><td><code>one more detail about super</code></td></tr></table>

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
Changed commit from **[`6fec49a`](https://github.com/sagemath/sagetrac-mirror/commit/6fec49af9b5fc2e916a87984f9f77984892a1e14)** to **[`e76b77a`](https://github.com/sagemath/sagetrac-mirror/commit/e76b77aa21ac863922db119572e0eb4868f5e086)**

**Comment by mkoeppe** [comment]
<div id="comment:4" align="right">comment:4</div>

Not sure if this change for the nested loops is an improvement.

```
-    ## Test if the current nodes drive us to new solutions
+    # Test if the current nodes drive us to new solutions
     if nexts:
-        res = []
-        for i in range(len(current)):
-            for j in range(len(nexts[i])):
-                res.append( insertion_tableau(part, current[i][1], len(weight), nexts[i][j], length) )
-        return res
-    else:
-        ## The current nodes are at the bottom of the tree
-        res = []
-        for i in range(len(current)):
-            res.append( insertion_tableau(part, current[i][1], len(weight), [[],[]], length) )
-        return res
+        return [insertion_tableau(part, curr_i[1], len(weight),
+                                  nexts_ij, length)
+                for nexts_i, curr_i in zip(nexts, current)
+                for nexts_ij in nexts_i]
+
+    # The current nodes are at the bottom of the tree
+    return [insertion_tableau(part, curr_i[1],
+                              len(weight), [[], []], length)
+            for curr_i in current]
```

**Comment by mkoeppe** [comment]
<div id="comment:5" align="right">comment:5</div>

I'd think that rewriting it either as 

```
        res = []
        for i in range(len(current)):
            res.extend(.... for ....)
```
or using `yield` would be better

**Comment by fchapoton** [comment]
<div id="comment:6" align="right">comment:6</div>

Replying to [Matthias Köppe](#comment%3A4):
> Not sure if this change for the nested loops is an improvement.

Why not ? This seems more pythonic to me.

**Comment by mkoeppe** [comment]
<div id="comment:7" align="right">comment:7</div>

Maybe it's just me, but I always have to look twice to see which is the inner loop in such as list comprehension with multiple `for` clauses

**Comment by tscrim** [comment]
<div id="comment:8" align="right">comment:8</div>

It took me a moment to get used to nested loops. Then I realized (and because I got errors) that languages are iterative, so it is always first-come-first-loop. I agree with Frédéric that it is more Pythonic; it is also faster too.

That method also explicitly has `list`, so it cannot be an iterator (although having something that returns an iterator would be nice, but doesn’t need to be done here).

I also find this change (and similar) looks weird:

```diff
-#####################
-# Ribbon Tableaux   #
-#####################
+# ####################
+# Ribbon Tableaux    #
+# ####################
```
Could we make an exception here?

**Comment by fchapoton** [comment]
<div id="comment:9" align="right">comment:9</div>

Well, this stuff about not starting comments with `##` is part of the pep8 standard. As we are currently not checking this with our linters, I can undo if you insist,

**Comment by tscrim** [comment]
<div id="comment:10" align="right">comment:10</div>

It just looks really weird here, that's all. The `###` line isn't really a comment, just boxing an identifier. PEP8 doesn't make any statement regarding dividers/boxing/etc.

**Comment by kwankyu** [comment]
<div id="comment:11" align="right">comment:11</div>

Replying to [Travis Scrimshaw](#comment%3A10):
> It just looks really weird here, that's all. The `###` line isn't really a comment, just boxing an identifier. PEP8 doesn't make any statement regarding dividers/boxing/etc.

I agree. We should leave it as it is.

On the other hand, I hope that we adopt an official style on the "boxing". Different authors are using different styles on those "title comments". I would suggest

```
#
# Ribbon Tableaux
#
```
But again this would be another issue for a vote (or no vote)...

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
<div id="comment:12"></div>

Branch pushed to git repo; I updated commit sha1. New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/c58f3f0ac1a934e59682bdc464e655f1a2198bb5"><code>c58f3f0</code></a></td><td><code>aesthetic commit</code></td></tr></table>

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
Changed commit from **[`e76b77a`](https://github.com/sagemath/sagetrac-mirror/commit/e76b77aa21ac863922db119572e0eb4868f5e086)** to **[`c58f3f0`](https://github.com/sagemath/sagetrac-mirror/commit/c58f3f0ac1a934e59682bdc464e655f1a2198bb5)**

**Comment by fchapoton** [comment]
<div id="comment:13" align="right">comment:13</div>

ok, guys. Is my last commit nice enough for you ?

Otherwise, I can do unicode boxes

```
# ┏━━━━━━━━━━━━━━━━━━━┓
# ┃  Ribbon Tableaux  ┃
# ┗━━━━━━━━━━━━━━━━━━━┛
```

**Comment by tscrim** [comment]
<div id="comment:14" align="right">comment:14</div>

I prefer this over unicode (which doesn't always display properly on my editor).

Thank you.

**Comment by tscrim** [comment]
Reviewer: **Travis Scrimshaw**

**Comment by vbraun** [comment]
Changed branch from **[u/chapoton/34637](https://github.com/sagemath/sagetrac-mirror/tree/u/chapoton/34637)** to **[`c58f3f0`](https://github.com/sagemath/sagetrac-mirror/commit/c58f3f0ac1a934e59682bdc464e655f1a2198bb5)**
