### ISSUE TITLE
wrappers for acb_poly_[rl]gamma_series

### ISSUE THREAD

**Issue by mezzarobba** [sagemath/sage#34632]
<div id="comment:0"></div>

Component: **numerical**

Author: **Marc Mezzarobba**

Branch/Commit: **[`cd0fb01`](https://github.com/sagemath/sagetrac-mirror/commit/cd0fb01afe3d90a12b09a81d5db5dff5d72cb5a4)**

Reviewer: **Frédéric Chapoton**

_Issue created by migration from https://trac.sagemath.org/ticket/34632_

**Comment by mezzarobba** [comment]
Commit: **[`cd0fb01`](https://github.com/sagemath/sagetrac-mirror/commit/cd0fb01afe3d90a12b09a81d5db5dff5d72cb5a4)**

**Comment by mezzarobba** [comment]
<div id="comment:1"></div>

New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/cd0fb01afe3d90a12b09a81d5db5dff5d72cb5a4"><code>cd0fb01</code></a></td><td><code>#34632 wrappers for acb_poly_[rl]gamma_series</code></td></tr></table>

**Comment by mezzarobba** [comment]
Branch: **[u/mmezzarobba/34632-acb_poly_lrgamma_series](https://github.com/sagemath/sagetrac-mirror/tree/u/mmezzarobba/34632-acb_poly_lrgamma_series)**

**Comment by fchapoton** [comment]
<div id="comment:2" align="right">comment:2</div>

ok, feu vert

**Comment by fchapoton** [comment]
Reviewer: **Frédéric Chapoton**

**Comment by mezzarobba** [comment]
<div id="comment:3" align="right">comment:3</div>

merci !

**Comment by vbraun** [comment]
Changed branch from **[u/mmezzarobba/34632-acb_poly_lrgamma_series](https://github.com/sagemath/sagetrac-mirror/tree/u/mmezzarobba/34632-acb_poly_lrgamma_series)** to **[`cd0fb01`](https://github.com/sagemath/sagetrac-mirror/commit/cd0fb01afe3d90a12b09a81d5db5dff5d72cb5a4)**
