### ISSUE TITLE
make sparsity a decision of the user

### ISSUE THREAD

**Issue by mantepse** [sagemath/sage#34636]
<div id="comment:0"></div>

The decision whether a Stream_XXX class uses a dense or a sparse cache should not depend on the input streams.

For example, for `Stream_add` it is actually irrelevant whether the input streams left and right are dense or sparse.

For `Stream_zero` and `Stream_exact`, a separate cache never makes sense.

This also makes the need to implement a conversion between sparse and dense less important.

Depends on #34552
Depends on #34653

CC:  @tscrim @fchapoton

Component: **combinatorics**

Keywords: **LazyPowerSeries**

Author: **Martin Rubey**

Branch/Commit: **[`de424bd`](https://github.com/sagemath/sagetrac-mirror/commit/de424bd78aab5b7e151316644ad460b39261734f)**

Reviewer: **Travis Scrimshaw**

_Issue created by migration from https://trac.sagemath.org/ticket/34636_

**Comment by mantepse** [comment]
Branch: **[u/mantepse/make_sparsity_a_decision_of_the_user](https://github.com/sagemath/sagetrac-mirror/tree/u/mantepse/make_sparsity_a_decision_of_the_user)**

**Comment by mantepse** [comment]
Changed keywords from none to **LazyPowerSeries**

**Comment by mantepse** [comment]
Author: **Martin Rubey**

**Comment by mantepse** [comment]
Description changed:
``````diff
--- 
+++ 
@@ -1 +1,7 @@
+The decision whether a Stream_XXX class uses a dense or a sparse cache should not depend on the input streams.
 
+For example, for `Stream_add` it is actually irrelevant whether the input streams left and right are dense or sparse.
+
+For `Stream_zero` and `Stream_exact`, a separate cache never makes sense.
+
+This also makes the need to implement a conversion between sparse and dense less important.
``````

**Comment by mantepse** [comment]
Commit: **[`bd3e3eb`](https://github.com/sagemath/sagetrac-mirror/commit/bd3e3ebf0d7b707b9b03ab42ee7e7c71a28df782)**

**Comment by mantepse** [comment]
<div id="comment:2"></div>

Last 10 new commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/41ca99b7bfee0c11c4ece0bffa0b9230a7b4f67b"><code>41ca99b</code></a></td><td><code>Merge branch 'u/mantepse/replace_lazy_power_series-32367' of trac.sagemath.org:sage into t/34470/categories_lazy_series-34470</code></td></tr><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/fb3a5cdb6745cb78983f6bf5fc88bef93f21040a"><code>fb3a5cd</code></a></td><td><code>Merge branch 'u/mantepse/categories_lazy_series-34470' of trac.sagemath.org:sage into t/34552/lazy_series_test_suite-34552</code></td></tr><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/855d2bf04aaebfc1696e34664b48521bffd6a79f"><code>855d2bf</code></a></td><td><code>remove unused variable</code></td></tr><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/75c275cf989059c02bf5bd11ad7ed0ba76b3ca5f"><code>75c275c</code></a></td><td><code>add documentation and doctests for _approximate_order</code></td></tr><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/539324204ae876de4292c469eed336d8b6ee0f4a"><code>5393242</code></a></td><td><code>fixes for pycodestyle and pyflakes</code></td></tr><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/67dff95676c5e40b6311785db4db3e53347b11c5"><code>67dff95</code></a></td><td><code>Merge branch 'develop' of trac.sagemath.org:sage into t/32367/replace_lazy_power_series-32367</code></td></tr><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/4fc981b458f8d628684decf221618911ace06333"><code>4fc981b</code></a></td><td><code>fix for pyflakes and blocks</code></td></tr><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/56cef070ebee69841f1ead61344557d10d0b56a0"><code>56cef07</code></a></td><td><code>Merge branch 'u/mantepse/replace_lazy_power_series-32367' of trac.sagemath.org:sage into t/34470/categories_lazy_series-34470</code></td></tr><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/3e84c90c8c9c3d74c8dd2b6b328029d74144b7bc"><code>3e84c90</code></a></td><td><code>Merge branch 'u/mantepse/categories_lazy_series-34470' of trac.sagemath.org:sage into t/34552/lazy_series_test_suite-34552</code></td></tr><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/bd3e3ebf0d7b707b9b03ab42ee7e7c71a28df782"><code>bd3e3eb</code></a></td><td><code>make sparsity a decision of the user</code></td></tr></table>

**Comment by mantepse** [comment]
Dependencies: **#34552**

**Comment by mantepse** [comment]
<div id="comment:4" align="right">comment:4</div>

A sparse representation does not make sense also for `Cauchy_invert`: `get_coefficient` accesses all previously computed values.

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
Changed commit from **[`bd3e3eb`](https://github.com/sagemath/sagetrac-mirror/commit/bd3e3ebf0d7b707b9b03ab42ee7e7c71a28df782)** to **[`814aa7c`](https://github.com/sagemath/sagetrac-mirror/commit/814aa7cd53e8ca569ddfd87ba1cfa498c564531d)**

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
<div id="comment:5"></div>

Branch pushed to git repo; I updated commit sha1. New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/814aa7cd53e8ca569ddfd87ba1cfa498c564531d"><code>814aa7c</code></a></td><td><code>remove Stream_cauchy_invert.get_coefficient, make sparse a mandatory argument, move _is_sparse an attribute of Stream_inexact</code></td></tr></table>

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
<div id="comment:6"></div>

Branch pushed to git repo; I updated commit sha1. New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/7043d1cf5d937c3f947634c088e8bdc2c13e4d9f"><code>7043d1c</code></a></td><td><code>remove redundant `__init__` methods, remove finished TODOs</code></td></tr></table>

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
Changed commit from **[`814aa7c`](https://github.com/sagemath/sagetrac-mirror/commit/814aa7cd53e8ca569ddfd87ba1cfa498c564531d)** to **[`7043d1c`](https://github.com/sagemath/sagetrac-mirror/commit/7043d1cf5d937c3f947634c088e8bdc2c13e4d9f)**

**Comment by mantepse** [comment]
<div id="comment:8" align="right">comment:8</div>

From #34611: it may make sense to make `Stream_uninitialized` always dense, and doctest that the following then works:

```
sage: L.<z> = LazyPowerSeriesRing(ZZ); C = L.undefined(); C.define(1 + z*C^2)
sage: C[500]
```

Another question: it may make sense to make `Stream_XXX` always sparse, if the computation of `s[n]` *obviously* does not benefit from the values of `s[n-1], s[n-2], ...`.  This is the case, for example, with `Stream_add`.

The benefit of a dense representation of `Stream_add` may be in storage and access: if we have a sparse representation and have to compute most values, the list representation uses (much) less memory, and access will be faster. For example, storing the first 600 values of a stream of integers as a list uses no more memory than storing 200 values in a dict.  Lookup in a list of about 1000 elements seems to take about 60%-70% of the time lookup in a dictionary takes.

In cases when we apply a very simple function to each coefficient, as in `Stream_neg`, we may not want to create a separate cache at all.  For `Stream_map_coefficients`, we currently only apply very costly functions.

**Comment by tscrim** [comment]
<div id="comment:9" align="right">comment:9</div>

I am wondering how much we even want the sparsity in the streams. We want it for the exact series in some cases (sparse versus dense for the (Laurent) polynomial ring), but it seems more like extra weight we are carrying around for the streams, which should instead simply be as dense or sparse as is most effective for them. Or maybe just for multiplication, which might be the only one that could matter? Do you remember if in any place we take advantage of the dense or sparse implementation currently?

**Comment by mantepse** [comment]
<div id="comment:10" align="right">comment:10</div>

I don't think we can decide for the user.  For multiplication it makes a big difference, whether you are only interested in `(f*g)[10000]` or in `(f*g)[:10000]`.  The former may be relevant, if you want to compute a few random coefficients, e.g., to quickly see how much they grow.  But I admit that I do not know any serious application.

Exact series are neither sparse nor dense in the sense of `Stream`, they implement their own (mixed) cache: an index and a list for the initial coefficients, and an index and a constant for the rest.

I am not completely sure whether I understand your question.  I think that `Stream_mul`, `Stream_cauchy_compose` and the like should have sparse and dense versions. `Stream_uninitialized` probably only a dense version, `Stream_add`, `Stream_sub`, etc. possibly only a sparse version.

The only two reasons for `Stream_add` etc. to have a dense version is, if the speedup in access and the memory overhead matter.  There is no additional code.  So I guess it is better to keep the option.  We currently only use subtraction, implicitly in `LazySymmetricFunction.revert`:

```
        g = P.undefined(valuation=1)
        g.define(b_inv * (X - (self - b * X)(g)))
```
I am guessing (but I am not sure) that it makes sense to use either only the sparse versions or only the dense versions of the operations here.

**Comment by tscrim** [comment]
<div id="comment:11" align="right">comment:11</div>

You’re right; for multiplication, we should have both a sparse and dense version.

Ah, right, we don’t store the polynomials themselves in the `Stream_exact`, although there can be uses for passing the sparsity to that. I don’t remember if we implement both types of exact storage. Perhaps we should, in case someone wants to create x<sup>10000</sup>.

I am mostly wondering how much we should drop within the streams to carry around the `_sparse` parameter altogether. The multiplication will likely be split into 2 classes (with not being too lazy with the dense multiplication); the rest, except possibly the exact, are all naturally either dense (e.g., inverse) or sparse (e.g., addition).

I will have to look at the code we currently have more closely I think to get a more clear picture. I don’t remember some of the details regarding this. Perhaps you already have a clear picture about this though.

**Comment by mantepse** [comment]
<div id="comment:12" align="right">comment:12</div>

Creating z<sup>10000</sup> is not a problem:

```
sage: L.<z> = LazyPowerSeriesRing(ZZ)
sage: f = z^100000
sage: f._coeff_stream.__dict__
{'_constant': 0,
 '_degree': 100001,
 '_initial_coefficients': (1,),
 '_true_order': True,
 '_approximate_order': 100000}
```
however, z<sup>100000</sup>-1 is:

```
sage: f = z^10 - 1
sage: f._coeff_stream.__dict__
{'_constant': 0,
 '_degree': 11,
 '_initial_coefficients': (-1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1),
 '_true_order': True,
 '_approximate_order': 0}
```

Curiously, it takes a very long time to create, all of which is spent in the polynomial exponentiation - this is, because the underlying polynomial ring, for some reason is always dense:

```python
class LazyLaurentSeriesRing(LazySeriesRing):
    def __init__(self, base_ring, names, sparse=True, category=None):
        self._sparse = sparse
        # We always use the dense because our CS_exact is implemented densely
        self._laurent_poly_ring = LaurentPolynomialRing(base_ring, names)
        self._internal_poly_ring = self._laurent_poly_ring
```

There are actually two easy improvements:

* a sparse version, so we can create 1 + x<sup>100000000</sup>
* I think that the polynomial ring should be dense or sparse depending on our input

and, orthogonal to this,

* a lazy version of `Stream_exact`, with coefficients provided by a function, might also help with the problem of computing large powers or large compositions of exact series.

I can imagine that having only sparse addition is bad.  I can try to create an example if you want.

What I'd be interested in is some help with van der Hoeven's algorithm in #34616.

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
<div id="comment:13"></div>

Branch pushed to git repo; I updated commit sha1. New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/e6c4cae0902abbdef92b68badad66c8833021eb3"><code>e6c4cae</code></a></td><td><code>make Stream_uninitialized always dense to avoid maximal recursion error</code></td></tr></table>

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
Changed commit from **[`7043d1c`](https://github.com/sagemath/sagetrac-mirror/commit/7043d1cf5d937c3f947634c088e8bdc2c13e4d9f)** to **[`e6c4cae`](https://github.com/sagemath/sagetrac-mirror/commit/e6c4cae0902abbdef92b68badad66c8833021eb3)**

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
Changed commit from **[`e6c4cae`](https://github.com/sagemath/sagetrac-mirror/commit/e6c4cae0902abbdef92b68badad66c8833021eb3)** to **[`de424bd`](https://github.com/sagemath/sagetrac-mirror/commit/de424bd78aab5b7e151316644ad460b39261734f)**

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
<div id="comment:14"></div>

Branch pushed to git repo; I updated commit sha1. New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/957738684943d639805ed2c727da7e3ccdc6d5f1"><code>9577386</code></a></td><td><code>implement Polynomial_generic_sparse.__floordiv__</code></td></tr><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/ec1eebddfd5f8f95e2b8a0efc26cc4179d86390b"><code>ec1eebd</code></a></td><td><code>Merge branch 'u/mantepse/__floordiv___for_sparse_polynomials' of trac.sagemath.org:sage into t/34636/make_sparsity_a_decision_of_the_user</code></td></tr><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/de424bd78aab5b7e151316644ad460b39261734f"><code>de424bd</code></a></td><td><code>make internal rings sparse or dense if the lazy series ring is sparse or dense</code></td></tr></table>

**Comment by mantepse** [comment]
<div id="comment:15" align="right">comment:15</div>

I made the internal polynomial rings sparse or dense according to the lazy series ring, although this really is of very little consequence.

Essentially, creating z<sup>100000</sup> is now fast in the sparse case, and some computations for exact series (powers, compositions) are now carried out with sparse polynomials.  I did not check, however, whether this makes sense.  We actually do not use the polynomial rings so much, not even for multiplication.

A completely sparse version of `Stream_exact` should be easy, I think - in the non-lazy setting we would simply have a dictionary of non-zero coefficients.

**Comment by mantepse** [comment]
<div id="comment:16" align="right">comment:16</div>

Although having a sparse version of `Stream_exact` should be easy, taking advantage of it may be much more work, because currently we always compute a *list* of initial coefficients in `lazy_ring.py`.

I very much doubt that it is worth the effort right now.

**Comment by tscrim** [comment]
<div id="comment:17" align="right">comment:17</div>

The dense Laurent polynomials might be a bit better at creating z<sup>10000</sup> than the usual polynomials as they factor out the valuation portion.

It might not be so prudent to spend time implementing a sparse version of `Stream_exact` right now actually. There will be some additional changes needed throughout the code (this might indicate that we need to refactor so the stream can handle more things in its construction method). There are plenty of other things that we can do to improve the speed and efficiency that are likely to be more useful to people.

**Comment by mantepse** [comment]
Changed dependencies from **#34552** to **#34552, #34653**

**Comment by tscrim** [comment]
<div id="comment:19" align="right">comment:19</div>

Let us move along. This is definitely an improvement, and we can do further work on subsequent tickets.

**Comment by tscrim** [comment]
Reviewer: **Travis Scrimshaw**

**Comment by vbraun** [comment]
Changed branch from **[u/mantepse/make_sparsity_a_decision_of_the_user](https://github.com/sagemath/sagetrac-mirror/tree/u/mantepse/make_sparsity_a_decision_of_the_user)** to **[`de424bd`](https://github.com/sagemath/sagetrac-mirror/commit/de424bd78aab5b7e151316644ad460b39261734f)**
