### ISSUE TITLE
sort out Debian's installation of cddlib's headers into cdd/

### ISSUE THREAD

**Issue by dimpase** [sagemath/sage#34634]
<div id="comment:0"></div>

since `cddlib`'s version `094k`, its headers are put into `cddlib/`.

But Debian renames it to `cdd/`. This needs further work on `spkg-configure.m4` of `cddlib`

CC:  @mkoeppe

Component: **build: configure**

Reviewer: **Matthias Koeppe**

_Issue created by migration from https://trac.sagemath.org/ticket/34634_

**Comment by dimpase** [comment]
<div id="comment:1" align="right">comment:1</div>

In fact, Debian is OK:
https://packages.debian.org/sid/amd64/libcdd-dev/filelist

shows that /usr/include/cdd is a link to /usr/include/cddlib, and the latter contains all the files.

Let's close this as invalid.

**Comment by mkoeppe** [comment]
Reviewer: **Matthias Koeppe**
