### ISSUE TITLE
fix some W605 in pyx files in rings

### ISSUE THREAD

**Issue by fchapoton** [sagemath/sage#34639]
<div id="comment:0"></div>

namely in polynomials/, number_fields/ and finite_rings/

CC:  @tscrim @kwankyu @kliem @slel

Component: **commutative algebra**

Author: **Frédéric Chapoton**

Branch/Commit: **[`f948791`](https://github.com/sagemath/sagetrac-mirror/commit/f948791311cb5bd47d22d5476180c93b2e529a45)**

Reviewer: **Travis Scrimshaw**

_Issue created by migration from https://trac.sagemath.org/ticket/34639_

**Comment by fchapoton** [comment]
Commit: **[`f948791`](https://github.com/sagemath/sagetrac-mirror/commit/f948791311cb5bd47d22d5476180c93b2e529a45)**

**Comment by fchapoton** [comment]
<div id="comment:1"></div>

New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/f948791311cb5bd47d22d5476180c93b2e529a45"><code>f948791</code></a></td><td><code>fix some W605 in pyx files in rings/</code></td></tr></table>

**Comment by fchapoton** [comment]
Branch: **[u/chapoton/34639](https://github.com/sagemath/sagetrac-mirror/tree/u/chapoton/34639)**

**Comment by fchapoton** [comment]
<div id="comment:2" align="right">comment:2</div>

green bot, so please review. Should be an easy one

**Comment by tscrim** [comment]
Reviewer: **Travis Scrimshaw**

**Comment by tscrim** [comment]
<div id="comment:3" align="right">comment:3</div>

LGTM.

**Comment by vbraun** [comment]
Changed branch from **[u/chapoton/34639](https://github.com/sagemath/sagetrac-mirror/tree/u/chapoton/34639)** to **[`f948791`](https://github.com/sagemath/sagetrac-mirror/commit/f948791311cb5bd47d22d5476180c93b2e529a45)**
