### ISSUE TITLE
refresh the file categories/rings.py

### ISSUE THREAD

**Issue by fchapoton** [sagemath/sage#34638]
<div id="comment:0"></div>

some pep8 details, mainly

CC:  @tscrim @kwankyu @kliem @slel

Component: **categories**

Author: **Frédéric Chapoton**

Branch/Commit: **[`0de22b1`](https://github.com/sagemath/sagetrac-mirror/commit/0de22b101de7f9a790e8cb043350760624c1a936)**

Reviewer: **Travis Scrimshaw**

_Issue created by migration from https://trac.sagemath.org/ticket/34638_

**Comment by fchapoton** [comment]
Commit: **[`790a684`](https://github.com/sagemath/sagetrac-mirror/commit/790a684e10ee9b0d632fb8448ac77d44dc5a42c4)**

**Comment by fchapoton** [comment]
<div id="comment:1"></div>

New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/790a684e10ee9b0d632fb8448ac77d44dc5a42c4"><code>790a684</code></a></td><td><code>refresh the file categories/rings.py</code></td></tr></table>

**Comment by fchapoton** [comment]
Branch: **[u/chapoton/34638](https://github.com/sagemath/sagetrac-mirror/tree/u/chapoton/34638)**

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
<div id="comment:2"></div>

Branch pushed to git repo; I updated commit sha1. New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/854064e92ce76ad3e8c1c0ae04aa65b6bcc4e8fe"><code>854064e</code></a></td><td><code>fix doctests</code></td></tr></table>

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
Changed commit from **[`790a684`](https://github.com/sagemath/sagetrac-mirror/commit/790a684e10ee9b0d632fb8448ac77d44dc5a42c4)** to **[`854064e`](https://github.com/sagemath/sagetrac-mirror/commit/854064e92ce76ad3e8c1c0ae04aa65b6bcc4e8fe)**

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
<div id="comment:3"></div>

Branch pushed to git repo; I updated commit sha1. New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/0de22b101de7f9a790e8cb043350760624c1a936"><code>0de22b1</code></a></td><td><code>fix the doc (using trac role)</code></td></tr></table>

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
Changed commit from **[`854064e`](https://github.com/sagemath/sagetrac-mirror/commit/854064e92ce76ad3e8c1c0ae04aa65b6bcc4e8fe)** to **[`0de22b1`](https://github.com/sagemath/sagetrac-mirror/commit/0de22b101de7f9a790e8cb043350760624c1a936)**

**Comment by fchapoton** [comment]
<div id="comment:4" align="right">comment:4</div>

green bot, so please review

**Comment by tscrim** [comment]
Reviewer: **Travis Scrimshaw**

**Comment by tscrim** [comment]
<div id="comment:5" align="right">comment:5</div>

LGTM.

**Comment by vbraun** [comment]
Changed branch from **[u/chapoton/34638](https://github.com/sagemath/sagetrac-mirror/tree/u/chapoton/34638)** to **[`0de22b1`](https://github.com/sagemath/sagetrac-mirror/commit/0de22b101de7f9a790e8cb043350760624c1a936)**
