### ISSUE TITLE
minor details in schemes

### ISSUE THREAD

**Issue by fchapoton** [sagemath/sage#34644]
<div id="comment:0"></div>

some about E241 and E502

CC:  @kliem @tscrim

Component: **refactoring**

Author: **Frédéric Chapoton**

Branch/Commit: **[`9410446`](https://github.com/sagemath/sagetrac-mirror/commit/94104462d5d78075dc37b6aeae3b14523bf91bbc)**

Reviewer: **Travis Scrimshaw**

_Issue created by migration from https://trac.sagemath.org/ticket/34644_

**Comment by fchapoton** [comment]
Commit: **[`9410446`](https://github.com/sagemath/sagetrac-mirror/commit/94104462d5d78075dc37b6aeae3b14523bf91bbc)**

**Comment by fchapoton** [comment]
<div id="comment:1"></div>

New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/94104462d5d78075dc37b6aeae3b14523bf91bbc"><code>9410446</code></a></td><td><code>minor details in schemes/</code></td></tr></table>

**Comment by fchapoton** [comment]
Branch: **[u/chapoton/34644](https://github.com/sagemath/sagetrac-mirror/tree/u/chapoton/34644)**

**Comment by fchapoton** [comment]
<div id="comment:2" align="right">comment:2</div>

green bot and lights, so please review

**Comment by tscrim** [comment]
Reviewer: **Travis Scrimshaw**

**Comment by tscrim** [comment]
<div id="comment:3" align="right">comment:3</div>

LGTM.

**Comment by vbraun** [comment]
Changed branch from **[u/chapoton/34644](https://github.com/sagemath/sagetrac-mirror/tree/u/chapoton/34644)** to **[`9410446`](https://github.com/sagemath/sagetrac-mirror/commit/94104462d5d78075dc37b6aeae3b14523bf91bbc)**
