### ISSUE TITLE
Add sage_docbuild/ext/ files to doc

### ISSUE THREAD

**Issue by kwankyu** [sagemath/sage#34642]
<div id="comment:0"></div>

We add 

```
src/sage_docbuild/ext/inventory_builder.py
src/sage_docbuild/ext/multidocs.py
src/sage_docbuild/ext/sage_autodoc.py
```
to the doc of sage documentation system.

Along the way, we also edit the top level index page appropriately.

Component: **documentation**

Author: **Kwankyu Lee**

Branch/Commit: **[`48ba8d0`](https://github.com/sagemath/sagetrac-mirror/commit/48ba8d0b9eb4373cd288418f4cfbfbf871695fc3)**

Reviewer: **Matthias Koeppe**

_Issue created by migration from https://trac.sagemath.org/ticket/34642_

**Comment by kwankyu** [comment]
Author: **Kwankyu Lee**

**Comment by kwankyu** [comment]
Branch: **[u/klee/add_ext___to_documentation_system_doc](https://github.com/sagemath/sagetrac-mirror/tree/u/klee/add_ext___to_documentation_system_doc)**

**Comment by kwankyu** [comment]
Description changed:
``````diff
--- 
+++ 
@@ -1 +1,10 @@
+We add 
 
+```
+src/sage_docbuild/ext/inventory_builder.py
+src/sage_docbuild/ext/multidocs.py
+src/sage_docbuild/ext/sage_autodoc.py
+```
+to the doc of sage documentation system.
+
+Along the way, we also edit the top level index page appropriately.
``````

**Comment by kwankyu** [comment]
Commit: **[`48ba8d0`](https://github.com/sagemath/sagetrac-mirror/commit/48ba8d0b9eb4373cd288418f4cfbfbf871695fc3)**

**Comment by kwankyu** [comment]
<div id="comment:4"></div>

New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/48ba8d0b9eb4373cd288418f4cfbfbf871695fc3"><code>48ba8d0</code></a></td><td><code>Add sage_docbuild/ext/* files to doc</code></td></tr></table>

**Comment by kwankyu** [comment]
<div id="comment:5" align="right">comment:5</div>

The Build & Test failure is not related to this ticket.

**Comment by mkoeppe** [comment]
Reviewer: **Matthias Koeppe**

**Comment by kwankyu** [comment]
<div id="comment:7" align="right">comment:7</div>

Thank you!

**Comment by vbraun** [comment]
Changed branch from **[u/klee/add_ext___to_documentation_system_doc](https://github.com/sagemath/sagetrac-mirror/tree/u/klee/add_ext___to_documentation_system_doc)** to **[`48ba8d0`](https://github.com/sagemath/sagetrac-mirror/commit/48ba8d0b9eb4373cd288418f4cfbfbf871695fc3)**
