### ISSUE TITLE
add svg display hook for plane partitions

### ISSUE THREAD

**Issue by fchapoton** [sagemath/sage#34646]
<div id="comment:0"></div>

so that Jupyter notebook can show them nicely

https://ipython.readthedocs.io/en/stable/api/generated/IPython.core.formatters.html#module-IPython.core.formatters

To test, open the notebook and try

```
PP = PlanePartition([[4,3,3,1],[2,1,1],[1,1]]);PP
```

CC:  @tscrim @slel

Component: **combinatorics**

Author: **Frédéric Chapoton**

Branch/Commit: **[`96539b4`](https://github.com/sagemath/sagetrac-mirror/commit/96539b4bfa0968e5f040a139e82a66ea19a278ee)**

Reviewer: **Travis Scrimshaw**

_Issue created by migration from https://trac.sagemath.org/ticket/34646_

**Comment by fchapoton** [comment]
Commit: **[`86c7099`](https://github.com/sagemath/sagetrac-mirror/commit/86c7099c7c8362f4805a11e08c416cdb40169397)**

**Comment by fchapoton** [comment]
Branch: **[u/chapoton/34646](https://github.com/sagemath/sagetrac-mirror/tree/u/chapoton/34646)**

**Comment by fchapoton** [comment]
<div id="comment:1"></div>

New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/86c7099c7c8362f4805a11e08c416cdb40169397"><code>86c7099</code></a></td><td><code>add svg display hook for plane partitions</code></td></tr></table>

**Comment by fchapoton** [comment]
Description changed:
``````diff
--- 
+++ 
@@ -1 +1,9 @@
 so that Jupyter notebook can show them nicely
+
+https://ipython.readthedocs.io/en/stable/api/generated/IPython.core.formatters.html#module-IPython.core.formatters
+
+To test, open the notebook and try
+
+```
+PP = PlanePartition([[4,3,3,1],[2,1,1],[1,1]]);PP
+```
``````

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
Changed commit from **[`86c7099`](https://github.com/sagemath/sagetrac-mirror/commit/86c7099c7c8362f4805a11e08c416cdb40169397)** to **[`f7b4067`](https://github.com/sagemath/sagetrac-mirror/commit/f7b4067449eb1fad0f67df9f3a96c32a50377957)**

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
<div id="comment:3"></div>

Branch pushed to git repo; I updated commit sha1. New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/f7b4067449eb1fad0f67df9f3a96c32a50377957"><code>f7b4067</code></a></td><td><code>fix the doctests</code></td></tr></table>

**Comment by fchapoton** [comment]
<div id="comment:4" align="right">comment:4</div>

hmm, one can probably avoid to use matrix here

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
<div id="comment:5"></div>

Branch pushed to git repo; I updated commit sha1. This was a forced push. New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/cea9605d9d3cfb7f83a755b65a179376676e3101"><code>cea9605</code></a></td><td><code>add svg display hook for plane partitions</code></td></tr></table>

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
Changed commit from **[`f7b4067`](https://github.com/sagemath/sagetrac-mirror/commit/f7b4067449eb1fad0f67df9f3a96c32a50377957)** to **[`cea9605`](https://github.com/sagemath/sagetrac-mirror/commit/cea9605d9d3cfb7f83a755b65a179376676e3101)**

**Comment by fchapoton** [comment]
<div id="comment:6" align="right">comment:6</div>

now without matrix

**Comment by fchapoton** [comment]
<div id="comment:7" align="right">comment:7</div>

this one should be fun to review, maybe

first use of Jupyter `_repr_svg_` display formatter !

**Comment by tscrim** [comment]
<div id="comment:8" align="right">comment:8</div>

Very pretty. However, along each of the boundaries, one of the edges is not included. I think you just need to extend things slightly in each direction.

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
<div id="comment:9"></div>

Branch pushed to git repo; I updated commit sha1. New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/96539b4bfa0968e5f040a139e82a66ea19a278ee"><code>96539b4</code></a></td><td><code>fine tuning</code></td></tr></table>

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
Changed commit from **[`cea9605`](https://github.com/sagemath/sagetrac-mirror/commit/cea9605d9d3cfb7f83a755b65a179376676e3101)** to **[`96539b4`](https://github.com/sagemath/sagetrac-mirror/commit/96539b4bfa0968e5f040a139e82a66ea19a278ee)**

**Comment by fchapoton** [comment]
<div id="comment:10" align="right">comment:10</div>

thanks, should be better now

**Comment by tscrim** [comment]
<div id="comment:11" align="right">comment:11</div>

Thanks. LGTM.

**Comment by mkoeppe** [comment]
Reviewer: **Travis Scrimshaw**

**Comment by vbraun** [comment]
Changed branch from **[u/chapoton/34646](https://github.com/sagemath/sagetrac-mirror/tree/u/chapoton/34646)** to **[`96539b4`](https://github.com/sagemath/sagetrac-mirror/commit/96539b4bfa0968e5f040a139e82a66ea19a278ee)**
