### ISSUE TITLE
remove one trace of python2

### ISSUE THREAD

**Issue by fchapoton** [sagemath/sage#34649]
<div id="comment:0"></div>

in one build script

Component: **build**

Author: **Frédéric Chapoton**

Branch/Commit: **[`86f8a14`](https://github.com/sagemath/sagetrac-mirror/commit/86f8a140a91f9ca935cbbbf79b3159b61e4e43cd)**

Reviewer: **Matthias Koeppe**

_Issue created by migration from https://trac.sagemath.org/ticket/34649_

**Comment by fchapoton** [comment]
Commit: **[`86f8a14`](https://github.com/sagemath/sagetrac-mirror/commit/86f8a140a91f9ca935cbbbf79b3159b61e4e43cd)**

**Comment by fchapoton** [comment]
<div id="comment:1"></div>

New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/86f8a140a91f9ca935cbbbf79b3159b61e4e43cd"><code>86f8a14</code></a></td><td><code>remove one trace of python2</code></td></tr></table>

**Comment by fchapoton** [comment]
Branch: **[u/chapoton/34649](https://github.com/sagemath/sagetrac-mirror/tree/u/chapoton/34649)**

**Comment by mkoeppe** [comment]
<div id="comment:2" align="right">comment:2</div>

`sage_bootstrap` still needs to support Python 2 - see https://doc.sagemath.org/html/en/installation/source.html#command-line-tools

**Comment by fchapoton** [comment]
<div id="comment:3" align="right">comment:3</div>

this does not break py2 compatibility

**Comment by mkoeppe** [comment]
Reviewer: **Matthias Koeppe**

**Comment by mkoeppe** [comment]
<div id="comment:4" align="right">comment:4</div>

Right

**Comment by vbraun** [comment]
Changed branch from **[u/chapoton/34649](https://github.com/sagemath/sagetrac-mirror/tree/u/chapoton/34649)** to **[`86f8a14`](https://github.com/sagemath/sagetrac-mirror/commit/86f8a140a91f9ca935cbbbf79b3159b61e4e43cd)**
