### ISSUE TITLE
pep8 cleanup for genera/normal_form

### ISSUE THREAD

**Issue by fchapoton** [sagemath/sage#34643]
<div id="comment:0"></div>

also one or two tweaks in the code

CC:  @tscrim @slel @mantepse

Component: **quadratic forms**

Author: **Frédéric Chapoton**

Branch/Commit: **[`9dc18ec`](https://github.com/sagemath/sagetrac-mirror/commit/9dc18eccad24a06de04f393854a4ecbff866c31a)**

Reviewer: **Travis Scrimshaw**

_Issue created by migration from https://trac.sagemath.org/ticket/34643_

**Comment by fchapoton** [comment]
<div id="comment:1"></div>

New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/d7474da083fc06e3316c4bdb54d7c1ddc3f3ff9d"><code>d7474da</code></a></td><td><code>pep8 cleanup for genera/normal_form</code></td></tr></table>

**Comment by fchapoton** [comment]
Branch: **[u/chapoton/34643](https://github.com/sagemath/sagetrac-mirror/tree/u/chapoton/34643)**

**Comment by fchapoton** [comment]
Commit: **[`d7474da`](https://github.com/sagemath/sagetrac-mirror/commit/d7474da083fc06e3316c4bdb54d7c1ddc3f3ff9d)**

**Comment by fchapoton** [comment]
<div id="comment:2" align="right">comment:2</div>

bot and lights are morally green, so please review (should be easy)

**Comment by tscrim** [comment]
Reviewer: **Travis Scrimshaw**

**Comment by tscrim** [comment]
<div id="comment:3" align="right">comment:3</div>

You are not also going to change?

```diff
-        if len(V) != 0 and D[V[0], V[0]] == 0:
+        if V and D[V[0], V[0]] == 0:
```

I find changes like this harder to parse:

```diff
-                B[i:i+2, :] = trafo * B[i:i+2, :]
+                B[i:i + 2, :] = trafo * B[i:i + 2, :]
```
I would apply the PEP8 higher priority operators spacing exception here (e.g., `3 * (x+y)`).

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
<div id="comment:4"></div>

Branch pushed to git repo; I updated commit sha1. New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/9dc18eccad24a06de04f393854a4ecbff866c31a"><code>9dc18ec</code></a></td><td><code>details fixed</code></td></tr></table>

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
Changed commit from **[`d7474da`](https://github.com/sagemath/sagetrac-mirror/commit/d7474da083fc06e3316c4bdb54d7c1ddc3f3ff9d)** to **[`9dc18ec`](https://github.com/sagemath/sagetrac-mirror/commit/9dc18eccad24a06de04f393854a4ecbff866c31a)**

**Comment by fchapoton** [comment]
<div id="comment:5" align="right">comment:5</div>

well, undone, but now my text editor complains again about missing spaces.

**Comment by tscrim** [comment]
<div id="comment:6" align="right">comment:6</div>

Thank you. I am sorry about that, but this does make it a lot easier to parse IMO since the spaces are delimiting the inputs. I would apply the same for function arguments, such as `f(x=y + 1, z=y + 2)`. The lack of spacing around the `=` (which is mandated by PEP8 and I also support to distinguish it from assignment `=`) really throws me off.

**Comment by vbraun** [comment]
Changed branch from **[u/chapoton/34643](https://github.com/sagemath/sagetrac-mirror/tree/u/chapoton/34643)** to **[`9dc18ec`](https://github.com/sagemath/sagetrac-mirror/commit/9dc18eccad24a06de04f393854a4ecbff866c31a)**
