### ISSUE TITLE
some details in permutation groups

### ISSUE THREAD

**Issue by fchapoton** [sagemath/sage#34647]
<div id="comment:0"></div>

mostly a few pep8 changes

CC:  @tscrim @kwankyu @kliem @slel

Component: **group theory**

Author: **Frédéric Chapoton**

Branch/Commit: **[`16fd967`](https://github.com/sagemath/sagetrac-mirror/commit/16fd967e51813ef97c7f9da6eee35ade6c5857de)**

Reviewer: **Travis Scrimshaw**

_Issue created by migration from https://trac.sagemath.org/ticket/34647_

**Comment by fchapoton** [comment]
<div id="comment:1"></div>

New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/16fd967e51813ef97c7f9da6eee35ade6c5857de"><code>16fd967</code></a></td><td><code>some details in permutation groups</code></td></tr></table>

**Comment by fchapoton** [comment]
Branch: **[u/chapoton/34647](https://github.com/sagemath/sagetrac-mirror/tree/u/chapoton/34647)**

**Comment by fchapoton** [comment]
Commit: **[`16fd967`](https://github.com/sagemath/sagetrac-mirror/commit/16fd967e51813ef97c7f9da6eee35ade6c5857de)**

**Comment by fchapoton** [comment]
<div id="comment:2" align="right">comment:2</div>

green lights, so please review, should be an easy one

**Comment by tscrim** [comment]
Reviewer: **Travis Scrimshaw**

**Comment by tscrim** [comment]
<div id="comment:3" align="right">comment:3</div>

LGTM.

**Comment by vbraun** [comment]
Changed branch from **[u/chapoton/34647](https://github.com/sagemath/sagetrac-mirror/tree/u/chapoton/34647)** to **[`16fd967`](https://github.com/sagemath/sagetrac-mirror/commit/16fd967e51813ef97c7f9da6eee35ade6c5857de)**
