### ISSUE TITLE
fix some pep8 in words/

### ISSUE THREAD

**Issue by fchapoton** [sagemath/sage#34640]
<div id="comment:0"></div>

Component: **combinatorics**

Author: **Frédéric Chapoton**

Branch/Commit: **[`5a339e1`](https://github.com/sagemath/sagetrac-mirror/commit/5a339e1fc56ba7b470b3aec91497ca6319b24ac9)**

Reviewer: **Matthias Koeppe**

_Issue created by migration from https://trac.sagemath.org/ticket/34640_

**Comment by fchapoton** [comment]
<div id="comment:1"></div>

New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/5a339e1fc56ba7b470b3aec91497ca6319b24ac9"><code>5a339e1</code></a></td><td><code>fix some pep in words</code></td></tr></table>

**Comment by fchapoton** [comment]
Branch: **[u/chapoton/34640](https://github.com/sagemath/sagetrac-mirror/tree/u/chapoton/34640)**

**Comment by fchapoton** [comment]
Commit: **[`5a339e1`](https://github.com/sagemath/sagetrac-mirror/commit/5a339e1fc56ba7b470b3aec91497ca6319b24ac9)**

**Comment by mkoeppe** [comment]
Reviewer: **Matthias Koeppe**

**Comment by vbraun** [comment]
Changed branch from **[u/chapoton/34640](https://github.com/sagemath/sagetrac-mirror/tree/u/chapoton/34640)** to **[`5a339e1`](https://github.com/sagemath/sagetrac-mirror/commit/5a339e1fc56ba7b470b3aec91497ca6319b24ac9)**
