### ISSUE TITLE
Add `multivariate_interpolation` for multivariate polynomial rings

### ISSUE THREAD

**Issue by jbirnick** [sagemath/sage#34651]
<div id="comment:0"></div>

We add a method `multivariate_interpolation` to the `MPolynomialRing_base` class.

Given a bound on the degree and either point/value pairs or a function, it returns the respective interpolation polynomial.

CC:  @schmittj @videlec

Component: **algebra**

Keywords: **interpolation, polynomials**

Author: **Johann Birnick**

Branch/Commit: **[`7eea889`](https://github.com/sagemath/sagetrac-mirror/commit/7eea8892b6d584d74f80c0554ae31a67e58cdff8)**

Reviewer: **Johannes Schmitt, Lorenz Panny**

_Issue created by migration from https://trac.sagemath.org/ticket/34651_

**Comment by jbirnick** [comment]
Branch: **[u/gh-jbirnick/multivariate_interpolation](https://github.com/sagemath/sagetrac-mirror/tree/u/gh-jbirnick/multivariate_interpolation)**

**Comment by jbirnick** [comment]
Changed branch from **[u/gh-jbirnick/multivariate_interpolation](https://github.com/sagemath/sagetrac-mirror/tree/u/gh-jbirnick/multivariate_interpolation)** to none

**Comment by jbirnick** [comment]
Commit: **[`e09725c`](https://github.com/sagemath/sagetrac-mirror/commit/e09725c4973792a294d84923746b3097befe5770)**

**Comment by jbirnick** [comment]
Branch: **[u/gh-jbirnick/multivariate_interpolation](https://github.com/sagemath/sagetrac-mirror/tree/u/gh-jbirnick/multivariate_interpolation)**

**Comment by jbirnick** [comment]
<div id="comment:4"></div>

New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/e09725c4973792a294d84923746b3097befe5770"><code>e09725c</code></a></td><td><code>Added multivariate_interpolation for multivariate polynomial rings.</code></td></tr></table>

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
Changed commit from **[`e09725c`](https://github.com/sagemath/sagetrac-mirror/commit/e09725c4973792a294d84923746b3097befe5770)** to **[`5e29ad6`](https://github.com/sagemath/sagetrac-mirror/commit/5e29ad644717a5c3ef8af53a8fbda8e1bdfdf4a8)**

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
<div id="comment:6"></div>

Branch pushed to git repo; I updated commit sha1. New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/5e29ad644717a5c3ef8af53a8fbda8e1bdfdf4a8"><code>5e29ad6</code></a></td><td><code>Improved documentation.</code></td></tr></table>

**Comment by jbirnick** [comment]
<div id="comment:7" align="right">comment:7</div>

The ticket is now ready for review.

As this is my first ever [SageMath](../wiki/SageMath) contribution, I also want to ask the following questions:

1. Is my way/style of importing correct? Or should I do it differently?                                                                   
2. I use internal functions, i.e. functions defined inside a function. Is this fine as it is or should I rename them with an underscore in front?
3. Is my way of reporting a warning good or is there a better/"sage-style" way?

Also: The status badge says the linting doesn't pass... however from the log I can't really see what is going wrong.

**Comment by schmittj** [comment]
<div id="comment:9" align="right">comment:9</div>

Mathematically the code looks very good to me, it has extensive documentation and - from what I can see - it follows the established code conventions for [SageMath](../wiki/SageMath). So I am happy to give an informal positive review, but it would be good if someone more familiar with Sage would have another look.

**Comment by yyyyx4** [comment]
<div id="comment:10" align="right">comment:10</div>

Welcome to Sage, this looks like a great first patch!

Some comments regarding the docstring formatting (according to the usual Sage conventions):

- Use backticks ` instead of quotes " around variable names inside the text. This will make the HTML documentation render it as code.
- In general, double colons `::` are used if and only if the following block is indented; use a single colon `:` otherwise.
- `NOTE:` → `.. NOTE::`
- `WARNING::` → `.. WARNING::`
- `SEEALSO:` → `.. SEEALSO::`, and insert another blank line after.
- Do not indent the `ALGORITHM:` block.
- No need to indent the enumerated lists either.
- `a evaluable function` → `an evaluable function`, or maybe drop the articles "a" altogether in that list.

I'm also wondering if the method should just be called `interpolation()`: the "multivariate" part follows from its class.

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
Changed commit from **[`5e29ad6`](https://github.com/sagemath/sagetrac-mirror/commit/5e29ad644717a5c3ef8af53a8fbda8e1bdfdf4a8)** to **[`d68678a`](https://github.com/sagemath/sagetrac-mirror/commit/d68678a1406970cc13011ab0dac577a28b76e7f7)**

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
<div id="comment:11"></div>

Branch pushed to git repo; I updated commit sha1. New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/8730e64d5453ed78fcd93ea403109c81e36e954f"><code>8730e64</code></a></td><td><code>Improved style.</code></td></tr><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/d68678a1406970cc13011ab0dac577a28b76e7f7"><code>d68678a</code></a></td><td><code>Corrected doctring formatting.</code></td></tr></table>

**Comment by jbirnick** [comment]
<div id="comment:12" align="right">comment:12</div>

Thanks for your feedback! I have fixed the points you mentioned.

Concerning the function name: `interpolation()` is certainly better for users to find the function. However I wanted to somehow make clear that the `lagrange_polynomial()` (for univariate poly rings) and `multivariate_interpolation()` (for multivariate poly rings) are different functions that also have different speed etc., and then only work for one or multiple variables, respectively.

In the end you are the Sage experts, so I'll call it whatever you all think is best, just let me know.

**Comment by yyyyx4** [comment]
<div id="comment:13" align="right">comment:13</div>

Sorry, I got it wrong: Single backticks are for math and double backticks are for code. There are definitely too many similar-but-different markup languages out there. So, for example:

```
        * ``function`` -- evaluable function in `n` variables, where `n` is the
          number of variables of the polynomial ring
```

I also seem to recall that Sage has a preference for formatting exceptions in accordance with Python's own style, i.e., starting with a lowercase letter and omitting the final punctuation, but I can't find a reference for this right now.

The warning about non-uniqueness of the solution can be useful, but I think it can also be very annoying: Imagine running this in a loop and getting spammed with an endless stream of those messages. Perhaps a cleaner way would be to instead introduce an optional keyword argument to additionally return a basis of the vector space of polynomials which evaluate to zero at the interpolation points? Users who wish to ensure uniqueness can then simply check that this basis is an empty list. (If you dislike this suggestion, we should think of some other way for users to silence the warning if desired.)

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
Changed commit from **[`d68678a`](https://github.com/sagemath/sagetrac-mirror/commit/d68678a1406970cc13011ab0dac577a28b76e7f7)** to **[`61150df`](https://github.com/sagemath/sagetrac-mirror/commit/61150df051de5c6841fe44a8cd4fc1af9f0d5b82)**

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
<div id="comment:14"></div>

Branch pushed to git repo; I updated commit sha1. New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/61150df051de5c6841fe44a8cd4fc1af9f0d5b82"><code>61150df</code></a></td><td><code>improved documentation, removed warning for non-unique solution</code></td></tr></table>

**Comment by jbirnick** [comment]
<div id="comment:15" align="right">comment:15</div>

I have fixed the markup.

**Exceptions formatting:** I have scrolled the Sage source and saw both, so I'm not sure. I personally prefer full sentences, so I kept it like that. However if there is any convention, I'll change it.

**Warnings/non-uniqueness:** Isn't the point that warnings are posted via a special warnings class? So people who don't want to see them should be able to somehow supress them. At least that looks like the clean solution to me. *However*, I wanted to imitate the behavior of `M.solve_right(v)`, so I checked what this does. And it doesn't give a warning at all, so I deleted my warning completely.
(Though personally I would prefer warnings.. maybe in a future ticket.)

**Comment by yyyyx4** [comment]
Reviewer: **Johannes Schmitt, Lorenz Panny**

**Comment by yyyyx4** [comment]
<div id="comment:16" align="right">comment:16</div>

Alright, looks good to me then. Thank you!

**Comment by mantepse** [comment]
<div id="comment:17" align="right">comment:17</div>

Sorry for being late: wouldn't it be better to call the method just "interpolation", or even "interpolate"?

There is a single occurrence of `CALL FORMATS` in sagemath currently, but it seems to me that even there, https://doc.sagemath.org/html/en/reference/matrices/sage/matrix/special.html#sage.matrix.special.ones_matrix, the documentation looks wrong and double backticks should be used:

**Comment by jbirnick** [comment]
<div id="comment:18" align="right">comment:18</div>

@mantepse concerning the name of the function, have you seen my previous comment:

> Concerning the function name: interpolation() is certainly better for users to find the function. However I wanted to somehow make clear that the lagrange_polynomial() (for univariate poly rings) and multivariate_interpolation() (for multivariate poly rings) are different functions that also have different speed etc., and that only work for one or multiple variables, respectively.

However if multiple experienced Sage users want me to change the name, I can do it. Just let me know.

Concerning documentation I didn't get your point.. is there anything wrongly formatted that I should correct?

**Comment by mantepse** [comment]
<div id="comment:19" align="right">comment:19</div>

I don't quite understand: doesn't this function also work in the univariate case?  I am not an expert, so it might be best to ask on sage-devel (and set the ticket to needs info in the meantime).  Or did you ask already, and I missed it?  In this case, please go ahead!

**Comment by jbirnick** [comment]
<div id="comment:20" align="right">comment:20</div>

This function theoretically works for one variable, but:

1. The class for univariate polynomial rings is a completely different one. I would have to copy (and simplify) the code there, which I don't because:
2. There already is an interpolation function for one variable (`lagrange_polynomial()`) that works faster.

All in all the classes for univariate and multivariate polynomial rings are completely different, and the algorithms for interpolation are different as well.

That's why I thought the names should reflect that. I will change the name to `interpolation()` now, and hope that people will recognize that the appropriate function for one variable is `lagrange_polynomial()`. (I mentioned this function in my documentation.)

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
<div id="comment:21"></div>

Branch pushed to git repo; I updated commit sha1 and set ticket back to needs_review. New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/7eea8892b6d584d74f80c0554ae31a67e58cdff8"><code>7eea889</code></a></td><td><code>changed function name</code></td></tr></table>

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
Changed commit from **[`61150df`](https://github.com/sagemath/sagetrac-mirror/commit/61150df051de5c6841fe44a8cd4fc1af9f0d5b82)** to **[`7eea889`](https://github.com/sagemath/sagetrac-mirror/commit/7eea8892b6d584d74f80c0554ae31a67e58cdff8)**

**Comment by vbraun** [comment]
Changed branch from **[u/gh-jbirnick/multivariate_interpolation](https://github.com/sagemath/sagetrac-mirror/tree/u/gh-jbirnick/multivariate_interpolation)** to **[`7eea889`](https://github.com/sagemath/sagetrac-mirror/commit/7eea8892b6d584d74f80c0554ae31a67e58cdff8)**
