### ISSUE TITLE
__floordiv__ for sparse polynomials

### ISSUE THREAD

**Issue by mantepse** [sagemath/sage#34653]
<div id="comment:0"></div>

Before this ticket, the following would raise an `ArithmeticError` in the sparse case:

```
sage: P.<x,y> = PolynomialRing(SR)
sage: R.<z> = PolynomialRing(P, sparse=False); R
Univariate Polynomial Ring in z over Multivariate Polynomial Ring in x, y over Symbolic Ring
sage: (x*z) // x
z
sage: R.<z> = PolynomialRing(P, sparse=True); R
Sparse Univariate Polynomial Ring in z over Multivariate Polynomial Ring in x, y over Symbolic Ring
sage: (x*z) // x
z
```

Component: **algebra**

Author: **Martin Rubey**

Branch/Commit: **[`9577386`](https://github.com/sagemath/sagetrac-mirror/commit/957738684943d639805ed2c727da7e3ccdc6d5f1)**

Reviewer: **Travis Scrimshaw**

_Issue created by migration from https://trac.sagemath.org/ticket/34653_

**Comment by mantepse** [comment]
Branch: **[u/mantepse/__floordiv___for_sparse_polynomials](https://github.com/sagemath/sagetrac-mirror/tree/u/mantepse/__floordiv___for_sparse_polynomials)**

**Comment by mantepse** [comment]
Commit: **[`9577386`](https://github.com/sagemath/sagetrac-mirror/commit/957738684943d639805ed2c727da7e3ccdc6d5f1)**

**Comment by mantepse** [comment]
Author: **Martin Rubey**

**Comment by mantepse** [comment]
<div id="comment:2"></div>

New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/957738684943d639805ed2c727da7e3ccdc6d5f1"><code>9577386</code></a></td><td><code>implement Polynomial_generic_sparse.__floordiv__</code></td></tr></table>

**Comment by mantepse** [comment]
Description changed:
``````diff
--- 
+++ 
@@ -1 +1,13 @@
+Before this ticket, the following would raise an `ArithmeticError` in the sparse case:
 
+```
+sage: P.<x,y> = PolynomialRing(SR)
+sage: R.<z> = PolynomialRing(P, sparse=False); R
+Univariate Polynomial Ring in z over Multivariate Polynomial Ring in x, y over Symbolic Ring
+sage: (x*z) // x
+z
+sage: R.<z> = PolynomialRing(P, sparse=True); R
+Sparse Univariate Polynomial Ring in z over Multivariate Polynomial Ring in x, y over Symbolic Ring
+sage: (x*z) // x
+z
+```
``````

**Comment by tscrim** [comment]
<div id="comment:3" align="right">comment:3</div>

LGTM.

**Comment by tscrim** [comment]
Reviewer: **Travis Scrimshaw**

**Comment by vbraun** [comment]
Changed branch from **[u/mantepse/__floordiv___for_sparse_polynomials](https://github.com/sagemath/sagetrac-mirror/tree/u/mantepse/__floordiv___for_sparse_polynomials)** to **[`9577386`](https://github.com/sagemath/sagetrac-mirror/commit/957738684943d639805ed2c727da7e3ccdc6d5f1)**
