### ISSUE TITLE
Make make doc-clean also remove reference/documentation/sage_docbuild

### ISSUE THREAD

**Issue by kwankyu** [sagemath/sage#34657]
<div id="comment:0"></div>

We should remove the artifacts `reference/documentation/sage_docbuild` directory when `make doc-clean`.

Component: **documentation**

Author: **Kwankyu Lee**

Branch/Commit: **[`3a41d78`](https://github.com/sagemath/sagetrac-mirror/commit/3a41d7820772b076135ae3a953e51a6a27d658cd)**

Reviewer: **Matthias Koeppe**

_Issue created by migration from https://trac.sagemath.org/ticket/34657_

**Comment by kwankyu** [comment]
Branch: **[u/klee/make_make_doc_clean_also_remove_reference_documentation_sage_docbuild](https://github.com/sagemath/sagetrac-mirror/tree/u/klee/make_make_doc_clean_also_remove_reference_documentation_sage_docbuild)**

**Comment by kwankyu** [comment]
Commit: **[`3a41d78`](https://github.com/sagemath/sagetrac-mirror/commit/3a41d7820772b076135ae3a953e51a6a27d658cd)**

**Comment by kwankyu** [comment]
<div id="comment:2"></div>

New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/3a41d7820772b076135ae3a953e51a6a27d658cd"><code>3a41d78</code></a></td><td><code>make doc-clean remove sage_docbuild</code></td></tr></table>

**Comment by kwankyu** [comment]
Author: **Kwankyu Lee**

**Comment by kwankyu** [comment]
Description changed:
``````diff
--- 
+++ 
@@ -1 +1 @@
-
+We should remove the artifacts `reference/documentation/sage_docbuild` directory when `make doc-clean`.
``````

**Comment by mkoeppe** [comment]
Reviewer: **Matthias Koeppe**

**Comment by mkoeppe** [comment]
<div id="comment:5" align="right">comment:5</div>

LGTM

**Comment by kwankyu** [comment]
<div id="comment:6" align="right">comment:6</div>

Thanks!

**Comment by vbraun** [comment]
Changed branch from **[u/klee/make_make_doc_clean_also_remove_reference_documentation_sage_docbuild](https://github.com/sagemath/sagetrac-mirror/tree/u/klee/make_make_doc_clean_also_remove_reference_documentation_sage_docbuild)** to **[`3a41d78`](https://github.com/sagemath/sagetrac-mirror/commit/3a41d7820772b076135ae3a953e51a6a27d658cd)**
