### ISSUE TITLE
Pickling frobenius endomorphism is broken

### ISSUE THREAD

**Issue by xcaruso** [sagemath/sage#34654]
<div id="comment:0"></div>

```
sage: K = Frac(GF(5)['T'])
sage: phi = K.frobenius_endomorphism()
sage: phi
Frobenius endomorphism x |--> x^5 of Fraction Field of Univariate Polynomial Ring in T over Finite Field of size 5
sage: loads(dumps(phi))
Identity endomorphism of Fraction Field of Univariate Polynomial Ring in T over Finite Field of size 5
```

CC:  @kryzar

Component: **pickling**

Keywords: **frobenius**

Author: **Xavier Caruso**

Branch/Commit: **[`a9a4183`](https://github.com/sagemath/sagetrac-mirror/commit/a9a4183e3d1d2f27407948d7636b7adc8cb4c6ff)**

Reviewer: **Sébastien Labbé, Kwankyu Lee**

_Issue created by migration from https://trac.sagemath.org/ticket/34654_

**Comment by xcaruso** [comment]
Branch: **[u/caruso/pickling_frobenius](https://github.com/sagemath/sagetrac-mirror/tree/u/caruso/pickling_frobenius)**

**Comment by xcaruso** [comment]
<div id="comment:2"></div>

New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/58de6133486d60c05d8c474faf6f376ed5bc890b"><code>58de613</code></a></td><td><code>fix pickling for FrobeniusEndomorphism_generic</code></td></tr></table>

**Comment by xcaruso** [comment]
Author: **Xavier Caruso**

**Comment by xcaruso** [comment]
Commit: **[`58de613`](https://github.com/sagemath/sagetrac-mirror/commit/58de6133486d60c05d8c474faf6f376ed5bc890b)**

**Comment by seblabbe** [comment]
<div id="comment:3" align="right">comment:3</div>

I suggest the following modifications:

- replace "prime" by "p" to match the attribute names
- improve the one sentence doc of both functions, in particuler "_extra_slots" does not mean anything and needs to be explained what it does

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
<div id="comment:4"></div>

Branch pushed to git repo; I updated commit sha1. New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/fce1d8a11f3aa84b3fe8a05e77e202e31ae16a2a"><code>fce1d8a</code></a></td><td><code>Address Sebastien's comments</code></td></tr></table>

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
Changed commit from **[`58de613`](https://github.com/sagemath/sagetrac-mirror/commit/58de6133486d60c05d8c474faf6f376ed5bc890b)** to **[`fce1d8a`](https://github.com/sagemath/sagetrac-mirror/commit/fce1d8a11f3aa84b3fe8a05e77e202e31ae16a2a)**

**Comment by seblabbe** [comment]
<div id="comment:5" align="right">comment:5</div>

I see the following failures on the patchbot report:

```
----------------------------------------------------------------------
sage -t --long --random-seed=98983843038100135194336768131633033400 src/sage/rings/polynomial/ore_function_field.py  # 9 doctests failed
sage -t --long --random-seed=98983843038100135194336768131633033400 src/sage/rings/finite_rings/hom_finite_field.pyx  # 5 doctests failed
sage -t --long --random-seed=98983843038100135194336768131633033400 src/sage/rings/polynomial/ore_polynomial_ring.py  # 3 doctests failed
sage -t --long --random-seed=98983843038100135194336768131633033400 src/sage/rings/polynomial/skew_polynomial_ring.py  # 10 doctests failed
----------------------------------------------------------------------
```

and few more on the other one:

```
----------------------------------------------------------------------
sage -t --long --warn-long 67.9 --random-seed=83963079143685479769442176755507876843 src/sage/schemes/toric/sheaf/klyachko.py  # 1 doctest failed
sage -t --long --warn-long 67.9 --random-seed=83963079143685479769442176755507876843 src/sage/interfaces/expect.py  # 2 doctests failed
sage -t --long --warn-long 67.9 --random-seed=83963079143685479769442176755507876843 src/sage/rings/polynomial/ore_function_field.py  # 9 doctests failed
sage -t --long --warn-long 67.9 --random-seed=83963079143685479769442176755507876843 src/sage/rings/finite_rings/hom_finite_field.pyx  # 5 doctests failed
sage -t --long --warn-long 67.9 --random-seed=83963079143685479769442176755507876843 src/sage/rings/polynomial/ore_polynomial_ring.py  # 3 doctests failed
sage -t --long --warn-long 67.9 --random-seed=83963079143685479769442176755507876843 src/sage/rings/polynomial/skew_polynomial_ring.py  # 10 doctests failed
----------------------------------------------------------------------
```

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
<div id="comment:6"></div>

Branch pushed to git repo; I updated commit sha1. New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/3c7685643bef6f9dbc40a00fa5a4efa735887285"><code>3c76856</code></a></td><td><code>retrieve p as domain.characteristic()</code></td></tr></table>

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
Changed commit from **[`fce1d8a`](https://github.com/sagemath/sagetrac-mirror/commit/fce1d8a11f3aa84b3fe8a05e77e202e31ae16a2a)** to **[`3c76856`](https://github.com/sagemath/sagetrac-mirror/commit/3c7685643bef6f9dbc40a00fa5a4efa735887285)**

**Comment by xcaruso** [comment]
<div id="comment:7" align="right">comment:7</div>

Seems to be fixed.

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
<div id="comment:8"></div>

Branch pushed to git repo; I updated commit sha1. New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/a9a4183e3d1d2f27407948d7636b7adc8cb4c6ff"><code>a9a4183</code></a></td><td><code>power -> _power</code></td></tr></table>

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
Changed commit from **[`3c76856`](https://github.com/sagemath/sagetrac-mirror/commit/3c7685643bef6f9dbc40a00fa5a4efa735887285)** to **[`a9a4183`](https://github.com/sagemath/sagetrac-mirror/commit/a9a4183e3d1d2f27407948d7636b7adc8cb4c6ff)**

**Comment by kwankyu** [comment]
<div id="comment:9" align="right">comment:9</div>

LGTM.

**Comment by kwankyu** [comment]
Reviewer: **Sébastien Labbé, Kwankyu Lee**

**Comment by vbraun** [comment]
Changed branch from **[u/caruso/pickling_frobenius](https://github.com/sagemath/sagetrac-mirror/tree/u/caruso/pickling_frobenius)** to **[`a9a4183`](https://github.com/sagemath/sagetrac-mirror/commit/a9a4183e3d1d2f27407948d7636b7adc8cb4c6ff)**
