### ISSUE TITLE
Update numpy to 1.23.5, scipy 1.9.3, networkx 2.8.8, meson_python 0.11.0

### ISSUE THREAD

**Issue by mkoeppe** [sagemath/sage#34658]
<div id="comment:0"></div>

https://github.com/numpy/numpy/releases/tag/v1.23.4

https://docs.scipy.org/doc/scipy/release.1.9.3.html

https://meson-python.readthedocs.io/en/latest/changelog.html#changelog

Depends on #34081

Upstream: **Fixed upstream, in a later stable release.**

CC:  @dimpase @dcoudert @kiwifb @orlitzky @jhpalmieri

Component: **packages: standard**

Author: **Matthias Koeppe**

Branch/Commit: **[`d74528c`](https://github.com/sagemath/sagetrac-mirror/commit/d74528c0c41e6368c14274817337d011ae24a6f7)**

Reviewer: **John Palmieri**

_Issue created by migration from https://trac.sagemath.org/ticket/34658_

**Comment by mkoeppe** [comment]
Branch: **[u/mkoeppe/update_numpy_to_1_23_4](https://github.com/sagemath/sagetrac-mirror/tree/u/mkoeppe/update_numpy_to_1_23_4)**

**Comment by mkoeppe** [comment]
Author: **Matthias Koeppe**

**Comment by mkoeppe** [comment]
Commit: **[`0d18405`](https://github.com/sagemath/sagetrac-mirror/commit/0d18405deace7965182ad0f1d87b07c744b256fb)**

**Comment by mkoeppe** [comment]
<div id="comment:2"></div>

New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/0d18405deace7965182ad0f1d87b07c744b256fb"><code>0d18405</code></a></td><td><code>build/pkgs/numpy: Update to 1.23.4</code></td></tr></table>

**Comment by mkoeppe** [comment]
Reviewer: **https://github.com/mkoeppe/sage/actions/runs/3251926884**

**Comment by mkoeppe** [comment]
Description changed:
``````diff
--- 
+++ 
@@ -1,2 +1,3 @@
 https://github.com/numpy/numpy/releases/tag/v1.23.4
 
+https://docs.scipy.org/doc/scipy/release.1.9.3.html
``````

**Comment by mkoeppe** [comment]
Dependencies: **#34081**

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
Changed commit from **[`0d18405`](https://github.com/sagemath/sagetrac-mirror/commit/0d18405deace7965182ad0f1d87b07c744b256fb)** to **[`ba5c196`](https://github.com/sagemath/sagetrac-mirror/commit/ba5c196223aa96014e0e138711f26d8238f3841b)**

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
<div id="comment:5"></div>

Branch pushed to git repo; I updated commit sha1. This was a forced push. Last 10 new commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/d36ed98544ee0e74941dbdffe021798124e4c176"><code>d36ed98</code></a></td><td><code>tox.ini (python3.*-minimal): Provide system liblzma so that system python can be accepted; not system xz</code></td></tr><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/f62b625ec6ef271e87e6a26deeb816387d5543c0"><code>f62b625</code></a></td><td><code>Merge #32182</code></td></tr><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/8990d53f335631f4926cfb1c1e18bfa9ecda5689"><code>8990d53</code></a></td><td><code>.github/workflows/docker.yml: Add option free_disk_space</code></td></tr><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/09244b05468c5b7b407074a60cbd3452eebd60a7"><code>09244b0</code></a></td><td><code>tox.ini (python3.x): Do not clobber user-provided EXTRA_SAGE_PACKAGES</code></td></tr><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/9fb4eac6f4a87fa73fa79a1b173cd09e590ab2fa"><code>9fb4eac</code></a></td><td><code>.github/workflows/docker.yml: Add option extra_sage_packages</code></td></tr><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/3897adb6aa1c59f4410315ea813e4ccc08cc3df0"><code>3897adb</code></a></td><td><code>tox.ini (manylinux-minimal): Provide system liblzma so that system python can be accepted; not system xz</code></td></tr><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/4b7f679a57c034c7dba6ae5fcd92505574122bc8"><code>4b7f679</code></a></td><td><code>Merge #34081</code></td></tr><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/fcc7087f16fd9c7f3015d5a40c51089b934f3834"><code>fcc7087</code></a></td><td><code>build/pkgs/scipy: Update to 1.9.3</code></td></tr><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/a2b5da4528b59fbbbc74bcaeee3acead6e7cd654"><code>a2b5da4</code></a></td><td><code>build/pkgs/networkx: Update to 2.8.7</code></td></tr><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/ba5c196223aa96014e0e138711f26d8238f3841b"><code>ba5c196</code></a></td><td><code>build/pkgs/pythran: Update to 0.12.0</code></td></tr></table>

**Comment by dimpase** [comment]
<div id="comment:7" align="right">comment:7</div>

I get test errors in `matrix2.pyx`, line 6935 which calls scipy on these tasks:

```
A = matrix(RDF, [[1, -2], [3, 4]])
B = matrix(RDF, [[0, 7], [2, -3]])
D, P = A.eigenmatrix_left(B)
(P * A - D * P * B).norm() < 1e-14
```
(and a similar at line 7151 (for _right rather than _left).

And it's not just numerical noise:

```
sage: (P * A - D * P * B).norm()
12.951156314021555
sage: P * A - D * P * B
[ 1.1102230246251565e-16     -12.951156314021551]
[-2.7755575615628914e-17 -3.1086244689504383e-15]
```

**Comment by dimpase** [comment]
<div id="comment:8" align="right">comment:8</div>

the 1st of two gen. eigenvectors is wrong.

```
sage: A.eigenvectors_left(B)
[(-2.1075759441619084, [(-0.9905315991237724, 0.1372849268394109)], 1),
 (-0.3922809560592623, [(-0.9668186179746967, 0.2554638133620835)], 1)]
```
vs. the previous version (1.8.1), correct one:

```
sage: A.eigenvectors_left(B)
[(1.8208523846306908, [(-0.5400711566794881, -0.8416193591659354)], 1),
 (-0.39228095605926194, [(-0.9668186179746967, 0.2554638133620835)], 1)]
```

This can be traced down to scipy call:

```
sage:         v, eig = scipy.linalg.eig(A.numpy(),
....:                                   B.numpy(),
....:                                   right=False, left=True,
....:                                   homogeneous_eigvals=False)
sage: v
array([-2.10757594+0.j, -0.39228096+0.j])
sage: eig
array([[-0.9905316 , -1.        ],
       [ 0.13728493,  0.26423138]])
```
vs, correct, previous version:

```
sage: v
array([ 1.82085238+0.j, -0.39228096+0.j])
sage: eig
array([[-0.54007116, -1.        ],
       [-0.84161936,  0.26423138]])
```

**Comment by dimpase** [comment]
Upstream: **Not yet reported upstream; Will do shortly.**

**Comment by dimpase** [comment]
<div id="comment:9" align="right">comment:9</div>

I can reproduce this with "plain" scipy on Gentoo (installed as system Gentoo package)

**Comment by dimpase** [comment]
<div id="comment:10" align="right">comment:10</div>

This is !Gentoo/Sage-specific. If instead of system- (or Sage-)built scipy I use binary wheels from pypi, everything is fine.

The next test will be to try building Sage's scipy on a non-Gentoo system.

**Comment by dimpase** [comment]
<div id="comment:11" align="right">comment:11</div>

cc-ing Gentoo people. On Gentoo-built scipy 1.9.3, one gets incorrect generalised eigenvectors.

```
$ python3
Python 3.10.7 (main, Oct 10 2022, 13:00:40) [GCC 11.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import scipy, numpy
>>> A=numpy.array([[ 1., -2.],[ 3.,  4.]])
>>> B=numpy.array([[ 0.,  7.],[ 2., -3.]])
>>> scipy.linalg.eig(A,B,right=False, left=True, homogeneous_eigvals=False)
(array([-2.10757594+0.j, -0.39228096+0.j]), array([[-0.9905316 , -1.        ],
       [ 0.13728493,  0.26423138]]))
```
instead of correct

```
(array([ 1.82085238+0.j, -0.39228096+0.j]), array([[-0.54007116, -1.        ],
       [-0.84161936,  0.26423138]]))
```

pip-installing binary wheels for numpy ans scipy from PyPI (same versions) produces correct results.

**Comment by dimpase** [comment]
<div id="comment:12" align="right">comment:12</div>

On Fedora 34, everything is fine (with openblas 0.3.19, not sure whether it matters)

**Comment by dimpase** [comment]
<div id="comment:13" align="right">comment:13</div>

Building Sage's OpenBLAS (Gentoo provides an older OpenBLAS, 0.3.20) appears to fix the problem.
Should we ban 0.3.20 ? Anyhow, Gentoo has to fix it.

**Comment by dimpase** [comment]
<div id="comment:14" align="right">comment:14</div>

Submitted https://bugs.gentoo.org/878883

**Comment by dimpase** [comment]
Changed upstream from **Not yet reported upstream; Will do shortly.** to **Reported upstream. No feedback yet.**

**Comment by dimpase** [comment]
Changed upstream from **Reported upstream. No feedback yet.** to **Reported upstream. Developers acknowledge bug.**

**Comment by dimpase** [comment]
<div id="comment:17" align="right">comment:17</div>

Further on arm64 (Apple M1) one gets

```
...
[scipy-1.9.3]   [1224/1224] scipy/io/_harwell_boeing/tests/test_hb.py
[scipy-1.9.3]   Preparing metadata (pyproject.toml): finished with status 'done'
[scipy-1.9.3] Building wheels for collected packages: scipy
[scipy-1.9.3]   Building wheel for scipy (pyproject.toml): started
[scipy-1.9.3]   Running command Building wheel for scipy (pyproject.toml)
[scipy-1.9.3]   Building wheel for scipy (pyproject.toml): finished with status 'done'
[scipy-1.9.3]   Created wheel for scipy: filename=scipy-1.9.3-cp310-cp310-macosx_13_arm64.whl size=21560240 sha256=7f146f5c01cacccb1f543dd03f7852c9fa69832ac83e3438a3054b07ddadf986
[scipy-1.9.3]   Stored in directory: /private/var/folders/81/vt06lnj17rj0cpc9gdshy4q00000gr/T/pip-ephem-wheel-cache-u972yyp0/wheels/07/68/a7/3970e07638c02f51cea93e74047bd18f05b865d87665dddaa5
[scipy-1.9.3] Successfully built scipy
[scipy-1.9.3] WARNING: Skipping scipy as it is not installed.
[scipy-1.9.3] Using pip 22.2.2 from /Volumes/dima/sage/local/var/lib/sage/venv-python3.10/lib/python3.10/site-packages/pip (python 3.10)
[scipy-1.9.3] Looking in links: /Volumes/dima/sage/local/var/lib/sage/venv-python3.10/var/lib/sage/wheels
[scipy-1.9.3] ERROR: scipy-1.9.3-cp310-cp310-macosx_13_arm64.whl is not a supported wheel on this platform.
[scipy-1.9.3] Warning: installing with "python3 -m pip install --verbose --no-index --find-links=/Volumes/dima/sage/local/var/lib/sage/venv-python3.10/var/lib/sage/wheels --disable-pip-version-check --isolated --no-cache-dir" failed. Retrying, adding "--no-deps --ignore-installed --ignore-requires-python"
[scipy-1.9.3] Using pip 22.2.2 from /Volumes/dima/sage/local/var/lib/sage/venv-python3.10/lib/python3.10/site-packages/pip (python 3.10)
[scipy-1.9.3] Looking in links: /Volumes/dima/sage/local/var/lib/sage/venv-python3.10/var/lib/sage/wheels
[scipy-1.9.3] ERROR: scipy-1.9.3-cp310-cp310-macosx_13_arm64.whl is not a supported wheel on this platform.
[scipy-1.9.3] Error: installing with pip  failed
```

**Comment by dimpase** [comment]
<div id="comment:18" align="right">comment:18</div>

upgrading to pip 22.3 does not help

**Comment by mkoeppe** [comment]
<div id="comment:19" align="right">comment:19</div>

Reported in https://github.com/mesonbuild/meson-python/issues/160#issuecomment-1297972659

**Comment by dimpase** [comment]
<div id="comment:20" align="right">comment:20</div>

on intel macOS 13 with Homebrew, I get meson complaining about perfectly OK `gfortran`.

---

update - in fact, Apple's command line tools didn't update themselves, and that was the reason for this error. Sorry for noise.

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
<div id="comment:22"></div>

Branch pushed to git repo; I updated commit sha1. New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/5fc95bdf1c57de290a993be8a7a7f0328f5e5032"><code>5fc95bd</code></a></td><td><code>Merge tag '9.8.beta3' into t/34658/update_numpy_to_1_23_4</code></td></tr><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/313d0fdf8e25e3799df87840e2efc5852acb750c"><code>313d0fd</code></a></td><td><code>build/pkgs/networkx: Update to 2.8.8</code></td></tr><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/3706d5dcc8a0f9de4d635d2fc9b7f2b6814d91ac"><code>3706d5d</code></a></td><td><code>build/pkgs/meson_python/patches: Add https://github.com/mesonbuild/meson-python/pull/202</code></td></tr></table>

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
Changed commit from **[`ba5c196`](https://github.com/sagemath/sagetrac-mirror/commit/ba5c196223aa96014e0e138711f26d8238f3841b)** to **[`3706d5d`](https://github.com/sagemath/sagetrac-mirror/commit/3706d5dcc8a0f9de4d635d2fc9b7f2b6814d91ac)**

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
<div id="comment:25"></div>

Branch pushed to git repo; I updated commit sha1. This was a forced push. New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/e9590f5c24b32e2c69dcd29553ae522d37bbfdcb"><code>e9590f5</code></a></td><td><code>build/pkgs/meson_python: Update to 0.11.0</code></td></tr><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/bbf5f95fc58782b544514959c9199ffb68060575"><code>bbf5f95</code></a></td><td><code>build/pkgs/numpy: Update to 1.23.5</code></td></tr></table>

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
Changed commit from **[`3706d5d`](https://github.com/sagemath/sagetrac-mirror/commit/3706d5dcc8a0f9de4d635d2fc9b7f2b6814d91ac)** to **[`bbf5f95`](https://github.com/sagemath/sagetrac-mirror/commit/bbf5f95fc58782b544514959c9199ffb68060575)**

**Comment by mkoeppe** [comment]
<div id="comment:26"></div>

New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/e9590f5c24b32e2c69dcd29553ae522d37bbfdcb"><code>e9590f5</code></a></td><td><code>build/pkgs/meson_python: Update to 0.11.0</code></td></tr><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/bbf5f95fc58782b544514959c9199ffb68060575"><code>bbf5f95</code></a></td><td><code>build/pkgs/numpy: Update to 1.23.5</code></td></tr></table>

**Comment by mkoeppe** [comment]
Changed upstream from **Reported upstream. Developers acknowledge bug.** to **Fixed upstream, in a later stable release.**

**Comment by mkoeppe** [comment]
Description changed:
``````diff
--- 
+++ 
@@ -1,3 +1,6 @@
 https://github.com/numpy/numpy/releases/tag/v1.23.4
 
 https://docs.scipy.org/doc/scipy/release.1.9.3.html
+
+https://meson-python.readthedocs.io/en/latest/changelog.html#changelog
+
``````

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
<div id="comment:27"></div>

Branch pushed to git repo; I updated commit sha1. New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/d74528c0c41e6368c14274817337d011ae24a6f7"><code>d74528c</code></a></td><td><code>Merge tag '9.8.beta4' into t/34658/update_numpy_to_1_23_4</code></td></tr></table>

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
Changed commit from **[`bbf5f95`](https://github.com/sagemath/sagetrac-mirror/commit/bbf5f95fc58782b544514959c9199ffb68060575)** to **[`d74528c`](https://github.com/sagemath/sagetrac-mirror/commit/d74528c0c41e6368c14274817337d011ae24a6f7)**

**Comment by jhpalmieri** [comment]
<div id="comment:29" align="right">comment:29</div>

On OS X M2, `scipy` fails some tests in its test suite, but installation succeeds anyway, not sure why.

```
=========================== short test summary info ============================
FAILED linalg/tests/test_solvers.py::test_solve_discrete_are - AssertionError: 
FAILED optimize/tests/test_linprog.py::TestLinprogIPSparse::test_bug_6139 - A...
FAILED optimize/tests/test_linprog.py::TestLinprogIPSparsePresolve::test_bug_6139
FAILED sparse/linalg/_isolve/tests/test_iterative.py::test_maxiter_worsening[gmres]
= 4 failed, 37207 passed, 3314 skipped, 12061 deselected, 136 xfailed, 12 xpassed, 326 warnings in 515.97s (0:08:35) =
```

**Comment by jhpalmieri** [comment]
<div id="comment:30" align="right">comment:30</div>

Test suite passes on OS X Intel.

**Comment by mkoeppe** [comment]
<div id="comment:31" align="right">comment:31</div>

One of them may be https://github.com/scipy/scipy/issues/16926

**Comment by jhpalmieri** [comment]
<div id="comment:32" align="right">comment:32</div>

I would prefer that a failing test suite meant a failed installation, but maybe `python3 -c 'import scipy; scipy.test()'` doesn't return a nonzero code if it fails.

**Comment by mkoeppe** [comment]
<div id="comment:33" align="right">comment:33</div>

I agree, we should fix this.

**Comment by jhpalmieri** [comment]
<div id="comment:34" align="right">comment:34</div>

Maybe we should merge this now and patch things up in follow-up tickets, since I (for one) can't build the most recent beta without this. Are there other issues that should be addressed on this ticket?

**Comment by jhpalmieri** [comment]
<div id="comment:35" align="right">comment:35</div>

(I took a quick glance at the `scipy` code, and it looks like it's trying to return different exit codes. It was only a very quick glance, though.)

**Comment by mkoeppe** [comment]
<div id="comment:36" align="right">comment:36</div>

Tests for Linux are still running at https://github.com/mkoeppe/sage/actions/runs/3519527763

**Comment by mkoeppe** [comment]
<div id="comment:38" align="right">comment:38</div>

There is a problem on `archlinux-standard` related to scipy; that is unchanged by this upgrade. That's #34779

**Comment by mkoeppe** [comment]
<div id="comment:39" align="right">comment:39</div>

The other Linux platforms look fine.

**Comment by jhpalmieri** [comment]
Changed reviewer from **https://github.com/mkoeppe/sage/actions/runs/3251926884** to **John Palmieri**

**Comment by jhpalmieri** [comment]
<div id="comment:40" align="right">comment:40</div>

Okay, then let's proceed here.

**Comment by mkoeppe** [comment]
<div id="comment:41" align="right">comment:41</div>

Thanks!

**Comment by dimpase** [comment]
<div id="comment:42" align="right">comment:42</div>

blocker, as on a recent macOS one cannot build scipy (1.9.20.

**Comment by vbraun** [comment]
Changed branch from **[u/mkoeppe/update_numpy_to_1_23_4](https://github.com/sagemath/sagetrac-mirror/tree/u/mkoeppe/update_numpy_to_1_23_4)** to **[`d74528c`](https://github.com/sagemath/sagetrac-mirror/commit/d74528c0c41e6368c14274817337d011ae24a6f7)**
