### ISSUE TITLE
some details in Brandt modules

### ISSUE THREAD

**Issue by fchapoton** [sagemath/sage#34667]
<div id="comment:0"></div>

fixing one lgtm warning about `QQ[[var]]`

CC:  @tscrim @slel @kwankyu @kliem @mantepse

Component: **modular forms**

Author: **Frédéric Chapoton**

Branch/Commit: **[`9080ed5`](https://github.com/sagemath/sagetrac-mirror/commit/9080ed5a295e04d273d165be689eebdef8578a10)**

Reviewer: **Travis Scrimshaw**

_Issue created by migration from https://trac.sagemath.org/ticket/34667_

**Comment by fchapoton** [comment]
<div id="comment:1"></div>

New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/9080ed5a295e04d273d165be689eebdef8578a10"><code>9080ed5</code></a></td><td><code>a few details in Brandt modules</code></td></tr></table>

**Comment by fchapoton** [comment]
Commit: **[`9080ed5`](https://github.com/sagemath/sagetrac-mirror/commit/9080ed5a295e04d273d165be689eebdef8578a10)**

**Comment by fchapoton** [comment]
Branch: **[u/chapoton/34667](https://github.com/sagemath/sagetrac-mirror/tree/u/chapoton/34667)**

**Comment by fchapoton** [comment]
<div id="comment:2" align="right">comment:2</div>

green lights, so please review (easy one)

**Comment by tscrim** [comment]
Reviewer: **Travis Scrimshaw**

**Comment by tscrim** [comment]
<div id="comment:3" align="right">comment:3</div>

LGTM.

**Comment by vbraun** [comment]
Changed branch from **[u/chapoton/34667](https://github.com/sagemath/sagetrac-mirror/tree/u/chapoton/34667)** to **[`9080ed5`](https://github.com/sagemath/sagetrac-mirror/commit/9080ed5a295e04d273d165be689eebdef8578a10)**
