### ISSUE TITLE
Fix a doctest failure due to a small numerical issue on 32 bit maxima-sbcl

### ISSUE THREAD

**Issue by tornaria** [sagemath/sage#34669]
<div id="comment:0"></div>

This only triggers when running maxima-sbcl on 32 bit, which gives:

```    
sage: maxima('exp(-sqrt(x))').nintegral('x',0,1)
(0.5284822353142306, 4.163291933423352e-11, 231, 0)
```
 
Compare to the "normal" result (64 bit, maxima-ecl on 32 bit):

```    
sage: maxima('exp(-sqrt(x))').nintegral('x',0,1)
(0.5284822353142306, 4.163314137883845e-11, 231, 0)
```

Since the difference is in the bound for the error in the numerical integration, it doesn't seem very important.

Component: **numerical**

Author: **Gonzalo Tornaría**

Branch/Commit: **[`30259c6`](https://github.com/sagemath/sagetrac-mirror/commit/30259c6c8a695c528e48b9e6bd9e18eb8a67eab3)**

Reviewer: **Frédéric Chapoton**

_Issue created by migration from https://trac.sagemath.org/ticket/34669_

**Comment by tornaria** [comment]
Commit: **[`30259c6`](https://github.com/sagemath/sagetrac-mirror/commit/30259c6c8a695c528e48b9e6bd9e18eb8a67eab3)**

**Comment by tornaria** [comment]
<div id="comment:1"></div>

New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/30259c6c8a695c528e48b9e6bd9e18eb8a67eab3"><code>30259c6</code></a></td><td><code>Fix a doctest failure due to a small numerical issue</code></td></tr></table>

**Comment by tornaria** [comment]
Branch: **[u/tornaria/doctest_numerical_fix](https://github.com/sagemath/sagetrac-mirror/tree/u/tornaria/doctest_numerical_fix)**

**Comment by fchapoton** [comment]
<div id="comment:2" align="right">comment:2</div>

ok

**Comment by fchapoton** [comment]
Reviewer: **Frédéric Chapoton**

**Comment by vbraun** [comment]
Changed branch from **[u/tornaria/doctest_numerical_fix](https://github.com/sagemath/sagetrac-mirror/tree/u/tornaria/doctest_numerical_fix)** to **[`30259c6`](https://github.com/sagemath/sagetrac-mirror/commit/30259c6c8a695c528e48b9e6bd9e18eb8a67eab3)**
