### ISSUE TITLE
fix E502 in modular

### ISSUE THREAD

**Issue by fchapoton** [sagemath/sage#34660]
<div id="comment:0"></div>

this is about

E502 the backslash is redundant between brackets

CC:  @tscrim @kwankyu @kliem @slel

Component: **refactoring**

Author: **Frédéric Chapoton**

Branch/Commit: **[`0f27e53`](https://github.com/sagemath/sagetrac-mirror/commit/0f27e53660c5ddcdf97dcf6ce194064ea1ca0371)**

Reviewer: **Travis Scrimshaw**

_Issue created by migration from https://trac.sagemath.org/ticket/34660_

**Comment by fchapoton** [comment]
Commit: **[`0f27e53`](https://github.com/sagemath/sagetrac-mirror/commit/0f27e53660c5ddcdf97dcf6ce194064ea1ca0371)**

**Comment by fchapoton** [comment]
Branch: **[u/chapoton/34660](https://github.com/sagemath/sagetrac-mirror/tree/u/chapoton/34660)**

**Comment by fchapoton** [comment]
<div id="comment:1"></div>

New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/0f27e53660c5ddcdf97dcf6ce194064ea1ca0371"><code>0f27e53</code></a></td><td><code>fix E502 in modular/</code></td></tr></table>

**Comment by fchapoton** [comment]
<div id="comment:2" align="right">comment:2</div>

bot and lights are morally green, so please review

**Comment by tscrim** [comment]
<div id="comment:3" align="right">comment:3</div>

LGTM.

**Comment by tscrim** [comment]
Reviewer: **Travis Scrimshaw**

**Comment by vbraun** [comment]
Changed branch from **[u/chapoton/34660](https://github.com/sagemath/sagetrac-mirror/tree/u/chapoton/34660)** to **[`0f27e53`](https://github.com/sagemath/sagetrac-mirror/commit/0f27e53660c5ddcdf97dcf6ce194064ea1ca0371)**
