### ISSUE TITLE
openssl spkg-configure.m4: Also require openssl if curl needs to be built

### ISSUE THREAD

**Issue by mkoeppe** [sagemath/sage#34665]
<div id="comment:0"></div>

Seen in `opensuse-15.3-gcc_11-python3.9`: 
https://github.com/mkoeppe/sage/actions/runs/3251926884/jobs/5344443553

```
  [curl-7.84.0]   checking for openssl options with pkg-config... no
  [curl-7.84.0]   checking for HMAC_Update in -lcrypto... no
  [curl-7.84.0]   checking for HMAC_Init_ex in -lcrypto... no
  [curl-7.84.0]   checking OpenSSL linking with -ldl... no
  [curl-7.84.0]   checking OpenSSL linking with -ldl and -lpthread... no
  [curl-7.84.0]   configure: OPT_OPENSSL: yes
  [curl-7.84.0]   configure: OPENSSL_ENABLED: 
  [curl-7.84.0]   configure: error: --with-openssl was given but OpenSSL could not be detected
  [curl-7.84.0]   ********************************************************************************
```

Depends on #32182

CC:  @sagetrac-tmonteil @dimpase @orlitzky

Component: **build: configure**

Author: **Matthias Koeppe**

Branch/Commit: **[`b39ffd2`](https://github.com/sagemath/sagetrac-mirror/commit/b39ffd2e38fe788cc674c8be22d2cbe946d2f4ab)**

Reviewer: **Dima Pasechnik**

_Issue created by migration from https://trac.sagemath.org/ticket/34665_

**Comment by mkoeppe** [comment]
Branch: **[u/mkoeppe/openssl_spkg_configure_m4__also_require_openssl_if_curl_needs_to_be_built](https://github.com/sagemath/sagetrac-mirror/tree/u/mkoeppe/openssl_spkg_configure_m4__also_require_openssl_if_curl_needs_to_be_built)**

**Comment by mkoeppe** [comment]
<div id="comment:2" align="right">comment:2</div>

Tested successfully using `tox -e docker-opensuse-15.3-gcc_11-python3.9-minimal -- curl`

---
New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/b39ffd2e38fe788cc674c8be22d2cbe946d2f4ab"><code>b39ffd2</code></a></td><td><code>build/pkgs/openssl/spkg-configure.m4: Also require openssl if curl needs to be built</code></td></tr></table>

**Comment by mkoeppe** [comment]
Commit: **[`b39ffd2`](https://github.com/sagemath/sagetrac-mirror/commit/b39ffd2e38fe788cc674c8be22d2cbe946d2f4ab)**

**Comment by mkoeppe** [comment]
Dependencies: **#32182**

**Comment by mkoeppe** [comment]
Author: **Matthias Koeppe**

**Comment by mkoeppe** [comment]
<div id="comment:6" align="right">comment:6</div>

Let's get this in please

**Comment by dimpase** [comment]
<div id="comment:7" align="right">comment:7</div>

Can we refactor this using `SAGE_SPKG_DEPCHECK` ?

**Comment by mkoeppe** [comment]
<div id="comment:8" align="right">comment:8</div>

No, that's an unrelated mechanism.

**Comment by dimpase** [comment]
Reviewer: **Dima Pasechnik**

**Comment by dimpase** [comment]
<div id="comment:9" align="right">comment:9</div>

ok

**Comment by mkoeppe** [comment]
<div id="comment:10" align="right">comment:10</div>

Thanks!

**Comment by vbraun** [comment]
Changed branch from **[u/mkoeppe/openssl_spkg_configure_m4__also_require_openssl_if_curl_needs_to_be_built](https://github.com/sagemath/sagetrac-mirror/tree/u/mkoeppe/openssl_spkg_configure_m4__also_require_openssl_if_curl_needs_to_be_built)** to **[`b39ffd2`](https://github.com/sagemath/sagetrac-mirror/commit/b39ffd2e38fe788cc674c8be22d2cbe946d2f4ab)**
