### ISSUE TITLE
some details in desolvers

### ISSUE THREAD

**Issue by fchapoton** [sagemath/sage#34663]
<div id="comment:0"></div>

about code and code formatting

CC:  @tscrim @kwankyu @dcoudert @orlitzky

Component: **calculus**

Author: **Frédéric Chapoton**

Branch/Commit: **[u/chapoton/34663](https://github.com/sagemath/sagetrac-mirror/tree/u/chapoton/34663) @ [`7f3c2b5`](https://github.com/sagemath/sagetrac-mirror/commit/7f3c2b5d10097ba53fa700a69b1ff408bc0cc1a4)**

Reviewer: **Matthias Koeppe, David Coudert**

_Issue created by migration from https://trac.sagemath.org/ticket/34663_

**Comment by fchapoton** [comment]
Branch: **[u/chapoton/34663](https://github.com/sagemath/sagetrac-mirror/tree/u/chapoton/34663)**

**Comment by fchapoton** [comment]
<div id="comment:1"></div>

New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/59f6fa7d7af978e488c9014292a9f3f27d4a0bd9"><code>59f6fa7</code></a></td><td><code>some details in desolvers</code></td></tr></table>

**Comment by fchapoton** [comment]
Commit: **[`59f6fa7`](https://github.com/sagemath/sagetrac-mirror/commit/59f6fa7d7af978e488c9014292a9f3f27d4a0bd9)**

**Comment by mkoeppe** [comment]
<div id="comment:2" align="right">comment:2</div>

This works, but how about getting rid of the use of `tmp_dir` in this file (see #33213)?

Also:

```
+    subprocess.check_call(f'gcc -o {runmefile} ' + os.path.join(tempdir, '*.c ') +
```
Because this command is processed by the shell, `runmefile` should be run through `shlex.quote`

```
+                          os.path.join('$SAGE_LOCAL', 'lib', 'libTIDES.a') + ' $LDFLAGS ' +
+                          os.path.join('-L$SAGE_LOCAL', 'lib ') + '-lmpfr -lgmp -lm  -O2 -w ' +
+                          os.path.join('-I$SAGE_LOCAL', 'include '),
+                          shell=True, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
+    subprocess.check_call(tempdir / 'runme', shell=True, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
```
`tempdir / 'runme'` can be replaced by `runmefile`

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
<div id="comment:3"></div>

Branch pushed to git repo; I updated commit sha1. New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/b11ec7fec1ce0d912848d3e8937bc1a800eae4ac"><code>b11ec7f</code></a></td><td><code>using shlex.quote</code></td></tr></table>

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
Changed commit from **[`59f6fa7`](https://github.com/sagemath/sagetrac-mirror/commit/59f6fa7d7af978e488c9014292a9f3f27d4a0bd9)** to **[`b11ec7f`](https://github.com/sagemath/sagetrac-mirror/commit/b11ec7fec1ce0d912848d3e8937bc1a800eae4ac)**

**Comment by fchapoton** [comment]
<div id="comment:4" align="right">comment:4</div>

now using `shlex.quote`

still using `tmp_dir`, to be changed rather in another ticket

**Comment by mkoeppe** [comment]
<div id="comment:5" align="right">comment:5</div>


```
+    subprocess.check_call(f'gcc -o {quote(runmefile)} ' + os.path.join(tempdir, '*.c ') +
+                          os.path.join('$SAGE_LOCAL', 'lib', 'libTIDES.a') + ' $LDFLAGS ' +
+                          os.path.join('-L$SAGE_LOCAL', 'lib ') + '-lmpfr -lgmp -lm  -O2 -w ' +
+                          os.path.join('-I$SAGE_LOCAL', 'include '),
+                          shell=True, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
```
Likewise `tempdir` (but not "*.c") needs to be shell-quoted. 
And strings with trailing space such as `'lib '` should really not be passed to os.path.join

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
Changed commit from **[`b11ec7f`](https://github.com/sagemath/sagetrac-mirror/commit/b11ec7fec1ce0d912848d3e8937bc1a800eae4ac)** to **[`3c78d9f`](https://github.com/sagemath/sagetrac-mirror/commit/3c78d9f5bd740ef5f1949fca12f851785ec92b9a)**

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
<div id="comment:6"></div>

Branch pushed to git repo; I updated commit sha1. New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/dbeeb2d77519b2aa13d4d82b8628df30598bbc5d"><code>dbeeb2d</code></a></td><td><code>Merge branch 'u/chapoton/34663' in 9.8.b2</code></td></tr><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/3c78d9f5bd740ef5f1949fca12f851785ec92b9a"><code>3c78d9f</code></a></td><td><code>more details in desolvers</code></td></tr></table>

**Comment by fchapoton** [comment]
<div id="comment:7" align="right">comment:7</div>

better now ?

**Comment by mkoeppe** [comment]
<div id="comment:8" align="right">comment:8</div>

Yes, better, but there's still another one of these:

```
+                          os.path.join('-I$SAGE_LOCAL', 'include '),
```

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
<div id="comment:9"></div>

Branch pushed to git repo; I updated commit sha1. New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/aaaed1cf68bc3b8d53e15123a247e3e5b24ddd6f"><code>aaaed1c</code></a></td><td><code>one more fix</code></td></tr></table>

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
Changed commit from **[`3c78d9f`](https://github.com/sagemath/sagetrac-mirror/commit/3c78d9f5bd740ef5f1949fca12f851785ec92b9a)** to **[`aaaed1c`](https://github.com/sagemath/sagetrac-mirror/commit/aaaed1cf68bc3b8d53e15123a247e3e5b24ddd6f)**

**Comment by fchapoton** [comment]
<div id="comment:10" align="right">comment:10</div>

done

**Comment by mkoeppe** [comment]
Reviewer: **Matthias Koeppe**

**Comment by vbraun** [comment]
<div id="comment:12" align="right">comment:12</div>


```
**********************************************************************
File "src/sage/calculus/desolvers.py", line 1770, in sage.calculus.desolvers.desolve_mintides
Failed example:
    sol = desolve_mintides(f, ics, 0, t, t, 1e-12, 1e-12) # optional -tides
Exception raised:
    Traceback (most recent call last):
      File "/var/lib/buildbot/slave/sage_git/build/src/sage/doctest/forker.py", line 695, in _run
        self.compile_and_execute(example, compiler, test.globs)
      File "/var/lib/buildbot/slave/sage_git/build/src/sage/doctest/forker.py", line 1093, in compile_and_execute
        exec(compiled, globs)
      File "<doctest sage.calculus.desolvers.desolve_mintides[4]>", line 1, in <module>
        sol = desolve_mintides(f, ics, Integer(0), t, t, RealNumber('1e-12'), RealNumber('1e-12')) # optional -tides
      File "/var/lib/buildbot/slave/sage_git/build/src/sage/calculus/desolvers.py", line 1807, in desolve_mintides
        genfiles_mintides(intfile, drfile, f, [N(_) for _ in ics], N(initial), N(final), N(delta), N(tolrel),
      File "/var/lib/buildbot/slave/sage_git/build/src/sage/interfaces/tides.py", line 635, in genfiles_mintides
        outfile.write('\tstrcpy(ofname, "'+ output +'");\n')
    TypeError: can only concatenate str (not "PosixPath") to str
**********************************************************************
```

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
<div id="comment:13"></div>

Branch pushed to git repo; I updated commit sha1. New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/f87d61b1817a4cb05214204423085b656e48d56e"><code>f87d61b</code></a></td><td><code>Merge branch 'u/chapoton/34663' in 9.8.b3</code></td></tr><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/c56f8fc717f22f2bfc5e11d2f42062bc27932bca"><code>c56f8fc</code></a></td><td><code>allow PosixPath or string as output</code></td></tr></table>

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
Changed commit from **[`aaaed1c`](https://github.com/sagemath/sagetrac-mirror/commit/aaaed1cf68bc3b8d53e15123a247e3e5b24ddd6f)** to **[`c56f8fc`](https://github.com/sagemath/sagetrac-mirror/commit/c56f8fc717f22f2bfc5e11d2f42062bc27932bca)**

**Comment by fchapoton** [comment]
<div id="comment:14" align="right">comment:14</div>

should be fixed now

**Comment by fchapoton** [comment]
<div id="comment:15" align="right">comment:15</div>

green lights, so please review

**Comment by dcoudert** [comment]
Changed reviewer from **Matthias Koeppe** to **Matthias Koeppe, David Coudert**

**Comment by dcoudert** [comment]
<div id="comment:16" align="right">comment:16</div>

LGTM (and doc builds well).

**Comment by vbraun** [comment]
Changed branch from **[u/chapoton/34663](https://github.com/sagemath/sagetrac-mirror/tree/u/chapoton/34663)** to **[`c56f8fc`](https://github.com/sagemath/sagetrac-mirror/commit/c56f8fc717f22f2bfc5e11d2f42062bc27932bca)**

**Comment by vbraun** [comment]
Changed branch from **[`c56f8fc`](https://github.com/sagemath/sagetrac-mirror/commit/c56f8fc717f22f2bfc5e11d2f42062bc27932bca)** to **[u/chapoton/34663](https://github.com/sagemath/sagetrac-mirror/tree/u/chapoton/34663)**

**Comment by vbraun** [comment]
<div id="comment:18" align="right">comment:18</div>

Doesn't work if tides is installed:

```
**********************************************************************
File "src/sage/calculus/desolvers.py", line 1770, in sage.calculus.desolvers.desolve_mintides
Failed example:
    sol = desolve_mintides(f, ics, 0, t, t, 1e-12, 1e-12) # optional -tides
Exception raised:
    Traceback (most recent call last):
      File "/var/lib/buildbot/slave/sage_git/build/src/sage/doctest/forker.py", line 695, in _run
        self.compile_and_execute(example, compiler, test.globs)
      File "/var/lib/buildbot/slave/sage_git/build/src/sage/doctest/forker.py", line 1093, in compile_and_execute
        exec(compiled, globs)
      File "<doctest sage.calculus.desolvers.desolve_mintides[4]>", line 1, in <module>
        sol = desolve_mintides(f, ics, Integer(0), t, t, RealNumber('1e-12'), RealNumber('1e-12')) # optional -tides
      File "/var/lib/buildbot/slave/sage_git/build/src/sage/calculus/desolvers.py", line 1814, in desolve_mintides
        subprocess.check_call(runmefile, shell=True, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
      File "/var/lib/buildbot/slave/sage_git/build/local/var/lib/sage/venv-python3.10.8/lib/python3.10/subprocess.py", line 364, in check_call
        retcode = call(*popenargs, **kwargs)
      File "/var/lib/buildbot/slave/sage_git/build/local/var/lib/sage/venv-python3.10.8/lib/python3.10/subprocess.py", line 345, in call
        with Popen(*popenargs, **kwargs) as p:
      File "/var/lib/buildbot/slave/sage_git/build/local/var/lib/sage/venv-python3.10.8/lib/python3.10/subprocess.py", line 971, in __init__
        self._execute_child(args, executable, preexec_fn, close_fds,
      File "/var/lib/buildbot/slave/sage_git/build/local/var/lib/sage/venv-python3.10.8/lib/python3.10/subprocess.py", line 1702, in _execute_child
        raise TypeError('path-like args is not allowed when '
    TypeError: path-like args is not allowed when shell is true
**********************************************************************
```

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
Changed commit from **[`c56f8fc`](https://github.com/sagemath/sagetrac-mirror/commit/c56f8fc717f22f2bfc5e11d2f42062bc27932bca)** to **[`7f3c2b5`](https://github.com/sagemath/sagetrac-mirror/commit/7f3c2b5d10097ba53fa700a69b1ff408bc0cc1a4)**

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
<div id="comment:19"></div>

Branch pushed to git repo; I updated commit sha1. New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/23fdb8355f3350da7e5d423108a0da7eb0245b64"><code>23fdb83</code></a></td><td><code>Merge branch 'u/chapoton/34663' in 9.8.beta4</code></td></tr><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/7f3c2b5d10097ba53fa700a69b1ff408bc0cc1a4"><code>7f3c2b5</code></a></td><td><code>back to using string for runmefile</code></td></tr></table>

**Comment by fchapoton** [comment]
<div id="comment:20" align="right">comment:20</div>

I tried to fix that, but now it seems to be failing.
