### ISSUE TITLE
Your GitHub account name is needed by Oct 29 for our Trac->GitHub migration

### ISSUE THREAD

**Issue by mkoeppe** [sagemath/sage#34664]
<div id="comment:0"></div>

Sage development will soon move from Trac to Github! This was decided in a [vote on sage-devel](https://groups.google.com/g/sage-devel/c/7h5JoRgHpxY) that closed on Oct 5, 2022. The migration work is coordinated in #30363.

The migration will convert all Trac tickets, including all comments, to GitHub Issues. 

We intend to attribute all comments of a Trac user to a corresponding GitHub account; but comments by Trac users for whom we do not have will be represented by a placeholder account.

You are cc'd here because we do not have your GitHub account on file. If you do not have one yet, now is a great time to open one.

Let us know:
- **preferably** by updating your contributor information at https://github.com/sagemath/website/blob/master/conf/contributors.xml; this information is presented in https://www.sagemath.org/development-map.html
- or by posting a comment here (but then you will receive emails when others post comments here too...)

CC:  @kwankyu @dimpase

Component: **website/wiki**

_Issue created by migration from https://trac.sagemath.org/ticket/34664_

**Comment by 75dcd244-d814-46b4-9d15-0253ba4f9020** [comment]
<div id="comment:1" align="right">comment:1</div>

Github username: itaibn 

https://github.com/itaibn/

**Comment by jdchristensen** [comment]
<div id="comment:2" align="right">comment:2</div>

I'm jdc on trac and jdchristensen on github.  Sorry, it wasn't clear to me how to update that xml file.

**Comment by hemmecke** [comment]
<div id="comment:3" align="right">comment:3</div>

hemmecke on github

**Comment by mkoeppe** [comment]
Description changed:
``````diff
--- 
+++ 
@@ -7,7 +7,7 @@
 You are cc'd here because we do not have your GitHub account on file. If you do not have one yet, now is a great time to open one.
 
 Let us know 
-- either by updating your contributor information at https://github.com/sagemath/website/blob/master/conf/contributors.xml; this information is presented in https://www.sagemath.org/development-map.html
+- either by updating your contributor information at https://github.com/sagemath/website/blob/master/conf/contributors.xml (click the "edit" symbol - this leads to opening a Pull Request); this information is presented in https://www.sagemath.org/development-map.html
 - or by just posting a comment here.
 
 
``````

**Comment by DrXyzzy** [comment]
<div id="comment:5" align="right">comment:5</div>

trac: hsnyder   github: https://github.com/DrXyzzy

**Comment by DrXyzzy** [comment]
Description changed:
``````diff
--- 
+++ 
@@ -7,7 +7,7 @@
 You are cc'd here because we do not have your GitHub account on file. If you do not have one yet, now is a great time to open one.
 
 Let us know 
-- either by updating your contributor information at https://github.com/sagemath/website/blob/master/conf/contributors.xml (click the "edit" symbol - this leads to opening a Pull Request); this information is presented in https://www.sagemath.org/development-map.html
+- either by updating your contributor information at https://github.com/sagemath/website/blob/master/conf/contributors.xml; this information is presented in https://www.sagemath.org/development-map.html
 - or by just posting a comment here.
 
 
``````

**Comment by monien** [comment]
<div id="comment:6" align="right">comment:6</div>

I am hmonien on trac 

GitHub username: monien 

https://github.com/monien

**Comment by tobihan** [comment]
<div id="comment:7" align="right">comment:7</div>

thansen on trac, tobihan on github

**Comment by bdba68b0-6998-4b11-97bd-1e93cfe969fa** [comment]
<div id="comment:8" align="right">comment:8</div>

I am ralfarogit on Github

**Comment by monien** [comment]
<div id="comment:11" align="right">comment:11</div>

## DO NOT SUBMIT CHANGES HERE

An e-mail is send out to all sage developers for each change! 

This results in roughly 350 x 350 unnecessary e-mails! 

There must be a better way to do this!

**Comment by jondo** [comment]
<div id="comment:12" align="right">comment:12</div>

jondo on Github

**Comment by mkoeppe** [comment]
<div id="comment:15" align="right">comment:15</div>

Replying to [Hartmut Monien](#comment%3A11):
> There must be a better way to do this!

Yes, as explained in the ticket description.

**Comment by 9f454552-d428-44f9-82a9-eab419fc7f8a** [comment]
<div id="comment:16" align="right">comment:16</div>

IrenePasquinelli is my github

**Comment by greg-minshall** [comment]
<div id="comment:18" align="right">comment:18</div>

minshall --> greg-minshall

**Comment by peterjeremy** [comment]
<div id="comment:19" align="right">comment:19</div>

I (Peter Jeremy) am `pjeremy` on trac & `peterjeremy` on github.

**Comment by tjl** [comment]
<div id="comment:20" align="right">comment:20</div>

tjlahey on trac & tjl on github

**Comment by asbuch** [comment]
<div id="comment:21" align="right">comment:21</div>

asbuch on trac, asbuch on github.

**Comment by Lazza** [comment]
<div id="comment:22" align="right">comment:22</div>

My [GitHub](../wiki/GitHub) username is Lazza

**Comment by ayyer** [comment]
<div id="comment:23" align="right">comment:23</div>

My Github username is ayyer.

**Comment by zimmermann6** [comment]
<div id="comment:24" align="right">comment:24</div>

trac login zimmerma, github login zimmermann6

**Comment by haaninjo** [comment]
<div id="comment:25" align="right">comment:25</div>

AJonsson on trac, haaninjo on github

**Comment by frederichan-IMJPRG** [comment]
<div id="comment:26" align="right">comment:26</div>

frederichan on trac, frederichan-IMJPRG on github

**Comment by 4c8b67d1-a796-4678-b0f7-077d0eb6abcb** [comment]
<div id="comment:27" align="right">comment:27</div>

On trac : falque
On [GitHub](../wiki/GitHub) : Justine Falque https://github.com/falque

**Comment by mstreng** [comment]
<div id="comment:28" align="right">comment:28</div>

mstreng on both trac and github

**Comment by nadialafreniere** [comment]
<div id="comment:29" align="right">comment:29</div>

nadialafreniere on both Github and Trac

**Comment by RBKreckel** [comment]
<div id="comment:30" align="right">comment:30</div>

trac login rbk, github login RBKreckel

**Comment by mkauers** [comment]
<div id="comment:31" align="right">comment:31</div>

trac login mkauers => github login mkauers

**Comment by staroste** [comment]
<div id="comment:32" align="right">comment:32</div>

trac: sstarosta github: staroste

**Comment by mstreng** [comment]
<div id="comment:33" align="right">comment:33</div>

Apparently the fact that we've been removed from the cc box does not mean that we don't get emails after posting a message here. So unless you want to get hundred's of emails, you should heed Hartmut's advice:

Replying to [Hartmut Monien](#comment%3A11):
> 
> ## DO NOT SUBMIT CHANGES HERE
>
>

**Comment by MatthieuDien** [comment]
<div id="comment:34" align="right">comment:34</div>

trac : MatthieuDien
github : MatthieuDien

**Comment by DanGrayson** [comment]
<div id="comment:35" align="right">comment:35</div>

I'm DanGrayson on github

**Comment by mkoeppe** [comment]
Description changed:
``````diff
--- 
+++ 
@@ -6,9 +6,9 @@
 
 You are cc'd here because we do not have your GitHub account on file. If you do not have one yet, now is a great time to open one.
 
-Let us know 
-- either by updating your contributor information at https://github.com/sagemath/website/blob/master/conf/contributors.xml; this information is presented in https://www.sagemath.org/development-map.html
-- or by just posting a comment here.
+Let us know:
+- **preferably** by updating your contributor information at https://github.com/sagemath/website/blob/master/conf/contributors.xml; this information is presented in https://www.sagemath.org/development-map.html
+- or by posting a comment here (but then you will receive emails when others post comments here too...)
 
 
 
``````

**Comment by SmoothDragon** [comment]
<div id="comment:38" align="right">comment:38</div>

trac: TomDraper github: SmoothDragon

**Comment by janmedlock** [comment]
<div id="comment:39" align="right">comment:39</div>

GitHub name: janmedlock

**Comment by eduenez** [comment]
<div id="comment:40" align="right">comment:40</div>

GitHub name: eduenez

**Comment by c4796b8b-df47-4c78-a415-d934347608f6** [comment]
<div id="comment:41" align="right">comment:41</div>

contributors.xml already has my github username, under 'url=""'

**Comment by mkoeppe** [comment]
<div id="comment:42" align="right">comment:42</div>

Replying to [Ximin Luo](#comment%3A41):
> contributors.xml already has my github username, under 'url=""'

Thanks, I've taken care of it in https://github.com/sagemath/website/pull/407

**Comment by msoos** [comment]
<div id="comment:43" align="right">comment:43</div>

GitHub name: msoos

**Comment by 188546cd-a485-46fd-ae74-488a1552fab0** [comment]
<div id="comment:44" align="right">comment:44</div>

trac: minz
github: mminzlaff

**Comment by d8d8a735-79e9-4a06-88a2-82260631ff64** [comment]
<div id="comment:45" align="right">comment:45</div>

trac: skirpichev github: skirpichev

**Comment by ce85a077-107c-4e69-bc86-120dab630e01** [comment]
<div id="comment:46" align="right">comment:46</div>

I'm amypang on Github, thanks.

**Comment by kwankyu** [comment]
<div id="comment:47" align="right">comment:47</div>

We are closing this ticket. Latecomers with a [GitHub](../wiki/GitHub) account are cordially directed to 

https://groups.google.com/g/sage-devel/c/-mGnxVr9z1c
