### ISSUE TITLE
sage.combinat.permutation.from_cycles produces wrong result when 'cycles' is a generator

### ISSUE THREAD

**Issue by maxale** [sagemath/sage#34662]
<div id="comment:0"></div>

We have

```
sage: cycles = [[1,2,3],[4,5,6]]
sage: sage.combinat.permutation.from_cycles(6,cycles)
[2, 3, 1, 5, 6, 4]
sage: sage.combinat.permutation.from_cycles(6,(c for c in cycles))
[1, 2, 3, 4, 5, 6]
```

where the former result is correct and the latter is wrong.

Component: **combinatorics**

Author: **Dave Morris**

Branch/Commit: **[`af2f762`](https://github.com/sagemath/sagetrac-mirror/commit/af2f7625c5f5a79020f3039bc546a79d42049f47)**

Reviewer: **Travis Scrimshaw**

_Issue created by migration from https://trac.sagemath.org/ticket/34662_

**Comment by DaveWitteMorris** [comment]
Branch: **[public/34662](https://github.com/sagemath/sagetrac-mirror/tree/public/34662)**

**Comment by DaveWitteMorris** [comment]
Author: **Dave Morris**

**Comment by DaveWitteMorris** [comment]
<div id="comment:3" align="right">comment:3</div>

Thanks for pointing out this bug. I rewrote the code to only access the input once, so it works with generators. The new code also verifies the input without sorting a list (which takes more than linear time).

---
New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/e5e8cd54b96bcc01beedee0e7ead7404e0dccb33"><code>e5e8cd5</code></a></td><td><code>trac 34662: create permutation from a generator</code></td></tr></table>

**Comment by DaveWitteMorris** [comment]
Commit: **[`e5e8cd5`](https://github.com/sagemath/sagetrac-mirror/commit/e5e8cd54b96bcc01beedee0e7ead7404e0dccb33)**

**Comment by DaveWitteMorris** [comment]
Changed stopgaps from **todo** to none

**Comment by tscrim** [comment]
<div id="comment:4" align="right">comment:4</div>

The test of `int(x)` doesn't quite do what it is claiming to do:

```
sage: int(1.5)
1
```
It would be better to just explicit convert the inputs to `ZZ`, which can just fail.

Likewise, do `p[i] = ZZ(i+1)`.

Please factor out the `len(cycle)` calls as a variable in the loop as an optimization.

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
<div id="comment:5"></div>

Branch pushed to git repo; I updated commit sha1. New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/af2f7625c5f5a79020f3039bc546a79d42049f47"><code>af2f762</code></a></td><td><code>improvements suggested by reviewer</code></td></tr></table>

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
Changed commit from **[`e5e8cd5`](https://github.com/sagemath/sagetrac-mirror/commit/e5e8cd54b96bcc01beedee0e7ead7404e0dccb33)** to **[`af2f762`](https://github.com/sagemath/sagetrac-mirror/commit/af2f7625c5f5a79020f3039bc546a79d42049f47)**

**Comment by DaveWitteMorris** [comment]
<div id="comment:6" align="right">comment:6</div>

Thanks for your comments.  I think I made the changes that you suggested.

**Comment by tscrim** [comment]
Reviewer: **Travis Scrimshaw**

**Comment by tscrim** [comment]
<div id="comment:7" align="right">comment:7</div>

Thanks. LGTM.

**Comment by DaveWitteMorris** [comment]
<div id="comment:8" align="right">comment:8</div>

Thanks!

**Comment by vbraun** [comment]
Changed branch from **[public/34662](https://github.com/sagemath/sagetrac-mirror/tree/public/34662)** to **[`af2f762`](https://github.com/sagemath/sagetrac-mirror/commit/af2f7625c5f5a79020f3039bc546a79d42049f47)**
