### ISSUE TITLE
full pep8 for elliptic_curves/cardinality

### ISSUE THREAD

**Issue by fchapoton** [sagemath/sage#34666]
<div id="comment:0"></div>

CC:  @tscrim @slel @kwankyu @kliem

Component: **elliptic curves**

Author: **Frédéric Chapoton**

Branch/Commit: **[`c488beb`](https://github.com/sagemath/sagetrac-mirror/commit/c488beb779d383377059ff37df8015d6e98d7db8)**

Reviewer: **Travis Scrimshaw**

_Issue created by migration from https://trac.sagemath.org/ticket/34666_

**Comment by fchapoton** [comment]
Branch: **[u/chapoton/34666](https://github.com/sagemath/sagetrac-mirror/tree/u/chapoton/34666)**

**Comment by fchapoton** [comment]
<div id="comment:1"></div>

New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/c488beb779d383377059ff37df8015d6e98d7db8"><code>c488beb</code></a></td><td><code>full pep8 for elliptic_curves/cardinality.py</code></td></tr></table>

**Comment by fchapoton** [comment]
Commit: **[`c488beb`](https://github.com/sagemath/sagetrac-mirror/commit/c488beb779d383377059ff37df8015d6e98d7db8)**

**Comment by fchapoton** [comment]
<div id="comment:2" align="right">comment:2</div>

green lights, so please review

**Comment by tscrim** [comment]
<div id="comment:3" align="right">comment:3</div>

LGTM.

**Comment by tscrim** [comment]
Reviewer: **Travis Scrimshaw**

**Comment by vbraun** [comment]
Changed branch from **[u/chapoton/34666](https://github.com/sagemath/sagetrac-mirror/tree/u/chapoton/34666)** to **[`c488beb`](https://github.com/sagemath/sagetrac-mirror/commit/c488beb779d383377059ff37df8015d6e98d7db8)**
