### ISSUE TITLE
change iterator for ordered set partitions

### ISSUE THREAD

**Issue by fchapoton** [sagemath/sage#34673]
<div id="comment:0"></div>

as suggested by

https://gitlab.com/modulispaces/admcycles/-/issues/100

CC:  @videlec @tscrim

Component: **combinatorics**

Author: **Frédéric Chapoton**

Branch/Commit: **[`362d8f1`](https://github.com/sagemath/sagetrac-mirror/commit/362d8f14e7d214e79ec8d597c71ea2ad79f01a1d)**

Reviewer: **Travis Scrimshaw**

_Issue created by migration from https://trac.sagemath.org/ticket/34673_

**Comment by fchapoton** [comment]
Branch: **[u/chapoton/34673](https://github.com/sagemath/sagetrac-mirror/tree/u/chapoton/34673)**

**Comment by fchapoton** [comment]
<div id="comment:1"></div>

New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/576598ed4c0fc3179ff5feb5dc285f4e0fa5e4b0"><code>576598e</code></a></td><td><code>change iterator for ordered set partitions</code></td></tr></table>

**Comment by fchapoton** [comment]
Commit: **[`576598e`](https://github.com/sagemath/sagetrac-mirror/commit/576598ed4c0fc3179ff5feb5dc285f4e0fa5e4b0)**

**Comment by fchapoton** [comment]
<div id="comment:2" align="right">comment:2</div>

hmm, in fact, it seems to make the timing even worse.. probably something bad happening in the element construction ?

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
<div id="comment:3"></div>

Branch pushed to git repo; I updated commit sha1. New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/b30b4c7e3bfd0e0bd38ca99cdbbc9f27e3be60ce"><code>b30b4c7</code></a></td><td><code>slightly better like this</code></td></tr></table>

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
Changed commit from **[`576598e`](https://github.com/sagemath/sagetrac-mirror/commit/576598ed4c0fc3179ff5feb5dc285f4e0fa5e4b0)** to **[`b30b4c7`](https://github.com/sagemath/sagetrac-mirror/commit/b30b4c7e3bfd0e0bd38ca99cdbbc9f27e3be60ce)**

**Comment by tscrim** [comment]
<div id="comment:4" align="right">comment:4</div>

I think there are a number of ways to speed things up:

1. We do not store the `_base_set` with the element. This is something that belongs the parent.
2. Add a `check` argument to the `__init__` and pass that along; in particular, skip the check when iterating over elements.
3. Cythonize `multiset_permutation_next_lex` and `multiset_permutation_to_ordered_set_partition`.
4. Directly write the `convert` as Python code to avoid the extra Python function calls. Furthermore, already make the parts a `frozenset` or `Set` to avoid extra transient objects.

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
<div id="comment:5"></div>

Branch pushed to git repo; I updated commit sha1. New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/3958ebce64100d730189e0958bd729dd389a521f"><code>3958ebc</code></a></td><td><code>some tweaks, not working yet</code></td></tr></table>

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
Changed commit from **[`b30b4c7`](https://github.com/sagemath/sagetrac-mirror/commit/b30b4c7e3bfd0e0bd38ca99cdbbc9f27e3be60ce)** to **[`3958ebc`](https://github.com/sagemath/sagetrac-mirror/commit/3958ebce64100d730189e0958bd729dd389a521f)**

**Comment by fchapoton** [comment]
<div id="comment:6" align="right">comment:6</div>

Thanks Travis for the suggestions.

Trying to include the underlying set in the parent, I stumbled upon the "element_constructor" not doing the job of using the correct specific parent. This is not the first time I meet this kind of issue, but I am still unable to fix that.

Also, I would like to avoid using the sage `Set` at all, because it seems to be deadly slow.

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
<div id="comment:7"></div>

Branch pushed to git repo; I updated commit sha1. New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/05413eeb2e5915b627244fd3104b5f508899509a"><code>05413ee</code></a></td><td><code>minor details</code></td></tr></table>

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
Changed commit from **[`3958ebc`](https://github.com/sagemath/sagetrac-mirror/commit/3958ebce64100d730189e0958bd729dd389a521f)** to **[`05413ee`](https://github.com/sagemath/sagetrac-mirror/commit/05413eeb2e5915b627244fd3104b5f508899509a)**

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
<div id="comment:8"></div>

Branch pushed to git repo; I updated commit sha1. New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/94c2ea5d9f3e0257cca6ccc389baf35635357edf"><code>94c2ea5</code></a></td><td><code>more tweaks</code></td></tr></table>

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
Changed commit from **[`05413ee`](https://github.com/sagemath/sagetrac-mirror/commit/05413eeb2e5915b627244fd3104b5f508899509a)** to **[`94c2ea5`](https://github.com/sagemath/sagetrac-mirror/commit/94c2ea5d9f3e0257cca6ccc389baf35635357edf)**

**Comment by tscrim** [comment]
<div id="comment:9" align="right">comment:9</div>

I don't quite understand your problem with `element_constructor`. Can you give me a little more detail?

I agree that we should avoid using `Set`, but we then require hashability for `frozenset`. This is desirable, and I don't see any real use-case otherwise. However, it is a slightly backwards incompatible change.

We will also need to special case the base set in `to_packed_word()` when the parent is `OrderedSetPartitions_all`. I also don't see a real use-case for such a parent.

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
<div id="comment:10"></div>

Branch pushed to git repo; I updated commit sha1. New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/4e9c186fa76fcabb94b1e08a8311529665d5374d"><code>4e9c186</code></a></td><td><code>more tweaks</code></td></tr></table>

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
Changed commit from **[`94c2ea5`](https://github.com/sagemath/sagetrac-mirror/commit/94c2ea5d9f3e0257cca6ccc389baf35635357edf)** to **[`4e9c186`](https://github.com/sagemath/sagetrac-mirror/commit/4e9c186fa76fcabb94b1e08a8311529665d5374d)**

**Comment by fchapoton** [comment]
<div id="comment:11" align="right">comment:11</div>

My problem is that currently

```
        sage: S = OrderedSetPartitions()
        sage: x = S([[3,5], [2], [1,4,6]])
        sage: x.parent()
        Ordered set partitions
```
whereas the parent should be `Ordered set partitions of {1,2,3,4,5,6}`

**Comment by tscrim** [comment]
<div id="comment:12" align="right">comment:12</div>

No, that is the correct answer. We have a parent that is the set of all ordered set partitions, no matter the base set.

Actually, I know a use case (answering the last part of [comment:9](#comment%3A9)): We need the union of `OrderedSetPartitions(n)` over all `n` to index the basis of `FQSym`.

**Comment by tscrim** [comment]
<div id="comment:13" align="right">comment:13</div>

The only issue is in `to_packed_word()`, right? Just check if the parent is `OrderedSetPartitions_all`, and in that case only, do we build the set as `frozenset(range(1, sum(len(p) for p in self)+1))`.

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
Changed commit from **[`4e9c186`](https://github.com/sagemath/sagetrac-mirror/commit/4e9c186fa76fcabb94b1e08a8311529665d5374d)** to **[`cd370cb`](https://github.com/sagemath/sagetrac-mirror/commit/cd370cb74bc9ad49815be69d0d424bf2b02099d4)**

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
<div id="comment:14"></div>

Branch pushed to git repo; I updated commit sha1. This was a forced push. New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/cd370cb74bc9ad49815be69d0d424bf2b02099d4"><code>cd370cb</code></a></td><td><code>change iterator for ordered set partitions</code></td></tr></table>

**Comment by fchapoton** [comment]
<div id="comment:15" align="right">comment:15</div>

thanks a lot. I have used a try-except in `base_set` method.

Now passing the doctests, with a twice faster but still very slow iterator.

**Comment by tscrim** [comment]
Reviewer: **Travis Scrimshaw**

**Comment by tscrim** [comment]
Changed commit from **[`cd370cb`](https://github.com/sagemath/sagetrac-mirror/commit/cd370cb74bc9ad49815be69d0d424bf2b02099d4)** to **[`7efd468`](https://github.com/sagemath/sagetrac-mirror/commit/7efd468620c0f78a195d0a501841915360f0e944)**

**Comment by tscrim** [comment]
<div id="comment:16" align="right">comment:16</div>

One micro-optimization: The change

```diff
-        par = parent(self)
+        par = self.parent()
```
is slightly slower because the first is a Cython function call (that accesses the Cython slot) versus a Python method call:

```
sage: O = OrderedSetPartition()
sage: %timeit parent(O)
28 ns ± 0.415 ns per loop (mean ± std. dev. of 7 runs, 10,000,000 loops each)
sage: %timeit O.parent()
55.6 ns ± 0.234 ns per loop (mean ± std. dev. of 7 runs, 10,000,000 loops each)
```
Up to you if you want to revert it.

I just pushed another >2x speedup by avoiding the useless check (comment:4 point 2).

I do think it would be nice to get rid of the `Set`. I highly doubt anyone will be affected by that change. If anyone is affected, then we can just apologize to them and tell them to make their objects immutable. Iterating over `OrderedSetPartitions(7)` now, over 80% of the time is spent in `Set.__init__`.

---
New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/7efd468620c0f78a195d0a501841915360f0e944"><code>7efd468</code></a></td><td><code>Reviewer change by introducing a check argument.</code></td></tr></table>

**Comment by tscrim** [comment]
Changed branch from **[u/chapoton/34673](https://github.com/sagemath/sagetrac-mirror/tree/u/chapoton/34673)** to **[u/tscrim/ordered_set_partition_iter-34673](https://github.com/sagemath/sagetrac-mirror/tree/u/tscrim/ordered_set_partition_iter-34673)**

**Comment by fchapoton** [comment]
Changed commit from **[`7efd468`](https://github.com/sagemath/sagetrac-mirror/commit/7efd468620c0f78a195d0a501841915360f0e944)** to **[`64c3482`](https://github.com/sagemath/sagetrac-mirror/commit/64c3482f88e43dd67d2c43b5eecb26843bc89ce9)**

**Comment by fchapoton** [comment]
Changed branch from **[u/tscrim/ordered_set_partition_iter-34673](https://github.com/sagemath/sagetrac-mirror/tree/u/tscrim/ordered_set_partition_iter-34673)** to **[u/chapoton/34673](https://github.com/sagemath/sagetrac-mirror/tree/u/chapoton/34673)**

**Comment by fchapoton** [comment]
<div id="comment:17" align="right">comment:17</div>

now using `parent(self)` again

---
New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/64c3482f88e43dd67d2c43b5eecb26843bc89ce9"><code>64c3482</code></a></td><td><code>re-using parent(self)</code></td></tr></table>

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
Changed commit from **[`64c3482`](https://github.com/sagemath/sagetrac-mirror/commit/64c3482f88e43dd67d2c43b5eecb26843bc89ce9)** to **[`023f37f`](https://github.com/sagemath/sagetrac-mirror/commit/023f37f0ae06ab31381eb627153e93fcce6662ba)**

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
<div id="comment:18"></div>

Branch pushed to git repo; I updated commit sha1. New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/023f37f0ae06ab31381eb627153e93fcce6662ba"><code>023f37f</code></a></td><td><code>using set and frozenset</code></td></tr></table>

**Comment by fchapoton** [comment]
<div id="comment:19" align="right">comment:19</div>

now using `set` and `frozenset`, and so really much faster in iteration. :)

Some doctests are failing because of a modified order in the doctests. It is ok to change the doctests ?

**Comment by tscrim** [comment]
<div id="comment:20" align="right">comment:20</div>

Replying to [Frédéric Chapoton](#comment%3A19):
> now using `set` and `frozenset`, and so really much faster in iteration. :)

Yay!

> Some doctests are failing because of a modified order in the doctests. It is ok to change the doctests ?

Of course.

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
Changed commit from **[`023f37f`](https://github.com/sagemath/sagetrac-mirror/commit/023f37f0ae06ab31381eb627153e93fcce6662ba)** to **[`63ee91e`](https://github.com/sagemath/sagetrac-mirror/commit/63ee91ee7314aec60c2d32d7d12a23b8813e7c4d)**

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
<div id="comment:21"></div>

Branch pushed to git repo; I updated commit sha1. New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/63ee91ee7314aec60c2d32d7d12a23b8813e7c4d"><code>63ee91e</code></a></td><td><code>fixing the doctests</code></td></tr></table>

**Comment by fchapoton** [comment]
<div id="comment:22" align="right">comment:22</div>

doctests now fixed, also in wqsym

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
<div id="comment:23"></div>

Branch pushed to git repo; I updated commit sha1. New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/64cae731f9ce71c2c945d70263fefe62481329e6"><code>64cae73</code></a></td><td><code>little detail</code></td></tr></table>

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
Changed commit from **[`63ee91e`](https://github.com/sagemath/sagetrac-mirror/commit/63ee91ee7314aec60c2d32d7d12a23b8813e7c4d)** to **[`64cae73`](https://github.com/sagemath/sagetrac-mirror/commit/64cae731f9ce71c2c945d70263fefe62481329e6)**

**Comment by tscrim** [comment]
<div id="comment:24" align="right">comment:24</div>

We have to be a little more careful about the parent in `from_finite_word()` as it can lead to pollution of the `WQSym` elements having indices in different parents (which are not comparable).

---
New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/362d8f14e7d214e79ec8d597c71ea2ad79f01a1d"><code>362d8f1</code></a></td><td><code>Being more careful with the parent in from_finite_word().</code></td></tr></table>

**Comment by tscrim** [comment]
Changed commit from **[`64cae73`](https://github.com/sagemath/sagetrac-mirror/commit/64cae731f9ce71c2c945d70263fefe62481329e6)** to **[`362d8f1`](https://github.com/sagemath/sagetrac-mirror/commit/362d8f14e7d214e79ec8d597c71ea2ad79f01a1d)**

**Comment by tscrim** [comment]
Changed branch from **[u/chapoton/34673](https://github.com/sagemath/sagetrac-mirror/tree/u/chapoton/34673)** to **[u/tscrim/ordered_set_partition_iter-34673](https://github.com/sagemath/sagetrac-mirror/tree/u/tscrim/ordered_set_partition_iter-34673)**

**Comment by fchapoton** [comment]
<div id="comment:25" align="right">comment:25</div>

ok, if you say so. Looks good to me

Vincent suggested to check if the original code in sage could be made more efficient than our current proposal, once no longer using Set. This seems unlikely to me.

**Comment by tscrim** [comment]
<div id="comment:26" align="right">comment:26</div>

No, you already had an improvement even while using `Set` as I understood it.

We don't want to mix different parents for `WQSym` basis indices because then `<=` doesn't work. So, e.g., `leading_support()` fails.

**Comment by vbraun** [comment]
Changed branch from **[u/tscrim/ordered_set_partition_iter-34673](https://github.com/sagemath/sagetrac-mirror/tree/u/tscrim/ordered_set_partition_iter-34673)** to **[`362d8f1`](https://github.com/sagemath/sagetrac-mirror/commit/362d8f14e7d214e79ec8d597c71ea2ad79f01a1d)**
