### ISSUE TITLE
Fix sage.misc.package_dir doctest after #32874

### ISSUE THREAD

**Issue by mkoeppe** [sagemath/sage#34674]
<div id="comment:0"></div>

CC:  @antonio-rojas

Component: **misc**

Author: **Matthias Koeppe**

Branch/Commit: **[`50b7486`](https://github.com/sagemath/sagetrac-mirror/commit/50b7486518c54ac32c358e2811c188aea3842c84)**

Reviewer: **Antonio Rojas**

_Issue created by migration from https://trac.sagemath.org/ticket/34674_

**Comment by mkoeppe** [comment]
Branch: **[u/mkoeppe/fix_sage_misc_package_dir_doctest_after__32874](https://github.com/sagemath/sagetrac-mirror/tree/u/mkoeppe/fix_sage_misc_package_dir_doctest_after__32874)**

**Comment by mkoeppe** [comment]
<div id="comment:2"></div>

New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/50b7486518c54ac32c358e2811c188aea3842c84"><code>50b7486</code></a></td><td><code>src/sage/misc/package_dir.py: Fix doctest after #32874</code></td></tr></table>

**Comment by mkoeppe** [comment]
Commit: **[`50b7486`](https://github.com/sagemath/sagetrac-mirror/commit/50b7486518c54ac32c358e2811c188aea3842c84)**

**Comment by mkoeppe** [comment]
Author: **Matthias Koeppe**

**Comment by kwankyu** [comment]
Reviewer: **Antonio Rojas**

**Comment by mkoeppe** [comment]
<div id="comment:5" align="right">comment:5</div>

Thanks!

**Comment by vbraun** [comment]
Changed branch from **[u/mkoeppe/fix_sage_misc_package_dir_doctest_after__32874](https://github.com/sagemath/sagetrac-mirror/tree/u/mkoeppe/fix_sage_misc_package_dir_doctest_after__32874)** to **[`50b7486`](https://github.com/sagemath/sagetrac-mirror/commit/50b7486518c54ac32c358e2811c188aea3842c84)**
