### ISSUE TITLE
Upgrade pip 22.3 and various other Python packages

### ISSUE THREAD

**Issue by mkoeppe** [sagemath/sage#34676]
<div id="comment:0"></div>

and introduce new standard packages 

- `hatch_fancy_pypi_readme`: Fancy PyPI READMEs with Hatch

- `hatch_vcs`: Hatch plugin for versioning with your preferred VCS

because of the dependencies changes originated from 

​https://github.com/python-jsonschema/jsonschema/blob/main/pyproject.toml#L1

https://github.com/platformdirs/platformdirs/blob/main/pyproject.toml#L1

Component: **packages: standard**

Author: **Matthias Koeppe**

Branch/Commit: **[`6a28162`](https://github.com/sagemath/sagetrac-mirror/commit/6a281622f4fcaaeb8c76231c5d9cb0a949ed4e0a)**

Reviewer: **Kwankyu Lee**

_Issue created by migration from https://trac.sagemath.org/ticket/34676_

**Comment by mkoeppe** [comment]
Branch: **[u/mkoeppe/upgrade_pip_22_3](https://github.com/sagemath/sagetrac-mirror/tree/u/mkoeppe/upgrade_pip_22_3)**

**Comment by mkoeppe** [comment]
Author: **Matthias Koeppe**

**Comment by mkoeppe** [comment]
<div id="comment:2"></div>

Last 10 new commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/4f17da2e62f7a0a0de50aa605c2d457b637206ed"><code>4f17da2</code></a></td><td><code>build/pkgs/zipp: Update to 3.9.0</code></td></tr><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/da30ebe85a2260446d8694f0b92fb30b88cf22ee"><code>da30ebe</code></a></td><td><code>build/pkgs/asttokens: Update to 2.0.8</code></td></tr><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/3f516961931c5ad302d60b4dca6184c001f716a8"><code>3f51696</code></a></td><td><code>build/pkgs/argon2_cffi: Update to 21.3.0</code></td></tr><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/bf09ae8184d2cb6001839361130351d4de301939"><code>bf09ae8</code></a></td><td><code>build/pkgs/bleach: Update to 5.0.1</code></td></tr><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/2d307f370755e06d9eed17f4b33c53cdd4532eea"><code>2d307f3</code></a></td><td><code>build/pkgs/cffi: Update to 1.15.1</code></td></tr><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/58088045b814b608a2d56e2c6045dc723680f9b4"><code>5808804</code></a></td><td><code>build/pkgs/debugpy: Update to 1.6.3</code></td></tr><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/9edbf9c4afd067e55a1e48e5453dbfa20dbcc6b3"><code>9edbf9c</code></a></td><td><code>build/pkgs/executing: Update to 1.1.1</code></td></tr><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/a3c906c6f9d068863123495861013ce249c0f6c8"><code>a3c906c</code></a></td><td><code>build/pkgs/fastjsonschema: Update to 2.16.2</code></td></tr><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/db2cb849ba14adba7dca98c5f7ba1b1b0e1b7429"><code>db2cb84</code></a></td><td><code>build/pkgs/setuptools_scm: Update to 6.4.2</code></td></tr><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/cef4347ca586307c6670588eb975327b6be29d0b"><code>cef4347</code></a></td><td><code>build/pkgs/platformdirs/dependencies: Update</code></td></tr></table>

**Comment by mkoeppe** [comment]
Commit: **[`cef4347`](https://github.com/sagemath/sagetrac-mirror/commit/cef4347ca586307c6670588eb975327b6be29d0b)**

**Comment by fchapoton** [comment]
<div id="comment:3" align="right">comment:3</div>

argon2_cffi no longer depends on six, see #34419

**Comment by mkoeppe** [comment]
Dependencies: **#34419**

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
<div id="comment:5"></div>

Branch pushed to git repo; I updated commit sha1. New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/ed79f1125ee048ecb9abe4349fe053433351a9c4"><code>ed79f11</code></a></td><td><code>update argon2_cffi and sagenb_export</code></td></tr><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/2fadb8987c968f605b18e8ddd5b290fbc57d6a5b"><code>2fadb89</code></a></td><td><code>cycler no longer depends on six</code></td></tr><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/1a2d6fb69574be9373492c0a9eedbec573792fe0"><code>1a2d6fb</code></a></td><td><code>Merge #34419</code></td></tr><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/ff408b52b29fb6bcaab8ad59c51ff1990d5695a0"><code>ff408b5</code></a></td><td><code>build/pkgs/hatchling: Update to 1.11.0</code></td></tr><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/013fb3ea13286fa03e875e2df450e530a70712db"><code>013fb3e</code></a></td><td><code>build/pkgs/hatch_fancy_pypi_readme: New (jsonschema build dep)</code></td></tr></table>

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
Changed commit from **[`cef4347`](https://github.com/sagemath/sagetrac-mirror/commit/cef4347ca586307c6670588eb975327b6be29d0b)** to **[`013fb3e`](https://github.com/sagemath/sagetrac-mirror/commit/013fb3ea13286fa03e875e2df450e530a70712db)**

**Comment by mkoeppe** [comment]
Changed dependencies from **#34419** to none

**Comment by mkoeppe** [comment]
<div id="comment:6" align="right">comment:6</div>

dropped the argon2_cffi upgrade, which is on #34419

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
<div id="comment:7"></div>

Branch pushed to git repo; I updated commit sha1. This was a forced push. Last 10 new commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/561689ee464f29e317ed8c7f0f64f34a137e1cf0"><code>561689e</code></a></td><td><code>build/pkgs/zipp: Update to 3.9.0</code></td></tr><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/6cec070aded5ce122aa8ec3fab6f9661510795a2"><code>6cec070</code></a></td><td><code>build/pkgs/asttokens: Update to 2.0.8</code></td></tr><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/bd342703f59740c467d17067c27db57afc97c98f"><code>bd34270</code></a></td><td><code>build/pkgs/bleach: Update to 5.0.1</code></td></tr><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/523f2d27c3c4450e259d2474037d6923a88e6907"><code>523f2d2</code></a></td><td><code>build/pkgs/cffi: Update to 1.15.1</code></td></tr><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/fbd95f95e24282495564ac5e253d4eb89e7835da"><code>fbd95f9</code></a></td><td><code>build/pkgs/debugpy: Update to 1.6.3</code></td></tr><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/a6e970b94d873bfb0c4869e98a5791a37e63cd66"><code>a6e970b</code></a></td><td><code>build/pkgs/executing: Update to 1.1.1</code></td></tr><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/8b6cea825812928bae7b8b55306c445ffebec2f7"><code>8b6cea8</code></a></td><td><code>build/pkgs/fastjsonschema: Update to 2.16.2</code></td></tr><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/37d912e330cf03a8cd2f9bcdfbf0c4986d06b5e5"><code>37d912e</code></a></td><td><code>build/pkgs/setuptools_scm: Update to 6.4.2</code></td></tr><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/266dfd2daf1baa48a22a1f408314cb6ce76331e9"><code>266dfd2</code></a></td><td><code>build/pkgs/platformdirs/dependencies: Update</code></td></tr><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/d4f0f424732014246e5ae3402f3a7f3ae636de59"><code>d4f0f42</code></a></td><td><code>build/pkgs/hatchling: Update to 1.11.0</code></td></tr></table>

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
Changed commit from **[`013fb3e`](https://github.com/sagemath/sagetrac-mirror/commit/013fb3ea13286fa03e875e2df450e530a70712db)** to **[`d4f0f42`](https://github.com/sagemath/sagetrac-mirror/commit/d4f0f424732014246e5ae3402f3a7f3ae636de59)**

**Comment by kwankyu** [comment]
<div id="comment:8" align="right">comment:8</div>

Would you explain these dependencies changes

```diff
--- a/build/pkgs/jsonschema/dependencies
+++ b/build/pkgs/jsonschema/dependencies
@@ -1,4 +1,4 @@
-$(PYTHON) vcversioner attrs importlib_metadata pyrsistent | $(PYTHON_TOOLCHAIN) hatchling
+$(PYTHON) vcversioner attrs importlib_metadata pyrsistent | $(PYTHON_TOOLCHAIN) hatchling hatch_fancy_pypi_readme
```

```diff
--- a/build/pkgs/platformdirs/dependencies
+++ b/build/pkgs/platformdirs/dependencies
@@ -1,4 +1,4 @@
-$(PYTHON) | $(PYTHON_TOOLCHAIN)
+$(PYTHON) setuptools_scm | $(PYTHON_TOOLCHAIN) hatchling hatch_vcs
```
Or how can I check them?

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
<div id="comment:9"></div>

Branch pushed to git repo; I updated commit sha1. This was a forced push. Last 10 new commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/826d419baecbd3061614b5eadcf862125c3b5cdd"><code>826d419</code></a></td><td><code>build/pkgs/zipp: Update to 3.9.0</code></td></tr><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/38ba4c8032af9f0fb7eae5b26aa10d3a141df2f8"><code>38ba4c8</code></a></td><td><code>build/pkgs/asttokens: Update to 2.0.8</code></td></tr><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/df5430bc0a84da05179832d535765674e3f00f91"><code>df5430b</code></a></td><td><code>build/pkgs/bleach: Update to 5.0.1</code></td></tr><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/b588629e7d14300b8e5d0208ee320d27b4f936f0"><code>b588629</code></a></td><td><code>build/pkgs/cffi: Update to 1.15.1</code></td></tr><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/a099c0389c979f553782bd875e2dcc7312b7f9c0"><code>a099c03</code></a></td><td><code>build/pkgs/debugpy: Update to 1.6.3</code></td></tr><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/8f2142f043a644fb384d5bb6b1c9c35bb061a5c3"><code>8f2142f</code></a></td><td><code>build/pkgs/executing: Update to 1.1.1</code></td></tr><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/701db6ef42ef6b17577cdc69c751f608ba43ebed"><code>701db6e</code></a></td><td><code>build/pkgs/fastjsonschema: Update to 2.16.2</code></td></tr><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/3077298f9b13bfbb905adb7b823e94d5001ebb14"><code>3077298</code></a></td><td><code>build/pkgs/setuptools_scm: Update to 6.4.2</code></td></tr><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/045e2282c5f3f8b1fb35a35d4195fa52cea0c480"><code>045e228</code></a></td><td><code>build/pkgs/platformdirs/dependencies: Update</code></td></tr><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/8ecf31d16c95420094a572f6276958213170703b"><code>8ecf31d</code></a></td><td><code>build/pkgs/hatchling: Update to 1.11.0</code></td></tr></table>

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
Changed commit from **[`d4f0f42`](https://github.com/sagemath/sagetrac-mirror/commit/d4f0f424732014246e5ae3402f3a7f3ae636de59)** to **[`8ecf31d`](https://github.com/sagemath/sagetrac-mirror/commit/8ecf31d16c95420094a572f6276958213170703b)**

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
<div id="comment:10"></div>

Branch pushed to git repo; I updated commit sha1. New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/5fc21762242d41875be7e733dc2dd93b64a0cfc8"><code>5fc2176</code></a></td><td><code>build/pkgs/asttokens: Update to 2.1.0</code></td></tr><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/7d876d9228b7c816866f4953a8b83e8014cd91ee"><code>7d876d9</code></a></td><td><code>build/pkgs/hatchling: Update to 1.11.1</code></td></tr><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/eb4ef6a0e9b9988377e95791ba32022ca6e1a4d5"><code>eb4ef6a</code></a></td><td><code>build/pkgs/pytz: Update to 2022.5</code></td></tr><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/2385e729c6d5cc8fed860ccda2ef7aa6119849d7"><code>2385e72</code></a></td><td><code>build/pkgs/tinycss2: Update to 1.2.1</code></td></tr><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/881ed1cb9738b706b0bc50560d5e8f65b4b9a28d"><code>881ed1c</code></a></td><td><code>build/pkgs/tomlkit: Update to 0.11.6</code></td></tr><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/a0e053d39f57bb4f069f6185997f0d5268e9989b"><code>a0e053d</code></a></td><td><code>build/pkgs/tox: Update to 3.27.0</code></td></tr><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/88556b190d8b301506b74e78154e1e8520adbed9"><code>88556b1</code></a></td><td><code>build/pkgs/tzdata: Update to 2022.6</code></td></tr><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/495c138b2ac8f2c46dafe1bce8375999d38b2a8c"><code>495c138</code></a></td><td><code>build/pkgs/virtualenv: Update to 20.16.6</code></td></tr><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/99b938824441aee06465e709387e591244fda46a"><code>99b9388</code></a></td><td><code>build/pkgs/zipp: Update to 3.10.0</code></td></tr><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/2affa9db5b8ab66c1ff52c96182b3842a08b4e5a"><code>2affa9d</code></a></td><td><code>build/pkgs/stack_data: Update to 0.6.0</code></td></tr></table>

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
Changed commit from **[`8ecf31d`](https://github.com/sagemath/sagetrac-mirror/commit/8ecf31d16c95420094a572f6276958213170703b)** to **[`2affa9d`](https://github.com/sagemath/sagetrac-mirror/commit/2affa9db5b8ab66c1ff52c96182b3842a08b4e5a)**

**Comment by mkoeppe** [comment]
<div id="comment:11" align="right">comment:11</div>

Replying to [Kwankyu Lee](#comment%3A8):
> Would you explain these dependencies changes
> 
> ```diff
> --- a/build/pkgs/jsonschema/dependencies
> +++ b/build/pkgs/jsonschema/dependencies
> @@ -1,4 +1,4 @@
> -$(PYTHON) vcversioner attrs importlib_metadata pyrsistent | $(PYTHON_TOOLCHAIN) hatchling
> +$(PYTHON) vcversioner attrs importlib_metadata pyrsistent | $(PYTHON_TOOLCHAIN) hatchling hatch_fancy_pypi_readme
> ```

This is from https://github.com/python-jsonschema/jsonschema/blob/main/pyproject.toml#L1, but in fact we also need `hatch_vcs` here


> ```diff
> --- a/build/pkgs/platformdirs/dependencies
> +++ b/build/pkgs/platformdirs/dependencies
> @@ -1,4 +1,4 @@
> -$(PYTHON) | $(PYTHON_TOOLCHAIN)
> +$(PYTHON) setuptools_scm | $(PYTHON_TOOLCHAIN) hatchling hatch_vcs
> ```
> Or how can I check them?
> 

This is from https://github.com/platformdirs/platformdirs/blob/main/pyproject.toml#L1

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
Changed commit from **[`2affa9d`](https://github.com/sagemath/sagetrac-mirror/commit/2affa9db5b8ab66c1ff52c96182b3842a08b4e5a)** to **[`14344db`](https://github.com/sagemath/sagetrac-mirror/commit/14344db952b4f0a66f46b25dbc9eca3f91b35587)**

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
<div id="comment:12"></div>

Branch pushed to git repo; I updated commit sha1. New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/14344db952b4f0a66f46b25dbc9eca3f91b35587"><code>14344db</code></a></td><td><code>build/pkgs/jsonschema/dependencies: Add hatch_vcs</code></td></tr></table>

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
<div id="comment:13"></div>

Branch pushed to git repo; I updated commit sha1. New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/9604ef08f7403a1c9cfbd4d9659741dc23baa078"><code>9604ef0</code></a></td><td><code>build/pkgs/executing: Update to 1.2.0</code></td></tr><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/6a281622f4fcaaeb8c76231c5d9cb0a949ed4e0a"><code>6a28162</code></a></td><td><code>build/pkgs: Add missing dependencies</code></td></tr></table>

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
Changed commit from **[`14344db`](https://github.com/sagemath/sagetrac-mirror/commit/14344db952b4f0a66f46b25dbc9eca3f91b35587)** to **[`6a28162`](https://github.com/sagemath/sagetrac-mirror/commit/6a281622f4fcaaeb8c76231c5d9cb0a949ed4e0a)**

**Comment by mkoeppe** [comment]
<div id="comment:14" align="right">comment:14</div>

Currently we don't have better infrastructure for doing upgrades than trying the upgrade & watching for error messages while doing a build with high parallelization

**Comment by kwankyu** [comment]
<div id="comment:15" align="right">comment:15</div>

Replying to [Matthias Köppe](#comment%3A14):
> Currently we don't have better infrastructure for doing upgrades than trying the upgrade & watching for error messages while doing a build with high parallelization

I understand. Hence the author is most informed of the sources of dependencies changes. I think it should be a norm that the author provides the information at least when the change is the reason to introduce new standard packages, perhaps in the ticket description.

**Comment by kwankyu** [comment]
Reviewer: **Kwankyu Lee**

**Comment by kwankyu** [comment]
Description changed:
``````diff
--- 
+++ 
@@ -1 +1,12 @@
+and introduce new standard packages 
 
+- `hatch_fancy_pypi_readme`: Fancy PyPI READMEs with Hatch
+
+- `hatch_vcs`: Hatch plugin for versioning with your preferred VCS
+
+because of the dependencies changes originated from 
+
+​https://github.com/python-jsonschema/jsonschema/blob/main/pyproject.toml#L1
+
+https://github.com/platformdirs/platformdirs/blob/main/pyproject.toml#L1
+
``````

**Comment by mkoeppe** [comment]
<div id="comment:18" align="right">comment:18</div>

Thanks, the ticket description is a good place for this (in addition to the commit messages)

**Comment by kwankyu** [comment]
<div id="comment:19" align="right">comment:19</div>

LGTM. Thanks.

**Comment by mkoeppe** [comment]
<div id="comment:20" align="right">comment:20</div>

Thank you!

**Comment by vbraun** [comment]
Changed branch from **[u/mkoeppe/upgrade_pip_22_3](https://github.com/sagemath/sagetrac-mirror/tree/u/mkoeppe/upgrade_pip_22_3)** to **[`6a28162`](https://github.com/sagemath/sagetrac-mirror/commit/6a281622f4fcaaeb8c76231c5d9cb0a949ed4e0a)**
