### ISSUE TITLE
fix the linter again

### ISSUE THREAD

**Issue by fchapoton** [sagemath/sage#34671]
<div id="comment:0"></div>

as some recent tickets have added final empty lines in some files

CC:  @mantepse @yyyyx4

Component: **refactoring**

Author: **Frédéric Chapoton**

Branch/Commit: **[`8eedb6c`](https://github.com/sagemath/sagetrac-mirror/commit/8eedb6cfe798ed8e429b8cc52589b2485686f92b)**

Reviewer: **Matthias Koeppe**

_Issue created by migration from https://trac.sagemath.org/ticket/34671_

**Comment by fchapoton** [comment]
<div id="comment:1" align="right">comment:1</div>

please review swiftly !

---
New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/8eedb6cfe798ed8e429b8cc52589b2485686f92b"><code>8eedb6c</code></a></td><td><code>fix the linter once again</code></td></tr></table>

**Comment by fchapoton** [comment]
Commit: **[`8eedb6c`](https://github.com/sagemath/sagetrac-mirror/commit/8eedb6cfe798ed8e429b8cc52589b2485686f92b)**

**Comment by fchapoton** [comment]
Branch: **[u/chapoton/34671](https://github.com/sagemath/sagetrac-mirror/tree/u/chapoton/34671)**

**Comment by mkoeppe** [comment]
Reviewer: **Matthias Koeppe**

**Comment by vbraun** [comment]
Changed branch from **[u/chapoton/34671](https://github.com/sagemath/sagetrac-mirror/tree/u/chapoton/34671)** to **[`8eedb6c`](https://github.com/sagemath/sagetrac-mirror/commit/8eedb6cfe798ed8e429b8cc52589b2485686f92b)**
