### ISSUE TITLE
fix most W2 and W3 in geometry, rings, schemes

### ISSUE THREAD

**Issue by fchapoton** [sagemath/sage#34677]
<div id="comment:0"></div>

only on .py files for now

another little step on the way towards activating W2 and W3 checks in the linter

made using

```
autopep8 -i -r --select=W2,W3 src/sage/geometry/
```
and the same for rings/ and schemes/

Component: **refactoring**

Author: **Frédéric Chapoton**

Branch/Commit: **[`d531fb3`](https://github.com/sagemath/sagetrac-mirror/commit/d531fb36cee5ab40447269e0534741ca0b3811cb)**

Reviewer: **Matthias Koeppe**

_Issue created by migration from https://trac.sagemath.org/ticket/34677_

**Comment by fchapoton** [comment]
Commit: **[`d531fb3`](https://github.com/sagemath/sagetrac-mirror/commit/d531fb36cee5ab40447269e0534741ca0b3811cb)**

**Comment by fchapoton** [comment]
Description changed:
``````diff
--- 
+++ 
@@ -1,3 +1,10 @@
 only on .py files for now
 
 another little step on the way towards activating W2 and W3 checks in the lnter
+
+made using
+
+```
+autopep8 -i -r --select=W2,W3 src/sage/geometry/
+```
+and the same for rings/ and schemes/
``````

**Comment by fchapoton** [comment]
Branch: **[u/chapoton/34677](https://github.com/sagemath/sagetrac-mirror/tree/u/chapoton/34677)**

**Comment by fchapoton** [comment]
<div id="comment:1"></div>

New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/d531fb36cee5ab40447269e0534741ca0b3811cb"><code>d531fb3</code></a></td><td><code>fix W2 and W3 in geometry, rings, schemes</code></td></tr></table>

**Comment by fchapoton** [comment]
Description changed:
``````diff
--- 
+++ 
@@ -1,6 +1,6 @@
 only on .py files for now
 
-another little step on the way towards activating W2 and W3 checks in the lnter
+another little step on the way towards activating W2 and W3 checks in the linter
 
 made using
 
``````

**Comment by mkoeppe** [comment]
Reviewer: **Matthias Koeppe**

**Comment by vbraun** [comment]
Changed branch from **[u/chapoton/34677](https://github.com/sagemath/sagetrac-mirror/tree/u/chapoton/34677)** to **[`d531fb3`](https://github.com/sagemath/sagetrac-mirror/commit/d531fb36cee5ab40447269e0534741ca0b3811cb)**
