### ISSUE TITLE
some care for trailing whitespaces

### ISSUE THREAD

**Issue by fchapoton** [sagemath/sage#34672]
<div id="comment:0"></div>

pycodestyle W2 and W3

here both in some py and pyx files

Component: **refactoring**

Author: **Frédéric Chapoton**

Branch/Commit: **[`ca00c97`](https://github.com/sagemath/sagetrac-mirror/commit/ca00c97bc3c4beee54c28157634a919d4b7eebb5)**

Reviewer: **Matthias Koeppe**

_Issue created by migration from https://trac.sagemath.org/ticket/34672_

**Comment by fchapoton** [comment]
Commit: **[`1a277d8`](https://github.com/sagemath/sagetrac-mirror/commit/1a277d834c7686dbad38e4f0c995cefba3fd327a)**

**Comment by fchapoton** [comment]
<div id="comment:1"></div>

New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/1a277d834c7686dbad38e4f0c995cefba3fd327a"><code>1a277d8</code></a></td><td><code>some care for trailing whitespaces (W2 and W3)</code></td></tr></table>

**Comment by fchapoton** [comment]
Branch: **[u/chapoton/34672](https://github.com/sagemath/sagetrac-mirror/tree/u/chapoton/34672)**

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
Changed commit from **[`1a277d8`](https://github.com/sagemath/sagetrac-mirror/commit/1a277d834c7686dbad38e4f0c995cefba3fd327a)** to **[`539da7d`](https://github.com/sagemath/sagetrac-mirror/commit/539da7dfabe48a9e5ecc8b7f44510afe3d63b614)**

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
<div id="comment:2"></div>

Branch pushed to git repo; I updated commit sha1. New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/539da7dfabe48a9e5ecc8b7f44510afe3d63b614"><code>539da7d</code></a></td><td><code>spaces in matroids, plot, sets</code></td></tr></table>

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
<div id="comment:3"></div>

Branch pushed to git repo; I updated commit sha1. New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/ca00c97bc3c4beee54c28157634a919d4b7eebb5"><code>ca00c97</code></a></td><td><code>spaces in crypto, data_structures and symbolic</code></td></tr></table>

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
Changed commit from **[`539da7d`](https://github.com/sagemath/sagetrac-mirror/commit/539da7dfabe48a9e5ecc8b7f44510afe3d63b614)** to **[`ca00c97`](https://github.com/sagemath/sagetrac-mirror/commit/ca00c97bc3c4beee54c28157634a919d4b7eebb5)**

**Comment by mkoeppe** [comment]
Reviewer: **Matthias Koeppe**

**Comment by vbraun** [comment]
Changed branch from **[u/chapoton/34672](https://github.com/sagemath/sagetrac-mirror/tree/u/chapoton/34672)** to **[`ca00c97`](https://github.com/sagemath/sagetrac-mirror/commit/ca00c97bc3c4beee54c28157634a919d4b7eebb5)**
