### ISSUE TITLE
fix some details in graphs

### ISSUE THREAD

**Issue by fchapoton** [sagemath/sage#34688]
<div id="comment:0"></div>

found by lgtm

CC:  @dcoudert

Component: **graph theory**

Author: **Frédéric Chapoton**

Branch/Commit: **[`2d79307`](https://github.com/sagemath/sagetrac-mirror/commit/2d793075a03cd2808610e50afe784210674e5651)**

Reviewer: **David Coudert**

_Issue created by migration from https://trac.sagemath.org/ticket/34688_

**Comment by fchapoton** [comment]
Commit: **[`2d79307`](https://github.com/sagemath/sagetrac-mirror/commit/2d793075a03cd2808610e50afe784210674e5651)**

**Comment by fchapoton** [comment]
Branch: **[u/chapoton/34688](https://github.com/sagemath/sagetrac-mirror/tree/u/chapoton/34688)**

**Comment by fchapoton** [comment]
<div id="comment:1"></div>

New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/2d793075a03cd2808610e50afe784210674e5651"><code>2d79307</code></a></td><td><code>fix some details in graphs (found by lgtm)</code></td></tr></table>

**Comment by dcoudert** [comment]
<div id="comment:2" align="right">comment:2</div>

LGTM.

**Comment by dcoudert** [comment]
Reviewer: **David Coudert**

**Comment by vbraun** [comment]
Changed branch from **[u/chapoton/34688](https://github.com/sagemath/sagetrac-mirror/tree/u/chapoton/34688)** to **[`2d79307`](https://github.com/sagemath/sagetrac-mirror/commit/2d793075a03cd2808610e50afe784210674e5651)**
