### ISSUE TITLE
Error with multiplication of points on elliptic curves over Integers(n)

### ISSUE THREAD

**Issue by tornaria** [sagemath/sage#34681]
<div id="comment:0"></div>

```
sage: E = EllipticCurve(Integers(11*19), [1,0])
sage: P = E(93,3)
sage: P + P
(5 : 118 : 1)
sage: 2 * P
...
AttributeError: 'EllipticCurve_generic_with_category' object has no attribute 'base_field'
```

CC:  @yyyyx4

Component: **number theory**

Author: **Gonzalo Tornaría**

Branch/Commit: **[`9bbacfe`](https://github.com/sagemath/sagetrac-mirror/commit/9bbacfe4e0232a26b2e50c93e8eed1c01c073ae1)**

Reviewer: **Lorenz Panny**

_Issue created by migration from https://trac.sagemath.org/ticket/34681_

**Comment by tornaria** [comment]
Commit: **[`6d31aad`](https://github.com/sagemath/sagetrac-mirror/commit/6d31aad9f67f9ff414b4dbdce70444d9f0b69004)**

**Comment by tornaria** [comment]
Author: **Gonzalo Tornaría**

**Comment by tornaria** [comment]
Branch: **[u/tornaria/34681](https://github.com/sagemath/sagetrac-mirror/tree/u/tornaria/34681)**

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
Changed commit from **[`6d31aad`](https://github.com/sagemath/sagetrac-mirror/commit/6d31aad9f67f9ff414b4dbdce70444d9f0b69004)** to **[`9bbacfe`](https://github.com/sagemath/sagetrac-mirror/commit/9bbacfe4e0232a26b2e50c93e8eed1c01c073ae1)**

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
<div id="comment:2"></div>

Branch pushed to git repo; I updated commit sha1. New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/eb5833f39ec177f501092470abddf7a74ffc60a5"><code>eb5833f</code></a></td><td><code>#34681: fix multiplication of points over Integers(n)</code></td></tr><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/9bbacfe4e0232a26b2e50c93e8eed1c01c073ae1"><code>9bbacfe</code></a></td><td><code>#34681: do not redo multiplication when pari fails</code></td></tr></table>

**Comment by yyyyx4** [comment]
<div id="comment:3" align="right">comment:3</div>

Related: #33228

**Comment by tornaria** [comment]
<div id="comment:4" align="right">comment:4</div>

Replying to [Lorenz Panny](#comment%3A3):
> Related: #33228

Thanks for the info. Looks quite interesting. However, this fix here seems trivial -- can we get this in? At the very least the first commit.

Also, given that pari `ellmul` works with integer mod composite (in the sense that it either gives the right answer or gives a `Fp_inv` error) it seems a pity to fall back to a generic implementation as in #33228.

Same as mentioned in #33228, this was spotted by a student trying to implement ECM. It seems an important application... If point multiplication is implemented via `ellmul` this means the students might even have a shot at getting good speed if they can figure out how to choose the parameters.

**Comment by yyyyx4** [comment]
<div id="comment:5" align="right">comment:5</div>

Replying to [Gonzalo Tornaría](#comment%3A4):
> However, this fix here seems trivial -- can we get this in?

Indeed, why not.

**Comment by yyyyx4** [comment]
Reviewer: **Lorenz Panny**

**Comment by vbraun** [comment]
Changed branch from **[u/tornaria/34681](https://github.com/sagemath/sagetrac-mirror/tree/u/tornaria/34681)** to **[`9bbacfe`](https://github.com/sagemath/sagetrac-mirror/commit/9bbacfe4e0232a26b2e50c93e8eed1c01c073ae1)**
