### ISSUE TITLE
make Compositions() an additive monoid

### ISSUE THREAD

**Issue by fchapoton** [sagemath/sage#34689]
<div id="comment:0"></div>

and also forbid compositions containing zeroes

CC:  @tscrim @mkoeppe @kwankyu @slel

Component: **combinatorics**

Author: **Frédéric Chapoton**

Branch/Commit: **[`8139c36`](https://github.com/sagemath/sagetrac-mirror/commit/8139c367dba1e9ac88703289feb4910e47b9dc7e)**

Reviewer: **Travis Scrimshaw**

_Issue created by migration from https://trac.sagemath.org/ticket/34689_

**Comment by fchapoton** [comment]
Branch: **[u/chapoton/34689](https://github.com/sagemath/sagetrac-mirror/tree/u/chapoton/34689)**

**Comment by fchapoton** [comment]
<div id="comment:1" align="right">comment:1</div>

not sure if I should change `__add__` to `_add_` or not

---
New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/415670ca7dd9c2789805dbd9d1c8c2cd24c68721"><code>415670c</code></a></td><td><code>make Compositions() an additive monoid.</code></td></tr></table>

**Comment by fchapoton** [comment]
Commit: **[`415670c`](https://github.com/sagemath/sagetrac-mirror/commit/415670ca7dd9c2789805dbd9d1c8c2cd24c68721)**

**Comment by fchapoton** [comment]
<div id="comment:2" align="right">comment:2</div>

This has amusing side effects on `ncsf.py`, for example

```
File "sage/combinat/ncsf_qsym/ncsf.py", line 1686, in sage.combinat.ncsf_qsym.ncsf.NonCommutativeSymmetricFunctions.Bases.ElementMethods.to_symmetric_function
3250
Failed example:
3251
    x = R.an_element(); x
3252
Expected:
3253
    2*R[] + 2*R[1] + 3*R[1, 1]
3254
Got:
3255
    R[] + R['_', 'a', 'n', '_', 'e', 'l', 'e', 'm', 'e', 'n', 't', '_'] + 2*R[1] + 3*R[1, 1]

```

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
Changed commit from **[`415670c`](https://github.com/sagemath/sagetrac-mirror/commit/415670ca7dd9c2789805dbd9d1c8c2cd24c68721)** to **[`f5be12f`](https://github.com/sagemath/sagetrac-mirror/commit/f5be12f4e5c0ee462c0036c674d4e87fb2f52e89)**

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
<div id="comment:3"></div>

Branch pushed to git repo; I updated commit sha1. New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/f5be12f4e5c0ee462c0036c674d4e87fb2f52e89"><code>f5be12f</code></a></td><td><code>provide "an_element" for Compositions</code></td></tr></table>

**Comment by fchapoton** [comment]
<div id="comment:4" align="right">comment:4</div>

lights are morally green, so please review

**Comment by tscrim** [comment]
<div id="comment:5" align="right">comment:5</div>

LGTM modulo that

```diff
-Preferably consider using ``IntegerVectors`` instead::
+Instead you must use ``IntegerVectors`` instead::
```
since it is no longer a preference.

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
<div id="comment:6"></div>

Branch pushed to git repo; I updated commit sha1. New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/8139c367dba1e9ac88703289feb4910e47b9dc7e"><code>8139c36</code></a></td><td><code>rephrase to "must use"</code></td></tr></table>

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
Changed commit from **[`f5be12f`](https://github.com/sagemath/sagetrac-mirror/commit/f5be12f4e5c0ee462c0036c674d4e87fb2f52e89)** to **[`8139c36`](https://github.com/sagemath/sagetrac-mirror/commit/8139c367dba1e9ac88703289feb4910e47b9dc7e)**

**Comment by fchapoton** [comment]
<div id="comment:7" align="right">comment:7</div>

thanks, done

**Comment by tscrim** [comment]
Reviewer: **Travis Scrimshaw**

**Comment by vbraun** [comment]
Changed branch from **[u/chapoton/34689](https://github.com/sagemath/sagetrac-mirror/tree/u/chapoton/34689)** to **[`8139c36`](https://github.com/sagemath/sagetrac-mirror/commit/8139c367dba1e9ac88703289feb4910e47b9dc7e)**
