### ISSUE TITLE
clean up old gcc < 8 patches

### ISSUE THREAD

**Issue by dimpase** [sagemath/sage#34682]
<div id="comment:0"></div>

One of these left after #34266 is

`build/pkgs/flint/patches/0001-flint.h-On-GCC-4.9-do-not-use-_Thread_local.patch`

there are more (see the branch)

CC:  @mkoeppe

Component: **build**

Author: **Dima Pasechnik**

Branch/Commit: **[`fb783e0`](https://github.com/sagemath/sagetrac-mirror/commit/fb783e02453ab76b41128bfd43787cca8d857003)**

Reviewer: **Matthias Koeppe**

_Issue created by migration from https://trac.sagemath.org/ticket/34682_

**Comment by dimpase** [comment]
<div id="comment:1"></div>

New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/0c9d28aed04495569ff6761937f5c6bec226ad08"><code>0c9d28a</code></a></td><td><code>Revert "build/pkgs/primesieve: Add patch to support ubuntu-trusty, linuxmint-17"</code></td></tr><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/fb783e02453ab76b41128bfd43787cca8d857003"><code>fb783e0</code></a></td><td><code>Revert "build/pkgs/flint/: Add patch for threads with GCC < 4.9"</code></td></tr><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/a9790410d2a5fa08063eef9721adb1f78bddc048"><code>a979041</code></a></td><td><code>Revert "Build gcc/gfortran without passing -std=gnu++11 to the system g++"</code></td></tr></table>

**Comment by dimpase** [comment]
Commit: **[`a979041`](https://github.com/sagemath/sagetrac-mirror/commit/a9790410d2a5fa08063eef9721adb1f78bddc048)**

**Comment by dimpase** [comment]
Author: **Dima Pasechnik**

**Comment by dimpase** [comment]
Branch: **[u/dimpase/config/remove_old_bits_for_old_gcc](https://github.com/sagemath/sagetrac-mirror/tree/u/dimpase/config/remove_old_bits_for_old_gcc)**

**Comment by dimpase** [comment]
Description changed:
``````diff
--- 
+++ 
@@ -1,3 +1,5 @@
 One of these left after #34266 is
 
 `build/pkgs/flint/patches/0001-flint.h-On-GCC-4.9-do-not-use-_Thread_local.patch`
+
+there are more (see the branch)
``````

**Comment by mkoeppe** [comment]
<div id="comment:2" align="right">comment:2</div>

"Build gcc/gfortran without passing -std=gnu++11 to the system g++" is still needed

**Comment by dimpase** [comment]
<div id="comment:3" align="right">comment:3</div>

Replying to [Matthias Köppe](#comment%3A2):
> "Build gcc/gfortran without passing -std=gnu++11 to the system g++" is still needed

Really? Isn't it meant to fix #29162, which was about gcc 4.9?

**Comment by mkoeppe** [comment]
<div id="comment:4" align="right">comment:4</div>

We have not made any changes to what versions of system gcc we require in order to build gcc from SPKG.

**Comment by dimpase** [comment]
<div id="comment:5" align="right">comment:5</div>

There are plenty of old versions of gcc that won't work regardless, so I don't see a point of keeping this.

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
Changed commit from **[`a979041`](https://github.com/sagemath/sagetrac-mirror/commit/a9790410d2a5fa08063eef9721adb1f78bddc048)** to **[`fb783e0`](https://github.com/sagemath/sagetrac-mirror/commit/fb783e02453ab76b41128bfd43787cca8d857003)**

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
<div id="comment:7"></div>

Branch pushed to git repo; I updated commit sha1. This was a forced push. New commits:

**Comment by dimpase** [comment]
<div id="comment:8" align="right">comment:8</div>

OK, I've left this part in.

**Comment by mkoeppe** [comment]
Reviewer: **Matthias Koeppe**

**Comment by vbraun** [comment]
Changed branch from **[u/dimpase/config/remove_old_bits_for_old_gcc](https://github.com/sagemath/sagetrac-mirror/tree/u/dimpase/config/remove_old_bits_for_old_gcc)** to **[`fb783e0`](https://github.com/sagemath/sagetrac-mirror/commit/fb783e02453ab76b41128bfd43787cca8d857003)**
