### ISSUE TITLE
update link to Fukuda's polyhedral FAQ

### ISSUE THREAD

**Issue by dimpase** [sagemath/sage#34685]
<div id="comment:0"></div>

CC:  @seblabbe @mkoeppe

Component: **documentation**

Author: **Dima Pasechnik**

Branch/Commit: **[`dd87547`](https://github.com/sagemath/sagetrac-mirror/commit/dd87547019684e21c1e23a640870231557aa5093)**

Reviewer: **Matthias Koeppe**

_Issue created by migration from https://trac.sagemath.org/ticket/34685_

**Comment by mkoeppe** [comment]
Reviewer: **Matthias Koeppe**

**Comment by vbraun** [comment]
Changed branch from **[u/dimpase/doc/polyFAQref](https://github.com/sagemath/sagetrac-mirror/tree/u/dimpase/doc/polyFAQref)** to **[`dd87547`](https://github.com/sagemath/sagetrac-mirror/commit/dd87547019684e21c1e23a640870231557aa5093)**
