### ISSUE TITLE
igraph, python_igraph: Update to 0.10.2

### ISSUE THREAD

**Issue by mkoeppe** [sagemath/sage#34680]
<div id="comment:0"></div>

As suggested in https://sagemath.zulipchat.com/#narrow/stream/271086-feedback/topic/hello/near/304508816

Depends on #34434

CC:  @dcoudert @dimpase

Component: **packages: optional**

Author: **Matthias Koeppe**

Branch/Commit: **[`dd328e8`](https://github.com/sagemath/sagetrac-mirror/commit/dd328e8d3b6f0707acf805bf37f2cf14c2875ef5)**

Reviewer: **David Coudert**

_Issue created by migration from https://trac.sagemath.org/ticket/34680_

**Comment by mkoeppe** [comment]
Dependencies: **#34434**

**Comment by mkoeppe** [comment]
Branch: **[u/mkoeppe/igraph__python_igraph__update_to_0_10_2](https://github.com/sagemath/sagetrac-mirror/tree/u/mkoeppe/igraph__python_igraph__update_to_0_10_2)**

**Comment by mkoeppe** [comment]
Author: **Matthias Koeppe**

**Comment by mkoeppe** [comment]
Commit: **[`dd328e8`](https://github.com/sagemath/sagetrac-mirror/commit/dd328e8d3b6f0707acf805bf37f2cf14c2875ef5)**

**Comment by mkoeppe** [comment]
<div id="comment:3"></div>

New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/73055b1f7de4955f5143c2a477a59d4ea945637a"><code>73055b1</code></a></td><td><code>sage -package update-latest: Handle wheel packages, use distribution name from install-requires.txt</code></td></tr><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/b0f638d9b3db3e2a251d530217e8c7d090bce860"><code>b0f638d</code></a></td><td><code>Minor fixes</code></td></tr><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/605492c3fab1058f0d0fb805d713c46e96708bf4"><code>605492c</code></a></td><td><code>Merge #34434</code></td></tr><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/5526199750a1320b5d10f14a82bd4f75a1139148"><code>5526199</code></a></td><td><code>build/pkgs/python_igraph: Update to 0.10.2</code></td></tr><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/dd328e8d3b6f0707acf805bf37f2cf14c2875ef5"><code>dd328e8</code></a></td><td><code>build/pkgs/igraph: Update to 0.10.2</code></td></tr></table>

**Comment by dcoudert** [comment]
Reviewer: **David Coudert**

**Comment by dcoudert** [comment]
<div id="comment:4" align="right">comment:4</div>

Successfully tested on fedora 35 and macOS 12.5.1.

LGTM.

**Comment by mkoeppe** [comment]
<div id="comment:5" align="right">comment:5</div>

Thanks!

**Comment by vbraun** [comment]
Changed branch from **[u/mkoeppe/igraph__python_igraph__update_to_0_10_2](https://github.com/sagemath/sagetrac-mirror/tree/u/mkoeppe/igraph__python_igraph__update_to_0_10_2)** to **[`dd328e8`](https://github.com/sagemath/sagetrac-mirror/commit/dd328e8d3b6f0707acf805bf37f2cf14c2875ef5)**
