### ISSUE TITLE
Frobenius endomorphism creation fail for infinite ring extension

### ISSUE THREAD

**Issue by kryzar** [sagemath/sage#34692]
<div id="comment:0"></div>

I wish to instantiate the Frobenius endomorphism of the field `Fq(X)` seen as a ring over `Fq[X]`. The following raises an exception:

```
sage: Fq = GF(11)
sage: FqX.<X> = Fq[]
sage: k = Frac(FqX)
sage: i = Hom(FqX, k).natural_map()
sage: K = k.over(i)
sage: K.frobenius_endomorphism()
---------------------------------------------------------------------------
NotImplementedError                       Traceback (most recent call last)
Input In [43], in <cell line: 6>()
      4 i = Hom(FqX, k).natural_map()
      5 K = k.over(i)
----> 6 K.frobenius_endomorphism()

File $SAGE_ROOT/sage/src/sage/rings/ring.pyx:1428, in sage.rings.ring.CommutativeRing.frobenius_endomorphism()
   1426     """
   1427     from .morphism import FrobeniusEndomorphism_generic
-> 1428     return FrobeniusEndomorphism_generic(self, n)
   1429 
   1430 def derivation_module(self, codomain=None, twist=None):

File $SAGE_ROOT/sage/src/sage/rings/morphism.pyx:2929, in sage.rings.morphism.FrobeniusEndomorphism_generic.__init__()
   2927 if not isinstance(domain, CommutativeRing):
   2928     raise TypeError("The base ring must be a commutative ring")
-> 2929 self._p = domain.characteristic()
   2930 if not self._p.is_prime():
   2931     raise TypeError("the characteristic of the base ring must be prime")

File $SAGE_ROOT/sage/src/sage/categories/rings.py:588, in Rings.ParentMethods.characteristic(self)
    586 from sage.rings.infinity import infinity
    587 from sage.rings.integer_ring import ZZ
--> 588 order_1 = self.one().additive_order()
    589 return ZZ.zero() if order_1 is infinity else order_1

File $SAGE_ROOT/sage/src/sage/rings/ring_extension_element.pyx:415, in sage.rings.ring_extension_element.RingExtensionElement.additive_order()
    413         5
    414     """
--> 415     return self._backend.additive_order()
    416 
    417 def multiplicative_order(self):

File $SAGE_ROOT/sage/src/sage/structure/element.pyx:2818, in sage.structure.element.RingElement.additive_order()
   2816     Return the additive order of ``self``.
   2817     """
-> 2818     raise NotImplementedError
   2819 
   2820 def multiplicative_order(self):

NotImplementedError:
```

Best,

Antoine Leudière

CC:  @DavidAyotte @xcaruso

Component: **algebra**

Author: **Antoine Leudière**

Branch/Commit: **[`ab2c211`](https://github.com/sagemath/sagetrac-mirror/commit/ab2c211033e15fa5237b20690a715d50577d06f1)**

Reviewer: **Xavier Caruso, David Ayotte**

_Issue created by migration from https://trac.sagemath.org/ticket/34692_

**Comment by DavidAyotte** [comment]
<div id="comment:1" align="right">comment:1</div>

Hi Antoine! I think that to make this works, you need to implement the `characteristic` method of a ring over a base.

**Comment by DavidAyotte** [comment]
<div id="comment:2" align="right">comment:2</div>

I investigated a bit further and, to make your above code work, I think that you simply need to implement the characteristic method for the class `sage.rings.ring_extensions.RingExtension_generic`:

```python
    def characteristic(self):
        return self._backend.characteristic()
```

I cc'ed Xavier here because he implemented extensions of rings and therefore he might know a better way to solve this.

**Comment by kryzar** [comment]
<div id="comment:3" align="right">comment:3</div>

Thank you David for the input. I am happy to do it!

A.

**Comment by kryzar** [comment]
Branch: **[public/ring-extension-characteristic](https://github.com/sagemath/sagetrac-mirror/tree/public/ring-extension-characteristic)**

**Comment by kryzar** [comment]
Commit: **[`501a254`](https://github.com/sagemath/sagetrac-mirror/commit/501a25411904ead8d9b097f465cd40b984eaa701)**

**Comment by kryzar** [comment]
<div id="comment:4" align="right">comment:4</div>

Here is a proposal. Let me know what you think.

Best,
Antoine

---
New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/501a25411904ead8d9b097f465cd40b984eaa701"><code>501a254</code></a></td><td><code>Implement `characteristic` method for rings extensions</code></td></tr></table>

**Comment by DavidAyotte** [comment]
<div id="comment:5" align="right">comment:5</div>

Very minor detail: in the output field you could write instead

```
A prime number or zero.
```
Also, I think that sometimes it is acceptable to omit the output field in the documentation when the output is relatively straightforward (but you can keep it like that, it's perfectly fine too).

If you are happy with your changes you can put your ticket in "need review". The next step would be to wait for the build actions to finish.

**Comment by DavidAyotte** [comment]
Author: **Antoine Leudière**

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
Changed commit from **[`501a254`](https://github.com/sagemath/sagetrac-mirror/commit/501a25411904ead8d9b097f465cd40b984eaa701)** to **[`bcffa0c`](https://github.com/sagemath/sagetrac-mirror/commit/bcffa0cf0842ebef2403d5c8b6aa88514beb86e1)**

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
<div id="comment:6"></div>

Branch pushed to git repo; I updated commit sha1. New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/bcffa0cf0842ebef2403d5c8b6aa88514beb86e1"><code>bcffa0c</code></a></td><td><code>Fix imprecision in documentation</code></td></tr></table>

**Comment by kryzar** [comment]
<div id="comment:7" align="right">comment:7</div>

Replying to [David Ayotte](#comment%3A5):
> Very minor detail: in the output field you could write instead
> 
> ```
> A prime number or zero.
> ```

I am so stupid.

> Also, I think that sometimes it is acceptable to omit the output field in the documentation when the output is relatively straightforward (but you can keep it like that, it's perfectly fine too).

I think this can help resolve any ambiguities.

> 
> If you are happy with your changes you can put your ticket in "need review". The next step would be to wait for the build actions to finish.

Thanks a lot; it was mostly your work (comment [comment:2]).

Best,

Antoine

---
New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/bcffa0cf0842ebef2403d5c8b6aa88514beb86e1"><code>bcffa0c</code></a></td><td><code>Fix imprecision in documentation</code></td></tr></table>

**Comment by xcaruso** [comment]
<div id="comment:9" align="right">comment:9</div>

Maybe, you should also have an example `B.over(A)` where `A` and `B` have different characteristic.
For example, I suggest to replace your last example by

```
    sage: E = Fp(7).over(ZZ)
    sage: E.characteristic()
    7
```

Also you should add a doctest (in the section TESTS) demonstrating that the bug noticed in this ticket is fixed.

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
<div id="comment:10"></div>

Branch pushed to git repo; I updated commit sha1. New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/675e24988a07f58d092a7ddb976c9e6ee04f3ba6"><code>675e249</code></a></td><td><code>Add tests for characteristic method</code></td></tr></table>

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
Changed commit from **[`bcffa0c`](https://github.com/sagemath/sagetrac-mirror/commit/bcffa0cf0842ebef2403d5c8b6aa88514beb86e1)** to **[`675e249`](https://github.com/sagemath/sagetrac-mirror/commit/675e24988a07f58d092a7ddb976c9e6ee04f3ba6)**

**Comment by xcaruso** [comment]
<div id="comment:11" align="right">comment:11</div>

For the last example, you don't need to create `i`. The following code works well:

```
sage: Fq = GF(11)
sage: FqX.<X> = Fq[]
sage: k = Frac(FqX)
sage: K = k.over(FqX)
sage: K.frobenius_endomorphism()
```

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
Changed commit from **[`675e249`](https://github.com/sagemath/sagetrac-mirror/commit/675e24988a07f58d092a7ddb976c9e6ee04f3ba6)** to **[`ab2c211`](https://github.com/sagemath/sagetrac-mirror/commit/ab2c211033e15fa5237b20690a715d50577d06f1)**

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
<div id="comment:12"></div>

Branch pushed to git repo; I updated commit sha1. New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/ab2c211033e15fa5237b20690a715d50577d06f1"><code>ab2c211</code></a></td><td><code>Fix doctest</code></td></tr></table>

**Comment by xcaruso** [comment]
<div id="comment:13" align="right">comment:13</div>

Looks good to me. Waiting for the patchbot.

**Comment by DavidAyotte** [comment]
<div id="comment:14" align="right">comment:14</div>

Looks good to me too! The failed doctest of the patchbot is definitely not related to this ticket and all the Github actions passed.

**Comment by DavidAyotte** [comment]
Reviewer: **Xavier Caruso, David Ayotte**

**Comment by kryzar** [comment]
<div id="comment:15" align="right">comment:15</div>

Copy that! Thank you for the review.

Does that mean I can merge this branch into that of Drinfeld modules? I need the patch to fix some bugs. Or should I wait for something else?

Best,

Antoine

**Comment by DavidAyotte** [comment]
<div id="comment:16" align="right">comment:16</div>

You can merge it an add this ticket number in the "dependencies" field of your ticket on Drinfeld modules. For more info, see https://doc.sagemath.org/html/en/developer/trac.html#the-ticket-fields

**Comment by vbraun** [comment]
Changed branch from **[public/ring-extension-characteristic](https://github.com/sagemath/sagetrac-mirror/tree/public/ring-extension-characteristic)** to **[`ab2c211`](https://github.com/sagemath/sagetrac-mirror/commit/ab2c211033e15fa5237b20690a715d50577d06f1)**
