### ISSUE TITLE
Fix conversion bug in modular forms rings

### ISSUE THREAD

**Issue by DavidAyotte** [sagemath/sage#34698]
<div id="comment:0"></div>

We currently have the following behavior:

```
sage: M = ModularFormsRing(Gamma0(2))
sage: E4 = ModularForms(1, 4).0
sage: F = M(E4)
sage: F[4].parent()
Modular Forms space of dimension 1 for Modular Group SL(2,Z) of weight 4 over Rational Field
```
The parent of `F[4]` is wrong as the group should be `Gamma0(2)`.

CC:  @videlec

Component: **modular forms**

Author: **David Ayotte**

Branch/Commit: **[`ba35b10`](https://github.com/sagemath/sagetrac-mirror/commit/ba35b103f8bbb3d4f82fd327b57d7ccd16699ec2)**

Reviewer: **Vincent Delecroix**

_Issue created by migration from https://trac.sagemath.org/ticket/34698_

**Comment by DavidAyotte** [comment]
Branch: **[u/gh-DavidAyotte/fix_modform_ring_conversion](https://github.com/sagemath/sagetrac-mirror/tree/u/gh-DavidAyotte/fix_modform_ring_conversion)**

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
Commit: **[`f3c6b0d`](https://github.com/sagemath/sagetrac-mirror/commit/f3c6b0db8e5e621c68d94a93441d944d0c5dad0d)**

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
<div id="comment:2"></div>

Branch pushed to git repo; I updated commit sha1. New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/f3c6b0db8e5e621c68d94a93441d944d0c5dad0d"><code>f3c6b0d</code></a></td><td><code>small changes</code></td></tr></table>

**Comment by DavidAyotte** [comment]
Author: **David Ayotte**

**Comment by videlec** [comment]
<div id="comment:4" align="right">comment:4</div>

In your change

```diff
-                forms_dictionary = {forms_datum.weight():forms_datum}
+                forms_dictionary = {forms_datum.weight() : forms_datum}
```
the spacing is wrong. It should be "no space before and one space after".

```
forms_dictionary = {forms_datum.weight(): forms_datum}
```

**Comment by videlec** [comment]
<div id="comment:5" align="right">comment:5</div>

See https://peps.python.org/pep-0008/

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
<div id="comment:7"></div>

Branch pushed to git repo; I updated commit sha1. New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/ba35b103f8bbb3d4f82fd327b57d7ccd16699ec2"><code>ba35b10</code></a></td><td><code>src/sage/modular/modform/ring.py: fix bad spacing in dictionaries</code></td></tr></table>

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
Changed commit from **[`f3c6b0d`](https://github.com/sagemath/sagetrac-mirror/commit/f3c6b0db8e5e621c68d94a93441d944d0c5dad0d)** to **[`ba35b10`](https://github.com/sagemath/sagetrac-mirror/commit/ba35b103f8bbb3d4f82fd327b57d7ccd16699ec2)**

**Comment by DavidAyotte** [comment]
<div id="comment:8" align="right">comment:8</div>

Replying to [Vincent Delecroix](#comment%3A4):
> In your change
> 
> ```diff
> -                forms_dictionary = {forms_datum.weight():forms_datum}
> +                forms_dictionary = {forms_datum.weight() : forms_datum}
> ```
> the spacing is wrong. It should be "no space before and one space after".
> 
> ```
> forms_dictionary = {forms_datum.weight(): forms_datum}
> ```

My bad, thank you for pointing this out!

**Comment by videlec** [comment]
Reviewer: **Vincent Delecroix**

**Comment by vbraun** [comment]
Changed branch from **[u/gh-DavidAyotte/fix_modform_ring_conversion](https://github.com/sagemath/sagetrac-mirror/tree/u/gh-DavidAyotte/fix_modform_ring_conversion)** to **[`ba35b10`](https://github.com/sagemath/sagetrac-mirror/commit/ba35b103f8bbb3d4f82fd327b57d7ccd16699ec2)**
