### ISSUE TITLE
companion matrix of constant polynomial has the wrong parent

### ISSUE THREAD

**Issue by mezzarobba** [sagemath/sage#34691]
<div id="comment:0"></div>

```
sage: companion_matrix([QQ.one()]).parent()
Full MatrixSpace of 0 by 0 dense matrices over Integer Ring
```

Component: **linear algebra**

Author: **Marc Mezzarobba**

Branch/Commit: **[`9acf764`](https://github.com/sagemath/sagetrac-mirror/commit/9acf7643c3999d616ae100df9e4aa86b9cc1cb23)**

Reviewer: **David Ayotte**

_Issue created by migration from https://trac.sagemath.org/ticket/34691_

**Comment by mezzarobba** [comment]
Author: **Marc Mezzarobba**

**Comment by mezzarobba** [comment]
<div id="comment:1"></div>

New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/9acf7643c3999d616ae100df9e4aa86b9cc1cb23"><code>9acf764</code></a></td><td><code>fix parent of 0×0 companion matrix</code></td></tr></table>

**Comment by mezzarobba** [comment]
Branch: **[u/mmezzarobba/34691-companion_matrix](https://github.com/sagemath/sagetrac-mirror/tree/u/mmezzarobba/34691-companion_matrix)**

**Comment by mezzarobba** [comment]
Commit: **[`9acf764`](https://github.com/sagemath/sagetrac-mirror/commit/9acf7643c3999d616ae100df9e4aa86b9cc1cb23)**

**Comment by DavidAyotte** [comment]
<div id="comment:2" align="right">comment:2</div>

Hi! It looks good to me. Thank you for this fix!

**Comment by DavidAyotte** [comment]
Reviewer: **gh-DavidAyotte**

**Comment by DavidAyotte** [comment]
Changed reviewer from **gh-DavidAyotte** to **David Ayotte**

**Comment by mezzarobba** [comment]
<div id="comment:5" align="right">comment:5</div>

Thanks for the review!

**Comment by vbraun** [comment]
Changed branch from **[u/mmezzarobba/34691-companion_matrix](https://github.com/sagemath/sagetrac-mirror/tree/u/mmezzarobba/34691-companion_matrix)** to **[`9acf764`](https://github.com/sagemath/sagetrac-mirror/commit/9acf7643c3999d616ae100df9e4aa86b9cc1cb23)**
