### ISSUE TITLE
Graph orientations require sorting vertices

### ISSUE THREAD

**Issue by pelegm** [sagemath/sage#34696]
<div id="comment:0"></div>

When one wishes to iterate over all orientations of a given graph, the procedure involves sorting the vertices of that graph. This causes errors when the vertices are not comparable. Example:

```
sage: T = Graph()                                              
sage: T.add_vertices([1,(2,3)])                                
sage: list(T.orientations())                                   
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-33-c6d7d547fed1> in <module>
----> 1 list(T.orientations())

/usr/lib/python3/dist-packages/sage/graphs/graph.py in orientations(self, data_structure, sparse)
   3775 
   3776         if not self.size():
-> 3777             D = DiGraph(data=[self.vertices(), []],
   3778                         format='vertices_and_edges',
   3779                         name=name,

/usr/lib/python3/dist-packages/sage/graphs/generic_graph.py in vertices(self, sort, key)
  10609             raise ValueError('sort keyword is False, yet a key function is given')
  10610         if sort:
> 10611             return sorted(list(self.vertex_iterator()), key=key)
  10612         return list(self.vertex_iterator())
  10613 

TypeError: '<' not supported between instances of 'int' and 'tuple'
```

Component: **graph theory**

Keywords: **orientation, digraph**

Reviewer: **David Coudert**

_Issue created by migration from https://trac.sagemath.org/ticket/34696_

**Comment by pelegm** [comment]
<div id="comment:1" align="right">comment:1</div>

The problem exists even when one tries `T.vertices()`, but one can overcome this by setting `sort=False` there.

**Comment by dcoudert** [comment]
<div id="comment:2" align="right">comment:2</div>

Which version of Sagemath are you using ?

In the code of 9.8.beta2 I see

```
        if not self.size():
            D = DiGraph(data=[self.vertices(sort=False), []],
```

and I can do:

```
sage: sage: T = Graph()
sage: sage: T.add_vertices([1,(2,3)])
sage: sage: list(T.orientations())
[Digraph on 2 vertices]
```

**Comment by pelegm** [comment]
<div id="comment:3" align="right">comment:3</div>

Oh, sorry! I am using [SageMath](../wiki/SageMath) version 9.0, Release Date: 2020-01-01. I should probably upgrade.

**Comment by dcoudert** [comment]
<div id="comment:4" align="right">comment:4</div>

The change has been done in ##22349, merge in sagemath 9.7. So yes, please check with the last version.

**Comment by pelegm** [comment]
<div id="comment:5" align="right">comment:5</div>

I apologise.

I can't remember: how do I close this ticket?

**Comment by dcoudert** [comment]
Reviewer: **David Coudert**

**Comment by dcoudert** [comment]
<div id="comment:6" align="right">comment:6</div>

no worries, it's better to check.
