### ISSUE TITLE
Further support for matplotlib 3.6

### ISSUE THREAD

**Issue by kiwifb** [sagemath/sage#34693]
<div id="comment:0"></div>

#34668 was focusing on making doctests pass but did not test docbuilding.

The following plot in `src/sage/plot/plot.py`

```
    .. PLOT::

        g = plot(2*x+1,(x,0,5),ticks=[[0,1,e,pi,sqrt(20)],2],tick_formatter="latex")
        sphinx_plot(g)
```
is causing the building of the documentation to fail horribly.

```
[plotting ]  from /home/portage/sci-mathematics/sage-doc-9999/work/sage-doc-9999/src/doc/en/reference/plotting/sage/plot/plot.rst:
[plotting ] Traceback (most recent call last):
[plotting ]   File "/usr/lib/python3.10/site-packages/matplotlib/artist.py", line 1378, in _get_tightbbox_for_layout_only
[plotting ]     return obj.get_tightbbox(*args, **{**kwargs, "for_layout_only": True})
[plotting ]   File "/usr/lib/python3.10/site-packages/matplotlib/axis.py", line 1251, in get_tightbbox
[plotting ]     ticks_to_draw = self._update_ticks()
[plotting ]   File "/usr/lib/python3.10/site-packages/matplotlib/axis.py", line 1198, in _update_ticks
[plotting ]     minor_locs = self.get_minorticklocs()
[plotting ]   File "/usr/lib/python3.10/site-packages/matplotlib/axis.py", line 1431, in get_minorticklocs
[plotting ]     mask = np.isclose(tr_minor_locs[:, None], tr_major_locs[None, :],
[plotting ]   File "<__array_function__ internals>", line 180, in isclose
[plotting ]   File "/usr/lib/python3.10/site-packages/numpy/core/numeric.py", line 2373, in isclose
[plotting ]     yfin = isfinite(y)
[plotting ] TypeError: ufunc 'isfinite' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''
[plotting ] During handling of the above exception, another exception occurred:
[plotting ] Traceback (most recent call last):
[plotting ]   File "/usr/lib/python3.10/site-packages/matplotlib/artist.py", line 1378, in _get_tightbbox_for_layout_only
[plotting ]     return obj.get_tightbbox(*args, **{**kwargs, "for_layout_only": True})
[plotting ]   File "/usr/lib/python3.10/site-packages/matplotlib/axes/_base.py", line 4428, in get_tightbbox
[plotting ]     ba = martist._get_tightbbox_for_layout_only(axis, renderer)
[plotting ]   File "/usr/lib/python3.10/site-packages/matplotlib/artist.py", line 1380, in _get_tightbbox_for_layout_only
[plotting ]     return obj.get_tightbbox(*args, **kwargs)
[plotting ]   File "/usr/lib/python3.10/site-packages/matplotlib/axis.py", line 1251, in get_tightbbox
[plotting ]     ticks_to_draw = self._update_ticks()
[plotting ]   File "/usr/lib/python3.10/site-packages/matplotlib/axis.py", line 1198, in _update_ticks
[plotting ]     minor_locs = self.get_minorticklocs()
[plotting ]   File "/usr/lib/python3.10/site-packages/matplotlib/axis.py", line 1431, in get_minorticklocs
[plotting ]     mask = np.isclose(tr_minor_locs[:, None], tr_major_locs[None, :],
[plotting ]   File "<__array_function__ internals>", line 180, in isclose
[plotting ]   File "/usr/lib/python3.10/site-packages/numpy/core/numeric.py", line 2373, in isclose
[plotting ]     yfin = isfinite(y)
[plotting ] TypeError: ufunc 'isfinite' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''
[plotting ] During handling of the above exception, another exception occurred:
[plotting ] Traceback (most recent call last):
[plotting ]   File "/usr/lib/python3.10/site-packages/matplotlib/artist.py", line 1378, in _get_tightbbox_for_layout_only
[plotting ]     return obj.get_tightbbox(*args, **{**kwargs, "for_layout_only": True})
[plotting ]   File "/usr/lib/python3.10/site-packages/matplotlib/axis.py", line 1251, in get_tightbbox
[plotting ]     ticks_to_draw = self._update_ticks()
[plotting ]   File "/usr/lib/python3.10/site-packages/matplotlib/axis.py", line 1198, in _update_ticks
[plotting ]     minor_locs = self.get_minorticklocs()
[plotting ]   File "/usr/lib/python3.10/site-packages/matplotlib/axis.py", line 1431, in get_minorticklocs
[plotting ]     mask = np.isclose(tr_minor_locs[:, None], tr_major_locs[None, :],
[plotting ]   File "<__array_function__ internals>", line 180, in isclose
[plotting ]   File "/usr/lib/python3.10/site-packages/numpy/core/numeric.py", line 2373, in isclose
[plotting ]     yfin = isfinite(y)
[plotting ] TypeError: ufunc 'isfinite' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''
[plotting ] During handling of the above exception, another exception occurred:
[plotting ] Traceback (most recent call last):
[plotting ]   File "/usr/lib/python3.10/site-packages/matplotlib/sphinxext/plot_directive.py", line 515, in _run_code
[plotting ]     exec(code, ns)
[plotting ]   File "<string>", line 2, in <module>
[plotting ]   File "<string>", line 37, in sphinx_plot
[plotting ]   File "/usr/lib/python3.10/site-packages/matplotlib/figure.py", line 3448, in tight_layout
[plotting ]     engine.execute(self)
[plotting ]   File "/usr/lib/python3.10/site-packages/matplotlib/layout_engine.py", line 180, in execute
[plotting ]     kwargs = get_tight_layout_figure(
[plotting ]   File "/usr/lib/python3.10/site-packages/matplotlib/_tight_layout.py", line 305, in get_tight_layout_figure
[plotting ]     kwargs = _auto_adjust_subplotpars(fig, renderer,
[plotting ]   File "/usr/lib/python3.10/site-packages/matplotlib/_tight_layout.py", line 82, in _auto_adjust_subplotpars
[plotting ]     bb += [martist._get_tightbbox_for_layout_only(ax, renderer)]
[plotting ]   File "/usr/lib/python3.10/site-packages/matplotlib/artist.py", line 1380, in _get_tightbbox_for_layout_only
[plotting ]     return obj.get_tightbbox(*args, **kwargs)
[plotting ]   File "/usr/lib/python3.10/site-packages/matplotlib/axes/_base.py", line 4428, in get_tightbbox
[plotting ]     ba = martist._get_tightbbox_for_layout_only(axis, renderer)
[plotting ]   File "/usr/lib/python3.10/site-packages/matplotlib/artist.py", line 1380, in _get_tightbbox_for_layout_only
[plotting ]     return obj.get_tightbbox(*args, **kwargs)
[plotting ]   File "/usr/lib/python3.10/site-packages/matplotlib/axis.py", line 1251, in get_tightbbox
[plotting ]     ticks_to_draw = self._update_ticks()
[plotting ]   File "/usr/lib/python3.10/site-packages/matplotlib/axis.py", line 1198, in _update_ticks
[plotting ]     minor_locs = self.get_minorticklocs()
[plotting ]   File "/usr/lib/python3.10/site-packages/matplotlib/axis.py", line 1431, in get_minorticklocs
[plotting ]     mask = np.isclose(tr_minor_locs[:, None], tr_major_locs[None, :],
[plotting ]   File "<__array_function__ internals>", line 180, in isclose
[plotting ]   File "/usr/lib/python3.10/site-packages/numpy/core/numeric.py", line 2373, in isclose
[plotting ]     yfin = isfinite(y)
[plotting ] TypeError: ufunc 'isfinite' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''
```
Tests of this plot were disabled in #34668 and now we need to remove the plot. The whole example needs to be replaced by something that works.

We could not overcome the problem of symbolic values that numpy rejects, but instead made a fix to circumvent numpy and revived the doctest and the example.

CC:  @tornaria

Component: **documentation**

Author: **Kwankyu Lee**

Branch/Commit: **[`6458968`](https://github.com/sagemath/sagetrac-mirror/commit/64589686c261d33e6b5aff2589bcae8af004bcc6)**

Reviewer: **Matthias Koeppe**

_Issue created by migration from https://trac.sagemath.org/ticket/34693_

**Comment by kiwifb** [comment]
<div id="comment:1" align="right">comment:1</div>

Currently making sure that this it the only change required and providing support to sage-on-gentoo users already using matplotlib 3.6.x before pushing a branch here.

**Comment by kiwifb** [comment]
Author: **François Bissey**

**Comment by kiwifb** [comment]
Branch: **[u/tornaria/matplotlib-3.6](https://github.com/sagemath/sagetrac-mirror/tree/u/tornaria/matplotlib-3.6)**

**Comment by kiwifb** [comment]
<div id="comment:2" align="right">comment:2</div>

The attached branch will let you build the doc with matplotlib 3.6.

---
New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/5501e0de0dca1cff0355326dd42bd8c7e5749568"><code>5501e0d</code></a></td><td><code>Support matplotlib 3.6</code></td></tr></table>

**Comment by kiwifb** [comment]
Commit: **[`5501e0d`](https://github.com/sagemath/sagetrac-mirror/commit/5501e0de0dca1cff0355326dd42bd8c7e5749568)**

**Comment by kiwifb** [comment]
<div id="comment:3" align="right">comment:3</div>

Not sure how I got to attach the wrong branch. Thankfully, I noticed.

---
New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/8b0c147037018b77b5c8c5147e78c3c7c6388d29"><code>8b0c147</code></a></td><td><code>Merge branch 'mpl3.6_doctest' into mpl3.6_docbuilding</code></td></tr><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/4645a0d0c10f9f1599aa01362593195af6d27a16"><code>4645a0d</code></a></td><td><code>Removing faulty plot</code></td></tr></table>

**Comment by kiwifb** [comment]
Changed commit from **[`5501e0d`](https://github.com/sagemath/sagetrac-mirror/commit/5501e0de0dca1cff0355326dd42bd8c7e5749568)** to **[`4645a0d`](https://github.com/sagemath/sagetrac-mirror/commit/4645a0d0c10f9f1599aa01362593195af6d27a16)**

**Comment by kiwifb** [comment]
Changed branch from **[u/tornaria/matplotlib-3.6](https://github.com/sagemath/sagetrac-mirror/tree/u/tornaria/matplotlib-3.6)** to **[u/fbissey/MPL3.6_docbuilding](https://github.com/sagemath/sagetrac-mirror/tree/u/fbissey/MPL3.6_docbuilding)**

**Comment by mkoeppe** [comment]
<div id="comment:4" align="right">comment:4</div>

Is this ready for review?

**Comment by kiwifb** [comment]
<div id="comment:5" align="right">comment:5</div>

Yes, it is ready.Our consensus at #34668 is that the point of this particular example is unclear. So, removing it does not seem to be a big deal.

**Comment by mkoeppe** [comment]
<div id="comment:6" align="right">comment:6</div>

I'm hitting the same error (`ufunc 'isfinite' not supported`) also in some of my own plotting code.

**Comment by mkoeppe** [comment]
<div id="comment:7" align="right">comment:7</div>

Possibly related: #29210 scipy.optimize.newton does not accept Sage input anymore

**Comment by kiwifb** [comment]
<div id="comment:8" align="right">comment:8</div>

Yes, I am now wondering if it is an issue that matplotlib (and scipy) may need to adapt to new stuff in numpy. But we cannot leave the plot in, since it breaks building the doc.

**Comment by kwankyu** [comment]
<div id="comment:9" align="right">comment:9</div>

Replying to [François Bissey](#comment%3A5):
> Yes, it is ready. Our consensus at #34668 is that the point of this particular example is unclear. 

It is clear. We can use symbolic values as tick marks. It is a useful feature. I may use it (though I never did :)

> So, removing it does not seem to be a big deal.

Removing a feature to upgrade a package is a big deal.

I investigated the real cause of the failure. Fortunately I found it. It is a kind of bug in matplotlib 3.6. I reported it to upstream:

https://github.com/matplotlib/matplotlib/issues/24557

Let's see how they react before we proceed.

**Comment by kwankyu** [comment]
<div id="comment:10" align="right">comment:10</div>

In the upstream discussion https://github.com/matplotlib/matplotlib/issues/24557#issuecomment-1329891836, they suggested to make our symbolic objects behave more `float`-like: 

> Can you add `isfinite` support to `Expression` (or a `ConstExpression` which may or may not already exist)? It seems to me that being able to ask if an expression is finite is something you should be able to ask.

or numpy-array-like:

> Is it possible for sagemath to provide a `.__array__ `method to convert to numpy arrays? 

I will investigate the former possibility. We have

```python
sage: a = sqrt(2)
sage: a.is_infinity()
False
``` 
but I don't know how to "add `isfinite` support" to satisfy numpy...

**Comment by kwankyu** [comment]
<div id="comment:11" align="right">comment:11</div>


```
sage: np.isfinite(2)
True
```
So Sage integers are numbers from the perspective of numpy. How does it do it?

**Comment by kwankyu** [comment]
<div id="comment:12" align="right">comment:12</div>

BTW, 

```
sage: np.can_cast(type(2), float, 'safe')
False
```
Strange...

**Comment by mkoeppe** [comment]
<div id="comment:13" align="right">comment:13</div>

I don't know if that's the mechanism why it works, but our `Integer`s are registered with the numbers ABC - https://docs.python.org/3/library/numbers.html

**Comment by kwankyu** [comment]
<div id="comment:14" align="right">comment:14</div>

Replying to [Matthias Köppe](#comment%3A13):
> I don't know if that's the mechanism why it works, but our `Integer`s are registered with the numbers ABC - https://docs.python.org/3/library/numbers.html

I tried that, but doesn't work. Not sure I missed something...

**Comment by kwankyu** [comment]
<div id="comment:15" align="right">comment:15</div>

Voilà, I found it. It is

https://numpy.org/doc/stable/reference/arrays.interface.html

**Comment by kwankyu** [comment]
<div id="comment:16" align="right">comment:16</div>

and https://numpy.org/doc/stable/reference/arrays.dtypes.html

Then

```python
class Symbolic(object):
    __array_interface__ = {'typestr': 'f'} 
    
    def __init__(self, a, b):
        self.num = a
        self.den = b
        
    def __str__(self):
        return '{}/{}'.format(self.num, self.den)
        
    def __float__(self):
        return float(self.num / self.den)
    
import matplotlib.pyplot as plt
import numpy as np
import sympy as sym
from matplotlib.ticker import FixedLocator, NullLocator, FuncFormatter

# make data
x = np.linspace(0, 3, 100)
y = 2 * x + 1

# plot
fig, ax = plt.subplots()

ax.plot(x, y, linewidth=2.0)

a = Symbolic(1,2)

ax.xaxis.set_major_locator(FixedLocator([a, 1, 2, 3]))
ax.xaxis.set_minor_locator(NullLocator())
ax.xaxis.set_major_formatter(FuncFormatter(lambda x, pos: str(x)))

plt.show()
```
works. Moreover

```python
>>> a = Symbolic(2,3)
>>> np.isfinite(a)
True
>>> np.array(a)
array(0.6666667, dtype=float32)
```
Hence so we now know how to make `Expression` float-like (from the perspective of numpy).

To implement this mechanism for `Expression` may require major restructuring, since  the scope of `Expression` is much more broad beyond constant expression. As suggested in the upstream discussion, we may need `ConstantExpression` that would hold only constant values, and make that float-like or complex-like. I feel this would be a grand work out of my capacity though. Symbolic expression experts may do it. But the first question is if this work is worth to do. If so, this would need a separate ticket.

**Comment by mkoeppe** [comment]
<div id="comment:17" align="right">comment:17</div>

Does `__array_interface__` have to be a class constant, or could it be a `lazy_attribute`?

**Comment by kwankyu** [comment]
<div id="comment:18" align="right">comment:18</div>

It can be `lazy_attributes` or `property`.

But I realized a major problem. By the mechanism, `Symbolic` is simply converted to floats, and you see `0.5` in the plot instead of `1/2`. So this defeats the original purpose! Now it seems to me that we cannot retain the feature (supporting symbolic ticks)...

**Comment by kwankyu** [comment]
<div id="comment:19" align="right">comment:19</div>

Replying to [Kwankyu Lee](#comment%3A18):
> By the mechanism, `Symbolic` is simply converted to floats, and you see `0.5` in the plot instead of `1/2`. So this defeats the original purpose! Now it seems to me that we cannot retain the feature (supporting symbolic ticks)...

The rescue is to use matplotlib's `FixedFormatter` to provide strings for the tick values separately. This would amount to reimplementing sage's `tick_formatter="latex"`.

Anyway, implementing this together with `ConstantExpression` seems a daunting task apart from the "worth to do" question.

I don't know how frequently the symbolic tick mark feature is used by sage users. If no one uses it :) then perhaps we may turn off this feature while we upgrade matplotlib to 3.6.

**Comment by kiwifb** [comment]
<div id="comment:20" align="right">comment:20</div>

OK. So, it is currently broken and will take some time and efforts to put it right, if there is a will.

In the meantime, the branch removes just a plot showcasing the capability because it breaks building the documentation in sage-on-distros which already have matplotlib 3.6.x available.
Should we comment the plotting code and add reference to a ticket with work in progress or just remove it until things are ready?

**Comment by kwankyu** [comment]
<div id="comment:21" align="right">comment:21</div>

How about just commenting them out mentioning this ticket?

But no one uses it? I really don't know. How about posting on sage-devel to prevent some one later to complain that his/her code doesn't work anymore...

**Comment by mkoeppe** [comment]
<div id="comment:22" align="right">comment:22</div>

I definitely use this feature (comment:6); -1 on removing the test

**Comment by kwankyu** [comment]
<div id="comment:23" align="right">comment:23</div>

Replying to [Matthias Köppe](#comment%3A22):
> I definitely use this feature (comment:6); -1 on removing the test

+1. 

Meanwhile I learned enough matplotlib to make up a simple fix for this ticket.

**Comment by kwankyu** [comment]
Changed author from **François Bissey** to **Kwankyu Lee**

**Comment by kwankyu** [comment]
Changed branch from **[u/fbissey/MPL3.6_docbuilding](https://github.com/sagemath/sagetrac-mirror/tree/u/fbissey/MPL3.6_docbuilding)** to **[u/klee/MPL3.6_docbuilding](https://github.com/sagemath/sagetrac-mirror/tree/u/klee/MPL3.6_docbuilding)**

**Comment by kwankyu** [comment]
<div id="comment:25"></div>

New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/f0a77039bb2be3eb7cd06c036aaa8085652db403"><code>f0a7703</code></a></td><td><code>Add back doctest</code></td></tr></table>

**Comment by kwankyu** [comment]
Description changed:
``````diff
--- 
+++ 
@@ -89,3 +89,7 @@
 [plotting ] TypeError: ufunc 'isfinite' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''
 ```
 Tests of this plot were disabled in #34668 and now we need to remove the plot. The whole example needs to be replaced by something that works.
+
+We could not overcome the problem of symbolic values that numpy rejects, but instead made a fix to circumvent numpy and revived the doctest and the example.
+
+
``````

**Comment by kwankyu** [comment]
Changed commit from **[`4645a0d`](https://github.com/sagemath/sagetrac-mirror/commit/4645a0d0c10f9f1599aa01362593195af6d27a16)** to **[`f0a7703`](https://github.com/sagemath/sagetrac-mirror/commit/f0a77039bb2be3eb7cd06c036aaa8085652db403)**

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
Changed commit from **[`f0a7703`](https://github.com/sagemath/sagetrac-mirror/commit/f0a77039bb2be3eb7cd06c036aaa8085652db403)** to **[`a8741d8`](https://github.com/sagemath/sagetrac-mirror/commit/a8741d8c60dc3e173b18cc373c4c203fcc2cec4f)**

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
<div id="comment:26"></div>

Branch pushed to git repo; I updated commit sha1. New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/8371dd75013d5b973333b6e577e7ef17bbf042c1"><code>8371dd7</code></a></td><td><code>Missing part of the fix</code></td></tr><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/dbfb9539ab9bbb5b2e460f4c4576835c58e84a2e"><code>dbfb953</code></a></td><td><code>Merge branch 'develop' into t/34693/MPL3.6_docbuilding</code></td></tr><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/a8741d8c60dc3e173b18cc373c4c203fcc2cec4f"><code>a8741d8</code></a></td><td><code>Edit the doctest</code></td></tr></table>

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
Changed commit from **[`a8741d8`](https://github.com/sagemath/sagetrac-mirror/commit/a8741d8c60dc3e173b18cc373c4c203fcc2cec4f)** to **[`6458968`](https://github.com/sagemath/sagetrac-mirror/commit/64589686c261d33e6b5aff2589bcae8af004bcc6)**

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
<div id="comment:27"></div>

Branch pushed to git repo; I updated commit sha1. New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/64589686c261d33e6b5aff2589bcae8af004bcc6"><code>6458968</code></a></td><td><code>More edis of the doctest</code></td></tr></table>

**Comment by mkoeppe** [comment]
Reviewer: **Matthias Koeppe**

**Comment by mkoeppe** [comment]
<div id="comment:28" align="right">comment:28</div>

I can confirm that this also fixes the issue in my plotting code. Thanks a lot for working on it!

**Comment by kwankyu** [comment]
<div id="comment:29" align="right">comment:29</div>

Thanks. I also checked the branch with #34796 that upgrades matplotlib to 3.6. It works well.

**Comment by vbraun** [comment]
Changed branch from **[u/klee/MPL3.6_docbuilding](https://github.com/sagemath/sagetrac-mirror/tree/u/klee/MPL3.6_docbuilding)** to **[`6458968`](https://github.com/sagemath/sagetrac-mirror/commit/64589686c261d33e6b5aff2589bcae8af004bcc6)**
