### ISSUE TITLE
some details about INPUT and INPUT in the doc

### ISSUE THREAD

**Issue by fchapoton** [sagemath/sage#34699]
<div id="comment:0"></div>

namely, add empty line after it when it is missing

also separate if the content is multiline

found using

```
git grep -A1 "PUT:" src/ | grep -v "PUT:" | grep "py-.*[a-z]"
```

CC:  @tscrim @slel @kwankyu @kliem

Component: **documentation**

Author: **Frédéric Chapoton**

Branch/Commit: **[`7fc01de`](https://github.com/sagemath/sagetrac-mirror/commit/7fc01deff4eb6c2d17bc3785126e07d7ed88c3e9)**

Reviewer: **Travis Scrimshaw, David Coudert**

_Issue created by migration from https://trac.sagemath.org/ticket/34699_

**Comment by fchapoton** [comment]
Branch: **[u/chapoton/34699](https://github.com/sagemath/sagetrac-mirror/tree/u/chapoton/34699)**

**Comment by fchapoton** [comment]
Commit: **[`87b4d8e`](https://github.com/sagemath/sagetrac-mirror/commit/87b4d8ec4a315a31bfa51a7a40eb5d52b603217d)**

**Comment by fchapoton** [comment]
<div id="comment:1"></div>

New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/87b4d8ec4a315a31bfa51a7a40eb5d52b603217d"><code>87b4d8e</code></a></td><td><code>some details about OUTPUT and INPUT in the doc</code></td></tr></table>

**Comment by fchapoton** [comment]
Description changed:
``````diff
--- 
+++ 
@@ -1,4 +1,4 @@
-namely, add empty lien after is missing
+namely, add empty line after it when it is missing
 
 also separate if the content is multiline
 
``````

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
Changed commit from **[`87b4d8e`](https://github.com/sagemath/sagetrac-mirror/commit/87b4d8ec4a315a31bfa51a7a40eb5d52b603217d)** to **[`fdfa523`](https://github.com/sagemath/sagetrac-mirror/commit/fdfa523d3b6444cd92e751f0d2f90ae2981276f4)**

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
<div id="comment:3"></div>

Branch pushed to git repo; I updated commit sha1. New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/fdfa523d3b6444cd92e751f0d2f90ae2981276f4"><code>fdfa523</code></a></td><td><code>a few more details</code></td></tr></table>

**Comment by tscrim** [comment]
Reviewer: **Travis Scrimshaw**

**Comment by tscrim** [comment]
<div id="comment:4" align="right">comment:4</div>

A while-we-are-at-it thing you can ignore if you want, but the bullet points in `categories/examples/` are overindented by the space. Otherwise LGTM.

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
Changed commit from **[`fdfa523`](https://github.com/sagemath/sagetrac-mirror/commit/fdfa523d3b6444cd92e751f0d2f90ae2981276f4)** to **[`7fdda63`](https://github.com/sagemath/sagetrac-mirror/commit/7fdda638f1b51472be81d25a66d7c9d70615eebe)**

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
<div id="comment:5"></div>

Branch pushed to git repo; I updated commit sha1. New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/7fdda638f1b51472be81d25a66d7c9d70615eebe"><code>7fdda63</code></a></td><td><code>fix suggested details</code></td></tr></table>

**Comment by fchapoton** [comment]
<div id="comment:6" align="right">comment:6</div>

thanks, done

**Comment by dcoudert** [comment]
<div id="comment:7" align="right">comment:7</div>

in `src/sage/algebras/free_algebra_quotient.py`

```diff
-    def _coerce_map_from_(self,S):
+    def _coerce_map_from_(self,S ):
```
In `src/sage/categories/examples/finite_coxeter_groups.py`:  <code>- \`n\` -- an integer with \`n>=2\`</code> -> <code>- \`n\` -- an integer with \`n\geq 2\`</code> ?

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
Changed commit from **[`7fdda63`](https://github.com/sagemath/sagetrac-mirror/commit/7fdda638f1b51472be81d25a66d7c9d70615eebe)** to **[`7fc01de`](https://github.com/sagemath/sagetrac-mirror/commit/7fc01deff4eb6c2d17bc3785126e07d7ed88c3e9)**

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
<div id="comment:8"></div>

Branch pushed to git repo; I updated commit sha1. New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/7fc01deff4eb6c2d17bc3785126e07d7ed88c3e9"><code>7fc01de</code></a></td><td><code>more fixes</code></td></tr></table>

**Comment by fchapoton** [comment]
<div id="comment:9" align="right">comment:9</div>

merci, voila. J'en ai profité pour nettoyer les deux fichiers.

**Comment by dcoudert** [comment]
<div id="comment:10" align="right">comment:10</div>

LGTM.

**Comment by dcoudert** [comment]
Changed reviewer from **Travis Scrimshaw** to **Travis Scrimshaw, David Coudert**

**Comment by vbraun** [comment]
Changed branch from **[u/chapoton/34699](https://github.com/sagemath/sagetrac-mirror/tree/u/chapoton/34699)** to **[`7fc01de`](https://github.com/sagemath/sagetrac-mirror/commit/7fc01deff4eb6c2d17bc3785126e07d7ed88c3e9)**
