### ISSUE TITLE
minor fixes in doc in pyx files

### ISSUE THREAD

**Issue by fchapoton** [sagemath/sage#34697]
<div id="comment:0"></div>

found using

```
git grep -A3 "STS::" src/sage/ | grep -v "STS::" | grep "::"
```
and the same for EXAMPLES

CC:  @tscrim @kwankyu @kliem @slel

Component: **documentation**

Author: **Frédéric Chapoton**

Branch/Commit: **[`01e1843`](https://github.com/sagemath/sagetrac-mirror/commit/01e18432b8c98c57b6c82b11de97bc3ba099b39d)**

Reviewer: **Travis Scrimshaw**

_Issue created by migration from https://trac.sagemath.org/ticket/34697_

**Comment by fchapoton** [comment]
Branch: **[u/chapoton/34697](https://github.com/sagemath/sagetrac-mirror/tree/u/chapoton/34697)**

**Comment by fchapoton** [comment]
<div id="comment:1"></div>

New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/0300962bf65a087a765ac6c897ed0811a314d15b"><code>0300962</code></a></td><td><code>minor fixes in doc in 2 pyx files</code></td></tr></table>

**Comment by fchapoton** [comment]
Commit: **[`0300962`](https://github.com/sagemath/sagetrac-mirror/commit/0300962bf65a087a765ac6c897ed0811a314d15b)**

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
Changed commit from **[`0300962`](https://github.com/sagemath/sagetrac-mirror/commit/0300962bf65a087a765ac6c897ed0811a314d15b)** to **[`01e1843`](https://github.com/sagemath/sagetrac-mirror/commit/01e18432b8c98c57b6c82b11de97bc3ba099b39d)**

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
<div id="comment:2"></div>

Branch pushed to git repo; I updated commit sha1. New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/01e18432b8c98c57b6c82b11de97bc3ba099b39d"><code>01e1843</code></a></td><td><code>more fixes in doc</code></td></tr></table>

**Comment by fchapoton** [comment]
Description changed:
``````diff
--- 
+++ 
@@ -1 +1,7 @@
+found using
 
+```
+git grep -A3 "STS::" src/sage/ | grep -v "STS::" | grep "::"
+```
+and the same for EXAMPLES
+
``````

**Comment by tscrim** [comment]
Reviewer: **Travis Scrimshaw**

**Comment by tscrim** [comment]
<div id="comment:4" align="right">comment:4</div>

LGTM.

**Comment by vbraun** [comment]
Changed branch from **[u/chapoton/34697](https://github.com/sagemath/sagetrac-mirror/tree/u/chapoton/34697)** to **[`01e1843`](https://github.com/sagemath/sagetrac-mirror/commit/01e18432b8c98c57b6c82b11de97bc3ba099b39d)**
