### ISSUE TITLE
fix cython warning in blas_dict

### ISSUE THREAD

**Issue by fchapoton** [sagemath/sage#34709]
<div id="comment:0"></div>

similar to #23771

plus full pep8 cleanup in stream.py

CC:  u/chapoton/34709

Component: **refactoring**

Author: **Frédéric Chapoton**

Branch/Commit: **[`3b1adb8`](https://github.com/sagemath/sagetrac-mirror/commit/3b1adb8d65dfe2c4e6d3091081a1b12b77209c6f)**

Reviewer: **David Coudert**

_Issue created by migration from https://trac.sagemath.org/ticket/34709_

**Comment by fchapoton** [comment]
Branch: **[u/chapoton/34709](https://github.com/sagemath/sagetrac-mirror/tree/u/chapoton/34709)**

**Comment by fchapoton** [comment]
<div id="comment:2"></div>

New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/5a9769fc5becdf0319d7d2277ff1085201eb14d5"><code>5a9769f</code></a></td><td><code>fix cython warning in blas_dict ; plus pep8 in stream</code></td></tr></table>

**Comment by fchapoton** [comment]
Commit: **[`5a9769f`](https://github.com/sagemath/sagetrac-mirror/commit/5a9769fc5becdf0319d7d2277ff1085201eb14d5)**

**Comment by dcoudert** [comment]
<div id="comment:3" align="right">comment:3</div>

LGTM.

**Comment by dcoudert** [comment]
Reviewer: **David Coudert**

**Comment by vbraun** [comment]
<div id="comment:4" align="right">comment:4</div>

Merge failure on top of:

bdcd8e2f903 Trac #34707: Bug in Clifford algebra multiplication

ab40677de1c Trac #34702: fix deprecated use of PyEval_Call*

b8151dc1099 Trac #34681: Error with multiplication of points on elliptic curves over Integers(n)

0fcca83be81 Trac #34651: Add `multivariate_interpolation` for multivariate polynomial rings

7c37d8de415 Trac #34611: fast implementation of exp

0a63c62c2da Trac #34397: pycodestyle cleanup in src/sage/graphs/generic_graph.py (part 9)

1f9b781eee1 Trac #34081: Upgrade scipy to 1.9.x, add meson toolchain

58c9281ec67 Trac #32267: make hadamard_matrix() use all the Hadamard matrices Sage knows

edfa1f93738 Trac #30423: F-Matrix Factory

7aa226ced2f Trac #34699: some details about INPUT and INPUT in the doc

c4079b7488c Trac #34697: minor fixes in doc in pyx files

813072800d9 Trac #34691: companion matrix of constant polynomial has the wrong parent

6b70584ab66 Trac #34638: refresh the file categories/rings.py

f634f6b0195 Trac #34368: implement the F,H,M triangles

859c3516190 Trac #34689: make Compositions() an additive monoid

b5082885f9a Trac #34665: openssl spkg-configure.m4: Also require openssl if curl needs to be built

487f2f9bca8 Trac #34662: sage.combinat.permutation.from_cycles produces wrong result when 'cycles' is a generator

ab0944d9eaf Trac #34636: make sparsity a decision of the user

24d0a8a1219 Trac #34381: Add infinite q-Pochhammer symbol

ef1d3d23588 Trac #34260: Implement northwest diagrams

bff11ac3b18 Trac #33176: Fix a few cython "referenced before assignment" warnings

89af3469590 Trac #32267: make hadamard_matrix() use all the Hadamard matrices Sage knows

c3028e74d80 Updated [SageMath](../wiki/SageMath) version to 9.8.beta3



merge was not clean: conflicts in src/sage/data_structures/stream.py

**Comment by fchapoton** [comment]
<div id="comment:5" align="right">comment:5</div>

conflict is with #34636

**Comment by fchapoton** [comment]
Changed branch from **[u/chapoton/34709](https://github.com/sagemath/sagetrac-mirror/tree/u/chapoton/34709)** to **[u/chapoton/t34709](https://github.com/sagemath/sagetrac-mirror/tree/u/chapoton/t34709)**

**Comment by fchapoton** [comment]
<div id="comment:6" align="right">comment:6</div>

now only touching the file blas_dict.pxd

setting back to positive

---
New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/3b1adb8d65dfe2c4e6d3091081a1b12b77209c6f"><code>3b1adb8</code></a></td><td><code>fix cython warning in blas_dict</code></td></tr></table>

**Comment by fchapoton** [comment]
Changed commit from **[`5a9769f`](https://github.com/sagemath/sagetrac-mirror/commit/5a9769fc5becdf0319d7d2277ff1085201eb14d5)** to **[`3b1adb8`](https://github.com/sagemath/sagetrac-mirror/commit/3b1adb8d65dfe2c4e6d3091081a1b12b77209c6f)**

**Comment by dcoudert** [comment]
<div id="comment:7" align="right">comment:7</div>

OK

**Comment by vbraun** [comment]
Changed branch from **[u/chapoton/t34709](https://github.com/sagemath/sagetrac-mirror/tree/u/chapoton/t34709)** to **[`3b1adb8`](https://github.com/sagemath/sagetrac-mirror/commit/3b1adb8d65dfe2c4e6d3091081a1b12b77209c6f)**
