### ISSUE TITLE
fix deprecated use of PyEval_Call*

### ISSUE THREAD

**Issue by fchapoton** [sagemath/sage#34702]
<div id="comment:0"></div>

Deprecated since Python 3.9 - https://docs.python.org/3/whatsnew/3.9.html?highlight=pyeval_callobject#changes-in-the-c-api

using `PyObject_Call` instead

https://docs.python.org/3/c-api/call.html#c.PyObject_Call

CC:  @tscrim @kwankyu @kliem @slel

Component: **refactoring**

Author: **Frédéric Chapoton**

Branch/Commit: **[`285c58f`](https://github.com/sagemath/sagetrac-mirror/commit/285c58f75903c835647cf1ecbaa5cc220890368d)**

Reviewer: **Matthias Koeppe**

_Issue created by migration from https://trac.sagemath.org/ticket/34702_

**Comment by fchapoton** [comment]
Commit: **[`d9de90a`](https://github.com/sagemath/sagetrac-mirror/commit/d9de90ace8082a5ac80421e2f57c7898bc4dd991)**

**Comment by fchapoton** [comment]
Branch: **[u/chapoton/34702](https://github.com/sagemath/sagetrac-mirror/tree/u/chapoton/34702)**

**Comment by fchapoton** [comment]
<div id="comment:1"></div>

New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/d9de90ace8082a5ac80421e2f57c7898bc4dd991"><code>d9de90a</code></a></td><td><code>fix deprecated use of PyEval_Call</code></td></tr></table>

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
Changed commit from **[`d9de90a`](https://github.com/sagemath/sagetrac-mirror/commit/d9de90ace8082a5ac80421e2f57c7898bc4dd991)** to **[`285c58f`](https://github.com/sagemath/sagetrac-mirror/commit/285c58f75903c835647cf1ecbaa5cc220890368d)**

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
<div id="comment:2"></div>

Branch pushed to git repo; I updated commit sha1. New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/285c58f75903c835647cf1ecbaa5cc220890368d"><code>285c58f</code></a></td><td><code>fix detail</code></td></tr></table>

**Comment by fchapoton** [comment]
<div id="comment:4" align="right">comment:4</div>

green lights, so please review

**Comment by mkoeppe** [comment]
Description changed:
``````diff
--- 
+++ 
@@ -1,3 +1,5 @@
+Deprecated since Python 3.9 - https://docs.python.org/3/whatsnew/3.9.html?highlight=pyeval_callobject#changes-in-the-c-api
+
 using `PyObject_Call` instead
 
 https://docs.python.org/3/c-api/call.html#c.PyObject_Call
``````

**Comment by mkoeppe** [comment]
Reviewer: **Matthias Koeppe**

**Comment by vbraun** [comment]
Changed branch from **[u/chapoton/34702](https://github.com/sagemath/sagetrac-mirror/tree/u/chapoton/34702)** to **[`285c58f`](https://github.com/sagemath/sagetrac-mirror/commit/285c58f75903c835647cf1ecbaa5cc220890368d)**
