### ISSUE TITLE
Remove object entries from TOC

### ISSUE THREAD

**Issue by kwankyu** [sagemath/sage#34706]
<div id="comment:0"></div>

**We decided to go for #34710 instead of this ticket**

Sphinx, upgraded to 5.2.3 in #34615, builds the doc with object (classes, functions, ...) entries in toc (table of contents). 

In a sense, this makes our doc broken since new entries are added to toc unintentionally. Original discussion: [#34615 comment:22](https://github.com/sagemath/sage/issues/34615#comment:22)

This tickets reverts the change using a Sphinx configuration variable, also introduced in Sphinx 5.2.3.

Reference:

https://github.com/sphinx-doc/sphinx/pull/10886

 

Component: **documentation**

Reviewer: **Matthias Koeppe**

_Issue created by migration from https://trac.sagemath.org/ticket/34706_

**Comment by kwankyu** [comment]
Branch: **[u/klee/remove_objects_definitions_from_toc](https://github.com/sagemath/sagetrac-mirror/tree/u/klee/remove_objects_definitions_from_toc)**

**Comment by kwankyu** [comment]
Author: **Kwankyu Lee**

**Comment by kwankyu** [comment]
Commit: **[`e14c857`](https://github.com/sagemath/sagetrac-mirror/commit/e14c85760435dc1721bf626d494e92ac9bfbd46b)**

**Comment by kwankyu** [comment]
<div id="comment:2"></div>

New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/e14c85760435dc1721bf626d494e92ac9bfbd46b"><code>e14c857</code></a></td><td><code>Add toc_object_entries conf variable with False value</code></td></tr></table>

**Comment by kwankyu** [comment]
Description changed:
``````diff
--- 
+++ 
@@ -1 +1,9 @@
+Sphinx, upgraded to 5.2.3 in #34615, builds the doc with object (classes, functions, ...) definitions in toc (table of contents). In a sense, this makes our doc broken since new entries are added to toc unintentionally.
 
+This tickets reverts the change using a Sphinx configuration variable, also introduced in Sphinx 5.2.3.
+
+Reference:
+
+https://github.com/sphinx-doc/sphinx/pull/10886
+
+ 
``````

**Comment by kwankyu** [comment]
Description changed:
``````diff
--- 
+++ 
@@ -1,3 +1,5 @@
+**See also #34710 for an alternative to this ticket**
+
 Sphinx, upgraded to 5.2.3 in #34615, builds the doc with object (classes, functions, ...) definitions in toc (table of contents). In a sense, this makes our doc broken since new entries are added to toc unintentionally.
 
 This tickets reverts the change using a Sphinx configuration variable, also introduced in Sphinx 5.2.3.
``````

**Comment by kwankyu** [comment]
Description changed:
``````diff
--- 
+++ 
@@ -1,6 +1,6 @@
 **See also #34710 for an alternative to this ticket**
 
-Sphinx, upgraded to 5.2.3 in #34615, builds the doc with object (classes, functions, ...) definitions in toc (table of contents). In a sense, this makes our doc broken since new entries are added to toc unintentionally.
+Sphinx, upgraded to 5.2.3 in #34615, builds the doc with object (classes, functions, ...) entries in toc (table of contents). In a sense, this makes our doc broken since new entries are added to toc unintentionally.
 
 This tickets reverts the change using a Sphinx configuration variable, also introduced in Sphinx 5.2.3.
 
``````

**Comment by kwankyu** [comment]
Description changed:
``````diff
--- 
+++ 
@@ -1,6 +1,8 @@
 **See also #34710 for an alternative to this ticket**
 
-Sphinx, upgraded to 5.2.3 in #34615, builds the doc with object (classes, functions, ...) entries in toc (table of contents). In a sense, this makes our doc broken since new entries are added to toc unintentionally.
+Sphinx, upgraded to 5.2.3 in #34615, builds the doc with object (classes, functions, ...) entries in toc (table of contents). 
+
+In a sense, this makes our doc broken since new entries are added to toc unintentionally. Original discussion: [#34615 comment:22](https://github.com/sagemath/sage/issues/34615#comment:22)
 
 This tickets reverts the change using a Sphinx configuration variable, also introduced in Sphinx 5.2.3.
 
``````

**Comment by kwankyu** [comment]
Description changed:
``````diff
--- 
+++ 
@@ -1,4 +1,4 @@
-**See also #34710 for an alternative to this ticket**
+**We decided to go for #34710 instead of this ticket**
 
 Sphinx, upgraded to 5.2.3 in #34615, builds the doc with object (classes, functions, ...) entries in toc (table of contents). 
 
``````

**Comment by kwankyu** [comment]
Changed author from **Kwankyu Lee** to none

**Comment by kwankyu** [comment]
Changed commit from **[`e14c857`](https://github.com/sagemath/sagetrac-mirror/commit/e14c85760435dc1721bf626d494e92ac9bfbd46b)** to none

**Comment by kwankyu** [comment]
Changed branch from **[u/klee/remove_objects_definitions_from_toc](https://github.com/sagemath/sagetrac-mirror/tree/u/klee/remove_objects_definitions_from_toc)** to none

**Comment by mkoeppe** [comment]
Reviewer: **Matthias Koeppe**
