### ISSUE TITLE
Bug in Clifford algebra multiplication

### ISSUE THREAD

**Issue by tscrim** [sagemath/sage#34707]
<div id="comment:0"></div>

This is a really bad associativity failure:

```
sage: r = ZZ['r'].fraction_field().gen()
sage: Q = QuadraticForm(r.parent(), 2, [0,r,0])
sage: C.<p,q> = CliffordAlgebra(Q)
sage: q * (p * q)
r*q
sage: (q * p) * q
-r*p*q + r^2
```

CC:  @trevorkarn @fchapoton

Component: **algebra**

Keywords: **Clifford**

Author: **Travis Scrimshaw**

Branch/Commit: **[`4d56288`](https://github.com/sagemath/sagetrac-mirror/commit/4d56288de56b4b90b5200c5a10f5536e87ce2c99)**

Reviewer: **Frédéric Chapoton**

_Issue created by migration from https://trac.sagemath.org/ticket/34707_

**Comment by tscrim** [comment]
<div id="comment:1" align="right">comment:1</div>

The first answer is the correct answer.

**Comment by tscrim** [comment]
Author: **Travis Scrimshaw**

**Comment by tscrim** [comment]
<div id="comment:2" align="right">comment:2</div>

Okay, it is a very special case. It was checking that the first element of the LHS when the RHS was single monomial. In this example, the first returned term happened to be the constant term, so it thought it just needed to multiply the LHS by that scalar. So it actually is not so bad of a bug, just a special case.

---
New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/4d56288de56b4b90b5200c5a10f5536e87ce2c99"><code>4d56288</code></a></td><td><code>Checking that the RHS is a scalar of 1, not the LHS.</code></td></tr></table>

**Comment by tscrim** [comment]
Commit: **[`4d56288`](https://github.com/sagemath/sagetrac-mirror/commit/4d56288de56b4b90b5200c5a10f5536e87ce2c99)**

**Comment by tscrim** [comment]
Branch: **[public/algebra/clifford_algebra_mult-34707](https://github.com/sagemath/sagetrac-mirror/tree/public/algebra/clifford_algebra_mult-34707)**

**Comment by fchapoton** [comment]
<div id="comment:3" align="right">comment:3</div>

ok if the bot comes back green

**Comment by fchapoton** [comment]
Reviewer: **Frédéric Chapoton**

**Comment by tscrim** [comment]
<div id="comment:5" align="right">comment:5</div>

Thank you! This has been around for a while and is a somewhat embarrassing bug from me...

**Comment by vbraun** [comment]
Changed branch from **[public/algebra/clifford_algebra_mult-34707](https://github.com/sagemath/sagetrac-mirror/tree/public/algebra/clifford_algebra_mult-34707)** to **[`4d56288`](https://github.com/sagemath/sagetrac-mirror/commit/4d56288de56b4b90b5200c5a10f5536e87ce2c99)**
