### ISSUE TITLE
clean whitespace W293 in py files

### ISSUE THREAD

**Issue by fchapoton** [sagemath/sage#34704]
<div id="comment:0"></div>

but one, changed elsewhere

and in some pyx files too

Component: **refactoring**

Author: **Frédéric Chapoton**

Branch/Commit: **[`ae432e3`](https://github.com/sagemath/sagetrac-mirror/commit/ae432e3ffc5e2464021f4e0d96e6d060d57468ec)**

Reviewer: **Matthias Koeppe**

_Issue created by migration from https://trac.sagemath.org/ticket/34704_

**Comment by fchapoton** [comment]
Branch: **[u/chapoton/34704](https://github.com/sagemath/sagetrac-mirror/tree/u/chapoton/34704)**

**Comment by fchapoton** [comment]
Commit: **[`ae432e3`](https://github.com/sagemath/sagetrac-mirror/commit/ae432e3ffc5e2464021f4e0d96e6d060d57468ec)**

**Comment by fchapoton** [comment]
<div id="comment:1"></div>

New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/ae432e3ffc5e2464021f4e0d96e6d060d57468ec"><code>ae432e3</code></a></td><td><code>clean W293 in py files (but one) and some pyx files</code></td></tr></table>

**Comment by mkoeppe** [comment]
Reviewer: **Matthias Koeppe**

**Comment by vbraun** [comment]
Changed branch from **[u/chapoton/34704](https://github.com/sagemath/sagetrac-mirror/tree/u/chapoton/34704)** to **[`ae432e3`](https://github.com/sagemath/sagetrac-mirror/commit/ae432e3ffc5e2464021f4e0d96e6d060d57468ec)**
