### ISSUE TITLE
remove traces of lgtm

### ISSUE THREAD

**Issue by fchapoton** [sagemath/sage#34703]
<div id="comment:0"></div>

as this website is going to be closed very soon

Component: **refactoring**

Keywords: **lgtm**

Author: **Frédéric Chapoton**

Branch/Commit: **[`52d539b`](https://github.com/sagemath/sagetrac-mirror/commit/52d539b1e0a8b9d13797168a8cf0d1e4fafef8f4)**

Reviewer: **Dave Morris**

_Issue created by migration from https://trac.sagemath.org/ticket/34703_

**Comment by fchapoton** [comment]
Branch: **[u/chapoton/34703](https://github.com/sagemath/sagetrac-mirror/tree/u/chapoton/34703)**

**Comment by fchapoton** [comment]
Commit: **[`88733f9`](https://github.com/sagemath/sagetrac-mirror/commit/88733f9402fa27c280430dc1009610d263b67ed3)**

**Comment by fchapoton** [comment]
<div id="comment:1"></div>

New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/88733f9402fa27c280430dc1009610d263b67ed3"><code>88733f9</code></a></td><td><code>remove traces of lgtm</code></td></tr></table>

**Comment by DaveWitteMorris** [comment]
<div id="comment:2" align="right">comment:2</div>

Please also correct a grammar mistake (that was already there) in one of the lines that you changed:

```
+++ b/src/sage/algebras/lie_algebras/examples.py
@@ -41,7 +41,7 @@ from sage.algebras.lie_algebras.classical_lie_algebra import gl
 from sage.algebras.lie_algebras.classical_lie_algebra import ClassicalMatrixLieAlgebra as ClassicalMatrix
-# the next 6 lines are here to silent pyflakes and lgtm warnings
+# the next 6 lines are here to silent pyflakes warnings

Please change to:
+# the next 6 lines are here to silence pyflakes warnings
```

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
Changed commit from **[`88733f9`](https://github.com/sagemath/sagetrac-mirror/commit/88733f9402fa27c280430dc1009610d263b67ed3)** to **[`52d539b`](https://github.com/sagemath/sagetrac-mirror/commit/52d539b1e0a8b9d13797168a8cf0d1e4fafef8f4)**

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
<div id="comment:3"></div>

Branch pushed to git repo; I updated commit sha1. New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/52d539b1e0a8b9d13797168a8cf0d1e4fafef8f4"><code>52d539b</code></a></td><td><code>fix typo</code></td></tr></table>

**Comment by fchapoton** [comment]
<div id="comment:4" align="right">comment:4</div>

done

**Comment by DaveWitteMorris** [comment]
<div id="comment:5" align="right">comment:5</div>

Thanks. Everything looks fine to me. 

I will try to run `maketestlong`. If that works and there are no comments from anyone else, then I will plan to set to positive review tomorrow.

**Comment by fchapoton** [comment]
<div id="comment:6" align="right">comment:6</div>

you can also just wait for the github actions to finish and then the "tags" will hopefully turn green

**Comment by DaveWitteMorris** [comment]
Changed keywords from none to **lgtm**

**Comment by DaveWitteMorris** [comment]
Reviewer: **Dave Morris**

**Comment by DaveWitteMorris** [comment]
<div id="comment:7" align="right">comment:7</div>

The PR removes the file `.lgtm.yml`, deletes mention of `lgtm` from `src/doc/en/developer/tools.rst`, and fixes some minor spacing issues. None of this should cause problems. This was confirmed by `Build & Test` (which passed), and I ran `make testlong` with no errors.

**Comment by vbraun** [comment]
Changed branch from **[u/chapoton/34703](https://github.com/sagemath/sagetrac-mirror/tree/u/chapoton/34703)** to **[`52d539b`](https://github.com/sagemath/sagetrac-mirror/commit/52d539b1e0a8b9d13797168a8cf0d1e4fafef8f4)**
