### ISSUE TITLE
fix and activate W605 and E306 in pyx files

### ISSUE THREAD

**Issue by fchapoton** [sagemath/sage#34705]
<div id="comment:0"></div>

Component: **refactoring**

Author: **Frédéric Chapoton**

Branch/Commit: **[`fda9085`](https://github.com/sagemath/sagetrac-mirror/commit/fda90859c17b01922d18086b64ad86bbca8f6948)**

Reviewer: **Matthias Koeppe**

_Issue created by migration from https://trac.sagemath.org/ticket/34705_

**Comment by fchapoton** [comment]
Branch: **[u/chapoton/34705](https://github.com/sagemath/sagetrac-mirror/tree/u/chapoton/34705)**

**Comment by fchapoton** [comment]
<div id="comment:1"></div>

New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/fda90859c17b01922d18086b64ad86bbca8f6948"><code>fda9085</code></a></td><td><code>fix and activate E306 and W605 in pyx files</code></td></tr></table>

**Comment by fchapoton** [comment]
Commit: **[`fda9085`](https://github.com/sagemath/sagetrac-mirror/commit/fda90859c17b01922d18086b64ad86bbca8f6948)**

**Comment by mkoeppe** [comment]
Reviewer: **Matthias Koeppe**

**Comment by vbraun** [comment]
Changed branch from **[u/chapoton/34705](https://github.com/sagemath/sagetrac-mirror/tree/u/chapoton/34705)** to **[`fda9085`](https://github.com/sagemath/sagetrac-mirror/commit/fda90859c17b01922d18086b64ad86bbca8f6948)**
