### ISSUE TITLE
Keep object entries in TOC in short form

### ISSUE THREAD

**Issue by kwankyu** [sagemath/sage#34710]
<div id="comment:0"></div>

Sphinx, upgraded to 5.2.3 in #34615, builds the doc with object (classes, functions, ...) entries in toc (table of contents).

We keep the object entries in TOC, but remove them from the main index pages.

CC:  @kiwifb @fchapoton @tscrim @mkoeppe @dimpase

Component: **documentation**

Author: **Kwankyu Lee**

Branch/Commit: **[`a1b70f3`](https://github.com/sagemath/sagetrac-mirror/commit/a1b70f3da76e4e2324b6b1c7cf3765bbc4f7d737)**

Reviewer: **François Bissey**

_Issue created by migration from https://trac.sagemath.org/ticket/34710_

**Comment by kwankyu** [comment]
Branch: **[u/klee/keep_objects_entries_in_toc_in_short_form](https://github.com/sagemath/sagetrac-mirror/tree/u/klee/keep_objects_entries_in_toc_in_short_form)**

**Comment by kwankyu** [comment]
Commit: **[`a4218e3`](https://github.com/sagemath/sagetrac-mirror/commit/a4218e318fc02a95498ef5ecfdcd7d185dbb8459)**

**Comment by kwankyu** [comment]
<div id="comment:2"></div>

New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/a4218e318fc02a95498ef5ecfdcd7d185dbb8459"><code>a4218e3</code></a></td><td><code>Keep objects entries in toc</code></td></tr></table>

**Comment by kwankyu** [comment]
Author: **Kwankyu Lee**

**Comment by kwankyu** [comment]
Description changed:
``````diff
--- 
+++ 
@@ -1 +1 @@
-
+**See also #34706 for an alternative to this ticket**
``````

**Comment by kwankyu** [comment]
Description changed:
``````diff
--- 
+++ 
@@ -1 +1,5 @@
 **See also #34706 for an alternative to this ticket**
+
+Sphinx, upgraded to 5.2.3 in #34615, builds the doc with object (classes, functions, ...) definitions in toc (table of contents).
+
+We keep the objects entries in TOC, but remove them from the main index pages.
``````

**Comment by kwankyu** [comment]
Description changed:
``````diff
--- 
+++ 
@@ -1,5 +1,5 @@
 **See also #34706 for an alternative to this ticket**
 
-Sphinx, upgraded to 5.2.3 in #34615, builds the doc with object (classes, functions, ...) definitions in toc (table of contents).
+Sphinx, upgraded to 5.2.3 in #34615, builds the doc with object (classes, functions, ...) entries in toc (table of contents).
 
-We keep the objects entries in TOC, but remove them from the main index pages.
+We keep the object entries in TOC, but remove them from the main index pages.
``````

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
<div id="comment:7"></div>

Branch pushed to git repo; I updated commit sha1. This was a forced push. New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/a1b70f3da76e4e2324b6b1c7cf3765bbc4f7d737"><code>a1b70f3</code></a></td><td><code>Keep objects entries in toc</code></td></tr></table>

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
Changed commit from **[`a4218e3`](https://github.com/sagemath/sagetrac-mirror/commit/a4218e318fc02a95498ef5ecfdcd7d185dbb8459)** to **[`a1b70f3`](https://github.com/sagemath/sagetrac-mirror/commit/a1b70f3da76e4e2324b6b1c7cf3765bbc4f7d737)**

**Comment by kwankyu** [comment]
<div id="comment:8" align="right">comment:8</div>

The recent upgrade of Sphinx to version 5.2.3 introduced unexpected changes in our documentation by the new "object entries in toc" feature of the new Sphinx.

See the main index page in the middle:

https://8f8af65e54d3a9962cfab40f15dc23f4e955b43f--sagemath-tobias.netlify.app/reference/curves/index.html

See the "CONTENTS" column on the right:

https://8f8af65e54d3a9962cfab40f15dc23f4e955b43f--sagemath-tobias.netlify.app/reference/curves/sage/schemes/riemann_surfaces/riemann_surface.html

To "fix" the unexpected changes, I prepared two tickets #34706 and #34710 (this ticket)

#34706 reverts the changes and makes the doc look as it did before the Sphinx upgrade.

#34710 keeps the object entries in toc, but remove them from the main index pages.

Now we need to make a choice:

(1) Accept the default of the new Sphinx (discard both of #34706 and #34710)

(2) Remove object entries from the doc (take #34706 and discard #34710)

https://e14c85760435dc1721bf626d494e92ac9bfbd46b--sagemath-tobias.netlify.app/reference/curves/index.html

https://e14c85760435dc1721bf626d494e92ac9bfbd46b--sagemath-tobias.netlify.app/reference/curves/sage/schemes/riemann_surfaces/riemann_surface.html


(3) Keep object entries but remove them from main index pages (take #34710 and discard #34706)

https://a1b70f3da76e4e2324b6b1c7cf3765bbc4f7d737--sagemath-tobias.netlify.app/reference/curves/index.html

https://a1b70f3da76e4e2324b6b1c7cf3765bbc4f7d737--sagemath-tobias.netlify.app/reference/curves/sage/schemes/riemann_surfaces/riemann_surface.html

(4) Still other possibility. Then please open a new ticket for your favorite style.

I advocate (3), but others may have different favors. So I invite a few for opinions. If all agree with me, we will go for (3). Otherwise, I will open a vote (again...) in sage-devel.

**Comment by mkoeppe** [comment]
<div id="comment:10" align="right">comment:10</div>

(3) is fine with me

**Comment by kiwifb** [comment]
<div id="comment:11" align="right">comment:11</div>

I also think 3 is good.

**Comment by jhpalmieri** [comment]
<div id="comment:12" align="right">comment:12</div>

I agree.

**Comment by kwankyu** [comment]
Description changed:
``````diff
--- 
+++ 
@@ -1,5 +1,3 @@
-**See also #34706 for an alternative to this ticket**
-
 Sphinx, upgraded to 5.2.3 in #34615, builds the doc with object (classes, functions, ...) entries in toc (table of contents).
 
 We keep the object entries in TOC, but remove them from the main index pages.
``````

**Comment by kwankyu** [comment]
<div id="comment:13" align="right">comment:13</div>

Thank you for expressing your opinions!

I will discard #34706. 

Please review this ticket.

**Comment by tscrim** [comment]
<div id="comment:14" align="right">comment:14</div>

Sounds like we can finally kill (with fire and holy water please) the manually edited TOC at the start of the files.

**Comment by kwankyu** [comment]
<div id="comment:15" align="right">comment:15</div>

For instance?

**Comment by tscrim** [comment]
<div id="comment:16" align="right">comment:16</div>

Permutations: https://doc.sagemath.org/html/en/reference/combinat/sage/combinat/permutation.html

Graphs: https://doc.sagemath.org/html/en/reference/graphs/sage/graphs/generic_graph.html

Digraphs: https://doc.sagemath.org/html/en/reference/graphs/sage/graphs/digraph.html

**Comment by kwankyu** [comment]
<div id="comment:17" align="right">comment:17</div>

True!

> Permutations: https://doc.sagemath.org/html/en/reference/combinat/sage/combinat/permutation.html

https://a1b70f3da76e4e2324b6b1c7cf3765bbc4f7d737--sagemath-tobias.netlify.app/reference/combinat/sage/combinat/permutation.html#module-sage.combinat.permutation

> 
> Graphs: https://doc.sagemath.org/html/en/reference/graphs/sage/graphs/generic_graph.html

https://a1b70f3da76e4e2324b6b1c7cf3765bbc4f7d737--sagemath-tobias.netlify.app/reference/graphs/sage/graphs/generic_graph.html

> Digraphs: https://doc.sagemath.org/html/en/reference/graphs/sage/graphs/digraph.html

https://a1b70f3da76e4e2324b6b1c7cf3765bbc4f7d737--sagemath-tobias.netlify.app/reference/graphs/sage/graphs/digraph.html

**Comment by kiwifb** [comment]
Reviewer: **François Bissey**

**Comment by kiwifb** [comment]
<div id="comment:18" align="right">comment:18</div>

Let's get things moving here.

**Comment by jhpalmieri** [comment]
<div id="comment:19" align="right">comment:19</div>

I saw something strange in a build this morning. It might be a glitch on my end, but I want to build the documentation one more time to make sure. If all goes well, I'll reset to positive.

**Comment by jhpalmieri** [comment]
<div id="comment:20" align="right">comment:20</div>

For reasons I do not understand, it took over 3 hours to build the PDF documentation. It was much faster on another machine, and I don't see anything in the changes here that would cause that sort of thing. So back to a positive review.

**Comment by kwankyu** [comment]
<div id="comment:21" align="right">comment:21</div>

Thank you both!

**Comment by vbraun** [comment]
Changed branch from **[u/klee/keep_objects_entries_in_toc_in_short_form](https://github.com/sagemath/sagetrac-mirror/tree/u/klee/keep_objects_entries_in_toc_in_short_form)** to **[`a1b70f3`](https://github.com/sagemath/sagetrac-mirror/commit/a1b70f3da76e4e2324b6b1c7cf3765bbc4f7d737)**
