### ISSUE TITLE
fast path for factoring monomials over number fields

### ISSUE THREAD

**Issue by mezzarobba** [sagemath/sage#34714]
<div id="comment:0"></div>

Trivial instances of univariate polynomial factorization over complicated number fields are extremely slow because Sage starts by trying to compute an integral basis.

We introduce a fast path that handles monomials — most importantly, the identity polynomial.

Ideally, we should do something similar over arbitrary rings, but this is currently difficult to implement in a generic because the `factor()` method of constants is under-specified. In particular, calling `factor()` on a rational number factors the numerator and denominator, which we certainly do not want when factoring the leading coefficient of an element of ℚ[x].

In the number field case, a possible generalization would be to detect constant multiples of polynomials that factor over ℚ. Not sure if this is a good idea.

Component: **number fields**

Author: **Marc Mezzarobba**

Branch/Commit: **[`4fc91e1`](https://github.com/sagemath/sagetrac-mirror/commit/4fc91e11292ce137885d4fc84135cd351d52a6fb)**

Reviewer: **Vincent Delecroix**

_Issue created by migration from https://trac.sagemath.org/ticket/34714_

**Comment by mezzarobba** [comment]
Author: **Marc Mezzarobba**

**Comment by mezzarobba** [comment]
Commit: **[`4fc91e1`](https://github.com/sagemath/sagetrac-mirror/commit/4fc91e11292ce137885d4fc84135cd351d52a6fb)**

**Comment by mezzarobba** [comment]
Branch: **[u/mmezzarobba/34714-trivialnffactor](https://github.com/sagemath/sagetrac-mirror/tree/u/mmezzarobba/34714-trivialnffactor)**

**Comment by mezzarobba** [comment]
<div id="comment:1"></div>

New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/4fc91e11292ce137885d4fc84135cd351d52a6fb"><code>4fc91e1</code></a></td><td><code>#34714 fast path for factoring monomials over number fields</code></td></tr></table>

**Comment by videlec** [comment]
Reviewer: **Vincent Delecroix**

**Comment by mezzarobba** [comment]
<div id="comment:3" align="right">comment:3</div>

Thanks!

**Comment by vbraun** [comment]
Changed branch from **[u/mmezzarobba/34714-trivialnffactor](https://github.com/sagemath/sagetrac-mirror/tree/u/mmezzarobba/34714-trivialnffactor)** to **[`4fc91e1`](https://github.com/sagemath/sagetrac-mirror/commit/4fc91e11292ce137885d4fc84135cd351d52a6fb)**
