### ISSUE TITLE
partial pep8 cleanup for number_field.py

### ISSUE THREAD

**Issue by fchapoton** [sagemath/sage#34712]
<div id="comment:0"></div>

also a few little code tweaks

CC:  @tscrim @kwankyu @kliem @slel

Component: **number fields**

Author: **Frédéric Chapoton**

Branch/Commit: **[`b694ec2`](https://github.com/sagemath/sagetrac-mirror/commit/b694ec2e30b611701f18b553e74c1dc6fef420ed)**

Reviewer: **Matthias Koeppe**

_Issue created by migration from https://trac.sagemath.org/ticket/34712_

**Comment by fchapoton** [comment]
Branch: **[u/chapoton/34712](https://github.com/sagemath/sagetrac-mirror/tree/u/chapoton/34712)**

**Comment by fchapoton** [comment]
Commit: **[`810fc34`](https://github.com/sagemath/sagetrac-mirror/commit/810fc34a9a6f7097a996e12a1258bbdf6dc68161)**

**Comment by fchapoton** [comment]
<div id="comment:1"></div>

New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/810fc34a9a6f7097a996e12a1258bbdf6dc68161"><code>810fc34</code></a></td><td><code>partial pep8 cleanup for number_field.py</code></td></tr></table>

**Comment by mkoeppe** [comment]
<div id="comment:2" align="right">comment:2</div>

tests fail with `RecursionError`

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
<div id="comment:3"></div>

Branch pushed to git repo; I updated commit sha1. New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/de39745601c2e627f5c844310a7099fa055347de"><code>de39745</code></a></td><td><code>fix wrong change</code></td></tr></table>

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
Changed commit from **[`810fc34`](https://github.com/sagemath/sagetrac-mirror/commit/810fc34a9a6f7097a996e12a1258bbdf6dc68161)** to **[`de39745`](https://github.com/sagemath/sagetrac-mirror/commit/de39745601c2e627f5c844310a7099fa055347de)**

**Comment by fchapoton** [comment]
<div id="comment:4" align="right">comment:4</div>

Fixed, was `__n` and not `_n`

**Comment by mkoeppe** [comment]
<div id="comment:5" align="right">comment:5</div>

I'd think it's better to just remove the commented-out version of `_will_be_better_coerce_from_other_cyclotomic_field`. It's from 2007 and it's unlikely that someone will just pick it up from this commented out code after > 15 years.

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
<div id="comment:6"></div>

Branch pushed to git repo; I updated commit sha1. New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/b694ec2e30b611701f18b553e74c1dc6fef420ed"><code>b694ec2</code></a></td><td><code>remove old commented code, fix more pep8</code></td></tr></table>

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
Changed commit from **[`de39745`](https://github.com/sagemath/sagetrac-mirror/commit/de39745601c2e627f5c844310a7099fa055347de)** to **[`b694ec2`](https://github.com/sagemath/sagetrac-mirror/commit/b694ec2e30b611701f18b553e74c1dc6fef420ed)**

**Comment by fchapoton** [comment]
<div id="comment:7" align="right">comment:7</div>

green bot, so please review

**Comment by mkoeppe** [comment]
Reviewer: **Matthias Koeppe**

**Comment by vbraun** [comment]
Changed branch from **[u/chapoton/34712](https://github.com/sagemath/sagetrac-mirror/tree/u/chapoton/34712)** to **[`b694ec2`](https://github.com/sagemath/sagetrac-mirror/commit/b694ec2e30b611701f18b553e74c1dc6fef420ed)**
