### ISSUE TITLE
move carmichael_lambda() from sage.crypto.util to sage.arith.misc

### ISSUE THREAD

**Issue by yyyyx4** [sagemath/sage#34719]
<div id="comment:0"></div>

The Carmichael λ function currently resides in the `sage.crypto.util` module, but it's really much more general than "just" crypto: λ(n) is the exponent of the unit group of ℤ/n. (The morally comparable Euler φ function does live in `sage.arith.misc` already.)

This patch lifts `carmichael_lambda()` out of obscurity, plus some tiny tweaks.

Component: **algebra**

Author: **Lorenz Panny**

Branch/Commit: **[`7e9aefc`](https://github.com/sagemath/sagetrac-mirror/commit/7e9aefca872ab761410a5283c2a1c0701aadff4a)**

Reviewer: **Matthias Koeppe**

_Issue created by migration from https://trac.sagemath.org/ticket/34719_

**Comment by yyyyx4** [comment]
Commit: **[`37ec154`](https://github.com/sagemath/sagetrac-mirror/commit/37ec15490ada135df0d2e4377f7092603435f3d4)**

**Comment by yyyyx4** [comment]
Branch: **[public/move_carmichael_lambda_from_crypto_to_arith_misc](https://github.com/sagemath/sagetrac-mirror/tree/public/move_carmichael_lambda_from_crypto_to_arith_misc)**

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
<div id="comment:2"></div>

Branch pushed to git repo; I updated commit sha1. New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/7e9aefca872ab761410a5283c2a1c0701aadff4a"><code>7e9aefc</code></a></td><td><code>fix doctest failures</code></td></tr></table>

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
Changed commit from **[`37ec154`](https://github.com/sagemath/sagetrac-mirror/commit/37ec15490ada135df0d2e4377f7092603435f3d4)** to **[`7e9aefc`](https://github.com/sagemath/sagetrac-mirror/commit/7e9aefca872ab761410a5283c2a1c0701aadff4a)**

**Comment by yyyyx4** [comment]
Description changed:
``````diff
--- 
+++ 
@@ -1,3 +1,3 @@
-The Carmichael λ function currently resides in the `sage.crypto` module, but it's really much more general than "just" crypto: λ(n) is the exponent of the unit group of ℤ/n. (The morally comparable Euler φ function does live in `sage.arith.misc` already.)
+The Carmichael λ function currently resides in the `sage.crypto.util` module, but it's really much more general than "just" crypto: λ(n) is the exponent of the unit group of ℤ/n. (The morally comparable Euler φ function does live in `sage.arith.misc` already.)
 
 This patch lifts `carmichael_lambda()` out of obscurity, plus some tiny tweaks.
``````

**Comment by mkoeppe** [comment]
Reviewer: **Matthias Koeppe**

**Comment by mkoeppe** [comment]
<div id="comment:4" align="right">comment:4</div>

Good idea, LGTM.

**Comment by vbraun** [comment]
Changed branch from **[public/move_carmichael_lambda_from_crypto_to_arith_misc](https://github.com/sagemath/sagetrac-mirror/tree/public/move_carmichael_lambda_from_crypto_to_arith_misc)** to **[`7e9aefc`](https://github.com/sagemath/sagetrac-mirror/commit/7e9aefca872ab761410a5283c2a1c0701aadff4a)**
