### ISSUE TITLE
tox.ini: Add gentoo-python3.11

### ISSUE THREAD

**Issue by sheerluck** [sagemath/sage#34715]
<div id="comment:0"></div>

Similar to #32838 but this time thanks to `docker.yml` we need two one-liners only

Branch for this ticket can be formed from ​[single commit in fork](https://github.com/sheerluck/sage/commit/e2d38e282ff701f3c79970eca7c54b5613d49526).

To test this ticket one needs #33842 and also to **bump LT_VERSION to 3.12.0**

```diff
--- a/build/pkgs/python3/spkg-configure.m4
+++ b/build/pkgs/python3/spkg-configure.m4
@@ -1,8 +1,8 @@
 SAGE_SPKG_CONFIGURE([python3], [
    m4_pushdef([MIN_VERSION],               [3.8.0])
    m4_pushdef([MIN_NONDEPRECATED_VERSION], [3.8.0])
-   m4_pushdef([LT_STABLE_VERSION],         [3.11.0])
-   m4_pushdef([LT_VERSION],                [3.11.0])
+   m4_pushdef([LT_STABLE_VERSION],         [3.12.0])
+   m4_pushdef([LT_VERSION],                [3.12.0])
    AC_ARG_WITH([python],
                [AS_HELP_STRING([--with-python=PYTHON3],
                                [Python 3 executable to use for the Sage venv; default: python3])])
```
and it seems like sagemath is not ready for that yet :(

Depends on #33842

Component: **porting**

_Issue created by migration from https://trac.sagemath.org/ticket/34715_

**Comment by sheerluck** [comment]
<div id="comment:1" align="right">comment:1</div>

✅ https://github.com/sheerluck/sage/actions/runs/3377922796/jobs/5607461032

**Comment by mkoeppe** [comment]
<div id="comment:2" align="right">comment:2</div>

I've cherry-picked this commit onto #33842

**Comment by mkoeppe** [comment]
Changed author from **Andrey Belgorodski** to none

**Comment by mkoeppe** [comment]
Dependencies: **#33842**
