### ISSUE TITLE
Update IPython to 8.6

### ISSUE THREAD

**Issue by mkoeppe** [sagemath/sage#34713]
<div id="comment:0"></div>

... and other updates related to IPython and Jupyter.

New standard package: `hatch_nodejs_version` (new build dep of `nbformat`)

Changed to a wheel package: `nbconvert` (because version 7.x tries to download some CSS at build time - see discussion in https://github.com/jupyter/nbconvert/pull/1827)

CC:  @egourgoulhon @kwankyu

Component: **packages: standard**

Author: **Matthias Koeppe**

Branch/Commit: **[`d91e7c0`](https://github.com/sagemath/sagetrac-mirror/commit/d91e7c085bd64c0933b517de96106b65fa5c12a7)**

Reviewer: **Kwankyu Lee**

_Issue created by migration from https://trac.sagemath.org/ticket/34713_

**Comment by mkoeppe** [comment]
Branch: **[u/mkoeppe/update_ipython_to_8_6](https://github.com/sagemath/sagetrac-mirror/tree/u/mkoeppe/update_ipython_to_8_6)**

**Comment by mkoeppe** [comment]
Description changed:
``````diff
--- 
+++ 
@@ -1 +1,6 @@
+... and other updates related to IPython and Jupyter.
 
+New standard package: `hatch_nodejs_version` (new build dep of `nbformat`)
+
+Changed to a wheel package: `nbconvert` (because version 7.x tries to download some CSS at build time - see discussion in https://github.com/jupyter/nbconvert/pull/1827)
+
``````

**Comment by mkoeppe** [comment]
Commit: **[`5da03da`](https://github.com/sagemath/sagetrac-mirror/commit/5da03da6517633e1e07715c50b1339ca45b09f5a)**

**Comment by mkoeppe** [comment]
<div id="comment:2"></div>

New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/aa2c315ba7ca755992c0e6b1278e560a70e75408"><code>aa2c315</code></a></td><td><code>build/pkgs/ipython: Update to 8.6.0</code></td></tr><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/eb2173ce26a4a9d45699cbee92e995bd1bca2d27"><code>eb2173c</code></a></td><td><code>build/pkgs/traitlets: Update to 5.5.0</code></td></tr><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/c517afb637b3f9f60d8403886c82d712f6fd9026"><code>c517afb</code></a></td><td><code>build/pkgs/pygments: Update to 2.13.0</code></td></tr><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/07a9a33642e1e93c23acd5491f16a520767b159e"><code>07a9a33</code></a></td><td><code>build/pkgs/nbformat: Update to 5.7.0</code></td></tr><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/5da03da6517633e1e07715c50b1339ca45b09f5a"><code>5da03da</code></a></td><td><code>build/pkgs/hatch_nodejs_version: New (nbformat build dep)</code></td></tr></table>

**Comment by mkoeppe** [comment]
Author: **Matthias Koeppe**

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
<div id="comment:3"></div>

Branch pushed to git repo; I updated commit sha1. New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/bfe5a2619cfb3f8bc2a93880f35f3ac446c7e008"><code>bfe5a26</code></a></td><td><code>build/pkgs/nbclient: Update to 0.7.0</code></td></tr><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/5f2315fa0bb94cb19f0c53268f6676b29ee6e602"><code>5f2315f</code></a></td><td><code>build/pkgs/tornado: Update to 6.2</code></td></tr><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/31014d934889b91e1d7ec64efdf579ab2e347227"><code>31014d9</code></a></td><td><code>build/pkgs/terminado: Update to 0.17.0</code></td></tr><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/8c1f91d8ac5ea3294abded103f6ece927c3526ba"><code>8c1f91d</code></a></td><td><code>build/pkgs/jupyter_client: Update to 7.4.4</code></td></tr><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/1721d58ac35e654f2acd6df72c3cb557b98245d4"><code>1721d58</code></a></td><td><code>build/pkgs/jupyter_core: Update to 4.11.2</code></td></tr><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/9d723b509ff96e20a815feed535b98dc10575308"><code>9d723b5</code></a></td><td><code>build/pkgs/nbconvert: Update to 6.5.3</code></td></tr><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/5b0d5f9c46036f052d9cb76524781ab9f7b04c3f"><code>5b0d5f9</code></a></td><td><code>build/pkgs/nbconvert: Update to 7.2.3, change to wheel package</code></td></tr><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/d91e7c085bd64c0933b517de96106b65fa5c12a7"><code>d91e7c0</code></a></td><td><code>build/pkgs/mistune: Update to 2.0.4</code></td></tr></table>

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
Changed commit from **[`5da03da`](https://github.com/sagemath/sagetrac-mirror/commit/5da03da6517633e1e07715c50b1339ca45b09f5a)** to **[`d91e7c0`](https://github.com/sagemath/sagetrac-mirror/commit/d91e7c085bd64c0933b517de96106b65fa5c12a7)**

**Comment by kwankyu** [comment]
<div id="comment:5" align="right">comment:5</div>

Thank you. LGTM.

**Comment by kwankyu** [comment]
Reviewer: **Kwankyu Lee**

**Comment by mkoeppe** [comment]
<div id="comment:6" align="right">comment:6</div>

Thanks!

**Comment by vbraun** [comment]
Changed branch from **[u/mkoeppe/update_ipython_to_8_6](https://github.com/sagemath/sagetrac-mirror/tree/u/mkoeppe/update_ipython_to_8_6)** to **[`d91e7c0`](https://github.com/sagemath/sagetrac-mirror/commit/d91e7c085bd64c0933b517de96106b65fa5c12a7)**
