### ISSUE TITLE
Check the presence of lrsnash for obtain_nash()

### ISSUE THREAD

**Issue by kwankyu** [sagemath/sage#34717]
<div id="comment:0"></div>

To fix failures like

```
File "src/sage/game_theory/catalog_normal_form_games.py", line 916, in sage.game_theory.catalog_normal_form_games.TravellersDilemma
Failed example:
    g.obtain_nash()
Exception raised:
    Traceback (most recent call last):
      File "/Users/kwankyu/GitHub/sage-dev/src/sage/doctest/forker.py", line 695, in _run
        self.compile_and_execute(example, compiler, test.globs)
      File "/Users/kwankyu/GitHub/sage-dev/src/sage/doctest/forker.py", line 1093, in compile_and_execute
        exec(compiled, globs)
      File "<doctest sage.game_theory.catalog_normal_form_games.TravellersDilemma[8]>", line 1, in <module>
        g.obtain_nash()
      File "/Users/kwankyu/GitHub/sage-dev/src/sage/game_theory/normal_form_game.py", line 1688, in obtain_nash
        return self._solve_lrs(maximization)
      File "/Users/kwankyu/GitHub/sage-dev/src/sage/game_theory/normal_form_game.py", line 1758, in _solve_lrs
        LrsNash().require()
      File "/Users/kwankyu/GitHub/sage-dev/src/sage/features/__init__.py", line 209, in require
        raise FeatureNotPresentError(self, presence.reason, presence.resolution)
    sage.features.FeatureNotPresentError: lrsnash is not available.
    Executable 'lrsnash' not found on PATH.
    No equivalent system packages for homebrew are known to Sage.
    To install lrsnash using the Sage package manager, you can try to run:
      !sage -i lrslib
    No equivalent system packages for pip are known to Sage.
    Further installation instructions might be available at http://cgm.cs.mcgill.ca/~avis/C/lrs.html.
```
I have been seeing these failures for a long time on my system (mac os).  

Component: **game theory**

Author: **Matthias Koeppe**

Branch/Commit: **[`4a11843`](https://github.com/sagemath/sagetrac-mirror/commit/4a118435b3a099874a1683100a1e7ee3b12d75b1)**

Reviewer: **Kwankyu Lee**

_Issue created by migration from https://trac.sagemath.org/ticket/34717_

**Comment by kwankyu** [comment]
Branch: **[u/klee/make_some_doctests_optional_for_lrsnash](https://github.com/sagemath/sagetrac-mirror/tree/u/klee/make_some_doctests_optional_for_lrsnash)**

**Comment by kwankyu** [comment]
Description changed:
``````diff
--- 
+++ 
@@ -1 +1,19 @@
+To fix failures like
 
+```
+File "src/sage/game_theory/catalog_normal_form_games.py", line 916, in sage.game_theory.catalog_normal_form_games.TravellersDilemma
+Failed example:
+    g.obtain_nash()
+Exception raised:
+    ...
+      File "/Users/kwankyu/GitHub/sage-temp/src/sage/features/__init__.py", line 209, in require
+        raise FeatureNotPresentError(self, presence.reason, presence.resolution)
+    sage.features.FeatureNotPresentError: lrsnash is not available.
+    Executable 'lrsnash' not found on PATH.
+    No equivalent system packages for homebrew are known to Sage.
+    To install lrsnash using the Sage package manager, you can try to run:
+      !sage -i lrslib
+    No equivalent system packages for pip are known to Sage.
+    Further installation instructions might be available at http://cgm.cs.mcgill.ca/~avis/C/lrs.html.
+```
+I have been seeing these failures for a long time on my system (mac os).  
``````

**Comment by kwankyu** [comment]
<div id="comment:2"></div>

New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/a4ed6037081e4e3fafb37dd9e842151dff1eeb17"><code>a4ed603</code></a></td><td><code>Add # optional - lrsnash to some doctests</code></td></tr></table>

**Comment by kwankyu** [comment]
Commit: **[`a4ed603`](https://github.com/sagemath/sagetrac-mirror/commit/a4ed6037081e4e3fafb37dd9e842151dff1eeb17)**

**Comment by kwankyu** [comment]
<div id="comment:3" align="right">comment:3</div>

Others don't have these failures? I saw no one report them.

**Comment by kwankyu** [comment]
Author: **Kwankyu Lee**

**Comment by mkoeppe** [comment]
<div id="comment:4" align="right">comment:4</div>

I don't think this is the right fix. `obtain_nash` decides on the default algorithm to use based on a feature test; but it checks for `Lrs` when it should check for `Lrslib` or `LrsNash`. It seems that on your system, you have the `lrs` executable but not `lrsnash`.

**Comment by kwankyu** [comment]
Description changed:
``````diff
--- 
+++ 
@@ -5,8 +5,18 @@
 Failed example:
     g.obtain_nash()
 Exception raised:
-    ...
-      File "/Users/kwankyu/GitHub/sage-temp/src/sage/features/__init__.py", line 209, in require
+    Traceback (most recent call last):
+      File "/Users/kwankyu/GitHub/sage-dev/src/sage/doctest/forker.py", line 695, in _run
+        self.compile_and_execute(example, compiler, test.globs)
+      File "/Users/kwankyu/GitHub/sage-dev/src/sage/doctest/forker.py", line 1093, in compile_and_execute
+        exec(compiled, globs)
+      File "<doctest sage.game_theory.catalog_normal_form_games.TravellersDilemma[8]>", line 1, in <module>
+        g.obtain_nash()
+      File "/Users/kwankyu/GitHub/sage-dev/src/sage/game_theory/normal_form_game.py", line 1688, in obtain_nash
+        return self._solve_lrs(maximization)
+      File "/Users/kwankyu/GitHub/sage-dev/src/sage/game_theory/normal_form_game.py", line 1758, in _solve_lrs
+        LrsNash().require()
+      File "/Users/kwankyu/GitHub/sage-dev/src/sage/features/__init__.py", line 209, in require
         raise FeatureNotPresentError(self, presence.reason, presence.resolution)
     sage.features.FeatureNotPresentError: lrsnash is not available.
     Executable 'lrsnash' not found on PATH.
``````

**Comment by kwankyu** [comment]
<div id="comment:7" align="right">comment:7</div>

> It seems that on your system, you have the `lrs` executable but not `lrsnash`. 

Right.

> I don't think this is the right fix. `obtain_nash` decides on the default algorithm to use based on a feature test; but it checks for `Lrs` when it should check for `Lrslib` or `LrsNash`. 

According to the exception message, it checks for `lrsnash` and says `lrsnash` is not available, which is correct, and suggests to me to install `lrslib`, which is an optional package. As `obtain_nash` is dependent on `lrsnash`, it should not be tested when the optional package was not installed. Right?

What is the right fix?

**Comment by mkoeppe** [comment]
Changed branch from **[u/klee/make_some_doctests_optional_for_lrsnash](https://github.com/sagemath/sagetrac-mirror/tree/u/klee/make_some_doctests_optional_for_lrsnash)** to **[u/mkoeppe/make_some_doctests_optional_for_lrsnash](https://github.com/sagemath/sagetrac-mirror/tree/u/mkoeppe/make_some_doctests_optional_for_lrsnash)**

**Comment by mkoeppe** [comment]
<div id="comment:9" align="right">comment:9</div>

Try this

---
New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/4a118435b3a099874a1683100a1e7ee3b12d75b1"><code>4a11843</code></a></td><td><code>src/sage/game_theory/normal_form_game.py: Use LrsNash feature test</code></td></tr></table>

**Comment by mkoeppe** [comment]
Changed commit from **[`a4ed603`](https://github.com/sagemath/sagetrac-mirror/commit/a4ed6037081e4e3fafb37dd9e842151dff1eeb17)** to **[`4a11843`](https://github.com/sagemath/sagetrac-mirror/commit/4a118435b3a099874a1683100a1e7ee3b12d75b1)**

**Comment by kwankyu** [comment]
Changed author from **Kwankyu Lee** to **Matthias Koeppe**

**Comment by kwankyu** [comment]
Reviewer: **Kwankyu Lee**

**Comment by kwankyu** [comment]
<div id="comment:10" align="right">comment:10</div>

it works great. Thanks!

**Comment by vbraun** [comment]
Changed branch from **[u/mkoeppe/make_some_doctests_optional_for_lrsnash](https://github.com/sagemath/sagetrac-mirror/tree/u/mkoeppe/make_some_doctests_optional_for_lrsnash)** to **[`4a11843`](https://github.com/sagemath/sagetrac-mirror/commit/4a118435b3a099874a1683100a1e7ee3b12d75b1)**
