### ISSUE TITLE
fix assertion failure in _discrete_log_pgroup() when group is trivial

### ISSUE THREAD

**Issue by yyyyx4** [sagemath/sage#34716]
<div id="comment:0"></div>

As of Sage 9.7, this causes an assertion failure:

```sage
sage: E = EllipticCurve(GF(487^2), [311,205])
sage: G = E.abelian_group().torsion_subgroup(42)
sage: P, Q = G.torsion_subgroup(6).gens()
sage: G.discrete_log(2*P + 3*Q, [P, Q])
```

The reason is that the `p`-power part of the group generated by `P` and `Q` is trivial for some prime(s) `p` dividing the group order of `G`, which throws off `_discrete_log_pgroup()`. Easy fix.

Component: **group theory**

Author: **Lorenz Panny**

Branch/Commit: **[`93dc05c`](https://github.com/sagemath/sagetrac-mirror/commit/93dc05ccd9a6bf3358e57902cf84da87b0d91339)**

Reviewer: **Kwankyu Lee**

_Issue created by migration from https://trac.sagemath.org/ticket/34716_

**Comment by yyyyx4** [comment]
Description changed:
``````diff
--- 
+++ 
@@ -7,4 +7,4 @@
 sage: G.discrete_log(2*P + 3*Q, [P, Q])
 ```
 
-The reason is that the `p`-power part of the group generated by `P` and `Q` is trivial for some prime(s) `p` dividing the group order, which throws off `._discrete_log_pgroup()`. Easy fix.
+The reason is that the `p`-power part of the group generated by `P` and `Q` is trivial for some prime(s) `p` dividing the group order, which throws off `_discrete_log_pgroup()`. Easy fix.
``````

**Comment by kwankyu** [comment]
Description changed:
``````diff
--- 
+++ 
@@ -7,4 +7,4 @@
 sage: G.discrete_log(2*P + 3*Q, [P, Q])
 ```
 
-The reason is that the `p`-power part of the group generated by `P` and `Q` is trivial for some prime(s) `p` dividing the group order, which throws off `_discrete_log_pgroup()`. Easy fix.
+The reason is that the `p`-power part of the group generated by `P` and `Q` is trivial for some prime(s) `p` dividing the group order of `G`, which throws off `_discrete_log_pgroup()`. Easy fix.
``````

**Comment by kwankyu** [comment]
<div id="comment:3" align="right">comment:3</div>

Wouldn't it be slightly more efficient to put the check in `discrete_log` so that trivial CRT data is discarded?

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
Changed commit from **[`ce4c48c`](https://github.com/sagemath/sagetrac-mirror/commit/ce4c48ca56e6fd502049e06191e79f09a17588e1)** to **[`bd5687c`](https://github.com/sagemath/sagetrac-mirror/commit/bd5687cc890ffa10f1de71f4cdd79568ad7afa18)**

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
<div id="comment:4"></div>

Branch pushed to git repo; I updated commit sha1. This was a forced push. New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/bd5687cc890ffa10f1de71f4cdd79568ad7afa18"><code>bd5687c</code></a></td><td><code>prevent assertion failure in _discrete_log_pgroup when group is trivial</code></td></tr></table>

**Comment by yyyyx4** [comment]
<div id="comment:5" align="right">comment:5</div>

Thanks, added the check to the loop in `.discrete_log()`. I didn't remove the check in `_discrete_log_pgroup()` because the trivial group is a p‑group after all, so the function should behave correctly.

**Comment by kwankyu** [comment]
<div id="comment:6" align="right">comment:6</div>

Replying to [Lorenz Panny](#comment%3A5):
> I didn't remove the check in `_discrete_log_pgroup()` because the trivial group is a p‑group after all, so the function should behave correctly.

As it is a non-public function (whose name starts with an underline) only for internal use, you may restrict the use of the function only for non-trivial p-groups, perhaps just with a comment about the restriction on the input. Thus you may avoid the duplicate check.

But if you still want to keep it for the reason you mentioned, just let me know.

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
Changed commit from **[`bd5687c`](https://github.com/sagemath/sagetrac-mirror/commit/bd5687cc890ffa10f1de71f4cdd79568ad7afa18)** to **[`93dc05c`](https://github.com/sagemath/sagetrac-mirror/commit/93dc05ccd9a6bf3358e57902cf84da87b0d91339)**

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
<div id="comment:7"></div>

Branch pushed to git repo; I updated commit sha1. This was a forced push. New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/93dc05ccd9a6bf3358e57902cf84da87b0d91339"><code>93dc05c</code></a></td><td><code>prevent assertion failure in _discrete_log_pgroup when group is trivial</code></td></tr></table>

**Comment by yyyyx4** [comment]
<div id="comment:8" align="right">comment:8</div>

I don't mind. Done.

**Comment by kwankyu** [comment]
Reviewer: **Kwankyu Lee**

**Comment by kwankyu** [comment]
<div id="comment:9" align="right">comment:9</div>

Thanks. LGTM.

**Comment by vbraun** [comment]
Changed branch from **[public/prevent_assertion_failure_in_AdditiveAbelianGroupWrapper_discrete_log](https://github.com/sagemath/sagetrac-mirror/tree/public/prevent_assertion_failure_in_AdditiveAbelianGroupWrapper_discrete_log)** to **[`93dc05c`](https://github.com/sagemath/sagetrac-mirror/commit/93dc05ccd9a6bf3358e57902cf84da87b0d91339)**
