### ISSUE TITLE
add .torsion_basis() method to EllipticCurve_finite_field

### ISSUE THREAD

**Issue by yyyyx4** [sagemath/sage#34718]
<div id="comment:0"></div>

Computing a basis of a particular `m`-torsion subgroup is an important subroutine in several algorithms for isogenies and endomorphism rings of elliptic curves over finite fields.

This patch adds a `.torsion_basis()` method to `EllipticCurve_finite_field`. Its current implementation is merely a thin wrapper around `.abelian_group()` and `.torsion_subgroup()` — the point of this patch is to introduce the interface first so that more optimizations can be incorporated later.

CC:  @defeo

Component: **elliptic curves**

Author: **Lorenz Panny**

_Issue created by migration from https://trac.sagemath.org/ticket/34718_

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
<div id="comment:2"></div>

Branch pushed to git repo; I updated commit sha1. This was a forced push. New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/f882209cdb2b6d9424f153042725c33aeab53cea"><code>f882209</code></a></td><td><code>add .torsion_basis() method to EllipticCurve_finite_field</code></td></tr></table>

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
Changed commit from **[`e7e40f0`](https://github.com/sagemath/sagetrac-mirror/commit/e7e40f093fad40f0cabe58c0367297f3d180cdd7)** to **[`f882209`](https://github.com/sagemath/sagetrac-mirror/commit/f882209cdb2b6d9424f153042725c33aeab53cea)**

**Comment by mkoeppe** [comment]
Removed branch from the issue description because it has been replaced by PR #34982
