### ISSUE TITLE
.multiplication_by_m_isogeny() fails for negative m

### ISSUE THREAD

**Issue by yyyyx4** [sagemath/sage#34727]
<div id="comment:0"></div>

```sage
sage: EllipticCurve([5,5]).multiplication_by_m_isogeny(-1)
# ...
AssertionError: bug in multiplication_by_m_isogeny()
```

```sage
sage: EllipticCurve([5,5]).multiplication_by_m_isogeny(-2)
# ...
NotImplementedError: Kohel's algorithm currently only supports cyclic isogenies (except for [2])
```

```sage
sage: EllipticCurve([5,5]).multiplication_by_m_isogeny(-3)
# ...
ValueError: n must be a positive integer (or -1 or -2)
```

All of these are because `.multiplication_by_m_isogeny()` calls `.torsion_polynomial()` with `m`, which may be negative, rather than `abs(m)`. As the last error message indicates, the values `-1` and `-2` additionally have special meaning for `.torsion_polynomial()`, which made debugging a bit more confusing...

Component: **elliptic curves**

Author: **Lorenz Panny**

Branch/Commit: **[`a6e99a7`](https://github.com/sagemath/sagetrac-mirror/commit/a6e99a73a0bb120cfe91b2bf487e3b6580205ab2)**

Reviewer: **Frédéric Chapoton**

_Issue created by migration from https://trac.sagemath.org/ticket/34727_

**Comment by yyyyx4** [comment]
<div id="comment:1"></div>

New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/a6e99a73a0bb120cfe91b2bf487e3b6580205ab2"><code>a6e99a7</code></a></td><td><code>use abs(m) to compute m-division polynomial</code></td></tr></table>

**Comment by yyyyx4** [comment]
Branch: **[public/34727](https://github.com/sagemath/sagetrac-mirror/tree/public/34727)**

**Comment by yyyyx4** [comment]
Description changed:
``````diff
--- 
+++ 
@@ -1 +1,20 @@
 
+```sage
+sage: EllipticCurve([5,5]).multiplication_by_m_isogeny(-1)
+# ...
+AssertionError: bug in multiplication_by_m_isogeny()
+```
+
+```sage
+sage: EllipticCurve([5,5]).multiplication_by_m_isogeny(-2)
+# ...
+NotImplementedError: Kohel's algorithm currently only supports cyclic isogenies (except for [2])
+```
+
+```sage
+sage: EllipticCurve([5,5]).multiplication_by_m_isogeny(-3)
+# ...
+ValueError: n must be a positive integer (or -1 or -2)
+```
+
+All of these are because `.multiplication_by_m_isogeny()` calls `.torsion_polynomial()` with `m`, which may be negative, rather than `abs(m)`. As the last error message indicates, the values `-1` and `-2` additionally have special meaning for `.torsion_polynomial()`, which made debugging a bit more confusing...
``````

**Comment by yyyyx4** [comment]
Author: **Lorenz Panny**

**Comment by yyyyx4** [comment]
Commit: **[`a6e99a7`](https://github.com/sagemath/sagetrac-mirror/commit/a6e99a73a0bb120cfe91b2bf487e3b6580205ab2)**

**Comment by fchapoton** [comment]
Reviewer: **Frédéric Chapoton**

**Comment by fchapoton** [comment]
<div id="comment:2" align="right">comment:2</div>

ok

**Comment by vbraun** [comment]
Changed branch from **[public/34727](https://github.com/sagemath/sagetrac-mirror/tree/public/34727)** to **[`a6e99a7`](https://github.com/sagemath/sagetrac-mirror/commit/a6e99a73a0bb120cfe91b2bf487e3b6580205ab2)**
