### ISSUE TITLE
change sorting for WeierstrassIsomorphism

### ISSUE THREAD

**Issue by yyyyx4** [sagemath/sage#34728]
<div id="comment:0"></div>

Currently, `EllipticCurve_generic.automorphisms()` returns the automorphisms in a more or less arbitrary (albeit deterministic) order.

It is much more natural to users to receive a list with the identity and negation first, since they exist for any curve, then any other automorphisms that may exist. (I have personally seen code making this incorrect assumption.)

In this patch, we change `._comparison_impl()` for `WeierstrassIsomorphism` in such a way that `[1]` and `[-1]` will appear first in a sorted list of automorphisms.

Diff without the dependencies: https://github.com/sagemath/sagetrac-mirror/compare/d92c9f4e4f671409ff695f4f294240492dbe7c86...c9e964632bdfd95c1f89557a5c7e1ef1c78a794a

Depends on #34727
Depends on #34722

CC:  @JohnCremona

Component: **elliptic curves**

Author: **Lorenz Panny**

Branch/Commit: **[`c9e9646`](https://github.com/sagemath/sagetrac-mirror/commit/c9e964632bdfd95c1f89557a5c7e1ef1c78a794a)**

Reviewer: **John Cremona**

_Issue created by migration from https://trac.sagemath.org/ticket/34728_

**Comment by yyyyx4** [comment]
Description changed:
``````diff
--- 
+++ 
@@ -2,6 +2,6 @@
 
 It is much more natural to users to receive a list with the identity and negation first, since they exist for any curve, then any other automorphisms that may exist. (I have personally seen code making this incorrect assumption.)
 
-In this patch, we change `._richcmp_()` for `WeierstrassIsomorphism` in such a way that `[1]` and `[-1]` will appear first in a sorted list of automorphisms.
+In this patch, we change `.__richcmp__()` for `baseWI` in such a way that `[1]` and `[-1]` will appear first in a sorted list of automorphisms.
 
 Diff without the dependencies: https://github.com/sagemath/sagetrac-mirror/compare/d92c9f4e4f671409ff695f4f294240492dbe7c86...6eaaf7e51cccaf7ea03890a2874f7f00eb7ab92c
``````

**Comment by JohnCremona** [comment]
Reviewer: **John Cremona**

**Comment by JohnCremona** [comment]
<div id="comment:2" align="right">comment:2</div>

All looks good, and I agree with the sorting strategy.  Two questions: (1) when p=2 in the random test is it still the case that the second auto in the list is multiplcation by -1? (2) In the test for the length of the autos, for the last two cases you don't really need to put both 0 and 1728 in the list since they are equal :) But I will not insist.

As long as the answer to (1) is yes, you can take a positive review from me.

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
Changed commit from **[`6eaaf7e`](https://github.com/sagemath/sagetrac-mirror/commit/6eaaf7e51cccaf7ea03890a2874f7f00eb7ab92c)** to **[`c9e9646`](https://github.com/sagemath/sagetrac-mirror/commit/c9e964632bdfd95c1f89557a5c7e1ef1c78a794a)**

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
<div id="comment:3"></div>

Branch pushed to git repo; I updated commit sha1. New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/4c4ce932ca309af16087c265ae7ccce052ee110b"><code>4c4ce93</code></a></td><td><code>0 == 1728 in characteristics 2 and 3</code></td></tr><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/c9e964632bdfd95c1f89557a5c7e1ef1c78a794a"><code>c9e9646</code></a></td><td><code>compare entire (u,r,s,t) tuple</code></td></tr></table>

**Comment by yyyyx4** [comment]
Description changed:
``````diff
--- 
+++ 
@@ -2,6 +2,6 @@
 
 It is much more natural to users to receive a list with the identity and negation first, since they exist for any curve, then any other automorphisms that may exist. (I have personally seen code making this incorrect assumption.)
 
-In this patch, we change `.__richcmp__()` for `baseWI` in such a way that `[1]` and `[-1]` will appear first in a sorted list of automorphisms.
+In this patch, we change `._comparison_impl()` for `WeierstrassIsomorphism` in such a way that `[1]` and `[-1]` will appear first in a sorted list of automorphisms.
 
-Diff without the dependencies: https://github.com/sagemath/sagetrac-mirror/compare/d92c9f4e4f671409ff695f4f294240492dbe7c86...6eaaf7e51cccaf7ea03890a2874f7f00eb7ab92c
+Diff without the dependencies: https://github.com/sagemath/sagetrac-mirror/compare/d92c9f4e4f671409ff695f4f294240492dbe7c86...c9e964632bdfd95c1f89557a5c7e1ef1c78a794a
``````

**Comment by yyyyx4** [comment]
<div id="comment:4" align="right">comment:4</div>

Thank you for the feedback!

(2) Done.

(1) The answer used to be no (I had incorrectly assumed that `u` uniquely identifies the isomorphism, which is manifestly untrue in characteristics 2 and 3), but it should be handled correctly now. This did require moving the comparison up from `baseWI` to `WeierstrassIsomorphism`, as the former knows nothing about the domain curve.

Since the new changes are not totally trivial, I'll let you have another look rather than setting it to positive review right away.

Another question: Did you check all modifications in this branch or just the ones in "diff without the dependencies"?

**Comment by JohnCremona** [comment]
<div id="comment:5" align="right">comment:5</div>

I checked all. Can't check again right now as travelling.

**Comment by JohnCremona** [comment]
<div id="comment:6" align="right">comment:6</div>

Thanks for the two extra changes. I like that the new sorting key code ends up several lines shorter!

**Comment by yyyyx4** [comment]
<div id="comment:7" align="right">comment:7</div>

Thank you! I'll also boldly go ahead and set #34722 to positive review, since the changes there are contained in this branch — which you've reviewed.

**Comment by JohnCremona** [comment]
<div id="comment:8" align="right">comment:8</div>

Replying to [Lorenz Panny](#comment%3A7):
> Thank you! I'll also boldly go ahead and set #34722 to positive review, since the changes there are contained in this branch — which you've reviewed.

OK fine

**Comment by vbraun** [comment]
Changed branch from **[public/sort_elliptic_curve_isomorphisms](https://github.com/sagemath/sagetrac-mirror/tree/public/sort_elliptic_curve_isomorphisms)** to **[`c9e9646`](https://github.com/sagemath/sagetrac-mirror/commit/c9e964632bdfd95c1f89557a5c7e1ef1c78a794a)**
