### ISSUE TITLE
some code cleanup in WeierstrassIsomorphism

### ISSUE THREAD

**Issue by yyyyx4** [sagemath/sage#34722]
<div id="comment:0"></div>

This is mainly to reduce the amount of code duplication in `sage.schemes.elliptic_curves.weierstrass_morphism.isomorphism` by turning it into a generator, plus generic style tweaks.

I consider the second commit (renaming `isomorphisms()` to `_isomorphisms()`) optional: The function has been marked as "not intended for users" forever, so I figured we might as well just hide it. Note that this does not affect the `EllipticCurve_generic.isomorphisms()` *method* in any way.

CC:  @JohnCremona

Component: **elliptic curves**

Author: **Lorenz Panny**

Branch/Commit: **[`99a6e3b`](https://github.com/sagemath/sagetrac-mirror/commit/99a6e3b014ad198fd6e25eb2d40debcf0714120f)**

Reviewer: **John Cremona**

_Issue created by migration from https://trac.sagemath.org/ticket/34722_

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
Changed commit from **[`6072f48`](https://github.com/sagemath/sagetrac-mirror/commit/6072f484f41b482cac237e5d332db3489763f72e)** to **[`fd812d2`](https://github.com/sagemath/sagetrac-mirror/commit/fd812d260732d6c96f2d5e4ed9df05128b05a45c)**

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
<div id="comment:2"></div>

Branch pushed to git repo; I updated commit sha1. This was a forced push. New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/5b840c6fa5593f952dcf82b7e35d9140913200b4"><code>5b840c6</code></a></td><td><code>some code cleanup around WeierstrassIsomorphism</code></td></tr><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/fd812d260732d6c96f2d5e4ed9df05128b05a45c"><code>fd812d2</code></a></td><td><code>hide internal function</code></td></tr></table>

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
<div id="comment:3"></div>

Branch pushed to git repo; I updated commit sha1. This was a forced push. New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/cf49d570110a48ff5238e5f894795e4739b45641"><code>cf49d57</code></a></td><td><code>some code cleanup around WeierstrassIsomorphism</code></td></tr><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/99a6e3b014ad198fd6e25eb2d40debcf0714120f"><code>99a6e3b</code></a></td><td><code>hide internal function</code></td></tr></table>

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
Changed commit from **[`fd812d2`](https://github.com/sagemath/sagetrac-mirror/commit/fd812d260732d6c96f2d5e4ed9df05128b05a45c)** to **[`99a6e3b`](https://github.com/sagemath/sagetrac-mirror/commit/99a6e3b014ad198fd6e25eb2d40debcf0714120f)**

**Comment by yyyyx4** [comment]
Reviewer: **John Cremona**

**Comment by yyyyx4** [comment]
<div id="comment:4" align="right">comment:4</div>

Setting to positive review per [#34728 comment:5](https://github.com/sagemath/sage/issues/34728#comment:5) and [#34728 comment:7](https://github.com/sagemath/sage/issues/34728#comment:7).

**Comment by vbraun** [comment]
Changed branch from **[public/some_WeierstrassIsomorphism_cleanup](https://github.com/sagemath/sagetrac-mirror/tree/public/some_WeierstrassIsomorphism_cleanup)** to **[`99a6e3b`](https://github.com/sagemath/sagetrac-mirror/commit/99a6e3b014ad198fd6e25eb2d40debcf0714120f)**
