### ISSUE TITLE
Optional package papilo (dependency of scip)

### ISSUE THREAD

**Issue by mkoeppe** [sagemath/sage#34726]
<div id="comment:0"></div>

https://github.com/scipopt/papilo/

https://github.com/scipopt/papilo/archive/refs/tags/v2.1.1.tar.gz

Not packaged anywhere - https://repology.org/projects/?search=papilo

scip uses papilo's header-only library, but papilo also likes to build an executable that may depend on scip and other solvers at compile time. - https://github.com/scipopt/papilo/issues/21

New packages needed as dependencies:
- https://github.com/oneapi-src/oneTBB - https://repology.org/project/onetbb/versions

CC:  @dimpase

Component: **packages: optional**

Author: **Matthias Koeppe**

Branch/Commit: **[`4b71c4a`](https://github.com/sagemath/sagetrac-mirror/commit/4b71c4ad8227b5fdb5b0b2f061a0139fa69f9534)**

Reviewer: **Dima Pasechnik**

_Issue created by migration from https://trac.sagemath.org/ticket/34726_

**Comment by mkoeppe** [comment]
Description changed:
``````diff
--- 
+++ 
@@ -1,4 +1,6 @@
 https://github.com/scipopt/papilo/
+
+https://github.com/scipopt/papilo/archive/refs/tags/v2.1.1.tar.gz
 
 Not packaged anywhere - https://repology.org/projects/?search=papilo
 
``````

**Comment by mkoeppe** [comment]
Description changed:
``````diff
--- 
+++ 
@@ -4,3 +4,6 @@
 
 Not packaged anywhere - https://repology.org/projects/?search=papilo
 
+scip uses papilo's header-only library
+
+but papilo also likes to build an executable that may depend on scip and other solvers at compile time 
``````

**Comment by mkoeppe** [comment]
Branch: **[u/mkoeppe/optional_package_papilo__dependency_of_scip_](https://github.com/sagemath/sagetrac-mirror/tree/u/mkoeppe/optional_package_papilo__dependency_of_scip_)**

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
Commit: **[`0dfa4b9`](https://github.com/sagemath/sagetrac-mirror/commit/0dfa4b9a8390ce54f4e00e542af4fc7166625bd2)**

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
<div id="comment:4"></div>

Branch pushed to git repo; I updated commit sha1. This was a forced push. New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/0dfa4b9a8390ce54f4e00e542af4fc7166625bd2"><code>0dfa4b9</code></a></td><td><code>build/pkgs/papilo: New</code></td></tr></table>

**Comment by mkoeppe** [comment]
<div id="comment:5" align="right">comment:5</div>

`tox -e docker-ubuntu-jammy-standard -- papilo` gives

```
  [papilo-2.1.1]   CMake Error at /usr/lib/x86_64-linux-gnu/cmake/Boost-1.74.0/BoostConfig.cmake:141 (find_package):
  [papilo-2.1.1]     Could not find a package configuration file provided by
  [papilo-2.1.1]     "boost_program_options" (requested version 1.74.0) with any of the
  [papilo-2.1.1]     following names:
  [papilo-2.1.1]   
  [papilo-2.1.1]       boost_program_optionsConfig.cmake
  [papilo-2.1.1]       boost_program_options-config.cmake
  [papilo-2.1.1]   
  [papilo-2.1.1]     Add the installation prefix of "boost_program_options" to CMAKE_PREFIX_PATH
  [papilo-2.1.1]     or set "boost_program_options_DIR" to a directory containing one of the
  [papilo-2.1.1]     above files.  If "boost_program_options" provides a separate development
  [papilo-2.1.1]     package or SDK, be sure it has been installed.
  [papilo-2.1.1]   Call Stack (most recent call first):
  [papilo-2.1.1]     /usr/lib/x86_64-linux-gnu/cmake/Boost-1.74.0/BoostConfig.cmake:258 (boost_find_component)
  [papilo-2.1.1]     /usr/share/cmake-3.22/Modules/FindBoost.cmake:594 (find_package)
  [papilo-2.1.1]     CMakeLists.txt:50 (find_package)
```

https://stackoverflow.com/questions/20502194/cmake-cannot-find-boost-program-options-on-debian

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
<div id="comment:6"></div>

Branch pushed to git repo; I updated commit sha1. New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/088b11ae1dc9a01a55d2213b7606dffb6c5469f8"><code>088b11a</code></a></td><td><code>build/pkgs/boost_cropped/distros/debian.txt: Add libboost-program-options-dev</code></td></tr></table>

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
Changed commit from **[`0dfa4b9`](https://github.com/sagemath/sagetrac-mirror/commit/0dfa4b9a8390ce54f4e00e542af4fc7166625bd2)** to **[`088b11a`](https://github.com/sagemath/sagetrac-mirror/commit/088b11ae1dc9a01a55d2213b7606dffb6c5469f8)**

**Comment by mkoeppe** [comment]
<div id="comment:7" align="right">comment:7</div>


```
[papilo-2.1.1] -- Could NOT find TBB (missing: TBB_DIR)
[papilo-2.1.1] -- Could NOT find TBB (missing: TBB_IMPORTED_TARGETS tbb tbbmalloc) (Required is at least version "2018")
[papilo-2.1.1] -- Downloading TBB
```

so we'll need to add tbb as a package

**Comment by mkoeppe** [comment]
Description changed:
``````diff
--- 
+++ 
@@ -4,6 +4,7 @@
 
 Not packaged anywhere - https://repology.org/projects/?search=papilo
 
-scip uses papilo's header-only library
+scip uses papilo's header-only library, but papilo also likes to build an executable that may depend on scip and other solvers at compile time. - https://github.com/scipopt/papilo/issues/21
 
-but papilo also likes to build an executable that may depend on scip and other solvers at compile time 
+New packages needed as dependencies:
+- https://github.com/oneapi-src/oneTBB - https://repology.org/project/onetbb/versions
``````

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
<div id="comment:9"></div>

Branch pushed to git repo; I updated commit sha1. New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/adb37b8a98a60b0e0baac8612d96ca825a46e1c3"><code>adb37b8</code></a></td><td><code>build/pkgs/papilo: Add dependency onetbb</code></td></tr></table>

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
Changed commit from **[`088b11a`](https://github.com/sagemath/sagetrac-mirror/commit/088b11ae1dc9a01a55d2213b7606dffb6c5469f8)** to **[`adb37b8`](https://github.com/sagemath/sagetrac-mirror/commit/adb37b8a98a60b0e0baac8612d96ca825a46e1c3)**

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
Changed commit from **[`adb37b8`](https://github.com/sagemath/sagetrac-mirror/commit/adb37b8a98a60b0e0baac8612d96ca825a46e1c3)** to **[`36abfb5`](https://github.com/sagemath/sagetrac-mirror/commit/36abfb534463cbe98c1c85fb9caf6ee588a5eed5)**

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
<div id="comment:10"></div>

Branch pushed to git repo; I updated commit sha1. New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/36abfb534463cbe98c1c85fb9caf6ee588a5eed5"><code>36abfb5</code></a></td><td><code>build/pkgs/onetbb: New</code></td></tr></table>

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
<div id="comment:11"></div>

Branch pushed to git repo; I updated commit sha1. This was a forced push. New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/b1e6d07bf82e5cf33c5d0118e554836018c51d49"><code>b1e6d07</code></a></td><td><code>build/pkgs/onetbb: New</code></td></tr></table>

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
Changed commit from **[`36abfb5`](https://github.com/sagemath/sagetrac-mirror/commit/36abfb534463cbe98c1c85fb9caf6ee588a5eed5)** to **[`b1e6d07`](https://github.com/sagemath/sagetrac-mirror/commit/b1e6d07bf82e5cf33c5d0118e554836018c51d49)**

**Comment by mkoeppe** [comment]
Author: **Matthias Koeppe**

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
<div id="comment:13"></div>

Branch pushed to git repo; I updated commit sha1. New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/b56f82a1158e1e2e0b1418703fc29be55e609437"><code>b56f82a</code></a></td><td><code>build/pkgs/onetbb/spkg-install.in: Do not treat compiler warnings as errors</code></td></tr></table>

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
Changed commit from **[`b1e6d07`](https://github.com/sagemath/sagetrac-mirror/commit/b1e6d07bf82e5cf33c5d0118e554836018c51d49)** to **[`b56f82a`](https://github.com/sagemath/sagetrac-mirror/commit/b56f82a1158e1e2e0b1418703fc29be55e609437)**

**Comment by mkoeppe** [comment]
<div id="comment:14" align="right">comment:14</div>

Our boost_cropped package does not provide program_options. 
ubuntu-bionic-minimal: https://github.com/mkoeppe/PySCIPOpt/actions/runs/3457453303/jobs/5774142273

```
[papilo-2.1.1]   CMake Error at /sage/local/share/cmake-3.24/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  [papilo-2.1.1]     Could NOT find Boost (missing: program_options) (found suitable version
  [papilo-2.1.1]     "1.66.0", minimum required is "1.65")
```

**Comment by dimpase** [comment]
<div id="comment:15" align="right">comment:15</div>

could it be due to out boost being over 5 years old? I'll check if we can update to 1.80 easily

**Comment by dimpase** [comment]
<div id="comment:16" align="right">comment:16</div>

see #34748 for boost update

**Comment by dimpase** [comment]
Dependencies: **#34748**

**Comment by dimpase** [comment]
<div id="comment:17" align="right">comment:17</div>

use updated boost_cropped

**Comment by dimpase** [comment]
Reviewer: **Dima Pasechnik**

**Comment by dimpase** [comment]
<div id="comment:18" align="right">comment:18</div>

lgtm  - with #34748, or with a systemwide (newer that 1.66, i.e. 1.74) boost)

**Comment by mkoeppe** [comment]
<div id="comment:19" align="right">comment:19</div>

Did you test on a system that does not have boost? 

libboost_program_options is an actual library, it's not header-only.

**Comment by dimpase** [comment]
<div id="comment:20" align="right">comment:20</div>

oops, OK. Let me see. Indeed, I have boost system-wide, so probably it was called, instead of using locally installed headers-only. I'll check if it can be built from our boost_cropped.

**Comment by dimpase** [comment]
<div id="comment:21" align="right">comment:21</div>

here is the linking of papilo binary built by Sage, and indeed, it links to system-wide boost :-(

```
$ ldd local/bin/papilo 
	linux-vdso.so.1 (0x00007fff5577e000)
	libboost_iostreams.so.1.80.0 => /usr/lib64/libboost_iostreams.so.1.80.0 (0x00007feb4b17c000)
	libboost_serialization.so.1.80.0 => /usr/lib64/libboost_serialization.so.1.80.0 (0x00007feb4b136000)
	libboost_program_options.so.1.80.0 => /usr/lib64/libboost_program_options.so.1.80.0 (0x00007feb4b0c9000)
	libtbb.so.12 => /mnt/opt/Sage/sage-dev/local/lib/libtbb.so.12 (0x00007feb4b07b000)
	[... the rest is OK]
```

---

For some reason, `papilo` also builds and installs two static libraries:

```
        "lib/libclusol.a",
        "lib/libpapilo-core.a"
```
Is this right?
`libtbb` does not link to `boost`.

**Comment by mkoeppe** [comment]
<div id="comment:22" align="right">comment:22</div>

boost is needed only for the papilo executables. We don't actually need them; scip only needs the papilo library. https://github.com/scipopt/papilo/issues/21

**Comment by mkoeppe** [comment]
<div id="comment:23" align="right">comment:23</div>

Short of what I propose in https://github.com/scipopt/papilo/issues/21, we can just patch out building the papilo executables to get rid of this dependency.

**Comment by dimpase** [comment]
<div id="comment:24" align="right">comment:24</div>

In case we'd like to build papilo executable, on macOS it needs boost 1.72 or newer.

**Comment by dimpase** [comment]
<div id="comment:25" align="right">comment:25</div>

We can also build a needed subset (or all)  of boost libraries from the boost_cropped tarball, in that sense we are good, too.

**Comment by mkoeppe** [comment]
Changed dependencies from **#34748** to none

**Comment by mkoeppe** [comment]
<div id="comment:26" align="right">comment:26</div>

Marc Pfetsch from the scip team advises that SCIP only needs the papilo headers.

I'll reduce this package to an do an ad-hoc installation of the headers.
This removes the need for work on boost.

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
<div id="comment:27"></div>

Branch pushed to git repo; I updated commit sha1. New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/5a04fdc4bddd9ce04b6570ddc6f6cf4b1e3a0a21"><code>5a04fdc</code></a></td><td><code>build/pkgs/papilo/spkg-install.in: Only install headers</code></td></tr></table>

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
Changed commit from **[`b56f82a`](https://github.com/sagemath/sagetrac-mirror/commit/b56f82a1158e1e2e0b1418703fc29be55e609437)** to **[`5a04fdc`](https://github.com/sagemath/sagetrac-mirror/commit/5a04fdc4bddd9ce04b6570ddc6f6cf4b1e3a0a21)**

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
<div id="comment:28"></div>

Branch pushed to git repo; I updated commit sha1. This was a forced push. New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/f27de021cb42101b9b7c8512fb0ac18e768195dc"><code>f27de02</code></a></td><td><code>build/pkgs/papilo/spkg-install.in: Only install headers</code></td></tr></table>

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
Changed commit from **[`5a04fdc`](https://github.com/sagemath/sagetrac-mirror/commit/5a04fdc4bddd9ce04b6570ddc6f6cf4b1e3a0a21)** to **[`f27de02`](https://github.com/sagemath/sagetrac-mirror/commit/f27de021cb42101b9b7c8512fb0ac18e768195dc)**

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
Changed commit from **[`f27de02`](https://github.com/sagemath/sagetrac-mirror/commit/f27de021cb42101b9b7c8512fb0ac18e768195dc)** to **[`a52e72f`](https://github.com/sagemath/sagetrac-mirror/commit/a52e72f39c93852e3f8207619dbbad4a18c781d9)**

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
<div id="comment:29"></div>

Branch pushed to git repo; I updated commit sha1. This was a forced push. New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/a52e72f39c93852e3f8207619dbbad4a18c781d9"><code>a52e72f</code></a></td><td><code>build/pkgs/papilo: Patch out dependency on boost program_options, use PAPILO_NO_BINARIES=1</code></td></tr></table>

**Comment by mkoeppe** [comment]
<div id="comment:30" align="right">comment:30</div>

build failure on fedora-37 - https://github.com/scipopt/papilo/issues/23

**Comment by mkoeppe** [comment]
<div id="comment:31" align="right">comment:31</div>

build failure of `onetbb` on `ubuntu-trusty-toolchain-gcc_9` https://github.com/mkoeppe/PySCIPOpt/actions/runs/3535481134/jobs/5933596249

```
2021.7.0/src/src/tbb/../../include/tbb/../oneapi/tbb/detail/_concurrent_skip_list.h:25,
                 from /sage/local/var/tmp/sage/build/onetbb-2021.7.0/src/src/tbb/../../include/tbb/../oneapi/tbb/concurrent_map.h:21,
                 from /sage/local/var/tmp/sage/build/onetbb-2021.7.0/src/src/tbb/../../include/tbb/concurrent_map.h:17,
                 from /sage/local/var/tmp/sage/build/onetbb-2021.7.0/src/test/tbb/test_concurrent_map.cpp:19:
/usr/include/c++/9/bits/basic_string.h: In instantiation of 'class std::basic_string<char, std::char_traits<char>, tbb::detail::d1::tbb_allocator<char> >':
/sage/local/var/tmp/sage/build/onetbb-2021.7.0/src/test/common/concurrent_associative_common.h:964:29:   required from 'void test_map_specific_types() [with Checker = OrderedMapTypesTester]'
/sage/local/var/tmp/sage/build/onetbb-2021.7.0/src/test/tbb/test_concurrent_map.cpp:90:52:   required from here
/usr/include/c++/9/bits/basic_string.h:3146:63: error: no class template named 'rebind' in 'class tbb::detail::d1::tbb_allocator<char>'
 3146 |       typedef typename _Alloc::template rebind<_CharT>::other _CharT_alloc_type;
      |                                                               ^~~~~~~~~~~~~~~~~
compilation terminated due to -Wfatal-errors.
make[5]: *** [test/CMakeFiles/test_concurrent_map.dir/tbb/test_concurrent_map.cpp.o] Error 1
make[5]: Target `test/CMakeFiles/test_concurrent_map.dir/build' not remade because of errors.
make[4]: *** [test/CMakeFiles/test_concurrent_map.dir/all] Error 2
```

**Comment by mkoeppe** [comment]
<div id="comment:32" align="right">comment:32</div>

That's https://github.com/oneapi-src/oneTBB/issues/383

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
Changed commit from **[`a52e72f`](https://github.com/sagemath/sagetrac-mirror/commit/a52e72f39c93852e3f8207619dbbad4a18c781d9)** to **[`3adc477`](https://github.com/sagemath/sagetrac-mirror/commit/3adc477a7c2e8852c86b6982b3947aa4f13a8547)**

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
<div id="comment:33"></div>

Branch pushed to git repo; I updated commit sha1. New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/1f30f5c6f7a285a7faaf2403dd5dcea4e00da611"><code>1f30f5c</code></a></td><td><code>Merge tag '9.8.beta4' into t/34726/optional_package_papilo__dependency_of_scip_</code></td></tr><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/b62841d168166ebf263bd536e8c570fb9615759a"><code>b62841d</code></a></td><td><code>build/pkgs/papilo/dependencies: Add gfortran</code></td></tr><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/6e78b577144bcf85323473e74ab367ddd27c1b4f"><code>6e78b57</code></a></td><td><code>build/pkgs/papilo/spkg-install.in: Set BOOST_ROOT</code></td></tr><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/3adc477a7c2e8852c86b6982b3947aa4f13a8547"><code>3adc477</code></a></td><td><code>build/pkgs/onetbb/spkg-configure.m4: New</code></td></tr></table>

**Comment by mkoeppe** [comment]
<div id="comment:34" align="right">comment:34</div>

build failures on `ubuntu-trusty-toolchain-gcc_9` (comment:31) and `fedora-37` (comment:30) remain, but that should not stop us from merging these optional packages. Both need help from upstream

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
<div id="comment:35"></div>

Branch pushed to git repo; I updated commit sha1. New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/45f957e011c946a26354615c4d86441c699a3617"><code>45f957e</code></a></td><td><code>Revert "build/pkgs/boost_cropped/distros/debian.txt: Add libboost-program-options-dev"</code></td></tr></table>

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
Changed commit from **[`3adc477`](https://github.com/sagemath/sagetrac-mirror/commit/3adc477a7c2e8852c86b6982b3947aa4f13a8547)** to **[`45f957e`](https://github.com/sagemath/sagetrac-mirror/commit/45f957e011c946a26354615c4d86441c699a3617)**

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
Changed commit from **[`45f957e`](https://github.com/sagemath/sagetrac-mirror/commit/45f957e011c946a26354615c4d86441c699a3617)** to **[`d26090f`](https://github.com/sagemath/sagetrac-mirror/commit/d26090f4b21f4def3e07b09a55dfa0264137b1dd)**

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
<div id="comment:36"></div>

Branch pushed to git repo; I updated commit sha1. New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/ebac2fdbc263993bb2a526f5dd41546ba81e3631"><code>ebac2fd</code></a></td><td><code>build/pkgs/papilo/patches: Add https://github.com/scipopt/papilo/commit/e34cfbe0b6d6b4c6e8d5d9305046a00821c81828</code></td></tr><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/d26090f4b21f4def3e07b09a55dfa0264137b1dd"><code>d26090f</code></a></td><td><code>build/pkgs/papilo/patches/import_memory_multiprecision.patch: New, back out ineffective patch</code></td></tr></table>

**Comment by mkoeppe** [comment]
<div id="comment:37" align="right">comment:37</div>

This fixed the build failure on fedora-37.

**Comment by mkoeppe** [comment]
<div id="comment:38" align="right">comment:38</div>

Ready for review

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
<div id="comment:39"></div>

Branch pushed to git repo; I updated commit sha1. New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/4b71c4ad8227b5fdb5b0b2f061a0139fa69f9534"><code>4b71c4a</code></a></td><td><code>build/pkgs/onetbb/distros/conda.txt: New</code></td></tr></table>

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
Changed commit from **[`d26090f`](https://github.com/sagemath/sagetrac-mirror/commit/d26090f4b21f4def3e07b09a55dfa0264137b1dd)** to **[`4b71c4a`](https://github.com/sagemath/sagetrac-mirror/commit/4b71c4ad8227b5fdb5b0b2f061a0139fa69f9534)**

**Comment by mkoeppe** [comment]
<div id="comment:41" align="right">comment:41</div>

Thanks!

**Comment by vbraun** [comment]
Changed branch from **[u/mkoeppe/optional_package_papilo__dependency_of_scip_](https://github.com/sagemath/sagetrac-mirror/tree/u/mkoeppe/optional_package_papilo__dependency_of_scip_)** to **[`4b71c4a`](https://github.com/sagemath/sagetrac-mirror/commit/4b71c4ad8227b5fdb5b0b2f061a0139fa69f9534)**
