### ISSUE TITLE
math display broken because of missing .

### ISSUE THREAD

**Issue by mantepse** [sagemath/sage#34731]
<div id="comment:0"></div>

Component: **documentation**

Author: **Martin Rubey**

Branch/Commit: **[`8cb464d`](https://github.com/sagemath/sagetrac-mirror/commit/8cb464d6bd4d314d33a0373ab62e7ea4c32391e9)**

Reviewer: **Dave Morris**

_Issue created by migration from https://trac.sagemath.org/ticket/34731_

**Comment by mantepse** [comment]
Branch: **[u/mantepse/math_display_broken_because_of_missing__](https://github.com/sagemath/sagetrac-mirror/tree/u/mantepse/math_display_broken_because_of_missing__)**

**Comment by DaveWitteMorris** [comment]
Commit: **[`8cb464d`](https://github.com/sagemath/sagetrac-mirror/commit/8cb464d6bd4d314d33a0373ab62e7ea4c32391e9)**

**Comment by DaveWitteMorris** [comment]
<div id="comment:2"></div>

New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/8cb464d6bd4d314d33a0373ab62e7ea4c32391e9"><code>8cb464d</code></a></td><td><code>add missing dot</code></td></tr></table>

**Comment by DaveWitteMorris** [comment]
Author: **Martin Rubey**

**Comment by DaveWitteMorris** [comment]
Reviewer: **Dave Morris**

**Comment by vbraun** [comment]
Changed branch from **[u/mantepse/math_display_broken_because_of_missing__](https://github.com/sagemath/sagetrac-mirror/tree/u/mantepse/math_display_broken_because_of_missing__)** to **[`8cb464d`](https://github.com/sagemath/sagetrac-mirror/commit/8cb464d6bd4d314d33a0373ab62e7ea4c32391e9)**
