### ISSUE TITLE
less use of gap.eval in linear code

### ISSUE THREAD

**Issue by fchapoton** [sagemath/sage#34737]
<div id="comment:0"></div>

but there remains some uses in the same file

Part of #26902. Follow-up ticket: #34771

CC:  @tscrim @slel @kwankyu @kliem

Component: **coding theory**

Author: **Frédéric Chapoton**

Branch: **[`d86dd0c`](https://github.com/sagemath/sagetrac-mirror/commit/d86dd0c79ca6b59dbfae69960fac3a60d0bc8485)**

Reviewer: **Kwankyu Lee**

_Issue created by migration from https://trac.sagemath.org/ticket/34737_

**Comment by fchapoton** [comment]
<div id="comment:1"></div>

New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/d86dd0c79ca6b59dbfae69960fac3a60d0bc8485"><code>d86dd0c</code></a></td><td><code>less use of gap.eval in linear_code</code></td></tr></table>

**Comment by fchapoton** [comment]
Branch: **[u/chapoton/34737](https://github.com/sagemath/sagetrac-mirror/tree/u/chapoton/34737)**

**Comment by fchapoton** [comment]
Commit: **[`d86dd0c`](https://github.com/sagemath/sagetrac-mirror/commit/d86dd0c79ca6b59dbfae69960fac3a60d0bc8485)**

**Comment by fchapoton** [comment]
<div id="comment:2" align="right">comment:2</div>

green lights, so please review

**Comment by kwankyu** [comment]
Reviewer: **Kwankyu Lee**

**Comment by kwankyu** [comment]
<div id="comment:3" align="right">comment:3</div>

LGTM. Thanks.

**Comment by vbraun** [comment]
Changed branch from **[u/chapoton/34737](https://github.com/sagemath/sagetrac-mirror/tree/u/chapoton/34737)** to **[`d86dd0c`](https://github.com/sagemath/sagetrac-mirror/commit/d86dd0c79ca6b59dbfae69960fac3a60d0bc8485)**

**Comment by dimpase** [comment]
Changed commit from **[`d86dd0c`](https://github.com/sagemath/sagetrac-mirror/commit/d86dd0c79ca6b59dbfae69960fac3a60d0bc8485)** to none

**Comment by dimpase** [comment]
Description changed:
``````diff
--- 
+++ 
@@ -1 +1,3 @@
 but there remains some uses in the same file
+
+Part of #26902. Follow-up ticket: #34771
``````
