### ISSUE TITLE
cleanup for QQ-curves

### ISSUE THREAD

**Issue by fchapoton** [sagemath/sage#34736]
<div id="comment:0"></div>

mostly pep8 details

also adding one doctest

Component: **elliptic curves**

Author: **Frédéric Chapoton**

Branch/Commit: **[`c0eaf1e`](https://github.com/sagemath/sagetrac-mirror/commit/c0eaf1e9a7ad01bbf8c6a464afbfee438cc0c62f)**

Reviewer: **Lorenz Panny**

_Issue created by migration from https://trac.sagemath.org/ticket/34736_

**Comment by fchapoton** [comment]
Commit: **[`c0eaf1e`](https://github.com/sagemath/sagetrac-mirror/commit/c0eaf1e9a7ad01bbf8c6a464afbfee438cc0c62f)**

**Comment by fchapoton** [comment]
Branch: **[u/chapoton/34736](https://github.com/sagemath/sagetrac-mirror/tree/u/chapoton/34736)**

**Comment by fchapoton** [comment]
<div id="comment:1"></div>

New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/c0eaf1e9a7ad01bbf8c6a464afbfee438cc0c62f"><code>c0eaf1e</code></a></td><td><code>cleanup for QQ-curves</code></td></tr></table>

**Comment by yyyyx4** [comment]
Reviewer: **Lorenz Panny**

**Comment by yyyyx4** [comment]
<div id="comment:2" align="right">comment:2</div>

The doctest failure seems entirely unrelated.

**Comment by vbraun** [comment]
Changed branch from **[u/chapoton/34736](https://github.com/sagemath/sagetrac-mirror/tree/u/chapoton/34736)** to **[`c0eaf1e`](https://github.com/sagemath/sagetrac-mirror/commit/c0eaf1e9a7ad01bbf8c6a464afbfee438cc0c62f)**
