### ISSUE TITLE
get rid of some usage of "long" python2 type in pyx files

### ISSUE THREAD

**Issue by fchapoton** [sagemath/sage#34739]
<div id="comment:0"></div>

CC:  @vbraun

Component: **refactoring**

Author: **Frédéric Chapoton**

Branch/Commit: **[`91704bb`](https://github.com/sagemath/sagetrac-mirror/commit/91704bbd12bdb01c4137d1d0dd51b68499258d26)**

Reviewer: **Kwankyu Lee**

_Issue created by migration from https://trac.sagemath.org/ticket/34739_

**Comment by fchapoton** [comment]
Commit: **[`f567abf`](https://github.com/sagemath/sagetrac-mirror/commit/f567abf978ca328f67595743b5248ee42485b41e)**

**Comment by fchapoton** [comment]
<div id="comment:1"></div>

New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/f567abf978ca328f67595743b5248ee42485b41e"><code>f567abf</code></a></td><td><code>get rid of some usage of "long" in pyx files</code></td></tr></table>

**Comment by fchapoton** [comment]
Branch: **[u/chapoton/34739](https://github.com/sagemath/sagetrac-mirror/tree/u/chapoton/34739)**

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
Changed commit from **[`f567abf`](https://github.com/sagemath/sagetrac-mirror/commit/f567abf978ca328f67595743b5248ee42485b41e)** to **[`e8cebc3`](https://github.com/sagemath/sagetrac-mirror/commit/e8cebc3b2a473343d3a07c5d5b6102265f265b4b)**

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
<div id="comment:2"></div>

Branch pushed to git repo; I updated commit sha1. New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/e8cebc3b2a473343d3a07c5d5b6102265f265b4b"><code>e8cebc3</code></a></td><td><code>fix typo</code></td></tr></table>

**Comment by fchapoton** [comment]
<div id="comment:3"></div>

New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/e8cebc3b2a473343d3a07c5d5b6102265f265b4b"><code>e8cebc3</code></a></td><td><code>fix typo</code></td></tr></table>

**Comment by jhpalmieri** [comment]
<div id="comment:4" align="right">comment:4</div>

Sorry, wrong ticket.

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
<div id="comment:5"></div>

Branch pushed to git repo; I updated commit sha1. New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/39ad89060c6931db6049620fdf9dc408941abb3a"><code>39ad890</code></a></td><td><code>fix factorial of type int</code></td></tr></table>

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
Changed commit from **[`e8cebc3`](https://github.com/sagemath/sagetrac-mirror/commit/e8cebc3b2a473343d3a07c5d5b6102265f265b4b)** to **[`39ad890`](https://github.com/sagemath/sagetrac-mirror/commit/39ad89060c6931db6049620fdf9dc408941abb3a)**

**Comment by kwankyu** [comment]
<div id="comment:6" align="right">comment:6</div>

Or this

```diff
--- a/src/sage/symbolic/expression.pyx
+++ b/src/sage/symbolic/expression.pyx
@@ -13724,7 +13724,7 @@ cpdef new_Expression(parent, x):
             return NaN
         exp = x
     elif isinstance(x, int):
-        exp = GEx(<long>x)
+        exp = x
     elif x is infinity:
         return new_Expression_from_GEx(parent, g_Infinity)
     elif x is minus_infinity:
```
?

**Comment by dcoudert** [comment]
<div id="comment:7" align="right">comment:7</div>

This change is not correct in `src/sage/rings/polynomial/plural.pyx`: extra `)`

```diff
+            raise NotImplementedError(f"not able to interpret {element)}"
```

**Comment by kwankyu** [comment]
<div id="comment:8" align="right">comment:8</div>


```diff
--- a/src/sage/symbolic/expression.pyx
+++ b/src/sage/symbolic/expression.pyx
@@ -13724,7 +13724,10 @@ cpdef new_Expression(parent, x):
             return NaN
         exp = x
     elif isinstance(x, int):
-        exp = GEx(<long>x)
+        try:
+            exp = GEx(<long>x)
+        except OverflowError:
+            exp = x
     elif x is infinity:
         return new_Expression_from_GEx(parent, g_Infinity)
     elif x is minus_infinity:
```
fixes the failing doctest, but introduces (or reveals?) a Heisenbug:

```
sage -t --warn-long 64.8 --random-seed=209400216403961693791706262075210533242 src/sage/schemes/toric/sheaf/klyachko.py
**********************************************************************
File "src/sage/schemes/toric/sheaf/klyachko.py", line 951, in sage.schemes.toric.sheaf.klyachko.KlyachkoBundle_class.random_deformation
Failed example:
    Vtilde.cohomology(dim=True, weight=(0,))
Expected:
    (1, 0)
Got:
    (0, 0)
**********************************************************************
```

**Comment by kwankyu** [comment]
<div id="comment:10" align="right">comment:10</div>

The Heisenbug might not be a bug as Vtilde is a random line bundle. I invited an expert.

**Comment by kwankyu** [comment]
<div id="comment:11" align="right">comment:11</div>

The Heisenbug has been tracked in #32773. So the failed doctest is not related with this ticket.

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
<div id="comment:12"></div>

Branch pushed to git repo; I updated commit sha1. New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/966f1596adefde7a85bab6c8c5b3f4b67537216f"><code>966f159</code></a></td><td><code>small fixes</code></td></tr></table>

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
Changed commit from **[`39ad890`](https://github.com/sagemath/sagetrac-mirror/commit/39ad89060c6931db6049620fdf9dc408941abb3a)** to **[`966f159`](https://github.com/sagemath/sagetrac-mirror/commit/966f1596adefde7a85bab6c8c5b3f4b67537216f)**

**Comment by fchapoton** [comment]
<div id="comment:13" align="right">comment:13</div>

all lights are green now

**Comment by kwankyu** [comment]
<div id="comment:14" align="right">comment:14</div>

Why `GEx(<int>x)` rather than `GEx(<long>x)`? GEx seems to accept C long type. C long is better than C int. No?

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
<div id="comment:15"></div>

Branch pushed to git repo; I updated commit sha1. New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/91704bbd12bdb01c4137d1d0dd51b68499258d26"><code>91704bb</code></a></td><td><code>switch back to <long></code></td></tr></table>

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
Changed commit from **[`966f159`](https://github.com/sagemath/sagetrac-mirror/commit/966f1596adefde7a85bab6c8c5b3f4b67537216f)** to **[`91704bb`](https://github.com/sagemath/sagetrac-mirror/commit/91704bbd12bdb01c4137d1d0dd51b68499258d26)**

**Comment by fchapoton** [comment]
<div id="comment:16" align="right">comment:16</div>

ok, done. If I understand correctly `<long>` is not a python type but a C type, right ?

**Comment by fchapoton** [comment]
<div id="comment:17" align="right">comment:17</div>

green lights again

**Comment by kwankyu** [comment]
<div id="comment:18" align="right">comment:18</div>

I looked into pynac code, and became confident that the code I suggested is right. The cython code first tries to make GEx (ginac ex) object holding C long data, then in the case of overflow exception, (eventually) make GEx object holding the original python int object.

Otherwise LGTM.

**Comment by kwankyu** [comment]
Reviewer: **Kwankyu Lee**

**Comment by kwankyu** [comment]
<div id="comment:19" align="right">comment:19</div>

Replying to [Frédéric Chapoton](#comment%3A16):
> ok, done. If I understand correctly `<long>` is not a python type but a C type, right?

Right. We are juggling with "python2 int", "python2 long", "python3 int", "C int", "C long" :)

**Comment by vbraun** [comment]
Changed branch from **[u/chapoton/34739](https://github.com/sagemath/sagetrac-mirror/tree/u/chapoton/34739)** to **[`91704bb`](https://github.com/sagemath/sagetrac-mirror/commit/91704bbd12bdb01c4137d1d0dd51b68499258d26)**
