### ISSUE TITLE
Rebase sage_autodoc to sphinx 5.3.0

### ISSUE THREAD

**Issue by kwankyu** [sagemath/sage#34730]
<div id="comment:0"></div>

We rebase `sage_autodoc` to Sphinx 5.3.0.

This is a step toward eventual removal of sage_autodoc in #30893, a customization of Sphinx autodoc extension for Sage objects.

Other related tickets are #27578. #30884, #31309, in this regard.

CC:  @kiwifb

Component: **documentation**

Author: **Kwankyu Lee**

Branch/Commit: **[`aa74d4b`](https://github.com/sagemath/sagetrac-mirror/commit/aa74d4badcbe6841833ff983ad5f756c5ac78752)**

Reviewer: **Tobias Diez**

_Issue created by migration from https://trac.sagemath.org/ticket/34730_

**Comment by kwankyu** [comment]
Branch: **[u/klee/rebase_sage_autodoc_to_sphinx_5_3_0](https://github.com/sagemath/sagetrac-mirror/tree/u/klee/rebase_sage_autodoc_to_sphinx_5_3_0)**

**Comment by kwankyu** [comment]
Author: **Kwankyu Lee**

**Comment by kwankyu** [comment]
Commit: **[`94a9718`](https://github.com/sagemath/sagetrac-mirror/commit/94a9718bb25511f52ee7c1a8890c7a9a257822ee)**

**Comment by kwankyu** [comment]
Description changed:
``````diff
--- 
+++ 
@@ -1 +1 @@
-
+We again rebase `sage_autodoc` to Sphinx 5.3.0.
``````

**Comment by kwankyu** [comment]
<div id="comment:3" align="right">comment:3</div>

Setting "needs review" to build the documentation for further check.

**Comment by kwankyu** [comment]
Description changed:
``````diff
--- 
+++ 
@@ -1 +1 @@
-We again rebase `sage_autodoc` to Sphinx 5.3.0.
+We rebase `sage_autodoc` to Sphinx 5.3.0.
``````

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
Changed commit from **[`94a9718`](https://github.com/sagemath/sagetrac-mirror/commit/94a9718bb25511f52ee7c1a8890c7a9a257822ee)** to **[`3e917a4`](https://github.com/sagemath/sagetrac-mirror/commit/3e917a48683f558c90819d93e0ed0cbecc6551aa)**

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
<div id="comment:6"></div>

Branch pushed to git repo; I updated commit sha1. New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/3e917a48683f558c90819d93e0ed0cbecc6551aa"><code>3e917a4</code></a></td><td><code>Remove spurious changes</code></td></tr></table>

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
Changed commit from **[`3e917a4`](https://github.com/sagemath/sagetrac-mirror/commit/3e917a48683f558c90819d93e0ed0cbecc6551aa)** to **[`aa74d4b`](https://github.com/sagemath/sagetrac-mirror/commit/aa74d4badcbe6841833ff983ad5f756c5ac78752)**

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
<div id="comment:9"></div>

Branch pushed to git repo; I updated commit sha1. New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/aa74d4badcbe6841833ff983ad5f756c5ac78752"><code>aa74d4b</code></a></td><td><code>More edits</code></td></tr></table>

**Comment by kwankyu** [comment]
Description changed:
``````diff
--- 
+++ 
@@ -1 +1,5 @@
 We rebase `sage_autodoc` to Sphinx 5.3.0.
+
+This is a step toward eventual removal of sage_autodoc, a customization of Sphinx autodoc extension for Sage objects.
+
+The next crucial step would be #27578.
``````

**Comment by kwankyu** [comment]
Description changed:
``````diff
--- 
+++ 
@@ -2,4 +2,4 @@
 
 This is a step toward eventual removal of sage_autodoc, a customization of Sphinx autodoc extension for Sage objects.
 
-The next crucial step would be #27578.
+The next crucial step would be #27578. Other related tickets are #30884, #31309
``````

**Comment by kwankyu** [comment]
Description changed:
``````diff
--- 
+++ 
@@ -2,4 +2,4 @@
 
 This is a step toward eventual removal of sage_autodoc, a customization of Sphinx autodoc extension for Sage objects.
 
-The next crucial step would be #27578. Other related tickets are #30884, #31309
+Other related tickets are #27578. #30884, #31309, in this regard.
``````

**Comment by kiwifb** [comment]
<div id="comment:13" align="right">comment:13</div>

Do you have a ticket for sphinx 5.3.0 or is it backward compatible?

**Comment by kwankyu** [comment]
<div id="comment:14" align="right">comment:14</div>

Replying to [François Bissey](#comment%3A13):
> Do you have a ticket for sphinx 5.3.0 or is it backward compatible?

There is no difference between `autodoc`s of sphinx 5.2.3 and 5.3.0.

**Comment by kwankyu** [comment]
<div id="comment:15" align="right">comment:15</div>

Moreover, as our old sage_autodoc (that is based on sphinx 1.8.x) still works with sphinx 5.2.3, autodoc extension seems pretty independent from the version of sphinx.

**Comment by kiwifb** [comment]
<div id="comment:16" align="right">comment:16</div>

I am fairly it has been touched here and there. But because of the ticket title I was wondering if we were doing something specific for sphinx 5.3.0. I have not checked we are compatible with sphinx 5.3.0 for example (and presumably if Antonio Rojas tested it, he didn't find/report any issues).

**Comment by kwankyu** [comment]
<div id="comment:17" align="right">comment:17</div>

Replying to [François Bissey](#comment%3A16):
> I am fairly it has been touched here and there. But because of the ticket title I was wondering if we were doing something specific for sphinx 5.3.0. 

I just used the latest from sphinx 5.x series.

**Comment by kwankyu** [comment]
<div id="comment:18" align="right">comment:18</div>

Replying to [François Bissey](#comment%3A16):
> I have not checked we are compatible with sphinx 5.3.0 for example (and presumably if Antonio Rojas tested it, he didn't find/report any issues).

When I did the rebase for sphinx 1.8.x, there were many regressions, which Jeroen Demeyer detected and reported to me. If there are none (or few) this time, that is because of the efforts made then. This time it is not that difficult. Next time, hopefully it would be even easier :)

**Comment by tobiasdiez** [comment]
<div id="comment:19" align="right">comment:19</div>

LGTM.

Since you are now familiar with the code, can you maybe list the major changes of sage's autodoc in #30893 with a proposal for how to remove the modification.

**Comment by tobiasdiez** [comment]
Description changed:
``````diff
--- 
+++ 
@@ -1,5 +1,5 @@
 We rebase `sage_autodoc` to Sphinx 5.3.0.
 
-This is a step toward eventual removal of sage_autodoc, a customization of Sphinx autodoc extension for Sage objects.
+This is a step toward eventual removal of sage_autodoc in #30893, a customization of Sphinx autodoc extension for Sage objects.
 
 Other related tickets are #27578. #30884, #31309, in this regard.
``````

**Comment by tobiasdiez** [comment]
Reviewer: **Tobias Diez**

**Comment by kwankyu** [comment]
<div id="comment:20" align="right">comment:20</div>

Replying to [Tobias Diez](#comment%3A19):
> LGTM.

Thanks.

> Since you are now familiar with the code, 

Well.., it was basically trial-and-errors with bits of understanding here and there :)

> can you maybe list the major changes of sage's autodoc in #30893 with a proposal for how to remove the modification.

I marked in the code where modifications are made. It is easy to list them:

1. skipping lazy imports to avoid deprecation warnings
2. providing argspecs for decorators (sage_wraps)
3. dealing with nested classes
4. dealing with cached function(methods) callers
5. dealing with classcall metaclass  
6. dealing with class aliases
7. using argspecs instead of signature 

but sorry no proposal for how to remove them. All looks difficult. I am not sure if the aim of eventual removal of sage_autodoc is really achievable. 

After #26254 merged, switching to signature seems the most urgent thing.

**Comment by tobiasdiez** [comment]
<div id="comment:21" align="right">comment:21</div>

Thanks for the summary, I've added it to #30893.

**Comment by vbraun** [comment]
Changed branch from **[u/klee/rebase_sage_autodoc_to_sphinx_5_3_0](https://github.com/sagemath/sagetrac-mirror/tree/u/klee/rebase_sage_autodoc_to_sphinx_5_3_0)** to **[`aa74d4b`](https://github.com/sagemath/sagetrac-mirror/commit/aa74d4badcbe6841833ff983ad5f756c5ac78752)**
