### ISSUE TITLE
polynomial quo_rem gives wrong answer for noncommutative rings

### ISSUE THREAD

**Issue by DaveWitteMorris** [sagemath/sage#34733]
<div id="comment:0"></div>

As reported in [this sage-devel thread](https://groups.google.com/g/sage-devel/c/D4jOrvAyyj8/m/yL9YEsE5GAAJ):

The `quo_rem` method for polynomials with quaternionic coefficients outputs incorrect results. Moreover, there is no way to specify whether we want a right or left division. Here is a specific example.

```
# Take the quaternion algebra (-1, -1)_QQ and the ring of polynomials over it:
HH = QuaternionAlgebra(QQ, -1, -1)
P.<x> = HH[]
# Take two polynomials
f = x^3 + HH.0*x + (HH.1 + 2*HH.2); print("f =", f)
g = HH.2*x + HH.1 + 3; print("g =", g)
# Try to compute the quotient and remainder
q, r = f.quo_rem(g)
# Check the correctness of the result assuming that this is RIGHT division
print(q*g + r == f)
# Check the correctness of the result assuming that this is LEFT division
print(g*q + r == f)
```

Both tests output False. Tested on Sage 9.5.

Mathematical background: the division with the remainder for polynomials over division rings is well known and fully described e.g. in [1] even in a more general setting when the variable does not commute with the coefficients (in our case it does commute). So it is just a matter of proper implementation.

[1] Ore, Oystein. Theory of non-commutative polynomials. Ann. of Math. (2) 34 (1933), no. 3, 480--508. [MR1503119](https://mathscinet.ams.org/mathscinet-getitem?mr=1503119)

Component: **algebra**

Author: **Dave Morris**

Branch/Commit: **[`b50426f`](https://github.com/sagemath/sagetrac-mirror/commit/b50426fcfe2a979d44de50b0069a9ee2d0eecf8d)**

Reviewer: **Martin Rubey**

_Issue created by migration from https://trac.sagemath.org/ticket/34733_

**Comment by DaveWitteMorris** [comment]
Branch: **[public/34733](https://github.com/sagemath/sagetrac-mirror/tree/public/34733)**

**Comment by DaveWitteMorris** [comment]
<div id="comment:2" align="right">comment:2</div>

The bug was that the multiplication by `y` and the multiplication by its inverse (`inv`) were not both on the same side.

Allowing the user to choose whether to have a left quotient or right quotient would be a bit more involved. (Adding a keyword argument for this would make the signature of this method incompatible with other implementations of `quo_rem`.) So I would like to leave this potential enhancement to a follow-up ticket.

---
New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/75026c0d2ab259a01854695c9fdf115c90c5dd8d"><code>75026c0</code></a></td><td><code>trac 34733 noncommutative quo_rem</code></td></tr></table>

**Comment by DaveWitteMorris** [comment]
Commit: **[`75026c0`](https://github.com/sagemath/sagetrac-mirror/commit/75026c0d2ab259a01854695c9fdf115c90c5dd8d)**

**Comment by mantepse** [comment]
<div id="comment:3" align="right">comment:3</div>

wouldn't it make sense to add the same doctest also for the other polynomial rings?

**Comment by DaveWitteMorris** [comment]
<div id="comment:4" align="right">comment:4</div>

Are you suggesting that we add a random doctest like this to the `quo_rem` methods for other polynomials that don't have one yet?  That sounds like a good idea to me, but I think it should be a separate ticket.

**Comment by mantepse** [comment]
<div id="comment:5" align="right">comment:5</div>

Yes, but why not here?  One could in theory also do a slightly more systematic check (eg., checking `quo_rem` for `some_elements`), and I'd agree that this would be for another ticket, but the simple thing could be done here, no?

**Comment by DaveWitteMorris** [comment]
<div id="comment:6" align="right">comment:6</div>

I think there are about 15 different files that define `quo_rem` for various types of single-variable polynomials. That's expanding the scope of a very simple bug fix ticket (which I was happy to do and thought was important, since it's a bug) to a fairly substantial enhancement (which I probably won't have time to do soon, but could probably do in January).

**Comment by mantepse** [comment]
<div id="comment:7" align="right">comment:7</div>

I think that the only other polynomial ring that really applies is the sparse version in `polynomial_element_generic.py`.  Do you think adding the following test is OK?

```diff
diff --git a/src/sage/rings/polynomial/polynomial_element_generic.py b/src/sage/rings/polynomial/polynomial_element_generic.py
index 868a5f691f9..f30e4325d1f 100644
--- a/src/sage/rings/polynomial/polynomial_element_generic.py
+++ b/src/sage/rings/polynomial/polynomial_element_generic.py
@@ -824,6 +824,17 @@ class Polynomial_generic_sparse(Polynomial):
             sage: f.quo_rem(g)
             (-y^5 + 2*y^2, y^3 - 2*x^2*y^2 - y)
 
+        Polynomials over noncommutative rings are also allowed
+        (after :trac:`34733`)::
+
+            sage: HH = QuaternionAlgebra(QQ, -1, -1)
+            sage: P.<x> = PolynomialRing(HH, sparse=True)
+            sage: f = P.random_element(5)
+            sage: g = P.random_element((0, 5))
+            sage: q, r = f.quo_rem(g)
+            sage: f == q*g + r
+            True
+
         TESTS::
 
             sage: P.<x> = PolynomialRing(ZZ, sparse=True)
```

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
Changed commit from **[`75026c0`](https://github.com/sagemath/sagetrac-mirror/commit/75026c0d2ab259a01854695c9fdf115c90c5dd8d)** to **[`af97acc`](https://github.com/sagemath/sagetrac-mirror/commit/af97acc4a3e7f5087e56235887a760147636c5bc)**

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
<div id="comment:8"></div>

Branch pushed to git repo; I updated commit sha1. New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/af97acc4a3e7f5087e56235887a760147636c5bc"><code>af97acc</code></a></td><td><code>add another doctest</code></td></tr></table>

**Comment by DaveWitteMorris** [comment]
<div id="comment:9" align="right">comment:9</div>

Yes, that's good, so I made the change (except that I deleted "(after :trac:`34733`)", because this ticket did not need to make any changes in this method).

**Comment by mantepse** [comment]
<div id="comment:10" align="right">comment:10</div>

Looks fine.  If you have time, maybe insert a space after the comma in `q,r`.  Thank you!

**Comment by mantepse** [comment]
Reviewer: **Martin Rubey**

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
Changed commit from **[`af97acc`](https://github.com/sagemath/sagetrac-mirror/commit/af97acc4a3e7f5087e56235887a760147636c5bc)** to **[`b50426f`](https://github.com/sagemath/sagetrac-mirror/commit/b50426fcfe2a979d44de50b0069a9ee2d0eecf8d)**

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
<div id="comment:12"></div>

Branch pushed to git repo; I updated commit sha1 and set ticket back to needs_review. New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/b50426fcfe2a979d44de50b0069a9ee2d0eecf8d"><code>b50426f</code></a></td><td><code>minor spacing improvement</code></td></tr></table>

**Comment by DaveWitteMorris** [comment]
<div id="comment:13" align="right">comment:13</div>

Thanks!  (Yes, the extra space is better.)

**Comment by vbraun** [comment]
Changed branch from **[public/34733](https://github.com/sagemath/sagetrac-mirror/tree/public/34733)** to **[`b50426f`](https://github.com/sagemath/sagetrac-mirror/commit/b50426fcfe2a979d44de50b0069a9ee2d0eecf8d)**
