### ISSUE TITLE
more opportunistic caching of elliptic-curve and point orders

### ISSUE THREAD

**Issue by yyyyx4** [sagemath/sage#34732]
<div id="comment:0"></div>

This is a follow-up to #32786 with the following changes:

- Copy curve orders between domain and codomain for all `EllipticCurveHom` instances of nonzero degree, rather than (previously) just `EllipticCurveIsogeny` objects.
- Copy point orders when pushing a point through an isomorphism.
- Copy point orders when pushing a point through an isogeny of degree coprime to the point order.
- Rearrange some computations in the √élu code (#34303, #34614) to make (better) use of cached orders; in particular, this unbreaks the use of `.set_order()` on the kernel point prior to passing it to `EllipticCurveHom_velusqrt`. [Thanks to Jonathan Komada Eriksen for reporting this last issue.]

CC:  @defeo @JohnCremona @tscrim

Component: **elliptic curves**

Author: **Lorenz Panny**

Branch/Commit: **[`7962944`](https://github.com/sagemath/sagetrac-mirror/commit/79629444afe7ecdaccae023876ead5ec5dcff415)**

Reviewer: **Travis Scrimshaw**

_Issue created by migration from https://trac.sagemath.org/ticket/34732_

**Comment by tscrim** [comment]
Reviewer: **Travis Scrimshaw**

**Comment by tscrim** [comment]
<div id="comment:2" align="right">comment:2</div>

LGTM.

**Comment by vbraun** [comment]
Changed branch from **[public/more_opportunistic_caching_of_curve_and_point_orders](https://github.com/sagemath/sagetrac-mirror/tree/public/more_opportunistic_caching_of_curve_and_point_orders)** to **[`7962944`](https://github.com/sagemath/sagetrac-mirror/commit/79629444afe7ecdaccae023876ead5ec5dcff415)**
