### ISSUE TITLE
tiny details in symbolic min and max

### ISSUE THREAD

**Issue by fchapoton** [sagemath/sage#34738]
<div id="comment:0"></div>

Component: **symbolics**

Author: **Frédéric Chapoton**

Branch/Commit: **[`d097f77`](https://github.com/sagemath/sagetrac-mirror/commit/d097f7769f94889054e7f57e6bcd27654de0a41e)**

Reviewer: **Matthias Koeppe**

_Issue created by migration from https://trac.sagemath.org/ticket/34738_

**Comment by fchapoton** [comment]
Commit: **[`d16faf2`](https://github.com/sagemath/sagetrac-mirror/commit/d16faf2ec7c8ed880cd65469304cb8935559b1e7)**

**Comment by fchapoton** [comment]
Branch: **[u/chapoton/34738](https://github.com/sagemath/sagetrac-mirror/tree/u/chapoton/34738)**

**Comment by fchapoton** [comment]
<div id="comment:1"></div>

New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/d16faf2ec7c8ed880cd65469304cb8935559b1e7"><code>d16faf2</code></a></td><td><code>tiny details in symbolic min and max</code></td></tr></table>

**Comment by mkoeppe** [comment]
<div id="comment:2" align="right">comment:2</div>


```
+Python builtin `\max` and `\min` are not able to deal with variables
```
shouldn't that be 

```
:func:`max`
```
etc. throughout?

**Comment by fchapoton** [comment]
<div id="comment:3" align="right">comment:3</div>

will this link to the python manuals ?

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
<div id="comment:4"></div>

Branch pushed to git repo; I updated commit sha1. New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/d097f7769f94889054e7f57e6bcd27654de0a41e"><code>d097f77</code></a></td><td><code>detail about min and max</code></td></tr></table>

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
Changed commit from **[`d16faf2`](https://github.com/sagemath/sagetrac-mirror/commit/d16faf2ec7c8ed880cd65469304cb8935559b1e7)** to **[`d097f77`](https://github.com/sagemath/sagetrac-mirror/commit/d097f7769f94889054e7f57e6bcd27654de0a41e)**

**Comment by fchapoton** [comment]
<div id="comment:5" align="right">comment:5</div>

done

**Comment by mkoeppe** [comment]
Reviewer: **Matthias Koeppe**

**Comment by vbraun** [comment]
Changed branch from **[u/chapoton/34738](https://github.com/sagemath/sagetrac-mirror/tree/u/chapoton/34738)** to **[`d097f77`](https://github.com/sagemath/sagetrac-mirror/commit/d097f7769f94889054e7f57e6bcd27654de0a41e)**
