### ISSUE TITLE
some details in hyperelliptic_padic_field

### ISSUE THREAD

**Issue by fchapoton** [sagemath/sage#34735]
<div id="comment:0"></div>

Component: **algebraic geometry**

Author: **Frédéric Chapoton**

Branch/Commit: **[`51dfa86`](https://github.com/sagemath/sagetrac-mirror/commit/51dfa8676979bd4e3e373fdbdf9df023a84ca16e)**

Reviewer: **Lorenz Panny**

_Issue created by migration from https://trac.sagemath.org/ticket/34735_

**Comment by fchapoton** [comment]
Branch: **[u/chapoton/34735](https://github.com/sagemath/sagetrac-mirror/tree/u/chapoton/34735)**

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
<div id="comment:2"></div>

Branch pushed to git repo; I updated commit sha1. New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/51dfa8676979bd4e3e373fdbdf9df023a84ca16e"><code>51dfa86</code></a></td><td><code>some details in hyperelliptic_padic_field</code></td></tr></table>

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
Commit: **[`51dfa86`](https://github.com/sagemath/sagetrac-mirror/commit/51dfa8676979bd4e3e373fdbdf9df023a84ca16e)**

**Comment by yyyyx4** [comment]
Reviewer: **Lorenz Panny**

**Comment by vbraun** [comment]
Changed branch from **[u/chapoton/34735](https://github.com/sagemath/sagetrac-mirror/tree/u/chapoton/34735)** to **[`51dfa86`](https://github.com/sagemath/sagetrac-mirror/commit/51dfa8676979bd4e3e373fdbdf9df023a84ca16e)**
