### ISSUE TITLE
modernize super in algebras/ again

### ISSUE THREAD

**Issue by fchapoton** [sagemath/sage#34745]
<div id="comment:0"></div>

using the short syntax super() where possible

CC:  @soehms

Component: **algebra**

Author: **Frédéric Chapoton**

Branch/Commit: **[`6cc5798`](https://github.com/sagemath/sagetrac-mirror/commit/6cc57984e6945c207289e2979f21eeb747843c9e)**

Reviewer: **Kwankyu Lee**

_Issue created by migration from https://trac.sagemath.org/ticket/34745_

**Comment by fchapoton** [comment]
<div id="comment:1"></div>

New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/6cc57984e6945c207289e2979f21eeb747843c9e"><code>6cc5798</code></a></td><td><code>modernize super in algebras</code></td></tr></table>

**Comment by fchapoton** [comment]
Branch: **[u/chapoton/34745](https://github.com/sagemath/sagetrac-mirror/tree/u/chapoton/34745)**

**Comment by fchapoton** [comment]
Commit: **[`6cc5798`](https://github.com/sagemath/sagetrac-mirror/commit/6cc57984e6945c207289e2979f21eeb747843c9e)**

**Comment by kwankyu** [comment]
<div id="comment:3" align="right">comment:3</div>

LGTM.

**Comment by kwankyu** [comment]
Reviewer: **Kwankyu Lee**

**Comment by soehms** [comment]
<div id="comment:4" align="right">comment:4</div>

Sorry for causing this and thanks for doing the work!

**Comment by vbraun** [comment]
Changed branch from **[u/chapoton/34745](https://github.com/sagemath/sagetrac-mirror/tree/u/chapoton/34745)** to **[`6cc5798`](https://github.com/sagemath/sagetrac-mirror/commit/6cc57984e6945c207289e2979f21eeb747843c9e)**
