### ISSUE TITLE
OS X 13: filter out dylib warning

### ISSUE THREAD

**Issue by jhpalmieri** [sagemath/sage#34741]
<div id="comment:0"></div>

With OS X 13 and/or Xcode 14, Sage can produce warnings

```
ld: warning: dylib (/path/to/SAGE_ROOT/local/lib/libec.dylib) was built for newer macOS version (13.0) than being linked (12.3)
```
Let's filter these out when doctesting.

Component: **doctest framework**

Author: **John Palmieri**

Branch/Commit: **[`bcab6e5`](https://github.com/sagemath/sagetrac-mirror/commit/bcab6e59d96411cce472f5cc79ef1d29ae0c42d8)**

Reviewer: **Kwankyu Lee**

_Issue created by migration from https://trac.sagemath.org/ticket/34741_

**Comment by jhpalmieri** [comment]
Branch: **[u/jhpalmieri/newer_osx_warning](https://github.com/sagemath/sagetrac-mirror/tree/u/jhpalmieri/newer_osx_warning)**

**Comment by jhpalmieri** [comment]
Commit: **[`0da93be`](https://github.com/sagemath/sagetrac-mirror/commit/0da93be72bf6457fb26301742449c38b06543285)**

**Comment by jhpalmieri** [comment]
<div id="comment:2"></div>

New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/0da93be72bf6457fb26301742449c38b06543285"><code>0da93be</code></a></td><td><code>trac 34741: suppress warnings about "dylib ... was built for newer macOS ..."</code></td></tr></table>

**Comment by kwankyu** [comment]
<div id="comment:3" align="right">comment:3</div>

Perhaps needs to add a comment mentioning this ticket (at least the ticket number) to explain why the filter was added.

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
<div id="comment:4"></div>

Branch pushed to git repo; I updated commit sha1. New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/bcab6e59d96411cce472f5cc79ef1d29ae0c42d8"><code>bcab6e5</code></a></td><td><code>trac 34741: add comment with ticket reference</code></td></tr></table>

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
Changed commit from **[`0da93be`](https://github.com/sagemath/sagetrac-mirror/commit/0da93be72bf6457fb26301742449c38b06543285)** to **[`bcab6e5`](https://github.com/sagemath/sagetrac-mirror/commit/bcab6e59d96411cce472f5cc79ef1d29ae0c42d8)**

**Comment by jhpalmieri** [comment]
<div id="comment:5" align="right">comment:5</div>

Good idea. Done.

**Comment by kwankyu** [comment]
<div id="comment:6" align="right">comment:6</div>

Thanks. LGTM.

**Comment by kwankyu** [comment]
Reviewer: **Kwankyu Lee**

**Comment by jhpalmieri** [comment]
<div id="comment:7" align="right">comment:7</div>

Thank you!

**Comment by vbraun** [comment]
Changed branch from **[u/jhpalmieri/newer_osx_warning](https://github.com/sagemath/sagetrac-mirror/tree/u/jhpalmieri/newer_osx_warning)** to **[`bcab6e5`](https://github.com/sagemath/sagetrac-mirror/commit/bcab6e59d96411cce472f5cc79ef1d29ae0c42d8)**
