### ISSUE TITLE
Update bliss to 0.77

### ISSUE THREAD

**Issue by mkoeppe** [sagemath/sage#34747]
<div id="comment:0"></div>

Using the fork https://github.com/ds4dm/Bliss

(see https://github.com/mkoeppe/bliss/issues/3)

CC:  @kiwifb

Component: **packages: optional**

Author: **Matthias Koeppe**

Branch/Commit: **[u/mkoeppe/update_bliss_to_0_77](https://github.com/sagemath/sagetrac-mirror/tree/u/mkoeppe/update_bliss_to_0_77) @ [`46dc79b`](https://github.com/sagemath/sagetrac-mirror/commit/46dc79ba9199c38dccc24072db87254873f367fa)**

_Issue created by migration from https://trac.sagemath.org/ticket/34747_

**Comment by mkoeppe** [comment]
Branch: **[u/mkoeppe/update_bliss_to_0_77](https://github.com/sagemath/sagetrac-mirror/tree/u/mkoeppe/update_bliss_to_0_77)**

**Comment by mkoeppe** [comment]
<div id="comment:2"></div>

New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/67c5c841185165078e08896e790f24fd7fa2060a"><code>67c5c84</code></a></td><td><code>build/pkgs/bliss: Update to 0.77+ds4dm</code></td></tr></table>

**Comment by mkoeppe** [comment]
Commit: **[`67c5c84`](https://github.com/sagemath/sagetrac-mirror/commit/67c5c841185165078e08896e790f24fd7fa2060a)**

**Comment by dcoudert** [comment]
<div id="comment:3" align="right">comment:3</div>

I tried on macOS silicon (M1) 12.6.1 and get multiple dockets errors, all 

```
sage -t --warn-long 33.5 --random-seed=322045618648464306013656253226348851101 src/sage/graphs/bliss.pyx
**********************************************************************
File "src/sage/graphs/bliss.pyx", line 413, in sage.graphs.bliss.canonical_form
Failed example:
    from sage.graphs.bliss import canonical_form                  # optional - bliss
Exception raised:
    Traceback (most recent call last):
      File "/Users/dcoudert/sage/src/sage/doctest/forker.py", line 695, in _run
        self.compile_and_execute(example, compiler, test.globs)
      File "/Users/dcoudert/sage/src/sage/doctest/forker.py", line 1093, in compile_and_execute
        exec(compiled, globs)
      File "<doctest sage.graphs.bliss.canonical_form[0]>", line 1, in <module>
        from sage.graphs.bliss import canonical_form                  # optional - bliss
    ImportError: dlopen(/Users/dcoudert/sage/src/sage/graphs/bliss.cpython-310-darwin.so, 0x0002): Library not loaded: '/Users/dcoudert/sage/local/lib/libbliss.2.dylib'
      Referenced from: '/Users/dcoudert/sage/src/sage/graphs/bliss.cpython-310-darwin.so'
      Reason: tried: '/Users/dcoudert/sage/local/lib/libbliss.2.dylib' (no such file), '/usr/local/lib/libbliss.2.dylib' (no such file), '/usr/lib/libbliss.2.dylib' (no such file)
```

I see file `/Users/dcoudert/sage/local/lib/libbliss.a` but not `libbliss.2.dylib`.

**Comment by mkoeppe** [comment]
<div id="comment:4" align="right">comment:4</div>

Thanks for testing! Indeed the shared library seems to be missing; I'll investigate

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
Changed commit from **[`67c5c84`](https://github.com/sagemath/sagetrac-mirror/commit/67c5c841185165078e08896e790f24fd7fa2060a)** to **[`46dc79b`](https://github.com/sagemath/sagetrac-mirror/commit/46dc79ba9199c38dccc24072db87254873f367fa)**

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
<div id="comment:6"></div>

Branch pushed to git repo; I updated commit sha1. New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/46dc79ba9199c38dccc24072db87254873f367fa"><code>46dc79b</code></a></td><td><code>build/pkgs/bliss/spkg-install.in: Use -DBUILD_SHARED_LIBS=ON</code></td></tr></table>

**Comment by mkoeppe** [comment]
<div id="comment:7" align="right">comment:7</div>

Remaining issue on macOS: https://github.com/ds4dm/Bliss/issues/8

**Comment by antonio-rojas** [comment]
<div id="comment:8" align="right">comment:8</div>

Duplicate #33010
