### ISSUE TITLE
Upgrade cmake to 3.24.3, increase minimum system cmake version to 3.11

### ISSUE THREAD

**Issue by mkoeppe** [sagemath/sage#34746]
<div id="comment:0"></div>

scip (#31329) fails to build with the older cmake provided by ubuntu-xenial (https://github.com/scipopt/scip/issues/32)

papilo (#34726) needs at least cmake 3.11.

3.10.x is shipped on ubuntu-bionic, linuxmint-19.

CC:  @dimpase

Component: **packages: standard**

Author: **Matthias Koeppe**

Branch/Commit: **[`96a9e22`](https://github.com/sagemath/sagetrac-mirror/commit/96a9e220680a7a89fa4c4da95382056d727188a9)**

Reviewer: **Dima Pasechnik**

_Issue created by migration from https://trac.sagemath.org/ticket/34746_

**Comment by mkoeppe** [comment]
Branch: **[u/mkoeppe/upgrade_cmake_to_3_24_3__increase_minimum_system_cmake_version_to_3_10](https://github.com/sagemath/sagetrac-mirror/tree/u/mkoeppe/upgrade_cmake_to_3_24_3__increase_minimum_system_cmake_version_to_3_10)**

**Comment by mkoeppe** [comment]
Commit: **[`dce791c`](https://github.com/sagemath/sagetrac-mirror/commit/dce791c7544c32388d34c7bfadaede61e51a1e92)**

**Comment by mkoeppe** [comment]
Author: **Matthias Koeppe**

**Comment by mkoeppe** [comment]
<div id="comment:2"></div>

New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/d18036b4148283139e7c66fb57f92468c0470715"><code>d18036b</code></a></td><td><code>build/pkgs/cmake: Update to 3.24.3</code></td></tr><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/dce791c7544c32388d34c7bfadaede61e51a1e92"><code>dce791c</code></a></td><td><code>build/pkgs/cmake/spkg-configure.m4: Increase minimum version from 3.4 to 3.10 (as found on ubuntu-bionic)</code></td></tr></table>

**Comment by mkoeppe** [comment]
Description changed:
``````diff
--- 
+++ 
@@ -1,4 +1,4 @@
 3.10.x is shipped on ubuntu-bionic, linuxmint-19
 
-scip fails to build with the older cmake provided by ubuntu-xenial (https://github.com/scipopt/scip/issues/32)
+scip (#31329) fails to build with the older cmake provided by ubuntu-xenial (https://github.com/scipopt/scip/issues/32)
 
``````

**Comment by mkoeppe** [comment]
Description changed:
``````diff
--- 
+++ 
@@ -1,4 +1,8 @@
-3.10.x is shipped on ubuntu-bionic, linuxmint-19
-
 scip (#31329) fails to build with the older cmake provided by ubuntu-xenial (https://github.com/scipopt/scip/issues/32)
 
+papilo (#34726) needs at least cmake 3.11.
+
+3.10.x is shipped on ubuntu-bionic, linuxmint-19.
+
+
+
``````

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
Changed commit from **[`dce791c`](https://github.com/sagemath/sagetrac-mirror/commit/dce791c7544c32388d34c7bfadaede61e51a1e92)** to **[`96a9e22`](https://github.com/sagemath/sagetrac-mirror/commit/96a9e220680a7a89fa4c4da95382056d727188a9)**

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
<div id="comment:5"></div>

Branch pushed to git repo; I updated commit sha1. New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/96a9e220680a7a89fa4c4da95382056d727188a9"><code>96a9e22</code></a></td><td><code>build/pkgs/cmake/spkg-configure.m4: Increase minimum version to 3.11</code></td></tr></table>

**Comment by dimpase** [comment]
<div id="comment:6" align="right">comment:6</div>

lgtm

**Comment by dimpase** [comment]
Reviewer: **Dima Pasechnik**

**Comment by mkoeppe** [comment]
<div id="comment:7" align="right">comment:7</div>

Thanks!

**Comment by vbraun** [comment]
Changed branch from **[u/mkoeppe/upgrade_cmake_to_3_24_3__increase_minimum_system_cmake_version_to_3_10](https://github.com/sagemath/sagetrac-mirror/tree/u/mkoeppe/upgrade_cmake_to_3_24_3__increase_minimum_system_cmake_version_to_3_10)** to **[`96a9e22`](https://github.com/sagemath/sagetrac-mirror/commit/96a9e220680a7a89fa4c4da95382056d727188a9)**
