### ISSUE TITLE
dead hyperlinks in developer manual

### ISSUE THREAD

**Issue by DavidAyotte** [sagemath/sage#34740]
<div id="comment:0"></div>

The following section of the developer manual:

https://doc.sagemath.org/html/en/developer/sage_manuals.html

contains multiple reference to a dead link: 

http://sphinx.pocoo.org

Component: **documentation**

Keywords: **hyperlinks**

Author: **David Ayotte**

Branch/Commit: **[`bdc07ac`](https://github.com/sagemath/sagetrac-mirror/commit/bdc07ac7c38417e221ad4ae894010ed302a9b26c)**

Reviewer: **Kwankyu Lee**

_Issue created by migration from https://trac.sagemath.org/ticket/34740_

**Comment by DavidAyotte** [comment]
Description changed:
``````diff
--- 
+++ 
@@ -1,7 +1,8 @@
-The hyperlink for the Sphinx documentation in the section:
+The following section of the developer manual:
 
-https://doc.sagemath.org/html/en/developer/sage_manuals.html#hyperlinks
+https://doc.sagemath.org/html/en/developer/sage_manuals.html
 
-is a dead link: http://sphinx.pocoo.org/markup/inline.html
+contains multiple reference to a dead link: 
 
-Looking at the sphinx documentation, I'm not sure what is the right section one should link to.
+http://sphinx.pocoo.org
+
``````

**Comment by DavidAyotte** [comment]
Branch: **[u/gh-DavidAyotte/sphinx_doc_hyperlink](https://github.com/sagemath/sagetrac-mirror/tree/u/gh-DavidAyotte/sphinx_doc_hyperlink)**

**Comment by DavidAyotte** [comment]
Commit: **[`dabdf89`](https://github.com/sagemath/sagetrac-mirror/commit/dabdf8924269ea9127990a8aeaa15474db8afeee)**

**Comment by DavidAyotte** [comment]
<div id="comment:3"></div>

New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/dabdf8924269ea9127990a8aeaa15474db8afeee"><code>dabdf89</code></a></td><td><code>src/doc/en/developer/sage_manuals.rst: fix dead links</code></td></tr></table>

**Comment by DavidAyotte** [comment]
Author: **David Ayotte**

**Comment by kwankyu** [comment]
<div id="comment:4" align="right">comment:4</div>

It seems that `http://www.sphinx-doc.org/markup/inline.html` can be replaced with `https://www.sphinx-doc.org/en/master/usage/restructuredtext/roles.html`

**Comment by DavidAyotte** [comment]
<div id="comment:5" align="right">comment:5</div>

Replying to [Kwankyu Lee](#comment%3A4):
> It seems that `http://www.sphinx-doc.org/markup/inline.html` can be replaced with `https://www.sphinx-doc.org/en/master/usage/restructuredtext/roles.html`

You're right, this is a better choice. Thanks!

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
Changed commit from **[`dabdf89`](https://github.com/sagemath/sagetrac-mirror/commit/dabdf8924269ea9127990a8aeaa15474db8afeee)** to **[`bdc07ac`](https://github.com/sagemath/sagetrac-mirror/commit/bdc07ac7c38417e221ad4ae894010ed302a9b26c)**

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
<div id="comment:6"></div>

Branch pushed to git repo; I updated commit sha1. New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/bdc07ac7c38417e221ad4ae894010ed302a9b26c"><code>bdc07ac</code></a></td><td><code>src/doc/en/developer/sage_manuals.rst: change hyperlink</code></td></tr></table>

**Comment by kwankyu** [comment]
Reviewer: **Kwankyu Lee**

**Comment by kwankyu** [comment]
<div id="comment:7" align="right">comment:7</div>

Thanks. LGTM.

**Comment by vbraun** [comment]
Changed branch from **[u/gh-DavidAyotte/sphinx_doc_hyperlink](https://github.com/sagemath/sagetrac-mirror/tree/u/gh-DavidAyotte/sphinx_doc_hyperlink)** to **[`bdc07ac`](https://github.com/sagemath/sagetrac-mirror/commit/bdc07ac7c38417e221ad4ae894010ed302a9b26c)**
