### ISSUE TITLE
Optional package soplex (dependency of scip)

### ISSUE THREAD

**Issue by mkoeppe** [sagemath/sage#34742]
<div id="comment:0"></div>

https://github.com/scipopt/soplex

CC:  @dimpase

Component: **packages: optional**

Author: **Matthias Koeppe**

Branch/Commit: **[`dbff7a0`](https://github.com/sagemath/sagetrac-mirror/commit/dbff7a06c737b71e8fb7eda107dd9d6c9f0cd4b5)**

Reviewer: **Dima Pasechnik**

_Issue created by migration from https://trac.sagemath.org/ticket/34742_

**Comment by mkoeppe** [comment]
Branch: **[u/mkoeppe/optional_package_soplex__dependency_of_scip_](https://github.com/sagemath/sagetrac-mirror/tree/u/mkoeppe/optional_package_soplex__dependency_of_scip_)**

**Comment by mkoeppe** [comment]
<div id="comment:2"></div>

New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/e3a05316c193f671a11050d74f5eb61cd1b39186"><code>e3a0531</code></a></td><td><code>build/pkgs/soplex: New</code></td></tr></table>

**Comment by mkoeppe** [comment]
Commit: **[`e3a0531`](https://github.com/sagemath/sagetrac-mirror/commit/e3a05316c193f671a11050d74f5eb61cd1b39186)**

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
<div id="comment:3"></div>

Branch pushed to git repo; I updated commit sha1. This was a forced push. New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/957e657f552310a20d674b10b36bcf867fd06cf2"><code>957e657</code></a></td><td><code>build/pkgs/soplex: New</code></td></tr></table>

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
Changed commit from **[`e3a0531`](https://github.com/sagemath/sagetrac-mirror/commit/e3a05316c193f671a11050d74f5eb61cd1b39186)** to **[`957e657`](https://github.com/sagemath/sagetrac-mirror/commit/957e657f552310a20d674b10b36bcf867fd06cf2)**

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
Changed commit from **[`957e657`](https://github.com/sagemath/sagetrac-mirror/commit/957e657f552310a20d674b10b36bcf867fd06cf2)** to **[`19614bc`](https://github.com/sagemath/sagetrac-mirror/commit/19614bc8b98978f4eb351d9990b2104ffb4677c2)**

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
<div id="comment:4"></div>

Branch pushed to git repo; I updated commit sha1. This was a forced push. New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/19614bc8b98978f4eb351d9990b2104ffb4677c2"><code>19614bc</code></a></td><td><code>build/pkgs/soplex: New</code></td></tr></table>

**Comment by mkoeppe** [comment]
Reviewer: **https://github.com/mkoeppe/sage/actions/runs/3448901075**

**Comment by mkoeppe** [comment]
<div id="comment:6" align="right">comment:6</div>

On macOS, install_name is broken

```
$ otool -L /Users/mkoeppe/s/sage/sage-rebasing/worktree-rebase/local/lib/libsoplexshared.dylib                                                                          git:t/21003/pyscipopt
/Users/mkoeppe/s/sage/sage-rebasing/worktree-rebase/local/lib/libsoplexshared.dylib:
	libsoplexshared.6.0.dylib (compatibility version 6.0.0, current version 6.0.2)
	/usr/lib/libz.1.dylib (compatibility version 1.0.0, current version 1.2.11)
	/usr/local/opt/gmp/lib/libgmp.10.dylib (compatibility version 15.0.0, current version 15.1.0)
	/usr/local/opt/gmp/lib/libgmpxx.4.dylib (compatibility version 11.0.0, current version 11.1.0)
	/usr/local/opt/mpfr/lib/libmpfr.6.dylib (compatibility version 8.0.0, current version 8.0.0)
	/usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 1300.23.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1311.100.3)
```

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
<div id="comment:7"></div>

Branch pushed to git repo; I updated commit sha1. New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/dbff7a06c737b71e8fb7eda107dd9d6c9f0cd4b5"><code>dbff7a0</code></a></td><td><code>build/pkgs/soplex: Fix install_name on macOS</code></td></tr></table>

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
Changed commit from **[`19614bc`](https://github.com/sagemath/sagetrac-mirror/commit/19614bc8b98978f4eb351d9990b2104ffb4677c2)** to **[`dbff7a0`](https://github.com/sagemath/sagetrac-mirror/commit/dbff7a06c737b71e8fb7eda107dd9d6c9f0cd4b5)**

**Comment by dimpase** [comment]
<div id="comment:9" align="right">comment:9</div>

lgtm

**Comment by dimpase** [comment]
Changed reviewer from **https://github.com/mkoeppe/sage/actions/runs/3448901075** to **Dima Pasechnik**

**Comment by mkoeppe** [comment]
<div id="comment:10" align="right">comment:10</div>

Thank you

**Comment by dcoudert** [comment]
<div id="comment:11" align="right">comment:11</div>

The patchbot reports an error when trying to build the doc

```
[sagemath_doc_html-none] [spkg     ] /home/sagemath/sage/src/doc/en/reference/spkg/soplex.rst: WARNING: document isn't included in any toctree
[sagemath_doc_html-none] [spkg     ] The inventory files are in ../../local/share/doc/sage/inventory/en/reference/spkg.
[sagemath_doc_html-none] Error building the documentation.
[sagemath_doc_html-none] Traceback (most recent call last):
[sagemath_doc_html-none]   File "/home/sagemath/sage/local/var/lib/sage/venv-python3.10.8/lib/python3.10/runpy.py", line 196, in _run_module_as_main
[sagemath_doc_html-none]     return _run_code(code, main_globals, None,
[sagemath_doc_html-none]   File "/home/sagemath/sage/local/var/lib/sage/venv-python3.10.8/lib/python3.10/runpy.py", line 86, in _run_code
[sagemath_doc_html-none]     exec(code, run_globals)
[sagemath_doc_html-none]   File "/home/sagemath/sage/pkgs/sage-docbuild/sage_docbuild/__main__.py", line 498, in <module>
[sagemath_doc_html-none]     sys.exit(main())
[sagemath_doc_html-none]   File "/home/sagemath/sage/pkgs/sage-docbuild/sage_docbuild/__main__.py", line 495, in main
[sagemath_doc_html-none]     builder()
[sagemath_doc_html-none]   File "/home/sagemath/sage/pkgs/sage-docbuild/sage_docbuild/builders.py", line 819, in _wrapper
[sagemath_doc_html-none]     getattr(DocBuilder, build_type)(self, *args, **kwds)
[sagemath_doc_html-none]   File "/home/sagemath/sage/pkgs/sage-docbuild/sage_docbuild/builders.py", line 163, in f
[sagemath_doc_html-none]     runsphinx()
[sagemath_doc_html-none]   File "/home/sagemath/sage/pkgs/sage-docbuild/sage_docbuild/sphinxbuild.py", line 327, in runsphinx
[sagemath_doc_html-none]     sys.stderr.raise_errors()
[sagemath_doc_html-none]   File "/home/sagemath/sage/pkgs/sage-docbuild/sage_docbuild/sphinxbuild.py", line 263, in raise_errors
[sagemath_doc_html-none]     raise OSError(self._error)
[sagemath_doc_html-none] OSError: /home/sagemath/sage/src/doc/en/reference/spkg/soplex.rst: WARNING: document isn't included in any toctree
[sagemath_doc_html-none] 
[sagemath_doc_html-none]     Note: incremental documentation builds sometimes cause spurious
[sagemath_doc_html-none]     error messages. To be certain that these are real errors, run
[sagemath_doc_html-none]     "make doc-clean doc-uninstall" first and try again.
[sagemath_doc_html-none] make[4]: *** [Makefile:28: doc-inventory--reference-spkg] Error 1
[sagemath_doc_html-none] make[4]: *** Waiting for unfinished jobs....
[sagemath_doc_html-none] [algebras ] The inventory files are in ../../local/share/doc/sage/inventory/en/reference/algebras.
[sagemath_doc_html-none] Build finished. The built documents can be found in /home/sagemath/sage/local/share/doc/sage/inventory/en/reference/algebras
[sagemath_doc_html-none] [manifolds] The inventory files are in ../../local/share/doc/sage/inventory/en/reference/manifolds.
[sagemath_doc_html-none] Build finished. The built documents can be found in /home/sagemath/sage/local/share/doc/sage/inventory/en/reference/manifolds
[sagemath_doc_html-none] make[3]: *** [Makefile:45: doc-inventory-reference] Error 2
make[2]: *** [Makefile:3228: sagemath_doc_html-SAGE_DOCS-no-deps] Error 2
make[1]: *** [Makefile:3228: /home/sagemath/sage/local/var/lib/sage/installed/sagemath_doc_html-none] Error 2
make[1]: Leaving directory '/home/sagemath/sage/build/make'
```

**Comment by dimpase** [comment]
<div id="comment:12" align="right">comment:12</div>

incremental rebuild of docs can't cope with a new document added, maybe?

**Comment by dcoudert** [comment]
<div id="comment:13" align="right">comment:13</div>

Right, but the patchbot compiles from scratch, no ?

**Comment by vbraun** [comment]
Changed branch from **[u/mkoeppe/optional_package_soplex__dependency_of_scip_](https://github.com/sagemath/sagetrac-mirror/tree/u/mkoeppe/optional_package_soplex__dependency_of_scip_)** to **[`dbff7a0`](https://github.com/sagemath/sagetrac-mirror/commit/dbff7a06c737b71e8fb7eda107dd9d6c9f0cd4b5)**
