### ISSUE TITLE
Update sage tutorial

### ISSUE THREAD

**Issue by kwankyu** [sagemath/sage#34751]
<div id="comment:0"></div>

Component: **documentation**

Author: **Kwankyu Lee**

Branch/Commit: **[`bb42d88`](https://github.com/sagemath/sagetrac-mirror/commit/bb42d889e2647edbe74dd3598d0dd5aafc9a97fe)**

Reviewer: **Eric Gourgoulhon**

_Issue created by migration from https://trac.sagemath.org/ticket/34751_

**Comment by kwankyu** [comment]
Branch: **[u/klee/update_sage_tutorial](https://github.com/sagemath/sagetrac-mirror/tree/u/klee/update_sage_tutorial)**

**Comment by kwankyu** [comment]
Commit: **[`1de3116`](https://github.com/sagemath/sagetrac-mirror/commit/1de311622a6412f45a2232ae4a51e9d13c75b464)**

**Comment by kwankyu** [comment]
<div id="comment:2"></div>

New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/1de311622a6412f45a2232ae4a51e9d13c75b464"><code>1de3116</code></a></td><td><code>Remove old materials from tutorial</code></td></tr></table>

**Comment by kwankyu** [comment]
Author: **Kwankyu Lee**

**Comment by egourgoulhon** [comment]
Reviewer: **Eric Gourgoulhon**

**Comment by egourgoulhon** [comment]
<div id="comment:3" align="right">comment:3</div>

LGTM. Thank you!

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
<div id="comment:4"></div>

Branch pushed to git repo; I updated commit sha1 and set ticket back to needs_review. New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/bb42d889e2647edbe74dd3598d0dd5aafc9a97fe"><code>bb42d88</code></a></td><td><code>A tiny fix for a glaring error</code></td></tr></table>

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
Changed commit from **[`1de3116`](https://github.com/sagemath/sagetrac-mirror/commit/1de311622a6412f45a2232ae4a51e9d13c75b464)** to **[`bb42d88`](https://github.com/sagemath/sagetrac-mirror/commit/bb42d889e2647edbe74dd3598d0dd5aafc9a97fe)**

**Comment by kwankyu** [comment]
<div id="comment:5" align="right">comment:5</div>

I was going to check the built doc, but you moved quicker than me :) I just checked the doc, and found no error fortunately.

Anyway, thanks!

PS: I made a small edit.

---
New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/bb42d889e2647edbe74dd3598d0dd5aafc9a97fe"><code>bb42d88</code></a></td><td><code>A tiny fix for a glaring error</code></td></tr></table>

**Comment by egourgoulhon** [comment]
<div id="comment:7" align="right">comment:7</div>

Replying to [Kwankyu Lee](#comment%3A5):
> 
> PS: I made a small edit.
> 

Thanks for the correction!

**Comment by vbraun** [comment]
Changed branch from **[u/klee/update_sage_tutorial](https://github.com/sagemath/sagetrac-mirror/tree/u/klee/update_sage_tutorial)** to **[`bb42d88`](https://github.com/sagemath/sagetrac-mirror/commit/bb42d889e2647edbe74dd3598d0dd5aafc9a97fe)**
