### ISSUE TITLE
some details in filtered simplicial complexes

### ISSUE THREAD

**Issue by fchapoton** [sagemath/sage#34759]
<div id="comment:0"></div>

- some pep8 changes
- fix details in documentation

CC:  @jhpalmieri

Component: **algebraic topology**

Author: **Frédéric Chapoton**

Branch/Commit: **[`71cc4e9`](https://github.com/sagemath/sagetrac-mirror/commit/71cc4e960313234d61cd58ef57eec73f6b3e87b6)**

Reviewer: **John Palmieri**

_Issue created by migration from https://trac.sagemath.org/ticket/34759_

**Comment by fchapoton** [comment]
<div id="comment:1"></div>

New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/2dcf70c25eadc1af982ef53c836bd47e88c3b343"><code>2dcf70c</code></a></td><td><code>some details in filtered simplicial complexes</code></td></tr></table>

**Comment by fchapoton** [comment]
Commit: **[`2dcf70c`](https://github.com/sagemath/sagetrac-mirror/commit/2dcf70c25eadc1af982ef53c836bd47e88c3b343)**

**Comment by fchapoton** [comment]
Branch: **[u/chapoton/34759](https://github.com/sagemath/sagetrac-mirror/tree/u/chapoton/34759)**

**Comment by mkoeppe** [comment]
<div id="comment:2" align="right">comment:2</div>


```
@@ -491,7 +492,7 @@ class FilteredSimplicialComplex(SageObject):
         Add a new interval (i.e. homology element).
 
         This method should not be called by users, it is used in
-        the ``_compute_persistence`` method. The simplex of
+        the ``_persistent_homology`` method. The simplex of
         death may be ``None``, in which case the interval is infinite.
```
Shouldn't this use

```
:meth:`_persistent_homology`
```

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
<div id="comment:3"></div>

Branch pushed to git repo; I updated commit sha1. New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/71cc4e960313234d61cd58ef57eec73f6b3e87b6"><code>71cc4e9</code></a></td><td><code>adding some :meth: links</code></td></tr></table>

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
Changed commit from **[`2dcf70c`](https://github.com/sagemath/sagetrac-mirror/commit/2dcf70c25eadc1af982ef53c836bd47e88c3b343)** to **[`71cc4e9`](https://github.com/sagemath/sagetrac-mirror/commit/71cc4e960313234d61cd58ef57eec73f6b3e87b6)**

**Comment by fchapoton** [comment]
<div id="comment:4" align="right">comment:4</div>

done, thx

**Comment by jhpalmieri** [comment]
Reviewer: **John Palmieri**

**Comment by jhpalmieri** [comment]
<div id="comment:6" align="right">comment:6</div>

Looks good to me.

**Comment by vbraun** [comment]
Changed branch from **[u/chapoton/34759](https://github.com/sagemath/sagetrac-mirror/tree/u/chapoton/34759)** to **[`71cc4e9`](https://github.com/sagemath/sagetrac-mirror/commit/71cc4e960313234d61cd58ef57eec73f6b3e87b6)**
