### ISSUE TITLE
Remove module-level imports from sage.plot

### ISSUE THREAD

**Issue by mkoeppe** [sagemath/sage#34754]
<div id="comment:0"></div>

... so that modularized distributions do not have to depend on matplotlib.

Component: **refactoring**

Author: **Matthias Koeppe**

Branch/Commit: **[`b50cd0b`](https://github.com/sagemath/sagetrac-mirror/commit/b50cd0b9b9fd1fb26e248669edc02a8fb2bf6150)**

Reviewer: **Dima Pasechnik**

_Issue created by migration from https://trac.sagemath.org/ticket/34754_

**Comment by mkoeppe** [comment]
Branch: **[u/mkoeppe/remove_module_level_imports_from_sage_plot](https://github.com/sagemath/sagetrac-mirror/tree/u/mkoeppe/remove_module_level_imports_from_sage_plot)**

**Comment by mkoeppe** [comment]
<div id="comment:2"></div>

New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/b50cd0b9b9fd1fb26e248669edc02a8fb2bf6150"><code>b50cd0b</code></a></td><td><code>Remove module-level imports from sage.plot</code></td></tr></table>

**Comment by mkoeppe** [comment]
Commit: **[`b50cd0b`](https://github.com/sagemath/sagetrac-mirror/commit/b50cd0b9b9fd1fb26e248669edc02a8fb2bf6150)**

**Comment by dimpase** [comment]
Reviewer: **Dima Pasechnik**

**Comment by mkoeppe** [comment]
<div id="comment:4" align="right">comment:4</div>

This doctest failure is unrelated

```
sage -t --random-seed=104608529635632774879741932645446645768 sage/interfaces/expect.py  # 2 doctests failed
```

**Comment by dimpase** [comment]
<div id="comment:5" align="right">comment:5</div>

lgtm

**Comment by mkoeppe** [comment]
<div id="comment:6" align="right">comment:6</div>

Thanks!

**Comment by vbraun** [comment]
Changed branch from **[u/mkoeppe/remove_module_level_imports_from_sage_plot](https://github.com/sagemath/sagetrac-mirror/tree/u/mkoeppe/remove_module_level_imports_from_sage_plot)** to **[`b50cd0b`](https://github.com/sagemath/sagetrac-mirror/commit/b50cd0b9b9fd1fb26e248669edc02a8fb2bf6150)**
