### ISSUE TITLE
add _repr_svg_ for Dyck words

### ISSUE THREAD

**Issue by fchapoton** [sagemath/sage#34755]
<div id="comment:0"></div>

to be displayed using Jupyter

CC:  @VivianePons @slel @nthiery @tscrim

Component: **combinatorics**

Author: **Frédéric Chapoton**

Branch/Commit: **[`90278a7`](https://github.com/sagemath/sagetrac-mirror/commit/90278a789175f4c204cd0f6861cfe795aad10b18)**

Reviewer: **Travis Scrimshaw**

_Issue created by migration from https://trac.sagemath.org/ticket/34755_

**Comment by fchapoton** [comment]
Commit: **[`90278a7`](https://github.com/sagemath/sagetrac-mirror/commit/90278a789175f4c204cd0f6861cfe795aad10b18)**

**Comment by fchapoton** [comment]
Branch: **[u/chapoton/34755](https://github.com/sagemath/sagetrac-mirror/tree/u/chapoton/34755)**

**Comment by fchapoton** [comment]
<div id="comment:1"></div>

New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/90278a789175f4c204cd0f6861cfe795aad10b18"><code>90278a7</code></a></td><td><code>_repr_svg_ for Dyck words</code></td></tr></table>

**Comment by fchapoton** [comment]
<div id="comment:2" align="right">comment:2</div>

needs review, should be an easy one, please

**Comment by tscrim** [comment]
<div id="comment:4" align="right">comment:4</div>

LGTM.

Bit of a side note: I am wondering if we really want the default to be the svg output. In particular, the output behavior changes radically for a single element versus a list. Anyways, just some musings.

**Comment by tscrim** [comment]
Reviewer: **Travis Scrimshaw**

**Comment by vbraun** [comment]
Changed branch from **[u/chapoton/34755](https://github.com/sagemath/sagetrac-mirror/tree/u/chapoton/34755)** to **[`90278a7`](https://github.com/sagemath/sagetrac-mirror/commit/90278a789175f4c204cd0f6861cfe795aad10b18)**
