### ISSUE TITLE
fix all W391 in pyx files

### ISSUE THREAD

**Issue by fchapoton** [sagemath/sage#34753]
<div id="comment:0"></div>

namely, no empty final lines

already done for py files, and will be added to the linter later

Component: **refactoring**

Author: **Frédéric Chapoton**

Branch/Commit: **[`cd0e58d`](https://github.com/sagemath/sagetrac-mirror/commit/cd0e58d4febe84d3d9b9d4472b26ecc179b1b53b)**

Reviewer: **Matthias Koeppe**

_Issue created by migration from https://trac.sagemath.org/ticket/34753_

**Comment by fchapoton** [comment]
Branch: **[u/chapoton/34753](https://github.com/sagemath/sagetrac-mirror/tree/u/chapoton/34753)**

**Comment by fchapoton** [comment]
<div id="comment:1"></div>

New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/cd0e58d4febe84d3d9b9d4472b26ecc179b1b53b"><code>cd0e58d</code></a></td><td><code>fix W391 in pyx files (no empty final lines)</code></td></tr></table>

**Comment by fchapoton** [comment]
Commit: **[`cd0e58d`](https://github.com/sagemath/sagetrac-mirror/commit/cd0e58d4febe84d3d9b9d4472b26ecc179b1b53b)**

**Comment by mkoeppe** [comment]
Reviewer: **Matthias Koeppe**

**Comment by vbraun** [comment]
Changed branch from **[u/chapoton/34753](https://github.com/sagemath/sagetrac-mirror/tree/u/chapoton/34753)** to **[`cd0e58d`](https://github.com/sagemath/sagetrac-mirror/commit/cd0e58d4febe84d3d9b9d4472b26ecc179b1b53b)**
