### ISSUE TITLE
latex of empty SkewPartition is broken

### ISSUE THREAD

**Issue by mantepse** [sagemath/sage#34760]
<div id="comment:0"></div>

```
sage: p = SkewPartition([[],[]])
sage: latex(p)
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
Input In [9], in <cell line: 1>()
----> 1 latex(p)

File ~/sage-develop/src/sage/misc/latex.py:929, in LatexCall.__call__(self, x, combine_all)
    898 r"""
    899 Return a :class:`LatexExpr` built out of the argument ``x``.
    900 
   (...)
    926     x 2
    927 """
    928 if has_latex_attr(x):
--> 929     return LatexExpr(x._latex_())
    930 try:
    931     f = latex_table[type(x)]

File ~/sage-develop/src/sage/combinat/skew_partition.py:254, in SkewPartition._latex_(self)
    235 def _latex_(self):
    236     r"""
    237     Return a `\LaTeX` representation of ``self``.
    238 
   (...)
    252         }
    253     """
--> 254     return self.parent().options._dispatch(self, '_latex_', 'latex')

File ~/sage-develop/src/sage/structure/global_options.py:1690, in GlobalOptions._dispatch(self, obj, dispatch_to, option, *args, **kargs)
   1688         dispatch_to = dispatch_to[:-1]
   1689     dispatch = getattr(obj, dispatch_to + '_' + self._value[option])
-> 1690     return dispatch(*args, **kargs)
   1692 raise ValueError('%s is not a dispatchable option!' % option)

File ~/sage-develop/src/sage/combinat/skew_partition.py:306, in SkewPartition._latex_young_diagram(self)
    304     for j in range(skew_size):
    305         arr[i][j] = None
--> 306 return tex_from_array(arr)

File ~/sage-develop/src/sage/combinat/output.py:175, in tex_from_array(array, with_lines)
    173 lr=lr_macro.substitute(bar='|' if with_lines else '')
    174 if Tableaux.options.convention == "English":
--> 175     return '{%s\n%s\n}' % (lr, tex_from_skew_array(array, with_lines))
    176 else:
    177     return '{%s\n%s\n}' % (lr, tex_from_skew_array(array[::-1], with_lines, align='t'))

File ~/sage-develop/src/sage/combinat/output.py:309, in tex_from_skew_array(array, with_lines, align)
    306     end_line=lambda r: r'\\'
    308 # now we draw the array
--> 309 tex=r'\raisebox{-.6ex}{$\begin{array}[%s]{*{%s}c}'%(align,max(map(len,array)))
    310 tex+=end_line(0)+'\n'
    311 for r in range(len(array)):

ValueError: max() arg is an empty sequence
```

CC:  @stumpc5

Component: **combinatorics**

Keywords: **findstat**

Author: **Martin Rubey**

Branch/Commit: **[`249ce49`](https://github.com/sagemath/sagetrac-mirror/commit/249ce49000a0beb73a5fe1ed51b43963adb1f01a)**

Reviewer: **Christian Stump**

_Issue created by migration from https://trac.sagemath.org/ticket/34760_

**Comment by mantepse** [comment]
<div id="comment:1" align="right">comment:1</div>

The findstat keyword refers to the fact that this bug was "discovered" by findstat.

**Comment by mantepse** [comment]
Branch: **[u/mantepse/latex_of_empty_skewpartition_is_broken](https://github.com/sagemath/sagetrac-mirror/tree/u/mantepse/latex_of_empty_skewpartition_is_broken)**

**Comment by mantepse** [comment]
Commit: **[`249ce49`](https://github.com/sagemath/sagetrac-mirror/commit/249ce49000a0beb73a5fe1ed51b43963adb1f01a)**

**Comment by mantepse** [comment]
Author: **Martin Rubey**

**Comment by mantepse** [comment]
<div id="comment:3"></div>

New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/249ce49000a0beb73a5fe1ed51b43963adb1f01a"><code>249ce49</code></a></td><td><code>fix latex for empty skew partitions</code></td></tr></table>

**Comment by DaveWitteMorris** [comment]
<div id="comment:4" align="right">comment:4</div>

Should this ticket be expanded to also fix the latex of other empty skew partitions? For example:

```
sage: latex(SkewPartition([[2],[2]]))
{\def\lr#1{\multicolumn{1}{|@{\hspace{.6ex}}c@{\hspace{.6ex}}|}{\raisebox{-.3ex}{$#1$}}}
\raisebox{-.6ex}{$\begin{array}[b]{*{2}c}\cline{3-2}
&\\
\end{array}$}
}
```
Sage does not give an error, but the output gives an error when it is put into latex:

```
Extra alignment tab has been changed to \cr.
<template> \endtemplate
l.8 \end{array}$}
```

**Comment by mantepse** [comment]
<div id="comment:5" align="right">comment:5</div>

Should we have

```
sage: SkewPartition([[],[]]) == SkewPartition([[3],[3]])
False
```
?

**Comment by mantepse** [comment]
<div id="comment:6" align="right">comment:6</div>

The documentation mentions empty rows.  The iterator only produces reduced skew partitions (i.e., no empty rows), but we do have

```
sage: SkewPartition([[3],[3]]) in SkewPartitions()
True
```

**Comment by mantepse** [comment]
<div id="comment:7" align="right">comment:7</div>

Since FindStat depends on this and `_unicode_art_` does not allow empty rows either, I would prefer to discuss this issue in a separate ticket.

**Comment by mantepse** [comment]
<div id="comment:8" align="right">comment:8</div>

ping?

**Comment by stumpc5** [comment]
<div id="comment:9" align="right">comment:9</div>

looks good to me

**Comment by mkoeppe** [comment]
Reviewer: **Christian Stump**

**Comment by vbraun** [comment]
Changed branch from **[u/mantepse/latex_of_empty_skewpartition_is_broken](https://github.com/sagemath/sagetrac-mirror/tree/u/mantepse/latex_of_empty_skewpartition_is_broken)** to **[`249ce49`](https://github.com/sagemath/sagetrac-mirror/commit/249ce49000a0beb73a5fe1ed51b43963adb1f01a)**
