### ISSUE TITLE
Fix random chain complex doctest

### ISSUE THREAD

**Issue by jhpalmieri** [sagemath/sage#34762]
<div id="comment:0"></div>

As reported in [#32544 comment:36](https://github.com/sagemath/sage/issues/32544#comment:36).

Component: **algebraic topology**

Author: **John Palmieri**

Branch/Commit: **[`89fdaf3`](https://github.com/sagemath/sagetrac-mirror/commit/89fdaf3944146a50f92bb12e60120b7d56313344)**

Reviewer: **Frédéric Chapoton**

_Issue created by migration from https://trac.sagemath.org/ticket/34762_

**Comment by jhpalmieri** [comment]
Branch: **[u/jhpalmieri/random-chain-complex-test](https://github.com/sagemath/sagetrac-mirror/tree/u/jhpalmieri/random-chain-complex-test)**

**Comment by jhpalmieri** [comment]
Commit: **[`89fdaf3`](https://github.com/sagemath/sagetrac-mirror/commit/89fdaf3944146a50f92bb12e60120b7d56313344)**

**Comment by jhpalmieri** [comment]
<div id="comment:2"></div>

New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/89fdaf3944146a50f92bb12e60120b7d56313344"><code>89fdaf3</code></a></td><td><code>trac 34762: fix doctest with random chain complexes</code></td></tr></table>

**Comment by fchapoton** [comment]
Reviewer: **Frédéric Chapoton**

**Comment by fchapoton** [comment]
<div id="comment:3" align="right">comment:3</div>

ok, thanks

**Comment by vbraun** [comment]
Changed branch from **[u/jhpalmieri/random-chain-complex-test](https://github.com/sagemath/sagetrac-mirror/tree/u/jhpalmieri/random-chain-complex-test)** to **[`89fdaf3`](https://github.com/sagemath/sagetrac-mirror/commit/89fdaf3944146a50f92bb12e60120b7d56313344)**
