### ISSUE TITLE
Remove src/sage/libs/fes.pyx

### ISSUE THREAD

**Issue by mkoeppe** [sagemath/sage#34761]
<div id="comment:0"></div>

We don't have `fes` as a package. It was an old-style package.

It exists in Fedora (https://repology.org/project/fes/versions) but upstream is defunct.

CC:  @kiwifb @jhpalmieri

Component: **refactoring**

Author: **Matthias Koeppe**

Branch/Commit: **[`1ecd042`](https://github.com/sagemath/sagetrac-mirror/commit/1ecd04267fc16a0e6b7b9c8763cd9ac6bb37f5d8)**

Reviewer: **John Palmieri**

_Issue created by migration from https://trac.sagemath.org/ticket/34761_

**Comment by mkoeppe** [comment]
Branch: **[u/mkoeppe/remove_src_sage_libs_fes_pyx](https://github.com/sagemath/sagetrac-mirror/tree/u/mkoeppe/remove_src_sage_libs_fes_pyx)**

**Comment by mkoeppe** [comment]
Commit: **[`444d3f3`](https://github.com/sagemath/sagetrac-mirror/commit/444d3f3f581a0f1cb2f3497664ffb46405182024)**

**Comment by mkoeppe** [comment]
Description changed:
``````diff
--- 
+++ 
@@ -1,2 +1,3 @@
 We don't have `fes` as a package. It was an old-style package.
 
+It exists in Fedora (https://repology.org/project/fes/versions) but upstream is defunct.
``````

**Comment by mkoeppe** [comment]
Author: **Matthias Koeppe**

**Comment by mkoeppe** [comment]
<div id="comment:2"></div>

New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/444d3f3f581a0f1cb2f3497664ffb46405182024"><code>444d3f3</code></a></td><td><code>src/sage/libs/fes.pyx: Remove</code></td></tr></table>

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
<div id="comment:3"></div>

Branch pushed to git repo; I updated commit sha1. New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/e7c8026920c146b96a2c2999139eded1825b3110"><code>e7c8026</code></a></td><td><code>src/sage/rings/polynomial/multi_polynomial_sequence.py: Remove use of fes</code></td></tr><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/8ed33a0492230c83d2a7c01d19908c2a8e2d43b0"><code>8ed33a0</code></a></td><td><code>src/doc/en/reference/libs/index.rst: Remove fes</code></td></tr></table>

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
Changed commit from **[`444d3f3`](https://github.com/sagemath/sagetrac-mirror/commit/444d3f3f581a0f1cb2f3497664ffb46405182024)** to **[`8ed33a0`](https://github.com/sagemath/sagetrac-mirror/commit/8ed33a0492230c83d2a7c01d19908c2a8e2d43b0)**

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
Changed commit from **[`8ed33a0`](https://github.com/sagemath/sagetrac-mirror/commit/8ed33a0492230c83d2a7c01d19908c2a8e2d43b0)** to **[`1ecd042`](https://github.com/sagemath/sagetrac-mirror/commit/1ecd04267fc16a0e6b7b9c8763cd9ac6bb37f5d8)**

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
<div id="comment:4"></div>

Branch pushed to git repo; I updated commit sha1. This was a forced push. New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/1ecd04267fc16a0e6b7b9c8763cd9ac6bb37f5d8"><code>1ecd042</code></a></td><td><code>src/doc/en/reference/libs/index.rst: Remove fes</code></td></tr></table>

**Comment by jhpalmieri** [comment]
<div id="comment:5" align="right">comment:5</div>

Is https://github.com/cbouilla/libfes-lite any use? Or should we just say, if someone wants to incorporate it, they can start from scratch or revive the deleted file?

**Comment by mkoeppe** [comment]
<div id="comment:6" align="right">comment:6</div>

I don't know anything about this library other than that it has not been available in Sage for a long time now and nobody seems to have missed it.

**Comment by jhpalmieri** [comment]
<div id="comment:7" align="right">comment:7</div>

Okay, let's remove it.

**Comment by jhpalmieri** [comment]
Reviewer: **John Palmieri**

**Comment by mkoeppe** [comment]
<div id="comment:8" align="right">comment:8</div>

Thanks! This will simplify #34346.

**Comment by vbraun** [comment]
Changed branch from **[u/mkoeppe/remove_src_sage_libs_fes_pyx](https://github.com/sagemath/sagetrac-mirror/tree/u/mkoeppe/remove_src_sage_libs_fes_pyx)** to **[`1ecd042`](https://github.com/sagemath/sagetrac-mirror/commit/1ecd04267fc16a0e6b7b9c8763cd9ac6bb37f5d8)**
