### ISSUE TITLE
GH Actions: Update actions

### ISSUE THREAD

**Issue by mkoeppe** [sagemath/sage#34766]
<div id="comment:0"></div>

- in particular upgrade to `actions/upload-artifact@v3` as the v2 version emits a warning about node 12

Component: **porting**

Author: **Matthias Koeppe**

Branch/Commit: **[`bd193c4`](https://github.com/sagemath/sagetrac-mirror/commit/bd193c4f4f1d1440559ed3aab8fd9189a094fd7e)**

Reviewer: **Kwankyu Lee**

_Issue created by migration from https://trac.sagemath.org/ticket/34766_

**Comment by mkoeppe** [comment]
Branch: **[u/mkoeppe/gh_actions__update_actions](https://github.com/sagemath/sagetrac-mirror/tree/u/mkoeppe/gh_actions__update_actions)**

**Comment by mkoeppe** [comment]
<div id="comment:2"></div>

New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/bd193c4f4f1d1440559ed3aab8fd9189a094fd7e"><code>bd193c4</code></a></td><td><code>.github/workflows: Update actions</code></td></tr></table>

**Comment by mkoeppe** [comment]
Commit: **[`bd193c4`](https://github.com/sagemath/sagetrac-mirror/commit/bd193c4f4f1d1440559ed3aab8fd9189a094fd7e)**

**Comment by mkoeppe** [comment]
Author: **Matthias Koeppe**

**Comment by mkoeppe** [comment]
Reviewer: **https://github.com/mkoeppe/sage/actions/runs/3519527763**

**Comment by kwankyu** [comment]
<div id="comment:3" align="right">comment:3</div>

Okay.

**Comment by kwankyu** [comment]
Changed reviewer from **https://github.com/mkoeppe/sage/actions/runs/3519527763** to **Kwankyu Lee**

**Comment by mkoeppe** [comment]
<div id="comment:4" align="right">comment:4</div>

Thanks!

**Comment by vbraun** [comment]
Changed branch from **[u/mkoeppe/gh_actions__update_actions](https://github.com/sagemath/sagetrac-mirror/tree/u/mkoeppe/gh_actions__update_actions)** to **[`bd193c4`](https://github.com/sagemath/sagetrac-mirror/commit/bd193c4f4f1d1440559ed3aab8fd9189a094fd7e)**
