### ISSUE TITLE
Implement _latex_ method for (quasi)modular forms ring elements

### ISSUE THREAD

**Issue by DavidAyotte** [sagemath/sage#34767]
<div id="comment:0"></div>

CC:  @videlec

Component: **modular forms**

Author: **David Ayotte**

Branch/Commit: **[u/gh-DavidAyotte/latex_quasimodforms](https://github.com/sagemath/sagetrac-mirror/tree/u/gh-DavidAyotte/latex_quasimodforms) @ [`03ab6c6`](https://github.com/sagemath/sagetrac-mirror/commit/03ab6c624ee5b8c4beb3a1caf7784773cc7e2453)**

Reviewer: **Travis Scrimshaw**

_Issue created by migration from https://trac.sagemath.org/ticket/34767_

**Comment by DavidAyotte** [comment]
Branch: **[u/gh-DavidAyotte/latex_quasimodforms](https://github.com/sagemath/sagetrac-mirror/tree/u/gh-DavidAyotte/latex_quasimodforms)**

**Comment by DavidAyotte** [comment]
Commit: **[`03ab6c6`](https://github.com/sagemath/sagetrac-mirror/commit/03ab6c624ee5b8c4beb3a1caf7784773cc7e2453)**

**Comment by DavidAyotte** [comment]
<div id="comment:2"></div>

New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/ab1b39d59164973205142819f4e8e961ce61b928"><code>ab1b39d</code></a></td><td><code>src/sage/modular/modform/element.py: implement `_latex_` method</code></td></tr><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/03ab6c624ee5b8c4beb3a1caf7784773cc7e2453"><code>03ab6c6</code></a></td><td><code>src/sage/modular/quasimodform/element.py: implement `_latex_` method</code></td></tr></table>

**Comment by DavidAyotte** [comment]
<div id="comment:3" align="right">comment:3</div>

Green bots, except the Github linter which is not related.

**Comment by tscrim** [comment]
<div id="comment:4" align="right">comment:4</div>

LGTM.

**Comment by tscrim** [comment]
Reviewer: **Travis Scrimshaw**

**Comment by DavidAyotte** [comment]
<div id="comment:5" align="right">comment:5</div>

Thank you!

**Comment by mkoeppe** [comment]
Merged in 10.0.beta0
