### ISSUE TITLE
meson: Add spkg-configure.m4

### ISSUE THREAD

**Issue by mkoeppe** [sagemath/sage#34765]
<div id="comment:0"></div>

Although `meson` is written in Python, `meson-python` invokes `meson` only as an executable (not as a Python package), so we can use a system `meson` package.

Depends on #34081

CC:  @dimpase

Component: **build: configure**

Author: **Matthias Koeppe**

Branch/Commit: **[`f5b5d99`](https://github.com/sagemath/sagetrac-mirror/commit/f5b5d990e343261ea3feec4afc17638419fbfa71)**

Reviewer: **Dima Pasechnik**

_Issue created by migration from https://trac.sagemath.org/ticket/34765_

**Comment by mkoeppe** [comment]
Branch: **[u/mkoeppe/meson__add_spkg_configure_m4](https://github.com/sagemath/sagetrac-mirror/tree/u/mkoeppe/meson__add_spkg_configure_m4)**

**Comment by mkoeppe** [comment]
Commit: **[`f5b5d99`](https://github.com/sagemath/sagetrac-mirror/commit/f5b5d990e343261ea3feec4afc17638419fbfa71)**

**Comment by mkoeppe** [comment]
Author: **Matthias Koeppe**

**Comment by mkoeppe** [comment]
<div id="comment:2"></div>

Last 10 new commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/4778030e2c0daaeca6e55695ee9659a25fa44251"><code>4778030</code></a></td><td><code>Merge #34572</code></td></tr><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/f62b625ec6ef271e87e6a26deeb816387d5543c0"><code>f62b625</code></a></td><td><code>Merge #32182</code></td></tr><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/8990d53f335631f4926cfb1c1e18bfa9ecda5689"><code>8990d53</code></a></td><td><code>.github/workflows/docker.yml: Add option free_disk_space</code></td></tr><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/09244b05468c5b7b407074a60cbd3452eebd60a7"><code>09244b0</code></a></td><td><code>tox.ini (python3.x): Do not clobber user-provided EXTRA_SAGE_PACKAGES</code></td></tr><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/9fb4eac6f4a87fa73fa79a1b173cd09e590ab2fa"><code>9fb4eac</code></a></td><td><code>.github/workflows/docker.yml: Add option extra_sage_packages</code></td></tr><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/3897adb6aa1c59f4410315ea813e4ccc08cc3df0"><code>3897adb</code></a></td><td><code>tox.ini (manylinux-minimal): Provide system liblzma so that system python can be accepted; not system xz</code></td></tr><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/79eccefc7a488e2f42cfbd2c5676c6b5ad52f6cb"><code>79eccef</code></a></td><td><code>build/make/Makefile.in: Only warn if meson_python testsuite fails</code></td></tr><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/853a6995c01958d6ec26c8c68cb266944eb8dc5b"><code>853a699</code></a></td><td><code>Merge tag '9.8.beta3' into t/34081/numpy_1_23_x__scipy_1_9_x</code></td></tr><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/cc351d4d8643cd1f0ce50f90db722a9cc4ad64f3"><code>cc351d4</code></a></td><td><code>Merge #34081</code></td></tr><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/f5b5d990e343261ea3feec4afc17638419fbfa71"><code>f5b5d99</code></a></td><td><code>build/pkgs/meson: Add spkg-configure.m4, distros/</code></td></tr></table>

**Comment by mkoeppe** [comment]
Dependencies: **34081**

**Comment by mkoeppe** [comment]
Description changed:
``````diff
--- 
+++ 
@@ -1 +1,2 @@
+Although `meson` is written in Python, `meson-python` invokes `meson` only as an executable (not as a Python package), so we can use a system `meson` package.
 
``````

**Comment by dimpase** [comment]
Changed dependencies from **34081** to **#34081**

**Comment by dimpase** [comment]
<div id="comment:5" align="right">comment:5</div>

lgtm

**Comment by dimpase** [comment]
Reviewer: **Dima Pasechnik**

**Comment by vbraun** [comment]
Changed branch from **[u/mkoeppe/meson__add_spkg_configure_m4](https://github.com/sagemath/sagetrac-mirror/tree/u/mkoeppe/meson__add_spkg_configure_m4)** to **[`f5b5d99`](https://github.com/sagemath/sagetrac-mirror/commit/f5b5d990e343261ea3feec4afc17638419fbfa71)**
