### ISSUE TITLE
GH Actions: Fix cygwin

### ISSUE THREAD

**Issue by mkoeppe** [sagemath/sage#34774]
<div id="comment:0"></div>

https://github.com/mkoeppe/sage/actions/runs/3519527759/jobs/5899571147

```
1.2.0
Chocolatey v1.2.0

cabal has been installed as a side by side installation.
Side by side installations are deprecated and is pending removal in v2.0.0.

ghc has been installed as a side by side installation.
Side by side installations are deprecated and is pending removal in v2.0.0.

Cygwin v3.3.6 [Approved]
cygwin package files install completed. Performing other installation steps.
Download site: http://mirrors.kernel.org/sourceware/cygwin/
Installing 64-bit Cygwin...
Cygwin has been installed.
Added C:\ProgramData\chocolatey\bin\Cygwin.exe shim pointed to 'c:\tools\cygwin\cygwin.bat'.
Copying cygwin package manager (setup) to C:\tools\cygwin
Environment Vars (like PATH) have changed. Close/reopen your shell to
 see the changes (or in powershell/cmd.exe just type `refreshenv`).
 The install of cygwin was successful.
  Software installed to 'C:\tools\cygwin'
Installing the following packages:
git;python39;python39-pip
By installing, you accept licenses for the packages.

Chocolatey installed 0/0 packages. 
 See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).
The system cannot find the file specified
```

Component: **porting: Cygwin**

_Issue created by migration from https://trac.sagemath.org/ticket/34774_

**Comment by tobiasdiez** [comment]
Since this is (completely) broken for quite some time, I've now disabled the workflow. Can be enabled again once someone volunteers to fix it: https://github.com/sagemath/sage/actions/workflows/ci-cygwin-standard.yml

**Comment by mkoeppe** [comment]
Good idea, thanks.

**Comment by orlitzky** [comment]
Would it be premature to suggest that Cygwin is toast? We announced [Sage 9.7 does not support Cygwin](https://github.com/sagemath/sage/wiki/Sage-9.7-Release-Tour) over a year ago and nobody cared. I think we should start deleting this stuff.

I was reminded of this because https://github.com/sagemath/sage/pull/36129 is going to bring back the psutil package.

**Comment by mkoeppe** [comment]
I would support removing it, but won't work on it myself
