### ISSUE TITLE
switch to libgap in sage/coding

### ISSUE THREAD

**Issue by dimpase** [sagemath/sage#34771]
<div id="comment:0"></div>

after #34737 there are still uses of pexpect GAP left there.
We remove them on this ticket.

Part of #26902

Depends on #34770

CC:  @kwankyu @fchapoton @wdjoyner @mkoeppe

Component: **coding theory**

Author: **Dima Pasechnik**

Branch/Commit: **[`b1257bf`](https://github.com/sagemath/sagetrac-mirror/commit/b1257bf2e06ffb1567bc650b88b380177027b010)**

Reviewer: **Vincent Delecroix, Matthias Koeppe**

_Issue created by migration from https://trac.sagemath.org/ticket/34771_

**Comment by dimpase** [comment]
Dependencies: **#34770**

**Comment by dimpase** [comment]
<div id="comment:1" align="right">comment:1</div>

Trying to use #34770 to avoid explict calls to `gfq_gap_to_sage` from `sage.interfaces.gap`.

**Comment by dimpase** [comment]
Branch: **[u/dimpase/coding/use_libgap](https://github.com/sagemath/sagetrac-mirror/tree/u/dimpase/coding/use_libgap)**

**Comment by dimpase** [comment]
Author: **Dima Pasechnik**

**Comment by dimpase** [comment]
Commit: **[`8777160`](https://github.com/sagemath/sagetrac-mirror/commit/8777160b557b7c0f7a785f0cf3c1583f7824964d)**

**Comment by dimpase** [comment]
<div id="comment:2"></div>

New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/21e38a73fa41698d02ec4c00597e35b5dbd0eda6"><code>21e38a7</code></a></td><td><code>fix coersion of libgap FFelements; switch to libgap</code></td></tr><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/d4bde80f350975b30e5795aa5ffc7333f5c80911"><code>d4bde80</code></a></td><td><code>make imports of is_GapEelment uniform across files</code></td></tr><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/8777160b557b7c0f7a785f0cf3c1583f7824964d"><code>8777160</code></a></td><td><code>use only libgap in coding/linear_code</code></td></tr></table>

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
Changed commit from **[`8777160`](https://github.com/sagemath/sagetrac-mirror/commit/8777160b557b7c0f7a785f0cf3c1583f7824964d)** to **[`b082066`](https://github.com/sagemath/sagetrac-mirror/commit/b082066ee160cdeb8eaf51b6b9c9be2ccd47525f)**

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
<div id="comment:3"></div>

Branch pushed to git repo; I updated commit sha1. New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/b082066ee160cdeb8eaf51b6b9c9be2ccd47525f"><code>b082066</code></a></td><td><code>use libgap in coding/binary_code</code></td></tr></table>

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
Changed commit from **[`b082066`](https://github.com/sagemath/sagetrac-mirror/commit/b082066ee160cdeb8eaf51b6b9c9be2ccd47525f)** to **[`ec1c72e`](https://github.com/sagemath/sagetrac-mirror/commit/ec1c72e1c55b9c15963398e0a2a8cac1d085f71d)**

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
<div id="comment:4"></div>

Branch pushed to git repo; I updated commit sha1. New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/ec1c72e1c55b9c15963398e0a2a8cac1d085f71d"><code>ec1c72e</code></a></td><td><code>fixed off by 1 error: switching to Python's indexing from GAP's</code></td></tr></table>

**Comment by dimpase** [comment]
<div id="comment:5" align="right">comment:5</div>

2 doctest errors in coding/ with these changes:

```
File "src/sage/coding/code_constructions.py", line 732, in sage.coding.code_constructions.ToricCode
Failed example:
    C.minimum_distance()
Expected:
    24
Got:
    30
**********************************************************************
File "src/sage/coding/code_constructions.py", line 740, in sage.coding.code_constructions.ToricCode
Failed example:
    C.minimum_distance()
Expected:
    6
Got:
    10
```
note that doctests using Guava for these codes added in `ec1c72e` output correct minimal distances.

**Comment by dimpase** [comment]
Description changed:
``````diff
--- 
+++ 
@@ -1,4 +1,5 @@
 after #34737 there are still uses of pexpect GAP left there.
+We remove them on this ticket.
 
 
 Part of #26902
``````

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
<div id="comment:7"></div>

Branch pushed to git repo; I updated commit sha1. New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/249acaace8bfac3242f4a2305fe7ef6e7db09251"><code>249acaa</code></a></td><td><code>do not overwrite all-0 vector v0</code></td></tr></table>

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
Changed commit from **[`ec1c72e`](https://github.com/sagemath/sagetrac-mirror/commit/ec1c72e1c55b9c15963398e0a2a8cac1d085f71d)** to **[`249acaa`](https://github.com/sagemath/sagetrac-mirror/commit/249acaace8bfac3242f4a2305fe7ef6e7db09251)**

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
Changed commit from **[`249acaa`](https://github.com/sagemath/sagetrac-mirror/commit/249acaace8bfac3242f4a2305fe7ef6e7db09251)** to **[`d60bf32`](https://github.com/sagemath/sagetrac-mirror/commit/d60bf32344f0136312632fcc51608481492d9078)**

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
<div id="comment:8"></div>

Branch pushed to git repo; I updated commit sha1. New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/d60bf32344f0136312632fcc51608481492d9078"><code>d60bf32</code></a></td><td><code>use libgap in doctest</code></td></tr></table>

**Comment by dimpase** [comment]
<div id="comment:11" align="right">comment:11</div>

With #34391, few doctests related to Guava will need to be adjusted, as Guava is less chatty in GAP 4.12.1.

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
<div id="comment:12"></div>

Branch pushed to git repo; I updated commit sha1. New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/274dc61e1fb21ce6eed806844339ebaa5b8da37c"><code>274dc61</code></a></td><td><code>easier way to get Guava's bindir</code></td></tr></table>

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
Changed commit from **[`d60bf32`](https://github.com/sagemath/sagetrac-mirror/commit/d60bf32344f0136312632fcc51608481492d9078)** to **[`274dc61`](https://github.com/sagemath/sagetrac-mirror/commit/274dc61e1fb21ce6eed806844339ebaa5b8da37c)**

**Comment by videlec** [comment]
<div id="comment:13" align="right">comment:13</div>

This is doing way too much conversions

```
H = libgap(aut_m).Intersection2(aut_B_aug)
rt_transversal = aut_B_aug.RightTransversal(H).List().sage()
rt_transversal = [PermutationGroupElement(g) for g in rt_transversal if str(g) != '()']
rt_transversal = [[a-1 for a in g.domain()] for g in rt_transversal]
rt_transversal = [g + list(xrange(len(g), n))
```
It would be nicer as

```
H = libgap(aut_m).Intersection2(aut_B_aug)
rt_transversal = aut_B_aug.RightTransversal(H)
rt_transversal = [[int(a) - 1 for a in g.ListPerm(n)] for g in rt_transversal if not g.IsOne()]
```

**Comment by videlec** [comment]
<div id="comment:14" align="right">comment:14</div>

At the time guava is loaded, one should check for its availability. The standard way is

```
sage: from sage.features.gap import GapPackage
sage: pkg = GapPackage("guava")
sage: pkg.require()
Traceback (most recent call last):
...
FeatureNotPresentError: gap_package_guava is not available.
`TestPackageAvailability("guava")` evaluated to `fail` in GAP.
```

**Comment by videlec** [comment]
Reviewer: **Vincent Delecroix**

**Comment by dimpase** [comment]
<div id="comment:16" align="right">comment:16</div>

Replying to [Vincent Delecroix](#comment%3A13):
> This is doing way too much conversions
> 
> ```
> H = libgap(aut_m).Intersection2(aut_B_aug)
> rt_transversal = aut_B_aug.RightTransversal(H).List().sage()
> rt_transversal = [PermutationGroupElement(g) for g in rt_transversal if str(g) != '()']
> rt_transversal = [[a-1 for a in g.domain()] for g in rt_transversal]
> rt_transversal = [g + list(xrange(len(g), n))
> ```
> It would be nicer as
> 
> ```
> H = libgap(aut_m).Intersection2(aut_B_aug)
> rt_transversal = aut_B_aug.RightTransversal(H)
> rt_transversal = [[int(a) - 1 for a in g.ListPerm(n)] for g in rt_transversal if not g.IsOne()]
> ```

Sure, thanks, I agree. My goal was to get it to work with libgap rather than pexpect gap, I mostly went with tweaking pre-existing code line by line.

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
<div id="comment:17"></div>

Branch pushed to git repo; I updated commit sha1. This was a forced push. Last 10 new commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/1c4a69fdfee7ccf9aebb40bbc29b4453852cacb1"><code>1c4a69f</code></a></td><td><code>use GapElement from an abstract superclass</code></td></tr><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/6e5ea791a3d846cfd70d9b361f168f6c2fa66a2b"><code>6e5ea79</code></a></td><td><code>move import of libgap into a function</code></td></tr><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/ee9a3d41cf4a458383bfe027f1ae59de548448b6"><code>ee9a3d4</code></a></td><td><code>use only libgap in coding/linear_code</code></td></tr><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/1f67fa2e8f344d5ade0bdad7180f4b5a28144d11"><code>1f67fa2</code></a></td><td><code>use libgap in coding/binary_code</code></td></tr><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/7528cfb2b9f516ce8403f99908d6fdc851a86968"><code>7528cfb</code></a></td><td><code>fixed off by 1 error: switching to Python's indexing from GAP's</code></td></tr><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/2bdf5914699b02fa00776d8a397f310d12ba69c2"><code>2bdf591</code></a></td><td><code>do not overwrite all-0 vector v0</code></td></tr><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/4167b6d5237fa77088a95cf77574af1617a6fbe8"><code>4167b6d</code></a></td><td><code>use libgap in doctest</code></td></tr><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/5e463c84b4c0baf3536959e44a68ef56f69b7d54"><code>5e463c8</code></a></td><td><code>easier way to get Guava's bindir</code></td></tr><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/781677fb112870b44db7b57dfd8d5c3b97f87418"><code>781677f</code></a></td><td><code>add missing string conversion</code></td></tr><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/8b0526ee6975c104a333a7452d3489172b404496"><code>8b0526e</code></a></td><td><code>code simplification, checking for Guava availability</code></td></tr></table>

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
Changed commit from **[`274dc61`](https://github.com/sagemath/sagetrac-mirror/commit/274dc61e1fb21ce6eed806844339ebaa5b8da37c)** to **[`8b0526e`](https://github.com/sagemath/sagetrac-mirror/commit/8b0526ee6975c104a333a7452d3489172b404496)**

**Comment by dimpase** [comment]
<div id="comment:18" align="right">comment:18</div>

fixed, rebased over the latest version of #34770. Ready for review.

**Comment by dimpase** [comment]
<div id="comment:20" align="right">comment:20</div>

ping?

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
<div id="comment:21"></div>

Branch pushed to git repo; I updated commit sha1. This was a forced push. New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/730cd6281c1eae05de0ee0c8683c095325480362"><code>730cd62</code></a></td><td><code>use only libgap in coding/linear_code</code></td></tr><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/5232c56a87729427b96922246211d23f48698bb3"><code>5232c56</code></a></td><td><code>use libgap in coding/binary_code</code></td></tr><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/930eea68fff2fea2ff13b12c8cf1a064011ae128"><code>930eea6</code></a></td><td><code>fixed off by 1 error: switching to Python's indexing from GAP's</code></td></tr><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/6576c4c9fb3cf1cd59bb3552d7cf569903078e25"><code>6576c4c</code></a></td><td><code>do not overwrite all-0 vector v0</code></td></tr><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/df9628cafe9e59edf74f6968b599b410263108c8"><code>df9628c</code></a></td><td><code>use libgap in doctest</code></td></tr><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/318b4310b6b39811ab7214fcefb170b917631d88"><code>318b431</code></a></td><td><code>easier way to get Guava's bindir</code></td></tr><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/65138168e6cde42fc503ccb5fe30495a43a87e9e"><code>6513816</code></a></td><td><code>add missing string conversion</code></td></tr><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/b1257bf2e06ffb1567bc650b88b380177027b010"><code>b1257bf</code></a></td><td><code>code simplification, checking for Guava availability</code></td></tr></table>

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
Changed commit from **[`8b0526e`](https://github.com/sagemath/sagetrac-mirror/commit/8b0526ee6975c104a333a7452d3489172b404496)** to **[`b1257bf`](https://github.com/sagemath/sagetrac-mirror/commit/b1257bf2e06ffb1567bc650b88b380177027b010)**

**Comment by dimpase** [comment]
<div id="comment:22" align="right">comment:22</div>

please review

**Comment by mkoeppe** [comment]
Changed reviewer from **Vincent Delecroix** to **Vincent Delecroix, Matthias Koeppe**

**Comment by mkoeppe** [comment]
<div id="comment:23" align="right">comment:23</div>

LGTM

**Comment by vbraun** [comment]
Changed branch from **[u/dimpase/coding/use_libgap](https://github.com/sagemath/sagetrac-mirror/tree/u/dimpase/coding/use_libgap)** to **[`b1257bf`](https://github.com/sagemath/sagetrac-mirror/commit/b1257bf2e06ffb1567bc650b88b380177027b010)**
