### ISSUE TITLE
fix coercion from libgap's finite fields, use libgap in sage/rings/finite_rings

### ISSUE THREAD

**Issue by dimpase** [sagemath/sage#34770]
<div id="comment:0"></div>

implement coercion from libgap's finite fields, to fix e.g.

```
sage: F=GF(25)
sage: F(libgap.Z(25)^3)
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
...
TypeError: unable to coerce <class 'sage.libs.gap.element.GapElement_FiniteField'>
```

With the ticket branch, this works:

```
sage: F=GF(25)
sage: F(libgap.Z(25)^3)
4*z2 + 3
```

---

As well, we switch to use libgap instead of pexpect GAP - internally
in the affected files. This is a part of #26902

CC:  @nbruin @mkoeppe @kwankyu

Component: **number theory**

Author: **Dima Pasechnik**

Branch/Commit: **[`6e5ea79`](https://github.com/sagemath/sagetrac-mirror/commit/6e5ea791a3d846cfd70d9b361f168f6c2fa66a2b)**

Reviewer: **Matthias Koeppe**

_Issue created by migration from https://trac.sagemath.org/ticket/34770_

**Comment by dimpase** [comment]
Description changed:
``````diff
--- 
+++ 
@@ -12,8 +12,8 @@
 With the ticket branch, this works:
 
 ```
-sage: sage: F=GF(25)
-sage: sage: F(libgap.Z(25)^3)
+sage: F=GF(25)
+sage: F(libgap.Z(25)^3)
 4*z2 + 3
 ```
 
``````

**Comment by dimpase** [comment]
Commit: **[`02bd544`](https://github.com/sagemath/sagetrac-mirror/commit/02bd544c5a0a348b2a448a9eb9f1cc7f7ae3fda0)**

**Comment by dimpase** [comment]
<div id="comment:2"></div>

New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/02bd544c5a0a348b2a448a9eb9f1cc7f7ae3fda0"><code>02bd544</code></a></td><td><code>fix coersion of libgap FFelements; switch to libgap</code></td></tr></table>

**Comment by dimpase** [comment]
Branch: **[u/dimpase/rings/FFEs_to_accept_libgap](https://github.com/sagemath/sagetrac-mirror/tree/u/dimpase/rings/FFEs_to_accept_libgap)**

**Comment by dimpase** [comment]
<div id="comment:4" align="right">comment:4</div>

I've left intact the ability to accept pexpect GAP data to be converted in Sage finite field elements - this means I need a test for this type.
I'm using an import statement 

```
from sage.interfaces.gap import is_GapElement
```
and a call to `is_GapElement()`.
Is there a way to avoid this call? I can also put the import into the `try` block and
set `is_GapElement()` to always return `False` in case of import exception.

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
<div id="comment:5"></div>

Branch pushed to git repo; I updated commit sha1. This was a forced push. New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/21e38a73fa41698d02ec4c00597e35b5dbd0eda6"><code>21e38a7</code></a></td><td><code>fix coersion of libgap FFelements; switch to libgap</code></td></tr></table>

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
Changed commit from **[`02bd544`](https://github.com/sagemath/sagetrac-mirror/commit/02bd544c5a0a348b2a448a9eb9f1cc7f7ae3fda0)** to **[`21e38a7`](https://github.com/sagemath/sagetrac-mirror/commit/21e38a73fa41698d02ec4c00597e35b5dbd0eda6)**

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
Changed commit from **[`21e38a7`](https://github.com/sagemath/sagetrac-mirror/commit/21e38a73fa41698d02ec4c00597e35b5dbd0eda6)** to **[`d4bde80`](https://github.com/sagemath/sagetrac-mirror/commit/d4bde80f350975b30e5795aa5ffc7333f5c80911)**

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
<div id="comment:6"></div>

Branch pushed to git repo; I updated commit sha1. New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/d4bde80f350975b30e5795aa5ffc7333f5c80911"><code>d4bde80</code></a></td><td><code>make imports of is_GapEelment uniform across files</code></td></tr></table>

**Comment by dimpase** [comment]
<div id="comment:7" align="right">comment:7</div>

I can also resort to not calling `is_GapElement()`, and rely on exceptions - this would need a bit more rearranging of if/else. 

However, there are still explicit tests like `sage: S(gap('Z(25)^3'))`, and there is a discrepancy between `libgap` and (pexpect) `gap` in the way they treat such inputs:

```
sage: gap('Z(25)^3')
Z(5^2)^3
sage: gap.eval('Z(25)^3')
'Z(5^2)^3'
sage: libgap.eval('Z(25)^3')
Z(5^2)^3
sage: libgap('Z(25)^3')
"Z(25)^3"
```

So these tests will have to go as soon as `gap` is set to `libgap`.

**Comment by kwankyu** [comment]
<div id="comment:9" align="right">comment:9</div>

I am not familiar with libgap and less with GAP...

This `gfq_gap_to_sage(e, self.parent)` runs faster than `libgap(e).sage(ring=self.parent)` with me. Then why do you replace the former with the latter? Removing pexpect gap is the primary objective?

**Comment by dimpase** [comment]
<div id="comment:10" align="right">comment:10</div>

Replying to [Kwankyu Lee](#comment%3A9):
 
> This `gfq_gap_to_sage(e, self.parent)` runs faster than `libgap(e).sage(ring=self.parent)` with me. 

Loading `libgap` takes time. After it's loaded, it should actually be faster to use
it.

In this particular case, you only need `libgap(e)` on `e` coming from pexpect `gap`.
So there is an extra conversion involved, and we are getting rid of  pexpect `gap`
anyway, so after this is done these conversions (to Sage types) will be much faster
(they are just `e.sage(ring=self.parent)`)

One should not use pexpect `gap`, it should be deprecated. Do you want this to happen on this ticket?

**Comment by dimpase** [comment]
<div id="comment:11" align="right">comment:11</div>

the only "real" use of `gfq_gap_to_sage` is in sage/coding - and this is eliminated in #34771, along with the use of pexpect GAP.

Thus the only possible speed regression can appear in user code, while using pexpect GAP.

**Comment by kwankyu** [comment]
Description changed:
``````diff
--- 
+++ 
@@ -1,4 +1,4 @@
-implement coersion from libgap's finite fields, to fix e.g.
+implement coercion from libgap's finite fields, to fix e.g.
 
 ```
 sage: F=GF(25)
``````

**Comment by kwankyu** [comment]
<div id="comment:12" align="right">comment:12</div>

Replying to [Dima Pasechnik](#comment%3A4):
> I'm using an import statement 
> 
> ```
> from sage.interfaces.gap import is_GapElement
> ```
> and a call to `is_GapElement()`.
> Is there a way to avoid this call? I can also put the import into the `try` block and
> set `is_GapElement()` to always return `False` in case of import exception.

Why is there a possibility of import exception?

The definition of `is_GapElement()` is `isinstance(x, GapElement)`. This lets you avoid the call. But perhaps I simply don't understand your intention or context...

**Comment by dimpase** [comment]
<div id="comment:13" align="right">comment:13</div>

Replying to [Kwankyu Lee](#comment%3A12):

> The definition of `is_GapElement()` is `isinstance(x, GapElement)`. This lets you avoid the call.

Great, this will simplify things a bit. It didn't cross my mind that `is_GapElement()`
is that simple.

**Comment by dimpase** [comment]
<div id="comment:14" align="right">comment:14</div>

Replying to [Dima Pasechnik](#comment%3A13):
> Replying to [Kwankyu Lee](#comment%3A12):
> 
> > The definition of `is_GapElement()` is `isinstance(x, GapElement)`. This lets you avoid the call.
> 
> 
> Great, this will simplify things a bit. It didn't cross my mind that `is_GapElement()`
> is that simple.
> 

well, not really, as one still need to import `GapElement` (Cython won't even compile without it)

**Comment by kwankyu** [comment]
<div id="comment:15" align="right">comment:15</div>

Do you want to avoid importing from `sage.interfaces.gap`? Why?

**Comment by mkoeppe** [comment]
<div id="comment:16" align="right">comment:16</div>

If this is for modularization purposes in which an import may fail: I am using this idiom for such isinstance tests:

```
try:
    from sage.interfaces.gap import GapElement
except ImportError:
    GapElement = ()

... isinstance(x, GapElement)
```

**Comment by dimpase** [comment]
<div id="comment:17" align="right">comment:17</div>

Replying to [Kwankyu Lee](#comment%3A15):
> Do you want to avoid importing from `sage.interfaces.gap`? Why? 

as a preparation for deprecation and removal. We really don't need
a pexpect interface to GAP.

**Comment by dimpase** [comment]
<div id="comment:18" align="right">comment:18</div>

Replying to [Matthias Köppe](#comment%3A16):
> If this is for modularization purposes in which an import may fail: I am using this idiom for such isinstance tests:

It's for coming deprecation and removal, seems to do the job here, too.

**Comment by mkoeppe** [comment]
<div id="comment:19" align="right">comment:19</div>

Another approach: #34804 Deprecate `sage.interfaces` `is_...Element` functions

**Comment by mkoeppe** [comment]
<div id="comment:20" align="right">comment:20</div>

Replying to [Dima Pasechnik](#comment%3A18):
> Replying to [Matthias Köppe](#comment%3A16):
> > If this is for modularization purposes in which an import may fail: I am using this idiom for such isinstance tests:
> 
> 
> It's for coming deprecation and removal, seems to do the job here, too.

For deprecation it will not work so well because modules such as `sage.interfaces.gap` create an instance of the interface class at load time, which would trigger the deprecation warning already.

**Comment by kwankyu** [comment]
<div id="comment:21" align="right">comment:21</div>

Replying to [Dima Pasechnik](#comment%3A17):
> Replying to [Kwankyu Lee](#comment%3A15):
> > Do you want to avoid importing from `sage.interfaces.gap`? Why? 
> 
> 
> as a preparation for deprecation and removal. We really don't need
> a pexpect interface to GAP.

Okay. So this ticket is not removing pexpect GAP, but just drying it out(not sure if this phrase conveys the meaning). This seems to force you to write clumsy code. 

How about adding only deprecation warnings without touching actual pexpect GAP code in this ticket, and then remove all of it in another ticket after deprecation period?

**Comment by dimpase** [comment]
<div id="comment:22" align="right">comment:22</div>

By the way, there is also an interesting import hell issue I encountered here: 
I'm changing here 4 files

```
src/sage/rings/finite_rings/element_givaro.pyx
src/sage/rings/finite_rings/element_ntl_gf2e.pyx
src/sage/rings/finite_rings/element_pari_ffelt.pyx
src/sage/rings/finite_rings/integer_mod_ring.py
```
Of them, the first 3 are very similar. However, I cannot do top-level
`from sage.libs.gap.element import GapElement_FiniteField` in each of them, only in  `element_ntl_gf2e.pyx` it does not
lead to an obscure runtime error (`Cannot import RDF`) from libgap.

**Comment by dimpase** [comment]
<div id="comment:23" align="right">comment:23</div>

Replying to [Matthias Köppe](#comment%3A19):
> Another approach: #34804 Deprecate `sage.interfaces` `is_...Element` functions

OK, this is interesting. So this would mean unconditionally importing `GapElement` from 
`sage.interfaces.abs`, right? I'm only not completely sure I understand what should be in the latter, as examples such as in `src/sage/rings/abc.pyx` look like dark magic to me.

**Comment by mkoeppe** [comment]
<div id="comment:24" align="right">comment:24</div>

Replying to [Dima Pasechnik](#comment%3A23):
> Replying to [Matthias Köppe](#comment%3A19):
> > Another approach: #34804 Deprecate `sage.interfaces` `is_...Element` functions
> 
> 
> OK, this is interesting. So this would mean unconditionally importing `GapElement` from 
> `sage.interfaces.abs`, right? 

Yes.

> I'm only not completely sure I understand what should be in the latter, as examples such as in `src/sage/rings/abc.pyx` look like dark magic to me.

I've pushed a barebones version to #34804. `src/sage/rings/abc.pyx` is longer, but it's just decoration

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
<div id="comment:25"></div>

Branch pushed to git repo; I updated commit sha1. New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/eb72ef050d94dd32cbb1499243af5de4e9eec22c"><code>eb72ef0</code></a></td><td><code>avoid is_GapElement</code></td></tr><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/1c4a69fdfee7ccf9aebb40bbc29b4453852cacb1"><code>1c4a69f</code></a></td><td><code>use GapElement from an abstract superclass</code></td></tr></table>

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
Changed commit from **[`d4bde80`](https://github.com/sagemath/sagetrac-mirror/commit/d4bde80f350975b30e5795aa5ffc7333f5c80911)** to **[`1c4a69f`](https://github.com/sagemath/sagetrac-mirror/commit/1c4a69fdfee7ccf9aebb40bbc29b4453852cacb1)**

**Comment by dimpase** [comment]
<div id="comment:26" align="right">comment:26</div>

OK, how about this? The branch of #34804 should be based on this one.

**Comment by mkoeppe** [comment]
<div id="comment:27" align="right">comment:27</div>

Yes, looking good.

**Comment by dimpase** [comment]
<div id="comment:28" align="right">comment:28</div>

review?

**Comment by mkoeppe** [comment]
<div id="comment:29" align="right">comment:29</div>

In this change:

```
--- a/src/sage/rings/finite_rings/element_ntl_gf2e.pyx
+++ b/src/sage/rings/finite_rings/element_ntl_gf2e.pyx
@@ -56,6 +54,11 @@ from .finite_field_ntl_gf2e import FiniteField_ntl_gf2e
 
 from sage.rings.polynomial.polynomial_ring_constructor import PolynomialRing
 
+from sage.libs.gap.element import GapElement_FiniteField
+
```
it would be good to use the `try except ... ()` so that there is no hard load-time dependency on libgap.

**Comment by dimpase** [comment]
<div id="comment:30" align="right">comment:30</div>

Replying to [Matthias Köppe](#comment%3A29):
> In this change:
> 
> ```
> --- a/src/sage/rings/finite_rings/element_ntl_gf2e.pyx
> +++ b/src/sage/rings/finite_rings/element_ntl_gf2e.pyx
> @@ -56,6 +54,11 @@ from .finite_field_ntl_gf2e import FiniteField_ntl_gf2e
>  
>  from sage.rings.polynomial.polynomial_ring_constructor import PolynomialRing
>  
> +from sage.libs.gap.element import GapElement_FiniteField
> +
> ```
> it would be good to use the `try except ... ()` so that there is no hard load-time dependency on libgap.

there are more importings of `GapElement_FiniteField` in this patch, i suppose you'd like to deal with them all.

Why don't we instead go the way we went with `GapElement` here, by adding `sage.libs.abc`, etc?

**Comment by mkoeppe** [comment]
<div id="comment:31" align="right">comment:31</div>

Replying to [Dima Pasechnik](#comment%3A30):
> Why don't we instead go the way we went with `GapElement` here, by adding `sage.libs.abc`, etc?

That's also fine

**Comment by dimpase** [comment]
<div id="comment:32" align="right">comment:32</div>

Replying to [Matthias Köppe](#comment%3A31):
> Replying to [Dima Pasechnik](#comment%3A30):
> > Why don't we instead go the way we went with `GapElement` here, by adding `sage.libs.abc`, etc?
> 
> 
> That's also fine

Can we do `sage.libs.abc` as a part of #32414, on a separate ticket?
After all, the current ticket is a part of #26902, which is not modularisation.

**Comment by mkoeppe** [comment]
<div id="comment:33" align="right">comment:33</div>

It's kind of why I suggested to use `try except ... ()` in [comment:30](#comment%3A30).

**Comment by dimpase** [comment]
<div id="comment:34" align="right">comment:34</div>

Replying to [Matthias Köppe](#comment%3A33):
> It's kind of why I suggested to use `try except ... ()` in [comment:30](#comment%3A30).

but we are not doing modularisation of libgap module here. that's why I don't want to `try:` here.

**Comment by mkoeppe** [comment]
<div id="comment:35" align="right">comment:35</div>

The ticket is introducing a modularization regression by inserting this new module-level import.

**Comment by dimpase** [comment]
<div id="comment:36" align="right">comment:36</div>

Replying to [Matthias Köppe](#comment%3A35):
> The ticket is introducing a modularization regression by inserting this new module-level import.

it replaces one modularization regression with another.

There are about 180 `from sage.libs.gap...` in Sage, I suppose none of them in `try... except block`. It's begging for a separate ticket, which is best attended to once we've replaced all pexpect GAP with libgap.

**Comment by mkoeppe** [comment]
<div id="comment:37" align="right">comment:37</div>

There are no unprotected module-level imports from `sage.libs.gap` in sage.rings. Please don't introduce one, that's all I'm asking.

**Comment by dimpase** [comment]
<div id="comment:38" align="right">comment:38</div>

Replying to [Matthias Köppe](#comment%3A37):
> There are no unprotected module-level imports from `sage.libs.gap` in sage.rings. Please don't introduce one, that's all I'm asking.

Do you mean it's OK for you to have imports in functions, say?
E.g. in `src/sage/rings/number_field/number_field.py` there is
`def _libgap_(self)` where `libgap` is unconditionally imported.

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
Changed commit from **[`1c4a69f`](https://github.com/sagemath/sagetrac-mirror/commit/1c4a69fdfee7ccf9aebb40bbc29b4453852cacb1)** to **[`6e5ea79`](https://github.com/sagemath/sagetrac-mirror/commit/6e5ea791a3d846cfd70d9b361f168f6c2fa66a2b)**

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
<div id="comment:39"></div>

Branch pushed to git repo; I updated commit sha1. New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/6e5ea791a3d846cfd70d9b361f168f6c2fa66a2b"><code>6e5ea79</code></a></td><td><code>move import of libgap into a function</code></td></tr></table>

**Comment by mkoeppe** [comment]
<div id="comment:40" align="right">comment:40</div>

Yes, that's https://doc.sagemath.org/html/en/developer/packaging_sage_library.html#module-level-runtime-dependencies bullet point 2 "Replace module-level imports by method-level imports."

**Comment by mkoeppe** [comment]
Reviewer: **Matthias Koeppe**

**Comment by mkoeppe** [comment]
<div id="comment:41" align="right">comment:41</div>

LGTM, thanks.

**Comment by vbraun** [comment]
Changed branch from **[u/dimpase/rings/FFEs_to_accept_libgap](https://github.com/sagemath/sagetrac-mirror/tree/u/dimpase/rings/FFEs_to_accept_libgap)** to **[`6e5ea79`](https://github.com/sagemath/sagetrac-mirror/commit/6e5ea791a3d846cfd70d9b361f168f6c2fa66a2b)**
