### ISSUE TITLE
GH Actions: Fix 'Build & Test using Conda'

### ISSUE THREAD

**Issue by mkoeppe** [sagemath/sage#34776]
<div id="comment:0"></div>

https://github.com/mkoeppe/sage/actions/runs/3519527725/jobs/5899570344

```
 
  Encountered problems while solving:
    - package giac-1.5.0.37-h6866182_0 requires gsl >=2.4,<2.5.0a0, but none of the providers can be installed
```

https://github.com/mkoeppe/sage/actions/runs/3519527725/jobs/5899570635

```
  Encountered problems while solving:
    - nothing provides path.py >=7.1,<8 needed by sage-8.1-py27_1
  
  conda-forge/noarch        
  conda-forge/osx-64        
```

CC:  @tobiasdiez @isuruf

Component: **porting**

Author: **Matthias Koeppe**

Branch/Commit: **[u/mkoeppe/gh_actions__fix__build___test_using_conda_](https://github.com/sagemath/sagetrac-mirror/tree/u/mkoeppe/gh_actions__fix__build___test_using_conda_) @ [`8032793`](https://github.com/sagemath/sagetrac-mirror/commit/8032793526be4bcbcecfa6c442c71ecff6d8688a)**

Reviewer: **https://github.com/sagemath/sagetrac-mirror/actions/runs/3529084492**

_Issue created by migration from https://trac.sagemath.org/ticket/34776_

**Comment by isuruf** [comment]
<div id="comment:1" align="right">comment:1</div>

Those seem like old versions. Did something change in dependencies in `distros/conda.txt` files?

**Comment by mkoeppe** [comment]
<div id="comment:2" align="right">comment:2</div>

`src/environment-optional.yml` ends up with a dependency on `sage` (also causes #34777), which comes in from our `_sagemath` spkg. I'll fix this.

**Comment by mkoeppe** [comment]
Branch: **[u/mkoeppe/gh_actions__fix__build___test_using_conda_](https://github.com/sagemath/sagetrac-mirror/tree/u/mkoeppe/gh_actions__fix__build___test_using_conda_)**

**Comment by mkoeppe** [comment]
Commit: **[`cfe3ce4`](https://github.com/sagemath/sagetrac-mirror/commit/cfe3ce4b58398c133ef70cf9bea2c83768fe1a5d)**

**Comment by mkoeppe** [comment]
Author: **Matthias Koeppe**

**Comment by mkoeppe** [comment]
Reviewer: **https://github.com/sagemath/sagetrac-mirror/actions/runs/3529084492**

**Comment by mkoeppe** [comment]
<div id="comment:4"></div>

New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/cfe3ce4b58398c133ef70cf9bea2c83768fe1a5d"><code>cfe3ce4</code></a></td><td><code>bootstrap-conda: Do not include underscore packages in environments</code></td></tr></table>

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
<div id="comment:5"></div>

Branch pushed to git repo; I updated commit sha1. New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/8032793526be4bcbcecfa6c442c71ecff6d8688a"><code>8032793</code></a></td><td><code>.github/workflows/ci-conda.yml: Add python3.10</code></td></tr></table>

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
Changed commit from **[`cfe3ce4`](https://github.com/sagemath/sagetrac-mirror/commit/cfe3ce4b58398c133ef70cf9bea2c83768fe1a5d)** to **[`8032793`](https://github.com/sagemath/sagetrac-mirror/commit/8032793526be4bcbcecfa6c442c71ecff6d8688a)**

**Comment by mkoeppe** [comment]
<div id="comment:6" align="right">comment:6</div>

That fixed it. Next problem: 

```
  Installing pip dependencies: 
Collecting jupymake>=0.9
    Downloading JuPyMake-0.9.tar.gz (10 kB)
    Preparing metadata (setup.py): started
    Preparing metadata (setup.py): finished with status 'error'
    Pip subprocess error:
    error: subprocess-exited-with-error
    
    × python setup.py egg_info did not run successfully.
    │ exit code: 1
    ╰─> [14 lines of output]
        Traceback (most recent call last):
          File "<string>", line 2, in <module>
          File "<pip-setuptools-caller>", line 34, in <module>
          File "/tmp/pip-install-2kcupmhw/jupymake_ac5dad76319647d4984156d3649190a7/setup.py", line 22, in <module>
            polymake_cflags = conditional_decode( subprocess.check_output( [ "polymake-config", "--cflags" ] ).strip() ).split(' ')
          File "/usr/share/miniconda/envs/sage-build/lib/python3.8/subprocess.py", line 415, in check_output
            return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
          File "/usr/share/miniconda/envs/sage-build/lib/python3.8/subprocess.py", line 493, in run
            with Popen(*popenargs, **kwargs) as process:
          File "/usr/share/miniconda/envs/sage-build/lib/python3.8/subprocess.py", line 858, in __init__
            self._execute_child(args, executable, preexec_fn, close_fds,
          File "/usr/share/miniconda/envs/sage-build/lib/python3.8/subprocess.py", line 1704, in _execute_child
            raise child_exception_type(errno_num, err_msg, err_filename)
        FileNotFoundError: [Errno 2] No such file or directory: 'polymake-config'
        [end of output]
```
https://github.com/sagemath/sagetrac-mirror/actions/runs/3529084492/jobs/5919802842

**Comment by isuruf** [comment]
<div id="comment:7" align="right">comment:7</div>

We don't have a conda package for `polymake`. I guess you can't build `jupymake` without it.
