### ISSUE TITLE
fixes in normal_basis

### ISSUE THREAD

**Issue by fchapoton** [sagemath/sage#34789]
<div id="comment:0"></div>

remove deprecation from #29543 

and makes sure that the code works to get the full basis in presence of weights.

CC:  @sorger-c

Component: **algebraic geometry**

Author: **Frédéric Chapoton**

Branch/Commit: **[`dafcbff`](https://github.com/sagemath/sagetrac-mirror/commit/dafcbff50b50377b1942583fbe3375bd65ebf6f4)**

Reviewer: **Christoph Sorger**

_Issue created by migration from https://trac.sagemath.org/ticket/34789_

**Comment by fchapoton** [comment]
Author: **Frédéric Chapoton**

**Comment by fchapoton** [comment]
Branch: **[#29543](https://github.com/sagemath/sagetrac-mirror/tree/#29543)**

**Comment by fchapoton** [comment]
Commit: **[`dafcbff`](https://github.com/sagemath/sagetrac-mirror/commit/dafcbff50b50377b1942583fbe3375bd65ebf6f4)**

**Comment by fchapoton** [comment]
Changed branch from **[#29543](https://github.com/sagemath/sagetrac-mirror/tree/#29543)** to **[u/chapoton/34789](https://github.com/sagemath/sagetrac-mirror/tree/u/chapoton/34789)**

**Comment by fchapoton** [comment]
<div id="comment:2"></div>

New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/dafcbff50b50377b1942583fbe3375bd65ebf6f4"><code>dafcbff</code></a></td><td><code>some fixes about normal_basis</code></td></tr></table>

**Comment by fchapoton** [comment]
<div id="comment:3" align="right">comment:3</div>

the red "lint failing" is normal, not related to this ticket

**Comment by fchapoton** [comment]
<div id="comment:4" align="right">comment:4</div>

tous les feux sont au vert (on peut ignorer le "lint:failing" en rouge)

**Comment by fchapoton** [comment]
Reviewer: **Christoph Sorger**

**Comment by fchapoton** [comment]
<div id="comment:6" align="right">comment:6</div>

merci. J'ai rajouté ton nom dans la case "reviewers".

**Comment by vbraun** [comment]
Changed branch from **[u/chapoton/34789](https://github.com/sagemath/sagetrac-mirror/tree/u/chapoton/34789)** to **[`dafcbff`](https://github.com/sagemath/sagetrac-mirror/commit/dafcbff50b50377b1942583fbe3375bd65ebf6f4)**
