### ISSUE TITLE
fixing the linter, once again

### ISSUE THREAD

**Issue by fchapoton** [sagemath/sage#34781]
<div id="comment:0"></div>

mostly broken by fusion_rings and lazy_rings recent tickets

Component: **refactoring**

Author: **Frédéric Chapoton**

Branch/Commit: **[`fdd4f7f`](https://github.com/sagemath/sagetrac-mirror/commit/fdd4f7f9f0b50a6718eb682d905557f2766f4b4f)**

Reviewer: **Matthias Koeppe, Lorenz Panny**

_Issue created by migration from https://trac.sagemath.org/ticket/34781_

**Comment by fchapoton** [comment]
Branch: **[u/chapoton/34781](https://github.com/sagemath/sagetrac-mirror/tree/u/chapoton/34781)**

**Comment by fchapoton** [comment]
<div id="comment:1"></div>

New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/927684bd04f2f9fa9ccde20174cb4c683dc31dde"><code>927684b</code></a></td><td><code>activate pycodestyle E275 in the minimal linter</code></td></tr></table>

**Comment by fchapoton** [comment]
Commit: **[`927684b`](https://github.com/sagemath/sagetrac-mirror/commit/927684bd04f2f9fa9ccde20174cb4c683dc31dde)**

**Comment by mkoeppe** [comment]
<div id="comment:2" align="right">comment:2</div>


```
310     E275 missing whitespace after keyword
1       E306 expected 1 blank line before a nested definition, found 0
6       W391 blank line at end of file
```

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
<div id="comment:3"></div>

Branch pushed to git repo; I updated commit sha1. New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/f7c983e03922ca9b996e9572baa41bd7a43758db"><code>f7c983e</code></a></td><td><code>fix linter and activate E275 only for pyx files</code></td></tr></table>

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
Changed commit from **[`927684b`](https://github.com/sagemath/sagetrac-mirror/commit/927684bd04f2f9fa9ccde20174cb4c683dc31dde)** to **[`f7c983e`](https://github.com/sagemath/sagetrac-mirror/commit/f7c983e03922ca9b996e9572baa41bd7a43758db)**

**Comment by fchapoton** [comment]
<div id="comment:4" align="right">comment:4</div>

strange, but then let us keep that for later and just fix the linter again here

**Comment by fchapoton** [comment]
Description changed:
``````diff
--- 
+++ 
@@ -1 +1 @@
-
+also fix the recent breakage of the linter
``````

**Comment by tscrim** [comment]
<div id="comment:6" align="right">comment:6</div>

Why are we removing the one blank line at the end of files? The description of W261 does not match its example. Its "best practice" has zero blank lines and removing these from the files in this change means they have none. If they are doing some other kind of counting, then it makes no sense to have zero "blank lines". I am quite confused by this.

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
<div id="comment:7"></div>

Branch pushed to git repo; I updated commit sha1. New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/9eca08f6d8237e6b6615cc5d64aa6e6c577b57c6"><code>9eca08f</code></a></td><td><code>fix indentation E111 in pyx files and disactivate E275</code></td></tr></table>

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
Changed commit from **[`f7c983e`](https://github.com/sagemath/sagetrac-mirror/commit/f7c983e03922ca9b996e9572baa41bd7a43758db)** to **[`9eca08f`](https://github.com/sagemath/sagetrac-mirror/commit/9eca08f6d8237e6b6615cc5d64aa6e6c577b57c6)**

**Comment by fchapoton** [comment]
Description changed:
``````diff
--- 
+++ 
@@ -1 +1 @@
-also fix the recent breakage of the linter
+mostly broken by fusion_rings and lazy_rings recent tickets
``````

**Comment by fchapoton** [comment]
<div id="comment:9" align="right">comment:9</div>

Replying to [Travis Scrimshaw](#comment%3A6):
> Why are we removing the one blank line at the end of files? The description of W261 does not match its example. Its "best practice" has zero blank lines and removing these from the files in this change means they have none. If they are doing some other kind of counting, then it makes no sense to have zero "blank lines". I am quite confused by this.

W391

https://www.flake8rules.com/rules/W391.html

**Comment by fchapoton** [comment]
<div id="comment:10" align="right">comment:10</div>

but indeed the description is faulty

the good thing is to end by one line break, but no empty lines

**Comment by tscrim** [comment]
<div id="comment:11" align="right">comment:11</div>

It's not just faulty, it doesn't even satisfy it's own logic. If it ends with a line break, then by definition, there is a blank line. Otherwise there is no line break at the end. If the end of the last line counts (again, what line break?), then how could there possibly be zero?

The general standard, as I understand it, is to have a blank line. This is what they are claiming too. They have a bug in their implementation with a false example IMO.

**Comment by fchapoton** [comment]
<div id="comment:12" align="right">comment:12</div>

maybe there is a confusion with "empty" meaning "no characters at all" or "just a bunch of spaces" ? There should be a line break, followed (and preceded) by no spaces.

**Comment by tscrim** [comment]
<div id="comment:13" align="right">comment:13</div>

But again, a line break would mean we have a blank line. If what they meant was any type of whitespace, then it would be zero.

Having exactly one line break means

```
Something\n
<blankline><EOF>
```
Otherwise there would be zero for

```
Something<EOF>
```

**Comment by mkoeppe** [comment]
<div id="comment:14" align="right">comment:14</div>

Replying to [Travis Scrimshaw](#comment%3A6):
> I am quite confused by this.

Yes.

- `Text\n`, then EOF -- good.
- `Text`, then EOF -- ungood - non-terminated line at EOF.
- `Text\n\n`, then EOF -- ungood - empty line before EOF.
- `Text\n \n`, then EOF -- ungood - line with trailing space.
- `Text\n `, then EOF -- plus ungood - line with trailing space, non-terminated.

**Comment by mkoeppe** [comment]
<div id="comment:15" align="right">comment:15</div>

I would suggest not to make style changes like this:

```
-      if a == id_anyon:
-          if x == b and y == d:
-              return 1
-          else:
-              return 0
+    if a == id_anyon:
+        return 1 if x == b and y == d else 0
```
I don't think it's universally agreed that this would be an improvement. Personally, I never use `if-else` expressions and I find them harder to read.

**Comment by fchapoton** [comment]
<div id="comment:16" align="right">comment:16</div>

maybe this debatable cosmetic change should not prevent to fix the linter as soon as possible ?

**Comment by yyyyx4** [comment]
<div id="comment:17" align="right">comment:17</div>

Replying to [Matthias Köppe](#comment%3A15):
> 
> ```
> -      if a == id_anyon:
> -          if x == b and y == d:
> -              return 1
> -          else:
> -              return 0
> +    if a == id_anyon:
> +        return 1 if x == b and y == d else 0
> ```

How about `int(x == b and y == d)`?

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
<div id="comment:18"></div>

Branch pushed to git repo; I updated commit sha1. New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/fdd4f7f9f0b50a6718eb682d905557f2766f4b4f"><code>fdd4f7f</code></a></td><td><code>little tweak</code></td></tr></table>

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
Changed commit from **[`9eca08f`](https://github.com/sagemath/sagetrac-mirror/commit/9eca08f6d8237e6b6615cc5d64aa6e6c577b57c6)** to **[`fdd4f7f`](https://github.com/sagemath/sagetrac-mirror/commit/fdd4f7f9f0b50a6718eb682d905557f2766f4b4f)**

**Comment by fchapoton** [comment]
<div id="comment:19" align="right">comment:19</div>

voilà, done

**Comment by mkoeppe** [comment]
Reviewer: **Matthias Koeppe, Lorenz Panny**

**Comment by vbraun** [comment]
Changed branch from **[u/chapoton/34781](https://github.com/sagemath/sagetrac-mirror/tree/u/chapoton/34781)** to **[`fdd4f7f`](https://github.com/sagemath/sagetrac-mirror/commit/fdd4f7f9f0b50a6718eb682d905557f2766f4b4f)**
