### ISSUE TITLE
various details in combinat/

### ISSUE THREAD

**Issue by fchapoton** [sagemath/sage#34783]
<div id="comment:0"></div>

about E271 and E272 pycodestyle warnings

Component: **combinatorics**

Author: **Frédéric Chapoton**

Branch/Commit: **[`b6d91e4`](https://github.com/sagemath/sagetrac-mirror/commit/b6d91e435f546f40cf7abe7cb5869a8205072cb7)**

Reviewer: **Matthias Koeppe**

_Issue created by migration from https://trac.sagemath.org/ticket/34783_

**Comment by fchapoton** [comment]
Commit: **[`12cf29e`](https://github.com/sagemath/sagetrac-mirror/commit/12cf29eeae843444ad1ee712c2504178c0e06f8b)**

**Comment by fchapoton** [comment]
<div id="comment:1"></div>

New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/12cf29eeae843444ad1ee712c2504178c0e06f8b"><code>12cf29e</code></a></td><td><code>various details in combinat/</code></td></tr></table>

**Comment by fchapoton** [comment]
Branch: **[u/chapoton/34783](https://github.com/sagemath/sagetrac-mirror/tree/u/chapoton/34783)**

**Comment by mkoeppe** [comment]
Reviewer: **Matthias Koeppe**

**Comment by vbraun** [comment]
<div id="comment:3" align="right">comment:3</div>

Merge failure on top of:

d16c14def33 Trac #34781: fixing the linter, once again

126b39e8cef Trac #34755: add `_repr_svg_` for Dyck words

29649335c9c Trac #34743: modernize super in root_systems

c508e6f0326 Trac #34835: openblas: Remove python from dependencies

f58a6e216a3 Trac #34823: deprecate is_GapElement

4d6221f2709 Trac #34819: Numerical separators behave inconsistently

a3fbf071611 Trac #34812: decompose identity into generators with coxeter3

03a22d74903 Trac #34802: fix some compilation warnings

6ef550c20a1 Trac #34799: fix order of multiplication in coxeter_groups

28c497ac37a Trac #34798: less use of type "long" in cython files

d6c4402e6e8 Trac #34770: fix coercion from libgap's finite fields, use libgap in sage/rings/finite_rings

67c8b766ea0 Trac #34582: Commutative graded algebras: remove sorting restriction

cf0782c7a2c Trac #34515: factorization of symmetric functions

25191d122bc Trac #34444: Implement Groebner cover

cb66c487fc5 Trac #33875: an_element for statistics and maps

4a38a459d17 Trac #32841: zn_poly removal

6825519ac7d Trac #32390: Make "./configure --enable-download-from-upstream-url" the default

c644d16b40b Trac #30666: Distributions sagemath-{flint-arb,homfly,giac,gap}, add "sage_setup: distribution" to Cython modules

873370d568b Trac #34795: Upgrade pybind11, docutils and other packages

ba79fabb451 Trac #34537: Upgrade to pari 2.15.1

bb7ee856390 Updated [SageMath](../wiki/SageMath) version to 9.8.beta5



merge was not clean: conflicts in src/sage/combinat/matrices/hadamard_matrix.py

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
<div id="comment:4"></div>

Branch pushed to git repo; I updated commit sha1. New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/b6d91e435f546f40cf7abe7cb5869a8205072cb7"><code>b6d91e4</code></a></td><td><code>Merge branch 'u/chapoton/34783' in 9.8.b5</code></td></tr></table>

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
Changed commit from **[`12cf29e`](https://github.com/sagemath/sagetrac-mirror/commit/12cf29eeae843444ad1ee712c2504178c0e06f8b)** to **[`b6d91e4`](https://github.com/sagemath/sagetrac-mirror/commit/b6d91e435f546f40cf7abe7cb5869a8205072cb7)**

**Comment by fchapoton** [comment]
<div id="comment:5" align="right">comment:5</div>

back to positive after easy merge

**Comment by vbraun** [comment]
Changed branch from **[u/chapoton/34783](https://github.com/sagemath/sagetrac-mirror/tree/u/chapoton/34783)** to **[`b6d91e4`](https://github.com/sagemath/sagetrac-mirror/commit/b6d91e435f546f40cf7abe7cb5869a8205072cb7)**
