### ISSUE TITLE
streamline .set_order() methods for elliptic curves and points

### ISSUE THREAD

**Issue by yyyyx4** [sagemath/sage#34787]
<div id="comment:0"></div>

Elliptic curves and points have `.set_order()` methods to supply the order to Sage's algorithms instead of computing it.

However, `.set_order()` for curves currently has a `num_checks=` keyword argument instead of the usual `check=` flag, and `.set_order()` for points does not have either argument and simply runs checks unconditionally.

In this patch we add `check=` arguments to both methods. Moreover, we make `.set_order()` work for points over general fields, where order-computation algorithms are not available at the moment.

Component: **elliptic curves**

Author: **Lorenz Panny**

Branch/Commit: **[`12d13b3`](https://github.com/sagemath/sagetrac-mirror/commit/12d13b393b384da2863ce09f24d125db4759d0c9)**

Reviewer: **Kwankyu Lee**

_Issue created by migration from https://trac.sagemath.org/ticket/34787_

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
<div id="comment:1"></div>

Branch pushed to git repo; I updated commit sha1. This was a forced push. New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/f9135f002b3a08e55c0ec74c349f7ba1721e20a6"><code>f9135f0</code></a></td><td><code>streamline .set_order() for elliptic curves and points</code></td></tr></table>

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
Changed commit from **[`408e3cc`](https://github.com/sagemath/sagetrac-mirror/commit/408e3ccf5d8f7398bd0e730508245fb37e14edb5)** to **[`f9135f0`](https://github.com/sagemath/sagetrac-mirror/commit/f9135f002b3a08e55c0ec74c349f7ba1721e20a6)**

**Comment by kwankyu** [comment]
<div id="comment:3" align="right">comment:3</div>

What is the role of `*` in the following?

```
    def set_order(self, value, *, check=True, num_checks=8):   
```

**Comment by kwankyu** [comment]
<div id="comment:4" align="right">comment:4</div>


```
            Q.set_order(n2, check=False)        # verifies n2*Q == 0   
```
By the change, the comment is wrong.

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
Changed commit from **[`f9135f0`](https://github.com/sagemath/sagetrac-mirror/commit/f9135f002b3a08e55c0ec74c349f7ba1721e20a6)** to **[`12d13b3`](https://github.com/sagemath/sagetrac-mirror/commit/12d13b393b384da2863ce09f24d125db4759d0c9)**

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
<div id="comment:5"></div>

Branch pushed to git repo; I updated commit sha1. New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/12d13b393b384da2863ce09f24d125db4759d0c9"><code>12d13b3</code></a></td><td><code>replace now-incorrect comment by assertion</code></td></tr></table>

**Comment by yyyyx4** [comment]
<div id="comment:6" align="right">comment:6</div>

Replying to [Kwankyu Lee](#comment%3A3):
> What is the role of `*` in the following?
> 
> ```
>     def set_order(self, value, *, check=True, num_checks=8):   
> ```

It marks all following arguments as keyword-only. I think enforcing that `check=` be passed as a keyword argument is a good idea: It makes a function call with a `check` argument much easier to understand than a boolean positional argument.

Replying to [Kwankyu Lee](#comment%3A4):
> 
> ```
>             Q.set_order(n2, check=False)        # verifies n2*Q == 0   
> ```
> By the change, the comment is wrong.

Good catch, fixed.

**Comment by kwankyu** [comment]
Reviewer: **Kwankyu Lee**

**Comment by kwankyu** [comment]
<div id="comment:7" align="right">comment:7</div>

Thanks. I didn't know that idiom though there are 97 uses of that idiom in sage :)

LGTM.

**Comment by yyyyx4** [comment]
<div id="comment:8" align="right">comment:8</div>

Thank you!

**Comment by vbraun** [comment]
Changed branch from **[public/streamline_set_order_methods](https://github.com/sagemath/sagetrac-mirror/tree/public/streamline_set_order_methods)** to **[`12d13b3`](https://github.com/sagemath/sagetrac-mirror/commit/12d13b393b384da2863ce09f24d125db4759d0c9)**
