### ISSUE TITLE
add .twists() to EllipticCurve_finite_field

### ISSUE THREAD

**Issue by yyyyx4** [sagemath/sage#34782]
<div id="comment:0"></div>

This patch adds a method `.twists()` to elliptic curves over finite fields `k`, which computes a set of `k`-isomorphism representatives of the `K`-isomorphism class where `K` is the algebraic closure of `k`.

This can be useful, for instance, to compute a list of all elliptic curves defined over `k` up to `k`-isomorphism:

```sage
def all_curves(F):
    return [E for j in F for E in EllipticCurve(j=j).twists()]
```

CC:  @JohnCremona @defeo

Component: **elliptic curves**

Authors: **Lorenz Panny**, **John Cremona**

_Issue created by migration from https://trac.sagemath.org/ticket/34782_

**Comment by mkoeppe** [comment]
Removed branch from the issue description because it has been replaced by PR #34981
