### ISSUE TITLE
fix and activate W291 in py files

### ISSUE THREAD

**Issue by fchapoton** [sagemath/sage#34785]
<div id="comment:0"></div>

this is about "no trailing whitespace"

Component: **refactoring**

Author: **Frédéric Chapoton**

Branch/Commit: **[`68cef16`](https://github.com/sagemath/sagetrac-mirror/commit/68cef160ba45dc79054e1a3723f05c202a5f8da4)**

Reviewer: **Matthias Koeppe**

_Issue created by migration from https://trac.sagemath.org/ticket/34785_

**Comment by fchapoton** [comment]
Branch: **[u/chapoton/34785](https://github.com/sagemath/sagetrac-mirror/tree/u/chapoton/34785)**

**Comment by fchapoton** [comment]
Commit: **[`68cef16`](https://github.com/sagemath/sagetrac-mirror/commit/68cef160ba45dc79054e1a3723f05c202a5f8da4)**

**Comment by fchapoton** [comment]
<div id="comment:1"></div>

New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/68cef160ba45dc79054e1a3723f05c202a5f8da4"><code>68cef16</code></a></td><td><code>fix and activate W291 (trailing whitespace) in linter</code></td></tr></table>

**Comment by mkoeppe** [comment]
Reviewer: **Matthias Koeppe**

**Comment by vbraun** [comment]
Changed branch from **[u/chapoton/34785](https://github.com/sagemath/sagetrac-mirror/tree/u/chapoton/34785)** to **[`68cef16`](https://github.com/sagemath/sagetrac-mirror/commit/68cef160ba45dc79054e1a3723f05c202a5f8da4)**
