### ISSUE TITLE
some care for E275

### ISSUE THREAD

**Issue by fchapoton** [sagemath/sage#34784]
<div id="comment:0"></div>

in (algebras, dynamics, matrix, schemes, categories) folders

Component: **refactoring**

Author: **Frédéric Chapoton**

Branch/Commit: **[`37067d0`](https://github.com/sagemath/sagetrac-mirror/commit/37067d08b700548ddd06b7a8ccd7f3d1452d08e1)**

Reviewer: **Kwankyu Lee**

_Issue created by migration from https://trac.sagemath.org/ticket/34784_

**Comment by fchapoton** [comment]
<div id="comment:1"></div>

New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/5417e7bc571f7ba919dd2055e12301444ce01477"><code>5417e7b</code></a></td><td><code>some care for E275 (algebras, dynamics, matrix, schemes, categories)</code></td></tr></table>

**Comment by fchapoton** [comment]
Commit: **[`5417e7b`](https://github.com/sagemath/sagetrac-mirror/commit/5417e7bc571f7ba919dd2055e12301444ce01477)**

**Comment by fchapoton** [comment]
Branch: **[u/chapoton/34784](https://github.com/sagemath/sagetrac-mirror/tree/u/chapoton/34784)**

**Comment by kwankyu** [comment]
<div id="comment:2" align="right">comment:2</div>

Space after comma in this line and many more after:

```diff
-                    else("T{}".format(p._names[p._index_to_pos[k[0]]]),v) \
+                    else ("T{}".format(p._names[p._index_to_pos[k[0]]]),v) \
```

This

```diff
             terms = [("T^({0}){1}".format(k[1], p._repr_generator(k[0])),v)\
-                      if k[1] > 1 else("T{}".format(p._repr_generator(k[0])),v)\
-                      if k[1] == 1 else ("{}".format(p._repr_generator(k[0])),
-                      v) for k,v in self.monomial_coefficients().items()]
+                     if k[1] > 1 else ("T{}".format(p._repr_generator(k[0])),v)\
+                     if k[1] == 1 else ("{}".format(p._repr_generator(k[0])),v)
+                     for k, v in self.monomial_coefficients().items()]
```
really needs a massive rewriting but at least 

```
   [... if ...
    else ... if ...
    else ...
    for ...]
```
would make it more readable.

This 

```diff
             terms = [("T^{{({0})}}{1}".format(k[1], latex(k[0])),v) if k[1] > 1 \
-                      else("T{}".format(latex(k[0])),v) if k[1] == 1 \
+                      else ("T{}".format(latex(k[0])),v) if k[1] == 1 \
                         else ("{}".format(latex(k[0])),v)\
                         for k, v in self.monomial_coefficients().items()]
```
needs to make `else` and `for` below aligned.

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
Changed commit from **[`5417e7b`](https://github.com/sagemath/sagetrac-mirror/commit/5417e7bc571f7ba919dd2055e12301444ce01477)** to **[`37067d0`](https://github.com/sagemath/sagetrac-mirror/commit/37067d08b700548ddd06b7a8ccd7f3d1452d08e1)**

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
<div id="comment:3"></div>

Branch pushed to git repo; I updated commit sha1. New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/37067d08b700548ddd06b7a8ccd7f3d1452d08e1"><code>37067d0</code></a></td><td><code>more tweaks (unrelated)</code></td></tr></table>

**Comment by fchapoton** [comment]
<div id="comment:4" align="right">comment:4</div>

voilà, done

**Comment by kwankyu** [comment]
Reviewer: **Kwankyu Lee**

**Comment by kwankyu** [comment]
<div id="comment:5" align="right">comment:5</div>

LGTM. Set positive review when Build & Test passes.

**Comment by fchapoton** [comment]
<div id="comment:6" align="right">comment:6</div>

thanks a lot

setting to positive

**Comment by vbraun** [comment]
Changed branch from **[u/chapoton/34784](https://github.com/sagemath/sagetrac-mirror/tree/u/chapoton/34784)** to **[`37067d0`](https://github.com/sagemath/sagetrac-mirror/commit/37067d08b700548ddd06b7a8ccd7f3d1452d08e1)**
