### ISSUE TITLE
some formatting for NOTE:: blocks

### ISSUE THREAD

**Issue by fchapoton** [sagemath/sage#34797]
<div id="comment:0"></div>

mostly in pyx files

Component: **documentation**

Author: **Frédéric Chapoton**

Branch/Commit: **[`8169b3a`](https://github.com/sagemath/sagetrac-mirror/commit/8169b3a9c502177e22b852894997d4fc724c7374)**

Reviewer: **David Coudert**

_Issue created by migration from https://trac.sagemath.org/ticket/34797_

**Comment by fchapoton** [comment]
Branch: **[u/chapoton/34797](https://github.com/sagemath/sagetrac-mirror/tree/u/chapoton/34797)**

**Comment by fchapoton** [comment]
<div id="comment:1"></div>

New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/8169b3a9c502177e22b852894997d4fc724c7374"><code>8169b3a</code></a></td><td><code>some formatting for NOTE:: blocks</code></td></tr></table>

**Comment by fchapoton** [comment]
Commit: **[`8169b3a`](https://github.com/sagemath/sagetrac-mirror/commit/8169b3a9c502177e22b852894997d4fc724c7374)**

**Comment by dcoudert** [comment]
<div id="comment:2" align="right">comment:2</div>

in `src/sage/rings/tate_algebra_element.pyx`, why are you doing this change ?

```diff
-        NOTE::
+        NOTE:
```

**Comment by fchapoton** [comment]
<div id="comment:3" align="right">comment:3</div>

Because the content, currently not indented, is a long explanation containing a nested list. I decided it was better for the moment to keep it unidented. I do not fix in this ticket the many occurences of "NOTE:".

**Comment by dcoudert** [comment]
Reviewer: **David Coudert**

**Comment by dcoudert** [comment]
<div id="comment:4" align="right">comment:4</div>

I understand. Thanks.

LGTM.

**Comment by vbraun** [comment]
Changed branch from **[u/chapoton/34797](https://github.com/sagemath/sagetrac-mirror/tree/u/chapoton/34797)** to **[`8169b3a`](https://github.com/sagemath/sagetrac-mirror/commit/8169b3a9c502177e22b852894997d4fc724c7374)**
