### ISSUE TITLE
Slight documentation update for modules built upon a FiniteRankFreeModule

### ISSUE THREAD

**Issue by egourgoulhon** [sagemath/sage#34792]
<div id="comment:0"></div>

After #34424 (merged in Sage 9.7.rc0), the documentation of `TensorFreeModule`, `ExtPowerFreeModule` and `ExtPowerDualFreeModule` should say that these classes inherit from `FiniteRankFreeModule_abstract`, not `FiniteRankFreeModule`.

CC:  @mkoeppe

Component: **linear algebra**

Keywords: **tensor**

Author: **Eric Gourgoulhon**

Branch/Commit: **[`fbfb3e2`](https://github.com/sagemath/sagetrac-mirror/commit/fbfb3e2eaa79e480a7d9bf50f11caa6aee20655a)**

Reviewer: **Matthias Koeppe**

_Issue created by migration from https://trac.sagemath.org/ticket/34792_

**Comment by egourgoulhon** [comment]
Branch: **[public/manifolds/update_documentation_tensor-34792](https://github.com/sagemath/sagetrac-mirror/tree/public/manifolds/update_documentation_tensor-34792)**

**Comment by egourgoulhon** [comment]
<div id="comment:1"></div>

New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/fbfb3e2eaa79e480a7d9bf50f11caa6aee20655a"><code>fbfb3e2</code></a></td><td><code>Update documentation for modules built upon a FiniteRankFreeModule (#34792)</code></td></tr></table>

**Comment by egourgoulhon** [comment]
Commit: **[`fbfb3e2`](https://github.com/sagemath/sagetrac-mirror/commit/fbfb3e2eaa79e480a7d9bf50f11caa6aee20655a)**

**Comment by mkoeppe** [comment]
Reviewer: **Matthias Koeppe**

**Comment by egourgoulhon** [comment]
<div id="comment:4" align="right">comment:4</div>

Thank you!

**Comment by vbraun** [comment]
Changed branch from **[public/manifolds/update_documentation_tensor-34792](https://github.com/sagemath/sagetrac-mirror/tree/public/manifolds/update_documentation_tensor-34792)** to **[`fbfb3e2`](https://github.com/sagemath/sagetrac-mirror/commit/fbfb3e2eaa79e480a7d9bf50f11caa6aee20655a)**
