### ISSUE TITLE
clean 3 files inside modular

### ISSUE THREAD

**Issue by fchapoton** [sagemath/sage#34793]
<div id="comment:0"></div>

mostly pep8 changes, also some error messages and doc formatting

Component: **modular forms**

Author: **Frédéric Chapoton**

Branch/Commit: **[`f65cf46`](https://github.com/sagemath/sagetrac-mirror/commit/f65cf462c7079ba1a87f43c00635885b716da7d8)**

Reviewer: **David Coudert**

_Issue created by migration from https://trac.sagemath.org/ticket/34793_

**Comment by fchapoton** [comment]
Commit: **[`0a4683f`](https://github.com/sagemath/sagetrac-mirror/commit/0a4683f0a7ffccf43ba46c95f93822057e645a64)**

**Comment by fchapoton** [comment]
Branch: **[u/chapoton/34793](https://github.com/sagemath/sagetrac-mirror/tree/u/chapoton/34793)**

**Comment by fchapoton** [comment]
<div id="comment:1"></div>

New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/0a4683f0a7ffccf43ba46c95f93822057e645a64"><code>0a4683f</code></a></td><td><code>cleanup of 3 files inside modular</code></td></tr></table>

**Comment by dcoudert** [comment]
<div id="comment:2" align="right">comment:2</div>

In `src/sage/modular/hecke/ambient_module.py`
- `Return True if and only if self is an ambient Hecke module.` -> <code>Return \`\`True\`\` if and only if self is an ambient Hecke module.</code>
- also for `Return True if this space is invariant under the action of`
- also for `Return True if and only if self is a submodule of V. Since this is an`

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
Changed commit from **[`0a4683f`](https://github.com/sagemath/sagetrac-mirror/commit/0a4683f0a7ffccf43ba46c95f93822057e645a64)** to **[`b56c781`](https://github.com/sagemath/sagetrac-mirror/commit/b56c78122419356a981e21c1a00753557bedb533)**

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
<div id="comment:3"></div>

Branch pushed to git repo; I updated commit sha1. New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/b56c78122419356a981e21c1a00753557bedb533"><code>b56c781</code></a></td><td><code>some details</code></td></tr></table>

**Comment by fchapoton** [comment]
<div id="comment:4" align="right">comment:4</div>

voilà

**Comment by dcoudert** [comment]
<div id="comment:5" align="right">comment:5</div>

LGTM.

**Comment by dcoudert** [comment]
Reviewer: **David Coudert**

**Comment by vbraun** [comment]
<div id="comment:7" align="right">comment:7</div>


```
sage -t --long --warn-long 37.0 --random-seed=123 src/sage/modular/hecke/degenmap.py
**********************************************************************
File "src/sage/modular/hecke/degenmap.py", line 56, in sage.modular.hecke.degenmap.DegeneracyMap
Failed example:
    d = M.degeneracy_map(11,2)
Expected:
    Traceback (most recent call last):
    ...
    ValueError: The level of self (=33) must be a divisor or multiple of level (=11), and t (=2) must be a divisor of the quotient.
Got:
    <BLANKLINE>
    Traceback (most recent call last):
      File "/home/release/Sage/src/sage/doctest/forker.py", line 695, in _run
        self.compile_and_execute(example, compiler, test.globs)
      File "/home/release/Sage/src/sage/doctest/forker.py", line 1093, in compile_and_execute
        exec(compiled, globs)
      File "<doctest sage.modular.hecke.degenmap.DegeneracyMap[6]>", line 1, in <module>
        d = M.degeneracy_map(Integer(11),Integer(2))
      File "/home/release/Sage/src/sage/modular/hecke/ambient_module.py", line 391, in degeneracy_map
        raise ValueError(("the level of self (=%s) must be a divisor or multiple of "
    ValueError: the level of self (=33) must be a divisor or multiple of level (=11) and t (=2) must be a divisor of the quotient
**********************************************************************
1 item had failures:
   1 of   9 in sage.modular.hecke.degenmap.DegeneracyMap
    [15 tests, 1 failure, 0.08 s]
----------------------------------------------------------------------
sage -t --long --warn-long 37.0 --random-seed=123 src/sage/modular/hecke/degenmap.py  # 1 doctest failed
----------------------------------------------------------------------
```

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
Changed commit from **[`b56c781`](https://github.com/sagemath/sagetrac-mirror/commit/b56c78122419356a981e21c1a00753557bedb533)** to **[`f65cf46`](https://github.com/sagemath/sagetrac-mirror/commit/f65cf462c7079ba1a87f43c00635885b716da7d8)**

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
<div id="comment:8"></div>

Branch pushed to git repo; I updated commit sha1. New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/8a74ab8fd785ced3079b37bc9dd0dc1e8a6bdf2b"><code>8a74ab8</code></a></td><td><code>Merge branch 'u/chapoton/34793' in 9.8.beta5</code></td></tr><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/f65cf462c7079ba1a87f43c00635885b716da7d8"><code>f65cf46</code></a></td><td><code>fix doctest</code></td></tr></table>

**Comment by fchapoton** [comment]
<div id="comment:9" align="right">comment:9</div>

setting back to positive after trivial doctest fix

**Comment by vbraun** [comment]
Changed branch from **[u/chapoton/34793](https://github.com/sagemath/sagetrac-mirror/tree/u/chapoton/34793)** to **[`f65cf46`](https://github.com/sagemath/sagetrac-mirror/commit/f65cf462c7079ba1a87f43c00635885b716da7d8)**
