### ISSUE TITLE
Upgrade matplotlib to 3.6

### ISSUE THREAD

**Issue by mkoeppe** [sagemath/sage#34796]
<div id="comment:0"></div>

As matplotlib 3.6 dependency, new standard package `contourpy` is added. 

Depends on #34693

Component: **packages: standard**

Author: **Matthias Koeppe**

Branch/Commit: **[`dac5ece`](https://github.com/sagemath/sagetrac-mirror/commit/dac5eceb0ff5a9476a198ac2122b16c5aa956749)**

Reviewer: **Kwankyu Lee**

_Issue created by migration from https://trac.sagemath.org/ticket/34796_

**Comment by mkoeppe** [comment]
Branch: **[u/mkoeppe/upgrade_matplotlib_to_3_6](https://github.com/sagemath/sagetrac-mirror/tree/u/mkoeppe/upgrade_matplotlib_to_3_6)**

**Comment by mkoeppe** [comment]
Author: **Matthias Koeppe**

**Comment by mkoeppe** [comment]
<div id="comment:2"></div>

New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/8b0c147037018b77b5c8c5147e78c3c7c6388d29"><code>8b0c147</code></a></td><td><code>Merge branch 'mpl3.6_doctest' into mpl3.6_docbuilding</code></td></tr><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/4645a0d0c10f9f1599aa01362593195af6d27a16"><code>4645a0d</code></a></td><td><code>Removing faulty plot</code></td></tr><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/20206ff1b9cccf1f9d4842af70ecc50aeeed17e5"><code>20206ff</code></a></td><td><code>Merge #34693</code></td></tr><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/e96e7a64284e6e24ca50d57fe612610b3b52a6e6"><code>e96e7a6</code></a></td><td><code>build/pkgs/matplotlib: Update to 3.6.2</code></td></tr><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/18a9e232160df764758fb1da52c3ae1f4e70b420"><code>18a9e23</code></a></td><td><code>build/pkgs/matplotlib_inline: Update to 0.1.6</code></td></tr></table>

**Comment by mkoeppe** [comment]
Commit: **[`18a9e23`](https://github.com/sagemath/sagetrac-mirror/commit/18a9e232160df764758fb1da52c3ae1f4e70b420)**

**Comment by mkoeppe** [comment]
<div id="comment:3" align="right">comment:3</div>

needs setuptools_scm>=7

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
<div id="comment:4"></div>

Branch pushed to git repo; I updated commit sha1. New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/ed959c1b55b5cc0adf78a25531d1852dd829e9a5"><code>ed959c1</code></a></td><td><code>build/pkgs/setuptools_scm: Update to 7.0.5</code></td></tr><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/df9d613c576a21c93e5e67a5113f3fd555a06209"><code>df9d613</code></a></td><td><code>build/pkgs/setuptools_scm_git_archive: Update to 1.4</code></td></tr><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/0ecabe5b52d42b014845aeb48473291e8fdf14f6"><code>0ecabe5</code></a></td><td><code>build/pkgs/contourpy: New (matplotlib dependency)</code></td></tr></table>

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
Changed commit from **[`18a9e23`](https://github.com/sagemath/sagetrac-mirror/commit/18a9e232160df764758fb1da52c3ae1f4e70b420)** to **[`0ecabe5`](https://github.com/sagemath/sagetrac-mirror/commit/0ecabe5b52d42b014845aeb48473291e8fdf14f6)**

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
Changed commit from **[`0ecabe5`](https://github.com/sagemath/sagetrac-mirror/commit/0ecabe5b52d42b014845aeb48473291e8fdf14f6)** to **[`bd54629`](https://github.com/sagemath/sagetrac-mirror/commit/bd54629a76a447bfcf31feaf631d6454af95ce51)**

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
<div id="comment:5"></div>

Branch pushed to git repo; I updated commit sha1. New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/f0a77039bb2be3eb7cd06c036aaa8085652db403"><code>f0a7703</code></a></td><td><code>Add back doctest</code></td></tr><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/8371dd75013d5b973333b6e577e7ef17bbf042c1"><code>8371dd7</code></a></td><td><code>Missing part of the fix</code></td></tr><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/dbfb9539ab9bbb5b2e460f4c4576835c58e84a2e"><code>dbfb953</code></a></td><td><code>Merge branch 'develop' into t/34693/MPL3.6_docbuilding</code></td></tr><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/a8741d8c60dc3e173b18cc373c4c203fcc2cec4f"><code>a8741d8</code></a></td><td><code>Edit the doctest</code></td></tr><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/64589686c261d33e6b5aff2589bcae8af004bcc6"><code>6458968</code></a></td><td><code>More edis of the doctest</code></td></tr><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/bd54629a76a447bfcf31feaf631d6454af95ce51"><code>bd54629</code></a></td><td><code>Merge #34693</code></td></tr></table>

**Comment by kwankyu** [comment]
Changed branch from **[u/mkoeppe/upgrade_matplotlib_to_3_6](https://github.com/sagemath/sagetrac-mirror/tree/u/mkoeppe/upgrade_matplotlib_to_3_6)** to **[u/klee/upgrade_matplotlib_to_3_6](https://github.com/sagemath/sagetrac-mirror/tree/u/klee/upgrade_matplotlib_to_3_6)**

**Comment by kwankyu** [comment]
Reviewer: **Kwankyu Lee**

**Comment by kwankyu** [comment]
<div id="comment:8"></div>

New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/58800b09c3d043a1f30c0541b9f7be2f1061aa9d"><code>58800b0</code></a></td><td><code>A tiny edit to kick off testing</code></td></tr></table>

**Comment by kwankyu** [comment]
Changed commit from **[`bd54629`](https://github.com/sagemath/sagetrac-mirror/commit/bd54629a76a447bfcf31feaf631d6454af95ce51)** to **[`58800b0`](https://github.com/sagemath/sagetrac-mirror/commit/58800b09c3d043a1f30c0541b9f7be2f1061aa9d)**

**Comment by kwankyu** [comment]
<div id="comment:9" align="right">comment:9</div>

matplotlib seems (order-)dependent on contourpy.

**Comment by mkoeppe** [comment]
<div id="comment:10" align="right">comment:10</div>

Yes, looks I forgot to add the dependency.

**Comment by kwankyu** [comment]
Description changed:
``````diff
--- 
+++ 
@@ -1 +1 @@
-
+As matplotlib 3.6 dependency, new standard package `contourpy` is added. 
``````

**Comment by mkoeppe** [comment]
Changed branch from **[u/klee/upgrade_matplotlib_to_3_6](https://github.com/sagemath/sagetrac-mirror/tree/u/klee/upgrade_matplotlib_to_3_6)** to **[u/mkoeppe/upgrade_matplotlib_to_3_6](https://github.com/sagemath/sagetrac-mirror/tree/u/mkoeppe/upgrade_matplotlib_to_3_6)**

**Comment by mkoeppe** [comment]
<div id="comment:14"></div>

New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/dac5eceb0ff5a9476a198ac2122b16c5aa956749"><code>dac5ece</code></a></td><td><code>build/pkgs/matplotlib/dependencies: Add contourpy</code></td></tr></table>

**Comment by mkoeppe** [comment]
Changed commit from **[`58800b0`](https://github.com/sagemath/sagetrac-mirror/commit/58800b09c3d043a1f30c0541b9f7be2f1061aa9d)** to **[`dac5ece`](https://github.com/sagemath/sagetrac-mirror/commit/dac5eceb0ff5a9476a198ac2122b16c5aa956749)**

**Comment by kwankyu** [comment]
<div id="comment:15" align="right">comment:15</div>

Build&Test passed green.

**Comment by mkoeppe** [comment]
<div id="comment:16" align="right">comment:16</div>

Thanks!

**Comment by vbraun** [comment]
Changed branch from **[u/mkoeppe/upgrade_matplotlib_to_3_6](https://github.com/sagemath/sagetrac-mirror/tree/u/mkoeppe/upgrade_matplotlib_to_3_6)** to **[`dac5ece`](https://github.com/sagemath/sagetrac-mirror/commit/dac5eceb0ff5a9476a198ac2122b16c5aa956749)**
