### ISSUE TITLE
Upgrade pybind11, docutils and other packages

### ISSUE THREAD

**Issue by mkoeppe** [sagemath/sage#34795]
<div id="comment:0"></div>

The pybind11 upgrade brings full support for python 3.11

The docutils upgrade avoids deprecation warnings with python 3.11

CC:  @dimpase @kwankyu @vbraun

Component: **packages: standard**

Author: **Matthias Koeppe**

Branch/Commit: **[`3666918`](https://github.com/sagemath/sagetrac-mirror/commit/366691865cfd4f36c48f6409e4a7da073472382b)**

Reviewer: **Dima Pasechnik**

_Issue created by migration from https://trac.sagemath.org/ticket/34795_

**Comment by mkoeppe** [comment]
Branch: **[u/mkoeppe/upgrade_pybind11_and_other_packages](https://github.com/sagemath/sagetrac-mirror/tree/u/mkoeppe/upgrade_pybind11_and_other_packages)**

**Comment by mkoeppe** [comment]
Author: **Matthias Koeppe**

**Comment by mkoeppe** [comment]
Description changed:
``````diff
--- 
+++ 
@@ -1 +1 @@
-
+The pybind11 upgrade brings full support for python 3.11
``````

**Comment by mkoeppe** [comment]
<div id="comment:2"></div>

Last 10 new commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/929838645671ea85294a3933e9ef14e0d538a375"><code>9298386</code></a></td><td><code>build/pkgs/hatch_nodejs_version: Update to 0.3.1</code></td></tr><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/6814586e72a856a0d1178e5ebf2b317495bd76c9"><code>6814586</code></a></td><td><code>build/pkgs/importlib_metadata: Update to 5.1.0</code></td></tr><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/83330f928be369326db9d68a7696ce10902ad2fa"><code>83330f9</code></a></td><td><code>build/pkgs/gmpy2: Update to 2.1.2</code></td></tr><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/ecaa5ea96274bbb3daa6364c651486b501f10658"><code>ecaa5ea</code></a></td><td><code>build/pkgs/docutils: Update to 0.19</code></td></tr><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/8a16149424d22414007157dc9da4944de4e89794"><code>8a16149</code></a></td><td><code>build/pkgs/cppy: Update to 1.2.1</code></td></tr><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/ff22d08b9449e2b064b83ac296f11fa8b747b953"><code>ff22d08</code></a></td><td><code>build/pkgs/argon2_cffi: Update to 21.3.0</code></td></tr><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/4814efc25836152485561c821b8c9c0c8241031d"><code>4814efc</code></a></td><td><code>build/pkgs/attrs: Update to 22.1.0</code></td></tr><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/6b9fbb1dbd16a21182ffdf575450de691d4aa099"><code>6b9fbb1</code></a></td><td><code>build/pkgs/pip: Update to 22.3.1</code></td></tr><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/7432ba944dfd76c5310d5cedfed113e828e85c47"><code>7432ba9</code></a></td><td><code>build/pkgs/texttable: Update to 1.6.7</code></td></tr><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/366691865cfd4f36c48f6409e4a7da073472382b"><code>3666918</code></a></td><td><code>build/pkgs/stack_data: Update to 0.6.1</code></td></tr></table>

**Comment by mkoeppe** [comment]
Commit: **[`3666918`](https://github.com/sagemath/sagetrac-mirror/commit/366691865cfd4f36c48f6409e4a7da073472382b)**

**Comment by mkoeppe** [comment]
<div id="comment:6" align="right">comment:6</div>

needed for the python 3.11 upgrade - #33842

**Comment by mkoeppe** [comment]
Description changed:
``````diff
--- 
+++ 
@@ -1 +1,3 @@
 The pybind11 upgrade brings full support for python 3.11
+
+The docutils upgrade avoids deprecation warnings with python 3.11
``````

**Comment by dimpase** [comment]
Reviewer: **Dima Pasechnik**

**Comment by dimpase** [comment]
<div id="comment:8" align="right">comment:8</div>

lgtm

**Comment by mkoeppe** [comment]
<div id="comment:9" align="right">comment:9</div>

Thanks!

**Comment by vbraun** [comment]
Changed branch from **[u/mkoeppe/upgrade_pybind11_and_other_packages](https://github.com/sagemath/sagetrac-mirror/tree/u/mkoeppe/upgrade_pybind11_and_other_packages)** to **[`3666918`](https://github.com/sagemath/sagetrac-mirror/commit/366691865cfd4f36c48f6409e4a7da073472382b)**
