### ISSUE TITLE
fix order of multiplication in coxeter_groups

### ISSUE THREAD

**Issue by mantepse** [sagemath/sage#34799]
<div id="comment:0"></div>

The method `pi.binary_factorizations` silently returned wrong results for elements in `Permutations(n)`, because the order of multiplication was wrong.

I also add some tests.

CC:  @tscrim

Component: **categories**

Author: **Martin Rubey**

Branch/Commit: **[`37d60d4`](https://github.com/sagemath/sagetrac-mirror/commit/37d60d4b87569ed4524fc76c5aeeb2984e683c92)**

Reviewer: **Travis Scrimshaw**

_Issue created by migration from https://trac.sagemath.org/ticket/34799_

**Comment by mantepse** [comment]
Branch: **[u/mantepse/fix_order_of_multiplication](https://github.com/sagemath/sagetrac-mirror/tree/u/mantepse/fix_order_of_multiplication)**

**Comment by mantepse** [comment]
Commit: **[`6d59adc`](https://github.com/sagemath/sagetrac-mirror/commit/6d59adca722d846d1f9d618a38c5b3e8bd3595ea)**

**Comment by mantepse** [comment]
Author: **Martin Rubey**

**Comment by mantepse** [comment]
<div id="comment:2"></div>

New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/6d59adca722d846d1f9d618a38c5b3e8bd3595ea"><code>6d59adc</code></a></td><td><code>fix order of multiplication in binary_factorizations</code></td></tr></table>

**Comment by mantepse** [comment]
Description changed:
``````diff
--- 
+++ 
@@ -1 +1,3 @@
+The method `pi.binary_factorizations` silently returned wrong results for elements in `Permutations(n)`, because the order of multiplication was wrong.
 
+I also add some tests.
``````

**Comment by tscrim** [comment]
<div id="comment:3" align="right">comment:3</div>

Another test that would be good is also changing the multiplication rule for permutations.

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
<div id="comment:4"></div>

Branch pushed to git repo; I updated commit sha1. New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/37d60d4b87569ed4524fc76c5aeeb2984e683c92"><code>37d60d4</code></a></td><td><code>tests also the option setting multiplication order</code></td></tr></table>

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
Changed commit from **[`6d59adc`](https://github.com/sagemath/sagetrac-mirror/commit/6d59adca722d846d1f9d618a38c5b3e8bd3595ea)** to **[`37d60d4`](https://github.com/sagemath/sagetrac-mirror/commit/37d60d4b87569ed4524fc76c5aeeb2984e683c92)**

**Comment by tscrim** [comment]
Reviewer: **Travis Scrimshaw**

**Comment by tscrim** [comment]
<div id="comment:5" align="right">comment:5</div>

Thank you. LGTM.

**Comment by vbraun** [comment]
Changed branch from **[u/mantepse/fix_order_of_multiplication](https://github.com/sagemath/sagetrac-mirror/tree/u/mantepse/fix_order_of_multiplication)** to **[`37d60d4`](https://github.com/sagemath/sagetrac-mirror/commit/37d60d4b87569ed4524fc76c5aeeb2984e683c92)**
