### ISSUE TITLE
move ProductTree and prod_with_derivative() to sage.rings.generic

### ISSUE THREAD

**Issue by yyyyx4** [sagemath/sage#34791]
<div id="comment:0"></div>

The class `ProductTree` and the function `prod_with_derivative()` were introduced in #34303. Both are fully generic in principle, but they remained in `hom_velusqrt.py` in the heat of the moment.

We should move them to a more suitable place; it seems `sage.rings.generic` is an appropriate choice. Slight tweaks to `ProductTree` while we're at it.

CC:  @jhpalmieri

Component: **algebra**

Author: **Lorenz Panny**

Branch/Commit: **[`c3dcb9b`](https://github.com/sagemath/sagetrac-mirror/commit/c3dcb9b011463d2c0ece76ac9382fac1d9e9ced0)**

Reviewer: **Kwankyu Lee**

_Issue created by migration from https://trac.sagemath.org/ticket/34791_

**Comment by yyyyx4** [comment]
Description changed:
``````diff
--- 
+++ 
@@ -1,4 +1,4 @@
-The class `ProductTree` and the function `prod_with_derivative()` were introduced in #34303. Both are fully generic in principle, but they were included in `hom_velusqrt.py` in the heat of the moment.
+The class `ProductTree` and the function `prod_with_derivative()` were introduced in #34303. Both are fully generic in principle, but they remained in `hom_velusqrt.py` in the heat of the moment.
 
-We should move them to a more suitable place; it seems `sage.arith.misc` is an appropriate choice. While we're at it, slight tweaks to `ProductTree`, and I believe importing it by default is a good idea to increase visibility and ease of use.
+We should move them to a more suitable place; it seems `sage.arith.misc` is an appropriate choice. Slight tweaks to `ProductTree` while we're at it, and I believe importing it by default is a good idea to increase visibility and ease of use.
 
``````

**Comment by mezzarobba** [comment]
<div id="comment:2" align="right">comment:2</div>

I think `ProductTree` could even go to its own file, since it may well be extended or ported to cython. Also, most of `misc.py` has a more number-theoretic flavor. (But that's just a suggestion and I'm fine with `misc.py` too.)

**Comment by yyyyx4** [comment]
<div id="comment:3" align="right">comment:3</div>

Currently `sage.misc.misc_c` contains the highly related `prod()` function. I think this could also be in a location such as `sage.rings.generic` (which doesn't currently exist), similar to how `sage.groups.generic` contains generic-group algorithms. Personally I don't have a preference.

**Comment by kwankyu** [comment]
<div id="comment:4" align="right">comment:4</div>

> I believe importing it by default is a good idea to increase visibility and ease of use.

-1. I don't think it has so general use. But I would hear John.

**Comment by jhpalmieri** [comment]
<div id="comment:5" align="right">comment:5</div>

First, especially if there might be expansions to `ProductTree`, it might very well make sense to put it in its own file. Second, regarding increased visibility, I would say no right now. For example I look at the documentation and I can't tell what it does. (There is one line of description, "A simple product tree," there is one line saying what the inputs are, and that's pretty much the extent of the documentation. I think it should have much more.) You should make sure it's in the reference manual, and if you think it's particularly useful, write a thematic tutorial about it and add that to the documentation — that's a good way to increase visibility.

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
Changed commit from **[`3ff3cdf`](https://github.com/sagemath/sagetrac-mirror/commit/3ff3cdf572d96d4541c0246216e034ccbc053de3)** to **[`8e6d94c`](https://github.com/sagemath/sagetrac-mirror/commit/8e6d94ca3aae8944524870e03c8ce26112a0cec0)**

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
<div id="comment:6"></div>

Branch pushed to git repo; I updated commit sha1. New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/8e6d94ca3aae8944524870e03c8ce26112a0cec0"><code>8e6d94c</code></a></td><td><code>Revert "import ProductTree with sage.arith.all"</code></td></tr></table>

**Comment by kwankyu** [comment]
<div id="comment:7" align="right">comment:7</div>

Replying to [John Palmieri](#comment%3A5):
> For example I look at the documentation and I can't tell what it does. (There is one line of description, "A simple product tree," there is one line saying what the inputs are, and that's pretty much the extent of the documentation. I think it should have much more.) 

+1. In the `ProductTree` class docstring, there is no description about a product tree. It may be described in terms of leaves, layers, and the root in a couple of sentences.

Instead of `a sequence of` (which sounds mathematical), `a list of` would be pythonic, and avoid an unnecessary confusion.

The `ALGORITHM` section of `prod_with_derivative` just describes the source code. Thus it is too much detailed but useless for a user. I suggest to remove it.

The paragraph `The main reason for this function ...` may be moved up and replace the aforementioned `ALGORITHM` section.

**Comment by yyyyx4** [comment]
<div id="comment:8" align="right">comment:8</div>

Thanks for the feedback, everyone. I'll work on the documentation.

Replying to [Kwankyu Lee](#comment%3A7):
> Instead of `a sequence of` (which sounds mathematical), `a list of` would be pythonic, and avoid an unnecessary confusion.

But in Python "a list" is much more specific than "a sequence"! For example, a tuple is a sequence but not a list. Indeed, the Python documentation does have a concept of "sequence": https://docs.python.org/3/library/stdtypes.html#sequence-types-list-tuple-range

> The paragraph `The main reason for this function ...` may be moved up and replace the aforementioned `ALGORITHM` section.

Are you suggesting to move it outside of the`EXAMPLES` block? Or just swap the two examples?

**Comment by kwankyu** [comment]
<div id="comment:9" align="right">comment:9</div>

Replying to [Lorenz Panny](#comment%3A8):
> Thanks for the feedback, everyone. I'll work on the documentation.
> 
> Replying to [Kwankyu Lee](#comment%3A7):
> > Instead of `a sequence of` (which sounds mathematical), `a list of` would be pythonic, and avoid an unnecessary confusion.
> 
> 
> But in Python "a list" is much more specific than "a sequence"! For example, a tuple is a sequence but not a list. Indeed, the Python documentation does have a concept of "sequence": https://docs.python.org/3/library/stdtypes.html#sequence-types-list-tuple-range

Strictly speaking, you are right. But it is usual to say "a tuple of" or "a list of" when an input of any sequence type is allowed. I think it is rather unusual to say "a sequence of" for an input of a sequence type (it makes one to think twice).

Again this is not a rule, but a suggestion of a style for uniformity.

> > The paragraph `The main reason for this function ...` may be moved up and replace the aforementioned `ALGORITHM` section.
> 
> 
> Are you suggesting to move it outside of the`EXAMPLES` block? Or just swap the two examples?

To move it to the place of `ALGORITHM` (perhaps removing `alpha`). If you do not, please write a new paragraph to explain the purpose (or usage) of the function at the place of the removed `ALGORITHM`.

**Comment by kwankyu** [comment]
Reviewer: **Kwankyu Lee**

**Comment by jhpalmieri** [comment]
<div id="comment:11" align="right">comment:11</div>

Replying to [Kwankyu Lee](#comment%3A9):
> Replying to [Lorenz Panny](#comment%3A8):
> > Thanks for the feedback, everyone. I'll work on the documentation.
> > 
> > Replying to [Kwankyu Lee](#comment%3A7):
> > > Instead of `a sequence of` (which sounds mathematical), `a list of` would be pythonic, and avoid an unnecessary confusion.
> > 
> > 
> > But in Python "a list" is much more specific than "a sequence"! For example, a tuple is a sequence but not a list. Indeed, the Python documentation does have a concept of "sequence": https://docs.python.org/3/library/stdtypes.html#sequence-types-list-tuple-range
> 
> 
> Strictly speaking, you are right. But it is usual to say "a tuple of" or "a list of" when an input of any sequence type is allowed. I think it is rather unusual to say "a sequence of" for an input of a sequence type (it makes one to think twice).
> 
> Again this is not a rule, but a suggestion of a style for uniformity.

I've seen "an iterable" used in documentation. That would be another option.

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
Changed commit from **[`8e6d94c`](https://github.com/sagemath/sagetrac-mirror/commit/8e6d94ca3aae8944524870e03c8ce26112a0cec0)** to **[`9ad5848`](https://github.com/sagemath/sagetrac-mirror/commit/9ad584887556a199b79abe79b182cd0d3d5c065f)**

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
<div id="comment:12"></div>

Branch pushed to git repo; I updated commit sha1. New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/6ff8acf01c44fa29a64ff1f7ccaa3752df33ad80"><code>6ff8acf</code></a></td><td><code>Merge tag '9.8.beta5' into public/move_product_tree_and_prod_with_derivatives</code></td></tr><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/6fffd92c03dab44798b4071cdd1c311ec5fdc304"><code>6fffd92</code></a></td><td><code>more detailed documentation</code></td></tr><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/cd1a78268b52657e66f99125a80f9b985e6be692"><code>cd1a782</code></a></td><td><code>move ProductTree and prod_with_derivative() to sage.rings.generic</code></td></tr><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/77a75eae9ab68a7f53790475dd426bcc0169a50d"><code>77a75ea</code></a></td><td><code>sequence -> iterable</code></td></tr><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/9ad584887556a199b79abe79b182cd0d3d5c065f"><code>9ad5848</code></a></td><td><code>illustrate correctness of DFT example</code></td></tr></table>

**Comment by yyyyx4** [comment]
<div id="comment:13" align="right">comment:13</div>

Tweaked documentation according to your suggestions, and moved the code in question to a new file `sage.rings.generic`. Some other functions from `sage.arith.misc` should probably also end up there, but perhaps not in this ticket.

(I didn't remove the `ALGORITHM:` block entirely, only reduced detail, and I clarified the text in the main docstring that was already alluding to the example instead of moving the example. Hopefully that'll make everyone happy.)

**Comment by kwankyu** [comment]
<div id="comment:14" align="right">comment:14</div>

Replying to [Lorenz Panny](#comment%3A13):
> ...Hopefully that'll make everyone happy.

Thanks. LGTM, though I am not completely happy with the overuse of `iterable` where common and simple `list` is enough. It's hard to make everyone happy :)

One last thing. Please insert spaces around `//` in

```diff
+            X = [X[i//2] % V[i] for i in range(len(V))]
```

You can set positive review for me. Thanks!

**Comment by kwankyu** [comment]
Description changed:
``````diff
--- 
+++ 
@@ -1,4 +1,4 @@
 The class `ProductTree` and the function `prod_with_derivative()` were introduced in #34303. Both are fully generic in principle, but they remained in `hom_velusqrt.py` in the heat of the moment.
 
-We should move them to a more suitable place; it seems `sage.arith.misc` is an appropriate choice. Slight tweaks to `ProductTree` while we're at it, and I believe importing it by default is a good idea to increase visibility and ease of use.
+We should move them to a more suitable place; it seems `sage.rings.generic` is an appropriate choice. Slight tweaks to `ProductTree` while we're at it, and I believe importing it by default is a good idea to increase visibility and ease of use.
 
``````

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
<div id="comment:16"></div>

Branch pushed to git repo; I updated commit sha1. New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/c3dcb9b011463d2c0ece76ac9382fac1d9e9ced0"><code>c3dcb9b</code></a></td><td><code>style tweak</code></td></tr></table>

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
Changed commit from **[`9ad5848`](https://github.com/sagemath/sagetrac-mirror/commit/9ad584887556a199b79abe79b182cd0d3d5c065f)** to **[`c3dcb9b`](https://github.com/sagemath/sagetrac-mirror/commit/c3dcb9b011463d2c0ece76ac9382fac1d9e9ced0)**

**Comment by yyyyx4** [comment]
<div id="comment:17" align="right">comment:17</div>

Thank you!

(By the way, regarding the "list" vs. "iterable" question, writing `list` has the opposite effect on me. It's the one that makes *me* think twice: Will passing a tuple or a generator work as well, and can I rely on it to keep working in the future? That's why I prefer specifying the correct technical requirement, even if such details are currently indeed rather non-uniform in the Sage codebase.)

**Comment by yyyyx4** [comment]
Description changed:
``````diff
--- 
+++ 
@@ -1,4 +1,4 @@
 The class `ProductTree` and the function `prod_with_derivative()` were introduced in #34303. Both are fully generic in principle, but they remained in `hom_velusqrt.py` in the heat of the moment.
 
-We should move them to a more suitable place; it seems `sage.rings.generic` is an appropriate choice. Slight tweaks to `ProductTree` while we're at it, and I believe importing it by default is a good idea to increase visibility and ease of use.
+We should move them to a more suitable place; it seems `sage.rings.generic` is an appropriate choice. Slight tweaks to `ProductTree` while we're at it.
 
``````

**Comment by kwankyu** [comment]
<div id="comment:18" align="right">comment:18</div>

Replying to [Lorenz Panny](#comment%3A17):
> ... writing `list` has the opposite effect on me. It's the one that makes *me* think twice: Will passing a tuple or a generator work as well, and can I rely on it to keep working in the future? That's why I prefer specifying the correct technical requirement, even if such details are currently indeed rather non-uniform in the Sage codebase.)

That is a good reason. Okay!

**Comment by vbraun** [comment]
Changed branch from **[public/move_product_tree_and_prod_with_derivatives](https://github.com/sagemath/sagetrac-mirror/tree/public/move_product_tree_and_prod_with_derivatives)** to **[`c3dcb9b`](https://github.com/sagemath/sagetrac-mirror/commit/c3dcb9b011463d2c0ece76ac9382fac1d9e9ced0)**
