### ISSUE TITLE
Run doc server along with jupyter server

### ISSUE THREAD

**Issue by kwankyu** [sagemath/sage#34794]
<div id="comment:0"></div>

Sage documentation links in `help` menu have been long broken in jupyterlab notebook interface, although they work fine in jupyter notebook interface.

Jupyterlab loads local files (sage documentation files) in `iframe` tag. This is problematic and it seems hopeless to make this work. A proper way is to run local http server serving the doc along with jupyter(lab) notebook server.

The branch uses thread parallelism to run sage doc server.

Try the branch with `sage --notebook=jupyterlab`. This runs a light-weight sage doc server at `http://localhost:<SAGE_DOC_LOCAL_PORT>`, where the environment variable `SAGE_DOC_LOCAL_PORT` defaults to 8000.

Set `export SAGE_DOC_SERVER_URL=https://doc.sagemath.org` before running `sage --notebook=jupyterlab` to use the public doc server. This will be useful for jupyterhub users.

Component: **notebook**

Author: **Kwankyu Lee**

Branch/Commit: **[public/run_doc_server](https://github.com/sagemath/sagetrac-mirror/tree/public/run_doc_server) @ [`70bdf46`](https://github.com/sagemath/sagetrac-mirror/commit/70bdf46e811b15d9886077ebdc5ce544626dc963)**

_Issue created by migration from https://trac.sagemath.org/ticket/34794_

**Comment by kwankyu** [comment]
Author: **Kwankyu Lee**

**Comment by kwankyu** [comment]
Description changed:
``````diff
--- 
+++ 
@@ -1 +1 @@
-
+Running jupyter notebook runs sage doc server along it so that sage documentation is available in notebook environment.
``````

**Comment by kwankyu** [comment]
Branch: **[u/klee/run_doc_server_along_with_jupyter_server](https://github.com/sagemath/sagetrac-mirror/tree/u/klee/run_doc_server_along_with_jupyter_server)**

**Comment by kwankyu** [comment]
Commit: **[`8b636bf`](https://github.com/sagemath/sagetrac-mirror/commit/8b636bf6ee8004ed21009876c5d0fa68be92325b)**

**Comment by kwankyu** [comment]
Changed branch from **[u/klee/run_doc_server_along_with_jupyter_server](https://github.com/sagemath/sagetrac-mirror/tree/u/klee/run_doc_server_along_with_jupyter_server)** to **[public/run_doc_server](https://github.com/sagemath/sagetrac-mirror/tree/public/run_doc_server)**

**Comment by kwankyu** [comment]
<div id="comment:3"></div>

New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/8b636bf6ee8004ed21009876c5d0fa68be92325b"><code>8b636bf</code></a></td><td><code>Run sage doc server for notebooks</code></td></tr></table>

**Comment by kwankyu** [comment]
Description changed:
``````diff
--- 
+++ 
@@ -1 +1,5 @@
-Running jupyter notebook runs sage doc server along it so that sage documentation is available in notebook environment.
+Sage documentation links in `help` menu has been long broken in jupyterlab notebook interface.
+
+A proper fix  is to run local http server serving sage doc along with jupyter(lab) notebook server.
+
+
``````

**Comment by kwankyu** [comment]
Description changed:
``````diff
--- 
+++ 
@@ -1,5 +1,7 @@
-Sage documentation links in `help` menu has been long broken in jupyterlab notebook interface.
+Sage documentation links in `help` menu have been long broken in jupyterlab notebook interface.
 
-A proper fix  is to run local http server serving sage doc along with jupyter(lab) notebook server.
+A proper fix is to run local http server serving sage doc along with jupyter(lab) notebook server.
+
+The branch uses thread parallelism to run sage doc server.
 
 
``````

**Comment by kwankyu** [comment]
Description changed:
``````diff
--- 
+++ 
@@ -4,4 +4,6 @@
 
 The branch uses thread parallelism to run sage doc server.
 
+Try the branch with `sage --notebook=jupyterlab`
 
+
``````

**Comment by kwankyu** [comment]
Description changed:
``````diff
--- 
+++ 
@@ -1,6 +1,6 @@
-Sage documentation links in `help` menu have been long broken in jupyterlab notebook interface.
+Sage documentation links in `help` menu have been long broken in jupyterlab notebook interface. By the way, they work well in jupyter notebook interface.
 
-A proper fix is to run local http server serving sage doc along with jupyter(lab) notebook server.
+Jupyterlab loads local files (sage documentation files) in `iframe` tag. This is problematic and it seems hopeless to make this work. A proper way is to run local http server serving the doc along with jupyter(lab) notebook server.
 
 The branch uses thread parallelism to run sage doc server.
 
``````

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
Changed commit from **[`8b636bf`](https://github.com/sagemath/sagetrac-mirror/commit/8b636bf6ee8004ed21009876c5d0fa68be92325b)** to **[`f3bf182`](https://github.com/sagemath/sagetrac-mirror/commit/f3bf1827a8720af3b81b657448f0e38d1cc3b798)**

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
<div id="comment:8"></div>

Branch pushed to git repo; I updated commit sha1. New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/f3bf1827a8720af3b81b657448f0e38d1cc3b798"><code>f3bf182</code></a></td><td><code>Edit messages</code></td></tr></table>

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
<div id="comment:9"></div>

Branch pushed to git repo; I updated commit sha1. New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/70bdf46e811b15d9886077ebdc5ce544626dc963"><code>70bdf46</code></a></td><td><code>Support SAGE_DOC_SERVER_URL for non-local doc server</code></td></tr></table>

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
Changed commit from **[`f3bf182`](https://github.com/sagemath/sagetrac-mirror/commit/f3bf1827a8720af3b81b657448f0e38d1cc3b798)** to **[`70bdf46`](https://github.com/sagemath/sagetrac-mirror/commit/70bdf46e811b15d9886077ebdc5ce544626dc963)**

**Comment by kwankyu** [comment]
Description changed:
``````diff
--- 
+++ 
@@ -4,6 +4,8 @@
 
 The branch uses thread parallelism to run sage doc server.
 
-Try the branch with `sage --notebook=jupyterlab`
+Try the branch with `sage --notebook=jupyterlab`. This runs a light-weight sage doc server at `http://localhost:<SAGE_DOC_LOCAL_PORT>`, where the environment variable `SAGE_DOC_LOCAL_PORT` defaults to 8000.
+
+Set `export SAGE_DOC_SERVER_URL=https://doc.sagemath.org` before running `sage --notebook=jupyterlab` to use the public doc server. This will be useful for jupyterhub users.
 
 
``````

**Comment by kwankyu** [comment]
Description changed:
``````diff
--- 
+++ 
@@ -1,4 +1,4 @@
-Sage documentation links in `help` menu have been long broken in jupyterlab notebook interface. By the way, they work well in jupyter notebook interface.
+Sage documentation links in `help` menu have been long broken in jupyterlab notebook interface, although they work fine in jupyter notebook interface.
 
 Jupyterlab loads local files (sage documentation files) in `iframe` tag. This is problematic and it seems hopeless to make this work. A proper way is to run local http server serving the doc along with jupyter(lab) notebook server.
 
``````
