### ISSUE TITLE
less use of type "long" in cython files

### ISSUE THREAD

**Issue by fchapoton** [sagemath/sage#34798]
<div id="comment:0"></div>

sequel of #34739

CC:  @kwankyu @kliem @dcoudert

Component: **refactoring**

Author: **Frédéric Chapoton**

Branch/Commit: **[`8fc9e87`](https://github.com/sagemath/sagetrac-mirror/commit/8fc9e87186d9ae1483fe1b8ae8ffdd1c071e5c77)**

Reviewer: **Kwankyu Lee**

_Issue created by migration from https://trac.sagemath.org/ticket/34798_

**Comment by fchapoton** [comment]
Branch: **[u/chapoton/34798](https://github.com/sagemath/sagetrac-mirror/tree/u/chapoton/34798)**

**Comment by fchapoton** [comment]
<div id="comment:1"></div>

New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/8fc9e87186d9ae1483fe1b8ae8ffdd1c071e5c77"><code>8fc9e87</code></a></td><td><code>less use of type "long" in pyx files (outside of p-adics)</code></td></tr></table>

**Comment by fchapoton** [comment]
Commit: **[`8fc9e87`](https://github.com/sagemath/sagetrac-mirror/commit/8fc9e87186d9ae1483fe1b8ae8ffdd1c071e5c77)**

**Comment by fchapoton** [comment]
<div id="comment:2" align="right">comment:2</div>

green lights, so please review

**Comment by kwankyu** [comment]
<div id="comment:3" align="right">comment:3</div>

LGTM, except 

```diff
--- a/src/sage/libs/ecl.pyx
+++ b/src/sage/libs/ecl.pyx
@@ -422,7 +422,7 @@ cdef cl_object python_to_ecl(pyobj, bint read_strings) except NULL:
     cdef bytes s
     cdef cl_object L, ptr, o
 
-    if isinstance(pyobj,bool):
+    if isinstance(pyobj, bool):
         if pyobj:
             return ECL_T
         else:
```
which you are free to fix.

**Comment by kwankyu** [comment]
Reviewer: **Kwankyu Lee**

**Comment by vbraun** [comment]
Changed branch from **[u/chapoton/34798](https://github.com/sagemath/sagetrac-mirror/tree/u/chapoton/34798)** to **[`8fc9e87`](https://github.com/sagemath/sagetrac-mirror/commit/8fc9e87186d9ae1483fe1b8ae8ffdd1c071e5c77)**
