### ISSUE TITLE
Vizing edge coloring optimization

### ISSUE THREAD

**Issue by mam15** [sagemath/sage#34809]
<div id="comment:0"></div>

This is an optimization of the existing edge_coloring algorithm for graphs, the implementation was discussed at https://groups.google.com/g/sage-devel/c/AzD3codkw2I

Component: **graph theory**

Keywords: **graph coloring**

Author: **Matheus Maldonado**

Branch/Commit: **[`8f61d88`](https://github.com/sagemath/sagetrac-mirror/commit/8f61d888a9d47807307d85fd45bf053bae32c002)**

Reviewer: **David Coudert**

_Issue created by migration from https://trac.sagemath.org/ticket/34809_

**Comment by dcoudert** [comment]
<div id="comment:1" align="right">comment:1</div>

It is not a good idea to change the label of edges inside the method. This main erase other data. Consider using an external dictionary.

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
<div id="comment:2"></div>

Branch pushed to git repo; I updated commit sha1. New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/2435f49cd8ebd0f7b1df13775a25baddac1bdfcc"><code>2435f49</code></a></td><td><code>Using external dict instead of graph labels</code></td></tr></table>

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
Changed commit from **[`2ba8294`](https://github.com/sagemath/sagetrac-mirror/commit/2ba8294ef10bf6e75aed219e5902c7436dfe62ec)** to **[`2435f49`](https://github.com/sagemath/sagetrac-mirror/commit/2435f49cd8ebd0f7b1df13775a25baddac1bdfcc)**

**Comment by mam15** [comment]
<div id="comment:3" align="right">comment:3</div>

Should be good now. I thought g = copy(g) would be enough but using another dict is much cleaner.

**Comment by dcoudert** [comment]
<div id="comment:4" align="right">comment:4</div>

You should use `frozenset(e)` instead of `tuple(sorted(e))`. 

Also, can you push the branch in something like `public/graphs/34809_vizing` to allow me to push review commits. It shall ease the reviewing process.

**Comment by mam15** [comment]
Changed branch from **[u/gh-mam15/vizing_edge_coloring](https://github.com/sagemath/sagetrac-mirror/tree/u/gh-mam15/vizing_edge_coloring)** to **[public/graphs/34809_vizing](https://github.com/sagemath/sagetrac-mirror/tree/public/graphs/34809_vizing)**

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
Changed commit from **[`2435f49`](https://github.com/sagemath/sagetrac-mirror/commit/2435f49cd8ebd0f7b1df13775a25baddac1bdfcc)** to **[`ef6b784`](https://github.com/sagemath/sagetrac-mirror/commit/ef6b784f72255be2c1279210040661ac8e22836e)**

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
<div id="comment:6"></div>

Branch pushed to git repo; I updated commit sha1. New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/ef6b784f72255be2c1279210040661ac8e22836e"><code>ef6b784</code></a></td><td><code>trac 34809: serious review commit</code></td></tr></table>

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
Changed commit from **[`ef6b784`](https://github.com/sagemath/sagetrac-mirror/commit/ef6b784f72255be2c1279210040661ac8e22836e)** to **[`d9a1684`](https://github.com/sagemath/sagetrac-mirror/commit/d9a16849b63ea4e2782bb8ce7c396d97548bb28f)**

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
<div id="comment:7"></div>

Branch pushed to git repo; I updated commit sha1. New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/d9a16849b63ea4e2782bb8ce7c396d97548bb28f"><code>d9a1684</code></a></td><td><code>trac 34809: style</code></td></tr></table>

**Comment by dcoudert** [comment]
<div id="comment:8" align="right">comment:8</div>

I did multiple corrections and small improvements(avoid recursive calls, avoid searching in lists, etc.). I have also strengthen the doctests to avoid issues due too small changes. Please do many tests to check if its correct.

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
<div id="comment:9"></div>

Branch pushed to git repo; I updated commit sha1. New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/c07e48e2ddf8eeb341f35e4af050d8c57c0fc38f"><code>c07e48e</code></a></td><td><code>Test case for random graphs</code></td></tr></table>

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
Changed commit from **[`d9a1684`](https://github.com/sagemath/sagetrac-mirror/commit/d9a16849b63ea4e2782bb8ce7c396d97548bb28f)** to **[`c07e48e`](https://github.com/sagemath/sagetrac-mirror/commit/c07e48e2ddf8eeb341f35e4af050d8c57c0fc38f)**

**Comment by mam15** [comment]
<div id="comment:10" align="right">comment:10</div>

I couldn't really think of anything the example you created didn't cover, so I ended up testing that example on random graphs, the only difference is I test for len(colors) == Delta or Delta+1.

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
<div id="comment:11"></div>

Branch pushed to git repo; I updated commit sha1. New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/e1382c7bbe782f9753bdcc726e720e95393d9725"><code>e1382c7</code></a></td><td><code>trac #34809: smaller doctest on random graphs</code></td></tr></table>

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
Changed commit from **[`c07e48e`](https://github.com/sagemath/sagetrac-mirror/commit/c07e48e2ddf8eeb341f35e4af050d8c57c0fc38f)** to **[`e1382c7`](https://github.com/sagemath/sagetrac-mirror/commit/e1382c7bbe782f9753bdcc726e720e95393d9725)**

**Comment by dcoudert** [comment]
Reviewer: **David Coudert**

**Comment by dcoudert** [comment]
<div id="comment:12" align="right">comment:12</div>

I changed the doctest to something smaller / faster.

Do you have other improvements for this method ?

**Comment by mam15** [comment]
<div id="comment:13" align="right">comment:13</div>

Not really for the time being, my focus was the ```O(|E||V|)``` algorithm

**Comment by dcoudert** [comment]
<div id="comment:14" align="right">comment:14</div>

There is an error due to the call `return _vizing_edge_coloring(g, hex_colors)` in the except statement.

```
sage: from sage.graphs.graph_coloring import edge_coloring
sage: G = graphs.CycleGraph(5) + graphs.Grid2dGraph(3, 4)
sage: edge_coloring(G, value_only=True, vizing=False)
4
sage: len(edge_coloring(G, value_only=False, vizing=False))
5
```

Also, you should check before the `ILP` if `Delta + 1 <= chi`, in which case you can directly call vizing on that component (but not on the graph).

**Comment by DaveWitteMorris** [comment]
<div id="comment:15" align="right">comment:15</div>

I have a few minor comments/suggestions.

1) Please eliminate the `hex_color` code duplication. Instead of copy-pasting the `hex_color` code, wouldn't it be better to have the private method return the coloring, and let the main routine process it if necessary?

Actually I would be +1 on deleting the `hex_color` keyword, but that would be a separate ticket. Duplicating this code is moving entirely in the wrong direction, in my opinion.

2) The new implementation changes the method in a backward-incompatible way.  Sage policy therefore requires a deprecation period.  This policy is not always enforced, but there should be a good reason, so it should be specifically discussed, and perhaps the change should be announced on sage-devel, to see if there are any objections.

I can easily imagine cases where this change breaks code.  For example, if I were looking at lots of graphs of the same maximum degree, I might want to make an incidence matrix that keeps track of which edges are incident with which colors of edges. In the current implementation, I am guaranteed that these matrices all have the same size, but that guarantee is being dropped.

3) The docstring's phrase "This may result in either a `\Delta`-edge-coloring or a `Delta + 1`-edge-coloring" is very unclear.  I think the usual definition of "k-coloring" is that it can use k colors or less, so every `(Delta + 1)`-edge-coloring is also a `\Delta`-edge-coloring.  Thus, Vizing's Theorem always produces a `(Delta + 1)`-edge coloring. So, instead of using the term "`\Delta`-edge-coloring", I think the phrasing should make it more clear that the number of colors that actually appear in the coloring is either `Delta` or `Delta + 1`.

(Also, I think parentheses are necessary around "`Delta + 1`", and I think there is a typo: "\Delta" is missing its backslash in "`Delta + 1`-edge-coloring".)

4) Please add a reference to this trac ticket in a docstring or comment.

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
<div id="comment:16"></div>

Branch pushed to git repo; I updated commit sha1. New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/bb35295eb69eb0cb621af65da7e73752df32611a"><code>bb35295</code></a></td><td><code>Docstring typos and clarity + algorith fixes</code></td></tr></table>

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
Changed commit from **[`e1382c7`](https://github.com/sagemath/sagetrac-mirror/commit/e1382c7bbe782f9753bdcc726e720e95393d9725)** to **[`bb35295`](https://github.com/sagemath/sagetrac-mirror/commit/bb35295eb69eb0cb621af65da7e73752df32611a)**

**Comment by mam15** [comment]
<div id="comment:17" align="right">comment:17</div>

Replying to [David Coudert](#comment%3A14):
> There is an error due to the call `return _vizing_edge_coloring(g, hex_colors)` in the except statement.
> 
> ```
> sage: from sage.graphs.graph_coloring import edge_coloring
> sage: G = graphs.CycleGraph(5) + graphs.Grid2dGraph(3, 4)
> sage: edge_coloring(G, value_only=True, vizing=False)
> 4
> sage: len(edge_coloring(G, value_only=False, vizing=False))
> 5
> ```
> 
> Also, you should check before the `ILP` if `Delta + 1 <= chi`, in which case you can directly call vizing on that component (but not on the graph).

Should be fixed now

Replying to [Dave Morris](#comment%3A15):
> I have a few minor comments/suggestions.
> 
> 1) Please eliminate the `hex_color` code duplication. Instead of copy-pasting the `hex_color` code, wouldn't it be better to have the private method return the coloring, and let the main routine process it if necessary?
> 
> Actually I would be +1 on deleting the `hex_color` keyword, but that would be a separate ticket. Duplicating this code is moving entirely in the wrong direction, in my opinion.
> 
> 2) The new implementation changes the method in a backward-incompatible way.  Sage policy therefore requires a deprecation period.  This policy is not always enforced, but there should be a good reason, so it should be specifically discussed, and perhaps the change should be announced on sage-devel, to see if there are any objections.
> 
> I can easily imagine cases where this change breaks code.  For example, if I were looking at lots of graphs of the same maximum degree, I might want to make an incidence matrix that keeps track of which edges are incident with which colors of edges. In the current implementation, I am guaranteed that these matrices all have the same size, but that guarantee is being dropped.
> 

This can be fixed by adding a new color class with a random edge if a coloring with Delta colors is found, not sure if it's the best solution though. Please let me know if you have any other idea or if we should just start a discussion on sage-devel about the deprecation of this function.

> 3) The docstring's phrase "This may result in either a `\Delta`-edge-coloring or a `Delta + 1`-edge-coloring" is very unclear.  I think the usual definition of "k-coloring" is that it can use k colors or less, so every `(Delta + 1)`-edge-coloring is also a `\Delta`-edge-coloring.  Thus, Vizing's Theorem always produces a `(Delta + 1)`-edge coloring. So, instead of using the term "`\Delta`-edge-coloring", I think the phrasing should make it more clear that the number of colors that actually appear in the coloring is either `Delta` or `Delta + 1`.
> 
> (Also, I think parentheses are necessary around "`Delta + 1`", and I think there is a typo: "\Delta" is missing its backslash in "`Delta + 1`-edge-coloring".)
> 
> 4) Please add a reference to this trac ticket in a docstring or comment.

Added all your suggestions.

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
<div id="comment:18"></div>

Branch pushed to git repo; I updated commit sha1. New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/e662f1c82af5c6437671628d2a1c9f2b55be40be"><code>e662f1c</code></a></td><td><code>trac #34809: avoid some code duplication</code></td></tr></table>

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
Changed commit from **[`bb35295`](https://github.com/sagemath/sagetrac-mirror/commit/bb35295eb69eb0cb621af65da7e73752df32611a)** to **[`e662f1c`](https://github.com/sagemath/sagetrac-mirror/commit/e662f1c82af5c6437671628d2a1c9f2b55be40be)**

**Comment by dcoudert** [comment]
<div id="comment:19" align="right">comment:19</div>

I added an internal function to avoid some code duplication. I also make sure that chi is updated.

Several points raised by Dave must be addressed. I agree that Vizing should return a `Delta + 1` coloring, even if the last color is an empty set (e.g., for the star graph which requires only `Delta` colors).

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
Changed commit from **[`e662f1c`](https://github.com/sagemath/sagetrac-mirror/commit/e662f1c82af5c6437671628d2a1c9f2b55be40be)** to **[`5a11c8b`](https://github.com/sagemath/sagetrac-mirror/commit/5a11c8b7896db5c246971d59818d1d001705cab2)**

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
<div id="comment:20"></div>

Branch pushed to git repo; I updated commit sha1. New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/5a11c8b7896db5c246971d59818d1d001705cab2"><code>5a11c8b</code></a></td><td><code>trac #34809: backward compat for vizing=True</code></td></tr></table>

**Comment by mam15** [comment]
<div id="comment:21" align="right">comment:21</div>

I think everything should be up to standard now, please let me know if I missed anything

**Comment by dcoudert** [comment]
<div id="comment:22" align="right">comment:22</div>

The is still some ambiguity in the description of the case `vizing == True`. The method should return a coloring using `Delta+ 1` colors, even if some colors are empty.

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
Changed commit from **[`5a11c8b`](https://github.com/sagemath/sagetrac-mirror/commit/5a11c8b7896db5c246971d59818d1d001705cab2)** to **[`a68435a`](https://github.com/sagemath/sagetrac-mirror/commit/a68435adb51e7a7fee427ff943e0fa4121d88104)**

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
<div id="comment:23"></div>

Branch pushed to git repo; I updated commit sha1. New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/a68435adb51e7a7fee427ff943e0fa4121d88104"><code>a68435a</code></a></td><td><code>trac #34809: fixing vizing=True in docs</code></td></tr></table>

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
Changed commit from **[`a68435a`](https://github.com/sagemath/sagetrac-mirror/commit/a68435adb51e7a7fee427ff943e0fa4121d88104)** to **[`8f61d88`](https://github.com/sagemath/sagetrac-mirror/commit/8f61d888a9d47807307d85fd45bf053bae32c002)**

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
<div id="comment:24"></div>

Branch pushed to git repo; I updated commit sha1. New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/8f61d888a9d47807307d85fd45bf053bae32c002"><code>8f61d88</code></a></td><td><code>trac #34809: rewriting vizing=True for clarity</code></td></tr></table>

**Comment by dcoudert** [comment]
<div id="comment:25" align="right">comment:25</div>

`@`Dave, do you agree with the proposed changes ? If so we can conclude the review of this ticket.

**Comment by dcoudert** [comment]
<div id="comment:26" align="right">comment:26</div>

For me this ticket is good to go.

**Comment by vbraun** [comment]
Changed branch from **[public/graphs/34809_vizing](https://github.com/sagemath/sagetrac-mirror/tree/public/graphs/34809_vizing)** to **[`8f61d88`](https://github.com/sagemath/sagetrac-mirror/commit/8f61d888a9d47807307d85fd45bf053bae32c002)**
