### ISSUE TITLE
deprecate constructing number-field fractional ideals via orders' .ideal() method

### ISSUE THREAD

**Issue by yyyyx4** [sagemath/sage#34806]
<div id="comment:0"></div>

Currently, Sage creates a fractional ideal of the containing number field when calling `.ideal()` on a maximal order. This is a mathematically questionable choice, but perhaps more importantly, it will inevitably cause inconsistencies once #34198 is done — the same code would start returning wildly different objects depending on whether the given order is maximal or not.

In this ticket, I propose to deprecate the use of `.ideal()` on a maximal order to create number-field fractional ideals. This will presumably affect lots of user code, so I think it's good to get the deprecation warning in as soon as possible.

Related, deeper issue: #3680

CC:  @slel

Component: **number fields**

Author: **Lorenz Panny**

_Issue created by migration from https://trac.sagemath.org/ticket/34806_

**Comment by yyyyx4** [comment]
Author: **Lorenz Panny**

**Comment by yyyyx4** [comment]
Description changed:
``````diff
--- 
+++ 
@@ -2,3 +2,4 @@
 
 In this ticket, I propose to deprecate the use of `.ideal()` on a maximal order to create number-field fractional ideals. This will presumably affect lots of user code, so I think it's good to get the deprecation warning in as soon as possible.
 
+Related, deeper issue: #3680
``````

**Comment by yyyyx4** [comment]
Branch: **[public/34806](https://github.com/sagemath/sagetrac-mirror/tree/public/34806)**

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
Commit: **[`40363f1`](https://github.com/sagemath/sagetrac-mirror/commit/40363f14428699e2ecd9f51d43ee8dbc4ed7bd7d)**

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
<div id="comment:2"></div>

Branch pushed to git repo; I updated commit sha1. New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/40363f14428699e2ecd9f51d43ee8dbc4ed7bd7d"><code>40363f1</code></a></td><td><code>add deprecation warning for #34806</code></td></tr></table>

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
<div id="comment:3"></div>

Branch pushed to git repo; I updated commit sha1. New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/f9c2d643544fe151951a40e4cdf642714babf7ca"><code>f9c2d64</code></a></td><td><code>fix some doctest failures</code></td></tr></table>

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
Changed commit from **[`40363f1`](https://github.com/sagemath/sagetrac-mirror/commit/40363f14428699e2ecd9f51d43ee8dbc4ed7bd7d)** to **[`f9c2d64`](https://github.com/sagemath/sagetrac-mirror/commit/f9c2d643544fe151951a40e4cdf642714babf7ca)**

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
Changed commit from **[`f9c2d64`](https://github.com/sagemath/sagetrac-mirror/commit/f9c2d643544fe151951a40e4cdf642714babf7ca)** to **[`636af13`](https://github.com/sagemath/sagetrac-mirror/commit/636af13e3d0033e944f4afc3f8ab665d2f6f87d1)**

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
<div id="comment:4"></div>

Branch pushed to git repo; I updated commit sha1. New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/636af13e3d0033e944f4afc3f8ab665d2f6f87d1"><code>636af13</code></a></td><td><code>fix some more doctest failures</code></td></tr></table>

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
<div id="comment:5"></div>

Branch pushed to git repo; I updated commit sha1. This was a forced push. New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/b97b28f1f21e2e406985a5809fd5b0f658cc6f40"><code>b97b28f</code></a></td><td><code>add deprecation warning for #34806</code></td></tr></table>

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
Changed commit from **[`636af13`](https://github.com/sagemath/sagetrac-mirror/commit/636af13e3d0033e944f4afc3f8ab665d2f6f87d1)** to **[`b97b28f`](https://github.com/sagemath/sagetrac-mirror/commit/b97b28f1f21e2e406985a5809fd5b0f658cc6f40)**

**Comment by mkoeppe** [comment]
Removed branch from issue description; replaced by PR #34979
