### ISSUE TITLE
Deprecate sage.interfaces is_...Element functions

### ISSUE THREAD

**Issue by mkoeppe** [sagemath/sage#34804]
<div id="comment:0"></div>

Introducing a module `sage.interfaces.abc` with abstract base classes for `isinstance` testing (see https://doc.sagemath.org/html/en/developer/packaging_sage_library.html#module-level-runtime-dependencies)

Part of #32414

Depends on #34770
Depends on #34823

CC:  @dimpase @kwankyu

Component: **refactoring**

Author: **Matthias Koeppe, Dima Pasechnik**

Branch/Commit: **[`b9eac04`](https://github.com/sagemath/sagetrac-mirror/commit/b9eac04c741264d2731d6d0b83b43a7fdeef98a3)**

Reviewer: **Dima Pasechnik**

_Issue created by migration from https://trac.sagemath.org/ticket/34804_

**Comment by mkoeppe** [comment]
Description changed:
``````diff
--- 
+++ 
@@ -1,2 +1,3 @@
 Introducing a module `sage.interfaces.abc` with abstract base classes for `isinstance` testing (see https://doc.sagemath.org/html/en/developer/packaging_sage_library.html#module-level-runtime-dependencies)
 
+Part of #32414
``````

**Comment by mkoeppe** [comment]
Branch: **[u/mkoeppe/deprecate_sage_interfaces_is____element_functions](https://github.com/sagemath/sagetrac-mirror/tree/u/mkoeppe/deprecate_sage_interfaces_is____element_functions)**

**Comment by dimpase** [comment]
<div id="comment:3" align="right">comment:3</div>


```diff
--- a/src/sage/interfaces/gap.py
+++ b/src/sage/interfaces/gap.py
@@ -211,6 +211,9 @@ import platform
 import string
 import warnings
 
+import sage.rings.abc
+
+
 WORKSPACE = gap_workspace_file()
 
 first_try = True
@@ -1524,7 +1527,7 @@ def gap_reset_workspace(max_workspace_size=None, verbose=False):
 
 
 @instancedoc
-class GapElement(GapElement_generic):
+class GapElement(GapElement_generic, sage.rings.abc.GapElement):
     def __getitem__(self, n):
         """
         EXAMPLES::
```

this is weird - do you mean `sage.interfaces...` there, not `sage.rings...` ?

---
New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/60318787933917af6759d86f02859d302b4cd559"><code>6031878</code></a></td><td><code>sage.interfaces.abc.GapElement: New, use it instead of sage.interfaces.gap.is_GapElement</code></td></tr></table>

**Comment by dimpase** [comment]
Commit: **[`6031878`](https://github.com/sagemath/sagetrac-mirror/commit/60318787933917af6759d86f02859d302b4cd559)**

**Comment by mkoeppe** [comment]
<div id="comment:4" align="right">comment:4</div>

Yes, sorry, it should be `sage.interfaces...` of course

**Comment by dimpase** [comment]
<div id="comment:5" align="right">comment:5</div>

I took (corrected) pieces of this branch to #34770. So this ought to be based on the branch there.

**Comment by mkoeppe** [comment]
Dependencies: **#34770**

**Comment by mkoeppe** [comment]
Work Issues: **rebase on #34770**

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
Changed commit from **[`6031878`](https://github.com/sagemath/sagetrac-mirror/commit/60318787933917af6759d86f02859d302b4cd559)** to **[`8572f15`](https://github.com/sagemath/sagetrac-mirror/commit/8572f1576a544ac533507cbfe09811d47943b518)**

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
<div id="comment:7"></div>

Branch pushed to git repo; I updated commit sha1. This was a forced push. New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/21e38a73fa41698d02ec4c00597e35b5dbd0eda6"><code>21e38a7</code></a></td><td><code>fix coersion of libgap FFelements; switch to libgap</code></td></tr><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/d4bde80f350975b30e5795aa5ffc7333f5c80911"><code>d4bde80</code></a></td><td><code>make imports of is_GapEelment uniform across files</code></td></tr><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/eb72ef050d94dd32cbb1499243af5de4e9eec22c"><code>eb72ef0</code></a></td><td><code>avoid is_GapElement</code></td></tr><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/1c4a69fdfee7ccf9aebb40bbc29b4453852cacb1"><code>1c4a69f</code></a></td><td><code>use GapElement from an abstract superclass</code></td></tr><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/6e5ea791a3d846cfd70d9b361f168f6c2fa66a2b"><code>6e5ea79</code></a></td><td><code>move import of libgap into a function</code></td></tr><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/8572f1576a544ac533507cbfe09811d47943b518"><code>8572f15</code></a></td><td><code>sage.interfaces.abc.GapElement: New, use it instead of sage.interfaces.gap.is_GapElement</code></td></tr></table>

**Comment by mkoeppe** [comment]
Changed dependencies from **#34770** to **#34770, #34823**

**Comment by mkoeppe** [comment]
Changed work issues from **rebase on #34770** to none

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
<div id="comment:9"></div>

Branch pushed to git repo; I updated commit sha1. New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/adc231ef98032f86f42167a98dd86f3800f1ee9f"><code>adc231e</code></a></td><td><code>remove is_GapElement from number fields code</code></td></tr><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/7c67a1089852beca7b5e0b80ad3cb2a319f0ceef"><code>7c67a10</code></a></td><td><code>deprecating is_GapElement</code></td></tr><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/6c75e9b0cc5679ee9ea5773ca1586eacf438e378"><code>6c75e9b</code></a></td><td><code>better rst, point at sage.interfaces.abc to use</code></td></tr><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/e99db3af3a814e9accdd10a915f651aabe9faa91"><code>e99db3a</code></a></td><td><code>src/sage/interfaces/gap.py: Reviewer edits</code></td></tr><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/b8024150aa19c47fb893eca9fccb00bcc7c3fd54"><code>b802415</code></a></td><td><code>Merge #34823</code></td></tr><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/27c8788aaea7e9e8fd3d4540ce4e56b5242d884f"><code>27c8788</code></a></td><td><code>src/sage/interfaces/abc.py (GpElement): New, use it for isinstance testing</code></td></tr></table>

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
Changed commit from **[`8572f15`](https://github.com/sagemath/sagetrac-mirror/commit/8572f1576a544ac533507cbfe09811d47943b518)** to **[`27c8788`](https://github.com/sagemath/sagetrac-mirror/commit/27c8788aaea7e9e8fd3d4540ce4e56b5242d884f)**

**Comment by mkoeppe** [comment]
Author: **Matthias Koeppe, ...**

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
<div id="comment:11"></div>

Branch pushed to git repo; I updated commit sha1. New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/106a85b699eb16eb328451fa23c2dee133362a26"><code>106a85b</code></a></td><td><code>src/sage/interfaces/abc.py (SingularElement, Macaulay2Element): New, use for isinstance testing</code></td></tr></table>

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
Changed commit from **[`27c8788`](https://github.com/sagemath/sagetrac-mirror/commit/27c8788aaea7e9e8fd3d4540ce4e56b5242d884f)** to **[`106a85b`](https://github.com/sagemath/sagetrac-mirror/commit/106a85b699eb16eb328451fa23c2dee133362a26)**

**Comment by mkoeppe** [comment]
Changed author from **Matthias Koeppe, ...** to **Matthias Koeppe**

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
Changed commit from **[`106a85b`](https://github.com/sagemath/sagetrac-mirror/commit/106a85b699eb16eb328451fa23c2dee133362a26)** to **[`2604174`](https://github.com/sagemath/sagetrac-mirror/commit/2604174d0ad2a7825d356ce8c219033cbf96eb96)**

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
<div id="comment:13"></div>

Branch pushed to git repo; I updated commit sha1. New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/2604174d0ad2a7825d356ce8c219033cbf96eb96"><code>2604174</code></a></td><td><code>src/sage/interfaces/abc.py: Add doc</code></td></tr></table>

**Comment by dimpase** [comment]
Changed branch from **[u/mkoeppe/deprecate_sage_interfaces_is____element_functions](https://github.com/sagemath/sagetrac-mirror/tree/u/mkoeppe/deprecate_sage_interfaces_is____element_functions)** to **[u/dimpase/deprecate_sage_interfaces_is____element_functions](https://github.com/sagemath/sagetrac-mirror/tree/u/dimpase/deprecate_sage_interfaces_is____element_functions)**

**Comment by dimpase** [comment]
Changed commit from **[`2604174`](https://github.com/sagemath/sagetrac-mirror/commit/2604174d0ad2a7825d356ce8c219033cbf96eb96)** to **[`b4d5d5b`](https://github.com/sagemath/sagetrac-mirror/commit/b4d5d5b94f175a8171abe0bc0cc5c3e6fe69df2f)**

**Comment by dimpase** [comment]
Reviewer: **Dima Pasechnik**

**Comment by dimpase** [comment]
<div id="comment:14"></div>

New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/b4d5d5b94f175a8171abe0bc0cc5c3e6fe69df2f"><code>b4d5d5b</code></a></td><td><code>deprecate is_GpElement</code></td></tr></table>

**Comment by dimpase** [comment]
<div id="comment:15" align="right">comment:15</div>

we have still only a fraction done:

```
Axiom            ?
Expect           ?
FriCAS           ?
Gap              done
Gp               done
Interface        ?
Kash             ?
LiE              ?
Lisp             ?
Macaulay2        done
Magma            ?
Maxima           ?
MaximaLib        ?
R                ?
Singular         done
```

**Comment by dimpase** [comment]
<div id="comment:16" align="right">comment:16</div>

How about an implementation with a decorator:

```python
r"""
Abstract base classes for interface elements
"""
def _add_doc():
    def wrapped(c):
        c.__doc__ = "\n Abstract base class for :class:`~sage.interfaces.gap." + c.__name__
        c.__doc__ += """
    
  This class is defined for the purpose of ``isinstance`` tests.  It should not be
  instantiated.

  EXAMPLES:

  By design, there is a unique direct subclass::

  """
        c.__doc__ += "    sage: len(sage.interfaces.abc."+c.__name__+".__subclasses__()) <= 1\n      True"
        return c
    return wrapped


@_add_doc()
class GapElement: pass


@_add_doc()
class GpElement: pass

...
```

Needless to say, docstrings etc work as they should this way. Decorator overhead - very small, if at all, IMHO.

**Comment by mkoeppe** [comment]
<div id="comment:17" align="right">comment:17</div>

Doctests are discovered by parsing files; they cannot be supplied by decorators.

**Comment by mkoeppe** [comment]
Changed author from **Matthias Koeppe** to **Matthias Koeppe, Dima Pasechnik**

**Comment by mkoeppe** [comment]
Changed branch from **[u/dimpase/deprecate_sage_interfaces_is____element_functions](https://github.com/sagemath/sagetrac-mirror/tree/u/dimpase/deprecate_sage_interfaces_is____element_functions)** to **[u/mkoeppe/deprecate_sage_interfaces_is____element_functions](https://github.com/sagemath/sagetrac-mirror/tree/u/mkoeppe/deprecate_sage_interfaces_is____element_functions)**

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
<div id="comment:20"></div>

Branch pushed to git repo; I updated commit sha1. New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/31128eedbd44371856f5062e0a46cd3de5852a7d"><code>31128ee</code></a></td><td><code>sage.interfaces.abc: Add MagmaElement, deprecate is_MagmaElement</code></td></tr></table>

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
Changed commit from **[`b4d5d5b`](https://github.com/sagemath/sagetrac-mirror/commit/b4d5d5b94f175a8171abe0bc0cc5c3e6fe69df2f)** to **[`31128ee`](https://github.com/sagemath/sagetrac-mirror/commit/31128eedbd44371856f5062e0a46cd3de5852a7d)**

**Comment by mkoeppe** [comment]
<div id="comment:21" align="right">comment:21</div>

The remaining is_... functions are not used anywhere

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
Changed commit from **[`31128ee`](https://github.com/sagemath/sagetrac-mirror/commit/31128eedbd44371856f5062e0a46cd3de5852a7d)** to **[`56b8bf6`](https://github.com/sagemath/sagetrac-mirror/commit/56b8bf6829e797a03f95bb0e4bca44fc81484376)**

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
<div id="comment:22"></div>

Branch pushed to git repo; I updated commit sha1. New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/56b8bf6829e797a03f95bb0e4bca44fc81484376"><code>56b8bf6</code></a></td><td><code>sage.interfaces.abc: Add AxiomElement, deprecate is_AxiomElement</code></td></tr></table>

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
<div id="comment:23"></div>

Branch pushed to git repo; I updated commit sha1. New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/381aaf9d04096b7a3feeb8824fda4368d8af975b"><code>381aaf9</code></a></td><td><code>src/sage/interfaces/axiom.py: Fix up</code></td></tr><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/4cd6a826dc7207ac7d5dcdb11ddf9776ada4e5dd"><code>4cd6a82</code></a></td><td><code>src/sage/interfaces/magma.py: Fix up</code></td></tr></table>

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
Changed commit from **[`56b8bf6`](https://github.com/sagemath/sagetrac-mirror/commit/56b8bf6829e797a03f95bb0e4bca44fc81484376)** to **[`4cd6a82`](https://github.com/sagemath/sagetrac-mirror/commit/4cd6a826dc7207ac7d5dcdb11ddf9776ada4e5dd)**

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
<div id="comment:24"></div>

Branch pushed to git repo; I updated commit sha1. New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/e957fc9292401d99e4b1cf0a5636c3599a0f436a"><code>e957fc9</code></a></td><td><code>sage.interfaces.abc: Add FriCASElement, deprecate is_FriCASElement</code></td></tr></table>

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
Changed commit from **[`4cd6a82`](https://github.com/sagemath/sagetrac-mirror/commit/4cd6a826dc7207ac7d5dcdb11ddf9776ada4e5dd)** to **[`e957fc9`](https://github.com/sagemath/sagetrac-mirror/commit/e957fc9292401d99e4b1cf0a5636c3599a0f436a)**

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
<div id="comment:25"></div>

Branch pushed to git repo; I updated commit sha1. New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/b9eac04c741264d2731d6d0b83b43a7fdeef98a3"><code>b9eac04</code></a></td><td><code>sage.interface: Deprecate unused is_*Element functions, but do not introduce ABCs for them</code></td></tr></table>

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
Changed commit from **[`e957fc9`](https://github.com/sagemath/sagetrac-mirror/commit/e957fc9292401d99e4b1cf0a5636c3599a0f436a)** to **[`b9eac04`](https://github.com/sagemath/sagetrac-mirror/commit/b9eac04c741264d2731d6d0b83b43a7fdeef98a3)**

**Comment by mkoeppe** [comment]
<div id="comment:26" align="right">comment:26</div>

Green checks, ready for review

**Comment by dimpase** [comment]
<div id="comment:27" align="right">comment:27</div>

Replying to [Matthias Köppe](#comment%3A17):
> Doctests are discovered by parsing files; they cannot be supplied by decorators.

Yes, they can. In fact, very easy to amend and doctest the docstring of a function:

```
$ cat d.py 
def docstr(f):
    """
    amends the docstring
    """
    f.__doc__ += """
    >>> tst(1)
    42
    """
    return f

@docstr
def tst(x):
    '''adds 1 to x
    >>> tst(0)
    1
    >>> tst(42)
    42 
    '''
    return x+1

if __name__ == '__main__':
    import doctest
    doctest.testmod()
$
$ python3 d.py 
**********************************************************************
File "/tmp/d.py", line 16, in __main__.tst
Failed example:
    tst(42)
Expected:
    42 
Got:
    43
**********************************************************************
File "/tmp/d.py", line 19, in __main__.tst
Failed example:
    tst(1)
Expected:
    42
Got:
    2
**********************************************************************
1 items had failures:
   2 of   3 in __main__.tst
```

See, the original `tst()` had 2 doctests, one was added by `@docstr` - and 3 were tested.
So it's perfectly doable for functions.

As a sanity check:

```
$ ipython3 
Python 3.9.2 (default, Feb 28 2021, 17:03:44) 
Type 'copyright', 'credits' or 'license' for more information
IPython 7.20.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: from d import  *

In [2]: tst?
Docstring:
adds 1 to x
>>> tst(0)
1
>>> tst(42)
42 

>>> tst(1)
42
File:      /tmp/d.py
Type:      function
```

---

As we see, doctests are run on `__doc__` attributes of functions, not by scraping the text of the file.

**Comment by dimpase** [comment]
<div id="comment:28" align="right">comment:28</div>

And it works, in vanilla Python 3.9, with classes too:

```python
def docstr(f):
    """
    amends the docstring
    """
    f.__doc__ += """
    >>> len(tst.__subclasses__()) > 0
    True
    """
    return f

@docstr
class tst:
    '''testing
    >>> len(tst.__subclasses__()) <= 1
    True
    '''
    pass

if __name__ == '__main__':
    import doctest
    doctest.testmod()
```
and so we see 2 doctests being run, one from the class body, one added by the decorator.

```
$ python3 c.py 
**********************************************************************
File "/tmp/c.py", line 17, in __main__.tst
Failed example:
    len(tst.__subclasses__()) > 0
Expected:
    True
Got:
    False
**********************************************************************
1 items had failures:
   1 of   2 in __main__.tst
***Test Failed*** 1 failures.
```
(You can easily modify this so that the class has empty `__doc__`, then one can create it in the decorator, so it's all sane here in vanilla Python).


I can only conclude that Sage's doctest system is borked at this point,and somehow
does a non-vanilla thing. 
Indeed,  `sage -t c.py` does not see the doctests added by the decorator.

**Comment by dimpase** [comment]
<div id="comment:29" align="right">comment:29</div>

I've opened #34828 to fix the doctest issue in [comment:28](#comment%3A28)

**Comment by mkoeppe** [comment]
<div id="comment:30" align="right">comment:30</div>

Let's not wait for that to be fixed

**Comment by dimpase** [comment]
<div id="comment:31" align="right">comment:31</div>

lgtm

**Comment by mkoeppe** [comment]
<div id="comment:32" align="right">comment:32</div>

Thank you!

**Comment by vbraun** [comment]
Changed branch from **[u/mkoeppe/deprecate_sage_interfaces_is____element_functions](https://github.com/sagemath/sagetrac-mirror/tree/u/mkoeppe/deprecate_sage_interfaces_is____element_functions)** to **[`b9eac04`](https://github.com/sagemath/sagetrac-mirror/commit/b9eac04c741264d2731d6d0b83b43a7fdeef98a3)**
