### ISSUE TITLE
fix some compilation warnings

### ISSUE THREAD

**Issue by fchapoton** [sagemath/sage#34802]
<div id="comment:0"></div>

CC:  @tscrim @slel @kwankyu @kliem

Component: **refactoring**

Author: **Frédéric Chapoton**

Branch/Commit: **[`5a4ba58`](https://github.com/sagemath/sagetrac-mirror/commit/5a4ba58a3ebe5f882d0aa91ece68a7cdf3df3ec0)**

Reviewer: **Travis Scrimshaw**

_Issue created by migration from https://trac.sagemath.org/ticket/34802_

**Comment by fchapoton** [comment]
Branch: **[u/chapoton/34802](https://github.com/sagemath/sagetrac-mirror/tree/u/chapoton/34802)**

**Comment by fchapoton** [comment]
Commit: **[`dcb2dda`](https://github.com/sagemath/sagetrac-mirror/commit/dcb2dda1836ca3a4b9b971ac7807301d5ac83405)**

**Comment by fchapoton** [comment]
<div id="comment:1"></div>

New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/dcb2dda1836ca3a4b9b971ac7807301d5ac83405"><code>dcb2dda</code></a></td><td><code>fix some compilation warnings</code></td></tr></table>

**Comment by fchapoton** [comment]
<div id="comment:2" align="right">comment:2</div>

please review

**Comment by tscrim** [comment]
Reviewer: **Travis Scrimshaw**

**Comment by tscrim** [comment]
<div id="comment:3" align="right">comment:3</div>

LGTM.

**Comment by fchapoton** [comment]
<div id="comment:4" align="right">comment:4</div>

sorry, I found another one

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
Changed commit from **[`dcb2dda`](https://github.com/sagemath/sagetrac-mirror/commit/dcb2dda1836ca3a4b9b971ac7807301d5ac83405)** to **[`5a4ba58`](https://github.com/sagemath/sagetrac-mirror/commit/5a4ba58a3ebe5f882d0aa91ece68a7cdf3df3ec0)**

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
<div id="comment:5"></div>

Branch pushed to git repo; I updated commit sha1. New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/5a4ba58a3ebe5f882d0aa91ece68a7cdf3df3ec0"><code>5a4ba58</code></a></td><td><code>remove another unused import</code></td></tr></table>

**Comment by fchapoton** [comment]
<div id="comment:6" align="right">comment:6</div>

back to needs review, with green lights

**Comment by vbraun** [comment]
Changed branch from **[u/chapoton/34802](https://github.com/sagemath/sagetrac-mirror/tree/u/chapoton/34802)** to **[`5a4ba58`](https://github.com/sagemath/sagetrac-mirror/commit/5a4ba58a3ebe5f882d0aa91ece68a7cdf3df3ec0)**
