### ISSUE TITLE
src/doc/en/installation/source.rst gives CRITICAL sphinx warnings

### ISSUE THREAD

**Issue by dimpase** [sagemath/sage#34813]
<div id="comment:0"></div>

```
[sagemath_doc_html-none] [installat] /Users/dima/software/sage/src/doc/en/installation/source.rst:455: CRITICAL: Title level inconsistent:
[sagemath_doc_html-none] [installat] Recommended programs
[sagemath_doc_html-none] [installat] ~~~~~~~~~~~~~~~~~~~~
[sagemath_doc_html-none] [installat] /Users/dima/software/sage/src/doc/en/installation/source.rst:508: CRITICAL: Title level inconsistent:
[sagemath_doc_html-none] [installat] Tcl/Tk
[sagemath_doc_html-none] [installat] ~~~~~~
[sagemath_doc_html-none] [installat] /Users/dima/software/sage/src/doc/en/installation/source.rst:548: CRITICAL: Title level inconsistent:
[sagemath_doc_html-none] [installat] General procedure
[sagemath_doc_html-none] [installat] ~~~~~~~~~~~~~~~~~
```

Note that `~~~~~...` is not even official Sphinx.

CC:  @jhpalmieri

Component: **documentation**

Author: **Dima Pasechnik**

Branch/Commit: **[`69ac8d4`](https://github.com/sagemath/sagetrac-mirror/commit/69ac8d4e67d3d1198967c2b11a4116b4504e09c9)**

Reviewer: **John Palmieri**

_Issue created by migration from https://trac.sagemath.org/ticket/34813_

**Comment by dimpase** [comment]
Author: **Dima Pasechnik**

**Comment by dimpase** [comment]
<div id="comment:1" align="right">comment:1</div>

replaced ~~s with <sup>^</sup>s
rst determines the subheading levels dynamically, if it sees

```    
    Foo
    ---
    
    Bar
    ^^^
    
    and then
    
    Baz
    ---
    
    Oops
    ~~~~
```    
it apparently can't figure out whether `Oops` heading should be bigger or smaller
than `Bar` heading. Thus the warning, fixed here.

---
New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/69ac8d4e67d3d1198967c2b11a4116b4504e09c9"><code>69ac8d4</code></a></td><td><code>replaced ~~s with <sup>^</sup>s</code></td></tr></table>

**Comment by dimpase** [comment]
Commit: **[`69ac8d4`](https://github.com/sagemath/sagetrac-mirror/commit/69ac8d4e67d3d1198967c2b11a4116b4504e09c9)**

**Comment by dimpase** [comment]
Branch: **[u/dimpase/docs/remove_tildas](https://github.com/sagemath/sagetrac-mirror/tree/u/dimpase/docs/remove_tildas)**

**Comment by jhpalmieri** [comment]
Reviewer: **John Palmieri**

**Comment by jhpalmieri** [comment]
<div id="comment:2" align="right">comment:2</div>

Not only does this give warnings, but it seems to omit printing the section titles completely, at least on my computer, and this fixes the problem. (The Sage website has those section titles.) It is also interesting that `~~~~~~` is used in other parts of the Sage documentation without any issues (`git grep '~~~~~~' src/doc` has lots of hits).

**Comment by jhpalmieri** [comment]
<div id="comment:3" align="right">comment:3</div>

Maybe the other places just don't mix `~~~~` with `<sup>^</sup>^^` or other subsection markdown, and that's why they don't cause problems.

**Comment by dimpase** [comment]
<div id="comment:4" align="right">comment:4</div>

Replying to [John Palmieri](#comment%3A3):
> Maybe the other places just don't mix `~~~~` with `<sup>^</sup>^^` or other subsection markdown, and that's why they don't cause problems. 

it seems that sphinx does some kind of discovery to establish hierarchy of subheadings in the text, and while you can certainly use
`~~~` and `<sup>^</sup>` and other such undertitles in the text, they should not contradict the hierarchy already established.
And in the file we fix here these two were both used for the same level of subheadings, thus the warning.

**Comment by vbraun** [comment]
Changed branch from **[u/dimpase/docs/remove_tildas](https://github.com/sagemath/sagetrac-mirror/tree/u/dimpase/docs/remove_tildas)** to **[`69ac8d4`](https://github.com/sagemath/sagetrac-mirror/commit/69ac8d4e67d3d1198967c2b11a4116b4504e09c9)**
