### ISSUE TITLE
Parking functions in sets and lists behave differently

### ISSUE THREAD

**Issue by mantepse** [sagemath/sage#34817]
<div id="comment:0"></div>

I have no clue what's going on here.

```
sage: P = ParkingFunctions(3)
sage: f = P([1,1,1])
sage: g = ParkingFunction([1,1,1])
sage: f in P
True
sage: g in P
True
sage: f in list(P)
True
sage: g in list(P)
True
sage: f in set(P)
True
sage: g in set(P)
False
```

Component: **combinatorics**

_Issue created by migration from https://trac.sagemath.org/ticket/34817_

**Comment by mantepse** [comment]
Description changed:
``````diff
--- 
+++ 
@@ -8,6 +8,10 @@
 True
 sage: g in P
 True
+sage: f in list(P)
+True
+sage: g in list(P)
+True
 sage: f in set(P)
 True
 sage: g in set(P)
``````

**Comment by dimpase** [comment]
<div id="comment:2" align="right">comment:2</div>

note that `f` and `g` have different parents:

```
sage: f.parent()
Parking functions of size 3
sage: g.parent()
Parking functions
```
now you have `f in set(P)`, so all parents of elements of `set(P)` should be `Parking functions of size 3`. So `g` is not there as it has a different parent.

**Comment by mantepse** [comment]
<div id="comment:3" align="right">comment:3</div>

I accidentally opened #34824, which now deals with the issue.  Sorry.
