### ISSUE TITLE
Numerical separators behave inconsistently

### ISSUE THREAD

**Issue by io4** [sagemath/sage#34819]
<div id="comment:0"></div>

PEP 515 numerical separators (such as 1_000_000, as introduced in #28490) behave inconsistently, ignoring everything after the first separator upon conversion to a different precision.

Reproduction:

```
    sage: z = 1_0000.000000000000000000000000000000000000
    sage: z # works as expected without the conversion
    10000.000000000000000000000000000000000000
    sage: RR(z)
    1.00000000000000
```

SageMath version 9.5, Release Date: 2022-01-30, Using Python 3.10.6, OS: Ubuntu 22.04.1

Also reproduces on Sage 9.7

Component: **python3**

Author: **Lucas Fiegl**

Branch/Commit: **[`7aac175`](https://github.com/sagemath/sagetrac-mirror/commit/7aac17573027833982f6c5fe64ab66959cea4ccb)**

Reviewer: **Marc Mezzarobba**

_Issue created by migration from https://trac.sagemath.org/ticket/34819_

**Comment by DaveWitteMorris** [comment]
<div id="comment:1" align="right">comment:1</div>

I suspect the incorrect value arises here (lines 1461-1465) in `src/sage/rings/real_mpfr.pyx`:

```
if isinstance(x, RealLiteral):
    s = (<RealLiteral>x).literal
    base = (<RealLiteral>x).base
    if mpfr_set_str(self.value, str_to_bytes(s), base, parent.rnd):
        self._set(s, base)
```
The [documentation of `mpfr_strtofr`](https://machinecognitis.github.io/Math.Mpfr.Native/html/31cf29bb-b672-5829-a62d-f91e9547eb0c.htm) says "The subject sequence is defined as the longest initial subsequence of the input string, starting with the first non-whitespace character, that is of the expected form." That could explain why everything after the first underscore is ignored.

Several lines later in the same method, I see:

```
s = str(x).replace(' ','').replace('_', '')
```
Maybe we could solve the problem by applying this replacement in the `__init__` method, which is defined later (lines 5669-5685) in the same file:

```
def __init__(self, RealField_class parent, x=0, int base=10):
        <snip docstring>
    RealNumber.__init__(self, parent, x, base)
    if isinstance(x, str):
        self.base = base
        self.literal = x
```
I.e., perhaps we should strip the underscores (and spaces?) before assigning to `self.literal`.

**Comment by io4** [comment]
<div id="comment:2" align="right">comment:2</div>

Seems that the purpose of stripping spaces is to faciliate comparation with "NaN+NaN*I" (whose default stringification contains spaces) so that shouldn't be needed.

Removing underscores before setting self.literal does fix the issue.

**Comment by io4** [comment]
Branch: **[u/gh-io4/numerical_separators_behave_inconsistently](https://github.com/sagemath/sagetrac-mirror/tree/u/gh-io4/numerical_separators_behave_inconsistently)**

**Comment by io4** [comment]
<div id="comment:4"></div>

New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/7aac17573027833982f6c5fe64ab66959cea4ccb"><code>7aac175</code></a></td><td><code>Remove numerical separators from RealLiterals to avoid conversion issues</code></td></tr></table>

**Comment by io4** [comment]
Commit: **[`7aac175`](https://github.com/sagemath/sagetrac-mirror/commit/7aac17573027833982f6c5fe64ab66959cea4ccb)**

**Comment by mezzarobba** [comment]
Author: **Lucas Fiegl**

**Comment by mezzarobba** [comment]
<div id="comment:5" align="right">comment:5</div>

lgtm, thanks for the fix!

**Comment by mezzarobba** [comment]
Reviewer: **Marc Mezzarobba**

**Comment by vbraun** [comment]
Changed branch from **[u/gh-io4/numerical_separators_behave_inconsistently](https://github.com/sagemath/sagetrac-mirror/tree/u/gh-io4/numerical_separators_behave_inconsistently)** to **[`7aac175`](https://github.com/sagemath/sagetrac-mirror/commit/7aac17573027833982f6c5fe64ab66959cea4ccb)**
