### ISSUE TITLE
rational maps for WeierstrassIsomorphism should not be polynomials

### ISSUE THREAD

**Issue by yyyyx4** [sagemath/sage#34811]
<div id="comment:0"></div>

The methods `.rational_maps()` and `.x_rational_map()` for `WeierstrassIsomorphism` return polynomials, but the same methods for other `EllipticCurveHom` return rational maps (i.e., elements of the fraction field).

For consistency, these methods should return the same types in all child classes of `EllipticCurveHom`, despite the rational maps actually having denominator `1` in this case.

Component: **elliptic curves**

Author: **Lorenz Panny**

Branch/Commit: **[`551d007`](https://github.com/sagemath/sagetrac-mirror/commit/551d0070ad4de4fc52649bdd62ffbe8706cc2373)**

Reviewer: **Travis Scrimshaw**

_Issue created by migration from https://trac.sagemath.org/ticket/34811_

**Comment by yyyyx4** [comment]
Commit: **[`551d007`](https://github.com/sagemath/sagetrac-mirror/commit/551d0070ad4de4fc52649bdd62ffbe8706cc2373)**

**Comment by yyyyx4** [comment]
Author: **Lorenz Panny**

**Comment by yyyyx4** [comment]
Branch: **[public/34811](https://github.com/sagemath/sagetrac-mirror/tree/public/34811)**

**Comment by tscrim** [comment]
Reviewer: **Travis Scrimshaw**

**Comment by tscrim** [comment]
<div id="comment:3" align="right">comment:3</div>

LGTM.

**Comment by vbraun** [comment]
Changed branch from **[public/34811](https://github.com/sagemath/sagetrac-mirror/tree/public/34811)** to **[`551d007`](https://github.com/sagemath/sagetrac-mirror/commit/551d0070ad4de4fc52649bdd62ffbe8706cc2373)**
