### ISSUE TITLE
pep cleanup in parallel/

### ISSUE THREAD

**Issue by fchapoton** [sagemath/sage#34815]
<div id="comment:0"></div>

also some pylint and codespell fixes there

CC:  @dcoudert @kwankyu

Component: **refactoring**

Author: **Frédéric Chapoton**

Branch/Commit: **[`f930224`](https://github.com/sagemath/sagetrac-mirror/commit/f93022471db0b5ceebb0d127a89aed8796865df4)**

Reviewer: **Matthias Koeppe**

_Issue created by migration from https://trac.sagemath.org/ticket/34815_

**Comment by fchapoton** [comment]
Branch: **[u/chapoton/34815](https://github.com/sagemath/sagetrac-mirror/tree/u/chapoton/34815)**

**Comment by fchapoton** [comment]
<div id="comment:1"></div>

New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/f93022471db0b5ceebb0d127a89aed8796865df4"><code>f930224</code></a></td><td><code>pep cleanup in parallel/</code></td></tr></table>

**Comment by fchapoton** [comment]
Commit: **[`f930224`](https://github.com/sagemath/sagetrac-mirror/commit/f93022471db0b5ceebb0d127a89aed8796865df4)**

**Comment by fchapoton** [comment]
<div id="comment:2" align="right">comment:2</div>

green bot, so please review

**Comment by mkoeppe** [comment]
Reviewer: **Matthias Koeppe**

**Comment by vbraun** [comment]
Changed branch from **[u/chapoton/34815](https://github.com/sagemath/sagetrac-mirror/tree/u/chapoton/34815)** to **[`f930224`](https://github.com/sagemath/sagetrac-mirror/commit/f93022471db0b5ceebb0d127a89aed8796865df4)**
