### ISSUE TITLE
adding the ring of integer-valued polynomials

### ISSUE THREAD

**Issue by fchapoton** [sagemath/sage#34814]
<div id="comment:0"></div>

in two different basis

CC:  @tscrim

Component: **commutative algebra**

Author: **Frédéric Chapoton**

_Issue created by migration from https://trac.sagemath.org/ticket/34814_

**Comment by fchapoton** [comment]
Branch: **[u/chapoton/34814](https://github.com/sagemath/sagetrac-mirror/tree/u/chapoton/34814)**

**Comment by fchapoton** [comment]
Commit: **[`901a695`](https://github.com/sagemath/sagetrac-mirror/commit/901a6958b9bb0be4815906cdaac1ee4098b3e265)**

**Comment by fchapoton** [comment]
<div id="comment:1" align="right">comment:1</div>

probably still a bit rough..

---
New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/901a6958b9bb0be4815906cdaac1ee4098b3e265"><code>901a695</code></a></td><td><code>adding the ring of integer-valued polynomials</code></td></tr></table>

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
Changed commit from **[`901a695`](https://github.com/sagemath/sagetrac-mirror/commit/901a6958b9bb0be4815906cdaac1ee4098b3e265)** to **[`bdafb11`](https://github.com/sagemath/sagetrac-mirror/commit/bdafb11a746418f9b3e95d4cc5eac182348fa3f5)**

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
<div id="comment:2"></div>

Branch pushed to git repo; I updated commit sha1. New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/bdafb11a746418f9b3e95d4cc5eac182348fa3f5"><code>bdafb11</code></a></td><td><code>remove commented code and alias</code></td></tr></table>

**Comment by mkoeppe** [comment]
<div id="comment:3" align="right">comment:3</div>

`PositiveBasis` seems like a terrible name to put in the global namespace. Perhaps make `IntegerValuedPolynomialRing` a constructor that takes a keyword for selecting the basis?

**Comment by fchapoton** [comment]
<div id="comment:4" align="right">comment:4</div>

Yes, I agree. It should be better to use a standard mechanism for "algebras with several bases". This mechanism exists and is used in several places but I do not master this for the moment.

Travis, would you know and tell me what I should do exactly in this direction ?

**Comment by tscrim** [comment]
<div id="comment:5" align="right">comment:5</div>

There are 2 ways to deal with multiple bases:

1. All bases are "equally good." Here, you would use the `WithRealizations` framework. See, e.g., the `DescentAlgebra` or many of the CHAs.

2. One basis is more special than the others. So the main global hook goes into that basis, and then you have methods that construct other bases. This is how I would model, e.g., Schubert polynomials as a basis for the polynomial ring.

To me, it seems like (2) is the situation here.

**Comment by mkoeppe** [comment]
Removed branch from the issue description because it has been replaced by PR #34988
