### ISSUE TITLE
Error when defining differentials over GCA's with relations.

### ISSUE THREAD

**Issue by miguelmarco** [sagemath/sage#34818]
<div id="comment:0"></div>

The following code

```
sage: A.<a,b,x,u> = GradedCommutativeAlgebra(QQ,degrees=(2,2,3,3))
sage: A = A.quotient(A.ideal([a*u,b*u,x*u]))
sage: A.cdg_algebra({a:u,x:a*b})
```

Produces an error

```
...

File ~/sage/src/sage/algebras/commutative_dga.py:253, in Differential.__init__(self, A, im_gens)
    251 for i in A.gens():
    252     if not self(self(i)).is_zero():
--> 253         raise ValueError("The given dictionary does not determine a valid differential")

ValueError: The given dictionary does not determine a valid differential

```

which is wrong, because the differential is valid in the quotient algebra.

It seems that the computations for the differential are done in the free algebra instead of the quotient one.

CC:  @tscrim @jhpalmieri

Component: **algebra**

Author: **Miguel Marco**

Branch/Commit: **[`8ba265b`](https://github.com/sagemath/sagetrac-mirror/commit/8ba265bd345917f100fbbb5b8f15753a357adfa2)**

Reviewer: **Travis Scrimshaw**

_Issue created by migration from https://trac.sagemath.org/ticket/34818_

**Comment by miguelmarco** [comment]
Branch: **[u/mmarco/error_when_defining_differentials_over_gca_s_with_relations_](https://github.com/sagemath/sagetrac-mirror/tree/u/mmarco/error_when_defining_differentials_over_gca_s_with_relations_)**

**Comment by miguelmarco** [comment]
Commit: **[`fe84785`](https://github.com/sagemath/sagetrac-mirror/commit/fe8478578b274536b46c4734fb1bb7da0e4b0657)**

**Comment by miguelmarco** [comment]
<div id="comment:2"></div>

New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/fe8478578b274536b46c4734fb1bb7da0e4b0657"><code>fe84785</code></a></td><td><code>Check for ideal preservation without creating an auxiliary algebra with non-valid differential</code></td></tr></table>

**Comment by tscrim** [comment]
<div id="comment:3" align="right">comment:3</div>

A few minor things:

```diff
-Check that #34818 is solved::
+Check that :trac:`34818` is solved::
```

```diff
         if isinstance(im_gens, (list, tuple)):
-           im_gens = {A.gen(i): x for i, x in enumerate(im_gens)}
-
-        im_gens = {A(a): A(im_gens[a]) for a in im_gens}
+           im_gens = {A.gen(i): A(x) for i, x in enumerate(im_gens)}
+        else:
+            im_gens = {A(a): A(im_gens[a]) for a in im_gens}
```

```diff
         def image_monomial(exponent):
             i = 0
             cexp = list(exponent)
             while i < len(cexp):
-                if cexp[i] == 0:
+                if not cexp[i]:
                     i +=1
                     continue
                 a = A.gen(i)
                 try:
                     da = im_gens[a]
                 except KeyError:
                     da = A.zero()
                 cexp[i] -= 1
-                b = prod([A.gen(j)**cexp[j] for j in range(len(cexp))])
+                b = prod(A.gen(j) ** cexp[j] for j in range(len(cexp)))
                 db = image_monomial(cexp)
-                im =  da * b + (-1)**A._degrees[i]*a*db
-                return(A(im))
+                im =  da * b + (-1)**A._degrees[i] * a * db
+                return A(im)
             return A.zero()
 
         for g in I.gens():
             d = g.dict()
-            res = A(sum([d[ex]*image_monomial(ex) for ex in d]))
+            res = A.sum(d[ex] * image_monomial(ex) for ex in d)
             if not res.is_zero():
-                raise ValueError("The differential does not preserve the ideal")
+                raise ValueError("the differential does not preserve the ideal")
```
Note that this last change might change a few error messages, but this is to follow a Python convention.

**Comment by miguelmarco** [comment]
<div id="comment:4" align="right">comment:4</div>

Your changes look good. Can you push them?

**Comment by tscrim** [comment]
Changed commit from **[`fe84785`](https://github.com/sagemath/sagetrac-mirror/commit/fe8478578b274536b46c4734fb1bb7da0e4b0657)** to **[`9fde881`](https://github.com/sagemath/sagetrac-mirror/commit/9fde88137fe5f849c9d20456f84cd8d3fc9397d8)**

**Comment by tscrim** [comment]
Changed branch from **[u/mmarco/error_when_defining_differentials_over_gca_s_with_relations_](https://github.com/sagemath/sagetrac-mirror/tree/u/mmarco/error_when_defining_differentials_over_gca_s_with_relations_)** to **[u/tscrim/differential_gca_relations-34818](https://github.com/sagemath/sagetrac-mirror/tree/u/tscrim/differential_gca_relations-34818)**

**Comment by tscrim** [comment]
<div id="comment:5" align="right">comment:5</div>

Done. I also took the liberty of making all of the error messages in the file follow the Python convention (to help prevent any inconsistencies).
  
---
New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/9fde88137fe5f849c9d20456f84cd8d3fc9397d8"><code>9fde881</code></a></td><td><code>Some small reviewer changes.</code></td></tr></table>

**Comment by tscrim** [comment]
Reviewer: **Travis Scrimshaw**

**Comment by miguelmarco** [comment]
<div id="comment:6" align="right">comment:6</div>

Great!

It can be set to positive review if nobody objects.

**Comment by fchapoton** [comment]
<div id="comment:7" align="right">comment:7</div>

pyflakes plugin says

```
+src/sage/algebras/commutative_dga.py:203:13 local variable 'squares' is assigned to but never used
```

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
<div id="comment:8"></div>

Branch pushed to git repo; I updated commit sha1. New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/a8600ba71fa962cc5e6419dbae43cb5407331789"><code>a8600ba</code></a></td><td><code>Removing the squares ideal.</code></td></tr></table>

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
Changed commit from **[`9fde881`](https://github.com/sagemath/sagetrac-mirror/commit/9fde88137fe5f849c9d20456f84cd8d3fc9397d8)** to **[`a8600ba`](https://github.com/sagemath/sagetrac-mirror/commit/a8600ba71fa962cc5e6419dbae43cb5407331789)**

**Comment by tscrim** [comment]
<div id="comment:9" align="right">comment:9</div>

Fixed.

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
Changed commit from **[`a8600ba`](https://github.com/sagemath/sagetrac-mirror/commit/a8600ba71fa962cc5e6419dbae43cb5407331789)** to **[`2bf730c`](https://github.com/sagemath/sagetrac-mirror/commit/2bf730c0f276ca0adf77bc9eab30ea10cbdaec1e)**

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
<div id="comment:10"></div>

Branch pushed to git repo; I updated commit sha1. New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/2bf730c0f276ca0adf77bc9eab30ea10cbdaec1e"><code>2bf730c</code></a></td><td><code>Merge branch 'develop' into u/tscrim/differential_gca_relations-34818</code></td></tr></table>

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
Changed commit from **[`2bf730c`](https://github.com/sagemath/sagetrac-mirror/commit/2bf730c0f276ca0adf77bc9eab30ea10cbdaec1e)** to **[`8ba265b`](https://github.com/sagemath/sagetrac-mirror/commit/8ba265bd345917f100fbbb5b8f15753a357adfa2)**

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
<div id="comment:11"></div>

Branch pushed to git repo; I updated commit sha1. New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/8ba265bd345917f100fbbb5b8f15753a357adfa2"><code>8ba265b</code></a></td><td><code>Addressing pyflakes.</code></td></tr></table>

**Comment by tscrim** [comment]
<div id="comment:12" align="right">comment:12</div>

Green bot modulo the pyflakes unused variable I just removed.

**Comment by tscrim** [comment]
<div id="comment:13" align="right">comment:13</div>

Morally green bot.

**Comment by miguelmarco** [comment]
<div id="comment:14" align="right">comment:14</div>

Positive review then?

**Comment by tscrim** [comment]
<div id="comment:15" align="right">comment:15</div>

Assuming Frédéric has no further ones, I think so.

**Comment by vbraun** [comment]
Changed branch from **[u/tscrim/differential_gca_relations-34818](https://github.com/sagemath/sagetrac-mirror/tree/u/tscrim/differential_gca_relations-34818)** to **[`8ba265b`](https://github.com/sagemath/sagetrac-mirror/commit/8ba265bd345917f100fbbb5b8f15753a357adfa2)**
