### ISSUE TITLE
Better position the camera in 3d graphics

### ISSUE THREAD

**Issue by kwankyu** [sagemath/sage#34822]
<div id="comment:0"></div>

Compare "before" and "after" of 

```sage
var('x,y,z')
implicit_plot3d((sqrt(x*x+y*y)-3)^2 + z*z - 1, (x,-4,4), (y,-4,4), (z,-1,1))
```
by the initial view and rotated views.

Component: **graphics**

Author: **Kwankyu Lee**

_Issue created by migration from https://trac.sagemath.org/ticket/34822_

**Comment by kwankyu** [comment]
Branch: **[u/klee/better_position_the_camera_in_3d_graphics](https://github.com/sagemath/sagetrac-mirror/tree/u/klee/better_position_the_camera_in_3d_graphics)**

**Comment by kwankyu** [comment]
Author: **Kwankyu Lee**

**Comment by kwankyu** [comment]
Commit: **[`c06d290`](https://github.com/sagemath/sagetrac-mirror/commit/c06d29073f11f35f78d4103516c773ca023d7750)**

**Comment by kwankyu** [comment]
<div id="comment:2"></div>

New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/c06d29073f11f35f78d4103516c773ca023d7750"><code>c06d290</code></a></td><td><code>Improve camera positioning for threejs</code></td></tr></table>

**Comment by kwankyu** [comment]
Description changed:
``````diff
--- 
+++ 
@@ -1 +1,9 @@
+Compare "before" and "after" of 
 
+```sage
+var('x,y,z')
+implicit_plot3d((sqrt(x*x+y*y)-3)^2 + z*z - 1, (x,-4,4), (y,-4,4), (z,-1,1))
+```
+by the initial position and by rotating.
+
+In "Build Documenation", the still images are broken. Locally there is no problem.
``````

**Comment by kwankyu** [comment]
Description changed:
``````diff
--- 
+++ 
@@ -6,4 +6,4 @@
 ```
 by the initial position and by rotating.
 
-In "Build Documenation", the still images are broken. Locally there is no problem.
+In "Build Documenation", the still images are broken. Locally there is no problem. Report if you see the broken still images locally.
``````

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
Changed commit from **[`c06d290`](https://github.com/sagemath/sagetrac-mirror/commit/c06d29073f11f35f78d4103516c773ca023d7750)** to **[`067b88b`](https://github.com/sagemath/sagetrac-mirror/commit/067b88bf9c2ca6cc393b9ea3dece71d8be09766f)**

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
<div id="comment:7"></div>

Branch pushed to git repo; I updated commit sha1. New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/067b88bf9c2ca6cc393b9ea3dece71d8be09766f"><code>067b88b</code></a></td><td><code>Adjust angles to be more human-friendly</code></td></tr></table>

**Comment by kwankyu** [comment]
Description changed:
``````diff
--- 
+++ 
@@ -4,6 +4,6 @@
 var('x,y,z')
 implicit_plot3d((sqrt(x*x+y*y)-3)^2 + z*z - 1, (x,-4,4), (y,-4,4), (z,-1,1))
 ```
-by the initial position and by rotating.
+by the initial view and rotated views.
 
-In "Build Documenation", the still images are broken. Locally there is no problem. Report if you see the broken still images locally.
+Note that in "Build Documenation", the still images are broken. This is not new and not related with this ticket.
``````

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
Changed commit from **[`067b88b`](https://github.com/sagemath/sagetrac-mirror/commit/067b88bf9c2ca6cc393b9ea3dece71d8be09766f)** to **[`0c45076`](https://github.com/sagemath/sagetrac-mirror/commit/0c45076d685ac8a7d488af0296481fc23d49a3a1)**

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
<div id="comment:9"></div>

Branch pushed to git repo; I updated commit sha1. New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/0c45076d685ac8a7d488af0296481fc23d49a3a1"><code>0c45076</code></a></td><td><code>Edit the comment</code></td></tr></table>

**Comment by kwankyu** [comment]
Description changed:
``````diff
--- 
+++ 
@@ -5,5 +5,3 @@
 implicit_plot3d((sqrt(x*x+y*y)-3)^2 + z*z - 1, (x,-4,4), (y,-4,4), (z,-1,1))
 ```
 by the initial view and rotated views.
-
-Note that in "Build Documenation", the still images are broken. This is not new and not related with this ticket.
``````

**Comment by mkoeppe** [comment]
Removed branch from issue description; replaced by PR #34960
