### ISSUE TITLE
Adding some new functionality to the Vector Partition Module

### ISSUE THREAD

**Issue by 25shriya** [sagemath/sage#34827]
<div id="comment:0"></div>

We add the following types of vector partitions:

1. Vector partitions with distinct parts.
2. Vector partitions with parts from a given set.
3. Vector partitions where certain parts are allowed to repeat while others are not.

Component: **combinatorics**

Keywords: **Vector Partitions, distinct parts**

Author: **Shriya M, Amritanshu Prasad**

Branch/Commit: **[`4900861`](https://github.com/sagemath/sagetrac-mirror/commit/4900861914015b11ea463f3cd92ab06aad2d5b87)**

Reviewer: **Julian Rüth**

_Issue created by migration from https://trac.sagemath.org/ticket/34827_

**Comment by 12d81aa2-5825-4c50-9de3-ede0c21017ed** [comment]
Description changed:
``````diff
--- 
+++ 
@@ -1 +1,5 @@
-Vector Partitions of a given vector is a multiset of integer vectors that sum to it. The module for Vector Partitions in [SageMath](../wiki/SageMath) was initially developed by Dr. Amritanshu Prasad. The module contained primitive features such as enlisting all vectors lexicographically lesser than or equal to the given vector, and also generating all possible partitions of it. This new version of Vector Partitions module features distinct part partitions, partitions with a given set of parts as input and also enables repetition of certain selective parts.
+We add the following types of vector partitions:
+
+1. Vector partitions with distinct parts.
+2. Vector partitions with parts fro a given set.
+3. Vector partitions where certain parts are allowed to repeat while others are not.
``````

**Comment by 25shriya** [comment]
Description changed:
``````diff
--- 
+++ 
@@ -1,5 +1,5 @@
 We add the following types of vector partitions:
 
 1. Vector partitions with distinct parts.
-2. Vector partitions with parts fro a given set.
+2. Vector partitions with parts from a given set.
 3. Vector partitions where certain parts are allowed to repeat while others are not.
``````

**Comment by 25shriya** [comment]
Changed branch from **[u/gh-25shriya/vector_partition](https://github.com/sagemath/sagetrac-mirror/tree/u/gh-25shriya/vector_partition)** to **[u/gh-25shriya/34827](https://github.com/sagemath/sagetrac-mirror/tree/u/gh-25shriya/34827)**

**Comment by 25shriya** [comment]
Changed commit from **[`aa3f59c`](https://github.com/sagemath/sagetrac-mirror/commit/aa3f59c2cd45742d3fbba7310bfa8be07ec84bb2)** to **[`eb5a8c1`](https://github.com/sagemath/sagetrac-mirror/commit/eb5a8c199f7725c6cf5230550077873faff32de3)**

**Comment by 25shriya** [comment]
<div id="comment:3"></div>

New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/eb5a8c199f7725c6cf5230550077873faff32de3"><code>eb5a8c1</code></a></td><td><code>Modified Vector Partitions Module</code></td></tr></table>

**Comment by saraedum** [comment]
<div id="comment:5" align="right">comment:5</div>


```
then the parts which satisfy the boolean function ``is_repeatable`` is allowed to be repeated.
```

should it be "are allowed" instead?

**Comment by saraedum** [comment]
Reviewer: **Julian Rüth**

**Comment by saraedum** [comment]
<div id="comment:6" align="right">comment:6</div>

Feel free to set this to positive review once the grammar has been fixed.

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
Changed commit from **[`eb5a8c1`](https://github.com/sagemath/sagetrac-mirror/commit/eb5a8c199f7725c6cf5230550077873faff32de3)** to **[`0fb1246`](https://github.com/sagemath/sagetrac-mirror/commit/0fb1246c083c16b0a76b3318be59e7a202426b53)**

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
<div id="comment:8"></div>

Branch pushed to git repo; I updated commit sha1. New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/0fb1246c083c16b0a76b3318be59e7a202426b53"><code>0fb1246</code></a></td><td><code>Corrected Doctest</code></td></tr></table>

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
<div id="comment:9"></div>

Branch pushed to git repo; I updated commit sha1. New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/773c55c41d07ecb42746efedef5be01178ad4909"><code>773c55c</code></a></td><td><code>Corrected Doctests</code></td></tr><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/4900861914015b11ea463f3cd92ab06aad2d5b87"><code>4900861</code></a></td><td><code>Corrected Doctests</code></td></tr></table>

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
Changed commit from **[`0fb1246`](https://github.com/sagemath/sagetrac-mirror/commit/0fb1246c083c16b0a76b3318be59e7a202426b53)** to **[`4900861`](https://github.com/sagemath/sagetrac-mirror/commit/4900861914015b11ea463f3cd92ab06aad2d5b87)**

**Comment by vbraun** [comment]
Changed branch from **[u/gh-25shriya/34827](https://github.com/sagemath/sagetrac-mirror/tree/u/gh-25shriya/34827)** to **[`4900861`](https://github.com/sagemath/sagetrac-mirror/commit/4900861914015b11ea463f3cd92ab06aad2d5b87)**
