### ISSUE TITLE
Uniformize headline: noncommutative polynomials

### ISSUE THREAD

**Issue by kwankyu** [sagemath/sage#34825]
<div id="comment:0"></div>

Component: **documentation**

Author: **Kwankyu Lee**

Branch/Commit: **[`6c34279`](https://github.com/sagemath/sagetrac-mirror/commit/6c34279634da03100c2bff5ef0480622119642a2)**

Reviewer: **Matthias Koeppe**

_Issue created by migration from https://trac.sagemath.org/ticket/34825_

**Comment by kwankyu** [comment]
Branch: **[u/klee/uniformize_headline__noncommutative_polynomials](https://github.com/sagemath/sagetrac-mirror/tree/u/klee/uniformize_headline__noncommutative_polynomials)**

**Comment by kwankyu** [comment]
Commit: **[`6c34279`](https://github.com/sagemath/sagetrac-mirror/commit/6c34279634da03100c2bff5ef0480622119642a2)**

**Comment by kwankyu** [comment]
Author: **Kwankyu Lee**

**Comment by kwankyu** [comment]
<div id="comment:2"></div>

New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/6c34279634da03100c2bff5ef0480622119642a2"><code>6c34279</code></a></td><td><code>Uniformize headlines</code></td></tr></table>

**Comment by mkoeppe** [comment]
Reviewer: **Matthias Koeppe**

**Comment by kwankyu** [comment]
<div id="comment:4" align="right">comment:4</div>

Thanks!

**Comment by vbraun** [comment]
Changed branch from **[u/klee/uniformize_headline__noncommutative_polynomials](https://github.com/sagemath/sagetrac-mirror/tree/u/klee/uniformize_headline__noncommutative_polynomials)** to **[`6c34279`](https://github.com/sagemath/sagetrac-mirror/commit/6c34279634da03100c2bff5ef0480622119642a2)**
