### ISSUE TITLE
deprecate is_GapElement

### ISSUE THREAD

**Issue by dimpase** [sagemath/sage#34823]
<div id="comment:0"></div>

Removing the last uses of `is_GapElement`, deprecating it

Depends on #34770

CC:  @mkoeppe

Component: **interfaces**

Author: **Dima Pasechnik**

Branch/Commit: **[`e99db3a`](https://github.com/sagemath/sagetrac-mirror/commit/e99db3af3a814e9accdd10a915f651aabe9faa91)**

Reviewer: **Matthias Koeppe**

_Issue created by migration from https://trac.sagemath.org/ticket/34823_

**Comment by dimpase** [comment]
Author: **Dima Pasechnik**

**Comment by dimpase** [comment]
Description changed:
``````diff
--- 
+++ 
@@ -1 +1 @@
-
+Removing the last uses of `is_GapElement`, deprecating it
``````

**Comment by dimpase** [comment]
Commit: **[`7c67a10`](https://github.com/sagemath/sagetrac-mirror/commit/7c67a1089852beca7b5e0b80ad3cb2a319f0ceef)**

**Comment by dimpase** [comment]
Branch: **[u/dimpase/rings/remove_last_is_GapElement](https://github.com/sagemath/sagetrac-mirror/tree/u/dimpase/rings/remove_last_is_GapElement)**

**Comment by dimpase** [comment]
<div id="comment:2"></div>

New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/21e38a73fa41698d02ec4c00597e35b5dbd0eda6"><code>21e38a7</code></a></td><td><code>fix coersion of libgap FFelements; switch to libgap</code></td></tr><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/d4bde80f350975b30e5795aa5ffc7333f5c80911"><code>d4bde80</code></a></td><td><code>make imports of is_GapEelment uniform across files</code></td></tr><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/eb72ef050d94dd32cbb1499243af5de4e9eec22c"><code>eb72ef0</code></a></td><td><code>avoid is_GapElement</code></td></tr><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/1c4a69fdfee7ccf9aebb40bbc29b4453852cacb1"><code>1c4a69f</code></a></td><td><code>use GapElement from an abstract superclass</code></td></tr><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/6e5ea791a3d846cfd70d9b361f168f6c2fa66a2b"><code>6e5ea79</code></a></td><td><code>move import of libgap into a function</code></td></tr><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/adc231ef98032f86f42167a98dd86f3800f1ee9f"><code>adc231e</code></a></td><td><code>remove is_GapElement from number fields code</code></td></tr><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/7c67a1089852beca7b5e0b80ad3cb2a319f0ceef"><code>7c67a10</code></a></td><td><code>deprecating is_GapElement</code></td></tr></table>

**Comment by dimpase** [comment]
<div id="comment:3" align="right">comment:3</div>

`sage/rings/` still need work to convert to `libgap`, it's not done here.

**Comment by mkoeppe** [comment]
<div id="comment:4" align="right">comment:4</div>


```
 def is_GapElement(x):
     """
+    Deprecated function
+
+    Use isinstance(x,GapElement)
+
     Returns True if x is a GapElement.
 
     EXAMPLES::
 
         sage: from sage.interfaces.gap import is_GapElement
         sage: is_GapElement(gap(2))
+        doctest:...: DeprecationWarning: The function is_GapElement is deprecated. Use isinstance(x, GapElement) instead
+        See https://trac.sagemath.org/34823 for details.
```

This needs better rst markup. Also, I think the message should point to sage.interfaces.abc specifically

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
<div id="comment:5"></div>

Branch pushed to git repo; I updated commit sha1. New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/6c75e9b0cc5679ee9ea5773ca1586eacf438e378"><code>6c75e9b</code></a></td><td><code>better rst, point at sage.interfaces.abc to use</code></td></tr></table>

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
Changed commit from **[`7c67a10`](https://github.com/sagemath/sagetrac-mirror/commit/7c67a1089852beca7b5e0b80ad3cb2a319f0ceef)** to **[`6c75e9b`](https://github.com/sagemath/sagetrac-mirror/commit/6c75e9b0cc5679ee9ea5773ca1586eacf438e378)**

**Comment by dimpase** [comment]
<div id="comment:6" align="right">comment:6</div>

OK, done

**Comment by mkoeppe** [comment]
Changed branch from **[u/dimpase/rings/remove_last_is_GapElement](https://github.com/sagemath/sagetrac-mirror/tree/u/dimpase/rings/remove_last_is_GapElement)** to **[u/mkoeppe/rings/remove_last_is_GapElement](https://github.com/sagemath/sagetrac-mirror/tree/u/mkoeppe/rings/remove_last_is_GapElement)**

**Comment by mkoeppe** [comment]
Reviewer: **Matthias Koeppe**

**Comment by mkoeppe** [comment]
Changed commit from **[`6c75e9b`](https://github.com/sagemath/sagetrac-mirror/commit/6c75e9b0cc5679ee9ea5773ca1586eacf438e378)** to **[`e99db3a`](https://github.com/sagemath/sagetrac-mirror/commit/e99db3af3a814e9accdd10a915f651aabe9faa91)**

**Comment by mkoeppe** [comment]
<div id="comment:8"></div>

New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/e99db3af3a814e9accdd10a915f651aabe9faa91"><code>e99db3a</code></a></td><td><code>src/sage/interfaces/gap.py: Reviewer edits</code></td></tr></table>

**Comment by vbraun** [comment]
Changed branch from **[u/mkoeppe/rings/remove_last_is_GapElement](https://github.com/sagemath/sagetrac-mirror/tree/u/mkoeppe/rings/remove_last_is_GapElement)** to **[`e99db3a`](https://github.com/sagemath/sagetrac-mirror/commit/e99db3af3a814e9accdd10a915f651aabe9faa91)**
