### ISSUE TITLE
openblas: Remove python from dependencies

### ISSUE THREAD

**Issue by mkoeppe** [sagemath/sage#34835]
<div id="comment:0"></div>

The installation uses `sage-bootstrap-python`, so the order-only dependency on `$(PYTHON)` can be removed

CC:  @dimpase

Component: **build**

Author: **Matthias Koeppe**

Branch/Commit: **[`e6bb8e6`](https://github.com/sagemath/sagetrac-mirror/commit/e6bb8e6bae03cb7760ccf5674a08cbc59d7e25fd)**

Reviewer: **Dima Pasechnik**

_Issue created by migration from https://trac.sagemath.org/ticket/34835_

**Comment by mkoeppe** [comment]
Branch: **[u/mkoeppe/openblas__remove_python_from_dependencies](https://github.com/sagemath/sagetrac-mirror/tree/u/mkoeppe/openblas__remove_python_from_dependencies)**

**Comment by mkoeppe** [comment]
Commit: **[`e6bb8e6`](https://github.com/sagemath/sagetrac-mirror/commit/e6bb8e6bae03cb7760ccf5674a08cbc59d7e25fd)**

**Comment by mkoeppe** [comment]
<div id="comment:2"></div>

New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/e6bb8e6bae03cb7760ccf5674a08cbc59d7e25fd"><code>e6bb8e6</code></a></td><td><code>build/pkgs/openblas/dependencies: Remove python</code></td></tr></table>

**Comment by mkoeppe** [comment]
Author: **Matthias Koeppe**

**Comment by dimpase** [comment]
<div id="comment:3" align="right">comment:3</div>

lgtm

**Comment by dimpase** [comment]
Reviewer: **Dima Pasechnik**

**Comment by mkoeppe** [comment]
<div id="comment:5" align="right">comment:5</div>

Thanks!

**Comment by vbraun** [comment]
Changed branch from **[u/mkoeppe/openblas__remove_python_from_dependencies](https://github.com/sagemath/sagetrac-mirror/tree/u/mkoeppe/openblas__remove_python_from_dependencies)** to **[`e6bb8e6`](https://github.com/sagemath/sagetrac-mirror/commit/e6bb8e6bae03cb7760ccf5674a08cbc59d7e25fd)**
