### ISSUE TITLE
sagemath-standard: Add missing dependency typing_extensions, set lower bounds for backport packages

### ISSUE THREAD

**Issue by mkoeppe** [sagemath/sage#34831]
<div id="comment:0"></div>

Used in `src/sage/dynamics/arithmetic_dynamics/projective_ds.py`.

We also set lower version bounds for backport packages `importlib_resources`, `importlib_metadata`, `typing_extensions` so that Sage developers can use Python 3.11 features.

CC:  @kwankyu @EnderWannabe @tobiasdiez

Component: **build**

Author: **Matthias Koeppe**

_Issue created by migration from https://trac.sagemath.org/ticket/34831_

**Comment by mkoeppe** [comment]
Branch: **[u/mkoeppe/sagemath_standard__add_missing_dependency_typing_extensions](https://github.com/sagemath/sagetrac-mirror/tree/u/mkoeppe/sagemath_standard__add_missing_dependency_typing_extensions)**

**Comment by mkoeppe** [comment]
Commit: **[`4e48354`](https://github.com/sagemath/sagetrac-mirror/commit/4e4835446c36e9e66d50daa1c85d0a02e88bf168)**

**Comment by mkoeppe** [comment]
<div id="comment:2" align="right">comment:2</div>

Actually the import seems unused in that file, but it's good to have this backport package as a dependency as preparation for more type annotations.

---
New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/4e4835446c36e9e66d50daa1c85d0a02e88bf168"><code>4e48354</code></a></td><td><code>sagelib: Add typing_extensions as a dependency</code></td></tr></table>

**Comment by mkoeppe** [comment]
Author: **Matthias Koeppe**

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
Changed commit from **[`4e48354`](https://github.com/sagemath/sagetrac-mirror/commit/4e4835446c36e9e66d50daa1c85d0a02e88bf168)** to **[`10dbc18`](https://github.com/sagemath/sagetrac-mirror/commit/10dbc18658b1e374637dfd7ec2ff79558e9a3e68)**

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
<div id="comment:4"></div>

Branch pushed to git repo; I updated commit sha1. New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/10dbc18658b1e374637dfd7ec2ff79558e9a3e68"><code>10dbc18</code></a></td><td><code>src/doc/en/developer/coding_in_python.rst: Mention typing_extensions</code></td></tr></table>

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
Changed commit from **[`10dbc18`](https://github.com/sagemath/sagetrac-mirror/commit/10dbc18658b1e374637dfd7ec2ff79558e9a3e68)** to **[`b9ac6a2`](https://github.com/sagemath/sagetrac-mirror/commit/b9ac6a247c1e56165e009a39e211e7969edfdb6a)**

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
<div id="comment:5"></div>

Branch pushed to git repo; I updated commit sha1. New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/b9ac6a247c1e56165e009a39e211e7969edfdb6a"><code>b9ac6a2</code></a></td><td><code>sagelib: Add importlib_metadata, importlib_resources as dependencies</code></td></tr></table>

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
<div id="comment:6"></div>

Branch pushed to git repo; I updated commit sha1. New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/d5c0748b1f10b14baf8feac8c6f7e3c043cda589"><code>d5c0748</code></a></td><td><code>build/pkgs/{importlib_metadata,importlib_resources,typing_extensions}/install-requires.txt: Set lower bounds for Python 3.11 features</code></td></tr></table>

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
Changed commit from **[`b9ac6a2`](https://github.com/sagemath/sagetrac-mirror/commit/b9ac6a247c1e56165e009a39e211e7969edfdb6a)** to **[`d5c0748`](https://github.com/sagemath/sagetrac-mirror/commit/d5c0748b1f10b14baf8feac8c6f7e3c043cda589)**

**Comment by mkoeppe** [comment]
Description changed:
``````diff
--- 
+++ 
@@ -1 +1,4 @@
-Used in `src/sage/dynamics/arithmetic_dynamics/projective_ds.py`
+Used in `src/sage/dynamics/arithmetic_dynamics/projective_ds.py`.
+
+We also set lower version bounds for backport packages `importlib_resources`, `importlib_metadata`, `typing_extensions` so that Sage developers can use Python 3.11 features.
+
``````

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
Changed commit from **[`d5c0748`](https://github.com/sagemath/sagetrac-mirror/commit/d5c0748b1f10b14baf8feac8c6f7e3c043cda589)** to **[`ecd18a9`](https://github.com/sagemath/sagetrac-mirror/commit/ecd18a915e5895bdd0a5c8c318c94092e6ba47ac)**

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
<div id="comment:8"></div>

Branch pushed to git repo; I updated commit sha1. New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/ecd18a915e5895bdd0a5c8c318c94092e6ba47ac"><code>ecd18a9</code></a></td><td><code>src/doc/en/developer/coding_in_python.rst: Fix markup</code></td></tr></table>

**Comment by EnderWannabe** [comment]
<div id="comment:9" align="right">comment:9</div>

Replying to [Matthias Köppe](#comment%3A2):
> Actually the import seems unused in that file, but it's good to have this backport package as a dependency as preparation for more type annotations.

I can't say I have any idea why I added this import. It seems like it can (and perhaps should) be removed.

**Comment by mkoeppe** [comment]
<div id="comment:10" align="right">comment:10</div>

I've opened #34859 to remove it.

**Comment by mkoeppe** [comment]
Branch has merge conflicts

**Comment by mkoeppe** [comment]
Removed branch from issue description; replaced by PR #35203
