### ISSUE TITLE
Support tox 4

### ISSUE THREAD

**Issue by mkoeppe** [sagemath/sage#34839]
<div id="comment:0"></div>

tox 4 renamed a tox.ini configuration keyword and has slightly changed quoting behavior.
 
Also tox >= 3.18 supports the renamed keyword - https://tox.wiki/en/3.27.1/changelog.html#v3-18-0-2020-07-23

Also the changed quote works with both versions.

Component: **packages: standard**

Author: **Matthias Koeppe, Frédéric Chapoton**

Branch/Commit: **[`70da140`](https://github.com/sagemath/sagetrac-mirror/commit/70da140f5f430c1cab53a858a8b33d43d23baf1e)**

Reviewer: **Frédéric Chapoton, Matthias Koeppe**

_Issue created by migration from https://trac.sagemath.org/ticket/34839_

**Comment by mkoeppe** [comment]
Branch: **[u/mkoeppe/support_tox_4](https://github.com/sagemath/sagetrac-mirror/tree/u/mkoeppe/support_tox_4)**

**Comment by mkoeppe** [comment]
Author: **Matthias Koeppe**

**Comment by mkoeppe** [comment]
<div id="comment:2"></div>

New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/d302a628936a965d4e5c3501b7989028274fac95"><code>d302a62</code></a></td><td><code>tox.ini, src/tox.ini: Adjust to tox 4, autoprovision tox >= 3.18</code></td></tr></table>

**Comment by mkoeppe** [comment]
Commit: **[`d302a62`](https://github.com/sagemath/sagetrac-mirror/commit/d302a628936a965d4e5c3501b7989028274fac95)**

**Comment by mkoeppe** [comment]
Description changed:
``````diff
--- 
+++ 
@@ -1,3 +1,7 @@
-tox 4 renamed a tox.ini configuration keyword. 
-Also tox >= 3.18 supports the renamed keyword. https://tox.wiki/en/3.27.1/changelog.html#v3-18-0-2020-07-23
+tox 4 renamed a tox.ini configuration keyword and has slightly changed quoting behavior.
+ 
+Also tox >= 3.18 supports the renamed keyword - https://tox.wiki/en/3.27.1/changelog.html#v3-18-0-2020-07-23
 
+Also the changed quote works with both versions.
+
+
``````

**Comment by fchapoton** [comment]
<div id="comment:4" align="right">comment:4</div>

The linter is finding rst issues outside of src/sage. Is this the desired behaviour ?

By the way, one should rather fix these issues.

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
Changed commit from **[`d302a62`](https://github.com/sagemath/sagetrac-mirror/commit/d302a628936a965d4e5c3501b7989028274fac95)** to **[`f8703ae`](https://github.com/sagemath/sagetrac-mirror/commit/f8703aeba13b8663e55b46494dec4fd305e65374)**

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
<div id="comment:5"></div>

Branch pushed to git repo; I updated commit sha1. New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/f8703aeba13b8663e55b46494dec4fd305e65374"><code>f8703ae</code></a></td><td><code>.github/workflows/lint.yml: Invoke tox with --</code></td></tr></table>

**Comment by mkoeppe** [comment]
<div id="comment:6" align="right">comment:6</div>

relint is fixed now - is this what you meant?

**Comment by fchapoton** [comment]
<div id="comment:7" align="right">comment:7</div>

no. I am talking about the errors seen in the third report

https://github.com/sagemath/sagetrac-mirror/actions/runs/3674822970/jobs/6213509002

**Comment by fchapoton** [comment]
Changed commit from **[`f8703ae`](https://github.com/sagemath/sagetrac-mirror/commit/f8703aeba13b8663e55b46494dec4fd305e65374)** to **[`9d76204`](https://github.com/sagemath/sagetrac-mirror/commit/9d76204fb5801054755b2e7bc54aeb6743742ced)**

**Comment by fchapoton** [comment]
Changed branch from **[u/mkoeppe/support_tox_4](https://github.com/sagemath/sagetrac-mirror/tree/u/mkoeppe/support_tox_4)** to **[u/chapoton/support_tox_4](https://github.com/sagemath/sagetrac-mirror/tree/u/chapoton/support_tox_4)**

**Comment by fchapoton** [comment]
<div id="comment:8" align="right">comment:8</div>

I have tried to fix these errors, let us see

---
New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/9d76204fb5801054755b2e7bc54aeb6743742ced"><code>9d76204</code></a></td><td><code>fix some rst issues in sage_docbuild and sage_setup</code></td></tr></table>

**Comment by fchapoton** [comment]
<div id="comment:9" align="right">comment:9</div>

looks good to me. Please check my commit and then set to positive.

**Comment by fchapoton** [comment]
Reviewer: **Frédéric Chapoton**

**Comment by mkoeppe** [comment]
<div id="comment:10" align="right">comment:10</div>

Thanks!

**Comment by mkoeppe** [comment]
Changed reviewer from **Frédéric Chapoton** to **Frédéric Chapoton, Matthias Koeppe**

**Comment by mkoeppe** [comment]
Changed author from **Matthias Koeppe** to **Matthias Koeppe, Frédéric Chapoton**

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
<div id="comment:11"></div>

Branch pushed to git repo; I updated commit sha1 and set ticket back to needs_review. New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/70da140f5f430c1cab53a858a8b33d43d23baf1e"><code>70da140</code></a></td><td><code>Merge branch 'u/chapoton/support_tox_4' in 9.8.b6</code></td></tr></table>

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
Changed commit from **[`9d76204`](https://github.com/sagemath/sagetrac-mirror/commit/9d76204fb5801054755b2e7bc54aeb6743742ced)** to **[`70da140`](https://github.com/sagemath/sagetrac-mirror/commit/70da140f5f430c1cab53a858a8b33d43d23baf1e)**

**Comment by fchapoton** [comment]
<div id="comment:12" align="right">comment:12</div>

setting back to positive after trivial rebase

**Comment by mkoeppe** [comment]
<div id="comment:13" align="right">comment:13</div>

"Critical" because it repairs the broken Lint workflow

**Comment by vbraun** [comment]
Changed branch from **[u/chapoton/support_tox_4](https://github.com/sagemath/sagetrac-mirror/tree/u/chapoton/support_tox_4)** to **[`70da140`](https://github.com/sagemath/sagetrac-mirror/commit/70da140f5f430c1cab53a858a8b33d43d23baf1e)**
