### ISSUE TITLE
fix E502 in some pyx files

### ISSUE THREAD

**Issue by fchapoton** [sagemath/sage#34837]
<div id="comment:0"></div>

mostly inside matrix/

Component: **refactoring**

Author: **Frédéric Chapoton**

Branch/Commit: **[`04ac04c`](https://github.com/sagemath/sagetrac-mirror/commit/04ac04c2f0cb16a5d3b7ca8403a46529ddaa24ca)**

Reviewer: **Matthias Koeppe**

_Issue created by migration from https://trac.sagemath.org/ticket/34837_

**Comment by fchapoton** [comment]
Commit: **[`04ac04c`](https://github.com/sagemath/sagetrac-mirror/commit/04ac04c2f0cb16a5d3b7ca8403a46529ddaa24ca)**

**Comment by fchapoton** [comment]
<div id="comment:1"></div>

New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/04ac04c2f0cb16a5d3b7ca8403a46529ddaa24ca"><code>04ac04c</code></a></td><td><code>fix E502 in pyx files inside matrix/ and some other folders</code></td></tr></table>

**Comment by fchapoton** [comment]
Branch: **[u/chapoton/34837](https://github.com/sagemath/sagetrac-mirror/tree/u/chapoton/34837)**

**Comment by mkoeppe** [comment]
Reviewer: **Matthias Koeppe**

**Comment by vbraun** [comment]
Changed branch from **[u/chapoton/34837](https://github.com/sagemath/sagetrac-mirror/tree/u/chapoton/34837)** to **[`04ac04c`](https://github.com/sagemath/sagetrac-mirror/commit/04ac04c2f0cb16a5d3b7ca8403a46529ddaa24ca)**
