### ISSUE TITLE
fix E271 and E272 in rings/ and schemes/

### ISSUE THREAD

**Issue by fchapoton** [sagemath/sage#34836]
<div id="comment:0"></div>

about

E271 multiple spaces after keyword

E272 multiple spaces before keyword

Component: **refactoring**

Author: **Frédéric Chapoton**

Branch/Commit: **[`2a3c759`](https://github.com/sagemath/sagetrac-mirror/commit/2a3c759b5f46452c087daa3fc135a39431744c2c)**

Reviewer: **Matthias Koeppe**

_Issue created by migration from https://trac.sagemath.org/ticket/34836_

**Comment by fchapoton** [comment]
Branch: **[u/chapoton/34836](https://github.com/sagemath/sagetrac-mirror/tree/u/chapoton/34836)**

**Comment by fchapoton** [comment]
Commit: **[`2a3c759`](https://github.com/sagemath/sagetrac-mirror/commit/2a3c759b5f46452c087daa3fc135a39431744c2c)**

**Comment by fchapoton** [comment]
<div id="comment:1"></div>

New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/2a3c759b5f46452c087daa3fc135a39431744c2c"><code>2a3c759</code></a></td><td><code>fix E271 and E272 in rings and schemes</code></td></tr></table>

**Comment by mkoeppe** [comment]
Reviewer: **Matthias Koeppe**

**Comment by vbraun** [comment]
Changed branch from **[u/chapoton/34836](https://github.com/sagemath/sagetrac-mirror/tree/u/chapoton/34836)** to **[`2a3c759`](https://github.com/sagemath/sagetrac-mirror/commit/2a3c759b5f46452c087daa3fc135a39431744c2c)**
