### ISSUE TITLE
setuptools_scm, contourpy, sphinxcontrib_websupport, typing_extensions: Add missing dependencies

### ISSUE THREAD

**Issue by mkoeppe** [sagemath/sage#34838]
<div id="comment:0"></div>

CC:  @dimpase @jhpalmieri

Component: **packages: standard**

Author: **Matthias Koeppe**

Branch/Commit: **[`c67b38f`](https://github.com/sagemath/sagetrac-mirror/commit/c67b38fb5ccc0f4dc724bc3cfbddae1f4d759389)**

Reviewer: **Dima Pasechnik, John Palmieri**

_Issue created by migration from https://trac.sagemath.org/ticket/34838_

**Comment by mkoeppe** [comment]
Branch: **[u/mkoeppe/setuptools_scm__contourpy__sphinxcontrib_websupport__add_missing_dependencies](https://github.com/sagemath/sagetrac-mirror/tree/u/mkoeppe/setuptools_scm__contourpy__sphinxcontrib_websupport__add_missing_dependencies)**

**Comment by mkoeppe** [comment]
Commit: **[`feb0a09`](https://github.com/sagemath/sagetrac-mirror/commit/feb0a094a3e795d8e381e66b8d772051acdc41eb)**

**Comment by mkoeppe** [comment]
Author: **Matthias Koeppe**

**Comment by mkoeppe** [comment]
<div id="comment:2"></div>

New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/feb0a094a3e795d8e381e66b8d772051acdc41eb"><code>feb0a09</code></a></td><td><code>build/pkgs/{setuptools_scm,contourpy,sphinxcontrib_websupport}: Add missing deps</code></td></tr></table>

**Comment by dimpase** [comment]
Reviewer: **Dima Pasechnik**

**Comment by dimpase** [comment]
<div id="comment:3" align="right">comment:3</div>

lgtm

**Comment by mkoeppe** [comment]
<div id="comment:4" align="right">comment:4</div>

Thanks!

**Comment by vbraun** [comment]
<div id="comment:5" align="right">comment:5</div>


```
The following package(s) may have failed to build (not necessarily
during this run of 'make all-start'):

* package:         typing_extensions-4.4.0
  last build time: Dec 21 20:47
  log file:        /home/release/Sage/logs/pkgs/typing_extensions-4.4.0.log
[...]
$ cat /home/release/Sage/logs/pkgs/typing_extensions-4.4.0.log
[...]
****************************************************
Package 'typing_extensions' is currently not installed
No legacy uninstaller found for 'typing_extensions'; nothing to do
Installing typing_extensions-4.4.0
Looking in links: /home/release/Sage/local/var/lib/sage/venv-python3.10.8/var/lib/sage/wheels
Processing /home/release/Sage/local/var/lib/sage/venv-python3.10.8/var/tmp/sage/build/typing_extensions-4.4.0/src
  Installing build dependencies: started
  Running command pip subprocess to install build dependencies
  Looking in links: /home/release/Sage/local/var/lib/sage/venv-python3.10.8/var/lib/sage/wheels
  ERROR: Could not find a version that satisfies the requirement flit_core<4,>=3.4 (from versions: none)
  ERROR: No matching distribution found for flit_core<4,>=3.4
  error: subprocess-exited-with-error
  
  × pip subprocess to install build dependencies did not run successfully.
  │ exit code: 1
  ╰─> See above for output.
```

**Comment by mkoeppe** [comment]
<div id="comment:6" align="right">comment:6</div>

That's another missing dependency, introduced in #34676

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
<div id="comment:7"></div>

Branch pushed to git repo; I updated commit sha1. This was a forced push. New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/952f7ba9fda9029c003440b5e9da469bc5353a33"><code>952f7ba</code></a></td><td><code>build/pkgs/{setuptools_scm,contourpy,sphinxcontrib_websupport}: Add missing deps</code></td></tr><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/856c670734df3618713d47514c484e3b550e69e7"><code>856c670</code></a></td><td><code>build/pkgs/typing_extensions/dependencies: Add flit_core</code></td></tr></table>

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
Changed commit from **[`feb0a09`](https://github.com/sagemath/sagetrac-mirror/commit/feb0a094a3e795d8e381e66b8d772051acdc41eb)** to **[`856c670`](https://github.com/sagemath/sagetrac-mirror/commit/856c670734df3618713d47514c484e3b550e69e7)**

**Comment by mkoeppe** [comment]
<div id="comment:10" align="right">comment:10</div>

In https://github.com/sagemath/sage/actions/runs/3751978232/jobs/6391768854, I also see a failure in building `setuptools_scm_git_archive`

**Comment by mkoeppe** [comment]
<div id="comment:11" align="right">comment:11</div>

Let's get this in

**Comment by jhpalmieri** [comment]
<div id="comment:12" align="right">comment:12</div>

What about the failure reported in [comment:10](#comment%3A10)?

**Comment by mkoeppe** [comment]
<div id="comment:13" align="right">comment:13</div>

I checked that the dependencies of that package are right. I don't understand that failure, and it has not reoccurred

**Comment by jhpalmieri** [comment]
<div id="comment:14" align="right">comment:14</div>

Okay.

**Comment by jhpalmieri** [comment]
Changed reviewer from **Dima Pasechnik** to **Dima Pasechnik, John Palmieri**

**Comment by mkoeppe** [comment]
<div id="comment:15" align="right">comment:15</div>

Thanks!

**Comment by vbraun** [comment]
<div id="comment:16" align="right">comment:16</div>

Circular dependencies:

```
make[3]: Circular /home/release/Sage/local/var/lib/sage/venv-python3.11.1/var/lib/sage/installed/typing_extensions-4.4.0 <- /home/release/Sage/local/var/lib/sage/venv-python3.11.1/var/lib/sage/installed/setuptools_scm-7.0.5 dependency dropped.
```
Note that this is currently a warning and the install fails successfully ;) 

My merge script checks for it though.

**Comment by dimpase** [comment]
<div id="comment:17" align="right">comment:17</div>


```
setuptools_scm/dependencies
$(PYTHON) typing_extensions | setuptools pip wheel tomli packaging
 
typing_extensions/dependencies
$(PYTHON) | $(PYTHON_TOOLCHAIN) flit_core
```
but

```
PYTHON_TOOLCHAIN = setuptools pip setuptools_scm wheel setuptools_wheel
```
so it's indeed circular. 
Note that
https://github.com/pypa/setuptools_scm/blob/main/pyproject.toml tells that it needs `typing_extensions`.
OTOH only `flit_core` is mentioned as a build dependency in https://github.com/python/typing_extensions/blob/main/pyproject.toml

**Comment by dimpase** [comment]
Changed commit from **[`856c670`](https://github.com/sagemath/sagetrac-mirror/commit/856c670734df3618713d47514c484e3b550e69e7)** to **[`c67b38f`](https://github.com/sagemath/sagetrac-mirror/commit/c67b38fb5ccc0f4dc724bc3cfbddae1f4d759389)**

**Comment by dimpase** [comment]
Changed branch from **[u/mkoeppe/setuptools_scm__contourpy__sphinxcontrib_websupport__add_missing_dependencies](https://github.com/sagemath/sagetrac-mirror/tree/u/mkoeppe/setuptools_scm__contourpy__sphinxcontrib_websupport__add_missing_dependencies)** to **[u/dimpase/setuptools_scm__contourpy__sphinxcontrib_websupport__add_missing_dependencies](https://github.com/sagemath/sagetrac-mirror/tree/u/dimpase/setuptools_scm__contourpy__sphinxcontrib_websupport__add_missing_dependencies)**

**Comment by dimpase** [comment]
<div id="comment:18"></div>

New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/c67b38fb5ccc0f4dc724bc3cfbddae1f4d759389"><code>c67b38f</code></a></td><td><code>remove unneeded and harmful dependency</code></td></tr></table>

**Comment by dimpase** [comment]
<div id="comment:19" align="right">comment:19</div>

works like this, too

**Comment by vbraun** [comment]
Changed branch from **[u/dimpase/setuptools_scm__contourpy__sphinxcontrib_websupport__add_missing_dependencies](https://github.com/sagemath/sagetrac-mirror/tree/u/dimpase/setuptools_scm__contourpy__sphinxcontrib_websupport__add_missing_dependencies)** to **[`c67b38f`](https://github.com/sagemath/sagetrac-mirror/commit/c67b38fb5ccc0f4dc724bc3cfbddae1f4d759389)**
