### ISSUE TITLE
modernize some for loops in cython files

### ISSUE THREAD

**Issue by fchapoton** [sagemath/sage#34847]
<div id="comment:0"></div>

changing things like

```
for i from 0 <= i < n
```
to

```
for i in range(n)
```

There remains many, as can be seen using

```
git grep " from .*<=" src/sage/
```

Component: **refactoring**

Author: **Frédéric Chapoton**

Branch/Commit: **[`16ef533`](https://github.com/sagemath/sagetrac-mirror/commit/16ef533bf81093d2ac21bfd24ac5ef1bb3fd74a4)**

Reviewer: **David Coudert**

_Issue created by migration from https://trac.sagemath.org/ticket/34847_

**Comment by fchapoton** [comment]
Branch: **[u/chapoton/34847](https://github.com/sagemath/sagetrac-mirror/tree/u/chapoton/34847)**

**Comment by fchapoton** [comment]
Description changed:
``````diff
--- 
+++ 
@@ -8,3 +8,9 @@
 ```
 for i in range(n)
 ```
+
+There remains many, as can be seen using
+
+```
+
+```
``````

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
<div id="comment:2"></div>

Branch pushed to git repo; I updated commit sha1. New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/16ef533bf81093d2ac21bfd24ac5ef1bb3fd74a4"><code>16ef533</code></a></td><td><code>modernize some for loops in cython files</code></td></tr></table>

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
Commit: **[`16ef533`](https://github.com/sagemath/sagetrac-mirror/commit/16ef533bf81093d2ac21bfd24ac5ef1bb3fd74a4)**

**Comment by fchapoton** [comment]
<div id="comment:3"></div>

New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/16ef533bf81093d2ac21bfd24ac5ef1bb3fd74a4"><code>16ef533</code></a></td><td><code>modernize some for loops in cython files</code></td></tr></table>

**Comment by fchapoton** [comment]
Description changed:
``````diff
--- 
+++ 
@@ -12,5 +12,5 @@
 There remains many, as can be seen using
 
 ```
-
+git grep " from .*<=" src/sage/
 ```
``````

**Comment by dcoudert** [comment]
<div id="comment:4" align="right">comment:4</div>

all the changes seems OK and the patchbot is green. Do you plan to do more changes or you just forgot to set this ticket to needs review ?

**Comment by fchapoton** [comment]
<div id="comment:5" align="right">comment:5</div>

juste oublié, rien d'autre prévu dans ce ticket

**Comment by dcoudert** [comment]
Reviewer: **David Coudert**

**Comment by dcoudert** [comment]
<div id="comment:6" align="right">comment:6</div>

Bonnes fêtes !

**Comment by vbraun** [comment]
Changed branch from **[u/chapoton/34847](https://github.com/sagemath/sagetrac-mirror/tree/u/chapoton/34847)** to **[`16ef533`](https://github.com/sagemath/sagetrac-mirror/commit/16ef533bf81093d2ac21bfd24ac5ef1bb3fd74a4)**
