### ISSUE TITLE
removal of some unused imports about string conversion

### ISSUE THREAD

**Issue by fchapoton** [sagemath/sage#34844]
<div id="comment:0"></div>

as this may help to reduce compilation warnings

Component: **refactoring**

Author: **Frédéric Chapoton**

Branch/Commit: **[`fc44813`](https://github.com/sagemath/sagetrac-mirror/commit/fc44813022d61df0d9a6763779d6c71668794df3)**

Reviewer: **Travis Scrimshaw**

_Issue created by migration from https://trac.sagemath.org/ticket/34844_

**Comment by fchapoton** [comment]
Commit: **[`fc44813`](https://github.com/sagemath/sagetrac-mirror/commit/fc44813022d61df0d9a6763779d6c71668794df3)**

**Comment by fchapoton** [comment]
<div id="comment:1"></div>

New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/fc44813022d61df0d9a6763779d6c71668794df3"><code>fc44813</code></a></td><td><code>removal of some unused imports about string conversions</code></td></tr></table>

**Comment by fchapoton** [comment]
Branch: **[u/chapoton/34844](https://github.com/sagemath/sagetrac-mirror/tree/u/chapoton/34844)**

**Comment by fchapoton** [comment]
<div id="comment:2" align="right">comment:2</div>

the doctest failure is unrelated

**Comment by tscrim** [comment]
Reviewer: **Travis Scrimshaw**

**Comment by tscrim** [comment]
<div id="comment:3" align="right">comment:3</div>

LGTM.

**Comment by vbraun** [comment]
Changed branch from **[u/chapoton/34844](https://github.com/sagemath/sagetrac-mirror/tree/u/chapoton/34844)** to **[`fc44813`](https://github.com/sagemath/sagetrac-mirror/commit/fc44813022d61df0d9a6763779d6c71668794df3)**
