### ISSUE TITLE
pep8 cleanup in ore_polynomial_element.pyx

### ISSUE THREAD

**Issue by fchapoton** [sagemath/sage#34843]
<div id="comment:0"></div>

also fixing one "unreachable code" compilation warning

CC:  @tscrim @dcoudert

Component: **algebra**

Author: **Frédéric Chapoton**

Branch/Commit: **[`bbe553a`](https://github.com/sagemath/sagetrac-mirror/commit/bbe553a1397fd2683c5f970475091bd6e9aaf658)**

Reviewer: **David Coudert**

_Issue created by migration from https://trac.sagemath.org/ticket/34843_

**Comment by fchapoton** [comment]
Description changed:
``````diff
--- 
+++ 
@@ -1 +1 @@
-
+also fixing one "unreachable code" compilation warning
``````

**Comment by fchapoton** [comment]
Commit: **[`bbe553a`](https://github.com/sagemath/sagetrac-mirror/commit/bbe553a1397fd2683c5f970475091bd6e9aaf658)**

**Comment by fchapoton** [comment]
<div id="comment:1"></div>

New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/bbe553a1397fd2683c5f970475091bd6e9aaf658"><code>bbe553a</code></a></td><td><code>pep cleanup in ore_polynomial_element.pyx</code></td></tr></table>

**Comment by fchapoton** [comment]
Branch: **[u/chapoton/34843](https://github.com/sagemath/sagetrac-mirror/tree/u/chapoton/34843)**

**Comment by fchapoton** [comment]
<div id="comment:2" align="right">comment:2</div>

bot is morally green, so please review

**Comment by dcoudert** [comment]
<div id="comment:3" align="right">comment:3</div>

LGTM.

**Comment by dcoudert** [comment]
Reviewer: **David Coudert**

**Comment by vbraun** [comment]
Changed branch from **[u/chapoton/34843](https://github.com/sagemath/sagetrac-mirror/tree/u/chapoton/34843)** to **[`bbe553a`](https://github.com/sagemath/sagetrac-mirror/commit/bbe553a1397fd2683c5f970475091bd6e9aaf658)**
