### ISSUE TITLE
Upgrade scipy to 1.10.x

### ISSUE THREAD

**Issue by mkoeppe** [sagemath/sage#34842]
<div id="comment:0"></div>

1.10.0 is out - https://github.com/scipy/scipy/releases

Component: **packages: standard**

_Issue created by migration from https://trac.sagemath.org/ticket/34842_

**Comment by mkoeppe** [comment]
Branch: **[u/mkoeppe/upgrade_scipy_to_1_10](https://github.com/sagemath/sagetrac-mirror/tree/u/mkoeppe/upgrade_scipy_to_1_10)**

**Comment by mkoeppe** [comment]
<div id="comment:2" align="right">comment:2</div>

Builds and tests OK on macOS.

---
New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/efc289a77a0b54fa4cc04874b336ccffd9dc300f"><code>efc289a</code></a></td><td><code>build/pkgs/scipy: Update to 1.10.0rc1</code></td></tr><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/1bfae8504ebcb2cc7a3f5ce5075f4cde56894ae7"><code>1bfae85</code></a></td><td><code>build/pkgs/meson: Update to 1.0.0rc1</code></td></tr><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/35906de709e3a673306fc38d5dea6272fe9bba60"><code>35906de</code></a></td><td><code>build/pkgs/meson/spkg-configure.m4: Require >= 0.64</code></td></tr></table>

**Comment by mkoeppe** [comment]
Commit: **[`35906de`](https://github.com/sagemath/sagetrac-mirror/commit/35906de709e3a673306fc38d5dea6272fe9bba60)**

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
Changed commit from **[`35906de`](https://github.com/sagemath/sagetrac-mirror/commit/35906de709e3a673306fc38d5dea6272fe9bba60)** to **[`39b9874`](https://github.com/sagemath/sagetrac-mirror/commit/39b9874bb7b826abe366672247d3e4ca79479cef)**

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
<div id="comment:3"></div>

Branch pushed to git repo; I updated commit sha1. This was a forced push. New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/4974b46dd5b2fa3636cd3a272a0006564962fed8"><code>4974b46</code></a></td><td><code>build/pkgs/scipy: Update to 1.10.0rc1</code></td></tr><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/d0b1f8aba0358a8052edda6ec9163244eb73c479"><code>d0b1f8a</code></a></td><td><code>build/pkgs/meson: Update to 1.0.0rc1</code></td></tr><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/8f52007b41bd6e3e6710d1acef7606a1503a8ba5"><code>8f52007</code></a></td><td><code>build/pkgs/meson/spkg-configure.m4: Require >= 0.64</code></td></tr><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/449d1678c0daceca27baaa916a5c99722cec2800"><code>449d167</code></a></td><td><code>build/pkgs/meson: Update to 1.0.0</code></td></tr><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/39b9874bb7b826abe366672247d3e4ca79479cef"><code>39b9874</code></a></td><td><code>build/pkgs/meson_python: Update to 0.12.0</code></td></tr></table>

**Comment by mkoeppe** [comment]
Description changed:
``````diff
--- 
+++ 
@@ -1,2 +1,2 @@
-1.10.0rc1 is out - https://github.com/scipy/scipy/releases
+1.10.0 is out - https://github.com/scipy/scipy/releases
 
``````

**Comment by mkoeppe** [comment]
Removed the branch from the issue description, it has been replaced by PR #35082
