### ISSUE TITLE
adapt findstat doctests to new newlines

### ISSUE THREAD

**Issue by mantepse** [sagemath/sage#34841]
<div id="comment:0"></div>

https://findstat.org now normalizes all newlines from `\n` to `\r\n`.  This ticket adapts the doctests accordingly.

Component: **combinatorics**

Keywords: **findstat**

Author: **Martin Rubey**

Branch/Commit: **[`631d1d3`](https://github.com/sagemath/sagetrac-mirror/commit/631d1d384cfd0d89452e8411796164fefa57732f)**

Reviewer: **Travis Scrimshaw**

_Issue created by migration from https://trac.sagemath.org/ticket/34841_

**Comment by mantepse** [comment]
Branch: **[u/mantepse/adapt_findstat_doctests_to_new_newlines](https://github.com/sagemath/sagetrac-mirror/tree/u/mantepse/adapt_findstat_doctests_to_new_newlines)**

**Comment by mantepse** [comment]
Description changed:
``````diff
--- 
+++ 
@@ -1 +1 @@
-
+https://findstat.org phases out `\r\n` in favour of `\n` as newline.  This ticket adapts the doctests accordingly.
``````

**Comment by mantepse** [comment]
Changed branch from **[u/mantepse/adapt_findstat_doctests_to_new_newlines](https://github.com/sagemath/sagetrac-mirror/tree/u/mantepse/adapt_findstat_doctests_to_new_newlines)** to none

**Comment by mantepse** [comment]
Changed keywords from none to **findstat**

**Comment by mantepse** [comment]
Author: **Martin Rubey**

**Comment by mantepse** [comment]
<div id="comment:3" align="right">comment:3</div>

There seems to be an inconsistency on findstat's part, let's wait a minute.

**Comment by mantepse** [comment]
Description changed:
``````diff
--- 
+++ 
@@ -1 +1 @@
-https://findstat.org phases out `\r\n` in favour of `\n` as newline.  This ticket adapts the doctests accordingly.
+https://findstat.org now normalizes all newlines from `\n` to `\r\n`.  This ticket adapts the doctests accordingly.
``````

**Comment by mantepse** [comment]
Branch: **[u/mantepse/adapt_findstat_doctests_to_new_newlines](https://github.com/sagemath/sagetrac-mirror/tree/u/mantepse/adapt_findstat_doctests_to_new_newlines)**

**Comment by mantepse** [comment]
<div id="comment:6"></div>

New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/677797a504ad3f2f3450aa5ea8276c495a835f4c"><code>677797a</code></a></td><td><code>fix line breaks in doctest</code></td></tr><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/27752e9a465eef2fcc1613db470e607dc2885840"><code>27752e9</code></a></td><td><code>replace \r\n with \n</code></td></tr><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/7dd5211bdfa7041e7bcc60f5aad26941d7b05ad5"><code>7dd5211</code></a></td><td><code>Merge branch 'u/mantepse/adapt_findstat_doctests_to_new_newlines' of trac.sagemath.org:sage into t/34841/adapt_findstat_doctests_to_new_newlines</code></td></tr><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/631d1d384cfd0d89452e8411796164fefa57732f"><code>631d1d3</code></a></td><td><code>fix another doctest</code></td></tr></table>

**Comment by mantepse** [comment]
Commit: **[`631d1d3`](https://github.com/sagemath/sagetrac-mirror/commit/631d1d384cfd0d89452e8411796164fefa57732f)**

**Comment by tscrim** [comment]
Reviewer: **Travis Scrimshaw**

**Comment by tscrim** [comment]
<div id="comment:7" align="right">comment:7</div>

LGTM.

**Comment by vbraun** [comment]
Changed branch from **[u/mantepse/adapt_findstat_doctests_to_new_newlines](https://github.com/sagemath/sagetrac-mirror/tree/u/mantepse/adapt_findstat_doctests_to_new_newlines)** to **[`631d1d3`](https://github.com/sagemath/sagetrac-mirror/commit/631d1d384cfd0d89452e8411796164fefa57732f)**
