### ISSUE TITLE
Remove direct use of "setup.py sdist", add targets "make SPKG-sdist"

### ISSUE THREAD

**Issue by mkoeppe** [sagemath/sage#34855]
<div id="comment:0"></div>

Direct use of "setup.py sdist" is deprecated. Instead we use `build` to create the sdists.

We add new targets `make sagemath_objects-sdist` etc.

We move targets `make pypi-sdists` (which now uses the new targets), `make wheel`, and `make pypi-wheels` from the top-level `Makefile` to `build/make/Makefile.in`. This improves `make pypi-wheels`: It no longer builds the sagemath-objects wheel multiple times (as dependencies of other packages).

Depends on #34858

CC:  @kiwifb

Component: **build**

Author: **Matthias Koeppe**

_Issue created by migration from https://trac.sagemath.org/ticket/34855_

**Comment by mkoeppe** [comment]
Branch: **[u/mkoeppe/remove_direct_use_of__setup_py_sdist_](https://github.com/sagemath/sagetrac-mirror/tree/u/mkoeppe/remove_direct_use_of__setup_py_sdist_)**

**Comment by mkoeppe** [comment]
<div id="comment:2"></div>

New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/cc58c2dd882b88cf0efe9f656e3d58aec0da4d5e"><code>cc58c2d</code></a></td><td><code>build/pkgs/sagelib/spkg-src: Use build</code></td></tr><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/eee3f1a5f2e4980276d261b38c9507e98b949ea2"><code>eee3f1a</code></a></td><td><code>Makefile (pypi-sdists): Install python_build</code></td></tr></table>

**Comment by mkoeppe** [comment]
Commit: **[`eee3f1a`](https://github.com/sagemath/sagetrac-mirror/commit/eee3f1a5f2e4980276d261b38c9507e98b949ea2)**

**Comment by mkoeppe** [comment]
Dependencies: **#34858**

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
<div id="comment:4"></div>

Branch pushed to git repo; I updated commit sha1. Last 10 new commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/ef75d6aa91d4d96a1f7a826abc6e0a4af30210d5"><code>ef75d6a</code></a></td><td><code>src/MANIFEST.in: Add pxd files etc</code></td></tr><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/2f4b0539a17cf2dd9ff53ccb85a3b7f8f218e6a8"><code>2f4b053</code></a></td><td><code>pkgs/sagemath-standard/setup.py: Run finder also for sdist, egg_info, dist_info</code></td></tr><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/00deebede6ae54768e8648bee89038e26d3515f8"><code>00deebe</code></a></td><td><code>pkgs/sagemath-objects/setup.py: Run finder also for sdist, egg_info, dist_info</code></td></tr><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/39bd748020fb651e5aeb7640ffe182e493353c79"><code>39bd748</code></a></td><td><code>src/sage/dynamics/arithmetic_dynamics/projective_ds.py: Remove unused import of typing_extensions</code></td></tr><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/e22943612656b225396e4dea4fae654108b3cf3d"><code>e229436</code></a></td><td><code>Merge #34859</code></td></tr><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/2b39b3d2e2b0a8720dfcd764345c03c120e06396"><code>2b39b3d</code></a></td><td><code>Merge #34858</code></td></tr><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/c59622a42624037d4eba61e353ea07ae00bd55f6"><code>c59622a</code></a></td><td><code>build/pkgs/sagemath*/spkg-src: Use build</code></td></tr><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/7fc93d06de9f0e34d2ea2077f1a022750c722235"><code>7fc93d0</code></a></td><td><code>build/pkgs/sagemath*/spkg-src: Use --skip-dependency-check</code></td></tr><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/4940db4cf4d32617f23a87e04bddaa01061a7f5f"><code>4940db4</code></a></td><td><code>build/make/Makefile.in: Add targets SPKG-src for script packages</code></td></tr><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/573fcfdfba04041260f8e06e54e37eb8a9f85da4"><code>573fcfd</code></a></td><td><code>build/make/Makefile.in: Move targets pypi-sdists, wheel, pypi-wheels here; use SPKG-sdist targets</code></td></tr></table>

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
Changed commit from **[`eee3f1a`](https://github.com/sagemath/sagetrac-mirror/commit/eee3f1a5f2e4980276d261b38c9507e98b949ea2)** to **[`573fcfd`](https://github.com/sagemath/sagetrac-mirror/commit/573fcfdfba04041260f8e06e54e37eb8a9f85da4)**

**Comment by mkoeppe** [comment]
Description changed:
``````diff
--- 
+++ 
@@ -1,4 +1,7 @@
-Direct use of "setup.py sdist" is deprecated.
+Direct use of "setup.py sdist" is deprecated. Instead we use `build` to create the sdists.
 
-Instead we use `build` to create the sdists.
+We add new targets `make sagemath_objects-sdist` etc.
 
+We move targets `make pypi-sdists` (which now uses the new targets), `make wheel`, and `make pypi-wheels` from the top-level `Makefile` to `build/make/Makefile.in`. This improves `make pypi-wheels`: It no longer builds the sagemath-objects wheel multiple times (as dependencies of other packages).
+
+
``````

**Comment by mkoeppe** [comment]
Author: **Matthias Koeppe**

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
<div id="comment:6"></div>

Branch pushed to git repo; I updated commit sha1. New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/0bd13ac7095789740ce098e23a7b0af4978c621c"><code>0bd13ac</code></a></td><td><code>build/make/Makefile.in: Remove duplicate setting of PYPI_WHEEL_PACKAGES</code></td></tr></table>

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
Changed commit from **[`573fcfd`](https://github.com/sagemath/sagetrac-mirror/commit/573fcfdfba04041260f8e06e54e37eb8a9f85da4)** to **[`0bd13ac`](https://github.com/sagemath/sagetrac-mirror/commit/0bd13ac7095789740ce098e23a7b0af4978c621c)**

**Comment by mkoeppe** [comment]
Removed branch from issue description; replaced by PR https://github.com/sagemath/sage/pull/35104
