### ISSUE TITLE
AttributeError 'sadfasdf'

### ISSUE THREAD

**Issue by loreno-heer** [sagemath/sage#34852]
<div id="comment:0"></div>

I got an error (accidentelly called the method on the manifold instead of the chart) it looks like something was not implemented:

```
> Chi = M.transition_map(M, [t-r, r, th, ph], name='Chi', latex_name=r'\Chi')

```

```
KeyError                                  Traceback (most recent call last)
File /ext/sage/9.7/src/sage/structure/category_object.pyx:839, in sage.structure.category_object.CategoryObject.getattr_from_category()
    838 try:
--> 839     return self.__cached_methods[name]
    840 except KeyError:
KeyError: 'transition_map'

During handling of the above exception, another exception occurred:
AttributeError                            Traceback (most recent call last)
Input In [22], in <cell line: 1>()
----> 1 Chi = M.transition_map(M, [t-r, r, th, ph], name='Chi', latex_name=r'\Chi')
File /ext/sage/9.7/src/sage/structure/category_object.pyx:833, in sage.structure.category_object.CategoryObject.__getattr__()
    831         AttributeError: 'PrimeNumbers_with_category' object has no attribute 'sadfasdf'
    832     """
--> 833     return self.getattr_from_category(name)
    834 
    835 cdef getattr_from_category(self, name):
File /ext/sage/9.7/src/sage/structure/category_object.pyx:848, in sage.structure.category_object.CategoryObject.getattr_from_category()
    846     cls = self._category.parent_class
    847 
--> 848 attr = getattr_from_other_class(self, cls, name)
    849 self.__cached_methods[name] = attr
    850 return attr
File /ext/sage/9.7/src/sage/cpython/getattr.pyx:356, in sage.cpython.getattr.getattr_from_other_class()
    354     dummy_error_message.cls = type(self)
    355     dummy_error_message.name = name
--> 356     raise AttributeError(dummy_error_message)
    357 cdef PyObject* attr = instance_getattr(cls, name)
    358 if attr is NULL:
AttributeError: 'PseudoRiemannianManifold_with_category' object has no attribute 'transition_map'
```

Component: **manifolds**

Reviewer: **Matthias Koeppe**

_Issue created by migration from https://trac.sagemath.org/ticket/34852_

**Comment by loreno-heer** [comment]
Description changed:
``````diff
--- 
+++ 
@@ -1,4 +1,4 @@
-I got an error, it looks like something was not implemented:
+I got an error (accidentelly called the method on the manifold instead of the chart) it looks like something was not implemented:
 
 
 ```
``````

**Comment by nbruin** [comment]
<div id="comment:2" align="right">comment:2</div>

Note that you get to see the trace-back from an error and that python lists source fragments to help analysis. The mention of the attribute is in:

[category_object.pyx:828](https://github.com/sagemath/sage-prod/blob/55a711e3d6251f2ff4f3bcccc4c6a8b7a2a8d1b2/src/sage/structure/category_object.pyx#L828)

which is a doctest. The error messages relevant for you are at the very top `KeyError`, repeated with full error message below its traceback. This error was deep down and caught, and then reraised as an `AttributeError` with a more informative error message; right at the bottom of the traceback.

Python's traceback formatting is still geared towards terminals, so the most important message is repeated at the very bottom, where it won't be scrolled back yet.

The error indicates exactly what's wrong (the attribute is not available on the object) and reflects user error. I think this can be closed as "invalid".

**Comment by mkoeppe** [comment]
Reviewer: **Matthias Koeppe**
