### ISSUE TITLE
sagelib: Remove unnecessary import of typing_extensions

### ISSUE THREAD

**Issue by mkoeppe** [sagemath/sage#34859]
<div id="comment:0"></div>

see also #34831

CC:  @EnderWannabe @fchapoton @jhpalmieri

Component: **refactoring**

Author: **Matthias Koeppe**

Branch/Commit: **[`39bd748`](https://github.com/sagemath/sagetrac-mirror/commit/39bd748020fb651e5aeb7640ffe182e493353c79)**

Reviewer: **John Palmieri**

_Issue created by migration from https://trac.sagemath.org/ticket/34859_

**Comment by mkoeppe** [comment]
Branch: **[u/mkoeppe/sagelib__remove_unnecessary_import_of_typing_extensions](https://github.com/sagemath/sagetrac-mirror/tree/u/mkoeppe/sagelib__remove_unnecessary_import_of_typing_extensions)**

**Comment by mkoeppe** [comment]
<div id="comment:2"></div>

New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/2c87163e2a275ef534f6ccaa0ede0ef7a29db303"><code>2c87163</code></a></td><td><code>src/sage/dynamics/arithmetic_dynamics/projective_ds.py: Remove unused import of typing_extensions</code></td></tr></table>

**Comment by mkoeppe** [comment]
Commit: **[`2c87163`](https://github.com/sagemath/sagetrac-mirror/commit/2c87163e2a275ef534f6ccaa0ede0ef7a29db303)**

**Comment by mkoeppe** [comment]
Author: **Matthias Koeppe**

**Comment by mkoeppe** [comment]
Description changed:
``````diff
--- 
+++ 
@@ -1 +1 @@
-
+see also #34831
``````

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
Changed commit from **[`2c87163`](https://github.com/sagemath/sagetrac-mirror/commit/2c87163e2a275ef534f6ccaa0ede0ef7a29db303)** to **[`7b3c972`](https://github.com/sagemath/sagetrac-mirror/commit/7b3c97215451cce0fe491253976a28f21758c3ce)**

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
<div id="comment:3"></div>

Branch pushed to git repo; I updated commit sha1. New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/ef75d6aa91d4d96a1f7a826abc6e0a4af30210d5"><code>ef75d6a</code></a></td><td><code>src/MANIFEST.in: Add pxd files etc</code></td></tr><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/2f4b0539a17cf2dd9ff53ccb85a3b7f8f218e6a8"><code>2f4b053</code></a></td><td><code>pkgs/sagemath-standard/setup.py: Run finder also for sdist, egg_info, dist_info</code></td></tr><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/00deebede6ae54768e8648bee89038e26d3515f8"><code>00deebe</code></a></td><td><code>pkgs/sagemath-objects/setup.py: Run finder also for sdist, egg_info, dist_info</code></td></tr><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/7b3c97215451cce0fe491253976a28f21758c3ce"><code>7b3c972</code></a></td><td><code>Merge #34859</code></td></tr></table>

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
Changed commit from **[`7b3c972`](https://github.com/sagemath/sagetrac-mirror/commit/7b3c97215451cce0fe491253976a28f21758c3ce)** to **[`39bd748`](https://github.com/sagemath/sagetrac-mirror/commit/39bd748020fb651e5aeb7640ffe182e493353c79)**

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
<div id="comment:4"></div>

Branch pushed to git repo; I updated commit sha1. This was a forced push. New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/39bd748020fb651e5aeb7640ffe182e493353c79"><code>39bd748</code></a></td><td><code>src/sage/dynamics/arithmetic_dynamics/projective_ds.py: Remove unused import of typing_extensions</code></td></tr></table>

**Comment by jhpalmieri** [comment]
Reviewer: **John Palmieri**

**Comment by jhpalmieri** [comment]
<div id="comment:6" align="right">comment:6</div>

Looks good to me.

**Comment by mkoeppe** [comment]
<div id="comment:7" align="right">comment:7</div>

Thank you!

**Comment by vbraun** [comment]
Changed branch from **[u/mkoeppe/sagelib__remove_unnecessary_import_of_typing_extensions](https://github.com/sagemath/sagetrac-mirror/tree/u/mkoeppe/sagelib__remove_unnecessary_import_of_typing_extensions)** to **[`39bd748`](https://github.com/sagemath/sagetrac-mirror/commit/39bd748020fb651e5aeb7640ffe182e493353c79)**
