### ISSUE TITLE
sage-env: Fix misconfiguration of pip

### ISSUE THREAD

**Issue by mkoeppe** [sagemath/sage#34853]
<div id="comment:0"></div>

```
./sage -sh -c 'pip cache'                                                                                                           git:t/34851/upgrade_singular_to_4_3_1p3
An error occurred during configuration: option format: invalid choice: 'columns' (choose from 'human', 'abspath')
```
as noted in [#34850 comment:19](https://github.com/sagemath/sage/issues/34850#comment:19)

CC:  @dimpase

Component: **scripts**

Author: **Matthias Koeppe**

Branch/Commit: **[`580dec9`](https://github.com/sagemath/sagetrac-mirror/commit/580dec95383b4f01f7fa5d2542258735a4606457)**

Reviewer: **Dima Pasechnik**

_Issue created by migration from https://trac.sagemath.org/ticket/34853_

**Comment by mkoeppe** [comment]
Branch: **[u/mkoeppe/sage_env__fix_misconfiguration_of_pip](https://github.com/sagemath/sagetrac-mirror/tree/u/mkoeppe/sage_env__fix_misconfiguration_of_pip)**

**Comment by mkoeppe** [comment]
Author: **Matthias Koeppe**

**Comment by mkoeppe** [comment]
<div id="comment:2"></div>

New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/580dec95383b4f01f7fa5d2542258735a4606457"><code>580dec9</code></a></td><td><code>src/bin/sage-env: Remove outdated setting of PIP_FORMAT</code></td></tr></table>

**Comment by mkoeppe** [comment]
Commit: **[`580dec9`](https://github.com/sagemath/sagetrac-mirror/commit/580dec95383b4f01f7fa5d2542258735a4606457)**

**Comment by dimpase** [comment]
<div id="comment:3" align="right">comment:3</div>

lgtm

**Comment by dimpase** [comment]
Reviewer: **Dima Pasechnik**

**Comment by mkoeppe** [comment]
<div id="comment:4" align="right">comment:4</div>

Thanks

**Comment by vbraun** [comment]
Changed branch from **[u/mkoeppe/sage_env__fix_misconfiguration_of_pip](https://github.com/sagemath/sagetrac-mirror/tree/u/mkoeppe/sage_env__fix_misconfiguration_of_pip)** to **[`580dec9`](https://github.com/sagemath/sagetrac-mirror/commit/580dec95383b4f01f7fa5d2542258735a4606457)**
