### ISSUE TITLE
Fix sagemath-standard sdist

### ISSUE THREAD

**Issue by mkoeppe** [sagemath/sage#34858]
<div id="comment:0"></div>

`./bootstrap && ./sage -sh -c '(cd pkgs/sagemath-standard && tox -v -v -v -e sagepython-sagewheels-nopypi-norequirements)'` fails in 9.8.beta5 because the sdist is broken

```

  cimport cython
  from sage.algebras.fusion_rings.poly_tup_engine cimport (
  ^
  ------------------------------------------------------------

  sage/algebras/fusion_rings/fast_parallel_fmats_methods.pyx:12:0: 'sage/algebras/fusion_rings/poly_tup_engine.pxd' not found

```

We fix this by 
- updating MANIFEST
- unconditionally running the module finder in pkgs/sagemath-standard/setup.py

We make the same change also in pkgs/sagemath-objects/setup.py (by symlink, this also affects sagemath-categories).

Depends on #34859

CC:  @kwankyu @kiwifb

Component: **distribution**

Author: **Matthias Koeppe**

Branch/Commit: **[`e229436`](https://github.com/sagemath/sagetrac-mirror/commit/e22943612656b225396e4dea4fae654108b3cf3d)**

Reviewer: **François Bissey**

_Issue created by migration from https://trac.sagemath.org/ticket/34858_

**Comment by mkoeppe** [comment]
Branch: **[u/mkoeppe/fix_sagemath_standard_sdist](https://github.com/sagemath/sagetrac-mirror/tree/u/mkoeppe/fix_sagemath_standard_sdist)**

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
Commit: **[`00deebe`](https://github.com/sagemath/sagetrac-mirror/commit/00deebede6ae54768e8648bee89038e26d3515f8)**

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
<div id="comment:2"></div>

Branch pushed to git repo; I updated commit sha1. New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/00deebede6ae54768e8648bee89038e26d3515f8"><code>00deebe</code></a></td><td><code>pkgs/sagemath-objects/setup.py: Run finder also for sdist, egg_info, dist_info</code></td></tr></table>

**Comment by mkoeppe** [comment]
Author: **Matthias Koeppe**

**Comment by mkoeppe** [comment]
Description changed:
``````diff
--- 
+++ 
@@ -11,3 +11,11 @@
 
 ```
 
+We fix this by 
+- updating MANIFEST
+- unconditionally running the module finder in pkgs/sagemath-standard/setup.py
+
+We make the same change also in pkgs/sagemath-objects/setup.py (by symlink, this also affects sagemath-categories).
+
+
+
``````

**Comment by mkoeppe** [comment]
Dependencies: **#34859**

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
Changed commit from **[`00deebe`](https://github.com/sagemath/sagetrac-mirror/commit/00deebede6ae54768e8648bee89038e26d3515f8)** to **[`e229436`](https://github.com/sagemath/sagetrac-mirror/commit/e22943612656b225396e4dea4fae654108b3cf3d)**

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
<div id="comment:4"></div>

Branch pushed to git repo; I updated commit sha1. New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/39bd748020fb651e5aeb7640ffe182e493353c79"><code>39bd748</code></a></td><td><code>src/sage/dynamics/arithmetic_dynamics/projective_ds.py: Remove unused import of typing_extensions</code></td></tr><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/e22943612656b225396e4dea4fae654108b3cf3d"><code>e229436</code></a></td><td><code>Merge #34859</code></td></tr></table>

**Comment by kiwifb** [comment]
<div id="comment:6" align="right">comment:6</div>

So no more sdist specific code in setup.py so simplification and make sure stuff is properly included in the manifest.

I am wondering if it is possible to first use a global include and then prune some of the files that are collected by that global include. I am just thinking we should explicitly list as few files as we can. It is a risk, because someone will forget to include them in the manifest when they create a new one - or delete one.

**Comment by mkoeppe** [comment]
<div id="comment:7" align="right">comment:7</div>

Yes, that's what the MANIFEST.in is doing. We do have to distinguish between the Cython-generated C/C++ files and actual C/C++ source files. Adding new such files is a relatively rare event

**Comment by kiwifb** [comment]
<div id="comment:8" align="right">comment:8</div>

I am very much in automation these days. While it is relatively short, maintaining this list by hand is a hazard. Which is why this ticket add 3 explicit files to `MANIFEST.in`. I am going to fill that under ideas to develop.

For the rest it looks good to me but I see #34859 has not been reviewed yet.

**Comment by mkoeppe** [comment]
<div id="comment:9" align="right">comment:9</div>

I hope to switch from setuptools to meson-python in #34630; then we can revisit this question.

**Comment by mkoeppe** [comment]
<div id="comment:10" align="right">comment:10</div>

Replying to [François Bissey](#comment%3A8):
> I see #34859 has not been reviewed yet.

Now the dependency has been reviewed

**Comment by kiwifb** [comment]
<div id="comment:11" align="right">comment:11</div>

Let's move on then.

**Comment by kiwifb** [comment]
Reviewer: **François Bissey**

**Comment by mkoeppe** [comment]
<div id="comment:12" align="right">comment:12</div>

Thanks!

**Comment by vbraun** [comment]
Changed branch from **[u/mkoeppe/fix_sagemath_standard_sdist](https://github.com/sagemath/sagetrac-mirror/tree/u/mkoeppe/fix_sagemath_standard_sdist)** to **[`e229436`](https://github.com/sagemath/sagetrac-mirror/commit/e22943612656b225396e4dea4fae654108b3cf3d)**
