### ISSUE TITLE
molien_series() should not use GAP's VirtualCharacter

### ISSUE THREAD

**Issue by dimpase** [sagemath/sage#34854]
<div id="comment:0"></div>

One can use GAP's PermutationCharacter() to avoid the troubles.

Currently we have a problem here:

```
sage: PG = PermutationGroup(["(1,2,3,4,5,6,7)","(5,6,7)"])
sage: PG.molien_series()
... weird error...
```

see the report in https://groups.google.com/d/msgid/sage-devel/42c6be87-614e-4a21-9273-91948f0c6216n%40googlegroups.com

CC:  @tscrim

Component: **group theory**

Author: **Dima Pasechnik**

Branch/Commit: **[`b7cf604`](https://github.com/sagemath/sagetrac-mirror/commit/b7cf604aa07cb9f63ee24aa6f3f21136cfacb680)**

Reviewer: **Travis Scrimshaw**

_Issue created by migration from https://trac.sagemath.org/ticket/34854_

**Comment by dimpase** [comment]
Author: **Dima Pasechnik**

**Comment by dimpase** [comment]
Branch: **[trac/u/dimpase/groups/fix_molien](https://github.com/sagemath/sagetrac-mirror/tree/trac/u/dimpase/groups/fix_molien)**

**Comment by dimpase** [comment]
<div id="comment:2"></div>

New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/b7cf604aa07cb9f63ee24aa6f3f21136cfacb680"><code>b7cf604</code></a></td><td><code>don't use virtual chars in Molien series computation</code></td></tr></table>

**Comment by dimpase** [comment]
Changed branch from **[trac/u/dimpase/groups/fix_molien](https://github.com/sagemath/sagetrac-mirror/tree/trac/u/dimpase/groups/fix_molien)** to **[u/dimpase/groups/fix_molien](https://github.com/sagemath/sagetrac-mirror/tree/u/dimpase/groups/fix_molien)**

**Comment by dimpase** [comment]
Commit: **[`b7cf604`](https://github.com/sagemath/sagetrac-mirror/commit/b7cf604aa07cb9f63ee24aa6f3f21136cfacb680)**

**Comment by tscrim** [comment]
Reviewer: **Travis Scrimshaw**

**Comment by tscrim** [comment]
<div id="comment:3" align="right">comment:3</div>

LGTM.

**Comment by vbraun** [comment]
Changed branch from **[u/dimpase/groups/fix_molien](https://github.com/sagemath/sagetrac-mirror/tree/u/dimpase/groups/fix_molien)** to **[`b7cf604`](https://github.com/sagemath/sagetrac-mirror/commit/b7cf604aa07cb9f63ee24aa6f3f21136cfacb680)**
