### ISSUE TITLE
bump giac's GIAC_MIN_VERSION to 1.9

### ISSUE THREAD

**Issue by dimpase** [sagemath/sage#34857]
<div id="comment:0"></div>

some distro's e.g. Fedora 34, carry giac 1.7, which is too old

Component: **build: configure**

Author: **Matthias Koeppe**

Branch/Commit: **[`d615eb2`](https://github.com/sagemath/sagetrac-mirror/commit/d615eb20e6c2209426ac67b0a4b4f504cbc912eb)**

Reviewer: **Dima Pasechnik**

_Issue created by migration from https://trac.sagemath.org/ticket/34857_

**Comment by mkoeppe** [comment]
<div id="comment:1" align="right">comment:1</div>

too old for what?

**Comment by kiwifb** [comment]
<div id="comment:2" align="right">comment:2</div>

Because #32354 raised the version of giac needed to 1.7.0-27 but didn't change `GIAC_MIN_VERSION` accordingly. Raising to 1.9 feels appropriate now.

**Comment by mkoeppe** [comment]
<div id="comment:3" align="right">comment:3</div>

ubuntu-jammy (LTS) only has 1.7.0.39, so I think it's better to just raise to some 1.7 version

**Comment by kiwifb** [comment]
<div id="comment:4" align="right">comment:4</div>

Replying to [Matthias Köppe](#comment%3A3):
> ubuntu-jammy (LTS) only has 1.7.0.39, so I think it's better to just raise to some 1.7 version

I am OK to raise it to just 1.7.0-27, I cannot think of any other tickets like #32354.

**Comment by mkoeppe** [comment]
<div id="comment:5" align="right">comment:5</div>

Unfortunately we don't know how to check the patchlevel. `giac --version` only reports 1.7.0 or 1.9.0

**Comment by kiwifb** [comment]
<div id="comment:6" align="right">comment:6</div>

Not even the header have the patch level. I do not think upstream provided a way to figure the patch level.

**Comment by mkoeppe** [comment]
<div id="comment:7" align="right">comment:7</div>

OK, then let's just use 1.9.0. Given that downstream versions of giac are affected by #33848, it's not a big loss that we have to build our own giac on ubuntu-jammy.

**Comment by mkoeppe** [comment]
Branch: **[u/mkoeppe/bump_giac_s_giac_min_version_to_1_9](https://github.com/sagemath/sagetrac-mirror/tree/u/mkoeppe/bump_giac_s_giac_min_version_to_1_9)**

**Comment by mkoeppe** [comment]
<div id="comment:9"></div>

New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/d615eb20e6c2209426ac67b0a4b4f504cbc912eb"><code>d615eb2</code></a></td><td><code>build/pkgs/giac/spkg-configure.m4: Require giac >= 1.9.0</code></td></tr></table>

**Comment by mkoeppe** [comment]
Author: **Matthias Koeppe**

**Comment by mkoeppe** [comment]
Commit: **[`d615eb2`](https://github.com/sagemath/sagetrac-mirror/commit/d615eb20e6c2209426ac67b0a4b4f504cbc912eb)**

**Comment by kiwifb** [comment]
<div id="comment:10" align="right">comment:10</div>

Well, I didn't realise the minimum version of giac was so low. I am not sure 1.5 releases would have work well, even before #32354. That's a rather trivial change. Do we want to keep a check on an upper version of giac? Currently at 1.9.999, which means the next major bump of giac will be rejected.

**Comment by dimpase** [comment]
<div id="comment:11" align="right">comment:11</div>

lgtm

**Comment by dimpase** [comment]
Reviewer: **Dima Pasechnik**

**Comment by vbraun** [comment]
Changed branch from **[u/mkoeppe/bump_giac_s_giac_min_version_to_1_9](https://github.com/sagemath/sagetrac-mirror/tree/u/mkoeppe/bump_giac_s_giac_min_version_to_1_9)** to **[`d615eb2`](https://github.com/sagemath/sagetrac-mirror/commit/d615eb20e6c2209426ac67b0a4b4f504cbc912eb)**
