### ISSUE TITLE
compute isomorphisms between quaternion orders

### ISSUE THREAD

**Issue by yyyyx4** [sagemath/sage#34861]
<div id="comment:0"></div>

This patch adds a method `QuaternionOrder.isomorphism_to()` which finds an isomorphism between two quaternion orders in the same quaternion algebra.

Algorithm: Two orders are isomorphic if and only if they are conjugate (Skolem–Noether), hence for isomorphic orders `O₁,O₂` the lattice `I = O₁·O₂` is principal. We search for a generator by minimizing the quadratic form associated to `I`; conjugation by such a generator then defines an isomorphism between `O₁` and `O₂`.

To make the computed ring isomorphism work correctly, it seems necessary to patch `RingHomomorphism_im_gens`: The `._im_gens_()` method on elements will necessarily use the generators of the quaternion *algebra*, not the order.

Component: **algebra**

Author: **Lorenz Panny**

_Issue created by migration from https://trac.sagemath.org/ticket/34861_

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
Changed commit from **[`f4f6f41`](https://github.com/sagemath/sagetrac-mirror/commit/f4f6f411d007c23eff6424f38ed9902448e87f7c)** to **[`f7b7b20`](https://github.com/sagemath/sagetrac-mirror/commit/f7b7b202e20f2d98e20c9f4441a7c8a1b53c0cbf)**

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
<div id="comment:2"></div>

Branch pushed to git repo; I updated commit sha1. New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/f7b7b202e20f2d98e20c9f4441a7c8a1b53c0cbf"><code>f7b7b20</code></a></td><td><code>factor out .minimal_element() method</code></td></tr></table>

**Comment by mkoeppe** [comment]
Removed branch from the issue description because it has been replaced by PR #34976

**Comment by kwankyu** [comment]
Would you explain the algorithm in more detail? Or is there a reference? Particularly, I have the following questions.

I see that $O_2=\beta O_1\beta^{-1}$ by Skolem-Noether. Then (1) why $I=O_1O_2$ is a principal ideal of what order? (2) why the element of $I$ minimizing the quadratic form associated with $I$ a generator of $I$? (3) I guess that the quadratic form associated with $I$ is the same quadratic form associated with the underlying quaternion algebra $B$. Am I right?

**Comment by yyyyx4** [comment]
I realized that this algorithm only works for maximal orders in definite quaternion algebras and updated the branch at #34976 accordingly. References are Lemma 17.4.7 and Exercise 4 in Chapter 17 of [Voight's book](https://math.dartmouth.edu/~jvoight/quat-book.pdf).
