### ISSUE TITLE
Uniformize headline: number theory

### ISSUE THREAD

**Issue by kwankyu** [sagemath/sage#34860]
<div id="comment:0"></div>

Started out so, but ended in cleaning up the number theory section of the main TOC.

CC:  @williamstein

Component: **documentation**

Author: **Kwankyu Lee**

Branch/Commit: **[`017648b`](https://github.com/sagemath/sagetrac-mirror/commit/017648b212b58ea6f6f33819f660e6a7f15314fd)**

Reviewer: **Matthias Koeppe**

_Issue created by migration from https://trac.sagemath.org/ticket/34860_

**Comment by kwankyu** [comment]
Branch: **[u/klee/uniformize_headline__number_theory](https://github.com/sagemath/sagetrac-mirror/tree/u/klee/uniformize_headline__number_theory)**

**Comment by kwankyu** [comment]
Commit: **[`d755384`](https://github.com/sagemath/sagetrac-mirror/commit/d755384c411c687b37245c13f5323e76aed53219)**

**Comment by kwankyu** [comment]
<div id="comment:2"></div>

New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/d755384c411c687b37245c13f5323e76aed53219"><code>d755384</code></a></td><td><code>Uniformize headlines of modular forms modules</code></td></tr></table>

**Comment by kwankyu** [comment]
Author: **Kwankyu Lee**

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
Changed commit from **[`d755384`](https://github.com/sagemath/sagetrac-mirror/commit/d755384c411c687b37245c13f5323e76aed53219)** to **[`0a844bf`](https://github.com/sagemath/sagetrac-mirror/commit/0a844bf6f45ec2ee38af33f4dea09163b43249d2)**

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
<div id="comment:4"></div>

Branch pushed to git repo; I updated commit sha1. This was a forced push. New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/0a844bf6f45ec2ee38af33f4dea09163b43249d2"><code>0a844bf</code></a></td><td><code>Uniformize headlines of number theory modules</code></td></tr></table>

**Comment by kwankyu** [comment]
Description changed:
``````diff
--- 
+++ 
@@ -1 +1 @@
-
+Started out so, but ended in cleaning up the number theory section of the main TOC.
``````

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
Changed commit from **[`0a844bf`](https://github.com/sagemath/sagetrac-mirror/commit/0a844bf6f45ec2ee38af33f4dea09163b43249d2)** to **[`12968fa`](https://github.com/sagemath/sagetrac-mirror/commit/12968faa7fce3d3f5f0df8f336f6ab79ebfb556d)**

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
<div id="comment:6"></div>

Branch pushed to git repo; I updated commit sha1. New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/12968faa7fce3d3f5f0df8f336f6ab79ebfb556d"><code>12968fa</code></a></td><td><code>Some edits on modform/notes.py</code></td></tr></table>

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
Changed commit from **[`12968fa`](https://github.com/sagemath/sagetrac-mirror/commit/12968faa7fce3d3f5f0df8f336f6ab79ebfb556d)** to **[`017648b`](https://github.com/sagemath/sagetrac-mirror/commit/017648b212b58ea6f6f33819f660e6a7f15314fd)**

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
<div id="comment:7"></div>

Branch pushed to git repo; I updated commit sha1. New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/017648b212b58ea6f6f33819f660e6a7f15314fd"><code>017648b</code></a></td><td><code>Uppercase a line in the main TOC</code></td></tr></table>

**Comment by mkoeppe** [comment]
Reviewer: **Matthias Koeppe**

**Comment by mkoeppe** [comment]
<div id="comment:8" align="right">comment:8</div>

This is a nice improvement.

Not sure if "to be sorted" if necessary to include in the section title

```
+
+Miscellaneous Modules (to be sorted)
+------------------------------------
+
```

**Comment by kwankyu** [comment]
<div id="comment:9" align="right">comment:9</div>

> Not sure if "to be sorted" is necessary to include in the section title
>
>
> +Miscellaneous Modules (to be sorted)
> +------------------------------------

I would be the first to remove the phrase if not necessary, but the modules in that section really need to be sorted out by an expert.

**Comment by vbraun** [comment]
Changed branch from **[u/klee/uniformize_headline__number_theory](https://github.com/sagemath/sagetrac-mirror/tree/u/klee/uniformize_headline__number_theory)** to **[`017648b`](https://github.com/sagemath/sagetrac-mirror/commit/017648b212b58ea6f6f33819f660e6a7f15314fd)**
