### ISSUE TITLE
construct QuadraticForm and BinaryQF objects from polynomial

### ISSUE THREAD

**Issue by yyyyx4** [sagemath/sage#34863]
<div id="comment:0"></div>

`QuadraticForm` and `BinaryQF` objects have a `.polynomial()` method to return the quadratic form represented as a multivariate polynomial, but the converse is not currently available. This patch adds it.

Component: **quadratic forms**

Author: **Lorenz Panny**

Branch/Commit: **[`9224d7e`](https://github.com/sagemath/sagetrac-mirror/commit/9224d7e06e480695b64d3da17341446e9e2ff5e3)**

Reviewer: **Matthias Koeppe**

_Issue created by migration from https://trac.sagemath.org/ticket/34863_

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
Changed commit from **[`87c8658`](https://github.com/sagemath/sagetrac-mirror/commit/87c86587080f3b3426e56fa78954ae4edc6b4dc4)** to **[`a3a94c0`](https://github.com/sagemath/sagetrac-mirror/commit/a3a94c0e1f0bcde66763aed9f4802cec8e68b6b4)**

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
<div id="comment:1"></div>

Branch pushed to git repo; I updated commit sha1. New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/a3a94c0e1f0bcde66763aed9f4802cec8e68b6b4"><code>a3a94c0</code></a></td><td><code>also implement .from_polynomial() for BinaryQF</code></td></tr></table>

**Comment by yyyyx4** [comment]
Description changed:
``````diff
--- 
+++ 
@@ -1 +1 @@
-`QuadraticForm` objects have a `.polynomial()` method to return the quadratic form represented as a multivariate polynomial, but the converse is not currently available. This patch adds it.
+`QuadraticForm` and `BinaryQF` objects have a `.polynomial()` method to return the quadratic form represented as a multivariate polynomial, but the converse is not currently available. This patch adds it.
``````

**Comment by mkoeppe** [comment]
<div id="comment:3" align="right">comment:3</div>


```
+        Construct a :class:`BinaryQF` from a bivariate polynomial
+        with integer coefficients. Converse of :meth:`polynomial`.
```

I think that should be "inverse"

**Comment by mkoeppe** [comment]
Reviewer: **Matthias Koeppe**

**Comment by mkoeppe** [comment]
<div id="comment:4" align="right">comment:4</div>

Other than that, LGTM.

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
Changed commit from **[`a3a94c0`](https://github.com/sagemath/sagetrac-mirror/commit/a3a94c0e1f0bcde66763aed9f4802cec8e68b6b4)** to **[`9224d7e`](https://github.com/sagemath/sagetrac-mirror/commit/9224d7e06e480695b64d3da17341446e9e2ff5e3)**

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
<div id="comment:5"></div>

Branch pushed to git repo; I updated commit sha1. New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/9224d7e06e480695b64d3da17341446e9e2ff5e3"><code>9224d7e</code></a></td><td><code>converse -> inverse</code></td></tr></table>

**Comment by yyyyx4** [comment]
<div id="comment:6" align="right">comment:6</div>

Thanks! Changed the word and setting to positive review under the assumption that that's what your [comment:4](#comment%3A4) meant.

**Comment by vbraun** [comment]
Changed branch from **[public/construct_quadratic_form_from_polynomial](https://github.com/sagemath/sagetrac-mirror/tree/public/construct_quadratic_form_from_polynomial)** to **[`9224d7e`](https://github.com/sagemath/sagetrac-mirror/commit/9224d7e06e480695b64d3da17341446e9e2ff5e3)**
