### ISSUE TITLE
compute matrix kernels modulo composites

### ISSUE THREAD

**Issue by yyyyx4** [sagemath/sage#34862]
<div id="comment:0"></div>

Currently, Sage cannot compute kernels of matrices over `Zmod(n)` for composite `n`.

This patch adds a call path from `Matrix.right_kernel_matrix()` to PARI's `matkermod()` function for matrices defined over `IntegerModRing`s with composite modulus.

Also, for symmetry we add a `.left_kernel_matrix()` method that simply calls `.transpose()` and defers to `.right_kernel_matrix()`.

Component: **linear algebra**

Author: **Lorenz Panny**

_Issue created by migration from https://trac.sagemath.org/ticket/34862_

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
Changed commit from **[`8ed83fa`](https://github.com/sagemath/sagetrac-mirror/commit/8ed83faf91893602357f3ccfc7d48d09e896ae40)** to **[`a005c96`](https://github.com/sagemath/sagetrac-mirror/commit/a005c96e3166484950d57df7e8c0c254b8d96bda)**

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
<div id="comment:2"></div>

Branch pushed to git repo; I updated commit sha1. New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/a005c96e3166484950d57df7e8c0c254b8d96bda"><code>a005c96</code></a></td><td><code>fix doctests</code></td></tr></table>

**Comment by mkoeppe** [comment]
Removed branch from the issue description because it has been replaced by PR #34968
