### ISSUE TITLE
FPLLL 5.4.4  and FPyLLL 0.5.9

### ISSUE THREAD

**Issue by malb** [sagemath/sage#34870]
<div id="comment:0"></div>

https://github.com/fplll/fplll/releases/download/5.4.4/fplll-5.4.4.tar.gz

https://github.com/fplll/fpylll/releases/download/0.5.9/fpylll-0.5.9.tar.gz

CC:  @kiwifb

Component: **packages: standard**

Author: **Martin Albrecht**

Branch/Commit: **[`1730504`](https://github.com/sagemath/sagetrac-mirror/commit/1730504131ba2f31cc0af4984276b85af0474dc7)**

Reviewer: **Matthias Koeppe, Dima Pasechnik**

_Issue created by migration from https://trac.sagemath.org/ticket/34870_

**Comment by malb** [comment]
Branch: **[u/malb/fplll__and_fpylll](https://github.com/sagemath/sagetrac-mirror/tree/u/malb/fplll__and_fpylll)**

**Comment by malb** [comment]
<div id="comment:2"></div>

New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/105bdeaaa7fae54f0f16b8d50c3e434f9d960041"><code>105bdea</code></a></td><td><code>FPLLL  and FPyLLL</code></td></tr></table>

**Comment by malb** [comment]
Description changed:
``````diff
--- 
+++ 
@@ -1 +1,3 @@
+https://github.com/fplll/fplll/releases/download/5.4.3/fplll-5.4.3.tar.gz
 
+https://github.com/fplll/fpylll/releases/download/0.5.8/fpylll-0.5.8.tar.gz
``````

**Comment by malb** [comment]
Commit: **[`105bdea`](https://github.com/sagemath/sagetrac-mirror/commit/105bdeaaa7fae54f0f16b8d50c3e434f9d960041)**

**Comment by malb** [comment]
Author: **Martin Albrecht**

**Comment by mkoeppe** [comment]
<div id="comment:4" align="right">comment:4</div>

I've run this (with some other upgrade tickets) in https://github.com/mkoeppe/sage/actions/runs/3813720548, looking fine

**Comment by mkoeppe** [comment]
Reviewer: **Matthias Koeppe**

**Comment by malb** [comment]
<div id="comment:6" align="right">comment:6</div>

some issues were reported upstream, we're fixing them and I'll cut a new release.

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
Changed commit from **[`105bdea`](https://github.com/sagemath/sagetrac-mirror/commit/105bdeaaa7fae54f0f16b8d50c3e434f9d960041)** to **[`9081136`](https://github.com/sagemath/sagetrac-mirror/commit/9081136dfcb60931f0c5d57257f987a028b18ed6)**

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
<div id="comment:7"></div>

Branch pushed to git repo; I updated commit sha1. New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/9081136dfcb60931f0c5d57257f987a028b18ed6"><code>9081136</code></a></td><td><code>FPLLL 5.4.4 and FPyLLL 0.5.8</code></td></tr></table>

**Comment by malb** [comment]
<div id="comment:8" align="right">comment:8</div>

Test failures on non x86_64 architectures were fixed in FPLLL 5.4.4.

**Comment by malb** [comment]
Description changed:
``````diff
--- 
+++ 
@@ -1,3 +1,3 @@
-https://github.com/fplll/fplll/releases/download/5.4.3/fplll-5.4.3.tar.gz
+https://github.com/fplll/fplll/releases/download/5.4.4/fplll-5.4.4.tar.gz
 
 https://github.com/fplll/fpylll/releases/download/0.5.8/fpylll-0.5.8.tar.gz
``````

**Comment by dimpase** [comment]
<div id="comment:9" align="right">comment:9</div>

fpylll does runtime checks on whether it is called from Sage. IMHO this is wrong, and the corresponding conversion ZZ->mpz code should be moved to Sage.

**Comment by malb** [comment]
<div id="comment:10" align="right">comment:10</div>

Replying to [Dima Pasechnik](#comment%3A9):
> fpylll does runtime checks on whether it is called from Sage. IMHO this is wrong, and the corresponding conversion ZZ->mpz code should be moved to Sage.

I don't think this should be discussed on this ticket. Can open another one?

**Comment by dimpase** [comment]
<div id="comment:11" align="right">comment:11</div>

Replying to [Martin Albrecht](#comment%3A10):
> Replying to [Dima Pasechnik](#comment%3A9):
> > fpylll does runtime checks on whether it is called from Sage. IMHO this is wrong, and the corresponding conversion ZZ->mpz code should be moved to Sage.
> 
> 
> I don't think this should be discussed on this ticket. Can open another one?

OK, sure, I opened #34908 for this.

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
Changed commit from **[`9081136`](https://github.com/sagemath/sagetrac-mirror/commit/9081136dfcb60931f0c5d57257f987a028b18ed6)** to **[`1730504`](https://github.com/sagemath/sagetrac-mirror/commit/1730504131ba2f31cc0af4984276b85af0474dc7)**

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
<div id="comment:12"></div>

Branch pushed to git repo; I updated commit sha1. New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/1730504131ba2f31cc0af4984276b85af0474dc7"><code>1730504</code></a></td><td><code>FPLLL 5.4.4 and FPyLLL 0.5.9</code></td></tr></table>

**Comment by malb** [comment]
Description changed:
``````diff
--- 
+++ 
@@ -1,3 +1,3 @@
 https://github.com/fplll/fplll/releases/download/5.4.4/fplll-5.4.4.tar.gz
 
-https://github.com/fplll/fpylll/releases/download/0.5.8/fpylll-0.5.8.tar.gz
+https://github.com/fplll/fpylll/releases/download/0.5.9/fpylll-0.5.9.tar.gz
``````

**Comment by malb** [comment]
<div id="comment:14" align="right">comment:14</div>

All updated now.

**Comment by mkoeppe** [comment]
Changed reviewer from **Matthias Koeppe** to **Matthias Koeppe, ...**

**Comment by dimpase** [comment]
Changed reviewer from **Matthias Koeppe, ...** to **Matthias Koeppe, Dima Pasechnik**

**Comment by dimpase** [comment]
<div id="comment:17" align="right">comment:17</div>

OK

**Comment by vbraun** [comment]
Changed branch from **[u/malb/fplll__and_fpylll](https://github.com/sagemath/sagetrac-mirror/tree/u/malb/fplll__and_fpylll)** to **[`1730504`](https://github.com/sagemath/sagetrac-mirror/commit/1730504131ba2f31cc0af4984276b85af0474dc7)**
