### ISSUE TITLE
rename "Starks" algorithm for isogenies to Stark

### ISSUE THREAD

**Issue by yyyyx4** [sagemath/sage#34871]
<div id="comment:0"></div>

...since that's the author's name.

CC:  @JohnCremona @categorie @shumow

Component: **elliptic curves**

Author: **Lorenz Panny**

Branch/Commit: **[public/fix_stark_algorithm_name](https://github.com/sagemath/sagetrac-mirror/tree/public/fix_stark_algorithm_name) @ [`4d21760`](https://github.com/sagemath/sagetrac-mirror/commit/4d21760477ffe64924e274e68e6631b35bed8a62)**

Reviewer: **John Cremona**

_Issue created by migration from https://trac.sagemath.org/ticket/34871_

**Comment by yyyyx4** [comment]
Commit: **[`4d21760`](https://github.com/sagemath/sagetrac-mirror/commit/4d21760477ffe64924e274e68e6631b35bed8a62)**

**Comment by yyyyx4** [comment]
Branch: **[public/fix_stark_algorithm_name](https://github.com/sagemath/sagetrac-mirror/tree/public/fix_stark_algorithm_name)**

**Comment by yyyyx4** [comment]
Author: **Lorenz Panny**

**Comment by yyyyx4** [comment]
<div id="comment:1"></div>

New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/4d21760477ffe64924e274e68e6631b35bed8a62"><code>4d21760</code></a></td><td><code>rename "Starks" algorithm to Stark</code></td></tr></table>

**Comment by JohnCremona** [comment]
<div id="comment:2" align="right">comment:2</div>

Fine by me assuming tests pass.  I see that you did put in a Deprecation Warning -- good!

**Comment by JohnCremona** [comment]
Reviewer: **John Cremona**

**Comment by mkoeppe** [comment]
Merged in 10.0.beta0
