### ISSUE TITLE
MixedIntegerLinearProgram.add_constraint: Option to return row indices, fix handling of empty constraints

### ISSUE THREAD

**Issue by mkoeppe** [sagemath/sage#34878]
<div id="comment:0"></div>

(from [#21003 comment:136](https://github.com/sagemath/sage/issues/21003#comment:136))

... for use with methods that take row indices as input, such as `row`, `row_bounds`, `remove_constraint`.

If a backend does not map a constraint to a unique new row (or `check_redundant=True` and the constraint is discarded by the frontend), the method may return `None`.

We also fix a longstanding bug in how empty constraints are handled in `add_constraint`. 

The changed interface (an optional return value) is backward-compatible with user code.

We also add a Feature CVXOPT so that the backend gets tested again.

CC:  @mantepse @dimpase

Component: **linear programming**

Author: **Matthias Koeppe, Martin Rubey**

Branch/Commit: **[`3b929f8`](https://github.com/sagemath/sagetrac-mirror/commit/3b929f89b56dd1347df6a125460262cfaae62eca)**

Reviewer: **Martin Rubey, Matthias Koeppe**

_Issue created by migration from https://trac.sagemath.org/ticket/34878_

**Comment by mkoeppe** [comment]
Branch: **[u/mkoeppe/mixedintegerlinearprogram_add_constraint__return_row_index](https://github.com/sagemath/sagetrac-mirror/tree/u/mkoeppe/mixedintegerlinearprogram_add_constraint__return_row_index)**

**Comment by mkoeppe** [comment]
Author: **Matthias Koeppe**

**Comment by mkoeppe** [comment]
<div id="comment:2" align="right">comment:2</div>

Doctests need adjusting because of the extra output

---
New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/7ad324ffec72c9310e8bf51df84438512c7f895e"><code>7ad324f</code></a></td><td><code>MixedIntegerLinearProgram.add_constraint: Return row index</code></td></tr></table>

**Comment by mkoeppe** [comment]
Commit: **[`7ad324f`](https://github.com/sagemath/sagetrac-mirror/commit/7ad324ffec72c9310e8bf51df84438512c7f895e)**

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
Changed commit from **[`7ad324f`](https://github.com/sagemath/sagetrac-mirror/commit/7ad324ffec72c9310e8bf51df84438512c7f895e)** to **[`9daa44c`](https://github.com/sagemath/sagetrac-mirror/commit/9daa44cbebde11538ce6da624887fa74c14e7825)**

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
<div id="comment:3"></div>

Branch pushed to git repo; I updated commit sha1. New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/9daa44cbebde11538ce6da624887fa74c14e7825"><code>9daa44c</code></a></td><td><code>src/sage/numerical/mip.pyx: Update doctests for .add_constraint returning the row index</code></td></tr></table>

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
Changed commit from **[`9daa44c`](https://github.com/sagemath/sagetrac-mirror/commit/9daa44cbebde11538ce6da624887fa74c14e7825)** to **[`e154d29`](https://github.com/sagemath/sagetrac-mirror/commit/e154d2999bef790a92b69524e967cd5feb8d4b66)**

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
<div id="comment:4"></div>

Branch pushed to git repo; I updated commit sha1. New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/bc01716f6774bd433b30babd322a9f0db521b7e0"><code>bc01716</code></a></td><td><code>MixedIntegerLinearProgram.add_constraint: Do not refuse to add empty constraints; they could be infeasible or we may need their row index for later</code></td></tr><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/e154d2999bef790a92b69524e967cd5feb8d4b66"><code>e154d29</code></a></td><td><code>src/sage/numerical/backends: Update doctests</code></td></tr></table>

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
Changed commit from **[`e154d29`](https://github.com/sagemath/sagetrac-mirror/commit/e154d2999bef790a92b69524e967cd5feb8d4b66)** to **[`8adca04`](https://github.com/sagemath/sagetrac-mirror/commit/8adca04fcff46fbbd3bfe357e8d1955081b671aa)**

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
<div id="comment:5"></div>

Branch pushed to git repo; I updated commit sha1. New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/166b1d3a0d4471a866281bac0a6fa5b56f0f4c4b"><code>166b1d3</code></a></td><td><code>src/sage/numerical/backends/cvxopt_backend.pyx: Update doctests</code></td></tr><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/8adca04fcff46fbbd3bfe357e8d1955081b671aa"><code>8adca04</code></a></td><td><code>src/sage/features/mip_backends.py: Add CVXOPT feature</code></td></tr></table>

**Comment by mkoeppe** [comment]
Description changed:
``````diff
--- 
+++ 
@@ -4,3 +4,7 @@
 
 If a backend does not map a constraint to a unique new row (or `check_redundant=True` and the constraint is discarded by the frontend), the method may return `None`.
 
+We also fix a longstanding bug in how empty constraints are handled in `add_constraint`. 
+
+The changed interface (a return value) is backward-compatible with user code, but lots of doctests need to be changed. To make sure that also CVXOPT backend is tested when cvxopt is installed, we add it as a Feature.
+
``````

**Comment by mantepse** [comment]
<div id="comment:8" align="right">comment:8</div>

I'm sorry to comment late.  I have two (quite orthogonal) suggestions:

* I think that `add_constraint` should return a list of constraints added, or `None`.
    * `None` should be returned if and only if the backend does not provide a means to remove this constraint again.  
    * The empty list should be returned if and only if the constraint was redundant.
    * Otherwise, removing the constraints using `remove_constraint` yields the original MILP.
* possibly, it would make sense to return this list only on demand, eg., have a flag `return_indices`.  I am guessing that this would be better for interactive use, and it also means that only very few doctests would have to be modified.

**Comment by mkoeppe** [comment]
<div id="comment:9" align="right">comment:9</div>

That would be fine with me. Do you want to push a branch that does this?

**Comment by mantepse** [comment]
<div id="comment:10" align="right">comment:10</div>

Yes, I can do this.

**Comment by mantepse** [comment]
Changed branch from **[u/mkoeppe/mixedintegerlinearprogram_add_constraint__return_row_index](https://github.com/sagemath/sagetrac-mirror/tree/u/mkoeppe/mixedintegerlinearprogram_add_constraint__return_row_index)** to **[u/mantepse/mixedintegerlinearprogram_add_constraint__return_row_index](https://github.com/sagemath/sagetrac-mirror/tree/u/mantepse/mixedintegerlinearprogram_add_constraint__return_row_index)**

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
<div id="comment:12"></div>

Branch pushed to git repo; I updated commit sha1. New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/cfe24fe41656e678df6014c11eed35e4cdf6da31"><code>cfe24fe</code></a></td><td><code>add a doctest for adding and removing constraints</code></td></tr></table>

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
Changed commit from **[`8adca04`](https://github.com/sagemath/sagetrac-mirror/commit/8adca04fcff46fbbd3bfe357e8d1955081b671aa)** to **[`cfe24fe`](https://github.com/sagemath/sagetrac-mirror/commit/cfe24fe41656e678df6014c11eed35e4cdf6da31)**

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
<div id="comment:13"></div>

Branch pushed to git repo; I updated commit sha1. New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/6c34bc3273b821304b9d8403bf936a5f9add88a7"><code>6c34bc3</code></a></td><td><code>make linter happy</code></td></tr></table>

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
Changed commit from **[`cfe24fe`](https://github.com/sagemath/sagetrac-mirror/commit/cfe24fe41656e678df6014c11eed35e4cdf6da31)** to **[`6c34bc3`](https://github.com/sagemath/sagetrac-mirror/commit/6c34bc3273b821304b9d8403bf936a5f9add88a7)**

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
<div id="comment:14"></div>

Branch pushed to git repo; I updated commit sha1. New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/3b929f89b56dd1347df6a125460262cfaae62eca"><code>3b929f8</code></a></td><td><code>forgot newline in docstring</code></td></tr></table>

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
Changed commit from **[`6c34bc3`](https://github.com/sagemath/sagetrac-mirror/commit/6c34bc3273b821304b9d8403bf936a5f9add88a7)** to **[`3b929f8`](https://github.com/sagemath/sagetrac-mirror/commit/3b929f89b56dd1347df6a125460262cfaae62eca)**

**Comment by mantepse** [comment]
<div id="comment:15" align="right">comment:15</div>

Please review!

In particular, whether

```
        The row indices of the constraints added, if
        ``return_indices`` is true and the backend guarantees that
        removing them again yields the original MIP, ``None``
        otherwise.
```
is correct, i.e., there are currently no backends that do anything bad.

**Comment by mantepse** [comment]
Reviewer: **Martin Rubey, Matthias Koeppe**

**Comment by mantepse** [comment]
Changed author from **Matthias Koeppe** to **Matthias Koeppe, Martin Rubey**

**Comment by mkoeppe** [comment]
<div id="comment:17" align="right">comment:17</div>

LGTM, thanks!

**Comment by mkoeppe** [comment]
Description changed:
``````diff
--- 
+++ 
@@ -6,5 +6,5 @@
 
 We also fix a longstanding bug in how empty constraints are handled in `add_constraint`. 
 
-The changed interface (a return value) is backward-compatible with user code, but lots of doctests need to be changed. To make sure that also CVXOPT backend is tested when cvxopt is installed, we add it as a Feature.
+The changed interface (a return value) is backward-compatible with user code.
 
``````

**Comment by mkoeppe** [comment]
Description changed:
``````diff
--- 
+++ 
@@ -6,5 +6,6 @@
 
 We also fix a longstanding bug in how empty constraints are handled in `add_constraint`. 
 
-The changed interface (a return value) is backward-compatible with user code.
+The changed interface (an optional return value) is backward-compatible with user code.
 
+We also add a Feature CVXOPT so that the backend gets tested again.
``````

**Comment by mantepse** [comment]
<div id="comment:20" align="right">comment:20</div>

Thank you!

Actually, it would be practical if the following too would also work, don't you think  (Ideally also with `False`, or `True` as argument)?

If you agree, it won't be hard to fix.  I don't know whether one can add these as constraints to all backends, but we could simply ignore the first and raise a `MIPSolverException` for the second.

This would make (my) user code much more readable.

```
sage: p = MixedIntegerLinearProgram(solver='GLPK')
sage: p.add_constraint(p.linear_functions_parent()(0 <= 0))
ValueError                                Traceback (most recent call last)
...
ValueError: at least one of "max" or "min" must be set

sage: p.add_constraint(p.linear_functions_parent()(1 <= 0))
ValueError                                Traceback (most recent call last)
...
ValueError: at least one of "max" or "min" must be set
```

**Comment by mkoeppe** [comment]
<div id="comment:21" align="right">comment:21</div>

You probably mean `linear_constraints_parent` here

**Comment by mkoeppe** [comment]
<div id="comment:22" align="right">comment:22</div>

It would be OK with me for
- p.add_constraint(True) to add the trivial constraint "0 <= 0"
- p.add_constraint(False) to add the infeasible constraint "0 <= -1"

**Comment by mantepse** [comment]
<div id="comment:23" align="right">comment:23</div>

Oh, thanks, yes, you are right.  Here we currently have

```
sage: p.add_constraint(p.linear_constraints_parent()(1 <= 0))
sage: p
Mixed Integer Program (no objective, 0 variables, 0 constraints)
sage: p.show()
Maximization:
  

Constraints:
Variables:
sage: p.linear_constraints_parent()(1 <= 0)
trivial constraint starting with 0
sage: p.linear_constraints_parent()(0 <= 0)
trivial constraint starting with 1
```

**Comment by mkoeppe** [comment]
<div id="comment:24" align="right">comment:24</div>

"trivial constraint starting with" is, of course, ridiculous wording. We should revise this.

**Comment by mantepse** [comment]
<div id="comment:25" align="right">comment:25</div>

I am away for a few hours now :-)

**Comment by mkoeppe** [comment]
<div id="comment:26" align="right">comment:26</div>

I've opened #34882 for this.

**Comment by mantepse** [comment]
<div id="comment:27" align="right">comment:27</div>

Thanks! However, I think the other two are bugs and should be fixed here.

**Comment by mkoeppe** [comment]
<div id="comment:28" align="right">comment:28</div>

Which two?

**Comment by mkoeppe** [comment]
<div id="comment:29" align="right">comment:29</div>

Note that there's the coercion route bool -> int -> ZZ

**Comment by mantepse** [comment]
<div id="comment:30" align="right">comment:30</div>


```
sage: p = MixedIntegerLinearProgram(solver='GLPK')
sage: p.add_constraint(p.linear_constraints_parent()(1 <= 0))
sage: p.solve()
0.0
```
because it is actually not adding a constraint.

**Comment by mkoeppe** [comment]
<div id="comment:31" align="right">comment:31</div>

that's bool -> int -> ZZ -> linear_function_parent -> linear_constraints_parent, not a bug

**Comment by mkoeppe** [comment]
<div id="comment:32" align="right">comment:32</div>

-> #34882

**Comment by mantepse** [comment]
<div id="comment:33" align="right">comment:33</div>

The problem is that for `f = p.linear_constraints_parent()(1 <= 0)` we have neither have `f.equations()` nor `f.inequalities()`.

The following does work (also for GLPK):

```
sage: p = MixedIntegerLinearProgram(solver='SCIP')
sage: f = p.linear_functions_parent()(1 - 0)
sage: p.add_constraint(f, max=0, return_indices=True)
[0]
sage: p.show()
Maximization:
  

Constraints:
  c1: <= -1.0
Variables:
```
I am not sure how reliable this is.  Also, shouldn't the max be shown?

**Comment by mantepse** [comment]
<div id="comment:34" align="right">comment:34</div>

Ah, sorry, now I see.  Sorry.

**Comment by mkoeppe** [comment]
<div id="comment:35" align="right">comment:35</div>

I agree that changing the display of the empty linear form in " <= -1.0" to 0 would be an improvement

**Comment by mantepse** [comment]
<div id="comment:36" align="right">comment:36</div>

So actually we should also try to do something sensible with `p.linear_constraints_parent()(False)`.

**Comment by vbraun** [comment]
Changed branch from **[u/mantepse/mixedintegerlinearprogram_add_constraint__return_row_index](https://github.com/sagemath/sagetrac-mirror/tree/u/mantepse/mixedintegerlinearprogram_add_constraint__return_row_index)** to **[`3b929f8`](https://github.com/sagemath/sagetrac-mirror/commit/3b929f89b56dd1347df6a125460262cfaae62eca)**
