### ISSUE TITLE
Implement Specht modules for arbitrary diagrams

### ISSUE THREAD

**Issue by tscrim** [sagemath/sage#34883]
<div id="comment:0"></div>

We implement Specht modules arbitrary diagrams as a submodule of the symmetric group algebra.

We also include a method to just compute the dimension to avoid having to (potentially) fully echelonize the basis for constructing the submodule.

CC:  @fchapoton @anneschilling @zabrocki @saliola @darijgr

Component: **combinatorics**

Keywords: **Specht module**

Author: **Travis Scrimshaw**

_Issue created by migration from https://trac.sagemath.org/ticket/34883_

**Comment by tscrim** [comment]
<div id="comment:1"></div>

New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/16dfa666709be741b66b8aec668998784651a91b"><code>16dfa66</code></a></td><td><code>Initial implementation of Specht modules.</code></td></tr></table>

**Comment by tscrim** [comment]
Commit: **[`16dfa66`](https://github.com/sagemath/sagetrac-mirror/commit/16dfa666709be741b66b8aec668998784651a91b)**

**Comment by tscrim** [comment]
Branch: **[public/combinat/specht_modules-34883](https://github.com/sagemath/sagetrac-mirror/tree/public/combinat/specht_modules-34883)**

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
<div id="comment:2"></div>

Branch pushed to git repo; I updated commit sha1. New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/2a33eb2a7e7e2fa8ce20b4f28364bcea4cff6fb0"><code>2a33eb2</code></a></td><td><code>Doing some refactoring and doc work.</code></td></tr></table>

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
Changed commit from **[`16dfa66`](https://github.com/sagemath/sagetrac-mirror/commit/16dfa666709be741b66b8aec668998784651a91b)** to **[`2a33eb2`](https://github.com/sagemath/sagetrac-mirror/commit/2a33eb2a7e7e2fa8ce20b4f28364bcea4cff6fb0)**

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
Changed commit from **[`2a33eb2`](https://github.com/sagemath/sagetrac-mirror/commit/2a33eb2a7e7e2fa8ce20b4f28364bcea4cff6fb0)** to **[`623cf34`](https://github.com/sagemath/sagetrac-mirror/commit/623cf34c0caa549e9f80bc706c4c2676922ba282)**

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
<div id="comment:3"></div>

Branch pushed to git repo; I updated commit sha1. New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/623cf34c0caa549e9f80bc706c4c2676922ba282"><code>623cf34</code></a></td><td><code>Adding additional documentation. Allowing permutations to act on the Specht module.</code></td></tr></table>

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
Changed commit from **[`623cf34`](https://github.com/sagemath/sagetrac-mirror/commit/623cf34c0caa549e9f80bc706c4c2676922ba282)** to **[`b283aa5`](https://github.com/sagemath/sagetrac-mirror/commit/b283aa569b6efeaa5d44d31cb8394c7e1bfb89cf)**

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
<div id="comment:4"></div>

Branch pushed to git repo; I updated commit sha1. New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/b283aa569b6efeaa5d44d31cb8394c7e1bfb89cf"><code>b283aa5</code></a></td><td><code>Fixing one last doctest.</code></td></tr></table>

**Comment by tscrim** [comment]
Description changed:
``````diff
--- 
+++ 
@@ -1 +1,3 @@
-For permutations, we implement a function to compute the dimension and a basis for Specht modules as a submodule of the symmetric group algebra.
+We implement Specht modules arbitrary diagrams as a submodule of the symmetric group algebra.
+
+We also include a method to just compute the dimension to avoid having to (potentially) fully echelonize the basis for constructing the submodule.
``````

**Comment by mkoeppe** [comment]
<div id="comment:6" align="right">comment:6</div>

Sure you want to abbreviate "base ring" as BR in keyword parameters?

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
Changed commit from **[`b283aa5`](https://github.com/sagemath/sagetrac-mirror/commit/b283aa569b6efeaa5d44d31cb8394c7e1bfb89cf)** to **[`32a0ac6`](https://github.com/sagemath/sagetrac-mirror/commit/32a0ac6611e8894afe923e94de298a4673b04c94)**

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
<div id="comment:7"></div>

Branch pushed to git repo; I updated commit sha1. New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/32a0ac6611e8894afe923e94de298a4673b04c94"><code>32a0ac6</code></a></td><td><code>Changing BR to base_ring as an argument.</code></td></tr></table>

**Comment by mkoeppe** [comment]
Removed branch from issue description because it has been replaced by PR #35036
