### ISSUE TITLE
Installation guide: On WSL, clear /mnt/c stuff from PATH

### ISSUE THREAD

**Issue by mkoeppe** [sagemath/sage#34889]
<div id="comment:0"></div>

As seen in https://groups.google.com/g/sage-devel/c/1nYw7-6QSkQ, our `configure` script fails to notice that some stuff in finds in PATH is not suitable:

```
configure:7510: found /mnt/c/Strawberry/perl/bin/pkg-config
configure:7522: result: /mnt/c/Strawberry/perl/bin/pkg-config
configure:7547: checking pkg-config is at least version 0.29
...
configure:33252: checking for xml2-config
configure:33275: found /mnt/c/Strawberry/c/bin/xml2-config
configure:33288: result: /mnt/c/Strawberry/c/bin/xml2-config
configure:33305: will use system package and not install SPKG libxml2
...
configure:42387: checking for PRIMESIEVE
configure:42394: $PKG_CONFIG --exists --print-errors "primesieve >= 8.0"
./configure: /mnt/c/Strawberry/perl/bin/pkg-config: perl: bad interpreter: No such file or directory
```

CC:  @dimpase @tobiasdiez

Component: **documentation**

Author: **Matthias Koeppe**

Branch/Commit: **[`80a84d4`](https://github.com/sagemath/sagetrac-mirror/commit/80a84d400add37b79e33660b53af06790c5f8191)**

Reviewer: **Dima Pasechnik**

_Issue created by migration from https://trac.sagemath.org/ticket/34889_

**Comment by mkoeppe** [comment]
Branch: **[u/mkoeppe/installation_guide__on_wsl__clear__mnt_c_stuff_from_path](https://github.com/sagemath/sagetrac-mirror/tree/u/mkoeppe/installation_guide__on_wsl__clear__mnt_c_stuff_from_path)**

**Comment by mkoeppe** [comment]
Commit: **[`80a84d4`](https://github.com/sagemath/sagetrac-mirror/commit/80a84d400add37b79e33660b53af06790c5f8191)**

**Comment by mkoeppe** [comment]
<div id="comment:2"></div>

New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/80a84d400add37b79e33660b53af06790c5f8191"><code>80a84d4</code></a></td><td><code>README.md: Add step to sanitize the environment</code></td></tr></table>

**Comment by mkoeppe** [comment]
Author: **Matthias Koeppe**

**Comment by dimpase** [comment]
Reviewer: **Dima Pasechnik**

**Comment by dimpase** [comment]
<div id="comment:3" align="right">comment:3</div>

lgtm

**Comment by tobiasdiez** [comment]
<div id="comment:4" align="right">comment:4</div>

Note that this workaround disables that one could run windows command line tools from within linux: https://learn.microsoft.com/en-us/windows/wsl/filesystems#run-windows-tools-from-linux

For example, without this workaround, one can run `code` from within the linux command line to open Windows' vscode in wsl mode in the correct folder.

**Comment by tobiasdiez** [comment]
<div id="comment:5" align="right">comment:5</div>

There is also a windows config option that controls whether the windows path is appended: https://learn.microsoft.com/en-us/windows/wsl/wsl-config#interop-settings

**Comment by mkoeppe** [comment]
<div id="comment:6" align="right">comment:6</div>

Maybe we can add something like "It's safe to keep `/mnt/c/.../Programs/Microsoft VS Code/bin/` in the PATH"?

**Comment by vbraun** [comment]
Changed branch from **[u/mkoeppe/installation_guide__on_wsl__clear__mnt_c_stuff_from_path](https://github.com/sagemath/sagetrac-mirror/tree/u/mkoeppe/installation_guide__on_wsl__clear__mnt_c_stuff_from_path)** to **[`80a84d4`](https://github.com/sagemath/sagetrac-mirror/commit/80a84d400add37b79e33660b53af06790c5f8191)**
