### ISSUE TITLE
set reverse=True by default in basis_for_quaternion_lattice()

### ISSUE THREAD

**Issue by yyyyx4** [sagemath/sage#34880]
<div id="comment:0"></div>

The `reverse=True` flag is recommended (and set by default) for quaternion orders, but I think it is also the better choice for all other quaternion lattices: Among other things, setting `reverse=True` makes the returned basis contain the norm of an ideal (very usefully generalizing the fact that the returned basis for an order contains `1`).

Component: **algebra**

Author: **Lorenz Panny**

_Issue created by migration from https://trac.sagemath.org/ticket/34880_

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
Changed commit from **[`1282c28`](https://github.com/sagemath/sagetrac-mirror/commit/1282c2833a4f3e5a09df121ce86014f01d05cdbd)** to **[`bc3cdda`](https://github.com/sagemath/sagetrac-mirror/commit/bc3cdda80a13d8b26823c3dfdb65c0753d31ef72)**

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
<div id="comment:1"></div>

Branch pushed to git repo; I updated commit sha1. This was a forced push. New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/bc3cdda80a13d8b26823c3dfdb65c0753d31ef72"><code>bc3cdda</code></a></td><td><code>set reverse=True by default in basis_for_quaternion_lattice()</code></td></tr></table>

**Comment by mkoeppe** [comment]
Removed branch from issue description, it is replaced by PR #34962
