### ISSUE TITLE
diff(jacobi_dn(x,k),x,1) returns a wrong result

### ISSUE THREAD

**Issue by mignonph75** [sagemath/sage#34884]
<div id="comment:0"></div>

−𝑘cn(𝑥|𝑘)sn(𝑥|𝑘) instead of −𝑘𝑘cn(𝑥|𝑘)sn(𝑥|𝑘)

see Abramowitz et Stegun, page 574, Table 16.16 Derivatives

Component: **calculus**

Reviewer: **Martin Rubey**

_Issue created by migration from https://trac.sagemath.org/ticket/34884_

**Comment by fchapoton** [comment]
<div id="comment:1" align="right">comment:1</div>

this is hardcoded in the file `src/sage/functions/jacobi.py`

should be very easy to fix, and add a doctest

you can easily login with a github account and provide a branch

**Comment by mantepse** [comment]
<div id="comment:2" align="right">comment:2</div>

If I recall correctly, fricas does the same. Strange.

**Comment by mignonph75** [comment]
<div id="comment:3" align="right">comment:3</div>

I would fix it like this

replace m by m * m in line 398 of src/sage/functions/jacobi.py :

```
397            elif self.kind == 'dn':
398               return -m * jacobi_sn(x, m) * jacobi_cn(x, m)
```

I do not know how to add a doctest.

**Comment by mantepse** [comment]
<div id="comment:4" align="right">comment:4</div>

Could you please explain?  In the reference you give, https://personal.math.ubc.ca/~cbm/aands/page_574.htm, I find in table 16.16.3

```
-m sn u cn u
```
Is there a translation of notation I do not understand? Is the derivative of `jacobi_nd` correct?

**Comment by mignonph75** [comment]
<div id="comment:5" align="right">comment:5</div>

m stands for k*k.

If I correct the dn elliptic jacobi function first derivative, sn elliptic jacobi function satisfies the 2nd order ODE :

```
(-((k**2*(1-jacobi('sn',x,k)**2)+1-k**2*jacobi('sn',x,k)**2))*jacobi('sn',x,k)\
+(1+k**2)*jacobi_sn(x,k)-2*k**2*jacobi_sn(x,k)**3).expand().factor()
```

first line being the corrected 2nd derivative of sn  elliptic jacobi.

same issue with diff(jacobi('nd',x,k),x,1) = 𝑘cd(𝑥|𝑘)sd(𝑥|𝑘)

**Comment by mignonph75** [comment]
<div id="comment:6" align="right">comment:6</div>

so line 498 of  src/sage/functions/jacobi.py        

```
 return m * jacobi_cd(x, m) * jacobi_sd(x, m) 
```

should be fixed in the same way as line 398

**Comment by mantepse** [comment]
<div id="comment:7" align="right">comment:7</div>

But isn't [SageMath](../wiki/SageMath) (and FriCAS) using the convention, that the second argument is `m` (rather than `k`)?

**Comment by mignonph75** [comment]
<div id="comment:8" align="right">comment:8</div>

Martin Rubey is right !

Sorry for my bad understanding of [SageMath](../wiki/SageMath) convention.

**Comment by mignonph75** [comment]
<div id="comment:9" align="right">comment:9</div>

This ticket can be closed.

**Comment by mantepse** [comment]
Reviewer: **Martin Rubey**
