### ISSUE TITLE
allow to remove no constraints

### ISSUE THREAD

**Issue by mantepse** [sagemath/sage#34881]
<div id="comment:0"></div>

Removing no constraint makes sage glpk currently crash, which we fix here.

CC:  @mkoeppe

Component: **linear programming**

Author: **Martin Rubey**

Branch/Commit: **[`b03cf22`](https://github.com/sagemath/sagetrac-mirror/commit/b03cf22dc0abc3e76566e7975fb94d5a08d11450)**

Reviewer: **Matthias Koeppe**

_Issue created by migration from https://trac.sagemath.org/ticket/34881_

**Comment by mantepse** [comment]
Branch: **[u/mantepse/allow_to_remove_no_constraints](https://github.com/sagemath/sagetrac-mirror/tree/u/mantepse/allow_to_remove_no_constraints)**

**Comment by mantepse** [comment]
<div id="comment:2"></div>

New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/b03cf22dc0abc3e76566e7975fb94d5a08d11450"><code>b03cf22</code></a></td><td><code>take care of the corner case for all backends in the frontend</code></td></tr></table>

**Comment by mantepse** [comment]
Description changed:
``````diff
--- 
+++ 
@@ -1 +1 @@
-
+Removing no constraint makes sage glpk currently crash, which we fix here.
``````

**Comment by mantepse** [comment]
Commit: **[`b03cf22`](https://github.com/sagemath/sagetrac-mirror/commit/b03cf22dc0abc3e76566e7975fb94d5a08d11450)**

**Comment by mantepse** [comment]
Author: **Martin Rubey**

**Comment by mkoeppe** [comment]
Reviewer: **Matthias Koeppe**

**Comment by vbraun** [comment]
Changed branch from **[u/mantepse/allow_to_remove_no_constraints](https://github.com/sagemath/sagetrac-mirror/tree/u/mantepse/allow_to_remove_no_constraints)** to **[`b03cf22`](https://github.com/sagemath/sagetrac-mirror/commit/b03cf22dc0abc3e76566e7975fb94d5a08d11450)**
