### ISSUE TITLE
fix E714 in pyx files outside of matrix/

### ISSUE THREAD

**Issue by fchapoton** [sagemath/sage#34895]
<div id="comment:0"></div>

 E714 test for object identity should be 'is not'

Component: **refactoring**

Author: **Frédéric Chapoton**

Branch/Commit: **[`fc00ba2`](https://github.com/sagemath/sagetrac-mirror/commit/fc00ba2d2705e3a188d819397599426715932d0a)**

Reviewer: **David Coudert**

_Issue created by migration from https://trac.sagemath.org/ticket/34895_

**Comment by fchapoton** [comment]
Commit: **[`fc00ba2`](https://github.com/sagemath/sagetrac-mirror/commit/fc00ba2d2705e3a188d819397599426715932d0a)**

**Comment by fchapoton** [comment]
<div id="comment:1"></div>

New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/fc00ba2d2705e3a188d819397599426715932d0a"><code>fc00ba2</code></a></td><td><code>fix E714 in pyx files outside of matrix/</code></td></tr></table>

**Comment by fchapoton** [comment]
Branch: **[u/chapoton/34895](https://github.com/sagemath/sagetrac-mirror/tree/u/chapoton/34895)**

**Comment by dcoudert** [comment]
Reviewer: **David Coudert**

**Comment by dcoudert** [comment]
<div id="comment:2" align="right">comment:2</div>

LGTM.

The error reported by the patchbot about a deprecation number has nothing to do with this ticket.

**Comment by fchapoton** [comment]
<div id="comment:3" align="right">comment:3</div>

merci et bonne année

**Comment by vbraun** [comment]
Changed branch from **[u/chapoton/34895](https://github.com/sagemath/sagetrac-mirror/tree/u/chapoton/34895)** to **[`fc00ba2`](https://github.com/sagemath/sagetrac-mirror/commit/fc00ba2d2705e3a188d819397599426715932d0a)**
