### ISSUE TITLE
fixing some E502 in tensor, dynamics, modules, plot, numerical

### ISSUE THREAD

**Issue by fchapoton** [sagemath/sage#34891]
<div id="comment:0"></div>

E502 the backslash is redundant between brackets

Depends on #34839

Component: **refactoring**

Author: **Frédéric Chapoton**

Branch/Commit: **[`4bc07ec`](https://github.com/sagemath/sagetrac-mirror/commit/4bc07ec05f42f56681d89a9e31610270d3b0aa96)**

Reviewer: **Matthias Koeppe**

_Issue created by migration from https://trac.sagemath.org/ticket/34891_

**Comment by fchapoton** [comment]
<div id="comment:1"></div>

New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/fc8eecf9f2d02fc0d6459f5949c6610d820cc996"><code>fc8eecf</code></a></td><td><code>fixing some E502 in tensor, dynamics, modules, plot, numerical</code></td></tr></table>

**Comment by fchapoton** [comment]
Commit: **[`fc8eecf`](https://github.com/sagemath/sagetrac-mirror/commit/fc8eecf9f2d02fc0d6459f5949c6610d820cc996)**

**Comment by fchapoton** [comment]
Branch: **[u/chapoton/34891](https://github.com/sagemath/sagetrac-mirror/tree/u/chapoton/34891)**

**Comment by mkoeppe** [comment]
<div id="comment:2" align="right">comment:2</div>

Consider merging #34839 so that the linter runs

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
<div id="comment:3"></div>

Branch pushed to git repo; I updated commit sha1. New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/d302a628936a965d4e5c3501b7989028274fac95"><code>d302a62</code></a></td><td><code>tox.ini, src/tox.ini: Adjust to tox 4, autoprovision tox >= 3.18</code></td></tr><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/f8703aeba13b8663e55b46494dec4fd305e65374"><code>f8703ae</code></a></td><td><code>.github/workflows/lint.yml: Invoke tox with --</code></td></tr><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/9d76204fb5801054755b2e7bc54aeb6743742ced"><code>9d76204</code></a></td><td><code>fix some rst issues in sage_docbuild and sage_setup</code></td></tr><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/70da140f5f430c1cab53a858a8b33d43d23baf1e"><code>70da140</code></a></td><td><code>Merge branch 'u/chapoton/support_tox_4' in 9.8.b6</code></td></tr><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/4bc07ec05f42f56681d89a9e31610270d3b0aa96"><code>4bc07ec</code></a></td><td><code>Merge branch 'u/chapoton/support_tox_4' into branch fixing E502</code></td></tr></table>

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
Changed commit from **[`fc8eecf`](https://github.com/sagemath/sagetrac-mirror/commit/fc8eecf9f2d02fc0d6459f5949c6610d820cc996)** to **[`4bc07ec`](https://github.com/sagemath/sagetrac-mirror/commit/4bc07ec05f42f56681d89a9e31610270d3b0aa96)**

**Comment by fchapoton** [comment]
<div id="comment:4" align="right">comment:4</div>

fixing the linter now also requires #34892

**Comment by mkoeppe** [comment]
Dependencies: **#34839**

**Comment by mkoeppe** [comment]
Reviewer: **Matthias Koeppe**

**Comment by vbraun** [comment]
Changed branch from **[u/chapoton/34891](https://github.com/sagemath/sagetrac-mirror/tree/u/chapoton/34891)** to **[`4bc07ec`](https://github.com/sagemath/sagetrac-mirror/commit/4bc07ec05f42f56681d89a9e31610270d3b0aa96)**
