### ISSUE TITLE
fix and activate pycodestyle E211

### ISSUE THREAD

**Issue by fchapoton** [sagemath/sage#34893]
<div id="comment:0"></div>

this one is about wrong space before opening parentheses:

E211 whitespace before '('

CC:  @tscrim @kwankyu @kliem @slel

Component: **refactoring**

Author: **Frédéric Chapoton**

Branch/Commit: **[`cb605f0`](https://github.com/sagemath/sagetrac-mirror/commit/cb605f0d700bfece3b4c836e6628f6a7c37b0690)**

Reviewer: **Martin Rubey**

_Issue created by migration from https://trac.sagemath.org/ticket/34893_

**Comment by fchapoton** [comment]
Branch: **[u/chapoton/34893](https://github.com/sagemath/sagetrac-mirror/tree/u/chapoton/34893)**

**Comment by fchapoton** [comment]
<div id="comment:1"></div>

New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/cda2f185fc04c0be3535a74ea8526a4b308972c8"><code>cda2f18</code></a></td><td><code>fix and activate E211</code></td></tr></table>

**Comment by fchapoton** [comment]
Commit: **[`cda2f18`](https://github.com/sagemath/sagetrac-mirror/commit/cda2f185fc04c0be3535a74ea8526a4b308972c8)**

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
<div id="comment:2"></div>

Branch pushed to git repo; I updated commit sha1. New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/7e528022e94041b67fceb922d16ed222db960cab"><code>7e52802</code></a></td><td><code>a few more pycodestyle fixes</code></td></tr></table>

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
Changed commit from **[`cda2f18`](https://github.com/sagemath/sagetrac-mirror/commit/cda2f185fc04c0be3535a74ea8526a4b308972c8)** to **[`7e52802`](https://github.com/sagemath/sagetrac-mirror/commit/7e528022e94041b67fceb922d16ed222db960cab)**

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
Changed commit from **[`7e52802`](https://github.com/sagemath/sagetrac-mirror/commit/7e528022e94041b67fceb922d16ed222db960cab)** to **[`5b88def`](https://github.com/sagemath/sagetrac-mirror/commit/5b88def806184e3736c9ec70b6eecbbb9af896e4)**

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
<div id="comment:3"></div>

Branch pushed to git repo; I updated commit sha1. This was a forced push. New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/5b88def806184e3736c9ec70b6eecbbb9af896e4"><code>5b88def</code></a></td><td><code>fix and activate E211</code></td></tr></table>

**Comment by fchapoton** [comment]
<div id="comment:4" align="right">comment:4</div>

green lights, so please review

**Comment by mantepse** [comment]
Reviewer: **Martin Rubey**

**Comment by mantepse** [comment]
<div id="comment:6" align="right">comment:6</div>

Thank you!

**Comment by vbraun** [comment]
<div id="comment:7" align="right">comment:7</div>

Merge failure on top of:

6defd0c273f Trac #34858: Fix sagemath-standard sdist

ab738d787b4 Trac #34635: Add tensor_factors() method to TensorProductOfHighestWeightModules in quantum_group_gap

0a9fb8c70f6 Trac #34581: Implement substitution in InfinitePolynomialRing

5c524cc8026 Trac #31668: Run TestSuite on polynomial rings

33cea587439 Trac #23712: Upgrade to Tachyon 0.99.5

a84dd73208c Trac #22067: generating function of integral points of polyhedra

158fb3eb005 Trac #21003: Add package pyscipopt, add MIP backend

931f19903b3 Trac #34838: setuptools_scm, contourpy, sphinxcontrib_websupport, typing_extensions: Add missing dependencies

9dc103a555c Trac #34537: Upgrade to pari 2.15.2

30d58156a46 Trac #34717: Check the presence of lrsnash for obtain_nash()

c7299453922 Trac #34891: fixing some E502 in tensor, dynamics, modules, plot, numerical

bc832cb3578 Trac #34889: Installation guide: On WSL, clear /mnt/c stuff from PATH

3570a9a63bd Trac #34881: allow to remove no constraints

0ceb1032430 Trac #34878: MixedIntegerLinearProgram.add_constraint: Option to return row indices, fix handling of empty constraints

df74efb66d2 Trac #34859: sagelib: Remove unnecessary import of typing_extensions

b6a76d7a848 Trac #34857: bump giac's GIAC_MIN_VERSION to 1.9

6a8155e6e5d Trac #34854: molien_series() should not use GAP's VirtualCharacter

dddf3ca0b08 Trac #34853: sage-env: Fix misconfiguration of pip

6f631021ac4 Trac #34847: modernize some for loops in cython files

9ffabc7f3e1 Trac #34844: removal of some unused imports about string conversion

4b50bc2af27 Trac #34843: pep8 cleanup in ore_polynomial_element.pyx

bdd14cec19b Trac #34837: fix E502 in some pyx files

172ad73ae38 Trac #34836: fix E271 and E272 in rings/ and schemes/

3d861266040 Trac #34749: Packages dsdp, scip_sdp

64d232b5bfd Trac #31329: Update scipoptsuite to 8.0.2 (now open source!), rename to scip

2dcafb3ac57 Trac #34839: Support tox 4

ad68f15d97f Trac #34648: Developer's guide: warn the transition to [GitHub](../wiki/GitHub) and add links to the transition guide

acebbc1a9e8 Trac #34824: do not include parent in hash of parking functions

9a7b6310dde Trac #34818: Error when defining differentials over GCA's with relations.

bb63c582122 Trac #34807: Add Construction of Hadamard matrices up to order 664

8a0b16d93be Trac #34804: Deprecate sage.interfaces is_...Element functions

80f8f950e95 Trac #34793: clean 3 files inside modular

b0cc282500e Trac #34547: Interfaces: use more lazy imports, restore top-level functions maxima_console etc.

5905da7ebfc Trac #33915: inseparable elliptic-curve isogenies

98b22ebdcf7 Trac #32826: scalar-multiplication endomorphisms of elliptic curves

4f11a750df9 Trac #8744: Improve add_edge in BipartiteGraph to make it independent from the current coloring

08aa2f8edaa Trac #33842: Upgrade python to 3.11

75bedf95960 Trac #34783: various details in combinat/

33fa8715bd5 Trac #34742: Optional package soplex (dependency of scip)

f84915f69d8 Trac #34726: Optional package papilo (dependency of scip)

e5cf1c0d9f2 Trac #34694: Bug in ExteriorAlgebra interior product

ebb9b611d02 Trac #34416: Manage pexpect logs created during doctesting

962177a2da1 Trac #33907: interfaces/expect.py random test failure

66409243991 Trac #16522: lazy_import doesn't resolve properly when indirectly imported

2114066f877 Updated [SageMath](../wiki/SageMath) version to 9.8.beta6



merge was not clean: conflicts in src/sage/combinat/root_system/cartan_type.py

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
Changed commit from **[`5b88def`](https://github.com/sagemath/sagetrac-mirror/commit/5b88def806184e3736c9ec70b6eecbbb9af896e4)** to **[`cb605f0`](https://github.com/sagemath/sagetrac-mirror/commit/cb605f0d700bfece3b4c836e6628f6a7c37b0690)**

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
<div id="comment:8"></div>

Branch pushed to git repo; I updated commit sha1. New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/cb605f0d700bfece3b4c836e6628f6a7c37b0690"><code>cb605f0</code></a></td><td><code>Merge branch 'u/chapoton/34893' in 9.8.beta7</code></td></tr></table>

**Comment by fchapoton** [comment]
<div id="comment:9" align="right">comment:9</div>

setting back to positive after trivial rebase

**Comment by vbraun** [comment]
Changed branch from **[u/chapoton/34893](https://github.com/sagemath/sagetrac-mirror/tree/u/chapoton/34893)** to **[`cb605f0`](https://github.com/sagemath/sagetrac-mirror/commit/cb605f0d700bfece3b4c836e6628f6a7c37b0690)**
