### ISSUE TITLE
Fixing the linter (again)

### ISSUE THREAD

**Issue by fchapoton** [sagemath/sage#34892]
<div id="comment:0"></div>

by removing all trailing whitespaces recently introduced

Depends on #34839

CC:  @MatteoCati @mkoeppe

Component: **refactoring**

Author: **Frédéric Chapoton**

Branch/Commit: **[`c41e4d7`](https://github.com/sagemath/sagetrac-mirror/commit/c41e4d78f268671ce9dcd533f811ba7ffe710109)**

Reviewer: **Matthias Koeppe**

_Issue created by migration from https://trac.sagemath.org/ticket/34892_

**Comment by fchapoton** [comment]
Branch: **[u/chapoton/34892](https://github.com/sagemath/sagetrac-mirror/tree/u/chapoton/34892)**

**Comment by fchapoton** [comment]
<div id="comment:1"></div>

New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/7b4aa1c7cf2557eb1a858535cab72824f087cc10"><code>7b4aa1c</code></a></td><td><code>full pep8 fix for t-sequences</code></td></tr></table>

**Comment by fchapoton** [comment]
Commit: **[`7b4aa1c`](https://github.com/sagemath/sagetrac-mirror/commit/7b4aa1c7cf2557eb1a858535cab72824f087cc10)**

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
<div id="comment:2"></div>

Branch pushed to git repo; I updated commit sha1. New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/d302a628936a965d4e5c3501b7989028274fac95"><code>d302a62</code></a></td><td><code>tox.ini, src/tox.ini: Adjust to tox 4, autoprovision tox >= 3.18</code></td></tr><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/f8703aeba13b8663e55b46494dec4fd305e65374"><code>f8703ae</code></a></td><td><code>.github/workflows/lint.yml: Invoke tox with --</code></td></tr><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/9d76204fb5801054755b2e7bc54aeb6743742ced"><code>9d76204</code></a></td><td><code>fix some rst issues in sage_docbuild and sage_setup</code></td></tr><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/70da140f5f430c1cab53a858a8b33d43d23baf1e"><code>70da140</code></a></td><td><code>Merge branch 'u/chapoton/support_tox_4' in 9.8.b6</code></td></tr><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/228070138396fd1f680c758bfeab58e1d19b66a2"><code>2280701</code></a></td><td><code>Merge branch 'u/chapoton/support_tox_4' into branch fixing pep8 in t_sequences</code></td></tr></table>

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
Changed commit from **[`7b4aa1c`](https://github.com/sagemath/sagetrac-mirror/commit/7b4aa1c7cf2557eb1a858535cab72824f087cc10)** to **[`2280701`](https://github.com/sagemath/sagetrac-mirror/commit/228070138396fd1f680c758bfeab58e1d19b66a2)**

**Comment by fchapoton** [comment]
<div id="comment:3" align="right">comment:3</div>

and the linter is green again (sigh)

**Comment by mkoeppe** [comment]
Dependencies: **#34839**

**Comment by mkoeppe** [comment]
Reviewer: **Matthias Koeppe**

**Comment by vbraun** [comment]
<div id="comment:6" align="right">comment:6</div>

Merge failure on top of:

2dcafb3ac57 Trac #34839: Support tox 4

ad68f15d97f Trac #34648: Developer's guide: warn the transition to [GitHub](../wiki/GitHub) and add links to the transition guide

acebbc1a9e8 Trac #34824: do not include parent in hash of parking functions

9a7b6310dde Trac #34818: Error when defining differentials over GCA's with relations.

bb63c582122 Trac #34807: Add Construction of Hadamard matrices up to order 664

8a0b16d93be Trac #34804: Deprecate sage.interfaces is_...Element functions

80f8f950e95 Trac #34793: clean 3 files inside modular

b0cc282500e Trac #34547: Interfaces: use more lazy imports, restore top-level functions maxima_console etc.

5905da7ebfc Trac #33915: inseparable elliptic-curve isogenies

98b22ebdcf7 Trac #32826: scalar-multiplication endomorphisms of elliptic curves

4f11a750df9 Trac #8744: Improve add_edge in BipartiteGraph to make it independent from the current coloring

08aa2f8edaa Trac #33842: Upgrade python to 3.11

75bedf95960 Trac #34783: various details in combinat/

33fa8715bd5 Trac #34742: Optional package soplex (dependency of scip)

f84915f69d8 Trac #34726: Optional package papilo (dependency of scip)

e5cf1c0d9f2 Trac #34694: Bug in ExteriorAlgebra interior product

ebb9b611d02 Trac #34416: Manage pexpect logs created during doctesting

962177a2da1 Trac #33907: interfaces/expect.py random test failure

66409243991 Trac #16522: lazy_import doesn't resolve properly when indirectly imported

2114066f877 Updated [SageMath](../wiki/SageMath) version to 9.8.beta6



merge was not clean: conflicts in src/sage/combinat/t_sequences.py

**Comment by fchapoton** [comment]
<div id="comment:7" align="right">comment:7</div>

merge failure due to #34807

**Comment by fchapoton** [comment]
<div id="comment:8" align="right">comment:8</div>

now waiting for the next release to make a new branch just removing the whitespaces

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
<div id="comment:9"></div>

Branch pushed to git repo; I updated commit sha1. This was a forced push. New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/c41e4d78f268671ce9dcd533f811ba7ffe710109"><code>c41e4d7</code></a></td><td><code>fixing the linter again</code></td></tr></table>

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
Changed commit from **[`2280701`](https://github.com/sagemath/sagetrac-mirror/commit/228070138396fd1f680c758bfeab58e1d19b66a2)** to **[`c41e4d7`](https://github.com/sagemath/sagetrac-mirror/commit/c41e4d78f268671ce9dcd533f811ba7ffe710109)**

**Comment by fchapoton** [comment]
Description changed:
``````diff
--- 
+++ 
@@ -1 +1 @@
-including all trailing whitespaces that would break the linter
+by removing all trailing whitespaces recently introduced
``````

**Comment by fchapoton** [comment]
<div id="comment:10" align="right">comment:10</div>

please review swiftly and merge asap

**Comment by vbraun** [comment]
Changed branch from **[u/chapoton/34892](https://github.com/sagemath/sagetrac-mirror/tree/u/chapoton/34892)** to **[`c41e4d7`](https://github.com/sagemath/sagetrac-mirror/commit/c41e4d78f268671ce9dcd533f811ba7ffe710109)**
