### ISSUE TITLE
some details about min and max

### ISSUE THREAD

**Issue by fchapoton** [sagemath/sage#34898]
<div id="comment:0"></div>

in particular using iterators inside and the default argument

CC:  @tscrim @slel @kwankyu @kliem

Component: **combinatorics**

Author: **Frédéric Chapoton**

Branch/Commit: **[`6044f16`](https://github.com/sagemath/sagetrac-mirror/commit/6044f164942dd17f7f1a26949b128c581ed238a4)**

Reviewer: **Travis Scrimshaw**

_Issue created by migration from https://trac.sagemath.org/ticket/34898_

**Comment by fchapoton** [comment]
Commit: **[`6044f16`](https://github.com/sagemath/sagetrac-mirror/commit/6044f164942dd17f7f1a26949b128c581ed238a4)**

**Comment by fchapoton** [comment]
<div id="comment:1"></div>

New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/6044f164942dd17f7f1a26949b128c581ed238a4"><code>6044f16</code></a></td><td><code>some details about min and max (using the default argument)</code></td></tr></table>

**Comment by fchapoton** [comment]
Branch: **[u/chapoton/34898](https://github.com/sagemath/sagetrac-mirror/tree/u/chapoton/34898)**

**Comment by fchapoton** [comment]
<div id="comment:2" align="right">comment:2</div>

green lights, so please review

**Comment by tscrim** [comment]
<div id="comment:3" align="right">comment:3</div>

LGTM.

**Comment by tscrim** [comment]
Reviewer: **Travis Scrimshaw**

**Comment by vbraun** [comment]
Changed branch from **[u/chapoton/34898](https://github.com/sagemath/sagetrac-mirror/tree/u/chapoton/34898)** to **[`6044f16`](https://github.com/sagemath/sagetrac-mirror/commit/6044f164942dd17f7f1a26949b128c581ed238a4)**
