### ISSUE TITLE
SCIPBackend: Faster copy, remove_constraint methods

### ISSUE THREAD

**Issue by mkoeppe** [sagemath/sage#34890]
<div id="comment:0"></div>

(from [#21003 comment:142](https://github.com/sagemath/sage/issues/21003#comment:142))

Depends on #21003

CC:  @mantepse @dimpase

Component: **linear programming**

Author: **Matthias Koeppe**

Reviewer: **Martin Rubey, ...**

_Issue created by migration from https://trac.sagemath.org/ticket/34890_

**Comment by mkoeppe** [comment]
Description changed:
``````diff
--- 
+++ 
@@ -1 +1 @@
-
+(from [#21003 comment:142](https://github.com/sagemath/sage/issues/21003#comment:142))
``````

**Comment by mkoeppe** [comment]
Author: **Matthias Koeppe**

**Comment by mkoeppe** [comment]
Branch: **[u/mkoeppe/scipbackend__faster_copy_method](https://github.com/sagemath/sagetrac-mirror/tree/u/mkoeppe/scipbackend__faster_copy_method)**

**Comment by mkoeppe** [comment]
<div id="comment:4"></div>

Last 10 new commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/b33be2612efe5ea5118cefa3e04c3d74766a6ca0"><code>b33be26</code></a></td><td><code>src/sage/graphs/graph_decompositions/vertex_separation.pyx: Factor out _vertex_separation_MILP_formulation</code></td></tr><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/4104322c5a99e4180444e71c705d1c99b379586d"><code>4104322</code></a></td><td><code>src/sage/numerical/backends/scip_backend.pyx: Store pyscipopt variables by index</code></td></tr><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/fe72aa5b094e22ba699f3492f8367bd9a93cbf1a"><code>fe72aa5</code></a></td><td><code>src/sage/graphs/graph_decompositions/vertex_separation.pyx: Add pyscipopt test</code></td></tr><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/b6242d23733b285b74030400e8f210d67a4c1644"><code>b6242d2</code></a></td><td><code>src/sage/numerical/backends/scip_backend.pyx: Mark sage.doctest: optional - pyscipopt</code></td></tr><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/7b19413f24c152afb52469871df0abca6d7c9a8f"><code>7b19413</code></a></td><td><code>src/sage/numerical/backends/scip_backend.pyx: Fix docstring blocks, break some long lines</code></td></tr><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/01d4cdc3cb057a9f06ab869945b0a14c6b149572"><code>01d4cdc</code></a></td><td><code>Merge tag '9.8.beta6' into t/21003/pyscipopt</code></td></tr><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/2040546c48830f892056475f32ec6a1aa5afe90c"><code>2040546</code></a></td><td><code>src/sage/numerical/backends/scip_backend.pyx: Fix copying variable types</code></td></tr><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/099c15ba7adede06fa50d7c09baa87c31b25725a"><code>099c15b</code></a></td><td><code>src/sage/numerical/backends/scip_backend.pyx: Cache constraints to avoid expensive calls to getConss</code></td></tr><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/48cf10490a3b45021d37a3b4aeedb9a9080d4eb7"><code>48cf104</code></a></td><td><code>Merge #21003</code></td></tr><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/953198edc1e256698068cbc8e63c9d6f973abe31"><code>953198e</code></a></td><td><code>SCIPBackend.__copy__: Use Model(sourceModel=...) for copying</code></td></tr></table>

**Comment by mkoeppe** [comment]
Commit: **[`953198e`](https://github.com/sagemath/sagetrac-mirror/commit/953198edc1e256698068cbc8e63c9d6f973abe31)**

**Comment by mkoeppe** [comment]
<div id="comment:5" align="right">comment:5</div>

Just 1 commit on top of #21003

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
Changed commit from **[`953198e`](https://github.com/sagemath/sagetrac-mirror/commit/953198edc1e256698068cbc8e63c9d6f973abe31)** to **[`81ea51c`](https://github.com/sagemath/sagetrac-mirror/commit/81ea51ce8ca5724631801133549d02b77aa99dc4)**

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
<div id="comment:7"></div>

Branch pushed to git repo; I updated commit sha1. New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/89e5778d3925db21fd7176d5aa6c334f5aa70b04"><code>89e5778</code></a></td><td><code>GenericBackend.remove_constraints: Fix handling of int</code></td></tr><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/38a33e0c91374b121567da228e7cde424148f992"><code>38a33e0</code></a></td><td><code>SCIPBackend.nrows: Use model.getNConss if constraints are not cached</code></td></tr><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/81ea51ce8ca5724631801133549d02b77aa99dc4"><code>81ea51c</code></a></td><td><code>SCIPBackend.remove_constraints: New, override generic implementation</code></td></tr></table>

**Comment by mantepse** [comment]
<div id="comment:9" align="right">comment:9</div>

When creating a constraint, then copying the MILP, and then adding the constraint to the copied MILP, I sometimes get errors as follows:

```
      File "/home/martin/sage-develop/src/sage/combinat/bijectionist.py", line 1956, in _find_counter_example
        solution = next(bmilp.solutions_iterator(on_blocks, tmp_constraints))
      File "/home/martin/sage-develop/src/sage/combinat/bijectionist.py", line 2676, in solutions_iterator
        bmilp.add_constraint(constraint, return_indices=True)
      File "sage/numerical/mip.pyx", line 2199, in sage.numerical.mip.MixedIntegerLinearProgram.add_constraint
        new_indices = self.add_constraint(lhs-rhs, max=0,
      File "sage/numerical/mip.pyx", line 2175, in sage.numerical.mip.MixedIntegerLinearProgram.add_constraint
        self._backend.add_linear_constraint(constraint.items(), min, max, name)
      File "sage/numerical/backends/scip_backend.pyx", line 410, in sage.numerical.backends.scip_backend.SCIPBackend.add_linear_constraint
        linfun = quicksum([v * mvars[c] for c, v in coefficients])
    IndexError: list index out of range
```

Maybe something like `copy_for_mip` is needed also for constraints?

**Comment by mkoeppe** [comment]
<div id="comment:10" align="right">comment:10</div>

are you passing `tmp_constraints` coming from one MIP to another?

**Comment by mantepse** [comment]
<div id="comment:11" align="right">comment:11</div>

yes, as I wrote.

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
Changed commit from **[`81ea51c`](https://github.com/sagemath/sagetrac-mirror/commit/81ea51ce8ca5724631801133549d02b77aa99dc4)** to **[`5e6ad56`](https://github.com/sagemath/sagetrac-mirror/commit/5e6ad5605b292b5977c50cf33fd664e905511931)**

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
<div id="comment:12"></div>

Branch pushed to git repo; I updated commit sha1. New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/5e6ad5605b292b5977c50cf33fd664e905511931"><code>5e6ad56</code></a></td><td><code>SCIPBackend.__copy__: Use origcopy=True</code></td></tr></table>

**Comment by mkoeppe** [comment]
<div id="comment:13" align="right">comment:13</div>

Please check if this fixes it

**Comment by mantepse** [comment]
<div id="comment:14" align="right">comment:14</div>

Yes, this makes it look good.

**Comment by mkoeppe** [comment]
<div id="comment:15" align="right">comment:15</div>

Thanks for testing!

**Comment by mantepse** [comment]
Reviewer: **Martin Rubey, ...**

**Comment by mantepse** [comment]
<div id="comment:17" align="right">comment:17</div>

I think I should mention that copying is still a bit slower than adding and removing constraints, apparently, no matter whether I use SCIP or GLPK.  

However, it seems that this is only relevant for extremely small problems, usually almost all time is spent in the solver itself.  

Running all tests with SCIP without copying takes about 4.2 seconds, with copying it is about 4.9 seconds.  Including the long tests, I get about 56 seconds either way.

(GLPK: with and without copying 2.4 seconds, including long tests 73 seconds)

Besides, it might make sense to have a method `add_constraints`, analogous to `remove_constraints`, this would save another 2 lines of code :-)

**Comment by mkoeppe** [comment]
<div id="comment:18" align="right">comment:18</div>

Thanks for these benchmarks with #33238. These timings suggest that we have been successful in removing the artificial slowdowns in `remove_constraints`.

Not sure about `add_constraints`. As `add_constraint` already accepts vector-valued constraints (via `LinearTensor`, `LinearTensorConstraint`), perhaps it could just be generalized to also accept lists in such places.

**Comment by mantepse** [comment]
<div id="comment:19" align="right">comment:19</div>

Is there any real difference between vector valued constraints and lists of constraints?

**Comment by mkoeppe** [comment]
<div id="comment:20" align="right">comment:20</div>

No. In the end, everything is a matrix

**Comment by mantepse** [comment]
<div id="comment:21" align="right">comment:21</div>

OK.  In any case, it is confusing that we have two methods for removing constraints but only one to add constraints.

**Comment by mkoeppe** [comment]
<div id="comment:22" align="right">comment:22</div>

We could introduce `add_constraints` as an alias of `add_constraint` after extending the accepted inputs as per [comment:18](#comment%3A18)

**Comment by mantepse** [comment]
<div id="comment:23" align="right">comment:23</div>

I guess, for `remove_constraints` you have done this already?

**Comment by mkoeppe** [comment]
<div id="comment:24" align="right">comment:24</div>

No, here on the ticket this is a fix for the backend method `remove_constraints`.

**Comment by mkoeppe** [comment]
<div id="comment:25" align="right">comment:25</div>

I've opened #34896 for these changes to the frontend

**Comment by mkoeppe** [comment]
Removed branch from issue description; replaced by PR #35103
