### ISSUE TITLE
LatticePoset breadth, error in documentation

### ISSUE THREAD

**Issue by f29946bc-ee7b-48cd-9abc-3445948c551d** [sagemath/sage#34902]
<div id="comment:0"></div>

I got a mail about my posting in year 2017: "However, I read Stephan's paper differently: He states that breadth k is equivalent  to containing a Boolean lattice with k atoms (but none with k+1 atoms) as a subORDER, and then states in his Lemma 1 that in the case k=3 this is the same as subLATTICE."

Hence documentation of `breadth()` in `LatticePoset` containing

This can be also characterized by sublattices: a lattice of breadth at least `$n$` contains a sublattice isomorphic to the Boolean lattice of `$2^n$` elements.

must be changed to

This can be also characterized by subposets: a lattice of breadth at least `$n$` contains a subposet isomorphic to the Boolean lattice of `$2^n$` elements.

Component: **combinatorics**

Keywords: **latticeposet**

Author: **Frédéric Chapoton**

Branch/Commit: **[u/chapoton/34902](https://github.com/sagemath/sagetrac-mirror/tree/u/chapoton/34902) @ [`26d7ced`](https://github.com/sagemath/sagetrac-mirror/commit/26d7ceda4f3d4bf30ed3f788083a0556d0e27c59)**

Reviewer: **Jori Mäntysalo**

_Issue created by migration from https://trac.sagemath.org/ticket/34902_

**Comment by fchapoton** [comment]
<div id="comment:1" align="right">comment:1</div>

Hello Jori, Happy New Year. Nice to see you back.

I have made the change, is it ok ?

---
New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/26d7ceda4f3d4bf30ed3f788083a0556d0e27c59"><code>26d7ced</code></a></td><td><code>fix doc in lattice</code></td></tr></table>

**Comment by fchapoton** [comment]
Commit: **[`26d7ced`](https://github.com/sagemath/sagetrac-mirror/commit/26d7ceda4f3d4bf30ed3f788083a0556d0e27c59)**

**Comment by fchapoton** [comment]
Author: **Frédéric Chapoton**

**Comment by fchapoton** [comment]
Branch: **[u/chapoton/34902](https://github.com/sagemath/sagetrac-mirror/tree/u/chapoton/34902)**

**Comment by f29946bc-ee7b-48cd-9abc-3445948c551d** [comment]
<div id="comment:2" align="right">comment:2</div>

Well, not really back; just a note of this, as this was my mistake years ago.

And yes, the patch is good.

**Comment by mkoeppe** [comment]
Reviewer: **Jori Mäntysalo**

**Comment by mkoeppe** [comment]
Merged in 10.0.beta0
