### ISSUE TITLE
create an optional package for kissat SAT solver

### ISSUE THREAD

**Issue by seblabbe** [sagemath/sage#34909]
<div id="comment:0"></div>

http://fmv.jku.at/kissat/

More precisely, version 3.0.0 available at https://github.com/arminbiere/kissat/archive/refs/tags/rel-3.0.0.tar.gz

Component: **packages: optional**

Author: **Sébastien Labbé, Matthias Koeppe**

Branch/Commit: **[`c02693d`](https://github.com/sagemath/sagetrac-mirror/commit/c02693d57f380d649cda15d46a9d53c566523025)**

Reviewer: **Matthias Koeppe, Sébastien Labbé**

_Issue created by migration from https://trac.sagemath.org/ticket/34909_

**Comment by seblabbe** [comment]
<div id="comment:1" align="right">comment:1</div>

Initial version

---
New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/d52caac65a1fcd3173a611ba6dc658a49bb1f15c"><code>d52caac</code></a></td><td><code>KISSAT 3.0.0: initial version for this optional package</code></td></tr></table>

**Comment by seblabbe** [comment]
Commit: **[`d52caac`](https://github.com/sagemath/sagetrac-mirror/commit/d52caac65a1fcd3173a611ba6dc658a49bb1f15c)**

**Comment by seblabbe** [comment]
Branch: **[u/slabbe/34909](https://github.com/sagemath/sagetrac-mirror/tree/u/slabbe/34909)**

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
<div id="comment:2"></div>

Branch pushed to git repo; I updated commit sha1. This was a forced push. New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/852c151028c49bca6ed0bd1a09ee90d8474f7bbc"><code>852c151</code></a></td><td><code>KISSAT 3.0.0: initial version for this optional package</code></td></tr></table>

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
Changed commit from **[`d52caac`](https://github.com/sagemath/sagetrac-mirror/commit/d52caac65a1fcd3173a611ba6dc658a49bb1f15c)** to **[`852c151`](https://github.com/sagemath/sagetrac-mirror/commit/852c151028c49bca6ed0bd1a09ee90d8474f7bbc)**

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
<div id="comment:3"></div>

Branch pushed to git repo; I updated commit sha1. This was a forced push. New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/bbb6d28e34fbd5b891f66a9d04aed90eea408c75"><code>bbb6d28</code></a></td><td><code>KISSAT 3.0.0: initial version for this optional package</code></td></tr></table>

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
Changed commit from **[`852c151`](https://github.com/sagemath/sagetrac-mirror/commit/852c151028c49bca6ed0bd1a09ee90d8474f7bbc)** to **[`bbb6d28`](https://github.com/sagemath/sagetrac-mirror/commit/bbb6d28e34fbd5b891f66a9d04aed90eea408c75)**

**Comment by seblabbe** [comment]
<div id="comment:4" align="right">comment:4</div>

using [helper function](https://doc.sagemath.org/html/en/developer/packaging.html#section-sdh-helpers) `sdh_configure` cause the following error:

```
[kissat-3.0.0] Configuring kissat-3.0.0
[kissat-3.0.0] configure: error: invalid option '--prefix=/home/slabbe/GitBox/sage/local' (try '-h')
[kissat-3.0.0] configure: error: invalid option '--prefix=/home/slabbe/GitBox/sage/local' (try '-h')
[kissat-3.0.0] *****************************************************************************************************
[kissat-3.0.0] Error configuring kissat-3.0.0
[kissat-3.0.0] *****************************************************************************************************
```

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
<div id="comment:5"></div>

Branch pushed to git repo; I updated commit sha1. New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/665a48c12da3acb6e1f6e57905ee2bfaeeb9c376"><code>665a48c</code></a></td><td><code>using ./configure instead of sdh_configure</code></td></tr></table>

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
Changed commit from **[`bbb6d28`](https://github.com/sagemath/sagetrac-mirror/commit/bbb6d28e34fbd5b891f66a9d04aed90eea408c75)** to **[`665a48c`](https://github.com/sagemath/sagetrac-mirror/commit/665a48c12da3acb6e1f6e57905ee2bfaeeb9c376)**

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
<div id="comment:6"></div>

Branch pushed to git repo; I updated commit sha1. New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/bba0024f4ccac1d053d6efb307f052ea6b8f3bbc"><code>bba0024</code></a></td><td><code>using just a spkg-install.in with no spkg-build.in</code></td></tr></table>

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
Changed commit from **[`665a48c`](https://github.com/sagemath/sagetrac-mirror/commit/665a48c12da3acb6e1f6e57905ee2bfaeeb9c376)** to **[`bba0024`](https://github.com/sagemath/sagetrac-mirror/commit/bba0024f4ccac1d053d6efb307f052ea6b8f3bbc)**

**Comment by seblabbe** [comment]
<div id="comment:7" align="right">comment:7</div>

With the current state, installation works:

```
Copying package files from temporary location /home/slabbe/GitBox/sage/local/var/tmp/sage/build/kissat-3.0.0/inst to /home/slabbe/GitBox/sage/local
Successfully installed kissat-3.0.0
Deleting temporary build directory
/home/slabbe/GitBox/sage/local/var/tmp/sage/build/kissat-3.0.0
Finished installing kissat-3.0.0
```
But, then I don't find the command:

```
 $ sage -sh
...
(sage-sh) slabbe@miami:sage$ kissat
bash: kissat : commande introuvable
```

**Comment by mkoeppe** [comment]
<div id="comment:8" align="right">comment:8</div>

The upstream package has a hand-written `configure` script that does not understand the standard option `--prefix`, and the generated Makefile has no target `make install`.

**Comment by mkoeppe** [comment]
Changed branch from **[u/slabbe/34909](https://github.com/sagemath/sagetrac-mirror/tree/u/slabbe/34909)** to **[u/mkoeppe/34909](https://github.com/sagemath/sagetrac-mirror/tree/u/mkoeppe/34909)**

**Comment by mkoeppe** [comment]
Author: **Sébastien Labbé, Matthias Koeppe**

**Comment by mkoeppe** [comment]
Changed commit from **[`bba0024`](https://github.com/sagemath/sagetrac-mirror/commit/bba0024f4ccac1d053d6efb307f052ea6b8f3bbc)** to **[`cea9e49`](https://github.com/sagemath/sagetrac-mirror/commit/cea9e49788f000e08d99646d063cd1c271d9396a)**

**Comment by mkoeppe** [comment]
<div id="comment:10"></div>

New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/12a1839972aac49a2b39537a37fc1c71a7637c4f"><code>12a1839</code></a></td><td><code>KISSAT 3.0.0: initial version for this optional package</code></td></tr><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/279bd4d527cea4a2cde6bc47296a202bf2f30f09"><code>279bd4d</code></a></td><td><code>using ./configure instead of sdh_configure</code></td></tr><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/8262dcd19b6d17d883e23a09a6f058b232ec9f44"><code>8262dcd</code></a></td><td><code>using just a spkg-install.in with no spkg-build.in</code></td></tr><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/ae362016bb9602f847bf600ae603f0aad3ef0f7a"><code>ae36201</code></a></td><td><code>build/pkgs/kissat/SPKG.rst: Fix title format, remove empty section</code></td></tr><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/cea9e49788f000e08d99646d063cd1c271d9396a"><code>cea9e49</code></a></td><td><code>build/pkgs/kissat: Fix scripts</code></td></tr></table>

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
<div id="comment:11"></div>

Branch pushed to git repo; I updated commit sha1. New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/a9913725f7081e7b4c409f54708ecc5f14ea9183"><code>a991372</code></a></td><td><code>build/pkgs/kissat/distros: Add more</code></td></tr></table>

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
Changed commit from **[`cea9e49`](https://github.com/sagemath/sagetrac-mirror/commit/cea9e49788f000e08d99646d063cd1c271d9396a)** to **[`a991372`](https://github.com/sagemath/sagetrac-mirror/commit/a9913725f7081e7b4c409f54708ecc5f14ea9183)**

**Comment by mkoeppe** [comment]
<div id="comment:12" align="right">comment:12</div>

builds, installs, and tests OK on macOS. Have not tried anything else.

**Comment by seblabbe** [comment]
<div id="comment:13" align="right">comment:13</div>

Great! Thanks for fixing the scripts Matthias. I needed help for that. I will test that now, but I first need to update my sage version to the most recent one.

**Comment by seblabbe** [comment]
<div id="comment:14" align="right">comment:14</div>

Did you manage to download the tarbal with the given upstream_url?
Because when we click on the link, it downloads a file named `kissat-rel-3.0.0.tar.gz` and wgetting it downloads `rel-3.0.0.tar.gz`. I think a file starting with `kissat` is better because `rel` I guess means `release`. Maybe we should just delete the upstream_url line?

**Comment by mkoeppe** [comment]
<div id="comment:15" align="right">comment:15</div>

The checksums.ini already handles this correctly.
That's why both `tarball` and `upstream_url` are given.

**Comment by seblabbe** [comment]
<div id="comment:16" align="right">comment:16</div>

Installation works, but during installation I notice the following line:

```
[kissat-3.0.0] mkdir: cannot create directory 'build': File exists
```

**Comment by seblabbe** [comment]
Changed branch from **[u/mkoeppe/34909](https://github.com/sagemath/sagetrac-mirror/tree/u/mkoeppe/34909)** to **[u/slabbe/34909](https://github.com/sagemath/sagetrac-mirror/tree/u/slabbe/34909)**

**Comment by seblabbe** [comment]
Changed commit from **[`a991372`](https://github.com/sagemath/sagetrac-mirror/commit/a9913725f7081e7b4c409f54708ecc5f14ea9183)** to **[`c02693d`](https://github.com/sagemath/sagetrac-mirror/commit/c02693d57f380d649cda15d46a9d53c566523025)**

**Comment by seblabbe** [comment]
<div id="comment:17"></div>

New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/c02693d57f380d649cda15d46a9d53c566523025"><code>c02693d</code></a></td><td><code>34909: removed line 'mkdir build' in spkg-install</code></td></tr></table>

**Comment by seblabbe** [comment]
Reviewer: **Sébastien Labbé**

**Comment by seblabbe** [comment]
<div id="comment:18" align="right">comment:18</div>

The build directory seems to be constructed in the configure script, so I removed the `mkdir build` line from the spkg-install.

I give positive review to your changes. I let you change the status to positive review if you agree with my changes.

Everything done here seems to work well (see #34911).

**Comment by mkoeppe** [comment]
Changed reviewer from **Sébastien Labbé** to **Matthias Koeppe, Sébastien Labbé**

**Comment by mkoeppe** [comment]
<div id="comment:19" align="right">comment:19</div>

LGTM, thanks.

**Comment by vbraun** [comment]
Changed branch from **[u/slabbe/34909](https://github.com/sagemath/sagetrac-mirror/tree/u/slabbe/34909)** to **[`c02693d`](https://github.com/sagemath/sagetrac-mirror/commit/c02693d57f380d649cda15d46a9d53c566523025)**
