### ISSUE TITLE
tikz output should be 1 paragraph, to keep sagetex happy

### ISSUE THREAD

**Issue by dimpase** [sagemath/sage#34904]
<div id="comment:0"></div>

This is to fix https://github.com/sagemath/sagetex/issues/64
where it was reported that the following does not work

```tex
\documentclass{article}
\usepackage{sagetex} 
\usepackage{tikz} 

\begin{document}

\sagestr{(polytopes.great_rhombicuboctahedron()).tikz([4,5,6],45,scale=0.75)}

\end{document}
```
This is due to tikzpicture being put in an argument to \newlabel, which does not accept multiple paragraphs.

CC:  @seblabbe @kcrisman @jplab

Component: **graphics**

Author: **Dima Pasechnik**

Branch/Commit: **[`32e0248`](https://github.com/sagemath/sagetrac-mirror/commit/32e02484547b7a25f44878c561325eb6ff31459e)**

Reviewer: **Sébastien Labbé**

_Issue created by migration from https://trac.sagemath.org/ticket/34904_

**Comment by dimpase** [comment]
Branch: **[u/dimpase/geometry/pplot_tikz](https://github.com/sagemath/sagetrac-mirror/tree/u/dimpase/geometry/pplot_tikz)**

**Comment by dimpase** [comment]
Author: **Dima Pasechnik**

**Comment by dimpase** [comment]
<div id="comment:1"></div>

New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/c04c26bd8f64ed92577fe14b3b6bc11144836ba0"><code>c04c26b</code></a></td><td><code>prevent empty lines in tikz polyhedra output</code></td></tr></table>

**Comment by dimpase** [comment]
Commit: **[`c04c26b`](https://github.com/sagemath/sagetrac-mirror/commit/c04c26bd8f64ed92577fe14b3b6bc11144836ba0)**

**Comment by dimpase** [comment]
<div id="comment:2" align="right">comment:2</div>

probably some docs should be amended too

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
<div id="comment:3"></div>

Branch pushed to git repo; I updated commit sha1. New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/25c64c4baef3a7f30ef0ff03c6fbfe1c0add0897"><code>25c64c4</code></a></td><td><code>update sagetex tutorial</code></td></tr></table>

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
Changed commit from **[`c04c26b`](https://github.com/sagemath/sagetrac-mirror/commit/c04c26bd8f64ed92577fe14b3b6bc11144836ba0)** to **[`25c64c4`](https://github.com/sagemath/sagetrac-mirror/commit/25c64c4baef3a7f30ef0ff03c6fbfe1c0add0897)**

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
Changed commit from **[`25c64c4`](https://github.com/sagemath/sagetrac-mirror/commit/25c64c4baef3a7f30ef0ff03c6fbfe1c0add0897)** to **[`c3c4083`](https://github.com/sagemath/sagetrac-mirror/commit/c3c40837fcd1095e4abf7bcf13d63f5684d7039d)**

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
<div id="comment:5"></div>

Branch pushed to git repo; I updated commit sha1. New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/c3c40837fcd1095e4abf7bcf13d63f5684d7039d"><code>c3c4083</code></a></td><td><code>clarify few details</code></td></tr></table>

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
<div id="comment:6"></div>

Branch pushed to git repo; I updated commit sha1. New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/32e02484547b7a25f44878c561325eb6ff31459e"><code>32e0248</code></a></td><td><code>fix doctests</code></td></tr></table>

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
Changed commit from **[`c3c4083`](https://github.com/sagemath/sagetrac-mirror/commit/c3c40837fcd1095e4abf7bcf13d63f5684d7039d)** to **[`32e0248`](https://github.com/sagemath/sagetrac-mirror/commit/32e02484547b7a25f44878c561325eb6ff31459e)**

**Comment by seblabbe** [comment]
Reviewer: **Sébastien Labbé**

**Comment by seblabbe** [comment]
<div id="comment:7" align="right">comment:7</div>

All tests passed on my sage. Positive review.

Note the deprecation warning:

```
sage: (polytopes.great_rhombicuboctahedron()).tikz([4,5,6],45,scale=0.75)                            
/home/slabbe/GitBox/sage/src/sage/geometry/polyhedron/base6.py:606: DeprecationWarning: 
The default type of the returned object will soon be changed from `sage.misc.latex.LatexExpr` 
to `sage.misc.latex_standalone.TikzPicture`.  Please update your code to specify 
the desired output type as `.tikz(output_type='LatexExpr')` to keep the old behavior 
or `.tikz(output_type='TikzPicture')` to use the future default behavior.                                                             
See https://trac.sagemath.org/33002 for details.  
```

The example in the description will need to be updated at some point to:

```
\documentclass{article}
\usepackage{sagetex} 
\usepackage{tikz} 

\begin{document}

\sagestr{(polytopes.great_rhombicuboctahedron()).tikz([4,5,6],45,scale=0.75,output_type='LatexExpr')}

\end{document}
```

**Comment by vbraun** [comment]
Changed branch from **[u/dimpase/geometry/pplot_tikz](https://github.com/sagemath/sagetrac-mirror/tree/u/dimpase/geometry/pplot_tikz)** to **[`32e0248`](https://github.com/sagemath/sagetrac-mirror/commit/32e02484547b7a25f44878c561325eb6ff31459e)**
