### ISSUE TITLE
tox.ini / GH Actions: Update Linux platforms

### ISSUE THREAD

**Issue by mkoeppe** [sagemath/sage#34903]
<div id="comment:0"></div>

`ubuntu-lunar` https://hub.docker.com/_/ubuntu

`fedora-38` (rawhide) https://hub.docker.com/_/fedora

`linuxmint-21.1` https://hub.docker.com/u/linuxmintd

Depends on #34849

CC:  @dimpase

Component: **porting**

Author: **Matthias Koeppe**

Branch/Commit: **[`474afe2`](https://github.com/sagemath/sagetrac-mirror/commit/474afe20fa232a36f3d19c3b698c7767d8521e07)**

Reviewer: **Dima Pasechnik**

_Issue created by migration from https://trac.sagemath.org/ticket/34903_

**Comment by mkoeppe** [comment]
Author: **Matthias Koeppe**

**Comment by mkoeppe** [comment]
Dependencies: **#34849**

**Comment by mkoeppe** [comment]
Branch: **[u/mkoeppe/tox_ini___gh_actions__update_linux_platforms](https://github.com/sagemath/sagetrac-mirror/tree/u/mkoeppe/tox_ini___gh_actions__update_linux_platforms)**

**Comment by mkoeppe** [comment]
Commit: **[`474afe2`](https://github.com/sagemath/sagetrac-mirror/commit/474afe20fa232a36f3d19c3b698c7767d8521e07)**

**Comment by mkoeppe** [comment]
<div id="comment:3"></div>

Last 10 new commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/449b56bc56bb24a8aa958317463757c6feedf90c"><code>449b56b</code></a></td><td><code>pkgs/sagemath*/tox.ini: Fix for tox 4</code></td></tr><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/4a27a3d089dff6f50dde00a68d896e28fed9a9c8"><code>4a27a3d</code></a></td><td><code>Merge #34839</code></td></tr><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/95fe89ab0635531f4626a5711343fb47da280374"><code>95fe89a</code></a></td><td><code>build/pkgs/tox/spkg-configure.m4: Check for good tox 3, tox 4 versions separately</code></td></tr><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/cc7196abb897a2b3d5bb939e800131b77322dd38"><code>cc7196a</code></a></td><td><code>src/tox.ini: More allowlist_externals for tox 4</code></td></tr><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/1999bd6f42480d570deb10f85d6d4219c2936af4"><code>1999bd6</code></a></td><td><code>src/tox.ini: Quoting fix for tox 4</code></td></tr><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/071c113fe6f7d4405b4f470c6f3ff02eb8359e3d"><code>071c113</code></a></td><td><code>Merge tag '9.8.beta6' into t/34849/more_fixes_to_support_tox_4</code></td></tr><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/6b8c666119fd96115b4efafc3b23984fdacf0f6b"><code>6b8c666</code></a></td><td><code>Merge #34839</code></td></tr><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/a2eb816f4f265d30e5f9e8b3721ee4c703a29e9b"><code>a2eb816</code></a></td><td><code>tox.ini: Require tox >= 4.2.7</code></td></tr><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/fba75012c8b725b599cd34f619e4bb66ee4d36f9"><code>fba7501</code></a></td><td><code>Merge #34849</code></td></tr><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/474afe20fa232a36f3d19c3b698c7767d8521e07"><code>474afe2</code></a></td><td><code>.github/workflows/docker.yml: Add ubuntu-lunar, fedora-38, linuxmint-21.1</code></td></tr></table>

**Comment by dimpase** [comment]
<div id="comment:4" align="right">comment:4</div>

`tox -e docker-debian-buster-i386-standard-incremental -- build ptest` (latest tox 4, 
this branch and #34537) fails, and I can't find logs.
Where are all these

```
[graphs-20210214.p0] installing. Log file: /sage/logs/pkgs/graphs-20210214.p0.log
```
etc, going?

**Comment by mkoeppe** [comment]
<div id="comment:5" align="right">comment:5</div>

It should tell you the sha of a Docker image with the failing build.
You can then inspect the image by starting a container (`docker run -it SHA... bash`)

**Comment by mkoeppe** [comment]
<div id="comment:6" align="right">comment:6</div>

`cat .tox/docker-debian-buster-i386-standard-incremental/Dockertags` will tell you the images that have been created.

**Comment by dimpase** [comment]
<div id="comment:7" align="right">comment:7</div>

And what does this info should tell me?

```
$ cat .tox/docker-debian-buster-i386-standard-incremental/Dockertags
sage-docker-debian-buster-i386-standard-with-targets:9.5.beta0-13242-gd4f48b5f00a-failed
sage-docker-debian-buster-i386-standard-with-targets:9.5.beta0-13242-gd4f48b5f00a-failed
sage-docker-debian-buster-i386-standard-with-targets:9.5.beta0-13242-gd4f48b5f00a-failed
sage-docker-debian-buster-i386-standard-with-targets:9.5.beta0-13242-gd4f48b5f00a-failed
$ cat .tox/docker-debian-buster-i386-standard/Dockertags
sage-docker-debian-buster-i386-standard-with-targets:9.5.beta0-13242-gd4f48b5f00a-failed
```

I tried "mounting" these with docker, to no avail.
It starts building, and errors out just the same (and nothing is mounted afterwards)

**Comment by mkoeppe** [comment]
<div id="comment:8" align="right">comment:8</div>

Use `docker run -it sage-docker-debian-buster-i386-standard-with-targets:9.5.beta0-13242-gd4f48b5f00a-failed bash`

If you don't provide the interpreter (bash), it will just continue with the build recipe

**Comment by dimpase** [comment]
<div id="comment:9" align="right">comment:9</div>

OK, lgtm

**Comment by dimpase** [comment]
Reviewer: **Dima Pasechnik**

**Comment by mkoeppe** [comment]
<div id="comment:10" align="right">comment:10</div>

Thanks!

**Comment by vbraun** [comment]
Changed branch from **[u/mkoeppe/tox_ini___gh_actions__update_linux_platforms](https://github.com/sagemath/sagetrac-mirror/tree/u/mkoeppe/tox_ini___gh_actions__update_linux_platforms)** to **[`474afe2`](https://github.com/sagemath/sagetrac-mirror/commit/474afe20fa232a36f3d19c3b698c7767d8521e07)**
