### ISSUE TITLE
Improvements to _vector_ of a quantum group module

### ISSUE THREAD

**Issue by tscrim** [sagemath/sage#34905]
<div id="comment:0"></div>

Currently, they do not support all of the keywords that can be passed, say, via `submodule`.

Component: **algebra**

Keywords: **quantum group, representation**

Author: **Travis Scrimshaw**

Branch/Commit: **[`e2d836e`](https://github.com/sagemath/sagetrac-mirror/commit/e2d836ed9ffd17d5db3a553140fe1e05e9d0c63e)**

Reviewer: **Matthias Koeppe**

_Issue created by migration from https://trac.sagemath.org/ticket/34905_

**Comment by tscrim** [comment]
Commit: **[`e2d836e`](https://github.com/sagemath/sagetrac-mirror/commit/e2d836ed9ffd17d5db3a553140fe1e05e9d0c63e)**

**Comment by tscrim** [comment]
<div id="comment:1"></div>

New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/e2d836ed9ffd17d5db3a553140fe1e05e9d0c63e"><code>e2d836e</code></a></td><td><code>Improvements to the `_vector_` of quantum group module elements.</code></td></tr></table>

**Comment by tscrim** [comment]
Branch: **[public/algebras/improve_quantum_group_elts-34905](https://github.com/sagemath/sagetrac-mirror/tree/public/algebras/improve_quantum_group_elts-34905)**

**Comment by mkoeppe** [comment]
<div id="comment:2" align="right">comment:2</div>

LGTM.

**Comment by mkoeppe** [comment]
Reviewer: **Matthias Koeppe**

**Comment by tscrim** [comment]
<div id="comment:3" align="right">comment:3</div>

Thank you.

**Comment by vbraun** [comment]
Changed branch from **[public/algebras/improve_quantum_group_elts-34905](https://github.com/sagemath/sagetrac-mirror/tree/public/algebras/improve_quantum_group_elts-34905)** to **[`e2d836e`](https://github.com/sagemath/sagetrac-mirror/commit/e2d836ed9ffd17d5db3a553140fe1e05e9d0c63e)**
