### ISSUE TITLE
Integer class should not be register as a “virtual subclass” of the metaclass numbers.Integral

### ISSUE THREAD

**Issue by cyrilbouvier** [sagemath/sage#34916]
<div id="comment:0"></div>

The `Integer` class should not be register as a “virtual subclass” of the metaclass `numbers.Integral` (it is done in line 7671 of `src/sage/rings/integer.pyx` for Sage 9.7).

```python
# Support Python's numbers abstract base class
import numbers
numbers.Integral.register(Integer)
```

The reason is that the `Integer` class does not adhere to the requirements of the metaclass `numbers.Integral` in **at least** one way: `denominator` and `numerator` are method (so callable) instead of attributes (so non callable).

For example, it breaks the usage of the python module `fractions` inside of Sage:

```python
import fractions
fractions.Fraction (1, 2)
```
With Sage 9.7 using Python 3.10.5, it raises an exception:

```
TypeError: unsupported operand type(s) for *: 'builtin_function_or_method' and 'builtin_function_or_method'
```
It is due to the fact that the code inside the `Fraction` class, after testing that the input are subclasses of `numbers.Rational` (which is true for Sage `Integer` because the class is register as a `numbers.Integral`), the code tries to use the attributes `.numerator` which is a callable for Sage `Integer`.

Component: **basic arithmetic**

_Issue created by migration from https://trac.sagemath.org/ticket/34916_

**Comment by mkoeppe** [comment]
<div id="comment:1" align="right">comment:1</div>

dup of #28234

**Comment by jhpalmieri** [comment]
I agree, a duplicate.
