### ISSUE TITLE
fix E266 in modular

### ISSUE THREAD

**Issue by fchapoton** [sagemath/sage#34919]
<div id="comment:0"></div>

about

```
E266 too many leading '#' for block comment
```

Component: **refactoring**

Author: **Frédéric Chapoton**

Branch/Commit: **[`eb44bfa`](https://github.com/sagemath/sagetrac-mirror/commit/eb44bfa1fd58e1be3049cfc332d5b32a31294966)**

Reviewer: **Matthias Koeppe**

_Issue created by migration from https://trac.sagemath.org/ticket/34919_

**Comment by fchapoton** [comment]
Branch: **[u/chapoton/34919](https://github.com/sagemath/sagetrac-mirror/tree/u/chapoton/34919)**

**Comment by fchapoton** [comment]
Commit: **[`eb44bfa`](https://github.com/sagemath/sagetrac-mirror/commit/eb44bfa1fd58e1be3049cfc332d5b32a31294966)**

**Comment by fchapoton** [comment]
<div id="comment:1"></div>

New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/eb44bfa1fd58e1be3049cfc332d5b32a31294966"><code>eb44bfa</code></a></td><td><code>fix E266 in modular/</code></td></tr></table>

**Comment by mkoeppe** [comment]
Reviewer: **Matthias Koeppe**

**Comment by vbraun** [comment]
Changed branch from **[u/chapoton/34919](https://github.com/sagemath/sagetrac-mirror/tree/u/chapoton/34919)** to **[`eb44bfa`](https://github.com/sagemath/sagetrac-mirror/commit/eb44bfa1fd58e1be3049cfc332d5b32a31294966)**
