### ISSUE TITLE
fix E714 in pyx files inside matrix/

### ISSUE THREAD

**Issue by fchapoton** [sagemath/sage#34921]
<div id="comment:0"></div>

about using "is not"

following #34895

Component: **refactoring**

Author: **Frédéric Chapoton**

Branch/Commit: **[`c621882`](https://github.com/sagemath/sagetrac-mirror/commit/c6218823d5993aa3b463bdb48ff367ef3337c322)**

Reviewer: **Martin Rubey**

_Issue created by migration from https://trac.sagemath.org/ticket/34921_

**Comment by fchapoton** [comment]
Branch: **[u/chapoton/34921](https://github.com/sagemath/sagetrac-mirror/tree/u/chapoton/34921)**

**Comment by fchapoton** [comment]
Description changed:
``````diff
--- 
+++ 
@@ -1 +1,3 @@
 about using "is not"
+
+following #34895
``````

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
Commit: **[`c621882`](https://github.com/sagemath/sagetrac-mirror/commit/c6218823d5993aa3b463bdb48ff367ef3337c322)**

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
<div id="comment:3"></div>

Branch pushed to git repo; I updated commit sha1. New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/c6218823d5993aa3b463bdb48ff367ef3337c322"><code>c621882</code></a></td><td><code>fix E714 in pyx files inside matrix/</code></td></tr></table>

**Comment by mantepse** [comment]
Reviewer: **Martin Rubey**

**Comment by vbraun** [comment]
Changed branch from **[u/chapoton/34921](https://github.com/sagemath/sagetrac-mirror/tree/u/chapoton/34921)** to **[`c621882`](https://github.com/sagemath/sagetrac-mirror/commit/c6218823d5993aa3b463bdb48ff367ef3337c322)**
