### ISSUE TITLE
fix and activate W391 in pyx files

### ISSUE THREAD

**Issue by fchapoton** [sagemath/sage#34929]
<div id="comment:0"></div>

W391 blank line at end of file

Component: **refactoring**

Author: **Frédéric Chapoton**

Reviewer: **Matthias Koeppe**

_Issue created by migration from https://trac.sagemath.org/ticket/34929_

**Comment by fchapoton** [comment]
Branch: **[u/chapoton/34929](https://github.com/sagemath/sagetrac-mirror/tree/u/chapoton/34929)**

**Comment by fchapoton** [comment]
<div id="comment:1"></div>

New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/81bec94c3616153279d2fc926d8d80c8080b8b6e"><code>81bec94</code></a></td><td><code>fix and activate W391 in cython files</code></td></tr></table>

**Comment by fchapoton** [comment]
Commit: **[`81bec94`](https://github.com/sagemath/sagetrac-mirror/commit/81bec94c3616153279d2fc926d8d80c8080b8b6e)**

**Comment by mkoeppe** [comment]
Reviewer: **Matthias Koeppe**

**Comment by vbraun** [comment]
Merge conflict, please open GitHub PR to fix

**Comment by mkoeppe** [comment]
Removed branch from issue description; replaced by PR #35091
