### ISSUE TITLE
sage -i ore_algebra fails (→ upgrade ore_algebra)

### ISSUE THREAD

**Issue by mezzarobba** [sagemath/sage#34924]
<div id="comment:0"></div>

As [reported](https://github.com/mkauers/ore_algebra/issues/57) by github user beew, `sage -i ore_algebra` no longer works.

I believe Sage needs to upgrade to a version of `ore_algebra` containing commit `31e5cf28` (for PEP420 support in Cython).

CC:  @tscrim

Component: **packages: optional**

Author: **Matthias Koeppe**

Branch/Commit: **[u/mkoeppe/sage__i_ore_algebra_fails____upgrade_ore_algebra_](https://github.com/sagemath/sagetrac-mirror/tree/u/mkoeppe/sage__i_ore_algebra_fails____upgrade_ore_algebra_) @ [`acef7ce`](https://github.com/sagemath/sagetrac-mirror/commit/acef7ce72cba2d426dc4a36ca041449b5589ffe4)**

Reviewer: **Travis Scrimshaw**

_Issue created by migration from https://trac.sagemath.org/ticket/34924_

**Comment by mkoeppe** [comment]
Branch: **[u/mkoeppe/sage__i_ore_algebra_fails____upgrade_ore_algebra_](https://github.com/sagemath/sagetrac-mirror/tree/u/mkoeppe/sage__i_ore_algebra_fails____upgrade_ore_algebra_)**

**Comment by mkoeppe** [comment]
Author: **Matthias Koeppe**

**Comment by mkoeppe** [comment]
<div id="comment:2" align="right">comment:2</div>

That's current `master` https://github.com/mkauers/ore_algebra/commits/master

---
New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/d639d637b61bd2ee575c896bb218974431a645b8"><code>d639d63</code></a></td><td><code>build/pkgs/ore_algebra: Update to version of 2023-01-13</code></td></tr></table>

**Comment by mkoeppe** [comment]
Commit: **[`d639d63`](https://github.com/sagemath/sagetrac-mirror/commit/d639d637b61bd2ee575c896bb218974431a645b8)**

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
Changed commit from **[`d639d63`](https://github.com/sagemath/sagetrac-mirror/commit/d639d637b61bd2ee575c896bb218974431a645b8)** to **[`acef7ce`](https://github.com/sagemath/sagetrac-mirror/commit/acef7ce72cba2d426dc4a36ca041449b5589ffe4)**

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
<div id="comment:3"></div>

Branch pushed to git repo; I updated commit sha1. This was a forced push. New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/acef7ce72cba2d426dc4a36ca041449b5589ffe4"><code>acef7ce</code></a></td><td><code>build/pkgs/ore_algebra: Update to version of 2023-01-13</code></td></tr></table>

**Comment by tscrim** [comment]
<div id="comment:6" align="right">comment:6</div>

I have both confirmed the problem and that this fix works.

**Comment by tscrim** [comment]
Reviewer: **Travis Scrimshaw**

**Comment by mkoeppe** [comment]
<div id="comment:7" align="right">comment:7</div>

Thanks!

**Comment by mkoeppe** [comment]
Merged in 10.0.beta0
