### ISSUE TITLE
Description of inputs for primes is misleading.

### ISSUE THREAD

**Issue by 0365a2d1-30f5-431b-af6e-31a43e4d0c79** [sagemath/sage#34920]
<div id="comment:0"></div>

The description of the input parameters for the "primes" function is incorrect:

```

- ``start`` - an integer - lower bound for the primes
- ``stop`` - an integer (or infinity) optional argument -
  giving upper (open) bound for the primes
```

The current description states that "stop" is optional and "start" is required, when in fact it is the opposite.

Component: **basic arithmetic**

Keywords: **primes**

Branch/Commit: **[u/gh-Eloitor/primes_fix](https://github.com/sagemath/sagetrac-mirror/tree/u/gh-Eloitor/primes_fix) @ [`05734dc`](https://github.com/sagemath/sagetrac-mirror/commit/05734dc21240dcee47ad789ec8960940813e74ae)**

_Issue created by migration from https://trac.sagemath.org/ticket/34920_

**Comment by 0365a2d1-30f5-431b-af6e-31a43e4d0c79** [comment]
Branch: **[u/gh_Eloitor/primes_fix](https://github.com/sagemath/sagetrac-mirror/tree/u/gh_Eloitor/primes_fix)**

**Comment by 0365a2d1-30f5-431b-af6e-31a43e4d0c79** [comment]
Changed branch from **[u/gh_Eloitor/primes_fix](https://github.com/sagemath/sagetrac-mirror/tree/u/gh_Eloitor/primes_fix)** to **[u/gh-Eloitor/primes_fix](https://github.com/sagemath/sagetrac-mirror/tree/u/gh-Eloitor/primes_fix)**

**Comment by 0365a2d1-30f5-431b-af6e-31a43e4d0c79** [comment]
<div id="comment:3" align="right">comment:3</div>

I'm sorry, I don't know how to add this branch to the ticket: https://github.com/Eloitor/sage/tree/u/gh_Eloitor/primes_fix

Edit: I found how to do it. I'll add the branch later.

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
<div id="comment:4"></div>

Branch pushed to git repo; I updated commit sha1. New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/01e940499cd2f871225d39d5741d903eb69633ed"><code>01e9404</code></a></td><td><code>Refactor QuaternionOrder to work with algebras over number fields.</code></td></tr><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/93681cb0f12e8998581b85080e73dcc77ba35005"><code>93681cb</code></a></td><td><code>Trac #34920: Fix description of inputs of primes.</code></td></tr></table>

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
Commit: **[`93681cb`](https://github.com/sagemath/sagetrac-mirror/commit/93681cb0f12e8998581b85080e73dcc77ba35005)**

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
<div id="comment:5"></div>

Branch pushed to git repo; I updated commit sha1. This was a forced push. New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/05734dc21240dcee47ad789ec8960940813e74ae"><code>05734dc</code></a></td><td><code>Trac #34920: Fix description of inputs of primes.</code></td></tr></table>

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
Changed commit from **[`93681cb`](https://github.com/sagemath/sagetrac-mirror/commit/93681cb0f12e8998581b85080e73dcc77ba35005)** to **[`05734dc`](https://github.com/sagemath/sagetrac-mirror/commit/05734dc21240dcee47ad789ec8960940813e74ae)**
