### ISSUE TITLE
fricas interface: __reduce__ doctest failure

### ISSUE THREAD

**Issue by jhpalmieri** [sagemath/sage#34927]
<div id="comment:0"></div>

This is a followup to #34547, making changes similar to ones already made there.

Component: **interfaces**

Author: **John Palmieri**

Branch/Commit: **[u/jhpalmieri/fricas-interface](https://github.com/sagemath/sagetrac-mirror/tree/u/jhpalmieri/fricas-interface) @ [`83e679a`](https://github.com/sagemath/sagetrac-mirror/commit/83e679a9ad28770faf9c7d4e900ae37000994cfe)**

Reviewer: **Matthias Koeppe**

_Issue created by migration from https://trac.sagemath.org/ticket/34927_

**Comment by jhpalmieri** [comment]
Branch: **[u/jhpalmieri/fricas-interface](https://github.com/sagemath/sagetrac-mirror/tree/u/jhpalmieri/fricas-interface)**

**Comment by jhpalmieri** [comment]
Commit: **[`83e679a`](https://github.com/sagemath/sagetrac-mirror/commit/83e679a9ad28770faf9c7d4e900ae37000994cfe)**

**Comment by jhpalmieri** [comment]
<div id="comment:2" align="right">comment:2</div>

The doctest was marked as optional, which is why I didn't catch it in #34547. It doesn't need to be optional, so that tag has been removed.

---
New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/83e679a9ad28770faf9c7d4e900ae37000994cfe"><code>83e679a</code></a></td><td><code>trac 34927:</code></td></tr></table>

**Comment by mkoeppe** [comment]
Reviewer: **Matthias Koeppe**

**Comment by 7822f248-ba56-45f1-ab3d-4de7482bdf9f** [comment]
<div id="comment:4" align="right">comment:4</div>

Fix OK for me too.

Thank you very much !

**Comment by mkoeppe** [comment]
Merged in 10.0.beta0
