### ISSUE TITLE
about error messages in categories/

### ISSUE THREAD

**Issue by fchapoton** [sagemath/sage#34928]
<div id="comment:0"></div>

namely changing those with a final dot to the common python style

CC:  @tscrim @kwankyu @kliem @slel

Component: **refactoring**

Author: **Frédéric Chapoton**

Branch/Commit: **[u/chapoton/34928](https://github.com/sagemath/sagetrac-mirror/tree/u/chapoton/34928) @ [`ea0753d`](https://github.com/sagemath/sagetrac-mirror/commit/ea0753d98fc89baa3adeff3a47656b77a227f839)**

Reviewer: **Matthias Koeppe**

_Issue created by migration from https://trac.sagemath.org/ticket/34928_

**Comment by fchapoton** [comment]
<div id="comment:1"></div>

New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/b77edb1e715cbacfe00ab374624acb23922b1fd6"><code>b77edb1</code></a></td><td><code>about error messages in categories/</code></td></tr></table>

**Comment by fchapoton** [comment]
Commit: **[`b77edb1`](https://github.com/sagemath/sagetrac-mirror/commit/b77edb1e715cbacfe00ab374624acb23922b1fd6)**

**Comment by fchapoton** [comment]
Branch: **[u/chapoton/34928](https://github.com/sagemath/sagetrac-mirror/tree/u/chapoton/34928)**

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
<div id="comment:2"></div>

Branch pushed to git repo; I updated commit sha1. New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/519b47eeda5d52cd0bf029a10f45abdc5c0b40ef"><code>519b47e</code></a></td><td><code>fix doctest</code></td></tr></table>

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
Changed commit from **[`b77edb1`](https://github.com/sagemath/sagetrac-mirror/commit/b77edb1e715cbacfe00ab374624acb23922b1fd6)** to **[`519b47e`](https://github.com/sagemath/sagetrac-mirror/commit/519b47eeda5d52cd0bf029a10f45abdc5c0b40ef)**

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
Changed commit from **[`519b47e`](https://github.com/sagemath/sagetrac-mirror/commit/519b47eeda5d52cd0bf029a10f45abdc5c0b40ef)** to **[`ea0753d`](https://github.com/sagemath/sagetrac-mirror/commit/ea0753d98fc89baa3adeff3a47656b77a227f839)**

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
<div id="comment:3"></div>

Branch pushed to git repo; I updated commit sha1. This was a forced push. New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/ea0753d98fc89baa3adeff3a47656b77a227f839"><code>ea0753d</code></a></td><td><code>about error messages in categories/</code></td></tr></table>

**Comment by fchapoton** [comment]
<div id="comment:4" align="right">comment:4</div>

green lights, so please review (easy one)

**Comment by mkoeppe** [comment]
Reviewer: **Matthias Koeppe**

**Comment by mkoeppe** [comment]
Merged in 10.0.beta0
