### ISSUE TITLE
less usage of python2 long type in padics

### ISSUE THREAD

**Issue by fchapoton** [sagemath/sage#34922]
<div id="comment:0"></div>

CC:  @xcaruso

Component: **padics**

Author: **Frédéric Chapoton**

Branch/Commit: **[`057771e`](https://github.com/sagemath/sagetrac-mirror/commit/057771ebfd6f23f2540ed62c38ab0fb9c8ffe9cf)**

Reviewer: **Sebastian Oehms**

_Issue created by migration from https://trac.sagemath.org/ticket/34922_

**Comment by fchapoton** [comment]
<div id="comment:1"></div>

New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/057771ebfd6f23f2540ed62c38ab0fb9c8ffe9cf"><code>057771e</code></a></td><td><code>less usage of python2 "long" type in p-adics</code></td></tr></table>

**Comment by fchapoton** [comment]
Commit: **[`057771e`](https://github.com/sagemath/sagetrac-mirror/commit/057771ebfd6f23f2540ed62c38ab0fb9c8ffe9cf)**

**Comment by fchapoton** [comment]
Branch: **[u/chapoton/34922](https://github.com/sagemath/sagetrac-mirror/tree/u/chapoton/34922)**

**Comment by fchapoton** [comment]
<div id="comment:2" align="right">comment:2</div>

green bot, so please review (boring but easy)

**Comment by soehms** [comment]
Reviewer: **Sebastian Oehms**

**Comment by soehms** [comment]
<div id="comment:3" align="right">comment:3</div>

LGTM

**Comment by vbraun** [comment]
Changed branch from **[u/chapoton/34922](https://github.com/sagemath/sagetrac-mirror/tree/u/chapoton/34922)** to **[`057771e`](https://github.com/sagemath/sagetrac-mirror/commit/057771ebfd6f23f2540ed62c38ab0fb9c8ffe9cf)**
