### ISSUE TITLE
New ABC sage.structure.element.NumberFieldElement, deprecate is_NumberFieldElement

### ISSUE THREAD

**Issue by mkoeppe** [sagemath/sage#34931]
<div id="comment:0"></div>

We also make `sage.rings.number_field` a namespace package. This is necessary because `.number_field_base` is needed in sagemath-categories (#32432), whereas implementation modules depend on NTL.

Part of Meta-ticket #32414

CC:  @tscrim

Component: **refactoring**

Author: **Matthias Koeppe**

_Issue created by migration from https://trac.sagemath.org/ticket/34931_

**Comment by mkoeppe** [comment]
Branch: **[u/mkoeppe/new_abc_sage_structure_element_numberfieldelement__deprecate_is_numberfieldelement](https://github.com/sagemath/sagetrac-mirror/tree/u/mkoeppe/new_abc_sage_structure_element_numberfieldelement__deprecate_is_numberfieldelement)**

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
<div id="comment:2"></div>

Branch pushed to git repo; I updated commit sha1. This was a forced push. New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/a9dacbe0f717ac312be98609228a936afaf8a4e3"><code>a9dacbe</code></a></td><td><code>is_NumberFieldElement: Deprecate, replace uses by isinstance</code></td></tr></table>

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
Commit: **[`a9dacbe`](https://github.com/sagemath/sagetrac-mirror/commit/a9dacbe0f717ac312be98609228a936afaf8a4e3)**

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
<div id="comment:3"></div>

Branch pushed to git repo; I updated commit sha1. New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/1cc09cccbde3b3eafb4f123d4f06ae8cb8cace28"><code>1cc09cc</code></a></td><td><code>Replace some imports of NumberFieldElement classes by ABC</code></td></tr><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/4dfefbf9e0cfc6f4aa4a402b6a053ffe6e838792"><code>4dfefbf</code></a></td><td><code>src/sage/rings/number_field/number_field_element.pyx: Update doctest with deprecation warning</code></td></tr></table>

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
Changed commit from **[`a9dacbe`](https://github.com/sagemath/sagetrac-mirror/commit/a9dacbe0f717ac312be98609228a936afaf8a4e3)** to **[`4dfefbf`](https://github.com/sagemath/sagetrac-mirror/commit/4dfefbf9e0cfc6f4aa4a402b6a053ffe6e838792)**

**Comment by mkoeppe** [comment]
Author: **Matthias Koeppe**

**Comment by mkoeppe** [comment]
<div id="comment:5" align="right">comment:5</div>

Instead of adding the ABCDEFIT `NumberFieldElement` to `sage.structure.element`, we could also create a tiny new module `sage.rings.number_field.number_field_element_base` for it. Not sure which of the two is preferable.

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
<div id="comment:6"></div>

Branch pushed to git repo; I updated commit sha1. New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/bacff9613fa0dd6b2a39b424371315f318d099c7"><code>bacff96</code></a></td><td><code>src/sage/rings/number_field/__init__.py: Remove</code></td></tr></table>

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
Changed commit from **[`4dfefbf`](https://github.com/sagemath/sagetrac-mirror/commit/4dfefbf9e0cfc6f4aa4a402b6a053ffe6e838792)** to **[`bacff96`](https://github.com/sagemath/sagetrac-mirror/commit/bacff9613fa0dd6b2a39b424371315f318d099c7)**

**Comment by mkoeppe** [comment]
Description changed:
``````diff
--- 
+++ 
@@ -1 +1,3 @@
+We also make `sage.rings.number_field` a namespace package.
+
 Part of Meta-ticket #32414
``````

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
<div id="comment:9"></div>

Branch pushed to git repo; I updated commit sha1. New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/3e95ebf75d9ccf231381840770077d118c0010d0"><code>3e95ebf</code></a></td><td><code>src/sage/structure/element.pyx: Fix up doctest</code></td></tr></table>

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
Changed commit from **[`bacff96`](https://github.com/sagemath/sagetrac-mirror/commit/bacff9613fa0dd6b2a39b424371315f318d099c7)** to **[`3e95ebf`](https://github.com/sagemath/sagetrac-mirror/commit/3e95ebf75d9ccf231381840770077d118c0010d0)**

**Comment by mkoeppe** [comment]
Removed branch from issue description; replaced by PR #35100
