### ISSUE TITLE
do we need to check python for ensurepip?

### ISSUE THREAD

**Issue by dimpase** [sagemath/sage#34938]
<div id="comment:0"></div>

On Ubunty 22.04, Python 3.11 comes with pip, but without ensurepip

So we don't need to check ensurepip if pip is already there

CC:  @mkoeppe @kiwifb

Component: **build: configure**

Reviewer: **Dima Pasechnik**

_Issue created by migration from https://trac.sagemath.org/ticket/34938_

**Comment by mkoeppe** [comment]
<div id="comment:1" align="right">comment:1</div>

ensurepip is needed for setting up venvs.

**Comment by mkoeppe** [comment]
<div id="comment:2" align="right">comment:2</div>

On Debian and Ubuntu, you need the `python3-venv` package; see build/pkgs/python3/distros/debian.txt

**Comment by dimpase** [comment]
<div id="comment:3" align="right">comment:3</div>

For what it's worth, I was unable to get Ubuntu's 22.04 python3.11 (they still ship 3.11.0) accepted by configure as good python to use.

But maybe 3.11.0 is broken.

**Comment by mkoeppe** [comment]
<div id="comment:4" align="right">comment:4</div>

Did you install python3-venv?

**Comment by dimpase** [comment]
<div id="comment:5" align="right">comment:5</div>

oops, I see. Never mind, a container-related confusion.

By the way, is there documentation on Sage "packages" on [GitHub](../wiki/GitHub), incorporated in Sage developer docs? (i.e. docker containers with pre-built Sage stuff which one can pull and then update, for quick testing?)

**Comment by dimpase** [comment]
Reviewer: **Dima Pasechnik**

**Comment by mkoeppe** [comment]
<div id="comment:7" align="right">comment:7</div>

https://doc.sagemath.org/html/en/developer/portability_testing.html#using-our-pre-built-docker-images-published-on-ghcr-io

https://doc.sagemath.org/html/en/developer/portability_testing.html#using-our-pre-built-docker-images-for-development-in-vs-code

**Comment by mkoeppe** [comment]
<div id="comment:8" align="right">comment:8</div>

And https://trac.sagemath.org/wiki/ReleaseTours/sage-9.8#tox-edocker-...-incremental
(documented, sparsely, in the top level tox.ini)
