### ISSUE TITLE
sage-bootstrap-python should accept python3.11

### ISSUE THREAD

**Issue by dimpase** [sagemath/sage#34937]
<div id="comment:0"></div>

at the moment it does not

CC:  @mkoeppe @kiwifb

Component: **build**

Author: **Matthias Koeppe**

Branch/Commit: **[u/mkoeppe/sage_bootstrap_python_should_accept_python3_11](https://github.com/sagemath/sagetrac-mirror/tree/u/mkoeppe/sage_bootstrap_python_should_accept_python3_11) @ [`9d54def`](https://github.com/sagemath/sagetrac-mirror/commit/9d54def6ebd7a5a156e4fbb2a531db7cef6d2c62)**

Reviewer: **Dima Pasechnik**

_Issue created by migration from https://trac.sagemath.org/ticket/34937_

**Comment by mkoeppe** [comment]
Branch: **[u/mkoeppe/sage_bootstrap_python_should_accept_python3_11](https://github.com/sagemath/sagetrac-mirror/tree/u/mkoeppe/sage_bootstrap_python_should_accept_python3_11)**

**Comment by mkoeppe** [comment]
Author: **Matthias Koeppe**

**Comment by mkoeppe** [comment]
Commit: **[`9d54def`](https://github.com/sagemath/sagetrac-mirror/commit/9d54def6ebd7a5a156e4fbb2a531db7cef6d2c62)**

**Comment by mkoeppe** [comment]
<div id="comment:2" align="right">comment:2</div>

Good catch. I've also added python3.12 for good measure.

---
New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/9d54def6ebd7a5a156e4fbb2a531db7cef6d2c62"><code>9d54def</code></a></td><td><code>build/bin/sage-bootstrap-python: Add python3.11, python3.12 to search list</code></td></tr></table>

**Comment by kiwifb** [comment]
<div id="comment:3" align="right">comment:3</div>

Separate issue but until when do we want to continue accepting python2(.7) for bootstrap? And generally older python (3.6 and 3.7 are still there).

**Comment by mkoeppe** [comment]
<div id="comment:4" align="right">comment:4</div>

As soon as it becomes too inconvenient to keep compatibility when implementing a new sage-bootstrap feature we should consider this question.

**Comment by dimpase** [comment]
Reviewer: **Dima Pasechnik**

**Comment by dimpase** [comment]
<div id="comment:5" align="right">comment:5</div>

lgtm

**Comment by mkoeppe** [comment]
<div id="comment:6" align="right">comment:6</div>

Thanks!

**Comment by mkoeppe** [comment]
Merged in 10.0.beta0
