### ISSUE TITLE
Implement Milnor fiber and Coxeter complexes and posets

### ISSUE THREAD

**Issue by tscrim** [sagemath/sage#34936]
<div id="comment:0"></div>

The Milnor fiber complex is defined by using standard parabolic cosets for well-generated complex reflection group `W`. When `W` is a Coxeter group, this is the Coxeter complex. The corresponding face poset also makes sense even when `W` is not well-generated, but it is no longer a meet semilattice (in all of the cases I tested, I don't have a proof though).

Depends on #34912

CC:  @stumpc5 @fchapoton

Component: **combinatorics**

Keywords: **complex reflection group**

Author: **Travis Scrimshaw**

Branch/Commit: **[public/combinat/coxeter_milnor_complex-34936](https://github.com/sagemath/sagetrac-mirror/tree/public/combinat/coxeter_milnor_complex-34936) @ [`d353472`](https://github.com/sagemath/sagetrac-mirror/commit/d35347244a1645771de7f64ce816cbd3a1eb8e2a)**

_Issue created by migration from https://trac.sagemath.org/ticket/34936_

**Comment by tscrim** [comment]
Dependencies: **#34912**

**Comment by tscrim** [comment]
Commit: **[`d353472`](https://github.com/sagemath/sagetrac-mirror/commit/d35347244a1645771de7f64ce816cbd3a1eb8e2a)**

**Comment by tscrim** [comment]
<div id="comment:1" align="right">comment:1</div>

#34912 is needed for a hashing issue (writing this is how I discovered it).

---
New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/498e8dbd59906fcd80ff10d5f3f66b0168cd5abc"><code>498e8db</code></a></td><td><code>faster iteration for complex non-real reflection group and new hash</code></td></tr><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/518ecbfb3a62dd809f090b15fe6158344f6b3077"><code>518ecbf</code></a></td><td><code>Merge branch 'u/stumpc5/reduced_words_of_reflectiongroup_elements_are_not_well_defined' of https://github.com/sagemath/sagetrac-mirror into u/tscrim/hash_reflection_groups-34912</code></td></tr><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/3a1a03ae2cc38d75691418bfda23a703e002139c"><code>3a1a03a</code></a></td><td><code>Updating `__hash__` and updating gap3 doctests to pass.</code></td></tr><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/14d6f6191190904f92728e00989de7ec1b7ff180"><code>14d6f61</code></a></td><td><code>Adding some systematic doctests and one detail.</code></td></tr><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/d35347244a1645771de7f64ce816cbd3a1eb8e2a"><code>d353472</code></a></td><td><code>Implementation of Milnor fiber/Coxeter complex/poset.</code></td></tr></table>

**Comment by tscrim** [comment]
Branch: **[public/combinat/coxeter_milnor_complex-34936](https://github.com/sagemath/sagetrac-mirror/tree/public/combinat/coxeter_milnor_complex-34936)**

**Comment by fchapoton** [comment]
can this be closed as fixed ?

**Comment by fchapoton** [comment]
@tscrim : can we close this issue ?

**Comment by tscrim** [comment]
Yes, indeed.
