### ISSUE TITLE
sage.{categories,matrix,structure}: Replace imports from sage.*.all for namespace packages

### ISSUE THREAD

**Issue by mkoeppe** [sagemath/sage#34949]
<div id="comment:0"></div>

Using `./sage -fiximports` from #34945.

Also remove trailing whitespace in the affected files.

Part of Meta-ticket #34201

CC:  @alexchandler100 @tscrim @fchapoton

Component: **refactoring**

Author: **Alex Chandler, Matthias Koeppe**

_Issue created by migration from https://trac.sagemath.org/ticket/34949_

**Comment by mkoeppe** [comment]
Branch: **[u/mkoeppe/sage__categories_matrix_structure___replace_imports_from_sage___all_for_namespace_packages](https://github.com/sagemath/sagetrac-mirror/tree/u/mkoeppe/sage__categories_matrix_structure___replace_imports_from_sage___all_for_namespace_packages)**

**Comment by mkoeppe** [comment]
<div id="comment:2"></div>

New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/a14d662aec9b9340385f0a92e7de92939e53c10c"><code>a14d662</code></a></td><td><code>sage -fiximports src/sage/{categories,matrix,structure}</code></td></tr><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/9911481804b7b9fac03695d9d74126a0410c7317"><code>9911481</code></a></td><td><code>src/sage/{categories,matrix,structure}: Manual fixes to imports</code></td></tr></table>

**Comment by mkoeppe** [comment]
Commit: **[`9911481`](https://github.com/sagemath/sagetrac-mirror/commit/9911481804b7b9fac03695d9d74126a0410c7317)**

**Comment by mkoeppe** [comment]
<div id="comment:3" align="right">comment:3</div>


```
[sagelib-9.8.beta7]     Error compiling Cython file:
[sagelib-9.8.beta7]     ------------------------------------------------------------
[sagelib-9.8.beta7]     ...
[sagelib-9.8.beta7]             if not isinstance(right, Element):
[sagelib-9.8.beta7]                 right = py_scalar_to_element(right)
[sagelib-9.8.beta7]                 if not isinstance(right, Element):
[sagelib-9.8.beta7]                     right = right.sage()
[sagelib-9.8.beta7]             from sage.arith.misc import GCD as gcd
[sagelib-9.8.beta7]                 from sage.arith.misc import GCD as gcd
[sagelib-9.8.beta7]     ^
[sagelib-9.8.beta7]     ------------------------------------------------------------
[sagelib-9.8.beta7] 
[sagelib-9.8.beta7]     sage/structure/element.pyx:4057:0: Possible inconsistent indentation
[sagelib-9.8.beta7] 
[sagelib-9.8.beta7]     Error compiling Cython file:
[sagelib-9.8.beta7]     ------------------------------------------------------------
[sagelib-9.8.beta7]     ...
[sagelib-9.8.beta7]             if not isinstance(right, Element):
[sagelib-9.8.beta7]                 right = py_scalar_to_element(right)
[sagelib-9.8.beta7]                 if not isinstance(right, Element):
[sagelib-9.8.beta7]                     right = right.sage()
[sagelib-9.8.beta7]             from sage.arith.misc import GCD as gcd
[sagelib-9.8.beta7]                 from sage.arith.misc import GCD as gcd
[sagelib-9.8.beta7]     ^
[sagelib-9.8.beta7]     ------------------------------------------------------------
[sagelib-9.8.beta7] 
[sagelib-9.8.beta7]     sage/structure/element.pyx:4057:0: Expected an identifier or literal
```

**Comment by jhpalmieri** [comment]
<div id="comment:5" align="right">comment:5</div>

I think these changes are to blame:

```diff
diff --git a/src/sage/structure/element.pyx b/src/sage/structure/element.pyx
index e9430f0..92e83bd 100644
--- a/src/sage/structure/element.pyx
+++ b/src/sage/structure/element.pyx
@@ -4047,8 +4053,8 @@ cdef class PrincipalIdealDomainElement(DedekindDomainElement):
             right = py_scalar_to_element(right)
             if not isinstance(right, Element):
                 right = right.sage()
-        if not ((<Element>right)._parent is self._parent):
-            from sage.arith.all import gcd
+        from sage.arith.misc import GCD as gcd
+            from sage.arith.misc import GCD as gcd
             return coercion_model.bin_op(self, right, gcd)
         return self._gcd(right)
 
@@ -4081,8 +4087,8 @@ cdef class PrincipalIdealDomainElement(DedekindDomainElement):
             right = py_scalar_to_element(right)
             if not isinstance(right, Element):
                 right = right.sage()
-        if not ((<Element>right)._parent is self._parent):
-            from sage.arith.all import lcm
+        from sage.arith.functions import lcm
+            from sage.arith.functions import lcm
             return coercion_model.bin_op(self, right, lcm)
         return self._lcm(right)
```

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
<div id="comment:7"></div>

Branch pushed to git repo; I updated commit sha1. New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/01cded97cb2a4cdbfef84f369a6217d8917edc8f"><code>01cded9</code></a></td><td><code>src/sage/structure/element.pyx: Fix up</code></td></tr></table>

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
Changed commit from **[`9911481`](https://github.com/sagemath/sagetrac-mirror/commit/9911481804b7b9fac03695d9d74126a0410c7317)** to **[`01cded9`](https://github.com/sagemath/sagetrac-mirror/commit/01cded97cb2a4cdbfef84f369a6217d8917edc8f)**

**Comment by mkoeppe** [comment]
<div id="comment:8" align="right">comment:8</div>

Thanks, fixed.

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
<div id="comment:10"></div>

Branch pushed to git repo; I updated commit sha1. New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/62032020ad6f73df11cdce1dbeec51aee35ed7cc"><code>6203202</code></a></td><td><code>sage.matrix: Consolidate imports from the same module</code></td></tr></table>

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
Changed commit from **[`01cded9`](https://github.com/sagemath/sagetrac-mirror/commit/01cded97cb2a4cdbfef84f369a6217d8917edc8f)** to **[`6203202`](https://github.com/sagemath/sagetrac-mirror/commit/62032020ad6f73df11cdce1dbeec51aee35ed7cc)**

**Comment by mkoeppe** [comment]
Changed author from **Alex Chandler** to **Alex Chandler, Matthias Koeppe**

**Comment by mkoeppe** [comment]
The branch is now on PR #35012
