### ISSUE TITLE
sagemath_doc_html depends on fpylll (for building)

### ISSUE THREAD

**Issue by dimpase** [sagemath/sage#34940]
<div id="comment:0"></div>

but this dependency is not listed. Thus, one can see a build error (I just run into it)

CC:  @mkoeppe @kiwifb @jhpalmieri

Component: **documentation**

Author: **Dima Pasechnik**

Reviewer: **Matthias Koeppe**

_Issue created by migration from https://trac.sagemath.org/ticket/34940_

**Comment by dimpase** [comment]
Commit: **[`8e3a310`](https://github.com/sagemath/sagetrac-mirror/commit/8e3a310df85b419eb16d822bf3ab3abbb630792c)**

**Comment by dimpase** [comment]
Author: **Dima Pasechnik**

**Comment by dimpase** [comment]
<div id="comment:1"></div>

New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/8e3a310df85b419eb16d822bf3ab3abbb630792c"><code>8e3a310</code></a></td><td><code>docbuilding needs fpylll</code></td></tr></table>

**Comment by dimpase** [comment]
Branch: **[u/dimpase/build/sagemath_doc_html_needs_fpylll](https://github.com/sagemath/sagetrac-mirror/tree/u/dimpase/build/sagemath_doc_html_needs_fpylll)**

**Comment by mkoeppe** [comment]
Reviewer: **Matthias Koeppe**

**Comment by mkoeppe** [comment]
<div id="comment:2" align="right">comment:2</div>

Thanks for catching this

**Comment by dimpase** [comment]
Several people have been bitten by this. @vbraun - please add this triviality to 9.8

**Comment by mkoeppe** [comment]
@vbraun Removed branch/commit because it has been replaced by PR #35011, which is already merged in 9.8.

**Comment by mkoeppe** [comment]
Merged in 10.0.beta0
