### ISSUE TITLE
sage.{algebras,combinat,matroids}: Replace imports from sage.*.all for namespace packages

### ISSUE THREAD

**Issue by mkoeppe** [sagemath/sage#34946]
<div id="comment:0"></div>

Using `./sage -fiximports` from #34945.

Also remove trailing whitespace in the affected files.

Part of Meta-ticket #32414

CC:  @alexchandler100 @fchapoton @tscrim

Component: **refactoring**

Author: **Alex Chandler, Matthias Koeppe**

Reviewer: **Travis Scrimshaw**

_Issue created by migration from https://trac.sagemath.org/ticket/34946_

**Comment by mkoeppe** [comment]
Branch: **[u/mkoeppe/sage__algebras_combinat_matroids___replace_imports_from_sage___all_for_namespace_packages](https://github.com/sagemath/sagetrac-mirror/tree/u/mkoeppe/sage__algebras_combinat_matroids___replace_imports_from_sage___all_for_namespace_packages)**

**Comment by mkoeppe** [comment]
Commit: **[`bdf2f33`](https://github.com/sagemath/sagetrac-mirror/commit/bdf2f331e31f0583a247409ef4b47beeb2b4cef7)**

**Comment by mkoeppe** [comment]
<div id="comment:3"></div>

New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/bdf2f331e31f0583a247409ef4b47beeb2b4cef7"><code>bdf2f33</code></a></td><td><code>sage -fiximports src/sage/algebras src/sage/combinat src/sage/matroids</code></td></tr></table>

**Comment by mkoeppe** [comment]
<div id="comment:5" align="right">comment:5</div>

Lint and Build&Test failures are unrelated.

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
Changed commit from **[`bdf2f33`](https://github.com/sagemath/sagetrac-mirror/commit/bdf2f331e31f0583a247409ef4b47beeb2b4cef7)** to **[`bd50b49`](https://github.com/sagemath/sagetrac-mirror/commit/bd50b49973d38726fee0fb92d99e62ab2ef31978)**

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
<div id="comment:7"></div>

Branch pushed to git repo; I updated commit sha1. New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/bd50b49973d38726fee0fb92d99e62ab2ef31978"><code>bd50b49</code></a></td><td><code>git grep -l -E ' (Q as QQ|Z as ZZ)' | xargs sed -i.bak 's/ Q as QQ/ QQ/;s/ Z as ZZ/ ZZ/;'</code></td></tr></table>

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
<div id="comment:8"></div>

Branch pushed to git repo; I updated commit sha1. New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/8e77597c00f4f9c563f658940e0df422b174e25b"><code>8e77597</code></a></td><td><code>sage.{algebras,combinat}: Consolidate imports from the same module</code></td></tr></table>

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
Changed commit from **[`bd50b49`](https://github.com/sagemath/sagetrac-mirror/commit/bd50b49973d38726fee0fb92d99e62ab2ef31978)** to **[`8e77597`](https://github.com/sagemath/sagetrac-mirror/commit/8e77597c00f4f9c563f658940e0df422b174e25b)**

**Comment by mkoeppe** [comment]
Changed author from **Alex Chandler** to **Alex Chandler, Matthias Koeppe**

**Comment by tscrim** [comment]
<div id="comment:10" align="right">comment:10</div>

LGTM.

**Comment by tscrim** [comment]
Reviewer: **Travis Scrimshaw**

**Comment by mkoeppe** [comment]
<div id="comment:11" align="right">comment:11</div>

Thanks!

**Comment by vbraun** [comment]
Merge conflict, please open GitHub PR to fix

**Comment by mkoeppe** [comment]
Removed the branch from the issue description; replaced by PR #35090
