### ISSUE TITLE
sage.{coding,groups}: Replace imports from sage.*.all for namespace packages

### ISSUE THREAD

**Issue by mkoeppe** [sagemath/sage#34948]
<div id="comment:0"></div>

Using `./sage -fiximports` from #34945.

Also remove trailing whitespace in the affected files.

Part of Meta-ticket #34201

CC:  @alexchandler100 @dimpase @fchapoton

Component: **refactoring**

Author: **Alex Chandler, Matthias Koeppe**

_Issue created by migration from https://trac.sagemath.org/ticket/34948_

**Comment by mkoeppe** [comment]
Branch: **[u/mkoeppe/sage__coding_groups___replace_imports_from_sage___all_for_namespace_packages](https://github.com/sagemath/sagetrac-mirror/tree/u/mkoeppe/sage__coding_groups___replace_imports_from_sage___all_for_namespace_packages)**

**Comment by mkoeppe** [comment]
<div id="comment:2"></div>

New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/3590a19184124a9ea5b29b28bf8d6e137e501e88"><code>3590a19</code></a></td><td><code>sage -fiximports src/sage/{coding,groups}</code></td></tr></table>

**Comment by mkoeppe** [comment]
Commit: **[`3590a19`](https://github.com/sagemath/sagetrac-mirror/commit/3590a19184124a9ea5b29b28bf8d6e137e501e88)**

**Comment by mkoeppe** [comment]
<div id="comment:3" align="right">comment:3</div>

Lint failure is unrelated.

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
Changed commit from **[`3590a19`](https://github.com/sagemath/sagetrac-mirror/commit/3590a19184124a9ea5b29b28bf8d6e137e501e88)** to **[`0b71513`](https://github.com/sagemath/sagetrac-mirror/commit/0b715137250bc3e0e0783b6e5e6e4fa50bf49bee)**

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
<div id="comment:5"></div>

Branch pushed to git repo; I updated commit sha1. New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/1121fa32c7d9c05eccc33861e280c9ef4a713e41"><code>1121fa3</code></a></td><td><code>git grep -l -E ' (Q as QQ|Z as ZZ)' | xargs sed -i.bak 's/ Q as QQ/ QQ/;s/ Z as ZZ/ ZZ/;'</code></td></tr><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/0d5a0e5b12a6c499c5b5dacd30410ba00a9ddbe5"><code>0d5a0e5</code></a></td><td><code>sage.{coding,groups}: Consolidate imports from the same module</code></td></tr><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/0b715137250bc3e0e0783b6e5e6e4fa50bf49bee"><code>0b71513</code></a></td><td><code>src/sage/coding/delsarte_bounds.py: Remove useless import in doctest</code></td></tr></table>

**Comment by mkoeppe** [comment]
Changed author from **Alex Chandler** to **Alex Chandler, Matthias Koeppe**

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
<div id="comment:7"></div>

Branch pushed to git repo; I updated commit sha1. This was a forced push. New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/018b7218311c4ff7731218ab2bc68bffe2b038d2"><code>018b721</code></a></td><td><code>sage -fiximports src/sage/{coding,groups}</code></td></tr><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/a9f06e87f1964574cbb9097f2c67a858286afc96"><code>a9f06e8</code></a></td><td><code>git grep -l -E ' (Q as QQ|Z as ZZ)' | xargs sed -i.bak 's/ Q as QQ/ QQ/;s/ Z as ZZ/ ZZ/;'</code></td></tr><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/00f6603ebc5081cbb4a2c9110c836d231b5feb49"><code>00f6603</code></a></td><td><code>sage.{coding,groups}: Consolidate imports from the same module</code></td></tr><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/f38e59f917d80932703f6b4f0ec6f90e08bfa82e"><code>f38e59f</code></a></td><td><code>src/sage/coding/delsarte_bounds.py: Remove useless import in doctest</code></td></tr></table>

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
Changed commit from **[`0b71513`](https://github.com/sagemath/sagetrac-mirror/commit/0b715137250bc3e0e0783b6e5e6e4fa50bf49bee)** to **[`f38e59f`](https://github.com/sagemath/sagetrac-mirror/commit/f38e59f917d80932703f6b4f0ec6f90e08bfa82e)**

**Comment by mkoeppe** [comment]
This was tested successfully in https://github.com/sagemath/sagetrac-mirror/actions/runs/4038221816 (before the migration), needs review.

**Comment by mkoeppe** [comment]
Removed branch from the issue description; replaced by PR #35099
