### ISSUE TITLE
changing some Cannot to cannot

### ISSUE THREAD

**Issue by fchapoton** [sagemath/sage#34944]
<div id="comment:0"></div>

in the error messages, to follow standard python practice

Component: **refactoring**

Author: **Frédéric Chapoton**

_Issue created by migration from https://trac.sagemath.org/ticket/34944_

**Comment by fchapoton** [comment]
<div id="comment:1"></div>

New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/3723f2d699daa6641c58b196ed10a195fa920ebd"><code>3723f2d</code></a></td><td><code>changing some Cannot to cannot in error messages</code></td></tr></table>

**Comment by fchapoton** [comment]
Branch: **[u/chapoton/34944](https://github.com/sagemath/sagetrac-mirror/tree/u/chapoton/34944)**

**Comment by fchapoton** [comment]
Commit: **[`3723f2d`](https://github.com/sagemath/sagetrac-mirror/commit/3723f2d699daa6641c58b196ed10a195fa920ebd)**

**Comment by mkoeppe** [comment]
<div id="comment:2" align="right">comment:2</div>

many doctest failures

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
Changed commit from **[`3723f2d`](https://github.com/sagemath/sagetrac-mirror/commit/3723f2d699daa6641c58b196ed10a195fa920ebd)** to **[`d7af60d`](https://github.com/sagemath/sagetrac-mirror/commit/d7af60d05d3ec88a6b8cf5c39d7273c51f9e6cd0)**

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
<div id="comment:3"></div>

Branch pushed to git repo; I updated commit sha1. New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/d7af60d05d3ec88a6b8cf5c39d7273c51f9e6cd0"><code>d7af60d</code></a></td><td><code>some fixes</code></td></tr></table>

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
<div id="comment:4"></div>

Branch pushed to git repo; I updated commit sha1. New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/4a5a470798e5688060a07a0d5057922633d9a917"><code>4a5a470</code></a></td><td><code>more fixes</code></td></tr></table>

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
Changed commit from **[`d7af60d`](https://github.com/sagemath/sagetrac-mirror/commit/d7af60d05d3ec88a6b8cf5c39d7273c51f9e6cd0)** to **[`4a5a470`](https://github.com/sagemath/sagetrac-mirror/commit/4a5a470798e5688060a07a0d5057922633d9a917)**

**Comment by mkoeppe** [comment]
Removed branch from issue description; replaced by PR #35007
