### ISSUE TITLE
sage.graphs: Replace imports from sage.*.all for namespace packages

### ISSUE THREAD

**Issue by mkoeppe** [sagemath/sage#34952]
<div id="comment:0"></div>

Using `./sage -fiximports` from #34945.

Also remove trailing whitespace in the affected files.

Part of Meta-ticket #34201

CC:  @alexchandler100 @dcoudert @dimpase

Component: **refactoring**

Author: **Alex Chandler**

Branch/Commit: **[u/mkoeppe/sage_graphs__replace_imports_from_sage___all_for_namespace_packages](https://github.com/sagemath/sagetrac-mirror/tree/u/mkoeppe/sage_graphs__replace_imports_from_sage___all_for_namespace_packages) @ [`180c16b`](https://github.com/sagemath/sagetrac-mirror/commit/180c16b6152b0b57bb1244abb0a55f79fda95fb7)**

Reviewer: **David Coudert**

_Issue created by migration from https://trac.sagemath.org/ticket/34952_

**Comment by mkoeppe** [comment]
Branch: **[u/mkoeppe/sage_graphs__replace_imports_from_sage___all_for_namespace_packages](https://github.com/sagemath/sagetrac-mirror/tree/u/mkoeppe/sage_graphs__replace_imports_from_sage___all_for_namespace_packages)**

**Comment by mkoeppe** [comment]
<div id="comment:2"></div>

New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/180c16b6152b0b57bb1244abb0a55f79fda95fb7"><code>180c16b</code></a></td><td><code>sage -fiximports src/sage/graphs</code></td></tr></table>

**Comment by mkoeppe** [comment]
Commit: **[`180c16b`](https://github.com/sagemath/sagetrac-mirror/commit/180c16b6152b0b57bb1244abb0a55f79fda95fb7)**

**Comment by dcoudert** [comment]
<div id="comment:3" align="right">comment:3</div>

LGTM.

**Comment by dcoudert** [comment]
Reviewer: **David Coudert**

**Comment by mkoeppe** [comment]
Merged in 10.0.beta0
