### ISSUE TITLE
use NTL's MinPolyMod() for more rings

### ISSUE THREAD

**Issue by yyyyx4** [sagemath/sage#34958]
<div id="comment:0"></div>

Follow-up to #34906: Here we implement the same functionality for rings of the form `(ℤ/m)[x]` with `m ≥ 3`.

CC:  @fchapoton

Component: **algebra**

Author: **Lorenz Panny**

_Issue created by migration from https://trac.sagemath.org/ticket/34958_

**Comment by mkoeppe** [comment]
Removed the branch from the issue description; replaced by PR #34966
