### ISSUE TITLE
sage.schemes:  Replace imports from sage.*.all for namespace packages

### ISSUE THREAD

**Issue by mkoeppe** [sagemath/sage#34951]
<div id="comment:0"></div>

Using `./sage -fiximports` from #34945.

Also remove trailing whitespace in the affected files.

Part of Meta-ticket #34201

CC:  @alexchandler100 @bhutz @yyyyx4

Component: **refactoring**

Author: **Alex Chandler, Matthias Koeppe**

_Issue created by migration from https://trac.sagemath.org/ticket/34951_

**Comment by mkoeppe** [comment]
Branch: **[u/mkoeppe/sage_schemes___replace_imports_from_sage___all_for_namespace_packages](https://github.com/sagemath/sagetrac-mirror/tree/u/mkoeppe/sage_schemes___replace_imports_from_sage___all_for_namespace_packages)**

**Comment by mkoeppe** [comment]
Commit: **[`dca994a`](https://github.com/sagemath/sagetrac-mirror/commit/dca994a4aadc4a8317bde37df4486eed0abf1179)**

**Comment by mkoeppe** [comment]
<div id="comment:2"></div>

New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/dca994a4aadc4a8317bde37df4486eed0abf1179"><code>dca994a</code></a></td><td><code>src/sage/schemes: Manual fixes to imports</code></td></tr></table>

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
Changed commit from **[`dca994a`](https://github.com/sagemath/sagetrac-mirror/commit/dca994a4aadc4a8317bde37df4486eed0abf1179)** to **[`aefcd52`](https://github.com/sagemath/sagetrac-mirror/commit/aefcd5296c58a9d4afaa06bd0654cf13b3d01a90)**

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
<div id="comment:3"></div>

Branch pushed to git repo; I updated commit sha1. This was a forced push. New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/aefcd5296c58a9d4afaa06bd0654cf13b3d01a90"><code>aefcd52</code></a></td><td><code>sage -fiximports src/sage/schemes</code></td></tr></table>

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
<div id="comment:5"></div>

Branch pushed to git repo; I updated commit sha1. New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/e545deaaf7864321f4c10eb786aeea171215c496"><code>e545dea</code></a></td><td><code>git grep -l -E ' (Q as QQ|Z as ZZ)' | xargs sed -i.bak 's/ Q as QQ/ QQ/;s/ Z as ZZ/ ZZ/;'</code></td></tr><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/44af9b91712a6628d80aa8d872327e0d48b2d7c3"><code>44af9b9</code></a></td><td><code>sage.schemes: Consolidate imports from the same module</code></td></tr></table>

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
Changed commit from **[`aefcd52`](https://github.com/sagemath/sagetrac-mirror/commit/aefcd5296c58a9d4afaa06bd0654cf13b3d01a90)** to **[`44af9b9`](https://github.com/sagemath/sagetrac-mirror/commit/44af9b91712a6628d80aa8d872327e0d48b2d7c3)**

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
Changed commit from **[`44af9b9`](https://github.com/sagemath/sagetrac-mirror/commit/44af9b91712a6628d80aa8d872327e0d48b2d7c3)** to **[`acf17b6`](https://github.com/sagemath/sagetrac-mirror/commit/acf17b6cfc29e31ed8b0d84a6fdefd1891b7c2a7)**

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
<div id="comment:6"></div>

Branch pushed to git repo; I updated commit sha1. This was a forced push. New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/d52ad2cae40b3f4dff3580bb072d794fc27ee3ff"><code>d52ad2c</code></a></td><td><code>sage -fiximports src/sage/schemes</code></td></tr><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/4a7bfc169589eef4016b93eeabdc01f7165f1c31"><code>4a7bfc1</code></a></td><td><code>git grep -l -E ' (Q as QQ|Z as ZZ)' | xargs sed -i.bak 's/ Q as QQ/ QQ/;s/ Z as ZZ/ ZZ/;'</code></td></tr><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/acf17b6cfc29e31ed8b0d84a6fdefd1891b7c2a7"><code>acf17b6</code></a></td><td><code>sage.schemes: Consolidate imports from the same module</code></td></tr></table>

**Comment by mkoeppe** [comment]
Changed author from **Alex Chandler** to **Alex Chandler, Matthias Koeppe**

**Comment by mkoeppe** [comment]
The attached branch is replaced by PR #35033.
