### ISSUE TITLE
sage.{functions,interfaces,symbolic}: Replace imports from sage.*.all for namespace packages

### ISSUE THREAD

**Issue by mkoeppe** [sagemath/sage#34954]
<div id="comment:0"></div>

Using `./sage -fiximports` from #34945.

Also remove trailing whitespace in the affected files.

Part of Meta-ticket #34201

CC:  @alexchandler100 @dimpase @DaveWitteMorris

Component: **refactoring**

Author: **Alex Chandler, Matthias Koeppe**

_Issue created by migration from https://trac.sagemath.org/ticket/34954_

**Comment by mkoeppe** [comment]
Branch: **[u/mkoeppe/sage__functions_interfaces_symbolic___replace_imports_from_sage___all_for_namespace_packages](https://github.com/sagemath/sagetrac-mirror/tree/u/mkoeppe/sage__functions_interfaces_symbolic___replace_imports_from_sage___all_for_namespace_packages)**

**Comment by mkoeppe** [comment]
Commit: **[`21148e5`](https://github.com/sagemath/sagetrac-mirror/commit/21148e59393ea5c503f856074b59bd27e4cec156)**

**Comment by mkoeppe** [comment]
<div id="comment:2"></div>

New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/21148e59393ea5c503f856074b59bd27e4cec156"><code>21148e5</code></a></td><td><code>sage -fiximports src/sage/{functions,interfaces,symbolic}</code></td></tr></table>

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
<div id="comment:4"></div>

Branch pushed to git repo; I updated commit sha1. New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/2870ffb3f904535c305a7b34a34b85d49c62ff97"><code>2870ffb</code></a></td><td><code>src/sage/interfaces/sage0.py: Hide a legitimate .all import from relint</code></td></tr><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/70e5c66306eedd1ca0a6f45f6ba277916eb64743"><code>70e5c66</code></a></td><td><code>sage.{functions,interfaces,symbolic}: Consolidate imports from the same module</code></td></tr><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/7305a7c18999526cb4f1238dec15cf7589225ee6"><code>7305a7c</code></a></td><td><code>git grep -l -E ' (Q as QQ|Z as ZZ)' | xargs sed -i.bak 's/ Q as QQ/ QQ/;s/ Z as ZZ/ ZZ/;'</code></td></tr></table>

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
Changed commit from **[`21148e5`](https://github.com/sagemath/sagetrac-mirror/commit/21148e59393ea5c503f856074b59bd27e4cec156)** to **[`7305a7c`](https://github.com/sagemath/sagetrac-mirror/commit/7305a7c18999526cb4f1238dec15cf7589225ee6)**

**Comment by mkoeppe** [comment]
Changed author from **Alex Chandler** to **Alex Chandler, Matthias Koeppe**

**Comment by mkoeppe** [comment]
This was successfully tested (before the migration) in https://github.com/sagemath/sagetrac-mirror/actions/runs/4038909985

**Comment by mkoeppe** [comment]
@fchapoton Please review

**Comment by mkoeppe** [comment]
Removed branch from issue description; replaced by PR #35105
