### ISSUE TITLE
sage.{topology,homology}: Replace imports from sage.*.all for namespace packages

### ISSUE THREAD

**Issue by mkoeppe** [sagemath/sage#34953]
<div id="comment:0"></div>

Using `./sage -fiximports` from #34945.

Also remove trailing whitespace in the affected files.

Part of Meta-ticket #34201

CC:  @alexchandler100 @jhpalmieri

Component: **refactoring**

Author: **Alex Chandler**

_Issue created by migration from https://trac.sagemath.org/ticket/34953_

**Comment by mkoeppe** [comment]
Branch: **[u/mkoeppe/sage__topology_homology___replace_imports_from_sage___all_for_namespace_packages](https://github.com/sagemath/sagetrac-mirror/tree/u/mkoeppe/sage__topology_homology___replace_imports_from_sage___all_for_namespace_packages)**

**Comment by mkoeppe** [comment]
<div id="comment:2"></div>

New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/301a0d1f4568ae4d17c44103d0d17ea93085f5f0"><code>301a0d1</code></a></td><td><code>sage -fiximports src/sage/{topology,homology}</code></td></tr></table>

**Comment by mkoeppe** [comment]
Commit: **[`301a0d1`](https://github.com/sagemath/sagetrac-mirror/commit/301a0d1f4568ae4d17c44103d0d17ea93085f5f0)**

**Comment by jhpalmieri** [comment]
This looks good to me. I don't see a pull request attached to it, so do I need to create one, or somehow link to the existing branch and/or commit?

**Comment by mkoeppe** [comment]
Thanks!

I think @vbraun will be able to merge the positively reviewed issues with attached branches.

**Comment by mkoeppe** [comment]
Removed branch from the issue description; replaced by PR #35098
