### ISSUE TITLE
sage.{finance,interacts,libs,numerical,stats,tests}: Replace imports from sage.*.all for namespace packages

### ISSUE THREAD

**Issue by mkoeppe** [sagemath/sage#34957]
<div id="comment:0"></div>

Part of meta-ticket #34201

CC:  @alexchandler100

Component: **refactoring**

Author: **Alex Chandler**

_Issue created by migration from https://trac.sagemath.org/ticket/34957_

**Comment by mkoeppe** [comment]
Branch: **[u/mkoeppe/sage__finance_interacts_libs_numerical_statistics_tests___replace_imports_from_sage___all_for_namespace_packages](https://github.com/sagemath/sagetrac-mirror/tree/u/mkoeppe/sage__finance_interacts_libs_numerical_statistics_tests___replace_imports_from_sage___all_for_namespace_packages)**

**Comment by mkoeppe** [comment]
<div id="comment:2"></div>

New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/1e88c12c13447aa29413bc69bbfe33cfe50a5335"><code>1e88c12</code></a></td><td><code>sage -fiximports src/sage/{finance,interacts,libs,numerical,statistics,tests}</code></td></tr><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/572896dfe19ab88967deefbebcc9be55d669a8d2"><code>572896d</code></a></td><td><code>src/sage/{numerical,tests}: Manual fixes to imports</code></td></tr></table>

**Comment by mkoeppe** [comment]
Commit: **[`572896d`](https://github.com/sagemath/sagetrac-mirror/commit/572896dfe19ab88967deefbebcc9be55d669a8d2)**

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
Changed commit from **[`572896d`](https://github.com/sagemath/sagetrac-mirror/commit/572896dfe19ab88967deefbebcc9be55d669a8d2)** to **[`965dfc6`](https://github.com/sagemath/sagetrac-mirror/commit/965dfc61eddd9cbe290d8449543ec77afc867c73)**

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
<div id="comment:3"></div>

Branch pushed to git repo; I updated commit sha1. New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/965dfc61eddd9cbe290d8449543ec77afc867c73"><code>965dfc6</code></a></td><td><code>sage -fiximports src/sage/stats</code></td></tr></table>

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
<div id="comment:5"></div>

Branch pushed to git repo; I updated commit sha1. New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/21b94bab1a499941c94a2dc00300a2c7bac79bde"><code>21b94ba</code></a></td><td><code>src/sage/libs/giac/auto-methods.pxi: Back out whitespace changes in this autogenerated file</code></td></tr></table>

**Comment by 7ed8c4ca-6d56-4ae9-953a-41e42b4ed313** [comment]
Changed commit from **[`965dfc6`](https://github.com/sagemath/sagetrac-mirror/commit/965dfc61eddd9cbe290d8449543ec77afc867c73)** to **[`21b94ba`](https://github.com/sagemath/sagetrac-mirror/commit/21b94bab1a499941c94a2dc00300a2c7bac79bde)**

**Comment by mkoeppe** [comment]
<div id="comment:7" align="right">comment:7</div>

This was tested before the migration in https://github.com/sagemath/sagetrac-mirror/actions/runs/4039609960/jobs/6944514787
The doctest failure in `sage/schemes/elliptic_curves/ell_number_field.py` is unrelated (it's #34959)

**Comment by mkoeppe** [comment]
Removed branch from issue description; replaced by PR #35107
