### ISSUE TITLE
"Codecov Report" automatic comment is extravagant

### ISSUE THREAD

**Issue by kwankyu** [sagemath/sage#35016]
Currently, a "Codecov Report" is being automatically added to every PR. While most of the time the information from the comment is not that important, the comment takes (almost forces) attention from the readers of the PR.

I wish that that is moved to the checks, if possible, or be turned off until we find a solution that makes it quiet.

**Comment by tobiasdiez** [comment]
It's possible to config this:
https://docs.codecov.com/docs/pull-request-comments
https://docs.codecov.com/docs/github-checks

**Comment by dimpase** [comment]
> It's possible to config this:

Is this something that can be done on the repo level?
Then it should be done...

**Comment by kwankyu** [comment]
I wish that the codecov comment is replaced with a one-line github-action comment, just like the documentation preview comment.
