### ISSUE TITLE
arrow((0,0), (0,0), linestyle='dashed') raises list index out of range

### ISSUE THREAD

**Issue by seblabbe** [sagemath/sage#35031]
With SageMath version 9.8.beta1, Release Date: 2022-09-29, this works:

```
sage: arrow((0,0), (0,0))
Launched png viewer for Graphics object consisting of 1 graphics primitive
```

but this is broken:

```
sage: arrow((0,0), (0,0), linestyle='dashed')
/home/slabbe/GitBox/sage/src/sage/repl/rich_output/display_manager.py:610: RichReprWarning: Exception in _rich_repr_ while displaying object: list index out of range
  warnings.warn(
Graphics object consisting of 1 graphics primitive
```

**Comment by aniketwdubey** [comment]
@seblabbe One way to work around this issue is to use the linetypes option instead of linestyle to specify the type of line used for the arrow. 
sage: arrow((0,0), (0,0), linetypes=['dashed'])

**Comment by videlec** [comment]
Are `linestyle` and `linetypes` equivalent? I am confused by having two arguments having the same purpose, one broken and the other not...
