### ISSUE TITLE
Replace "t: " prefix with "a: " in labels

### ISSUE THREAD

**Issue by kwankyu** [sagemath/sage#35041]
As we experienced the labels for some days by now,  

one more change to consider about already beautiful labels, *before too late*, is to replace "t: " prefix with "a: ". Then the labels are ordered nicely: a typical PR would have labels like

Blah blah "a: enhancement" "c: linear algebra" "p: major / 3"  "s: needs review" 
Blah blah "a: feature" "c: number theory" "p: minor / 4" "s: needs work"
Blah blah "a: bug" "c: documentation" "p: trivial / 5" "r: wontfix"

*Hence the status labels prefixed with "s: " are placed at the end!*

We may read "a: " prefix as *aim" while  "t: " represents *type*. Thus "type: enhancement" changes to "aim: enhancement" 

Note that one may read "a: " as an indefinite article "a" :-)

----

The previous suggestion was to change "t: " with "q: ", which no one liked. Hence this new proposal.

**Comment by mantepse** [comment]
maybe "r:" for "request" and "d: wontfix" for "decision".  A side effect would be that the decision comes right after the component.

**Comment by mkoeppe** [comment]
Let me point out again (for those who did not see these discussions before) that it's _already too late_ for such changes; see https://github.com/sagemath/trac-to-github/issues/112#issuecomment-1382345536

**Comment by kwankyu** [comment]
In the previous discussions, @mkoeppe you said that It  would be too late to change colors, and consequently the *categories* of labels because the categories are implied by the colors. But we could still make changes to names. No?

Anyway, I just tested renaming and recoloring of labels. Both affect correctly to all issues whether open or closed. Is it correct what you said before? Issues converted from Trac would be different?

I am sore to suggest a change to labels after the migration and to lose "t: " prefix for *type* labels. But it seems more important to make labels useful as far as possible because we should live with them forever.

Note: somewhere else I had suggested to change "s: " to "z: " for the same effect.

**Comment by mkoeppe** [comment]
Yes, the current label is changed. But the recorded label-change events keep the old label (text and color). https://github.com/sagemath/trac-to-github/issues/99#issuecomment-1379693577 has the screenshots that illustrate this.

**Comment by kwankyu** [comment]
The colors and the names are changed also for label-change events for new labels. 

You are saying that the *events recorded during the migration* will not change (because the name and the color is baked into the event)?

**Comment by mkoeppe** [comment]
That's right. Likewise for the label-events that have already been made interactively now.

**Comment by kwankyu** [comment]
Sorry that I am repeating. 

> Likewise for the label-events that have already been made interactively now.

Interactively? Then they are created after the migration. They will be changed. I tested this. No?

**Comment by mkoeppe** [comment]
It has nothing to do with the migration. The screenshot that I linked did not use migration.

**Comment by kwankyu** [comment]
I am confused. Would you check it in GitHub.com again?

**Comment by kwankyu** [comment]
I tested it again in my repo. The names and the colors in label-change events are all changed.

**Comment by mkoeppe** [comment]
Hm... interesting.

**Comment by kwankyu** [comment]
We can experiment with the "sagemath/sage" repo. We can change, see the effect, and change back. I think this is safe.

**Comment by kwankyu** [comment]
> maybe "r:" for "request" and "d: wontfix" for "decision". A side effect would be that the decision comes right after the component.

The side effect seems bad. 

Because the *decision* *resolution* labels will be added instead of "positive review" *state* label, we may give to them "s: " prefix the same with *state* labels. Perhaps this was already suggested by @tobiasdiez before, If I remember correctly.

All this discussion assumes that it is not *too late* :-)

**Comment by kwankyu** [comment]
> We can experiment with the "sagemath/sage" repo. We can change, see the effect, and change back. I think this is safe.

@mkoeppe 

Regardless of this issue, would you check whether we have a full control on the label names and colors over all issues and labeling events?

**Comment by kwankyu** [comment]
Closing as no one cares.
