### ISSUE TITLE
Using Flask with sagemath

### ISSUE THREAD

**Issue by Eloitor** [sagemath/sage#35051]
### Is there an existing issue for this?

- [X] I have searched the existing issues for a bug report that matches the one I want to file, without success.

### Did you read the documentation and troubleshoot guide?

- [X] I have read the documentation and troubleshoot guide

### Environment

```markdown
- **OS**: Void Linux x86_64-glibc
- **Sage Version**: version 9.7, Release Date: 2022-09-19
```

### Steps To Reproduce

1. Install Flask
2. Create this example file

```
from flask import Flask

app = Flask(__name__)

@app.route('/')
def index():
    F = NumberField(x**2-x-1, name='w')
    w = F.gen()
    I = Ideal(F, 1)
    print(F)        # This is fine
    print(I)        # This gives an error
    
    return F.__str__()

if __name__ == '__main__':
    app.run()
```

3. run this file with sagemath, and access http://127.0.0.1:5000/ on a browser

### Expected Behavior

The field and the ideal are printed in the terminal. The field is shown in the browser.

### Actual Behavior

The field is printed in the terminal, but then an error occurs.

This is the output of `sage test_flask.sage &> output.txt`:

[output.txt](https://github.com/sagemath/sage/files/10699583/output.txt)

**Comment by mezzarobba** [comment]
It works if you change the last line to `app.run(threaded=False)`.

After talking to @videlec who discussed the issue with Bill Alombert before, my understanding is that we are still far from being able to use pari from multiple threads in sage. (See also sagemath/cypari2#116.)

**Comment by Eloitor** [comment]
Thanks for the hint! The line should be changed to `app.run(threaded=False)`. Should I close this issue?

**Comment by mezzarobba** [comment]
> Thanks for the hint! The line should be changed to `app.run(threaded=False)`. 

Yes, thanks.

> Should I close this issue?

I don't think it makes sense to keep it open.
