### ISSUE TITLE
pkg-config should be `_bootstrap`, not `_prereq`, on all distros

### ISSUE THREAD

**Issue by dimpase** [sagemath/sage#35088]
### Is there an existing issue for this?

- [X] I have searched the existing issues for a bug report that matches the one I want to file, without success.

### Did you read the documentation and troubleshoot guide?

- [X] I have read the documentation and troubleshoot guide

### Environment

- **OS**: Manjaro Linux (sort of arch linux)
- **Sage Version**: 9.8

```
$ git grep pkg-config | grep build/pkgs/_
build/pkgs/_bootstrap/distros/arch.txt:# Otherwise: Error: could not locate the pkg-config autoconf macros. These are
build/pkgs/_bootstrap/distros/arch.txt:pkg-config
build/pkgs/_bootstrap/distros/debian.txt:pkg-config
build/pkgs/_bootstrap/distros/fedora.txt:pkg-config
build/pkgs/_bootstrap/distros/freebsd.txt:autoconf automake libtool pkg-config
build/pkgs/_bootstrap/distros/homebrew.txt:autoconf automake libtool pkg-config
build/pkgs/_bootstrap/distros/nix.txt:autoconf automake libtool pkg-config
build/pkgs/_prereq/distros/conda.txt:pkg-config
build/pkgs/_prereq/distros/slackware.txt:pkg-config
build/pkgs/_prereq/distros/void.txt:pkg-config
```

**Comment by mkoeppe** [comment]
No, pkg-config is not a required prereq. Sage can build its own pkg-config. Only the bootstrap phase requires it.
I don't know why it is listed in `_prereq`, not bootstrap, for these 3.

**Comment by dimpase** [comment]
but not having `pkg-config` at configure time is silly. It makes perhaps 50% or more of our `spkf-configure` tests useless.

**Comment by dimpase** [comment]
perhaps there should be an advice, like "run `make pkgconf && ./configure` if it's not installed.

**Comment by mkoeppe** [comment]
We already issue advice on what packages should be installed at the end of configure.

**Comment by mkoeppe** [comment]
> like "run `make pkgconf && ./configure` if it's not installed.

What? This makes no sense

**Comment by dimpase** [comment]
> This makes no sense

well, I meant to say, making the resutling `pkg-config` available to `./configure`, as well. 

Anyhow, it's very tempting to just make pkg-config a global pre-req. 
To hell with purist hipsters who want Sage to build seamlessly on their very bare macOS laptops...

**Comment by mkoeppe** [comment]
> I meant to say, making the resutling `pkg-config` available to `./configure`, as well.

This also makes no sense because the Sage-installed pkg-config cannot magically obtain the pc files of system packages.

**Comment by dimpase** [comment]
this is still unresolved. Why we require pkg-config on some platforms, where it is available, but not on the other ones?

**Comment by mkoeppe** [comment]
Edited the issue description.

**Comment by dimpase** [comment]
> pkg-config cannot magically obtain the pc files of system packages

if they were installed, then why not? Typically a library would install a .pc file regardless of availability of pkg-config, and
then pkg-config has a list of pre-defined locations to look for .pc files, I suppose it includes `/usr/lib*/` etc. At least that's what an experiment 
```
$ make pkgconf # Sage's pkg-config
$ ./local/bin/pkg-config --list-all | wc -l
205
$ pkg-config --list-all | wc -l
193
```
shows - a long list,  a bit longer than shown by  system's ` pkg-config  - as it also picks up installed by Sage .pc files.

**Comment by mkoeppe** [comment]
> if they were installed, then why not?

Because it cannot (and should not) guess the system location.

**Comment by dimpase** [comment]
> > if they were installed, then why not?
> 
> Because it cannot (and should not) guess the system location.

but it does guess it. And we don't tell it not to do so. So it seems to be just wishful thinking on your side here.

**Comment by mkoeppe** [comment]
No. Currently we have a funny script `build/pkgs/pkgconf/patches/pkg-config.in` that gets installed and that delegates to system pkg-config if there is a system pkg-config.

**Comment by dimpase** [comment]
it's not funny, it's evil rotten Easter egg - cause it gets installed after the build is done, by `build/pkgs/pkgconf/spkg-postinst.in`. The only trace in log is
```
[pkgconf-1.8.0] Running post-install script for pkgconf-1.8.0.
[pkgconf-1.8.0] pkg-config.out -> /home/dimpase/work/software/sage/local/bin/pkg-config
```
no explanation, nothing. Coding style "read the code, sucker" :-)
