### ISSUE TITLE
--with-system-python3 seems to be a noop

### ISSUE THREAD

**Issue by dimpase** [sagemath/sage#35089]
### Is there an existing issue for this?

- [X] I have searched the existing issues for a bug report that matches the one I want to file, without success.

### Did you read the documentation and troubleshoot guide?

- [X] I have read the documentation and troubleshoot guide

### Environment

```markdown
**multiplatform**

`--with-system-python3` confiigure option should be processed somewhere, I guess in 
`build/pkgs/python3/spkg-configure.m4` - but it's not there.
```

### Expected Behavior

`--with-system-python3=no` should have an effect

### Actual Behavior

no effect

### Additional Information

see [sage-release report](https://groups.google.com/d/msgid/sage-release/75d380a7-ded5-4925-aa9b-88a00752d69an%40googlegroups.com).

**Comment by dimpase** [comment]
@mkoeppe - any idea?

**Comment by mkoeppe** [comment]
User error, nothing to fix - see https://groups.google.com/g/sage-release/c/9qEMm1dwED8/m/xDGPffSFAgAJ

**Comment by dimpase** [comment]
shouldn't an unrecognised option throw an error, or at least a bigger warning?

**Comment by mkoeppe** [comment]
It's standard behavior of autoconf-generated `configure` scripts. One can use `--disable-option-checking` to suppress the warning, but AFAIK there is no option to escalate it to an error.

**Comment by dimpase** [comment]
$t^2$
