### ISSUE TITLE
remove ci-cygwin workflow from the standard CI

### ISSUE THREAD

**Issue by dimpase** [sagemath/sage#35134]
### Is there an existing issue for this?

- [X] I have searched the existing issues for a bug report that matches the one I want to file, without success.

### Did you read the documentation and troubleshoot guide?

- [X] I have read the documentation and troubleshoot guide

### Environment

```markdown
GitHub
```

### Expected Behavior

If I change a branch in a PR, only meaningful, non-broken, CI should start.

### Actual Behavior

If I change a branch in a PR, I almost immeduately get
```
[sagemath/sage] PR run failed: .github/workflows/ci-cygwin-....
```
messages (2, at least).

### Additional Information

I suppose something is broken there, badly - should we remove these useless tests?

**Comment by mkoeppe** [comment]
#35052 fixes it and just needs to be merged.
