### ISSUE TITLE
Set() comparison for (non)equality broken

### ISSUE THREAD

**Issue by dimpase** [sagemath/sage#35178]
### Is there an existing issue for this?

- [X] I have searched the existing issues for a bug report that matches the one I want to file, without success.

### Did you read the documentation and troubleshoot guide?

- [X] I have read the documentation and troubleshoot guide

### Environment

```markdown
** Sage 10.0.betas ** and earlier
```

### Steps To Reproduce

```
sage: L = {0}
sage: L == Set(L)
True
sage: L != Set(L)
True
```

### Expected Behavior

`!=` should be the negation of `==`

### Actual Behavior

both `==` and `!=` comparisons being `True` is pretty bad

**Comment by jhpalmieri** [comment]
This might fix it:

```
diff --git a/src/sage/sets/set.py b/src/sage/sets/set.py
index b988525a880..5b7ab78be2e 100644
--- a/src/sage/sets/set.py
+++ b/src/sage/sets/set.py
@@ -1064,7 +1064,8 @@ class Set_object_enumerated(Set_object):
         """
         if not isinstance(other, Set_object_enumerated):
             if isinstance(other, (set, frozenset)):
-                return self.set() == other
+                if self.set() == other:
+                    return rich_to_bool(op, 0)
             return NotImplemented
         if self.set() == other.set():
             return rich_to_bool(op, 0)

```
