### ISSUE TITLE
function help such as tan? in the docker build causes segfault

### ISSUE THREAD

**Issue by chenri2006** [sagemath/sage#35209]
### Is there an existing issue for this?

- [X] I have searched the existing issues for a bug report that matches the one I want to file, without success.

### Did you read the documentation and troubleshoot guide?

- [X] I have read the documentation and troubleshoot guide

### Environment

```markdown
- **OS**: almalinux 9, centos 7
- **Sage Version**: 9.7, 9.8, latest
```

### Steps To Reproduce

$ docker run -it --rm sagemath/sagemath                                                                                   
┌────────────────────────────────────────────────────────────────────┐
│ SageMath version 9.7, Release Date: 2022-09-19                     │
│ Using Python 3.10.5. Type "help()" for help.                       │
└────────────────────────────────────────────────────────────────────┘
sage: tan?

### Expected Behavior

This happens for the public sagemath/sagemath docker image as well as the image I built from source, using version 9.8 and develop version. The correct behavior from sagecell or cocalc is just the output of the function description for 'tan'.

### Actual Behavior

The actual behavior is a trace stack for a segfault:

------------------------------------------------------------------------
/home/sage/sage/local/var/lib/sage/venv-python3.10.5/lib/python3.10/site-packages/cysignals/signals.cpython-310-x86_64-linux-gnu.so(+0x8704)[0x7fc957017704]
...
/home/sage/sage/local/var/lib/sage/venv-python3.10.5/lib/libpython3.10.so.1.0(Py_BytesMain+0x5e)[0x7fc957aa4b3e]
/lib/x86_64-linux-gnu/libc.so.6(+0x29d90)[0x7fc9576bfd90]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0x80)[0x7fc9576bfe40]
python3(_start+0x25)[0x555e0ef6c095]
------------------------------------------------------------------------
Attaching gdb to process id 141.
Cannot find gdb installed
GDB is not installed.
Install gdb for enhanced tracebacks.
------------------------------------------------------------------------
Unhandled SIGSEGV: A segmentation fault occurred.
This probably occurred because a *compiled* module has a bug
in it and is not properly wrapped with sig_on(), sig_off().
Python will now terminate.
------------------------------------------------------------------------
Segmentation fault (core dumped)

**Comment by mkoeppe** [comment]
Closing as outdated
