### ISSUE TITLE
Polyhedron with minimize = false

### ISSUE THREAD

**Issue by raphaelsulzer** [sagemath/sage#35226]
### Is there an existing issue for this?

- [x] I have searched the existing issues for a bug report that matches the one I want to file, without success.

### Problem Description

Hi, I newly discovered this great library. It is very useful and well documented. Thank you contributors!

In my application I am intersecting [polyedra](https://doc.sagemath.org/html/en/reference/discrete_geometry/sage/geometry/polyhedron/constructor.html) with `base_ring=QQ`. I need additional vertices in my polyhedrons, that lie on the convex hull but are redundant. The documentation mentions the unused `minimize = false` option when initializing a polyhedron. Is there any type in sage that supports my usecase? Ideally, those redundant vertices should also be preserved after intersection operations.
Or do the backend computation not support such behaviour?

### Proposed Solution

Implement `minimize = false` for the polyhedron class.

### Alternatives Considered

I keep a separate list of vertices, but I cannot perform intersection operations with this list.

**Comment by mkoeppe** [comment]
Keeping redundant points is not supported by any of our polyhedral computation backends, as far as I know.

It sounds to me like you may want to just define a class that stores a pair (Polyhedron, Set of additional points).

Or maybe `PolyhedralComplex` is what you're looking for.

**Comment by raphaelsulzer** [comment]
OK, I understand. Thank you!
