### ISSUE TITLE
in ubuntu 22.04 these instructions don't work: "sudo apt-get install  sagemath sagemath-doc-en sagemath-jupyter"

### ISSUE THREAD

**Issue by williamstein** [sagemath/sage#35259]
When I found this page

https://doc.sagemath.org/html/en/reference/spkg/_sagemath.html

I immediately thought... "I bet these don't work".  The only one I wanted to try was Ubuntu with the latest version, and indeed it didn't work.  The instructions are 
```
sudo apt-get install  sagemath sagemath-doc-en sagemath-jupyter
```
but "sagemath-doc-en" has to be replaced by "sagemath-doc".  

I wonder if the top of the page should just say "The package names may change slightly or be deprecated and we do not regularly test them, so please pay attention to the output of your package manager."

I also noticed that the sentence at the bottom seem to be missing a period. Also, the trac link is broken, since it is just `https://trac.sagemath.org/27330` instead of `https://trac.sagemath.org/ticket/27330`.  Was that a standard redirect with trac (to not have /ticket" or was it a mistake in this particular link?  I have no idea, but if it is common, then I can add new redirects [here](https://github.com/sagemath/trac.sagemath.org). 

<img width="949" alt="image" src="https://user-images.githubusercontent.com/1276278/224374942-d2e8cf0c-e12d-43c8-956b-974c19268106.png">

**Comment by mkoeppe** [comment]
Just send a PR for the relevant file in https://github.com/sagemath/sage/tree/develop/build/pkgs/_sagemath/distros

**Comment by mkoeppe** [comment]
> I wonder if the top of the page should just say "The package names may change slightly or be deprecated and we do not regularly test them

We use this package info also for setting up devcontainers, so this info has to be maintained. It's currently not tested automatically.

**Comment by williamstein** [comment]
> We use this package info also for setting up devcontainers, so this info has to be maintained. It's currently not tested automatically.

In that case, we could add clear directions somewhere in bold saying how to report a problem when you try to copy/paste the directions and they don't work.  I was not in any way surprised when the Ubuntu install line didn't work on the current LTS version of Ubuntu -- these things tend to be fragile.

**Comment by mkoeppe** [comment]
> the trac link is broken, since it is just `https://trac.sagemath.org/27330` instead of `https://trac.sagemath.org/ticket/27330`.

My guess is that this was rewritten by @haraldschilly's postprocessing scripts. In the source code, we had `/ticket/`. It's all history now, of course, as #35015 has updated all links
