### ISSUE TITLE
`sage.plot.animate`: Use `Executable.absolute_filename`, pass configured FFMPEG via sage-conf

### ISSUE THREAD

**Issue by beew** [sagemath/sage#35255]
Part of:
- #30818

----
Original issue description:

I have compiled sage with a local version of ffmpeg successfully by issuing these commands before running configure

```
export PATH="$HOME/opt/ffmpeg6/bin:$PATH"
export LD_LIBRARY_PATH="$HOME/opt/ffmpeg6/lib:$LD_LIBRARY_PATH"
export PKG_CONFIG_PATH="$HOME/opt/ffmpeg6/lib/pkgconfig:$PKG_CONFIG_PATH"

```
 Now I would like to make sure that sage respects these environmental variables at run time. Should I put them in .sage/sagerc?
 
 Running sage --sh, I found these two environmental variables 
```
SAGE_ORIG_PATH

SAGE_ORIG_PATH_SET
```
I am trying to find some documentation on these but can't find any. Can someone explain to me what these are?

OS is Ubuntu 22.04, sage 9.8

**Comment by mkoeppe** [comment]
`SAGE_ORIG_PATH` is no longer in use in the runtime environment. It has a limited use during the build.

Sage does not have the mechanism that you are looking for.

If you want ffmpeg in your `PATH`, you will have to set `PATH` in your `~/.profile` or `~/.bashrc` etc.; or symlink it into a directory that is in `PATH`. Likewise with `LD_LIBRARY_PATH` (if setting this is actually needed).

`PKG_CONFIG_PATH` is not needed at runtime.
