### ISSUE TITLE
EllipticCurve.lift_x() is often deterministic, but not always

### ISSUE THREAD

**Issue by yyyyx4** [sagemath/sage#35281]
### Is there an existing issue for this?

- [X] I have searched the existing issues for a bug report that matches the one I want to file, without success.

### Problem Description

Many doctests use `.lift_x()` to construct a specific point, hence they implicitly rely on the method being deterministic. This is true in many cases, but there are base-ring implementations for which it fails:

```sage
sage: F.<t> = GF((101,3))
sage: E = EllipticCurve(F, [1,1])
sage: for _ in range(10):
....:     print(E.lift_x(t+1))
....:
(t + 1 : 39*t^2 + 14*t + 12 : 1)
(t + 1 : 39*t^2 + 14*t + 12 : 1)
(t + 1 : 62*t^2 + 87*t + 89 : 1)
(t + 1 : 62*t^2 + 87*t + 89 : 1)
(t + 1 : 62*t^2 + 87*t + 89 : 1)
(t + 1 : 39*t^2 + 14*t + 12 : 1)
(t + 1 : 62*t^2 + 87*t + 89 : 1)
(t + 1 : 39*t^2 + 14*t + 12 : 1)
(t + 1 : 62*t^2 + 87*t + 89 : 1)
(t + 1 : 39*t^2 + 14*t + 12 : 1)
```

This creates the unpleasant situation that users will write code which silently assumes that `.lift_x()` is deterministic, then encounter surprising bugs once they try the same code on other base fields where it suddenly behaves randomly.

Cc: @JohnCremona

### Proposed Solution

Make `.lift_x()` deterministic and document that guarantee.

This can be as easy as calling `ys.sort()` in two places in `.lift_x()`, but it breaks a lot of doctests — including some that I'm not confident enough about to change them.

### Alternatives Considered

Make all `.sqrt()` methods deterministic.

This seems more work, is more likely to miss some cases, and is prone to other implementations being added later that break the guarantee again.

**Comment by JohnCremona** [comment]
Sounds good to me. I can help with checking doctests, but not this week

**Comment by yyyyx4** [comment]
Here's a [branch](https://github.com/yyyyx4/sage/tree/public/make_lift_x_deterministic). Some test failures remain unresolved because I wasn't sure how they should be fixed:

```
sage -t --random-seed=301221052125093850803729426946140079108 src/sage/schemes/elliptic_curves/height.py  # 3 doctests failed
sage -t --random-seed=301221052125093850803729426946140079108 src/sage/schemes/elliptic_curves/ell_rational_field.py  # 1 doctest failed
sage -t --random-seed=301221052125093850803729426946140079108 src/sage/schemes/elliptic_curves/period_lattice.py  # 4 doctests failed
```

**Comment by JohnCremona** [comment]
I will look at it.  Can you post the test failures, as I'm at a conference and I am not sure how long it will take me to build you  branch and run the tests myself?

**Comment by JohnCremona** [comment]
> Here's a [branch](https://github.com/yyyyx4/sage/tree/public/make_lift_x_deterministic). Some test failures remain unresolved because I wasn't sure how they should be fixed:
> 
> ```
> sage -t --random-seed=301221052125093850803729426946140079108 src/sage/schemes/elliptic_curves/height.py  # 3 doctests failed
> sage -t --random-seed=301221052125093850803729426946140079108 src/sage/schemes/elliptic_curves/ell_rational_field.py  # 1 doctest failed
> sage -t --random-seed=301221052125093850803729426946140079108 src/sage/schemes/elliptic_curves/period_lattice.py  # 4 doctests failed
> ```

In height.py, for the first 2 it is fine to replace the old output with the new.  For the first one, the old output is L(-P) and in the second it's the same (notice that the old and new outputs add to 1).  The third one is numerical noise: I would either add some ... or look up the right thing to do in a numerical doctest to say "accept if the two sides differ by less than ...".
I am going to add a commit to your branch with fixes justified as follows:

ell_rational_field:  the output looks very verbose only because this test is run with verbose=True.  The output is a list of 43 points up to sign, and it's fine that with the new code a different choice is made between P and -P.

ell_period_lattice: as in heights.py all are correct it's just that P and -P have been switched.

I'll make sure that there are no other failing tests and push to the make_lift_x_deterministic branch...

**Comment by JohnCremona** [comment]
OK, there's now a PR at https://github.com/yyyyx4/sage/pull/1.  Merge that to update this, then I'll give this a positive review.

**Comment by yyyyx4** [comment]
Thank you! It seems the correct way to add a branch to this ~~ticket~~ issue is by creating a pull request, which I just did: #35644.
