### ISSUE TITLE
objects.inv contains only modules

### ISSUE THREAD

**Issue by saraedum** [sagemath/sage#35298]
### Is there an existing issue for this?

- [X] I have searched the existing issues for a bug report that matches the one I want to file, without success. (There's a meta ticket. Not sure if these are updated still: https://github.com/sagemath/sage/issues/20080)

### Problem Description

Currently, the `objects.inv` deployed at https://doc.sagemath.org/html/en/reference/objects.inv only exposes modules and documents but not classes and functions. This makes it hard to link to SageMath's documentation from other projects with [intersphinx](https://www.sphinx-doc.org/en/master/usage/extensions/intersphinx.html).

Here's an example that shows that the class `DiscreteValuation` is missing. Only it's module is around. (Same for all other classes.)
```sh
$ python -m sphinx.ext.intersphinx https://doc.sagemath.org/html/en/reference/objects.inv | grep DiscreteValuation
$ python -m sphinx.ext.intersphinx https://doc.sagemath.org/html/en/reference/objects.inv | grep discrete_valuation
	sage.categories.complete_discrete_valuation categories/sage/categories/complete_discrete_valuation.html#module-sage.categories.complete_discrete_valuation
	sage.categories.discrete_valuation       categories/sage/categories/discrete_valuation.html#module-sage.categories.discrete_valuation
	categories/sage/categories/complete_discrete_valuation Complete Discrete Valuation Rings (CDVR) and Fields (CDVF): categories/sage/categories/complete_discrete_valuation.html
	categories/sage/categories/discrete_valuation Discrete Valuation Rings (DVR) and Fields (DVF): categories/sage/categories/discrete_valuation.html
```

### Proposed Solution

I don't understand why the `objects.inv` of SageMath is so short. Other projects I am working on (e.g. `sage-flatsurf`) produce a proper `objects.inv` without any special sphinx configuration.

**Comment by saraedum** [comment]
cc @videlec I tried to link to SageMath from sage-flatsurf without success because of this.

**Comment by mkoeppe** [comment]
> I don't understand why the `objects.inv` of SageMath is so short.

Because the reference manual is split into many separate Sphinx documents, each of which has its own `objects.inv`, for example https://doc.sagemath.org/html/en/reference/numerical/objects.inv

https://github.com/sagemath/sage-package/blob/master/sage_package/sphinx.py has code for intersphinxing to it.

**Comment by saraedum** [comment]
Thanks, I'll try that then.
