### ISSUE TITLE
pyscipopt does not work with Python 3.11

### ISSUE THREAD

**Issue by dimpase** [sagemath/sage#35299]
### Is there an existing issue for this?

- [X] I have searched the existing issues for a bug report that matches the one I want to file, without success.

### Did you read the documentation and troubleshoot guide?

- [X] I have read the documentation and troubleshoot guide

### Environment

```markdown
- **any OS**:
- **Sage with Python 11**:
```

### Steps To Reproduce

Building: `make pyscipopt` fails with Python 3.11

### Expected Behavior

should work

### Actual Behavior

is broken, see  https://github.com/scipopt/PySCIPOpt/issues/660

The reason is use of non-public API, see there for more details

### Additional Information

See also [https://groups.google.com/d/msgid/sage-devel/42199586-647d-4dc0-9b88-9ff5c7ff8737n%40googlegroups.com](https://groups.google.com/d/msgid/sage-devel/42199586-647d-4dc0-9b88-9ff5c7ff8737n%40googlegroups.com?utm_medium=email&utm_source=footer).

**Comment by mkoeppe** [comment]
Doesn't the failing code come from Cython?

**Comment by dimpase** [comment]
Hmm, are you saying that our Cython does not support Python 3.11?

**Comment by mkoeppe** [comment]
Just saying that if you look for the failing code in the pyscipopt repository, you won't find it

**Comment by mkoeppe** [comment]
BTW a Cython upgrade is in the making in #35084

**Comment by dimpase** [comment]
certainly one has to inspect the generated cython file, and see what lines are guilty

**Comment by dimpase** [comment]
certainly one has to inspect the generated cython file, and see what lines are guilty.

I can reproduce this on macOS 13 with homebrew and python3.11.2 from python.org. Will post details later, awk atm

**Comment by mkoeppe** [comment]
Let's do the Cython upgrade and see.

**Comment by dimpase** [comment]
> Let's do the Cython upgrade and see.

Are you working on it?

**Comment by mkoeppe** [comment]
If you have time to work on it now, go for it. I can't get to it before tomorrow or so.

**Comment by mkoeppe** [comment]
The problem is simply that we are using the PyPI sdist of PySCIPOpt, which contains a `scip.c` that was prebuilt with an old Cython (`/* Generated by Cython 0.29.28 */`).

**Comment by mkoeppe** [comment]
The solution: Merge #652, tag a new release....

**Comment by dimpase** [comment]
blyad'!
