### ISSUE TITLE
Which algorithm is used for computing the gcd of sparse polynomial

### ISSUE THREAD

**Issue by Believe2323** [sagemath/sage#35301]
### Is there an existing issue for this?

- [X] I have searched the existing issues for a bug report that matches the one I want to file, without success.

### Problem Description

There are lot of algorithms that compute the gcd of the polynomial for handling different cases 
Is there any fast algorithm that computes the gcd of polynomial faster, also wants to know which algorithm does sage math used for computing the gcd of sparse polynomial 

### Proposed Solution

NA

### Alternatives Considered

Different algorithms are used for computing the gcd of the polynomial

**Comment by mezzarobba** [comment]
Please use one of the [support mailing lists](https://www.sagemath.org/help-groups.html) or https://ask.sagemath.org/ for questions.
