### ISSUE TITLE
Sage documentation preview for the devel branch accessible through the wiki

### ISSUE THREAD

**Issue by kwankyu** [sagemath/sage#35328]
### Is there an existing issue for this?

- [X] I have searched the existing issues for a bug report that matches the one I want to file, without success.

### Problem Description

It is very useful that the sage documentation for the branch of a PR is built and accessible through a comment attached to the PR.

Similarly it would be useful that the sage documentation for the devel branch is built and accessible, perhaps, through the wiki,  whenever the devel branch is updated. For this purpose, perhaps the url to the built documentation should be fixed (that is, not dependent on the sage version)

CC: @tobiasdiez 

### Proposed Solution

None

### Alternatives Considered

None

### Additional Information

None

**Comment by tobiasdiez** [comment]
The docs for the develop branch are published at https://sagemath-tobias.netlify.app/

**Comment by kwankyu** [comment]
Thanks!

**Comment by kwankyu** [comment]
Added links in the wiki.
