### ISSUE TITLE
inverse_mod(-2,7) is wrong

### ISSUE THREAD

**Issue by yes-uisu** [sagemath/sage#35402]
### Is there an existing issue for this?

- [X] I have searched the existing issues for a bug report that matches the one I want to file, without success.

### Did you read the documentation and troubleshoot guide?

- [X] I have read the documentation and troubleshoot guide

### Environment

```markdown
- **OS**:windows 10
- **Sage Version**: 8.8
```

### Expected Behavior

calculate inverse_mod(-2,7),output is 3. But the correct answer is 5. 

### Actual Behavior

calculate inverse_mod(-2,7),output is 3.

**Comment by yyyyx4** [comment]
No, $3$ is the correct result: $3 \cdot (-2) = -6 = 1-7 \equiv 1 \pmod 7$.
