### ISSUE TITLE
No link for base class of `Vector_double_dense`

### ISSUE THREAD

**Issue by ShriKaranHanda** [sagemath/sage#35444]
### Is there an existing issue for this?

- [X] I have searched the existing issues for a bug report that matches the one I want to file, without success.

### Did you read the documentation and troubleshoot guide?

- [X] I have read the documentation and troubleshoot guide

### Environment

```markdown
- **OS**: Ubuntu 20.04
- **Sage Version**: 10.0.beta7
```

### Steps To Reproduce

1. Go to [this](https://doc.sagemath.org/html/en/reference/modules/sage/modules/vector_double_dense.html#sage.modules.vector_double_dense.Vector_double_dense) link
2. `Vector_numpy_dense` doesn't have a corresponding link

### Expected Behavior

It should be hyperlinked.

### Actual Behavior

There is no link.

**Comment by mkoeppe** [comment]
This can be fixed by adding the missing module to `src/doc/en/reference/modules/index.rst`

**Comment by karan0handa** [comment]
I've added the missing module, and can access the documentation via the index page, but there is still no link for `Vector_numpy_dense`. I ran the following command to build ./sage --docbuild reference/modules html`. After this didn't work, then I did `./sage --docbuild reference html`, but the issue still persists.

**Comment by mkoeppe** [comment]
> I've added the missing module

PR please.
