### ISSUE TITLE
Sage 10.0.beta8 failing to build on Mac inside conda

### ISSUE THREAD

**Issue by grhkm21** [sagemath/sage#35469]
### Is there an existing issue for this?

- [X] I have searched the existing issues for a bug report that matches the one I want to file, without success.

### Did you read the documentation and troubleshoot guide?

- [X] I have read the documentation and troubleshoot guide

### Environment

```markdown
- **OS**: macOS Monterey 12.6 (21G115)
- **Sage Version**: 10.0.beta8
- **Shell**: Fish
```

### Steps To Reproduce

1. I created a conda environment and activated it with `conda activate sage-dev`
2. I installed packages as suggested in one of the readme files: `conda install arb brial cliquer eclib libflint fplll giac lcalc libbraiding linbox mpfi ntl "pari=*=*_pthread" pari-elldata pari-galdata pari-galpol pari-seadata pari-galdata pari-seadata-small ppl rpy2 singular symmetrica`
3. I run the `./configure` command that's listed in one of the pages: `./configure --with-python=$CONDA_PREFIX/bin/python --prefix=$CONDA_PREFIX (for pkg in (./sage -package list :standard: --has-file spkg-configure.m4 --has-file distros/conda.txt); echo --with-system-$pkg=force; end)`
4. It fails to find any of the installed packages from step 2 - check log.

Also, when I check my environment, I do find the packages installed:
```bash
$ fd ntl -d 3 $CONDA_PREFIX
/Users/grhkm/miniconda/envs/sage-dev/conda-meta/libflint-2.9.0-hfd2f71f_ntl_100.json
/Users/grhkm/miniconda/envs/sage-dev/conda-meta/ntl-11.4.3-h0ab3c2f_1.json
/Users/grhkm/miniconda/envs/sage-dev/include/NTL/
/Users/grhkm/miniconda/envs/sage-dev/include/flint/NTL-interface.h
/Users/grhkm/miniconda/envs/sage-dev/include/gdfontl.h
/Users/grhkm/miniconda/envs/sage-dev/include/giac/giacintl.h
/Users/grhkm/miniconda/envs/sage-dev/include/libintl.h
/Users/grhkm/miniconda/envs/sage-dev/lib/libintl.8.dylib
/Users/grhkm/miniconda/envs/sage-dev/lib/libintl.a
/Users/grhkm/miniconda/envs/sage-dev/lib/libintl.dylib
/Users/grhkm/miniconda/envs/sage-dev/lib/libntl.43.dylib
/Users/grhkm/miniconda/envs/sage-dev/lib/libntl.a
/Users/grhkm/miniconda/envs/sage-dev/lib/libntl.dylib
/Users/grhkm/miniconda/envs/sage-dev/man/man3/Fcntl.3
/Users/grhkm/miniconda/envs/sage-dev/share/aclocal/intlmacosx.m4
/Users/grhkm/miniconda/envs/sage-dev/share/doc/NTL/
```

### Config log

It doesn't seem to exist? But this is the terminal output, when running step 3, if that's what you meant:
[sage_log.txt](https://github.com/sagemath/sage/files/11185473/sage_log.txt)

### Package logs

The folder is empty...

### Additional Information

I don't know what I should give. It is very weird since the packages are definitely all installed, but conda is not finding it. I have had similar issues with the c-compiler and cpp-compiler and f-compiler(?) inside the conda environment, but I got around that by setting environment variables. Could this be related to me using a Fish shell? Since the syntax for setting environment variables is completely different.

**Comment by mkoeppe** [comment]
In the activated conda environment, please type `conda list; env; cat config.log`.

**Comment by grhkm21** [comment]
Hey! Here are the outputs in order.
[env_list.txt](https://github.com/sagemath/sage/files/11185917/env_list.txt)
[conda_list.txt](https://github.com/sagemath/sage/files/11185915/conda_list.txt)
[config.log](https://github.com/sagemath/sage/files/11185916/config.log)

**Comment by mkoeppe** [comment]
I'd recommend to remove whatever sets the environment variables `CC`, `CXX`, `FC`, and also `LD_LIBRARY_PATH` (which is noneffective on macOS) and `C_INCLUDE_PATH` from your init scripts. In a freshly activated conda environment (with the compiler packages installed - as looks correct in your conda_list.txt), these variables should already be set to the correct values.
Then re-run `./configure` and if the problem persists, please post config.log again

**Comment by grhkm21** [comment]
Okay, it took a while and I have done what you said, so that `env | grep "cc="` returns nothing. However, I now run into a new problem, saying that "at least one of CC CXX FC is not set" and recommends me to run `conda install c-compiler cxx-compiler fortran-compiler`. However, they're installed, as `conda list | grep compiler` shows all three compilers installed...

[config.log](https://github.com/sagemath/sage/files/11186001/config.log)

**Comment by mkoeppe** [comment]
In the activated conda environment, these environment variables should be automatically set. For example, on my machine, I see:
```
$ env | grep CC
CC=x86_64-apple-darwin13.4.0-clang
```

**Comment by grhkm21** [comment]
It is not set for me... Maybe it's my conda's problem? Should I try to reinstall conda entirely?

**Comment by mkoeppe** [comment]
> Could this be related to me using a Fish shell?

Quite possibly. Is this your login shell? Why is it coming from `/usr/local`?

**Comment by grhkm21** [comment]
Yes it's my login shell, it's just located at `/usr/local/bin/fish` when I type `which fish`. I think some part of the Sage build process is not compatible with fish. For example, the README tells me to run `source ./.homebrew-build-env`, but the syntax `A=B` doesn't work in fish, it should be something like `set A B`. Maybe that's why the environment variables are not set

**Comment by mkoeppe** [comment]
When you use conda, `.homebrew-build-env` should not be used. (But a PR providing an equivalent `.homebrew-build-env.fish` would be welcome.)

**Comment by mkoeppe** [comment]
Why do you also have `/opt/local/bin` in your PATH? That's typically the install location of homebrew on the Apple Silicon architecture?

**Comment by grhkm21** [comment]
To be honest, my system's kind of a mess, it's barely holding itself together by me adding things to the PATH when I need them

**Comment by mkoeppe** [comment]
Does conda work for you properly in other environments on this system?

Starting with a fresh reinstall of conda is probably a good idea.

**Comment by grhkm21** [comment]
`conda` *seems* to work properly in my daily usage, which makes me more confused. I will reinstall conda and try everything again later. Thanks for helping!

**Comment by grhkm21** [comment]
Update: I can confirm that installing with conda on another Linux machine from scratch works, but on my Mac machine it refuses to work even after reinstalling conda. I assume somewhere in my machine it's just messed up but I have no idea where :( I will see if I have better luck with the other approaches. Or maybe I can become a vegan and not use fish

[new config.log, should be essentially the same as before](https://github.com/sagemath/sage/files/11186417/config.log)
