### ISSUE TITLE
Confusions in left and right division for Ore polynomials

### ISSUE THREAD

**Issue by kwankyu** [sagemath/sage#35531]
```sage
sage: k.<a> = GF(5^3)
....: Frob = k.frobenius_endomorphism()
....: S = OrePolynomialRing(k, Frob, 'x')
....: S
Ore Polynomial Ring in x over Finite Field in a of size 5^3 twisted by a |--> a^5
sage: x = S.gen()
sage: f = x*a + a*x^2+a*x^4
sage: g = (a^7+a)*x^2*(a+1)+ (a^3+1)*x + 1
sage: f
a*x^4 + a*x^2 + (2*a^2 + 4*a + 4)*x
sage: g
(3*a^2 + 2*a + 4)*x^2 + (2*a + 3)*x + 1
sage: q = f // g
sage: r = f % g
sage: f == g*q+r
False
sage: f == q*g+r
True
```

According to the documentation (1)
```
The operators // and % give respectively the quotient and the remainder of the right euclidean division
```

But the definition of the right euclidean division is (2)

![Screen Shot 2023-04-18 at 1 34 25 PM](https://user-images.githubusercontent.com/1456101/232672322-87ba2939-00b4-48b1-894d-f03cc009f18e.png)

Apparently the two docs are inconsistent. What is the correct definition of the right euclidean division? @xcaruso 

According to Ore himself, the right-hand division of $F$ by $G$ is $F=QG+R$. So (2) is wrong.

**Comment by xcaruso** [comment]
You're right. The documentation is wrong. Thanks for catching this!

**Comment by kwankyu** [comment]
Is this also correct "Right(-hand) gcd is computed by right(-hand) extended euclidean algorithm that does right(-hand) divisions"?

This "right" and "left" confusion seems not uncommon in papers on Ore polynomials. The wrong documentation (2) in sage makes the situation worse.

**Comment by xcaruso** [comment]
> Is this correct "Right(-hand) gcd is computed by right(-hand) euclidean algorithm that does right(-hand) divisions"?

I think it's correct, yes! But all of these correspond to left lcm and left modules...

**Comment by kwankyu** [comment]
Thanks. 

By left modules, you mean left ideals in the form Re for an element e of the ring R.

I will prepare a PR later.
