### ISSUE TITLE
SageMath docs references trac tickets

### ISSUE THREAD

**Issue by wermos** [sagemath/sage#35568]
I was [browsing through the docs](https://doc.sagemath.org/html/en/reference/number_fields/sage/rings/number_field/number_field_element.html) and I found that the docs reference a trac ticket, which returns a 404 if you click on it. It redirects you [here](https://trac.sagemath.org/16147).

It looks like there are multiple examples of broken links like that in the docs. [Here](https://doc.sagemath.org/html/en/reference/plotting/sage/plot/plot.html) is another example that tries to redirect you [here](https://trac.sagemath.org/2900). [Here](https://doc.sagemath.org/html/en/reference/combinat/sage/combinat/integer_vector.html) is another example. (Redirect leads [here](https://trac.sagemath.org/34510).)

**Comment by davidlowryduda** [comment]
This is resolved in #35015. When the next doc deployment occurs, these links will be updated to point to the appropriate github issues.
