### ISSUE TITLE
Conrey number of trivial character

### ISSUE THREAD

**Issue by jwj61** [sagemath/sage#35628]
### Is there an existing issue for this?

- [X] I have searched the existing issues for a bug report that matches the one I want to file, without success.

### Did you read the documentation and troubleshoot guide?

- [X] I have read the documentation and troubleshoot guide

### Environment

```markdown
- **OS**: Ubuntu 20.04.5 LTS
- **Sage Version**: 9.7
```

### Steps To Reproduce

g=DirichletGroup(1)
[z.conrey_number() for z in g]

### Expected Behavior

Answer should be [1]

### Actual Behavior

Sage give
[0]

### Additional Information

 0 is not a valid Conrey number of a Dirichlet character

**Comment by fchapoton** [comment]
This calls pari function `znconreyexp`  on the character converted to pari.

So either a bug in the conversion to pari, or a bug in pari. Please investigate.

**Comment by fchapoton** [comment]
If so,  please report upstream and put a link here to the discussion there

**Comment by fchapoton** [comment]
upstream is https://pari.math.u-bordeaux.fr/cgi-bin/bugreport.cgi?bug=2479

**Comment by jwj61** [comment]
The pari function does not claim to produce the Conrey number as defined in the LMFDB whereas the Sage documentation does specifically reference the LMFDB definition.  I think sage should make the small adjustment.
