### ISSUE TITLE
documentation: an vs a

### ISSUE THREAD

**Issue by videlec** [sagemath/sage#35642]
There are many wrong instances of the indefinite article _a_/_an_ in the doc. eg
```
arith/misc.py:    -  ``n`` - an nonzero integer
categories/sets_cat.py:               `r` is an homomorphism from `B` to `A` (typically a
...
```
More delicate : some beginning vowels are not vowel sound, for example y-sound
```
algebras/quantum_groups/fock_space.py:            Return an unicode art representing the generator indexed by ``m``.
combinat/dyck_word.py:        Return an unicode art representation of this Dyck word.
combinat/posets/hasse_diagram.py:        This lattice has an unique "possible orthocomplement" for every
graphs/base/c_graph.pyx:        The digraph obtained from the ``PetersenGraph`` has an unique strongly
...
```
Also, most of the words starting with h should be used with _a_ and not _an_
```
algebras/commutative_dga.py:            Return the cohomology class of an homogeneous cycle, as an element
categories/complex_reflection_groups.py:    element of `\operatorname{GL}(V)` fixing an hyperplane pointwise
categories/sets_cat.py:               `r` is an homomorphism from `B` to `A` (typically a
...
```
(only exceptions are heir, heiress, honest, honour, hour)

**Comment by aybeedee** [comment]
Do the above mentioned constitute all of them? Or is it required to search for more?

**Comment by videlec** [comment]
> Do the above mentioned constitute all of them? Or is it required to search for more?

The examples in the PR issue description are a very small part. I did use `git grep` to find them. For example
```console
$ git grep '\san\s[bcdfghjklmnpqrstvwxyz]'
```
give 327 occurrences of doubtful usage of `an` (some of them being correct as the above also catches `an hour` which is correct).

**Comment by aybeedee** [comment]
Ok I'll see if I can go through all of them

**Comment by ydv-ankit** [comment]
hey! I know hindi very well and these can be resolved with accordance to hindi very easily, can I do it ?

**Comment by MedantSharan** [comment]
Hello there, I believe I have fixed this issue. Please check and approve my PR.

**Comment by fchapoton** [comment]
closing as completed in #36229
