### ISSUE TITLE
sage build stops waiting for response

### ISSUE THREAD

**Issue by beew** [sagemath/sage#35670]
### Is there an existing issue for this?

- [X] I have searched the existing issues for a bug report that matches the one I want to file, without success.

### Did you read the documentation and troubleshoot guide?

- [X] I have read the documentation and troubleshoot guide

### Environment

```markdown
- **OS**: Ubuntu 22.04
- **Sage Version**: 9.8, 10.0 in fact all versions I have built.
```

### Steps To Reproduce

I am not sure if this is a bug or intended When building sage, the build process stops after installing a component with output likes

"Finished installing x".  To continue the user have to press return,

then sage will output

"Ok, will install y"

### Expected Behavior

build should continue without requiring user input. It takes a long time for sage to build, I would like it to just type "make" and let it run so I could do something else  instead of having to wait around to press return and wait for

"ok"

### Actual Behavior

See above

**Comment by jhpalmieri** [comment]
This should happen only if you are trying to install an experimental package. What `./configure` command did you use?
