### ISSUE TITLE
SciPy 1.11.x

### ISSUE THREAD

**Issue by mkoeppe** [sagemath/sage#35703]
1.11.0rc1 available 2023-05-31

Improvements possibly relevant for Sage, from https://scipy.github.io/devdocs/release/1.11.0-notes.html:
- [scipy.optimize.linprog](https://scipy.github.io/devdocs/reference/generated/scipy.optimize.linprog.html#scipy.optimize.linprog) now passes unrecognized options directly to HiGHS (to be checked)

- Depends on #35404
- Depends on #35810

**Comment by dimpase** [comment]
they already have 1.12.0

**Comment by mkoeppe** [comment]
No, that is not released yet. https://pypi.org/project/scipy/#history
