### ISSUE TITLE
GLPK/exact isn't exact on simple, rational LPs

### ISSUE THREAD

**Issue by ed359** [sagemath/sage#35727]
### Is there an existing issue for this?

- [X] I have searched the existing issues for a bug report that matches the one I want to file, without success.

### Did you read the documentation and troubleshoot guide?

- [X] I have read the documentation and troubleshoot guide

### Environment

```markdown
- **OS**: macOS 13.4
- **Sage Version**: 10.0 binaries from the manifold project
```

### Steps To Reproduce

From a fresh install run the following code:

```python
def build_prog(solver):
    p = MixedIntegerLinearProgram(solver=solver, maximization=False, base_ring=QQ)
    x = p.new_variable(nonnegative=True)
    p.set_objective(p.sum(x[i] for i in range(6)))
    for i in range(6):
        p.add_constraint(x[i], min=1/6)
    return p, x

p1, x1 = build_prog('PPL')
print(f'PPL: {p1.solve()}')
print(p1.get_values(x1, convert=True))
print()

p2, x2 = build_prog('InteractiveLP')
print(f'InteractiveLP: {p2.solve()}')
print(p2.get_values(x3, convert=True))
print()

p3, x3 = build_prog('GLPK/exact')
print(f'GLPK/exact: {p3.solve()}')
print(p3.get_values(x3, convert=True))
```

### Expected Behavior

The expected behavior is that both PPL and GLPK/exact are able to find the exact rational solution 1 to the LP

```
PPL: 1
{0: 1/6, 1: 1/6, 2: 1/6, 3: 1/6, 4: 1/6, 5: 1/6}

InteractiveLP: 1
{0: 1/6, 1: 1/6, 2: 1/6, 3: 1/6, 4: 1/6, 5: 1/6}

GLPK/exact: 1
{0: 1/6, 1: 1/6, 2: 1/6, 3: 1/6, 4: 1/6, 5: 1/6}
```

### Actual Behavior

The actual behavior is that GLPK/exact is *not exact*, even when getting the values with `convert=True`.

```
PPL: 1
{0: 1/6, 1: 1/6, 2: 1/6, 3: 1/6, 4: 1/6, 5: 1/6}

InteractiveLP: 1
{0: 1/6, 1: 1/6, 2: 1/6, 3: 1/6, 4: 1/6, 5: 1/6}

GLPK/exact: 0.9999999999999999
{0: 0.16666666666666666, 1: 0.16666666666666666, 2: 0.16666666666666666, 3: 0.16666666666666666, 4: 0.16666666666666666, 5: 0.16666666666666666}
```

### Additional Information

I can read the documentation and observe that GLPK/exact is (supposed to be) doing exact rational computation on the inside, but data input and output is via double precision floats. See https://doc.sagemath.org/html/en/reference/numerical/sage/numerical/backends/glpk_exact_backend.html: "The only access to data is via double-precision floats, however. It reconstructs rationals from doubles and also provides results as doubles." It thus appears that I am reporting something like a bug with reconstructing rationals, or if (strangely) this is how GLPK/exact is supposed to work then the documentation should clearly indicate that GLPK.exact *cannot be expected to solve simple rational LPs correctly*. This kind of bug is felt downstream as it's tempting to check ```p.solve() == 1``` when with errors we need something like ```abs(p.solve() - 1) < 0.00001``` instead. Sage's own use of MILPs is/was littered with this kind of bug (#32191 and also #23798 for a slightly different issue).

I can also see that this summer the optimization functionality in sage is getting a major overhaul. We have lots of open tickets, including some relevant ones:
- #18765 is about bridging sage's backends with GLPK/exact directly so that the float bottleneck is overcome. 
- #35199 is about extending the SCIP/SoPlex backend to allow exact rational computations

**Comment by mkoeppe** [comment]
Yes, the only way to get an exact result from GLPK/exact is to read out the basis information and then reconstruct the optimal tableau. (This is not implemented in Sage.)

I don't think it's a promising direction to put any more work into GLPK (and interfacing to it). 
A PR that improves the documentation regarding this peculiarity of GLPK/exact is certainly welcome, though.

Much better alternatives are available: For double precision results, HiGHS; and for exact results, SoPlex. Any help with these is very welcome!

**Comment by mkoeppe** [comment]
Oh, and `convert=True` will only do something if you declare the variable to be integer.

**Comment by mkoeppe** [comment]
> I can't easily verify that the interface is exposed in [pyscipopt](https://github.com/scipopt/PySCIPOpt). Would a good way of connecting sage to SoPlex be to do the work in pyscipopt and then write a backend in sage that calls SoPlex via pyscipopt?

Yes, preparing this as an improvement of pyscipopt would seem the best way to do this. It would probably be a good idea to check with the authors whether there are already any efforts in this direction, and/or if such as contribution would be welcome.

**Comment by ed359** [comment]
It appears that SCIP doesn't expose SoPlex particularly precisely. At least, I could not figure out how to set the SoPlex options described [here](https://soplex.zib.de/doc/html/EXACT.php) via SCIP because the relevant SoPlex options are not in the list of [SCIP parameters](https://www.scipopt.org/doc/html/PARAMETERS.php). This leads me to think that calling SoPlex itself directly and not via SCIP or pyscipopt will be the way to go for an exact backend for sage. There are some very out-of-date cython bindings to SoPlex [here](https://github.com/SBRG/soplex_cython) which may help get a backend started.

**Comment by mkoeppe** [comment]
There is also the SCIP feature branch https://github.com/scipopt/scip/tree/exact-rational, which may be helpful here. (I haven't checked what the interfaces look like.)
