### ISSUE TITLE
Tutorial link of pdf pointing to wrong document name

### ISSUE THREAD

**Issue by geoffreysxu** [sagemath/sage#35736]
### Is there an existing issue for this?

- [X] I have searched the existing issues for a bug report that matches the one I want to file, without success.

### Did you read the documentation and troubleshoot guide?

- [X] I have read the documentation and troubleshoot guide

### Environment

```markdown
- **OS**: ubuntu
- **Sage Version**: 10.0
```

### Steps To Reproduce

1. After build doc-pdf, open "sage-10.0/local/share/doc/sage/index.html"
2. PDF/Tutorial link cannot find the pdf file:
    sage-10.0/local/share/doc/sage/pdf/en/tutorial/SageTutorial.pdf

### Expected Behavior

PDF/Tutorial in "sage-10.0/local/share/doc/sage/index.html" should point to "sage_tutorial.pdf" instead of "SageTutorial.pdf".

### Actual Behavior

Your file couldn’t be accessed

**Comment by jhpalmieri** [comment]
I think this should do it:
```
diff --git a/src/doc/en/tutorial/conf.py b/src/doc/en/tutorial/conf.py
index 8a4f626f44..38ea627d93 100644
--- a/src/doc/en/tutorial/conf.py
+++ b/src/doc/en/tutorial/conf.py
@@ -33,6 +33,6 @@ htmlhelp_basename = 'sage_tutorial'
 # Grouping the document tree into LaTeX files. List of tuples
 # (source start file, target name, title, author, document class [howto/manual]).
 latex_documents = [
-  ('index', 'sage_tutorial.tex', 'Tutorial',
+  ('index', 'SageTutorial.tex', project,
    'The Sage Development Team', 'manual'),
 ]
```
