### ISSUE TITLE
Expands symbolic expression incorrectly and/or hangs

### ISSUE THREAD

**Issue by galashin** [sagemath/sage#35747]
### Is there an existing issue for this?

- [X] I have searched the existing issues for a bug report that matches the one I want to file, without success.

### Did you read the documentation and troubleshoot guide?

- [X] I have read the documentation and troubleshoot guide

### Environment

```markdown
- **OS**: ubuntu 22.04
- **Sage Version**: 9.2
```

### Steps To Reproduce

The following code
```
J=(10, 11, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 24, 25, 28, 31, 32, 34, 35, 38)
t=SR("t")
print("expected = ",SR(prod([t*SR("t%d"%j)-1/SR("t%d"%j) for j in J])).factor()) #correct
print("found    = ",SR(prod([t*SR("t%d"%j)-1/SR("t%d"%j) for j in J])).expand().collect(t).factor()) #wrong/hangs
print("found2   = ",SR(prod([t*SR("t%d"%j)-1/SR("t%d"%j) for j in J])).factor().expand().collect(t).factor()) #hangs
```
should output three equal symbolic expressions. Instead, it outputs the `expected` one and hangs on the other two. This is on CoCalc, and the same happens on my local machine (Mac OS Ventura 13.2, SageMath 9.4). On my local Docker version of CoCalc (SageMath 9.2), it outputs the `expected` one correctly and the `found` one incorrectly, and hangs on the `found2` one:
```
sage: J=(10, 11, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 24, 25, 28, 31, 32, 34, 35, 38) 
....: t=SR("t") 
....: print("expected = ",SR(prod([t*SR("t%d"%j)-1/SR("t%d"%j) for j in J])).factor()) #correct 
....: print("found    = ",SR(prod([t*SR("t%d"%j)-1/SR("t%d"%j) for j in J])).expand().collect(t).factor()) #wrong/hangs 
....: print("found2   = ",SR(prod([t*SR("t%d"%j)-1/SR("t%d"%j) for j in J])).factor().expand().collect(t).factor()) #hangs                                               
expected =  (t*t10^2 - 1)*(t*t11^2 - 1)*(t*t13^2 - 1)*(t*t14^2 - 1)*(t*t15^2 - 1)*(t*t16^2 - 1)*(t*t17^2 - 1)*(t*t18^2 - 1)*(t*t19^2 - 1)*(t*t20^2 - 1)*(t*t21^2 - 1)*(t*t22^2 - 1)*(t*t24^2 - 1)*(t*t25^2 - 1)*(t*t28^2 - 1)*(t*t31^2 - 1)*(t*t32^2 - 1)*(t*t34^2 - 1)*(t*t35^2 - 1)*(t*t38^2 - 1)/(t10*t11*t13*t14*t15*t16*t17*t18*t19*t20*t21*t22*t24*t25*t28*t31*t32*t34*t35*t38)
found    =  (t - 1)^20*t10*t11*t13*t14*t15*t16*t17*t18*t19*t20*t21*t22*t24*t25*t28*t31*t32*t34*t35*t38
```
Works fine for other values of `J`, e.g., `J=(1,2,3,5,10,15,38)`.

### Expected Behavior

should output three equal symbolic expressions

### Actual Behavior

outputs the `expected` one and hangs on the other two

**Comment by DaveWitteMorris** [comment]
I don't think this is a bug, so I plan to close this issue unless someone explains why I am wrong.

I don't think the calculation is hung, just taking a long time. The calculation of `found` expands the product of 20 binomials, which yields an expression with over a million terms. Working with this will be slow.  A similar expression with only 10 binomials is pretty quick, but a test with 14 binomials took a few minutes. The time is increasing exponentially, so I would expect the calculation with 20 binomials to take several hours or maybe a few days.

PS `SR` is not designed to handle polynomials efficiently, so I would guess that the calculation could be completed much faster by working in a polynomial ring (or Laurent polynomial ring).

**Comment by galashin** [comment]
Thank you, my bad.

I did some more investigating and found a smaller example `J=(10, 11, 13, 14, 15, 16, 17, 18, 19, 20, 21)` where SageMath 9.2 produces a wrong answer. SageMath 9.4 computes this example correctly, so I agree the issue should be closed.

P.S. Actually, it's the `factor()` command that was taking a really long time. Either way, I agree that using polynomial rings was the correct way to go.
