### ISSUE TITLE
Crystals cannot be seen in the dark

### ISSUE THREAD

**Issue by mkoeppe** [sagemath/sage#35740]
### Is there an existing issue for this?

- [X] I have searched the existing issues for a bug report that matches the one I want to file, without success.

### Did you read the documentation and troubleshoot guide?

- [X] I have read the documentation and troubleshoot guide

### Environment

```markdown
web
```

### Steps To Reproduce

1. View https://doc.sagemath.org/html/en/thematic_tutorials/lie/crystals.html#crystals-of-letters
2. Switch the doc theme to dark mode.

### Expected Behavior

Crystals should glow in the dark.

### Actual Behavior

Crystals cannot be seen.

### Additional Information

@anneschilling @tscrim

**Comment by cherry-1729-9090** [comment]
Hi. I have identified the issues as highlighted in the pictures. Could you please confirm whether the issues I identified are correct or not? If these are indeed the issues, I would like to work on resolving them. I have experience in Python, HTML, CSS, and Java and am eager to contribute to your projects.


![Screenshot (26)](https://github.com/sagemath/sage/assets/145871325/00778d5c-0508-4a10-a8a5-34dac7ea8d2c)
![Screenshot (27)](https://github.com/sagemath/sage/assets/145871325/a0ea0115-e88c-4a78-ba48-86136b27a7b1)

**Comment by tscrim** [comment]
Yes, that is the issue. Feel free to work on it.

**Comment by cherry-1729-9090** [comment]
Thank you for confirming! I'm excited to work on this. Since I'm new to your library, is there any documentation or specific guidelines I should refer to before opening a PR? Your guidance would be greatly appreciated.

**Comment by tscrim** [comment]
You can find all of the necessary information in our developer's guide: https://doc.sagemath.org/html/en/developer/
