### ISSUE TITLE
Error message following output from "sage -h"

### ISSUE THREAD

**Issue by dyne2meter** [sagemath/sage#35753]
### Is there an existing issue for this?

- [X] I have searched the existing issues for a bug report that matches the one I want to file, without success.

### Did you read the documentation and troubleshoot guide?

- [X] I have read the documentation and troubleshoot guide

### Environment

```markdown
- **OS**: MacOS 10.13.6
- **Sage Version**: 10.0
```

### Steps To Reproduce

I'm using the bundle from the 3-manifolds project and the app bundle is in a sub-directory of /Applications on my system; I have not tested extensively, but sage is making computations for me as I expect. However, when I give the shell command (my shell is tcsh)

% sage - h

I get a good bit of the expected output of a help request and then a couple of strange error messages:

(see below)

### Expected Behavior

I expected the help output without the error message.

### Actual Behavior

I get normal output from sage -h followed by a couple of error messages:

{{{
SageMath version 10.0, Release Date: 2023-05-20

Running Sage:

  file.[sage|py|spyx] -- run given .sage, .py or .spyx file
  -c <cmd>            -- evaluate cmd as sage code
  --notebook=[...]    -- start the Sage notebook (valid options are
                         'default', 'jupyter', 'jupyterlab', and 'export')
                         Current default is 'jupyter'
  -n, --notebook      -- shortcut for --notebook=default
  --nodotsage         -- run Sage without using the user's .sage directory:
                         create and use a temporary .sage directory instead
  -t [options] <--all|files|dir>
                      -- test examples in .py, .pyx, .sage, .tex or .rst files
                         selected options:
                           --long - include lines with the phrase 'long time'
                           --verbose - print debugging output during the test
                           --optional - controls which optional tests are run
                           --help - show all testing options

Running external programs:

  --gap [...]         -- run Sage's Gap with given arguments
  --gp [...]          -- run Sage's PARI/GP calculator with given arguments
  --pip [...]         -- invoke pip, the Python package manager
  --maxima [...]      -- run Sage's Maxima with given arguments
  --mwrank [...]      -- run Sage's mwrank with given arguments
  --python [...], --python3 [...] -- run the Python 3 interpreter
  -R [...]            -- run Sage's R with given arguments
  --singular [...]    -- run Sage's singular with given arguments

Getting help:

  -v, --version       -- display Sage version information
  -h, -?, --help      -- print this help message
  --advanced          -- list all command line options
/var/tmp/sage-10.0-current/venv/bin/sage: line 191: /Applications/Youser/ScienceMath/SageMath-10-0.app/Contents/Frameworks/Sage.framework/Versions/10.0/build/bin/sage-site: No such file or directory
/var/tmp/sage-10.0-current/venv/bin/sage: line 191: exec: /Applications/Youser/ScienceMath/SageMath-10-0.app/Contents/Frameworks/Sage.framework/Versions/10.0/build/bin/sage-site: cannot execute: No such file or directory
}}}

### Additional Information

There indeed is no such path that begins ../../Versions/10.0/build etc. inside the app bundle. I don't really think there should be, but somehow the system is looking for something along those lines.

**Comment by DaveWitteMorris** [comment]
@culler: is this some minor issue with the 3-manifolds release?

**Comment by dyne2meter** [comment]
Yeah, I guess so. I probably shouldn't have posted.

**Comment by DaveWitteMorris** [comment]
I should have said: "thanks for reporting the bug", even though it is minor. I suspect it is some minor issue in the 3-manifolds build, but it may just be something weird about your system. I'm not an expert on this type of thing.

**Comment by culler** [comment]
Yes, even minor issues deserve to be fixed.  But this issue belongs at the Sage_macOS project.  I will open an issue there. 

The basic problem is that that the app bundle does not include the Sage build directory.  But the sage script needs to be adjusted so that it doesn't try to access that directory.  Or maybe the app should include the build/bin directory, or enough of it to make sage -h work.  The app does not support building optional parts of Sage, other than pypi packages which are installed in ~/.sage, because modifying the app bundle would invalidate its signature and Apple would refuse to run the app after that.

**Comment by dyne2meter** [comment]
Thanks for the info. The 3-manifolds project is without qualification a magnificent effort, and now I have some insight into why some paths are missing.
