### ISSUE TITLE
Sage Crash Report

### ISSUE THREAD

**Issue by DhamnekarWinod** [sagemath/sage#35769]
<html>
<body>
<div class="wide-content-host" style="border: 0px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-variant-numeric: inherit; font-variant-east-asian: inherit; font-variant-alternates: inherit; font-weight: 400; font-stretch: inherit; font-size: 14px; line-height: inherit; font-family: &quot;Segoe UI&quot;, &quot;Segoe UI Web (West European)&quot;, &quot;Segoe UI&quot;, -apple-system, BlinkMacSystemFont, Roboto, &quot;Helvetica Neue&quot;, sans-serif; font-optical-sizing: inherit; font-kerning: inherit; font-feature-settings: inherit; font-variation-settings: inherit; margin: 0px; padding: 0px; vertical-align: baseline; color: rgb(66, 66, 66); letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(250, 250, 250); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><div class="Vm3e5 L8m1x pinIo" style="border: 1px solid var(--readingPaneCardBorder); font: inherit; margin: 0px 20px 8px 8px; padding: 0px 12px 12px; vertical-align: baseline; color: inherit; background-image: ; background-position-x: ; background-position-y: ; background-size: ; background-repeat-x: ; background-repeat-y: ; background-attachment: ; background-origin: ; background-clip: ; background-color: var(--neutralPrimarySurface); border-radius: 4px; width: calc(100% - 53.5px);"><div role="region" tabindex="-1" aria-label="Message body" class="ulb23 GNqVo yxtKT allowTextSelection" style="border: 0px; font-style: inherit; font-variant: inherit; font-weight: 400; font-stretch: inherit; font-size: 15px; line-height: inherit; font-family: inherit; font-optical-sizing: inherit; font-kerning: inherit; font-feature-settings: inherit; font-variation-settings: inherit; margin: 16px 0px 10px; padding: 0px 0px 2px; vertical-align: baseline; color: var(--neutralDark); cursor: auto; user-select: text; overflow-y: auto; will-change: scroll-position;"><div visiblity="visible" style="border: 0px; font: inherit; margin: 0px; padding: 0px; vertical-align: baseline; color: inherit;"><div class="rps_597c" style="border: 0px; font: inherit; margin: 0px; padding: 0px; vertical-align: baseline; color: inherit;"><div dir="ltr" style="border: 0px; font: inherit; margin: 0px; padding: 0px; vertical-align: baseline; color: inherit;"><div class="x_elementToProof" style="border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: 12pt; line-height: inherit; font-family: Calibri, Helvetica, sans-serif; font-optical-sizing: inherit; font-kerning: inherit; font-feature-settings: inherit; font-variation-settings: inherit; margin: 0px; padding: 0px; vertical-align: baseline; color: rgb(0, 0, 0);">To,</div><div class="x_elementToProof" style="border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: 12pt; line-height: inherit; font-family: Calibri, Helvetica, sans-serif; font-optical-sizing: inherit; font-kerning: inherit; font-feature-settings: inherit; font-variation-settings: inherit; margin: 0px; padding: 0px; vertical-align: baseline; color: rgb(0, 0, 0);"> SageMath Developer,</div><div class="x_elementToProof" style="border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: 12pt; line-height: inherit; font-family: Calibri, Helvetica, sans-serif; font-optical-sizing: inherit; font-kerning: inherit; font-feature-settings: inherit; font-variation-settings: inherit; margin: 0px; padding: 0px; vertical-align: baseline; color: rgb(0, 0, 0);">Sir,</div><div class="x_elementToProof" style="border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: 12pt; line-height: inherit; font-family: Calibri, Helvetica, sans-serif; font-optical-sizing: inherit; font-kerning: inherit; font-feature-settings: inherit; font-variation-settings: inherit; margin: 0px; padding: 0px; vertical-align: baseline; color: rgb(0, 0, 0);">Hi, I downloaded and installed SageMath-9.2-Installer-v0.6.1.exe from <a href="https://github.com/sagemath/sage-windows/releases" target="_blank" rel="noopener noreferrer" data-auth="NotApplicable" class="x_ContentPasted0" style="border: 0px; font: inherit; margin: 0px; padding: 0px; vertical-align: baseline;">Releases · sagemath/sage-windows (github.com)</a> for Windows 10,64 bit, version 22H2. But SageMath console crashed at once when I opened it by clicking on its icon.  The file containing the Sage Crash Report is attached herewith. I hope you will understand and correct this issue. </div><div class="x_elementToProof" style="border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: 12pt; line-height: inherit; font-family: Calibri, Helvetica, sans-serif; font-optical-sizing: inherit; font-kerning: inherit; font-feature-settings: inherit; font-variation-settings: inherit; margin: 0px; padding: 0px; vertical-align: baseline; color: rgb(0, 0, 0);"><br aria-hidden="true"></div><div class="x__Entity x__EType_OWALinkPreview x__EId_OWALinkPreview x__EReadonly_1" style="border: 0px; font: inherit; margin: 0px; padding: 0px; vertical-align: baseline; color: inherit;"><div id="LPBorder_GTaHR0cHM6Ly9naXRodWIuY29tL3NhZ2VtYXRoL3NhZ2Utd2luZG93cy9yZWxlYXNlcw.." class="x_LPBorder527393" style="border: 0px; font: inherit; margin: 16px 0px; padding: 0px; vertical-align: baseline; color: inherit; width: 800px; max-width: 800px; min-width: 424px; position: relative;">

  | Releases · sagemath/sage-windowsBuild tools for the Sagemath Windows installer. Contribute to sagemath/sage-windows development by creating an account on GitHub.github.com
-- | --

</div></div><div class="x_elementToProof" style="border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: 12pt; line-height: inherit; font-family: Calibri, Helvetica, sans-serif; font-optical-sizing: inherit; font-kerning: inherit; font-feature-settings: inherit; font-variation-settings: inherit; margin: 0px; padding: 0px; vertical-align: baseline; color: rgb(0, 0, 0);"><span class="x_ContentPasted1" style="border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: 12pt; line-height: inherit; font-family: inherit; font-optical-sizing: inherit; font-kerning: inherit; font-feature-settings: inherit; font-variation-settings: inherit; margin: 0px; padding: 0px; vertical-align: baseline; color: inherit;">Looking forward to remedial measures from you at the earliest.</span><div class="x_ContentPasted1" style="border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: 12pt; line-height: inherit; font-family: inherit; font-optical-sizing: inherit; font-kerning: inherit; font-feature-settings: inherit; font-variation-settings: inherit; margin: 0px; padding: 0px; vertical-align: baseline; color: inherit;">Thank you,</div><span style="border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: 12pt; line-height: inherit; font-family: inherit; font-optical-sizing: inherit; font-kerning: inherit; font-feature-settings: inherit; font-variation-settings: inherit; margin: 0px; padding: 0px; vertical-align: baseline; color: inherit;"></span>SageMath User,</div><div class="x_elementToProof" style="border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: 12pt; line-height: inherit; font-family: Calibri, Helvetica, sans-serif; font-optical-sizing: inherit; font-kerning: inherit; font-feature-settings: inherit; font-variation-settings: inherit; margin: 0px; padding: 0px; vertical-align: baseline; color: rgb(0, 0, 0);">W.M.D.</div></div></div></div></div><div class="g4Y3U" style="border: 0px; font: inherit; margin: 0px; padding: 0px; vertical-align: baseline; color: inherit; clear: both;"></div><div tabindex="-1" class="th6py full HJy2l" style="border: 0px; font: inherit; margin: 12px 16px 0px -4px; padding: 0px; vertical-align: baseline; color: inherit; -webkit-box-align: center; align-items: center; display: flex; flex-wrap: wrap; position: relative;"><div class="FGlQz body-156" style="border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: 14px; line-height: inherit; font-family: &quot;Segoe UI&quot;, &quot;Segoe UI Web (West European)&quot;, &quot;Segoe UI&quot;, -apple-system, BlinkMacSystemFont, Roboto, &quot;Helvetica Neue&quot;, sans-serif; font-optical-sizing: inherit; font-kerning: inherit; font-feature-settings: inherit; font-variation-settings: inherit; margin: 0px; padding: 0px; vertical-align: baseline; color: var(--neutralPrimary); background-image: ; background-position-x: ; background-position-y: ; background-size: ; background-repeat-x: ; background-repeat-y: ; background-attachment: ; background-origin: ; background-clip: ; background-color: var(--neutralPrimarySurface); -webkit-font-smoothing: antialiased;"><button type="button" aria-label="Reply" class="ms-Button ms-Button--action ms-Button--command d5kvP full xgQkx FGlQz root-873" data-is-focusable="true" style="border: 1px solid var(--neutralTertiaryAlt); font-style: inherit; font-variant: inherit; font-weight: 600; font-stretch: inherit; font-size: 14px; line-height: inherit; font-family: &quot;Segoe UI&quot;, &quot;Segoe UI Web (West European)&quot;, &quot;Segoe UI&quot;, -apple-system, BlinkMacSystemFont, Roboto, &quot;Helvetica Neue&quot;, sans-serif; font-optical-sizing: inherit; font-kerning: inherit; font-feature-settings: inherit; font-variation-settings: inherit; margin: 4px 0px 0px 4px; padding: 0px 8px; vertical-align: baseline; color: unset; outline: transparent; position: relative; -webkit-font-smoothing: antialiased; border-radius: 4px; box-sizing: border-box; cursor: pointer; display: inline-block; text-decoration: none; text-align: center; height: 32px; background-color: var(--neutralPrimarySurface); user-select: none; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial; min-width: 0px; white-space: nowrap; width: fit-content;"><span class="ms-Button-flexContainer flexContainer-279" data-automationid="splitbuttonprimary" style="border: 0px; font: inherit; margin: 0px; padding: 0px; vertical-align: baseline; color: inherit; display: flex; height: 30px; flex-wrap: nowrap; justify-content: flex-start; align-items: center;"><i data-icon-name="ArrowReplyRegular" aria-hidden="true" class="ms-Icon root-90 ms-Button-icon icon-874" style="display: flex; font-size: 20px; margin: 0px 4px; height: auto; line-height: 16px; text-align: center; flex-shrink: 0; color: var(--themeDarkAlt);"><span role="presentation" aria-hidden="true" class="FLwLv" style="border: 0px; font: inherit; margin: 0px; padding: 0px; vertical-align: middle; color: inherit; display: inline-block; height: 1em; width: 1em; contain: layout;"><i class="Q0K3G ___198tor0 f14t3ns0 fne0op0 fg4l7m0 fmd4ok8 f1sxfq9t" fill="currentColor" aria-hidden="true" style="font-family: FluentSystemIcons; display: inline-block; font-style: normal; line-height: 1em; contain: layout; fill: currentcolor; font-weight: 400; height: 20px; vertical-align: top; width: 20px;"></i></span></i><span class="ms-Button-textContainer textContainer-280" style="border: 0px; font: inherit; margin: 0px; padding: 0px; vertical-align: baseline; color: inherit; flex-grow: 0; display: block;"><span class="ms-Button-label label-171" id="id__1992" style="border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: 14px; font-family: inherit; font-optical-sizing: inherit; font-kerning: inherit; font-feature-settings: inherit; font-variation-settings: inherit; margin: 0px 4px; padding: 0px; vertical-align: baseline; color: inherit; display: block;">Reply</span></span></span></button></div><div class="FGlQz body-156" style="border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: 14px; line-height: inherit; font-family: &quot;Segoe UI&quot;, &quot;Segoe UI Web (West European)&quot;, &quot;Segoe UI&quot;, -apple-system, BlinkMacSystemFont, Roboto, &quot;Helvetica Neue&quot;, sans-serif; font-optical-sizing: inherit; font-kerning: inherit; font-feature-settings: inherit; font-variation-settings: inherit; margin: 0px; padding: 0px; vertical-align: baseline; color: var(--neutralPrimary); background-image: ; background-position-x: ; background-position-y: ; background-size: ; background-repeat-x: ; background-repeat-y: ; background-attachment: ; background-origin: ; background-clip: ; background-color: var(--neutralPrimarySurface); -webkit-font-smoothing: antialiased;"><button type="button" aria-label="Forward" class="ms-Button ms-Button--action ms-Button--command d5kvP full xgQkx FGlQz root-873" data-is-focusable="true" style="border: 1px solid var(--neutralTertiaryAlt); font-style: inherit; font-variant: inherit; font-weight: 600; font-stretch: inherit; font-size: 14px; line-height: inherit; font-family: &quot;Segoe UI&quot;, &quot;Segoe UI Web (West European)&quot;, &quot;Segoe UI&quot;, -apple-system, BlinkMacSystemFont, Roboto, &quot;Helvetica Neue&quot;, sans-serif; font-optical-sizing: inherit; font-kerning: inherit; font-feature-settings: inherit; font-variation-settings: inherit; margin: 4px 0px 0px 4px; padding: 0px 8px; vertical-align: baseline; color: unset; outline: transparent; position: relative; -webkit-font-smoothing: antialiased; border-radius: 4px; box-sizing: border-box; cursor: pointer; display: inline-block; text-decoration: none; text-align: center; height: 32px; background-color: var(--neutralPrimarySurface); user-select: none; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial; min-width: 0px; white-space: nowrap; width: fit-content;"><span class="ms-Button-flexContainer flexContainer-279" data-automationid="splitbuttonprimary" style="border: 0px; font: inherit; margin: 0px; padding: 0px; vertical-align: baseline; color: inherit; display: flex; height: 30px; flex-wrap: nowrap; justify-content: flex-start; align-items: center;"><i data-icon-name="ArrowForwardRegular" aria-hidden="true" class="ms-Icon root-90 ms-Button-icon icon-874" style="display: flex; font-size: 20px; margin: 0px 4px; height: auto; line-height: 16px; text-align: center; flex-shrink: 0; color: var(--themeDarkAlt);"><span role="presentation" aria-hidden="true" class="FLwLv" style="border: 0px; font: inherit; margin: 0px; padding: 0px; vertical-align: middle; color: inherit; display: inline-block; height: 1em; width: 1em; contain: layout;"><i class="Q0K3G ___198tor0 f14t3ns0 fne0op0 fg4l7m0 fmd4ok8 f1sxfq9t" fill="currentColor" aria-hidden="true" style="font-family: FluentSystemIcons; display: inline-block; font-style: normal; line-height: 1em; contain: layout; fill: currentcolor; font-weight: 400; height: 20px; vertical-align: top; width: 20px;"></i></span></i><span class="ms-Button-textContainer textContainer-280" style="border: 0px; font: inherit; margin: 0px; padding: 0px; vertical-align: baseline; color: inherit; flex-grow: 0; display: block;"><span class="ms-Button-label label-171" id="id__1995" style="border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: 14px; font-family: inherit; font-optical-sizing: inherit; font-kerning: inherit; font-feature-settings: inherit; font-variation-settings: inherit; margin: 0px 4px; padding: 0px; vertical-align: baseline; color: inherit; display: block;">Forward</span></span></span></button></div></div></div></div><br class="Apple-interchange-newline">
</body>
</html>To,
 SageMath Developer,
Sir,
Hi, I downloaded and installed SageMath-9.2-Installer-v0.6.1.exe from [Releases · sagemath/sage-windows (github.com)](https://github.com/sagemath/sage-windows/releases) for Windows 10,64 bit, version 22H2. But SageMath console crashed at once when I opened it by clicking on its icon.  The file containing the Sage Crash Report is attached herewith. I hope you will understand and correct this issue. 

[Releases · sagemath/sage-windows](https://github.com/sagemath/sage-windows/releases)
Build tools for the Sagemath Windows installer. Contribute to sagemath/sage-windows development by creating an account on GitHub.
github.com
Looking forward to remedial measures from you at the earliest.
Thank you,
SageMath User,
W.M.D.
[Sage_crash_report.txt](https://github.com/sagemath/sage/files/11745676/Sage_crash_report.txt)

**Comment by fchapoton** [comment]
Sagemath 9.2 is very old and no longer supported. Use Windows Subsystem for Linux and install Sagemath 10.0 in there.
