### ISSUE TITLE
Fix enumeration/cardinality of `UnorderedTuples`, remove dependency on GAP (for modularization)

### ISSUE THREAD

**Issue by mkoeppe** [sagemath/sage#35784]
That's a gratuitous dependency on a heavy library, which could be rewritten using just `itertools`.

Part of:
- https://github.com/sagemath/sage/issues/29705

**Comment by deinst** [comment]
I am more than willing to fix this,  but I am less than certain what should be done in the case where the underlying iterable has duplicates.  For example,

   sage: S=[1,1,2,3,4,5]
   sage: t = Tuples(S,2)
   sage: t.cardinality() 
   25
   sage: len(t.list())
   36

My instinct is that `Tuples.__iter__()` is incorrectly implemented (it should ignore the second '1'), but I don't want to break anyone that might depend on the original behavior.

**Comment by mkoeppe** [comment]
This does look like a bug to me. @tscrim, @fchapoton, do you agree?

**Comment by tscrim** [comment]
I agree that it is a bug. As such, @deinst you do not have to fix other people's code relying on bad behavior. I would just implement both iterators with `itertools` and directly implement the formulas for their `cardinality()` methods.
