### ISSUE TITLE
recursion limit gets reset (but only in batch mode)

### ISSUE THREAD

**Issue by dm248** [sagemath/sage#35803]
### Is there an existing issue for this?

- [X] I have searched the existing issues for a bug report that matches the one I want to file, without success.

### Did you read the documentation and troubleshoot guide?

- [X] I have read the documentation and troubleshoot guide

### Environment

```markdown
- **OS**: Linux Mint 20.2 (Ubuntu 20.04 variant)
- **Sage Version**: 10.1.beta3, Release Date: 2023-06-11 (pulled from github a few days ago)
                    bug also exhibited by sage 9.6 
- **build steps**: 
configure
make
make install
```

### Steps To Reproduce

Run the following lines in batch mode (e.g., sage tst.sage). You will see the recursion limit being reset to the default 3000 by P = Z[x]. Interestingly, it works fine if you type the same lines in the interpreter..

#tst.sage
N = 100
sys.setrecursionlimit(2**31 - 1)
Z = Zmod(N)
print(f"RECURSION LIMIT: {sys.getrecursionlimit()}")
P = Z[x]
print(f"RECURSION LIMIT: {sys.getrecursionlimit()}")

### Expected Behavior

Defining a poly ring should not change the recursion limit - especially, it should not decrease it. 

### Actual Behavior

Recursion limit gets reset to the python default of 3000.

**Comment by mezzarobba** [comment]
```
~/tmp$ cat tst.py
import sys
from sage.all_cmdline import PolynomialRing, ZZ, x
print(f"RECURSION LIMIT: {sys.getrecursionlimit()}")
PolynomialRing(ZZ, 'x')
print(f"RECURSION LIMIT: {sys.getrecursionlimit()}")
PolynomialRing(ZZ, x)
print(f"RECURSION LIMIT: {sys.getrecursionlimit()}")
ZZ['x']
print(f"RECURSION LIMIT: {sys.getrecursionlimit()}")
ZZ[x]
print(f"RECURSION LIMIT: {sys.getrecursionlimit()}")

~/tmp$ sage -python tst.py
RECURSION LIMIT: 1000
RECURSION LIMIT: 1000
RECURSION LIMIT: 1000
RECURSION LIMIT: 1000
RECURSION LIMIT: 3000
```

**Comment by mezzarobba** [comment]
Ok so it looks like `ZZ[x]` somehow ends up importing jedi(!!!), and sure enough, at
https://github.com/davidhalter/jedi/blob/f2444b4be5e6040308fa587041957d6596dee500/jedi/api/__init__.py#L48 you can see that jedi unconditionally sets the recursion limit to 3000. The import of jedi is (indirectly) triggered by the instruction `from sage.repl.ipython_extension import run_once` at line 1019 of `interfaces/sympy.py`, and presumably this has already been done at startup time when running interactively...
