### ISSUE TITLE
macos:  Singular issues (version 4.3.2p2 from Homebrew)

### ISSUE THREAD

**Issue by GMS103** [sagemath/sage#35833]
### Is there an existing issue for this?

- [X] I have searched the existing issues for a bug report that matches the one I want to file, without success.

### Did you read the documentation and troubleshoot guide?

- [X] I have read the documentation and troubleshoot guide

### Environment

```markdown
- OS:  macOS 11.7.8, macOS 12.6.7, macOS 13.4.1
- Sage Version:  SageMath version 10.1.beta6
```

### Steps To Reproduce

```
% brew info singular
[…]
/opt/homebrew/Cellar/singular/4.3.2p2
[…]
% ./configure
[…]
singular: using system package; SPKG will not be installed
[…]
% make
[…]
% make ptestlong
[…]
% 
```

### Expected Behavior

```All tests passed!```

### Actual Behavior

1. ```./configure``` unexpectedly opens the URL
https://www.singular.uni-kl.de/Manual/4-3-2/
in one or more browsers.
2. ```make ptestlong``` gives (among other things):
```
sage -t --long --warn-long … --random-seed=… src/sage/modular/modform_hecketriangle/readme.py  # 1 doctest failed
sage -t --long --warn-long … --random-seed=… src/sage/modular/modform_hecketriangle/abstract_space.py  # 3 doctests failed
sage -t --long --warn-long … --random-seed=… src/sage/modular/modform_hecketriangle/space.py  # 2 doctests failed
sage -t --long --warn-long … --random-seed=… src/sage/interfaces/singular.py  # 5 doctests failed
sage -t --long --warn-long … --random-seed=… src/sage/libs/singular/function.pyx  # 1 doctest failed
sage -t --long --warn-long … --random-seed=… src/sage/libs/singular/singular.pyx  # 1 doctest failed
sage -t --long --warn-long … --random-seed=… src/sage/structure/coerce_actions.pyx  # 3 doctests failed
```

### Additional Information

See [SageMath_10.1.beta6_Singular_Homebrew.txt](https://github.com/sagemath/sage/files/11996081/SageMath_10.1.beta6_Singular_Homebrew.txt).

With ```./configure --without-system-singular``` ("standard, SPKG version 4.3.1p3 will be installed") none of the above 7 issues appears.  See [SageMath_10.1.beta6_Singular_SPKG.txt](https://github.com/sagemath/sage/files/11996082/SageMath_10.1.beta6_Singular_SPKG.txt).

For the time being, should Homebrew's Singular be ignored and the SPKG be built?

Should our ```configure``` be modified?

**Comment by jhpalmieri** [comment]
Should we close either this or #35273 (I don't care which)? This one is a bit more complete (including issue 1 about opening a web page during configure) and is focused on Singular.

I think that we should disallow homebrew's Singular. I also wonder what will go on if Sage packages version 4.3.2.p2 — see #35676.
