### ISSUE TITLE
accept fricas from the system

### ISSUE THREAD

**Issue by dimpase** [sagemath/sage#35837]
### Is there an existing issue for this?

- [X] I have searched the existing issues for a bug report that matches the one I want to file, without success.

### Problem Description

system-wide fricas is sometimes avaliable, and may be used instead of Sage-built one. 

### Proposed Solution

create spkg-configure for it

**Comment by slel** [comment]
From a discussion on fricas-devel:

- https://groups.google.com/g/fricas-devel/c/EC7n_spDOE8/m/wYafMehlCAAJ
