### ISSUE TITLE
Improve WSL permissions issue in "install from source" documentation

### ISSUE THREAD

**Issue by Daniel-Khodabakhsh** [sagemath/sage#35840]
### Is there an existing issue for this?

- [X] I have searched the existing issues for a bug report that matches the one I want to file, without success.

### Problem Description

Currently, the WSL permissions which is encountered when building Sage from source is under the [Ubuntu on Windows Subsystem for Linux (WSL) prerequisite installation](https://doc.sagemath.org/html/en/installation/source.html#ubuntu-on-windows-subsystem-for-linux-wsl-prerequisite-installation) section of the documentation.

![image](https://github.com/sagemath/sage/assets/9839187/e4d7eab3-376d-438b-ab0a-14c415a470ae)

However WSL is not Ubuntu on WSL. WSL supports multiple versions of Linux and Ubuntu is but one of them.

As someone who uses WSL and not Ubuntu, I skipped this section and spent and an hour tracking down the permissions error.

### Proposed Solution

Create a new WSL-specific section for this error and how to handle it.

### Alternatives Considered

There are no alternatives.

**Comment by mkoeppe** [comment]
PR welcome
