### ISSUE TITLE
abs/arg for complex numbers containing radicals

### ISSUE THREAD

**Issue by teschlg** [sagemath/sage#35871]
### Is there an existing issue for this?

- [X] I have searched the existing issues for a bug report that matches the one I want to file, without success.

### Problem Description

Neither abs nor square work in this case

[abs(1+I\*sqrt(3)), arg(1+I\*sqrt(3))]

### Proposed Solution

Of course the result should be

[2, pi/3]

### Alternatives Considered

Using

QQbar(1+I*sqrt(3)).abs()

seems to work, but it is hard to get the result in a nice form.

### Additional Information

One problem seems to be that sage does not recognize "1+I*sqrt(3)" as a number but thinks it is an symbolic expression.

**Comment by DaveWitteMorris** [comment]
You need to tell sagemath that you want the simplified forms of the expressions. 
```
sage: abs(1+I*sqrt(3)).simplify()
2
sage: arg(1+I*sqrt(3)).simplify()
1/3*pi
```
