### ISSUE TITLE
Wikipedia link not rendered correctly

### ISSUE THREAD

**Issue by wermos** [sagemath/sage#35938]
### Expected Behavior

The link should be rendered correctly.

### Actual Behavior

The Wikipedia link [here](https://doc.sagemath.org/html/en/reference/graphs/sage/graphs/connectivity.html#sage.graphs.connectivity.TriconnectivitySPQR) is not rendered correctly.

It shows up like this:
> See the:wikipedia:$SPQR_tree$.

### Environment

```markdown
Online documentation at https://doc.sagemath.org/html/en/
```

### Checklist

- [X] I have searched the existing issues for a bug report that matches the one I want to file, without success.
- [X] I have read the documentation and troubleshoot guide

**Comment by grhkm21** [comment]
<img width="672" alt="Screenshot 2023-07-12 at 17 00 34" src="https://github.com/sagemath/sage/assets/83517584/1c1c15dd-a4c6-44e9-94f4-c5915cf93f85">

Not for me?

**Comment by wermos** [comment]
Huh, it is working for me now too. I guess it was a random one-time thing. I'll close the issue, in that case.
