### ISSUE TITLE
Non-homogeneous GradedModularFormElement multiplication and exponentiation is incorrect

### ISSUE THREAD

**Issue by grhkm21** [sagemath/sage#35932]
### Steps To Reproduce

Code:

```python
sage: M = ModularFormsRing(1)
sage: E4, E6 = M.gens()
sage: E4 + M(1)
2 + 240*q + 2160*q^2 + 6720*q^3 + 17520*q^4 + 30240*q^5 + O(q^6)
sage: (E4 + M(1))^2
3 + 720*q + 64080*q^2 + 1056960*q^3 + 7943760*q^4 + 37530720*q^5 + O(q^6)
```

### Expected Behavior

Well, it should start with `4 + ...` since `E4 + M(1)` start with `2 + ...`. In particular, it should be `E4^2 + 2 * E4 + 1` instead of the current computed `E4^2 + E4 + 1`.

### Actual Behavior

I found the buggy line, so I will just report it (and make a PR soon): On line 3558 of `sage.modular.modform`, i.e. inside the `_mul_` method of `GradedModularFormElement`, it has the following incorrect line:

```python
        GM = self.__class__
        f_self = self._forms_dictionary
        f_other = other._forms_dictionary
        f_mul = {}
        for k_self in f_self.keys():
            for k_other in f_other.keys():
                f_mul[k_self + k_other] = f_self[k_self]*f_other[k_other]        # Line 3558
        return GM(self.parent(), f_mul)
```
It should be `+=` instead of `=`, just like normal polynomial multiplication.

### Environment

```markdown
- **Sage Version**: 10.0
```

### Checklist

- [X] I have searched the existing issues for a bug report that matches the one I want to file, without success.
- [X] I have read the documentation and troubleshoot guide

**Comment by grhkm21** [comment]
Is it possible for me to add labels (modular-forms) myself? Or can I not because I haven't made any contributions to the repo before?

**Comment by sheerluck** [comment]
```diff
--- a/element.py
+++ b/element.py
@@ -3555,7 +3555,10 @@
         f_mul = {}
         for k_self in f_self.keys():
             for k_other in f_other.keys():
-                f_mul[k_self + k_other] = f_self[k_self]*f_other[k_other]
+                if k_self + k_other in f_mul:
+                    f_mul[k_self + k_other] += f_self[k_self]*f_other[k_other]
+                else:
+                    f_mul[k_self + k_other] = f_self[k_self]*f_other[k_other]
         return GM(self.parent(), f_mul)
 
     def _lmul_(self, c):
```
with that I get `4 + 960*q + 66240*q^2 + 1063680*q^3 + 7961280*q^4 + 37560960*q^5 + O(q^6)` for `(E4 + M(1)) ^ 2`

**Comment by grhkm21** [comment]
@sheerluck Oops, I forgot to push the patch. I will push it to https://github.com/sagemath/sage/pull/35944 since it's relevant for that as well

<img width="407" alt="Screenshot 2023-07-14 at 16 12 07" src="https://github.com/sagemath/sage/assets/83517584/39b1298d-8792-4ac8-9115-0768b45fc75f">

**Comment by DavidAyotte** [comment]
Hello, this is indeed a bug, thank you for reporting this and fixing it. I will review the patch once it is finished.
