### ISSUE TITLE
Matroid .equals() Function Returns True For Uniform Matroids of Different Rank

### ISSUE THREAD

**Issue by jsantillan3** [sagemath/sage#35946]
### Steps To Reproduce

```
sage: M = matroids.Uniform(3,5)
sage: U = matroids.Uniform(2,5)
sage: M.equals(U)
```

### Expected Behavior

These matroids are not equal, `M.equals(U)` should return `False`

### Actual Behavior

`M.equals(U)` returns `True`

### Additional Information
@mkoeppe @xuluze

### Environment

```markdown
- **OS**:
- **Sage Version**:
```

### Checklist

- [X] I have searched the existing issues for a bug report that matches the one I want to file, without success.
- [X] I have read the documentation and troubleshoot guide

**Comment by grhkm21** [comment]
Hi, just to be clear, I don't know too much about matroid theory. However, looking at the docs and [source code](https://github.com/sagemath/sage/blob/1ca4a47dbd7c59f09b4840d66f6ced9edde9686a/src/sage/matroids/matroid.pyx#L3354), it says that `.equals` checks for Matroid equality, which only requires them to "have the same groundset and a subset `X` is independent in `M` $\iff$ it is independent in `N`" (i.e. some kind of isomorphism). Are you aware of that and does your example really contradict this definition?

There's also this note below:

```
        .. NOTE::

            This method tests abstract matroid equality. The ``==`` operator
            takes a more restricted view: ``M == N`` returns ``True`` only if

            #. the internal representations are of the same type,
            #. those representations are equivalent (for an appropriate
               meaning of "equivalent" in that class), and
            #. ``M.equals(N)``.
```
And indeed running `==` on your example gives the expected `False`.

**Comment by DaveWitteMorris** [comment]
Thanks for the bug report. This answer is certainly not correct, but I don't know where the problem is, so it will require investigation.
