### ISSUE TITLE
SageMath should upgrade the jupyter_core spkg from 4.11.2 to 4.12.0

### ISSUE THREAD

**Issue by culler** [sagemath/sage#35953]
### Steps To Reproduce

Install a current version of jupyterlab with sage -pip and start the server.

### Expected Behavior

server runs

### Actual Behavior

An exception is thrown because jupyterlab expects to find ensure_async in the jupyter-core package but it does not exist in 4.11.2.  It does exist in 4.12.0.  It disappears in the early 5.X versions. So 4.12.0 (the latest with major version 4) is the sweet spot. I have tested, and both the sage notebook and jupyter lab work fine with 4.12.0.

### Environment

```markdown
- **OS**: MacOS
- **Sage Version**: 10.0
```

### Checklist

- [X] I have searched the existing issues for a bug report that matches the one I want to file, without success.
- [X] I have read the documentation and troubleshoot guide

**Comment by mkoeppe** [comment]
4.12.0 is a strange release; it only exists on PyPI but is not mentioned anywhere else

**Comment by mkoeppe** [comment]
Looks like a safe change, as it only adds PR https://github.com/jupyter/jupyter_core/pull/317
