### ISSUE TITLE
Bug in the result give by the modular decomposition

### ISSUE THREAD

**Issue by Nasaku03** [sagemath/sage#36012]
### Steps To Reproduce

1. In jupyter, i executed:
2. from sage.graphs.graph_decompositions.modular_decomposition import \
              modular_decomposition, test_modular_decomposition, print_md_tree
d = {1:[2,5], 2:[1,3,5], 3:[2,4,5], 4:[3,5], 5:[1,2,3,4,6], 6:[5,7,8], 7:[6,8,9,10,11,12,13], 8:[6,7,9,10,11,12,13], 9:[7,8], 10:[7,8,11], 11:[7,8,10,12], 12:[7,8,11,13], 13:[7,8,12]}
g = Graph(d)
print_md_tree(modular_decomposition(g))

### Expected Behavior

**PRIME
.SERIES
..8
..7
.PARALLEL
..PRIME
...10
...11
...12
...13
..9
.6
.5
.PRIME
..2
..1
..3
..4**

### Actual Behavior

**PRIME
.SERIES
..8
..7
.PARALLEL
..SERIES
...11
...PARALLEL
....10
....12
....13
..9
.6
.5
.PRIME
..2
..1
..3
..4**

### Environment

```markdown
- **OS**:Ubuntu 20.04
- **Sage Version**:9.5
```

### Checklist

- [X] I have searched the existing issues for a bug report that matches the one I want to file, without success.
- [X] I have read the documentation and troubleshoot guide

**Comment by dcoudert** [comment]
Related issues #25872, #33902

**Comment by dcoudert** [comment]
Thank you for reporting. We had many issues with a former implementation of the method and we changed that.
You should consider upgrading to a newer version of Sagemath (e.g. 10.0).

```py
┌────────────────────────────────────────────────────────────────────┐
│ SageMath version 10.1.beta9, Release Date: 2023-08-05              │
│ Using Python 3.11.3. Type "help()" for help.                       │
└────────────────────────────────────────────────────────────────────┘
┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
┃ Warning: this is a prerelease version, and it may be unstable.     ┃
┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛
sage: from sage.graphs.graph_decompositions.modular_decomposition import modular_decomposition, test_modular_decomposition, print_md_tree
....: d = {1:[2,5], 2:[1,3,5], 3:[2,4,5], 4:[3,5], 5:[1,2,3,4,6], 6:[5,7,8], 7:[6,8,9,10,11,12,13], 8:[6,7,9,10,11,12,13], 9:[7,8], 10:[7,8,11], 11:[7
....: ,8,10,12], 12:[7,8,11,13], 13:[7,8,12]}
....: g = Graph(d)
....: print_md_tree(modular_decomposition(g))
PRIME
 SERIES
  7
  8
 5
 PRIME
  2
  1
  3
  4
 6
 PARALLEL
  PRIME
   11
   10
   12
   13
  9
```
