### ISSUE TITLE
old Polymake incompatibility with system Perl 5.38 (Fedora 39) - update to polymake 4.11

### ISSUE THREAD

**Issue by mkoeppe** [sagemath/sage#36023]
https://forum.polymake.org/viewtopic.php?t=1914

Polymake recommends installing suitable Perl via perlbrew:
https://polymake.org/doku.php/install/install#perlbrew

Polymake also provides BinaryBuilder.org/JLL-based binaries that ship a suitable Perl (and all libraries include gmp, ...). 
- https://polymake.org/doku.php/install/jll
- ... made using https://github.com/JuliaPackaging/JLLPrefixes.jl and https://github.com/benlorenz/pmjll
- ... from https://github.com/JuliaBinaryWrappers/Perl_jll.jl (built from https://github.com/JuliaPackaging/Yggdrasil/tree/master/P/Perl/bundled)
- ... from https://github.com/JuliaBinaryWrappers/polymake_jll.jl 
- etc.

**Comment by orlitzky** [comment]
Polymake is masked for removal on Gentoo too for the same issue.

**Comment by dimpase** [comment]
https://github.com/polymake/polymake/releases/tag/V4.11 has perl 5.38 support, all rejoice please
