### ISSUE TITLE
archlinux-latest-standard: System maxima does not work

### ISSUE THREAD

**Issue by mkoeppe** [sagemath/sage#36028]
Building the documentation fails with this:

https://github.com/sagemath/sage/actions/runs/5706565894/job/15465342057#step:8:2303
```
  [sagemath_doc_html-none]   ;;; Warning: Maxima is unable to set up the help system.
  [sagemath_doc_html-none]   (Details: CL-INFO::LOAD-PRIMARY-INDEX: Filesystem error with pathname #P"/usr/share/info/maxima-index.lisp".
  [sagemath_doc_html-none]   Either
  [sagemath_doc_html-none]    1) the file does not exist, or
  [sagemath_doc_html-none]    2) we are not allowed to access the file, or
  [sagemath_doc_html-none]    3) the pathname points to a broken symbolic link.)
  [sagemath_doc_html-none]   
```

@dimpase @antonio-rojas @orlitzky

**Comment by antonio-rojas** [comment]
Arch Linux docker images don't intall files in /usr/share/{man,info} for space saving reasons.

The line `NoExtract  = usr/share/man/* usr/share/info/*` needs to be removed from `/etc/pacman.conf` in the docker image for this to work.

**Comment by mkoeppe** [comment]
OK, this means that we need to improve the spkg-configure.m4 for maxima

**Comment by dimpase** [comment]
do we have ability to patch Docker images we use for CI? Surely, we can run an appropriate `sed` incantation before each call to `pacman` in `build/bin/write-dockerfile.sh`, but it's kinda ugly...

**Comment by orlitzky** [comment]
What is failing? Sphinx is as helpful as ever.

**Comment by dimpase** [comment]
on Archlinux's default Docker image, maxima docs are not installed by default, leading to a broken (for Sage's purposes) install of Maxima

**Comment by orlitzky** [comment]
But why do we need the maxima docs to build what looks like the plotting documentation?

**Comment by dimpase** [comment]
it does not seem to to be related to plotting. If I try to reproduce this locally on a Debian system, by removing the lisp file in question, I see
```
[sagemath_doc_html-none] sage --docbuild --no-pdf-links reference/combinat inventory --no-prune-empty-dirs
[sagemath_doc_html-none] [combinat ] building [inventory]: targets for 200 source files that are out of date
[sagemath_doc_html-none] [combinat ] updating environment: [config changed ('version')] 374 added, 0 changed, 1 removed
[sagemath_doc_html-none] [combinat ] /home/dimpase/work/software/sage/local/var/lib/sage/venv-python3.9/lib/python3.9/site-packages/sphinx/util/inspect.py:376: DeprecationWarning: this class is deprecated, do not use
[sagemath_doc_html-none] [combinat ] See https://github.com/sagemath/sage/issues/31545 for details.
[sagemath_doc_html-none] [combinat ]   return getattr(obj, name, *defargs)
[sagemath_doc_html-none] ;;; Warning: Maxima is unable to set up the help system.
[sagemath_doc_html-none] (Details: CL-INFO::LOAD-PRIMARY-INDEX: Filesystem error with pathname #P"/home/dimpase/work/software/sage/local/share/info/maxima-index.lisp".
[sagemath_doc_html-none] Either
[sagemath_doc_html-none]  1) the file does not exist, or
...
```
that is, `sphinx` is calling `getattr()` on a Sage object which insists on Maxima having help installed.

**Comment by dimpase** [comment]
> OK, this means that we need to improve the spkg-configure.m4 for maxima

done in #36391
