### ISSUE TITLE
msolve interface is missing support for non-finite fields

### ISSUE THREAD

**Issue by maxale** [sagemath/sage#36055]
### Problem Description

While `msolve` well support equations over `QQ`, Sage's interface does not support anything besides finite fields of bounded characteristic:
```
File /usr/local/sage/sage/src/sage/rings/polynomial/msolve.py:106, in groebner_basis_degrevlex(ideal)
    103 base = ideal.base_ring()
    104 if not (isinstance(base, FiniteField) and base.is_prime_field() and
    105         base.characteristic() < 2**31):
--> 106     raise NotImplementedError(f"unsupported base field: {base}")
    108 drlpolring = ideal.ring().change_ring(order='degrevlex')
    109 msolve_out = _run_msolve(ideal, ["-g", "2"])

NotImplementedError: unsupported base field: Rational Field
```

### Proposed Solution

Add to Sage's interface support for every field that is supported by `msolve`.

### Alternatives Considered

N/A

### Is there an existing issue for this?

- [X] I have searched the existing issues for a bug report that matches the one I want to file, without success.

**Comment by mezzarobba** [comment]
Actually the interface does support all fields that were supported by msolve 0.4.9, that is, if I recall correctly:
- for computing zero-dimensional varieties, small prime fields and ℝ (ℚ and its extensions, as well as extensions of small prime fields, are not supported natively by msolve but supported by the interface by combining msolve's support for parameterizations with Sage's rootfinders),
- for computing Gröbner bases, small prime fields only.
msolve 0.5.0 added support (or at least some support?) for Gröbner bases over the rationals. I believe this is the only feature for which the interface is not up to date. Were you thinking of anything else?

**Comment by maxale** [comment]
Indeed, my primary interest is in Gröbner bases computation over `QQ`, and I did not check what other features may be missing in the msolve interface.

**Comment by mezzarobba** [comment]
Ok, thanks. If you want you can try the linked PR and see if it fixes the issue.
