### ISSUE TITLE
get rid of obsolete PyInt_* and PyInt_*

### ISSUE THREAD

**Issue by dimpase** [sagemath/sage#36081]
### Steps To Reproduce

According to https://py3c.readthedocs.io/ all these `PyInt_AS_LONG`, etc should become `PyLong_AS_LONG`, etc etc

However, this is still not fixed, and cause trouble now and then, see e.g. #36080 

In few places, where C/C++ header files are used in Sage, one sees C redefines:
https://github.com/sagemath/sage/blob/0fd596703c824a53f4ffb54556f336de436dde59/src/sage/geometry/triangulation/triangulations.h#L9

But this is not how things should be done in the long run.

### Expected Behavior

There should be no obsolete low level ``PyInt_...` calls.

### Actual Behavior

They are still there.

### Environment

```markdown
not platform-dependent
```

### Checklist

- [X] I have searched the existing issues for a bug report that matches the one I want to file, without success.
- [X] I have read the documentation and troubleshoot guide

**Comment by dimpase** [comment]
Note that the current CPython simply defines `PyLong_AS_LONG` as a (slow) `PyLong_AsLong`, see https://github.com/python/cpython/blob/2e1f688fe0f0a612e54c09f5a7027a834dd8b8d5/Include/longobject.h#L31

**Comment by fchapoton** [comment]
Here are the file containing `PyInt_AS_LONG`

```
src/sage/arith/long.pxd:1
src/sage/geometry/triangulation/triangulations.cc:3
src/sage/geometry/triangulation/triangulations.h:1
src/sage/modular/arithgroup/farey.hpp:1
src/sage/rings/complex_arb.pyx:3
src/sage/rings/finite_rings/integer_mod.pyx:4
src/sage/rings/integer.pyx:3
src/sage/rings/integer_ring.pyx:1
src/sage/rings/padics/common_conversion.pyx:1
src/sage/rings/padics/padic_template_element.pxi:2
src/sage/rings/polynomial/polynomial_integer_dense_flint.pyx:2
src/sage/rings/polynomial/polynomial_rational_flint.pyx:2
src/sage/rings/polynomial/polynomial_real_mpfr_dense.pyx:2
src/sage/rings/real_arb.pyx:5
```

**Comment by fchapoton** [comment]
please review #36111
