### ISSUE TITLE
PlanePartitions are not hashable

### ISSUE THREAD

**Issue by mantepse** [sagemath/sage#36118]
### Steps To Reproduce

```
sage: p = PlanePartitions(4).an_element(); p
Plane partition [[4]]
sage: hash(p)
Traceback (most recent call last):
...
TypeError: unhashable type: 'list'
```

### Expected Behavior

```
sage: p = PlanePartitions(4).an_element()
sage: hash(p)
```
should return a hash.

### Actual Behavior

A `TypeError` is raised.

### Additional Information

Plane partitions inherit from `ClonableArray`, but the elements of the array are lists, eg.:
```
    def __init__(self, parent, pp, check=True):
...
        if isinstance(pp, PlanePartition):
            ClonableArray.__init__(self, parent, pp, check=False)
        else:
            pp = [list(_) for _ in pp]
            if pp:
                for i in reversed(range(len(pp))):
                    while pp[i] and not pp[i][-1]:
                        del pp[i][-1]
                    if not pp[i]:
                        pp.pop(i)
            ClonableArray.__init__(self, parent, pp, check=check)
...
```

### Environment

```markdown
irrelevant.
```

### Checklist

- [X] I have searched the existing issues for a bug report that matches the one I want to file, without success.
- [X] I have read the documentation and troubleshoot guide

**Comment by Cobord** [comment]
Where are some places where PlanePartitions are being put into a set? Or any other places something that expects to be able to hash PlanePartitions but cannot?

**Comment by mantepse** [comment]
This is mostly needed in user code.  For example, imagine that you want to find a bijection between TSSCPP and ASM:
```
sage: n = 4
sage: A = AlternatingSignMatrices(n)
sage: B = PlanePartitions([2*n]*3, symmetry='TSSCPP')
sage: bij = Bijectionist(A, B)
# next, you would specify some statistics or maps to be preserved
# ...
sage: ascii_art(list(bij.minimal_subdistributions_iterator()))
```

**Comment by Cobord** [comment]
Then I wouldn't say a bug because that is a [more general issue](https://stackoverflow.com/questions/7842049/are-mutable-hashmap-keys-a-dangerous-practice). This is described well with the distinction of frozenset and set. That idea works around something mutating under your feet with a version that can't. For this example, what if there was a method that does some time step of a box falling problem that mutates the partition. I don't want to store every step as a brand new immutable object when I just want the final partition for some calculation about limit shapes.

**Comment by mantepse** [comment]
This sounds an awful lot like premature optimization. Why are you afraid of creating a new plane partition? Note that, in general, if you add a single box to an existing one, you may be copying the old one anyway. If you really need to squeeze out all you can I think it would be best to create a specialized class for "chains" of plane partitions.
