### ISSUE TITLE
 inconsistent depreciation of `UnionCombinatorialClass` and `FilteredCombinatorialClass`

### ISSUE THREAD

**Issue by dimpase** [sagemath/sage#36133]
@fchapoton This deprecation in #31545 is inconsistent. While `InfiniteAbstractCombinatorialClass` can indeed go (can be just removed now, as ~2 years passed  since its deprecation), `UnionCombinatorialClass` and `FilteredCombinatorialClass` are used in `CombinatorialClass` - which is not formally deprecated (there is a comment there saying it is, but no deprecation notice).

_Originally posted by @dimpase in https://github.com/sagemath/sage/issues/31545#issuecomment-1691357694_

**Comment by mkoeppe** [comment]
There are a bunch of related open issues. 
https://github.com/sagemath/sage/issues?q=is%3Aopen+sort%3Aupdated-desc+combinatorialclass
