### ISSUE TITLE
toml package is obsolete

### ISSUE THREAD

**Issue by orlitzky** [sagemath/sage#36175]
### Expected Behavior

toml is not installed

### Actual Behavior

toml is installed

### Additional Information

I think our `toml` package is obsolete. The only other package listing it as a requirement is tox, but tox only needs it with ancient pythons: https://github.com/tox-dev/tox/blob/3.27.1/setup.cfg#L45

I think our dependency can be replaced with tomli at which point toml can go.

### Environment

```markdown
Gentoo / git develop
```

### Checklist

- [X] I have searched the existing issues for a bug report that matches the one I want to file, without success.
- [X] I have read the documentation and troubleshoot guide

**Comment by mkoeppe** [comment]
Our tox needs to be updated to 4.x anyway - #34840
