### ISSUE TITLE
fix commit 8255c94 "Reject system Singular built without FLINT"

### ISSUE THREAD

**Issue by sheerluck** [sagemath/sage#36193]
### Steps To Reproduce

while creating docker images for september, I noticed, that my perfectly prepared `singular-4.3.2_p7` is rejected as
```
checking whether Singular is built with FLINT... no
```
well I know that my Singular is built with FLINT
so what is going on?

Turn out one line in commit `8255c94` is missing:
```diff
--- a/build/pkgs/singular/spkg-configure.m4
+++ b/build/pkgs/singular/spkg-configure.m4
@@ -12,6 +12,7 @@ SAGE_SPKG_CONFIGURE([singular], [
             #include <singular/singularconfig.h>
             #if !defined(HAVE_FLINT)
             #  error "Need Singular compiled with FLINT"
+            #endif
           ], [])
         ], [
           AC_MSG_RESULT([yes])
```
and that leads to `error: unterminated #if` and not to `error "Need Singular compiled with FLINT"`

When we added that missing line, we have
```
checking whether Singular is built with FLINT... yes
```
as it should be

### Expected Behavior

Singular is accepted

### Actual Behavior

Singular is rejected

### Environment

```markdown
- **OS**: all of them
- **Sage Version**: “master” branch
```

### Checklist

- [X] I have searched the existing issues for a bug report that matches the one I want to file, without success.
- [X] I have read the documentation and troubleshoot guide

**Comment by sheerluck** [comment]
I know I will be frowned upon and called irresponsible, but I really wish somebody just committed and pushed that lonely `#endif` into `develop` and closed this issue, skipping a fork/branch/PR/test/positive-review steps.

**Comment by orlitzky** [comment]
Just create a PR with that one line. You don't even have to run it. I'll test it real quick and positive-review it.
