### ISSUE TITLE
Can not create group homomorphism with trivial symmetric group as domain

### ISSUE THREAD

**Issue by ddorian1** [sagemath/sage#36204]
### Steps To Reproduce

Running the code

```python
h = SymmetricGroup(1).hom(SymmetricGroup(2))
```

or

```python
h = SymmetricGroup(1).hom([SymmetricGroup(2).gen()])
```

in the console or on SageMathCell.

### Expected Behavior

In both cases `h` should be the unique homomorphism from `SymmetricGroup(1)` to `SymmetricGroup(2)`.

### Actual Behavior

The first variant yields `GAPError: Error, <gens> and <imgs> must be lists of same length`, the second variant yields `ValueError: provide an image for each generator`.

### Additional Information

`SymmetricGroup(1).gens()` is a list of length 1, hence the second variant actually provides one image for each generator, in contrast to the error message.

### Environment

```markdown
- **OS**: SageMathCell
- **Sage Version**: 10.1
```

### Checklist

- [X] I have searched the existing issues for a bug report that matches the one I want to file, without success.
- [X] I have read the documentation and troubleshoot guide

**Comment by fchapoton** [comment]
Maybe related to
```
sage: SymmetricGroup(1).gens()
((),)
```
