### ISSUE TITLE
update nauty to version 2.8.6

### ISSUE THREAD

**Issue by maxale** [sagemath/sage#36257]
### Problem Description

[nauty](https://pallini.di.uniroma1.it) 2.8.6 was released almost a year ago, but Sage still uses version 2.7.x

### Proposed Solution

Please update the nauty package in Sage to the current version, and update Sage's interface to support the newly added options for `geng`.

### Alternatives Considered

N/A

### Is there an existing issue for this?

- [X] I have searched the existing issues for a bug report that matches the one I want to file, without success.

**Comment by mkoeppe** [comment]
@maxale Upgrade in #36541
