### ISSUE TITLE
sage-doc silently fails to build properly with recent furo (2023.8.19)

### ISSUE THREAD

**Issue by kiwifb** [sagemath/sage#36274]
### Environment

```markdown
- Gentoo
- sage-on-gentoo built 10.2.beta2 but probably all versions using system furo 2023.8.19 + affected.
```

### Steps To Reproduce

It is normal sage-on-gentoo build using all system components. During the build of documentation I have numerous message
```
This documentation is not using `furo.css` as the stylesheet. If you have set `html_style` in your conf.py file, remove it.
```
While the documentation seems to install correctly I have nothing apart from index html pages. All html pages with actual documentations are missing.

### Config log

Not relevant as configure is not run in such build.

### Checklist

- [X] I have searched the existing issues for a bug report that matches the one I want to file, without success.
- [X] I have read the documentation and troubleshoot guide

**Comment by kiwifb** [comment]
As it turns out furo-2023.8.19 has compatibility problems with some versions of sphinx. Version to avoid, 2023.9.10 works well.
https://github.com/pradyunsg/furo/commit/9e40071eb8c4c3e38845b57c4f5242bef2a44af2

**Comment by dimpase** [comment]
the up to date furo works great with sphinx 7.2.6 (with #36296). And Sage's furo doesn't work with the up to date furo.

It's high time we upgrade our sphinx, furo, etc...

Can this one be closed?

**Comment by kiwifb** [comment]
Yes. If we have all that coming and know what to avoid it is all good.
