### ISSUE TITLE
build/pkgs/toml doesn't have install info - remove?

### ISSUE THREAD

**Issue by dimpase** [sagemath/sage#36301]
### Steps To Reproduce

that's all it has:

```
$ ls -R build/pkgs/toml/
build/pkgs/toml/:
distros

build/pkgs/toml/distros:
arch.txt  debian.txt  fedora.txt  gentoo.txt  opensuse.txt
```

### Expected Behavior

it should not be there

### Actual Behavior

it is there. Remove?

### Environment

```markdown
all
```

### Checklist

- [X] I have searched the existing issues for a bug report that matches the one I want to file, without success.
- [X] I have read the documentation and troubleshoot guide

**Comment by dimpase** [comment]
@mkoeppe - you seem to have added these.

**Comment by mkoeppe** [comment]
This package was removed in #36176, but #36141 added these distro files.

Can be removed, e.g. as part of #36276
