### ISSUE TITLE
`setuptools_scm_git_archive` is obsolete since setuptools_scm version 7

### ISSUE THREAD

**Issue by frenzymadness** [sagemath/sage#36317]
setuptools_scm version 7 and newer supports Git archives by itself. The migration guide is available in the [Readme](https://github.com/Changaco/setuptools_scm_git_archive#readme) of the project.

The problem is, that the plugin [is not compatible](https://github.com/Changaco/setuptools_scm_git_archive/issues/23) with setuptools_scm 8, and the incompatibility might break your builds.

**Comment by mkoeppe** [comment]
Thanks! Removed in #36319.
