### ISSUE TITLE
allow use of ptyprocess>0.5.1

### ISSUE THREAD

**Issue by dimpase** [sagemath/sage#36331]
This is a macOS-only problem.

 -----------

Even just upgrading `ptyprocess` from 0.5.1 to 0.5.2 causes the breakage. All later versions (0.6.0, 0.7.0) are broken.

_Originally posted by @mkoeppe in https://github.com/sagemath/sage/issues/31280#issuecomment-1418118629_

**Comment by mkoeppe** [comment]
Dup of #32147
