### ISSUE TITLE
Incremental workflow is failing and spawning multiple builds

### ISSUE THREAD

**Issue by tobiasdiez** [sagemath/sage#36350]
### Steps To Reproduce

https://github.com/sagemath/sage/actions/runs/6332485170/job/17199091624
https://github.com/sagemath/sage/actions/runs/6332567933

### Expected Behavior

Builds pass

### Actual Behavior

Builds fail, and there are a lot of them that take quite a long time and block ci of other PRs.

### Additional Information

I've disabled the workflow for now, until this is fixed.

### Environment

```markdown
CI
```

### Checklist

- [X] I have searched the existing issues for a bug report that matches the one I want to file, without success.
- [X] I have read the documentation and troubleshoot guide

**Comment by mkoeppe** [comment]
The **PR tested there** (#36129) needs work, that's all.

**Comment by mkoeppe** [comment]
So kindly reactivate the workflows.

**Comment by tobiasdiez** [comment]
Please have a look at the logs again.

**Comment by mkoeppe** [comment]
?

**Comment by tobiasdiez** [comment]
Did you actually looked at the logs again? There were three prs failing, all because of missing setuptools
