### ISSUE TITLE
De Bruijn Graph plot has shifted vertex.

### ISSUE THREAD

**Issue by jfab20** [sagemath/sage#36384]
### Steps To Reproduce

```
from sage.graphs import * 
D = digraphs.DeBruijn(2,2)
P = plot(D, vertex_size=500)
P.show()
```

The picture that I get is the following:
![t2p6](https://github.com/sagemath/sage/assets/81712003/5b4a0543-96a0-403c-b818-1c31d6aacf94)

### Expected Behavior

The plot of the graph is normal.

### Actual Behavior

There are weird circles appearing below the 00 and 11 vertices.

### Environment

```markdown
- **OS**: 6.5.5-arch1-1
- **Sage Version**: 10.1
```

### Checklist

- [X] I have searched the existing issues for a bug report that matches the one I want to file, without success.
- [X] I have read the documentation and troubleshoot guide

**Comment by DaveWitteMorris** [comment]
The plot is correct:
```python
sage: D
De Bruijn digraph (k=2, n=2): Looped digraph on 4 vertices
```
The circles that you see are the loops.  If you don't want them, type `D.remove_loops()` before defining `P`. Then `P.show()` will give the picture that you expected.

**Comment by jfab-123** [comment]
> The plot is correct:
> 
> ```python
> sage: D
> De Bruijn digraph (k=2, n=2): Looped digraph on 4 vertices
> ```
> 
> The circles that you see are the loops. If you don't want them, type `D.remove_loops()` before defining `P`. Then `P.show()` will give the picture that you expected.

That's how loops are plotted? Can't you represent the loop as an arrow from the vertex to itself?
