### ISSUE TITLE
Problems with Jupyter integration

### ISSUE THREAD

**Issue by o0nd7ots** [sagemath/sage#36414]
### Steps To Reproduce

1. Be on Arch-based distro (Artix in my case)
2. run pacman -S sagemath jupyter-notebook
3. `sagemath` works fine but `sage -n jupyter` produces an error:
```
┌────────────────────────────────────────────────────────────────────┐
│ SageMath version 10.1, Release Date: 2023-08-20                    │
│ Using Python 3.11.5. Type "help()" for help.                       │
└────────────────────────────────────────────────────────────────────┘
Please wait while the Sage Jupyter Notebook server starts...
Traceback (most recent call last):
  File "/usr/bin/sage-notebook", line 32, in __init__
    from notebook.notebookapp import main
ModuleNotFoundError: No module named 'notebook.notebookapp'
The Jupyter notebook is not installed (at least not in this Sage installation).
You can install it by running
  sage -i notebook
Alternatively, you can follow the instructions at
  https://doc.sagemath.org/html/en/installation/launching.html#setting-up-sagemath-as-a-jupyter-kernel-in-an-existing-jupyter-notebook-or-jupyterlab-installation
to use Sage with an existing Jupyter notebook installation.
```
4. run `sage -i notebook`. Get another error: `Error: unknown option: -i`
5. Follow the steps from the [official website](https://doc.sagemath.org/html/en/installation/launching.html#setting-up-sagemath-as-a-jupyter-kernel-in-an-existing-jupyter-notebook-or-jupyterlab-installation):
```
user@host ~ $ jupyter kernelspec install --user $(sage -sh -c 'ls -d $SAGE_VENV/share/jupyter/kernels/sagemath') --name sagemath    
Traceback (most recent call last):
  File "/usr/bin/jupyter-kernelspec", line 8, in <module>
    sys.exit(KernelSpecApp.launch_instance())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/traitlets/config/application.py", line 1051, in launch_instance
    app.start()
  File "/usr/lib/python3.11/site-packages/jupyter_client/kernelspecapp.py", line 338, in start
    return self.subapp.start()
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/jupyter_client/kernelspecapp.py", line 151, in start
    self.kernel_spec_manager.install_kernel_spec(
  File "/usr/lib/python3.11/site-packages/jupyter_client/kernelspec.py", line 401, in install_kernel_spec
    shutil.copytree(source_dir, destination)
  File "/usr/lib/python3.11/shutil.py", line 561, in copytree
    return _copytree(entries=entries, src=src, dst=dst, symlinks=symlinks,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/shutil.py", line 515, in _copytree
    raise Error(errors)
shutil.Error: [('/usr/share/jupyter/kernels/sagemath/doc', '/home/user/.local/share/jupyter/kernels/sagemath/doc', "[Errno 2] No such file or directory: '/usr/share/jupyter/kernels/sagemath/doc'")]
```
6. install `sagemath-doc`
7. run the command from 5th point again:
```
[InstallKernelSpec] Removing existing kernelspec in /home/user/.local/share/jupyter/kernels/sagemath
[InstallKernelSpec] Installed kernelspec sagemath in /home/user/local/share/jupyter/kernels/sagemath
```
8. Try running `sage -n jupyter` again: get the same error as in 3rd point
9. run `jupyter notebook` and open a sagemath project. Jupyter is using the sagemath kernel.

### Expected Behavior

1. `sage -i notebook` installs jupyter-notebook and allows for `sage -n jupyter`
2. `jupyter kernelspec install...` allows to run `sage -n jupyter`
3. 3. (suggestion) when no `doc` found suggest installing it. Preferably edit the wiki since its Jupyter dependent.
I mean that I had to look into the error for some time and if I had seen it somewhere it would have saved me the headache.

### Actual Behavior

Explained in steps to reproduce.

`sage -n jupyter` fails to start even though Sagemath is an avalible kernel that operates well in jupyter

### Environment

```markdown
- **OS**: Artix on Linux 6.5.5-artix1-1
- **Sage Version**: 10.1
- **Jupyter-notebook version**: 7.0.4-1
```

### Checklist

- [X] I have searched the existing issues for a bug report that matches the one I want to file, without success.
- [X] I have read the documentation and troubleshoot guide

**Comment by o0nd7ots** [comment]
Also I cannot create new Sagemath files/projects via Jupyter:
![image](https://github.com/sagemath/sage/assets/124466962/933a5594-e1f4-408c-b8a9-408ced53272a)

**Comment by mkoeppe** [comment]
This is a bug in downstream packaging, which is best reported to the maintainers of the package in your Linux distribution.

On our side, Sage does not support Notebook 7 yet. That's #36129

**Comment by o0nd7ots** [comment]
I have reported it. Thanks for the guidance.

Does that mean that using Notebook 7 is discouraged / a hack?

**Comment by o0nd7ots** [comment]
I love this, thank you so much!
