### ISSUE TITLE
sage is taking too many days to compute number of minimum S-boxes in a Block cipher (MILP)

### ISSUE THREAD

**Issue by smitadas95** [sagemath/sage#36448]
Sage is taking a lot of time to compute the minimum number of S-boxes in a block cipher for higher number of rounds using GLPK/coin solver. Please suggest if we can use parallelism using multi threading?

**Comment by mkoeppe** [comment]
try with SCIP as a solver

**Comment by maxale** [comment]
This looks like an issue irrelevant to Sage as it relies on external MILP solvers. Sage cannot do much about the solvers not being able to solve the problem in reasonable time. Luckily there exists a variety of solvers to try, including free SCIP (mentioned above), and free for academic use Gurobi and CPLEX. They may do a better job than GLPK/coin.

As for parallelization, it's up to the solver whether to use it. For example, Gurobi does use multi-threading by itself.
