### ISSUE TITLE
Failure compiling/cythonizing cypari2/handle_error.pyx, cypari2 installs standalone just fine

### ISSUE THREAD

**Issue by ssteinerx** [sagemath/sage#36502]
### Environment

```markdown
- **OS**: Ubuntu 23.04
- **Sage Version**: 10.1
- **Cython Version**: 3.0.4
- **Python Version**: 3.11.5
```

### Steps To Reproduce

pip install --upgrade sagemath-standard

sagemath-standard 9.x installed or not, doesn't change anything.

### Config log

I don't know what config.log this means, I assume from a source build, but this is just a pip install.

### Package logs

Pip's output:

$ pip install --upgrade sagemath-standard
Defaulting to user installation because normal site-packages is not writeable
Collecting sagemath-standard
  Using cached sagemath-standard-10.1.tar.gz (19.2 MB)
  Installing build dependencies ... error
  error: subprocess-exited-with-error
  
  × pip subprocess to install build dependencies did not run successfully.
  │ exit code: 1
  ╰─> [161 lines of output]
      Collecting sage-conf~=10.1
        Using cached sage_conf-10.1-py3-none-any.whl
      Collecting setuptools>=49.6.0
        Using cached setuptools-68.2.2-py3-none-any.whl.metadata (6.3 kB)
      Collecting wheel>=0.36.2
        Using cached wheel-0.41.2-py3-none-any.whl.metadata (2.2 kB)
      Collecting sage-setup~=10.1
        Using cached sage_setup-10.1-py3-none-any.whl
      Collecting cypari2>=2.1.1
        Using cached cypari2-2.1.3.tar.gz (127 kB)
        Preparing metadata (setup.py): started
        Preparing metadata (setup.py): finished with status 'done'
      Collecting cysignals>=1.10.2
        Using cached cysignals-1.11.4-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (4.0 kB)
      Collecting cython<1.0,>=0.29.21
        Using cached Cython-0.29.36-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.manylinux_2_24_x86_64.whl.metadata (3.1 kB)
      Collecting gmpy2>=2.1.0
        Using cached gmpy2-2.1.5-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (1.8 MB)
      Collecting jinja2>=2.11.2
        Using cached Jinja2-3.1.2-py3-none-any.whl (133 kB)
      Collecting jupyter_core>=4.6.3
        Using cached jupyter_core-5.4.0-py3-none-any.whl.metadata (3.4 kB)
      Collecting numpy>=1.19
        Using cached numpy-1.26.1-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (61 kB)
      Collecting pkgconfig>=1.5.1
        Using cached pkgconfig-1.5.5-py3-none-any.whl (6.7 kB)
      Collecting pplpy>=0.8.6
        Using cached pplpy-0.8.9-cp311-cp311-linux_x86_64.whl
      Collecting memory_allocator
        Using cached memory_allocator-0.1.3-cp311-cp311-linux_x86_64.whl
      Collecting MarkupSafe>=2.0 (from jinja2>=2.11.2)
        Using cached MarkupSafe-2.1.3-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (3.0 kB)
      Collecting platformdirs>=2.5 (from jupyter_core>=4.6.3)
        Using cached platformdirs-3.11.0-py3-none-any.whl.metadata (11 kB)
      Collecting traitlets>=5.3 (from jupyter_core>=4.6.3)
        Using cached traitlets-5.11.2-py3-none-any.whl.metadata (10 kB)
      Using cached setuptools-68.2.2-py3-none-any.whl (807 kB)
      Using cached wheel-0.41.2-py3-none-any.whl (64 kB)
      Using cached cysignals-1.11.4-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (1.2 MB)
      Using cached Cython-0.29.36-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.manylinux_2_24_x86_64.whl (1.9 MB)
      Using cached jupyter_core-5.4.0-py3-none-any.whl (28 kB)
      Using cached numpy-1.26.1-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (18.2 MB)
      Using cached MarkupSafe-2.1.3-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (28 kB)
      Using cached platformdirs-3.11.0-py3-none-any.whl (17 kB)
      Using cached traitlets-5.11.2-py3-none-any.whl (83 kB)
      Building wheels for collected packages: cypari2
        Building wheel for cypari2 (setup.py): started
        Building wheel for cypari2 (setup.py): finished with status 'error'
        error: subprocess-exited-with-error
      
        × python setup.py bdist_wheel did not run successfully.
        │ exit code: 1
        ╰─> [101 lines of output]
            /home/ssteiner/.local/lib/python3.11/site-packages/setuptools/__init__.py:80: _DeprecatedInstaller: setuptools.installer and fetch_build_eggs are deprecated.
            !!
      
                    ********************************************************************************
                    Requirements should be satisfied by a PEP 517 installer.
                    If you are using pip, you can try `pip install --use-pep517`.
                    ********************************************************************************
      
            !!
              dist.fetch_build_eggs(dist.setup_requires)
            running bdist_wheel
            running build
            running build_py
            creating build
            creating build/lib.linux-x86_64-cpython-311
            creating build/lib.linux-x86_64-cpython-311/cypari2
            copying cypari2/__init__.py -> build/lib.linux-x86_64-cpython-311/cypari2
            copying cypari2/auto_paridecl.pxd -> build/lib.linux-x86_64-cpython-311/cypari2
            copying cypari2/types.pxd -> build/lib.linux-x86_64-cpython-311/cypari2
            copying cypari2/string_utils.pxd -> build/lib.linux-x86_64-cpython-311/cypari2
            copying cypari2/closure.pxd -> build/lib.linux-x86_64-cpython-311/cypari2
            copying cypari2/stack.pxd -> build/lib.linux-x86_64-cpython-311/cypari2
            copying cypari2/pari_instance.pxd -> build/lib.linux-x86_64-cpython-311/cypari2
            copying cypari2/paridecl.pxd -> build/lib.linux-x86_64-cpython-311/cypari2
            copying cypari2/gen.pxd -> build/lib.linux-x86_64-cpython-311/cypari2
            copying cypari2/paripriv.pxd -> build/lib.linux-x86_64-cpython-311/cypari2
            copying cypari2/convert.pxd -> build/lib.linux-x86_64-cpython-311/cypari2
            copying cypari2/handle_error.pxd -> build/lib.linux-x86_64-cpython-311/cypari2
            copying cypari2/cypari.h -> build/lib.linux-x86_64-cpython-311/cypari2
            copying cypari2/Py_SET_SIZE.h -> build/lib.linux-x86_64-cpython-311/cypari2
            running build_ext
            INFO: Disabling color, you really want to install colorlog.
            Disabling color, you really want to install colorlog.
            Compiling cypari2/closure.pyx because it changed.
            Compiling cypari2/convert.pyx because it changed.
            Compiling cypari2/gen.pyx because it changed.
            Compiling cypari2/handle_error.pyx because it changed.
            Compiling cypari2/pari_instance.pyx because it changed.
            Compiling cypari2/stack.pyx because it changed.
            Compiling cypari2/string_utils.pyx because it changed.
            [1/7] Cythonizing cypari2/closure.pyx
            [2/7] Cythonizing cypari2/convert.pyx
            [3/7] Cythonizing cypari2/gen.pyx
            [4/7] Cythonizing cypari2/handle_error.pyx
      
            Error compiling Cython file:
            ------------------------------------------------------------
            ...
                >>> pari('warning("test")')
                """
                global cb_pari_err_handle
                global cb_pari_err_recover
                cb_pari_err_handle = _pari_err_handle
                cb_pari_err_recover = _pari_err_recover
                                      ^
            ------------------------------------------------------------
      
            cypari2/handle_error.pyx:152:26: Cannot assign type 'void (long) except *' to 'void (*)(long) noexcept'. Exception values are incompatible. Suggest adding 'noexcept' to type 'void (long) except *'.
            Traceback (most recent call last):
              File "<string>", line 2, in <module>
              File "<pip-setuptools-caller>", line 34, in <module>
              File "/tmp/pip-install-tubs0jq5/cypari2_bc5ae0c5eb954ea494c2ab64c3132d3b/setup.py", line 66, in <module>
                setup(
              File "/home/ssteiner/.local/lib/python3.11/site-packages/setuptools/__init__.py", line 103, in setup
                return distutils.core.setup(**attrs)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
              File "/home/ssteiner/.local/lib/python3.11/site-packages/setuptools/_distutils/core.py", line 185, in setup
                return run_commands(dist)
                       ^^^^^^^^^^^^^^^^^^
              File "/home/ssteiner/.local/lib/python3.11/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
                dist.run_commands()
              File "/home/ssteiner/.local/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
                self.run_command(cmd)
              File "/home/ssteiner/.local/lib/python3.11/site-packages/setuptools/dist.py", line 989, in run_command
                super().run_command(command)
              File "/home/ssteiner/.local/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
                cmd_obj.run()
              File "/home/ssteiner/.local/lib/python3.11/site-packages/wheel/bdist_wheel.py", line 364, in run
                self.run_command("build")
              File "/home/ssteiner/.local/lib/python3.11/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
                self.distribution.run_command(command)
              File "/home/ssteiner/.local/lib/python3.11/site-packages/setuptools/dist.py", line 989, in run_command
                super().run_command(command)
              File "/home/ssteiner/.local/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
                cmd_obj.run()
              File "/home/ssteiner/.local/lib/python3.11/site-packages/setuptools/_distutils/command/build.py", line 131, in run
                self.run_command(cmd_name)
              File "/home/ssteiner/.local/lib/python3.11/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
                self.distribution.run_command(command)
              File "/home/ssteiner/.local/lib/python3.11/site-packages/setuptools/dist.py", line 989, in run_command
                super().run_command(command)
              File "/home/ssteiner/.local/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
                cmd_obj.run()
              File "/tmp/pip-install-tubs0jq5/cypari2_bc5ae0c5eb954ea494c2ab64c3132d3b/setup.py", line 46, in run
                self.distribution.ext_modules[:] = cythonize(
                                                   ^^^^^^^^^^
              File "/home/ssteiner/.local/lib/python3.11/site-packages/Cython/Build/Dependencies.py", line 1154, in cythonize
                cythonize_one(*args)
              File "/home/ssteiner/.local/lib/python3.11/site-packages/Cython/Build/Dependencies.py", line 1321, in cythonize_one
                raise CompileError(None, pyx_file)
            Cython.Compiler.Errors.CompileError: cypari2/handle_error.pyx
            [end of output]
      
        note: This error originates from a subprocess, and is likely not a problem with pip.
        ERROR: Failed building wheel for cypari2
        Running setup.py clean for cypari2
      Failed to build cypari2
      ERROR: Could not build wheels for cypari2, which is required to install pyproject.toml-based projects
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× pip subprocess to install build dependencies did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

### Additional Information

Sorry if this is not supposed to be here.  It's not a bug, it's not a failure building the whole magilla from source, it's not a feature request,  it just won't install with regular pip due to a compilation step that the sagemath installation attempts that the cypari2 package does not.  cypari2 installs just fine but it doesn't try to cythonize itself as far as I can tell; sagemath does and it won't.

### Checklist

- [X] I have searched the existing issues for a bug report that matches the one I want to file, without success.
- [X] I have read the documentation and troubleshoot guide

**Comment by mkoeppe** [comment]
outdated
