### ISSUE TITLE
New in 10.2.beta8 : no `view` in console / emacs

### ISSUE THREAD

**Issue by EmmanuelCharpentier** [sagemath/sage#36526]
### Steps To Reproduce

On Debian testing (up to date) running on core i7 + 16 GB RAM, using Sagemath 10.2.beta8 compiled from source,

```
sage: var("a,b")
(a, b)
sage: foo=1/(1+e^-(a*x+b))
sage: view(foo.diff(x,2).factor())
```

### Expected Behavior

the typeset expression in the PDF viewer's window.

### Actual Behavior

gives no error whatsoever in the Sage console, but thePDF viewer (evince in my case) displays 

```
Impossible d’ouvrir le document « file:///tmp/tmpqp2yuobe/sage.pdf ».
Erreur lors de l’ouverture du fichier /tmp/tmpqp2yuobe/sage.pdf : Aucun fichier ou dossier de ce type
```

(*i. e.* the PDF file does not exist).

### Additional Information

Already reported [here](https://groups.google.com/g/sage-release/c/VLopiVZYijE/m/kyymsq2eAwAJ).

Volker Braun's message announcing the beta contains : 

```
4a60001a052 gh-36436: src/sage/misc/latex.py: replace tmp_dir()
```

but I have trouble to find this issue in Github.

FWIW : the expression is correctly typeset and displayed in a Jupyter notebook (with `show`) and in emacs (after enabling typeset output).

### Environment

```markdown
- **OS**: Debian testing (up to date)
- **Sage Version**: 10.2.beta8
```

### Checklist

- [X] I have searched the existing issues for a bug report that matches the one I want to file, without success.
- [X] I have read the documentation and troubleshoot guide

**Comment by EmmanuelCharpentier** [comment]
Priority set to `major` (serious pain in console users' arses...).

**Comment by dimpase** [comment]
the change was here: https://github.com/sagemath/sage/pull/36436
(Volker's gh-X usually refers to the PR X rather than to issue X)

**Comment by mkoeppe** [comment]
What's the situation here?
