### ISSUE TITLE
.longest_path(algorithm='backtrack') gives incorrect result

### ISSUE THREAD

**Issue by maxale** [sagemath/sage#36530]
### Steps To Reproduce

The following code returns produces a path on 26 vertices:

```
G = DiGraph( ((x,y) for x,y in Tuples(range(10,100),2) if x!=y and y%sum(ZZ(x).digits())==0), format='list_of_edges' )
with seed(0):
    L = G.longest_path(algorithm='backtrack')
print(L.order())
```

while `G.longest_path(solver='gurobi')` produces a path on 64 vertices .

Also, `G.longest_path(algorithm='backtrack')` ignores the starting vertex when its given. For example, using `L = G.longest_path(94, algorithm='backtrack')` still produces a path starting at vertex 47.

### Expected Behavior

Using `algorithm='backtrack'` should produce a correct longest path, and obey other given parameters (such as a starting vertex).

### Actual Behavior

See above.

### Environment

```markdown
- **OS**: Ubuntu 22.04.3 LTS
- **Sage Version**: 10.2.beta5
```

### Checklist

- [X] I have searched the existing issues for a bug report that matches the one I want to file, without success.
- [X] I have read the documentation and troubleshoot guide

**Comment by dcoudert** [comment]
As documented, the `backtrack` algorithm is a randomized heuristic. So we cannot expect an optimal solution.
```
          * While the MILP formulation returns an exact answer, the backtrack
            algorithm is a randomized heuristic.
```
I agree that the backtrack algorithm should not ignore the starting / ending vertices, but I don't know how to change this heuristic to do that. One should propose another method.

**Comment by dcoudert** [comment]
This is related to https://ask.sagemath.org/question/69746/some-strange-behaviors-of-longest_path/

**Comment by maxale** [comment]
A couple of comments:

- the term "backtrack" is confusing here since typically [backtracking](https://en.wikipedia.org/wiki/Backtracking) refers to a **deterministic** algorithm that is guaranteed to find all solutions. It may be worth to rename this to "heuristic" or alike to avoid confusion if there is no such guarantee.
- if there is no easy way to fix the heuristic to support some parameters, this needs to be described in the documentation and `.longest_path()` should raise an error if unsupported combination of parameters is given to it.
