### ISSUE TITLE
substitution fails in the fraction field of an InfinitePolynomialRing

### ISSUE THREAD

**Issue by mantepse** [sagemath/sage#36576]
### Steps To Reproduce

```
sage: P.<a> = InfinitePolynomialRing(QQ)
sage: c = a[0]/(a[0] + 1)
sage: c
a_0/(a_0 + 1)
sage: c.subs({a[0]: 1})
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Cell In [90], line 1
----> 1 c.subs({a[Integer(0)]: Integer(1)})

File ~/sage-trac/src/sage/structure/element.pyx:822, in sage.structure.element.Element.subs()
    820 for i in range(ngens):
    821     gen = parent.gen(i)
--> 822     if str(gen) in kwds:
    823         variables.append(kwds[str(gen)])
    824     elif in_dict and gen in in_dict:

File ~/sage-trac/src/sage/structure/sage_object.pyx:221, in sage.structure.sage_object.SageObject.__repr__()
    219     except AttributeError:
    220         return super().__repr__()
--> 221     return reprfunc()
    222 
    223 def _ascii_art_(self):

File ~/sage-trac/src/sage/rings/fraction_field_element.pyx:478, in sage.rings.fraction_field_element.FractionFieldElement._repr_()
    476     '1/x'
    477 """
--> 478 if self.is_zero():
    479     return "0"
    480 s = "%s" % self._numerator

File ~/sage-trac/src/sage/rings/fraction_field_element.pyx:1017, in sage.rings.fraction_field_element.FractionFieldElement.is_zero()
   1015         True
   1016     """
-> 1017     return self._numerator.is_zero()
   1018 
   1019 def is_one(self):

AttributeError: 'InfinitePolynomialGen' object has no attribute 'is_zero'
```

### Expected Behavior

It should return the result of the substitution.

### Actual Behavior

A cryptic error is raised.

### Additional Information

The problem is that the fraction field inherits `subs` from `Element`.  This tries to access the `i`-th generator of the ring.  However, in the `InfinitePolynomialRing`, the `i`-the generator actually corresponds to the `i`-th **family** of generators.  For example:
```
sage: P.gen(0)
a_*
```
Note that, for example, symmetric functions do not have `gens` at all, so `Element.subs` does nothing and this bug does not surface there.

### Environment

```markdown
irrelevant.
```

### Checklist

- [X] I have searched the existing issues for a bug report that matches the one I want to file, without success.
- [X] I have read the documentation and troubleshoot guide

**Comment by maxale** [comment]
While the issue is not fixed, a possible workaround is to make substitution separately in the numerator and in the denominator of `c`:

`c.numerator().subs({a[0]: 1}) / c.denominator().subs({a[0]: 1})`
