### ISSUE TITLE
Upload coverage fails/takes very long since beta.6

### ISSUE THREAD

**Issue by tobiasdiez** [sagemath/sage#36620]
### Steps To Reproduce

https://github.com/sagemath/sage/actions/runs/6712342128/job/18241914417

### Expected Behavior

Be quick (10sec)

### Actual Behavior

Takes about 1.5h

### Additional Information

Seems to be the case since beta 6. In particular, the PR https://github.com/sagemath/sage/pull/36367 seems to be the earliest case where the upload takes so long (which I don't quite understand, maybe an issue with a symlink?!). Alternatively, it may have been https://github.com/sagemath/sage/pull/36348 (the only other PR that touched the build & test workflow in that release cycle).

### Environment

```markdown
CI
```

### Checklist

- [X] I have searched the existing issues for a bug report that matches the one I want to file, without success.
- [X] I have read the documentation and troubleshoot guide

**Comment by mkoeppe** [comment]
Yes, this is quite annoying. Looking at the timestamps in the log: 
```
[2023-11-01T01:06:08.891Z] ['info'] Searching for coverage files...
[2023-11-01T02:44:16.875Z] ['info'] => Found 1 possible coverage files:
```
... it spent over 90minutes in this step. I'd guess something is misconfigured in this Action.
