### ISSUE TITLE
Possibility of extending `has_homomorphism_to` to support returning all homomorphisms?

### ISSUE THREAD

**Issue by guojing0** [sagemath/sage#36717]
As continuation of PR [#36504](https://github.com/sagemath/sage/pull/36504), I am working on some functionalities related to counting (graph) homomorphisms. Currently, Sage already has `has_homomorphism_to` function, but it only returns one homomorphism even if multiple exist.

It seems that this function is implemented with some LP solver. Would it be possible to extend it to support returning all homomorphisms?

**Edit**: This one will be addressed in a new branch.

**Comment by dcoudert** [comment]
A solution (certainly not the most efficient) is to add a `while True` loop to repeat solve + extract the solution + add a constraint to prevent finding again the same solution. You end the loop when you have no more solutions or the size of the solution increases (case `core == True`).

**Comment by guojing0** [comment]
I searched relevant keywords but couldn't find anything helpful. For hom's from G to H, when G is much smaller than H, other than this brute-force approach, do you know any other algorithms that could potentially be useful, if also relatively easy to implement?

**Comment by dcoudert** [comment]
I don't know the existing results for the enumeration or for counting graph homomorphisms. I suggest you to do the literature review first.

**Comment by guojing0** [comment]
> I don't know the existing results for the enumeration or for counting graph homomorphisms. I suggest you to do the literature review first.

Will do.

I am actually implementing counting hom's, and the algorithm requires these kinds of enumeration

**Comment by guojing0** [comment]
@dcoudert If we were to have a `homomorphisms.py`, should we move `has_homomorphism_to` function from `graphs.py` to the new file, since it's related to a homomorphism...

**Comment by dcoudert** [comment]
yes, but this can be done in a second time.

**Comment by dcoudert** [comment]
Yes, you can create a class.

As I already told you, if you create a new file, please name it `homomorphisms.py`. Names of files, methods and class must be clear for all users.

**Comment by guojing0** [comment]
> Yes, you can create a class.
> 
> 
> 
> As I already told you, if you create a new file, please name it `homomorphisms.py`. Names of files, methods and class must be clear for all users.

Yes I do intend to, this is not the final product yet. This separation is primarily for development purpose.
