### ISSUE TITLE
OS X: system Pari is rejected because of unknown shell command

### ISSUE THREAD

**Issue by jhpalmieri** [sagemath/sage#36729]
### Steps To Reproduce

`timeout` is not a valid shell command in OS X, so the test
```
        AC_MSG_CHECKING([whether factor() bug 2469 of pari 2.15.3 is fixed])
        result=`echo "f=factor(2^2203-1); print(\"ok\")" | timeout 1 $GP -qf`
```
introduced in #35302 fails even with a recent version of `pari` installed via `homebrew`.

### Expected Behavior

Sage should be able to use `homebrew`'s version of `pari`.

### Actual Behavior

`config.log` says
```
configure:24946: checking whether factor() bug 2469 of pari 2.15.3 is fixed
configure:24953: result: no; cannot use system pari/GP with known bug
...
configure:25276: no suitable system package found for SPKG pari
```
If I remove `timeout` from that line, then the system `pari is used, Sage builds correctly, and all tests pass. Also the shell command
```
echo "f=factor(2^2203-1); print(\"ok\")" | gp -qf 
```
executes without error and finishes very quickly.

### Environment

```markdown
- **OS**: OS X 14.1
- **Sage Version**: 10.2.rc3
```

### Checklist

- [X] I have searched the existing issues for a bug report that matches the one I want to file, without success.
- [X] I have read the documentation and troubleshoot guide

**Comment by jhpalmieri** [comment]
> ```
> brew install coreutils
> ```
> 
> will provide `timeout` command. So we'd add `coreutils` to the list of Homebrew packages to install

#36732 should fix the problem, so we shouldn't need to do this.

**Comment by mkoeppe** [comment]
Also the conda CI on macOS is affected by this.

**Comment by dimpase** [comment]
> Also the conda CI on macOS is affected by this.

I'm sure conda also has an analog of `coreutils` to be added to requirements
