### ISSUE TITLE
Fast cardinality method for IntegerVectorsModPermutationGroup

### ISSUE THREAD

**Issue by jukkakohonen** [sagemath/sage#36787]
### Problem Description

`IntegerVectorsModPermutationGroup` has no implementation of `cardinality`, so it defaults to iterating over the whole set and tallying. This is obviously slow for large sets.

For example, with vectors of length 10, summing to 20, and with the permutation group where the first two elements can be swapped, it takes more than two minutes to compute the cardinality.

### Proposed Solution

The cardinality should be calculated using the cycle index theorem (see e.g. [Peter Cameron's blog post](https://cameroncounts.wordpress.com/2018/03/16/a-counting-problem/) for an explanation).

An example code is here. This should be more or less a ready plug-in for the cardinality method.

```
def fast_cardinality(self):
    G = self._permgroup
    k = G.degree()              # Number of boxes
    d = self._sum               # Number of balls
    m = self._max_part          # Maximum balls in one box, -1 for no limit
    if m == -1:
        m = d
        
    if k==0:
        # Special case, no boxes.
        if d==0:
            return 1
        else:
            return 0

    # Power series with enough precision
    R.<x> = PowerSeriesRing(QQ, default_prec = d+1)

    # The function-counting series, for maximum part size m, is
    # (1-t^(m+1)) / (1-t) = 1+t+...+t^m.
    #
    # For the figure-counting series, we substitute x^cyclen for t.
    
    Z = G.cycle_index()
    funcount = sum(coeff * prod((1-x^((m+1)*cyclen)) / (1-x^cyclen)
                                for cyclen in cyctype)
                   for (cyctype, coeff) in Z)

    # Extract the x^d coefficient.
    dic = funcount.dict()
    if d in dic:
        return Integer(dic[d])  # Convert from Rational to Integer
    else:
        return 0
```

### Alternatives Considered

We could leave it as is, and rely on users to perform the cycle index calculations.

### Additional Information

Here is a speed comparison.

Permutation group acting on 10 elements, and only containing two permutations, the trivial one and the swap `(1,2)`. Count the vectors that sum to 20.

The times are about 0.1 seconds versus 161 seconds.

```
sage: G=PermutationGroup([(1,2)],domain=range(10)); V=IntegerVectorsModPermutationGroup(G,20)                                             
sage: t0=time(); fast_cardinality(V), time()-t0                                                                                           
(5911763, 0.09431600570678711)
sage: t0=time(); V.cardinality(), time()-t0                                                                                               
(5911763, 160.82350969314575)
sage: version()                                                                                                                           
'SageMath version 9.0, Release Date: 2020-01-01'
```

### Is there an existing issue for this?

- [X] I have searched the existing issues for a bug report that matches the one I want to file, without success.

**Comment by mantepse** [comment]
Brilliant!

**Comment by mantepse** [comment]
Here is a (rather thorough) summary: https://doc.sagemath.org/html/en/developer/coding_basics.html#writing-testable-examples

The actual doctest should not take long on the average computer, the absolute maximum is a second.  Since you are mostly testing a theorem, I'd suggest to include the corner cases (i.e., group of order 1) and maybe a few more specific groups, and that `max_part` and `sum` are handled correctly.

I don't think that it is necessary to do 40000 comparisons.

If you really want to do systematic tests on small permutation groups, you can compare `len(list(S)) == S.cardinality()`.

**Comment by jukkakohonen** [comment]
In fact the above example code was not complete: it did not handle the case where max_part is given but sum is not. The code in the pull request should handle that case too.

**Comment by jukkakohonen** [comment]
Incidentally, this is now faster, for counting integer partitions of given maximum length, than `Partitions.cardinality` which resorts to iterating.

```
sage: P = Partitions(80, max_length=10)
sage: %time P.cardinality()
CPU times: user 1min 45s, sys: 7.87 ms, total: 1min 45s
Wall time: 1min 45s
1314972

sage: V = IntegerVectorsModPermutationGroup(SymmetricGroup(10), 80)
sage: %time V.cardinality()
CPU times: user 22.1 ms, sys: 4 µs, total: 22.1 ms
Wall time: 21.7 ms
1314972
```

**Comment by mantepse** [comment]
> Incidentally, this is now faster, for counting integer partitions of given maximum length, than `Partitions.cardinality` which resorts to iterating.
> 
> ```
> sage: P = Partitions(80, max_length=10)
> sage: %time P.cardinality()
> CPU times: user 1min 45s, sys: 7.87 ms, total: 1min 45s
> Wall time: 1min 45s
> 1314972

Indeed, `Partitions(n, max_length=k)` should probably have its own class.  Currently, it is `Partitions_with_constraints`, although we have, for example, `Partitions_parts_in`.
