### ISSUE TITLE
math formulas in published 10.2 documentation are broken

### ISSUE THREAD

**Issue by haraldschilly** [sagemath/sage#36824]
### Steps To Reproduce

build the html files via the `doc-html` build target

### Expected Behavior

the URLs of all assets in all `*html` pages must be relative, not absolute.

### Actual Behavior

The `doc-html` build target produces the `*.html` artifacts. They contain an absolute paths:

```
~/sage-git/local/share/doc/sage/html$ grep -R /user/sage-git/local/share/mathjax/mathjax/tex-chtml.js | head
ru/tutorial/interfaces.html:    <script defer="defer" src="/home/user/sage-git/local/share/mathjax/mathjax/tex-chtml.js"></script>
ru/tutorial/interactive_shell.html:    <script defer="defer" src="/home/user/sage-git/local/share/mathjax/mathjax/tex-chtml.js"></script>
ru/tutorial/tour_help.html:    <script defer="defer" src="/home/user/sage-git/local/share/mathjax/mathjax/tex-chtml.js"></script>
ru/tutorial/tour_linalg.html:    <script defer="defer" src="/home/user/sage-git/local/share/mathjax/mathjax/tex-chtml.js"></script>
ru/tutorial/tour_polynomial.html:    <script defer="defer" src="/home/user/sage-git/local/share/mathjax/mathjax/tex-chtml.js"></script>
ru/tutorial/tour_advanced.html:    <script defer="defer" src="/home/user/sage-git/local/share/mathjax/mathjax/tex-chtml.js"></script>
ru/tutorial/tour_functions.html:    <script defer="defer" src="/home/user/sage-git/local/share/mathjax/mathjax/tex-chtml.js"></script>
[...]
```

### Additional Information

The browser can't load the asset. This is the error.

```
GET https://doc.sagemath.org/home/user/sage-git/local/share/mathjax/mathjax/tex-chtml.js net::ERR_ABORTED 404 (Not Found)
```
The `"/home/user/sage-git/local/"` shouldn't be there.

In the vicinity of this in the generated html pages at the bottom, there are other assets loaded like that:

```
    <script src="_static/scripts/furo.js"></script>
    <script src="_static/clipboard.min.js"></script>
    <script src="_static/copybutton.js"></script>
```

---

P.S.: I had to click on the "I have read the documentation and troubleshoot guide" checkbox to submit this issue, although I did NOT read it. Please let me know if there is a fix for this anywhere in it.

### Environment

```markdown
- **OS**: Linux
- **Sage Version**: 10.2
```

### Checklist

- [X] I have searched the existing issues for a bug report that matches the one I want to file, without success.
- [X] I have read the documentation and troubleshoot guide

**Comment by haraldschilly** [comment]
`git-grepping` around the problem is caused by ab1649ca36c … feels like the case of publishing the documentation wasn't considered at all.

**Comment by dimpase** [comment]
This is strange, as we now have a CI which builds and publishes (temp) docs, see e.g.
https://deploy-preview-36771--sagemath-tobias.netlify.app/html/en/ from 
https://github.com/sagemath/sage/pull/36771

@orlitzky @tobiasdiez

**Comment by dimpase** [comment]
@haraldschilly - would installing mathjax locally on the server solve this?

**Comment by dimpase** [comment]
> On that page, the same asset is loaded from an external site:

what's `that` here?

**Comment by haraldschilly** [comment]
@dimpase No, I just run `make doc-html && make doc-pdf` and that's it. Thanks for pointing this out.

**Comment by haraldschilly** [comment]
> > On that page, the same asset is loaded from an external site:
> 
> what's `that` here?

https://deploy-preview-36771--sagemath-tobias.netlify.app/html/en/

**Comment by dimpase** [comment]
> @dimpase No, I just run `make doc-html && make doc-pdf` and that's it. Thanks for pointing this out.
I understood your `that` wrongly, sorry. Anyway, OK, so I suppose that if you clean the docs and rerun this with `SAGE_USE_CDNS=yes` you'll get it fixed.

**Comment by tobiasdiez** [comment]
You can find the workflow that currently publishes the dev-preview of the docs at https://github.com/sagemath/sage/blob/develop/.github/workflows/doc-build.yml.

Thanks for your continued work on the docs. As it is hard to test your post-processing, would it be possible if you could add them here in the main repo? Maybe we can even set-up an automatic publishing to production on releases, fully automating the process.
