### ISSUE TITLE
wrong canonical height depending on the model

### ISSUE THREAD

**Issue by AurelPage** [sagemath/sage#36834]
### Steps To Reproduce

`K.<a> = NumberField(x^2 - 84131656042917)`
`eqn = [0, 0, 0, -5482707841/48, -244634179112639/864]`
`E = EllipticCurve(K,eqn)`
`P = E(349189/12, 1/2*a)`
`P.height()`
`(2*P).height()/P.height()`
`n=2^7; (n*P).height()/(n^2)`

### Expected Behavior

The correct value is 10.4560438181991, and the ratio h(2P)/h(P) should be 4.

### Actual Behavior

The computed value is 12.9409504679871, and the computed ratio is 3.33904914795933.

### Additional Information

The height is correctly computed with another model of the same curve (minimal model over Q, base-changed to K):
`ME = EllipticCurve(K,[1, 0, 0, -114223080, -283150929600])`
`MP = ME(29099, 1/2*a - 29099/2)`
`MP.height()`
`(2*MP).height()/(MP.height())`

### Environment

```markdown
- **OS**: Ubuntu 22.04.3 LTS
- **Sage Version**: SageMath 10.2.beta6
```

### Checklist

- [X] I have searched the existing issues for a bug report that matches the one I want to file, without success.
- [X] I have read the documentation and troubleshoot guide

**Comment by AurelPage** [comment]
I don't know which algorithm is used in this implementation, but it most likely does the computation via local heights. The theory and explicit formulas can be found in Silverman's Advanced topics in the arithmetic of elliptic curves, chapter VI. Note that on this example, Magma refuses to do the computation (non-integral model), and Pari was raising an error after trying to invert 0 mod 2. In Pari, this has been fixed; one of the bugs was an incorrect formula in a change of coordinates that was making the model integral.

**Comment by fchapoton** [comment]
This returns the sum of two terms. The second one alone looks like the correct value.
```
ipdb> p self.non_archimedean_local_height(prec=precision)
2.48490664978800
ipdb> p self.archimedean_local_height(prec=precision)
10.4560438181991
```

Should the first contribution be zero ? @JohnCremona  ?

**Comment by JohnCremona** [comment]
It's my code, hence my fault, and I will fix it - but not right away as I am travelling (at ANTS) until the middle of next week.

Obviously the code needs to take into account the non-minimality and/or non-integrality and it seems not to be doing so properly.

**Comment by JohnCremona** [comment]
OK, I am now building an updated version of Sage and will fix this when that is done.

**Comment by JohnCremona** [comment]
Note 1: it is enough to transfer to an integral model, which is cheap; this gives the correct asnwer.  It is not necessary to go to a global minimal (or semiminimal) model, which is a good thing as that involves computing the class group of the field, which is slow (even with proof=False).  So one fix is to ensure that the model is integral and mvoe to an integral model if not.  I will either do that or see if the formula can take non-integrality into account.

**Comment by JohnCremona** [comment]
I have a simple fix which I will make into a PR with a test tomorrow.  It was just a matter of changing ``v.divides(c)`` into ``c.valuation(v)!=0`` in a couple of places.
