### ISSUE TITLE
Symbolic power of a nilpotent matrix is zero

### ISSUE THREAD

**Issue by phul-ste** [sagemath/sage#36838]
### Steps To Reproduce

If we run 
```
Z=matrix([[0,1],[0,0]])
n=var('n')
Zn=Z^n;Zn
```
we get the null matrix.

### Expected Behavior

I would have expected a result like
`matrix([0^n,n*0^(n-1)],[0,0^n]])
`
to see that the matrix is not automatically zero for small n.

### Actual Behavior

The actual result is 
`matrix([[0,0],[0,0]])`

### Additional Information

I highly suspect that it is caused by the `.simplify_full()` method which turns `0^n` into `0`.

### Environment

```markdown
- **OS**: Ubuntu 20.04
- **Sage Version**: 9.0
- Jupyter Notebook
```

### Checklist

- [X] I have searched the existing issues for a bug report that matches the one I want to file, without success.
- [X] I have read the documentation and troubleshoot guide

**Comment by RuchitJagodara** [comment]
I didn't get it why do you want the result in that format because after all it is zero only, right ? @phul-ste

**Comment by phul-ste** [comment]
@RuchitJagodara 
It is not zero for small values of n.
If the 0^n=0 only fails for $n=0$, the failure is more significant for nilpotent matrices.

In fact, the problem arose with students in a practical class given by a colleague of mine. There was an exact formula for some matrices (e.g.  `matrix([1,1],[0,1]])` ) while for some nilpotent matrix, the brutal limit case result was given.
(and this is part of some trust issues on sage's results from the aforementioned colleague that I had recently convinced to try an opensource software)

**Comment by RuchitJagodara** [comment]
Hmm... Got it. Thank you for the clarification, @phul-ste. I will try to solve this as soon as possible. (This type of bug/error is very rare because as soon as someone reports it, it gets resolved. It's good to see that people are trying out open-source softwares.)

**Comment by RuchitJagodara** [comment]
I have corrected the code and now it is working fine. Please, review it, @phul-ste.

**Comment by phul-ste** [comment]
@RuchitJagodara I wrote a modification suggestion in order to use kronecker_delta instead of powers of 0.
(Hoping I am doing it right, I have never developed neither reviewed anything before)

Apart from that, everything seemed ok to me,
Thank you

**Comment by RuchitJagodara** [comment]
@phul-ste, can you please review it again? I have made some changes as per your suggestions.
