### ISSUE TITLE
`.ci/create-changes-html.sh` fails when an HTML file is removed

### ISSUE THREAD

**Issue by mkoeppe** [sagemath/sage#36887]
### Steps To Reproduce

https://github.com/sagemath/sage/actions/runs/7217053087/job/19664244861?pr=36885#step:11:156

### Expected Behavior

diff created 

### Actual Behavior

```
+ PATH=/sage/venv/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin .ci/create-changes-html.sh 4725a0315a962bee6a612f04009dcb66c4e55b09 /sage/local/share/doc/sage/html
Traceback (most recent call last):
  File "<stdin>", line 12, in <module>
FileNotFoundError: [Errno 2] No such file or directory: '/sage/local/share/doc/sage/html/en/reference/spkg/deprecation.html'
cat: diff.html: No such file or directory
rm: cannot remove 'diff.html': No such file or directory
```

### Environment

```markdown
CI
```

### Checklist

- [X] I have searched the existing issues for a bug report that matches the one I want to file, without success.
- [X] I have read the documentation and troubleshoot guide

**Comment by kwankyu** [comment]
This seems the same symptom fixed by https://github.com/sagemath/sage/pull/36871

**Comment by kwankyu** [comment]
Ah, okay. I will investigate.

**Comment by kwankyu** [comment]
Could you test the PR with the failing case?
