### ISSUE TITLE
Doc preview upload stopped working

### ISSUE THREAD

**Issue by kwankyu** [sagemath/sage#36973]
### Steps To Reproduce

Visit here for example and open the step "Deploy to Netlify":

https://github.com/sagemath/sage/actions/runs/7333910646/job/19969968370#:~:text=Error%3A%20Site%20not%20found.%20Please%20rerun%20%22netlify%20link%22

```
Run netlify/actions/cli@master
...
"/home/runner/work/sage/sage":"/github/workspace" fc7ce0:599d07be1b984f97889431b2402d54b8 deploy --dir=docs/docs/docs ${NETLIFY_PRODUCTION:+"--prod"} --message ${NETLIFY_MESSAGE} --alias ${NETLIFY_ALIAS}
 ›   Error: Site not found. Please rerun "netlify link"
```

### Expected Behavior

Doc preview should be published to the deployment site.

### Actual Behavior

Doc preview links open a false site.

### Additional Information

@tobiasdiez 

### Environment

```markdown
- **OS**:
- **Sage Version**:
```

### Checklist

- [X] I have searched the existing issues for a bug report that matches the one I want to file, without success.
- [X] I have read the documentation and troubleshoot guide

**Comment by mkoeppe** [comment]
as noted also in https://github.com/sagemath/sage/issues/34874#issuecomment-1868628209
