### ISSUE TITLE
ipython 8.19.0 breaks sagemath, making it unusable

### ISSUE THREAD

**Issue by tornaria** [sagemath/sage#36975]
See: https://github.com/ipython/ipython/pull/14223#issuecomment-1869776898

My workaround in https://github.com/void-linux/void-packages/pull/47913 is to patch out the buggy feature. Cf https://github.com/void-linux/void-packages/blob/master/srcpkgs/python3-ipython/patches/fix-sagemath-prompt.patch.

Other than this, everything seems ok with ipython 8.19 (at least all doctests pass).

**Comment by mkoeppe** [comment]
They also dropped Python 3.9 IIRC, so we won't merge it soon

**Comment by mkoeppe** [comment]
But we should add an install-requires upper bound

**Comment by tornaria** [comment]
> But we should add an install-requires upper bound

Upstream is aware of the issue and will fix it in an upcoming 8.19.1. Better to only skip 8.19.0. See: https://github.com/ipython/ipython/pull/14223#issuecomment-1870467577

**Comment by tornaria** [comment]
@antonio-rojas it might be the case that sagemath is currently broken on arch (?)

**Comment by done-with-fish** [comment]
> @antonio-rojas it might be the case that sagemath is currently broken on arch (?)

Yes, sagemath is currently broken on arch (which is why I'm lurking here!).

**Comment by tornaria** [comment]
> > @antonio-rojas it might be the case that sagemath is currently broken on arch (?)
> 
> Yes, sagemath is currently broken on arch (which is why I'm lurking here!).

The patch I linked above is safe and works fine (it's what we are shipping on void linux). Or else wait a few days for upstream to release 8.19.1 and arch to ship it  (or downgrade ipython to 8.18 if that's possible).

**Comment by Carreau** [comment]
8.20 published with a fix and 8.19 yanked. Apologies again for the breakage.

**Comment by amca01** [comment]
I've just discovered this when experimenting with Sage in the console - using a fairly recently upgraded (4 days ago) Arch linux.  Thanks for the fix - I've just seen that ipython is indeed upgradeable via pacman, so I'll do another system upgrade.

**Comment by mkoeppe** [comment]
As 8.19.0 has been yanked - https://pypi.org/project/ipython/#history - I think we can close this
