### ISSUE TITLE
`vertex_separation()` returns orderings that are not optimal

### ISSUE THREAD

**Issue by ericbrandwein** [sagemath/sage#36996]
### Steps To Reproduce

There are some graphs for which the function `sage.graphs.graph_decompositions.vertex_separation.vertex_separation` does not return the optimal ordering, although it seems to return the correct cost. As an example, the following test fails:

```python
from sage.graphs.graph import Graph
from sage.graphs.graph_generators import graphs
from sage.graphs.graph_decompositions.vertex_separation import vertex_separation

def test_vertex_separation(self):
    graph = Graph({
        1: [4],
        4: [0],
        0: [3],
        2: [3],
        3: []
    })
    cost, layout = vertex_separation(graph)
    for index in range(len(layout)):
        vertices_before = layout[:index]
        vertices_after = layout[index:]
        active_vertices_before = filter(lambda v: has_neighbor_in(graph, v, vertices_after), vertices_before)
        assert len(list(active_vertices_before)) <= cost

def has_neighbor_in(graph, vertex, vertices):
    return any(v in graph.neighbors(vertex) for v in vertices)
```

### Expected Behavior

`vertex_separation()` should return an optimal ordering, and the cost should be consistent with the ordering.

### Actual Behavior

`vertex_separation()` returns orderings that have greater cost than the one returned.

### Additional Information

The definition in Wikipedia: https://en.wikipedia.org/wiki/Pathwidth#Vertex_separation_number

### Environment

```markdown
- **OS**: Manjaro Linux 23.1.1
- **Sage Version**: 10.2
```

### Checklist

- [X] I have searched the existing issues for a bug report that matches the one I want to file, without success.
- [X] I have read the documentation and troubleshoot guide

**Comment by ericbrandwein** [comment]
To add to this, I tested with all possible algorithms (`'BAB'`, `'exponential'`, and `'MILP'`) and it gives the same answer.

**Comment by dcoudert** [comment]
The method counts the number of neighbors on the right of the vertices in the prefix. This is strictly equivalent to counting the number of neighbors in the prefix (left part) of the vertices in the suffix (right part). In other words, the method return the reverse order of what you expect. Honestly, I find it more natural to count the number of neighbors in the suffix of the vertices in prefix and I think it easier to implement this way.

**Comment by ericbrandwein** [comment]
Great, thanks for the response! Maybe this clarification could be added to the docs?https://doc.sagemath.org/html/en/reference/graphs/sage/graphs/graph_decompositions/vertex_separation.html#sage.graphs.graph_decompositions.vertex_separation.vertex_separation

**Comment by ericbrandwein** [comment]
Oh, I see it's already defined there: https://doc.sagemath.org/html/en/reference/graphs/sage/graphs/graph_decompositions/vertex_separation.html#vertex-separation. Closing, sorry!
