### ISSUE TITLE
configure: mathjax quoting error on Gentoo

### ISSUE THREAD

**Issue by orlitzky** [sagemath/sage#37019]
### Steps To Reproduce

Run `./configure` on Gentoo

### Expected Behavior

The mathjax-3.x package is either used or suggested to you

### Actual Behavior

```
checking for the package system in use... gentoo
./configure: 1: eval: cannot create =dev-libs/mathjax-3: Directory nonexistent
configure:
```

### Additional Information

The quoting that made this work was removed in a0246a5aff6d13a48a46cbe4e36ee9bb41c9c941 (hi @mkoeppe), but maybe there's some other way to keep the shell from thinking `>` is redirecting stdout.

### Environment

```markdown
Gentoo Linux
```

### Checklist

- [X] I have searched the existing issues for a bug report that matches the one I want to file, without success.
- [X] I have read the documentation and troubleshoot guide

**Comment by mkoeppe** [comment]
Likely underquoting in `SAGE_SYSTEM_PACKAGE_NOTICE` when `eval` is used.

**Comment by mkoeppe** [comment]
Please try #37020

**Comment by orlitzky** [comment]
Fixed by https://github.com/sagemath/sage/pull/37020
