### ISSUE TITLE
'Vertex' object does not support item assignment

### ISSUE THREAD

**Issue by hahahahahahahap** [sagemath/sage#37032]
v is  `<class 'sage.geometry.polyhedron.representation.Vertex'>
`
 I want to do the following:：
`v[0]=v[0]+1`
But the operation was blocked`TypeError: 'Vertex' object does not support item assignment`

How can I modify the data in this class, I just want to modify the value of the point？

**Comment by DaveWitteMorris** [comment]
This is a forum for issues about sagemath development, not for questions about how to use the software. You should post this question at a site such as [ask sage](https://ask.sagemath.org/questions/)

**Comment by hahahahahahahap** [comment]
> This is a forum for issues about sagemath development, not for questions about how to use the software. You should post this question at a site such as [ask sage](https://ask.sagemath.org/questions/)

I am so sorry for my behavior. I should have read the source code carefully before asking this question. The source code is really very detailed. Finally, my respect for your contribution.
