### ISSUE TITLE
pos_dict of CubeGraph(3) is not useful

### ISSUE THREAD

**Issue by pelegm** [sagemath/sage#37040]
### Steps To Reproduce

```sage
graphs.CubeGraph(3).plot()
```

### Expected Behavior

A plot in which each vertex appears in a different spot.
Better: a plot that looks like a cube.
(yes, I know the method `plot3d`)

### Actual Behavior

The vertices `010` and `101` appear at the same point in the drawing.
Indeed, this can be seen by checking `_pos`:
```sage
sage: graphs.CubeGraph(3)._pos
{'000': (0.0, 0.0),
 '001': (-0.4999999999999998, 0.8660254037844387),
 '010': (0.5000000000000001, 0.8660254037844386),
 '011': (3.3306690738754696e-16, 1.7320508075688772),
 '100': (1.0, 0.0),
 '101': (0.5000000000000002, 0.8660254037844387),
 '110': (1.5, 0.8660254037844386),
 '111': (1.0000000000000002, 1.7320508075688772)}
```

### Additional Information

This looks slightly more like what I would have expected:
```sage
{'000': (0,0), '001': (0,1), '010': (1,0), '011': (1,1), '100': (0.707,0.707), '101': (0.707,1.707), '110': (1.707,0.707), '111': (1.707,1.707)}
```

### Environment

```markdown
- **OS**: Ubuntu 20.04
- **Sage Version**: 9.0 (but also verified this on 9.5)
```

### Checklist

- [x] I have searched the existing issues for a bug report that matches the one I want to file, without success.
- [X] I have read the documentation and troubleshoot guide

**Comment by dcoudert** [comment]
This is not a bug. It's in accordance with the documentation of the method. We already have 2 well documented embeddings. If you think that a third one is needed, feel free to add it along with appropriate documentation.
