### ISSUE TITLE
solve diverged integrals

### ISSUE THREAD

**Issue by zfrhv** [sagemath/sage#37051]
### Problem Description

on the [official docs](https://doc.sagemath.org/html/en/reference/calculus/sage/symbolic/integration/integral.html) it tells:
```python
sage: forget() # always remember to forget assumptions you no longer need
sage: integrate(1/x^3,(x,0,1))
Traceback (most recent call last):
...
ValueError: Integral is divergent.
sage: integrate(1/x^3,x,-1,3)
Traceback (most recent call last):
...
ValueError: Integral is divergent.
```
but it doesnt tells how to solve it.

also in [this issue](https://ask.sagemath.org/question/26152/improper-integral-error/) its suggested to try to use a different method, but none of [those methods](https://doc.sagemath.org/html/en/reference/calculus/sage/symbolic/integration/integral.html) can solve this integral:
```
maxima
sympy
mathematica_free
fricas
giac
libgiac
```

### Proposed Solution

fix the integration with mathematica_free (because on wolframe alpha the integral does work),  
or implement a new method that can solve the integral.

### Alternatives Considered

cooperate with maxima to add a feature to solve the integral even when its diverged

### Is there an existing issue for this?

- [X] I have searched the existing issues for a bug report that matches the one I want to file, without success.

**Comment by DaveWitteMorris** [comment]
The answers from sagemath are correct. [Wolfram alpha says "(integral does not converge)", so I do not understand the comment that "on wolframe alpha the integral does work".] I think this issue should be closed.

**Comment by zfrhv** [comment]
![image](https://github.com/sagemath/sage/assets/53610738/e29a88fc-2c37-46fe-ae9a-e7bebdc07b26)
it gave result of 4/9

**Comment by DaveWitteMorris** [comment]
No, 4/9 is is the "principal value" of the integral, not the actual value: note that the label on the box containing this answer is "Cauchy principal value" (and there is "PV" before the integral sign). The correct answer is in the box labelled "Result": "(integral does not converge)".

**Comment by zfrhv** [comment]
then is there any way to do 
```python
sage: integrate(1/x^3,x,-1,3)
```
and return the principal value instead of an error?

**Comment by DaveWitteMorris** [comment]
See the answers to this [ask sagemath](https://ask.sagemath.org/question/73780/cauchy-principal-value-integral/) question.

**Comment by zfrhv** [comment]
they use workarounds to get the specific results,
its nice for specifically simple cases but its impossible in my case.

im a simple physicist and im not really deep into math, my integral is:
```python
def combine(v1, v2):
  return v1.dot_product(v2)
def parallel_1(v1, v2): # v1 projection when parallel to v2 => (v1 ∥ v2)
  v2_unit = v2.normalized()
  return v1.dot_product(v2_unit) * v2_unit
def vertical_1(v1, v2): # v1 projection when vertical to v2 => (v1 ⊥ v2)
  v2_unit = v2.normalized()
  return v1 - parallel_1(v1, v2)

var('p1_x, p2_x, p2_y')

assume(p2_y > 0)

p1 = vector([p1_x, 0])
p2 = vector([p2_x, p2_y])
v1 = vector([1,0])
v2 = vector([1,0])


L = p2 - p1
L_unit = L.normalized()

F_2_T = vector([0,0])

F_2_T += - combine(v1, L_unit) * combine(v2, L_unit) * L_unit * 8
F_2_T += + combine(vertical_1(v1, L_unit), vertical_1(v2, L_unit)) * L.normalized() * 4
F_2_T += + combine(v1, L_unit) * vertical_1(v2, L_unit) * 4
F_2_T += + combine(v2, L_unit) * vertical_1(v1, L_unit) * 4

F_2_T = F_2_T / L.norm()^4


integrate(integrate(F_2_T, p1_x, -infinity, infinity), p2_x, -infinity, infinity)
```
(i already know that the result is (0,0) i just need to prove it)
there is a lot of complex math and vectors and it returns me:
```python
...
/opt/sagemath-9.3/local/lib/python3.7/site-packages/sage/interfaces/maxima_lib.py in sr_integral(self, *args)
    793 # in pexpect interface, one looks for this - e.g. integrate(1/x^3,x,-1,3) gives a principal value
    794 #            if "divergent" in s or 'Principal Value' in s:
--> 795                 raise ValueError("Integral is divergent.")
    796             elif "Is" in s: # Maxima asked for a condition
    797                 self._missing_assumption(s)

ValueError: Integral is divergent.
```
so it attempts to do divergent integral automatically:
```python
integrate(1/x^3,x,-1,3)
```

i have a variable and i tried 
```python
sage: integrate(integrate(F_2_T, p1_x, -infinity, infinity).principal_value(), p2_x, -infinity, infinity).principal_value()
...
AttributeError: 'FreeModule_ambient_field_with_category.element_class' object has no attribute 'principal_value'
```
i guess he is not good with variables

i feel like im dealing with workarounds here, it would be nice to just have something like:
```python
integrate(integrate(F_2_T, p1_x, -infinity, infinity, pv=True), p2_x, -infinity, infinity, pv=True)
```

**Comment by DaveWitteMorris** [comment]
This is a forum for issues about developing the sagemath software, and this discussion has gotten off that track. Questions about how to use sagemath should be posted at a forum such as [ask sagemath](https://ask.sagemath.org/)

**Comment by zfrhv** [comment]
but this problem [has already been asked](https://ask.sagemath.org/question/26152/improper-integral-error/) and there is no working solution
seems to me that its more development issue

**Comment by zfrhv** [comment]
i not trying to argue, i just want to contribute with what i can
you can close this issue if it seems irrelevant

**Comment by DaveWitteMorris** [comment]
Asking for sagemath to implement a `principal_value` keyword for integrals is a reasonable enhancement request. That seems to be the gist of the development issue in this thread. That has already been suggested in #13511, so I think the current issue will be closed as a duplicate. 

[The [ask sagemath question](https://ask.sagemath.org/question/26152/improper-integral-error/) that you linked to is about a different problem, where maxima (and hence sagemath) thinks an integral is divergent, even though it's not. (Those seem to be bugs in maxima and in the interface to mathematica_free.)]

**Comment by zfrhv** [comment]
thank you for clarifying, closing as its a duplicate 👍
