### ISSUE TITLE
failed to build source code 10.2

### ISSUE THREAD

**Issue by cyegger** [sagemath/sage#37117]
### Environment

```markdown
- **OS**: Ubuntu 22.04
- **Sage Version**: 10.2
```

### Steps To Reproduce

I met the error :

make[1]: Entering directory '/home/egger/sagemath/sage'
rm -rf config/install-sh config/compile config/config.guess config/config.sub config/missing configure build/make/Makefile-auto.in
rm -f src/doc/en/installation/*.txt
rm -rf src/doc/en/reference/spkg/*.rst
for a in environment environment-optional src/environment src/environment-dev src/environment-optional; do rm -f $a.yml $a-3.[89].yml $a-3.1[0-9].yml; done
rm -f src/Pipfile
rm -f src/pyproject.toml
rm -f src/requirements.txt
rm -f src/setup.cfg
make[1]: Leaving directory '/home/egger/sagemath/sage'
bootstrap:: installing 'm4/sage_spkg_configures.m4'
bootstrap:: installing 'm4/sage_spkg_versions.m4'
bootstrap:: installing 'm4/sage_spkg_versions_toml.m4'
./bootstrap: 1: src/bootstrap: not found
make: *** [Makefile:328: configure] Error 1

### Config log

make[1]: Entering directory '/home/egger/sagemath/sage'
rm -rf config/install-sh config/compile config/config.guess config/config.sub config/missing configure build/make/Makefile-auto.in
rm -f src/doc/en/installation/*.txt
rm -rf src/doc/en/reference/spkg/*.rst
for a in environment environment-optional src/environment src/environment-dev src/environment-optional; do rm -f $a.yml $a-3.[89].yml $a-3.1[0-9].yml; done
rm -f src/Pipfile
rm -f src/pyproject.toml
rm -f src/requirements.txt
rm -f src/setup.cfg
make[1]: Leaving directory '/home/egger/sagemath/sage'
bootstrap:: installing 'm4/sage_spkg_configures.m4'
bootstrap:: installing 'm4/sage_spkg_versions.m4'
bootstrap:: installing 'm4/sage_spkg_versions_toml.m4'
./bootstrap: 1: src/bootstrap: not found
make: *** [Makefile:328: configure] Error 1

### Checklist

- [X] I have searched the existing issues for a bug report that matches the one I want to file, without success.
- [X] I have read the documentation and troubleshoot guide

**Comment by fccoelho** [comment]
I had the same issue on 10.3

**Comment by chrisxu3** [comment]
I'm also running into this same issue, on 10.4 this time. 

```
rm -rf config/install-sh config/compile config/config.guess config/config.sub config/missing configure build/make/Makefile-auto.in
rm -f src/doc/en/installation/*.txt
rm -rf src/doc/en/reference/spkg/*.rst
for a in environment environment-optional src/environment src/environment-dev src/environment-optional; do rm -f $a.yml $a-3.[89].yml $a-3.1[0-9].yml; done
rm -f src/Pipfile
rm -f src/pyproject.toml
rm -f src/requirements.txt
rm -f src/setup.cfg
bootstrap:: installing 'm4/sage_spkg_configures.m4'
bootstrap:: installing 'm4/sage_spkg_versions.m4'
bootstrap:: installing 'm4/sage_spkg_versions_toml.m4'
./bootstrap: 1: ./bootstrap: src/bootstrap: not found
```

**Comment by mkoeppe** [comment]
I suspect this is the same as https://groups.google.com/g/sage-devel/c/I6_yXdtMwQk/m/xQZoZFSGBgAJ,
which is now handled by #38039

**Comment by mkoeppe** [comment]
@chrisxu3 Thanks for the confirmation. If you have any suggestions for improvements of our documentation, that would be valuable
