### ISSUE TITLE
Failing to build cvxopt-1.3.2

### ISSUE THREAD

**Issue by drago-96** [sagemath/sage#37149]
### Environment

```markdown
- **OS**: macOS Sonoma 14.2.1
- **Sage Version**: 10.3.beta6
```

### Steps To Reproduce

1. `git clone https://github.com/sagemath/sage.git sage-test && cd sage-test`
2. Install all packages suggested [here](https://doc.sagemath.org/html/en/installation/source.html#macos-package-installation)
3. `` export SAGE_ROOT=`pwd` ``
4. `export MAKE="make -j4"`
5. `source ./.homebrew-build-env`
6. `make configure`
7. `./configure`
8. `make`

### Config log

[config.log](https://github.com/sagemath/sage/files/14025402/config.log)

### Package logs

[cvxopt-1.3.2.log](https://github.com/sagemath/sage/files/14025412/cvxopt-1.3.2.log)

### Additional Information

I think that this is closely related to issue #31905, which has been closed, but it seems not to be fully resolved.

I also tried building with the environment variables `CVXOPT_SUITESPARSE_INC_DIR` and `CVXOPT_SUITESPARSE_LIB_DIR` set to homebrew path of suite-sparse, but that didn't solve the issue either.

### Checklist

- [X] I have searched the existing issues for a bug report that matches the one I want to file, without success.
- [X] I have read the documentation and troubleshoot guide

**Comment by jhpalmieri** [comment]
A workaround is `./configure --with-system-suitesparse=no` before building Sage, but it would be nice to be able to use `suite-sparse` from `homebrew`.

**Comment by drago-96** [comment]
Actually I was wrong, by setting `CVXOPT_SUITESPARSE_INC_DIR=/opt/homebrew/include/suitesparse` and `CVXOPT_SUITESPARSE_LIB_DIR=/opt/homebrew/lib` it seems to build fine!

However, I have no idea if and how I can make the sage build system do this check and eventually set these variables.

**Comment by jhpalmieri** [comment]
Perhaps editing (and the rerunning) `SAGE_ROOT/.homebrew-build-env`?

**Comment by dimpase** [comment]
The route cause of the trouble is an attempt to use pre-installed brand new version of SuiteSparse (7.6.0).

It was released this month (we should upgrade our  SuiteSparse, by the way, I'll do a PR on this). 

The error comes from 
`  #include "umfpack.h"` in CVXOPT code, 
but by right it should be   `#include <suitesparse/umfpack.h>"`

CVXOPT doesn't do a great job detecting these things it seems.
