### ISSUE TITLE
Taking the dual of an elliptic curve isogeny raises AssertionError

### ISSUE THREAD

**Issue by pjbruin** [sagemath/sage#37168]
### Steps To Reproduce

We create an isogeny between elliptic curves over a finite field of 23^2 elements:
```
sage: R.<x> = GF(23)[]
sage: F.<a> = FiniteField(23^2, modulus=x^2-x+1)
sage: E0 = EllipticCurve(F, (0, 1))
sage: E1 = EllipticCurve(F, (8, 1))
sage: phi = E0.isogeny(kernel=E0((a, 0)), codomain=E1)
sage: phi.dual()
```

### Expected Behavior

The dual of `phi` should be returned.

### Actual Behavior

The following error is raised:
```
Traceback (most recent call last):
...
AssertionError: bug in dual()
```

### Additional Information

The error is not raised when `codomain=E1` is omitted.

### Environment

```markdown
- **Sage Version**: SageMath 10.3.beta6
```

### Checklist

- [X] I have searched the existing issues for a bug report that matches the one I want to file, without success.
- [X] I have read the documentation and troubleshoot guide

**Comment by pjbruin** [comment]
@yyyyx4 the Git log says you wrote the relevant part of dual(), could you have a look?

**Comment by yyyyx4** [comment]
Interesting, thanks for reporting this. I'll have a look approximately tomorrow.
