### ISSUE TITLE
Improve the documentation of discrete dynamical systems

### ISSUE THREAD

**Issue by mantepse** [sagemath/sage#37188]
### Steps To Reproduce

There are typos and repeated sentences in https://doc.sagemath.org/html/en/reference/dynamics/sage/dynamics/finite_dynamical_system.html

### Expected Behavior

There shouldn't be any typos!

### Actual Behavior

There are typos!

### Additional Information

Tthis, A discrete dynamical system (henceforth DDS) is a pair of a set and a map . This set is called the ground set of the DDS, while the map is called the evolution of the DDS.

A discrete dynamical system (short: DDS) is a pair of a set and a map .

### Environment

```markdown
irrelevant
```

### Checklist

- [X] I have searched the existing issues for a bug report that matches the one I want to file, without success.
- [X] I have read the documentation and troubleshoot guide

**Comment by vamshipy** [comment]
i am working on this..

**Comment by Omegaconstant** [comment]
Hello,
Is this issue still open?

If so, I would like to work on this.
Thank you :-)

**Comment by mantepse** [comment]
Oh, that would be wonderful!  You have done a great job on the other issue!

**Comment by Omegaconstant** [comment]
Thank you.
I will start working on this.

**Comment by Dhrumil07** [comment]
Hi, I have raised [this](https://github.com/sagemath/sage/pull/37506) PR, which will resolve this issue. Can you review the PR @mantepse ?
Also, if any additional improvements in the documentation are required, please let me know.
