### ISSUE TITLE
Implement a function to generate the acyclic orientations of an undirected graph

### ISSUE THREAD

**Issue by saatvikraoIITGN** [sagemath/sage#37253]
### Problem Description

In graph theory, an acyclic orientation of an undirected graph is an assignment of a direction to each edge (an orientation) that does not form any directed cycle and therefore makes it into a directed acyclic graph. Every graph has an acyclic orientation. Currently, SageMath lacks a built-in functionality to find acyclic orientations of undirected graphs. The absence of this feature limits users who require such computations for graph-related research and applications.

### Proposed Solution

We will be referring to a research paper by Matthew B. Squire [https://www.sciencedirect.com/science/article/abs/pii/S0196677497908919](url)

The proposed solution involves introducing a new function to address the current lack of a dedicated feature for computing acyclic orientations in SageMath. 
The function would take an undirected graph as input and implement a multi-step process: 
- first, it would reorder the vertices using a greedy approach based on degree centrality, ensuring efficient computation. 
- Then, the edges would be labeled according to the reordering of vertices. 
- Following this, the function would utilize a recursive algorithm to explore subsets of the graph's edges and generate acyclic orientations by considering a partially ordered set. 

The proposed solution encapsulates the essential logic demonstrated in the provided Python code, offering a seamless and integrated way for users to obtain acyclic orientations within the SageMath environment.

### Alternatives Considered

**Manual Implementation:** Users can manually implement the logic provided in the example code, but a built-in function would simplify the process and promote code reusability.

### Is there an existing issue for this?

- [X] I have searched the existing issues for a bug report that matches the one I want to file, without success.

**Comment by mantepse** [comment]
you should compare the timing with `self.tutte_polynomial().subs(x=2, y=0)`.

**Comment by dcoudert** [comment]
For information, there is an open pull request on this question: #35075

**Comment by dcoudert** [comment]
See also #37272 for the generation of non-isomorphic acyclic orientations using `nauty_directg`.

**Comment by saatvikraoIITGN** [comment]
Sure! I will mention these issues when I submit a PR
