### ISSUE TITLE
QEPCAD crashing

### ISSUE THREAD

**Issue by anirjoshi** [sagemath/sage#37349]
### Steps To Reproduce

1. start sage in MacOS 13.4 M2
2. copy paste the following
3. 
```
var('y')
var('r1')
var('r2')
var('tmp')
qf = qepcad_formula
constr0 = (+tmp - tmp + (Rational(73/70))  + (Rational(-1/1)* (y^2))  + (Rational(-1/1)* (r1)) < 0)
constr1 = (+tmp - tmp + (Rational(143/70)* (y))  + (Rational(1/1)* (r2)) < 0)
constr2 = (+tmp - tmp + (Rational(-73/70)) < 0)
F1 = qf.and_(constr0, constr1, constr2)
F3 =F1
print(qepcad(qf.exists(y,F3)))
```
5. This prints `Qepcad crashed -- automatically restarting.` and then just waits for a long long time and does not terminate.

### Expected Behavior

On another linux system this prints rather quickly (<5 secs)
`42 a - 23 /= 0 /\ 42 a + 23 /= 0 /\ b /= 0 /\ 42 r - 443 /= 0 /\ 42 r + 443 /= 0 /\ [ 3111696 a^4 r^4 - 6223392 a^4 b^2 r^2 + 1866312 a^2 b^2 r^2 - 1314705672 a^4 r^2 + 3111696 a^4 b^4 - 1866312 a^2 b^4 + 279841 b^4 + 70027272 a^4 b^2 - 21000242 a^2 b^2 + 138867277201 a^4 < 0 \/ [ 42 a - 23 > 0 /\ 1764 a^2 r^2 - 1764 a^2 b^2 + 529 b^2 - 372649 a^2 > 0 ] \/ [ 42 a + 23 < 0 /\ 1764 a^2 r^2 - 1764 a^2 b^2 + 529 b^2 - 372649 a^2 > 0 ] \/ [ 1764 a^2 b^2 - 529 b^2 - 176400 a^2 > 0 /\ 42 r - 443 > 0 ] \/ [ 1764 a^2 b^2 - 529 b^2 - 176400 a^2 > 0 /\ 42 r + 443 < 0 ] ]`

### Actual Behavior

On my system MacOS 13.4 M2, this prints `Qepcad crashed -- automatically restarting.` and then just keeps waiting and does not terminate.

### Additional Information

The version of sage is: SageMath version 10.1, and I have installed it in MacOS 13.4 M2

### Environment

```markdown
- **OS**: MacOS 13.4
- **Sage Version**: 10.1
```

### Checklist

- [X] I have searched the existing issues for a bug report that matches the one I want to file, without success.
- [X] I have read the documentation and troubleshoot guide

**Comment by auntyellow** [comment]
@anirjoshi actually the process `qepcad` exits and no another process starts.

**Comment by auntyellow** [comment]
@anirjoshi your expected result doesn't look like related to your input codes. In my laptop (MacOS 13.4, M2, Sage 10.2) your codes return `TRUE`.

**Comment by anirjoshi** [comment]
@auntyellow Thank you! Had a typo, the sage file that doesn't work is:
```
var('x')
var('c')
var('d')
var('e')
var('tmp')
qf = qepcad_formula
constr0 = (tmp - tmp +(Rational(1/1)* (x^2)* (d))  + (Rational(1/64))  + (Rational(1/8)* (x))  + (Rational(1/8)* (x)* (c)* (d))  + (Rational(1/1)* (d)* (e)) < 0)
constr1 = (tmp - tmp +(Rational(1/1)* (x^2))  + (Rational(1/64)* (d))  + (Rational(1/1)* (c)) < 0)
F1 = qf.and_(constr0, constr1)
F3 =F1
print(qepcad(qf.exists(x,F3)))

```

**Comment by anirjoshi** [comment]
@auntyellow , thank you for pointing it out, I do not know the expected output. On linux machine it just outputs `finish  &` and on a mac, it outputs `Qepcad crashed -- automatically restarting.`

**Comment by anirjoshi** [comment]
@auntyellow  I have raised a new issue here, [Issue](https://github.com/sagemath/sage/issues/37507#issue-2160947841)

**Comment by maxale** [comment]
> @auntyellow I have raised a new issue here, [Issue](https://github.com/sagemath/sage/issues/37507#issue-2160947841)

How the two issues are different?

**Comment by anirjoshi** [comment]
@maxale  Thank you for the response! These issues are similar, therefore closing this one now.
