### ISSUE TITLE
Long testing time: topology/moment_angle_complex.py

### ISSUE THREAD

**Issue by gmou3** [sagemath/sage#37378]
There are quite a few time-consuming tests in this file, most of them without a `# long time` designation.

A couple of them are especially bad:

```
File "src/sage/topology/moment_angle_complex.py", line 595, in sage.topology.moment_angle_complex.MomentAngleComplex.?
Warning, slow doctest:
    Z.homology()
Test ran for 63.65 s, check ran for 0.00 s
[...]
File "src/sage/topology/moment_angle_complex.py", line 721, in sage.topology.moment_angle_complex.MomentAngleComplex.euler_characteristic
Warning, slow doctest:
    M.euler_characteristic()
Test ran for 54.54 s, check ran for 0.00 s
```

@OP5642 Can these two tests be replaced with faster ones from smaller simplicial complexes?

**Comment by tscrim** [comment]
Those tests are far faster on my laptop (~16s and ~11s), but yes, they should have been marked as `# long time` (which was my fault as the reviewer). However, it is not easier to make them smaller and nontrivial. Indeed, part of the point is they are (very) large simplicial complexes that are computed within a reasonable time. I think we should just mark them as `# long time` rather than try to shrink them down.

**Comment by gmou3** [comment]
Ok. On a more general point, why do we always test these `# long time` commands? Shouldn't this only happen manually or at specific points of the release cycle?

**Comment by OP5642** [comment]
I apologize for not addressing this sooner, but yes, as @tscrim said, I think it's best to mark them as ``# long time``, because we want to show that the computation is relatively quick even for large simplicial complexes.

**Comment by tscrim** [comment]
> Ok. On a more general point, why do we always test these `# long time` commands? Shouldn't this only happen manually or at specific points of the release cycle?

They have been known to catch bugs that cannot be seen on smaller examples. So it is good to run them through the CI tests. They are also tested before each PR is merged (for the same reason).

**Comment by gmou3** [comment]
> They are also tested before each PR is merged (for the same reason).

That's reasonable. My puzzlement is about the fact that they are run after each commit in a PR: doesn't that make the `# long time` labels less purposeful?

**Comment by tscrim** [comment]
> > They are also tested before each PR is merged (for the same reason).
> 
> That's reasonable. My puzzlement is about the fact that they are run after each commit in a PR: doesn't that make the `# long time` labels less purposeful?

For CI testing, yes, but not for testing locally on a developer’s machine.

**Comment by gmou3** [comment]
Ok, I see. Thank you.
