### ISSUE TITLE
Version selector for the documentation

### ISSUE THREAD

**Issue by mkoeppe** [sagemath/sage#37384]
- We have the stable version at https://doc.sagemath.org/html/en/ 
- We have the development version at https://deploy-livedoc--sagemath.netlify.app/html/en (linked from https://github.com/sagemath/sage/wiki). 
- We have the version of a particular branch created by the doc-build workflow.
- We can build locally.

We should include a version selector in the generated HTML files that allows us to switch between these versions easily.

Multiple technical solutions:

Version switcher dropdowns — PyData Theme 0.15.2 documentation
https://pydata-sphinx-theme.readthedocs.io/en/stable/user_guide/version-dropdown.html

sphinx-versioned-docs · PyPI
https://pypi.org/project/sphinx-versioned-docs/

Quickstart — sphinx-multiversion 0.2.4 documentation
https://holzhaus.github.io/sphinx-multiversion/master/quickstart.html

steinwurf/versjon: Tool for injecting version selector in Sphinx's HTML output
https://github.com/steinwurf/versjon

My Sphinx Best Practice Guide for Multi-version Documentation in Different Languages — Coding With Thomas
https://www.codingwiththomas.com/blog/my-sphinx-best-practice-for-a-multiversion-documentation-in-different-languages

Versioned documentation — Read the Docs user documentation
https://docs.readthedocs.io/en/stable/versions.html

**Comment by Omegaconstant** [comment]
Hello,
I would like to work on this.

Thank you :-)

**Comment by mkoeppe** [comment]
Implemented in #38285
