### ISSUE TITLE
Documentation of hidden options `sage -ba` etc.

### ISSUE THREAD

**Issue by grhkm21** [sagemath/sage#37429]
In `src/bin/sage` [here](https://github.com/sagemath/sage/blob/develop/src/bin/sage#L932) there are options that are handled but not exposed to the user, e.g. `sage -ba` which I believe cleans the directory before building again? I believe they can be better documented, both in the code and in the `--help` menu.

Note that #37419 moves the code around

**Comment by mezzarobba** [comment]
`sage -ba` is documented in `sage --advanced`.

**Comment by grhkm21** [comment]
Thanks! Sorry about that.
