### ISSUE TITLE
Use different label than "blocker" to merge changes from PRs

### ISSUE THREAD

**Issue by tobiasdiez** [sagemath/sage#37428]
### Problem Description

Currently there are 9 PRs marked as blocker, but only one of them fixes a bug in the ci and would need to be applied to other PRs. This may lead to other PRs breaking for no reason (eg https://github.com/sagemath/sage/pull/36524 is broken because of one of these blocker PRs).

### Proposed Solution

Use a different label than "p1: blocker". 

### Alternatives Considered

No idea, open for suggestions.

### Is there an existing issue for this?

- [X] I have searched the existing issues for a bug report that matches the one I want to file, without success.

**Comment by mkoeppe** [comment]
This was done in #37950.
