### ISSUE TITLE
Bug in integration on a Riemann surface<title>

### ISSUE THREAD

**Issue by DisneyHogg** [sagemath/sage#37438]
### Steps To Reproduce

Inside the Sage terminal, run 

```
R.<z,x> = QQ[]
f = x*(1^5+z^5) + (x*1*z)^2 - x^4*1*z - 2*1^3*z^3
S = Curve(f).riemann_surface()
S.riemann_matrix()
```

### Expected Behavior

You would expect this to successfully compute the Riemann matrix of the corresponding Riemann surface. 

### Actual Behavior

It gives a `ValueError` inside `rigorous_line_integral`. 

### Additional Information

This error doesn't occur if instead you either use `R.<x,z> = QQ[]` or `S = Curve(f).riemann_surface(integration_method="heuristic")`, which suggests it is an error in how the path-splitting method is being applied in certain configurations. This has been discussed [on sage-devel](https://groups.google.com/g/sage-devel/c/wcznXH3WLSM/m/EVP_1k-FAQAJ). 

### Environment

```markdown
- **OS**: both Red Hat Enterprise 8.9 and Ubuntu 18.04.6
- **Sage Version**: both 9.8, 10.3.beta0, and 10.3.beta4
```

### Checklist

- [X] I have searched the existing issues for a bug report that matches the one I want to file, without success.
- [X] I have read the documentation and troubleshoot guide

**Comment by kh-abd-kh** [comment]
Two seperate problems:
Hi, I don't know if this the correct topics or i should  have opened an new issue.
While calculating thetanulls for various g=6,7 curves. I had a problem 
the prog hangs out goes and never return. in calculating the RM.

I tracked the source of the error
in your 
def cohomology_basis(self, option=1)
actually the default in singular is 2
def cohomology_basis(self, option=2)
it solved the problem for most of the cuves but still fails for the macbeath g=7 curve.

The second Problem
Also, It seems that everybody followed the original code For RiemannTheta
# lib/src/RiemannTheta
#
# RiemannTheta
#
# Author: Bernard Deconinck  (2001).
# Modifications by Mark van Hoeij.

where they initialize the lattice data for the  convergence ellipsoid inside the theta.
That is a true pain in the neck.
a- imagine plotting 100x100 figs of the same curve each time for 10000 you reinitialize the theta
for the same curve or (b) doing the even theta  scan. There is no need for reinitialization

In "abelfunctions" it is takes long time for g=7 >120 sec.
In yours it fast but still needs a call to pari for higher genus
fails for 1G Pari stack UP to  4G pari stack is ok for g <=9. But for g=10
shall needs >12G pari stack for prec better than 10^-5

I hope it is understood. 
Many INFINITly THANKS for your work.

**Comment by DisneyHogg** [comment]
> Two seperate problems: Hi, I don't know if this the correct topics or i should have opened an new issue. 

The two points you have raised here are somewhat different, and so deserve different action:

> I tracked the source of the error in your def cohomology_basis(self, option=1) actually the default in singular is 2 def cohomology_basis(self, option=2) it solved the problem for most of the cuves but still fails for the macbeath g=7 curve.

You are reporting an issue with the performance of the code, so you should raise a separate issue, give a reproducible description of the problem at hand including your environment etc., and then if the problem is one that needs fixing a separate pull request can be opened for a fix. 

> The second Problem Also, It seems that everybody followed the original code For RiemannTheta lib/src/RiemannTheta
> 
> RiemannTheta
> 
> Author: Bernard Deconinck (2001). Modifications by Mark van Hoeij.
> 
> where they initialize the lattice data for the convergence ellipsoid inside the theta. That is a true pain in the neck. a- imagine plotting 100x100 figs of the same curve each time for 10000 you reinitialize the theta for the same curve or (b) doing the even theta scan. There is no need for reinitialization
> 
> In "abelfunctions" it is takes long time for g=7 >120 sec. In yours it fast but still needs a call to pari for higher genus fails for 1G Pari stack UP to 4G pari stack is ok for g <=9. But for g=10 shall needs >12G pari stack for prec better than 10^-5

For your second problem, it seems you are asking about the best implementations of the Riemann theta function. I did not think the theta function had been implemented in Sage. abelfunctions that you mention is separately maintained so questions about their implementation are best discussed over there. You could raise an issue for a possible enhancement to include a Riemann theta in Sage, but that would be a different discussion.

**Comment by kh-abd-kh** [comment]
so  sorry for being completly newbie for this github, 
ok, for the first problem i will open new issue.
for the second, it seems that it has a very long history since 2009
https://github.com/sagemath/sage/issues/6371#
i shall see and explain how it is relevant. 
Nbruin theta breaks down for higher genus g >9 over limited 16G system due to the Pari stack. But it is still an important
contribution.
