### ISSUE TITLE
Method `.random_element` not impl'ed for`LaurentPolynomialRing`

### ISSUE THREAD

**Issue by grhkm21** [sagemath/sage#37454]
#### New Method

```sage
sage: LaurentPolynomialRing(QQ, "x").random_element() # errors
```

#### Original Method

Run `sage.rings.tests.test_random_arith` with seed `97302818739086349733003447647548552705`:

```sh
$ sage -c "from sage.rings.tests import test_random_arith as t; t(trials=1000, seed=97302818739086349733003447647548552705)" | tail -n 7
Univariate Laurent Polynomial Ring in x over Number Field in aa with defining polynomial x^2 - 3*x - 99 over its base field
Random testing has revealed a problem in test_random_arith
Please report this bug!  You may be the first
person in the world to have seen this problem.
Please include this random seed in your bug report:
Random seed: 97302818739086349733003447647548552705
NotImplementedError()
```

### Additional Information

Discovered in https://github.com/sagemath/sage/actions/runs/8031658497/job/21940219082?pr=37441 of #37441

Edit: Note that the cause of the workflow failing is NOT this method (as the failure is marked as a "timeout"). However, this is still logged as "Please report this bug".

### Environment

```markdown
Sage Version: both 10.2 & `develop`
```

### Checklist

- [X] I have searched the existing issues for a bug report that matches the one I want to file, without success.
- [X] I have read the documentation and troubleshoot guide

**Comment by grhkm21** [comment]
It seems that
```sage
sage: LaurentPolynomialRing(QQ, "x").random_element() # errors
```
is not implemented. I guess I can try to implement a quick one real quick...

**Comment by grhkm21** [comment]
Also I am very confused. I get this bug almost *every* run with `test_random_arith(trials=1000)`. How is this test only caught now?

**Comment by tscrim** [comment]
That seems to occur not too often and it simply should not have been included, or at least protected against, since it is not implemented (although the implementation is quite easy by using a random polynomial). Anyways, we should *independently* implement the random Laurent polynomial.

**Comment by GiacomoPope** [comment]
Would the implementation of this differ all that much from the usual impl of random elements in a polynomial ring?

**Comment by grhkm21** [comment]
No, pretty much you just sample a shifted version then divide by a power of x

**Comment by tscrim** [comment]
Indeed, it just needs an additional `min_val` to specify the minimal valuation, which would correspond to the appropriate shift. (Note this also affects the polynomial sampling degree.)

**Comment by GiacomoPope** [comment]
I have this a go here: https://github.com/sagemath/sage/pull/37490

**Comment by tscrim** [comment]
How about this for an easy fix: We `print("pass")` if it passes, so any `...` should end with a `pass` line. This won't print if it fails without trying to come up with fancier ways to change the doctests.

**Comment by grhkm21** [comment]
This feel like a worse fix to me but yeah sure
