### ISSUE TITLE
`LaurentPolynomialRing` define the zero polynomial to have degree `-1` which is ambiguous

### ISSUE THREAD

**Issue by GiacomoPope** [sagemath/sage#37491]
### Steps To Reproduce

```py
sage: R = LaurentPolynomialRing(QQ, 3, 'x')
sage: x0, x1, x2 = R.gens()
sage: R.zero().degree()
-1
sage: R.zero().degree(x0)
-1
sage: R.zero().degree(x1)
-1
sage: R.zero().degree(x2)
-1
sage: (1/x0).degree(x0)
-1
sage: (1/x0).degree()
-1
```

### Expected Behavior

The degree of `0` should be distinct from polynomials we can construct

### Actual Behavior

The degree of `0` is `-1`, the same as `1/x0` or other similar polynomials.

### Additional Information

For standard univariate and multivariate polynomial rings, the degree being `-1` is essentially a nice trick in place of $-\infty$, but for Laurent polynomial rings where negative degree makes total sense, this ambiguity with zero is confusing.

One idea would be to instead have it return `- infinity`.

### Environment

```markdown
- **Sage Version**: SageMath version 10.3.rc0, Release Date: 2024-02-25
```

### Checklist

- [X] I have searched the existing issues for a bug report that matches the one I want to file, without success.
- [X] I have read the documentation and troubleshoot guide

**Comment by GiacomoPope** [comment]
The issue is here:

```py
cdef long singular_polynomial_deg(poly *p, poly *x, ring *r) noexcept:
    cdef long _deg, deg
    cdef int dummy

    deg = -1
    _deg = -1
    if p == NULL:
        return -1
    if r != currRing:
        rChangeCurrRing(r)
    if x == NULL:
        return p_LDeg(p, &dummy, r)

    cdef int i = 0
    for i in range(1,r.N+1):
        if p_GetExp(x, i, r):
            break
    while p:
        _deg =  p_GetExp(p,i,r)
        if _deg > deg:
            deg = _deg
        p = pNext(p)
    return deg
```

The zero polynomial is determined to be `NULL` and so `-1` is returned.

**Comment by GiacomoPope** [comment]
Oh ok, so this is apparently a contested thing even in the literature:

https://math.stackexchange.com/questions/1796312/what-is-the-degree-of-the-zero-polynomial-and-why-is-it-so

So there's not going to be a simple issue for this

**Comment by grhkm21** [comment]
Yes, this is "normal" or at least the convention taken in Sage. Usually it's defined as $\deg(0) = -\infty$, but Sage uses $\deg(0) = -1$. It's also the case for univariate

**Comment by GiacomoPope** [comment]
Some further context, we also have:

```py
sage: R.<x> = LaurentSeriesRing(QQ)
sage: R.zero().valuation()
+Infinity
sage: R.zero().degree()
-1
sage:
sage: R.<x> = LaurentPolynomialRing(QQ)
sage: R.zero().valuation()
+Infinity
sage: R.zero().degree()
-1
sage:
sage: R.<x> = LazyLaurentSeriesRing(QQ)
sage: R.zero().valuation()
+Infinity
sage: R.zero().degree()
# Errors
```

So the valuation seems to have been written with this in mind but the degree is picking up the result from the underlying polynomial ring? Makes me lean towards a patch giving `-Infinity` for the zero polynomial
