### ISSUE TITLE
"DeprecationWarning: There is no current event loop" at startup

### ISSUE THREAD

**Issue by DavidAyotte** [sagemath/sage#37539]
### Steps To Reproduce

* SageMath version: 10.3.rc2
* OS: Ubuntu 22.04.4 LTS under WSL2
* At sage startup, I get the following message:
```
~/sage$ sage
┌────────────────────────────────────────────────────────────────────┐
│ SageMath version 10.3.rc2, Release Date: 2024-03-04                │
│ Using Python 3.11.1. Type "help()" for help.                       │
└────────────────────────────────────────────────────────────────────┘
┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
┃ Warning: this is a prerelease version, and it may be unstable.     ┃
┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛
/home/davidayotte/sage/local/var/lib/sage/venv-python3.11.1/lib/python3.11/site-packages/prompt_toolkit/application/application.py:988: DeprecationWarning: There is no current event loop
  loop = asyncio.get_event_loop()
```
* **Note 1**: the script `init.sage` located at `~/.sage/init.sage` does not run anymore. I use this script in order to assign custom variables at startup.
* **Note 2**: I'm still able to use SageMath afterward.

### Expected Behavior

I expect sage to run and the `init.sage` script to assign my variables.

### Actual Behavior

The script `init.sage` does not run and the deprecation warning shows up in the console.

### Additional Information

See also : 
* sage-support thread: https://groups.google.com/g/sage-support/c/uh1g2nkVcyc
* AskSageMath question: https://ask.sagemath.org/question/76321/there-is-no-current-event-loop/
* This StackOverflow question: https://stackoverflow.com/questions/73361664/asyncio-get-event-loop-deprecationwarning-there-is-no-current-event-loop

### Environment

- **OS** : Ubuntu 22.04.4 LTS under WSL2
- **Sage Version** : 10.3.rc2

### Checklist

- [X] I have searched the existing issues for a bug report that matches the one I want to file, without success.
- [X] I have read the documentation and troubleshoot guide

**Comment by kwankyu** [comment]
No problem with me on mac,
```
$ sage
┌────────────────────────────────────────────────────────────────────┐
│ SageMath version 10.3.rc2, Release Date: 2024-03-04                │
│ Using Python 3.11.6. Type "help()" for help.                       │
└────────────────────────────────────────────────────────────────────┘
┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
┃ Warning: this is a prerelease version, and it may be unstable.     ┃
┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛
sage: import prompt_toolkit
sage: prompt_toolkit.__version__
'3.0.41'
sage: QQQ
Rational Field
```
I have put `QQQ = QQ` in my `~/.sage/init.sage` to experiment. What is your version of `prompt_toolkit`?

**Comment by QMeqGR** [comment]
I see this warning on startup as well. I'm on Fedora 39.

```
$ sage
┌────────────────────────────────────────────────────────────────────┐
│ SageMath version 10.3.rc2, Release Date: 2024-03-04                │
│ Using Python 3.12.2. Type "help()" for help.                       │
└────────────────────────────────────────────────────────────────────┘
┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
┃ Warning: this is a prerelease version, and it may be unstable.     ┃
┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛
/home/packages/SOURCE/sage/local/var/lib/sage/venv-python3.12/lib64/python3.12/site-packages/prompt_toolkit/application/application.py:988: DeprecationWarning: There is no current event loop
  loop = asyncio.get_event_loop()
sage: 
```

**Comment by kwankyu** [comment]
I suspect that this is related with `prompt_toolkit`. What is your version?

**Comment by QMeqGR** [comment]
`sage: import prompt_toolkit
sage: prompt_toolkit.__version__
'3.0.41'
sage: QQ
Rational Field
`

**Comment by kwankyu** [comment]
Maybe install the latest version?
```
./sage -pip install prompt_toolkit==3.0.43
```
