### ISSUE TITLE
Optional spkg symengine_py has an invalid upstream url

### ISSUE THREAD

**Issue by culler** [sagemath/sage#37558]
### Environment

```markdown
- **All OS's**:
- **10.3.rc2**:
```

### Steps To Reproduce

Build Sage with the symengine_py optional package enabled

### Config log

[config.log](https://github.com/sagemath/sage/files/14512931/config.log)

### Package logs

[symengine_py-0.11.0.log](https://github.com/sagemath/sage/files/14512932/symengine_py-0.11.0.log)

### Additional Information

The problem here is that the file downloaded from the upstream url given in the spkg, namely:
   https://pypi.io/packages/source/p/symengine/symengine-0.11.0.tar.gz
is not the same as the file downloaded from the url specified on pypi, namely:
   https://files.pythonhosted.org/packages/fe/53/6289257bca1b326740460ea31cbc266ae171541b65bbada4b8d31f8ed3e1/symengine-0.11.0.tar.gz

The first file has md5 hash 5a859121a56e81179bef72816fb82ccd while the second has the md5 hash specified both in the checksums.ini file and on PyPI, namely d10f4ba5c27b09ef234fcafddf824ce5.

This is probably the tip of an iceberg.  It seems that all of wheel spkgs use upstream urls at pypi.io instead of the pypi urls which include a uuid.  Apparently one can no longer trust the pypi.io links.

### Checklist

- [X] I have searched the existing issues for a bug report that matches the one I want to file, without success.
- [X] I have read the documentation and troubleshoot guide

**Comment by culler** [comment]
Note that the "p" in the pypi.io url should be "s".  But this seems to make no difference.  You get the same file with "p" as with "s".

**Comment by mkoeppe** [comment]
I'm getting 404 on https://pypi.io/packages/source/p/symengine/symengine-0.11.0.tar.gz

**Comment by culler** [comment]
This has changed since this morning.  I am now getting a 301 with curl.

In any case, the official pypi url with the big hash value embedded in it works fine.  I see no reason why the upstream url specified in the spkg should not be the official pypi url.

The bigger question is how many other spkgs have upstream urls which are now broken.  The PyPI documentation says not to rely on those pypi.io urls.  Maybe they have now broken them.

**Comment by culler** [comment]
Actually, I don't think it changed since this morning.  I think the bad file I was getting was just an html file reporting the 301 error, not a different tarball.  Not that it makes much difference as far as Sage is concerned if Sage ever tries to use the upstream url.

**Comment by mkoeppe** [comment]
Actually the upstream url just has a typo. I'm fixing it in #37762
