### ISSUE TITLE
graphs.triangulations(3) does not return the triangle

### ISSUE THREAD

**Issue by pvalicov** [sagemath/sage#37562]
### Steps To Reproduce

len(list(graphs.triangulations(3)))

### Expected Behavior

1

### Actual Behavior

0

### Additional Information

The triangle (complete graph on 3 vertices) should be considered as a triangulation and returned by the iterator. 

### Environment

```markdown
- **OS**: Ubuntu 22.04
- **Sage Version**: 10.1
```

### Checklist

- [X] I have searched the existing issues for a bug report that matches the one I want to file, without success.
- [X] I have read the documentation and troubleshoot guide

**Comment by tscrim** [comment]
While surprising, this is actually the correct documented behavior. Note that it requires the degree to be $\geq 3$, but the triangle (cycle graph on 3 vertices) only has degree 2.

That being said, it likely wouldn't be a bad thing to special case that. @dcoudert might have some thoughts on this.

**Comment by pvalicov** [comment]
Indeed, the possible combinations of minimum degree and minimum connectivity make the triangle impossible. Also the dual is a multigraph, so this might be an issue too. Perhaps, simply adding in the documentation of the function that the triangle is excluded, would be sufficient.

**Comment by tscrim** [comment]
To be fair, it is already documented (by the degree condition). However, an example for the 3 vertex case explaining why it’s empty could make it more clear.

**Comment by dcoudert** [comment]
a doctest is added in #37602.
