### ISSUE TITLE
Muffle DeprecationWarning during docbuild

### ISSUE THREAD

**Issue by mkoeppe** [sagemath/sage#37664]
These deprecation warnings are not helpful and should be suppressed.

Example:
```
[sagemath_doc_html-10.4.beta0]   [cryptogra] /sage/local/var/lib/sage/venv-python3.11.1/lib/python3.11/site-packages/sphinx/util/inspect.py:330: DeprecationWarning:
[sagemath_doc_html-10.4.beta0]   [cryptogra] Importing carmichael_lambda from here is deprecated; please use "from sage.arith.misc import carmichael_lambda" instead.
[sagemath_doc_html-10.4.beta0]   [cryptogra] See https://github.com/sagemath/sage/issues/34719 for details.
[sagemath_doc_html-10.4.beta0]   [cryptogra]   return getattr(obj, name, *defargs)
[sagemath_doc_html-10.4.beta0]   [cryptogra] The inventory file is in ../inventory/en/reference/cryptography.
```

**Comment by thecaligarmo** [comment]
Most of these are coming from `lazy_import` as it has the `deprecation` parameter. Is the point of this issue to remove the `deprecation` parameter altogether? (Why was it added in the first place?)  Or is it to go through and remove all lazy imports which contain these deprecation warnings? (If so, I still don't see why there's a `deprecation` parameter if we'd want to remove those lazy imports altogether.)

**Comment by mkoeppe** [comment]
No, the deprecation warnings have an important function: They alert about code (in library and users' code) that should be updated.
Just during the docbuild (sphinx), these warnings should not be shown.

**Comment by thecaligarmo** [comment]
Sounds good. So far what I have is that I can remove all `DeprecationWarning` when we do sphinx. This would remove *all* deprecation warnings and not just the ones coming form `lazy_import`. If that's not the idea, lemme know, but if so, I'll submit a pull request with the changes.

**Comment by mkoeppe** [comment]
Yes, this sounds like a suitable solution.
