### ISSUE TITLE
RST liner is failing due to RST304 failure

### ISSUE THREAD

**Issue by GiacomoPope** [sagemath/sage#37711]
### Steps To Reproduce

```
Jack: sage % ./sage --version                                                           
SageMath version 10.4.beta1, Release Date: 2024-03-31
Jack: sage % ./sage -tox -e rst -- ./src/sage                          
rst: commands[0] /Users/Jack/sage/sage/src> flake8 --select=RST sage
sage/algebras/quantum_groups/quantum_group_gap.py:8:1: RST304 Unknown interpreted text role "gap_package".
sage/combinat/designs/incidence_structures.py:1812:1: RST304 Unknown interpreted text role "gap_package".
sage/groups/cubic_braid.py:272:1: RST304 Unknown interpreted text role "gap".
sage/groups/generic.py:1626:1: RST304 Unknown interpreted text role "gap".
sage/groups/matrix_gps/finitely_generated_gap.py:225:1: RST304 Unknown interpreted text role "gap".
rst: exit 1 (54.79 seconds) /Users/Jack/sage/sage/src> flake8 --select=RST sage pid=9808
  rst: FAIL code 1 (54.86=setup[0.07]+cmd[54.79] seconds)
  evaluation failed :( (55.02 seconds)
```

### Expected Behavior

All listing should pass on the develop branch

### Actual Behavior

Linting has failures on the develop branch

### Environment

```markdown
- **OS**: MacOS 14.3.1
- **Sage Version**: 10.4.beta1
```

### Checklist

- [X] I have searched the existing issues for a bug report that matches the one I want to file, without success.
- [X] I have read the documentation and troubleshoot guide

**Comment by GiacomoPope** [comment]
Oh is this an issue because the linter is being run before the new docs have been built? Maybe patience is the solution here.

**Comment by GiacomoPope** [comment]
Examples of failing PR:

https://github.com/sagemath/sage/pull/37441
https://github.com/sagemath/sage/pull/37513
https://github.com/sagemath/sage/pull/37615

**Comment by mkoeppe** [comment]
Thanks. I'm preparing a fix.
