### ISSUE TITLE
PyPy and AppImage

### ISSUE THREAD

**Issue by gmou3** [sagemath/sage#37741]
A couple of ideas:
- Would support for the PyPy python implementation be advantageous for sage? (It appears not to be currently supported.)
- Any thoughts on packaging sage as an AppImage?

**Comment by mkoeppe** [comment]
Yes, Sage only supports CPython.

Porting efforts to other implementations and platforms could start with the modularized distributions sagemath-objects, sagemath-categories etc.

**Comment by culler** [comment]
@gmou3: There is now a beta version of a SageMath AppImage available at:
[https://github.com/3-manifolds/sage_appimage/releases](https://github.com/3-manifolds/sage_appimage/releases)
