### ISSUE TITLE
g_algebra doesn't support most relations for free algebras

### ISSUE THREAD

**Issue by jacksonwalters** [sagemath/sage#37780]
### Problem Description

The only relations that seem to work are the carefully constructed examples. For instance, if I want to enforce the relation x^2 = 1, I get the following value error:
```

A.<x,y> = FreeAlgebra(GF(3), 2)
P.<x,y> = A.g_algebra(relations={x^2:A(1)},order = 'lex', check=False)

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
Cell In[10], line 2
      1 A = FreeAlgebra(GF(Integer(3)), Integer(2), names=('x', 'y',)); (x, y,) = A._first_ngens(2)
----> 2 P = A.g_algebra(relations={x**Integer(2):A(Integer(1))},order = 'lex', check=False, names=('x', 'y',)); (x, y,) = P._first_ngens(2)

File /private/var/tmp/sage-10.3-current/local/var/lib/sage/venv-python3.11.1/lib/python3.11/site-packages/sage/algebras/free_algebra.py:953, in FreeAlgebra_generic.g_algebra(self, relations, names, order, check)
    951 assert isinstance(to_commute, FreeAlgebraElement), to_commute
    952 assert isinstance(commuted, FreeAlgebraElement), commuted
--> 953 (v1, e1), (v2, e2) = next(iter(to_commute))[0]
    954 assert e1 == 1
    955 assert e2 == 1

ValueError: not enough values to unpack (expected 2, got 1)

```
### Proposed Solution

Someone who understands free algebras could re-implement the relations properly.

### Alternatives Considered

I don't know of any alternatives for creating an algebra with relations.

### Additional Information

SageMath 10.3, M1 2020, Sonoma 14.4.1

### Is there an existing issue for this?

- [X] I have searched the existing issues for a bug report that matches the one I want to file, without success.

**Comment by fchapoton** [comment]
This is supposed to work only for relations that are "swapping variables into correct order + lower terms". Your example does not fit this definition. 

Read https://www.singular.uni-kl.de/Manual/4-0-3/sing_534.htm

**Comment by jacksonwalters** [comment]
Oh, I see. I should've read about G-algebras. 

I believe I have implemented what I want, Laurent polynomials in non-commutative variables with relations, by using `GroupAlgebra(G,R)` where `G` is a quotient of a free group, and `R` is a field.

```
#a short presentation for S_n
#{x,y|x^2 = y^n = (xy)^{n−1} = 1, (xy^{−1}xy)^3 = 1, (xy^{−j}xy^j)^2 = 1 for 2 \le j \le ⌊n/2⌋}
n=4
F.<a,b> = FreeGroup()
G = F / ([a^2, b^n, (a*b)^(n-1), (a*b^(-1)*a*b)^3] + [(a*b^(-j)*a*b^j)^2 for j in range(2,floor(n/2)+1)])
assert G.is_isomorphic(SymmetricGroup(n))
#can use free group algebra corresponding to g
R = GF(3)
FGA = GroupAlgebra(G, R); FGA
Algebra of Finitely presented group < a, b | a^2, b^4, (a*b)^3, (a*b^-1*a*b)^3, (a*b^-2*a*b^2)^2 > over Finite Field of size 3
```
