### ISSUE TITLE
Computing log(int(0), 2) takes a long time (same as #29164 but with python int)

### ISSUE THREAD

**Issue by cyrilbouvier** [sagemath/sage#37794]
### Steps To Reproduce

```py
log(int(0), 2)
```

### Expected Behavior

```py
-Infinity
```

### Actual Behavior

Sage runs for a long time and cannot be killed with Ctrl+C (I need to call `kill <sage pid> <python3 pid>`  to stop everything)

### Additional Information

It looks like a duplicate of #29164 but there is a subtle difference: In #29164 the 0 is a Sage integer, here the 0 is a python integer.

Variants that work:
```py
sage: log(ZZ(0), 2)
-Infinity
sage: log(0.0, 2)
-infinity
sage: log(ZZ(0))
-Infinity
sage: log(int(0))
-Infinity
```

### Environment

```markdown
- **OS**: Debian
- **Sage Version**: 10.3
```

### Checklist

- [X] I have searched the existing issues for a bug report that matches the one I want to file, without success.
- [X] I have read the documentation and troubleshoot guide

**Comment by user202729** [comment]
Sage's version of GiNaC has diverged from upstream development a long time ago (see README.md in the ginac folder), so we should just fix it in Sage repository.
