### ISSUE TITLE
Group algebra of free group quotient does not simplify upon multiplication

### ISSUE THREAD

**Issue by jacksonwalters** [sagemath/sage#37815]
### Problem Description

Suppose we create a group algebra using a quotient of a free group:

```
#a short presentation for S_n
#{x,y|x^2 = y^n = (xy)^{n−1} = 1, (xy^{−1}xy)^3 = 1, (xy^{−j}xy^j)^2 = 1 for 2 \le j \le ⌊n/2⌋}
n=4
F.<a,b> = FreeGroup()
G = F / ([a^2, b^n, (a*b)^(n-1), (a*b^(-1)*a*b)^3] + [(a*b^(-j)*a*b^j)^2 for j in range(2,floor(n/2)+1)])
print(G.is_isomorphic(SymmetricGroup(n)))
True
print(G.structure_description())
'S4'
#can use free group algebra corresponding to G
R = GF(3)
FGA = GroupAlgebra(G, R); FGA
```

When we multiply elements in `FGA` they are not reduced according to the group relations.

```
poly3 = 1 + (a^-1*b^-2)^2 + b^-2 + a^-1*b^-2*a^-1
poly3*poly3
1 + (a^-1*b^-2*a^-1)^2 + b^-4 + (a^-1*b^-2)^4 + (a^-1*b^-2)^2 + 2*b^-2 + 2*(a^-1*b^-2*a^-1)^2*b^-2 + 2*a^-1*b^-2*a^-1 + 2*(b^-2*a^-1)^2*b^-2
```

### Proposed Solution

Use reduce. 

```
#function to reduce elements of the free group algebra quotient using group relations
def reduce(v):
    k = G.rewriting_system()
    k.make_confluent()
    return sum(FGA(item[1])*FGA(k.reduce(item[0])) for item in list(v))

reduce(poly3)
1 + a*b*a*b^-1*a*b + b^2 + a*b^2*a
#the polynomials are still idempotent even when written in terms of generators and relations
reduce(poly3) == reduce(poly3*poly3)
True
```

### Alternatives Considered

There's really no alternative to reducing expressions in free group elements by relations.

### Is there an existing issue for this?

- [X] I have searched the existing issues for a bug report that matches the one I want to file, without success.

**Comment by tscrim** [comment]
This is actually an undecidable problem in general. Generically, a group does not have a confluent rewriting system, and it cannot know it has one ahead of time (much less that it can be prohibitively expensive to compute). We could possibly do something for finitely presented groups we know are finite, but in that case you are almost certainly better off just working with the group algebra of the finite group (likely realized in another way, such as a permutation group).

**Comment by jacksonwalters** [comment]
Ah, right. As you say, could be nice in cases where the confluent rewriting system exists. In my case, I thought I would get some mileage viewing things in terms of a free algebra quotient. However, Groebner bases (also undecidable in general) don't reveal any information, so I think it's going to make more sense just to study the quotient rings corresponding to 1-e_i, where e_i are idempotents, directly.
