### ISSUE TITLE
>  about #37300 - justification

### ISSUE THREAD

**Issue by dimpase** [sagemath/sage#37811]
Currently, @tobiasdiez [is blocked](https://github.com/sagemath/sage/pull/37796#issuecomment-2059537868) from posting on @mkoeppe's PRs. I understand that that's why he could not explain his action here. I think it would have been helpful to propose (or at least explain) this label change on sage-devel in that case.

_Originally posted by @saraedum in https://github.com/sagemath/sage/issues/37300#issuecomment-2059546878_

**Comment by dimpase** [comment]
manipulating labels is the only way for blocked on GH users to show what
they think about the PR.
I've requested https://github.com/sagemath/sage/pull/37300

to be -1d on my behalf while it was discussed on sage-devel

I trust that @tobiasdiez wants to -1 it too, as this is the way he reacted during the discussion of the topic on sage-devel

**Comment by dimpase** [comment]
@jplab - me as well as @tobiasdiez are blocked here on GH by @mkoeppe, preventing us  from commenting or reviewing blocker's PRs.

**Comment by saraedum** [comment]
I think you need to explicitly tell somebody to record a -1 for you for it to happen. This could be the Code of Conduct Committee. But if you know of somebody else who can do that for you, that might be a better solution since we are already quite busy with the regular Committee work.

**Comment by dimpase** [comment]
@saraedum I think it should be on the blocker to arrange that the blocked ones can exercise their rights to vote, not the other way around.

As well, the one putting up positive review label should list the votes, right? This has not happened.

From now on, I am willing to carpet- `-1` every single PR by the blocker.
 @tobiasdiez would you like to join this action too?

By the way, as I explained on the issue related to CoCC election, deciding a range of PRs by whatever majority voting is prone to completely ignoring the minority.
@kcrisman recalls this for sure.

**Comment by saraedum** [comment]
> @saraedum I think it should be on the blocker to arrange that the blocked ones can exercise their rights to vote, not the other way around.

I understand that you can exercise your right to vote as described above.

> As well, the one putting up positive review label should list the votes, right? This has not happened.

The PR is not disputed because a vote was called on sage-devel. So, there's no need to list votes I believe.

> From now on, I am willing to carpet- `-1` every single PR by the blocker. @tobiasdiez would you like to join this action too?

I would very strongly advise against such tactics. I am not speaking for the Code of Conduct Committee here but I don't think the community as a whole would tolerate such tactics.

**Comment by saraedum** [comment]
I believe you gave a justification for #37300 here. I would prefer not to establish this "issue" as a parallel channel to sage-devel and sage-conduct. If you want to change how things are done, feel free to reach out to the committee on sage-conduct or propose something on sage-devel. I don't see why precisely the people who have been tagged here should be the ones discussing this issue.

Feel free to reopen if you think that more needs to be added about the original topic of the issue that only relates to the people subscribed here.

**Comment by dimpase** [comment]
> > From now on, I am willing to carpet- `-1` every single PR by the blocker. @tobiasdiez would you like to join this action too?
> 
> I would very strongly advise against such tactics. I am not speaking for the Code of Conduct Committee here but I don't think the community as a whole would tolerate such tactics.

If the community tolerates @mkoeppe blocking people, it would tolerate a pushback against these blocks, no?

What is the use of your regular CoCC meetings? You cannot dare call out a developer for pushing people out of the project?
Fine, I'll be packing up then.
