### ISSUE TITLE
FreeAlgebra doesn't reduce using ideal relations

### ISSUE THREAD

**Issue by jacksonwalters** [sagemath/sage#37852]
### Steps To Reproduce

For the free algebra, the quotient by an ideal should result in relations in the quotient ring.

### Expected Behavior

For a polynomial ring, we get the expected relation.

```
R.<x,y> = PolynomialRing(QQ, 2)
S.<a,b> = R.quotient(x^2 + y^2)
S.gens()
(a, b)
a^2+b^2 == 0
True
```

### Actual Behavior

For a free algebra, the variables in the quotient don't satisfy any relations.

```
R.<x,y> = FreeAlgebra(QQ, 2)
S.<a,b> = R.quotient(x^2 + y^2)
S.gens()
(a, b)
a^2+b^2 == 0
False
```

### Environment

```markdown
- **OS**: Mac M1 2020, Sonoma 14.4.1
- **Sage Version**: 10.3
```

### Checklist

- [X] I have searched the existing issues for a bug report that matches the one I want to file, without success.
- [X] I have read the documentation and troubleshoot guide

**Comment by tscrim** [comment]
The free algebra would need to compute a Gröbner basis, which is generally infinite (unlike for polynomial rings!). So the free algebra quotients (well, really generic quotients) do the safe thing, and only consider the representation given as there is no canonical form. You're basically wanting a solution to an undecidable problem, and ad-hoc methods aren't such a good way to implement things.
