### ISSUE TITLE
sage_numerical_backends_cplex package does not compile

### ISSUE THREAD

**Issue by maxale** [sagemath/sage#37875]
### Environment

```markdown
- **OS**: Ubuntu 22.04.4 LTS
- **Sage Version**: 10.3
```

### Config log

.

### Package logs

[sage_numerical_backends_cplex-9.0b12] Using cached file /usr/local/sage/sage/upstream/sage_numerical_backends_cplex-9.0b12.tar.gz
[sage_numerical_backends_cplex-9.0b12] sage_numerical_backends_cplex-9.0b12
[sage_numerical_backends_cplex-9.0b12] ====================================================
[sage_numerical_backends_cplex-9.0b12] Setting up build directory for sage_numerical_backends_cplex-9.0b12
[sage_numerical_backends_cplex-9.0b12] Finished extraction
[sage_numerical_backends_cplex-9.0b12] No patch files found in ../patches
[sage_numerical_backends_cplex-9.0b12] ****************************************************
[sage_numerical_backends_cplex-9.0b12] Host system:
[sage_numerical_backends_cplex-9.0b12] Linux tpt490s 5.15.0-102-generic #112-Ubuntu SMP Tue Mar 5 16:50:32 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux
[sage_numerical_backends_cplex-9.0b12] ****************************************************
[sage_numerical_backends_cplex-9.0b12] C compiler: gcc
[sage_numerical_backends_cplex-9.0b12] C compiler version:
[sage_numerical_backends_cplex-9.0b12] Using built-in specs.
[sage_numerical_backends_cplex-9.0b12] COLLECT_GCC=gcc
[sage_numerical_backends_cplex-9.0b12] COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/11/lto-wrapper
[sage_numerical_backends_cplex-9.0b12] OFFLOAD_TARGET_NAMES=nvptx-none:amdgcn-amdhsa
[sage_numerical_backends_cplex-9.0b12] OFFLOAD_TARGET_DEFAULT=1
[sage_numerical_backends_cplex-9.0b12] Target: x86_64-linux-gnu
[sage_numerical_backends_cplex-9.0b12] Configured with: ../src/configure -v --with-pkgversion='Ubuntu 11.4.0-1ubuntu1~22.04' --with-bugurl=file:///usr/share/doc/gcc-11/README.Bugs --enable-languages=c,ada,c++,go,brig,d,fortran,objc,obj-c++,m2 --prefix=/usr --with-gcc-major-version-only --program-suffix=-11 --program-prefix=x86_64-linux-gnu- --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --enable-bootstrap --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-vtable-verify --enable-plugin --enable-default-pie --with-system-zlib --enable-libphobos-checking=release --with-target-system-zlib=auto --enable-objc-gc=auto --enable-multiarch --disable-werror --enable-cet --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-offload-targets=nvptx-none=/build/gcc-11-XeT9lY/gcc-11-11.4.0/debian/tmp-nvptx/usr,amdgcn-amdhsa=/build/gcc-11-XeT9lY/gcc-11-11.4.0/debian/tmp-gcn/usr --without-cuda-driver --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu --with-build-config=bootstrap-lto-lean --enable-link-serialization=2
[sage_numerical_backends_cplex-9.0b12] Thread model: posix
[sage_numerical_backends_cplex-9.0b12] Supported LTO compression algorithms: zlib zstd
[sage_numerical_backends_cplex-9.0b12] gcc version 11.4.0 (Ubuntu 11.4.0-1ubuntu1~22.04) 
[sage_numerical_backends_cplex-9.0b12] ****************************************************
[sage_numerical_backends_cplex-9.0b12] Package 'sage_numerical_backends_cplex' is currently not installed
[sage_numerical_backends_cplex-9.0b12] No legacy uninstaller found for 'sage_numerical_backends_cplex'; nothing to do
[sage_numerical_backends_cplex-9.0b12] Installing sage_numerical_backends_cplex-9.0b12
[sage_numerical_backends_cplex-9.0b12] Looking in links: /usr/local/sage/sage/local/var/lib/sage/venv-python3.10/var/lib/sage/wheels
[sage_numerical_backends_cplex-9.0b12] Processing /usr/local/sage/sage/local/var/lib/sage/venv-python3.10/var/tmp/sage/build/sage_numerical_backends_cplex-9.0b12/src
[sage_numerical_backends_cplex-9.0b12]   Preparing metadata (setup.py): started
[sage_numerical_backends_cplex-9.0b12]   Running command python setup.py egg_info
[sage_numerical_backends_cplex-9.0b12]   Using cplex_include_directories=['/usr/local/CPLEX_Studio221/cplex/include/ilcplex'], libraries=['cplex2210'], library_dirs=['/usr/local/CPLEX_Studio221/cplex/bin/x86-64_linux']
[sage_numerical_backends_cplex-9.0b12]   Checking whether HAVE_SAGE_CPYTHON_STRING...
[sage_numerical_backends_cplex-9.0b12]   Checking whether HAVE_ADD_COL_UNTYPED_ARGS...
[sage_numerical_backends_cplex-9.0b12]   /usr/local/sage/sage/local/var/lib/sage/venv-python3.10/lib/python3.10/site-packages/Cython/Compiler/Main.py:381: FutureWarning: Cython directive 'language_level' not set, using '3str' for now (Py3). This has changed from earlier releases! File: /usr/local/sage/sage/local/var/lib/sage/venv-python3.10/var/tmp/sage/build/sage_numerical_backends_cplex-9.0b12/src/check_add_col_untyped_args.pyx
[sage_numerical_backends_cplex-9.0b12]     tree = Parsing.p_module(s, pxd, full_module_name)
[sage_numerical_backends_cplex-9.0b12]   Using compile_time_env: {'HAVE_SAGE_CPYTHON_STRING': True, 'HAVE_ADD_COL_UNTYPED_ARGS': True}
[sage_numerical_backends_cplex-9.0b12]   /usr/local/sage/sage/local/var/lib/sage/venv-python3.10/lib/python3.10/site-packages/Cython/Compiler/Main.py:381: FutureWarning: Cython directive 'language_level' not set, using '3str' for now (Py3). This has changed from earlier releases! File: /usr/local/sage/sage/local/var/lib/sage/venv-python3.10/var/tmp/sage/build/sage_numerical_backends_cplex-9.0b12/src/sage_numerical_backends_cplex/cplex_backend.pxd
[sage_numerical_backends_cplex-9.0b12]     tree = Parsing.p_module(s, pxd, full_module_name)
[sage_numerical_backends_cplex-9.0b12] 
[sage_numerical_backends_cplex-9.0b12]   Error compiling Cython file:
[sage_numerical_backends_cplex-9.0b12]   ------------------------------------------------------------
[sage_numerical_backends_cplex-9.0b12]   ...
[sage_numerical_backends_cplex-9.0b12]        int CPXsetlogfilename(c_cpxenv * env, char * filename, char * mode)
[sage_numerical_backends_cplex-9.0b12] 
[sage_numerical_backends_cplex-9.0b12]        # CONSTANTS
[sage_numerical_backends_cplex-9.0b12]        int CPX_ON = 1
[sage_numerical_backends_cplex-9.0b12]        int CPX_PARAM_SCRIND = 1035
[sage_numerical_backends_cplex-9.0b12]        int CPX_INFBOUND = 1.0E+20
[sage_numerical_backends_cplex-9.0b12]                           ^
[sage_numerical_backends_cplex-9.0b12]   ------------------------------------------------------------
[sage_numerical_backends_cplex-9.0b12] 
[sage_numerical_backends_cplex-9.0b12]   sage_numerical_backends_cplex/cplex_backend.pxd:222:24: Cannot assign type 'double' to 'int'
[sage_numerical_backends_cplex-9.0b12]   Traceback (most recent call last):
[sage_numerical_backends_cplex-9.0b12]     File "<string>", line 2, in <module>
[sage_numerical_backends_cplex-9.0b12]     File "<pip-setuptools-caller>", line 34, in <module>
[sage_numerical_backends_cplex-9.0b12]     File "/usr/local/sage/sage/local/var/lib/sage/venv-python3.10/var/tmp/sage/build/sage_numerical_backends_cplex-9.0b12/src/setup.py", line 123, in <module>
[sage_numerical_backends_cplex-9.0b12]       ext_modules = cythonize(ext_modules, include_path=sys.path,
[sage_numerical_backends_cplex-9.0b12]     File "/usr/local/sage/sage/local/var/lib/sage/venv-python3.10/lib/python3.10/site-packages/Cython/Build/Dependencies.py", line 1154, in cythonize
[sage_numerical_backends_cplex-9.0b12]       cythonize_one(*args)
[sage_numerical_backends_cplex-9.0b12]     File "/usr/local/sage/sage/local/var/lib/sage/venv-python3.10/lib/python3.10/site-packages/Cython/Build/Dependencies.py", line 1321, in cythonize_one
[sage_numerical_backends_cplex-9.0b12]       raise CompileError(None, pyx_file)
[sage_numerical_backends_cplex-9.0b12]   Cython.Compiler.Errors.CompileError: sage_numerical_backends_cplex/cplex_backend.pyx
[sage_numerical_backends_cplex-9.0b12]   Compiling sage_numerical_backends_cplex/cplex_backend.pyx because it changed.
[sage_numerical_backends_cplex-9.0b12]   [1/1] Cythonizing sage_numerical_backends_cplex/cplex_backend.pyx
[sage_numerical_backends_cplex-9.0b12]   error: subprocess-exited-with-error
[sage_numerical_backends_cplex-9.0b12]   
[sage_numerical_backends_cplex-9.0b12]   × python setup.py egg_info did not run successfully.
[sage_numerical_backends_cplex-9.0b12]   │ exit code: 1
[sage_numerical_backends_cplex-9.0b12]   ╰─> See above for output.
[sage_numerical_backends_cplex-9.0b12]   
[sage_numerical_backends_cplex-9.0b12]   note: This error originates from a subprocess, and is likely not a problem with pip.
[sage_numerical_backends_cplex-9.0b12]   full command: /usr/local/sage/sage/local/var/lib/sage/venv-python3.10/bin/python3 -c '
[sage_numerical_backends_cplex-9.0b12]   exec(compile('"'"''"'"''"'"'
[sage_numerical_backends_cplex-9.0b12]   # This is <pip-setuptools-caller> -- a caller that pip uses to run setup.py
[sage_numerical_backends_cplex-9.0b12]   #
[sage_numerical_backends_cplex-9.0b12]   # - It imports setuptools before invoking setup.py, to enable projects that directly
[sage_numerical_backends_cplex-9.0b12]   #   import from `distutils.core` to work with newer packaging standards.
[sage_numerical_backends_cplex-9.0b12]   # - It provides a clear error message when setuptools is not installed.
[sage_numerical_backends_cplex-9.0b12]   # - It sets `sys.argv[0]` to the underlying `setup.py`, when invoking `setup.py` so
[sage_numerical_backends_cplex-9.0b12]   #   setuptools doesn'"'"'t think the script is `-c`. This avoids the following warning:
[sage_numerical_backends_cplex-9.0b12]   #     manifest_maker: standard file '"'"'-c'"'"' not found".
[sage_numerical_backends_cplex-9.0b12]   # - It generates a shim setup.py, for handling setup.cfg-only projects.
[sage_numerical_backends_cplex-9.0b12]   import os, sys, tokenize
[sage_numerical_backends_cplex-9.0b12]   
[sage_numerical_backends_cplex-9.0b12]   try:
[sage_numerical_backends_cplex-9.0b12]       import setuptools
[sage_numerical_backends_cplex-9.0b12]   except ImportError as error:
[sage_numerical_backends_cplex-9.0b12]       print(
[sage_numerical_backends_cplex-9.0b12]           "ERROR: Can not execute `setup.py` since setuptools is not available in "
[sage_numerical_backends_cplex-9.0b12]           "the build environment.",
[sage_numerical_backends_cplex-9.0b12]           file=sys.stderr,
[sage_numerical_backends_cplex-9.0b12]       )
[sage_numerical_backends_cplex-9.0b12]       sys.exit(1)
[sage_numerical_backends_cplex-9.0b12]   
[sage_numerical_backends_cplex-9.0b12]   __file__ = %r
[sage_numerical_backends_cplex-9.0b12]   sys.argv[0] = __file__
[sage_numerical_backends_cplex-9.0b12]   
[sage_numerical_backends_cplex-9.0b12]   if os.path.exists(__file__):
[sage_numerical_backends_cplex-9.0b12]       filename = __file__
[sage_numerical_backends_cplex-9.0b12]       with tokenize.open(__file__) as f:
[sage_numerical_backends_cplex-9.0b12]           setup_py_code = f.read()
[sage_numerical_backends_cplex-9.0b12]   else:
[sage_numerical_backends_cplex-9.0b12]       filename = "<auto-generated setuptools caller>"
[sage_numerical_backends_cplex-9.0b12]       setup_py_code = "from setuptools import setup; setup()"
[sage_numerical_backends_cplex-9.0b12]   
[sage_numerical_backends_cplex-9.0b12]   exec(compile(setup_py_code, filename, "exec"))
[sage_numerical_backends_cplex-9.0b12]   '"'"''"'"''"'"' % ('"'"'/usr/local/sage/sage/local/var/lib/sage/venv-python3.10/var/tmp/sage/build/sage_numerical_backends_cplex-9.0b12/src/setup.py'"'"',), "<pip-setuptools-caller>", "exec"))' --no-user-cfg egg_info --egg-base /tmp/pip-pip-egg-info-gvqd87i_
[sage_numerical_backends_cplex-9.0b12]   cwd: /usr/local/sage/sage/local/var/lib/sage/venv-python3.10/var/tmp/sage/build/sage_numerical_backends_cplex-9.0b12/src/
[sage_numerical_backends_cplex-9.0b12]   Preparing metadata (setup.py): finished with status 'error'
[sage_numerical_backends_cplex-9.0b12] error: metadata-generation-failed
[sage_numerical_backends_cplex-9.0b12] 
[sage_numerical_backends_cplex-9.0b12] × Encountered error while generating package metadata.
[sage_numerical_backends_cplex-9.0b12] ╰─> See above for output.
[sage_numerical_backends_cplex-9.0b12] 
[sage_numerical_backends_cplex-9.0b12] note: This is an issue with the package mentioned above, not pip.
[sage_numerical_backends_cplex-9.0b12] hint: See above for details.
[sage_numerical_backends_cplex-9.0b12] Warning: building with "python3 -m pip wheel --wheel-dir=dist --verbose --no-deps --no-index --isolated --ignore-requires-python --find-links=/usr/local/sage/sage/local/var/lib/sage/venv-python3.10/var/lib/sage/wheels" failed.
[sage_numerical_backends_cplex-9.0b12] Retrying with "python3 -m pip wheel --wheel-dir=dist --verbose --no-deps --no-index --isolated --ignore-requires-python --no-build-isolation --no-binary :all:".
[sage_numerical_backends_cplex-9.0b12] Processing /usr/local/sage/sage/local/var/lib/sage/venv-python3.10/var/tmp/sage/build/sage_numerical_backends_cplex-9.0b12/src
[sage_numerical_backends_cplex-9.0b12]   Preparing metadata (setup.py): started
[sage_numerical_backends_cplex-9.0b12]   Running command python setup.py egg_info
[sage_numerical_backends_cplex-9.0b12]   Using cplex_include_directories=['/usr/local/CPLEX_Studio221/cplex/include/ilcplex'], libraries=['cplex2210'], library_dirs=['/usr/local/CPLEX_Studio221/cplex/bin/x86-64_linux']
[sage_numerical_backends_cplex-9.0b12]   Checking whether HAVE_SAGE_CPYTHON_STRING...
[sage_numerical_backends_cplex-9.0b12]   Checking whether HAVE_ADD_COL_UNTYPED_ARGS...
[sage_numerical_backends_cplex-9.0b12]   Using compile_time_env: {'HAVE_SAGE_CPYTHON_STRING': True, 'HAVE_ADD_COL_UNTYPED_ARGS': True}
[sage_numerical_backends_cplex-9.0b12]   /usr/local/sage/sage/local/var/lib/sage/venv-python3.10/lib/python3.10/site-packages/Cython/Compiler/Main.py:381: FutureWarning: Cython directive 'language_level' not set, using '3str' for now (Py3). This has changed from earlier releases! File: /usr/local/sage/sage/local/var/lib/sage/venv-python3.10/var/tmp/sage/build/sage_numerical_backends_cplex-9.0b12/src/sage_numerical_backends_cplex/cplex_backend.pxd
[sage_numerical_backends_cplex-9.0b12]     tree = Parsing.p_module(s, pxd, full_module_name)
[sage_numerical_backends_cplex-9.0b12] 
[sage_numerical_backends_cplex-9.0b12]   Error compiling Cython file:
[sage_numerical_backends_cplex-9.0b12]   ------------------------------------------------------------
[sage_numerical_backends_cplex-9.0b12]   ...
[sage_numerical_backends_cplex-9.0b12]        int CPXsetlogfilename(c_cpxenv * env, char * filename, char * mode)
[sage_numerical_backends_cplex-9.0b12] 
[sage_numerical_backends_cplex-9.0b12]        # CONSTANTS
[sage_numerical_backends_cplex-9.0b12]        int CPX_ON = 1
[sage_numerical_backends_cplex-9.0b12]        int CPX_PARAM_SCRIND = 1035
[sage_numerical_backends_cplex-9.0b12]        int CPX_INFBOUND = 1.0E+20
[sage_numerical_backends_cplex-9.0b12]                           ^
[sage_numerical_backends_cplex-9.0b12]   ------------------------------------------------------------
[sage_numerical_backends_cplex-9.0b12] 
[sage_numerical_backends_cplex-9.0b12]   sage_numerical_backends_cplex/cplex_backend.pxd:222:24: Cannot assign type 'double' to 'int'
[sage_numerical_backends_cplex-9.0b12]   Traceback (most recent call last):
[sage_numerical_backends_cplex-9.0b12]     File "<string>", line 2, in <module>
[sage_numerical_backends_cplex-9.0b12]     File "<pip-setuptools-caller>", line 34, in <module>
[sage_numerical_backends_cplex-9.0b12]     File "/usr/local/sage/sage/local/var/lib/sage/venv-python3.10/var/tmp/sage/build/sage_numerical_backends_cplex-9.0b12/src/setup.py", line 123, in <module>
[sage_numerical_backends_cplex-9.0b12]       ext_modules = cythonize(ext_modules, include_path=sys.path,
[sage_numerical_backends_cplex-9.0b12]     File "/usr/local/sage/sage/local/var/lib/sage/venv-python3.10/lib/python3.10/site-packages/Cython/Build/Dependencies.py", line 1154, in cythonize
[sage_numerical_backends_cplex-9.0b12]       cythonize_one(*args)
[sage_numerical_backends_cplex-9.0b12]     File "/usr/local/sage/sage/local/var/lib/sage/venv-python3.10/lib/python3.10/site-packages/Cython/Build/Dependencies.py", line 1321, in cythonize_one
[sage_numerical_backends_cplex-9.0b12]       raise CompileError(None, pyx_file)
[sage_numerical_backends_cplex-9.0b12]   Cython.Compiler.Errors.CompileError: sage_numerical_backends_cplex/cplex_backend.pyx
[sage_numerical_backends_cplex-9.0b12]   Compiling sage_numerical_backends_cplex/cplex_backend.pyx because it changed.
[sage_numerical_backends_cplex-9.0b12]   [1/1] Cythonizing sage_numerical_backends_cplex/cplex_backend.pyx
[sage_numerical_backends_cplex-9.0b12]   error: subprocess-exited-with-error
[sage_numerical_backends_cplex-9.0b12]   
[sage_numerical_backends_cplex-9.0b12]   × python setup.py egg_info did not run successfully.
[sage_numerical_backends_cplex-9.0b12]   │ exit code: 1
[sage_numerical_backends_cplex-9.0b12]   ╰─> See above for output.
[sage_numerical_backends_cplex-9.0b12]   
[sage_numerical_backends_cplex-9.0b12]   note: This error originates from a subprocess, and is likely not a problem with pip.
[sage_numerical_backends_cplex-9.0b12]   full command: /usr/local/sage/sage/local/var/lib/sage/venv-python3.10/bin/python3 -c '
[sage_numerical_backends_cplex-9.0b12]   exec(compile('"'"''"'"''"'"'
[sage_numerical_backends_cplex-9.0b12]   # This is <pip-setuptools-caller> -- a caller that pip uses to run setup.py
[sage_numerical_backends_cplex-9.0b12]   #
[sage_numerical_backends_cplex-9.0b12]   # - It imports setuptools before invoking setup.py, to enable projects that directly
[sage_numerical_backends_cplex-9.0b12]   #   import from `distutils.core` to work with newer packaging standards.
[sage_numerical_backends_cplex-9.0b12]   # - It provides a clear error message when setuptools is not installed.
[sage_numerical_backends_cplex-9.0b12]   # - It sets `sys.argv[0]` to the underlying `setup.py`, when invoking `setup.py` so
[sage_numerical_backends_cplex-9.0b12]   #   setuptools doesn'"'"'t think the script is `-c`. This avoids the following warning:
[sage_numerical_backends_cplex-9.0b12]   #     manifest_maker: standard file '"'"'-c'"'"' not found".
[sage_numerical_backends_cplex-9.0b12]   # - It generates a shim setup.py, for handling setup.cfg-only projects.
[sage_numerical_backends_cplex-9.0b12]   import os, sys, tokenize
[sage_numerical_backends_cplex-9.0b12]   
[sage_numerical_backends_cplex-9.0b12]   try:
[sage_numerical_backends_cplex-9.0b12]       import setuptools
[sage_numerical_backends_cplex-9.0b12]   except ImportError as error:
[sage_numerical_backends_cplex-9.0b12]       print(
[sage_numerical_backends_cplex-9.0b12]           "ERROR: Can not execute `setup.py` since setuptools is not available in "
[sage_numerical_backends_cplex-9.0b12]           "the build environment.",
[sage_numerical_backends_cplex-9.0b12]           file=sys.stderr,
[sage_numerical_backends_cplex-9.0b12]       )
[sage_numerical_backends_cplex-9.0b12]       sys.exit(1)
[sage_numerical_backends_cplex-9.0b12]   
[sage_numerical_backends_cplex-9.0b12]   __file__ = %r
[sage_numerical_backends_cplex-9.0b12]   sys.argv[0] = __file__
[sage_numerical_backends_cplex-9.0b12]   
[sage_numerical_backends_cplex-9.0b12]   if os.path.exists(__file__):
[sage_numerical_backends_cplex-9.0b12]       filename = __file__
[sage_numerical_backends_cplex-9.0b12]       with tokenize.open(__file__) as f:
[sage_numerical_backends_cplex-9.0b12]           setup_py_code = f.read()
[sage_numerical_backends_cplex-9.0b12]   else:
[sage_numerical_backends_cplex-9.0b12]       filename = "<auto-generated setuptools caller>"
[sage_numerical_backends_cplex-9.0b12]       setup_py_code = "from setuptools import setup; setup()"
[sage_numerical_backends_cplex-9.0b12]   
[sage_numerical_backends_cplex-9.0b12]   exec(compile(setup_py_code, filename, "exec"))
[sage_numerical_backends_cplex-9.0b12]   '"'"''"'"''"'"' % ('"'"'/usr/local/sage/sage/local/var/lib/sage/venv-python3.10/var/tmp/sage/build/sage_numerical_backends_cplex-9.0b12/src/setup.py'"'"',), "<pip-setuptools-caller>", "exec"))' --no-user-cfg egg_info --egg-base /tmp/pip-pip-egg-info-g8ixvxgk
[sage_numerical_backends_cplex-9.0b12]   cwd: /usr/local/sage/sage/local/var/lib/sage/venv-python3.10/var/tmp/sage/build/sage_numerical_backends_cplex-9.0b12/src/
[sage_numerical_backends_cplex-9.0b12]   Preparing metadata (setup.py): finished with status 'error'
[sage_numerical_backends_cplex-9.0b12] error: metadata-generation-failed
[sage_numerical_backends_cplex-9.0b12] 
[sage_numerical_backends_cplex-9.0b12] × Encountered error while generating package metadata.
[sage_numerical_backends_cplex-9.0b12] ╰─> See above for output.
[sage_numerical_backends_cplex-9.0b12] 
[sage_numerical_backends_cplex-9.0b12] note: This is an issue with the package mentioned above, not pip.
[sage_numerical_backends_cplex-9.0b12] hint: See above for details.
[sage_numerical_backends_cplex-9.0b12] *******************************************************************************************************************************************************************************************************************
[sage_numerical_backends_cplex-9.0b12] Error building a wheel for sage_numerical_backends_cplex-9.0b12
[sage_numerical_backends_cplex-9.0b12] *******************************************************************************************************************************************************************************************************************
[sage_numerical_backends_cplex-9.0b12] 
[sage_numerical_backends_cplex-9.0b12] real	0m3.213s
[sage_numerical_backends_cplex-9.0b12] user	0m2.891s
[sage_numerical_backends_cplex-9.0b12] sys	0m0.255s
[sage_numerical_backends_cplex-9.0b12] ************************************************************************
[sage_numerical_backends_cplex-9.0b12] Error installing package sage_numerical_backends_cplex-9.0b12
[sage_numerical_backends_cplex-9.0b12] ************************************************************************
[sage_numerical_backends_cplex-9.0b12] Please email sage-devel (http://groups.google.com/group/sage-devel)
[sage_numerical_backends_cplex-9.0b12] explaining the problem and including the log files
[sage_numerical_backends_cplex-9.0b12]   /usr/local/sage/sage/logs/pkgs/sage_numerical_backends_cplex-9.0b12.log
[sage_numerical_backends_cplex-9.0b12] and
[sage_numerical_backends_cplex-9.0b12]   /usr/local/sage/sage/config.log
[sage_numerical_backends_cplex-9.0b12] Describe your computer, operating system, etc.
[sage_numerical_backends_cplex-9.0b12] If you want to try to fix the problem yourself, *don't* just cd to
[sage_numerical_backends_cplex-9.0b12] /usr/local/sage/sage/local/var/lib/sage/venv-python3.10/var/tmp/sage/build/sage_numerical_backends_cplex-9.0b12 and type 'make' or whatever is appropriate.
[sage_numerical_backends_cplex-9.0b12] Instead, the following commands setup all environment variables
[sage_numerical_backends_cplex-9.0b12] correctly and load a subshell for you to debug the error:
[sage_numerical_backends_cplex-9.0b12]   (cd '/usr/local/sage/sage/local/var/lib/sage/venv-python3.10/var/tmp/sage/build/sage_numerical_backends_cplex-9.0b12' && '/usr/local/sage/sage/sage' --buildsh)
[sage_numerical_backends_cplex-9.0b12] When you are done debugging, you can type "exit" to leave the subshell.
[sage_numerical_backends_cplex-9.0b12] ************************************************************************

### Additional Information

It looks like the package was not updated for quite a while.

### Checklist

- [X] I have searched the existing issues for a bug report that matches the one I want to file, without success.
- [X] I have read the documentation and troubleshoot guide

**Comment by dcoudert** [comment]
Same issue on macOS 12.7.4 and cplex 2211

**Comment by mkoeppe** [comment]
I've pushed a tentative fix to https://github.com/sagemath/sage-numerical-backends-cplex

**Comment by mkoeppe** [comment]
Package update in #38319.
