### ISSUE TITLE
Wrong order of finite matrix groups

### ISSUE THREAD

**Issue by alexander-betts** [sagemath/sage#37934]
### Steps To Reproduce

On Sage 10.3 running in CoCalc, run
```
sage: GL(2,Integers(4)).order()
180
sage: GL(2,Integers(1)).order()
0
```

### Expected Behavior

```
sage: GL(2,Integers(4)).order()
96
sage: GL(2,Integers(1)).order()
1
```
First one works in sage version 10.2, second one returns recursion error.

### Actual Behavior

See above. Seems to be computing GL(2,Integers(q)).order() as (q-1)^2*q*(q+1).

### Additional Information

Explanation of correct computation: [here](https://math.stackexchange.com/questions/3357934/order-of-gl2-mathbbz-4).

### Environment

```markdown
- **OS**: CoCalc
- **Sage Version**: 10.3
```

### Checklist

- [X] I have searched the existing issues for a bug report that matches the one I want to file, without success.
- [X] I have read the documentation and troubleshoot guide

**Comment by S17A05** [comment]
This seems to have been introduced by #36881, since the formula given there only works if the finite base ring is a field; previously (for your example) the method called GAP to compute the order instead.

**Comment by S17A05** [comment]
There is also some other funny stuff introduced by this change, such as
```
sage: GL(1, ZZ).order()
+Infinity
```
