### ISSUE TITLE
gfortran doesn't build on latest OS X + Xcode + Homebrew

### ISSUE THREAD

**Issue by jhpalmieri** [sagemath/sage#38006]
### Environment

```markdown
- **OS**: OS X 14.4.1
- **Sage Version**: 10.4.beta6
```

### Steps To Reproduce

`./configure --with-system-gfortran=no` followed by `make`.

### Config log

[config.log](https://github.com/sagemath/sage/files/15325568/config.log)

### Package logs

[gfortran-12.2.0.log](https://github.com/sagemath/sage/files/15325571/gfortran-12.2.0.log)

### Additional Information

With this plus #38002, it is now difficult to build Sage on OS X: any version of Sage earlier than 10.4.beta6 refuses to use the system's `gfortran` because it is too new, so it tries to build its own, which fails as noted here. With 10.4.beta6, the problem at #38002 arises, causing the build to fail.

### Checklist

- [X] I have searched the existing issues for a bug report that matches the one I want to file, without success.
- [X] I have read the documentation and troubleshoot guide

**Comment by mkoeppe** [comment]
Yes, I have also seen this in the CI macOS, for example https://github.com/sagemath/sage/actions/runs/9053838531/job/24873010721#step:10:2443

**Comment by mkoeppe** [comment]
I've opened #38007 for this (not ready yet)
