### ISSUE TITLE
`Arch Linux`: missing packages `libgiac` and `texlive-collection-luatex`

### ISSUE THREAD

**Issue by gmou3** [sagemath/sage#38015]
### Steps To Reproduce

In `Arch Linux`, run
```
sudo pacman -S libgiac
sudo pacman -S texlive-collection-luatex
```

### Expected Behavior

Normal package installation. These packages are recommended in the [Installation Guide](https://doc.sagemath.org/html/en/installation/source.html).

### Actual Behavior

```
error: target not found: libgiac
error: target not found: texlive-collection-luatex
```

### Additional Information

Sage installation proceeds smoothly if these packages are skipped.

### Environment

```markdown
- **OS**: Arch Linux x86_64
- **Sage Version**: 10.4.beta6
```

### Checklist

- [X] I have searched the existing issues for a bug report that matches the one I want to file, without success.
- [X] I have read the documentation and troubleshoot guide

**Comment by mkoeppe** [comment]
@antonio-rojas Can you help?

**Comment by antonio-rojas** [comment]
The documentations is wrong, those packages don't exist. In fact `texlive-collection-luatex` has never existed, Google says it's a Fedora package.

**Comment by n-WN** [comment]
~> sudo pacman -S libgiac
error: target not found: libgiac
~> sudo pacman -S maxima-fas                        1
error: target not found: maxima-fas
