### ISSUE TITLE
Ignore sequences with the keyword 'dead' when reading the OEIS database.

### ISSUE THREAD

**Issue by PeterLuschny** [sagemath/sage#38044]
### Expected Behavior

Ignore sequences with the keyword 'dead' when reading the OEIS database.

### Actual Behavior

The opposite of the expected behavior.

### Additional Information

For ten years, we have asked to ignore sequences containing the keyword 'dead' when reading the OEIS database.

https://github.com/sagemath/sage/issues/17330

There are purely internal reasons why these sequences are in OEIS. Such sequences are not intended to be passed on. You cannot signal this more drastically than with the keyword 'dead'. And Sage should respect that.

What happened? Not what we intended; requests ('oeis(...,n)') still issue these false, misleading, and duplicated sequences. Every user still has to filter out the crap themselves.

Worse still, videlec had also noticed this (Mar 23, 2016) and wrote: "The patch provided does not do what is in the description. Namely, the dead sequences are not ignored!"

Unfortunately, in the same breath, he suggests adding an 'explicit error message' (which mo271 later toned down to a run-time warning).

The consequence is the opposite of what was intended: these sequences are not only not ignored but are particularly highlighted.

Even after adding a filter in some applications (like in 
https://github.com/PeterLuschny/BinaryQuadraticForms/blob/main/BinaryQF.ipynb
which we gladly recommend as a test case) these RuntimeWarnings continue to appear

    site-packages/sage/databases/oeis.py:1152:RuntimeWarning: This sequence is dead: "A141158: Duplicate of A038872." warn('This sequence is dead: "{}: {}"'.format(self.id(), self.name()), RuntimeWarning)

although this is now entirely misleading. I would have to continue patching even the warnings.

This absurd situation could be remedied with a single line: when reading the database put in:

    if 'dead' in seq.keywords() : continue

Please insert this line and change the warning to: "Move along, Nothing to See Here."

### Environment

```markdown
* OS: WSL: Ubuntu-22.04
* Sage Version 9.8
```

### Checklist

- [X] I have searched the existing issues for a bug report that matches the one I want to file, without success.
- [X] I have read the documentation and troubleshoot guide

**Comment by fchapoton** [comment]
Please review #38045

**Comment by PeterLuschny** [comment]
Handled and resolved in #38045 .
