### ISSUE TITLE
Reduce usage of `sage.modules.misc.gram_schmidt` in lattice-related methods

### ISSUE THREAD

**Issue by TheBlupper** [sagemath/sage#38115]
### Problem Description

When dealing with lattice bases I often find myself using ones which have a lower rank than the number of rows. This is not an issue in most circumstances, but calculating Gram-Schmidt orthogonalization fails since the rows are linearly dependent.

`sage.matrix.matrix_integer_dense.Matrix_integer_dense.is_LLL_reduced` uses `sage.modules.misc.gram_schmidt` internally which is as mentioned prone to errors and is also very slow for large lattices.

`sage.modules.misc.gram_schmidt` is also used in `sage.modules.free_module_integer.IntegerLattice.approximate_closest_vector` which thus suffers from the same problems.

### Proposed Solution

For `is_LLL_reduced` I suggest we instead use fpylll's method `LLL.is_reduced`. It also accepts delta and eta arguments and does not complain when there are some linearly dependent vectors. It is also way faster in my experience.

For `approximate_closest_vector` I think implementing something akin to https://github.com/fplll/fpylll/blob/master/src/fpylll/algorithms/babai.py would be better (we don't want to use that one directly, I think it has issues with precision in the norm). I have not researched what the bounds of this algorithm is.

### Alternatives Considered

We could try to speed up `gram_schmidt` and make it more resilient, but I do not think it is worth the effort. #8143 also mentioned speeding up this function.

### Is there an existing issue for this?

- [X] I have searched the existing issues for a bug report that matches the one I want to file, without success.

**Comment by TheBlupper** [comment]
I would just like some opinions on whether this is something we want and if there would be problems with this, I can start work on the PR shortly.

**Comment by grhkm21** [comment]
sounds fine
