### ISSUE TITLE
Wrong result with tdlib for treewidth

### ISSUE THREAD

**Issue by dcoudert** [sagemath/sage#38159]
### Steps To Reproduce

```py
sage: from sage.graphs.graph_decompositions.tree_decomposition import width_of_tree_decomposition
sage: G = Graph('q~~|~q{mLhUo}?v?EO`{?h`?wo@w?fo?As_?lG?Cp_?Uc??{?_?|???Y_G?@gH??{?_?A{???Dp???Dk???Ax????l????Dh????Qo???GkG???_lG????Q_???I@p?G???uO????As????@@gH????FG??A??AW_??A??d????CG@w?C????PE?@????D@G?C???t?O??????')
sage: G.treewidth(algorithm='sage')
5
sage: G.treewidth(algorithm='tdlib')
6
sage: T = G.treewidth(algorithm='tdlib', certificate=True)
sage: width_of_tree_decomposition(G, T)
6
```

### Expected Behavior

```py
sage: G.treewidth(algorithm='tdlib')
5
```

### Actual Behavior

```py
sage: G.treewidth(algorithm='tdlib')
6
```

### Environment

```markdown
- **OS**: macOS 12.7.5 and fedora 39
- **Sage Version**: 10.4.beta8
```

### Checklist

- [X] I have searched the existing issues for a bug report that matches the one I want to file, without success.
- [X] I have read the documentation and troubleshoot guide

**Comment by dcoudert** [comment]
Another example with only 10 nodes
```
sage: G = Graph('I~~}vPlr_')
sage: G.treewidth(algorithm='sage')
5
sage: G.treewidth(algorithm='tdlib')
6
```

**Comment by dimpase** [comment]
@felix-salfelder

**Comment by felix-salfelder** [comment]
I'm not familiar with the compressed string representation. Please remind me how to convert `'I~~}vPlr_'` into a graph.

Which version of tdlib (aka treedec) is this, and which algorithm does it use?

Thanks

**Comment by mkoeppe** [comment]
See also:
- #30813

**Comment by felix-salfelder** [comment]
I figured that `'I~~}vPlr_'` has 10 vertices and 32 edges.

It looks like this in gr format

    p tw 10 32
    1 2
    1 3
    1 4
    1 5
    1 6
    1 7
    1 8
    1 10
    2 3
    2 4
    2 5
    2 6
    2 7
    2 8
    2 9
    2 10
    3 4
    3 5
    3 6
    3 8
    3 9
    4 5
    4 6
    4 7
    5 6
    5 7
    5 8
    5 9
    5 10
    6 9
    6 10
    7 10

With this input, `tdecomp --ex17` (develop branch) gives me

    s td 9 6 10
    b 1 1 5
    b 2 1 2 5
    b 3 1 2 5 7
    b 4 1 2 4 5 7
    b 5 1 2 4 5 7 10
    b 6 1 2 4 5 6 10
    b 7 1 2 3 4 5 6
    b 8 1 2 3 5 8
    b 9 2 3 5 6 9
    1 2
    2 3
    3 4
    4 5
    5 6
    6 7
    7 8
    7 9

Similar decompositions also from fi, ppfi and bmd (all with tw 5, if tw is the size of a biggest bag minus 1).

I can't say much about the cython sage integration, and obviously the results may depend on vertex order and such things. Do you actually get a suboptimal decomposition? Which one?

**Comment by dcoudert** [comment]
The graph has 10 vertices and 33 edges
```
p tw 10 33
1 2
1 3
1 4
1 5
1 6
1 7
1 8
1 10
2 3
2 4
2 5
2 6
2 7
2 8
2 9
2 10
3 4
3 5
3 6
3 8
3 9
4 5
4 6
4 7
5 6
5 7
5 8
5 9
5 10
6 9
6 10
7 10
8 9
```
and we get the decomposition:
```
s td 4 7 10
b 1 1 2 5 6 7 10
b 2 1 2 3 4 5 6 7
b 3 1 2 3 5 6 8
b 4 2 3 5 6 8 9
1 2
2 3
3 4
```
We clearly have to use a newer version of tdlib. We currently call a former function `sage_exact_decomposition` from version `0.3.1.p0`. We will have to figure out how to use the current interfaces.

**Comment by felix-salfelder** [comment]
On Thu, Jun 06, 2024 at 11:33:16PM -0700, David Coudert wrote:
> The graph has 10 vertices and 33 edges

Thanks, interesting. I used a tool "showg" to decode the string. Then
hand edited the output... It had to go wrong.

The current algorithms also work on the 33 edge graph, but I havent
tried the dated exact decomposition (cutset I suppose), as it's not
enabled in tdecomp.

> We clearly have to use a newer version of tdlib. We currently call a
> former function `sage_exact_decomposition` from version `0.3.1.p0`. We
> will have to figure out how to use the current interfaces.

The new python bindings need work. Perhaps it should be split out, and
become more "pythonic", with a dependency on libtreedec provided by the
main package. Time will tell, suggestions welcome.

**Comment by dimpase** [comment]
> On Thu, Jun 06, 2024 at 11:33:16PM -0700, David Coudert wrote:
> > The graph has 10 vertices and 33 edges
> 
> Thanks, interesting. I used a tool "showg" to decode the string. Then
> hand edited the output... It had to go wrong.
> 
> The current algorithms also work on the 33 edge graph, but I havent
> tried the dated exact decomposition (cutset I suppose), as it's not
> enabled in tdecomp.
> 
> > We clearly have to use a newer version of tdlib. We currently call a
> > former function `sage_exact_decomposition` from version `0.3.1.p0`. We
> > will have to figure out how to use the current interfaces.
> 
> The new python bindings need work. Perhaps it should be split out, and
> become more "pythonic", with a dependency on libtreedec provided by the
> main package. Time will tell, suggestions welcome.
> 

The best would be to have a Python package on PyPI, dependent on libtreedec. Then it would become the only point of entry to tdlib in Sage, simplifying things.

**Comment by felix-salfelder** [comment]
On Fri, Jun 07, 2024 at 05:09:40AM -0700, Dima Pasechnik wrote:
> The best would be to have a Python package on PyPI, dependent on
> libtreedec. Then it would become the only point of entry to tdlib in
> Sage, simplifying things.

If I understand correctly, we should eventually build a shared library.
A starting point could be the various treedec/_*.cpp minus the
BOOST_PYTHON_MODULE wrapper code.

Apparently, these steps are needed.

- copy treedec to lib
- remove all references to python in lib/*
- adjust rules in lib/*, link it all into libtreedec.so
- do the opposite in treedec/*, link with -ltreedec
- (examples/treedec: also use libtreedec)
- .. whatever else to meet PyPI needs.

All we need is a volunteer, but count me in as a reviewer.

**Comment by mkoeppe** [comment]
> We clearly have to use a newer version of tdlib.

- #38163

**Comment by dimpase** [comment]
> On Fri, Jun 07, 2024 at 05:09:40AM -0700, Dima Pasechnik wrote: The best would be to have a Python package on PyPI, dependent on libtreedec. Then it would become the only point of entry to tdlib in Sage, simplifying things.
> If I understand correctly, we should eventually build a shared library. 
> [...]

The question is whether to use Cython, or instead use Boost/Python or pybind11.  The latter is a Sage package, and is used in scipy, contourpy, etc. It's said to be lighter and easier that Boost/Python.

**Comment by dimpase** [comment]
> The question is whether to use Cython, or instead use Boost/Python or pybind11.

one can also can take Cython/C++ code in Sage and modify it appropriately.

**Comment by dimpase** [comment]
> @dcoudert ##38163 should have a test showing that the error here is tested. Can you please communicate this,



> @dcoudert ##38163 should have a test showing that the error here is tested. Can you please communicate this,

it's actually does not fix the issue here, according to my testing.

**Comment by dcoudert** [comment]
> > @dcoudert ##38163 should have a test showing that the error here is tested. Can you please communicate this,
> 
> it's actually does not fix the issue here, according to my testing.

Have you tried running `make sagemath_tdlib` ? it's working for me on macOS and fedora 39...

In fact, I'm missing a proper documentation on how to install each of our optional packages. I have the filling that we have many ways and that we should sometimes favor one of them, but not always the sage depending on the package...

**Comment by dimpase** [comment]
`make sagemath_tdlib` is not working for me. I get a rather obscure error:
```
...
[tdlib-0.9.3.p0] Finished installing tdlib-0.9.3.p0
make --no-print-directory sagemath_environment-SAGE_VENV-no-deps
[sagemath_environment-10.4.beta8] Setting up build directory /mnt/opt/Sage/sage-clang/local/var/lib/sage/venv-python3.11/var/tmp/sage/build/sagemath_environment-10.4.beta8
[sagemath_environment-10.4.beta8] Host system: Linux hilbert 6.0.8-gentoo-x86_64 #2 SMP PREEMPT_DYNAMIC Sun Dec 18 22:31:12 GMT 2022 x86_64 Intel(R) Core(TM) i7-6600U CPU @ 2.60GHz GenuineIntel GNU/Linux
[sagemath_environment-10.4.beta8] C compiler: gcc, Using built-in specs., COLLECT_GCC=gcc, COLLECT_LTO_WRAPPER=/usr/libexec/gcc/x86_64-pc-linux-gnu/13/lto-wrapper, Target: x86_64-pc-linux-gnu, Configured with: /var/tmp/portage/sys-devel/gcc-13.2.1_p20240210/work/gcc-13-20240210/configure --host=x86_64-pc-linux-gnu --build=x86_64-pc-linux-gnu --prefix=/usr --bindir=/usr/x86_64-pc-linux-gnu/gcc-bin/13 --includedir=/usr/lib/gcc/x86_64-pc-linux-gnu/13/include --datadir=/usr/share/gcc-data/x86_64-pc-linux-gnu/13 --mandir=/usr/share/gcc-data/x86_64-pc-linux-gnu/13/man --infodir=/usr/share/gcc-data/x86_64-pc-linux-gnu/13/info --with-gxx-include-dir=/usr/lib/gcc/x86_64-pc-linux-gnu/13/include/g++-v13 --disable-silent-rules --disable-dependency-tracking --with-python-dir=/share/gcc-data/x86_64-pc-linux-gnu/13/python --enable-languages=c,c++,fortran --enable-obsolete --enable-secureplt --disable-werror --with-system-zlib --enable-nls --without-included-gettext --disable-libunwind-exceptions --enable-checking=release --with-bugurl=https://bugs.gentoo.org/ --with-pkgversion='Gentoo 13.2.1_p20240210 p14' --with-gcc-major-version-only --enable-libstdcxx-time --enable-lto --disable-libstdcxx-pch --enable-shared --enable-threads=posix --enable-__cxa_atexit --enable-clocale=gnu --disable-multilib --with-multilib-list=m64 --disable-fixed-point --enable-targets=all --enable-libgomp --disable-libssp --disable-libada --disable-cet --disable-systemtap --disable-valgrind-annotations --disable-vtable-verify --disable-libvtv --without-zstd --without-isl --enable-default-pie --enable-default-ssp --disable-fixincludes --with-build-config=bootstrap-O3, Thread model: posix, Supported LTO compression algorithms: zlib, gcc version 13.2.1 20240210 (Gentoo 13.2.1_p20240210 p14)
[sagemath_environment-10.4.beta8] No stamp file for package 'sagemath_environment' in /mnt/opt/Sage/sage-clang/local/var/lib/sage/venv-python3.11/var/lib/sage/installed
[sagemath_environment-10.4.beta8] No spkg-legacy-uninstall script; nothing to do
[sagemath_environment-10.4.beta8] [spkg-install] * Creating isolated environment: venv+pip...
[sagemath_environment-10.4.beta8] [spkg-install] * Installing packages in isolated environment:
[sagemath_environment-10.4.beta8] [spkg-install]   - setuptools >= 68.1.1
[sagemath_environment-10.4.beta8] [spkg-install]   - wheel >=0.36.2
[sagemath_environment-10.4.beta8] [spkg-install] > /mnt/opt/Sage/sage-clang/local/var/lib/sage/venv-python3.11/bin/python3 -m
[sagemath_environment-10.4.beta8] [spkg-install]   pip --python /tmp/build-env-_ris87b1/bin/python install --use-pep517 --no-
[sagemath_environment-10.4.beta8] [spkg-install]   warn-script-location --no-compile -r /tmp/build-reqs-_yylu9p_.txt
[sagemath_environment-10.4.beta8] [spkg-install] < Looking in links: file:///mnt/opt/Sage/sage-clang/local/var/lib/sage/venv-
[sagemath_environment-10.4.beta8] [spkg-install]   python3.11/var/lib/sage/wheels
[sagemath_environment-10.4.beta8] [spkg-install] < ERROR: Could not find a version that satisfies the requirement wheel>=0.36.2
[sagemath_environment-10.4.beta8] [spkg-install]   (from versions: none)
[sagemath_environment-10.4.beta8] [spkg-install] < ERROR: No matching distribution found for wheel>=0.36.2
[sagemath_environment-10.4.beta8] [spkg-install] 
[sagemath_environment-10.4.beta8] [spkg-install] Traceback (most recent call last):
[sagemath_environment-10.4.beta8] [spkg-install]   File "/usr/lib/python3.11/site-packages/build/__main__.py", line 178, in _handle_build_error
[sagemath_environment-10.4.beta8] [spkg-install]     yield
[sagemath_environment-10.4.beta8] [spkg-install]   File "/usr/lib/python3.11/site-packages/build/__main__.py", line 429, in main
[sagemath_environment-10.4.beta8] [spkg-install]     built = build_call(
[sagemath_environment-10.4.beta8] [spkg-install]             ^^^^^^^^^^^
[sagemath_environment-10.4.beta8] [spkg-install]   File "/usr/lib/python3.11/site-packages/build/__main__.py", line 268, in build_package_via_sdist
[sagemath_environment-10.4.beta8] [spkg-install]     sdist = _build(isolation, srcdir, outdir, 'sdist', config_settings, skip_dependency_check, installer)
[sagemath_environment-10.4.beta8] [spkg-install]             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[sagemath_environment-10.4.beta8] [spkg-install]   File "/usr/lib/python3.11/site-packages/build/__main__.py", line 170, in _build
[sagemath_environment-10.4.beta8] [spkg-install]     return _build_in_isolated_env(srcdir, outdir, distribution, config_settings, installer)
[sagemath_environment-10.4.beta8] [spkg-install]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[sagemath_environment-10.4.beta8] [spkg-install]   File "/usr/lib/python3.11/site-packages/build/__main__.py", line 135, in _build_in_isolated_env
[sagemath_environment-10.4.beta8] [spkg-install]     env.install(builder.build_system_requires)
[sagemath_environment-10.4.beta8] [spkg-install]   File "/usr/lib/python3.11/site-packages/build/env.py", line 136, in install
[sagemath_environment-10.4.beta8] [spkg-install]     self._env_backend.install_requirements(requirements)
[sagemath_environment-10.4.beta8] [spkg-install]   File "/usr/lib/python3.11/site-packages/build/env.py", line 265, in install_requirements
[sagemath_environment-10.4.beta8] [spkg-install]     run_subprocess(cmd)
[sagemath_environment-10.4.beta8] [spkg-install]   File "/usr/lib/python3.11/site-packages/build/_ctx.py", line 71, in run_subprocess
[sagemath_environment-10.4.beta8] [spkg-install]     subprocess.run(cmd, capture_output=True, check=True, env=env)
[sagemath_environment-10.4.beta8] [spkg-install]   File "/usr/lib/python3.11/subprocess.py", line 571, in run
[sagemath_environment-10.4.beta8] [spkg-install]     raise CalledProcessError(retcode, process.args,
[sagemath_environment-10.4.beta8] [spkg-install] subprocess.CalledProcessError: Command '['/mnt/opt/Sage/sage-clang/local/var/lib/sage/venv-python3.11/bin/python3', '-m', 'pip', '--python', '/tmp/build-env-_ris87b1/bin/python', 'install', '--use-pep517', '--no-warn-script-location', '--no-compile', '-r', '/tmp/build-reqs-_yylu9p_.txt']' returned non-zero exit status 1.
[sagemath_environment-10.4.beta8] [spkg-install] 
[sagemath_environment-10.4.beta8] [spkg-install] ERROR Command '['/mnt/opt/Sage/sage-clang/local/var/lib/sage/venv-python3.11/bin/python3', '-m', 'pip', '--python', '/tmp/build-env-_ris87b1/bin/python', 'install', '--use-pep517', '--no-warn-script-location', '--no-compile', '-r', '/tmp/build-reqs-_yylu9p_.txt']' returned non-zero exit status 1.
[sagemath_environment-10.4.beta8] [spkg-install] ***************************************************************************************************************************************************************************************************
[sagemath_environment-10.4.beta8] [spkg-install] Failure building sdist and wheel
[sagemath_environment-10.4.beta8] [spkg-install] ***************************************************************************************************************************************************************************************************
[sagemath_environment-10.4.beta8] ************************************************************************
[sagemath_environment-10.4.beta8] Error installing package sagemath_environment-10.4.beta8
[sagemath_environment-10.4.beta8] ************************************************************************
[sagemath_environment-10.4.beta8] Please email sage-devel (http://groups.google.com/group/sage-devel)
[sagemath_environment-10.4.beta8] explaining the problem and including the log files
[sagemath_environment-10.4.beta8]   /mnt/opt/Sage/sage-clang/logs/pkgs/sagemath_environment-10.4.beta8.log
[sagemath_environment-10.4.beta8] and
[sagemath_environment-10.4.beta8]   /mnt/opt/Sage/sage-clang/config.log
[sagemath_environment-10.4.beta8] Describe your computer, operating system, etc.
[sagemath_environment-10.4.beta8] If you want to try to fix the problem yourself, *don't* just cd to
[sagemath_environment-10.4.beta8] /mnt/opt/Sage/sage-clang/local/var/lib/sage/venv-python3.11/var/tmp/sage/build/sagemath_environment-10.4.beta8 and type 'make' or whatever is appropriate.
[sagemath_environment-10.4.beta8] Instead, the following commands setup all environment variables
[sagemath_environment-10.4.beta8] correctly and load a subshell for you to debug the error:
[sagemath_environment-10.4.beta8]   (cd '/mnt/opt/Sage/sage-clang/local/var/lib/sage/venv-python3.11/var/tmp/sage/build/sagemath_environment-10.4.beta8' && '/mnt/opt/Sage/sage-clang/sage' --buildsh)
[sagemath_environment-10.4.beta8] When you are done debugging, you can type "exit" to leave the subshell.
[sagemath_environment-10.4.beta8] ************************************************************************
make[4]: *** [Makefile:3611: sagemath_environment-SAGE_VENV-no-deps] Error 1
make[3]: *** [Makefile:3611: /mnt/opt/Sage/sage-clang/local/var/lib/sage/venv-python3.11/var/lib/sage/installed/sagemath_environment-10.4.beta8] Error 2
make[2]: *** [Makefile:3067: all-build] Error 2
make[2]: Leaving directory '/mnt/opt/Sage/sage-clang/build/make'
***************************************************************
Error building Sage.
```
Also, a clean install
```
./configure --enable-system-site-packages --enable-sagemath_tdlib && make build
```
errors out with the same error.
This probably means that `sagemath_environment` has broken `--enable-system-site-packages`.
@orlitzky

**Comment by dimpase** [comment]
One way or the other, https://github.com/sagemath/sage/pull/38163https://github.com/sagemath/sage/pull/38163 should add the test from the example here.

**Comment by dcoudert** [comment]
I agree (https://github.com/sagemath/sage/pull/38163#issuecomment-2158616196)

**Comment by mkoeppe** [comment]
Just open a PR for that please.
