### ISSUE TITLE
`bell_polynomial(n,n)` should be multivariate polynomial in `x0`, not `x`

### ISSUE THREAD

**Issue by maxale** [sagemath/sage#38186]
### Steps To Reproduce

Let's compute the complete Bell polynomial via:
```
sum(bell_polynomial(5,k) for k in (0..5))
```

### Expected Behavior

`bell_polynomial(5,k)` for different `k` should have compatible parents and their summation should be done without an issue. In particular, `bell_polynomial(5,5)` should be multivariate polynomial in a single variable `x0`.

### Actual Behavior

In reality, we have

```
sage: bell_polynomial(5,5).parent()
Multivariate Polynomial Ring in x over Integer Ring

sage: sum(bell_polynomial(5,k) for k in (0..5))
[...]
TypeError: unsupported operand parent(s) for +: 'Multivariate Polynomial Ring in x0, x1, x2, x3, x4 over Integer Ring' and 'Multivariate Polynomial Ring in x over Integer Ring'
```

### Environment

```markdown
- **OS**: Ubuntu 22.04.4 LTS
- **Sage Version**: 10.3
```

### Checklist

- [X] I have searched the existing issues for a bug report that matches the one I want to file, without success.
- [X] I have read the documentation and troubleshoot guide

**Comment by grhkm21** [comment]
Works fine for me on 10.4b9:
```sage
sage: sum(bell_polynomial(5, k) for k in (0..5))
x0^5 + 10*x0^3*x1 + 15*x0*x1^2 + 10*x0^2*x2 + 10*x1*x2 + 5*x0*x3 + x4
```
Have you updated?

**Comment by grhkm21** [comment]
It was fixed in [this commit](https://github.com/sagemath/sage/commit/15aeb9a4db2eedecf7c3205e296ac90d63c94e87#diff-b8b21f960c3c1ba7d9d036ac2df642c9d624d9b53b7c0b367f907c1a744ae6a5R3091-R3094) in 3rd April 2024.
