### ISSUE TITLE
a PR claiming a fix must validate it

### ISSUE THREAD

**Issue by dimpase** [sagemath/sage#38192]
~~#38163 claims to fix #38159, but does not provide a test showing this.~~

~~Thus, if #38163 is closed, it will trigger closing #38159. Thus the claim should be removed, or a~~ followup PR or issue opened.

**Comment by dimpase** [comment]
Another problem with https://github.com/sagemath/sage/pull/38163 is that it has made an optional package tdlib dependent upon an experimental package sagemath_environment. This is not how it is supposed to work, an optional package can only depend on optional and standard packages. @dcoudert - please retract your positive review.

@vbraun -  please refrain from merging https://github.com/sagemath/sage/pull/38163 in its present form.

**Comment by dimpase** [comment]
And the blocker #38190 also points at #38163 being responsible for breaking the build in some cases.

**Comment by saraedum** [comment]
> Another problem with #38163 is that it has made an optional package tdlib dependent upon an experimental package sagemath_environment. This is not how it is supposed to work, an optional package can only depend on optional and standard packages.

Could you explain where that dependency is? It's not in `dependencies` at least.

**Comment by dimpase** [comment]
with #38163,  it is in the build dependencies:

```
cat build/pkgs/sagemath_tdlib/dependencies
tdlib cysignals boost_cropped | $(PYTHON_TOOLCHAIN) sage_setup sagemath_environment cython pkgconfig $(PYTHON)
```

**Comment by saraedum** [comment]
I don't see that in the changeset of the PR. What am I doing wrong?

**Comment by dimpase** [comment]
This can be closed as soon as there is a test certifying that https://github.com/sagemath/sage/issues/38159 got fixed.

**Comment by dimpase** [comment]
@S17A05 : 
> https://github.com/sagemath/sage/pull/38163 claims to fix https://github.com/sagemath/sage/issues/38159, but does not provide a test showing this.

> Thus, if https://github.com/sagemath/sage/pull/38163 is closed, it will trigger closing https://github.com/sagemath/sage/issues/38159. Thus the claim should be removed, **or a followup PR or issue opened.**

Is there a followup?

**Comment by S17A05** [comment]
> @S17A05 :
> 
> > #38163 claims to fix #38159, but does not provide a test showing this.
> 
> > Thus, if #38163 is closed, it will trigger closing #38159. Thus the claim should be removed, **or a followup PR or issue opened.**
> 
> Is there a followup?

Not that I know of; however, the claim was removed - is that not what you were asking for (alternatively to a followup)? After all, issue #38159 will stay open independently.

**Comment by dimpase** [comment]
closing in favour of #38159

**Comment by dimpase** [comment]
@S17A05 - sorry for not realising that #38159 is perfectly good to track this  further. mea culpa.
