### ISSUE TITLE
Fix broken docker/Dockerfile again

### ISSUE THREAD

**Issue by soehms** [sagemath/sage#38253]
It seems that the fix of #38049 didn't work as expected see [this run for beta7](https://github.com/sagemath/sage/actions/runs/9234698759/job/25411312307#step:8:15396) and [this one for beta8](https://github.com/sagemath/sage/actions/runs/9333677050/job/25693858666#step:8:15441), explicitly in the first case:

```
#16 64.41 [sagemath_doc_html-none] [spkg-install] sage -advanced > en/reference/repl/options.txt
#16 64.41 [sagemath_doc_html-none] [spkg-install] Traceback (most recent call last):
#16 64.41 [sagemath_doc_html-none] [spkg-install]   File "<frozen runpy>", line 198, in _run_module_as_main
#16 64.41 [sagemath_doc_html-none] [spkg-install]   File "<frozen runpy>", line 88, in _run_code
#16 64.41 [sagemath_doc_html-none] [spkg-install]   File "/home/sage/sage/local/var/lib/sage/venv-python3.11.8/lib/python3.11/site-packages/sage_docbuild/__main__.py", line 66, in <module>
#16 64.41 [sagemath_doc_html-none] [spkg-install]     from sage.env import SAGE_DOC_SRC
#16 64.41 [sagemath_doc_html-none] [spkg-install] ModuleNotFoundError: No module named 'sage'
#16 64.41 [sagemath_doc_html-none] [spkg-install] Error: 'sage --docbuild --all-documents' failed
#16 64.41 [sagemath_doc_html-none] [spkg-install] make[5]: *** [Makefile:41: doc-inventory-reference] Error 1
```

In the [run for beta4](https://github.com/sagemath/sage/actions/runs/8860984377/job/24333924316#step:8:5751) the module still was found.

@mkoeppe, do you have any idea what is missing?

_Originally posted by @soehms in https://github.com/sagemath/sage/issues/38049#issuecomment-2150516269_
            
This will be fixed as soon as #38304 is merged (see https://github.com/sagemath/sage/issues/38253#issuecomment-2203791462),

**Comment by soehms** [comment]
@saraedum can you help with this, too?

**Comment by mkoeppe** [comment]
@soehms Not an answer to your question, but would you mind signing up for the https://groups.google.com/g/sagemath-admins mailing list? Trying to streamline communication involving all who maintain [infrastructure](https://github.com/sagemath/sage/wiki/Infrastructure)

**Comment by soehms** [comment]
> @soehms Not an answer to your question, but would you mind signing up for the https://groups.google.com/g/sagemath-admins mailing list? Trying to streamline communication involving all who maintain [infrastructure](https://github.com/sagemath/sage/wiki/Infrastructure)

What do I have to do for this? At the moment the link is hidden for me.

**Comment by mkoeppe** [comment]
I can add you if you tell me what email address to use

**Comment by soehms** [comment]
> I can add you if you tell me what email address to use

I sent it via Zulip!

**Comment by mkoeppe** [comment]
@soehms Likely this is fixed by 
- #38304

**Comment by soehms** [comment]
> Likely this is fixed by

> Thanks! I'll have a look at it!

**Comment by mkoeppe** [comment]
Thanks for testing! I'll remember that the Docker build is a good test for the `--disable-editable` configuration, which is not tested by any other GH Actions workflow.

**Comment by soehms** [comment]
> Thanks for testing! I'll remember that the Docker build is a good test for the `--disable-editable` configuration, which is not tested by any other GH Actions workflow.

BTW: Since the error showed in `sagemath_doc_html` I wondered if it is really necessary to have docbuild in these Docker images. Is there a way to skip this? What is the configure option `--disable-doc` supposed to do?

**Comment by mkoeppe** [comment]
The Dockerfile already seems to do this when it invokes `make build` (which builds everything except the doc), but then in the following stage it builds the doc

**Comment by soehms** [comment]
> The Dockerfile already seems to do this when it invokes `make build` (which builds everything except the doc), but then in the following stage it builds the doc

Yes, but since the error occurred in the second stage, my question was about the `make` call in that stage. It might help to reduce the size of the `sagemath/sagemath` images, right?
