### ISSUE TITLE
Conda bugs introduced by package update in https://github.com/sagemath/sage/pull/37998

### ISSUE THREAD

**Issue by tobiasdiez** [sagemath/sage#38265]
@vbraun To clarify why I've set it to needs-work and would like to ask you to remove it again from the merge queue.

The PR https://github.com/sagemath/sage/pull/37998 claims to fix the ARM build of macos but the package updates (commit https://github.com/sagemath/sage/pull/37998/commits/f0e064bdcf8af7b4bc9e568ff553cd51004fdd92) introduce test failures:
- Test run before this commit: https://github.com/sagemath/sage/actions/runs/9525058035/job/26258729278
- Test run after this commit: https://github.com/sagemath/sage/actions/runs/9525536510/job/26259809272

Same errors can also be found in https://github.com/sagemath/sage/pull/37998#issuecomment-2169133377

So instead of fixing the ARM build on our CI, it now *introduces* test failures for everyone using conda on macos ARM. 

I'm fine with merging the PR (after the recent revisions) without the problematic package update commit.

---

@sagemath/conduct I've set the PR again to needs work due to these test failures. I'm not sure how to correctly handle the situation given that the release manager of course has the right to overwrite "disputed" labels but at the same time test failures (on certain systems) are usually accepted reasons to not merge a given PR. It would be nice if you could find a solution to this strange state of affairs where I cannot explain state changes on the PR itself (which would have prevented @vbraun from merging it based on an outdated review of mine).

**Comment by mkoeppe** [comment]
Outdated.
