### ISSUE TITLE
Implementing generators for some small graphs/ digraphs

### ISSUE THREAD

**Issue by janmenjayap** [sagemath/sage#38320]
### Problem Description

Currently, there are no existing implementation of the generators for the following graphs/ digraphs:
- Bicorn graph
- Tricorn graph
- Murty graph
- KohTindell digraph
- Cubeplex graph
- Twinplex graph

### Proposed Solution

We shall follow the generators for the graphs as explained below. 

1. The definitions/ generators go as follows:

- **Bicorn graph and Tricorn graph**<sup>2</sup>

![bicorn-tricorn](https://github.com/sagemath/sage/assets/83154020/7cbf1d17-63dd-4860-b4a5-8899cebc9c72)

- **Murty graph**<sup>1<sup>

![Murty-graph](https://github.com/sagemath/sage/assets/83154020/3180c0de-8f02-4339-afbc-840f9c6ca8bd)

- **KohTindell digraph**<sup>2</sup>

![KohTindellDiGraph](https://github.com/sagemath/sage/assets/83154020/0a35d34f-c7ec-4698-bab0-1cf9add4561d)

- **Cubeplex graph and Twinplex graph**<sup>3</sup>

![Cubeplex-Twinplex](https://github.com/sagemath/sage/assets/83154020/ba35f175-7893-459d-be16-78014b0344cf)

### Alternatives Considered

Their might be different embeddings possible for each individual graph/ digraph mentioned.

### Additional Information

This implementation is a part of the project: [link](https://summerofcode.withgoogle.com/programs/2024/projects/iY5gx4Ls).

cc: @dcoudert.

### Is there an existing issue for this?

- [X] I have searched the existing issues for a bug report that matches the one I want to file, without success.

---
### References
1. Marcelo H. de Carvalho, Nishad Kothari, Xiumei Wang and Yixun Linc. *Birkhoff–von Neumann graphs that are PM-compact*. 2019. arXiv: [abs/1807.07339](https://arxiv.org/abs/1807.07339).
2. C.L. Lucchesi, U.S.R. Murty. *Perfect Matchings: A Theory of Matching Covered Graphs*. Algorithms and Computation in Mathematics. Springer Cham, 1st edition, 2024. doi: [10.1007/978-3-031-47504-7](https://doi.org/10.1007/978-3-031-47504-7).
3. Serguei Norine and Robin Thomas. *Minimally Non-Pfaffian Graphs*. Combinatorica, vol. 27, no. 5, pages: 587 -- 600, Springer. 2007. doi: [10.1016/j.jctb.2007.12.005](https://doi.org/10.1016/j.jctb.2007.12.005).

**Comment by dcoudert** [comment]
Have you checked that these graphs are not already available under a different name ?
For instance, the Koh-Tindell digraph is `digraphs,Circulant(7, [1, 5])`.

**Comment by janmenjayap** [comment]
The Bicorn graph is `graphs.StaircaseGraph(4)`. Up to my knowledge, there is no implementation of the other four graphs.

These are like specific graphs. For example, `graphs.WagnerGraph()` is essentially `graphs.MoebiusLadderGraph(4)` or `graphs.CirculantGraph(8, [1, 4])`, but since it is a named graph, I suppose it demands a separate implementation.

Actually, I meant the named implementation. Sorry for the confusion.

**Comment by dcoudert** [comment]
For some graphs, for instance for the Koh-Tindell digraph, it might be enough to add the documentation of circulant digraph that when parameters are `(7, [1, 5])`, the digraph is also known as the Koh-Tindell digraph ?

I'm not against adding named (di)graphs but we can avoid adding lot's of code for graph that can be obtained from a family.

**Comment by janmenjayap** [comment]
Sure. Will do that. 😊👍
