### ISSUE TITLE
Documentation error in ncsf ?

### ISSUE THREAD

**Issue by 0-andy-0** [sagemath/sage#38370]
### Steps To Reproduce

open https://doc.sagemath.org/html/en/reference/combinat/sage/combinat/ncsf_qsym/ncsf.html

### Expected Behavior

Maybe should say:  Over QQ (or any other Q-algebra), this Hopf algebra Psi is isomorphic to the universal enveloping algebra of its space of primitive elements.  The primitives form a countably generated free Lie algebra, so Psi is the tensor algebra on a countably infinity dimension vector space.

### Actual Behavior

Says:  Over QQ (or any other Q-algebra), this Hopf algebra Psi is isomorphic to the tensor algebra of its space of primitive elements.

### Environment

```markdown
- **OS**: any
- **Sage Version**: 10.3
```

### Checklist

- [X] I have searched the existing issues for a bug report that matches the one I want to file, without success.
- [X] I have read the documentation and troubleshoot guide

**Comment by fchapoton** [comment]
would you like to fix it yourself ? 
You can do it here : navigate to the file (Code menu on top of the page) and then click on the pencil to edit the file.
