### ISSUE TITLE
HyperellipticCurve_generic doesn't define _latex_

### ISSUE THREAD

**Issue by vincentmacri** [sagemath/sage#38386]
### Steps To Reproduce

Steps:
1. Define and try to print and display a hyperelliptic curve
```python
F.<x> = QQ[]
F = x^2 + x + 1

C = HyperellipticCurve(F)

print(C)
display(C)
```

### Expected Behavior

Both the print and display output the same content, with `display` having better formatting using LaTeX.

### Actual Behavior

`display` is falling back to the default LaTeX representation for generic curves because `_latex_` is not defined for hyperelliptic curves.

In the above example, `print(C)` gives
```
Hyperelliptic Curve over Rational Field defined by y^2 = x^2 + x + 1
```
which is a good way to print out the curve.

However `display(C)` gives (I'm showing the LaTeX code for the output since GitHub doesn't support LaTeX):

```
\text{Projective Plane curve over $\Bold{Q}$ defined by $-x_{0}^{2} + x_{1}^{2} - x_{0} x_{2} - x_{2}^{2}$}
```
which is not as readable as what you get from printing the curve.

### Environment

```markdown
- **OS**: Fedora 40
- **Sage Version**: 10.4rc2, running in a system Jupyter notebook installation
```

### Checklist

- [X] I have searched the existing issues for a bug report that matches the one I want to file, without success.
- [X] I have read the documentation and troubleshoot guide

**Comment by DaveWitteMorris** [comment]
My understanding of the issue is that the output is correct, but could be improved. So this is an enhancement request, not a bug report.
