### ISSUE TITLE
10.4 git fails to build on Fedora 40 with `--enable-system-site-packages`

### ISSUE THREAD

**Issue by QMeqGR** [sagemath/sage#38399]
### Environment

```markdown
- **OS**: Fedora 40
- **Sage Version**: 10.4
 
```

Steps To Reproduce:

Download fresh git repo.
./bootstrap
export SAGE_PROFILE=yes
CFLAGS="-O2 -march=raptorlake" ./configure --no-create --no-recursion --enable-system-site-packages
make

The following packages fail to build.

* package:         fpylll-0.6.0
  last build time: Jul 21 08:51
  log file:        /home/packages/SOURCE/sage/logs/pkgs/fpylll-0.6.0.log

* package:         cypari-2.1.5
  last build time: Jul 21 08:51
  log file:        /home/packages/SOURCE/sage/logs/pkgs/cypari-2.1.5.log

The log file says: [spkg-install] /home/packages/SOURCE/sage/local/var/lib/sage/venv-python3.12/bin/python3: No module named build

But it is installed on my system:

```
[ehm ~]$ python3
Python 3.12.4 (main, Jun  7 2024, 00:00:00) [GCC 14.1.1 20240607 (Red Hat 14.1.1-5)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import build
>>> 
```

So I installed the packages by hand ('pip3 install fpylll cypari') and re-ran the configure script. But 'make' still tries to build them, even though I have set "--enable-system-site-packages" in my configure call.

**Comment by mkoeppe** [comment]
Try with #38358

**Comment by QMeqGR** [comment]
Works. Thank you.
