### ISSUE TITLE
Building gfortran fails on GNU/Linux with Apple silicon

### ISSUE THREAD

**Issue by aikrahguzar** [sagemath/sage#38424]
### Environment

```markdown
- **OS**: Fedora Asahi Remix 40
- **Sage Version**: SageMath version 10.5.beta0, Release Date: 2024-07-24
```

### Steps To Reproduce

I ran on a Macbook air M2 running Fedora Asahi Linux,
```
./configure
make build
```

### Config log

[config.log.txt](https://github.com/user-attachments/files/16377181/config.log.txt)

### Package logs

[gfortran-13.2.0.log.txt](https://github.com/user-attachments/files/16377174/gfortran-13.2.0.log.txt)

### Additional Information

The error seems to be due to the fact that the build process tries to install darwin version of the gfrotran and not the linux version.

I can workaround this by installing gfrotran from fedora repos. However that runs into issue with installing tachyon https://github.com/sagemath/sage/issues/23712#issuecomment-2250137693

[Aside] I have a working installation of sage from nixpkgs. I wonder how they are getting around the tachyon issue.

### Checklist

- [X] I have searched the existing issues for a bug report that matches the one I want to file, without success.
- [X] I have read the documentation and troubleshoot guide

**Comment by dimpase** [comment]
Sage should leave building Fortran to experts.
Can't you use gfortran from the OS distribution?

**Comment by dimpase** [comment]
tachyon issue is a different one. for one, tachyon doesn't use Fortran.

That is, just use gfortran from OS.

**Comment by aikrahguzar** [comment]
> Sage should leave building Fortran to experts. Can't you use gfortran from the OS distribution?

Installing the fedora package works.

**Comment by mkoeppe** [comment]
@aikrahguzar Please try with 
- #38442

**Comment by aikrahguzar** [comment]
> @aikrahguzar Please try with
> 
>     * [`build/pkgs/gcc`: Update to 13.3 #38442](https://github.com/sagemath/sage/pull/38442)

Thanks a lot. I checked out that commit, uninstalled the fedora gfortran and then ran `make build` again. `gfortran` was built successfully and now the build has moved on  to openblas. So the original issue seems fixed.

**Comment by mkoeppe** [comment]
Thanks for testing!
