### ISSUE TITLE
Non integer coercion with Finite Field 

### ISSUE THREAD

**Issue by Shay2Shay** [sagemath/sage#38448]
### Steps To Reproduce

```
sage: M = MatrixSpace(GF(2), nrows=3, ncols=1)
sage: vector1 = vector(QQ, [1.1, 2, 3])
sage: vector2 = vector(QQ, [1.4, 2, 3])
sage:
sage: M(vector1)
... # ZeroDivisionError: inverse of Mod(0, 2) does not exist
sage: 
sage: M(vector2)
[1]
[0]
[1]
```

### Expected Behavior

Should not coerce between `non integral values` and `Finite Fields`

### Actual Behavior

Attempts to coerce integral as well as non-integral rationals - sometime throws `Zero Division Error` and sometimes let it pass
Tested for GF(2^2) and GF(5) which throws same error

### Additional Information

The following behaves as expected
```
sage: base = GF(2)
sage: base(2.2)
... # TypeError: Attempt to coerce non-integral RealNumber to Integer

sage: Q = vector(base, [1.4, 2, 3])
... # TypeError: unable to convert 1.40000000000000 to an element of Finite Field of size 2

sage: Q = vector(base, [1.0, 2.0, 3.0]); Q
(1, 0, 1)

```

### Environment

```markdown
- **OS**: Ubuntu 20.04
- **Sage Version**: 10.4
```

### Checklist

- [X] I have searched the existing issues for a bug report that matches the one I want to file, without success.
- [ ] I have read the documentation and troubleshoot guide

**Comment by fchapoton** [comment]
Calling M on this vector is performing conversion and not coercion. In other words, it tries hard to make the element belong to the demanded ring, even if there is no natural ring morphism.

This fails in the first case because `11/10` has 2 in the denominator. On the other hand, `7/5` has not, so this works.

No bug here.
