### ISSUE TITLE
`is_t_design` method of the class `IncidenceStructure` sometimes returns wrong answer

### ISSUE THREAD

**Issue by buchi1002** [sagemath/sage#38454]
### Steps To Reproduce

All you have to do is to activate SageMath.

### Expected Behavior

```sage
sage: IS = IncidenceStructure(points=[0,1,2,3,4,5], blocks=[[0,1], [1,2], [0,2]])
sage: print(IS.is_t_design(return_parameters=True))
(False, (0,0,0,0))
```
or
```sage
sage: IS = IncidenceStructure(points=[0,1,2,3,4,5], blocks=[[0,1], [1,2], [0,2]])
sage: print(IS.is_t_design(return_parameters=True))
(True, (2, 3, 2, 1))
```

### Actual Behavior

```sage
sage: IS = IncidenceStructure(points=[0,1,2,3,4,5], blocks=[[0,1], [1,2], [0,2]])
sage: print(IS.is_t_design(return_parameters=True))
(True, (1, 6, 2, 1))
```

### Environment

```markdown
- **OS**: Ubuntu 22.04.4 LTS
- **Sage Version**:9.5
```

### Checklist

- [X] I have searched the existing issues for a bug report that matches the one I want to file, without success.
- [x] I have read the documentation and troubleshoot guide

**Comment by DaveWitteMorris** [comment]
Thanks for the bug report.

The code verifies that if a t-subset is covered by some block, then it is covered by lambda blocks, but the code does not verify that all t-subsets are covered.  This should be easy to fix, so I expect to have a PR ready soon.
