### ISSUE TITLE
Multivariate polynomial ring ideal reduce() method does not work on integer

### ISSUE THREAD

**Issue by user202729** [sagemath/sage#38560]
### Steps To Reproduce

```sage
sage: R.<x, y> = QQ[]
sage: R.ideal(x, y).reduce(1)
```

### Expected Behavior

Returns `1`.

### Actual Behavior

`AttributeError: 'sage.rings.integer.Integer' object has no attribute 'reduce'`

### Environment

```markdown
- **OS**: Linux
- **Sage Version**: `'SageMath version 10.4, Release Date: 2024-07-19'`
```

### Checklist

- [X] I have searched the existing issues for a bug report that matches the one I want to file, without success.
- [X] I have read the documentation and troubleshoot guide

**Comment by maxale** [comment]
It's not a bug since `reduce()` here expects a polynomial not a number. Use `R(1)` or `R.one()` instead of `1`.

**Comment by user202729** [comment]
But `1` can be naturally converted to `R(1)`. Besides, it does work with univariate polynomial ring

```sage
sage: R.<x> = QQ[]
sage: R.ideal(x).reduce(1)
1
```

In any case I see no harm converting the argument to an element of `R` inside `.reduce()` if it isn't already one. Would make it more convenient to use.
