### ISSUE TITLE
switch from `genbg` to `genbgL` in the backend of `nauty_genbg()`

### ISSUE THREAD

**Issue by maxale** [sagemath/sage#38618]
### Problem Description

In #29821 hypergraph generation was switched from nauty's `genbg` to `genbgL`.

### Proposed Solution

The current issue requests the same switch in the backend of `graphs.nauty_genbg()` function.

### Alternatives Considered

N/A

### Is there an existing issue for this?

- [X] I have searched the existing issues for a bug report that matches the one I want to file, without success.

**Comment by dcoudert** [comment]
See #38621
