### ISSUE TITLE
Missing degree checks for Jacobian elements

### ISSUE THREAD

**Issue by vincentmacri** [sagemath/sage#38623]
### Steps To Reproduce

```python
K = GF(7)
Kx.<x> = FunctionField(K)
_.<v> = K[]
F.<y> = Kx.extension(v^2 - (x^6 + 3))
O = F.maximal_order()

D3 = O.ideal(x + 3, y + 5).place() + O.ideal (x + 4, y + 5).place() + O.ideal (x + 5, y + 5).place() + O.ideal(x + 6, y + 5).place()
D3_reduced = O.ideal(x+1, y+2).place() + O.ideal(x+2, y+2).place()

J = F.jacobian(model='hess')
D3_jacobian = J(D3)
D3_reduced_jacobian = J(D3_reduced)

print(D3_jacobian == D3_reduced_jacobian)  # True
print(D3_reduced_jacobian == D3_jacobian)  # False
```

### Expected Behavior

The `==` operator should be symmetric. I believe in the example above the comparison result should be `True`.

### Actual Behavior

The `==` operator is not symmetric.

### Additional Information

I believe the relevant code here was added by @kwankyu in #35467.

### Environment

```markdown
- **OS**: Fedora 40
- **Sage Version**: 10.4, compiled with conda
```

### Checklist

- [X] I have searched the existing issues for a bug report that matches the one I want to file, without success.
- [X] I have read the documentation and troubleshoot guide

**Comment by vincentmacri** [comment]
> I believe in the example above the comparison result should be `True`.

Actually upon further testing I think the issue here is that `D3` and `D3_reduced` aren't divisors of degree zero and hence not elements of the Jacobian. The bug might be that no error was raised when they were constructed as Jacobian elements. Since they aren't Jacobian elements, Jacobian operations don't make sense on them.

**Comment by kwankyu** [comment]
Sorry, I missed this Issue. I will look into it soon.

**Comment by kwankyu** [comment]
The genus of F is 2. Hence a point of the Jacobian is internally represented by a positive divisor of degree 2. So your input D for J(D) should be either a divisor of degree zero or a positive divisior of degree 2.
```sage
J = F.jacobian(model='hess')
D3_jacobian = J(D3)  # D3 has degree 4; this should error out
D3_reduced_jacobian = J(D3_reduced) # D3_reduced has degree 2; okay
```
Thus the real bug is  that `J` does not check the degree of its input divisor...

**Comment by kwankyu** [comment]
> The "Jacobian" constructed in
> 
> ```python
> J = F.jacobian(model='hess'); J
> Jacobian of Function field in y defined by y^2 + 6*x^6 + 4 (Hess model)
> ```
> 
> tries to be independent from the model "hess" in creating its points. Hence to create a point of the Jacobian, it should only accept a divisor of degree zero. 

I lifted this restriction in the PR. Now J accepts effective divisors as input. Now
```python
sage: K = GF(7)
....: Kx.<x> = FunctionField(K)
....: _.<v> = K[]
....: F.<y> = Kx.extension(v^2 - (x^6 + 3))
....: O = F.maximal_order()
....: 
....: D3 = O.ideal(x + 3, y + 5).place() + O.ideal (x + 4, y + 5).place() + O.ideal (x + 5, y + 5).place() + O.ideal(x + 6, y + 5).place()
....: D3_reduced = O.ideal(x+1, y+2).place() + O.ideal(x+2, y+2).place()
sage: J = F.jacobian(model='hess')
....: J(D3)
Traceback (most recent call last):
...
ValueError: effective divisor is not of degree 2
sage: J(D3_reduced)
[Place (x + 1, y + 2)
 + Place (x + 2, y + 2)]
```

**Comment by kwankyu** [comment]
The PR needs review.
