### ISSUE TITLE
cannot build pdf doc

### ISSUE THREAD

**Issue by beew** [sagemath/sage#38642]
### Environment

```markdown
- **OS**: Ubuntu 22.04
- **Sage Version**: 10.4
```

### Steps To Reproduce

Tried to build pdf documents with 

```
make doc-pdf

```

and failed, see package log attached.

### Config log

[config.log](https://github.com/user-attachments/files/16928359/config.log)

### Package logs

[sagemath_doc_pdf-none.log](https://github.com/user-attachments/files/16928475/sagemath_doc_pdf-none.log)

### Additional Information

I tried then
```
./sage --docbuild tutorial pdf

```
and it also failed, with log attached below
[sage_build_pdf_error.log](https://github.com/user-attachments/files/16928519/sage_build_pdf_error.log)

### Checklist

- [X] I have searched the existing issues for a bug report that matches the one I want to file, without success.
- [X] I have read the documentation and troubleshoot guide

**Comment by vbraun** [comment]
Seems like your TeX installation misses some required fonts:

reason: File not found: "FreeSerif.otf"
