### ISSUE TITLE
"demand by Tobias Diez on #38227" is for keeping existent practices

### ISSUE THREAD

**Issue by dimpase** [sagemath/sage#38648]
The [demand by Tobias Diez](https://groups.google.com/g/sage-devel/c/sVcJiJdUxRs/m/oEntIDE9AgAJ), to deviate from the long-standing practice of synchronized version constraints, are out of scope of this upgrade PR. Setting to "disputed".

_Originally posted by @mkoeppe in https://github.com/sagemath/sage/issues/38227#issuecomment-2334343469_

**Comment by mkoeppe** [comment]
"synchronized" does not mean "pinned".
