### ISSUE TITLE
`.edge_cut(algorithm='LP')` returns edges without labels

### ISSUE THREAD

**Issue by maxale** [sagemath/sage#38713]
### Steps To Reproduce

```
sage: g = graphs.PetersenGraph()

sage: g.edge_cut(0, 3, vertices=True, use_edge_labels=True)
[3,
 [(0, 1, None), (0, 4, None), (0, 5, None)],
 [[0], [1, 2, 3, 4, 5, 6, 7, 8, 9]]]

sage: g.edge_cut(0, 3, vertices=True, use_edge_labels=True, algorithm="FF")
[3,
 [(0, 1, None), (0, 4, None), (0, 5, None)],
 [[0], [1, 2, 3, 4, 5, 6, 7, 8, 9]]]

sage: g.edge_cut(0, 3, vertices=True, use_edge_labels=True, algorithm="LP")
(3, [(2, 3), (3, 4), (3, 8)], [[0, 1, 2, 4, 5, 6, 7, 8, 9], [3]])
```

### Expected Behavior

`.edge_cut(algorithm='LP')` should return edges with labels, consistently with other algorithms.

### Actual Behavior

Edges are reported as tuples of vertices without labels.

### Additional Information

It breaks other methods that depend on `.edge_cut` such as `.gomory_hu_tree(algorithm="LP")`, which fails with an error:

> ValueError: not enough values to unpack (expected 3, got 2)

as reported at https://ask.sagemath.org/question/79320/

### Environment

- **OS**: Ubuntu 24.04.1 LTS
- **Sage Version**: 10.5.beta3

### Checklist

- [X] I have searched the existing issues for a bug report that matches the one I want to file, without success.
- [X] I have read the documentation and troubleshoot guide

**Comment by dcoudert** [comment]
I pushed a fix in #38725.
