### ISSUE TITLE
bug in vertex_connectivity

### ISSUE THREAD

**Issue by jhpalmieri** [sagemath/sage#38723]
### Steps To Reproduce

See https://ask.sagemath.org/question/79327/graphs-vertex_connectivity-misleading-behavior-for-parameter-k/ for the original report. Run

```
from sage.graphs.connectivity import vertex_connectivity
s3 = graphs.SierpinskiGasketGraph(3)
vertex_connectivity(s3, k=1)  # should be True
vertex_connectivity(s3, k=2)  # should be True
vertex_connectivity(s3, k=3)  # should be False
```

The first of these returns `False` rather than `True`.

### Expected Behavior

`vertex_connectivity(s3, k=1)` should return `True`.

### Actual Behavior

It returns `False`.

### Additional Information

A potential fix, but I am not an expert on the graph theory code or indeed on graph theory:

```diff
diff --git a/src/sage/graphs/connectivity.pyx b/src/sage/graphs/connectivity.pyx
index ba51598009..cbdec12a5c 100644
--- a/src/sage/graphs/connectivity.pyx
+++ b/src/sage/graphs/connectivity.pyx
@@ -1622,9 +1622,10 @@ def vertex_connectivity(G, value_only=True, sets=False, k=None, solver=None, ver
             # We follow the convention of is_connected, is_biconnected and
             # is_strongly_connected
             return k == 1
-        if (g.is_directed() and k > min(min(g.in_degree()), min(g.out_degree()))) \
-           or (not g.is_directed() and (k > min(g.degree()))):
-            return False
+        if g.is_directed():
+            return k <= min(min(g.in_degree()), min(g.out_degree()))
+        if not g.is_directed():
+            return k <= min(g.degree())
         value_only = True
         sets = False

``` 

### Environment

- **OS**: OS X 14.7
- **Sage Version**: 10.5.beta5

### Checklist

- [X] I have searched the existing issues for a bug report that matches the one I want to file, without success.
- [X] I have read the documentation and troubleshoot guide

**Comment by dcoudert** [comment]
I pushed a fix in #38726.
