### ISSUE TITLE
Solve

### ISSUE THREAD

**Issue by Nickzad143** [sagemath/sage#38800]
import sympy as sp

# Define the variables
x, y = sp.symbols('x y')

# Define the quadratic expression in the exponent
expression = -3*x**2 - 2*y**2 + 8*x + 6*y

# Calculate the second partial derivatives
f_xx = sp.diff(expression, x, x)
f_yy = sp.diff(expression, y, y)
f_xy = sp.diff(expression, x, y)

# Calculate the discriminant
discriminant = f_xx * f_yy - f_xy**2

# Print the discriminant
print('The discriminant of the function is:', discriminant)

**Comment by yyyyx4** [comment]
Indeed, this seems to be a `sympy` example. I don't see how it's supposed to communicate an issue with SageMath.
