### ISSUE TITLE
`sqrt(Mod(,))` produces a result from some extended ring when no square roots exist

### ISSUE THREAD

**Issue by maxale** [sagemath/sage#38803]
### Steps To Reproduce

Check this out:
```
sage: is_square(Mod(2, 101010))
False
sage: sqrt(Mod(2, 101010))
sqrt2
sage: _.parent()
Univariate Quotient Polynomial Ring in sqrt2 over Ring of integers modulo 101010 with modulus x^2 + 101008
```

### Expected Behavior

As `is_square()` tells us, `Mod(2, 101010)` is not a square and thus computing `sqrt(Mod(2, 101010))` should raise a `ValueError`.

### Actual Behavior

Instead, it produces a result from some extension ring. Sage should not do so, unless it is explicitly asked to look for a root in a wider ring.

### Additional Information

See #38802 for a related issue with parameter `all=True`.

### Environment

- **OS**: Ubuntu 24.04.1 LTS
- **Sage Version**: 10.5.beta6

### Checklist

- [X] I have searched the existing issues for a bug report that matches the one I want to file, without success.
- [X] I have read the documentation and troubleshoot guide

**Comment by DaveWitteMorris** [comment]
If you want `sqrt` to raise a `ValueError`, you can use the `extend` keyword. 
```
sage: sqrt(Mod(2, 101010), extend=False)
---------------------------------------------------------------------------
ValueError ...
```
The default value of `extend` is `True`, which seems to make sense, because (for example) I think that most users would expect `sqrt(2)` to return the principal square root of two, not raise an error. 

I think this issue should be closed as "won't fix".

**Comment by maxale** [comment]
Hmmm. I believe the default `extend=True` is inconsistent with the (default) expectation of a polynomial roots be from the ring of its coefficients:
```
sage: x = polygen(Zmod(101010))
sage: (x^2 - 2).roots(multiplicities=False)
[]
```
This also computes values for `sqrt(Mod(2,101010))`, but tells that there are none.

**Comment by DaveWitteMorris** [comment]
Different methods with overlapping domains have different points of view, so it's not surprising to me that they have different defaults. I don't see a problem.

**Comment by maxale** [comment]
Ok, then.
