### ISSUE TITLE
Random test failures in `finitely_presented_named`

### ISSUE THREAD

**Issue by tobiasdiez** [sagemath/sage#38889]
### Expected Behavior

Test pass

### Actual Behavior

```
sage -t --warn-long 5.0 --random-seed=130677747974987316498399576088509580425 src/sage/groups/finitely_presented_named.py
**********************************************************************
File "src/sage/groups/finitely_presented_named.py", line 485, in sage.groups.finitely_presented_named.AlternatingPresentation
Failed example:
    A1.is_isomorphic(A2), A1.order()
Expected:
    (True, 1)
Got:
    #I  Forcing finiteness test
    (True, 1)
```

### Environment

Linux: https://github.com/sagemath/sage/actions/runs/11572245422/job/32211815924

### Checklist

- [X] I have searched the existing issues for a bug report that matches the one I want to file, without success.
- [X] I have read the documentation and troubleshoot guide

**Comment by miguelmarco** [comment]
Does it happen consistently or is it random?

**Comment by tobiasdiez** [comment]
Random but pretty often. I only looked at the meson workflow so far, not sure if it is specific to this.

**Comment by user202729** [comment]
Looks like that specific comment comes from GAP.

A previous commit that modifies these things is 36b305ff1501a8f78329c8162f4acb6a5f3aa4ca .

If it's random it may be difficult…
