### ISSUE TITLE
DisjointSet ignores errors

### ISSUE THREAD

**Issue by videlec** [sagemath/sage#38939]
Because `DisjointSet` is a cython class, some care has to be taken with respect to functions that contain python code that could possibly raise an error. For example, the function `union` does contain python code that could possibly raise an error, but the error is not raised
```
sage: d = DisjointSet('abcde')
sage: d.union('a', 'f')
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
KeyError: 'f'
Exception ignored in: 'sage.sets.disjoint_set.DisjointSet_of_hashables.union'
Traceback (most recent call last):
  File "<ipython-input-8-206901714f0d>", line 1, in <module>
KeyError: 'f'
```

**Comment by DaveWitteMorris** [comment]
Please clarify why this is a bug. I think raising an error is correct here (since 'f' is not one of the sets).

**Comment by videlec** [comment]
The bug is that the error is **not** raised. Isn't it explicit enough?

**Comment by DaveWitteMorris** [comment]
OK, I was confused.  (My bad, but github issues usually include both the expected behavior and the actual behavior, and I was confused about both in this case.)  If I understand correctly, currently the code prints a message but does not raise an error, but you (like me) think it should raise an error.

**Comment by videlec** [comment]
Indeed. The code prints that an error has occurred and been ignored. And I think it should raise an error.

**Comment by dcoudert** [comment]
method `union` is currently defined with a  `noexcept`. We can change that to `except *`. I will push a possible fix. Let's hope it will not break too many tests.
