### ISSUE TITLE
PolynomialRing(Zmod(n), 'x') error

### ISSUE THREAD

**Issue by wang2000star** [sagemath/sage#39000]
### Steps To Reproduce

PolynomialRing(Zmod(n), 'x')

### Expected Behavior

Compiles fine

### Actual Behavior

when n>=2**63, 
the error show that
"
/home/sage-10.4/local/var/lib/sage/venv-python3.12.4/lib/python3.12/site-packages/cysignals/signals.cpython-312-x86_64-linux-gnu.so(+0xa294)[0x7f3b5216c294]
/home/sage-10.4/local/var/lib/sage/venv-python3.12.4/lib/python3.12/site-packages/cysignals/signals.cpython-312-x86_64-linux-gnu.so(+0xa356)[0x7f3b5216c356]
/home/sage-10.4/local/var/lib/sage/venv-python3.12.4/lib/python3.12/site-packages/cysignals/signals.cpython-312-x86_64-linux-gnu.so(+0xcc36)[0x7f3b5216ec36]
/lib/x86_64-linux-gnu/libc.so.6(+0x42520)[0x7f3b52672520]
/home/sage-10.4/src/sage/libs/ntl/ntl_ZZ_p.cpython-312-x86_64-linux-gnu.so(_ZN3NTL3remERNS_2ZZERKS0_S3_+0x36)[0x7f3b4aacb1a9]
/home/sage-10.4/src/sage/libs/ntl/ntl_ZZ_p.cpython-312-x86_64-linux-gnu.so(_ZN3NTL4convERNS_4ZZ_pERKNS_2ZZE+0x2f)[0x7f3b4aadaf26]
/home/sage-10.4/src/sage/libs/ntl/ntl_ZZ_p.cpython-312-x86_64-linux-gnu.so(_ZN3NTL4ZZ_pC1ERKNS_15INIT_VAL_STRUCTERKNS_2ZZE+0x38)[0x7f3b4aad9412]
/home/sage-10.4/src/sage/libs/ntl/ntl_ZZ_p.cpython-312-x86_64-linux-gnu.so(+0x5469a)[0x7f3b4aabd69a]
/home/sage-10.4/local/var/lib/sage/venv-python3.12.4/lib/libpython3.12.so.1.0(+0x1cc748)[0x7f3b52a36748]
/home/sage-10.4/src/sage/libs/ntl/ntl_ZZ_pX.cpython-312-x86_64-linux-gnu.so(+0xb097e)[0x7f3b4a6be97e]
/home/sage-10.4/local/var/lib/sage/venv-python3.12.4/lib/libpython3.12.so.1.0(+0x1cc748)[0x7f3b52a36748]
/home/sage-10.4/local/var/lib/sage/venv-python3.12.4/lib/libpython3.12.so.1.0(_PyObject_MakeTpCall+0x94)[0x7f3b529d0d14]
/home/sage-10.4/src/sage/rings/polynomial/polynomial_modn_dense_ntl.cpython-312-x86_64-linux-gnu.so(+0xc3040)[0x7f3af9d02040]
/home/sage-10.4/local/var/lib/sage/venv-python3.12.4/lib/libpython3.12.so.1.0(+0x1c59a1)[0x7f3b52a2f9a1]
/home/sage-10.4/local/var/lib/sage/venv-python3.12.4/lib/libpython3.12.so.1.0(+0x1724d8)[0x7f3b529dc4d8]
/home/sage-10.4/src/sage/rings/polynomial/polynomial_modn_dense_ntl.cpython-312-x86_64-linux-gnu.so(+0xd6c2a)[0x7f3af9d15c2a]
/home/sage-10.4/local/var/lib/sage/venv-python3.12.4/lib/libpython3.12.so.1.0(+0x1cc748)[0x7f3b52a36748]
/home/sage-10.4/local/var/lib/sage/venv-python3.12.4/lib/libpython3.12.so.1.0(_PyObject_MakeTpCall+0x94)[0x7f3b529d0d14]
/home/sage-10.4/local/var/lib/sage/venv-python3.12.4/lib/libpython3.12.so.1.0(_PyEval_EvalFrameDefault+0x4244)[0x7f3b5297a024]
/home/sage-10.4/src/sage/misc/cachefunc.cpython-312-x86_64-linux-gnu.so(+0x1966d)[0x7f3b50fdb66d]
/home/sage-10.4/local/var/lib/sage/venv-python3.12.4/lib/libpython3.12.so.1.0(+0x1b05f0)[0x7f3b52a1a5f0]
/home/sage-10.4/src/sage/misc/cachefunc.cpython-312-x86_64-linux-gnu.so(+0x3d7d4)[0x7f3b50fff7d4]
/home/sage-10.4/src/sage/rings/polynomial/polynomial_element.cpython-312-x86_64-linux-gnu.so(+0x2b8db)[0x7f3b07c4b8db]
/home/sage-10.4/src/sage/rings/polynomial/polynomial_element.cpython-312-x86_64-linux-gnu.so(+0x47f04)[0x7f3b07c67f04]
/home/sage-10.4/local/var/lib/sage/venv-python3.12.4/lib/libpython3.12.so.1.0(+0x1cc748)[0x7f3b52a36748]
/home/sage-10.4/local/var/lib/sage/venv-python3.12.4/lib/libpython3.12.so.1.0(_PyObject_MakeTpCall+0x94)[0x7f3b529d0d14]
/home/sage-10.4/local/var/lib/sage/venv-python3.12.4/lib/libpython3.12.so.1.0(_PyEval_EvalFrameDefault+0x4244)[0x7f3b5297a024]
/home/sage-10.4/src/sage/structure/parent.cpython-312-x86_64-linux-gnu.so(+0x154b4)[0x7f3b50d624b4]
/home/sage-10.4/local/var/lib/sage/venv-python3.12.4/lib/libpython3.12.so.1.0(+0x1724d8)[0x7f3b529dc4d8]
/lib/x86_64-linux-gnu/libc.so.6(+0x29d90)[0x7f3b52659d90]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0x80)[0x7f3b52659e40]
python3(_start+0x25)[0x55ec14e07095]
"

### Environment

- **OS**: Ubuntu 22.04
- **Sage Version**: 10.4

### Checklist

- [X] I have searched the existing issues for a bug report that matches the one I want to file, without success.
- [X] I have read the documentation and troubleshoot guide

**Comment by user202729** [comment]
I can't reproduce. Try upgrading to latest version?

**Comment by DaveWitteMorris** [comment]
I am unable to reproduce this in Sagemath 10.4 (with Python 3.12.4) on Ubuntu 22.04, so I think there is probably something wrong with your installation, rather than a bug in sage itself. Therefore, I think you should try a different forum to get help. Perhaps [ask.sagemath.org](https://ask.sagemath.org/).

**Comment by maxale** [comment]
Possibly similar to #38376
