### ISSUE TITLE
`.all_cycles_iterator()` freezes on digraphs with bidirectional edges

### ISSUE THREAD

**Issue by maxale** [sagemath/sage#39173]
### Steps To Reproduce

Example:
```
list( DiGraph([(1,2),(2,1)]).all_cycles_iterator() )
```

### Expected Behavior

Should work.

### Actual Behavior

Freezes.

### Environment

- **OS**: Ubuntu 24.04.1 LTS
- **Sage Version**: 10.6.beta1

### Checklist

- [X] I have searched the existing issues for a bug report that matches the one I want to file, without success.
- [X] I have read the documentation and troubleshoot guide

**Comment by DaveWitteMorris** [comment]
I think this is user error.  There are infinitely many cycles, so constructing a list of them will take forever.  Instead, you can try something like:
```
sage: list( DiGraph([(1,2),(2,1)]).all_cycles_iterator(max_length=8) )
[[1, 2, 1],
 [1, 2, 1, 2, 1],
 [1, 2, 1, 2, 1, 2, 1],
 [1, 2, 1, 2, 1, 2, 1, 2, 1]]
```
or
```
sage: list( DiGraph([(1,2),(2,1)]).all_cycles_iterator(simple=True) )
[[1, 2, 1]]
```
or you could iterate over all the cycles (e.g., in a `for` loop), but you can't put them all into a list.

**Comment by maxale** [comment]
My bad. I thought of simple cycles.
