### ISSUE TITLE
Paley construction #1 with prime power modulus

### ISSUE THREAD

**Issue by bzliu94** [sagemath/sage#39213]
### Steps To Reproduce

Using Sagemath library with conda and Python 3.10.

1. Open a Python session.
2. Run `from sage.combinat.matrices.hadamard_matrix import hadamard_matrix_paleyI`.
3. Run `s_paley = hadamard_matrix_paleyI(Integer(344), false)`.
4. Run `sum(s[0])` and `sum(s[1])`; see 344 and 0, respectively.

### Expected Behavior

Caring about method `sage.combinat.matrices.hadamard_matrix.hadamard_matrix_paleyI`.

Aiming to make a correct Paley matrix when dealing with q = n - 1 with q a prime power (e.g. 7 ^ 3) and  q = 3 mod 4.

### Actual Behavior

Zeroth row sums to q + 1, which is fine. However, non-zeroth row has wrong distribution of -1 and 1 values, as it sums to 0 = -1 + 1, which would be the case for q a prime but not cube of a prime, necessarily. Specifically, for q = 7 ^ 3, we should see a sum for a non-zeroth row of 40 = -1 + 41, instead.

### Additional Information

I suspect within method definition use of method `is_square()` is either incorrect or we ought to be using a different method; it seems to give us different values than `quadratic_residues()` implies. For example, `len(quadratic_residues(Integer(343)))` gives 151, not 171 s.t. latter is what we'd need for us to have in a Jacobsthal matrix (meaning ignoring a left border when we do not normalize at end) row sums of +1 (after replacing zeroes with one, which we get from adding identity later, in some sense), e.g. when q is p ^ 1 for a prime p.

(One would use `from sage.arith.misc import quadratic_residues` as well.)

References:
- https://en.wikipedia.org/wiki/Paley_construction
- https://doc.sagemath.org/html/en/reference/combinat/sage/combinat/matrices/hadamard_matrix.html

### Environment

- **OS**: Ubuntu 24.04 LTS
- **Sage Version**:  10.4

### Checklist

- [X] I have searched the existing issues for a bug report that matches the one I want to file, without success.
- [X] I have read the documentation and troubleshoot guide

**Comment by DaveWitteMorris** [comment]
I think the method is behaving correctly, so I think we can close this issue as "won't fix".

The rows of a Hadamard matrix are pairwise orthogonal. Since the first row consists entirely of 1's, this implies that the sum of each row (except the first) must be 0.

**Comment by bzliu94** [comment]
Okay, I stand corrected. Turns out working with GF(q) with e.g. q = p ^ 3 and p prime requires that I deal with it differently. Thanks for your feedback.
