### ISSUE TITLE
Clean up partitions_c.cc and partitions_c.h

### ISSUE THREAD

**Issue by craigcitro** [sagemath/sage#4486]
<div id="comment:0"></div>

These files need audited. In particular, `partitions_c.cc` should depend on `partitions_c.h`, and shouldn't duplicate the code there. Someone familiar with C should go ahead and clean these files up.

Component: **misc**

_Issue created by migration from https://trac.sagemath.org/ticket/4486_

**Comment by mezzarobba** [comment]
`partitions_c.cc` no longer exists (#29600)
