### ISSUE TITLE
ideas for improving the SAGE tutorial

### ISSUE THREAD

**Issue by williamstein** [sagemath/sage#482]
<div id="comment:0"></div>

Here are some ideas from a user for improving the SAGE tutorial:

* 2nd para of abstract: point reader to the official python tutorial for syntax issues
* section 5 "programming": mention X? and X?? again
* why doesn't "print?" work?  "attach?"
* why does att[tab] give me attr and not "attach"?
* Why does "time for M in L:" break. 
* Putting cputime(t) alone by itself in the script doesn't print anything.  Why? (Because you have to put "print cputime(t)")
* In many cases using xrange instead of range can be vastly better
* nohup sage file.sage > out&   # very useful
* even better: use screen instead of nohup - you can reconnect to the session later
* How to change a .sage file to a .spyx file:
   1. Profile your file.sage file with %prun -- premature optimization is root of all evil
   2. Start with file.py instead of file.sage.
   3. Use "from sage.all import stuff you need" at the top
   4. Consider cdef'ing classes, cdef'ing methods, and cdef'ing variables.
 

CC:  @sagetrac-mvngu @kcrisman

Component: **documentation**

_Issue created by migration from https://trac.sagemath.org/ticket/482_

**Comment by jhpalmieri** [comment]
I propose that we close this. Tickets can be opened for more targeted changes to the tutorial, rather than the mostly outdated laundry list here.
