### ISSUE TITLE
cohomology of simplicial complexes with finite coefficients as modules over steenrod algebras

### ISSUE THREAD

**Issue by a5044511-c4d7-49ce-acf4-06b1c0aef1de** [sagemath/sage#6103]
<div id="comment:0"></div>

Implement functionality in sage to return the ZZ-graded cohomology with GF(p)-coefficients of an arbitrary simplicial complex as a module over the Steenrod algebra A(p).

This will depend on #6099, #6100, #6101, and #5882. The methodolgy will be similar to that implemented in the ticket #6102.

CC:  @jhpalmieri @antieau

Component: **algebraic topology**

_Issue created by migration from https://trac.sagemath.org/ticket/6103_

**Comment by jhpalmieri** [comment]
Note that #36310 only does that at the prime 2, not in general. Still good enough (IMHO) to close this, if #36310 is merged.
