### ISSUE TITLE
Python/distutils uses C compiler for C++ code

### ISSUE THREAD

**Issue by bac7d3ea-3f1b-4826-8464-f0b53d5e12d2** [sagemath/sage#7028]
<div id="comment:0"></div>

Using

* Solaris 10 update 7 on SPARC
* sage-4.1.2.alpha2
* Sun Studio 12.1
* An updated configure script to allow the Sun compiler to be used, I found that matplotlib-0.99.0 will not build. 

CC was set to the Sun C compler, and CXX to the Sun C++ compiler, What appears to be happening is that matplotlib is taking the CC variable but using that to try to build C++ code.

**Upstream**: https://bugs.python.org/issue1222585

Upstream: **Reported upstream. Developers acknowledge bug.**

Component: **packages: standard**

_Issue created by migration from https://trac.sagemath.org/ticket/7028_

**Comment by mkoeppe** [comment]
Closing this as outdated.
