### ISSUE TITLE
add lpsolve spkg

### ISSUE THREAD

**Issue by jasongrout** [sagemath/sage#8661]
<div id="comment:0"></div>

See http://www.math.unl.edu/~shartke2/files/ for the spkg.

See http://groups.google.com/group/sage-devel/browse_frm/thread/94f30bf9a589d88e/fc9f4e7b63836151 for previous discussion.

CC:  @wdjoyner @sagetrac-hartke @nathanncohen @dimpase

Component: **packages: optional**

_Issue created by migration from https://trac.sagemath.org/ticket/8661_

**Comment by mkoeppe** [comment]
More powerful alternatives are available. We can close this.
